### ISSUE TITLE
proposal: aws_iam_group_membership optionally only ensures membership, does not remove memberships

### ISSUE THREAD

**Issue by danp** [terraform-providers/terraform-provider-aws#10]
### Terraform Version

```
% terraform -v          
Terraform v0.9.8
```

### Affected Resource(s)

* [aws_iam_group_membership](https://www.terraform.io/docs/providers/aws/r/iam_group_membership.html)

### Terraform Configuration Files

```hcl
resource "aws_iam_group_membership" "release_manager_dynamo" {
  provider = "aws.release_manager_iam"
  name     = "release-manager-${var.spaceID}-dynamo-membership"
  group    = "${var.release_manager_iam_group}"
  users    = ["${aws_iam_user.release_manager.name}"]
}
```

### Expected Behavior

Hi, here is where I will propose what I'd like:

In the example snippet above, with just the one user listed, membership for that user would be ensured but any other members of the group would be left alone. This could be achieved with a new `only_present` or similar boolean. This would make the resource behave more like, say, [heroku_app](https://www.terraform.io/docs/providers/heroku/r/app.html) when it manages config vars.

### Actual Behavior

If the group at AWS has users A and B but applying the above config only lists B, A will be removed. If the config above then works out to list A (such as if using a different terraform env), A 
would be re-added and B would be removed.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We are using a trick sort of described [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_delegate-permissions_examples.html#creds-policies-credentials) where using the magic `${aws:username}` variable in policies you can create a user which can manage users named eg `${aws:username}-*` and can only add them to a group named `${aws:username}`. Elsewhere in our terraform config we have an aliased aws provider (`release_manager_iam` in config above) using credentials which have this ability.

**Comment by artburkart** [comment]
I was taking a look at the implementation of this and realized I'm not sure how this works in practice. If I set `only_present` to `true`, does this mean it is no longer possible to remove users from the given membership? I guess so, right? 

For example, if I have this:

```hcl
resource "aws_iam_group_membership" "release_manager_dynamo" {
  provider = "aws.release_manager_iam"
  name     = "release-manager-${var.spaceID}-dynamo-membership"
  group    = "${var.release_manager_iam_group}"
  users    = ["${aws_iam_user.release_manager.name1}", "${aws_iam_user.release_manager.name2}"]
  only_present = true
}
```
Then change it to this:

```hcl
resource "aws_iam_group_membership" "release_manager_dynamo" {
  provider = "aws.release_manager_iam"
  name     = "release-manager-${var.spaceID}-dynamo-membership"
  group    = "${var.release_manager_iam_group}"
  users    = ["${aws_iam_user.release_manager.name1}"]
  only_present = true
}
```

I guess that would be a no op, right?

**Comment by artburkart** [comment]
Also, I think this might be a dup of #113

**Comment by danp** [comment]
Right, yeah, with `only_present = true` `aws_iam_group_membership` would only ever add users to the group, never remove. So this probably is a dup of https://github.com/terraform-providers/terraform-provider-aws/issues/113. Guessing based on numbering (this issue being 10, that being 113) that I searched before the issue migration from hashicorp/terraform was done. We can merge this into 113.

**Comment by bflad** [comment]
For anyone still lurking on this old issue, you can now non-exclusively manage group membership with the new [`aws_iam_user_group_membership` resource](https://www.terraform.io/docs/providers/aws/r/iam_user_group_membership.html) in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading and happy Terraform'ing! 🎉
