### ISSUE TITLE
Add count parameter to routing_config

### ISSUE THREAD

**Issue by Punith13** [terraform-providers/terraform-provider-aws#10000]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The routing_config argument of the aws_lambda_alias needs a count parameter as it is applicable only after 2 versions of lambda are published 

```
resource "aws_lambda_alias" "test_alias" {
  name             = "testalias"
  description      = "a sample description"
  function_name    = "${aws_lambda_function.lambda_function_test.arn}"
  function_version = "1"

  routing_config {
    count                      = "${data.external.lambda_version.result.lambda_version == "0" ? 0 : 1}"  -- required 
    additional_version_weights = "${map("${aws_lambda_function.test.version}", 0.05)}"
  }
}
```

**Comment by grimm26** [comment]
If you upgrade to terraform 0.12.x you should instead be able to do something like:
```
resource "aws_lambda_alias" "test_alias" {
  name             = "testalias"
  description      = "a sample description"
  function_name    = "aws_lambda_function.lambda_function_test.arn
  function_version = "1"

  routing_config = {
    additional_version_weights = data.external.lambda_version.result.lambda_version > 0 ? map(aws_lambda_function.test.version, 0.05) : null
  }
}
```

**Comment by Punith13** [comment]
@grimm26  It works! , thank you.
