### ISSUE TITLE
aws_ssm_maintenance_window_target doesn't process multiple targets{ } correctly

### ISSUE THREAD

**Issue by robmoss2k** [terraform-providers/terraform-provider-aws#10009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

+ Terraform v0.12.8
+ provider.aws v2.26.0

### Affected Resource(s)

* aws_ssm_maintenance_window_target

### Terraform Configuration Files

```hcl
resource "aws_ssm_maintenance_window" "development_maintenance_window" {
  name                       = "DevelopmentWindow"
  schedule                   = "cron(0 0 21 ? 1/1 TUE#2 *)"
  cutoff                     = 1
  duration                   = 3
  allow_unassociated_targets = true
  enabled                    = true
  schedule_timezone          = "Europe/London"
  tags = {
    "Role" = "Development"
  }
}

resource "aws_ssm_maintenance_window_target" "sap_database_development" {
  window_id         = "${aws_ssm_maintenance_window.development_maintenance_window.id}"
  name              = "SAPDatabaseDevelopmentWindowTarget"
  description       = "SAP Database Development Window Target"
  resource_type     = "INSTANCE"
  owner_information = "SAP Database Development Window"
  targets {
    key = "tag:Role"
    values = [
      "Development"
    ]
  }
  targets {
    key = "tag:SAPDatabase"
    values = [
      "ada",
      "db2",
      "db4",
      "db6",
      "hdb",
      "mss",
      "ora",
      "syb"
    ]
  }
}

```

### Debug Output

https://gist.github.com/robmoss2k/7383973e62bbb23230004591b1a66a1d

### Expected Behavior

A maintenance window task should have been registered against the maintenance window based on two tags, as happens with the AWS CLI and the AWS Console.

### Actual Behavior

The following validation error occurred:
Error: ValidationException: Targets must be specified in one of the following formats: 1) 1 target with "Key=InstanceIds" and "Values=" a list of up to 50 instance IDs, or 2) Up to 5 targets, each of which can be either "Key=tag:<key>,Values=<tag_values>" or "Key=tag-key,Values=<tag_keys>", and each with up to 5 unique tag keys/values or3) 1 target with "Key=resource-groups:Name" and "Value=<resource_group_name>", and optionally another target with "Key=resource-groups:ResourceTypeFilters" and "Values=<list>" of up to 5 Resource Type filters.
        status code: 400, request id: 63521dc2-ba60-42bc-95fc-981ccb6eece4

### Steps to Reproduce

1. `terraform apply`

**Comment by ryndaniels** [comment]
Hi @robmoss2k - thanks for opening this issue! I was able to reproduce this error, and I see in the error output the following: `"2) Up to 5 targets, each of which can be either "Key=tag:,Values=<tag_values>" or "Key=tag-key,Values=<tag_keys>", and each with up to 5 unique tag keys/values"` like you noted. It looks like the API has a maximum of 5 values for each key of this type. I was able to get the following configuration block with multiple `target`s and only 5 values to work:

```
resource "aws_ssm_maintenance_window_target" "sap_database_development" {
  window_id         = "${aws_ssm_maintenance_window.development_maintenance_window.id}"
  name              = "SAPDatabaseDevelopmentWindowTarget"
  description       = "SAP Database Development Window Target"
  resource_type     = "INSTANCE"
  owner_information = "SAP Database Development Window"
  targets {
    key = "tag:Role"
    values = [
      "Development"
    ]
  }
  targets {
    key = "tag:SAPDatabase"
    values = [
      "ada",
      "db2",
      "db4",
      "db6",
      "hdb"
    ]
  }
}
```

I know this isn't ideal since it looks like you need to have more than 5 values. Assuming you aren't able to change what you're doing to use only 5, could you tell me if this is a new problem you're seeing (was this config working for you previously)?

**Comment by robmoss2k** [comment]
I can only apologise. I assumed that it was because of the multiple tags, not because of too many tag values on one of the tags, as it was the first time I'd tried using more than one tag, and coincidentally also the first time I'd added so many values for a single tag. While it isn't ideal, the correct place to file this issue is with AWS directly. I will raise a ticket with them, as the arbitrary limit on tag values is pointless.
