### ISSUE TITLE
Cannot set billing_mode for backend locks maintained in dynamodb 

### ISSUE THREAD

**Issue by mukundgandlur** [terraform-providers/terraform-provider-aws#10014]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I am using S3 and DynamoDB to maintain terraform backend state and locks. The table created with the configuration given below always generates a DynamoDB table with billing_mode Provisioned. Need an option to chose a "Pay On Request" billing_mode.

### New or Affected Resource(s)

Dynamodb table that saves the locks

### Potential Terraform Configuration

```hcl
terraform {
  backend "s3" {
    bucket         = "terraform-up-and-running-state"
    key            = "xx/xxxx/terraform.tfstate"
    region         = "xx-xxx-x"
    dynamodb_table = "terraform-up-and-running-locks"
    encrypt        = true
  }
}
```

### References

https://medium.com/@mitesh_shamra/state-management-with-terraform-9f13497e54cf

**Comment by bflad** [comment]
Hi @mukundgandlur 👋 Thank you for submitting this, it would certainly be a welcome and cost-saving enhancement for DynamoDB Tables only being used for Terraform state locking! The catch is that the code for the Terraform S3 Backend which implements the DynamoDB Table locking lives upstream at https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3 and this code does does not actually create the S3 Bucket or DynamoDB Table. Those must be created/managed outside of the Terraform S3 Backend configuration.

To create/manage your Terraform state lock DynamoDB Table with `PAY_PER_REQUEST` billing mode, a Terraform configuration similar to the following can be applied _outside_ of the Terraform configuration declaring `backend "s3"`:

```hcl
resource "aws_dynamodb_table" "example" {
  name           = "terraform-up-and-running-locks"
  billing_mode   = "PAY_PER_REQUEST"
  # ... other configuration ...
}
```

The [Terraform S3 Backend documentation](https://www.terraform.io/docs/backends/types/s3.html) goes into further details about a recommended architecture for multi-account setups, if that is the desired goal.

If you're looking for general assistance beyond the information provided here, [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by the small set of code maintainers. If you have feature requests or documentation suggestions for the Terraform S3 Backend, those will need to be submitted upstream to [hashicorp/terraform](https://github.com/hashicorp/terraform). Hope this helps. 👍
