### ISSUE TITLE
Unable to add inline rules to aws_default_security_group permanently

### ISSUE THREAD

**Issue by NicoleYson** [terraform-providers/terraform-provider-aws#10019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.8
+ provider.archive v1.2.2
+ provider.aws v2.26.0
+ provider.datadog v2.3.0
+ provider.http v1.1.1
+ provider.pagerduty v1.4.0
```

### Affected Resource(s)

* `aws_default_security_group`

### Terraform Configuration Files

```hcl
resource "aws_default_security_group" "default" {
  vpc_id = module.vpc.vpc_id
  egress {
    from_port        = 443
    to_port          = 443
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
    description      = "Allows HTTPS outbound to any IP"
  }
}
```

### Expected Behavior

`terraform apply` -> adds the rules to the default security group
a subsequent `terraform apply` -> no changes should occur
### Actual Behavior

`terraform apply` -> adds the rules to the default security group
`terraform apply` -> tries to remove rules from the default security group
`terraform apply` -> adds the rules back again
![image](https://user-images.githubusercontent.com/14220781/64391959-8c5c9a80-cfff-11e9-89a9-675b8586a325.png)

![image](https://user-images.githubusercontent.com/14220781/64391853-27a14000-cfff-11e9-9e11-d9f6b2f0b56f.png)

I've also tried `terraform destroy --target aws_default_security_group.default` and applying again, but the results were the same. 

### Steps to Reproduce

`terraform apply`
`terraform apply`

### References

The behavior seems similar to:
terraform-providers/terraform-provider-aws#2069
terraform-providers/terraform-provider-aws#3628
terraform-providers/terraform-provider-aws#4410

(Edit 9/23): 
It appears as though it's happening now to normal security groups as well, leading  me to believe it's a general issue with inline rules? 
https://github.com/terraform-providers/terraform-provider-aws/issues/370 
https://github.com/terraform-providers/terraform-provider-aws/issues/10097

**Comment by gdavison** [comment]
Hi @NicoleYson, are you still seeing this error? I'm not able to reproduce it, but unfortunately it has been some time since you reported this.

**Comment by NicoleYson** [comment]
Hi @gdavison! I have not had the time to attempt to reproduce this, yet. 
But I do see that in similar issues, people are reporting it is still an issue in 0.12 this year 
- https://github.com/terraform-providers/terraform-provider-aws/issues/370#issuecomment-612474835 
- https://github.com/terraform-providers/terraform-provider-aws/issues/10097#issuecomment-614100229

**Comment by gdavison** [comment]
Thanks for the reply, @NicoleYson. I'll close this issue. If anyone encounters it in the future, they can open a new issue and link this one for additional context.
