### ISSUE TITLE
Support EnableHttpEndpoint for aws_rds_cluster

### ISSUE THREAD

**Issue by dave-lew99** [terraform-providers/terraform-provider-aws#10026]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RDS clusters for Aurora Serverless support the EnableHttpEndpoint option (equivalent to the --enable-http-endpoint CLI command)

### New or Affected Resource(s)

aws_rds_cluster

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster" "default" {
  cluster_identifier      = "NewCluster"
  vpc_security_group_ids  = ["${aws_security_group.security_group.id}"]
  db_subnet_group_name    = "${aws_db_subnet_group.default.name}"
  engine_mode             = "serverless"
  master_username         = "master"
  master_password         = "abc123"
  backup_retention_period = 7
  skip_final_snapshot     = false
  enable_http_api         = true

  scaling_configuration {
    auto_pause               = true
    max_capacity             = 32
    min_capacity             = 2
    seconds_until_auto_pause = 300
  }

}
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html

* #0000

**Comment by SamCullin** [comment]
Ye I am trying to directly integrate APIGateway with RDS and I need the http endpoint in order to do this.
