### ISSUE TITLE
AWS Config remediation exceptions

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Config now includes automatic remediation capability with AWS Config rules.

### New or Affected Resource(s)

* `aws_config_remediation_exception`

### Potential Terraform Configuration

```hcl
resource "aws_config_remediation_exception" "example" {
  config_rule_name = "${aws_config_rule.example.name}"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/09/use-aws-config-rules-to-automatically-remediate-non-compliant-resources/).
[Blog post](https://aws.amazon.com/blogs/mt/aws-config-auto-remediation/).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/10011

**Comment by bflad** [comment]
Remediation Configurations are covered under https://github.com/terraform-providers/terraform-provider-aws/issues/7972 and the pull request https://github.com/terraform-providers/terraform-provider-aws/pull/9348. The new functionality in AWS Go SDK v1.23.16 is Remediation Exceptions. I'd suggest retitling this feature request for the latter to reduce confusion. 👍

**Comment by lorengordon** [comment]
Seems like hashibot was premature here. The title was changed as requested.
