### ISSUE TITLE
aws_flow_log sending to s3 - Error validating S3 bucket name

### ISSUE THREAD

**Issue by anastasioss** [terraform-providers/terraform-provider-aws#10029]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v2.27.0
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

resource "aws_flow_log"

resource "aws_s3_bucket"

### Terraform Configuration Files

```hcl
resource "aws_flow_log" "vpc-flow-log" {
  log_destination      = "${aws_s3_bucket.vpc-flow-log.bucket}"
  log_destination_type = "s3"
  traffic_type         = "ALL"
  vpc_id               = "${module.network.vpc_id}"
}

resource "aws_s3_bucket" "vpc-flow-log" {
  bucket = "arn:aws:s3:::xxxxx-flow-logs"
}
```

### Debug Output

https://gist.github.com/anastasioss/b96da8a4eb570109729790571e10f689

### Panic Output
N/A
### Expected Behavior

Terraform apply action, should configure the vpc flow and use the S3 bucket for the vpc flow logs.

### Actual Behavior

Despite the fact that Terraform plan was successful, Terraform apply returned:

Error: Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.vpc-flow-log: 1 error(s) occurred:

* aws_s3_bucket.vpc-flow-log: Error validating S3 bucket name: only lowercase alphanumeric characters and hyphens allowed in "arn:aws:s3:::xxxxx-flow-logs"

### Steps to Reproduce

1. Try to create a new resource "aws_flow_log" with its respective resource "aws_s3_bucket".

2. `terraform apply`

### Important Factoids
No
### References
N/A

**Comment by ryndaniels** [comment]
Hi @anastasioss! Thanks for opening this issue! It looks like the error you're seeing is related to the name of your bucket that you have configured. The error says: `only lowercase alphanumeric characters and hyphens allowed` and the name you currently have configured for it has `:` in it: `"arn:aws:s3:::xxxxx-flow-logs"`. Can you try your configuration with a bucket name without the colons in it? Something like:

```
resource "aws_s3_bucket" "vpc-flow-log" {
  bucket = "xxxxx-flow-logs"
}
```
or similar should do the trick. Thanks! 🙂

**Comment by anastasioss** [comment]
Hi @ryndaniels,

Thank you for your prompt answer.

It seems to be so trivial, but the catch there is that the requirement it's not just a bucket name, but a proper, valid ARN ("^arn:[\\w-]+:([a-zA-Z0-9\\-])+:([a-z]{2}-(gov-)?[a-z]+-\\d{1})?:(\\d{12})?:(.*)$").

If we use the solution you recommended, we have the following error:

```
Error: Error running plan: 1 error(s) occurred:

* aws_flow_log.vpc-flow-log: "log_destination" doesn't look like a valid ARN ("^arn:[\\w-]+:([a-zA-Z0-9\\-])+:([a-z]{2}-(gov-)?[a-z]+-\\d{1})?:(\\d{12})?:(.*)$"): "xxxxxx-flow-logs"
```

There is also another use case, this check will fail. For example, if you need to store multiple VPC flow logs, in one bucket, under multiple folders (e.g. bucket1/vpc1, bucket1/vpc2, bucket1/vpc3). If I am not mistaken, with this check in place, you have the constraint to create one bucket per vpc.

Thank you.

**Comment by ryndaniels** [comment]
Hi @anastasioss! You're right, sorry for missing that in the config! For your first case, I believe if you use the `arn` attribute instead of the `bucket` attribute when defining the `aws_flow_log` configuration, that should solve the "doesn't look like a valid ARN" error:

```
resource "aws_flow_log" "vpc-flow-log" {
  log_destination      = "${aws_s3_bucket.vpc-flow-log.arn}"
...
}

resource "aws_s3_bucket" "vpc-flow-log" {
  bucket = "xxxxx-flow-logs"
}
```

Are you able to give that a try and see if that gets you anywhere?

**Comment by anastasioss** [comment]
Hi @ryndaniels,

I did that change and yes, it is now creating both (vpc flow log AND S3 bucket).

Any ideas on how to use multiple VPC flow logs, under one "root" S3 bucket?

Thank you.

**Comment by ryndaniels** [comment]
Hi @anastasioss - you can create multiple flow logs with the same bucket, so long as they have non-identical configurations. So, as an example, you could do something like:

```
resource "aws_s3_bucket" "vpc-flow-log" {
  bucket = "xxx-flow-logs"
}

resource "aws_flow_log" "vpc-flow-log-accept" {
  log_destination      = "${aws_s3_bucket.vpc-flow-log.arn}"
  log_destination_type = "s3"
  traffic_type         = "ACCEPT"
...
}

resource "aws_flow_log" "vpc-flow-log-reject" {
  log_destination      = "${aws_s3_bucket.vpc-flow-log.arn}"
  log_destination_type = "s3"
  traffic_type         = "REJECT"
...
}
```

In general though, issues in this repository are more for specific code bugs or feature requests in the provider code itself. Questions like these are better suited to the [forums here](https://discuss.hashicorp.com/c/terraform-providers/tf-aws), so I'm going to go ahead and close this issue, and if you have further usage questions, please give the forums a try! 🙂
