### ISSUE TITLE
Fix TypeSet computed-only data source schemas once they aren't collapsed

### ISSUE THREAD

**Issue by ryndaniels** [terraform-providers/terraform-provider-aws#10030]
As part of fixing #7198, we found a few other data sources that have all-Computed configuration blocks that will be impacted by that fix. Some of the impacts will fix other bugs where multiple results would have disappeared (as was the original symptom described in #7198):

* datasource (aws_instance) attribute (ebs_block_device) 
* datasource (aws_launch_configuration) attribute (ephemeral_block_device) 
* datasource (aws_launch_configuration) attribute (ebs_block_device) 
* datasource (aws_ecs_cluster) attribute (setting) 
* datasource (aws_dynamodb_table) attribute (global_secondary_index) 

Some of these will need to be changed from `TypeSet` to `TypeList` as they will only ever contain one item:

* datasource (aws_instance) attribute (root_block_device) 
* datasource (aws_elasticsearch_domain) attribute (log_publishing_options)
* datasource (aws_dynamodb_table) attribute (ttl) 

Once [this fix](https://github.com/hashicorp/terraform/pull/22719) is merged and being used in the AWS Provider, we should make sure to go make those `TypeList` changes to avoid causing further problems.

**Comment by bflad** [comment]
For the benefit of other travelers, this statement:

> Some of these will need to be changed from TypeSet to TypeList as they will only ever contain one item:

Is to retain Terraform 0.11 compatibility with `attribute.0.XXX` references as well as keep our test check functions compatible. In Terraform 0.12, the rich data types currently require `tolist(attribute)[0]` references, as there should be an error when attempting to index a `set`:

```console
> toset(list("a", "b", "c"))[0]

> Error: Invalid index

  on <console-input> line 1:
  (source code not available)

This value does not have any indices.

> tolist(toset(list("a", "b", "c")))[0]
a
```

Switching the underlying data type from `set` to `list` seems like it is compatible with `tolist()` so there should be no configuration changes required:

```console
> tolist(list("a", "b", "c"))[0]
a
```

**Comment by bflad** [comment]
New upstream fix PR is here: https://github.com/hashicorp/terraform-plugin-sdk/pull/197

**Comment by bflad** [comment]
This functionality was merged upstream in Terraform Plugin SDK version 2.0.0, which was merged into the Terraform AWS Provider as part of version 3.2.0. If there are any specific resources or data sources that have buggy behavior after this change, we'll let fresh bug reports tease them out. 👍
