### ISSUE TITLE
Refactor Out randomString()

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#10040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is a function named `randomString()`, which generates a random lowercase alphabetical string:

https://github.com/terraform-providers/terraform-provider-aws/blob/b4efb0be0ac4315f2f4ac52955e58fc32ffe05d5/aws/resource_aws_db_parameter_group_test.go#L624-L632

Most usage of this function should be replaced with [`acctest.RandStringFromCharSet(len, acctest.CharSetAlpha)`](https://godoc.org/github.com/hashicorp/terraform/helper/acctest#RandStringFromCharSet), which is functionally equivalent and part of the Terraform Provider SDK.

### Affected Resource(s)

- [ ] `aws/resource_aws_db_parameter_group_test.go`
- [x] `aws/resource_aws_elb_test.go`
- [x] `aws/resource_aws_iam_role_policy_test.go`
- [ ] `aws/resource_aws_iam_role_test.go`
- [x] `aws/resource_aws_iam_user_policy_test.go`
- [ ] `aws/resource_aws_iam_user_test.go`
- [x] `aws/resource_aws_redshift_cluster_test.go`
- [x] `aws/resource_aws_redshift_parameter_group_test.go`
- [x] `aws/resource_aws_redshift_security_group_test.go`
- [x] `aws/resource_aws_redshift_subnet_group_test.go`
- [x] `aws/resource_aws_worklink_fleet_test.go`
- [x] `aws/resource_aws_worklink_website_certificate_authority_association_test.go`
- [ ] `aws/validators_test.go` (see also #8424)

**Comment by Jukie** [comment]
Are we ready to make changes in https://github.com/terraform-providers/terraform-provider-aws/blob/b4efb0be0ac4315f2f4ac52955e58fc32ffe05d5/aws/resource_aws_db_parameter_group_test.go#L624-L632 now @bflad?

**Comment by Jukie** [comment]
Scratch that, looks like aws/validators_test.go is the last one. Considering there doesn't seem to be a consensus for #8424 would you prefer to refactor aws/validators_test.go so we can close this issue in the meantime?

**Comment by bflad** [comment]
@Jukie let's refactor `aws/validators_test.go` for now and feel free to remove `randomString()` itself then -- thanks so much for helping out with this issue!
