### ISSUE TITLE
New service: Amazon Quantum Ledger Database 

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon QLDB is now GA.

### New or Affected Resource(s)

* `aws_qldb_ledger`

### Potential Terraform Configuration

```hcl
resource "aws_qldb_ledger" "example" {
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/09/announcing-general-availability-qldb/).
[Blog post](https://aws.amazon.com/blogs/aws/now-available-amazon-quantum-ledger-database-qldb/).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/10011

**Comment by pbalduino** [comment]
I already have something done for this. I can send a PR.

**Comment by pbalduino** [comment]
Also it will be useful to have `aws_qldb_table` and `aws_qldb_index`.

**Comment by bflad** [comment]
Hey @pbalduino 👋 The QLDB tables and indices appear to be part of [PartiQL](https://docs.aws.amazon.com/qldb/latest/developerguide/ql-reference.statements.html) and not the [API](https://docs.aws.amazon.com/qldb/latest/developerguide/API_Operations.html). The Terraform AWS Provider is specifically focused on just interacting with AWS APIs -- so we would be expecting any PartiQL handling to be done in a separate Terraform provider. If AWS does wind up implementing an "execute query" type API call for QLDB, we can revisit that topic. 👍

**Comment by bflad** [comment]
Hi folks 👋 A new `aws_qldb_ledger` data source and resource have been merged and will release with version 2.35.0 of the Terraform AWS Provider, Thursday next week. Thanks to @kristiandrucker for the implementation. 👍 

For additional feature requests and bug reports with QLDB functionality, please create new GitHub issues.
