### ISSUE TITLE
No exception is thrown for non-existent AWS ECR data resources

### ISSUE THREAD

**Issue by vermdeep** [terraform-providers/terraform-provider-aws#10071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.8
+ provider.aws v2.27.0

### Affected Resource(s)

* aws_ecr

### Terraform Configuration Files

```hcl
data "aws_ecr_repository" "repository" {
  name = "services/x"
}

output "x" {
value = data.aws_ecr_repository.repository
}
```

### Expected Behavior
Terraform should have raised the error that ecr repository is not found, like it does in case of *aws_instance* and *aws_db_instance* data sources.

### Actual Behavior
Terraform does not produce error and produces following output:
```
Outputs:

x = {}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by anGie44** [comment]
This bug has been fixed with #10520, now merged and set to release with upcoming `v3.0.0` of the Terraform AWS Provider.
