### ISSUE TITLE
Changing the name option for a aws_ssm_parameter creates a new parameter in the Parameter Store

### ISSUE THREAD

**Issue by FransUrbo** [terraform-providers/terraform-provider-aws#1008]
If I only change the `name` option to a `aws_ssm_parameter` resource, TF will create a NEW parameter, not rename the old one (or possibly delete the old, create the new).

### Terraform Version
0.9.8

### Affected Resource(s)
- aws_ssm_parameter

### Terraform Configuration Files
```hcl
provider "aws" {}
resource "aws_ssm_parameter" "test" {
  name                   = "test1"
  type                   = "SecureString"
  value                  = "secret"
}
```

### Expected Behavior
The old parameter should be either renamed to the new name, or possibly (if easier) simply been deleted and the new resource created.

### Actual Behavior
I ended up with TWO parameters, one with the old name and one with the new name.

### Steps to Reproduce
1. `terraform apply`
2. Change the `name` option to `test2`
3. `terraform apply`

**Comment by FransUrbo** [comment]
PS. Please back port to 0.9 if possible!

**Comment by FransUrbo** [comment]
Additionally, if I after running `apply` the second time then run `destroy` only the last parameter will be deleted. The initial one, `test1` will remain and have to be deleted manually.

**Comment by FransUrbo** [comment]
No. I shouldn't have to enable overwrite to be able to rename things. That's not how anything else in TF works!

It doesn't complain at all if I change the `name` option, it will simply/silently create a new parameter.

**Comment by stack72** [comment]
Can you confirm what the behaviour is using the cli?

**Comment by FransUrbo** [comment]
This will of course create two resources:
```
aws ssm put-parameter --name test1 --type SecureString --value "test"
aws ssm put-parameter --name test2 --type SecureString --value "test"
```

This works of course, so this is what TF then needs to do, and I'm fine with that:
```
aws ssm put-parameter --name test1 --type SecureString --value "test1"
aws ssm delete-parameter --name test1
aws ssm put-parameter --name test2 --type SecureString --value "test"
```
That is, TF should know that the `name` option have changed, and would/should force a recreate of the resource (TF does that elsewhere for similar things). This is "bad", but because you don't get a "handle" or anything back in this case (that I could see), there's no other choice...
But on the other hand, a recreate in this case isn't that big of a deal - it's the same value and it's quick to do...

Although there's throttling somewhere (not sure how much and when - it only happened once and i wasn't paying attention to that at the moment).

**Comment by stack72** [comment]
So you are saying that a change of name should be ForceNew?

**Comment by FransUrbo** [comment]
There's no other option :(.
