### ISSUE TITLE
Add support for AWS Glue Workflows

### ISSUE THREAD

**Issue by kevindixon** [terraform-providers/terraform-provider-aws#10116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Glue Workflows were introduced in June to aid in creation of complex ETL workflows - essentially, they orchestrate triggers, jobs and crawlers into workflow structures and encapsulate running and logging of that workflow.

### New or Affected Resource(s)

* aws_glue_crawler
* aws_glue_job
* aws_glue_trigger
* (new) workflow structure(s)

### Potential Terraform Configuration

```
TBD
```

### References

* https://docs.aws.amazon.com/en_pv/glue/latest/dg/workflows_overview.html
* https://docs.aws.amazon.com/en_pv/glue/latest/dg/aws-glue-api-workflow.html

**Comment by bflad** [comment]
Hi folks 👋 A new `aws_glue_workflow` resource and enhancements regarding workflow support in the `aws_glue_trigger` resource have been merged and will release with version 2.39.0 of the Terraform AWS Provider, by Thursday. Thanks to @Achal-Aggarwal and @bdoepf for the implementations. 👍 

For further feature requests or bug reports with this functionality, please open new GitHub issues. 😄
