### ISSUE TITLE
default aws_ebs_volume type

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#1012]
terraform 0.9.8

Is the team aware of any recent(ish) change to the default type of an aws_ebs_volume. 

I have been creating gp2 type aws_ebs_volumes for ages (without specifying the type), but have started to notice that recent ebs_volumes have been created as standard (without specifying the type). I didn't notice anything in breaking changes in the CHANGELOGs at terraform. 

If it has been changed, maybe worth updating the changelogs with a breaking change - but if it hasn't I'm perplexed :)

**Comment by stack72** [comment]
@gtmtech 

We don't actually set a default type - 

```
"type": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
```

That must be controlled on the AWS side.... I am trying to find the code now

Paul

**Comment by stack72** [comment]
This is in their SDK:

```
	// The volume type. This can be gp2 for General Purpose SSD, io1 for Provisioned
	// IOPS SSD, st1 for Throughput Optimized HDD, sc1 for Cold HDD, or standard
	// for Magnetic volumes.
	//
	// Default: standard
	VolumeType *string `type:"string" enum:"VolumeType"`
```

**Comment by gtmtech** [comment]
Thanks - I've been provisioning using terraform for ages, and for some reason some have come out as standard and some as gp2 - I wonder maybe their default changes for different instance types.

Thanks for the clarification on terraform end

**Comment by stack72** [comment]
no worries :) maybe a question on their SDK will be good to get your answers https://github.com/aws/aws-sdk-go
