### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by midacts** [terraform-providers/terraform-provider-aws#10136]
Has your team considered creating a Slack workspace like the AzureRM provider has?
`terraform-azure.slack.com`

Having a slack workspace dedicated to the specific provider seems to have been the most beneficial for me working with the provider, compared to using gitter or Google groups.

**Comment by nywilken** [comment]
Hi @midacts thanks for posting this question. Yes, we have considered it and will be rolling this out soon. 

>Having a slack workspace dedicated to the specific provider seems to have been the most beneficial for me working with the provider, compared to using gitter or Google groups. 

We share the same sentiment about having a provider workspace to help folks working on the provider. Keep an eye on the README for a link to the slack workspace once created.

**Comment by midacts** [comment]
![PogChamp](https://user-images.githubusercontent.com/3960208/65146253-59e07380-d9e9-11e9-83f6-606b11264273.png)

Awesome. I'll keep an eye on the README.
I'm looking forward to it.   : )
