### ISSUE TITLE
Add ecs_service wait_for_stable property

### ISSUE THREAD

**Issue by richardgavel** [terraform-providers/terraform-provider-aws#10149]
A change was recently added to support a wait_for_deployed on aws_cloudfront_distribution: https://github.com/terraform-providers/terraform-provider-aws/pull/8116. It'd be nice to have similar wait_for_x properties on other resources. In this case, a wait_for_stable that mimics the cli call (https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html).

**Comment by ewbankkit** [comment]
Is this the same as https://github.com/terraform-providers/terraform-provider-aws/issues/3107?

**Comment by richardgavel** [comment]
Yes
