### ISSUE TITLE
Amazon API Gateway private REST APIs with VPC endpoints

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon API Gateway simplifies accessing private APIs by allowing you to associate one or more Amazon Virtual Private Cloud (VPC) Endpoints to a private API.

### New or Affected Resource(s)

* [`api_gateway_rest_api`](https://www.terraform.io/docs/providers/aws/r/api_gateway_rest_api.html)

### Potential Terraform Configuration

```hcl
resource "aws_api_gateway_rest_api" "example" {
  name = "example"

  endpoint_configuration {
    types = ["PRIVATE"]
    vpc_endpoint_ids = ["${aws_vpc_endpoint.example.id}"]
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-api-gateway-simplifies-invoking-private-apis/).
[Developer guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/associate-private-api-with-vpc-endpoint.html).

Requires [AWS SDK v1.24.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.24.1):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10011

**Comment by bflad** [comment]
Support for the `endpoint_configuration` configuration block `vpc_endpoint_ids` argument in the `aws_api_gateway_rest_api` resource has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
