### ISSUE TITLE
Terraform wrongly detects that it can change an EBS volume size

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#1019]
Terraform 0.9.8

I have provisioned an EBS volume using

```
resource "aws_ebs_volume" "foo" {
    count             = "${var.flags["enable_foo"]}"
    availability_zone = "${element(var.availability_zones, count.index)}"
    size              = 256
    lifecycle {
        prevent_destroy = true
    }

    tags {
        Name        = "foo"
    }
}
```

I successfully terraform it and then try to change the size to 512. 

During a plan terraform reports that the type of change is a "~" not a "-/+" and it can change the 256 to 512 (ie not create a new resource). 

However AWS does not allow this, and I get an error - so I have to destroy the EBS vol and recreate it instead.

**Comment by stack72** [comment]
Hi @gtmtech 

I'm not sure what you mean `AWS does not allow this` - what circumstances do they not allow this under? Is this a specific EBS type stopping it?

Thanks

Paul

**Comment by stack72** [comment]
ping @gtmtech

**Comment by sshvetsov** [comment]
@gtmtech: AWS did not **used** to allow this. It is now possible to increase size of EBS volume since announcement of [Elastic Volumes](https://aws.amazon.com/blogs/aws/amazon-ebs-update-new-elastic-volumes-change-everything/). There are some limitations of course: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/considerations.html

**Comment by gtmtech** [comment]
Ah this may explain it @sshvetsov - due to another issue I've raised, some of our volumes ended up being `standard` type which equates to magnetic, and not `gp2` or ssd - with `standard` type, the resizing of an EBS volume is not allowed (according to those docs you just sent) - perhaps terraform could check for this @stack72

**Comment by stack72** [comment]
Hi @gtmtech 

I don't think that terraform should be aware of those roles - hardcoding them means we could potentially stop people's infra from changing as they expected. I would rather add a note to the documentation to link to the latest limitations

Would that suffice?

Paul

**Comment by gtmtech** [comment]
Fair enough

**Comment by gtmtech** [comment]
@stack72  I've had second thoughts about this, and think that actually things do need fixing. Terraform plans the wrong changes in all sorts of ebs change cases. Take this for example:

```
~ aws_ebs_volume.foo
    type: "standard" => "gp2"
```

A simple change, just because the type is changed. Except this is impossible:

```
InvalidParameterValue: Volume type EBS Magnetic is not supported.
	status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

I guess we have to ask the question do we want terraform to do the right thing? The user knows if they want to change an EBS from standard to gp2, and if they do, terraform should know to destroy and recreate the resource, and not attempt an impossible change. 

Because if we allow these impossible changes, the user just has to go back to manually doing stuff, and/or creative use of plan -destroy -target first ANYWAY, and then recreate, so terraform is just not being useful in this case.

**Comment by stack72** [comment]
Hi

I'm sorry, I no longer work on the Terraform team so one of the HashiCorp
team will have to look at this instead

Paul
