### ISSUE TITLE
Terraform ignores EBS volume size 

### ISSUE THREAD

**Issue by unacceptable** [terraform-providers/terraform-provider-aws#10232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
``` sh
> $ terraform -v
Terraform v0.12.9
+ provider.aws v2.29.0
+ provider.local v1.3.0
+ provider.random v2.2.0
+ provider.tls v2.1.0
```

### Affected Resource(s)

* aws_launch_configuration
* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "ecs" {
    ...
    root_block_device {
        volume_type = "gp2"
        volume_size = 20
        encrypted   = true
    }
}

resource "aws_autoscaling_group" "ecs" {
   ...
}
```

### Debug Output

N/A - I don't believe that it would add anything of note for this specific issue, but would be happy to provide it if others feel that it would.

### Panic Output

N/A

### Expected Behavior

I would expect an EC2 instance with an EBS volume with a max size of 30GB and a min size of whatever is specified in the `root_block_device` block to be used, vice always a 30GB

### Actual Behavior

Terraform creates a snapshot with a larger than needed EBS volume:

``` sh
aws_autoscaling_group.ecs: Still creating... [9m50s elapsed]
aws_autoscaling_group.ecs: Still creating... [10m0s elapsed]

Error: "project-environment-webservices-cluster": Waiting up to 10m0s: Need at least 4 healthy instances in ASG, have 0. Most recent activity: {
  ActivityId: "db95b594-d7be-ab7c-ee18-d55d87b8a2f4",
  AutoScalingGroupName: "project-environment-webservices-cluster",
  Cause: "At 2019-09-24T21:38:14Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 4.",
  Description: "Launching a new EC2 instance.  Status Reason: Volume of size 20GB is smaller than  snapshot 'snap-095a59a84a4452968', expect size >= 30GB. Launching EC2 instance failed.",
  Details: "{\"Subnet ID\":\"subnet-0f171eddb85de550f\",\"Availability Zone\":\"us-west-2c\"}",
  EndTime: 2019-09-24 21:38:16 +0000 UTC,
  Progress: 100,
  StartTime: 2019-09-24 21:38:16.618 +0000 UTC,
  StatusCode: "Failed",
  StatusMessage: "Volume of size 20GB is smaller than  snapshot 'snap-095a59a84a4452968', expect size >= 30GB. Launching EC2 instance failed."
}

  on Terraform/ec2.tf line 27, in resource "aws_autoscaling_group" "ecs":
  27: resource "aws_autoscaling_group" "ecs" {


script returned exit code 1
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None

**Comment by gdavison** [comment]
Hi @unacceptable. This is a limitation on the AWS side. EBS volumes cannot be created from a snapshot larger than the volume. See Step 8 at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-restoring-volume.html#ebs-create-volume-from-snapshot
