### ISSUE TITLE
EKS subnet_ids not accepting list values as expected. 

### ISSUE THREAD

**Issue by kodali-adobe** [terraform-providers/terraform-provider-aws#10243]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
* Terraform 0.12

### Affected Resource(s)

* aws 2.29 
aws_eks_cluster

### Terraform Configuration Files

```hcl
#Code with Bug#
resource "aws_eks_cluster" "cluster" {
  name     = var.cluster-name
  role_arn = aws_iam_role.cluster_role.arn

  vpc_config {
    security_group_ids      = [aws_security_group.cluster-secgroup.id]
    subnet_ids              = ["${aws_subnet.example1_subnet.*.id}", "${aws_subnet.example2_subnet.*.id}"]

    endpoint_private_access = true
    endpoint_public_access  = true
  }
}
```

```hcl
#This works as the string is accepted value#
resource "aws_eks_cluster" "cluster" {
  name     = var.cluster-name
  role_arn = aws_iam_role.cluster_role.arn

  vpc_config {
    security_group_ids      = [aws_security_group.cluster-secgroup.id]
    subnet_ids              = "${aws_subnet.example_subnet.*.id}"
    endpoint_private_access = true
    endpoint_public_access  = true
  }
}
```

### Actual Behavior

The API for EKS create cluster on subnet_ids accepts list of strings as value. But, on the code with bug, It causes following error, with expected string as the required value.
```Inappropriate value for attribute "subnet_ids": element 0: string required.```

### Steps to Reproduce

1. `terraform plan`

### References
https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html
https://www.terraform.io/docs/providers/aws/r/eks_cluster.html

* #0000

**Comment by bflad** [comment]
Hi @kodali-adobe 👋 Sorry you are running into trouble here.

Without seeing the definition of your `aws_subnet` resources, it is hard to provide an exact recommendation, but something that may help would be removing the string interpolations with `"${` and `}"` so the configuration is only using 0.12 syntax.

The use of the splat (`*`) operator in your references (e.g. `aws_subnet.example_subnet.*.id`) also implies these are resources using `count`. If they are not using `count`, you should remove the `.*` as well.

Please provide the full configuration and we can take a deeper look, thanks.

**Comment by bflad** [comment]
Closing due to lack of response.
