### ISSUE TITLE
Glue Crawler database name should be lower case

### ISSUE THREAD

**Issue by vertexclique** [terraform-providers/terraform-provider-aws#10252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_glue_crawler

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

```
When expanding the plan for
module.etl.aws_glue_crawler.glue_crawler_test to include new values
learned so far during apply, provider "aws" produced an invalid new value for
.database_name: was cty.StringVal("TestMeDatabase"), but now
cty.StringVal("testmedatabase").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior

Destroy and instantiate. Synchronization shouldn't be a problem.

### Actual Behavior

The discrepancy between the generated plan and the rules of database name.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Code was in a terraform module. So I don't know it makes a difference or not. Also hardcoded.

### References

* #7958

**Comment by bflad** [comment]
Hi @vertexclique 👋 Thank you for submitting this and sorry you ran into trouble there. To fix this issue in your configuration, lowercase the names being passed into the `database_name` and `name` arguments. Since this appears to be covering the same intention of #7958 and fix of #8288, to consolidate efforts and discussions I'm going to close this issue in preference of the earlier ones. 👍
