### ISSUE TITLE
Creating glue table using a provider gives access denied

### ISSUE THREAD

**Issue by bhavikkumar** [terraform-providers/terraform-provider-aws#10251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.9
+ provider.aws v2.29.0

### Affected Resource(s)

* aws_glue_catalog_database

### Terraform Configuration Files

```hcl
resource "aws_glue_catalog_database" "default" {
  name = "east"
}

resource "aws_glue_catalog_database" "another_region" {
  name     = "west"
  provider = aws.oregon
}

provider "aws" {
  region  = "us-east-1"
  version = "~> 2.29.0"
  profile = var.profile

  assume_role {
    role_arn     = data.terraform_remote_state.my-state.outputs.deployment_role_arn
    session_name = "default"
  }
}

provider "aws" {
  alias   = "oregon"
  region  = "us-west-2"
  profile = var.profile

  assume_role {
    role_arn     = data.terraform_remote_state.my-state.outputs.deployment_role_arn
    session_name = "oregon"
  }
}
```

### Expected Behavior

Expected both glue databses to get created. The `east` to be created in us-east-1 and `west` bucket to be created in us-west-2. 

### Actual Behavior

The `east` bucket is created successfully, however the `west` bucket produces the following error:

However the following error is produced on the `west` bucket even though the role being used is the same with full admin privileges.
```
Error creating Catalog Database: AccessDeniedException: Insufficient Lake Formation permission(s): Required Create Database on Catalog
        status code: 400, request id: 89565eb5-e013-11e9-b556-51dde1f07a21
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Vino-Bala** [comment]
Hi,
Try this.
In AWS Lake Formation console login as data lake's admin account
Click on "Permissions" -> "Admins and database creators" in the navigation box on your left
On the right side, in "Database creators" section, grant permission for the user, which you have configured to use Athena.

**Comment by leopepe** [comment]
You need to guarantee access to Gule user via Lake Formation permissions. Or you can also enable the backward compatibility with IAM Permission schema.
https://docs.aws.amazon.com/lake-formation/latest/dg/upgrade-glue-lake-formation.html

**Comment by bhavikkumar** [comment]
Thanks @Vino-Bala @leopepe. I will close this.
