### ISSUE TITLE
Supply tags in the CreateFileSystemInput when create and EFS resource

### ISSUE THREAD

**Issue by dbgeek** [terraform-providers/terraform-provider-aws#10278]
At our organisation we control our access who can create EFS resources by continual by  `TAG`. The function `resourceAwsEfsFileSystemCreate`it does not add the `TAGS` to the `CreateFileSystemInput`so we getting the `AcessDeniedExpetion`when we trying to create an `EFS`resource

```
Error: Error creating EFS file system: AccessDeniedException: User: arn:aws:sts::xxxxxxxx:assumed-role/xxxx.IdP_admin/xxxxx@xxxxx is not authorized to perform: elasticfilesystem:CreateFileSystem on the specified resource
        status code: 403, request id: xxxxxx-6515-4175-99ae-56f004381386
```
## Terraform Version
* Terraform 0.12
## Affected Resource(s)
* resource_aws_efs_file_system

**Comment by bflad** [comment]
Hi @dbgeek 👋 Thanks for submitting this. This was merged earlier today (#10254) and will release in version 2.31.0 of the Terraform AWS Provider, next Thursday.
