### ISSUE TITLE
rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by SarahRiley** [terraform-providers/terraform-provider-aws#10280]
I'm seeing a bunch of `err: rpc error: code = Canceled desc = context canceled`.  This repo plans fine with 0.11, but fails on 0.12.  There are ~3000 items in the terraform state.

### Terraform Version

0.12.7

### Affected Resource(s)

* aws_v2.30.0_x4

### Terraform Configuration Files
```
resource "aws_subnet" "private" {
  count = var.vpc_subnet != "" ? local.availability_zone_count : 0

  availability_zone = element(local.availability_zones, count.index)
  cidr_block        = cidrsubnet(cidrsubnet(aws_vpc.main[0].cidr_block, 1, 0), 3, count.index)
  vpc_id            = aws_vpc.main[0].id

  tags = {
    AZ                                   = element(local.availability_zones, count.index)
    Env                                  = var.env
    Product                              = var.product
    Name                                 = "private-${element(local.availability_zones, count.index)}"
    Tier                                 = "private"
    ZoneId                               = element(data.aws_availability_zone.zone.*.zone_id, count.index)
    "kubernetes.io/role/internal-elb"    = "1"
    "kubernetes.io/cluster/main-cluster" = "shared"
  }
}
```
### Debug Output

```
2019/09/27 19:16:19 [TRACE] module.vpn_prod.module.vpc: eval: *terraform.EvalSequence
2019/09/27 19:16:19 [TRACE] module.vpn_prod.module.vpc: eval: *terraform.EvalGetProvider
2019/09/27 19:16:19 [TRACE] module.vpn_prod.module.vpc: eval: *terraform.EvalReadState
2019/09/27 19:16:19 [TRACE] EvalReadState: reading state for module.vpn_prod.module.vpc.aws_subnet.private[2]
2019/09/27 19:16:19 [TRACE] UpgradeResourceState: schema version of module.vpn_prod.module.vpc.aws_subnet.private[2] is still 1; calling provider "aws" for any other minor fixups
2019/09/27 19:16:19 [TRACE] GRPCProvider: UpgradeResourceState
2019/09/27 19:16:19 [ERROR] module.vpn_prod.module.vpc: eval: *terraform.EvalReadState, err: rpc error: code = Canceled desc = context canceled
2019/09/27 19:16:19 [ERROR] module.vpn_prod.module.vpc: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2019/09/27 19:16:19 [TRACE] [walkRefresh] Exiting eval tree: module.vpn_prod.module.vpc.aws_subnet.private[2]
2019/09/27 19:16:19 [TRACE] vertex "module.vpn_prod.module.vpc.aws_subnet.private[2]": visit complete
```

Further output at:

https://gist.githubusercontent.com/SarahRiley/92f09b4bc8ba9ae1e6422d5a09af1824/raw/fddd31da0972e3db9202402fd921a68219db0eac/gistfile1.txt

### Expected Behavior

Terraform planned correctly

### Actual Behavior

Terraform errored with multiple `err: rpc error: code = Canceled desc = context canceled` and a `timeout while waiting for plugin to start`, which the debug says is the aws plugin.

### Steps to Reproduce

1. `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by SarahRiley** [comment]
This is running with the official Docker image.

**Comment by SarahRiley** [comment]
We ended up splitting this repo into 3, and this section no longer has problems.

**Comment by jufemaiz** [comment]
Can we reopen this?

Is the problem the size?

**Comment by SarahRiley** [comment]
I thought it was size, then eventually found that this came up again in one of the repos that had been split. The cause ended up being an extra set of [] being used in formatlist after the upgrader had run, but it required a lot of binary searching of resources to track down. 

I think you should file a separate issue.

**Comment by jufemaiz** [comment]
For the record, I think we had an issue with memory allocation (CI/CD tooling).
