### ISSUE TITLE
aws_lambda_alias try and fail being updated in line when Lambda function name is changed

### ISSUE THREAD

**Issue by gileri** [terraform-providers/terraform-provider-aws#10298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.9
+ provider.aws v2.30.0

### Affected Resource(s)

* aws_lambda_alias

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "example" {
  function_name = "example"
 # Other attributes
}

resource "aws_lambda_alias" "example_prod" {
  name             = "prod"
  function_name    = aws_lambda_function.example.arn
  function_version = "$LATEST"
}
```

### Expected Behavior

Terraform should I believe :
1. Destroy the lambda alias
2. Destroy the lambda function
3. Create the lambda function
4. Create the alias

### Actual Behavior

```hcl
  # aws_lambda_function.example must be replaced
-/+ resource "aws_lambda_function" "example" {
      ~ arn                            = "arn:aws:lambda:eu-central-1:1234:function:example" -> (known after apply)
      ~ function_name                  = "example" -> "example-new" # forces replacement
[...]
  # aws_lambda_alias.example_prod will be updated in-place
  ~ resource "aws_lambda_alias" "transactional_retry_prod" {
        arn              = "arn:aws:lambda:eu-central-1:1234:function:example:prod"
      ~ function_name    = "arn:aws:lambda:eu-central-1:1234:function:example" -> (known after apply)
        function_version = "$LATEST"
        id               = "arn:aws:lambda:eu-central-1:1234:function:example:prod"
        invoke_arn       = "<ARN>"
        name             = "prod"
    }
[
```
```
Error: Error updating Lambda alias: ResourceNotFoundException: Alias not found: arn:aws:lambda:eu-central-1:1234:function:example:prod
        status code: 404, request id: 00c68f23-32ed-437d-a18d-a84f27ba9a54

  on example.tf line 31, in resource "aws_lambda_alias" "example_prod":
  31: resource "aws_lambda_alias" "example_prod" {
```

### Steps to Reproduce

1. Create a lambda, and an lambda alias
2. `terraform apply`
3. Change the `function_name` of the lambda in Terraform.
4. `terraform apply`

### References

* #4090 look similar to this one. I'm not sure, but I think that adding `ForceNew: true` to the function_name attribute of `aws_lambda_alias` should solve the issue.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. Thanks to @eservent for the implementation. 👍
