### ISSUE TITLE
Tech debt: Use standard cross-account acceptance testing setup

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://github.com/terraform-providers/terraform-provider-aws/pull/7627 added standard cross-account acceptance testing setup functions `testAccAlternateRegionProviderConfig()`, `testAccGetAlternateRegion()` etc.
Ensure that these functions are used in acceptance tests for other cross-region resources.

* `aws_instance` - `TestAccAWSInstance_multipleRegions()`
* `aws_rds_cluster` - `TestAccAWSRDSCluster_EncryptedCrossRegionReplication()`
* `aws_route53_zone_association` - `TestAccAWSRoute53ZoneAssociation_region()`
* `aws_s3_bucket` - Multiple

Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/7702
* #8316
* #15737
* #15791

**Comment by RickyRajinder** [comment]
Hi, I'd like to contribute. Should each hard coded value be replaced with the alternate region functions or should the tests be extended to test on both default and alternate regions?

**Comment by ewbankkit** [comment]
@RickyRajinder Thanks for volunteering 👏.
Looking at e.g. `testAccAWSClusterConfigEncryptedCrossRegionReplica()` I would suggest
* Removing the 2 hard-coded provider blocks
```hcl
provider "aws" {
  alias  = "useast1"
  region = "us-east-1"
}
provider "aws" {
  alias  = "uswest2"
  region = "us-west-2"
}
```
* Replacing
```go
	return fmt.Sprintf(`
```
with
```go
	return testAccAlternateRegionProviderConfig() + fmt.Sprintf(`
```
* Remove all `provider = "aws.useast1"` lines
* Replace all `provider  = "aws.uswest2"` with `provider = "aws.alternate"`

**Comment by ewbankkit** [comment]
Also in `TestAccAWSRDSCluster_EncryptedCrossRegionReplication()`, calling `acctest.RandInt()` twice is going to cause the import test case to recreate the resources. So save the random value in a variable and pass it to `testAccAWSClusterConfigEncryptedCrossRegionReplica()`.

**Comment by ewbankkit** [comment]
Re-evaluate once https://github.com/terraform-providers/terraform-provider-aws/pull/12277 et al. are merged.

**Comment by ewbankkit** [comment]
Revisit for v3.x after https://github.com/terraform-providers/terraform-provider-aws/pull/14312 is merged.

**Comment by ewbankkit** [comment]
Closing as this is being/has been addressed via the linked issues.
