### ISSUE TITLE
Redshift elastic resize fails due to unexpected state

### ISSUE THREAD

**Issue by cmbrad** [terraform-providers/terraform-provider-aws#10337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.9
Terraform Provider AWS v2.30.0

### Affected Resource(s)

* aws_redshift_cluster

### Terraform Configuration Files

```hcl
resource "aws_redshift_cluster" "redshift_cluster" {
  cluster_identifier = "test-cluster"
  database_name      = "dev"
  master_username    = "redshiftadmin"
  master_password = "..."
  node_type          = "dc2.large"
  cluster_type       = "multi-node"
  number_of_nodes = 4
  enhanced_vpc_routing = true
}
```

### Expected Behavior

The Redshift cluster resizes successfully.

### Actual Behavior

The Redshift cluster fails to resize and produces an error. Resizing to a different amount of nodes to trigger a classic resize still works as expected.

```
Error: Error Modifying Redshift Cluster (test-cluster): unexpected state 'available, prep-for-resize', wanted target 'available'. last error: %!s(<nil>)

 
  on .terraform/modules/redshift-cluster/redshift/cluster/main.tf line 35, in resource "aws_redshift_cluster" "redshift_cluster":

  35: resource "aws_redshift_cluster" "redshift_cluster" {
```

### Steps to Reproduce

1. Define a redshift cluster with multiple nodes (for example, 4)
2. `terraform apply`
3. Change the number of nodes to a number where elastic resize will take effect (for example, 2, since it's half of 4)
4. `terraform apply`

### References

* #7599

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week. Thanks to @kterada0509 for the implementation. 👍
