### ISSUE TITLE
Inconsistent behaviour of aws_eks_cluster_auth token

### ISSUE THREAD

**Issue by gdurandvadas** [terraform-providers/terraform-provider-aws#10362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
➜ terraform -v
Terraform v0.12.9
+ provider.aws v2.30.0
+ provider.kubernetes v1.9.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_eks_cluster_auth

### Terraform Configuration Files

```hcl
data "aws_eks_cluster_auth" "this" {
  depends_on  = [module.kubernetes]
  name        = local.cluster_name
}

# Wait for EKS Endpoint to be available
resource "null_resource" "delay" {
  count = module.kubernetes.cluster_endpoint != null ? 1 : 0
  provisioner "local-exec" {
    command = "sleep 60"
  }
}

# Debug
resource "null_resource" "token" {
  provisioner "local-exec" {
    command = "echo ${data.aws_eks_cluster_auth.this.token}"
  }
}

provider "kubernetes" {
  host                   = module.kubernetes.cluster_endpoint
  cluster_ca_certificate = "${base64decode(module.kubernetes.cluster_certificate_authority_data)}"
  token                  = data.aws_eks_cluster_auth.this.token
  load_config_file       = false
  # Debug
  # exec {
  #   api_version = "client.authentication.k8s.io/v1alpha1"
  #   args        = ["token", "-i", "${local.cluster_name}"]
  #   command     = "aws-iam-authenticator"
  # }
}
```

### Debug Output

🤷‍♂️

### Expected Behavior

- EKS Cluster is created
- aws_eks_cluster_auth uses aws-iam-authenticator in the back to provide a token
- Kubernetes provider should be able to use the aws_eks_cluster_auth token to authenticate with EKS every time

### Actual Behavior

First time run
- EKS Cluster is created
- aws_eks_cluster_auth uses aws-iam-authenticator in the back to provide a token
- Kubernetes provider can access the cluster

Next runs
- EKS Cluster exist
- aws_eks_cluster_auth uses aws-iam-authenticator in the back to provide a token
- Kubernetes provider fails with 
```
is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace
```

#### Throubleshoot
- echo ${data.aws_eks_cluster_auth.this.token}
- use the token in Kubernetes provider `token`
- Kubernetes provider can access the cluster

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by pierresteiner** [comment]
We did experience that as well. It is caused by the depends_on in the aws_eks_cluster_auth

The following should work:
```hcl
data "aws_eks_cluster_auth" "this" {
  name = module.kubernetes.cluster_id
}
````
This is a workaround, IMHO it should also work with the depends_on

**Comment by gdurandvadas** [comment]
@pierresteiner yes, that way works. I think that documentation can be improved regarding this.

**Comment by mclate** [comment]
Please, Please, Please! Add this to documentation! I've spent three days trying to solve this issue and was about to file an issue when _accidentally_ have found this one. This is very non intuitive and no error ever pointing to this behaviour.
