### ISSUE TITLE
aws_iam_user_policy_attachment does not resolve policy resource arn dependency

### ISSUE THREAD

**Issue by tburow** [terraform-providers/terraform-provider-aws#10377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
Your version of Terraform is out of date! The latest version
is 0.12.9. You can update by downloading from www.terraform.io/downloads.html

terragrunt version v0.18.7

### Affected Resource(s)

resource "aws_iam_policy" "policy" {
  name        = "user-${var.ENV}-policy"
  description = "svc user policy"
  policy      = "${data.template_file.policy.rendered}"
}

resource "aws_iam_user_policy_attachment" "policy-attach" {
  user       = "${aws_iam_user.s3-access-user.name}"
  policy_arn = "${aws_iam_policy.policy.arn}"
}

* aws_XXXXX

### Terraform Configuration Files

see resource listing ^^^

### Debug Output

Error: Error running plan: 1 error occurred:
	* aws_iam_user_policy_attachment.policy-attach: 1 error occurred:
	* aws_iam_user_policy_attachment.policy-attach: Resource 'aws_iam_policy.policy' not found for variable 'aws_iam_policy.policy.arn'

### Expected Behavior

should have resolved the resource dependency normally

### Actual Behavior

will not resolve the policy ARN attribute when running a plan or apply

alt troubleshooting steps:
if I do a plan `--target=aws_iam_user_policy_attachment.policy-attach` it resolves the dependency properly

If i force a dependency with a `depends_on` block - it still does not resolve

### Steps to Reproduce

1. `terraform apply`, `terraform plan`, `terraform plan --target=`

### Important Factoids

running under terragrunt infrastructure live orchestration model -

**Comment by tburow** [comment]
ok doing a little more digging on this issue - if I do a targeted deploy the plan succeeds and I get the following error -

terragrunt plan --target=aws_iam_user_policy_attachment.policy-attach
Error: Error applying plan:
2 errors occurred:
	* aws_iam_user_policy_attachment.policy-attach: Resource 'aws_iam_policy.policy' not found for variable 'aws_iam_policy.policy.arn'
	* aws_iam_policy.policy: "policy" contains an invalid JSON: invalid character '"' after array element

Where as previously I got the preceeding error

**Comment by gregkoganvmm** [comment]
Ran into the same issue - the policy was indeed invalid (silly whitespace issue), but the underlying message is never shown unless you do a targeted deploy or comment out the attachment policy.

**Comment by tburow** [comment]
ultimately that was also my issue.  I had to also specify the target to get the correct error.   
I think the bug here is the error reporting on the policy resource.

**Comment by bflad** [comment]
The issue (or an iteration of this issue) of hidden validation errors was fixed in the early alphas of Terraform 0.12: https://github.com/hashicorp/terraform/issues/18129

Can you confirm this behavior still exists with recent versions of Terraform 0.12?

**Comment by tburow** [comment]
I cant at this time - we are working on 0.12 upgrade but there's a long list of prerequisites that we need to satisfy first. I'm hoping for mid January - then I might be able to confirm this.

**Comment by bflad** [comment]
Considering many reports like these were resolved with the upgrade to Terraform 0.12, I'm going to optimistically close this issue since it will be awhile for confirmation. If there is still an issue with recent versions of Terraform CLI (0.12+) and the Terraform AWS Provider, please create a new bug report and we'll take a fresh look. Thanks!
