### ISSUE TITLE
Error installing provider "AWS": failed to find installed plugin version 2.31.0

### ISSUE THREAD

**Issue by KwyjibojonesJr** [terraform-providers/terraform-provider-aws#10389]
Hello,
I searched for this and didnt find anything. so here goes.
the error message terraform gives me is:

---------------------------------------------------------------------------------
"$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "AWS" (hashicorp/aws) 2.31.0...

Error installing provider "AWS": failed to find installed plugin version 2.31.0; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

Error: failed to find installed plugin version 2.31.0; this is a bug in Terraform and should be reported"
----------------------------------------------------------------------------------

I have other projects on the same system in other folders that run just fine. The most recent one uses provider.aws: version = "-> 2.27"

I am running this on a Fedora 30 system. and I am using: terraform_0.12.9_linux_amd64.zip

Please let me know if you need anything else.

Thanks

**Comment by KwyjibojonesJr** [comment]
Hi again, I just found out about this: export TF_LOG=TRACE
So here is some more data.

$ terraform init
2019/10/04 13:56:24 [INFO] Terraform version: 0.12.9  
2019/10/04 13:56:24 [INFO] Go runtime version: go1.12.9
2019/10/04 13:56:24 [INFO] CLI args: []string{"/home/kjones/bin/terraform", "init"}
2019/10/04 13:56:24 [DEBUG] Attempting to open CLI config file: /home/kjones/.terraformrc
2019/10/04 13:56:24 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/10/04 13:56:24 [INFO] CLI command args: []string{"init"}

Initializing the backend...
2019/10/04 13:56:24 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2019/10/04 13:56:24 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2019/10/04 13:56:24 [DEBUG] New state was assigned lineage "0b1b94be-6bf8-1d7f-9357-aa8a7a5103e1"
2019/10/04 13:56:24 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2019/10/04 13:56:24 [TRACE] Meta.Backend: instantiated backend of type <nil>
2019/10/04 13:56:24 [DEBUG] checking for provider in "."
2019/10/04 13:56:24 [DEBUG] checking for provider in "/home/kjones/bin"
2019/10/04 13:56:24 [DEBUG] checking for provisioner in "."
2019/10/04 13:56:24 [DEBUG] checking for provisioner in "/home/kjones/bin"
2019/10/04 13:56:24 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2019/10/04 13:56:24 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2019/10/04 13:56:24 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2019/10/04 13:56:24 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2019/10/04 13:56:24 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2019/10/04 13:56:24 [TRACE] statemgr.Filesystem: read nil snapshot
2019/10/04 13:56:24 [DEBUG] checking for provider in "."
2019/10/04 13:56:24 [DEBUG] checking for provider in "/home/kjones/bin"
2019/10/04 13:56:24 [DEBUG] plugin requirements: "aws"=""
2019/10/04 13:56:24 [DEBUG] plugin requirements: "AWS"=""

2019/10/04 13:56:24 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2019/10/04 13:56:24 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
Initializing provider plugins...
- Checking for available provider plugins...
2019/10/04 13:56:25 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/aws/versions"
2019/10/04 13:56:25 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/aws/versions
2019/10/04 13:56:25 [DEBUG] fetching provider location from "https://registry.terraform.io/v1/providers/hashicorp/aws/2.31.0/download/linux/amd64"
2019/10/04 13:56:25 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/2.31.0/download/linux/amd64
2019/10/04 13:56:25 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_SHA256SUMS
2019/10/04 13:56:25 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_SHA256SUMS.sig
2019/10/04 13:56:25 [DEBUG] verified GPG signature with key from HashiCorp Security <security@hashicorp.com>
2019/10/04 13:56:25 [DEBUG] getting provider "aws" (hashicorp/aws) version "2.31.0"
2019/10/04 13:56:25 [DEBUG] plugin cache is disabled, so downloading aws 2.31.0 from https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip?checksum=sha256:99f45732dc7525b95707cde996881bd8565ea520db4161193e06d605c3230c71
- Downloading plugin for provider "aws" (hashicorp/aws) 2.31.0...
2019/10/04 13:56:25 [TRACE] HTTP client HEAD request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip
2019/10/04 13:56:25 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip
2019/10/04 13:56:27 [DEBUG] looking for the aws 2.31.0 plugin we just installed
2019/10/04 13:56:27 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/10/04 13:56:27 [DEBUG] found provider "terraform-provider-aws_v2.31.0_x4"
2019/10/04 13:56:27 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws", Version:"2.31.0", Path:"/home/kjones/WorkCodez/terraformedu/tfur/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.31.0_x4"}:struct {}{}}
2019/10/04 13:56:27 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws", Version:"2.31.0", Path:"/home/kjones/WorkCodez/terraformedu/tfur/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.31.0_x4"}:struct {}{}}
2019/10/04 13:56:27 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/AWS/versions"
2019/10/04 13:56:27 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/AWS/versions
2019/10/04 13:56:27 [DEBUG] fetching provider location from "https://registry.terraform.io/v1/providers/hashicorp/aws/2.31.0/download/linux/amd64"
2019/10/04 13:56:27 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/aws/2.31.0/download/linux/amd64
2019/10/04 13:56:28 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_SHA256SUMS
2019/10/04 13:56:28 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_SHA256SUMS.sig
2019/10/04 13:56:28 [DEBUG] verified GPG signature with key from HashiCorp Security <security@hashicorp.com>
2019/10/04 13:56:28 [DEBUG] getting provider "AWS" (hashicorp/aws) version "2.31.0"
2019/10/04 13:56:28 [DEBUG] plugin cache is disabled, so downloading AWS 2.31.0 from https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip?checksum=sha256:99f45732dc7525b95707cde996881bd8565ea520db4161193e06d605c3230c71
- Downloading plugin for provider "AWS" (hashicorp/aws) 2.31.0...
2019/10/04 13:56:28 [TRACE] HTTP client HEAD request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip
2019/10/04 13:56:28 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip
2019/10/04 13:56:29 [DEBUG] looking for the AWS 2.31.0 plugin we just installed
2019/10/04 13:56:29 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/10/04 13:56:29 [DEBUG] found provider "terraform-provider-aws_v2.31.0_x4"
2019/10/04 13:56:29 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws", Version:"2.31.0", Path:"/home/kjones/WorkCodez/terraformedu/tfur/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.31.0_x4"}:struct {}{}}
2019/10/04 13:56:29 [DEBUG] filtered plugins discovery.PluginMetaSet{}

Error installing provider "AWS": failed to find installed plugin version 2.31.0; this is a bug in Terraform and should be reported.

**Comment by bflad** [comment]
Hi @KwyjibojonesJr 👋 Thank you for reporting this and sorry you are running into trouble.

The reason for the failure within Terraform's automatic plugin installation does not appear to be too obvious at first glance given the provided trace logs:

```
Downloading plugin for provider "AWS" (hashicorp/aws) 2.31.0...
2019/10/04 13:56:28 [TRACE] HTTP client HEAD request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip
2019/10/04 13:56:28 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.31.0/terraform-provider-aws_2.31.0_linux_amd64.zip
2019/10/04 13:56:29 [DEBUG] looking for the AWS 2.31.0 plugin we just installed
2019/10/04 13:56:29 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/10/04 13:56:29 [DEBUG] found provider "terraform-provider-aws_v2.31.0_x4"
2019/10/04 13:56:29 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws", Version:"2.31.0", Path:"/home/kjones/WorkCodez/terraformedu/tfur/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.31.0_x4"}:struct {}{}}
2019/10/04 13:56:29 [DEBUG] filtered plugins discovery.PluginMetaSet{}

Error installing provider "AWS": failed to find installed plugin version 2.31.0; this is a bug in Terraform and should be reported.
```

This certainly is unexpected behavior where it appears to have downloaded the provider, found its location within your local Terraform configuration directory, but reports back a failure to install. You may want to verify that the zip file extracted properly into `/home/kjones/WorkCodez/terraformedu/tfur/.terraform/plugins/linux_amd64/`.

The code that manages the Terraform plugin discovery and installation does not live within this codebase, but is instead managed by the Terraform CLI code that lives upstream at https://github.com/hashicorp/terraform so the installation can be consistent across all Terraform providers. Since this issue is currently in the `terraform-providers` GitHub organization and not `hashicorp`, I cannot automatically transfer this GitHub issue myself to the correct repository, but if you could, please submit this bug report upstream ( https://github.com/hashicorp/terraform/issues/new?template=bug_report.md) where the team that manages this code can appropriately look into the issue and help you.
