### ISSUE TITLE
Request for aws_cloudfront_distribution Data Resource

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#10398]
I've created a aws_cloudfront_distribution resource in a separate project and separate account. I would like to be able to lookup the DomainName for this resource using the data resource.

using aws cli, I would use this https://docs.aws.amazon.com/cli/latest/reference/cloudfront/get-distribution.html

I would first run:

`aws cloudfront list-distributions` to look the distribution id, then:

`aws cloudfront get-distribution --id S11A16G5KZMEQD`

**Comment by bflad** [comment]
Hi @e-moshaya 👋 Thank you for submitting this. This appears to be a similar request to https://github.com/terraform-providers/terraform-provider-aws/issues/6586, so to consolidate efforts and discussions, I'm going to close this issue in preference of the earlier one.
