### ISSUE TITLE
Add CloudWatch Events EventBuses

### ISSUE THREAD

**Issue by ayashjorden** [terraform-providers/terraform-provider-aws#1042]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.7

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudwatch_events_eventbuses - doesn't exist yet.

### Expected Behavior
Add support for CloudWatch Events Event-Buses

### Actual Behavior
Not supported yet

### Important Factoids
EventBus related AWS CLI sub-commands are available only from version 1.11.114, make sure this version is installed by using: pip install -U 'awscli>=1.11.114'

### References
- [AWS CLI Events](http://docs.aws.amazon.com/cli/latest/reference/events/index.html#cli-aws-events)

**Comment by agarstang** [comment]
The CLI (as per your link) and GO SDK (as per [here](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchevents/)) only appear to support describing Event Buses at the moment :(

**Comment by JoshiiSinfield** [comment]
Hi,
We'd be interested in this feature.

The SDK has a "PutPermission" operation allowing programmatic addition of permissions for another account to send events to the event bus therefore a resource to add permissions would be great.

A data source to retrieve the ARN of the default event bus as the CLI does:
aws events describe-event-bus
{
    "Name": "default", 
    "Arn": "arn:aws:events:eu-west-1:*********:event-bus/default"
}

although that ARN could be stored in a variable I'd rather look it up from a data source.

Cheers,
Josh

**Comment by kamusin** [comment]
+1 to this feature as well

**Comment by laurence-hubbard** [comment]
+1

**Comment by smastrorocco** [comment]
+1

**Comment by walterheck** [comment]
Would be very happy to see this as it's the recommended way to get events to work between AWS accounts: http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEvents-CrossAccountEventDelivery.html

**Comment by bflad** [comment]
Hi folks, I have submitted a PR for a new `aws_cloudwatch_event_permission` resource, which will let you add cross-account permissions (`*` or individual account numbers): #2888

If you're interested in a CloudWatch Events default bus data source (these exist in accounts automatically), I'd suggest creating an issue specifically for it.

A friendly reminder: the best way to get attention on an issue from the maintainers is using 👍  reactions on the original issue. 😄

**Comment by bflad** [comment]
The `aws_cloudwatch_event_permission` resource has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
