### ISSUE TITLE
Support "Require https" on elasticsearch

### ISSUE THREAD

**Issue by alexisde** [terraform-providers/terraform-provider-aws#10424]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

AWS announced support for https required on elasticsearch domains, Would it be possible to implement?

https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-elasticsearch-service-provides-option-to-mandate-https/?ck_subscriber_id=512831964

Add `require_https` argument to elasticsearch resources

* aws_elasticsearch

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "example" {
  domain_name           = "example"
  elasticsearch_version = "1.5"
  require_https = true

  cluster_config {
    instance_type = "r4.large.elasticsearch"
  }

  snapshot_options {
    automated_snapshot_start_hour = 23
  }

  tags = {
    Domain = "TestDomain"
  }
}
```

### References

* #0000

**Comment by bflad** [comment]
Support for this functionality in the `aws_elasticsearch_domain` resource has been added via a new `domain_endpoint_options` configuration block:

```hcl
resource "aws_elasticsearch_domain" "example" {
  # ... other configuration ...

  domain_endpoint_options {
    enforce_https = true
  }
}
```

And will release with version 2.47.0 of the Terraform AWS Provider, tomorrow. Thanks to @barrytam20 for the implementation. 👍
