### ISSUE TITLE
slow down calls to aws_autoscaling_group to not hit API rate limit

### ISSUE THREAD

**Issue by FernandoMiguel** [terraform-providers/terraform-provider-aws#10438]
### Description

when using aws_autoscaling_group with a large number of target_group_arns, we hit aws api rate limit.
Would like to request for the api calls be throttled to be within the limits

### New or Affected Resource(s)

aws_autoscaling_group.target_group_arns

### error message

```
Trying to update too many Load Balancers/Target Groups at once. The limit is 10
```

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/256

**Comment by bflad** [comment]
Hi @FernandoMiguel 👋 Thanks for submitting this and sorry you are running into trouble. This appears to fall under the same underlying issue as #256 which has the associated pull request #10435. I just left a code review for that pull request which ensures that this error does not occur. To consolidate efforts and discussions, I'm going to close this issue in preference of #256 and #10435. 👍
