### ISSUE TITLE
 Client VPN Endpoint - Create Client Route

### ISSUE THREAD

**Issue by nijave** [terraform-providers/terraform-provider-aws#10437]
### Description
Like https://github.com/terraform-providers/terraform-provider-aws/issues/7494, it looks like this is also missing. This is needed to update the Client VPN routing table

### New or Affected Resource(s)
aws_ec2_client_vpn_route

### Potential Terraform Configuration
https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.CreateClientVpnRoute

```hcl
resource "aws_ec2_client_vpn_route" "route" {
  client_vpn_endpoint_id = ""
  destination_cidr_block = ""
  target_vpc_subnet_id = ""

  description = "optional description"
}
```

### References
https://docs.aws.amazon.com/cli/latest/reference/ec2/create-client-vpn-route.html

**Comment by RickyRajinder** [comment]
Hi, could I possibly submit a PR for this?

**Comment by ben-poole** [comment]
Workaround:
```
resource "null_resource" "client_vpn_route" {
  provisioner "local-exec" {
    when = "create"
    command = "aws ec2 create-client-vpn-route --client-vpn-endpoint-id ${aws_ec2_client_vpn_endpoint.client_vpn.id} --destination-cidr-block 0.0.0.0/0 --target-vpc-subnet-id ${var.subnet_id}"
  }
  provisioner "local-exec" {
    when = "destroy"
    command = "aws ec2  delete-client-vpn-route --client-vpn-endpoint-id ${aws_ec2_client_vpn_endpoint.client_vpn.id} --destination-cidr-block 0.0.0.0/0"
  }
}
```

**Comment by Cryptophobia** [comment]
Any update on when a solution for this issue will be merged in to the main "aws_ec2_client_vpn_endpoint" resource? 

I see every few days someone makes a PR to address this issue.
