### ISSUE TITLE
Add data provider for aws_waf_rate_based_rule and aws_wafregional_rate_based_rule

### ISSUE THREAD

**Issue by philippmoehler0440** [terraform-providers/terraform-provider-aws#10449]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently aws waf (regional) rate based rules are only available as resource. It would be helpful to have a data provider for those, too.

### New or Affected Resource(s)

* data aws_waf_rate_based_rule
* data aws_wafregional_rate_based_rule

### Potential Terraform Configuration

```hcl
data "aws_waf_rate_based_rule" "myrule" {
  name = "myRule"
}

data "aws_wafregional_rate_based_rule" "myrule" {
  name = "myRule"
}

```

### References

* none found

**Comment by bflad** [comment]
Hi folks 👋 Good news! These two new data sources were just merged today and will release with version 2.33.0 of the Terraform AWS Provider, on Thursday. 👍
