### ISSUE TITLE
Generated identifiers for DocumentDB with identifier_prefix are too long

### ISSUE THREAD

**Issue by limitusus** [terraform-providers/terraform-provider-aws#10468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With `cluster_identifier_prefix` and `identifier_prefix`, auto-generated cluster and instance name is too long(max 100 chars, which may not be documented yet) to specify in AWS DMS for a target endpoint.

![image](https://user-images.githubusercontent.com/133476/66629433-b297da80-ec3c-11e9-81df-816923e8bd02.png)

`xxxxxxxxx-xxxxxxxx-20191009094106591600000001.cluster-yyyyyyyyyyyy.ap-northeast-1.docdb.amazonaws.com` (101 chars)

I believe it's OK for RDS as the domain name ends with `rds.amazonaws.com`, but for DocDB, `docdb.amazonaws.com` is longer by 2 chars.
An idea is just shorten the auto-generated cluster/instance name with `cluster_identifier_prefix` and `identifier_prefix`.
Looks it's defined in [resources](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/resource/id.go#L24), so maybe that should be modified a bit.

### New or Affected Resource(s)

* aws_docdb_cluster
* aws_docdb_cluster_instance

### Potential Terraform Configuration

```hcl
resource "aws_docdb_cluster" "cluster" {
  cluster_identifier_prefix = "xxxxxxxxx-xxxxxxxx-"
  engine                    = "docdb"
  engine_version = "3.6.0"
  ...
}

resource "aws_docdb_cluster_instance" "cluster" {
  count = 3
  identifier_prefix  = "xxxxxxxxx-xxxxxxxx-"
  cluster_identifier = aws_docdb_cluster.cluster.id
  ...
}
```

### References

* N/A

**Comment by nywilken** [comment]
@limitusus thanks for opening up this issue. I agree that we should look to modify the auto-generated prefix a bit, but I don't think changing the `const` might be the way to go. Since the length of a prefix may vary upon the resource under configuration, as you said it just so happens to work for `RDS`. I don't have a solution just yet other than having a local function within the resource to shorten the generated ID as we know the max length for DocDB identifiers.
