### ISSUE TITLE
aws_rds_cluster_instance should support ca_cert_identifier

### ISSUE THREAD

**Issue by goosmurf** [terraform-providers/terraform-provider-aws#10467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_rds_cluster_instance` should support `ca_cert_identifier` like `aws_db_instance`.

Without this it is impossible to update to the new [rds-ca-2019 bundle](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html) via Terraform.

### New or Affected Resource(s)

* aws_rds_cluster_instance

**Comment by ldormoy** [comment]
BTW this also affects the aws_db_instance resource

**Comment by sunilkumarmohanty** [comment]
It seems the golang sdk does not have this support yet. However, db_instance has the support.
