### ISSUE TITLE
aws_db_instance should support ca_cert_identifier

### ISSUE THREAD

**Issue by sunilkumarmohanty** [terraform-providers/terraform-provider-aws#10489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_db_instance

### Potential Terraform Configuration

```hcl

resource "aws_db_instance" "test" {

	ca_cert_identifier = "rds-ca-2019"
        ...
}
```

### References

* #10467

**Comment by bflad** [comment]
Support for the new `ca_cert_identifier` argument in the `aws_db_instance` resource has been merged and will release in version 2.37.0 of the Terraform AWS Provider by Thursday next week. Thanks to @sunilkumarmohanty for the implementation. 👍
