### ISSUE TITLE
Request to combine Datasource and Resource listing in documentation

### ISSUE THREAD

**Issue by prashant-ee** [terraform-providers/terraform-provider-aws#10499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Request to combine the data source of a resource and details of the resource as once in the document. This should allow everyone to find all the details in one place. 

Currently to get the details of the resource one has to jump around the documentation to get the details. 

This will be similar to what we have currently for importing the resource. That information is along with the resource details itself. 

### New or Affected Resource(s)

This will affect only the documentation. The documentation for all the resources will be affected because of this.

**Comment by ryndaniels** [comment]
Hi @prashant-ee - thanks for taking the time to open this issue. We've actually found that having the documentation separate for resources and data sources is what makes the most sense for this project, as well as maintaining consistency with the way documentation is arranged for the other providers, so we're going to go ahead and leave it as is. 🙂
