### ISSUE TITLE
aws_ssm_document: add targettype as a supported input

### ISSUE THREAD

**Issue by aidancasey1** [terraform-providers/terraform-provider-aws#10540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When I create Run Documents using terraform, I'm unable to set the Target Type. 
: invalid or unknown key: targettype
The official AWS Automation docuements use the following 
"TargetType": "/AWS::EC2::Instance", 

### New or Affected Resource(s)

*aws_ssm_document
Resource: aws_ssm_document

### Potential Terraform Configuration

resource "aws_ssm_document" "automation-document" {
  name                  = "test-"automation-document"
  document_type = "Automation"
  **targettype          = "/AWS::EC2::Instance"**
  content = {} 

### References

* #0000

**Comment by bflad** [comment]
Support for the `aws_ssm_document` resource `target_type` argument has been merged and will release with version 2.47.0 of the Terraform AWS Provider, tomorrow. Thanks to @DrFaust92 for the implementation. 👍
