### ISSUE TITLE
Amazon MSK cluster expansion

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon MSK clusters can now be expanded, i.e. the broker count can be updated.

### New or Affected Resource(s)

* [`aws_msk_cluster`](https://www.terraform.io/docs/providers/aws/r/msk_cluster.html)

### Potential Terraform Configuration

```hcl
n/a
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/10/now-expand-your-amazon-msk-clusters-and-deploy-new-clusters-across-2-azs/).
[Guide](https://docs.aws.amazon.com/msk/latest/developerguide/msk-update-broker-count.html).

Requires [AWS SDK v1.25.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.14):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10476

**Comment by eddwardo** [comment]
Documented here:
https://docs.aws.amazon.com/msk/latest/developerguide/msk-update-broker-count.html

Implemented here:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_msk_cluster.go#L350

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.51.0 of the Terraform AWS Provider, end of next week. Thanks to @marcoreni for the implementation. 👍
