### ISSUE TITLE
The provider provider.aws does not support data source "aws_cloudwatch_event_rule".

### ISSUE THREAD

**Issue by Nikita-Kumar** [terraform-providers/terraform-provider-aws#10595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.12
+ provider.aws v2.33.0

### Affected Resource(s)

* aws_cloudwatch_event_rule

### Terraform Configuration Files

```hcl
variable "env_name" {}

data "aws_cloudwatch_event_rule" "CW_Trigger" {
  name = "cw-trigger-${lower(var.env_name)}"
}
```

### Debug Output
Invalid data source
The provider provider.aws does not support data source
"aws_cloudwatch_event_rule".

### Expected Behavior

The script should have been able to fetch details of the data source.

### Actual Behavior

It failed

### Steps to Reproduce

1. `Fill in the variable`
2. `terraform apply`

**Comment by tomelliff** [comment]
Hi @Nikita-Kumar. Was this meant to be a feature request? There isn't yet an `aws_cloudwatch_event_rule` data source. If so, what's your wider use case here? Is there a reason you need the `arn` or some other attribute of the event rule in a different context to when you are creating the rule?

**Comment by Nikita-Kumar** [comment]
@tomelliff Yes this was meant to be a feature request. I need to use the ARN for the `aws_cloudwatch_event_rule` because of some complexities in the project where I can't use it in the same terraform script where it was created. I have managed to workaround this but it would have been useful to have a data source for this.

**Comment by tomelliff** [comment]
Where do you need the ARN? The `aws_cloudwatch_event_target` just takes the name of the rule, not the ARN but I'm not sure where else you'd need to use the output from the rule creation.

**Comment by ryndaniels** [comment]
@Nikita-Kumar thanks for taking the time to open this. Could you please provide a bit more detail about the use case you would need this for, so the team can determine if that's something that makes sense to implement? Thanks!

**Comment by bflad** [comment]
Closing due to lack of response. If you wish to still submit a feature request, please create a new issue providing the use case or potential Terraform configuration and we will take a fresh look. Thanks.
