### ISSUE TITLE
Provide IPv6 address attributes on aws_instance and aws_network_interface

### ISSUE THREAD

**Issue by msnelling** [terraform-providers/terraform-provider-aws#1060]
Currently there is no way that I can see of retrieving the assigned IPv6 address(es) to aws_instance and aws_network_interface resources.

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_network_interface

**Comment by foxx** [comment]
Any idea when support for this will be added? Kinda crucial feature for adopting IPv6 in AWS.

**Comment by michan49** [comment]
Is there any plans of having this in the near future?
