### ISSUE TITLE
aws_kinesis_firehose_delivery_stream to support ClusterEndpoint for ElasticSearch

### ISSUE THREAD

**Issue by developerinlondon** [terraform-providers/terraform-provider-aws#10623]
Currently terraform only supports creating a kinesis firehose delivery stream by specifying an elasticsearch domainARN, but for cross-account elasticsearch (released on October 8th, 2019) we need support for passing the ClusterEndpoint as described in the AWS documentation and API here:
https://docs.aws.amazon.com/firehose/latest/dev/controlling-access.html#cross-account-delivery-es (look at point 3)
https://docs.aws.amazon.com/firehose/latest/dev/controlling-access.html#using-iam-es
https://docs.aws.amazon.com/cli/latest/reference/firehose/create-delivery-stream.html
(api call supports clusterEndpoint however terraform does not it seems)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Support for this new functionality (`elasticsearch_configuration` configuration block `cluster_endpoint` argument in the `aws_kinesis_firehose_delivery_stream` resource) has been merged and will release with version 3.5.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
