### ISSUE TITLE
status attribute in accounts/non_master_accounts attribute in aws_organizations_organization resource/datasource

### ISSUE THREAD

**Issue by felixculpaq** [terraform-providers/terraform-provider-aws#10646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
 Currently, in Terraform there can be a quite useful **aws_organizations_organization** resource/datasource for a getting dynamic list for accounts of aws organization. But in a practice, every company have a lot of **SUSPENDED** accounts, that don't need any actions and existence in a list of aws accounts. The current realization of **aws_organizations_organization** datasource can't allow us to filter active accounts and suspended accounts because don't give us a **status** attribute of every account in an organization. I'm pretty sure that adding **status** attribute will be increasing value of **aws_organizations_organization** datasource. 

### New or Affected Resource(s)

* aws_organizations_organization resource/datasource

### Potential Terraform Configuration

```hcl
data "aws_organizations_organization" "example" {
}

output "org_accounts_statuses" {
  value = { for account in data.aws_organizations_organization.example.accounts : account.name => account.status }
}

```

### References

* Related pull request is ready and here:
 [#10647](https://github.com/terraform-providers/terraform-provider-aws/pull/10647)

**Comment by bflad** [comment]
Support for this new attribute in the `aws_organizations_organization` resource and datasource has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week. Thanks to @felixculpaq for the implementation. 👍
