### ISSUE TITLE
data aws_lb cannot find a load balancer by name

### ISSUE THREAD

**Issue by jglapa** [terraform-providers/terraform-provider-aws#10669]
### Terraform Version

Terraform v0.12.12
+ provider.aws v2.33.0

### Affected Resource(s)

* aws_lb data source

### Terraform Configuration Files

```hcl

provider "aws" {
  region = "eu-west-1"
}

data "aws_lb" "my-lb" {
   name = "foobar-terraform-elb"
}
```

### Debug Output

https://gist.github.com/jglapa/99f5a0d9358480e27dd983149f91684f

### Expected Behavior

load balancer should be found

### Actual Behavior

```
Error: Error retrieving LB: LoadBalancerNotFound: Load balancers '[foobar-terraform-elb]' not found
	status code: 400, request id: fd8a1fed-b7c1-4eee-973c-539b3daed354

  on test.tf line 28, in data "aws_lb" "my-lb":
  28: data "aws_lb" "my-lb" {


```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

the load balancer with the given name exists ( it was created from the example here: https://www.terraform.io/docs/providers/aws/r/elb.html)

```
aws elb describe-load-balancers | jq '.LoadBalancerDescriptions[].LoadBalancerName'
"awseb-e-u-AWSEBLoa-ZLUHO08ONCDP"
"awseb-e-s-AWSEBLoa-FMJMGD7SHN80"
"awseb-e-s-AWSEBLoa-6S23NX79VB1P"
"foobar-terraform-elb"
```

Debug output also shows the given resources is there.

**Comment by asmontas-i** [comment]
"aws_lb" data source is for ALB and NLB only. For classic load balancer you should use "aws_elb" data source.

**Comment by jglapa** [comment]
> "aws_lb" data source is for ALB and NLB only. For classic load balancer you should use "aws_elb" data source.

You are absolutely right! using `aws_elb` did the job . 
Thanks @asmontas-i
