### ISSUE TITLE
AWS Storage Gateway - add support for Gateway Log Group

### ISSUE THREAD

**Issue by pintbrewer** [terraform-providers/terraform-provider-aws#10681]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Storage Gateway - Gateway now accepts a Cloudwatch Log Group. 
The provider Resource: aws_storagegateway_gateway should take an Argument for gateway_log_group as either the name or arn of a Cloudwatch Log Group.
The default configuration in the console is "diabled"

### New or Affected Resource(s)

* aws_storagegateway_gateway

### Potential Terraform Configuration

```hcl
resource "aws_storagegateway_gateway" "example" {
  gateway_ip_address = "1.2.3.4"
  gateway_name       = "example"
  gateway_timezone   = "GMT"
  gateway_type       = "FILE_S3"
  gateway_log_group = "my_log_group_name"
}.
```

### References

* https://docs.aws.amazon.com/storagegateway/latest/userguide/DocumentHistory.html

Support for Amazon CloudWatch Logs | You can now configure file gateways with Amazon CloudWatch Log Groups to get notified about errors and the health of your gateway and its resources. For more information, see Getting Notified About Gateway Health and Errors With Amazon CloudWatch Log Groups in the AWS Storage Gateway User Guide. | September 4, 2019
-- | -- | --

**Comment by bflad** [comment]
Support for this functionality via a new `cloudwatch_log_group_arn` argument has been merged and will release with version 2.47.0 of the Terraform AWS Provider, tomorrow. Thanks to @DrFaust92 for the implementation. 👍
