### ISSUE TITLE
import aws_directory_service_directory doesn't import connect_settings

### ISSUE THREAD

**Issue by wjrogers** [terraform-providers/terraform-provider-aws#10716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.13
+ provider.aws v2.34.0
+ provider.http v1.1.1
+ provider.null v2.1.2

### Affected Resource(s)

* aws_directory_service_directory

### Terraform Configuration Files

```hcl
resource "aws_directory_service_directory" "corp" {
  type = "ADConnector"
  size = "Small"
  name = "CORP.local"
  short_name = "CORP"
  description = "CORP"
  password = "secret"

  connect_settings {
    customer_username = "aws"
    customer_dns_ips = [
      "10.1.1.1",
      "10.2.1.1",
    ]
    subnet_ids = [
      "subnet-1",
      "subnet-2",
    ]
    vpc_id = "vpc-1"
  }

  tags = {}
}
```

### Expected Behavior

`terraform import` adds all attributes of the directory -- including `connect_settings` -- to the terraform state. Subsequent plans do not modify the AWS resource.

### Actual Behavior

After `import`, the `connect_settings` attribute is missing from the state, and subsequent plans _replace_ the resource. Output of `terraform state show`:

```hcl
resource "aws_directory_service_directory" "corp" {
    access_url        = "d-redacted.awsapps.com"
    alias             = "d-redacted"
    description       = "CORP"
    dns_ip_addresses  = [
        "10.3.1.1",
        "10.3.2.1",
    ]
    enable_sso        = false
    id                = "d-redacted"
    name              = "CORP.local"
    security_group_id = "sg-0"
    short_name        = "CORP"
    size              = "Small"
    tags              = {}
    type              = "ADConnector"
}
```

Output of `terraform plan`:

```txt
  # aws_directory_service_directory.corp must be replaced
-/+ resource "aws_directory_service_directory" "corp" {
      # ...

      + connect_settings { # forces replacement
          + customer_dns_ips  = [
              + "10.1.1.1",
              + "10.2.1.1",
            ] # forces replacement
          + customer_username = "aws" # forces replacement
          + subnet_ids        = [
              + "subnet-1",
              + "subnet-2",
            ] # forces replacement
          + vpc_id            = "vpc-1" # forces replacement
        }
    }
```

### Steps to Reproduce

1. Create an AWS Directory Service AD Connector manually in the AWS console.
1. Write a terraform configuration that describes the resource e.g. as above.
1. `terraform import aws_directory_service_directory.corp d-redacted`
1. `terraform plan`

**Comment by erighi** [comment]
Hello, 
I am trying to import my aws ms ad and I have the same issue

**Comment by DrFaust92** [comment]
i opened a PR to address this, the issue stems from trying to set a non existent `connect_ips` attribute and swallowing the error.

**Comment by wjrogers** [comment]
I just noticed that the provider also cannot detect changes to `customer_dns_ips` in an existing directory resource. When I manually change the "Existing DNS addresses" in the AWS Console then modify the Terraform configuration to match, Terraform always wants to destroy and re-create the directory, even though in reality there is no drift. Is this the same bug? Seems plausible that import and refreshing of state would use the same code path.

**Comment by DrFaust92** [comment]
I believe its the same issue because it just failed silently before when setting state. i saw it fail after adding error handling. `customer_dns_ips` was set in the same place i changed
