### ISSUE TITLE
Cloudwatch Dashboard Support

### ISSUE THREAD

**Issue by cfbarbero** [terraform-providers/terraform-provider-aws#1072]
AWS CLI now supports [CloudWatch Dashboards](https://aws.amazon.com/blogs/aws/new-api-cloudformation-support-for-amazon-cloudwatch-dashboards/).

We use cloudwatch dashboards extensively and would love to manage them with TF along with the rest of our AWS infrastructure.

**Comment by Ninir** [comment]
Hey folks,
Just to let you know that the [CloudWatch dashboard resource](https://github.com/terraform-providers/terraform-provider-aws/pull/1172) was just merged.

Happy Terraforming!

**Comment by nwalke** [comment]
@Ninir Are docs coming later for this?

**Comment by Ninir** [comment]
Hey @nwalke 

Just pushed a PR for that. Thanks for noticing!

**Comment by brightskylee** [comment]
When will this 0.1.4 version be released?
