### ISSUE TITLE
Amazon S3 Inventory now reports the Intelligent-tiering access tier for objects

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10743]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon S3 Inventory now reports the Intelligent-tiering access tier for objects.

### New or Affected Resource(s)

* [`aws_s3_bucket_inventory`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_inventory.html)

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_inventory" "test" {
  bucket = "${aws_s3_bucket.test.id}"

  optional_fields = ["IntelligentTieringAccessTier"]
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-s3-inventory-now-reports-the-intelligent-tiering-access-tier-for-objects/).

Requires [AWS SDK v1.25.24](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.24):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10686

**Comment by bflad** [comment]
Support for this new value in the validation has been merged and will release with version 2.37.0 of the Terraform AWS Provider, by Thursday next week. Thanks to @ewbankkit for the implementation. 👍
