### ISSUE TITLE
Amazon Elastic File System Infrequent Access Now Supports a 7-day Lifecycle Management Policy

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Elastic File System Infrequent Access now supports a 7-day lifecycle management policy.

### New or Affected Resource(s)

* [`aws_efs_file_system`](https://www.terraform.io/docs/providers/aws/r/efs_file_system.html)

### Potential Terraform Configuration

```hcl
resource "aws_efs_file_system" "example" {
  lifecycle_policy {
    transition_to_ia = "AFTER_7_DAYS"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-elastic-file-system-infrequent-access-now-supports-7-day-lifecycle-management-policy/).

Requires [AWS SDK v1.25.28](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.28):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10717

**Comment by bflad** [comment]
Support for this new value in the validation has been merged and will release with version 2.37.0 of the Terraform AWS Provider, by Thursday next week. Thanks to @ewbankkit for the implementation. 👍
