### ISSUE TITLE
can't remove ipv6_cidr_block from aws_subnet

### ISSUE THREAD

**Issue by dmrzzz** [terraform-providers/terraform-provider-aws#10815]
Removing a previously-applied `ipv6_cidr_block` parameter from `aws_subnet` does not produce the expected behavior of removing the IPv6 CIDR.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.13
+ provider.aws v2.35.0
```

### Affected Resource(s)

* aws_subnet

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "vpc" {
  cidr_block = "192.168.0.0/24"
  assign_generated_ipv6_cidr_block = true
}

resource "aws_subnet" "subnet" {
  vpc_id          = aws_vpc.vpc.id
  cidr_block      = "192.168.0.0/26"
  #ipv6_cidr_block = cidrsubnet(aws_vpc.vpc.ipv6_cidr_block, 8, 0)
}

output "subnet" {
  value = aws_subnet.subnet
}
```

### Steps to Reproduce

1. `terraform apply`

   creates the VPC (with IPv6) and subnet (IPv4-only), as expected

2. Uncomment the `ipv6_cidr_block` line

3. `terraform apply`

   updates the subnet in-place to add ipv6_cidr_block, as expected

4. Re-comment the `ipv6_cidr_block` line

5. `terraform apply`

   Expected: should update the subnet to remove ipv6_cidr_block
   Actual: apply completes immediately with no changes, and my subnet still has IPv6

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 3.3.0 of the Terraform AWS Provider, shortly. Thanks to @DrFaust92 for the implementation. 👍
