### ISSUE TITLE
error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid

### ISSUE THREAD

**Issue by raolivei** [terraform-providers/terraform-provider-aws#10840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Summary

I have created a module to dynamically enable GuardDuty in the region specified in the module instantiation. This very same code works fine in another AWS account when I `terraform plan`. 
But, for this specific environment, It will only work if I limit the execution to a single module every time – e.g.:`terraform plan -target=module.guardduty.module.guardduty_detector_us_east_1`

### Terraform Version

Terraform v0.12.12
+ provider.archive v1.3.0
+ provider.aws v2.35.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

Anything AWS - the issue is with the provider authentication

### Terraform Configuration Files

Where `providers.tf` contains:
```hcl
module "guardduty_detector_us_east_1" {
  environment = var.environment
  source      = "./guardduty"
  region      = "us-east-1"
  is_master   = "${var.is_master}"
}

module "guardduty_detector_us_east_2" {
  environment = var.environment
  source      = "./guardduty"
  region      = "us-east-2"
}

module "guardduty_detector_us_west_1" {
  environment = var.environment
  source      = "./guardduty"
  region      = "us-west-1"
}

module "guardduty_detector_us_west_2" {
  environment = var.environment
  source      = "./guardduty"
  region      = "us-west-2"
}
```
Where `interface.tf` contains:
```hcl
variable "environment" {
  type        = "string"
  default     = "org"
}
```
Where `./guardduty/main.tf` contains:
```hcl
provider "aws" {
  region = var.region
  alias  = "guardduty_dynamic_region"
}

resource "aws_guardduty_detector" "guardduty_detector" {
  provider = "aws.guardduty_dynamic_region"
  enable   = true
}
```
Where `./guardduty/interface.tf` contains:
```hcl
variable "environment" {
  type        = "string"
  description = "The name of the environment"
}

variable "region" {
  type        = string
  description = "List of regions to enable GuardDuty."
}
```

### Debug Output

https://gist.github.com/raolivei/e21b639101e6b85f09c4a156a8a28281.js

### Expected Behavior

`terraform plan` should work regardless if filtered by the target.

### Actual Behavior

```
Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid
        status code: 403, request id: 7e5d9e70-04ce-11ea-9b6d-8f4a48871b2f

  on ../modules/monitoring/guardduty_detector/guardduty/main.tf line 1, in provider "aws":
   1: provider "aws" {
```
### Steps to Reproduce

I am not using AWS ACCESS KEYS. Instead:

1. Configure `aws-vault` in your environment properly.

2. `terraform apply`

### References

I have looked into quite a few similar issues but none have the same config and the resolutions haven't worked for me.

**Comment by gdavison** [comment]
Hi @raolivei. Thanks for taking the time to submit this issue.

Please take a look at https://www.terraform.io/docs/configuration/modules.html#providers-within-modules. Defining the `provider` block in the module can often cause issues similar to this.

I'm going to close the issue, but if the issue still happens after moving the `provider` blocks to the root, please [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md)

**Comment by raolivei** [comment]
I just want to clarify that my TF configuration was right. The issue was with the Hong-Kong region being deactivated in my AWS account.
Enabling the region fixed the issue.

**Comment by ambusv** [comment]
@raolivei - You are correct. I have same issue which resolved by enable the region
