### ISSUE TITLE
Option to output container definition diff against previous task definition

### ISSUE THREAD

**Issue by johansnow** [terraform-providers/terraform-provider-aws#10845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very helpful if it was possible (always or configurable) to get output for the container definition in diff format against the previous task definition, so that even though a new task definition is created, only those parts of the container definition that changed between the old and new task definitions are shown.

**Summary**
terraform produces more than 500 lines of output for container definition of a new task definition, where only a single line differs from the previous task definition.

If would be awesome if it was possible for terraform to show only the diff from the previous terraform managed task def.

**Background**
Disregarding our jenkins pipeline for CI environment, we are using two ways of deploying new tasks: terraform and our own Deployer.
- When creating a new service, we explicitly specify the docker image to use in our terraform scripts.
- Other than the very first time, we only change docker image through our Deployer.
- Terraform is used to manage all other task definition settings.
- Except for the first time, information about what docker image to use is pulled with data "external" from the previous task def.

But this means that when I
1. run terraform
2. change docker image through the Deployer
3. run terraform (without changes to the tf resources)
Actual result: A single line has changed in the container definition. A new task definition is created (which incidentally is identical to the one that is currently active). terraform outputs over 500 lines of container definition.

For clarity, the actual output looks like this (but has been shortened)

> \# module.base.module.ecs.aws_ecs_service.service_fg[9] will be updated in-place
>   ~ resource "aws_ecs_service" "service_fg" {
>         cluster                            = "x"
>         deployment_maximum_percent         = 200
>         /* and another 20-30 rows without ~, -, + markers, removed for brevity */
>       ~ task_definition                    = "arn:aws:ecs:us-east-1:ACCOUNT-ID:task-definition/x-example-service:258" -> (known after apply)
>     }
> 
> \# module.base.module.ecs.aws_ecs_task_definition.task_def[9] will be created
> + resource "aws_ecs_task_definition" "task_def" {
>     + arn                      = (known after apply)
>     + container_definitions    = jsonencode(
>           [
>             + {
>                 + cpu               = 240
>                 + dockerLabels      = {
>                     + com.datadoghq.ad.check_names  = jsonencode(
>                           [
>                             + "prometheus",
>                           ]
>                       )
>                     // and a few more - all same as last time, all marked with +
>                   }
>                 + environment       = [
>                     + {
>                         + name  = "service_name"
>                         + value = "example-service"
>                       } 
>                       //  and a lot more environment vars - all same as last time, all marked with +
>                   ]
>                 + secrets           = [
>                     + {
>                         + name      = "foo.bar"
>                         + valueFrom = "arn:aws:ssm:us-east-1:725526741327:parameter/x/foo.bar"
>                       }
>                      // and a lot more more ssm params - all same as last time, all marked with +
>                   ]
>                 + image             = "ACCOUNT-ID.dkr.ecr.us-east-1.amazonaws.com/example-service:IMAGE-TAG"
>                 // Note: "IMAGE-TAG" was the only change between container definition from previous task def to this task def
>               }
>           ]
>       )
> 

Desired output

> + resource "aws_ecs_task_definition" "task_def" {
>     + arn                      = (known after apply)
>     + container_definitions    = jsonencode(
>           [
>               - image              = "ACCOUNT-ID.dkr.ecr.us-east-1.amazonaws.com/example-service:PREVIOUS-TAG"
>               + image             = "ACCOUNT-ID.dkr.ecr.us-east-1.amazonaws.com/example-service:IMAGE-TAG"
>           ]
>     )

### New or Affected Resource(s)

One or perhaps both of these
* data "template_file" "container_definition"
* resource "aws_ecs_task_definition" "task_def"

### Potential Terraform Configuration

The contain definition of our resource "aws_ecs_task_definition" references a data "template_file" which in turn references module output produced by a data "external" which fetches the docker image used by the currently used task def.

### References

* #0000

**Comment by bflad** [comment]
Hi @johansnow 👋 Thank you for submitting this. Having the ability to display succinct plan output would be quite nice.

The plan/apply difference output (the user interface of it) is handled upstream by [Terraform CLI](https://github.com/hashicorp/terraform). Terraform Providers have no method to influence this UI so therefore we cannot do anything in this project and I'm going to close this issue since I cannot transfer it across GitHub organizations either. Our recommendation would be to reopen this at https://github.com/hashicorp/terraform/issues/new/choose so the appropriate team can triage this feature request. 👍
