### ISSUE TITLE
aws_launch_configuration: it will be good to have arn on terraform state file

### ISSUE THREAD

**Issue by priguha93** [terraform-providers/terraform-provider-aws#10858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

LaunchConfigurationARN isn't showing up on the terraform state file, although its returned by describe-launch-configurations call. It will be good to have it on the state file too.

### New or Affected Resource(s)

* aws_launch_configuration

### Potential Terraform Configuration

```hcl
resource "aws_launch_configuration" "foobar" {
  name_prefix         = "config"
  image_id      = "${aws_ami.example.id}"
  instance_type = "t2.micro"
  root_block_device {
    delete_on_termination = false
    encrypted = true
  }
}

resource "aws_ami" "example" {
  name                = "terraform-example"
  virtualization_type = "hvm"
  root_device_name    = "/dev/sda1"
  ena_support = true
  architecture = "x86_64"
  sriov_net_support  = "simple"
  ebs_block_device {
    device_name = "/dev/sda1"
    snapshot_id = "snap-097268252a2890bea"
    volume_size = 8
    volume_type = "io1"
    iops = 300
    delete_on_termination = true
  }
  ephemeral_block_device {
    device_name = "/dev/xvda"
    virtual_name = "ephemeral1"
  }
}
```

### References

* #0000

**Comment by bflad** [comment]
Support for the `arn` attribute in the `aws_launch_configuration` resource and data source has been merged and will release with version 2.44.0 of the Terraform AWS Provider, next Thursday. Thanks to @thatderek for the implementation. 👍
