### ISSUE TITLE
aws_lb needs to support setting the drop_invalid_header_fields setting

### ISSUE THREAD

**Issue by fszymanskivertex** [terraform-providers/terraform-provider-aws#10862]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Based on a change in default behavior to the AWS load balancers described at https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html, the routing.http.drop_invalid_header_fields.enabled defaults to true for load balancers starting on November 11, 2019. 

Due to the AWS implementation, headers that should be valid such as "access_token" are being dropped. This is discussed on the official forums at https://forums.aws.amazon.com/thread.jspa?messageID=923165&#923165

In order to allow load balancers to be created in the previous behavior, the aws_lb resource needs to be able to set the drop_invalid_header_fields setting.

### New or Affected Resource(s)
* aws_lb

### References
* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html
* https://forums.aws.amazon.com/thread.jspa?messageID=923165&#923165

**Comment by bionicles** [comment]
had a hell of a time getting LB -> lambda to work this week, it just hung and wouldn't forward to the lambda, would love to see better LB, Lambda docs / support in Terraform because ALB is theoretically easier/better/cheaper than API Gateway for Lambda, and it integrates nicely with Cloudfront

**Comment by jonDowdle** [comment]
AWS changed the default for this field. The default is now `false`.

**Comment by kireledan** [comment]
I'm going to work on this today. Should have PR up by EOD or morning.

**Comment by jmgreg31** [comment]
Any updates on this issue?  I understand AWS changed the default back to false, but we need a way to explicitly set this value to false now that it is an option.  This change has a significant impact to our infrastructure and would like to avoid any issues should AWS decide to change their minds on the defaults.

**Comment by bwalding** [comment]
The impact of this LB setting not being set to `true` just hit the news after a Slack security issue - https://hackerone.com/reports/737140 - https://news.ycombinator.com/item?id=22567937

**Comment by bflad** [comment]
Support for the `drop_invalid_header_fields` argument for the `aws_lb` resource has been merged and will release with version 2.54.0 of the Terraform AWS Provider, on Thursday. Thanks to @kireledan for the implementation. 👍
