### ISSUE TITLE
Is aws cloud directory supported by TF? 

### ISSUE THREAD

**Issue by jltuts** [terraform-providers/terraform-provider-aws#10884]
Is aws cloud directory supported by TF? 

I don't see it in docs. 
---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forum](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by bflad** [comment]
Hi @jltuts 👋 The Terraform AWS Provider does not support [AWS Cloud Directory](https://aws.amazon.com/cloud-directory/) at this time. If you would like to submit a feature request for this functionality, please submit an issue following the [feature request template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) while noting expected use cases and using the [API Reference](https://docs.aws.amazon.com/clouddirectory/latest/APIReference/API_Operations.html) to determine the infrastructure components that might make sense as Terraform resources. Thanks. 👍
