### ISSUE TITLE
How to setup a lambda function to log into a specific log group

### ISSUE THREAD

**Issue by christhomas** [terraform-providers/terraform-provider-aws#10911]
I have read on the "aws_lambda_function" documentation a way to setup a log group for a lambda function to use. But I cannot see or understand how lambda would know which log group to use, since there is no direct connection between them.

This problem comes especially if you have an application which has multiple lambdas, each with their own log group.

I have a role + policy which grants access to 5 log groups, one for each lambda. But there is no way of saying which of these 5 log groups the policy has access to, each specific lambda should use.

**Comment by fabiomatavelli** [comment]
The lambda will write logs to its log group called `/aws/lambda/<your_function_name>` and you cannot change it. Since the log group is only created on the first run of the lambda, the terraform example creates it in advance with the retention period set.

**Comment by christhomas** [comment]
Oh, thats disappointing to hear. But thanks for letting me know
