### ISSUE TITLE
EBS snapshot: Add tags while copying

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10924]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of [AWS SDK v1.25.36](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.36), you can now add tags while copying EBS snapshots.

### New or Affected Resource(s)

* [`aws_ebs_snapshot_copy`](https://www.terraform.io/docs/providers/aws/r/ebs_snapshot_copy.html)

### Potential Terraform Configuration

```hcl
resource "aws_ebs_snapshot_copy" "example" {
  tags = {
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/copy-snapshot-api-supports-adding-tags-while-copying-snapshots/).

Requires:

* #10900

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.40.0 of the Terraform AWS Provider next week. Thanks to @DrFaust92 for the implementation. 👍
