### ISSUE TITLE
Amazon EMR cluster ARN

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10921]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of [AWS SDK v1.25.36](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.36):

> Access to the cluster ARN makes it easier for you to author resource-level permissions policies in AWS Identity and Access Management. To simplify the process of obtaining the cluster ARN, Amazon EMR has added a new field containing the cluster ARN to all API responses that include the cluster ID.

### New or Affected Resource(s)

* [`aws_emr_cluster`](https://www.terraform.io/docs/providers/aws/r/emr_cluster.html)

### Potential Terraform Configuration

```hcl
resource "aws_emr_cluster" "example" {}

arn = aws_emr_cluster.example.arn
```

### References

Requires:

* https://github.com/terraform-providers/terraform-provider-aws/pull/10900

**Comment by bflad** [comment]
This new attribute has been merged and will release with version 2.41.0 of the Terraform AWS Provider, later this week. Thanks @thatderek for the implementation. 👍
