### ISSUE TITLE
AWS App Mesh support for TLS in transit encryption

### ISSUE THREAD

**Issue by brunocous** [terraform-providers/terraform-provider-aws#10922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Encryption in transit is an important feature for service meshes. App Mesh support's for it is still for preview channel only (see ref 1). The virtual node Terraform resource does not provide the option at the moment.

### New or Affected Resource(s)

* [`aws_appmesh_virtual_node`](https://www.terraform.io/docs/providers/aws/r/appmesh_virtual_node.html)

### Proposed interface
According to the documentation, a certificate should be created somewhere (ACM), and a `tls` object should be added to the listener of each virtual node. This tls object has two options: a mode and reference to a ACM certificate.
```hcl
"tls": {
            "mode": "STRICT",
            "certificate": {
                "acm": {
                    "certificateArn": "${CERTIFICATE_ARN}"
                }
            }
        }
```

### References
* https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual-node-tls.html

**Comment by ewbankkit** [comment]
@brunocous I had been looking at the App Mesh preview channel in https://github.com/terraform-providers/terraform-provider-aws/pull/9468 but put this on pause as the features started to move into the release channel.
I'm not sure what plans are for supporting preview channels in general.

**Comment by SeanFaheyYgrene** [comment]
@ewbankkit as a heads up this feature is now out of preview.

**Comment by SebastianC** [comment]
any idea when this may be reviewed/merged?

**Comment by lays147** [comment]
Is there any timeline when this will be available on the provider?
