### ISSUE TITLE
Support for regional S3 us-east-1 endpoint

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I noticed this in the release notes for [AWS SDK v1.25.35](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.35):

> Adds support for S3 configuring an SDK Amazon S3 client for the regional us-east-1 endpoint instead of the default global S3 endpoint.
> Adds a new configuration option, S3UsEast1RegionalEndpoint which when set to RegionalS3UsEast1Endpoint, and region is us-east-1 the S3 client will resolve the us-east-1 regional endpoint, s3.us-east-1.amazonaws.com instead of the global S3 endpoint, s3.amazonaws.com. The SDK defaults to the current global S3 endpoint resolution for backwards compatibility.
> Opt-in to the us-east-1 regional endpoint via the SDK's Config, environment variable, AWS_S3_US_EAST_1_REGIONAL_ENDPOINT=regional, or shared config option, s3_us_east_1_regional_endpoint=regional.

How does this affect the Terraform AWS Provider?

### References

Related:
* https://github.com/aws/aws-sdk-go/pull/2938

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/10886

**Comment by ewbankkit** [comment]
Something else in the release notes for [AWS SDK v1.26.5](https://github.com/aws/aws-sdk-go/releases/tag/v1.26.5):

> Updates Amazon S3 endpoints allowing you to configure your client to opt-in to using S3 with the us-east-1 regional endpoint, instead of global.

**Comment by bflad** [comment]
@ewbankkit do we need to do anything here?

**Comment by ewbankkit** [comment]
I'll take a look.

**Comment by ewbankkit** [comment]
Other than the AWS SDK release notes item quoted above I can find nothing documented about this functionality.
I can see no use case for supporting this currently. I'll close this issue.
