### ISSUE TITLE
Support for AWS FIFO SQS as Lambda trigger

### ISSUE THREAD

**Issue by dfens1** [terraform-providers/terraform-provider-aws#10944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

It seems like FIFO SQS queues are now supported as Lambda triggers. 

### New or Affected Resource(s)

aws_lambda_event_source_mapping

### Potential Terraform Configuration

Sorry for the lack of code formatting. I’m typing this on a phone..

Example config:

resource "aws_lambda_event_source_mapping" "example" {
  event_source_arn = "${aws_sqs_queue.sqs_queue_test.arn}"
  function_name    = "${aws_lambda_function.example.arn}"
}

Since this actually doesn’t include an SQS type, I wonder if a change is required at all... if not, apologies for wasting everyone’s time. 

### References

https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

**Comment by tomelliff** [comment]
As far as I can see here this should just be the same configuration as a normal SQS queue but just refer to a FIFO queue instead. Is this not working for you already? If not could you post an example of trying to set this up and provide any errors that happen when you try it?

**Comment by dfens1** [comment]
never mind - my problem was caused by a different error on my side and as @tomelliff pointed out, FIFO queues can already be used as Lambda triggers
