### ISSUE TITLE
Support ALB weighted target groups

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Application Load Balancers now support weighted target groups routing.

### New or Affected Resource(s)

* [`aws_lb_listener`](https://www.terraform.io/docs/providers/aws/r/lb_listener.html)
* [`aws_lb_listener_rule`](https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html)

### Potential Terraform Configuration

```hcl
resource "aws_lb_listener_rule" "example" {
  action {
    type = "forward"
    ...
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/application-load-balancer-simplifies-deployments-support-for-weighted-target-groups/).
[Blog post](https://aws.amazon.com/blogs/aws/new-application-load-balancer-simplifies-deployment-with-weighted-target-groups/).

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8126

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/10940

**Comment by kazeshini178** [comment]
Would this include support for the new conditions available on ALBs?

**Comment by tomelliff** [comment]
@kazeshini178 what do you mean by that? I think this is referring to https://aws.amazon.com/blogs/aws/new-application-load-balancer-simplifies-deployment-with-weighted-target-groups/ so it would add weighting to the target groups for listeners and listener rules and also the option for target group stickiness.

**Comment by ewbankkit** [comment]
@kazeshini178 The new conditions you are looking for may be addressed by https://github.com/terraform-providers/terraform-provider-aws/issues/8126.

**Comment by kazeshini178** [comment]
@ewbankkit  Correct, was wondering if that was bundled part of this request as that thread seems to have gone silent, though i only noticed not that the pull request for it is still active.

**Comment by srikanth787** [comment]
@ewbankkit @dpiddockcmp I don't think ask for weighted target groups is implemented through #8126

**Comment by houstonj1** [comment]
@srikanth787 is right, #8126 does not include features requested above, which would be awesome 🙏

**Comment by stephen-james-pe** [comment]
Hello, I plan on using this feature soon on a project, is there an estimated time it will be available?

**Comment by ADobrodey** [comment]
> Enabling target-level stickiness requires that any weighted routing rules associated with this target group have group-level stickiness enabled first. If the target group is not part of a weighted routing rule, there are no prerequisites for enabling target-level stickiness.

Without support of group stickiness in ALB rules CodeDeploy fails with an error:
```
ERROR: CodeDeployBlueGreen: hudson.AbortException: CodeDeployBlueGreen: Deployment status [Failed] !!!:
code: ELASTIC_LOAD_BALANCING_INVALID
message: The ELB could not be updated due to the following error: You must enable group stickiness on a rule if you enabled target stickiness on one of its target groups.
```

**Comment by rdelcampog** [comment]
> > Enabling target-level stickiness requires that any weighted routing rules associated with this target group have group-level stickiness enabled first. If the target group is not part of a weighted routing rule, there are no prerequisites for enabling target-level stickiness.
> 
> Without support of group stickiness in ALB rules CodeDeploy fails with an error:
> 
> ```
> ERROR: CodeDeployBlueGreen: hudson.AbortException: CodeDeployBlueGreen: Deployment status [Failed] !!!:
> code: ELASTIC_LOAD_BALANCING_INVALID
> message: The ELB could not be updated due to the following error: You must enable group stickiness on a rule if you enabled target stickiness on one of its target groups.
> ```

Check: https://github.com/terraform-providers/terraform-provider-aws/pull/11606/files#r366770507

Must be added to the documentation but I think is expected.

**Comment by pbn4** [comment]
> > Enabling target-level stickiness requires that any weighted routing rules associated with this target group have group-level stickiness enabled first. If the target group is not part of a weighted routing rule, there are no prerequisites for enabling target-level stickiness.
> 
> Without support of group stickiness in ALB rules CodeDeploy fails with an error:
> 
> ```
> ERROR: CodeDeployBlueGreen: hudson.AbortException: CodeDeployBlueGreen: Deployment status [Failed] !!!:
> code: ELASTIC_LOAD_BALANCING_INVALID
> message: The ELB could not be updated due to the following error: You must enable group stickiness on a rule if you enabled target stickiness on one of its target groups.
> ```

Any ideas on how to fix this? Moving back to 0.12.19 yields same results.

**Comment by lucjross** [comment]
For now I'm using a provisioner for this: https://gist.github.com/lucjross/e1a369a68103d198cb576af866c81b50

**Comment by rdelcampog** [comment]
Please try this #12574 implementation and vote 👍 in the PR. Hope everything goes OK and is merged soon.

**Comment by jmgreg31** [comment]
Can someone let me know if I am understanding this correctly.  The docmentation for `aws_lb_listener_rule` states that 
```
Forward Blocks (for forward) support the following:

target_group - (Required) One or more target groups block.
```

However, if I only attempt to configure one target group, I get the error:
```
Error: action.0.forward.0.target_group: attribute supports 2 item as a minimum, config has 1 declared
```

Would I also need to set the `target_group_arn` in the main action block if I dynamically only needed one target group to be attached?
