### ISSUE TITLE
aws_eks_node_group creating instances with public IPs

### ISSUE THREAD

**Issue by richstokes** [terraform-providers/terraform-provider-aws#10941]
Terraform v0.12.16
+ provider.aws v2.38.0
+ provider.http v1.1.1

```hcl
resource "aws_eks_node_group" "nodegroup0" {
  cluster_name    = aws_eks_cluster.il-w2.name
  node_group_name = "nodegroup0"
  node_role_arn   = aws_iam_role.il-w2-node.arn
  subnet_ids      = aws_subnet.il-w2[*].id

  disk_size       = 50
  instance_types  = ["r5.large"]

  version         = "1.14" # Kubernetes version

  scaling_config {
    desired_size = 2
    max_size     = 100
    min_size     = 2
  }

  tags = {
    Name = "Kubernetes Worker Node"
   }

  labels = {
    Type = "r5.large-16GB"
   }   
}
```

When the instances are spun up they have public IPs. This should not happen since the subnets are set to not auto assign a public IP. Remote access to the nodes is also disabled.

**Comment by richstokes** [comment]
I think this is a bug/limitation on the AWS side

**Comment by replicant0wnz** [comment]
Is the bug documented on the AWS side? You can easily avoid assigning public IP's to the nodegroup when using eskctl. It's set at the ASG ..
