### ISSUE TITLE
Tag (and/or describe) an EC2 network interface

### ISSUE THREAD

**Issue by elofu17** [terraform-providers/terraform-provider-aws#10948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since #1403 was closed, I'm opening a new issue for the same thing (tagging) and adding a reqest for setting the description as well.

I see the workaround found in #1403, using 'aws_network_interface', but that is rather a VPC resource  than an EC2 resource... It would be nice to be able to do everything under 'aws_instance' directly.

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration
```
Either put everything new in the 'network_interface' block, like this:
resource "aws_instance" "foo" {
  ...
  tags = {
    Name = "EC2 foo tag"
  }
  network_interface {
    network_interface_id = xxxxx
    device_index         = 0
    description          = "foo eth0 description"
    tags = {
      Name = "foo eth0 tag"
    }
  }
}

Or put the 'description' in the 'network_interface' block, and tags like it is already done for 'volume_tags':
resource "aws_instance" "foo" {
  ...
  network_interface {
    network_interface_id = xxxxx
    device_index         = 0
    description          = "foo eth0 description"
  }
  volume_tags = {
    Name  = "foo root volume tag"
  }
  network_interface_tags = {
    Name  = "foo eth0 tag"
  }
}
```

### References

See issue #1403

**Comment by bflad** [comment]
Drive-by comment: If this is to be implemented, I would strongly discourage the usage of a top-level `network_interface_tags` argument that applies to all attached network interfaces for an EC2 Instance -- we have had multitudes of issues regarding the usage and expectations of `volume_tags`, mostly from the ability to separately attach and manage tags of EBS Volumes from other Terraform resources. The `volume_tags` argument is likely to be deprecated in the future in preference of using a `tags` argument within each block device so they can individually only worry about their own tags.

**Comment by elofu17** [comment]
Agree. Perhaps the solution here is not to make 'aws_instance' even more complex, but simply write a couple of nice code examples in the 'aws_instance' manual page, with a separate 'aws_network_interface' resource (with tags, description, private_ips and what not).
