### ISSUE TITLE
Glue Database: Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by priguha93** [terraform-providers/terraform-provider-aws#10947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.13
+ provider.aws v2.38.0

### Affected Resource(s)

* aws_glue_catalog_table

### Terraform Configuration Files

```hcl
resource "aws_glue_catalog_database" "aws_glue_catalog_database" {
  name = "MyCatalogDatabase"
  parameters = {
    param1 = "value1"
    param2 = true
    param3 = 50
  }
}

resource "aws_glue_catalog_table" "aws_glue_catalog_table" {
  name          = "MyCatalogTable"
  database_name = "${aws_glue_catalog_database.aws_glue_catalog_database.name}"

  table_type = "EXTERNAL_TABLE"

  parameters = {
    EXTERNAL              = "TRUE"
    "parquet.compression" = "SNAPPY"
  }

  storage_descriptor {
    location      = "s3://my-bucket/event-streams/my-stream"
    input_format  = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
    output_format = "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"

    ser_de_info {
      name                  = "my-stream"
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"

      parameters = {
        "serialization.format" = 1
      }
    }

    columns {
      name = "my_string"
      type = "string"
    }

    columns {
      name = "my_double"
      type = "double"
    }

    columns {
      name    = "my_date"
      type    = "date"
      comment = ""
    }

    columns {
      name    = "my_bigint"
      type    = "bigint"
      comment = ""
    }

    columns {
      name    = "my_struct"
      type    = "struct<my_nested_string:string>"
      comment = ""
    }
  }
}
```

### Expected Behavior

Terraform should create the table without errors

### Actual Behavior

Terraform returned error:

```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_glue_catalog_table.aws_glue_catalog_table to
include new values learned so far during apply, provider "aws" produced an
invalid new value for .database_name: was cty.StringVal("MyCatalogDatabase"),
but now cty.StringVal("mycatalogdatabase").
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @priguha93 👋 Thank you for submitting this and sorry you ran into trouble there. To fix this issue in your configuration, lowercase the names being passed into the `database_name` and `name` arguments. Terraform expects the configuration to match the API result, however the Glue API is automatically lowercasing the result, which is causing the Terraform error. Since this appears to be covering the same intention of #7958 and fix of #8288, to consolidate efforts and discussions I'm going to close this issue in preference of the earlier ones. 👍
