### ISSUE TITLE
Amazon EC2 Auto Scaling supports instance weighting

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon EC2 Auto Scaling now lets you include instance weights in Auto Scaling groups (ASGs) that are configured to provision and scale across multiple instance types.

### New or Affected Resource(s)

* [`aws_autoscaling_group`](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html)

### Potential Terraform Configuration

```hcl
resource "aws_autoscaling_group" "example" {
  mixed_instances_policy {
    launch_template {
      launch_template_specification {
        launch_template_id = "${aws_launch_template.example.id}"
      }

      override {
        instance_type     = "c5.18xlarge"
        weighted_capacity = 18
      }

      override {
        instance_type     = "c5.24xlarge"
        weighted_capacity = 24
      }
    }
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ec2-auto-scaling-supports-instance-weighting/).
[User guide](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-weighting.html).

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.41.0 of the Terraform AWS Provider, later this week. Thanks to @gvolco for the implementation. 👍
