### ISSUE TITLE
Amazon EC2 Auto Scaling supports maximum instance lifetime

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10956]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon EC2 Auto Scaling now lets you safely and securely recycle instances in an Auto Scaling group (ASG) at a regular cadence.

### New or Affected Resource(s)

* [`aws_autoscaling_group`](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html)

### Potential Terraform Configuration

```hcl
resource "aws_autoscaling_group" "example" {
  max_instance_lifetime = 2592000 // 30 days in seconds.
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ec2-auto-scaling-supports-max-instance-lifetime/).
[User guide](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-max-instance-lifetime.html).

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.41.0 of the Terraform AWS Provider, later this week. Thanks to @razaj92 for the implementation. 👍
