### ISSUE TITLE
Add BUILD_GENERAL1_2XLARGE compute_type support for CodeBuild

### ISSUE THREAD

**Issue by DzmitrySudnik** [terraform-providers/terraform-provider-aws#10979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for a new compute type for CodeBuild, see AWS announcement linked below

### New or Affected Resource(s)

* aws_codebuild_project

### References

AWS announcement for a new compute type for CodeBuild:
* https://aws.amazon.com/about-aws/whats-new/2019/11/aws-codebuild-adds-support-for-arm--gpu--and-x-large-compute-typ/

* #0000

**Comment by bflad** [comment]
For anyone interested in implementing this:

* Available AWS Go SDK constants: https://docs.aws.amazon.com/sdk-for-go/api/service/codebuild/#pkg-constants
* Schema (where the values are validated): https://github.com/terraform-providers/terraform-provider-aws/blob/101295fdf4b62139d82808d43fd04d84bd1bb435/aws/resource_aws_codebuild_project.go#L168-L176
* Resource documentation: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/codebuild_project.html.markdown

**Comment by DzmitrySudnik** [comment]
My naive attempt (very first experience in go for me) failed miserably on upgrading aws-sdk (since that constant is not in 2.38 which is currently used). Don't have time to learn go package management today, any help is welcome. Also see a parallel attempt just to upgrade that dependency and it looks pretty huge and scary: https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by bflad** [comment]
@DzmitrySudnik the latest AWS Go SDK has now been merged.
