### ISSUE TITLE
allow no spot_price / max_price in aws_launch_configuration / aws_launch_template

### ISSUE THREAD

**Issue by scalp42** [terraform-providers/terraform-provider-aws#10975]
Hi folks,

Looking at AWS, we can request spot instances while not specifying a max price, "Request Spot Instances at the Spot price, capped at the On-Demand price":

<img width="847" alt="Screen Shot 2019-11-21 at 12 08 38" src="https://user-images.githubusercontent.com/1475276/69373153-0b08c180-0c58-11ea-9355-d1aff38bd477.png">

Looking at the `aws_launch_template` ![resource](https://www.terraform.io/docs/providers/aws/r/launch_template.html#market-options), it looks like you can specify `max_price` in the `spot_options` block but what happens if you don't mention one? Is it capped on on-demand price?

Any insights?

Thanks in advance 😄

**Comment by ryndaniels** [comment]
Hi @scalp42 - looking at the API reference [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotMarketOptions.html), it looks like you're correct that the max price is set to the on-demand price by default. In general, we prefer that this repo be reserved for feature requests and bugs in the provider itself, so questions like this in the future would be better suited for [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws)). Thanks!
