### ISSUE TITLE
Importing aws_network_acl_rule

### ISSUE THREAD

**Issue by jerroydmoore** [terraform-providers/terraform-provider-aws#10983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to import existing network acl rules. This was originally reported in #703 along with importing `aws_route`. import support for `aws_route` was complete but not `aws_network_acl_rule`. I think we should to track each request individually, hence filing this issue.

### New or Affected Resource(s)

* aws_network_acl_rule

### Potential Terraform Configuration

N/A

### References

* #704

**Comment by ahharu** [comment]
Any updates?

**Comment by anGie44** [comment]
The fix for this has been merged and will release with version 2.59.0 of the Terraform AWS Provider.
