### ISSUE TITLE
Support Nodejs 12.x, python 3.8, and Java 11 runtime in Lambda

### ISSUE THREAD

**Issue by chrsalx** [terraform-providers/terraform-provider-aws#10996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Specifying `nodejs12.x`, `python3.8`, or `java11` as a lambda function runtime results in error but these runtimes are currently available through the aws console.

Here's a screenshot of the console: [http://tinyurl.com/unfqjjz](http://tinyurl.com/unfqjjz)

```
➜ terraform -v
Terraform v0.12.16
+ provider.aws v2.34.0
+ provider.template v2.1.2
```

```
➜ terraform plan

Error: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 go1.x java8 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x provided python2.7 python3.6 python3.7 ruby2.5], got java11

```

### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "lambda_fn" {
  function_name = "lambda_fn"
  ...
  runtime = "java11" | "nodejs12.x" | "python3.8"
}
```

### References

* #8627

**Comment by ewbankkit** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/10919.
@chrsalx AWS Lambda support for Java 11, Node.js 12 and Python 3.8 was added in https://github.com/terraform-providers/terraform-provider-aws/pull/10938 and released in [version 2.39.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/v2.39.0/CHANGELOG.md).
