### ISSUE TITLE
ACM certificate tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#10992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Tag-on create is now available for AWS Certificate Manager (ACM).
> Upon creation, you can tag your ACM certificates.

### New or Affected Resource(s)

* [`aws_acm_certificate`](https://www.terraform.io/docs/providers/aws/r/acm_certificate.html)

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/tag-on-create-and-tag-based-iam-for-aws-certificate-manager-and-private-certificate-authority/).

Requires [AWS SDK v1.25.41](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.41):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by bflad** [comment]
Support for tag-on-create with the `aws_acm_certificate` resource has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
