### ISSUE TITLE
Support multiple Target Groups per Listener Rule

### ISSUE THREAD

**Issue by thenom** [terraform-providers/terraform-provider-aws#11003]
### Description

This is a feature request to support the following new AWS feature to support weighted multiple target groups per listener rule:
https://aws.amazon.com/blogs/aws/new-application-load-balancer-simplifies-deployment-with-weighted-target-groups/

### New or Affected Resource(s)

* aws_lb_listener_rule

aws cli example:
```bash
aws elbv2 modify-listener    \
     --listener-arn "<listener arn>" \
     --default-actions        \
        '[{
          "Type": "forward",
          "Order": 1,
          "ForwardConfig": {
             "TargetGroups": [
               { "TargetGroupArn": "<target group 1 arn>",
                 "Weight": 80 },
               { "TargetGroupArn": "<target group 2 arn>",
                 "Weight": 20 },
             ]
          }
         }]'
```

### Potential Terraform Configuration

```hcl
resource "aws_lb_listener_rule" "static" {
  listener_arn = "${aws_lb_listener.front_end.arn}"
  priority     = 100

  action {
    type             = "forward"
    target_group_arn = "${aws_lb_target_group.blue.arn}"
    weight           = 50
  }

  action {
    type             = "forward"
    target_group_arn = "${aws_lb_target_group.green.arn}"
    weight           = 50
  }

  condition {
    field  = "path-pattern"
    values = ["/static/*"]
  }
}
```

### References

https://aws.amazon.com/blogs/aws/new-application-load-balancer-simplifies-deployment-with-weighted-target-groups/

**Comment by thenom** [comment]
I am fairly new to Go but will take a look

**Comment by thenom** [comment]
Thinking this might be better programatically so the block could be dynamically iterated through, not sure it makes much difference though:

### Potential Terraform Configuration

```hcl
resource "aws_lb_listener_rule" "static" {
  listener_arn = "${aws_lb_listener.front_end.arn}"
  priority     = 100

  action {
    type             = "forward"

    target_group {
        target_group_arn = "${aws_lb_target_group.blue.arn}"
        weight           = 50
    }

    target_group {
        target_group_arn = "${aws_lb_target_group.green.arn}"
        weight           = 50
    }
  }

  condition {
    field  = "path-pattern"
    values = ["/static/*"]
  }
}
```

**Comment by pierre-roudaut-cko** [comment]
This feature is much needed for the creation of autoscaling policies `aws_autoscaling_policy`.
Scaling policies can't be created without having listeners attached to target groups.

> "The load balancer does not route traffic to the target group"

**Comment by aeschright** [comment]
Hi @thenom 👋 It appears we have multiple issues opened for this feature, so I'm closing this one in favor of the earlier #10942. Thanks!
