### ISSUE TITLE
Support alternative routing algorithms in aws_lb_target_group

### ISSUE THREAD

**Issue by gileri** [terraform-providers/terraform-provider-aws#11019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS Application Load Balancers [now supports alternative routing algorithms](https://aws.amazon.com/fr/about-aws/whats-new/2019/11/application-load-balancer-now-supports-least-outstanding-requests-algorithm-for-load-balancing-requests/) for Target Groups, starting with `Least Outstanding Requests`.

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  port     = 80
  protocol = "HTTP"
  vpc_id   = aws_vpc.main.id
  load_balancing {
    algorithm {
      # type = "round_robin" # Default
      type = "least_outstanding_requests"
    }
  }
}
```

### References
* https://aws.amazon.com/fr/about-aws/whats-new/2019/11/application-load-balancer-now-supports-least-outstanding-requests-algorithm-for-load-balancing-requests/
* https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetGroupAttribute.html#API_TargetGroupAttribute_Contents

**Comment by bflad** [comment]
Support for a new `load_balancing_algorithm_type` argument with the `aws_lb_target_group` resource (aliased with `aws_alb_target_group` as well) has been merged and will release with version 2.52.0 of the Terraform AWS Provider, Thursday this week. Thanks to @dhoeric for the implementation. 👍
