### ISSUE TITLE
aws_batch_compute_environment: launch_template update should destroy and recreate CE

### ISSUE THREAD

**Issue by lisajluo** [terraform-providers/terraform-provider-aws#11012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform --version
Terraform v0.12.16
+ provider.aws v2.39.0

```

### Affected Resource(s)

* aws_batch_compute_environment

### Terraform Configuration Files

```hcl
resource "aws_batch_compute_environment" "R5OnDemandEBS1000" {
  compute_environment_name = "R5OnDemandEBS1000"

  compute_resources {
    launch_template {
      launch_template_id = module.launch_template_batch_ebs1000.id
      version            = "7"
      # Change the above, for example to version = "6"
    }

    instance_role = aws_iam_instance_profile.ecs_instance_role.arn

    instance_type = [
      "r5.8xlarge"
    ]

    max_vcpus = 1600
    min_vcpus = 0

    security_group_ids = [
      aws_security_group.batch.id
    ]

    subnets = local.subnets_private

    type = "EC2"
    tags = local.tags
  }

  service_role = aws_iam_role.aws_batch_service_role.arn
  type         = "MANAGED"
  depends_on = [
    aws_iam_role_policy_attachment.aws_batch_service_role
  ]
}
```

### Expected Behavior

AWS Compute Environments do not support updates to the Launch Template (or other compute resources besides vcpus) via the API. Updates outside of those supported should create a destroy/recreate plan/apply.

See:
- https://docs.aws.amazon.com/batch/latest/APIReference/API_UpdateComputeEnvironment.html
- https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeResourceUpdate.html

Other resources can only be managed as part of a create:
- https://docs.aws.amazon.com/batch/latest/APIReference/API_CreateComputeEnvironment.html

### Actual Behavior

Plan shows CE resource modified in-place with LT updated:

```  # module.use1_standard_ce.aws_batch_compute_environment.R5OnDemandEBS1000 will be updated in-place
  ~ resource "aws_batch_compute_environment" "R5OnDemandEBS1000" {
        arn                      = "arn:aws:batch:<region>:<account>:compute-environment/R5OnDemandEBS1000"
        compute_environment_name = "R5OnDemandEBS1000"
        ecs_cluster_arn          = "arn:aws:ecs:<region>:<account>:cluster/<clusterid>"
        id                       = "R5OnDemandEBS1000"
        service_role             = "arn:aws:iam::<account>:role/aws_batch_service_role_id"
        state                    = "ENABLED"
        status                   = "VALID"
        status_reason            = "ComputeEnvironment Healthy"
        type                     = "MANAGED"

      ~ compute_resources {
            bid_percentage     = 0
            desired_vcpus      = 0
            instance_role      = "arn:aws:iam::<account>:instance-profile/ecs_instance_role"
            instance_type      = [
                "r5.8xlarge",
            ]
            max_vcpus          = 1600
            min_vcpus          = 0
            security_group_ids = [
                "sg-id1",
            ]
            subnets            = [
                "subnet-id1",
                "subnet-id2",
                "subnet-id3",
                "subnet-id4",
            ]
            tags               = {
                "component"        = "compute_environment"
                "environment"      = "dev"
            }
            type               = "EC2"

          ~ launch_template {
                launch_template_id = "lt-id1"
              ~ version            = "7" -> "6"
            }
        }
    }
```

Apply appears to be successful:

```
$ terraform apply update.out
module.use1_standard_ce.aws_batch_compute_environment.R5OnDemandEBS1000: Modifying... [id=R5OnDemandEBS1000]
module.use1_standard_ce.aws_batch_compute_environment.R5OnDemandEBS1000: Modifications complete after 1s [id=R5OnDemandEBS1000]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

However, subsequent runs show the same diff: (since API doesn't support LT update):

```
...
          ~ launch_template {
                launch_template_id = "lt-id1"
              ~ version            = "7" -> "6"
            }
...
```

### Steps to Reproduce

1. Update CE with change in LT (or probably any other unsupported resource)
2. `terraform plan -out update.out`
3. `terraform apply update.out`

### Important Factoids

N/A

### References

N/A

**Comment by bflad** [comment]
Hi @lisajluo 👋 Thank you for reporting this and sorry you ran into trouble here. This indeed does look incorrect in the Terraform resource. If you or someone is interested in fixing this, each of the underlying schema attributes under `launch_template`:

https://github.com/terraform-providers/terraform-provider-aws/blob/d9d419d78212a22851290108776246e48a384182/aws/resource_aws_batch_compute_environment.go#L74-L87

Should have `ForceNew: true,` added so Terraform properly signals resource recreation instead of an update it cannot complete. 👍
