### ISSUE TITLE
aws_cloudwatch_metric_alarm with expression throws ValidationError Period must not be null

### ISSUE THREAD

**Issue by lpfeup** [terraform-providers/terraform-provider-aws#11011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.39.0

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "test" {
  alarm_name          = "test"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = "1"
  threshold           = "0.1"
  treat_missing_data  = "ignore"
  alarm_description   = "Test"

  metric_query {
    id          = "e1"
    expression  = "SEARCH('{AWS/ElasticBeanstalk,EnvironmentName,InstanceId} MetricName=\"LoadAverage5min\"', 'Maximum', 300)"
    return_data = "true"
  }
}
```

### Debug Output

https://gist.github.com/lpfeup/368c310ed87e7b058f0f11a4b688e391

### Expected Behavior

`terraform apply` with success

### Actual Behavior

`terraform apply` thrown `ValidationError: Period must not be null`. 
If I specify a `period` for  `aws_cloudwatch_metric_alarm`, I get the following error: `"period": conflicts with metric_query`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jaredvacanti** [comment]
I have this same error - is this a bug or is there a different way to create the alarm?

**Comment by DogaCUlupinar** [comment]
This happens because AWS Cloudwatch does not support alarms on `SEARCH` metrics. 
ref: https://stackoverflow.com/questions/55543319/creating-a-cloudwatch-alarm-based-on-a-search-expression

**Comment by lpfeup** [comment]
Thank you @DogaCUlupinar, I wrongly assumed that it was supported. And since the `ValidationError` referred to the `period`, that led me to believe it was a bug.

Feel free to close the issue.

**Comment by bflad** [comment]
Closing as requested by the original author above.

The error message `ValidationError: Period must not be null` is being returned by the CloudWatch API, so any changes to the messaging will need to be done by the CloudWatch service team via either an AWS Support case or reaching out to your AWS account managers. If there does happen to be a bug in the Terraform resource implementation, please let us know.
