### ISSUE TITLE
AuthFailure: AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by lucaswxp** [terraform-providers/terraform-provider-aws#1102]
Hey guys.

Recently I started getting the following error back from terraform:

```
aws_security_group.canada-squid: AuthFailure: AWS was not able to validate the provided access credentials
	status code: 401, request id: f1569889-c513-466a-9056-637538038058
```

There was no change in the my environment or keys, but this error started coming up a couple weeks ago. I tried creating news keys now, but still get the same error. I'm using v0.9.11, any idea to debug this?

**Comment by OliverCole** [comment]
Is it just that resource? Does the AWS CLI work?

Definitely consider posting a debug log!

**Comment by lucaswxp** [comment]
The problem was with the system's clock. This solved:
```
sudo ntpdate time.nist.gov
```
