### ISSUE TITLE
Support Least Outstanding Requests for ALB 

### ISSUE THREAD

**Issue by piotrb** [terraform-providers/terraform-provider-aws#11039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS just announced this new feature. This seems to be handled through target group attributes.

setting `load_balancing.algorithm.type` to `least_outstanding_requests` will do it .. the default being `round_robin` so that's the two valid options.

This seems the same mechanism as things like `slow_start` or `stickiness` are set, so this would live in code somewhere near that.

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

potentially mirror the aws dot notation ...
```hcl
resource "aws_lb_target_group" "test" {
  load_balancing {
    algorithm {
      type = "least_outstanding_requests"
    }
  }
}
```

or just flatten it ..
```hcl
resource "aws_lb_target_group" "test" {
  load_balancing_algorithm_type = "least_outstanding_requests"
}
```

### References

https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html#routing-algorithm

https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetGroupAttribute.html

**Comment by ewbankkit** [comment]
@piotrb I think this one duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/11019.

**Comment by piotrb** [comment]
Yea looks like it

**Comment by bflad** [comment]
Closing this issue to consolidate efforts and discussions in #11019. 👍
