### ISSUE TITLE
Lambda creation fails in version 2.40.0 in LocalStack

### ISSUE THREAD

**Issue by ciaranevans** [terraform-providers/terraform-provider-aws#11037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform Version = `1.12.6`
`aws` Provider Version = `2.40`
### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```
resource aws_lambda_function find-images {
  function_name = "sentinel-find-images"
  handler = "sentinel-find-images.handler"
  role = ""
  runtime = "python3.6"
  filename = "../../lambda/sentinel-find-images/sentinel-find-images.zip"
  timeout = 900
  memory_size = 3000
  environment {
    variables = {
      STAGE = "TESTING"
    }
  }
}
```

### Debug Output

https://gist.github.com/ciaranevans/de537317f933b98df7af306bb86e2730 For failing run
https://gist.github.com/ciaranevans/0a30164e61ae444198a59fad37c80013 For successful run

### Expected Behavior

Terraform finishes deployment with line similar to:

```
Apply complete! Resources: 24 added, 0 changed, 0 destroyed.
```

### Actual Behavior

All functions failed to deploy (According to Terraform), shown in debug logs above.

However they are actually deployed - my tests that wait for them to be deployed kick off and pass...

Tests are initiated once:
```
aws lambda list-functions --endpoint-url=http://localhost:4574 | jq '.[] | length'
```
returns a number == to the number of functions I'm deploying

### Steps to Reproduce

1. Create AWS provider with LocalStack with:

```
provider aws {
  region                      = "eu-west-2"
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4567"
    cloudwatchlogs = "http://localhost:4586"
    dynamodb       = "http://localhost:4569"
    iam            = "http://localhost:4593"
    lambda         = "http://localhost:4574"
    s3             = "http://localhost:4572"
    sns            = "http://localhost:4575"
    sqs            = "http://localhost:4576"
    ssm            = "http://localhost:4583"
  }
}
```

2. Create a Lambda function resource
3. `terraform apply`

### Important Factoids

* Deploying against LocalStack
* Works with `aws` provider version `2.39`
* Does not work with `aws` provider version `2.40`

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/11016 is the only pull request in the new release that appears to touch Lambdas.

**Comment by ewbankkit** [comment]
@ciaranevans My guess is that this is a [LocalStack](https://localstack.cloud/)-specific problem.
The AWS Lambda [`GetFunctionConfiguration`](https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConfiguration.html) API now returns a [`State`](https://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConfiguration.html#SSS-GetFunctionConfiguration-response-State) field and the Terraform AWS Provider (as of v2.40.0) uses this field to ensure that the lambda function is created successfully.
A missing value (as in the current LocalStack implementation) results in an empty `State` value which isn't either the in-progress value (`Pending`) or success value (`Active`), triggering the error you experienced.

You can [pin the provider version](https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions) to v2.39.0 until LocalStack support this functionality; I'd suggest opening an issue in [their repo](https://github.com/localstack/localstack/issues) and referening this issue.

**Comment by ciaranevans** [comment]
@ewbankkit Great, thanks for taking a look into this!

I did indeed end up pinning the version. Couldn't quite figure out which end of the stick was going wrong!

**Comment by ciaranevans** [comment]
Fixed in the latest version of LocalStack, tested with version `2.41.0` of the AWS Provider
