### ISSUE TITLE
aws_batch_job_definition does not respect lifecycle ignore_changes

### ISSUE THREAD

**Issue by mmshin** [terraform-providers/terraform-provider-aws#11038]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.16
+ provider.aws v2.40.0

### Affected Resource(s)

* aws_batch_job_definition

### Terraform Configuration Files

```hcl
   # for the jsonencode magic
   resource "aws_batch_job_definition" "batch" {
     count                = var.create ? 1 : 0
     name                 = var.name
     type                 = "container"
     container_properties = replace(replace("${jsonencode(local.container_properties)}", "/\"(true|false|[[:digit:]]+)\"/", "$1"), "string:", "")

     lifecycle {
       ignore_changes = [container_properties]
     }
   }
```

### Expected Behavior
No infrastructure changes

### Actual Behavior

```hcl

  + resource "aws_batch_job_definition" "batch" {
      + arn                  = (known after apply)
      + container_properties = jsonencode(
            {
              + image      = ""
              + jobRoleArn = "arn:aws:iam::123456789:role/dev-batchContainerRole"
              + memory     = 512
              + vcpus      = 2
            }
        )
      + id                   = (known after apply)
      + name                 = "dev"
      + revision             = (known after apply)
      + type                 = "container"
    }
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/5924

**Comment by bflad** [comment]
A potential fix for this has been merged and will release with version 2.48.0 of the Terraform AWS Provider, Thursday this week.
