### ISSUE TITLE
Add Tag Policies to Organizations Support

### ISSUE THREAD

**Issue by curator** [terraform-providers/terraform-provider-aws#11032]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon announced support for Tag Policies to manage intra-organization tagging standards and support should be added for this construct.

### New or Affected Resource(s)

* aws_organizations_policy

### Potential Terraform Configuration

```hcl
resource "aws_organizations_policy" "tags_example" {
  name = "tags_example"
  type = ?? # Currently unknown
  content = <<CONTENT
{
    "tags": {
        "CostCenter": {
            "tag_key": {
                "@@assign": "CostCenter"
            },
            "tag_value": {
                "@@assign": [
                    "100",
                    "200"
                ]
            },
            "enforced_for": {
                "@@assign": [
                    "secretsmanager:*"
                ]
            }
        }
    }
}
CONTENT
}
```

### References

* https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_tag-policies.html
* https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_example-tag-policies.html#tag-policy-example-key-case

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-launches-tag-policies/).
[Blog post](https://aws.amazon.com/blogs/aws/new-use-tag-policies-to-manage-tags-across-multiple-aws-accounts/).

**Comment by DavidFluck** [comment]
I'm happy to submit a PR for this soon. I have a work in progress branch, and I can already create/update/destroy tag policies. I want to verify that functionality is solid, and then I would just have to update the tests and documentation.

**Comment by bflad** [comment]
Related feature request to track `aws_organizations_organization` resource support for `TAG_POLICY` as valid `enabled_policy_types` value: #11202

**Comment by khurdz** [comment]
Hi,
Any update on this ?
We are looking forward to testing and using it soon :)

**Comment by alangford** [comment]
testing out 2.46.0 and getting this error when changing the type to TAG_POLICY

Error: expected type to be one of [SERVICE_CONTROL_POLICY], got TAG_POLICY


`resource "aws_organizations_policy" "force_account_name" {
  name        = "force-account-name"
  description = "This policy is to force the use of the account name tag. this tag is required when determining which account the resource resides in."
  type        = "TAG_POLICY"
  content     = <<CONTENT
{
    "tags": {
        "account-name": {
            "tag_key": {
                "@@assign": "account-name"
            },
            "enforced_for": {
                "@@assign": [
                    "apigateway:apikeys",
                    "apigateway:domainnames",
                    "apigateway:restapis",
                    "apigateway:stages",
                    "appmesh:*",
                    "athena:*",
                    "acm:*",
                    "cloudfront:*",
                    "cloudtrail:*",
                    "cloudwatch:*",
                    "events:*",
                    "codebuild:*",
                    "codecommit:*",
                    "codepipeline:*",
                    "cognito-identity:*",
                    "cognito-idp:*",
                    "comprehend:*",
                    "config:*",
                    "directconnect:*",
                    "dms:*",
                    "dynamodb:*",
                    "ec2:capacity-reservation",
                    "ec2:client-vpn-endpoint",
                    "ec2:customer-gateway",
                    "ec2:dhcp-options",
                    "ec2:elastic-ip",
                    "ec2:fleet",
                    "ec2:fpga-image",
                    "ec2:host-reservation",
                    "ec2:image",
                    "ec2:instance",
                    "ec2:internet-gateway",
                    "ec2:launch-template",
                    "ec2:natgateway",
                    "ec2:network-acl",
                    "ec2:network-interface",
                    "ec2:reserved-instances",
                    "ec2:route-table",
                    "ec2:security-group",
                    "ec2:snapshot",
                    "ec2:spot-instance-request",
                    "ec2:subnet",
                    "ec2:traffic-mirror-filter",
                    "ec2:traffic-mirror-target",
                    "ec2:traffic-mirror-session",
                    "ec2:volume",
                    "ec2:vpc",
                    "ec2:vpc-endpoint",
                    "ec2:vpc-endpoint-service",
                    "ec2:vpc-peering-connection",
                    "ec2:vpn-connection",
                    "ec2:vpn-gateway",
                    "elasticfilesystem:*",
                    "elasticbeanstalk:application",
                    "elasticbeanstalk:applicationversion",
                    "elasticbeanstalk:configurationtemplate",
                    "elasticbeanstalk:platform",
                    "ecs:task-set",
                    "ecs:cluster",
                    "ecs:service",
                    "elasticache:*",
                    "elasticloadbalancing:*",
                    "firehose:*",
                    "fsx:*",
                    "iotanalytics:*",
                    "iotevents:*",
                    "kinesisanalytics:*",
                    "kms:*",
                    "lambda:*",
                    "rds:cluster-pg",
                    "rds:es",
                    "rds:og",
                    "rds:pg",
                    "rds:ri",
                    "rds:secgrp",
                    "rds:subgrp",
                    "redshift:*",
                    "ram:*",
                    "resource-groups:*",
                    "route53:hostedzone",
                    "route53resolver:*",
                    "s3:bucket",
                    "secretsmanager:*",
                    "sqs:queue",
                    "states:activity",
                    "storagegateway:*",
                    "ssm:automation-execution",
                    "ssm:document",
                    "ssm:opsitem",
                    "ssm:session",
                    "ssm:patchbaseline",
                    "ssm:maintenancewindowtask",
                    "ssm:managed-instance",
                    "workspaces:*"
                ]
            }
        }
    }
}
CONTENT
}`

**Comment by ericksoen** [comment]
@alangford There's a few different places the `TAG_POLICY` needs to be enabled to be fully functional. In v2.46.0, a change was merged to allow enabling it at the organization level, but did not include any changes to permit is as a `TAG_POLICY` type for the `aws_organizations_policy` resource. The PR for that change is referenced above #11612 (I've resolved the WIP items, but don't have any ETA on when it will be reviewed, merged, or released)

**Comment by alangford** [comment]
Thank you @ericksoen I will close #11754 for being invalid

**Comment by bflad** [comment]
Support for tag policies has been merged into the `aws_organizations_policy` and `aws_organizations_policy_attachment` resources, which will release with version 2.48.0 of the Terraform AWS Provider, tomorrow. Thanks to @ericksoen for the implementation. 👍 

Please note that if you use restrictive IAM policies for the Terraform execution, that the underlying API call for the `aws_organizations_policy_attachment` resource has switched from `ListPoliciesForTarget` to `ListTargetsForPolicy`.
