### ISSUE TITLE
KMS asymmetric keys

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Key Management Service (KMS) now enables you to create and use asymmetric customer master keys (CMKs) and data key pairs.

### New or Affected Resource(s)

* [`aws_kms_key`](https://www.terraform.io/docs/providers/aws/r/kms_key.html)

### Potential Terraform Configuration

```hcl
resource "aws_kms_key" "example" {
  key_usage                = "SIGN_VERIFY"
  customer_master_key_spec = "ECC_NIST_P384"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-key-management-service-supports-asymmetric-keys/).
[Blog post](https://aws.amazon.com/blogs/security/digital-signing-asymmetric-keys-aws-kms/).

Requires [AWS SDK v1.25.42](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.42):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.47.0 of the Terraform AWS Provider, tomorrow. Thanks to @ewbankkit for the implementation. 👍
