### ISSUE TITLE
RDS Aurora cluster endpoint tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RDS Aurora cluster endpoints can now be tagged.

### New or Affected Resource(s)

* [`aws_rds_cluster_endpoint`](https://www.terraform.io/docs/providers/aws/r/rds_cluster_endpoint.html)

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_endpoint" "example" {
  tags = {
    Name = "Example"
  }
}
```

### References

Requires [AWS SDK v1.25.42](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.42):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by bflad** [comment]
Support for `aws_rds_cluster_endpoint` tagging has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
