### ISSUE TITLE
Private IP address selection for internal NLBs

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now select the private IPv4 address that is used for your internal-facing Network Load Balancer, on a per-subnet basis.

### New or Affected Resource(s)

* [`aws_lb`](https://www.terraform.io/docs/providers/aws/r/lb.html)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Blog post](https://aws.amazon.com/blogs/aws/aws-load-balancer-update-lots-of-new-features-for-you/).

Requires [AWS SDK v1.25.42](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.42):
* https://github.com/terraform-providers/terraform-provider-aws/pull/10955

**Comment by bflad** [comment]
Hi folks 👋  This functionality has been merged and will release with version 3.1.0 of the Terraform AWS Provider, next Thursday. Thanks to @KadenLNelson for the implementation. 👍
