### ISSUE TITLE
ECS won't accept memoryReservation parameter.

### ISSUE THREAD

**Issue by kurtwheeler** [terraform-providers/terraform-provider-aws#1104]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- ecs_task_definition
- aws_ecs_service

### Terraform Configuration Files
```hcl
resource "aws_ecs_task_definition" "cognoma-nginx" {
  family = "cognoma-nginx"
  container_definitions = "${file("task-definitions/nginx.json.secret")}"
}

resource "aws_ecs_service" "nginx" {
  name = "cognoma-nginx"
  cluster = "${aws_ecs_cluster.cognoma.id}"
  task_definition = "${aws_ecs_task_definition.cognoma-nginx.arn}"
  desired_count  = 2
  deployment_minimum_healthy_percent = 50
  deployment_maximum_percent = 100
  iam_role = "${aws_iam_role.ecs-service-role.name}"
  depends_on = ["aws_iam_role_policy.ecs-service"]

  load_balancer {
    elb_name = "${aws_elb.cognoma-nginx.name}"
    container_name = "cognoma-nginx"
    container_port = 80
  }

  lifecycle {
    ignore_changes = ["task_definition"]
  }
}
```
where the `task-definitions/nginx.json.secret` file contains:
```json
[
    {
        "volumesFrom": [],
        "extraHosts": null,
        "dnsServers": null,
        "disableNetworking": null,
        "dnsSearchDomains": null,
        "portMappings": [
            {
                "hostPort": 80,
                "containerPort": 80,
                "protocol": "tcp"
            }
        ],
        "hostname": null,
        "essential": true,
        "entryPoint": [],
        "mountPoints": [],
        "name": "cognoma-nginx",
        "memoryReservation": 128,
        "ulimits": null,
        "dockerSecurityOptions": null,
        "environment": [],
        "links": null,
        "workingDirectory": null,
        "readonlyRootFilesystem": null,
        "image": "934349674827.dkr.ecr.us-east-1.amazonaws.com/cognoma-nginx:latest",
        "command": null,
        "user": null,
        "dockerLabels": null,
        "logConfiguration": null,
        "privileged": null,
        "memoryReservation": null
    }
]
```

### Debug Output
Running terraform with the `TF_LOG` variable set caused such a huge amount of output that it overwrote my entire terminal. If it's really that important I can pipe it into a file and submit that as a gist, however I think the following output really shows the issue pretty well:
```
Error applying plan:

1 error(s) occurred:

* aws_ecs_task_definition.cognoma-nginx: 1 error(s) occurred:

* aws_ecs_task_definition.cognoma-nginx: ClientException: Invalid setting for container 'cognoma-nginx'. At least one of 'memory' or 'memoryReservation' must be specified.
	status code: 400, request id: ae55365a-65b7-11e7-b5c5-e59b83c17c53
* aws_ecs_service.cognoma-task-service: 1 error(s) occurred:
```

### Expected Behavior
My task definition should have been updated successfully.

### Actual Behavior
I got an error response from Amazon's API saying `At least one of 'memory' or 'memoryReservation' must be specified.` which is wrong because I did in fact specify memoryReservation.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

NOTE:
This does seem to be an issue with AWS' API, however I only have a basic service plan so I cannot open a technical support ticket with them. I'm wondering if anyone else has seen this and/or potentially discovered workarounds.

**Comment by bflad** [comment]
@kurtwheeler are you still having this issue? For reference, in our environment we use `memoryReservation` in container definitions without issue on recent versions of the AWS provider. Likely this was fixed in a AWS SDK update awhile back, similar to #2174.

**Comment by aliusmiles** [comment]
Confirmed on:
terraform: v0.10.8
terraform-provider-aws: v1.9.0

**Comment by bflad** [comment]
@aliusmiles confirmed `memoryReservation` is working or not working? 😉

**Comment by aliusmiles** [comment]
Sorry for the vague reply, confirmed that `memoryReservation` is working with terraform-provider-aws v1.9.0.

**Comment by bflad** [comment]
Great news! I'll close this issue then.
