### ISSUE TITLE
nodejs12.x runtime for lambda functions not available

### ISSUE THREAD

**Issue by akumar-bmj** [terraform-providers/terraform-provider-aws#11067]
terraform version as follows
terraform -version
Terraform v0.11.14

I read that AWS now support nodejs version 12.x. Is this available in terraform.

When I updated my terraform code I recieved this error
expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 go1.x java8 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x provided python2.7 python3.6 python3.7 ruby2.5], got nodejs12.x

**Comment by ewbankkit** [comment]
@akumar-bmj AWS Lambda support for Java 11, Node.js 12 and Python 3.8 was added in https://github.com/terraform-providers/terraform-provider-aws/pull/10938 and released in [version 2.39.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/v2.39.0/CHANGELOG.md).

**Comment by akumar-bmj** [comment]
Thanks @ewbankkit
