### ISSUE TITLE
EKS Windows Node Group

### ISSUE THREAD

**Issue by gibsonje** [terraform-providers/terraform-provider-aws#11065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to create Windows node groups for EKS.

The EKS docs show that with eksctl you can create windows node groups but the terraform eks node group module doesn't allow it.

https://docs.aws.amazon.com/eks/latest/userguide/launch-windows-workers.html

```
eksctl create nodegroup \
--region us-west-2 \
--cluster windows \
--name windows-ng \
--node-type t2.large \
--nodes 3 \
--nodes-min 1 \
--nodes-max 4 \
--node-ami-family WindowsServer2019FullContainer
```

I see a list of amis here:
https://github.com/weaveworks/eksctl/blob/ef183767fa7a19205d02e63375aacb889b55b732/pkg/ami/static_resolver_ami.go

Docs show this:
https://eksctl.io/usage/custom-ami-support/

With 4 AMI families, Amazon Linux, Ubuntu, Windows Server Full, Windows Server Core. 

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "windows_nodes" {
  cluster_name    = "foo"
  node_group_name = "foo-windows"
  node_role_arn   = "${data.aws_iam_role.node.arn}"
  subnet_ids      = ["${data.aws_subnet_ids.eks_private.ids}"]

  ami_type        = "WindowsServer2019FullContainer"

  scaling_config {
    desired_size = "1"
    max_size     = "5"
    min_size     = "1"
  }
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
Related:
* https://github.com/aws/containers-roadmap/issues/584

**Comment by ewbankkit** [comment]
@gibsonje The `eksctl` command you showed does not create an [EKS managed nodegroup](https://eksctl.io/usage/eks-managed-nodegroups/), instead creating a standard [unmanaged nodegroup](https://eksctl.io/usage/windows-worker-nodes/).
I think there need to be enhancements from Amazon to enabled managed Windows nodegroups.

**Comment by bflad** [comment]
Hi @gibsonje 👋 Thank you for submitting this. As mentioned above, this functionality is not directly available via the EKS API at the moment. This support can be tracked at https://github.com/aws/containers-roadmap/issues/584. When the API support becomes available we will support this directly in the Terraform AWS Provider, but for now we will opt to close this feature request until that time comes. 👍

**Comment by gibsonje** [comment]
Sounds good, thanks!
