### ISSUE TITLE
S3 Access Points support

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon S3 Access Points is a new S3 feature that simplifies managing data access at scale for shared data sets on Amazon S3.

### New or Affected Resource(s)

* `aws_s3_access_point`
* [`aws_s3_bucket_object`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_object.html) - Need to verify that objects can be accessed through [access point ARNs](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html)

### Potential Terraform Configuration

```hcl
data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "example" {
  bucket = "example"
}

resource "aws_s3_access_point" "example" {
  account_id = data.aws_caller_identity.current.account_id
  bucket     = aws_s3_bucket.example.id
  name       = "example"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-s3-access-points-manage-data-access-at-scale-shared-data-sets/).
[Blog post](https://aws.amazon.com/blogs/aws/easily-manage-shared-data-sets-with-amazon-s3-access-points/).
[Developer guide](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-points.html).

Requires [AWS SDK v1.25.46](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.46):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11116

**Comment by bflad** [comment]
Support for a new `aws_s3_access_point` resource has been merged and will release with version 2.51.0 of the Terraform AWS Provider, end of this week. Thanks to @ewbankkit for the implementation. 👍
