### ISSUE TITLE
Unable to change certificate authority of a MySQL RDS instance to rds-ca-2019

### ISSUE THREAD

**Issue by lyenliang** [terraform-providers/terraform-provider-aws#11131]
According to #10417, this bug was fixed in AWS Provider v2.37.0. But why do I still encounter it in v2.40? 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.17
+ provider.aws v2.40.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
provider "aws" {
  region     = "ap-northeast-1"
  version    = "~> 2.40"    
}

resource "aws_db_instance" "test-ca-db" {
  instance_class       = "db.t3.micro"
  identifier           = "test-ca-db"
  snapshot_identifier  = "arn:aws:rds:ap-northeast-1:123456789123:snapshot:rds:my-snapshot"
  vpc_security_group_ids = ["sg-c98ejaq1","sg-06fue8sa4301cd064"]
  parameter_group_name = "my_group"
  publicly_accessible  = false
  password             = "1234abcd"
  skip_final_snapshot  = true
  storage_encrypted    = true
  ca_cert_identifier   = "rds-ca-2019"
}
```

### Expected Behavior

The RDS instance's certificate authority should be changed to `rds-ca-2019`. 

### Actual Behavior

The RDS instance's certificate authority remains in `rds-ca-2015`. 

### Steps to Reproduce

1. `terraform apply`

### References

* #10417, #10490

**Comment by huseyinham** [comment]
Hopefully this doesn't sound patronising, but someone in the PR you referenced mentioned they needed to set `apply_immediately = true` for it to actually take effect. Would that solve your issue? Or is this behaviour after you tried that?

Link for reference:
https://github.com/terraform-providers/terraform-provider-aws/issues/10417#issuecomment-557238558

**Comment by lyenliang** [comment]
Thank you @huseyinham, `apply_immediately = true` solves my problem.
