### ISSUE TITLE
Amazon API Gateway HTTP APIs

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon API Gateway offers faster, cheaper, simpler APIs using HTTP APIs.

**The API Gateway HTTP API is in preview.**

### New or Affected Resource(s)

* [`aws_api_gateway_v2_api`](https://github.com/terraform-providers/terraform-provider-aws/pull/8842)
* ...

### Potential Terraform Configuration

```hcl
resource "aws_api_gateway_v2_api" "example" {
  protocol_type = "HTTP"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-api-gateway-offers-faster-cheaper-simpler-apis-using-http-apis-preview/).
[Blog post](https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/).
[Developer guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html).

Requires [AWS SDK v1.25.48](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.48):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11149

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7004

**Comment by rpstreef** [comment]
This is an apigatewayv2 resource just like the websockets API

**Comment by bionicles** [comment]
here is the line of code which really matters: 
https://github.com/aws/aws-sdk-go/blob/2dfbfbc3d3a60ab6ef72537b890eff246f6cb1f2/models/apis/apigatewayv2/2018-11-29/api-2.json#L4575

**Comment by ewbankkit** [comment]
HTTP APIs have are now GA.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/03/api-gateway-private-integrations-aws-elb-cloudmap-http-apis-release/).
[Blog post](https://aws.amazon.com/blogs/compute/building-better-apis-http-apis-now-generally-available/).

Requires [AWS SDK v1.29.23](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.23):
* https://github.com/terraform-providers/terraform-provider-aws/pull/12359

**Comment by AlienHoboken** [comment]
@ewbankkit looking at this it seems that there is currently no way to define routes or integrations yet, just the top-level gateway resource.

Is this something you have in mind or is it something someone else would need to take up the mantle on?

Thanks for the great PR and getting this out there day 1 of GA. Many people are looking forward to leveraging HTTP APIs and your work helps make this possible 🎉

**Comment by ewbankkit** [comment]
Preview functionality:
* [`aws_apigatewayv2_api`](https://www.terraform.io/docs/providers/aws/r/apigatewayv2_api.html) resource
  * Add `cors_configuration` attribute
  * Add `credentials_arn`, `route_key` and `target` attributes to support [_quick create_](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-basic-concept.html#apigateway-definition-quick-create).
    This will create API Gateway managed [`aws_apigatewayv2_integration`](https://github.com/terraform-providers/terraform-provider-aws/pull/8949), [`aws_apigatewayv2_route`](https://github.com/terraform-providers/terraform-provider-aws/pull/8881) and [`aws_apigatewayv2_stage`](https://github.com/terraform-providers/terraform-provider-aws/pull/9232) resources.
* [`aws_apigatewayv2_authorizer`](https://github.com/terraform-providers/terraform-provider-aws/pull/9228) resource
  * Add `jwt_configuration` attribute to support [JSON Web Tokens](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-jwt-authorizer.html)
* [`aws_apigatewayv2_stage`](https://github.com/terraform-providers/terraform-provider-aws/pull/9232) resource
   * Investigate [`DeleteRouteSettings`](https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-stages-stagename-routesettings-routekey.html#apis-apiid-stages-stagename-routesettings-routekeydelete) API
* [`aws_apigatewayv2_deployment`](https://github.com/terraform-providers/terraform-provider-aws/pull/9245) resource
  * Add [`payload_format_version`](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format) attribute
* [`aws_apigatewayv2_domain_name`](https://github.com/terraform-providers/terraform-provider-aws/pull/9391) resource
  * Use `DomainNameStatus`

**Comment by vincenting** [comment]
Hi, any idea on providing a body attribute for the aws_api_gateway_v2_api resource.  It has similar behaviour to the body attribute in `resource_aws_api_gateway_rest_api.go`, but here we have to call different API to create (ImportApi) and update(ReImportApi) the API.

Is there any plan for that, it will help the developers like me who want to migrate the RestAPIGateway based infra to the new version. (I haven't developed GoLang for a long while, I will try to create an MR for that too)

**Comment by ewbankkit** [comment]
@vincenting My initial thinking around this was to recommend using the [instructions in the developer guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-open-api.html#http-api-import.example) to import the API using the AWS CLI and then use `terraform import` to adopt the API into Terraform. Either way I think you would have to write the HCL code for the resource.

**Comment by AleksandarTokarev** [comment]
Sorry for the comment, but i am trying to understanding some things,
I want to use Terraform to create resources for HTTP API Gateway (which got in GA recently).
Is that supported in terraform yet? If so what version of terraform i need for that?
Thanks a lot

**Comment by ewbankkit** [comment]
@AleksandarTokarev The ability to manage the base HTTP API resource was released in v2.53.0.
See [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/7004#issuecomment-606705835) on support for the additional relevant resources.

**Comment by spaszek** [comment]
@AleksandarTokarev There are no required resources [from this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/7004#issuecomment-511237779) in Terraform yet. AWS is working on it, but WebSockets are higher on the priority list(as they said in the comment linked in above comment). I wouldn't expect HTTP API to be available in the next few months.

**Comment by podrezo** [comment]
Hi there, I'm currently having an issue with the `aws_apigatewayv2_stage` resource type, used for an HTTP API, where on initial create it succeeds but when trying to make any kind of change to any resource (not necessarily even this resource) it tries to update the `logging_level` property to "OFF" (which is the default) but it doesn't succeed because of error "Execution logs are not supported on protocolType HTTP". Should I open an issue for this problem or will this be fixed as part of this PR? Is there any workaround for this? Thanks!

**Comment by LaurenceGA** [comment]
@podrezo 
See this issue: #12893
There is a PR open too.

**Comment by podrezo** [comment]
@LaurenceGA amazing - thanks so much!

**Comment by ewbankkit** [comment]
@podrezo @LaurenceGA Please upvote the linked issue if you haven't already.

**Comment by luneo7** [comment]
I am also having issues with aws_apigatewayv2_integration, when creating it is ok, but when updating it is always trying to set passthrough_behavior = WHEN_NO_MATCH when doing integration with VPC_LINK

**Comment by luneo7** [comment]
To bypass the aws_apigatewayv2_stage error I had to add:
```
lifecycle {
    ignore_changes = [deployment_id, default_route_settings]
  }
```
And to also stop receiving changes to passthrough_behavior in aws_apigatewayv2_integration had to add:
```
lifecycle {
    ignore_changes = [passthrough_behavior]
  }
```

**Comment by shouze** [comment]
@luneo7 same thing for us with the passthrough_behavior on each update.

**Comment by acburdine** [comment]
Created https://github.com/terraform-providers/terraform-provider-aws/pull/13062 to address the passthrough_behavior issue 😄

**Comment by warrenstephens** [comment]
I have to use an ignore_changes block on my **aws_apigatewayv2_stage** resource with AWS provider 2.70.0 -- this has no other fix currently?

`
    lifecycle {
        ignore_changes = [deployment_id]
    }
`

**Comment by ewbankkit** [comment]
@warrenstephens The issue with perpetual diffs on `deployment_id` has been raised in #13633 and fixed in #13644 - scheduled to be released in v3.0.0 of the provider.

**Comment by warrenstephens** [comment]
@ewbankkit Thank you.  I have my first stabilized aws_apigatewayv2_api with WEBSOCKET protocol -- after a few days of ramping up on AWS gateway.

I was happy to learn that I can get JSON responses from both my $default route and named route despite the AWS docs that seemed to hint otherwise.

**Comment by warrenstephens** [comment]
@ewbankkit I have been fighting for a week since my post above to get my aws_apigatewayv2_api with WEBSOCKET protocol working with Cognito (OAuth "client_credentials") having no luck, only 403 errors -- is there some sample code having that integration available somewhere?  I am willing to clean gutters, chop firewood, etc, to get it working!

**Comment by warrenstephens** [comment]
I found the fix.  The "Action" part of the policy that is returned by the authorizer lambda must be an array of string, not a single string.  Like this:

`"Action": [ "execute-api:Invoke" ],`

**Comment by ewbankkit** [comment]
With the merge of #12567, scheduled for release with v3.3.0 of the Terraform AWS Provider, I am going to close this original API Gateway HTTP APIs issue.
Please open new issues for any feature requests or bug reports.
