### ISSUE TITLE
Add support for ECS capacity providers

### ISSUE THREAD

**Issue by ryndaniels** [terraform-providers/terraform-provider-aws#11150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Based on [this announcement](https://aws.amazon.com/blogs/aws/aws-ecs-cluster-auto-scaling-is-now-generally-available/), we want to add support for ECS capacity providers.

### New or Affected Resource(s)

* aws_ecs_cluster (add support for `PutClusterCapacityProviders` in update method, plus `default_capacity_provider_strategy` and `capacity_providers` arguments in schema)
* awc_ecs_service (add `capacity_provider_strategy` to schema)
* aws_ecs_capacity_provider (new resource)

### New Resource: aws_ecs_capacity_provider

Create: CreateCapacityProvider
Read: DescribeCapacityProvider
Update: UpdateCapacityProvider
Delete: DeleteCapacityProvider

```hcl
resource "aws_ecs_capacity_provider" "example" {
  name = "example" # Type: TypeString, Required: true
  tags = {}        # Type: TypeMap, Required: true

  auto_scaling_group_provider {         # Type: TypeList, Required: true, MaxItems: 1, Elem: *schema.Resource
    auto_scaling_group_arn = ""         # Type: TypeString, Required: true
    managed_termination_protection = "" # Type: TypeString, Required: true

    managed_scaling {               # Type: TypeList, Required: true, MaxItems: 1, Elem: *schema.Resource
      maximum_scaling_step_size = 1 # Type: TypeInt, Optional: true, Default: 10000
      minimum_scaling_step_size = 1 # Type: TypeInt, Optional: true, Default: 1
      status = ""                   # Type: TypeString, Optional: true (maybe Default: ENABLED)
      target_capacity = 1           # Type: TypeInt, Optional: true
    }
  }
}
```

### Updated Resource: aws_ecs_cluster

(Only showing new arguments/API calls)

Update: PutClusterCapacityProviders

```hcl
resource "aws_ecs_cluster" "example" {
  capacity_providers = [""] # Type: TypeList, Optional: true, Elem: *schema.Schema TypeString

  default_capacity_provider_strategy { # Type: TypeList, Optional: true, MaxItems: 1, Elem: *schema.Resource
    base = 1                           # Type: TypeInt, Optional: true,
    capacity_provider = ""             # Type: TypeString, Required: true
    weight = 1                         # Type: TypeInt, Optional: true
  }
}
```

### Updated Resource: aws_ecs_service

(Only showing new arguments, no new API calls)

```hcl
resource "aws_ecs_service" "example" {
  capacity_provider_strategy { # Type: TypeSet, Optional: true, Elem: *schema.Resource
    base = 1                   # Type: TypeInt, Optional: true,
    capacity_provider = ""     # Type: TypeString, Required: true
    weight = 1                 # Type: TypeInt, Optional: true
  }
}
```

**Comment by bflad** [comment]
Initial support for ECS Capacity Providers has been merged and will release with version 2.42.0 of the Terraform AWS Provider, shortly. This was a great effort by a few folks including @ryndaniels, @aeschright, @gdavison so kudos to those involved in making this happen. 🚀
