### ISSUE TITLE
Changing name of "A" record is incorrect

### ISSUE THREAD

**Issue by gorlovjob** [terraform-providers/terraform-provider-aws#11156]
### Terraform Version

Terraform v0.12.17

### AWS_provider Version

aws_v2.41.0_x4

### Affected Resource(s)

* aws_route53_record 

### Terraform Configuration Files
```
resource "aws_route53_zone" "private" {
  name = var.domain_name
  vpc {
    vpc_id = var.vpc_id
  }
  comment = var.comment
  force_destroy = true
  tags = var.tags
}

resource "aws_route53_record" "www" {
  count       = length(var.records)
  zone_id = aws_route53_zone.private.zone_id
  name    = var.records.*.hostname[count.index]
  type    = var.records.*.type[count.index]
  ttl     = var.records.*.ttl[count.index]
  records = [var.records.*.ip[count.index]]

  depends_on = [aws_route53_zone.private]
}
```
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I created "A" record. In AWS web console I saw it. Now I want change name the record. Terraform have to delete old record and create new.

### Actual Behavior

Terraform work without problem: old record deleted, new record created, but in AWS web console I see and new, and old record.

### Steps to Reproduce

1. Create "A" record throught terraform.
2. Change name of "A" record in terraform file.
3. Terraform apply.
4. Look in AWS web console.

**Comment by bflad** [comment]
Hi @gorlovjob 👋 Thank you for reporting this and sorry you ran into trouble. This appears to be very similar in nature or a duplicate to #9024, so to consolidate any efforts and discussions on this issue, I'm going to close this issue in preference of the existing one.
