### ISSUE TITLE
"deregistration_delay.timeout_seconds" is not parsed from target group attributes

### ISSUE THREAD

**Issue by hisdream86** [terraform-providers/terraform-provider-aws#11167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`deregistration_delay.timeout_seconds` is not parsed from target group attributes when the function **flattenAwsLbTargetGroupResource()** is called.

https://github.com/terraform-providers/terraform-provider-aws/blob/3bad5dbd5d8df67cb85dc1bfc838bda295134000/aws/resource_aws_lb_target_group.go#L588

This causes that the "deregistration_delay" always imported as "null" with `terraform init` command.

`"deregistration_delay": null,`

### New or Affected Resource(s)

* aws_lb_target_group

### Potential Terraform Configuration

```
resource "aws_lb_target_group" "my_nlb_tg" {
  name = "my-nlb-tg"
  vpc_id = var.vpc.vpc_id
  target_type = "instance"
  protocol = "TCP"
  port = 80
}
```

`$ terraform import aws_lb_target_group.my_nlb_tg {arn}`

### References

* #0000

**Comment by markbaird** [comment]
For some reason `deregistration_delay` is working for ALB but ignored for NLB.

**Comment by hisdream86** [comment]
I got it. thank 👍
