### ISSUE TITLE
Feature Request: WAFv2 Regex Pattern Set Data Source

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#11179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In November 2019, AWS released a new version of the WAF API, [WAFv2](https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html), which offers improved functionality over the previous WAF API ("WAF Classic") such as [Managed Rules](https://github.com/terraform-providers/terraform-provider-aws/issues/11046) and WAF Capacity Units. This new API requires separate Terraform resource implementations from the previous resource implementations.

### New Data Source

* aws_wafv2_regex_pattern_set

### Potential Terraform Configuration

```hcl
data "aws_wafv2_regex_pattern_set" "example" {
  name = ""
  scope = ""
}
```

### References

- Requires: https://github.com/terraform-providers/terraform-provider-aws/pull/11172
- API Reference: https://docs.aws.amazon.com/waf/latest/APIReference/API_Operations_AWS_WAFV2.html
- SDK Reference: https://docs.aws.amazon.com/sdk-for-go/api/service/wafv2/

**Comment by anGie44** [comment]
The feature has been merged and will release with `v2.63.0` of the Terraform AWS Provider, expected in this week's release.
