### ISSUE TITLE
aws_organizations_organization: enable TAG_Policy for enabled_policy_types

### ISSUE THREAD

**Issue by GeorgeShort** [terraform-providers/terraform-provider-aws#11202]
When trying to create an aws_organizations_organization with below configuration:

resource "aws_organizations_organization" "org" {
  aws_service_access_principals = [
    "tagpolicies.tag.amazonaws.com"
  ]

  feature_set = "ALL"
  
  aws_service_access_principals = ["SERVICE_CONTROL_POLICY", "TAG_POLICY"]
}

Error:
expected enabled_policy_types.0 to be one of [SERVICE_CONTROL_POLICY], got TAG_POLICY

API Reference: 
https://docs.aws.amazon.com/organizations/latest/APIReference/API_EnablePolicyType.html

**Comment by bflad** [comment]
Related feature request to track `aws_organizations_policy` resource support for `TAG_POLICY` as valid `type` value: #11032

**Comment by bflad** [comment]
Support for `TAG_POLICY` in the `aws_organizations_organization` resource has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week. Thanks to @nikolaifa for the implementation. 👍
