### ISSUE TITLE
Open Monitoring (Prometheus) isn't available for aws_msk_cluster

### ISSUE THREAD

**Issue by Alexx-G** [terraform-providers/terraform-provider-aws#11215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS MSK supports monitoring either via CloudWatch or OpenMonitoring (prometheus), however this option doesn't seem to be available via `aws_msk_cluster` resource.
Since this option is available in SDK https://docs.aws.amazon.com/msk/1.0/apireference/clusters.html#clusters-schemas , perhaps it can be implemented in the aws-provider as well.

### New or Affected Resource(s)

* aws_msk_cluster

**Comment by marcoreni** [comment]
This requires SDK v1.25.49 https://github.com/terraform-providers/terraform-provider-aws/pull/11210

**Comment by ddcprg** [comment]
Is no one working on this at the moment? I may be able to help with this one

**Comment by marcoreni** [comment]
@ddcprg see #11451

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.51.0 of the Terraform AWS Provider, end of next week. Thanks to @marcoreni for the implementation. 👍

**Comment by Alexx-G** [comment]
Thanks a ton @marcoreni and @bflad ! :1st_place_medal:
