### ISSUE TITLE
aws_codebuild_project queued_timeout option missing

### ISSUE THREAD

**Issue by hryamzik** [terraform-providers/terraform-provider-aws#11213]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Queued timeout](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-queuedtimeoutinminutes) can't be set with terraform.

### New or Affected Resource(s)

* aws_codebuild_project

### Potential Terraform Configuration

```hcl
resource "aws_codebuild_project" "example" {
  name           = "test-project"
  description    = "test_codebuild_project"
  service_role   = "${aws_iam_role.example.arn}"
  build_timeout  = "5"
  queued_timeout = "30"
...
```

**Comment by moraneva** [comment]
PR submitted #11261
