### ISSUE TITLE
Obscure error when aws kinesis firehose delivery stream s3 buffer interval is too low

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-aws#1122]
I tried setting up a aws_kinesis_firehose_delivery_stream and set `s3_configuration.buffer_interval` to `30`. This is below the minimum which is `60`. I was greeted by this super unhelpful error:

```
* aws_kinesis_firehose_delivery_stream.deck_archetype_log_stream: 1 error(s) occurred:

* aws_kinesis_firehose_delivery_stream.deck_archetype_log_stream: [WARN] Error creating Kinesis Firehose Delivery Stream: "1 validation error(s) found.", code: "InvalidParameter"
```

It took me a while to figure out that the problem was with the buffer interval. I don't know if the problem is in terraform or AWS, but it'd be nice to check for the minimum at plan time either way.

**Comment by ApsOps** [comment]
+1 It gives a similar error when password field size is less than 6. Interestingly, updating the stream gives proper error:
```
* aws_kinesis_firehose_delivery_stream.kinesis_firehose_redshift: Error Updating Kinesis Firehose Delivery Stream: "test_stream"
InvalidParameter: 1 validation error(s) found.
- minimum field size of 6, UpdateDestinationInput.RedshiftDestinationUpdate.Password.
```
