### ISSUE TITLE
Missing argument reference in document

### ISSUE THREAD

**Issue by hangxie** [terraform-providers/terraform-provider-aws#11230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v2.41.0

### Affected Resource(s)
data/aws_billing_service_account
data/aws_ebs_default_kms_key
data/aws_ebs_encryption_by_default
data/aws_inspector_rules_packages

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Document provides argument reference that matches source code, or set both `Required` and `Optional` to false to indicate the attribute is not an argument.

### Actual Behavior
Missing argument reference in document.

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
1. data/aws_billing_service_account
  * source: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_billing_service_account.go#L15-L20 (`arn`)
   * doc: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/billing_service_account.html.markdown
2. data/aws_ebs_default_kms_key
  * source: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_ebs_default_kms_key.go#L15-L19 (`key_arn`)
  * doc: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/ebs_default_kms_key.html.markdown
3. data/aws_ebs_encryption_by_default
  * source: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_ebs_encryption_by_default.go#L15-L19 (`enabled`)
  * https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/ebs_encryption_by_default.html.markdown
4. data/aws_inspector_rules_packages
  * source: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_inspector_rules_packages.go#L18-L24 (`arns`)
  * doc: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/inspector_rules_packages.html.markdown

**Comment by bflad** [comment]
Hi @hangxie 👋  Thank you for filing this. Looking at the source code and documentation source, they all look correct. For read-only schema attributes, the preference is to only set `Computed: true` and omit the implicit `Required: false` and `Optional: false`. This is a stylistic choice for many Terraform Providers and one we enforce via static analysis at the moment. Since we do not plan on changing this stylistic choice within this provider as it matches the broader ecosystem of Terraform Provider schema declarations, I'm going to close this.
