### ISSUE TITLE
Provide ability to add "documentation-parts" to new resource aws_api_gateway_integration_documentation

### ISSUE THREAD

**Issue by nwayve** [terraform-providers/terraform-provider-aws#1123]
Hi there,

Feature Request:
Create a new resource named: `aws_api_gateway_integration_documentation`
Purpose to provide documentation as seen exported from the AWS cli command:
`aws apigateway get-documentation-parts --rest-api-id="uid"`
When manually manipulating an API Gateway Integration via the AWS Web UI, navigate to a resource method, open the Method Request, and expand the URL Query String Parameters.  If no querystring parameters exist, create one, but on any existing, in the far right-hand column where the delete (x) action is, there's also a "View Documentation" book icon.  This is also available for the method itself (at the top), request headers, the request body, response statuses, response headers, and response bodies.

I've provided an example below of one method of implementing this and might not be the most ideal but it could be an option.

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_api_gateway_method_documentation (currently does not exist)

### Terraform Configuration Files
```hcl
resource "aws_api_gateway_rest_api" "test" {
  name = "MyDemoAPI"
  description = "This is my API for demonstration purposes"
}
resource "aws_api_gateway_resource" "test" {
  rest_api_id = "${aws_api_gateway_rest_api.test.id}"
  parent_id   = "${aws_api_gateway_rest_api.test.root_resource_id}"
  path_part   = "mytestresource"
}
resource "aws_api_gateway_method" "test" {
  rest_api_id   = "${aws_api_gateway_rest_api.test.id}"
  resource_id   = "${aws_api_gateway_resource.test.id}"
  http_method   = "GET"
  authorization = "NONE"
}
resource "aws_api_gateway_integration" "MyDemoIntegration" {
  rest_api_id = "${aws_api_gateway_rest_api.MyDemoAPI.id}"
  resource_id = "${aws_api_gateway_resource.MyDemoResource.id}"
  http_method = "${aws_api_gateway_method.MyDemoMethod.http_method}"
  type        = "MOCK"

  request_parameters = {
    "integration.request.querystring" = "'foo'"
  }
}

resource "aws_api_gateway_integration_documentation" "d" {
  integration_id = "${aws_api_gateway_integration.MyDemoIntegration.id}"
  type = "QUERY_PARAMETER"
  properties = <<EOF
{
  "description": "foo querystring description"
}
EOF
}
```

### Expected Behavior / Desired Output After Deployment:
`aws apigateway get-documentation-parts --rest-api-id="uid"`
```json
{
    "items": [
        {
            "properties": "{\n    \"description\": \"foo querystring description\"\n}",
            "id": "uid",
            "location": {
                "path": "/",
                "type": "QUERY_PARAMETER",
                "method": "GET",
                "name": "foo"
            }
        }
    ]
}
```

### Closing thoughts
The disappointing part about these documentation parts implemented by AWS is that they're not exported in any of the Swagger doc exports (vanilla, AWS extensions, or Postman extensions).  The only real way to get at them is through the AWS cli or an sdk.

**Comment by bflad** [comment]
@nwayve turns out this was actually implemented in [v1.7.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018) and never referenced back to for closing out. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

Hope this helps!
