### ISSUE TITLE
[feature] aws_route53_zone attachment to multiple vpcs 

### ISSUE THREAD

**Issue by sheldonkwok** [terraform-providers/terraform-provider-aws#1125]
### Terraform Version
v0.9.11

### Affected Resource(s)

- aws_route53_zone

### Feature
It's currently possible to associate a zone to multiple VPCs in the AWS console. This feature is not exposed through terraform. Here are the docs on how to accomplish this with the AWS console. 

http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zone-private-associate-vpcs.html

**Comment by Gufran** [comment]
@sheldonkwok Does this help https://www.terraform.io/docs/providers/aws/r/route53_zone_association.html

I believe it is the same functionality as described in route 53 documentation.

**Comment by sheldonkwok** [comment]
Whoops, missed that one. You're totally right. Thanks!

**Comment by stack72** [comment]
Thanks folks :)
