### ISSUE TITLE
[Feature] aws_kms_key resource support external origin

### ISSUE THREAD

**Issue by MCyprien** [terraform-providers/terraform-provider-aws#1126]
### Terraform Version
- 0.9.11

### Affected Resource(s)
- aws_kms_key

### Feature
- aws_kms_key does not manage key with external origin, we cannot create nor import external kms keys

**Comment by MCyprien** [comment]
this issue is linked to PR #1127

**Comment by petems** [comment]
So I was looking over this today and it's harder than it looks. Mapping the current CLI steps into Terraform I think would look like this:

1. Create aws_kms_external resource (Like in #1127  (https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-create-cmk.html)
2. Create new data sources to fetch the KMS public key and token (eg. `aws_kms_key_public_key` and `aws_kms_key_token`) (https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-get-public-key-and-token.html)
3. Create a new `aws_encrypted_key_material` resource using the information from the data sources (https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-encrypt-key-material.html)
4. Import the key_material into the aws_kms_external resource (https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-import-key-material.html)

Each step gets progressivly more tricky to implement 😅 

But the more steps implemented in Terraform, it would make the process a lot easier! 😄

**Comment by MCyprien** [comment]
Hello @petems,
A have some comments on this as I looked into it when I created the issue :)
1. This step is the easy part, nothing to say :)
2. The datasource can be very useful because you will need those materials to encrypt your key
3. and 4. This is the tricky part. I don't think having `aws_encrypted_key_material` resource is a good idea, let me explain:
     *  with the datasource, you will get a public key and a token.
         * public key is used to encrypt the key you want to push to KMS
         * token is used to push your encrypted key in AWS
     * BUT the public key and token expire and only last for 24h

So:
     * What do we store in tfstate to tell TF it needs to do something or not ?
     * Is it ok to check that the KMS key, we want to use, is waiting for import or not and execute resource depending on that ? (don't know if I am really clear on this one)
     * Do you think of something else ?

**Comment by bflad** [comment]
The new aws_kms_external_key resource with (optional) support for importing key material has been merged and will release with version 2.4.0 of the Terraform AWS Provider in the next two days. 👍

**Comment by bflad** [comment]
This has been released in [version 2.4.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#240-march-29-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
