### ISSUE TITLE
Redundant ec2:ModifyNetworkInterfaceAttribute call when updating aws_network_interface

### ISSUE THREAD

**Issue by nozaq** [terraform-providers/terraform-provider-aws#11273]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.18
+ provider.archive v1.3.0
+ provider.aws v2.41.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

- aws_network_interface

#### 1st Apply

First, apply the following tf file.

```hcl
module "this_vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "eni-test"
  cidr = "192.168.0.0/24"

  azs            = ["ap-northeast-1a"]
  public_subnets = ["192.168.0.0/25"]

  enable_nat_gateway = false
}

resource "aws_network_interface" "eni" {
  subnet_id         = module.this_vpc.public_subnets[0]
  source_dest_check = false
}
```

#### 2nd Apply

Then, add `tags` attribute to `aws_network_interface.eni` and apply.

```hcl
module "this_vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "eni-test"
  cidr = "192.168.0.0/24"

  azs            = ["ap-northeast-1a"]
  public_subnets = ["192.168.0.0/25"]

  enable_nat_gateway = false
}

resource "aws_network_interface" "eni" {
  subnet_id         = module.this_vpc.public_subnets[0]
  source_dest_check = false

  tags = {
    "DummyTag" = 1
  }
}
```

### Debug Output

A part of the debug output from 2nd apply (full log not provided for security purpose).
https://gist.github.com/nozaq/b872123c8ceb7961089a8fee0c30ff8a

### Panic Output

Terraform doesn't produce a panic.

### Expected Behavior

On 2nd apply, only [ec2:CreateTags](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTags.html) is called to update tags on `aws_network_interface.eni`.

### Actual Behavior

On 2nd apply, [ec2:ModifyNetworkInterfaceAttribute](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyNetworkInterfaceAttribute.html) is called with SourceDestCheck paramter before ec2:CreateTags.

ec2:ModifyNetworkInterfaceAttribute call is redundant since SourceDestCheck parameter doesn't change on this apply.

### Steps to Reproduce

1. `terraform apply` with the `1st Apply` code above.
2. `terraform apply` with the `2nd Apply` code above.

### Important Factoids

None

### References

None

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.42.0 of the Terraform AWS Provider, later today. Thanks to @nozaq for the implementation. 👍
