### ISSUE TITLE
EKS Managed node groups autoscaling

### ISSUE THREAD

**Issue by steve21168** [terraform-providers/terraform-provider-aws#11296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the aws_eks_node_group scaling_config block you are required to set the desired size. This is undesirable b/c I want to let my nodes autoscale within the min-max range I set. Everytime my terraform is deployed it tries to reset the ASG to the desired size set within terraform.

I believe desired size should be optional. When you use an ASG directly with Terraform the desired_capacity is optional and would expect the same for this API that manages an ASG behind the scenes.

### New or Affected Resource(s)

Resource: aws_eks_node_group
Block: scaling_config

### Potential Terraform Configuration

```hcl
  scaling_config {
    max_size     = 1
    min_size     = 1
  }
```

### References

* https://www.terraform.io/docs/providers/aws/r/eks_node_group.html

**Comment by mklauber** [comment]
To note, a potential workaround we have adopted is to add the following lifecycle settings to our nodegroup.  This allows the nodegroup to be scaled without having TF revert those changes.
```
  lifecycle {
    ignore_changes = ["scaling_config"]
  }
```

**Comment by bflad** [comment]
Hi folks 👋 Similar to other AWS resources like this, the autoscaling values are potentially required for creation, but optional for updates (pending verification here: https://github.com/terraform-providers/terraform-provider-aws/pull/11157#pullrequestreview-361901748). In terms of the Terraform, the above `lifecycle` inclusion may be required and if so should likely be added to the resource documentation.
