### ISSUE TITLE
Unable to delete an aws_iam_user if aws_iam_user_login_profile was defined

### ISSUE THREAD

**Issue by cjeanneret** [terraform-providers/terraform-provider-aws#1130]
Hello,

I just hit a bug in the aws provider: I'm unable to delete a user because of some weird dependency.

### Terraform Version
v0.9.8

### Affected Resource(s)
- aws_iam_user
- aws_iam_user_login_profile

### How to reproduce
- create an aws_iam_user
- create an aws_iam_user_login_profile for that user
- ``terraform apply``
- test the user, use it as wanted… that works fine
- delete the two resources in the .tf file
- ``terraform apply``

### What should happen
Terraform should just drop the two resources, and Voilà

### What actually happens
Terraform crashes and complain:
```
Error applying plan:                                       

1 error(s) occurred:                                       

* aws_iam_user.test_user (destroy): 1 error(s) occurred:    

* aws_iam_user.test_user: Error deleting IAM User test_user: DeleteConflict: Cannot delete entity, must delete login profile first.                                                                                                          
        status code: 409, request id: xx-xx-xx-xx-xx
```

So, for now, I'm just unable to remove terraform managed users :cry: 

Any idea?

Thank you!

**Comment by cjeanneret** [comment]
Ah, seems to be related to #119. Would be great to get some updates :).

**Comment by Ninir** [comment]
Hey @cjeanneret 

Just checked it using example from [the documentation](https://www.terraform.io/docs/providers/aws/r/iam_user_login_profile.html) and TF 0.9.11, and it worked as expected. In fact, when deleting a user (and using the `force_destroy` argument), the access keys, login profiles & MFA devices are now deleted prior to removing the user.

Could you check and tell me how it goes, so that I can close this PR?

Thanks!

**Comment by Ninir** [comment]
Hey @cjeanneret 

Since the provided use-case works for us, I am going to close this one if you don't mind.
Tell us if you are still encountering this issue, and we'll reopen and discuss.
Thanks!

**Comment by tomasnorre** [comment]
I have the same issue, I didn't manage to delete the user over Terraform, but I used the debug information to see which user it was, and I removed it manually from the AWS console. 

https://www.terraform.io/docs/internals/debugging.html
