### ISSUE TITLE
Terraform 0.12 aws_lambda_permission resource replaced every apply

### ISSUE THREAD

**Issue by JoBaAl** [terraform-providers/terraform-provider-aws#11322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.17

* provider.archive v1.3.0
* provider.aws v2.41.0
* provider.external v1.2.0

### Affected Resource(s)

* aws_lambda_permission

### Expected Behavior

No replacements on apply if there's no changes on the resource.

### Actual Behavior

I'm creating dynamically the following resource:

```
resource "aws_lambda_permission" "lambda_permision" {
  count         = length(var.stages)
  statement_id  = "${var.lambda}${element(var.stages, count.index)}Invoke"
  action        = "lambda:InvokeFunction"
  function_name = "${var.lambda}:${element(var.stages, count.index)}"
  principal     = "apigateway.amazonaws.com"
  source_arn    = "arn:aws:execute-api:${var.region}:${var.account_id}:${var.rest_api_id}/*/${var.method}${aws_api_gateway_resource.api_resource.path}"
}
```
The variables are always the same. But every apply I receive the following notification:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.signurl_get.aws_lambda_permission.lambda_permision[0] must be replaced
-/+ resource "aws_lambda_permission" "lambda_permision" {
        action        = "lambda:InvokeFunction"
      ~ function_name = "lambda_test_version" -> "lambda_test_version:v1" # forces replacement
      ~ id            = "lambda_test_versionv1Invoke" -> (known after apply)
        principal     = "apigateway.amazonaws.com"
      - qualifier     = "v1" -> null # forces replacement
        source_arn    = "arn:aws:execute-api:eu-west-1:887428995966:t4m0c9z1uk/*/GET/signurl"
        statement_id  = "lambda_test_versionv1Invoke"
    }

  # module.signurl_get.aws_lambda_permission.lambda_permision[1] must be replaced
-/+ resource "aws_lambda_permission" "lambda_permision" {
        action        = "lambda:InvokeFunction"
      ~ function_name = "lambda_test_version" -> "lambda_test_version:v2" # forces replacement
      ~ id            = "lambda_test_versionv2Invoke" -> (known after apply)
        principal     = "apigateway.amazonaws.com"
      - qualifier     = "v2" -> null # forces replacement
        source_arn    = "arn:aws:execute-api:eu-west-1:887428995966:t4m0c9z1uk/*/GET/signurl"
        statement_id  = "lambda_test_versionv2Invoke"
    }

```

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @JoBaAl 👋 

According to the plan output, it appears you need to move the qualifier (e.g. `:v1`) to the `qualifier` argument of the resource to prevent the difference. e.g.

```hcl
resource "aws_lambda_permission" "lambda_permision" {
  count         = length(var.stages)
  statement_id  = "${var.lambda}${element(var.stages, count.index)}Invoke"
  action        = "lambda:InvokeFunction"
  function_name = "${var.lambda}" # changed line
  principal     = "apigateway.amazonaws.com"
  qualifier     = "${element(var.stages, count.index)}" # changed line
  source_arn    = "arn:aws:execute-api:${var.region}:${var.account_id}:${var.rest_api_id}/*/${var.method}${aws_api_gateway_resource.api_resource.path}"
}
```

The Lambda service is notorious for allowing many input forms into Function name fields (such as ARNs and qualified names like the ones you gave), but standardizing them to use qualifier fields in the API responses which Terraform uses for drift detection. Can you confirm adjusting your configuration works as expected?

**Comment by bflad** [comment]
Closing due to lack of response. If you are still having an issue after trying the above proposed solution, please submit a new bug report. Thanks.
