### ISSUE TITLE
Error creating Capacity Providers on ECS Cluster

### ISSUE THREAD

**Issue by encryptblockr** [terraform-providers/terraform-provider-aws#11338]
getting these errors with this push
using latest terraform and latest aws provider

```
$ terraform --version
Terraform v0.12.18
+ provider.aws v2.42.0
+ provider.template v2.1.2
```

```
Error: error creating capacity provider: ClientException: The managed termination protection setting for the capacity provider is invalid. To enable managed termination protection for a capacity provider, the Auto Scaling group must have instance protection from scale in enabled.
```

i have enabled `protect_from_scale_in       = true` for the autoscaling group so not sure what the issue is

References
#11151

**Comment by encryptblockr** [comment]
ok this works now

i think was issue with my autoscaling group not able to update when launch configuration changes so i fixed that and now i am able to create capacity provider


**BUT** when the capacity provider was created after a successful terraform apply, i am not able to see it under the "capacity providers" tab of the ECS cluster

am i missing anything? where do i see the capacity provider created by terraform?

**Comment by encryptblockr** [comment]
here is latest when trying to attach the capacity provider created to the ECS cluster
capacity provider `arn:aws:ecs:abc123` and was able to even reference it in my terraform which is why it can even have a capacity provider to search..but now can't find it

```
Error: error changing ECS cluster capacity provider settings (arn:aws:ecs:abc123): InvalidParameterException: The specified capacity provider 'arn:aws:ecs:abc123' was not found. Specify a valid capacity provider and try again.
```

**Comment by encryptblockr** [comment]
final update!

when i used `name` of capacity provider instead of the `arn` then it works
this is a bug!

works now when i referenced the capacity provider by the `name`
did not work when i referenced by the `arn`

**Comment by cesar-rodriguez** [comment]
Any chance you can post your terraform here? I'm trying to make this work and having a difficult time.

**Comment by MBali-GitHub** [comment]
@encryptblockr : Can you share the syntax you've used, and did you hardcode the value?

It works fine when I hard code the name of the capacity provider
capacity_providers = ["mytest"] ---- This works

But it throws an error when i try to refer it like 
capacity_providers = ["${aws_ecs_capacity_provider.capacityProvider.name}"] ----This does not work

The error doesn't give any details, and just names some resources in my project.
Cycle: module.ecs_cluster.aws_launch_template.launchTemplate, module.ecs_cluster.aws_autoscaling_group.asg, module.ecs_cluster.aws_ecs_capacity_provider.capacityProvider, module.ecs_cluster.aws_ecs_cluster.ecsCluster, module.ecs_cluster.data.template_file.user_data

**Comment by eversC** [comment]
I'm seeing the same as @encryptblockr where `name` of capacity provider works but `arn` doesn't, yet [the provider docs for ecs_cluster](https://www.terraform.io/docs/providers/aws/r/ecs_cluster.html#capacity_providers) state:

> capacity_provider - (Required) The short name or full Amazon Resource Name (ARN) of the capacity provider.

**Comment by ItsKarma** [comment]
I was also able to confirm using the `name` instead of the `arn` worked for both `capacity_providers` and `default_capacity_provider_strategy{capacity_provider}`.

This appears to only be an issue with the Terraform documentation. The [aws cli docs](https://docs.aws.amazon.com/cli/latest/reference/ecs/put-cluster-capacity-providers.html) do **not** indicate the full arn can be used, but only the name of the capacity provider(s).

> --capacity-providers (list)
> The name of one or more capacity providers to associate with the cluster.
