### ISSUE TITLE
Attribute to retrieve ECR login credentials

### ISSUE THREAD

**Issue by Phat3** [terraform-providers/terraform-provider-aws#11332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During the creation of a repository on an Amazon Elastic Container Registry (ECR) it would be very helpful to have a way to retrieve the login credential for the newly created registry. I've noticed two related pull requests ([#3145](https://github.com/terraform-providers/terraform-provider-aws/pull/3145), [#2824](https://github.com/terraform-providers/terraform-provider-aws/pull/2824))  that propose a new *data source* to retrieve this information, but they appeared to be closed without being merged to master. 

What is the reason why those pull requests were closed? Is there a better way to retrieve the login credentials?

My use case is the following:
1. Create a new repository using `aws_ecr_repository`
2. Get the login credentials for the registry that contains the repository created above
3. Pass the credential to external scripts that push some image to the repository

For now, as a workaround, I pass the registry id to my script and then I get the credentials using a library to interface with the API for AWS (boto3 in my case), I log in to the registry and finally push the image. The goal is to remove the needs to use AWS API in my script.

Thanks in advance.

### New or Affected Resource(s)

* aws_ecr_repository

### Potential Terraform Configuration

```hcl
resource "aws_ecr_repository" "dummy_repo" {
  name    = "dummy_repo"
  image_tag_mutability    = "MUTABLE"
}

output "ecr_login_credentials" {
  value    = "${aws_ecr_repository.dummy_repo.registry_credentials}"
  description    = "Returns the login credentials for the registry that contains the specified repository" 
}
```

### References

* [#3145](https://github.com/terraform-providers/terraform-provider-aws/pull/3145)
* [#2824](https://github.com/terraform-providers/terraform-provider-aws/pull/2824)

**Comment by anGie44** [comment]
This feature, coined `aws_ecr_authorization_token` has been merged and will release with `v2.67.0` of the Terraform AWS Provider, expected later in today's release.
