### ISSUE TITLE
Importing aws_lamda_event_source_mapping for Kinesis stream attempts to create a new resource

### ISSUE THREAD

**Issue by vit-stepanovs** [terraform-providers/terraform-provider-aws#1133]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_lambda_event_source_mapping

### Terraform Configuration Files
```hcl
resource "aws_lambda_event_source_mapping" "lambda" {
  batch_size        = 5
  event_source_arn  = "${aws_kinesis_stream.kinesis_stream.arn}"
  enabled           = true
  function_name     = "${aws_lambda_function.lambda.arn}"
  starting_position = "TRIM_HORIZON"
}
```

### Expected Behavior
I have an existing lambda in S3 that pulls from a Kinesis stream. When I run

`terraform import aws_lambda_event_source_mapping.lambda 012345678-9abc-def0-1234-56789abcdef0`

I expect terraform to reconcile the state with my manual config and not attempt to create a new lambda event source mapping resource.

### Actual Behavior
When I run `terraform plan`, I see this:
```
-/+ aws_lambda_event_source_mapping.lambda
    batch_size:              "5" => "5"
    enabled:                 "" => "true"               
    event_source_arn:        "arn:aws:kinesis:us-west-2:123456789012:stream/KinesisStream" => "arn:aws:kinesis:us-west-2:123456789012:stream/KinesisStream"
    function_arn:            "arn:aws:lambda:us-west-2:123456789012:function:MyProcessor" => "<computed>"
    function_name:           "arn:aws:lambda:us-west-2:123456789012:function:MyProcessor" => "arn:aws:lambda:us-west-2:123456789012:function:MyProcessor"
    last_modified:           "" => "<computed>"
    last_processing_result:  "OK" => "<computed>"
    starting_position:       "" => "TRIM_HORIZON" (forces new resource)
    state:                   "Enabled" => "<computed>"
    state_transition_reason: "User action" => "<computed>"
    uuid:                    "012345678-9abc-def0-1234-56789abcdef0" => "<computed>"
```
From the above output, I understand that Terraform will attempt to create a new resource. I am not able to leave the starting_position field empty in my configuration, since that field is required.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import aws_lambda_event_source_mapping.lambda 012345678-9abc-def0-1234-56789abcdef0`
2. Put the above configuration into a .tf file.
3. `terraform plan`

**Comment by venkz** [comment]
We ran into the same issue and had some events re-processed as a result of this.

In my case, my code looked like this.
`
resource "aws_lambda_event_source_mapping" "ordered_event_source_mappings" {
  count = "${length(keys(var.ordered_queues))}"
  batch_size        = 10
  event_source_arn = "${element(aws_kinesis_stream.ordered-streams.*.arn, count.index)}"
  enabled           = true
  function_name     = "Some lambda name foo"
  starting_position = "TRIM_HORIZON"
}
`
where ordered_queues are a list of kinesis queues.

**Comment by tierra** [comment]
Might be worth also noting that a `terraform refresh` doesn't resolve this either.

**Comment by pselle** [comment]
Thanks for describing the issue well, I've looked into seeing how we might be able to address this.

Unfortunately, (this is a limitation in the AWS SDK)[https://godoc.org/github.com/aws/aws-sdk-go/service/lambda#EventSourceMappingConfiguration] ([and API](https://docs.aws.amazon.com/lambda/latest/dg/API_GetEventSourceMapping.html)) in how it returns the value for a request for an event source mapping. When Terraform requests the event source mapping from AWS, `starting_position` is not one of the values that Terraform will get back -- so in this scenario, Terraform doesn't have a way to populate the `starting_position` value in your statefile, but then the value is required when interacting further with AWS.

Thus, there's not a current path for fixing this, so the described workarounds are probably best, pending being able to read that value from AWS.
