### ISSUE TITLE
Amazon Kinesis Data Analytics now supports Apache Flink 1.8

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now build and run streaming applications using Apache Flink 1.8 in Amazon Kinesis Data Analytics.

### New or Affected Resource(s)

* [`aws_kinesis_analytics_application`](https://www.terraform.io/docs/providers/aws/r/kinesis_analytics_application.html)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-kinesis-data-analytics-now-supports-apache-flink-18/).

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7332

Requires [AWS SDK v1.26.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.26.4):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11314

**Comment by brunocous** [comment]
What is the status on this?

**Comment by ewbankkit** [comment]
Supported via https://github.com/terraform-providers/terraform-provider-aws/pull/11652.

**Comment by mighelone** [comment]
Any news on that? I saw that #13161 has been merged, but I cannot find information if the resource can be provided with TF
