### ISSUE TITLE
aws_dx_private_virtual_interface missing "amazonSideAsn" output attribute

### ISSUE THREAD

**Issue by rfc1149** [terraform-providers/terraform-provider-aws#11350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After creating a direct connect virtual interface, there is currently no way in terraform to retrieve the "amazonSideAsn" attribute. This attribute is generated by amazon, and is necessary to know in order to set up the BGP peering connection, for instance by using the [panos provider](https://www.terraform.io/docs/providers/panos/r/bgp_peer.html#peer_as) to configure the customer side equipment. 

The request here is to expose this, perhaps, "amazon_side_asn" as an attribute of the resource. This would follow the pattern used in the [aws_dx_gateway](https://www.terraform.io/docs/providers/aws/r/dx_gateway.html) resource, except in this case it would be an attribute instead of an argument, since the amazon side ASN is not user configurable on direct connect vifs.

I would finally just note for clarity, this is separate from the current argument of "bgp_asn" which is the Autonomous System number of the customer side.

### New or Affected Resource(s)

* aws_dx_private_virtual_interface
* aws_dx_hosted_private_virtual_interface
* aws_dx_public_virtual_interface
* aws_dx_hosted_public_virtual_interface

### Potential Terraform Configuration

```hcl
aws_dx_private_virtual_interface.foo.amazon_side_asn
```

### References

https://docs.aws.amazon.com/directconnect/latest/APIReference/API_DescribeVirtualInterfaces.html

**Comment by ewbankkit** [comment]
Also applies to `aws_dx_transit_virtual_interface` and `aws_dx_hosted transit_virtual_interface` resources.

**Comment by ewbankkit** [comment]
I can address this along with the refactor to use the `keyvaluetags` package.

**Comment by bflad** [comment]
Support for the `amazon_side_asn` attribute in Direct Connect resources has been merged and will release with version 2.51.0 of the Terraform AWS Provider, end of this week. Thanks to @ryno75 for the acceptance testing assistance and @ewbankkit for the implementation. 👍
