### ISSUE TITLE
aws_db_instance db_subnet_group attribute does not work

### ISSUE THREAD

**Issue by ryan-dyer-sp** [terraform-providers/terraform-provider-aws#1135]
### Terraform Version
0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- data_aws_db_instance

### Terraform Configuration Files
```hcl
data "aws_db_instance" "source_db" {
  db_instance_identifier = "${var.source_db_name}"
}

resource "aws_rds_cluster" "default" {
  provider = "aws.dev_us-east-1"
  cluster_identifier = "${var.cluster_id}"
  availability_zones = [ "${data.aws_subnet.available.*.availability_zone}" ]
  database_name = "${var.db_name}"
  master_username = "${var.username}"
  master_password = "${var.password}"
  vpc_security_group_ids = [ "${data.aws_security_group.db_sg.id}" ]
  apply_immediately = false
  #db_subnet_group_name = "${var.db_subnet_group_name}"
  db_subnet_group_name = "${data.aws_db_instance.source_db.db_subnet_group}"
  db_cluster_parameter_group_name = "sp-aurora-56-cpg"
  storage_encrypted = true
  skip_final_snapshot = true
}
```

### Debug Output
https://gist.github.com/ryan-dyer-sp/d1e1c668b0ad34fc1ce5c96a6e6ca18f
Not debug output as i dont think it helps for this.

### Panic Output
NA

### Expected Behavior
The attribute works according to documentation: https://www.terraform.io/docs/providers/aws/d/db_instance.html#db_subnet_group

### Actual Behavior
Claims the attribute is invalid.  Tried multiple other attributes within this data resource and they work.  I believe the issue is in the code
```
d.Set("db_subnet_group", dbInstance.DBSubnetGroup)
```
I believe this should be db.Instance.DBSubnetGroup.DBSubnetGroupName

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
NA

### References
NA

**Comment by stack72** [comment]
Hi @ryan-dyer-sp 

You are indeed correct - sorry for the issue here! I just opened a PR that fixes it

Paul

**Comment by ryan-dyer-sp** [comment]
Thanks! Any chance I can get a dev build with this fix in it?  I tried checking out the code and fixing and building myself, but the build fails for me.
