### ISSUE TITLE
aws_alb_listener_rule can not be modified when using new coniditions

### ISSUE THREAD

**Issue by Console32** [terraform-providers/terraform-provider-aws#11362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.18
+ provider.aws v2.42.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_alb_listener_rule

### Terraform Configuration Files

```hcl
resource aws_alb_listener_rule "oidc_auth_rules" {
  count = length(var.oidc_settings)

  listener_arn = aws_alb_listener.alb_listener_user.arn
  action {
    type = "authenticate-oidc"

    authenticate_oidc {
      authorization_endpoint = "${var.oidc_settings[count.index].issuer}/authorize"
      client_id              = var.oidc_settings[count.index].client_id
      client_secret          = var.oidc_settings[count.index].client_secret
      issuer                 = "${var.oidc_settings[count.index].issuer}/"
      token_endpoint         = "${var.oidc_settings[count.index].issuer}/oauth/token"
      user_info_endpoint     = "${var.oidc_settings[count.index].issuer}/userinfo"
      session_cookie_name    = var.oidc_settings[count.index].cookie
      scope                  = "openid email profile"

      authentication_request_extra_params = {
        audience   = "${var.oidc_settings[count.index].issuer}/userinfo"
        connection = "main-tenant-oidc"
        prompt     = "login"
      }
    }
  }

  condition {
    query_string {
      key   = "profile"
      value = var.oidc_settings[count.index].profile_match
    }
  }
```

### Expected Behavior

Modifying a aws_alb_listener_rule should update the listener rule as `planned`
```
  # aws_alb_listener_rule.oidc_auth_rules[0] will be updated in-place
  ~ resource "aws_alb_listener_rule" "oidc_auth_rules" {
      ....
          ~ authenticate_oidc {
             ...

                on_unauthenticated_request          = "authenticate"
              ~ scope                               = "openid email profile" -> "openid profile"
            }
        }
       ....

        condition {
            field  = "query-string"
            values = []

            query_string {
                key   = "profile"
                value = "MPM.Search"
            }
        }
    }
```
### Actual Behavior

> Error: Both field and values must be set in a condition block
> 
>   on load_balancer.tf line 40, in resource "aws_alb_listener_rule" "oidc_auth_rules":
>   40: resource aws_alb_listener_rule "oidc_auth_rules" {

### Steps to Reproduce

1. Create a aws_alb
2. Create a aws_alb_listener
3. Create a aws_alb_listener_rule that contains a condition of type `query string`
4. `terraform apply`
5. Modify the aws_alb_listener_rule to trigger a inplace update (changing the scope for example)
6. `terraform apply`

### References

* #8268 (Feature added very recently)

**Comment by bflad** [comment]
The fix for this issue has been merged and will release with version 2.43.0 of the Terraform AWS Provider, later today. Thanks to @dpiddockcmp for the help fixing this. 👍
