### ISSUE TITLE
Support Agent cloudwatch log exports for RDS

### ISSUE THREAD

**Issue by smartersteni** [terraform-providers/terraform-provider-aws#11361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For MS SQL RDS, AWS now supports exporting agent logs to cloudwatch but this is not supported in the Terraform provider yet.

### New or Affected Resource(s)

* aws_db_instance

### Potential Terraform Configuration

```hcl
resource "aws_db_instance" "this" {
...
   enabled_cloudwatch_logs_exports = [
     "agent",
     "error",
   ]
}
```

### References

* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.SQLServer.html#USER_LogAccess.SQLServer.PublishtoCloudWatchLogs

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.49.0 of the Terraform AWS Provider, Thursday this week. Thanks to @owenfarrell for the implementation. 👍
