### ISSUE TITLE
aws_db_instance DBName must begin with a letter and contain only alphanumeric characters.

### ISSUE THREAD

**Issue by Zevran** [terraform-providers/terraform-provider-aws#1137]
Hi,

### Terraform Version
```Terraform v0.9.11```

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
```hcl
data "aws_availability_zones" "available" {}

resource "aws_vpc" "main" {
  cidr_block = "10.10.0.0/16"
}

resource "aws_subnet" "main" {
  count             = "2"
  cidr_block        = "${cidrsubnet(aws_vpc.main.cidr_block, 8, count.index)}"
  availability_zone = "${data.aws_availability_zones.available.names[count.index]}"
  vpc_id            = "${aws_vpc.main.id}"
}

resource "aws_db_subnet_group" "main" {
  name       = "tf-db-main-${terraform.env}"
  subnet_ids = ["${aws_subnet.main.*.id}"]
}

resource "aws_db_instance" "main" {
  allocated_storage    = 10
  storage_type         = "gp2"
  engine               = "postgres"
  engine_version       = "9.6.2"
  instance_class       = "${terraform.env == "production" ? "db.t2.medium" : "db.t2.small"}"
  name                 = "mydatabase-${terraform.env}"
  username             = "mydatabase_user"
  password             = "mydatabase_user"
  db_subnet_group_name = "${aws_db_subnet_group.main.name}"
}
```

### Expected Behavior
I should have the ability to create an aws db instance with a name containing non alphanumeric characters such as ```-``` or ```_```.
I tried manually through aws console and it went well.

### Actual Behavior
```
* aws_db_instance.main: 1 error(s) occurred:

* aws_db_instance.main: Error creating DB Instance: InvalidParameterValue: DBName must begin with a letter and contain only alphanumeric characters.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

Thanks !

Keep going ! You are doing a great job 😃  !

**Comment by vce-xx** [comment]
I stumbled on this too. But turned out that what I was looking for was the [identifer](https://www.terraform.io/docs/providers/aws/r/db_instance.html#identifier) argument.
`identifier - The name of the RDS instance`

**Comment by rastakajakwanna** [comment]
Actually, it should not be closed... the bug is valid. Initial RDS DB scheme (at least for MySQL) allows `_` underscore, while this provider not. Our team ran into this bug this week.
