### ISSUE TITLE
add iam group data source

### ISSUE THREAD

**Issue by eredi93** [terraform-providers/terraform-provider-aws#1138]
we currently have a iam role data source but not a iam group one.
my use case, i dont fully manage my account with terraform and i need to make sure that any user part of group A are part of the KMS key policy.
i currently hacked around a module that uses a data external and a bash script that returns a list of names and ARNs but it would be better to have a proper data source for it. writing modules that uses bash scripts and aws cli to get what i need makes me 😱

**Comment by eredi93** [comment]
this is great! thanks so much for adding that.
could you add users as part of `Attributes Reference` ? the API response has a Users array, what i'm proposing is having a `users_arn` and `users_name` arrays as outputs of the data source.

**Comment by stack72** [comment]
Hi @eredi93 

Please can you open another issue for this so that it doesn't get lost in a closed issue?

Thanks

Paul

**Comment by eredi93** [comment]
sure will do
