### ISSUE TITLE
aws_nat_gateway does not always properly destroy itself

### ISSUE THREAD

**Issue by fraenkel** [terraform-providers/terraform-provider-aws#11385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.17

### Affected Resource(s)

* aws_nat_gateway

### Terraform Configuration Files

```hcl
resource "aws_subnet" "public" {
  for_each = var.subnets_public

  vpc_id               = aws_vpc.network.id
  availability_zone_id = each.value
  cidr_block           = each.key
}

resource "aws_eip" "natgw" {
  for_each = var.subnets_public
  vpc      = true

  tags = merge(var.tags_extra, {
    Name = "${var.name}-natgw-${each.value}"
  })
}

resource "aws_nat_gateway" "network" {
  for_each = var.subnets_public

  allocation_id = aws_eip.natgw[each.key].id
  subnet_id     = aws_subnet.public[each.key].id

  tags = merge(var.tags_extra, { Name = "${var.name}-${each.value}" })
}

```

### Expected Behavior

Successful destruction.

### Actual Behavior

When I perform a `terraform plan --destroy` and then `terraform apply`, we occasionally receive
```
Plan: 0 to add, 0 to change, 16 to destroy.
Releasing state lock. This may take a few moments...

aws_route_table_association.private[\"10.1.48.0/20\"]: Destroying... [id=rtbassoc-08a9430b49fef6814]
aws_route_table_association.private[\"10.1.80.0/20\"]: Destroying... [id=rtbassoc-09223d644a61fbfff]
aws_internet_gateway.network: Destroying... [id=igw-0ccc6a20eced9fa04]
aws_default_route_table.public: Destroying... [id=rtb-02489ab6ff6232a82]
aws_eip.public[\"10.1.0.0/20\"]: Destroying... [id=eipalloc-08af63431a0a305e4]
aws_subnet.public[\"10.1.0.0/20\"]: Destroying... [id=subnet-0ff957d3249ed8523]
aws_eip.public[\"10.1.16.0/20\"]: Destroying... [id=eipalloc-01269b3ef1467b950]
aws_eip.natgw[\"10.1.16.0/20\"]: Destroying... [id=eipalloc-0d2192f48c15cc81e]
aws_default_route_table.public: Destruction complete after 0s
aws_default_security_group.default: Destroying... [id=sg-0d46bbb1e82e827a2]
aws_eip.public[\"10.1.32.0/20\"]: Destroying... [id=eipalloc-07aa6af7d40bed2b9]
aws_default_security_group.default: Destruction complete after 0s
aws_subnet.public[\"10.1.16.0/20\"]: Destroying... [id=subnet-0d73efa43497e0a7d]
aws_route_table_association.private[\"10.1.64.0/20\"]: Destroying... [id=rtbassoc-0b2c722a6c1548b47]
aws_route_table_association.private[\"10.1.48.0/20\"]: Destruction complete after 0s
aws_eip.natgw[\"10.1.0.0/20\"]: Destroying... [id=eipalloc-04d81d902b38f3d15]
aws_route_table_association.private[\"10.1.80.0/20\"]: Destruction complete after 0s
aws_eip.natgw[\"10.1.32.0/20\"]: Destroying... [id=eipalloc-0f5ff0f5383927ddb]
aws_route_table_association.private[\"10.1.64.0/20\"]: Destruction complete after 0s
aws_subnet.public[\"10.1.32.0/20\"]: Destroying... [id=subnet-057b64d49444c5b05]
aws_eip.natgw[\"10.1.16.0/20\"]: Destruction complete after 0s
aws_eip.public[\"10.1.16.0/20\"]: Destruction complete after 0s
aws_subnet.public[\"10.1.16.0/20\"]: Destruction complete after 0s
aws_eip.natgw[\"10.1.0.0/20\"]: Destruction complete after 0s
aws_eip.natgw[\"10.1.32.0/20\"]: Destruction complete after 0s
aws_subnet.public[\"10.1.0.0/20\"]: Destruction complete after 9s
aws_internet_gateway.network: Still destroying... [id=igw-0ccc6a20eced9fa04, 10s elapsed]
aws_subnet.public[\"10.1.32.0/20\"]: Still destroying... [id=subnet-057b64d49444c5b05, 10s elapsed]
aws_internet_gateway.network: Destruction complete after 11s
aws_subnet.public[\"10.1.32.0/20\"]: Destruction complete after 17s
aws_vpc.network: Destroying... [id=vpc-01e4bdea897c25d97]
aws_vpc.network: Destruction complete after 0s

Error: AuthFailure: You do not have permission to access the specified resource.
\tstatus code: 400, request id: fb112f95-24b1-4bd3-94a6-c557b91ef7ee

Error: AuthFailure: You do not have permission to access the specified resource.
\tstatus code: 400, request id: aa491005-ce5d-455c-a01d-0de2ba1f9743
```

I have filed a separate issue, https://github.com/hashicorp/terraform/issues/23734, since I cannot just re-plan/apply.

**Comment by bflad** [comment]
Hi @fraenkel 👋 Thank you for reporting this and sorry you are running into trouble here.

Would it be possible for you to create a Gist with the failing section of the debug logs? e.g. `TF_LOG=debug terraform apply` This will help us confirm which API call is failing (since it looks like we aren't including the relevant context in our error messaging there 😅).

One thing to potentially try here, which is buried a little in the [`aws_nat_gateway` resource documentation](https://www.terraform.io/docs/providers/aws/r/nat_gateway.html), is adding an explicit `depends_on` configuration to the `aws_internet_gateway` resource, e.g.

```hcl
resource "aws_nat_gateway" "network" {
  # ... other configuration ...

  depends_on = [
    aws_internet_gateway.network,
  ]
}
```

This will ensure that the `aws_nat_gateway` resources are created after the IGW and deleted before the IGW.

**Comment by bflad** [comment]
Looking at the output again and the additional information in the upstream bug report (https://github.com/hashicorp/terraform/issues/23734), its interesting that we do not see the `aws_nat_gateway.network` resource destruction at all before the `aws_eip.natgw` resources. 🤔 Were those resources never included in the destroy plan?

I feel like I've seen that `AuthFailure` error before with destroying EIPs when it was still attached to an AWS managed resource (like a NAT Gateway), which would make sense if the NAT Gateways were not destroyed first.

**Comment by fraenkel** [comment]
I believe if we add the dependency it might clear things up. The problem is that this fails only 10% of the time so its hard to debug. I will add the dependency on the `aws_internet_gateway` and see if the problem no longer occurs.

**Comment by fraenkel** [comment]
I will reopen this if the added dependency does not resolve the issue.
