### ISSUE TITLE
EC2 placement group resource tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EC2 placement groups now support [resource tagging](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources).

### New or Affected Resource(s)

* [`aws_placement_group`](https://www.terraform.io/docs/providers/aws/r/placement_group.html)

### Potential Terraform Configuration

```hcl
resource "aws_placement_group" "example" {
  tags = {
    Usage = "For example use only"
  }
}
```

### References

Requires [AWS SDK v1.26.7](https://github.com/aws/aws-sdk-go/releases/tag/v1.26.7):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11375

**Comment by bflad** [comment]
Support for tagging `aws_placement_group` resources has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week.
