### ISSUE TITLE
When creating ECS service on a new cluster, the service linked role doesn't exist yet

### ISSUE THREAD

**Issue by fields** [terraform-providers/terraform-provider-aws#11417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.13
+ provider.aws v2.43.0

### Affected Resource(s)

aws_ecs_service

### Expected Behavior

When creating an ECS service immediately after creating a new cluster in the same terraform apply, it should wait for AWS to create the service linked role, and succeed in creating the service.

### Actual Behavior

It tries to create the service before AWS finishes creating the ECS service linked role, and fails with this error.

```
Error: InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
	status code: 400, request id: ZZZZZZZ "YYYYYYY"
  on ../../terraform-modules/container_service/ecs_service.tf line 1, in resource "aws_ecs_service" "XXXXX":
   1: resource "aws_ecs_service" "XXXXX" {
```

If terraform apply is run again shortly thereafter, it works.

### Steps to Reproduce

1. have a terraform plan file which creates a new ECS cluster and a service
2. `terraform apply` (fails)
3. Wait a minute or two
4. `terraform apply` (works)

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.44.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
