### ISSUE TITLE
update aws_ssm_maintenance_window to support the description field

### ISSUE THREAD

**Issue by onedumslack** [terraform-providers/terraform-provider-aws#11430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the aws_ssm_maintenance_window resource does not appear to support the "description" field that is an optional supported field in the aws api and cli.

### New or Affected Resource(s)

aws_ssm_maintenance_window

### References
CLI command to add a description:
aws ssm update-maintenance-window --window-id ${windowId} --description 'maintenance window description'

**Comment by bflad** [comment]
Hi @onedumslack 👋 Thank you for submitting this. There appears to be an earlier feature request for this functionality (https://github.com/terraform-providers/terraform-provider-aws/issues/9035) so to consolidate any discussions and efforts, I'm going to close this issue in preference of the earlier one.
