### ISSUE TITLE
InvalidDBInstanceState: Instance is already being deleted

### ISSUE THREAD

**Issue by pauldraper** [terraform-providers/terraform-provider-aws#11434]
### Terraform Version

```
Terraform v0.12.13
+ provider.aws v2.28.1
```

### Affected Resource(s)

* aws_rds_cluster_instance

### References

This appears to be the same bug as #5622, but for `aws_rds_cluster_instance`:

If an instance is already being deleted (whether manually, or from a Terraform request that is now being retried), the delete operation fails, rather than wait for the existing delete operation to complete.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.44.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
