### ISSUE TITLE
func ValidateARN regex check needs to support additional regions

### ISSUE THREAD

**Issue by jered-miller** [terraform-providers/terraform-provider-aws#11444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
 0.12.16

### Affected Resource(s)

* All resources that call func validateArn

### Expected Behavior

Referencing a KMS Key ARN in aws_ami_copy should allow a key to be associated for encryption during the copy.

### Actual Behavior

An error occured stating that "This doesn't look like a valid ARN".  validateARN does not support certain unlisted AWS regions.  The pattern check needs to allow more flexibility in the second tuple for gov regions.  i.e. us-XXXX-east-1.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is running in an unlisted AWS region.

### References

* #0000

**Comment by bflad** [comment]
Pull request submitted: https://github.com/terraform-providers/terraform-provider-aws/pull/11471

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.44.0 of the Terraform AWS Provider, on Thursday. 👍

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8307
