### ISSUE TITLE
Blocks of type "default_capacity_provider_strategy" are not expected here.

### ISSUE THREAD

**Issue by leonardocastanodiaz** [terraform-providers/terraform-provider-aws#11443]
### Error appears when I try to define capacity providers.

Please help me to find the reason this piece of code was working last time that I ran the terraform apply command and now I got this error.

Thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
+ Terraform v0.12.13
+ provider.aws v2.33.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_ecs_cluster

### Terraform Configuration Files

```hcl

 46 resource "aws_ecs_cluster" "jenkins-fargate-cluster-by-terraform" {
 47   name = "Jenkins-Fargate-Cluster-by-Terraform"
 48   capacity_providers  = ["FARGATE", "FARGATE_SPOT"]
 49
 50   default_capacity_provider_strategy {
 51     capacity_provider = "FARGATE_SPOT"
 52     weight                   = 100
 53   }
 54
 55
 56   tags = {
 57     Name = var.name
 58     Environment = var.env
 59   }
 60
 61 }


```

### Debug Output
```
 Error: Unsupported argument
    on ecs.tf line 48, in resource "aws_ecs_cluster" "jenkins-fargate-cluster-by-terraform":
    48:   capacity_providers  = ["FARGATE", "FARGATE_SPOT"]
    An argument named "capacity_providers" is not expected here.


 Error: Unsupported block type
    on ecs.tf line 50, in resource "aws_ecs_cluster" "jenkins-fargate-cluster-by-terraform":
    50:   default_capacity_provider_strategy {
```

### Expected Behavior
+ Create a ECS Cluster with FARGATE,  FARGATE_SPOT as capacity providers

### Actual Behavior
+ Terraform shows an error.

### Steps to Reproduce

1. `terraform apply`

**Comment by blckct** [comment]
Have you tried updating the AWS Provider to latest version? Or checking the CHANGELOG to see if you're running a version that supports that resource (v2.42)?

**Comment by leonardocastanodiaz** [comment]
@blckct Thank you very much problem solved with this command.
`terraform init -upgrade`

Now my versions are:
`Terraform v0.12.13
+ provider.aws v2.43.0
+ provider.template v2.1.2`
