### ISSUE TITLE
EMR create a new resource aws_emr_instances_fleet 

### ISSUE THREAD

**Issue by dthauvin** [terraform-providers/terraform-provider-aws#1146]
Hi there,

Is it possible to create new resource which supports "instance fleets" for aws EMR ? with all features like : 
-- Maximum bid price spot instance for master
--Maximum bid price for core et task type
-- On-demand vCPUs and Spot vCPUs for Core and task type
--  Defined duration and Provisioning timeout for core and task type 

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)

- aws_emr_cluster
- aws_emr_instance_group

**Comment by damdr** [comment]
Hello 
in the "AWS SDK for Go API Reference" we can find the AddInstanceFleet function . 
If it helps .
http://docs.aws.amazon.com/sdk-for-go/api/service/emr/

**Comment by copumpkin** [comment]
Another vote for this

**Comment by copumpkin** [comment]
Looks like there's a languishing PR for this, in case anyone wants to try it out: https://github.com/terraform-providers/terraform-provider-aws/pull/1475

**Comment by darrenhaken** [comment]
Is this just not being picked up?

**Comment by sanoojm** [comment]
@darrenhaken @copumpkin @jmsantorum I have all the conflicts fixed and sync. I am using it in my preprod environment as well. How to I proceed to update this PR? @jmsantorum, can you give me access to push a new branch to your repo? If anyone know a better way, please suggest.

**Comment by c4po** [comment]
Ok, I made another PR [13946](https://github.com/terraform-providers/terraform-provider-aws/pull/13946)  for this issue. 
Please review.
We really need this feature in our EMR.
Once this merged, I will try add the [EMR Managed Scaling](https://github.com/terraform-providers/terraform-provider-aws/pull/13946) feature.

**Comment by bostrowski13** [comment]
would be great to see this accepted and merged.  looks like the work is done minus a PR and integration!

**Comment by npinnaka** [comment]
+1

**Comment by bflad** [comment]
Support for new `core_instance_fleet` and `master_instance_fleet` configuration blocks in the `aws_emr_cluster` resource has been merged and will release with version 3.5.0 of the Terraform AWS Provider, later this week. Thanks to @c4po for the implementation. 👍 

Support for task instance fleets, via a new `aws_emr_instance_fleet` resource, will be reviewed in the coming days.

**Comment by bflad** [comment]
Support for the new `aws_emr_instance_fleet` resource has also been merged and will release with version 3.5.0 of the Terraform AWS Provider, likely on Thursday. Thanks again to @c4po for their efforts!

**Comment by c4po** [comment]
thanks for the help @bflad  👏 🎉 
I may have some other PRs for document and data source coming for review.
