### ISSUE TITLE
ALB weighted target groups

### ISSUE THREAD

**Issue by houstonj1** [terraform-providers/terraform-provider-aws#11477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are new features on ALBs that allow for multiple target groups on a listener with a weighted priority. The potential configuration would allow for multiple action blocks on a aws_lb_listener_rule with a priority included.

AWS Reference: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-target-groups.html

### New or Affected Resource(s)

* aws_lb_listener_rule

### Potential Terraform Configuration

```hcl
resource "aws_alb_listener_rule" "my_lb_listener_rule" {
  listener_arn = ...
  priority     = ...

  action {
    type             = "forward"
    target_group_arn = arn_1
    priority = 8                            # 80% to target 1
  }

  action {
    type             = "forward"
    target_group_arn = arn_2
    priority = 2                            # 20% to target 2
  }

  condition {
    ....
  }
}
```

### References

* #10942

**Comment by DrMerlin** [comment]
Using 8 for 80% and 2 for 20% seems odd to me.  Is that from the AWS API?  Or just something that seemed good to you, James?

**Comment by houstonj1** [comment]
> Using 8 for 80% and 2 for 20% seems odd to me. Is that from the AWS API? Or just something that seemed good to you, James?

Great question @DrMerlin! AWS offers values 0-999 for target weights, so there is a wide range of granularity to use. My example above was for simplicity :)

**Comment by bflad** [comment]
Hi @houstonj1 👋 Thank you for submitting this. This appears to be a duplicate or very similar to #10942, so to consolidate any discussions and efforts, I'm going to close this issue in preference of the earlier one. Please upvote and follow that issue for further updates.

**Comment by houstonj1** [comment]
Thanks @bflad, I see there was a PR merged related to that and the issue was closed. The purpose of this was to make it visible again. Thank you!

**Comment by bflad** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/10942 is still open -- one of the referenced pull requests (#8268) was indeed merged with similar, but unrelated functionality.
