### ISSUE TITLE
aws_ssm_parameter - Change from "SecureString" to "String" is not handled correctly

### ISSUE THREAD

**Issue by jonathan-flowers** [terraform-providers/terraform-provider-aws#11490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

* Initial 
```
resource "aws_ssm_parameter" "PostgresDbHostParameter" {
  name        = "/ExampleName"
  type        = "SecureString"
  description = "An example parameter"
  key_id      = aws_kms_key.InfrastructureKmsCmk.key_id
  value       = "testurl.com"
}
```

* After change
```
resource "aws_ssm_parameter" "PostgresDbHostParameter" {
  name        = "/ExampleName"
  type        = "String"
  description = "An example parameter"
  value       = "testurl.com"
}
```

(Note the change in **type** from **SecureString** to **String**, and the removal of the **key_id** field

### Debug Output

```
Error: error creating SSM parameter: ValidationException: KeyId is required for SecureString type parameter only.
status code: 400, request id: ce928f67-5d43-4ef3-9cff-330c0c997682
on main.tf line 50, in resource "aws_ssm_parameter" "PostgresDbHostParameter":
50: resource "aws_ssm_parameter" "PostgresDbHostParameter" {
```

### Expected Behavior

* When running `terraform plan` or `terraform apply`, updating this resource block is counted as a "change".
* However, AWS does not actually support "changing" a Parameter type after creation.  Therefore, rather than this being handled as a change, I would expect Terraform to destroy the existing resource and "recreate" a new one of the new type.

### Actual Behavior

* Terraform fails with an error referring to a "missing field" (key_id) that really isn't missing because the type is no longer "SecureString"
* As a workaround, I got this to work by commenting out the block entirely (causing Terraform to destroy the "SecureString" resource) and then un-commenting it (causing Terraform to recreate it as a "String".  This two-step process resolved the issue

### Steps to Reproduce

1. Create .tf file with a "SecureString" SSM Parameter resource block
2. Run `terraform apply`
3. Change the resource type to "String" and remove the `key_id` field
4. Run terraform apply.  One change will be picked up.  However, when entering 'yes' to continue you will receive the above error.

**Comment by bflad** [comment]
Hi @jonathan-flowers 👋 Thank you for reporting this. The fix for this has been merged and will release with version 2.47.0 of the Terraform AWS Provider, Thursday next week.
