### ISSUE TITLE
aws_dx_public_virtual_interface route_filter_prefixes update causes unnecessary destroy/create

### ISSUE THREAD

**Issue by ryno75** [terraform-providers/terraform-provider-aws#11504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.8
any

### Affected Resource(s)

* aws_dx_public_virtual_interface

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "2.43.0"
  region  = "us-west-2"
}

resource "aws_dx_public_virtual_interface" "vif" {
  name             = "test-pub-vif"
  connection_id    = "dxcon-fgjv6a5o"
  bgp_asn          = 33333
  vlan             = 1234
  address_family   = "ipv4"
  amazon_address   = "1.1.1.10/31"
  customer_address = "1.1.1.11/31"

  route_filter_prefixes = [
    "1.1.1.0/24",
  ]
}
```

### Expected Behavior

The plan should have reflected a simple update to the `route_filter_prefixes` attribute

### Actual Behavior

Terraform plan to destroy/create the resource to update the `route_filter_prefixes`

### Steps to Reproduce

1.  Run `terraform apply`:
```
Terraform will perform the following actions:

  # aws_dx_public_virtual_interface.vif will be created
  + resource "aws_dx_public_virtual_interface" "vif" {
      + address_family        = "ipv4"
      + amazon_address        = "1.1.1.10/31"
      + arn                   = (known after apply)
      + aws_device            = (known after apply)
      + bgp_asn               = 33333
      + bgp_auth_key          = (known after apply)
      + connection_id         = "dxcon-fgjv6a5o"
      + customer_address      = "1.1.1.11/31"
      + id                    = (known after apply)
      + name                  = "test-pub-vif"
      + route_filter_prefixes = [
          + "1.1.1.0/24",
        ]
      + vlan                  = 1234
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_dx_public_virtual_interface.vif: Creating...
aws_dx_public_virtual_interface.vif: Still creating... [10s elapsed]
aws_dx_public_virtual_interface.vif: Creation complete after 11s [id=dxvif-fgdgxvlz]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

2. Apply the following diff:
```diff
--- a/test.tf
+++ b/test.tf
@@ -14,5 +14,6 @@ resource "aws_dx_public_virtual_interface" "vif" {

   route_filter_prefixes = [
     "1.1.1.0/24",
+    "1.1.2.0/24",
   ]
 }
```

3. Run `terraform plan`:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_dx_public_virtual_interface.vif must be replaced
-/+ resource "aws_dx_public_virtual_interface" "vif" {
        address_family        = "ipv4"
        amazon_address        = "1.1.1.10/31"
      ~ arn                   = "arn:aws:directconnect:us-west-2:251324252109:dxvif/dxvif-fgdgxvlz" -> (known after apply)
      ~ aws_device            = "EqSe2-1n6ty6z4wgpqf" -> (known after apply)
        bgp_asn               = 33333
      ~ bgp_auth_key          = "0xvG6cYF6tVct38eop7_6eur" -> (known after apply)
        connection_id         = "dxcon-fgjv6a5o"
        customer_address      = "1.1.1.11/31"
      ~ id                    = "dxvif-fgdgxvlz" -> (known after apply)
        name                  = "test-pub-vif"
      ~ route_filter_prefixes = [ # forces replacement
            "1.1.1.0/24",
          + "1.1.2.0/24",
        ]
      - tags                  = {} -> null
        vlan                  = 1234
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by ewbankkit** [comment]
@ryno75 Thanks for reporting this.
The Direct Connect service allows only the MTU attribute of any virtual interface to be [updated](https://docs.aws.amazon.com/directconnect/latest/APIReference/API_UpdateVirtualInterfaceAttributes.html), so a change to any other attribute (e.g. `route_filter_prefixes`) requires that the resource be recreated.

**Comment by ryno75** [comment]
> @ryno75 Thanks for reporting this.
> The Direct Connect service allows only the MTU attribute of any virtual interface to be [updated](https://docs.aws.amazon.com/directconnect/latest/APIReference/API_UpdateVirtualInterfaceAttributes.html), so a change to any other attribute (e.g. `route_filter_prefixes`) requires that the resource be recreated.

Thanks @ewbankkit . Yeah, I just noticed this and came back here to close this issue. haha. I am guessing I saw the routeFilterPrefixes in the response section when I looked at the API docs previously. how lame of me and how lame of them for only supporting the MTU!
