### ISSUE TITLE
Configure "FROM email address" for Cognito user pool (aws_cognito_user_pool)

### ISSUE THREAD

**Issue by jverhoelen** [terraform-providers/terraform-provider-aws#11507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When letting Cognito send emails through SES ("Yes - Use Amazon SES") and having "FROM email address ARN" configured, it is also interesting to populate the "FROM email address" field. This field, in addition to the one for the ARN, can be used to set a sender name ("e.g. MyCompany <no-reply@mycompany.com>"). When setting this manually in Cognito it works. Unfortunately there is no property in "aws_cognito_user_pool.email_configuration" to configure it through Terraform.

### New or Affected Resource(s)

* aws_cognito_user_pool ("email_configuration" to be precise)

### Potential Terraform Configuration

A stripped down configuration of the resource containing the potentially new field "email_configuration.from_email_address".

```hcl
resource "aws_cognito_user_pool" "kunden" {

  email_configuration = {
    reply_to_email_address = "${local.default_email_from_address}"
    source_arn = "${local.default_email_source_arn}"
    from_email_address = "MyCompany <no-reply@mycompany.com>" # <-- new property
    email_sending_account = "DEVELOPER"
  }
}
```

### References

<img width="900" alt="Screenshot 2020-01-07 at 09 58 45" src="https://user-images.githubusercontent.com/6791360/71882497-dd5ad780-3134-11ea-9113-382ef65f4073.png">

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. Thanks to @jverhoelen for the implementation. 👍
