### ISSUE TITLE
AWS Lambda support missing for dotnetcore2.2 and dotnetcore3.0

### ISSUE THREAD

**Issue by ezavgorodniy** [terraform-providers/terraform-provider-aws#11508]
When I'm deploying my .NET Core application with version of core 2.2 I'm getting 

Error: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5], got dotnetcore2.2

**Comment by DrFaust92** [comment]
this is not support by AWS SDK:
https://github.com/aws/aws-sdk-go/blob/master/service/lambda/api.go
not does lambda support it:
https://docs.aws.amazon.com/lambda/latest/dg//lambda-runtimes.html

**Comment by ezavgorodniy** [comment]
Make sense now. Thanks for your response.
