### ISSUE TITLE
Security group: Changing description recreates it

### ISSUE THREAD

**Issue by jgrossmac** [terraform-providers/terraform-provider-aws#1150]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform Version: 0.9.8

### Affected Resource(s)
aws_security_group
Although I think it may apply to multiple resources

### Terraform Configuration Files
```hcl
resource "aws_security_group" "api" {
  name        = "${var.random}-api"
  description = ""
  vpc_id      = "${var.vpc_id}"

    tags {
    Name            = "${var.random}-api"
    BusinessUnit    = "${var.b_tag}"
    Environment     = "${var.branch}"
    Service         = "${var.s_tag}"
    ManagedBy       = "${var.m_tag}"
  }
}

#In
resource "aws_security_group_rule" "api_ingress1" {
  security_group_id = "${aws_security_group.api.id}"
  type              = "ingress"
  protocol          = "tcp"
  from_port         = "${var.db_port}"
  to_port           = "${var.db_port}"
  source_security_group_id  = "${aws_security_group.db.id}"
}

#Out
resource "aws_security_group_rule" "api_egress1" {
  security_group_id = "${aws_security_group.api.id}"
  type              = "egress"
  protocol          = "tcp"
  from_port         = "${var.db_port}"
  to_port           = "${var.db_port}"
  source_security_group_id  = "${aws_security_group.db.id}"
}
```

### Debug Output
https://gist.github.com/jgrossmac/d7fbaf22f627c8dd8cd62406c22e7a3b

### Expected Behavior
I would expect it to just update the description if it finds that resource already exists.

### Actual Behavior
diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create security group with a description
2. terraform apply
3. change security group description
4. terraform apply

**Comment by Ninir** [comment]
Will close this one since fixes have been brought for that specific case.
If this issue occurs again, please tell us here, thanks!
