### ISSUE TITLE
Processing Configuration fails for aws_kinesis_firehose_delivery_stream with Splunk Destination

### ISSUE THREAD

**Issue by dex83** [terraform-providers/terraform-provider-aws#11516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
TF Version: 12
AWS Provider Version: 2.43

### Affected Resource(s)

 
* aws_kinesis_firehose_delivery_stream

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "aws_kinesis_firehose_delivery_stream" "kinesis_stream" {
  name        = "${var.kinesis_name}"
  destination = "splunk"
  server_side_encryption {
    enabled = true
  }

  s3_configuration {
    role_arn           = "${aws_iam_role.firehose.arn}"
    bucket_arn         = "arn:aws:s3:::${var.bucket_name}"
    buffer_size        = 5
    buffer_interval    = 300
    compression_format = "GZIP"
    kms_key_arn        = "${aws_kms_key.a.arn}"
  }

  splunk_configuration {
    hec_endpoint               = "${var.hec_endpoint}"
    hec_token                  = "${var.hec_token}"
    hec_acknowledgment_timeout = 180
    hec_endpoint_type          = "Event"
    s3_backup_mode             = "FailedEventsOnly"
    cloudwatch_logging_options {
      enabled         = true
      log_group_name  = "${aws_cloudwatch_log_group.kinesis_log_group.name}"
      log_stream_name = "${aws_cloudwatch_log_stream.kinesis_log_stream.name}"
    }

    processing_configuration = [
      {
        enabled = "true"
        processors = [
          {
            type = "Lambda"
            parameters = [
              {
                parameter_name  = "LambdaArn"
                parameter_value = "${aws_lambda_function.lambda-transform.arn}:$LATEST"
              },
              {
                parameter_name  = "RoleArn"
                parameter_value = "${aws_iam_role.firehose.arn}"
              },
              {
                parameter_name  = "BufferSizeInMBs"
                parameter_value = 3
              },
              {
                parameter_name  = "BufferIntervalInSeconds"
                parameter_value = 60
              }

            ]
          },
        ]
      },
    ]

  }

}

### Debug Output
Unsupported argument in resource "aws_kinesis_firehose_delivery_stream" "kinesis_stream":
processing_configuration
An argument named "processing_configuration" is not expected here. Did you
mean to define a block of type "processing_configuration"?

### Expected Behavior

The Splunk FireHose Delivery Stream should be created and associated with a Lambda Transformation Function.

### Actual Behavior

Error at the plan level. 
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by dkondratovych** [comment]
hey @dex83 try to change the format how you define `processing_configuration `

Take a look at the example 

https://github.com/terraform-providers/terraform-provider-aws/blob/68ef163e0da53f40970ccc82149a2c7510aa1be6/aws/resource_aws_kinesis_firehose_delivery_stream_test.go#L2116

**Comment by dex83** [comment]
Thank you @dkondratovych. I will give this a try and report back.

**Comment by dex83** [comment]
Thank you @dkondratovych  that worked. My lambda Function is now associated with the Delivery Stream's processing configuration successfully.

**Comment by dex83** [comment]
I think the documentation for this aws_kinesis_firehose_delivery_stream resource needs to be updated.
