### ISSUE TITLE
Add ca_cert_identifier property to aws_rds_cluster_instance

### ISSUE THREAD

**Issue by Streadz** [terraform-providers/terraform-provider-aws#11527]
#11078 

# Description

2 months ago, the ca_cert_identifier property was added to the [aws_db_instance](https://www.terraform.io/docs/providers/aws/r/db_instance.html#ca_cert_identifier) resource (original issue thread for this change is [here](https://github.com/terraform-providers/terraform-provider-aws/issues/10417#issuecomment-554510991)). This feature request is to add the same property to the [aws_rds_cluster_instance](https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html), which are instances found in Aurora clusters. This would simplify our certificate maintenance if such a property was available.

### New or Affected Resource(s)

- aws_rds_cluster_instance

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bflad** [comment]
Hi @Streadz 👋 Thank you for submitting this. The `ca_cert_identifier` addition for the `aws_rds_cluster_instance` resource has recently been merged (via https://github.com/terraform-providers/terraform-provider-aws/pull/10954) and will release with version 2.44.0 of the Terraform AWS Provider tomorrow. See also the [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) for other recent changes that may be pending release.

**Comment by Streadz** [comment]
Thanks @bflad, I was just going through the codebase and saw that it was merged back in November! Are opened issues always solved this quickly? 😂
