### ISSUE TITLE
When setting endpoints{} in provider{}, they are ignored on init

### ISSUE THREAD

**Issue by flickerfly** [terraform-providers/terraform-provider-aws#11523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
[root@209ea7b30e47 aws-il5]# terraform -v
Terraform v0.12.6
+ provider.ansible v1.0.3
+ provider.aws v2.43.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

Can't init because provider not using endpoints as configured.

### Terraform Configuration Files

```hcl
provider "aws" {
    region = "${var.aws_region}"
    endpoints {
      ec2 = "https://vpce-****-****.us-west-1.vpce.amazonaws.com"
      sts = "https://vpce-*****-****.sts.us-west-1.vpce.amazonaws.com"
      elb = "https://vpce-****-****.elasticloadbalancing.us-west-1.vpce.amazonaws.com"
    }
}
```

I have tried also adding these to the provider to skip sts:
```
    skip_requesting_account_id = true
    skip_credentials_validation = true
```

### Debug Output

```
# terraform init
Initializing the backend...

Error: error validating provider credentials: error calling sts:GetCallerIdentity: RequestError: send request failed
caused by: Post https://sts.us-west-1.amazonaws.com/: EOF

# terraform apply
Error: error validating provider credentials: error calling sts:GetCallerIdentity: RequestError: send request failed
caused by: Post https://sts.us-west-1.amazonaws.com/: EOF
```

### Expected Behavior

Use the VPC endpoints for sts and other services instead of the standard ones. This VPC has no Internet gateway so I can not get to the normal endpoints and must use the VPC endpoints provided. 

### Actual Behavior

I was given an error that I couldn't get to the standard STS API endpoint. 

### Steps to Reproduce

0.  Configure VPC endpoint for sts in your AWS VPC
1.  Configure custom service endpoint in the provider{endpoints{sts=""} as described here: https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html
2. `terraform init`

Instead, try with AWS CLI sts command like this and find it working:
`aws sts get-caller-identity --endpoint-url="https://vpce-*****-*****.sts.us-west-1.vpce.amazonaws.com"`

### References

https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html

**Comment by ewbankkit** [comment]
@flickerfly Are you using the S3 backend for Terraform state? If so, then it has its own configuration where you can customize various AWS service endpoints.
See: https://www.terraform.io/docs/backends/types/s3.html#configuration-variables.

**Comment by flickerfly** [comment]
Thank you, that is true and I'd forgotten to consider that.
