### ISSUE TITLE
Error creating API Gateway Stage: ConflictException: Stage already exists

### ISSUE THREAD

**Issue by chgangaraju** [terraform-providers/terraform-provider-aws#1153]
I am trying to deploy an API in API Gateway with cloudwatch logs enabled.  As given in this   [documentation](https://www.terraform.io/docs/providers/aws/r/api_gateway_method_settings.html), it's creating two stages (dev, prod). If i provide two stage names in `aws_api_gateway_deployment`, `aws_api_gateway_stage` which is creating two stages. If i give a same name, It's throwing an error saying `Stage already exists`

It looks like its not possible to create a single stage with cloudwatch logs enabled using terraform?

    resource "aws_api_gateway_deployment" "test-deploy" {
      depends_on = [ /*something goes here*/]
    
      rest_api_id = "${aws_api_gateway_rest_api.test.id}"
      stage_name  = "test"
    
      variables = {
        "function" = "${var.lambda_function_name}"
      }
    }
    
    resource "aws_api_gateway_stage" "test" {
      stage_name = "${var.stage_name}"
      rest_api_id = "${aws_api_gateway_rest_api.test.id}"
      deployment_id = "${aws_api_gateway_deployment.test-deploy.id}"
    }
    
    resource "aws_api_gateway_method_settings" "settings" {
      rest_api_id = "${aws_api_gateway_rest_api.test.id}"
      stage_name  = "${aws_api_gateway_stage.test.stage_name}"
      method_path = "*/*"
    
      settings {
        metrics_enabled = true
        logging_level = "INFO"
      }
    }

Error:

    aws_api_gateway_stage.test: Error creating API Gateway Stage: ConflictException: Stage already exists

I can't use `aws_api_gateway_method_settings` without `aws_api_gateway_stage`, `aws_api_gateway_deployment` which creates two different stages.

**Comment by chgangaraju** [comment]
It seems like a documentation problem and the example given [here](https://www.terraform.io/docs/providers/aws/r/api_gateway_method_settings.html). `aws_api_gateway_deployment` creates a stage, but i faced a issue saying stage does not exist when i don't have `depends_on` statement. Its working with the following code.

    resource "aws_api_gateway_deployment" "test-deploy" {
      depends_on = [ /*something goes here*/]

      rest_api_id = "${aws_api_gateway_rest_api.test.id}"
      stage_name  = "${var.stage_name}"

      variables = {
        "function" = "${var.lambda_function_name}"
      }
    }

    resource "aws_api_gateway_method_settings" "settings" {
      depends_on  = ["aws_api_gateway_deployment.test-deploy"]
      rest_api_id = "${aws_api_gateway_rest_api.test.id}"
      stage_name  = "${var.stage_name}"
      method_path = "*/*"

      settings {
        metrics_enabled = true
        logging_level = "INFO"
      }
    }

It would be good if [this documentation](https://www.terraform.io/docs/providers/aws/r/api_gateway_method_settings.html) can be updated with a simple example without complicating/creating multiple stages.

**Comment by viswaug** [comment]
This is still an issue IMHO. I am running into it too. Not have a stage resource works like above since the deployment resource creates it, but it should still be considered a bug since we are not able to use both the resources in the script which seems like a valid thing to do.

Can we consider opening it back up again?

**Comment by Leopard2A5** [comment]
I'm having the same issue, i can't create a `deployment` resource with the same `stage_name` as in a `stage` resource. `stage_name` is required in the `deployment` resource but there you can't specify all the properties that you can specify in a `stage` resource. IMHO this isn't fixed and should be reopened.

**Comment by SachinMule** [comment]
Yes, this needs to be reopened.
I get ConflictException when i use "aws_api_gateway_deployment" and "aws_api_gateway_stage" because i want to set the "cache_cluster_size" on the stage.

**Comment by Puneeth-n** [comment]
Yea, had this issue few months ago. the trick is to depend on all related methods and integration and to just use the deployment and not the stage. The method_settings should then depend on the deployment.

**Comment by serialseb** [comment]
This prevents assigning a client certificate to the stage that gets implicitly created by the deployment, or any other property on `aws_api_gateway_stage`, unless I'm misunderstanding something.

**Comment by svyandun** [comment]
Has anyone figured a way to make this work?
I too get a conflict when trying to enable cache on a stage.

**Comment by fmthoma** [comment]
I'm running into this bug, too. I need to explicitly configure a stage to associate it with a given certificate.

[The AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/apigateway/create-deployment.html) says:
> `--stage-name (string)`
>
> The name of the Stage resource for the Deployment resource to create.
>
> `--stage-description (string)`
>
> The description of the Stage resource for the Deployment resource to create.

So apparently, AWS itself creates a new stage for each deployment. Indeed, Terraform [only calls the AWS API](https://github.com/terraform-providers/terraform-provider-aws/blob/ddd2205c6b6cc547ce5a940f9a16bf66f3276c3a/aws/resource_aws_api_gateway_deployment.go#L82):

```go
	deployment, err := conn.CreateDeployment(&apigateway.CreateDeploymentInput{
		RestApiId:        aws.String(d.Get("rest_api_id").(string)),
		StageName:        aws.String(d.Get("stage_name").(string)),
		Description:      aws.String(d.Get("description").(string)),
		StageDescription: aws.String(d.Get("stage_description").(string)),
		Variables:        aws.StringMap(variables),
        })
```

However, according to the AWS documentation, it seems that `--stage-name` is not a required parameter. So I think the easy fix would be to make `stage_name` and `stage_description` optional in `aws_api_gateway_deployment`.

**Comment by vlad2** [comment]
Hello,

Any solution to this issue?

**Comment by mhvelplund** [comment]
For posterity, the solution is to set `stage_name   = ""` in the `aws_api_gateway_deployment` resource.
