### ISSUE TITLE
Error if aws_ssm_activation is manually removed from AWS

### ISSUE THREAD

**Issue by fatbasstard** [terraform-providers/terraform-provider-aws#11534]
If a SSM Activation is manually removed in AWS the Terraform plan fails with:

`Error: ActivationList was nil or empty`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v.0.12.19

### Affected Resource(s)

* aws_ssm_activation

### Expected Behavior

If a SSM activation is manually removed, I expect Terraform to detect the SSM activation to be missing and recreate it.

### Actual Behavior
Terraform returns an error:

`Error: ActivationList was nil or empty`

Only way to fix this is to manually remove the activation from the state file.

### Steps to Reproduce

1. Create SSM Activation ([The sample from the documentation is sufficient](https://www.terraform.io/docs/providers/aws/r/ssm_activation.html#example-usage))
2. `terraform apply`
3. Manually remove the activation from AWS
2. `terraform plan`

### References

* [Source](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_activation.go#L152)

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.47.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
