### ISSUE TITLE
iam group data source does not offer users output

### ISSUE THREAD

**Issue by eredi93** [terraform-providers/terraform-provider-aws#1154]
i opened https://github.com/terraform-providers/terraform-provider-aws/issues/1138 and asked for the data source, really happy that it got added but my problem is still not fixed as i need a list of users ARN and names.
could you add users as part of Attributes Reference ? the API response has a Users array, what i'm proposing is having a users_arn and users_name arrays as outputs of the data source.

ref https://github.com/terraform-providers/terraform-provider-aws/issues/1138#issuecomment-315332550

**Comment by galindro** [comment]
@stack72 @bflad is there an ETA for this enhancement be developed? I would like to have this return to add IAM users from a given IAM group to configmap/aws-auth from AWS EKS cluster, as a workarround for the problem reported in https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/176.

**Comment by bflad** [comment]
This functionality was recently released in [version 2.36.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2360-november-14-2019). 👍
