### ISSUE TITLE
ECS task definition's container definitions ignore firelensConfiguration

### ISSUE THREAD

**Issue by shiftie** [terraform-providers/terraform-provider-aws#11551]
### Terraform Version

Terraform v0.12.15
+ provider.aws v2.14.0

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

```hcl
resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = 
  [{
    "image": "amazon/aws-for-fluent-bit:latest",
    "name": "log_router",
    "cpu": 10,
    "memory": 256,
    "essential": true,
    "firelensConfiguration": {
        "type": "fluentbit",
        "options": {
            "enable-ecs-log-metadata": "true"
        }
    }
  }]
}
```

### Expected Behavior

Container should have `firelensConfiguration` defined OR if we define only this container, it should say:
`When a firelensConfiguration object is specified, at least one container has to be configured with the awsfirelens log driver.`.

### Actual Behavior

`firelensConfiguration` is null.
Seems like `firelensConfiguration` attribute is ignored.

### Steps to Reproduce

1. `terraform apply`

**Comment by blckct** [comment]
You're using a very old version of provider, try updating it to version that was published after FireLens was announced.

**Comment by shiftie** [comment]
that did the trick @blckct  ty!! 👍
