### ISSUE TITLE
aws_s3_bucket: UnsupportedArgument acceleration_status in us-gov region

### ISSUE THREAD

**Issue by dekimsey** [terraform-providers/terraform-provider-aws#11556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.19
+ provider.aws v2.43.1
+ provider.null v2.1.2
+ provider.template v2.1.2
```
### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

Note it doesn't matter if `acceleration_status` is set to Suspended or Enabled.

```hcl
resource "aws_s3_bucket" "this" {
  bucket_prefix       = "foo-"
  acl                 = "private"
  acceleration_status = var.acceleration_status
  tags = {
    terraform = "true"
  }

```

### Debug Output

None

### Panic Output

None

### Expected Behavior

s3 bucket created successfully.

### Actual Behavior

```
Error: Error putting S3 acceleration: UnsupportedArgument: The request contained an unsupported argument.
    status code: 400, request id: D6C1756A80C277E5, host id: rT2dEL2WsDrSu5+np5sJrBM6INmF3MvTRRS7vB5hvaGdUtlZkk4XRCzTsKPmTwyi3zKiWyJUe6o=
  on .terraform/modules/repo-tw-custom-el6/main.tf line 7, in resource "aws_s3_bucket" "this":
   7: resource "aws_s3_bucket" "this" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

US government region

### References

* #8664

**Comment by slapula** [comment]
I was under the impression that this feature does not exist yet in Govcloud.  Has that changed recently?

**Comment by dekimsey** [comment]
Correct, it doesn't. I'm hoping that instead of failing & aborting, the parameter can be ignored similar to the implementation in the referenced ticket #8664.

**Comment by slapula** [comment]
Why do you need to keep the parameter around when operating in a region that doesn't support it? Versus just removing the parameter etc...

**Comment by dekimsey** [comment]
Fair question, in our case we operate in multiple regions and this parameter is being set by a module. I don't recall, but passing null didn't seem to work either. I think because null meant the default of `true` was being taken in our variable.

We have a couple of variables that indicate this is the gov cloud region and need certain features disabled. On some resources a simple `false` suffices, however this resource it does not and will error.

**Comment by c4milo** [comment]
@dekimsey, let me know if #12049 does it for you.

**Comment by dekimsey** [comment]
@c4milo, I'm going to have to take this one on faith.

**Comment by dekimsey** [comment]
(Okay. Didn't mean to close this. That's what I get for replying on mobile.)

Anyway. @c4milo I'm going to take your patch on faith. I cannot test it because getting our gov team to run a custom build of the provider will be quite an exercise. Patch is so simple and is handling the error I saw, I have faith it'll work perfectly. Thank you for identifying such a simple fix!

**Comment by c4milo** [comment]
@dekimsey, please keep us posted!

**Comment by gdavison** [comment]
@dekimsey what is the behaviour of the resource if your `var.acceleration_status` is set to `null` instead of a value? This is a Terraform language feature that might address the problem.

**Comment by gdavison** [comment]
Hi @dekimsey, sorry for the delay in getting back to this issue. I addressed an associated PR, but left this hanging.

To work around the differences in AWS support by region, you could make the value of `acceleration_status` either a variable or `local` value, and set it to `null` if the region does not support it.

For example
```terraform
data "aws_region" "current" {}

locals {
  acceleration_status = data.aws_region.current.name != "us-gov-west-1" ? "Enabled" : null
}

resource "aws_s3_bucket" "bucket" {
  bucket              = "my_bucket"
  acceleration_status = local. acceleration_status
}
```

I'm going to close this issue since this sample should allow you to work in multiple regions and partitions. If you run into problems, please open another issue.
