### ISSUE TITLE
Add support for Target Tracking Policies in EC2 Auto Scaling

### ISSUE THREAD

**Issue by thomasbiddle** [terraform-providers/terraform-provider-aws#1156]
Target Tracking Policies have just been added into EC2 Auto Scaling.

Behind the scenes, this is using a similar configuration to the new DynamoDB autoscaling; so this may be in conjunction with #888 .

**Blog Post:** https://aws.amazon.com/blogs/aws/new-target-tracking-policies-for-ec2-auto-scaling/

**User Guide:** https://docs.aws.amazon.com/autoscaling/latest/userguide/as-scaling-target-tracking.html

**Comment by Jonesie** [comment]
👍

**Comment by nickm4062** [comment]
was this addressed in #1650 ?

**Comment by flyinprogrammer** [comment]
@nickm4062 i don't believe so. App Autoscaling and Autoscaling are different resource types.

**Comment by hermes-pimentel** [comment]
Any news ?

**Comment by fahrenq** [comment]
+ Any news?

**Comment by hibiitt** [comment]
any update please

**Comment by rryke** [comment]
also looking to use this :)

**Comment by ershad** [comment]
Waiting for this feature :)

**Comment by acannon828** [comment]
+1

**Comment by radeksimko** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/2611 was just merged and will be part of the next release (`1.10.0`).

Thanks for all the interest expressed via upvote reactions. 👍

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
