### ISSUE TITLE
aws_transfer_server: support Elastic IPs

### ISSUE THREAD

**Issue by marcoreni** [terraform-providers/terraform-provider-aws#11569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS Transfer now supports Elastic IPs. With this, there's no more need to create a NLB to expose the server in known IP address.

Terraform provider should support these as well.

### New or Affected Resource(s)
* `aws_transfer_server`

### Potential Terraform Configuration

```hcl
resource "aws_transfer_server" "foo" {
  endpoint_details {
    address_allocation_ids = ["eipalloc-..."]
    subnet_ids = ["subnet-..."]
    vpc_id = "vpc-..."
    vpc_endpoint_id = "vpce-..."
  }
  endpoint_type = "VPC"
}
```

### References
Announcement: https://aws.amazon.com/about-aws/whats-new/2020/01/aws-transfer-for-sftp-supports-vpc-security-groups-and-elastic-ip-addresses/
Docs: https://docs.aws.amazon.com/transfer/latest/userguide/create-sftp-server-in-vpc.html
Requires [AWS SDK v1.28.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.0):
* #11501

**Comment by bflad** [comment]
Support for the `VPC` endpoint type (including additional `endpoint_details` arguments to support EIPs) has been merged and will release with version 3.8.0 of the Terraform AWS Provider, likely later today. Thanks to @sshearn for the implementation. 👍
