### ISSUE TITLE
Egress-only internet gateway resource tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Egress-only internet gateways now support [resource tagging](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources).

### New or Affected Resource(s)

* [`aws_egress_only_internet_gateway`](https://www.terraform.io/docs/providers/aws/r/egress_only_internet_gateway.html)

### Potential Terraform Configuration

```hcl
resource "aws_egress_only_internet_gateway" "example" {
  tags = {
    Usage = "For example use only"
  }
}
```

### References

Requires [AWS SDK v1.28.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.0):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11501

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/1319
* https://github.com/terraform-providers/terraform-provider-aws/issues/5103

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.57.0 of the Terraform AWS Provider, later this week. Thanks to @stefansundin for the implementation. 👍
