### ISSUE TITLE
Provide DNS name from Global Accelerator resource

### ISSUE THREAD

**Issue by wlonkly** [terraform-providers/terraform-provider-aws#11579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Route53 supports ALIAS records pointing at Global Accelerator (GA) listeners _but_ the ALIAS needs to point to the DNS name of the GA. The current Terraform resource doesn't export a DNS name/zone attribute, so you can't wire up an alias with Terraform.

(The workaround is to create an A record pointing at the static `ip_addresses` of the GA, but ALIASes are a nice bit of self-documentation instead of having magic addresses that you have to cross-reference.)

### New or Affected Resource(s)

* `aws_globalaccelerator_accelerator`

### Potential Terraform Configuration

```hcl
resource "aws_globalaccelerator_accelerator" "example" {
  name            = "example"
  ip_address_type = "IPV4"
  enabled         = true
}

resource "aws_route53_record" "record" {
  zone_id = "SOME_ZONE_ID"
  name    = "ga.example.com"

  alias {
    name                   = aws_globalaccelerator_accelerator.example.dns_name
    zone_id                = aws_globalaccelerator_accelerator.example.zone_id
    evaluate_target_health = false
  }
}
```

### References

* https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html (returns `DNSName`). 
* https://docs.aws.amazon.com/global-accelerator/latest/dg/about-accelerators.dns-addressing.html
* It's not clear to me where `zone_id` would come from

**Comment by bflad** [comment]
Support for `dns_name` and `hosted_zone_id` attributes has been merged and will release with version 2.52.0 of the Terraform AWS Provider, Thursday next week. Thanks to @wlonkly for the implementation. 👍
