### ISSUE TITLE
r/aws_inspector_assessment_template: Support resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Inspector assessment templates support resource tags.

### New or Affected Resource(s)

* [`aws_inspector_assessment_template`](https://www.terraform.io/docs/providers/aws/r/inspector_assessment_template.html)

### Potential Terraform Configuration

```hcl
resource "aws_inspector_assessment_template" "example" {
  tags = {
    Usage = "example"
  }
}
```

### References

[User guide](https://docs.aws.amazon.com/inspector/latest/userguide/inspector_assessments.html#inspector-assessment-templates).

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. Thanks to @ewbankkit for the implementation. 👍
