### ISSUE TITLE
Upcoming Lambda API change

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-aws#11609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS will be changing how lambda's in a VPC work.
https://aws.amazon.com/blogs/compute/coming-soon-updated-lambda-states-lifecycle-for-vpc-networking/
### New or Affected Resource(s)

* aws_lambda_function

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "pre_signup_lambda" {
  filename      = var.pre_signup_archive
  function_name = "${module.default_label.id}-Pre-Signup"
  description   = "Lambda function for pre-signup for ${var.name} in ${var.environment} environment"
  role          = aws_iam_role.lambda.arn
  handler       = "lambdas/preSignup.handler"

  vpc_config {
      subnet_ids         = module.vpc.private_subnets
      security_group_ids = [aws_security_group.fusion_lambda.id]
  }

  runtime     = "nodejs10.x"
  timeout     = 6
  memory_size = 240
}
```

### References

I read through the code and I don't see anywhere that the status of the lambda is taken into consideration. In the lambda read function we could probably check if the lambda is deployed into a VPC and if so we could do a retry operation until the status comes back as "Active".

**Comment by bflad** [comment]
Hi @shadycuz 👋 Thank you for writing this up.

This should already be handled by https://github.com/terraform-providers/terraform-provider-aws/pull/11016, which was released in version 2.40.0 of the Terraform AWS Provider. If there are additional changes needed, please let us know. Thanks.
