### ISSUE TITLE
Renaming aws_iot_policy does not work

### ISSUE THREAD

**Issue by fatbasstard** [terraform-providers/terraform-provider-aws#11684]
Renaming of an `aws_iot_policy` does not work. The resource in AWS is not renamed, only the `Name` in the state is altered. This also breaks referring resources like `aws_iot_policy_attachment`  which returns `ResourceNotFoundException: Policy not found` exceptions.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v.0.12.19

### Affected Resource(s)

* aws_iot_policy
* aws_iot_policy_attachment

### Expected Behavior

The IoT policy iteself is renamed and everything works like a charm.

### Actual Behavior

Terraform things the Name is changed, but it actually is not, causing the State file to be "wrong" and breaking resources that reference to an IoT policy

### Steps to Reproduce

1. Create a IoT Policy ([The sample from the documentation is sufficient](https://www.terraform.io/docs/providers/aws/r/iot_policy.html)) 
2. `terraform apply`
3. rename the IoT Policy
4. `terraform apply` and it breaks

### Important Factoids

- After the rename of the IOT policy, the resource in AWS is not altered
- State file content after the rename:

```hcl
    {
      "mode": "managed",
      "type": "aws_iot_policy",
      "name": "pubsub",
      "provider": "provider.aws",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:iot:eu-west-1:<XXX>:policy/PubSubToAnyTopic",
            "default_version_id": "1",
            "id": "PubSubToAnyTopic",
            "name": "PubSubToAnyTopic_Rename",
            "policy": "<XXX>"
          },
          "private": "<XXX>"
        }
      ]
    },
```
- Error thrown on the IoT Policy attachment: 

```
Error: error attaching policy PubSubToAnyTopic_Rename to target arn:aws:iot:eu-west-1:<XXX>:cert/<XXX>: ResourceNotFoundException: Policy not found
```

**Comment by bflad** [comment]
The above fix has been merged and will release with version 2.68.0 of the Terraform AWS Provider, later this week. Thanks to @ewbankkit for the implementation. 👍
