### ISSUE TITLE
Incorrect default value for Serverless RDS minimum capacity

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#11698]
In the resource `aws_rds_cluster`, the default value for `scaling_configuration.min_capacity` is defined as `2` in the Terraform schema, but the AWS API returns `1`.

Correcting this will be a potentially breaking change.

### References

* #11602

**Comment by anGie44** [comment]
Breaking change has been merged and will release with the upcoming`v3.0.0` of the Provider.
