### ISSUE TITLE
Api Gateway Data Source can fail to set root_resource_id attribute if the API contains more than 25 routes.

### ISSUE THREAD

**Issue by Jacob-Laverty** [terraform-providers/terraform-provider-aws#11695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Tested on TF version 0.11.14 and provider version 2.44.0

### Affected Resource(s)

* data.aws_api_gateway_rest_api

### Expected Behavior

The AWS provider should set the root_resource_id regardless of the number of routes on the API.

### Actual Behavior

The GetResources call currently being used in the ApiGateway resource only returns a default 25 routes. It then iterates over those 25 routes looking for the root route ("/") and sets the attribute when found. If there are more than 25 routes on the API it can incorrectly fail to set the root_resource_id.

Code in question: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.45.0/aws/data_source_aws_api_gateway_rest_api.go#L58-L70

Fix is pretty simple as the AWS Go SDK offers a paginated GetResourcePages call. We just paginate through the resources applying the same logic and stop pagination when the root is found. I'll submit a follow up PR after creating the issue, just wanted to get it documented :)

### Steps to Reproduce

This is somewhat tricky to reproduce exactly as I'm not entirely sure how AWS determines in what order to return the routes on the API. However you can create an API with > 25 routes and add a small debug statement in the Code linked above and see it will only ever look through at most 25 routes in its current state.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.47.0 of the Terraform AWS Provider, tomorrow. Thanks to @Jacob-Laverty for the implementation. 👍
