### ISSUE TITLE
ECS Service Incorrectly Marked as Changed if it has a Placement Strategy

### ISSUE THREAD

**Issue by pnquest** [terraform-providers/terraform-provider-aws#1169]
### Terraform Version
v0.9.11

### Affected Resource(s)
- aws_ecs_service

### Terraform Configuration Files
```hcl
resource "aws_ecs_service" "service" {
    name = "${var.task_name}${var.environment}"
    cluster = "${var.cluster_id}"
    task_definition = "${module.tsk.task_arn}"
    desired_count = "${var.task_desired_count}"
    iam_role = "${var.task_role_arn}"

    placement_strategy {
        type = "spread"
        field = "host"
    }
}
```

### Expected Behavior
There was no change to the service definition, so `terraform plan` should have said there were no changes to apply.

### Actual Behavior
Terraform thinks the `placement_strategy` has changed even though it did not. And re-creates the service on every apply. The only workaround I have found for this is removing the `placement_strategy`

### Steps to Reproduce
1.  Create an `aws_ecs_service` with the placement strategy shown in the above code and apply it.
2.  Immediately run `terraform plan` again and it will show the service as changed.
3. You can repeat this infinitely no matter how many times you apply the supposed changes.

### References
- [issue 11644][terraform-11644] in the main Terraform repo states that the issue (or something very similar) was fixed in version 0.8.6, but this is not the case.

[terraform-11644]: https://github.com/hashicorp/terraform/issues/11644

**Comment by dcloud9** [comment]
Similar behaviour in `aws_ecs_task_definition`. No code change, but TF `0.11.0` and aws-provider `1.3.0` always trigger a `(forces new resource)` on container_definitions and id.

**Comment by bflad** [comment]
@dcloud9 I think you might be referencing a different bug that was fixed in terraform-provider-aws 1.3.1: #2339 

@pnquest this should be fixed in terraform-provider-aws 0.1.3: #1025

**Comment by dcloud9** [comment]
Thanks @bflad. Will update to `1.3.1` soon.

**Comment by bflad** [comment]
Closing as the mentioned bugs should've been addressed previously (please correct me if I'm wrong): https://github.com/terraform-providers/terraform-provider-aws/issues/1169#issuecomment-348099755

Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
