### ISSUE TITLE
More descriptive error for ecs_service when target group is not registered to LB

### ISSUE THREAD

**Issue by Crusad** [terraform-providers/terraform-provider-aws#11706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am creating and `ecs_service` and using `load_balancer` block. Because I don't want to apply certain changes now, I commented out a `aws_lb_listener_rule` to not apply. Because of that the target group, to which the ecs_service should attach to and register new tasks into, is not associated to the load_balancer and apply fails. It all makes sense except the error I was receiving - it's not very descriptive and clear. I enabled TF_LOG=DEBUG and then I found the problem. 
It took me a while to figure out the problem and might be just my lack of knowledge but would it be possible to pass this DEBUG output to normal terraform output? And/Or update the documentation to explain the target group must be attached to a load balancer?

I received:
```
Error: InvalidParameterException:  "<name of ecs service>"

  on main.tf line 137, in resource "aws_ecs_service" "name":
 137: resource "aws_ecs_service" "name" {
```
When enabling DEBUG I discovered:
```
2020-01-22T11:29:41.083+0100 [DEBUG] plugin.terraform-provider-aws_v2.45.0_x4: 2020/01/22 11:29:41 [DEBUG] [aws-sdk-go] {"__type":"InvalidParameterException","message":"The target group with targetGroupArn arn:aws:elasticloadbalancing:ap-southeast-2:XXXXXXXXXXXX:targetgroup/XXXXXXXX/XXXXXXXXX does not have an associated load balancer."}
```
### New or Affected Resource(s)

* aws_ecs_service, aws_lb_listener_rule, aws_lb_target_group

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "name" {
  name = local.name_prefix
  cluster = aws_ecs_cluster.isl-name.arn
  task_definition = aws_ecs_task_definition.name_task.arn
  #iam_role = aws_iam_role.ecs_role.name
  scheduling_strategy = "DAEMON"
  depends_on = [aws_lb_listener_rule.webfacing_odata,aws_lb_listener.internal_443]

  load_balancer {
    target_group_arn = aws_lb_target_group.isl-name-tg-443.arn
    container_name = local.name_prefix
    container_port = 443
  }
  load_balancer {
    target_group_arn = aws_lb_target_group.isl-name-tg-8443.arn
    container_name = local.name_prefix
    container_port = 443
  }

# resource "aws_lb_listener_rule" "webfacing_name" {} - commented out
```

**Comment by ppodbielski** [comment]
up

**Comment by Crusad** [comment]
Doing more investigation - it seems that my original troubleshooting was wrong. I am still receiving this error even with the listener rule in place and on subsequent applies when only the ecs_service is missing. The error I see on TF_LOG=ERROR is 

```
2020/01/22 14:58:06 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: InvalidParameterException:  "<name of ecs service>"
2020/01/22 14:58:06 [ERROR] <root>: eval: *terraform.EvalSequence, err: InvalidParameterException:  "<name of ecs service>"
```

**Comment by Crusad** [comment]
Maybe a symptom of #11682?

**Comment by bflad** [comment]
Hi folks 👋 Thank you for reporting this and sorry you are running into trouble here. The error code and symptoms indicate that this is related to https://github.com/terraform-providers/terraform-provider-aws/issues/11682 (which is a regression where the error message is not surfaced by the AWS Go SDK) so to consolidate discussions and efforts, I'm going to close this issue in preference of the existing one. The good news is that this should be resolved via AWS Go SDK update today and Terraform AWS Provider release tomorrow. 👍
