### ISSUE TITLE
cloudtrail provider keeps reapplying event_selector

### ISSUE THREAD

**Issue by tl-adrian-bridgett** [terraform-providers/terraform-provider-aws#11712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform v0.12.19
+ provider.aws v2.44.0

### Affected Resource(s)

* aws_cloudtrail

### Terraform Configuration Files

```hcl
resource "aws_cloudtrail" "cloudtrail" {
  name                  = var.name
  s3_bucket_name        = var.s3_bucket
  is_multi_region_trail = true
  is_organization_trail = true
  event_selector {
    include_management_events = true
    read_write_type           = "WriteOnly"
  }
}
```

### Debug Output

https://gist.github.com/tl-adrian-bridgett/3b9371e77fd1ae00c33123d1190e1521

### Expected Behavior

Nothing (the event selector is already setup this way according to AWS console (and rerunning TF doesn't make a difference).

### Actual Behavior

It "changes". 

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply` once more - this shows the change wants to be done again (but has actually succeeded)

**Comment by klauern** [comment]
I'm seeing this on the `2.47.0` version of the provider.aws version as well.

**Comment by tgourley01** [comment]
ETA on this?

**Comment by cloudyparts** [comment]
Still seeing this with the latest provider 2.61.0

**Comment by bflad** [comment]
Hi folks 👋  The fix for this issue should be merged and will release with version 2.68.0 of the Terraform AWS Provider, likely later today. Thanks to @ts-tek for the implementation. 👍

**Comment by rossmckelvie** [comment]
@bflad I am using provider 2.68.0 and this issue persists. I still need to use the lifecycle workaround to avoid this change on every apply.

For anyone looking here is the workaround I am using
```hcl
  # TODO: remove lifecycle once above linked issue is resolved. lifecycle is a temporary workaround
  lifecycle {
    ignore_changes = [event_selector]
  }
```

**Comment by bflad** [comment]
@rossmckelvie can you please open a [new bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) and include your configuration? Thanks.

**Comment by rossmckelvie** [comment]
@bflad sure but it is same as this ticket, as well as #3697

**Comment by bflad** [comment]
@rossmckelvie below is the test configuration we are using, which does not display any `event_selector` differences after apply:

https://github.com/terraform-providers/terraform-provider-aws/blob/3f12b61ae5c088a57eb5e3e21977c64bc04cec25/aws/resource_aws_cloudtrail_test.go#L1348-L1356

This seems to resemble the original issue configuration above other than enabling multi-region/organization support. If these two settings are influencing the perpetual difference, then we will need to capture those as a separate test case and fix the issue separately.
