### ISSUE TITLE
Failure to create aws_elasticache_cluster due to CacheSubnetGroupNotFoundFault

### ISSUE THREAD

**Issue by Kentzo** [terraform-providers/terraform-provider-aws#1171]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_elasticache_cluster
- aws_elasticache_subnet_group

### Terraform Configuration Files
```hcl
resource "aws_elasticache_cluster" "redis" {
  cluster_id = "ID"
  engine = "redis"
  node_type = "cache.t2.micro"
  port = 6379
  num_cache_nodes = 1
  parameter_group_name = "default.redis3.2"
  subnet_group_name = "subnet"
}

resource "aws_elasticache_subnet_group" "Subnet" {
  name = "subnet"
  subnet_ids = ["..."]
}
```

### Expected Behavior
Terraform should wait for creation of all resources and then exit successfully.

### Actual Behavior
Terraform fails to create a resource with:
```
Error applying plan:

1 error(s) occurred:

* aws_elasticache_cluster.redis: 1 error(s) occurred:

* aws_elasticache_cluster.redis: Error creating Elasticache: CacheSubnetGroupNotFoundFault: Cache Subnet Group subnet does not exist.
    status code: 400, request id: ...

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This error is rare, most of the time the very same scripts work flawlessly.
Running `terraform apply` for the second time in a row fixes the issue.

**Comment by Kentzo** [comment]
Related problem happens while running the `terraform destroy` command:

```
1 error(s) occurred:

* aws_elasticache_subnet_group.Subnet (destroy): 1 error(s) occurred:

* aws_elasticache_subnet_group.Subnet: CacheSubnetGroupInUse: Cache subnet group subnet is currently in use by a cache cluster.
	status code: 400, request id: ...
```

It looks like some dependency is not being awaited properly.

**Comment by stack72** [comment]
Hi @Kentzo 

Right now, this Terraform config doesn't know that there is a dependency between the 2 resources. When we need to specify a specific dependency, we can use interpolation for this as follows:

```
resource "aws_elasticache_cluster" "redis" {
  cluster_id = "ID"
  engine = "redis"
  node_type = "cache.t2.micro"
  port = 6379
  num_cache_nodes = 1
  parameter_group_name = "default.redis3.2"
  subnet_group_name = "${aws_elasticache_subnet_group.Subnet.name}"
}

resource "aws_elasticache_subnet_group" "Subnet" {
  name = "subnet"
  subnet_ids = ["..."]
}
```

That will build the correct dependency tree between the resources. Without this dependency, Terraform will assume that `subnet` (the subnet group) already exists in AWS and will try and find it by name

Hope this helps

Paul

**Comment by tombuildsstuff** [comment]
Closing this issue @stack72's request
