### ISSUE TITLE
Error on lb_target_group showing as ecs_service InvalidParameterException

### ISSUE THREAD

**Issue by biinari** [terraform-providers/terraform-provider-aws#11723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.45.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_ecs_service
* aws_lb_target_group

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "example" {
  name                 = "example"
  port                 = "80"
  protocol             = "HTTP"
  vpc_id               = "${var.vpc_id}"
  target_type          = "instance" # NOTE: should be "ip"
}

resource "aws_ecs_service" "example" {
  name            = "example"
  cluster         = "${aws_ecs_cluster.example.id}"
  task_definition = "${aws_ecs_task_definition.example.arn}"
  launch_type     = "FARGATE"

  network_configuration {
    assign_public_ip = true
    subnets          = ["${var.subnet_id}"]
    security_groups  = ["${aws_security_group.example.id}"]
  }

  load_balancer {
    target_group_arn = "${aws_lb_target_group.example.arn}"
    container_name   = "example"
    container_port   = "80"
  }
}
```

### Debug Output

*TODO: run with a minimal config to generate a reasonable and easily redactable debug output.*

In debug output, Response ecs/CreateService results in 400 Bad Request with:

```
{"__type":"InvalidParameterException","message":"The provided target group arn:aws:elasticloadbalancing:us-west-1:819738237059:targetgroup/stag-us-west-1-ember-nginx/83ef74e405d1e7f8 has target type instance, which is incompatible with the awsvpc network mode specified in the task definition."}
```

### Expected Behavior

Error message should explain that the target_type of lb_target_group is invalid.

### Actual Behavior

```
Error applying plan:

1 error occurred:
	* module.ember_nginx.aws_ecs_service.nginx: 1 error occurred:
	* aws_ecs_service.nginx: InvalidParameterException:  "staging-ember-nginx"
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @biinari 👋 Thank you for reporting this and sorry you are running into trouble here. The error code and symptoms indicate that this is related to https://github.com/terraform-providers/terraform-provider-aws/issues/11706, https://github.com/terraform-providers/terraform-provider-aws/issues/11719, and https://github.com/terraform-providers/terraform-provider-aws/issues/11682 (which is a regression where the error messaging is not correctly surfaced by the AWS Go SDK) so to consolidate discussions and efforts, I'm going to close this issue in preference of #11682. The good news is that this should be resolved via AWS Go SDK update today and Terraform AWS Provider release tomorrow. 👍
