### ISSUE TITLE
Add support for Customer Managed CMK's for aws_kinesis_firehose_delivery_stream

### ISSUE THREAD

**Issue by pcktdmp** [terraform-providers/terraform-provider-aws#11721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for Customer Managed CMK's, currently only AWS owned CMK's are supported.

### New or Affected Resource(s)

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_kinesis_firehose_delivery_stream.go#L700

### Potential Terraform Configuration

```hcl

resource "aws_kinesis_firehose_delivery_stream" "extended_s3_stream" {
    server_side_encryption {
        enabled = true
        kms_key_arn = "<arn>"
    }
...
```

### References

https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html
https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.7.0 of the Terraform AWS Provider, later today. Thanks to @StevenKGER for the implementation. 👍
