### ISSUE TITLE
aws_route_tables data source returns a set but docs say it is a list

### ISSUE THREAD

**Issue by iloveicedgreentea** [terraform-providers/terraform-provider-aws#11738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.45.0

### Affected Resource(s)

data.aws_route_tables

### Terraform Configuration Files

```hcl

data "aws_route_tables" "source" {
  vpc_id = data.aws_vpc.source.id
}

  route_table_id            = data.aws_route_tables.source.ids[count.index]
}
```

### Expected Behavior

Docs say *.ids returns a LIST https://www.terraform.io/docs/providers/aws/d/route_tables.html#ids

### Actual Behavior

It actually returns a SET
`data.aws_route_tables.target.ids is set of string with 3 elements`

This happened after an upgrade to TF 12. Seems like the docs just need to get updated.

### Steps to Reproduce
Use the code above.

**Comment by iloveicedgreentea** [comment]
Note: it is correct here https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/d/subnet_ids.html.markdown

But not on the site

**Comment by freibuis** [comment]
sets suck! every run requires a forces replacement  :(
