### ISSUE TITLE
aws_sagemaker_notebook_instance - support for options

### ISSUE THREAD

**Issue by mateuszboryn** [terraform-providers/terraform-provider-aws#11734]
In resource aws_sagemaker_notebook_instance please add support for following options from API https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateNotebookInstance.html :
- DirectInternetAccess
- RootAccess
- VolumeSizeInGB
- AcceleratorTypes

**Comment by marinetteman2** [comment]
Immediate need

**Comment by barrettabelmode3** [comment]
Hi, 

I am happy to work on this - new to contribution here.. It looks in the contribution guide "issue is verified and categorized by a Terraform collaborator". Can someone triage this so the community can work on it? Thanks

**Comment by scarolan** [comment]
We would really like to see the feature, let us know how we can help.

**Comment by DrFaust92** [comment]
Closing as DirectInternetAccess, RootAccess, VolumeSizeInGB are merged and AcceleratorTypes has a specific issue #10208
