### ISSUE TITLE
Recently enabled EFS service in AWS China regions is using incorrect domain name.

### ISSUE THREAD

**Issue by mbokman** [terraform-providers/terraform-provider-aws#11749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.19
+ provider.aws v2.45.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_efs_file_system

### Terraform Configuration Files

```hcl
resource "aws_efs_file_system" "efs" {
  performance_mode = "generalPurpose"

  encrypted = true
}
```

### Expected Behavior

```hcl
$ terraform state show module.dbsdevlsp.aws_efs_file_system.efs\[0\]
# module.dbsdevlsp.aws_efs_file_system.efs[0]:
resource "aws_efs_file_system" "efs" {
    arn                             = "arn:aws-cn:elasticfilesystem:cn-north-1:xxxxxxxxxx:file-system/fs-abcdefgh"
    creation_token                  = "terraform-20200124105304526000000001"
    dns_name                        = "fs-abcdefgh.efs.cn-north-1.amazonaws.com.cn"
    encrypted                       = true
    id                              = "fs-abcdefgh"
    kms_key_id                      = "arn:aws-cn:kms:cn-north-1:xxxxxxxxxx:key/abcdefgh-1234-5678-90ab-cdefghijklmn"
    performance_mode                = "generalPurpose"
    provisioned_throughput_in_mibps = 0
    throughput_mode                 = "bursting"
}
```
### Actual Behavior

```hcl
$ terraform state show module.dbsdevlsp.aws_efs_file_system.efs\[0\]
# module.dbsdevlsp.aws_efs_file_system.efs[0]:
resource "aws_efs_file_system" "efs" {
    arn                             = "arn:aws-cn:elasticfilesystem:cn-north-1:xxxxxxxxxx:file-system/fs-abcdefgh"
    creation_token                  = "terraform-20200124105304526000000001"
    dns_name                        = "fs-abcdefgh.efs.cn-north-1.amazonaws.com"
    encrypted                       = true
    id                              = "fs-abcdefgh"
    kms_key_id                      = "arn:aws-cn:kms:cn-north-1:xxxxxxxxxx:key/abcdefgh-1234-5678-90ab-cdefghijklmn"
    performance_mode                = "generalPurpose"
    provisioned_throughput_in_mibps = 0
    throughput_mode                 = "bursting"
}
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This is in AWS China region cn-north-1.

### References

* It seems to me that aws/resource_aws_efs_file_system.go line 396: `func resourceAwsEfsDnsName(fileSystemId, region string) string` uses improper hardcoding for the domain name ("amazonaws.com") while the actual domain name used in cn-north-1 seems to be "amazonaws.com.cn".

**Comment by bflad** [comment]
Hi @mbokman 👋 Thank you for reporting this. We actually just merged the fix for this in https://github.com/terraform-providers/terraform-provider-aws/pull/11746, which will release with version 2.47.0 of the Terraform AWS Provider, Thursday next week. 👍
