### ISSUE TITLE
Terraform Resource "aws_ram_principal_association" does not accept list

### ISSUE THREAD

**Issue by brucebolden** [terraform-providers/terraform-provider-aws#11756]
!--- Please list the affected resources and data sources. --->

Terraform v0.12.20
provider.aws v2.46.0

### Terraform Configuration Files

```hcl
resource "aws_ram_principal_association" "target_account_id" {
  principal          = ["111111111111", "222222222222"]
  resource_share_arn = aws_ram_resource_share.mytgw.arn
}

```

### Debug Output

Error: Incorrect attribute value type

  on ../../modules/create-tgw-ss/ss-tgw-create.tf line 31, in resource "aws_ram_principal_association" "target_account_id":
  31:   principal          = ["111111111111", "222222222222"]

Inappropriate value for attribute "principal": string required.

### Expected Behavior

Terrform will share the resource to all accounts listed in the list

### Actual Behavior

Terraform responds that I am using an invalid data type

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
According to the AWS Docs, list are supported using "aws cli"
https://docs.aws.amazon.com/cli/latest/reference/ram/create-resource-share.html
### References

* #0000

**Comment by bflad** [comment]
Hi @brucebolden 👋 Thank you for submitting this. In the Terraform AWS Provider, we prefer 1:1 mappings with associations to simplify implementation and help operators prevent overlapping configurations. If you are interested in creating multiple associations, the Terraform configuration language supports the [`count` and `for_each` meta-arguments for resources](https://www.terraform.io/docs/configuration/resources.html#meta-arguments). e.g.

```hcl
terraform {
  required_providers {
    aws = ">= 1.59.0"
  }

  required_version = ">= 0.12.6"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_ram_resource_share" "example" {
  name = "example"
}

resource "aws_ram_principal_association" "example" {
  for_each = toset(["111111111111", "222222222222"])

  principal          = each.value
  resource_share_arn = aws_ram_resource_share.example.arn
}

```

```console
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ram_principal_association.example["111111111111"] will be created
  + resource "aws_ram_principal_association" "example" {
      + id                 = (known after apply)
      + principal          = "111111111111"
      + resource_share_arn = (known after apply)
    }

  # aws_ram_principal_association.example["222222222222"] will be created
  + resource "aws_ram_principal_association" "example" {
      + id                 = (known after apply)
      + principal          = "222222222222"
      + resource_share_arn = (known after apply)
    }

  # aws_ram_resource_share.example will be created
  + resource "aws_ram_resource_share" "example" {
      + allow_external_principals = false
      + arn                       = (known after apply)
      + id                        = (known after apply)
      + name                      = "example"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Since this is possible today and implemented as expected for consistency with other resources in this provider, we are going to close this out, but please don't hesitate to reach out again. Thanks!
