### ISSUE TITLE
VPC endpoint id doesn't match regex pattern in AWS SFTP server configuration

### ISSUE THREAD

**Issue by ParkhomenkoDmitro** [terraform-providers/terraform-provider-aws#11761]
### Terraform Version

hashicorp/terraform:0.12.6

### Affected Resource(s)

* aws_transfer_server

### Terraform Configuration Files

```hcl
resource "aws_transfer_server" "sftp_staging_server" {
  identity_provider_type = "SERVICE_MANAGED"

  endpoint_type = "VPC_ENDPOINT"

  endpoint_details {
    vpc_endpoint_id = aws_vpc.test.id
  }

tags = {
    NAME = "sftp-staging"
    ENV  = "staging"
  }
}
```

### Debug Output

https://gist.github.com/ParkhomenkoDmitro/06155ec0dcff2184d4d9f2a81d2242f3

### Expected Behavior

terraform should finish plan successfully for creating private AWS SFTP server in my VPC. The key point is that my VPC has id 'vpc-c28e7aee'.

### Actual Behavior

terraform plan failed
### Steps to Reproduce

1. `terraform plan`

**Comment by claydanford** [comment]
Hi @ParkhomenkoDmitro,

You put in a vpc id, where it expects a vpce-id.

Vpc, is not the same as vpc endpoint.

https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html
