### ISSUE TITLE
aws_kms_key: eventual consistency problem with tags

### ISSUE THREAD

**Issue by jurajseffer** [terraform-providers/terraform-provider-aws#11781]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.7
+ provider.aws v2.41.0

### Affected Resource(s)

* aws_kms_key

### Terraform Configuration Files

```hcl
locals {
  bucket_name = "some-bucket"
}

resource aws_kms_key bucket {
  description             = "KMS key for ${local.bucket_name} bucket"
  deletion_window_in_days = 14
}
```
### Expected Behavior

KMS key should have been fully created.

### Actual Behavior

Terraform created the key but failed to list the tags, error:
```
Error: error listing tags for KMS Key (***): NotFoundException: Key 'arn:aws:kms:***:key/***' does not exist
	status code: 400, request id: ***
```

### Steps to Reproduce

It appears to be a race condition as the same operation was applied to many different AWS accounts at the same time but only one failed this way.

Next plan shows tainted `aws_kms_key` resource and apply successfully finishes.

1. `terraform apply`

**Comment by jValdron** [comment]
I'm hitting the same race condition once in a while, with similar Terraform code:
```
resource "aws_kms_key" "rds_encryption" {
  description             = "Encrypts the source artifacts for RDS in an S3 bucket."
  deletion_window_in_days = 7
}
```

I believe the culprit is on this line: https://github.com/terraform-providers/terraform-provider-aws/blob/671177ac81c9ca9e4489b40616dd17a2c40b2794/aws/resource_aws_kms_key.go#L205

The `keyvaluetags.KmsListTags` call should probably have a retry, like every other calls in that method.

If that makes sense, I can try adding a retry to that call.
