### ISSUE TITLE
aws_eks_cluster's vpc_config attribute shouldn't be a list

### ISSUE THREAD

**Issue by yann-soubeyrand** [terraform-providers/terraform-provider-aws#11786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.46.0
```

### Affected Resource(s)

* aws_eks_cluster

### Expected Behavior

`aws_eks_cluster`'s `vpc_config` attribute is a list whereas it shouldn't. Indeed, `aws eks describe-cluster` doesn't return a list for the `resourcesVpcConfig` attribute.

### Actual Behavior

`aws_eks_cluster`'s `vpc_config` attribute is a list.

### References

Related issue: https://github.com/terraform-providers/terraform-provider-aws/issues/11775

**Comment by bflad** [comment]
Please see https://github.com/terraform-providers/terraform-provider-aws/issues/11775#issuecomment-579438063 as the explanation for closing this issue as well. Thanks again for submitting these.
