### ISSUE TITLE
VPC Endpoints for Sagemaker Notebooks do not resolve the service_name to the correct value

### ISSUE THREAD

**Issue by davidmlee-okta** [terraform-providers/terraform-provider-aws#11806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.14
+ provider.aws v2.46.0
```

### Affected Resource(s)

* aws_vpc_endpoint_service

### Terraform Configuration Files

```hcl
data "aws_vpc_endpoint_service" "sagemaker_notebook" {
  service = "aws.sagemaker.us-east-1.notebook"
}
```

### Debug Output
```
Error: Error refreshing state: 1 error occurred:
	* module.vpc_sip.data.aws_vpc_endpoint_service.sagemaker_notebook: 1 error occurred:
	* module.vpc_sip.data.aws_vpc_endpoint_service.sagemaker_notebook: data.aws_vpc_endpoint_service.sagemaker_notebook: error reading VPC Endpoint Service (com.amazonaws.us-east-1.aws.sagemaker.us-east-1.notebook): InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.us-east-1.aws.sagemaker.us-east-1.notebook' does not exist
	status code: 400, request id: c603bd2a-45cf-4056-b9ab-e16f5ea1671d
```

### Expected Behavior

The `data.aws_vpc_endpoint_service.sagemaker_notebook.service_name` should resolve to `aws.sagemaker.us-east-1.notebook`

### Actual Behavior

The `data.aws_vpc_endpoint_service.sagemaker_notebook.service_name` resolves incorrectly to `com.amazonaws.us-east-1.aws.sagemaker.us-east-1.notebook`

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
Sagemaker Notebook endpoints are the only service that does not follow the pattern of `com.amazonaws.{region}.{service}` and instead use `{aws_partition}.{service}.{region}.{component}` pattern.

### References
https://github.com/terraform-providers/terraform-provider-aws/blob/v2.46.0/aws/data_source_aws_vpc_endpoint_service.go#L82

This may need to be modified to support the unique service name for Sagemaker Notebook.

**Comment by ewbankkit** [comment]
[Developer guide](https://docs.aws.amazon.com/sagemaker/latest/dg/interface-vpc-endpoint.html).
@davidmlee-okta You can work around by setting `service_name = "aws.sagemaker.us-east-1.notebook"`

**Comment by davidmlee-okta** [comment]
@ewbankkit Thanks -- that is a functional workaround, so I am not blocked by this. However this may still be a minor pitfall for others as this is just one exception among all the other services. For example, `sagemaker.runtime` and `sagemaker.api` can use the standard `service = "sagemaker.runtime"` format, but this does not work for `service = "sagemaker.notebook"`.

**Comment by ewbankkit** [comment]
@davidmlee-okta Agreed that this needs fixing.

**Comment by bflad** [comment]
Documentation update has been merged and will deploy with the release of version 2.54.0 of the Terraform AWS Provider, later this week.
