### ISSUE TITLE
`make test` failure

### ISSUE THREAD

**Issue by RubyLi0612** [terraform-providers/terraform-provider-aws#1181]
### Terraform Version
Terraform v0.9.11

### Debug Output
https://gist.github.com/RubyLi0612/ac77311c33d0a595f9b2d615b736d99e

### Expected Behavior
pass `make test`

### Actual Behavior
Test fails with debug outputs

### Steps to Reproduce
I followed the documentation in this repository. I clone it to the suggested path. GOPATH is correctly set beforehand. Then cd into this local repo, running `make build` is fine. Then running `make test` gives the debug outputs.

### Important Factoids
From the output, it seems to be some error with configuration. I'm not sure id=f there should be some AWS key set beforehand. Yet following the instructed steps in README generates the error.

**Comment by trung** [comment]
I've encountered similar issue. Unsetting existing AWS_* environment variables would fix it.

**Comment by RubyLi0612** [comment]
Thank you. It solved the problem.
