### ISSUE TITLE
Disallow empty `filter` block on `aws_s3_bucket_metric` resource

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#11813]
The resource `aws_s3_bucket_metric` currently allows an empty `filter` block, which is meaningless, as it creates no filter.

When a filter is supplied, at least one of `prefix` or `tags` should be required.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_bucket_metric

### Terraform Configuration Files

This example should not be valid, since it is equivalent to not supplying a filter at all.
```hcl
resource "aws_s3_bucket_metric" "test" {
  bucket = aws_s3_bucket.test.id
  name   = "%s"
  filter {}
}
```

**Comment by anGie44** [comment]
The change in #14230 has been merged and will release with the upcoming `v3.0.0` of the Provider.
