### ISSUE TITLE
Minimum AWS FSx size is set to 3600GB instead of 1200GB

### ISSUE THREAD

**Issue by giacomodabisias** [terraform-providers/terraform-provider-aws#11828]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20

### Affected Resource(s)

AWS FSx

* aws_fsx_lustre_file_system

### Debug Output

Error: module.onebox.aws_fsx_lustre_file_system.permanent_storage: expected storage_capacity to be at least (3600), got 1200

### Expected Behavior

Creation of an FSx filesystem with 1200GB capacity

### Actual Behavior

produced an error message stating that the minimum capacity is 3600GB

### Steps to Reproduce

Create an FSx filesystem 

resource "aws_fsx_lustre_file_system" "fsx_storage" {
  storage_capacity = 1200
  subnet_ids       = ["test_subnet"]
}

### References

AWS announcement about the size decrease:
https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-fsx-lustre-reduces-minimum-file-system-size/

* #0000

**Comment by bflad** [comment]
For inspiration on how to address this, please see the similar decrease that was made in the `aws_fsx_windows_file_server` resource here: https://github.com/terraform-providers/terraform-provider-aws/pull/11272

**Comment by giacomodabisias** [comment]
@bflad thanks.
Can I just move on with this and make a PR for it?

**Comment by bflad** [comment]
The validation update has been merged and will release with version 2.48.0 of the Terraform AWS Provider, tomorrow. Thanks to @slapula for the implementation. 👍
