### ISSUE TITLE
Adding aws_rds_cluster_parameter_group to aws_rds_cluster_instance throws DBParameterGroupNotFound error

### ISSUE THREAD

**Issue by lennu** [terraform-providers/terraform-provider-aws#11826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.template v2.1.2

### Affected Resource(s)

* aws_rds_cluster_parameter_group
* aws_rds_cluster_instance

### Terraform Configuration Files

```hcl
resource "aws_rds_cluster" "debug" {
  cluster_identifier = "rds-cluster-debug"
  database_name      = "debug"
  master_username    = "username"
  master_password    = "password"
  engine             = "aurora-mysql"
  engine_version     = "5.7.12"


  vpc_security_group_ids = [
    aws_security_group.debug.id
  ]

  db_subnet_group_name = aws_db_subnet_group.debug.name
  skip_final_snapshot  = true
  apply_immediately    = true

  storage_encrypted = true
}

resource "aws_rds_cluster_parameter_group" "debug" {
  name        = "rds-cluster-parameter-group-debug"
  family      = "aurora-mysql5.7"
}

resource "aws_rds_cluster_instance" "debug" {
  identifier              = "rds-cluster-instance-debug"
  cluster_identifier      = aws_rds_cluster.debug.id
  instance_class          = "db.t2.small"
  apply_immediately       = true
  engine                  = "aurora-mysql"
  engine_version          = "5.7.12"
  db_parameter_group_name = "rds-cluster-parameter-group-debug"
}

resource "aws_db_subnet_group" "debug" {
  name       = "debug"
  subnet_ids = ["subnet-_", "subnet-_"]
}

resource "aws_security_group" "debug" {
  name   = "debug"
  vpc_id = "vpc-_"
}

```

### Debug Output

https://gist.github.com/lennu/2f6b99727ecf967bf5e34c8dab242ec4

### Expected Behavior

It should have created/updated aws_rds_cluster_instance by adding db_parameter_group_name and taking it into use.

### Actual Behavior

Terraform outputs error:

```
Error: error creating RDS DB Instance: DBParameterGroupNotFound: DBParameterGroup not found: rds-cluster-parameter-group-debug
	status code: 404, request id: _

  on main.tf line 41, in resource "aws_rds_cluster_instance" "debug":
  41: resource "aws_rds_cluster_instance" "debug" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by CyrilDevOps** [comment]
You have to associate the cluster_parameter_group to the aws_rds_cluster
with  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.debug.id

or create a simple parameter_group to associate it to your cluster_instance.

**Comment by lennu** [comment]
Thanks, this worked! The documentation wasn't quite clear on this but I guess it now makes sense.
