### ISSUE TITLE
aws_dms_replication_instance resource creation has too short of a timeout

### ISSUE THREAD

**Issue by ryan-dyer-sp** [terraform-providers/terraform-provider-aws#1182]
### Terraform Version
v0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_dms_replication_instance

### Terraform Configuration Files
```
resource "aws_dms_replication_instance" "default" {
  allocated_storage = 20
  apply_immediately = true
  replication_instance_class = "${var.repl_instance_size}"
  engine_version = "1.9.0"
  replication_instance_id = "${var.pod_name}-repl-cc"
  publicly_accessible = false
  multi_az = true
  replication_subnet_group_id = "default-${data.aws_vpc.selected.id}"
  vpc_security_group_ids = [ "${data.aws_security_group.db_sg.id}" ]
}
```

### Debug Output
```
aws_dms_replication_instance.default: Still creating... (3m0s elapsed)
Releasing state lock. This may take a few moments...
Error applying plan:

1 error(s) occurred:

* aws_dms_replication_instance.default: 1 error(s) occurred:

* aws_dms_replication_instance.default: unexpected state 'modifying', wanted target 'available'. last error: %!s(<nil>)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
[terragrunt] [/home/rdyer/repos/sp-terraform/providers/dev/cc_db_dms/us-east-1/alcatraz] 2017/07/18 20:30:53 Module /home/rdyer/repos/sp-terraform/providers/dev/cc_db_dms/us-east-1/alcatraz has finished with an error: exit status 1
[terragrunt] 2017/07/18 20:30:53 Encountered the following errors:
exit status 1
```
### Panic Output
-NA-

### Expected Behavior
The resource creation should not timeout after 3 mins.  A t2.large instance can take much longer to standup and become available.  I'd suggest at least a 15 minute timeout.  Multiple attempts at creating this resource has put the time to create right around the 10 mark; different instance sizes may take longer.

### Actual Behavior
terraform fails.  I can wait until the instance does become available and then rerun tf apply to continue the building up remaining infrastructure.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
-NA

### References
-NA

**Comment by ryan-dyer-sp** [comment]
Also of note is that the documentation says it supports the timeouts flag and default for create is 30m.  I have also tried to set timeouts for create and I still see terraform bail on creating this resource after 3m and not being in the available state.

**Comment by Ninir** [comment]
Hey @ryan-dyer-sp,

It seems related to a AWS missing status, that [has been fixed](https://github.com/terraform-providers/terraform-provider-aws/pull/1114).

Are you able to check using Terraform 0.10, and the v0.1.3 release for the AWS provider?

Thanks!

**Comment by ryan-dyer-sp** [comment]
If you can point me to a download location, I'd be happy to.

**Comment by radeksimko** [comment]
Here's where to get the mentioned RC version of Terraform:
https://releases.hashicorp.com/terraform/0.10.0-rc1/

We (intentionally) don't publish RCs and betas on the website as they don't have the same guarantees of stability. In other words once we reach `0.10.0` final it will be published at https://www.terraform.io/downloads.html as usual.

**Comment by stack72** [comment]
@radeksimko / @Ninir now that 0.10 is generally available - should this be closed?

**Comment by radeksimko** [comment]
That's right - thanks for the ping @stack72
