### ISSUE TITLE
resource aws_launch_configuration root_block_device: missing kms_key_id

### ISSUE THREAD

**Issue by dopsy** [terraform-providers/terraform-provider-aws#11855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* aws_launch_configuration

### Terraform Configuration Files

```resource "aws_launch_configuration" "test" {
  count                = "${terraform.workspace == "prod" || terraform.workspace == "dr" ? 1 : 0}" 
  name                 = local.cluster_name
  image_id             = data.aws_ami.centos.id
  instance_type        = var.instance_type
  key_name             = var.key_name
  security_groups      = aws_security_group.test_nodes.*.id
  iam_instance_profile = aws_iam_instance_profile.profile[count.index].id  
  user_data            = data.template_file.cloud-init-cluster.rendered

  root_block_device {
    volume_type           = "gp2"
    volume_size           = var.volume_size
    delete_on_termination = false
    encrypted             = true
    kms_key_id            = data.aws_kms_key.main.arn

```

### Expected Behavior

kms_key_Id accepted

### Actual Behavior

An argument named "kms_key_id" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

https://www.terraform.io/docs/providers/aws/r/launch_configuration.html has info that kms_key_id ir supported for root_block_device.  While checking https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_launch_configuration.go i see that it's not there.
```
"root_block_device": {
				Type:     schema.TypeList,
				Optional: true,
				Computed: true,
				MaxItems: 1,
				Elem: &schema.Resource{
					// "You can only modify the volume size, volume type, and Delete on
					// Termination flag on the block device mapping entry for the root
					// device volume." - bit.ly/ec2bdmap
					Schema: map[string]*schema.Schema{
						"delete_on_termination": {
							Type:     schema.TypeBool,
							Optional: true,
							Default:  true,
							ForceNew: true,
						},

						"encrypted": {
							Type:     schema.TypeBool,
							Optional: true,
							Computed: true,
							ForceNew: true,
						},

						"iops": {
							Type:     schema.TypeInt,
							Optional: true,
							Computed: true,
							ForceNew: true,
						},

						"volume_size": {
							Type:     schema.TypeInt,
							Optional: true,
							Computed: true,
							ForceNew: true,
						},

						"volume_type": {
							Type:     schema.TypeString,
							Optional: true,
							Computed: true,
							ForceNew: true,
						},
```

**Comment by dopsy** [comment]
Can i get any update please?

**Comment by DrFaust92** [comment]
Unfortunately there is no such setting for the auto scaling api. its not that terraform lacks this but the AWS API doesn't support it.
Maybe there can be another call to ebs api and change it, but thats really hacky.

**Comment by bflad** [comment]
Hi folks 👋 As @DrFaust92 mentions, the AutoScaling API with backs Launch Configurations does not support this argument ([CreateLaunchConfiguration](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CreateLaunchConfiguration.html) > [BlockDeviceMapping](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_BlockDeviceMapping.html) > [Ebs](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_Ebs.html)), therefore we cannot add it directly to the Terraform resource. Instead, please see other EC2 features like EBS Encryption By Default and Launch Templates, which can be used to accomplish setting a KMS CMK for EBS Volumes.
