### ISSUE TITLE
Fix and enable tfproviderlint S023 check: schema should not include Elem with incompatible Type

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#11867]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `Elem` in these cases in extraneous, has no effect, and should be removed. See also: https://github.com/bflad/tfproviderlint/blob/master/passes/S023/README.md

e.g.

```
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_instance.go:374:15: S023: schema should not include Elem with incompatible Type
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_docdb_cluster.go:163:15: S023: schema should not include Elem with incompatible Type
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_neptune_cluster.go:223:15: S023: schema should not include Elem with incompatible Type
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_rds_cluster.go:302:15: S023: schema should not include Elem with incompatible Type
```

### Definition of Done

- Fix S023 reports
- In `GNUmakefile`, add `-S023` to `tfproviderlint` command under lint target and have TravisCI testing pass

**Comment by megubyte** [comment]
I've left a draft pull request with my changes - I was trying to run the acceptance tests but they take a while so might want to defer off to some other computer at a later date if I want to contribute, I guess...
