### ISSUE TITLE
Fix and enable tfproviderlint S020 check: schema should not combine Computed only with ForceNew

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#11865]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using `ForceNew` with `Computed: true` only (no `Optional`/`Required`) is extraneous and not valid. See also: https://github.com/bflad/tfproviderlint/blob/master/passes/S020/README.md

The fix in all these is to remove the extraneous `ForceNew` declaration per attribute.

e.g.

```
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ami.go:171:28: S020: schema should not only enable Computed and enable ForceNew
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ami_copy.go:145:28: S020: schema should not only enable Computed and enable ForceNew
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_ami_from_instance.go:132:28: S020: schema should not only enable Computed and enable ForceNew
/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_inspector_assessment_template.go:29:11: S020: schema should not only enable Computed and enable ForceNew
```

### Definition of Done

- Fix S020 reports
- In `GNUmakefile`, add `-S020` to `tfproviderlint` command under lint target and have TravisCI testing pass

**Comment by breathingdust** [comment]
The fix for this has been merged and will release in version 2.57.0 of the Terraform AWS Provider, later this week.
