### ISSUE TITLE
Add support for IAM policies in EFS Filesystem

### ISSUE THREAD

**Issue by commarla** [terraform-providers/terraform-provider-aws#11881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Mid January, AWS [release IAM authentication and authorization for NFS Clients ](https://aws.amazon.com/blogs/aws/new-for-amazon-efs-iam-authorization-and-access-points/)

It's included in [SDK v1.28.1](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#Release-v1281-2020-01-13) 

### New or Affected Resource(s)

* aws_efs_file_system

### Potential Terraform Configuration

```hcl
resource "aws_efs_file_system" "foo" {
  creation_token = "my-product"

  tags = {
    Name = "MyProduct"
  }

    policy = <<POLICY
{
    "Version": "2012-10-17",
    "Id": "ExamplePolicy01",
    "Statement": [
        {
            "Sid": "ExampleSatement01",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": [
                "elasticfilesystem:ClientMount",
                "elasticfilesystem:ClientWrite"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "true"
                }
            }
        }
    ]
}
POLICY

}
```

### References

* https://aws.amazon.com/blogs/aws/new-for-amazon-efs-iam-authorization-and-access-points/
* https://docs.aws.amazon.com/efs/latest/ug/iam-access-control-nfs-efs.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/efs/#PutFileSystemPolicyInput

**Comment by anGie44** [comment]
This feature has been merged and will release with `v2.63.0` of the Terraform AWS Provider, expected in this week's release.
