### ISSUE TITLE
aws_eks_node_group fails to spin up if associated iam role has path != "/"

### ISSUE THREAD

**Issue by sdickhoven** [terraform-providers/terraform-provider-aws#11898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform version
Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.external v1.2.0
```

### Affected Resource(s)

* `aws_eks_node_group`

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "node_pool" {
  name = "bar"
  path = "/foo/"
  ...
}

resource "aws_eks_node_group" "default" {
  node_role_arn  = aws_iam_role.node_pool.arn
  ...
}
```

### Expected Behavior

Managed node group comes up.

### Actual Behavior

Managed node group creation times out because nodes cannot join the cluster.

The problem is that the nodes don't have a valid IAM role that allows them to perform the required operations. They are associated with the non-existent IAM role `foo` instead of `foo/bar` (see example above).

Changing the path for the IAM role from "/foo/" to "/" fixes the problem.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @sdickhoven 👋 Thank you for reporting this and sorry you are running into trouble here.

The `aws_eks_node_group` resource only passes through the given role:

https://github.com/terraform-providers/terraform-provider-aws/blob/3c84f53f15b4e4d4b9cc744478d37c97e9b9166e/aws/resource_aws_eks_node_group.go#L192

You may want to open a ticket with AWS Support, since this may be an issue with the API itself.

**Comment by sdickhoven** [comment]
hi @bflad

👍 will do. thanks for the quick feedback.

**Comment by sdickhoven** [comment]
just to follow up. here's what aws support said:

> This is a known feature request to us and as far as I can see from my end, the Service Team is aware of it.
> [...]
> At this moment, there is no workaround.

there's no eta for a fix.

since this is not a terraform provider issue i'll leave it up to you if you want to close this issue or keep it open until a fix is in place upstream.

tx

**Comment by bflad** [comment]
Hi @sdickhoven 👋  Just to followup, I believe there is now an [AWS Containers Roadmap issue](https://github.com/aws/containers-roadmap/issues/926) for this. We suggest you and others 👍  and subscribe there for further updates.
