### ISSUE TITLE
aws_route53_record: timeouts out creating record in a busy route53 zone

### ISSUE THREAD

**Issue by abhinavdahiya** [terraform-providers/terraform-provider-aws#11896]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

more detailed logs at https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-openshift-controller-manager-operator/129/pull-ci-openshift-cluster-openshift-controller-manager-operator-master-e2e-aws/536/artifacts/e2e-aws/installer/.openshift_install.log

The relevant error message

```
level=error msg="Error: [ERR]: Error building changeset: timeout while waiting for state to become 'accepted' (timeout: 5m0s)"
level=error
level=error msg="  on ../tmp/openshift-install-771650541/route53/base.tf line 33, in resource \"aws_route53_record\" \"api_external\":"
level=error msg="  33: resource \"aws_route53_record\" \"api_external\" {"
level=error
level=error
```

### Expected Behavior

When adding records to a Route53 zone that is quite busy i.e. see a lot of addition/removal of records, AWS errors with failure to admit the change set causing the provider to backoff for appropriate time.

### Actual Behavior

The provider has a hard coded 5 minutes backoff timeout, and a lot of the terraform apply fail for the creation of records. Allowing users to modify this timeout for their own scale would benefit or circumvent the failure.

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
The artificial, hardcoded five minute timeouts for creation and deletions in the `aws_route53_record` resource have been removed in preference of the default AWS Go SDK retrying logic. Thank you to @abhinavdahiya for the implementation. 👍
