### ISSUE TITLE
resource aws_acm_certificate broken since tag on create added?

### ISSUE THREAD

**Issue by Glen-Moonpig** [terraform-providers/terraform-provider-aws#11903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.20

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

```hcl
resource "aws_acm_certificate" "domain_certificate" {
  domain_name               = "*.test.com"
  subject_alternative_names = ["*.test.net"]
  validation_method         = "DNS"
  tags                      = {
    "environment" = var.environment_name,
    "name"        = var.tag_name,
    "owner"       = var.tag_owner,
    "team"        = var.tag_team
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

It should have created a new ACM certificate with tags applied

### Actual Behavior

I get a permissions error.
`Error: Error requesting certificate: AccessDeniedException: User: arn:aws:ts::1234567890:assumed-role/deployment/1293487623984761293 is not authorized to perform: acm:AddTagsToCertificate
        status code: 400, request id: cd486be3-5271-4001-acrf-3db209ae2be0`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The role does have the required permissions

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "acm:RequestCertificate",
                "acm:ListTagsForCertificate",
                "acm:ListCertificates",
                "acm:ImportCertificate"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "acm:UpdateCertificateOptions",
                "acm:ResendValidationEmail",
                "acm:RenewCertificate",
                "acm:RemoveTagsFromCertificate",
                "acm:ImportCertificate",
                "acm:GetCertificate",
                "acm:ExportCertificate",
                "acm:DescribeCertificate",
                "acm:AddTagsToCertificate"
            ],
            "Resource": "arn:aws:acm:*:1234567890:certificate/*"
        }
    ]
}
```

### References

* #0000

**Comment by Glen-Moonpig** [comment]
I think this bug was introduced in #11073

**Comment by DrFaust92** [comment]
@Glen-Moonpig, i think the user/role your deployment is running with is lacking the `acm:AddTagsToCertificate` permission

**Comment by Glen-Moonpig** [comment]
> @Glen-Moonpig, i think the user/role your deployment is running with is lacking the `acm:AddTagsToCertificate` permission

The policy attached to the role is shown above, it does have the "acm:AddTagsToCertificate" action and this worked fine before the change.

As a workaround I am setting the tags to an empty map `{}` and it is working fine.

**Comment by ewbankkit** [comment]
@Glen-Moonpig Do you have access to the CloudTrail logs for the failing API call? Maybe more information there.

**Comment by Glen-Moonpig** [comment]
I think this is a bug in AWS.

When you add tags to an already created certificate you need action "acm:AddTagsToCertificate", which can be restricted by ARN like "arn:aws:acm:*:1234567890:certificate/*".

But when you add tags while creating a certificate you need action "acm:AddTagsToCertificate", but the ARN must be "*".

**Comment by Glen-Moonpig** [comment]
AWS support claim that this is by design...

**Comment by ewbankkit** [comment]
Maybe because the certificate has no ARN until creation is complete?

**Comment by Glen-Moonpig** [comment]
Yes that is correct, it does have no ARN until created, but if you use the IAM policy builder in the AWS console, when you choose the AddTagsToCertificate action it says you can use a particular ARN with it, which is not strictly the case.
