### ISSUE TITLE
VPC Endpoint and VPC Endpoint Service tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11926]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> This release provides support for tagging when you create a VPC endpoint, or VPC endpoint service.

### New or Affected Resource(s)

* [`aws_vpc_endpoint`](https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html)
* [`aws_vpc_endpoint_service`](https://www.terraform.io/docs/providers/aws/r/vpc_endpoint_service.html)

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-vpc-endpoints-and-endpoint-services-now-support-tag-on-create/).

Requires [AWS SDK v1.28.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.11):

* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

Related:

* https://github.com/terraform-providers/terraform-provider-aws/pull/11730
* https://github.com/terraform-providers/terraform-provider-aws/pull/11931

**Comment by DrFaust92** [comment]
Addressed in #12290 & #12288

**Comment by bflad** [comment]
Thanks so much, @DrFaust92 👍
