### ISSUE TITLE
Change profile in provider doesn't change access rights

### ISSUE THREAD

**Issue by gdoumenc** [terraform-providers/terraform-provider-aws#11952]
Changing the profile in the provider doesn't force the reinitialization of terraform and produces an access error. I need to delete ```.terraform``` folder to solve the issue.

**Comment by pcantea** [comment]
Also running into this issue. I can provide logs if needed

**Comment by bflad** [comment]
Hi folks 👋  Thank you for reporting this and sorry you ran into trouble here. Unfortunately we will need all the information in the [bug report issue template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) so we can triage and potentially reproduce your issue to fix it. Please open a new bug report following the template and we can take a look. Please also note that there are some major authentication improvements and bug fixes that will be occurring in the next few weeks and released with version 3.0.0 of the Terraform AWS Provider.
