### ISSUE TITLE
AWS AppSync integration with AWS X-Ray

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#11969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now enable AWS X-Ray for your APIs in AWS AppSync, making it easier to trace and analyze user requests as they travel through the APIs to the backend data sources.

### New or Affected Resource(s)

* [`aws_appsync_graphql_api`](https://www.terraform.io/docs/providers/aws/r/appsync_graphql_api.html)

### Potential Terraform Configuration

```hcl
resource "aws_appsync_graphql_api" "example" {
  xray_enabled = true
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/aws-appsync-releases-integration-with-aws-x-ray-and-graphql-info-object-support/).

Requires [AWS SDK v1.28.12](https://github.com/aws/aws-sdk-go/releases/tag/v1.28.12):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.53.0 of the Terraform AWS Provider, later this week. Thanks to @nerixim for the implementation. 👍
