### ISSUE TITLE
Codebuild's new source_version property throwing "Error: Unsupported argument"

### ISSUE THREAD

**Issue by slaughtr** [terraform-providers/terraform-provider-aws#11966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20
### Affected Resource(s)

* aws_codebuild_project
Specifically the `source` block, and the newly added (v 2.48.0) `source_version` property within that.

### Terraform Configuration Files

```hcl
resource "aws_codebuild_project" "default" {
...omitted

  source {
    type                = "GITHUB"
    location            = "https://github.com/${var.codebuild_source_repo_owner}/${var.name}.git"
    git_clone_depth     = 0
    insecure_ssl        = false
    report_build_status = true
    source_version      = var.codebuild_source_branch # this line 

    auth {
      type     = "OAUTH"
      resource = var.github_token
    }
  }

...omitted
}
```

### Debug Output

https://gist.github.com/slaughtr/0ece939b24885f972fcfbe2d302f2893

### Expected Behavior

Per #9831 the `source_version` property in the `source` config should be valid.

### Actual Behavior

`Unsupported argument` error.

### Steps to Reproduce

1. Ensure you're using version 2.48.0, then create an `aws_codebuild_project` resource and supply a `source_version` property to the `source` config. 
2. Attempt to `terraform apply` or `terraform plan`.

### Important Factoids

I'm using `terragrunt`, though I don't believe that would contribute to the issue.

### References

* #9831
* https://github.com/terraform-providers/terraform-provider-aws/blob/v2.48.0/CHANGELOG.md

**Comment by ewbankkit** [comment]
@slaughtr Sorry for the confusion here.
In fact `source_version` is a top-level argument for `aws_codebuild_project` resource, not nested in the `source` block:

```hcl
resource "aws_codebuild_project" "example" {
  source {
  }

  source_version = "master"
}
```

The example in the [documentation](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html#example-usage) is incorrect and should be corrected.

**Comment by slaughtr** [comment]
I don't know why I didn't think to try that 🤦‍♂  It totally works, finally my codebuild deployments are doing what they're supposed to do!
