### ISSUE TITLE
resource aws_kms_grant doesn't support import

### ISSUE THREAD

**Issue by rampaldheeraj** [terraform-providers/terraform-provider-aws#11976]
Terraform Version
v0.12.17
provider.aws v2.48.0

Affected Resource(s)
aws_kms_grant

Terraform Configuration Files
Not relevant
Debug Output
Error: resource aws_kms_grant doesn't support import

Expected Behavior
import succeeds without error

Actual Behavior
Error as above

Steps to Reproduce
try to import aws_kms_grant

**Comment by bflad** [comment]
Support for `aws_kms_grant` resource import has been merged and will release with version 2.56.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
