### ISSUE TITLE
Unable to use Dynamo Global tables with Version 2019.11.21

### ISSUE THREAD

**Issue by kyeotic** [terraform-providers/terraform-provider-aws#11982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.18

### Affected Resource(s)

* aws_dynamodb_global_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "data" {
  // ...
}


resource "aws_dynamodb_global_table" "data" {
  name = local.table_name

  depends_on = [
    aws_dynamodb_table.data
  ]

  provider = aws.us

  replica {
    region_name = "ap-southeast-1"
  }

  replica {
    region_name = "eu-west-1"
  }
}
```

### Debug Output

```
Error: TableNotFoundException: Table not found: Table: '/../' not found in region: 'eu-west-1'.
```

### Expected Behavior

Table is created by adding a global table region

### Actual Behavior

Error: table not found

### Steps to Reproduce

Apply above configuration

1. `terraform apply`

### Important Factoids

AWS released a new version of [Dynamo Global Tables](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables.tutorial.html) back in november that use a very different creation strategy.

**old version** you created empty table in each region, then created a global table to tie them together.

**new version** you create a table in a region, then **add regions** which creates new tables in the target region.

Terraform does not handle this correctly, it is apparently unaware of the new version's expected behavior.

### References

* https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables.tutorial.html

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/11096

**Comment by kyeotic** [comment]
Damn, missed that while searching. This is definitely a dupe
