### ISSUE TITLE
Adding ParallelizationFactor, MaximumRecordAgeInSeconds, BisectBatchOnFunctionError, MaximumRetryAttempts, DestinationConfig

### ISSUE THREAD

**Issue by rubemz** [terraform-providers/terraform-provider-aws#11999]
Asking to reopen https://github.com/terraform-providers/terraform-provider-aws/pull/11070 based on https://github.com/terraform-providers/terraform-provider-aws/pull/11070#issuecomment-583423281

I'm also needing to configure via Terraform the `MaximumRetryAttempts` for a Lambda -> Kinesis integration

**Comment by kostas-theo** [comment]
This is already implemented here: https://github.com/terraform-providers/terraform-provider-aws/pull/11100

**Comment by bflad** [comment]
This functionality was released late last week with version 2.51.0 of the Terraform AWS Provider. 👍
