### ISSUE TITLE
MediaConnect not available in release

### ISSUE THREAD

**Issue by adamgilman** [terraform-providers/terraform-provider-aws#11990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some work has previously been done on MediaConnect support in terraform but, I'm unsure of what the next steps are to get the already developed functionality into a release. 

#7940 + #7217 + #7431

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Sorry #7217 was prematurely closed for adding a MediaConnect Flow resource, reopening that. Outputs/Entitlements work can be tracked in #7940.

I just provided an initial review of #7431 which should get the ball rolling here again, but closing this to consolidate efforts and discussions into the earlier issues.
