### ISSUE TITLE
resource aws_kinesis_stream must always be replaced

### ISSUE THREAD

**Issue by kamercer** [terraform-providers/terraform-provider-aws#12003]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform: 2.20
provider.aws: 2.48

### Affected Resource(s)

* aws_kinesis_Stream

### Terraform Configuration Files

```hcl
resource "aws_kinesis_stream" "test_stream" {
  name = "test_stream"
  shard_count = 1
  encryption_type = "KMS"
  kms_key_id =  aws_kms_key.key.arn
}
```

### Debug Output

https://gist.github.com/kamercer/a0f812e28a390f70c8b8ac1bd3d164b7

### Expected Behavior
The kms key should have been replaced with the new one.

### Actual Behavior
Terraform plans to update the stream in-place during the plan phase.  During the apply phase, it completes the modifications after about 10 seconds but the old kms key is still in place.

### Steps to Reproduce
The kinesis stream continued to use the old kms key.

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

### Important Factoids

I also attempted to use aws_kms_key.key.key_id instead of aws_kms_key.key.arn but that did not do anything.

### References

* #0000

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. Thanks to @theophilechevalier for the implementation. 👍
