### ISSUE TITLE
[feature] support route53 multivalue records

### ISSUE THREAD

**Issue by udangel-r7** [terraform-providers/terraform-provider-aws#1205]
### Affected Resource(s)
- aws_route53_record

route53 recently introduced multivalue records - https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-route-53-announces-support-for-multivalue-answers-in-response-to-dns-queries/ which are currently not supported by terraform. 

http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets.html

**Comment by Josh-West-Bose** [comment]
+1

**Comment by lalinsky** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/1686
