### ISSUE TITLE
r/aws_spot_fleet_request: Support tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#12078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EC2 Spot Fleet request can now be tagged.
These tags apply to the spot fleet request resource and are separate from the tags that can be specified in the `launch_specification` configuration block and which apply to the EC2 instances in the fleet. 

### New or Affected Resource(s)

* [`aws_spot_fleet_request`](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html)

### Potential Terraform Configuration

```hcl
resource "aws_spot_fleet_request" "example" {
  tags = {
    Usage = "dev"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-ec2-now-supports-tagging-ec2-spot-fleet-requests/).
[API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html).

Requires [AWS SDK v1.29.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.0):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/11934

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.57.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
