### ISSUE TITLE
r/aws_cloud9_environment_ec2: Support tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#12077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Cloud9 now supports the ability to tag Cloud9 development environments.

### New or Affected Resource(s)

* [`aws_cloud9_environment_ec2`](https://www.terraform.io/docs/providers/aws/r/cloud9_environment_ec2.html)

### Potential Terraform Configuration

```hcl
resource "aws_cloud9_environment_ec2" "example" {
  tags = {
    Usage = "dev"
  }
}
```

### References

[User guide](https://docs.aws.amazon.com/cloud9/latest/user-guide/tags.html).

Requires [AWS SDK v1.29.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.4):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

**Comment by bflad** [comment]
Support for tagging functionality in the `aws_cloud9_environment_ec2` resource has been merged and will release with version 2.53.0 of the Terraform AWS Provider, later this week.
