### ISSUE TITLE
Fix and enable tfproviderlint R007 and R008 checks: Deprecated d.Partial() and d.SetPartial()

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#12083]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of Terraform Plugin SDK v1.7.0, `(github.com/hashicorp/terraform-plugin-sdk/helper/schema.ResourceData).Partial()` and `(github.com/hashicorp/terraform-plugin-sdk/helper/schema.ResourceData).SetPartial()` have been deprecated with no replacement.

tfproviderlint check references:

- https://github.com/bflad/tfproviderlint/blob/master/passes/R007/README.md
- https://github.com/bflad/tfproviderlint/blob/master/passes/R008/README.md

The following files have their usage, which should be removed:

- [x] `aws/resource_aws_ami.go`
- [x] `aws/resource_aws_ami_copy.go`
- [x] `aws/resource_aws_ami_from_instance.go`
- [x] `aws/resource_aws_api_gateway_stage.go`
- [x] `aws/resource_aws_autoscaling_group.go`
- [x] `aws/resource_aws_codestarnotifications_notification_rule.go`
- [x] `aws/resource_aws_db_cluster_snapshot.go`
- [x] `aws/resource_aws_db_event_subscription.go`
- [x] `aws/resource_aws_db_instance.go`
- [x] `aws/resource_aws_db_option_group.go`
- [x] `aws/resource_aws_db_parameter_group.go`
- [x] `aws/resource_aws_db_security_group.go`
- [x] `aws/resource_aws_db_snapshot.go`
- [x] `aws/resource_aws_db_subnet_group.go`
- [x] `aws/resource_aws_default_network_acl.go`
- [x] `aws/resource_aws_directory_service_directory.go`
- [x] `aws/resource_aws_docdb_cluster.go`
- [x] `aws/resource_aws_docdb_cluster_instance.go`
- [x] `aws/resource_aws_docdb_cluster_parameter_group.go`
- [x] `aws/resource_aws_docdb_subnet_group.go`
- [x] `aws/resource_aws_ec2_client_vpn_endpoint.go`
- [x] `aws/resource_aws_elasticache_parameter_group.go`
- [x] `aws/resource_aws_elb.go`
- [x] `aws/resource_aws_emr_cluster.go`
- [x] `aws/resource_aws_globalaccelerator_accelerator.go`
- [x] `aws/resource_aws_iam_instance_profile.go`
- [x] `aws/resource_aws_instance.go`
- [x] `aws/resource_aws_internet_gateway.go`
- [x] `aws/resource_aws_lambda_function.go`
- [x] `aws/resource_aws_lb_listener_rule.go`
- [x] `aws/resource_aws_licensemanager_license_configuration.go`
- [x] `aws/resource_aws_neptune_cluster.go`
- [x] `aws/resource_aws_neptune_cluster_instance.go`
- [x] `aws/resource_aws_neptune_cluster_parameter_group.go`
- [x] `aws/resource_aws_neptune_event_subscription.go`
- [x] `aws/resource_aws_neptune_parameter_group.go`
- [x] `aws/resource_aws_neptune_subnet_group.go`
- [x] `aws/resource_aws_network_acl.go`
- [x] `aws/resource_aws_network_interface.go`
- [x] `aws/resource_aws_opsworks_rds_db_instance.go`
- [x] `aws/resource_aws_proxy_protocol_policy.go`
- [x] `aws/resource_aws_qldb_ledger.go`
- [x] `aws/resource_aws_rds_cluster.go`
- [x] `aws/resource_aws_rds_cluster_instance.go`
- [ ] `aws/resource_aws_rds_cluster_parameter_group.go`
- [x] `aws/resource_aws_redshift_cluster.go`
- [x] `aws/resource_aws_redshift_event_subscription.go`
- [x] `aws/resource_aws_redshift_parameter_group.go`
- [x] `aws/resource_aws_redshift_snapshot_copy_grant.go`
- [x] `aws/resource_aws_redshift_snapshot_schedule.go`
- [x] `aws/resource_aws_redshift_subnet_group.go`
- [x] `aws/resource_aws_route53_resolver_endpoint.go`
- [x] `aws/resource_aws_route53_resolver_rule.go`
- [x] `aws/resource_aws_route53_zone.go`
- [x] `aws/resource_aws_route_table.go`
- [x] `aws/resource_aws_sagemaker_endpoint.go`
- [x] `aws/resource_aws_sagemaker_model.go`
- [x] `aws/resource_aws_sagemaker_notebook_instance.go`
- [x] `aws/resource_aws_security_group.go`
- [x] `aws/resource_aws_spot_fleet_request.go`
- [x] `aws/resource_aws_spot_instance_request.go`
- [x] `aws/resource_aws_subnet.go`
- [x] `aws/resource_aws_vpc.go`
- [x] `aws/resource_aws_vpc_endpoint_service.go`
- [x] `aws/resource_aws_vpc_peering_connection.go`
- [x] `aws/resource_aws_vpn_connection.go`
- [x] `aws/resource_aws_workspaces_directory.go`

### Definition of Done

- [x] The `-R007` and `-R008` flags are added to the tfproviderlint/awsproviderlint command in `GNUmakefile` and CI passes

**Comment by ewbankkit** [comment]
`d.Partial` and `d.SetPartial` for the `aws_workspaces_directory` resource are removed in https://github.com/terraform-providers/terraform-provider-aws/pull/11645.

**Comment by ewbankkit** [comment]
@bflad `aws/resource_aws_iam_instance_profile` and `aws/resource_aws_sagemaker_*` are done, leaving just the 2 outstanding linked PRs.
