### ISSUE TITLE
AWS Lambda support for Ruby 2.7

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#12101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Lambda now supports Ruby 2.7.

### New or Affected Resource(s)

* [`aws_lambda_function`](https://www.terraform.io/docs/providers/aws/r/lambda_function.html)
* [`aws_lambda_layer_version`](https://www.terraform.io/docs/providers/aws/r/lambda_layer_version.html) plus corresponding data source

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "example" {
  runtime = "ruby2.7"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/aws-lambda-supports-ruby-2-7/).
[Blog post](https://aws.amazon.com/blogs/compute/aws-lambda-now-supports-ruby-2-7/).

Requires [AWS SDK v1,29.6](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.6):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11893

**Comment by bflad** [comment]
Support for the `runtime` value of `ruby2.7` has been merged and will release with version 2.51.0 of the Terraform AWS Provider, end of this week. Thanks to @jhole89 for the implementation. 👍
