### ISSUE TITLE
Trying to add skip_destroy="true" to a vol attachment

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#1211]
Terraform 0.9.8

Forgot to add skip_destroy="true" to an aws_volume_attachment - add it then plan:

```
~ aws_volume_attachment.foo
    skip_destroy: "" => "true"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Then apply:

```
Error applying plan:

1 error(s) occurred:

* aws_volume_attachment.foo: 1 error(s) occurred:

* aws_volume_attachment.foo: doesn't support update
```

It would be much better if you could add skip_destroy especially as it is only a terraform flag and not a resource flag anyway. (also if something doesnt support update, the plan shouldnt plan a change)

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
