### ISSUE TITLE
DocumentDB Cluster Instance Resource doesn't support `ca_cert_identifier`

### ISSUE THREAD

**Issue by Mattsi-Jansky** [terraform-providers/terraform-provider-aws#12154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Core version: 11.14
Providers:

```
11:44:12  * provider.aws: version = "~> 2.50"
11:44:12  * provider.external: version = "~> 1.2"
11:44:12  * provider.null: version = "~> 2.1"
11:44:12  * provider.template: version = "~> 2.1"
```

### Affected Resource(s)

* aws_docdb_cluster_instance

### Terraform Configuration Files

```hcl
variable "docdb_cluster_username" {
  description = "The DocDB Cluster Username."
  type        = "string"
}

variable "docdb_cluster_password" {
  description = "The DocDB Cluster Password."
  type        = "string"
}

variable "ca_cert" {
  description = "A certificate in the form of rds-ca-YYYY where YYYY is a year"
} 

resource "aws_docdb_cluster" "docdb_cluster" {
  cluster_identifier      = "our-cluster-identifier"
  engine                  = "docdb"
  master_username         = "${var.docdb_cluster_username}"
  master_password         = "${var.docdb_cluster_password}"
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
  vpc_security_group_ids  = ["<our security group>"]
  db_subnet_group_name    = "<Our subnet group>"

  skip_final_snapshot       = "false"
  final_snapshot_identifier = "${var.env}-${lookup(var.release, "component")}"
}

resource "aws_docdb_cluster_instance" "cluster_instances" {
  count              = 3
  identifier         = "our-identifier"
  cluster_identifier = "${aws_docdb_cluster.docdb_cluster.id}"
  instance_class     = "db.r5.large"
  ca_cert_identifier = "${var.ca_cert}"
}
```

### Debug Output

Unfortunately getting debug info will be difficult due to our setup (everything running on a build server I don't personally have access to); if you think it'd be useful let me know and I'll find a way.

### Expected Behavior

* I set the `ca_cert_identifier` property in a `aws_docdb_cluster_instance`
* It should change the `ca_cert_identifier` property to the supplied value (from `rds-ca-2015` to `rds-ca-2019`)

### Actual Behavior

The logs indicate that it tries to set the property on each instance, like so: 

```
[2020-02-25T11:44:59.157Z]  ~ aws_docdb_cluster_instance.cluster_instances[0] 
[2020-02-25T11:44:59.157Z] ca_cert_identifier: "rds-ca-2015" => "rds-ca-2019" 
[2020-02-25T11:44:59.157Z] 
[2020-02-25T11:44:59.157Z]  ~ aws_docdb_cluster_instance.cluster_instances[1] 
[2020-02-25T11:44:59.157Z] ca_cert_identifier: "rds-ca-2015" => "rds-ca-2019" 
[2020-02-25T11:44:59.157Z] 
[2020-02-25T11:44:59.157Z]  ~ aws_docdb_cluster_instance.cluster_instances[2] 
[2020-02-25T11:44:59.157Z] ca_cert_identifier: "rds-ca-2015" => "rds-ca-2019" 
```

However, in the UI I can see that the property hasn't changed. Also, each time the Terraform runs it will try to set the property again, outputting the same log as above. 

It seems to be failing silently. The apply ultimately succeeds with `Apply complete!` and no obvious errors.

### Steps to Reproduce

* Setup an AWS DocDB cluster and try to change the certificate to a non-default value

### Important Factoids

The resource definition for `aws_docdb_cluster_instance` (`/aws/resource_aws_docdb_cluster_instance.go`) seems to be a close copy of the RDS resource definition (`/aws/resource_aws_rds_cluster_instance.go`). When it comes to `ca_cert_identifier` it is exactly the same except for one missing block of code: https://github.com/terraform-providers/terraform-provider-aws/blob/e7cd260316a08a7e071e65f8b4a326d8f452a88f/aws/resource_aws_rds_cluster_instance.go#L339-L343

Perhaps that piece of code should be in the resource definition for `aws_docdb_cluster_instance`?

**Comment by drexler** [comment]
@Mattsi-Jansky are you _applying_ the changes to the cluster immediately. If not, do you see the changes being reflected in the pending maintenance window in the UI?  I had to do the same with RDS and after a couple of tests, we applied it immediately and thereafter reset the `apply_immediately` property to `false`.

**Comment by bflad** [comment]
Hi @Mattsi-Jansky, the recommendation above by @drexler is on point here -- in order for updates like this one to apply, the `apply_immediately = true` must be given in the resource configuration. Without that, updates will occur during the next maintenance window due to how the API behaves. If you feel the documentation around this can be improved, please let us know. 👍
