### ISSUE TITLE
aws_alb subnets shows as one subnet with comma-separated ids

### ISSUE THREAD

**Issue by pscadiz** [terraform-providers/terraform-provider-aws#1216]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_alb

### Terraform Configuration Files
Input variable subnet/security_groups is a comma-separated list of ids coming from a data source. Setting default to see example
```hcl
variable "security_groups" {
   default = "sg-12345678"
}
variable "subnets" {
   default = "subnet-12345678,subnet-87654321"
}

resource "aws_alb" "alb" {
  name = "alb-test"
  internal = "false"
  security_groups = ["${var.security_groups}"]
  subnets = ["${var.subnets}"]
}
```

### Expected Behavior
Plan should see two subnets with different IDs

### Actual Behavior
```
+ module.alb.aws_alb.alb
    arn:                        "<computed>"
    arn_suffix:                 "<computed>"
    dns_name:                   "<computed>"
    enable_deletion_protection: "false"
    idle_timeout:               "60"
    internal:                   "false"
    ip_address_type:            "<computed>"
    name:                       "alb-test"
    security_groups.#:          "1"
    security_groups.4279578247: "sg-12345678"
    subnets.#:                  "1"
    subnets.2530630612:         "subnet-65d0d813,subnet-e159bd86"
    vpc_id:                     "<computed>"
    zone_id:                    "<computed>"
```
Terraform apply then fails with the error
```
aws_alb.alb: Error creating Application Load Balancer: ValidationError: At least two subnets in two different Availability Zones must be specified
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by grubernaut** [comment]
Hi @pscadiz, thanks for the issue! 

If you change the `variable` definition to include a `type` for the `subnets` variable does the error still occur? 
ie: 
```
variable "subnets" {
  default = ["subnet1", "subnet2"]
  type = "list"
}
```

**Comment by pscadiz** [comment]
Hi @grubernaut ,

Unfortunately no, placing the value (default or not) inside [] still recognizes the subnets as one but comma-separated.

Resolved it by using split though:
``hcl
variable "security_groups" {
   default = "sg-12345678"
}
variable "subnets" {
   default = "subnet-12345678,subnet-87654321"
}

resource "aws_alb" "alb" {
  name = "alb-test"
  internal = "false"
  security_groups = ["${split(",",var.security_groups)}"]
  subnets = ["${split(",",var.subnets)}"]
}
```

If this is an accepted solution, then ticket can be closed.

**Comment by grubernaut** [comment]
Hi @pscadiz, that's correct, but if you explicitly set the `type` of the variable does that work? 
Basically, Terraform is seeing the variable as a single string. If the parent module sets these values as a single string, separated by comma's, then yes, using `split()` would work best here. 
If you supply an actual list variable for `subnets` and explicitly specify the variable to be a list, that should work as well.

**Comment by grubernaut** [comment]
Going to close for now, as the original issue is solved. Happy to answer any further questions though. Thanks!

**Comment by catsby** [comment]
Hey @pscadiz we're glad you found a solution here. I'm curious if the `[]` in your usage was throwing off the suggestion of using `type = "list"`, for example:

```hcl
variable "subnets" {
  default = ["subnet1", "subnet2"]
  type = "list"
}

resource "aws_alb" "alb" {
  [...]
  subnets = "${var.subnets}"
}
```

Let us know if that works!
