### ISSUE TITLE
Resources (and data) for MediaLive

### ISSUE THREAD

**Issue by iancward** [terraform-providers/terraform-provider-aws#12166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_medialive_channel
* aws_medialive_input
* aws_medialive_input_security_group
* aws_medialive_multiplex
* aws_medialive_multiplex_program

Data resources for these would also be useful.

The first three would be required to manage a MediaLive pipeline; the Multiplex might not be as much of a priority. 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by iancward** [comment]
Looks like this might be a dupe of #4936.

**Comment by ewbankkit** [comment]
@iancward Yes, you are correct. I'll close this one.
Thanks.
