### ISSUE TITLE
Test Reports with AWS CodeBuild

### ISSUE THREAD

**Issue by rubytobi** [terraform-providers/terraform-provider-aws#12178]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS extended the Codebuild Service with new functionality: Test Reports
The Report Groups can be populated form within a build by exporting JUnit or Cucumber test reports. Also, these reports can be persisted to S3 if specified on the Report Group.

_"AWS CodeBuild announced the launch of a new feature in CodeBuild called Reports. This feature allows you to view the reports generated by functional or integration tests. The reports can be in the JUnit XML or Cucumber JSON format. You can view metrics such as Pass Rate %, Test Run Duration, and number of Passed versus Failed/Error test cases in one location. Builders can use any testing frameworks as long as the reports are generated in the supported formats.
You can see the test reports created by CodeBuild in the respective Report Group, where they are stored for 30 days. For longer retention, you can store the reports in an Amazon S3 bucket. Each test report is further broken down by individual test cases."_

Also, boto3 already supports the new functionality.

### New or Affected Resource(s)
* aws_codebuild_reportgroup

### Potential Terraform Configuration
```hcl
resource aws_codebuild_reportgroup sample {
 name = "my-report-group"
 type = "TEST"
 exportConfig = {
  exportConfigType: "S3" | "NO_EXPORT"
  s3Destination: {
   bucket: "my-bucket"
   path: "my-custom-prefix"
   packaging: "ZIP" | "NONE"
   encryptionKey: "my-kms-key"
   encryptionDisabled: True | False
   }
  }
}
```

### References
https://aws.amazon.com/blogs/devops/test-reports-with-aws-codebuild/
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/codebuild.html

**Comment by bflad** [comment]
The new `aws_codebuild_report_group` resource has been merged and will release with version 3.5.0 of the Terraform AWS Provider, later next week. Thanks to @DrFaust92 for the implementation. 👍
