### ISSUE TITLE
ElasticBeanstalk configuration template - Tomcat solution stack 2.6.1 results in error 

### ISSUE THREAD

**Issue by completenovice** [terraform-providers/terraform-provider-aws#1219]
We have a data source for the latest version of Tomcat 7 Java 7, but it seems that on a Terraform Plan fails if an existing EB Template resource uses version 2.6.1, which was recently replaced by 2.6.2.

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_elastic_beanstalk_configuration_template
- aws_elastic_beanstalk_solution_stack

### Terraform Configuration Files
```hcl
data "aws_elastic_beanstalk_solution_stack" "tomcat7_java7" {
	most_recent   = true
	name_regex    = "^64bit Amazon Linux (.*) Tomcat 7 Java 7$"
}

resource "aws_elastic_beanstalk_configuration_template" "eb_template" {
	name                = "eb_template"
	application         = "${aws_elastic_beanstalk_application.templates.name}"
	solution_stack_name = "${data.aws_elastic_beanstalk_solution_stack.tomcat7_java7.name}"
}
```

### Expected Behavior
Update the resource from Tomcat 7 with Java 7 running on 64bit Amazon Linux/2.6.1 to Tomcat 7 with Java 7 running on 64bit Amazon Linux/2.6.2

### Actual Behavior
Terraform Plan fails with the following error:
`Error refreshing state: 1 error(s) occurred:

* aws_elastic_beanstalk_configuration_template.eb_template: 1 error(s) occurred:

* aws_elastic_beanstalk_configuration_template.eb_template: aws_elastic_beanstalk_configuration_template.eb_template: InvalidParameterValue: No Platform named 'arn:aws:elasticbeanstalk:eu-west-1::platform/Tomcat 7 with Java 7 running on 64bit Amazon Linux/2.6.1' found.
	status code: 400, request id: retracted`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have an existing resource running Tomcat 7 with Java 7 running on 64bit Amazon Linux/2.6.1 and use the data module to retrieve the latest version.
2. Run terraform plan/apply

**Comment by stack72** [comment]
Hi @completenovice 

I believe this has been fixed by https://github.com/terraform-providers/terraform-provider-aws/pull/1222

//cc @grubernaut 

P.
