### ISSUE TITLE
aws_autoscaling_group's target_group_arns is not updated if argument target_group_arns is removed

### ISSUE THREAD

**Issue by nitrocode** [terraform-providers/terraform-provider-aws#12201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.21
+ provider.aws v2.50.0
```

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "this" {
  availability_zones        = ["us-west-2b", "us-west-2c"]
  name                      = "asg"
  max_size                  = 20
  min_size                  = 1
  health_check_grace_period = 300
  health_check_type         = "EC2"
  desired_capacity          = 10
  force_delete              = true
  launch_configuration      = aws_launch_configuration.this.name
  load_balancers            = [aws_elb.this.name, aws_elb.that.name]

  # target_group_arns = []
  target_group_arns = [
    aws_lb_target_group.this.arn,
    aws_lb_target_group.that.arn
  ]

  ...
}
```

### Expected Behavior

Remove the target group arns if `target_group_arns` is no longer supplied

### Actual Behavior

Target group arns are not removed from the autoscaling group

### Steps to Reproduce

1. Remove or comment out the argument `target_group_arns`
2. `terraform apply`
3. delete target groups
4. scale up asg and it will fail
    * > Launching a new EC2 instance. Status Reason: One or more target groups not found. Validating load balancer configuration failed.
5. Comment in argument but set the argument to an empty list
6. `terraform apply`
7. asg will now scale up successfully

### References

* #0000

**Comment by carlosjgp** [comment]
Relates to https://github.com/terraform-providers/terraform-provider-aws/issues/3265 ?

**Comment by nitrocode** [comment]
Yes and it appears it was fixed recently. Thank you.
