### ISSUE TITLE
r/aws_globalaccelerator_accelerator: Support tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#12202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Global Accelerator supports tagging for accelerators.

### New or Affected Resource(s)

* [`aws_globalaccelerator_accelerator`](https://www.terraform.io/docs/providers/aws/r/globalaccelerator_accelerator.html)

### Potential Terraform Configuration

```hcl
resource "aws_globalaccelerator_accelerator" "example" {
  tags = {
    Usage = "dev"
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/02/aws-global-accelerator-now-supports-bring-your-own-ip-addresses/).
[Developer guide](https://docs.aws.amazon.com/global-accelerator/latest/dg/tagging-in-global-accelerator.html).

Requires [AWS SDK v1.29.12](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.12):
* https://github.com/terraform-providers/terraform-provider-aws/pull/12128

**Comment by bflad** [comment]
Support for tagging with the `aws_globalaccelerator_accelerator` resource has been merged and will release with version 2.53.0 of the Terraform AWS Provider, later this week. Thanks to @teraken0509 for the implementation. 👍
