### ISSUE TITLE
aws_route53_query_log failes on valid input

### ISSUE THREAD

**Issue by ofirshtrull** [terraform-providers/terraform-provider-aws#12229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
+ Terraform v0.12.21
+ provider.aws v2.46.0
+ provider.local v1.4.0
+ provider.tls v2.1.1

### Affected Resource(s)

* aws_route53_query_log

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_log_resource_policy" "route53-query-logging-policy" {
  policy_document = data.aws_iam_policy_document.route53-query-logging-policy.json
  policy_name     = "route53-query-logging-policy"
}

resource "aws_cloudwatch_log_group" "main" {
  name              = format("/aws/route53/%s", local.route53_zone)
  retention_in_days = 60
}

resource "aws_route53_query_log" "main" {
  depends_on = [aws_cloudwatch_log_resource_policy.route53-query-logging-policy]

  cloudwatch_log_group_arn = aws_cloudwatch_log_group.main.arn
  zone_id                  = local.route53_id
}
```

### Expected Behavior

create the resorce 

### Actual Behavior

i run the command (Copy paste from the documentation) and I get that I am using a bad arn
from aws documentation and from my result from aws_cloudwatch_log_group.main.arn i get a valid result such as
`arn:aws:logs:eu-west-1:123456789:log-group:/aws/eks/appname/application:*`
 
and i get the next result

module.route53_zone.aws_route53_query_log.main: Creating...

Error: Error creating Route53 query logging configuration: InvalidInput: The ARN for the CloudWatch Logs log group is invalid.
	status code: 400, request id: 1bad6bb7-46fe-4765-8e58-54b88189a7cf

  on ../../modules/route53/zone/main.tf line 43, in resource "aws_route53_query_log" "main":
  43: resource "aws_route53_query_log" "main" {
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tomelliff** [comment]
That doesn't look like a valid log group ARN to me. Instead it should be `arn:aws:logs:eu-west-1:123456789:log-group:/aws/eks/appname/application` eg minus the `:*` which signifies all the log streams in the log group.

If you drop the `:*` does it work?

**Comment by ofirshtrull** [comment]
Nope tried that
In the documentation it also shows that the ending :* is a valid syntax

**Comment by tomelliff** [comment]
Can you link to that documentation?

**Comment by tomelliff** [comment]
I've just read the [resource documentation](https://www.terraform.io/docs/providers/aws/r/route53_query_log.html) and it has this notice at the top:

> NOTE: There are restrictions on the configuration of query logging. Notably, the CloudWatch log group must be in the us-east-1 region, a permissive CloudWatch log resource policy must be in place, and the Route53 hosted zone must be public. See Configuring Logging for DNS Queries for additional details.

You need to create your log group in `us-east-1` not `eu-west-1` like your output shows.

**Comment by ofirshtrull** [comment]
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/query-logs.html
10.b I think is relevent

**Comment by ofirshtrull** [comment]
aws_cloudwatch_log_group doesn't allow me to create a resource in a different region 
(no region option)

**Comment by tomelliff** [comment]
You need to specify a different provider like the resource docs show:

```hcl
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

resource "aws_cloudwatch_log_group" "aws_route53_example_com" {
  provider = "aws.us-east-1"

  name              = "/aws/route53/${aws_route53_zone.example_com.name}"
  retention_in_days = 30
}
```

**Comment by ofirshtrull** [comment]
Thanks it worked
