### ISSUE TITLE
EMR Custom AMI support

### ISSUE THREAD

**Issue by clinty** [terraform-providers/terraform-provider-aws#1223]
Amazon has finally made the Bring-Your-Own-AMI feature of EMR generally available.

https://github.com/aws/aws-sdk-net/commit/9aa0d95e32fde37a75ae9780b5fc184d12c4f7a9

Please support this API enhancement.

Probably relevant to #1178

**Comment by qsorix** [comment]
+1

**Comment by ktel1218** [comment]
+1

**Comment by jitsen** [comment]
+1

**Comment by vireshjivane** [comment]
+1

**Comment by gordonbondon** [comment]
We need this functionality at my dayjob so I'm going to take a stab at it.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
