### ISSUE TITLE
r/aws_flow_log: Support tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#12245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon VPC Flow Logs adds support for tags and tagging on resource creation.

### New or Affected Resource(s)

* [`aws_flow_log`](https://www.terraform.io/docs/providers/aws/r/flow_log.html)

### Potential Terraform Configuration

```hcl
resource "aws_flow_log" "example" {
  tags = {
    Usage = "dev"
  }
}
```

### References

[User guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-resources).

Requires [AWS SDK v1.29.16](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.16):
* https://github.com/terraform-providers/terraform-provider-aws/pull/12214

**Comment by bflad** [comment]
Support for tagging `aws_flow_log` resources has been merged and will release with version 2.53.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
