### ISSUE TITLE
Support AWS Storage GW SMB File Share Admin User List

### ISSUE THREAD

**Issue by Andrew-Kulpa** [terraform-providers/terraform-provider-aws#12255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Storage Gateway SMB File Share adds support for specifying admin user list.

### New or Affected Resource(s)

* aws_storagegateway_smb_file_share

### Potential Terraform Configuration

```hcl
resource "aws_storagegateway_smb_file_share" "example" {
  #...
  admin_user_list = ["@smb_admins"]
}
```

### Attempted Solutions
*  #12196
    * This Pull Request implements this feature. Honestly, its my first PR here so maybe I'm missing a step in the PR process. Still, I noticed Hashibot never labeled it for `needs-triage` or anything for that matter.

### References

* [User Guide](https://docs.aws.amazon.com/storagegateway/latest/userguide/smb-acl.html)
* [Storage Gateway](https://docs.aws.amazon.com/sdk-for-go/api/service/storagegateway/)

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.8.0 of the Terraform AWS Provider, later this week. Thanks to @Andrew-Kulpa for the implementation. 👍
