### ISSUE TITLE
resource aws_network_interface - add ipv6 support

### ISSUE THREAD

**Issue by justin-choponis-sp** [terraform-providers/terraform-provider-aws#12260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems you can't use `ipv6_addresses` or `ipv6_address_count` with aws_network_interface. Requesting addition of support here. Issue is: if you have an EC2 instance with multiple ENIs, you can't manage ipv6 with it. You can only seem to mange ipv6 with and ENI when it is the primary ENI via aws_instance using arguments `ipv6_addresses` or `ipv6_address_count`. I believe we should have the same two arguments available for aws_network_interface. 

I believe `vendor\github.com\aws\aws-sdk-go\service\ec2\api.go` has the necessary methods to call from `aws\resource_aws_network_interface.go`.

This is regarding provider version 2.51.0.

### New or Affected Resource(s)

* aws_network_interface (affected)

### Potential Terraform Configuration

Example - I'd like to be able to something like this and assign both ipv6 and private ipv4 addresses to an ENI. Today, ipv6_addresses is not a valid argument for this resource (nor is ipv6_address_count).
```hcl
resource "aws_network_interface" "fw1_eni" {
  description       = "interface 1 for firewall 1"
  subnet_id         = var.subnet_ids[0]
  ipv6_addresses = [var.ips_v6[0]]
  private_ips       = [var.ips_v4[0]]
  security_groups   = [aws_security_group.fw_sg_1.id]
  source_dest_check = false
}
```

### References

* My request here looks similar to this one that has been open since 2017: https://github.com/terraform-providers/terraform-provider-aws/issues/1707.

**Comment by bflad** [comment]
Support for new `ipv6_addresses` and `ipv6_address_count` arguments in the `aws_network_interface` resource has been merged and will release with version 3.12.0 of the Terraform AWS Provider, next week. Thanks to @DrFaust92 for the implementation. 👍
