### ISSUE TITLE
AWS Regions discovery by opt-in status

### ISSUE THREAD

**Issue by szczad** [terraform-providers/terraform-provider-aws#12270]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon dynamically expands their cloud into new regions. Users have ability to enable/disable some of them on demand. But there is no possibility to list all of them at once using one request/resource. 

### New or Affected Resource(s)

* `data.aws_resources`

### Potential Terraform Configuration

```hcl
data "aws_regions" "all_regions_opt_in_status" {
	all_regions = true

        filter {
              name = "opt-in-status"
	      values = ["opt-in-not-required"]
        }
}
```

### References

* [AWS API Documentation - DescribeRegions](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html)

**Comment by bflad** [comment]
Support for a new `aws_regions` data source has been merged and will release with version 2.58.0 of the Terraform AWS Provider, later this week. Thanks to @szczad for the implementation. 👍
