### ISSUE TITLE
S3 remote state doesn't work

### ISSUE THREAD

**Issue by marcosmachado81** [terraform-providers/terraform-provider-aws#12319]
I'm trying setup terraform to use remote state in S3 bucket but doesn't work.

I can create, manipulate, delete, and more using local state but when I setup a remote backend using S3 I get this message:

```
$terraform init

Initializing the backend...

Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider

```

I'm using 2 files, credentials and terraform.tf

credentias:
```
[default]
aws_access_key_id = <key>
aws_secret_access_key = <key>
```
terraform.tf:
```
terraform {
  backend "s3" {
    bucket = "remotestateforterraform"
    key = "terraform-state/terraform.tfstate"
    region ="eu-west-3"
    profile    = "default"
  }
}
provider "aws" {
  region = var.region
  shared_credentials_file = "./credentials"
  profile                 = "default"
}

```
terraform version:
```
$ terraform --version
Terraform v0.12.23
+ provider.aws v2.51.0

```
When I use local state I can connect to the AWS and create EC2 instances, buckets, and more.

The log output:
```
2020/03/09 15:30:54 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value <removed**>
2020/03/09 15:30:54 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/03/09 15:30:54 [DEBUG] New state was assigned lineage "<removed**>"
2020/03/09 15:30:54 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
2020/03/09 15:30:54 [INFO] Setting AWS metadata API timeout to 100ms
2020/03/09 15:30:55 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2020/03/09 15:30:55 [INFO] Attempting to use session-derived credentials

Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider


```
**I don't know whether these data are sensibles, but I think these aren't important to understand the problem

**Comment by djcrabhat** [comment]
So it looks like you need to set the value of your `shared_credentials_file` https://www.terraform.io/docs/backends/types/s3.html#shared_credentials_file on your terraform backend block, not the provider block.  Think of the s3 backend as running before your providers and the rest of the fun stuff terraform runs.  The backend is independently accessing AWS, not through the "aws" provider.

**Comment by marcosmachado81** [comment]
> So it looks like you need to set the value of your `shared_credentials_file` https://www.terraform.io/docs/backends/types/s3.html#shared_credentials_file on your terraform backend block, not the provider block. Think of the s3 backend as running before your providers and the rest of the fun stuff terraform runs. The backend is independently accessing AWS, not through the "aws" provider.

Yep! I tried this.. but documentation says "optional" and in this case is necessary.

thanks
