### ISSUE TITLE
r/aws_nat_gateway: Tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#12326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon VPC NAT Gateway now supports tag-on-create.

### New or Affected Resource(s)

* [`aws_nat_gateway`](https://www.terraform.io/docs/providers/aws/r/nat_gateway.html)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-vpc-nat-gateway-now-supports-tag-on-create/).

Requires [AWS SDK v1.29.20](https://github.com/aws/aws-sdk-go/releases/tag/v1.29.20):
* https://github.com/terraform-providers/terraform-provider-aws/pull/12294

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
