### ISSUE TITLE
S3 bucket deletion takes a lot of time for buckets with large number of objects

### ISSUE THREAD

**Issue by nithinvenugopal** [terraform-providers/terraform-provider-aws#12323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.21 and AWS terraform provider v2.27.0

### Affected Resource(s)

aws_s3_bucket

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "s3_bucket" {
  provider            = "aws.client"
  bucket              = "${var.s3_bucket_name}"
  acl                 = "private"
  force_destroy       = "true"
  tags                = "${var.s3_bucket_tags}"
  acceleration_status = "Enabled"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
aws_s3_bucket.s3_bucket: Destruction complete after 37m4s

### Expected Behavior
Terraform v0.11.11 and aws terraform provider v2.27.0 used to delete S3 bucket with around 5000 objects within 1 minute

### Actual Behavior
Terraform v0.12  and aws terraform provider v2.49 takes around 30 minutes to delete a bucket having around 5000 objects

### Steps to Reproduce

1. Create a S3 bucket
2. Upload large number of objects around 5000 to this S3 bucket (with object size around 200kb for example)
3. Delete the bucket

**Comment by ewbankkit** [comment]
@nithinvenugopal Thanks for reporting this.
The same issue has already been raised in https://github.com/terraform-providers/terraform-provider-aws/issues/12146. Could you please close this one and consolidate the conversation over there?

**Comment by nithinvenugopal** [comment]
closing as it is a duplicate.
