### ISSUE TITLE
Add tags to aws_globalaccelerator_accelerator resource

### ISSUE THREAD

**Issue by nunofernandes** [terraform-providers/terraform-provider-aws#12320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I need to add tags to the aws_globalaccelerator_accelerator resource.

### New or Affected Resource(s)

* aws_globalaccelerator_accelerator

### Potential Terraform Configuration

```hcl

resource "aws_globalaccelerator_accelerator" "this" {
 ...
  tags = {
    "Terraform" = "true"
  }
}
```

**Comment by ewbankkit** [comment]
Duplicates:
* https://github.com/terraform-providers/terraform-provider-aws/issues/12202

@nunofernandes This has been implemented via https://github.com/terraform-providers/terraform-provider-aws/pull/12309 and will release with version 2.53.0 of the Terraform AWS Provider, later this week.
