### ISSUE TITLE
An argument named "zone_awareness_config" is not expected here

### ISSUE THREAD

**Issue by adoux** [terraform-providers/terraform-provider-aws#12365]
Hello,

I searched a bit but couldn't find any open issue regarding the problem I'm facing, that is Terraform fails to apply a simple plan to create an Elasticsearch domain (_aws_elasticsearch_domain_) because of the _zone_awareness_config_ block.
Terraform tells me the block is not expected here although it is at the right place (inside a _cluster_config_ block).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.23
+ provider.aws v2.52.0
+ provider.kubernetes v1.11.1
+ provider.random v2.2.1

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```hcl
resource "aws_elasticsearch_domain" "ess-domain" {
  domain_name           = "${var.eks_cluster_name}-ess"
  elasticsearch_version = var.ess_version

  cluster_config {
    instance_type            = var.ess_data_instance_type
    instance_count           = length(var.az_list)
    dedicated_master_enabled = true
    dedicated_master_count   = length(var.az_list)
    dedicated_master_type    = var.ess_master_instance_type
    zone_awareness_enabled   = true

    zone_awareness_config = {
      availability_zone_count = length(var.az_list)
    }
  }

  vpc_options {
    subnet_ids         = aws_subnet.sn-ess[*].id
    security_group_ids = [
      aws_security_group.sg-ess.id
    ]
  }

  ebs_options {
    ebs_enabled = true
    volume_type = "gp2"
    volume_size = var.ess_node_size
  }

  tags = {  
    "Name" = "${var.eks_cluster_name}-ess-domain"
  }
}
```

### Debug Output

https://gist.github.com/adoux/56abf81196d80f1e6d6476dfb346ddee

### Expected Behavior

As the zone_awareness_config block is located in the right block (cluster_config), it should simply work.

### Actual Behavior

Terraform fails to apply the plan:

```
Error: Unsupported argument

  on modules/ess/ess.tf line 13, in resource "aws_elasticsearch_domain" "ess-domain":
  13:     zone_awareness_config = {

An argument named "zone_awareness_config" is not expected here. Did you mean
to define a block of type "zone_awareness_config"?
```

### Steps to Reproduce

1. `terraform apply`

Thanks in advance for your help!

**Comment by loivis** [comment]
try like this?
```
zone_awareness_config {
      availability_zone_count = length(var.az_list)
    }
```

**Comment by antonydandrea** [comment]
Having the same issue without the =. I read another issue where the solution was to update the aws provider, but mine is the most up to date (2.66)

  zone_awareness_config {
    availability_zone_count = 2
  }

Blocks of type "zone_awareness_config" are not expected here.

**Comment by bflad** [comment]
Hi @adoux 👋  The solution provided above by @loivis should be what you need here. If you need additional help please open a new issue. Thanks!
