### ISSUE TITLE
AWS Route53 of other account

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-providers/terraform-provider-aws#12362]
Hi Team, Currently we associate a Route 53 private hosted zone with a VPC on a different AWS account using the below link, can this be done in terraform completely.

https://aws.amazon.com/premiumsupport/knowledge-center/private-hosted-zone-different-account/

**Comment by arnvid** [comment]
@dhineshbabuelango  - there is an ongoing discussion on the following link for this aswell:
https://github.com/terraform-providers/terraform-provider-aws/issues/384

**Comment by bflad** [comment]
Support for Route 53 cross-account VPC Associations via a new `aws_route53_vpc_association_authorization` resource and updated `aws_route53_zone_association` resource handling has been merged and will release with version 3.1.0 of the Terraform AWS Provider, likely later today. Thanks to @goakley and @RyanJarv for implementation. 👍
