### ISSUE TITLE
terraform should be able to import opsworks application

### ISSUE THREAD

**Issue by schollii** [terraform-providers/terraform-provider-aws#12376]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Command `terraform import aws_opsworks_application.NAME AWS_APP_ID` should work. I could implement. 

### New or Affected Resource(s)

* aws_opsworks_application

**Comment by bflad** [comment]
Support for `aws_opsworks_application` resource import has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. 👍
