### ISSUE TITLE
Grabbing the EIP from a NAT instance, not created with TF.

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-aws#1238]
So.. any one know if this is possible. I don't see a data source in TF for nat instances, so maybe this is more of a feature request? Other than a manual import? I'm not sure I can do a manual import.

**Comment by radeksimko** [comment]
Hi @shadycuz 
just to better understand your request here - are we talking about NAT _instance_ (from logical AWS perspective just a regular EC2 instance you built yourself) or NAT _gateway_ ("NAT as a service" managed by AWS)?

We already have an EIP data source:
https://www.terraform.io/docs/providers/aws/d/eip.html
As long as you know the EIP ID you can pull the IP (or the other way around).

If you wish to lookup an EIP associated with NAT gateway (via NAT gateway ID) then we don't have a data source for that (yet): https://www.terraform.io/docs/providers/aws/r/nat_gateway.html#id

**Comment by shadycuz** [comment]
@radeksimko Yes I should have been clear. I'm speaking of a NAT Gateway. I have 3 NAT gateways created from kops. I need to whitelist those ip's when I create a elasticsearch cluster in terraform. 

I'm not familiar with GO but I think I can use another similar data source (aws_vpn_gateway) and PR a working aws_nat_gateway data source. What do you think?

**Comment by radeksimko** [comment]
> I think I can use another similar data source (aws_vpn_gateway) and PR a working aws_nat_gateway data source. What do you think?

That sounds like a good plan.

**Comment by ewbankkit** [comment]
See also https://github.com/terraform-providers/terraform-provider-aws/issues/849 for a plan to handle tagging of the implicitly created EIP.

**Comment by bflad** [comment]
The `aws_nat_gateway` data source (https://www.terraform.io/docs/providers/aws/d/nat_gateway.html) was released in [v1.2.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#120-october-31-2017). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
