### ISSUE TITLE
resource/aws_lambda_function: Add validation to handler length

### ISSUE THREAD

**Issue by moraneva** [terraform-providers/terraform-provider-aws#12410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_lambda_function

### References

https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html

```
Handler
The name of the method within your code that Lambda calls to execute your function. The format includes the file name. It can also include namespaces and other qualifiers, depending on the runtime. For more information, see Programming Model.

Type: String

Length Constraints: Maximum length of 128.
```

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. 👍
