### ISSUE TITLE
New staticcheck v2020.1.3 SA5011 Failures (possible nil pointer dereference) in golangci-lint v1.24.0

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#12413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`golangci-lint` v1.24.0 includes an update to `staticcheck`. This update is more sensitive to `nil` pointer dereferences:

```
aws/resource_aws_emr_cluster.go:1428:28: SA5011: possible nil pointer dereference (staticcheck)
  instanceCount := len(resp.Instances)
                            ^
aws/resource_aws_autoscaling_notification.go:84:26: SA5011: possible nil pointer dereference (staticcheck)
    for _, n := range resp.NotificationConfigurations {
                           ^
```

Spot checking these, they are true positives. The code should be updated and this check should remain enabled going forward.

### Affected Resource(s)

- aws_autoscaling_notification
- aws_emr_cluster

### Definition of Done

- Code updates pass staticcheck v2020.1.3 or golangci-lint v1.24.0 (`staticcheck` linter only, there are other failures to be separately addressed). Since this codebase does not include these dependency updates yet due to the failures, the tools will need to be manually installed/updated in your development environment following the tool documentation.
- Existing acceptance testing passes for `TestAccAWSASGNotification_` and `TestAccAWSEMRCluster_` patterns. See also the [Running Acceptance Testing section in the Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#running-an-acceptance-test).

### References

- https://staticcheck.io/docs/checks#SA5011
- https://github.com/terraform-providers/terraform-provider-aws/pull/12397

**Comment by bcatubig** [comment]
I'd like to pick this up. Will submit a PR.
