### ISSUE TITLE
Add validate_request_headers to aws_api_gateway_request_validator

### ISSUE THREAD

**Issue by kevingunn-wk** [terraform-providers/terraform-provider-aws#12438]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_api_gateway_request_validator` is missing the option to also validate headers. Currently only body and parameters are supported.

### New or Affected Resource(s)

* aws_api_gateway_request_validator

### Potential Terraform Configuration

```hcl
resource "aws_api_gateway_request_validator" "validator" {
  rest_api_id  = var.api_gateway_id
  name          = "gateway-validator"

  validate_request_body            = true
  validate_request_parameters = true
  validate_request_headers       = true
}

```

### References

* https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-validation-set-up.html#api-gateway-request-validation-setup-in-console

**Comment by DrFaust92** [comment]
Hey @kevingunn-wk, i couldnt find the relevant API flag for this and then looked into the documentation you linked.

```
Validate body: This is the body-only validator.

Validate query string parameters and headers: This is the parameters-only validator.

Validate body, query string parameters, and headers: This validator is for both body and parameters validation.
```

It would seem that `validate_request_parameters` already covers this functionality. (based on the provided docs)

**Comment by kevingunn-wk** [comment]
Yeah, I looked at the API after I opened this and realized that was the case. When I first deployed this out, it didn't work for me. I have since found out that my API deployment doesn't seem to be working properly as the stage is not getting deployed.

So, this can be closed out. Sorry for the false-issue.
