### ISSUE TITLE
aws_acm_certificate appears to be waiting for DNS validation to complete when subject_alternative_names list is bigger than default service limit

### ISSUE THREAD

**Issue by raolivei** [terraform-providers/terraform-provider-aws#12445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.23
+ provider.aws v2.52.0
```

### Affected Resource(s)

* [acm_certificate](https://www.terraform.io/docs/providers/aws/r/acm_certificate.html)

### Terraform Configuration Files

Assuming that `var.list` has more than 50 items:

```hcl
variable "domains" {
  type = list(string)
}

resource "aws_acm_certificate" "vanity_domains_cert" {
  domain_name               = sort(var.domains)[0]
  subject_alternative_names = concat(var.domains, formatlist("*.%s", concat(var.domains,[])))
  validation_method         = "DNS"
```

### Expected Behavior

The certificate should be created in a state of pending validation, and Terraform should return success.

### Actual Behavior

The certificate is created in a state of pending validation, but Terraform appears to wait for validation of the SAN to succeed (which it won't, DNS records haven't been retrieved and added yet), and then errors as follows:

```
aws_acm_certificate.main: Creating...
  arn:                         "" => "<computed>"
  domain_name:                 "" => "example.com"
  domain_validation_options.#: "" => "<computed>"
  subject_alternative_names.#: "" => "1"
  subject_alternative_names.0: "" => "one.example.com"
  validation_emails.#:         "" => "<computed>"
  validation_method:           "" => "DNS"
aws_acm_certificate.main: Still creating... (10s elapsed)
aws_acm_certificate.main: Still creating... (20s elapsed)
aws_acm_certificate.main: Still creating... (30s elapsed)
aws_acm_certificate.main: Still creating... (40s elapsed)
aws_acm_certificate.main: Still creating... (50s elapsed)
aws_acm_certificate.main: Still creating... (1m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* aws_acm_certificate.main: 1 error(s) occurred:

* aws_acm_certificate.main: No validation options need to retry: {
  DomainName: "one.example.com",
  ValidationMethod: "DNS",
  ValidationStatus: "PENDING_VALIDATION"
}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
Note: when there are less than 30 domain values included, the certificate is created without errors, as expected, so this issue appears to be related to the default ACM certificate service limit in the AWS account.

My account has permission to create up to 100 CNAMEs for every ACM certificate. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The concatenation on `subject_alternative_names` value is a way to add the domain + sub-domain entries (example.com + *.example.com) to every value specified in the domains variable list.

**Comment by bflad** [comment]
Hi folks 👋 Apologies if this error is confusing in any way. This happens during the asynchronous process where a certificate with DNS validation is requested and the ACM service has yet to return back the DNS validation records for the domains. We have just merged an update to the `aws_acm_certificate` resource that will now allow it to wait for up to 5 minutes (instead of just 1 minute) for the ACM service to generate the DNS validation records for certificates with higher amounts of Subject Alternative Names or if this asynchronous ACM DNS validation value creation is otherwise being slow. This will release in version 2.64.0 of the Terraform AWS Provider, later this week. Thanks to @gilbsgilbs for the implementation. 👍
