### ISSUE TITLE
Update DOCS for security_groups in aws_instance

### ISSUE THREAD

**Issue by leonkatz** [terraform-providers/terraform-provider-aws#1249]
Updated Documentation for aws_instance for aws provider for security_groups should specify that it takes id's, this can seem like it should be names and is confusing.

**Comment by radeksimko** [comment]
Hi @leonkatz 
sorry for any confusion. There's difference between using some EC2 resources in default VPC (or EC2 Classic) and inside VPC. This is one of those examples.

Can you provide an example of a config where you were successfully able to use SG IDs in `security_groups` + tell us whether that is in a (non)default VPC or EC2 Classic or just standard VPC?

This may help:
http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-account-attributes.html (specifically `supported-platforms`).

Once you have specified [`subnet_id`](https://www.terraform.io/docs/providers/aws/r/instance.html#subnet_id) it means the instance is VPC-based, so `security_groups` field becomes irrelevant at that point, while `vpc_security_group_ids` becomes relevant.

**Comment by koooge** [comment]
When I create EC2 instance with `security_groups = ${sg's id}` by ` terraform apply`, it issucceed.
But and then, when I type `terraform plan`, it shows "(new resource required)"
This seems requireing ${sg's name}.

Is this intended?

rel? #255

**Comment by n3ph** [comment]
Can't reproduce..

```console

```

21:57 n3ph@mag-xps ~/tmp ✘  terraform apply
data.aws_vpc.default: Refreshing state...
data.aws_ami.amzn2: Refreshing state...
data.aws_security_group.default: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_instance.web
      id:                           <computed>
      ami:                          "ami-09a2e326dc3bfcc2a"
      associate_public_ip_address:  <computed>
      availability_zone:            <computed>
      ebs_block_device.#:           <computed>
      ephemeral_block_device.#:     <computed>
      get_password_data:            "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           <computed>
      ipv6_addresses.#:             <computed>
      key_name:                     <computed>
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      password_data:                <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      root_block_device.#:          <computed>
      security_groups.#:            "1"
      security_groups.3814588639:   "default"
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tenancy:                      <computed>
      volume_tags.%:                <computed>
      vpc_security_group_ids.#:     <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_instance.web: Creating...
  ami:                          "" => "ami-09a2e326dc3bfcc2a"
  associate_public_ip_address:  "" => "<computed>"
  availability_zone:            "" => "<computed>"
  ebs_block_device.#:           "" => "<computed>"
  ephemeral_block_device.#:     "" => "<computed>"
  get_password_data:            "" => "false"
  instance_state:               "" => "<computed>"
  instance_type:                "" => "t2.micro"
  ipv6_address_count:           "" => "<computed>"
  ipv6_addresses.#:             "" => "<computed>"
  key_name:                     "" => "<computed>"
  network_interface.#:          "" => "<computed>"
  network_interface_id:         "" => "<computed>"
  password_data:                "" => "<computed>"
  placement_group:              "" => "<computed>"
  primary_network_interface_id: "" => "<computed>"
  private_dns:                  "" => "<computed>"
  private_ip:                   "" => "<computed>"
  public_dns:                   "" => "<computed>"
  public_ip:                    "" => "<computed>"
  root_block_device.#:          "" => "<computed>"
  security_groups.#:            "" => "1"
  security_groups.3814588639:   "" => "default"
  source_dest_check:            "" => "true"
  subnet_id:                    "" => "<computed>"
  tenancy:                      "" => "<computed>"
  volume_tags.%:                "" => "<computed>"
  vpc_security_group_ids.#:     "" => "<computed>"
aws_instance.web: Still creating... (10s elapsed)
aws_instance.web: Still creating... (20s elapsed)
aws_instance.web: Creation complete after 22s (ID: i-01064abdad81200b8)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
```console
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_vpc.default: Refreshing state...
data.aws_ami.amzn2: Refreshing state...
data.aws_security_group.default: Refreshing state...
aws_instance.web: Refreshing state... (ID: i-01064abdad81200b8)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

**Comment by ryndaniels** [comment]
Closing this as it is a duplicate of #255.
