### ISSUE TITLE
aws_ecs_service should now support updating placement strategy and constraints in-place for existing ECS Services

### ISSUE THREAD

**Issue by gnjack** [terraform-providers/terraform-provider-aws#12490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Amazon have just announced that ECS supports updating Placement Strategy and Constraints for existing ECS Services.](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-ecs-supports-in-preview-updating-placement-strategy-and-constraints-for-existing-ecs-services/)

> Previously, a change to the task placement parameters required the user to recreate the service. Now, customers can use the UpdateService API to change the placement logic for an existing service by updating the service with the desired placement strategy and constraints. ECS will enforce these changes at the time of the next service deployment.

### New or Affected Resource(s)

* aws_ecs_service
  * ordered_placement_strategy
  * placement_constraints

Both `aws_ecs_service.ordered_placement_strategy` and `aws_ecs_service.placement_constraints` are currently marked as `ForceNew`. They should be changed to allow update in place. This will require adding logic to `resourceAwsEcsServiceUpdate` https://github.com/terraform-providers/terraform-provider-aws/blob/a2373c1b81023e2b3c329905bb0f409c6d63c540/aws/resource_aws_ecs_service.go#L886

### References

* https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-ecs-supports-in-preview-updating-placement-strategy-and-constraints-for-existing-ecs-services/

**Comment by bflad** [comment]
Support for in-place updates of these, along with adding a `force_new_deployment` argument, have been merged and will release with version 2.63.0 of the Terraform AWS Provider later this week. 👍
