### ISSUE TITLE
aws_glue_catalog_table.ser_de_info.name is documented as optional, but fails if not specified

### ISSUE THREAD

**Issue by lbenedetto** [terraform-providers/terraform-provider-aws#12519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.24
+ provider.aws v2.54.0

### Affected Resource(s)

* aws_glue_catalog_table.ser_de_info.name

### Issue
The name field of ser_de_info is documented as being optional, but if it is not specified, and error is given when attempting to apply

```
Error: Error updating Glue Catalog Table: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, UpdateTableInput.TableInput.StorageDescriptor.SerdeInfo.Name.
```

Looks like it's trying to set name to `""` instead of `null` like it says it's going to do in the diff

```
~ ser_de_info {
    - name                  = "testName" -> null
      parameters            = {
          "serialization.format" = "1"
      }
      serialization_library = "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
}
```

### References
ser_de_info
name - (Optional) Name of the SerDe.
https://www.terraform.io/docs/providers/aws/r/glue_catalog_table.html#ser_de_info

**Comment by drexler** [comment]
Yeah, there are some missing validation checks for this. Looking at the [Go SDK -AWS Glue Reference](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#StorageDescriptor), both the `Name` and `SerializationLibrary` properties require at least one character.
