### ISSUE TITLE
HDD support for aws_fsx_windows_file_system

### ISSUE THREAD

**Issue by affinitywaterltd** [terraform-providers/terraform-provider-aws#12553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

In March 2020, AWS announced support for a HDD storage option. Can the `aws_fsx_windows_file_system` be updated to support this?
This feature is already available through CloudFormation which could be used as influence.

### New or Affected Resource(s)

* aws_fsx_windows_file_system

### Potential Terraform Configuration

Addition of a `storage_type` parameter with options of `hdd` or `ssd`

```hcl
resource "aws_fsx_windows_file_system" "example" {
  active_directory_id = "${aws_directory_service_directory.example.id}"
  kms_key_id          = "${aws_kms_key.example.arn}"
  storage_type        = "hdd"
  storage_capacity    = 300
  subnet_ids          = ["${aws_subnet.example.id}"]
  throughput_capacity = 1024
}
```

### References

* https://aws.amazon.com/blogs/aws/new-low-cost-hdd-storage-option-for-amazon-fsx-for-windows-file-server/
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html

**Comment by bflad** [comment]
Requires [AWS Go SDK v1.29.33](https://github.com/aws/aws-sdk-go/pull/3236) / https://github.com/terraform-providers/terraform-provider-aws/pull/12414 or later before implementation.

**Comment by JuanOI** [comment]
@bflad any idea when this might become available. This is currently blocking a customer. Thanks!
