### ISSUE TITLE
FR: Multiple improvements to aws_ssm_patch_baseline

### ISSUE THREAD

**Issue by sfrode** [terraform-providers/terraform-provider-aws#1257]
The aws_ssm_patch_baseline seems to be needing a few updates:

1) aws_ssm_patch_baseline is missing support for the "OperatingSystem" parameter, leading to a situation where the API defaults to Windows as the only supported OS.

2) Lack of support for the "ApprovedPatchesComplianceLevel" parameter

3) There is no support for updating resources, leading to a new patch baseline with every single change.

**Comment by stack72** [comment]
Hi @sfrode 

PR in progress now :)

Paul

**Comment by sfrode** [comment]
@stack72 - thanks a lot! This was awsomely fast!

I'll follow up the lack of support for Updates in another ticket as it seems to be a common theme amongst the SSM resources.

Thanks a lot!

**Comment by stack72** [comment]
@sfrode no worries at all - as long as you can agree that we can drop 3 for the need to close this PR then i am happy to push forward :)

I think the separate task of adding updates to all the required resources is the right thing

**Comment by sfrode** [comment]
Agreed

**Comment by stack72** [comment]
Awesome!

**Comment by stack72** [comment]
Ping @sfrode to open the issue for SSM resource updates ;)
