### ISSUE TITLE
Support for Ultrawarm with aws_elasticsearch_domain

### ISSUE THREAD

**Issue by amulyas** [terraform-providers/terraform-provider-aws#12606]
Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Description
AWS ES Team Launched UW https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ultrawarm.html
These option to be added to https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html 
    "WarmEnabled": true,
    "WarmCount": 6,
    "WarmType": "ultrawarm1.medium.elasticsearch"

**Comment by ace03uec** [comment]
This feature is now available in GA. https://aws.amazon.com/about-aws/whats-new/2020/05/aws-announces-amazon-elasticsearch-service-ultrawarm-general-availability/

**Comment by sc250024** [comment]
Yes please!
