### ISSUE TITLE
aws_storagegateway_smb_file_share does not populate the path attribute

### ISSUE THREAD

**Issue by artur-sak13** [terraform-providers/terraform-provider-aws#12622]
## Description
`aws_storagegateway_smb_file_share` is [documented](https://www.terraform.io/docs/providers/aws/r/storagegateway_smb_file_share.html#attribute-reference) as exposing the path attribute needed to mount the share:

> * path - File share path used by the NFS client to identify the mount point.

This is the same issue as #12527 but for the smb file share.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.49.0
```

### Affected Resource(s)

* aws_storagegateway_smb_file_share

### Expected Behavior

The path attribute is available for other resources to use.

### Actual Behavior

```
This object has no argument, nested block, or exported attribute named "path".
```

### References

* #12527

**Comment by bflad** [comment]
The `path` attribute for the `aws_storagegateway_smb_file_share` resource has been merged and will release with version 2.60.0 of the Terraform AWS Provider, later this week. Thanks to @artur-sak13 for the implementation. 👍
