### ISSUE TITLE
Cannot import aws_appautoscaling_policy for DynamoDB secondary indexes

### ISSUE THREAD

**Issue by jamesye-canva** [terraform-providers/terraform-provider-aws#12648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.9
+ provider.aws v2.56.0
```

### Affected Resource(s)

* aws_appautoscaling_policy

### Expected Behavior

Import succeeds.

### Actual Behavior

Import fails with error:
```
Error: Failed to read scaling policy: Error retrieving scaling policies: ValidationException: 1 validation error detected: Value 'index' at 'scalableDimension' failed to satisfy constraint: Member must satisfy enum value set: [removed for brevity]
```

### Steps to Reproduce

1. `terraform import <RESOURCE_ADDRESS> dynamodb/table/<TABLE_NAME>/index/<INDEX_NANE>/dynamodb:index:ReadCapacityUnits/DynamoDBReadCapacityUtilization:table/<TABLE_NAME>/index/<INDEX_NAME>`

### Important Factoids

`validateAppautoscalingPolicyImportInput()` in `/aws/resource_aws_appautoscaling_policy.go` parses the given resource ID, of the format `<serviceNamespace>/<resourceId>/<scalableDimension>/<policyName>`.

This assumes that for the `dynamodb` namespace, the resource ID is two parts separated by `/`, e.g. `table/<TABLE_NAME>`. This is not the case for secondary indexes, which are four parts, `table/<TABLE_NAME/index/<INDEX_NAME>`.

The parsed values are:
- `resourceId: table/<TABLE_NAME>`
- `scalableDimension: index`
- `policyName: <INDEX_NAME>/dynamodb:index:ReadCapacityUnits/DynamoDBReadCapacityUtilization:table/<TABLE_NAME>/index/<INDEX_NAME>`

They should be:
- `resoruceId: table/<TABLE_NAME>/index/<INDEX_NAME>`
- `scalableDimension: dynamodb:index:ReadCapacityUnits`
- `policyName: DynamoDBReadCapacityUtilization:table/<TABLE_NAME>/index/<INDEX_NAME>`

### References

* <https://github.com/terraform-providers/terraform-provider-aws/blob/02afaa62e2ab9b136af361b5d827e1112a8dd141/aws/resource_aws_appautoscaling_policy.go#L442-L446>
* #8306 (previously import did not work for DynamoDB tables)

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.57.0 of the Terraform AWS Provider, later this week. Thanks to @camhux for the implementation. 👍
