### ISSUE TITLE
resource aws_inspector_assessment_template doesn't support import

### ISSUE THREAD

**Issue by cdchris12** [terraform-providers/terraform-provider-aws#12644]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.44.0
```

### Affected Resource(s)

* aws_inspector_assessment_template

### Terraform Configuration Files

```hcl
resource "aws_inspector_assessment_template" "test" {
  name       = "test"
}
```

### Debug Output

https://gist.github.com/cdchris12/8c9b35433d66cf56a0dbff6ed4d0a859

### Panic Output

N/A

### Expected Behavior

According to [the docs](https://www.terraform.io/docs/providers/aws/r/inspector_assessment_template.html#import), importing this resource is supported.

### Actual Behavior

Terraform fails to import the AWS Inspector assessment template:

```
Error: resource aws_inspector_assessment_template doesn't support import
```

### Steps to Reproduce

1. Setup new AWS Inspector assessment template in AWS
2. Attempt to import that assessment template into terraform
3. See error.

### Important Factoids

None.

### References

None.

**Comment by DrFaust92** [comment]
hey @cdchris12 , update your provider version to 2.54.0 it earliest its supported.

**Comment by cdchris12** [comment]
Thanks for the tip; that got it working for me!
