### ISSUE TITLE
Implement aws_sns_topic Sweeper

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#12658]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The acceptance testing can leave lingering resources on failed runs (e.g. via coding issues during development or panics). These lingering resources can cause quota limits to be reached, extraneous money to be spent, or in some worst cases leave open security risks in the testing account.

We do not require sweeper implementation during initial resource implementation at this time, but this may change in the future when the process can be simplified and documented better.

e.g. after many years of daily (or more) testing runs

```console
$ aws sns list-topics | jq '.Topics | length'
155
```

This resource sweeper should have dependencies on upstream resources, e.g. (some sweepers may not be implemented)

- aws_autoscaling_notification
- aws_budgets_budget
- aws_config_delivery_channel
- aws_dax_cluster
- aws_db_event_subscription
- aws_elasticache_cluster
- aws_elasticache_replication_group
- aws_glacier_vault
- aws_neptune_event_subscription
- aws_redshift_event_subscription
- aws_s3_bucket_notification
- aws_ses_event_destination
- aws_ses_identity_notification
- aws_ses_receipt_rule
- aws_sns_platform_application

### New or Affected Resource(s)

* aws_sns_topic

### Definition of Done

* Sweeper implemented without errors
* Testing account empty of this resource:

```console
$ aws sns list-topics | jq '.Topics | length'
0
```

**Comment by ewbankkit** [comment]
These upstream resources require sweepers added:

* [ ] `aws_autoscaling_notification`
* [ ] `aws_budgets_budget`
* [ ] `aws_db_event_subscription`
* [ ] `aws_glacier_vault`
* [ ] `aws_neptune_event_subscription`
* [ ] `aws_redshift_event_subscription`
* [ ] `aws_s3_bucket_notification`
* [ ] `aws_ses_event_destination`
* [ ] `aws_ses_identity_notification`
* [ ] `aws_ses_receipt_rule`
* [ ] `aws_sns_platform_application`

**Comment by ewbankkit** [comment]
As a follow on, use the new internal `waiters` package added for `aws_db_event_subscription` in the main resource code.
