### ISSUE TITLE
Setting `iops` on non-provisioned IOPS EBS volumes should be a validation error

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#12667]
When creating or updating an EBS volume, either as a bare resource or as a root volume or attached volume on an EC2 instance, the code either logs a warning (root devices and creating a standalone resource) or does nothing (attached volumes or updating a standalone resource).

This should be treated as a validation error instead.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `aws_instance`
* `aws_ebs_volume`

**Comment by anGie44** [comment]
The associated changes in #14310 have been merged and will release with the upcoming `v3.0.0` of the Terraform AWS Provider.
