### ISSUE TITLE
Lambda_layer cannot be created from arn

### ISSUE THREAD

**Issue by nan008** [terraform-providers/terraform-provider-aws#12689]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.random v2.2.1

### Affected Resource(s)

* aws_lambda_layer_version

according to the Terraform Notes (https://www.terraform.io/docs/providers/aws/r/lambda_function.html#lambda-layers) I can use arn/layers_arn in my Terraform to reference open source arn from another AWS account which AWS also allows on their Counsole

 Lambda Layers

NOTE: The aws_lambda_layer_version attribute values for arn and layer_arn were swapped in version 2.0.0 of the Terraform AWS Provider. For version 1.x, use layer_arn references. For version 2.x, use arn references.

### Terraform Configuration Files

```hcl
resource "aws_lambda_layer_version" "lambda_layer" {
layer_arn = "arn:aws:lambda:${data.aws_region.current.name}:464622532012:layer:Datadog-Python37:11"
layer_name = "Datadog-Python37"
compatible_runtimes = ["python3.7"]
}

```

### Expected Behavior

Lambda_layer created with the correct account_id and version number

### Actual Behavior

```
Error: "layer_arn": this field cannot be set

  on datadog.tf line 267, in resource "aws_lambda_layer_version" "lambda_layer":
 267: resource "aws_lambda_layer_version" "lambda_layer" {
```

arn has the same result

```
Error: "arn": this field cannot be set

  on datadog.tf line 267, in resource "aws_lambda_layer_version" "lambda_layer":
 267: resource "aws_lambda_layer_version" "lambda_layer" {
```

### Steps to Reproduce

use the config 

resource "aws_lambda_layer_version" "lambda_layer" {
layer_arn = "arn:aws:lambda:${data.aws_region.current.name}:464622532012:layer:Datadog-Python37:11"
layer_name = "Datadog-Python37"
compatible_runtimes = ["python3.7"]
}

1. `terraform apply`

### Important Factoids

Please note I am very new to the Terraform but everything else on my .tf is working without issue
This terraform is building Datadog config files and the arn is given by the DD themselves. Manual creation in AWS console works without any issue, Terraform cannot create the layer from arn, it will create from the zip file but with the wrong account ID and version

```
resource "aws_lambda_layer_version" "lambda_layer" {
filename = "datadog/datadog_lambda_py3.7.zip"
layer_name = "Datadog-Python37"
compatible_runtimes = ["python3.7"]
}
```

What I get
```
Layer version
1
Version ARN
arn:aws:lambda:eu-west-1:420XXXXXX88:layer:Datadog-Python37:1
```

And it should be 
```
Layer version
11
Version ARN
arn:aws:lambda:eu-west-1: 464622532012:layer:Datadog-Python37:11
```

**Comment by ewbankkit** [comment]
@nan008 Thanks for raising this.
`arn` (the layer version ARN) and `layer_arn` are [`Computed`](https://www.terraform.io/docs/extend/schemas/schema-behaviors.html#computed)-only attributes and so can't be set for resource creation.
Please see [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/12728#issuecomment-611077136) for an investigation path.

**Comment by Arlington1985** [comment]
@nan008 , this is not the right way of referencing to third party AWS layers. I had same issue and here is how I fixed it. Please see [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/12728#issuecomment-611081268)

**Comment by nan008** [comment]
@Arlington1985 @ewbankkit thank you guys, unfortunately the lambda_layer on terraform.io is not really explained properly and this is the only think on terraform that I had problem with. I actually tried the solution that Arlington1985 suggested without [] and got an error, so decided it cannot be that simple to reference the layers within the function.
