### ISSUE TITLE
aws_launch_template UnauthorizedOperation - even as admin user

### ISSUE THREAD

**Issue by jebbens** [terraform-providers/terraform-provider-aws#12722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.56.0

### Affected Resource(s)

aws_launch_template

### Terraform Configuration Files
provider "aws" {
  profile    = "default"
  region     = "us-east-1"
}
resource "aws_launch_template" "rLaunchTemplate" {
  image_id      = "ami-b70554c8"
}
resource "aws_autoscaling_group" "rAutoScalingGroup" {
  max_size           = 2
  min_size           = 1
  vpc_zone_identifier = ["subnet-xyz","subnet-xyz"]
  mixed_instances_policy {
    instances_distribution {
      on_demand_allocation_strategy = "prioritized"
      on_demand_base_capacity = "1"
      on_demand_percentage_above_base_capacity = "100"
    }
    launch_template {
      launch_template_specification {
        launch_template_id = aws_launch_template.rLaunchTemplate.id
      }
      override {
        instance_type     = "m5.large"
      }
      override {
        instance_type     = "t3.large"
      }
      override {
        instance_type     = "r5.large"
      }
      override {
        instance_type     = "c5.large"
      }
    }
  }
}

### Expected Behavior

Expected to stack to build in our vpc. 

### Actual Behavior

Error: UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message...status code 403, request id: xxx...on <file_name> line x in resource "aws_launch_template" "rLaunchTemplate" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I have updated the iam user I am using with my aws credentials in the terminal to AdministratorAccess, but continue to get unauthorized error

**Comment by smaruy30** [comment]
@jebbens 

try adding permissions bellow.
```
"Action": [
    "ec2:CreateLaunchTemplate",
    "ec2:CreateLaunchTemplateVersion",
    "ec2:ModifyLaunchTemplate"
],
```
Hope It works. I encountered same error message, added these permissions to IAM role, then error has gone.
