### ISSUE TITLE
aws_instance metadata_options don't honor the defaults

### ISSUE THREAD

**Issue by acdha** [terraform-providers/terraform-provider-aws#12723]
## Description

The EC2 aws_instance resource lists several options with default values:

https://www.terraform.io/docs/providers/aws/r/instance.html#metadata-options

Unfortunately, you have to specify these values to have Terraform successfully create the resource.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.http v1.1.1
```

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
   metadata_options {
     # Require usage of the newer v2 metadata API:
    http_tokens = "required"
   }
```

### Expected Behavior

Terraform would use the documented default values for the unspecified fields

### Actual Behavior

```
InvalidParameterValue: A value of '' is not valid for HttpEndpoint
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/12564
* https://github.com/terraform-providers/terraform-provider-aws/issues/10949
* https://github.com/terraform-providers/terraform-provider-aws/pull/12491

**Comment by acdha** [comment]
Odd - #12564 has the exact error message but Github search didn’t turn it up before I opened this issue. I’m inclined to close this as a duplicate.
