### ISSUE TITLE
Add support for EFS File Systems configuration in Amazon ECS and AWS Fargate

### ISSUE THREAD

**Issue by marcincuber** [terraform-providers/terraform-provider-aws#12741]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for new feature `EFSVolumeConfiguration` which is available for ECS + Fargate running platform version 1.4.

### References

* https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-ecs-aws-fargate-support-amazon-efs-filesystems-generally-available/

**Comment by DrFaust92** [comment]
`EFSVolumeConfiguration` support is already present but was not tested with fargate (there is no particular fargate config for this block)

the IAM and Access Point configs needs to be added

**Comment by marcincuber** [comment]
@DrFaust92 I tried upgrading my ECS Fargate services using latest terraform provider and it didn't upgrade it to platform version 1.4. Could it be that it requires SDK upgrade as well?

**Comment by DrFaust92** [comment]
Can you share your config? 

The changes are for ecs task definition and the platform version is part of ecs service (may be needed to specify explicitly 1.4 and not the default) 

I'll try to test it but I don't see anything in the new sdk version that's related

**Comment by marcincuber** [comment]
Hi I am using my module which you can find here together with the ecs_service resources. https://github.com/umotif-public/terraform-aws-ecs-fargate/blob/master/main.tf#L220

I am not specifying `platform_version` which means that for FARGATE it should default to LATEST which is 1.4.

**Comment by bflad** [comment]
`LATEST` not being "latest" may be confirmed here: https://github.com/aws/containers-roadmap/issues/53#issuecomment-611165795 (e.g. an API issue)

**Comment by tabletcorry** [comment]
`LATEST` still points to `1.3.0` per the docs: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html

> To use a specific platform version, specify the version number when creating or updating your service. If you specify LATEST, your tasks use platform version 1.3.0.

So to test this, you must specify `1.4.0` at the moment.

**Comment by DrFaust92** [comment]
Argh, I user 1.4 and not 1.4.0 so it might the reason it failed on my side.

I'll check again.

**Comment by TravisZ** [comment]
Thanks @tabletcorry! Just tested with `1.4.0` and confirmed it worked :)

**Comment by marcincuber** [comment]
So to wrap up this issue. This feature is already support and to use the latest version fargate we need to specify the following:
```hcl
resource "aws_ecs_service" "service" {
  ...
  platform_version = "1.4.0"
}
```
and for some random reason LATEST version still points at 1.3.0 version.
