### ISSUE TITLE
Kinesis Firehose - add support for specific region

### ISSUE THREAD

**Issue by justinnaldzin** [terraform-providers/terraform-provider-aws#12768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Within the **Kinesis Firehose** resource `aws_kinesis_firehose_delivery_stream`, would like the ability to specify a specific **region**.

Currently there is no `region` or `region_name` argument available in the definition and creating a new stream defaults to the `region` specified in the `provider` resource (I think).

### New or Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_firehose_delivery_stream" "my_firehose_delivery_stream" {
  name        = "my-firehose-delivery-stream"
  region_name = "us-east-1"
  destination = "extended_s3"
  extended_s3_configuration {
    ...
  }
}
```

### References

* #0000

**Comment by Jukie** [comment]
Couldn't you just specify multiple providers similar to how this would be handled with global RDS? 
Ref: https://www.terraform.io/docs/providers/aws/r/rds_global_cluster.html

**Comment by justinnaldzin** [comment]
Good recommendation, this is acceptable, thank you!
