### ISSUE TITLE
resource_aws_dlm_lifecycle_policy `times` validation is incorrect

### ISSUE THREAD

**Issue by christek91** [terraform-providers/terraform-provider-aws#12799]
It looks like the regex used for validation in the provider is slightly off w/ what the API uses. The regex in the docs doesn't allow you to drop the leading 0 in the hours field: https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateRule.html#dlm-Type-CreateRule-Times 

The fix looks super simple, and I have it queued up in a PR already. Will add it to a comment here when submitted. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`Terraform v0.11.7`
AWS Provider: `  version = "1.59"`

### Affected Resource(s)

* aws_resource_aws_dlm_lifecycle_policy

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "dlm_lifecycle_role" {
  name = "dlm-lifecycle-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "dlm.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "dlm_lifecycle" {
  name = "dlm-lifecycle-policy"
  role = "${aws_iam_role.dlm_lifecycle_role.id}"

  policy = <<EOF
{
   "Version": "2012-10-17",
   "Statement": [
      {
         "Effect": "Allow",
         "Action": [
            "ec2:CreateSnapshot",
            "ec2:DeleteSnapshot",
            "ec2:DescribeVolumes",
            "ec2:DescribeSnapshots"
         ],
         "Resource": "*"
      },
      {
         "Effect": "Allow",
         "Action": [
            "ec2:CreateTags"
         ],
         "Resource": "arn:aws:ec2:*::snapshot/*"
      }
   ]
}
EOF
}

resource "aws_dlm_lifecycle_policy" "example" {
  description        = "example DLM lifecycle policy"
  execution_role_arn = "${aws_iam_role.dlm_lifecycle_role.arn}"
  state              = "ENABLED"

  policy_details {
    resource_types = ["VOLUME"]

    schedule {
      name = "2 weeks of daily snapshots"

      create_rule {
        interval      = 24
        interval_unit = "HOURS"
        times         = ["7:45"]
      }

      retain_rule {
        count = 14
      }

      tags_to_add = {
        SnapshotCreator = "DLM"
      }

      copy_tags = false
    }

    target_tags = {
      Snapshot = "true"
    }
  }
}
```

### Expected Behavior

Plan and Apply operations should succeed.

### Actual Behavior

Plan succeeds, but on apply you get:
```
Error: Error applying plan:
1 error(s) occurred:
* aws_dlm_lifecycle_policy.example: error creating DLM Lifecycle Policy: InvalidRequestException: The following parameter(s) are invalid: Times {7:00} in Schedule {example DLM lifecycle policy}
        status code: 400, request id: xxx-xxx-xxx
```

### Steps to Reproduce

1. `terraform plan` (should succeed)
2. `terraform apply` (should fail)

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.58.0 of the Terraform AWS Provider, later this week. Thanks to @christek91 for the implementation. 👍
