### ISSUE TITLE
AppSync: Missing "excludeVerboseContent" option from "aws_appsync_graphql_api" Resource

### ISSUE THREAD

**Issue by mk0a1a** [terraform-providers/terraform-provider-aws#12828]
The `excludeVerboseContent` option is missing in `log_config` for the `aws_appsync_graphql_api` resource. In the AWS console, this is done by toggling the `Include verbose content` checkbox. By enabling this option, logs generated by AppSync will include request headers, response headers, context, and evaluated mapping templates, regardless of field logging level. The [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/appsync/create-graphql-api.html) also has this option in its `--log-config` flag.

Shorthand Syntax:
```
fieldLogLevel=string,cloudWatchLogsRoleArn=string,excludeVerboseContent=boolean
```

JSON Syntax:
```json
{
  "fieldLogLevel": "NONE"|"ERROR"|"ALL",
  "cloudWatchLogsRoleArn": "string",
  "excludeVerboseContent": true|false
}
```

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.59.0 of the Terraform AWS Provider, later this week. Thanks to @drexler for the implementation. 👍
