### ISSUE TITLE
Allow attachment between aws_codedeploy_deployment_group and aws_elb

### ISSUE THREAD

**Issue by hbarcelos** [terraform-providers/terraform-provider-aws#1283]
### Terraform Version
`0.9.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_codedeploy_deployment_group
- aws_elb

### Motivation
Currently it's only possible to attach deployment groups to autoscaling groups.

However, this is not enough when there is an ELB on top of that autoscaling group, because the deploy will not be able to block traffic and de-register the instance from the ELB. 

By doing so, active connections **will be dropped** during the deploy.

For more details, check the [docs for AppSpec Hooks](http://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html):

> **Note**
> 
> For in-place deployments, the six hooks related to blocking and allowing traffic apply only if you specify a Classic Load Balancer from Elastic Load Balancing in the deployment group.

**Comment by JoshuaEstes** [comment]
This can be as easy as an option when defining the AWS CodeDeploy Group. I'm running into issues with this now and have looked into this a little bit.

http://docs.aws.amazon.com/cli/latest/reference/deploy/create-deployment-group.html

```
resource "aws_codedeploy_deployment_group" "foo" {
  load_balancer_info = "${aws_elb.foo.name}"
}
```

I was able to find an article that explains how to do this using the AppSpec Hooks, but it's a lot easier for me to just log into AWS and update the Deployment Group to use the ELB I want. It sucks that it's manual, but it's a lot less work than using the hooks.

**Comment by JoshuaEstes** [comment]
PR #1162 should resolve this

**Comment by bflad** [comment]
The support for handling this was added to the `aws_codedeploy_deployment_group` resource in the [v1.1.0 release of the provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#110-october-16-2017) (let us know if it does not handle this use case correctly). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
