### ISSUE TITLE
aws_default_route_table doesn't apply tags at initial apply

### ISSUE THREAD

**Issue by nibrahv** [terraform-providers/terraform-provider-aws#12839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.57.0

### Affected Resource(s)

aws_default_route_table

### Terraform Configuration Files

N/A

### Debug Output

terraform_debug-1stApply.log
terraform_debug-2ndApply.log

https://gist.github.com/nibrahv/4d10a417ab65f7efe967c48603c0e449

### Panic Output

N/A

### Expected Behavior

Provisioning new AWS VPC and using "aws_default_route_table" resource to identify default route table created during VPC creation.  Expectation is to set "Name" and other tags during "terraform apply".  

### Actual Behavior

Initial "terraform apply" completes without error, however no tags are set on the default route table resource.  When running "apply" a second time, it identifies the missing tags and sets them appropriately:

(Terraform output)
Terraform will perform the following actions:

  # aws_default_route_table.rtb_VMC will be updated in-place
  ~ resource "aws_default_route_table" "rtb_VMC" {
        default_route_table_id = "rtb-027da73bf0fd77b78"
        id                     = "rtb-027da73bf0fd77b78"
        owner_id               = "############"
        propagating_vgws       = []
        route                  = []
      ~ tags                   = {
          + "Name" = "rtb_VMC"
          + "foo"  = "bar"
          + "foo1" = "1bar"
          + "foo2" = "2bar"
          + "foo3" = "3bar"
        }
        vpc_id                 = "vpc-0bafc004395a089ae"
    }

Plan: 0 to add, **1 to change**, 0 to destroy.
(Terraform output)

### Steps to Reproduce

Code:
resource "aws_vpc" "default_vmc_vpc" {
   cidr_block = "10.1.0.0/16"
}

resource "aws_default_route_table" "rtb_VMC" {
   default_route_table_id =  aws_vpc.default_vmc_vpc.default_route_table_id
   tags = {
      Name = "rtb_VMC"
      foo = "bar"
      foo1 = "1bar"
      foo2 = "2bar"
      foo3 = "3bar"
      }
}

1. `terraform apply`
(note missing tags in AWS management console)

2. 'terraform apply'
(note actions to perform in execution plan, "1 to change")

### Important Factoids

OS: CentOS Linux release 7.7.1908 

### References

N/A

* #0000

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.60.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
