### ISSUE TITLE
aws_iot_topic_rule:Add Qos field to republish to IoT topic

### ISSUE THREAD

**Issue by shanmud** [terraform-providers/terraform-provider-aws#12830]
### Community Note

* AWS now supporting QoS While republishing to IoT topic. 

### New or Affected Resource(s)

* aws_iot_topic_rule

### References

* https://aws.amazon.com/about-aws/whats-new/2019/08/aws-iot-core-adds-ability-to-configure-quality-of-service-for-republish-action/

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.62.0 of the Terraform AWS Provider, later this week. Thanks to @drexler for the implementation. 👍
