### ISSUE TITLE
Skip adding needs-triage label for maintainer submitted issues

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#12841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Configure the GitHub actions workflow so as not to add the needs-triage label if the issue was submitted by a maintainer.

The current behavior means that maintainers need to wait for the action to operate on their new issue before manually removing the label.

**Comment by bflad** [comment]
Submitted a quick and dirty fix for this, PTAL: https://github.com/terraform-providers/terraform-provider-aws/pull/12857
