### ISSUE TITLE
Error when retrieving a Gateway API ( Endpoint_type: private with VPC Endpoint) in data

### ISSUE THREAD

**Issue by beydiat** [terraform-providers/terraform-provider-aws#12870]
**Code :** 
data "aws_api_gateway_rest_api" "api-gw" {
  name = "my-existing-api-gateway-name"
}

**Errors :** 
Error: error setting endpoint_configuration: endpoint_configuration.0.vpc_endpoint_ids: '': source data must be an array or slice, got struct

  on main.tf line 5, in data "aws_api_gateway_rest_api" "api-gw":
   5: data "aws_api_gateway_rest_api" "api-gw" {

**Comment by bflad** [comment]
A fix for this was submitted here: #12825
