### ISSUE TITLE
aws_lambda_alias import sets function_name attribute to function's ARN

### ISSUE THREAD

**Issue by angelyan** [terraform-providers/terraform-provider-aws#12875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.20
+ provider.aws v2.58.0
```

### Affected Resource(s)

* aws_lambda_alias

### Terraform Configuration Files

```hcl
resource "aws_lambda_alias" "alias" {
  function_name = "lambda"
  function_version = "..."
  name = "alias"
}
```

### Expected Behavior

`terraform import aws_lambda_alias.alias lambda/alias` should set the attribute `function_name` to `lambda`.

### Actual Behavior

`terraform import aws_lambda_alias.alias lambda/alias` sets the attribute `function_name` to the function's ARN.

```
Terraform will perform the following actions:

  # aws_lambda_alias.alias must be replaced
-/+ resource "aws_lambda_alias" "alias" {
      ~ arn              = "arn:aws:lambda:<region>:<account>:function:lambda:alias" -> (known after apply)
        description      = "..."
      ~ function_name    = "arn:aws:lambda:<region>:<account>:function:lambda" -> "lambda" # forces replacement
        function_version = "..."
      ~ id               = "arn:aws:lambda:<region>:<account>:function:lambda:alias" -> (known after apply)
      ~ invoke_arn       = "..." -> (known after apply)
        name             = "alias"
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. Create the lambda alias
2. Run `terraform import`
3. Run `terraform plan`

**Comment by bflad** [comment]
The fix for this behavior has been merged and will release with version 3.0.0 of the Terraform AWS Provider, likely in about two weeks. 👍
