### ISSUE TITLE
Missing aws_apigatewayv2_vpc_link

### ISSUE THREAD

**Issue by bjweaver** [terraform-providers/terraform-provider-aws#12880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_apigatewayv2_vpc_link is not implemented in AWS provider

https://docs.aws.amazon.com/cli/latest/reference/apigatewayv2/create-vpc-link.html

**Comment by gdavison** [comment]
This will be addressed by #12577
