### ISSUE TITLE
Implement `CreateDefaultVPC` in aws_default_vpc

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-aws#1289]
In AWS SDK 1.10.18, AWS added the ability to recreate the default VPC without needing to contact AWS

http://docs.aws.amazon.com/cli/latest/reference/ec2/create-default-vpc.html

**Comment by ewbankkit** [comment]
@stack72 How about adding a `create_if_missing` attribute on `aws_default_vpc` with a default of value of `false` for backwards compat?

**Comment by bflad** [comment]
Let's track this further in #4959 -- we should probably talk about the full lifecycle at once instead of just the creation portion 😄
