### ISSUE TITLE
Error removing configuration_info from aws_msk_cluster

### ISSUE THREAD

**Issue by angelabad** [terraform-providers/terraform-provider-aws#12895]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- Terraform v0.12.24
- provider.aws v2.58.0

### Affected Resource(s)

* aws_msk_cluster

### Terraform Configuration Files

If you have msk  cluster with configuration info like this:

```hcl
  configuration_info {
    arn = aws_msk_configuration.this.arn
    revision = aws_msk_configuration.this.latest_revision
  }
```
Apply works fine, but if after apply you remove this code:

### Expected Behavior

Terraform should remove configuration info from aws msk cluster resource

### Actual Behavior

Terraform doesnt remove this configuration, it tries to set the block arn to null

```
~ configuration_info {
     - arn      = "arn:aws:kafka:eu-west-2:394597695348:configuration/kafka-17740831363609595903/9a6221c6-9a8c-470d-b47e-9ff26558efa8-4" -> null
       revision = 1
}
```

And it fails wiht:

```
Error: error updating MSK Cluster (arn:aws:kafka:eu-west-2:394597695348:cluster/kafka/2e19ba97-34a0-4b59-a83c-dfefe7a1d8f1-4) configuration: BadRequestException: Invalid Configuration ARN.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "1b8fefeb-9946-4900-8440-eaefaf4a4ed3"
  },
  InvalidParameter: "configurationInfo",
  Message_: "Invalid Configuration ARN."
}
```

### Steps to Reproduce

1. Create configuration_info block
2. `terraform apply`
3. Remove configuration_info block
4. `terraform apply`

Thanks for your work!

**Comment by andymalakov** [comment]
My 2-cents: not much can be done here: AWS does not provide API to remove MSK configuration at this point (August 2020). See https://docs.aws.amazon.com/cli/latest/reference/kafka/index.html (there is no `delete-configuration` or similar command).

**Comment by angelabad** [comment]
Now AWS api has this: https://docs.aws.amazon.com/cli/latest/reference/kafka/delete-configuration.html

I will try a PR with this!

**Comment by angelabad** [comment]
This is solved with new versions of the provider
