### ISSUE TITLE
Incorrect example in "aws_apigatewayv2_deployment" docs

### ISSUE THREAD

**Issue by christhomas** [terraform-providers/terraform-provider-aws#12896]
On the page: https://www.terraform.io/docs/providers/aws/r/apigatewayv2_deployment.html

It gives an example:
```
resource "aws_apigatewayv2_deployment" "example" {
  api_id      = "${aws_apigatewayv2_route.example.api_id}"
  description = "Example deployment"
}
```

It's using the wrong resource "aws_apigatewayv2_route" in the example code. Probably it should be using "aws_apigatewayv2_api" instead.

**Comment by ewbankkit** [comment]
Strictly speaking that is OK as the reference is to the `api_id` attribute of the route and this shows a more likely dependency relationship as a deployment requires at least one route on the API.

**Comment by christhomas** [comment]
I know what you mean, it just struck me as strange as to why you'd get the api_id from the route resource and not the API resource. For daisy-chaining a developers "train of thought" and leading them to understand how the resources connect, I guess it makes sense. I still think it's weird, but if you wanna close this, then I'm ok with that

**Comment by ewbankkit** [comment]
Yes, could you please close?
