### ISSUE TITLE
aws_lambda_alias is recreated when function_name changes from function name to ARN and viceversa

### ISSUE THREAD

**Issue by angelyan** [terraform-providers/terraform-provider-aws#12901]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.58.0
```

### Affected Resource(s)

* aws_lambda_alias

### Terraform Configuration Files

```diff
resource "aws_lambda_alias" "alias" {
- function_name = "lambda"
+ function_name = "arn:aws:lambda:<region>:<account>:function:lambda"
  function_version = "..."
  name = "alias"
}
```

### Expected Behavior

`terraform plan` should show no changes.

### Actual Behavior

`terraform plan` shows that alias will be recreated even though the ARN points to the same function.

```hcl
Terraform will perform the following actions:

  # aws_lambda_alias.alias must be replaced
-/+ resource "aws_lambda_alias" "alias" {
      ~ arn              = "arn:aws:lambda:<region>:<account>:function:lambda:alias" -> (known after apply)
        description      = "..."
      ~ function_name    = "lambda" -> "arn:aws:lambda:<region>:<account>:function:lambda" # forces replacement
        function_version = "..."
      ~ id               = "arn:aws:lambda:<region>:<account>:function:lambda:alias" -> (known after apply)
      ~ invoke_arn       = "..." -> (known after apply)
        name             = "alias"
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. Create a lambda alias with `function_name` argument set to the name of the function.
2. Change `function_name` to the ARN of the function.
3. Run `terraform plan`.

**Comment by bflad** [comment]
This difference suppression has been merged and will release with version 2.59.0 of the Terraform AWS Provider, later this week. Thanks to @angelyan for the implementation. 👍
