### ISSUE TITLE
Support aws_service_discovery_private_dns_namespace Resource Import

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#12913]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_service_discovery_private_dns_namespace` resource does not currently support import. It would be great if it did!

Implementation should include:
- [x] Resource `Importer` `State` implementation
- [x] Acceptance testing with `ImportState` and `ImportStateVerify`
- [x] Documentation

### Affected Resource(s)

* aws_service_discovery_private_dns_namespace

### References

* [Contributing Guide section on Adding Resource Import Support](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#adding-resource-import-support)

**Comment by anGie44** [comment]
The fix for this has been merged and will release with version 2.59.0 of the Terraform AWS Provider.
