### ISSUE TITLE
Not able to update tags for AWS ElasticCache 

### ISSUE THREAD

**Issue by sahilthakral-olx** [terraform-providers/terraform-provider-aws#12938]
### Issue

I am not able to update tags in my AWS Elasticache cluster using terraform. I am able to successfully apply my terraform changes, but the tags doesn't get reflected when I check them  on AWS console.

I even checked my statefile and the tags were present in the state file but are not applied to my elasticache cluster.

### Terraform Version

0.11.10

### Affected Resource(s)

* aws_elasticache_replication_group

### Steps to Reproduce

1. Create an AWS elasticache cluster using aws_elasticache_replication_group resource.
2. After it gets created, add tags to it and apply again
3. Terraform will show that tags are applied successfully, but in reality that are not applied to the elasticache cluster.

**Comment by DrFaust92** [comment]
Reading and Update tag capabilities are missing, i'll open a PR to address this.
FYI the resource being tagged is not the group itself but the nodes/clusters in the group

**Comment by sean-zou** [comment]
Can anyone help to merge the pr? We've been waiting for it for a while

**Comment by anGie44** [comment]
Hi @sahilthakral-olx, @sean-zou , et al. 👋 The fix has been merged and will release with `v3.4.0` of the Terraform AWS Provider, likely out later today :)
