### ISSUE TITLE
 localstack has been moved to a single port (default 4566)

### ISSUE THREAD

**Issue by ozbillwang** [terraform-providers/terraform-provider-aws#12932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

>Note: Starting with localstack version 0.11.0, all APIs are exposed via a single edge service, which is accessible on http://localhost:4566 by default

The related document need be updated: 

https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/guides/custom-service-endpoints.html.md#localstack

https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html#localstack

### New or Affected Resource(s)

No, only document updates

I'd like to set a single endpoint, but not sure how to do that, any hints for me?

Change from 

```
provider "aws" {
  # ... potentially other provider configuration ...

  endpoints {
    apigateway     = "http://localhost:4567"
    cloudformation = "http://localhost:4581"
    cloudwatch     = "http://localhost:4582"
    dynamodb       = "http://localhost:4569"
    ec2            = "http://localhost:4597"
    es             = "http://localhost:4578"
    firehose       = "http://localhost:4573"
    iam            = "http://localhost:4593"
    kinesis        = "http://localhost:4568"
    lambda         = "http://localhost:4574"
    route53        = "http://localhost:4580"
    redshift       = "http://localhost:4577"
    s3             = "http://localhost:4572"
    secretsmanager = "http://localhost:4584"
    ses            = "http://localhost:4579"
    sns            = "http://localhost:4575"
    sqs            = "http://localhost:4576"
    ssm            = "http://localhost:4583"
    stepfunctions  = "http://localhost:4585"
    sts            = "http://localhost:4592"
  }
}
```

to

```
provider "aws" {
  # ... potentially other provider configuration ...

  endpoints = "http://localhost:4566"
}
```

**Comment by bflad** [comment]
Hi folks 👋

The [Custom Service Endpoints feature](https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html) of the Terraform AWS Provider is designed to offer the lowest level configuration of endpoints per AWS service. It should be possible to adjust the provider endpoint configuration to repeatedly point to the same URL for each LocalStack service, e.g.

```
provider "aws" {
  # ... potentially other provider configuration ...

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    ec2            = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}
```

If that configuration does not work, please reach out.

**Comment by ozbillwang** [comment]
Thanks, that's what I currently do. 

If this update is not planned, I am fine to continous this way.
