### ISSUE TITLE
How can I attache an integration to route for API gateway version2?

### ISSUE THREAD

**Issue by zhaoyi0113** [terraform-providers/terraform-provider-aws#12934]
I am using `aws_apigatewayv2_api` related resources to manage API Gateway Version2. But I found there are some key features missing:

- How can I attach an integration to route?
- How can I define a path and method to a route?

Corresponding feature on AWS console is shown in below screenshot:

![image](https://user-images.githubusercontent.com/3355579/79951067-6535d900-84bb-11ea-944a-327d7d301fb2.png)

![image](https://user-images.githubusercontent.com/3355579/79951136-83033e00-84bb-11ea-8517-ec094ecffa46.png)

I can't find any information in your doc.

**Comment by ewbankkit** [comment]
@zhaoyi0113 Thanks for opening this.
Integrations are attached to routes via the [`aws_apigatewayv2_route.target`](https://www.terraform.io/docs/providers/aws/r/apigatewayv2_route.html) attribute, for example

```hcl
resource "aws_apigatewayv2_integration" "ConnectIntegrat" {
  api_id             = "${aws_apigatewayv2_api.SimpleChatWebSocket.id}"
  integration_type   = "AWS_PROXY"
  description        = "Connect Integration"
  integration_uri    = "${aws_lambda_function.OnConnectFunction.invoke_arn}"
  integration_method = "POST"
}

resource "aws_apigatewayv2_route" "ConnectRoute" {
  api_id         = "${aws_apigatewayv2_api.SimpleChatWebSocket.id}"
  route_key      = "$connect"
  operation_name = "ConnectRoute"
  target         = "integrations/${aws_apigatewayv2_integration.ConnectIntegrat.id}"
}
```

A full-features WebSocket API example is in https://github.com/terraform-providers/terraform-provider-aws/pull/9533.
We will provide similar examples for HTTP APIs.

**Comment by zhaoyi0113** [comment]
Thanks for your response. How can I define `path` for the route? And what does `route_key` mean in terraform?

**Comment by zhaoyi0113** [comment]
ok I found I need to define the path on the route key with the format METHOD: PATH. 
It would be good to add that on the doc
