### ISSUE TITLE
Wanted - aws_nat_gateway datasource

### ISSUE THREAD

**Issue by clintoncwolfe** [terraform-providers/terraform-provider-aws#1293]
I wish I could query the existing NAT gateway instances; in my use case, I needed to find the EIP associated with the NAT.  I've implemented a workaround using an external datasource, shelling out to AWS CLI, and using jq to parse the response - that's not very portable, though.

#1196 seemed straightforward, so I thought I would volunteer to make an attempt at an implementation; any reason not to?

**Comment by shadycuz** [comment]
This is a duplicate of  #1238 , a PR is in the works.

**Comment by clintoncwolfe** [comment]
I'll help out where I can - thanks for catching the dupe!
