### ISSUE TITLE
Newly added AWS region (af-south-1) is invalid when planning

### ISSUE THREAD

**Issue by Petrie65** [terraform-providers/terraform-provider-aws#12941]
AWS region **Afica (Cape Town) af-south-1** was made available on 22 April 2020 and does not work with Terraform yet.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* provider

### Terraform Configuration Files

```hcl
# Create a new instance of the latest Ubuntu 14.04 on an
# t2.micro node with an AWS Tag naming it "HelloWorld"
provider "aws" {
  region = "af-south-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "HelloWorld"
  }
}
```

### Debug Output

```
Error: Invalid AWS Region: af-south-1

  on main.tf line 3, in provider "aws":
   3: provider "aws" {
```

### Expected Behavior

Successful plan for resources in region 'af-south-1'

### Actual Behavior

Unsuccessful plan with error

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

N/A

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/12940

**Comment by bflad** [comment]
Hi @Petrie65 👋 Thank you for submitting this. New regions require some slight updates in the provider to support natively. Please track #12940 for updates about this functionality and information about the `skip_region_validation` workaround in the meantime.
