### ISSUE TITLE
Tags for the IOT topic rules

### ISSUE THREAD

**Issue by Kydybets** [terraform-providers/terraform-provider-aws#12947]
### Description
Due to official documentation
https://docs.aws.amazon.com/iot/latest/developerguide/tagging-iot.html
we can tag IOT resources with cli
https://docs.aws.amazon.com/cli/latest/reference/iot/create-topic-rule.html
Could you please provide such possibility

### New or Affected Resource(s)

* aws_iot_topic_rule

### Potential Terraform Configuration

Maybe would be useful to use it like everywhere:

```hcl
tags = {
    Name = "HelloWorld"
  }
```

**Comment by bflad** [comment]
Support for managing `aws_iot_topic_rule` resource tags has been merged and will release with version 2.63.0 of the Terraform AWS Provider, later this week. 👍
