### ISSUE TITLE
Support for vpc_link for http apis?

### ISSUE THREAD

**Issue by rayterrill** [terraform-providers/terraform-provider-aws#12969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there support for creating vpc_links for http apis (API Gateway v2 APIs)? It looks like the current aws_api_gateway_vpc_link resource only understands how to build REST API (v1) vpc_links, connecting to NLBs.

### New or Affected Resource(s)

* aws_api_gateway_vpc_link or aws_api_gatewayv2_vpc_link

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-vpclink.html

**Comment by verokarhu** [comment]
That functionality should be in the next release, see #12577
