### ISSUE TITLE
data "aws_prefix_list" is not able to fetch correct CIDR blocks from AWS IP list https://ip-ranges.amazonaws.com/ip-ranges.json

### ISSUE THREAD

**Issue by nyadav08** [terraform-providers/terraform-provider-aws#12966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.23

provider.aws: version = "2.58"

### Affected Resource(s)

data "aws_prefix_list"

### Terraform Configuration Files

```hcl

data "aws_prefix_list" "private_s3" {
  name = "com.amazonaws.us-west-2.s3"
}
resource "aws_security_group" "endpoint-s3" {
  name   = "${var.project_id}-endpoint-s3"
  vpc_id = var.vpc_id  egress {
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
    cidr_blocks = data.aws_prefix_list.private_s3.cidr_blocks
  } 
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

It should have add below IP ranges based on IP range list from AWS for us-west-2 S3. https://ip-ranges.amazonaws.com/ip-ranges.json
52.92.32.0/22
54.231.160.0/19
52.218.128.0/17

### Actual Behavior

Its only adding CIDR block 52.218.128.0/17

### Steps to Reproduce

1. `terraform apply`

### References
https://ip-ranges.amazonaws.com/ip-ranges.json
https://awsiprange.com/browse?service=s3&region=us-west-2&show_service=on&show_region=on&show_prefix=on

* #0000

**Comment by ewbankkit** [comment]
@nyadav08 Thanks for raising this.
`cidr_blocks` is a list of individual CIDR blocks (should have length 3 in `us-west-2`), so you will need to use something like [`for_each`](https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings) to create multiple SG rules.

**Comment by nyadav08** [comment]
Thanks for your response but this is related to egress rules for a security groups. We don't want to create multiple SG's as compared to multiple egress rules inside on SG.

This issue is only happening for us-west-2 region and it works fine for ca-central-1 and other regions.

`data "aws_prefix_list" "private_s3" {
  name = "com.amazonaws.us-west-2.s3"
}
resource "aws_security_group" "endpoint-s3" {
  name   = "${var.project_id}-endpoint-s3"
  vpc_id = var.vpc_id  egress {
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
    cidr_blocks = data.aws_prefix_list.private_s3.cidr_blocks
  }  `

**Comment by ewbankkit** [comment]
```console
$ aws --region us-west-2 ec2 describe-prefix-lists
{
    "PrefixLists": [
        {
            "Cidrs": [
                "52.218.128.0/17"
            ],
            "PrefixListId": "pl-68a54001",
            "PrefixListName": "com.amazonaws.us-west-2.s3"
        },
        {
            "Cidrs": [
                "52.94.28.0/23",
                "52.94.10.0/24"
            ],
            "PrefixListId": "pl-00a54069",
            "PrefixListName": "com.amazonaws.us-west-2.dynamodb"
        }
    ]
}
```

**Comment by ewbankkit** [comment]
@nyadav08 Thanks for raising this issue.
The `cidr_blocks` attribute of the `aws_vpc_endpoint` resource returns the result of the `DescribePrefixLists` EC2 API call for the specified service and as the output above shows, this is currently the single value `52.218.128.0/17`.
I suggest contacting AWS Support with a query as to why the published IP ranges has 2 values for S3 in `us-west-2`.

I have hit this kind of problem before in my own work and created a couple of Terraform providers to help with this.
[Here's a gist](https://gist.github.com/ewbankkit/6be9526f3c975c72972ce26986c58cc7) that shows how to use them to return a set containing the 2 values you are expecting.:

```console
$ terraform apply
data.get_file.aws_ip_ranges: Refreshing state...
data.jmespath_search.us_west_2_s3: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

prefix_list = [
  "52.218.128.0/17",
  "52.92.128.0/17",
]
```
