### ISSUE TITLE
Add support for updating SSM resource attributes

### ISSUE THREAD

**Issue by sfrode** [terraform-providers/terraform-provider-aws#1296]
As discussed with @stack72 in #1257, there is a lack of support for updating some SSM resources, leading to resources being recreated with every change. As such, after having surveyed the current SDK that is bundled with this provider, I propose to add update functions to the following resources and and removing the ForceNew option on the listed attributes.

**aws_ssm_association**:
parameters
schedule_expression
output_location

**aws_ssm_patch_baseline**:
name
description
global_filter
approval_rule
approved_patches
rejected_patches
approved_patches_compliance_level

Thank you!

**Comment by grubernaut** [comment]
Related, and possibly fixed via: #1295

**Comment by sfrode** [comment]
The changes in #1295 are not related to this ticket that seeks to improve the following resources:
aws_ssm_association
aws_ssm_patch_baseline

**Comment by stack72** [comment]
@sfrode I opened the PR that adds your enhancements :)
