### ISSUE TITLE
Allow tls_config attribute on aws_apigatewayv2_integration resource

### ISSUE THREAD

**Issue by rayterrill** [terraform-providers/terraform-provider-aws#12971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It looks like this attribute was removed in commit ffbce32f931a9b33adc8407a267ba176c510bd44. Per the docs this would allow us to flip to HTTPS in private integrations (https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-integrations-integrationid.html).

### New or Affected Resource(s)

* aws_apigatewayv2_integration

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-integrations-integrationid.html

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8949

**Comment by ewbankkit** [comment]
Opened https://github.com/terraform-providers/terraform-provider-aws/pull/13013 to fix this.
