### ISSUE TITLE
Deleting `aws_route` resource fails when deleted outside of Terraform

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#12979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource

* aws_route

**Comment by ewbankkit** [comment]
This MAY be fixed by the check for `isAWSErr(err, "InvalidRoute.NotFound", "")` added in

https://github.com/terraform-providers/terraform-provider-aws/pull/13048/files#diff-d3a4498775ec9e84c2f0d213247c00b5R486-R489

**Comment by gdavison** [comment]
That would do it! Closed in #13048
