### ISSUE TITLE
awsproviderlint: New Check: Ensure isResourceTimeoutError() or tfresource.TimedOut() is called after resource.Retry()

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#12985]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Terraform AWS Provider, it is important that any resource.Retry() calls are immediately followed with a check against isResourceTimeoutError(). The AWS Go SDK automatically performs retries against the underlying API calls and when in this retrying state, the timeout from resource.Retry() can cancel the requests returning the timeout error instead of any API error. This behavior was referenced in various subtle bugs across the entire provider, since it required API requests to be throttled in the practitioner's accounts.

### Flagged Code

```
err := resource.Retry(time.Duration, RetryFunc)

if err != nil {
  return err
}
```
### Passing Code

```
err := resource.Retry(time.Duration, RetryFunc)

if tfresource.TimedOut(err) {
  // AWS Go SDK call again
}

if err != nil {
  return err
}
```
#7873

**Comment by bflad** [comment]
Implementing this in `go/analysis` might prove challenging while the `semgrep` rule below seems to get close to what we want here:

```yaml
rules:
  - id: helper-schema-resource-Retry-without-isResourceTimeoutError
    languages: [go]
    message: Check resource.Retry() errors with isResourceTimeoutError()
    paths:
      exclude:
        - vendor/
      include:
        - aws/
    patterns:
      - pattern-either:
        - pattern: |
            $ERR := resource.Retry(...)
            ...
            return nil
        - pattern: |
            $ERR = resource.Retry(...)
            ...
            return nil
        - pattern: |
            $ERR := resource.Retry(...)
            ...
            return $ERR
        - pattern: |
            $ERR = resource.Retry(...)
            ...
            return $ERR
      - pattern-not: |
          $ERR := resource.Retry(...)
          ...
          if isResourceTimeoutError($ERR) { ... }
          ...
          return nil
      - pattern-not: |
          $ERR = resource.Retry(...)
          ...
          if isResourceTimeoutError($ERR) { ... }
          ...
          return nil
      - pattern-not: |
          $ERR := resource.Retry(...)
          ...
          if isResourceTimeoutError($ERR) { ... }
          ...
          return $ERR
      - pattern-not: |
          $ERR = resource.Retry(...)
          ...
          if isResourceTimeoutError($ERR) { ... }
          ...
          return $ERR
    severity: WARNING
```
