### ISSUE TITLE
Improve aws_launch_template documentation to mention describe delete_on_termination behavior

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#12983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Improve the documentation of `aws_launch_template` to describe the behavior mentioned in #8612. This can cause unexpected issues for practitioners. The actual fix for the issue involves a breaking change and therefore must wait for resolution in the next major release.

### New or Affected Resource(s)

* aws_launch_template

### References

* #8612

**Comment by phils** [comment]
@anGie44  Thanks.. is there a ticket in the 3.0 milestone to make this breaking change?
