### ISSUE TITLE
awsproviderlint: New Check: Avoid *testing.T parameters for testAccCheck.*(Not)?Recreated functions

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#12999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some resource acceptance testing has TestCheckFunc for verifying if a resource was (not) recreated. Some of these TestCheckFunc accept *testing.T as a parameter, which is extraneous since the functions should be returning errors within the function, not calling APIs such as t.Fatalf().

It may make sense to promote this check to `tfproviderlint` instead.

### Flagged Code
```
func testAccCheckAwsBackupSelectionRecreated(t *testing.T, before, after *backup.GetBackupSelectionOutput) resource.TestCheckFunc {
```
### Passing Code
```
func testAccCheckAwsBackupSelectionRecreated(before, after *backup.GetBackupSelectionOutput) resource.TestCheckFunc {
```

**Comment by bflad** [comment]
This issue is now superseded by:

* https://github.com/terraform-providers/terraform-provider-aws/issues/13278
* https://github.com/bflad/tfproviderlint/issues/171

👍
