### ISSUE TITLE
apigatewayv2_integration tls_config attribute not present - cant do Private Integration against HTTPS Listener

### ISSUE THREAD

**Issue by AleksandarTokarev** [terraform-providers/terraform-provider-aws#13001]
I am trying to do a Private Integration against HTTPS Listener of Application Load Balancer. In order to do, we need to have the TLS Config parameter available. I see it was added, but then it got removed. Obviously it needs to be brought back in order for the private integrations to work. I tested this in Cloudformation and it works fine.
https://github.com/terraform-providers/terraform-provider-aws/commit/ffbce32f931a9b33adc8407a267ba176c510bd44

### Terraform Version
Terraform v0.11.2
provider.aws v2.59.0

### Affected Resource(s)
aws_apigatewayv2_integration/
https://www.terraform.io/docs/providers/aws/r/apigatewayv2_integration.html

### Terraform Configuration Files

```
resource "aws_apigatewayv2_integration" "example" {
  api_id             = "${aws_apigatewayv2_api.example.id}"
  integration_type   = "HTTP_PROXY"
  connection_type    = "VPC_LINK"
  connection_id      = "${aws_apigatewayv2_vpc_link.vpc_link.id}"
  integration_uri    = "${var.alb_arn}"
  integration_method = "ANY"
  tls_config         = "url2.dev.randomurl.com"
}
```

### Expected Behavior

The API V2 Integration should have been created with Secure Server name in order to connect to HTTPS listener

### Actual Behavior

Error: aws_apigatewayv2_integration.example: : invalid or unknown key: tls_config

### Steps to Reproduce

1.terraform init
2.terraform apply

### References
I see this was added but then removed in this PR: 
https://github.com/terraform-providers/terraform-provider-aws/commit/ffbce32f931a9b33adc8407a267ba176c510bd44
Obviously doing a private integration against HTTPS listener is not possible without this. I tested this in cloud formation and it seems to work with that attirubute.

**Comment by ewbankkit** [comment]
@AleksandarTokarev Thanks for raising this.
This has already been noted in https://github.com/terraform-providers/terraform-provider-aws/issues/12971.
Could you please close this issue and upvote the linked one?

**Comment by AleksandarTokarev** [comment]
Sure will do that. Thanks @ewbankkit
