### ISSUE TITLE
cloudwatch_event_target's documentation missing clear instruction on "run_command_targets" 

### ISSUE THREAD

**Issue by BastienM** [terraform-providers/terraform-provider-aws#1304]
### Terraform Version

`0.9.5`

### Affected Resource(s)

- aws_cloudwatch_event_target

### Terraform Configuration Files
```hcl

resource "aws_ssm_document" "target" {
  name          = "target"
  document_type = "Command"

  content = "${data.template_file.target.rendered}"
}

resource "aws_cloudwatch_event_rule" "target" {
  name        = "target"
  description = "target"

  schedule_expression = "cron(*/5 * * * *)"
}

resource "aws_cloudwatch_event_target" "target" {
  rule      = "${aws_cloudwatch_event_rule.target.name}"
  target_id = "target"
  arn       = "${aws_ssm_document.target.arn}"
  role_arn  = "${aws_iam_role.role_ssm.arn}"

  run_command_targets = []
}
```

### Context
I want a SSM command to be run periodically on a set of EC2 instances having the tag **Name** set to a certain value.

### Expected Behavior
Comprehensive documentation on what `run_command_targets` awaits as parameter(s) and how to format the data to be supply.

### Actual Behavior
So far from reading the documentation I still didn't catched how this resource's argument wants the data to be formatted.

The only thing I got, after several tries, is that it wants an array(`[]`).

I tried using `"${map("run_command_parameters", list("tag:Name", "frontend"))}` but it results in Terraform telling me that it does not expect a String but an Array.

### Steps to Reproduce
1. `terraform apply`

### References
- **cloudwatch_event_target** documentation [page](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_target.html)

**Comment by Ninir** [comment]
Hey @BastienM 

Thanks for taking the time to open this issue!

`run_command_targets` is actually a list containing `key` & `values` attributes.
To better translate this, let me expose an example:

```hcl
resource "aws_cloudwatch_event_target" "test" {
  arn         = "${aws_ssm_document.foo.arn}"
  rule        = "${aws_cloudwatch_event_rule.console.id}"
  role_arn = "${aws_iam_role.test_role.arn}"

  run_command_targets {
    key = "tag:Name"
    values = ["acceptance_test"]
  }

  run_command_targets {
    key = "tag:Foo"
    values = ["bar"]
  }
}
```

As you can see, it is possible to define multiple `run_command_targets`, which would be taken into account in the resource.

Will update the documentation accordingly, thanks for noticing!

**Comment by BastienM** [comment]
Thank you for quick answer.

I updated my code using the exemple you provided and it now works perfectly.

**Comment by af6140** [comment]
This does not work with multiple run_command_targets any more,
