### ISSUE TITLE
AWS Glue SFTP connection type unsupported with the current Go SDK

### ISSUE THREAD

**Issue by drexler** [terraform-providers/terraform-provider-aws#13064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.24

### Affected Resource(s)

* resource_aws_glue_connection

### Important Factoids

It appears that SFTP is not supported by the Go SDK but the provider does. This should be removed and the relevant documentation updated. 

### References

* #13011
* [SFTP Unsupported - Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#ConnectionInput)

**Comment by DrFaust92** [comment]
The provider will start using enums slices for validations, it seems the the AWS GO SDK exposes this as a valid value (for some reason) and its part of the `ConnectionType_Values` slice in the sdk.
so i'm going to close this, i'll add a comment in the docs.
