### ISSUE TITLE
aws_cloudfront_origin_access_identity - error deleting, not found

### ISSUE THREAD

**Issue by michalschott** [terraform-providers/terraform-provider-aws#13067]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.14 / probably not terraform related itself

### Affected Resource(s)

* aws_cloudfront_origin_access_identity

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_origin_access_identity" "this" {
...
}
```

### Expected Behavior

If resource does not exist, it should be removed from state.

### Actual Behavior
 Instead it just errors similar to https://github.com/terraform-providers/terraform-provider-aws/issues/12900 

### Steps to Reproduce

1. create resource with TF
2. remove it with aws cli / manually
3. run apply

**Comment by bflad** [comment]
The fix for this has been merged and will be released with version 2.67.0 of the Terraform AWS Provider, likely tomorrow. Thanks to @DrFaust92 for the implementation. 👍
