### ISSUE TITLE
eks-getting-started guide is broken

### ISSUE THREAD

**Issue by JesterOrNot** [terraform-providers/terraform-provider-aws#13071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.59.0
+ provider.http v1.2.0
```

### Affected Resource(s)

* examples/eks-getting-started guide

### Terraform Configuration Files

This is in the examples/eks-getting-started guide

### Expected Behavior

Guide does not crash

### Actual Behavior

I get the following

```
Error: error waiting for EKS Node Group (terraform-eks-demo:demo) creation: Ec2SubnetInvalidConfiguration: One or more Amazon EC2 Subnets of [subnet-053f0598226074145, subnet-0badf4770adfbb0ba] for node group demo does not automatically assign public IP addresses to instances launched into it. If you want your instances to be assigned a public IP address, then you need to enable auto-assign public IP address for the subnet. See IP addressing in VPC guide: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-ip-addressing.html#subnet-public-ip. Resource IDs: [subnet-053f0598226074145 subnet-0badf4770adfbb0ba]

  on eks-worker-nodes.tf line 41, in resource "aws_eks_node_group" "demo":
  41: resource "aws_eks_node_group" "demo" {
```

### Steps to Reproduce

1. `git clone 'https://github.com/terraform-providers/terraform-provider-aws.git'`
2. `cd terraform-provider-aws/examples/eks-getting-started`
3. `terraform init`
4. `terraform apply`
5. type yes and click enter
6. See that it fails

**Comment by dbpolito** [comment]
Due to this change https://aws.amazon.com/blogs/containers/upcoming-changes-to-ip-assignment-for-eks-managed-node-groups/

now you need to set https://www.terraform.io/docs/providers/aws/r/subnet.html#map_public_ip_on_launch to true

**Comment by JesterOrNot** [comment]
Got it, I just thought the guide should be updated because as of right now it doesn't work

**Comment by thewizardofoz** [comment]
Hi, 

I set [map_public_ip_on_launch = True](https://gitlab.com/itsmeoz/terraform-eks-cluster-deployment/-/blob/ci-integration/vpc.tf#L19), no change. 

As Daniel mentioned above, after [this improvement](https://github.com/aws/containers-roadmap/issues/607) I started getting the error.

Best,

**Comment by bugb** [comment]
@JesterOrNot , @thewizardofoz  I still can not figure out how to fix this problem, is there any help?

**Comment by sveba** [comment]
I also have this problem and no fix for it yet. Any advice?

**Comment by bugb** [comment]
@sveba  I do not have any good solution for this but now I am using Gcloud provider and everything seems good so far

**Comment by junweilee** [comment]
> Hi,
> 
> I set [map_public_ip_on_launch = True](https://gitlab.com/itsmeoz/terraform-eks-cluster-deployment/-/blob/ci-integration/vpc.tf#L19), no change.
> 
> As Daniel mentioned above, after [this improvement](https://github.com/aws/containers-roadmap/issues/607) I started getting the error. Besides, I would like to deploy my k8s worker nodes without public IP.
> 
> Best,

Try running `terraform plan` and then `terraform apply`. It worked for me after making that change.

**Comment by bflad** [comment]
The fix to include the `map_public_ip_on_launch = true` argument in `examples/eks-getting-started` has been merged.

**Comment by waynehsei** [comment]
Anyone had the same exception after the new update?
```error waiting for EKS Node Group (terraform-eks-demo:demo) creation: NodeCreationFailure: Instances failed to join the kubernetes cluster.```
