### ISSUE TITLE
aws_wafregional_xss_match_set tuples causing err: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by siassaj** [terraform-providers/terraform-provider-aws#13073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.59.0
+ provider.external v1.2.0
+ provider.local v1.4.0

### Affected Resource(s)

* aws_wafregional_xss_match_set

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~> 2.59"
  region = "ap-southeast-2"
}

resource "aws_wafregional_xss_match_set" "xss_match_set" {
  name = "test-generic-detect-xss"

  xss_match_tuple {
    text_transformation = "HTML_ENTITY_DECODE"

    field_to_match {
      type = "BODY"
    }
  }
}
```

### Debug Output

https://gist.github.com/siassaj/9890b90f349729d3dbcc429914da1435#file-debug-log

### Panic Output

https://gist.github.com/siassaj/9890b90f349729d3dbcc429914da1435#file-crash-log

### Expected Behavior

Create the xss_match_set with the xss_match_tuple

### Actual Behavior

Fail with error
err: rpc error: code = Unavailable desc = transport is closing

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Creating `aws_wafregional_xss_match_set` without `xss_match_tuple` is successful:

```hcl
resource "aws_wafregional_xss_match_set" "xss_match_set" {
  name = "test-generic-detect-xss"
}
```

### References

* #0000

**Comment by ewbankkit** [comment]
@siassaj Thanks for opening this.
This issue has already been raised in #13014 and a fix, https://github.com/terraform-providers/terraform-provider-aws/pull/13024, has already been merged and will be released in the next version of the Terraform AWS Provider.

**Comment by siassaj** [comment]
Thank you for your time!
