### ISSUE TITLE
data provider for security groups

### ISSUE THREAD

**Issue by zerolaser** [terraform-providers/terraform-provider-aws#1313]
I was looking for data provider `aws_security_group` to get the id of the SG just like we have `aws_ami` or `aws_subnet`. 
Is there a specific reason why the data provider `aws_security_group` hasn't been implemented yet or is there an alternative work around ?

**Comment by zerolaser** [comment]
@radeksimko any update on this ?

**Comment by bflad** [comment]
There are two data sources available for EC2 security groups now:
* [`aws_security_group`](https://www.terraform.io/docs/providers/aws/d/security_group.html) (expects single result)
* [`aws_security_groups`](https://www.terraform.io/docs/providers/aws/d/security_groups.html) (allows multiple results)

The latter plural data source was just released in [version 1.25.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1250-june-27-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
