### ISSUE TITLE
ref #12867 and resource/aws_rds_cluster - still a problem with Error: error creating RDS Global Cluster: InvalidParameterValue: Access Denied to API Version: APIGlobalDatabases in 2.60.0

### ISSUE THREAD

**Issue by csakshaug** [terraform-providers/terraform-provider-aws#13163]
I think it is still a issue with this error both in eu-north-1 and in eu-central-1. I have also talked with the gruntwork guys about it.

```
Error: error creating RDS Global Cluster: InvalidParameterValue: Access Denied to API Version: APIGlobalDatabases
        status code: 400, request id: xx
```

### Terraform Version

`Terraform v0.12.24`

### Debug Output

[output](https://gist.githubusercontent.com/csakshaug/f7038a3f055f4fdbffc68c8a629b7293/raw/5d747da18d4ea227435c627742cc5d352b663e46/terraform-rds-global-cluster-error.txt)

### Expected Behavior

Start creating a RDS aurora cluster

### Actual Behavior

Gettings this error in `eu-north-1` (not supported?)
```
Error: error creating RDS Global Cluster: InvalidParameterValue: Access Denied to API Version: APIGlobalDatabases
        status code: 400, request id: xx
```

This error in `eu-central-1`
```
Error: error creating RDS Global Cluster: InvalidParameterValue: The requested engine version was not found or does not support global functionality
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @csakshaug 👋  Thank you for submitting this and sorry you ran into trouble here. These limitations are imposed by the RDS service/API itself and not related to any validation that the Terraform AWS Provider is doing. Please see the [RDS User Guide](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html#aurora-global-database.limitations) for more information about supported engine versions and regions for Global Clusters.
