### ISSUE TITLE
aws_egress_only_internet_gateway does not support import

### ISSUE THREAD

**Issue by anshprat** [terraform-providers/terraform-provider-aws#1319]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)

aws_egress_only_internet_gateway

### Terraform Configuration Files
```hcl
* module.vpc-init.aws_egress_only_internet_gateway.ipv6_egress_igw (import id: eigw-xxx): import module.vpc-init.aws_egress_only_internet_gateway.ipv6_egress_igw (id: eigw-xxx): resource aws_egress_only_internet_gateway doesn't support import
```

**Comment by bflad** [comment]
Support for `aws_egress_only_internet_gateway` resource import has been merged and will release with version 2.46.0 of the Terraform AWS Provider, Thursday next week.
