### ISSUE TITLE
Retry on aws_route when route table exists but no matching destination is found.

### ISSUE THREAD

**Issue by vmorkunas** [terraform-providers/terraform-provider-aws#13201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_route resource sometimes crashes while describing route tables with error (due to aws api latency):

Unable to find matching route for Route Table (rtb-08f8b12546e9e1ed8) and destination CIDR block (0.0.0.0/0).

However most of the cases, it's crashing due to latency in aws api, route is not visible in aws yet and it's trying to read route tables already and crashes without finding it on the first try. If retry would be implemented on this case, this could allow to recover after this error and it won't stop terraform run with an error. (now it just gives an error and doesn't retry)

### New or Affected Resource(s)

* aws_route

### Potential Terraform Configuration

```hcl
resource "aws_route" "source" {
    timeouts {
        create = "5m"
        delete = "5m"
    }

    for_each = {for object in var.routing.src_rt_ids: object.name => object.id}

    **route_table_id = each.value**
    destination_cidr_block = var.routing.dst_cidr
    vpc_peering_connection_id = var.routing.peering_connection_id

}
```

**Comment by ewbankkit** [comment]
@vmorkunas Is this the same as https://github.com/terraform-providers/terraform-provider-aws/issues/13138? If so, could you please close this one and add any additional information to the linked issue.
Thanks.
