### ISSUE TITLE
Route53 PTR Records not deleted on taint

### ISSUE THREAD

**Issue by Gary-Armstrong** [terraform-providers/terraform-provider-aws#13234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20
+ provider.aws v2.61.0
+ provider.template v2.1.2

### Affected Resource(s)
* aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "reverse-private" {
  count   = var.instance-count
  zone_id = var.rev-zone-id

  name = format(
    "%s.%s.%s.%s.in-addr.arpa.",
    element(
      split(
        ".",
        element(aws_instance.instance.*.private_ip, count.index),
      ),
      3,
    ),
    element(
      split(
        ".",
        element(aws_instance.instance.*.private_ip, count.index),
      ),
      2,
    ),
    element(
      split(
        ".",
        element(aws_instance.instance.*.private_ip, count.index),
      ),
      1,
    ),
    element(
      split(
        ".",
        element(aws_instance.instance.*.private_ip, count.index),
      ),
      0,
    ),
  )

  type    = "PTR"
  ttl     = "600"
  records = ["${var.product}-${var.tier}-${var.cluster}-${var.role}-${format("%02d", count.index)}-${var.region}"]
}
```

### Debug Output

https://gist.github.com/Gary-Armstrong/26d1359d3e7b53fecd95fccf855253b4

### Panic Output

None

### Expected Behavior

New Route53 DNS record created and old one deleted permanently.

### Actual Behavior

New Route53 DNS record created and old one either is not deleted or is recreated with previous reverse IP address. Net result is that every taint/recreate cycle leaves behind an undesired DNS record.

Terraform output indicates that the deletion succeeds, so it seems possible the new record is being recreated using the outdated IP address. However, if that is the case, I don't understand how there would be another new record using the correct (new) IP address.

### Steps to Reproduce

1. `terraform taint 'module.master.aws_instance.instance[0]`
2. `terraform taint 'module.master.aws_route53_record.reverse-private[0]'`
3. `terraform apply`

### Important Factoids

I'm not doing anything wacky. Calling a module from a root module.

### References

Did not find any references on GH or StackOverflow.

* #0000

**Comment by bflad** [comment]
Hi @Gary-Armstrong 👋  Thank you for reporting this and sorry you ran into trouble here.

This appears to be similar to https://github.com/terraform-providers/terraform-provider-aws/issues/9024, which has a pending fix https://github.com/terraform-providers/terraform-provider-aws/pull/11335, so to consolidate efforts and discussions I'm going to close this one in preference of the existing items. Please note that they will likely be addressed today.
