### ISSUE TITLE
 data.aws_secretsmanager_secret_version Keeps triggering no-op plan output

### ISSUE THREAD

**Issue by bcomnes** [terraform-providers/terraform-provider-aws#13235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.61.0
+ provider.github v2.6.1

### Affected Resource(s)

* data.aws_secretsmanager_secret_version.*

### Terraform Configuration Files

```hcl
resource "aws_secretsmanager_secret" "service_gh_pat" {
  name        = "service_gh_pat"
  description = "Shared Github PAT from l12s-bot account with just the REPO scope."
}

data "aws_secretsmanager_secret_version" "service_gh_pat" {
  secret_id  = "service_gh_pat"
  depends_on = [aws_secretsmanager_secret.service_gh_pat]
}

locals {
  service_gh_pat = jsondecode(data.aws_secretsmanager_secret_version.service_gh_pat.secret_string)["GH_MACHINE_TOKEN"]
}
```

### Debug Output

https://gist.github.com/bcomnes/dc2803f9c6f559611824cdf7ab589f21

### Expected Behavior

I would expect the other resources that rely on the secret value output to not show up in the plan if the secret value hasn't changed.

### Actual Behavior

During the plan, all resources that rely on the secret value output are always marked for changes, even though nothing ends up chaining when you apply when the value hasn't changed. 

### Steps to Reproduce

Read a value out of the secret manager, and use it in another resource.  Make sure everything is fully applied then run 

1. `terraform plan`

You will see, despite nothing changing, the resource is marked for changes.

### References

* #0000

**Comment by andrzej-jedrzejewski** [comment]
I have the same issue......Plan looks terrible if you have a lot of secrets........

**Comment by bcomnes** [comment]
I fixed this and should have closed this.

> However, due to the data resource behavior of deferring the read until the apply phase when depending on values that are not yet known, using depends_on with data resources will force the read to always be deferred to the apply phase, and therefore a configuration that uses depends_on with a data resource can never converge.

https://www.terraform.io/docs/configuration/data-sources.html

A depends_on in a data source causes the data source to always be stale.
