### ISSUE TITLE
bad name used in example

### ISSUE THREAD

**Issue by xdfil** [terraform-providers/terraform-provider-aws#13242]
https://registry.terraform.io/providers/hashicorp/aws/2.61.0/docs/resources/nat_gateway#example-usage

We are using the subnet name `public`, that can cause confusion because the term "public" is used in AWS documentation to describe subnets that **do not** use an `aws_nat_gateway`. 

```
resource "aws_nat_gateway" "gw" {
  allocation_id = "${aws_eip.nat.id}"
  subnet_id     = "${aws_subnet.public.id}"
}
```

**Comment by bflad** [comment]
Hi @xdfil 👋 Thank you for filing this. If you or anyone is interested in updating the documentation file, it can be found at: [`website/docs/r/nat_gateway.html.markdown`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/nat_gateway.html.markdown)
