### ISSUE TITLE
Terraform MSK: Unsupported block type logging

### ISSUE THREAD

**Issue by Ycallaer** [terraform-providers/terraform-provider-aws#13255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.20

### Affected Resource(s)

* aws_msk_cluster

### Expected Behavior

When specifying the block logging_info, we should be able to specify how we want logging to happen (as per documentation: https://www.terraform.io/docs/providers/aws/r/msk_cluster.html)

### Actual Behavior

```hcl
Error: Unsupported block type

  on .terraform/modules/kafka-msk/main.tf line 33, in resource "aws_msk_cluster" "msk_cluster":
  33:   logging_info {

Blocks of type "logging_info" are not expected here.

```

### Steps to Reproduce

Follow the example code on https://www.terraform.io/docs/providers/aws/r/msk_cluster.html
The moment you specify the logging_block the code fails

**Comment by bflad** [comment]
Hi @Ycallaer 👋 Thank you for submitting this and sorry you ran into trouble here. That functionality was recently added in [version 2.55.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2550-march-27-2020). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

Regarding the resource documentation itself -- please note that the documentation on terraform.io is only relevant for the most recent version of the provider. To view version specific documentation (which will made the default in the coming months), you can browse the [Terraform Registry documentation](https://registry.terraform.io/providers/hashicorp/aws/). 👍 

Hope this helps.
