### ISSUE TITLE
Github Submodule support for aws_codebuild_project

### ISSUE THREAD

**Issue by raobystorm** [terraform-providers/terraform-provider-aws#13254]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For our project we need to fetch git submodules in codebuild.
But I found current code does only support CodeCommit for this option.
Since CodeBuild does support github for fetching submodules, I couldn't find a reason why this hasn't been implemented.
If no reason this couldn't be done I will try to fix by myself :)

### New or Affected Resource(s)

* resource_aws_codebuild_project.go

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_project.go#L1051
```
	if sourceType == codebuild.SourceTypeCodecommit {
		if v, ok := data["git_submodules_config"]; ok && len(v.([]interface{})) > 0 {
			config := v.([]interface{})[0].(map[string]interface{})

			gitSubmodulesConfig := &codebuild.GitSubmodulesConfig{}

			if v, ok := config["fetch_submodules"]; ok {
				gitSubmodulesConfig.FetchSubmodules = aws.Bool(v.(bool))
			}

			projectSource.GitSubmodulesConfig = gitSubmodulesConfig
		}
	}
```

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

  source {
    type                = "GITHUB"
    buildspec           = "XXX"
    location            = "XXX"
    auth {
      type = "OAUTH"
    }
    git_submodules_config {
      fetch_submodules = true
    }
```

### References

* #0000

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.62.0 of the Terraform AWS Provider, later this week. Thanks to @raobystorm for the implementation. 👍
