### ISSUE TITLE
Api Gateway V2 (Web Sockets) Integration error on re-apply

### ISSUE THREAD

**Issue by mcqj** [terraform-providers/terraform-provider-aws#13261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.24
provider.aws v2.61.0

### Affected Resource(s)

"aws_apigatewayv2_integration"

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_integration" "message-int" {
  api_id = aws_apigatewayv2_api.websocket.id
  integration_type = "AWS_PROXY"
  integration_uri = aws_lambda_function.message.invoke_arn
#  passthrough_behavior = "WHEN_NO_MATCH"
}
```

### Expected Behavior
No error on modification

### Actual Behavior
Error on modification/
When run in a clean environment, the integration is created correctly and runs as expected.
However, if *any* change is made to the terraform config, attempting to re-apply results in the following error.
```
Error: error updating API Gateway v2 integration: BadRequestException: Invalid HttpMethod specified. Valid options are GET,PUT,POST,DELETE,PATCH,OPTIONS,HEAD,ANY
```
As this is a websockets API, the reference to HTTP methods is hard to fathom.

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@mcqj Thanks for raising this. I can reproduce and will address with a PR.
As a workaround, you should be able to explicitly set

```hcl
integration_method = "POST"
```

**Comment by mcqj** [comment]
Thanks @ewbankkit - I can confirm that the workaround solved the issue.
