### ISSUE TITLE
provider "api" not available for installation

### ISSUE THREAD

**Issue by T00mm** [terraform-providers/terraform-provider-aws#13283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
0.12.24
```

### Affected Resource(s)

* "aws" (hashicorp/aws) 2.61.0
* api_gateway_stage

### Terraform Configuration Files

```hcl
resource "api_gateway_stage" "default" {
stage_name = "dev"
rest_api_id = aws_api_gateway_rest_api.default.id
deployment_id = aws_api_gateway_deployment.default.id
xray_tracing_enabled = true
}
```

### Debug Output

```
provider "api" not available for installation.·
   A provider named "api" could not be found in the Terraform Registry.
```
### Expected Behavior

No provider API is needed, the initialization should succeed.

### Actual Behavior

Terraform fails on init as it can't download this provider.

### Steps to Reproduce

1. `terraform init`

### Important Factoids

No

**Comment by DrFaust92** [comment]
Change to "aws_api_gateway_stage"

**Comment by DrFaust92** [comment]
hey @T00mm , are you still having an issue or can we close this?

**Comment by T00mm** [comment]
No, your suggestion helped! Thanks
