### ISSUE TITLE
Support force update of EKS managed node groups

### ISSUE THREAD

**Issue by zlangbert** [terraform-providers/terraform-provider-aws#13296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When updating the release version of an EKS managed node groups in the console there is an option to force the update. As described [here](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-update-behavior.html), this will forcefully delete any pods after 15 minutes that were not able to be drained. Currently this parameter is [hard-coded to false](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_node_group.go#L377), it would be great to be able to specify this in the configuration.

Specifically in my case I am trying to work around this Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/72320

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_eks_node_group" "example" {
  cluster_name    = aws_eks_cluster.example.name
  node_group_name = "example"
  force_update = true
  ...
}
```

**Comment by bflad** [comment]
Support for a new `force_update_version` argument in the `aws_eks_node_group` resource has been merged and will release with version 2.63.0 of the Terraform AWS Provider, likely later today. 👍
