### ISSUE TITLE
aws_flow_log - "tags" is not expected here

### ISSUE THREAD

**Issue by klucks83** [terraform-providers/terraform-provider-aws#13307]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20

### Affected Resource(s)

* provider.aws v2.50.0

### Terraform Configuration Files

```hcl

resource "aws_flow_log" "vpc_flow_logs" {
  iam_role_arn    = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/flow-logs-role"
  log_destination = aws_cloudwatch_log_group.vpc_flow_logs.arn
  traffic_type    = "ALL"
  vpc_id          = aws_vpc.vpc.id
  tags = merge(map(
    "Name", "VPC Flow Logs",
  ), var.tags)
}

```

### Expected Behavior

Documentation says tags should work.  https://www.terraform.io/docs/providers/aws/r/flow_log.html

### Actual Behavior

Error: Unsupported argument

  on vpc.tf line 131, in resource "aws_flow_log" "vpc_flow_logs":
 131:   tags = merge(map(

An argument named "tags" is not expected here.

### Steps to Reproduce

$ terraform validate

### References

* #0000

**Comment by bflad** [comment]
Hi @Ycallaer 👋 Thank you for submitting this and sorry you ran into trouble here. That functionality was recently added in [version 2.53.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2530-march-12-2020). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

Regarding the resource documentation itself -- please note that the documentation on terraform.io is only relevant for the most recent version of the provider. To view version specific documentation (which will made the default in the coming months), you can browse the [Terraform Registry documentation](https://registry.terraform.io/providers/hashicorp/aws/). 👍 

Hope this helps.
