### ISSUE TITLE
AWS WAF regional support

### ISSUE THREAD

**Issue by unk1nd0n3** [terraform-providers/terraform-provider-aws#1333]
Hi there,

please add support of AWS regional WAF (ACLs, Rule and related constrains)

### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_waf_web_acl
- aws_waf_web_rule

**Comment by joshma** [comment]
FYI, it looks like there was work in progress but the author ran out of time:

https://github.com/hashicorp/terraform/pull/13707
https://github.com/hashicorp/terraform/pull/13708
https://github.com/hashicorp/terraform/pull/13709
https://github.com/hashicorp/terraform/pull/13710
https://github.com/hashicorp/terraform/pull/13711
https://github.com/hashicorp/terraform/pull/13712

**Comment by tomgoren** [comment]
Does anyone have any plans of ever working on this?

It would be a very useful addition. Thank you!

**Comment by giuliocalzolari** [comment]
It would be awesome to have waf regional. 
they just extend to two new regions Frankfurt and Sydney

https://aws.amazon.com/about-aws/whats-new/2018/01/aws-shield-advanced-and-aws-waf-now-available-in-asia-pacific-sydney-and-eu-frankfurt-regions/

most of the job is already done in a PR
https://github.com/terraform-providers/terraform-provider-aws/pull/1753

Thank you!

**Comment by cemo** [comment]
AWS WAF related PR's are targeted to [v1.12.0]. @bflad It maybe be targeted an earlier milestone.

[v1.12.0]: https://github.com/terraform-providers/terraform-provider-aws/milestone/14

**Comment by radeksimko** [comment]
Hi folks 👋 
as @cemo mentioned [`v1.12.0`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018) (latest release) does contain a number of WAF Regional resources and all the remaining resources will be part of [`v1.13.0`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-unreleased) (upcoming release).

For that reason I'm going to close this issue. If there's anything missing or you find a bug in those resources (or existing WAF Regional resources) please open a new issue for these and we can take a look.

Thanks!
