### ISSUE TITLE
Firehose kinesis & elaastic support VpcConfiguration

### ISSUE THREAD

**Issue by ddiawara** [terraform-providers/terraform-provider-aws#13379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by ewbankkit** [comment]
@ddiawara Thanks for raising this.
It's a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/13015, which is being addressed via https://github.com/terraform-providers/terraform-provider-aws/pull/13269.
Could you please close this issue.

**Comment by ddiawara** [comment]
thanks
