### ISSUE TITLE
Amazon Kinesis Data Analytics applications can access resources in VPCs

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#13386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now enable your Amazon Kinesis Data Analytics for Java applications to access resources within your Amazon Virtual Private Cloud (Amazon VPC).

### New or Affected Resource(s)

* [`aws_kinesis_analyticsv2_application`](https://github.com/terraform-providers/terraform-provider-aws/pull/11652)

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_analyticsv2_application" "example" {
    vpc_configuration {
    }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/access-resources-within-your-amazon-virtual-private-cloud-using-amazon-kinesis-data-analytics/).

**Comment by bobtiernay-okta** [comment]
This would be useful for a lot of use cases I would assume. Looking forward to it being supported.

**Comment by bobtiernay-okta** [comment]
Also, for visibility, might be helpful to add the https://github.com/terraform-providers/terraform-provider-aws/labels/service%2Fkinesisanalytics label.

**Comment by ewbankkit** [comment]
I will tackle this after #11652 is merged.
