### ISSUE TITLE
Remove Deprecated Attributes and Code for Removed Attributes

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since the last major release we have deprecated different fields due to changes in the corresponding APIs or fields that did not end up being used.  As this deprecation phase is now complete, it is now time to remove these fields entirely. 

The Terraform SDK v2.0 (with which 3.0 takes as a dependency update) also removes the `Removed` attribute from the schema entirely [SDK #414](https://github.com/hashicorp/terraform-plugin-sdk/pull/414). We will need to remove all usages of that attribute along with any code it currently adorns.

### Practioner Impact

- Attributes marked as `deprecated` which previously emitted warnings when used will now emit an `Unsupported Argument` error.
- Attributes marked as `removed` which previously emitted an error detailing that the attribute was removed and what attribute to use instead will now emit a generic `Unsupported Argument` error.

### References

* [SDK #414](https://github.com/hashicorp/terraform-plugin-sdk/pull/414)

**Comment by bflad** [comment]
### Affected Resources

* [provider `kinesis_analytics` and `r53` endpoints](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/provider.go#L1270-L1272)
* [`aws_api_gateway_method` resource `request_parameters_in_json` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_api_gateway_method.go#L93-L97)
* [`aws_cognito_user_pool` resource `admin_create_user_config` configuration block `unused_account_validity_days` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_cognito_user_pool.go#L66-L73)
* Remove just this line (the attribute must be present in the state upgrade schema!): https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_dx_gateway_association_migrate.go#L72
* [`aws_dx_gateway_association` resource `vpn_gateway_id` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_dx_gateway_association.go#L92-L98)
* [`aws_dx_gateway_association_proposal` resource `vpn_gateway_id` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_dx_gateway_association_proposal.go#L70-L76)
* `aws_emr_cluster` resource `master_instance_type`, `core_instance_type`, `core_instance_count`, `instance_group`
* [`aws_flow_log` resource `log_group_name` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_flow_log.go#L57-L64)
* [`aws_glue_job` resource `allocated_capacity` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_glue_job.go#L26-L33)
* [`aws_iam_access_key` resource `ses_smtp_password` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_iam_access_key.go#L45-L50)
* [`aws_iam_instance_profile` resource `roles` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_iam_instance_profile.go#L73-L81)
* [Various schema handling within `aws_lb_listener_rule` resource `condition` configuration block](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_lb_listener_rule.go#L286-L431)
* `aws_ssm_maintenance_window_task` resource [`logging_info` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_ssm_maintenance_window_task.go#L95-L117) and [`task_parameters` attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_ssm_maintenance_window_task.go#L119-L137)

**Comment by bflad** [comment]
I'm going to leave the `aws_flow_log` resource `log_group_name` removal out of this major release. It appears the API will not automatically convert a flow log created with `LogGroupName` to also populate `LogDestination`. See also [EC2 API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeFlowLogs.html#API_DescribeFlowLogs_Examples) / #12502. We could try to "guess" the correct ARN value if `LogDestination == nil` but that could require knowing information the provider may not always have access to (e.g. the account ID portion of the ARN). 😖  We can followup with the EC2 service team to see if they plan on populating that information at some point.

The rest of the removals are awaiting team review.

**Comment by bflad** [comment]
All set, except `aws_flog_log` as mentioned above. 👍

**Comment by SJM-J2** [comment]
I am getting the following all over on out stacks.. any input on how to remedy would be GREATLY appreciated

This is the ONLY page I can find on google for this right now

Error: Invalid resource instance data in state

  on ../../tf_modules/api_gateway_resource/api_gateway_resource.tf line 51:
  51: resource "aws_api_gateway_method" "this_method" {

Instance module.api_resource_history.aws_api_gateway_method.this_method["ANY"]
data could not be decoded from the state: unsupported attribute
"request_parameters_in_json".

**Comment by bflad** [comment]
Please post additional information in https://github.com/hashicorp/terraform/issues/25752 -- the maintainers of the Terraform AWS Provider are not sure if anything can be done within this codebase to fix the underlying issue at this time.

**Comment by khaledavarteq** [comment]
> I am getting the following all over on out stacks.. any input on how to remedy would be GREATLY appreciated
> 
> This is the ONLY page I can find on google for this right now
> 
> Error: Invalid resource instance data in state
> 
> on ../../tf_modules/api_gateway_resource/api_gateway_resource.tf line 51:
> 51: resource "aws_api_gateway_method" "this_method" {
> 
> Instance module.api_resource_history.aws_api_gateway_method.this_method["ANY"]
> data could not be decoded from the state: unsupported attribute
> "request_parameters_in_json".
> 
> We aren't using that param at all, so no clue how to remove it and make state work again

@SJM-J2 I've had a similar issue. You may try this: remove any reference to the data source and execute `terraform plan`, then re-add the references to the data source and execute `terraform plan` again. HTH.
