### ISSUE TITLE
Only Retry on Expected Errors

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Switch any retrying logic that retries on any error (usually written as any AWS Go SDK error) to only retry on specific errors. Retrying on any error means that the Terraform resource can potentially retry on unresolvable conditions, such as credential expiration, resource disappearance, etc.

**Comment by bflad** [comment]
### Affected Resources

* [`aws_appautoscaling_target`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_appautoscaling_target.go#L172-L175)
* [`aws_codepipeline`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_codepipeline.go#L198-L200)
* [`aws_launch_configuration`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_launch_configuration.go#L512-L514)
* [`aws_network_acl_rule`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_network_acl_rule.go#L200-L202)
* [`aws_route`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_route.go#L287-L292) ([also](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_route.go#L307-L312))
* [`aws_sns_topic_subscription`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_sns_topic_subscription.go#L243-L246)
* [`aws_ssm_activation`](https://github.com/terraform-providers/terraform-provider-aws/blob/19e07b2d9e8fc8f52bb1d773766495f58a20b8b2/aws/resource_aws_ssm_activation.go#L110-L112)

**Comment by bflad** [comment]
Final two PRs pending team review: https://github.com/terraform-providers/terraform-provider-aws/pull/14259 / https://github.com/terraform-providers/terraform-provider-aws/pull/14262

**Comment by bflad** [comment]
All set. 👍
