### ISSUE TITLE
Remove Multiple Resource Imports

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform Plugin SDK supports importing the state of multiple resources in `helper/schema.Resource.Importer.State` functions. These new additional resources imported cannot have their state references controlled by the practitioner, risking API deletion in the next Terraform run unless the Terraform configuration is carefully updated to match the secondary resource import structure. This is a tedious and error prone process, especially for newer practitioners. Terraform may also not have access to these secondary resources during import, returning unexpected and unavoidable errors. Given all this, practitioners have come to expect that Terraform resource imports only do the resource given.

### Practitioner Impact

- Imports will behave differently for the affected resources.

### References

* #394
* #6036
* #6552
* #9001
* #9508
* #10095

**Comment by bflad** [comment]
## Affected Resources

- `aws_dx_gateway_association`
- `aws_s3_bucket`
- `aws_security_group`

**Comment by anGie44** [comment]
closing since the referenced resources and their respective PRs are now merged
