### ISSUE TITLE
Remove Hashing from State Storage

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13406]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hashing schema attribute values in the Terraform state storage was implemented as a workaround for attribute-level encryption of some sensitive values. However, Terraform is designed to work with wholly known values during resource operations and performing differences. For example, if a resource only saves a hashed value in the state, during update operations the resource will incorrectly send the hashed value in API operations.

To remove the hashing from resources, any StateFunc must be replaced with a DiffSuppressFunc that does not show a difference between the whole value and the hashed value. State migration is not possible since the previous state value is only the hash of the real value, however any configured values that omit setting the state explicitly via (helper/schema.ResourceData).Set(), should implicitly update the state value with the configuration value on first refresh.

### References

* [Terraform #516](https://github.com/hashicorp/terraform/issues/516)
* [Terraform #9556](https://github.com/hashicorp/terraform/issues/9556)
* #3894 
* #7401
* #9685 
* #10847
* #10849

**Comment by bflad** [comment]
### Affected Resources

* `aws_acm_certificate`: `certificate_body`, `certificate_chain`, `private_key`
* `aws_iam_server_certificate`: `certificate_body`, `certificate_chain`, `private_key`
* `aws_sns_platform_application`: `platform_credential`, `platform_principal`

These attributes need separate discussion and should probably remain out of scope:

* `aws_instance`: `user_data`
* `aws_launch_configuration`: `user_data`
* `aws_spot_fleet_request`: `user_data`

### Other References

* https://github.com/terraform-providers/terraform-provider-aws/pull/1740

**Comment by bflad** [comment]
All set with `aws_sns_platform_application` -- will work on `aws_acm_certificate` and `aws_iam_server_certificate` later today or tomorrow using the community contributions where possible.

**Comment by bflad** [comment]
Final PR pending team review: https://github.com/terraform-providers/terraform-provider-aws/pull/14187
