### ISSUE TITLE
Ensure All Singular Data Sources Return Errors on Zero Results

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For consistency, all Terraform AWS Provider data sources that are expected to return a single result should error if that result is not found. Terraform can have undefined behaviors when this condition occurs and many practitioners now expect these errors.

### References

* #10071
* #10520 
* #10521

**Comment by bflad** [comment]
## Affected Data Sources

* `aws_directory_service_directory` (`return nil` usage)
* `aws_ecr_repository` (`return nil` usage)
* `aws_efs_file_system` (`return nil` usage)
* `aws_launch_template` (`return nil` usage)

**Comment by anGie44** [comment]
closing as affected data sources have been updated and changes will be released with `v3.0.0` of the Provider.
