### ISSUE TITLE
One of examples on aws_sns_topic_subscription doc is not working

### ISSUE THREAD

**Issue by pei-lun** [terraform-providers/terraform-provider-aws#1342]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
- aws_sns_topic_subscription

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_sns_topic" "user_updates" {
  name = "user-updates-topic"
}

resource "aws_sqs_queue" "user_updates_queue" {
  name = "user-updates-queue"
}

resource "aws_sns_topic_subscription" "user_updates_sqs_target" {
  topic_arn = "${aws_sns_topic.user_updates.arn}"
  protocol  = "sqs"
  endpoint  = "${aws_sqs_queue.user_updates_queue.arn}"
}
```

### Debug Output
https://gist.github.com/pei-lun/a820a0335cbf8e7a97c45581ce80622f

### Expected Behavior
The created SQS queue can receive messages published to the created SNS topic.

### Actual Behavior
The created SQS queue can not receive messages published to the created SNS topic.

### Steps to Reproduce
1. `terraform apply`
2. Publish message to the created SNS topic via AWS CLI or via console.

### Important Factoids
The AWS account using terraform is attached with AdministratorAccess policy.

The SQS queue can receive messages after adding the following aws_sqs_queue_policy configuration.

```hcl
resource "aws_sqs_queue_policy" "user_updates_queue_policy" {
    queue_url = "${aws_sqs_queue.user_updates_queue.id}"

    policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": "*",
    "Action": "sqs:SendMessage",
    "Resource": "${aws_sqs_queue.user_updates_queue.arn}",
    "Condition": {
      "ArnEquals": {
        "aws:SourceArn": "${aws_sns_topic.user_updates.arn}"
      }
    }
  }]
}
POLICY
}
```

**Comment by dedamico** [comment]
this doc page now has a full example of "You can subscribe SNS topics to SQS queues in different Amazon accounts and regions:" including the aws_sqs_queue_policy configuration.
