### ISSUE TITLE
AWS Transit Virtual Interfaces, directconnect/describetags fails with missing account ID

### ISSUE THREAD

**Issue by MichaelSweikata** [terraform-providers/terraform-provider-aws#13461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v

Terraform v0.12.13
+ provider.archive v1.3.0
+ provider.aws v2.60.0
+ provider.vault v2.10.0

### Affected Resource(s)

AWS Direct Connects for the Transit Virtual Interface:

aws_dx_transit_virtual_interface

### Terraform Configuration Files

Example terraform code files: https://gist.github.com/MichaelSweikata/07b6bd2414af3a63b9c868cc27df3a32

### Debug Output

Trace level debug on the execution: https://gist.github.com/MichaelSweikata/54ce7dcc29e52dcaad2b8e810fbec99d

### Expected Behavior

The terraform plan being able to complete successfully.

### Actual Behavior

When executing the terraform plan, the ARN format is not constructed correctly:

```Error: error listing tags for Direct Connect transit virtual interface (arn:aws:directconnect:us-east-1::dxvif/dxvif-fguyo2xb): DirectConnectClientException: Invalid ARN format: arn:aws:directconnect:us-east-1::dxvif/dxvif-fguyo2xb```

The ARN structure is missing the account ID:

arn:aws:directconnect:us-east-1::dxvif/dxvif-fguyo2xb

When I examine the statefile, the ARN value is correct:

https://gist.github.com/MichaelSweikata/c59fccbb01b9d34db23c9e8c9f0b7078

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The state file is stored remotely in an S3 bucket. When I do a brand new state file and build, there is no issue, but using the existing state file in the remote S3 bucket, it fails.

The actual line of code that looks like it might be having an issue? https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_dx_transit_virtual_interface.go#L177

If I run this without existing resources, it builds correctly.

I'm not sure if there's anything else I can provide, or in a better format to help with?

**Comment by ewbankkit** [comment]
@MichaelSweikata Thanks for raising this issue.
How are you configuring the credentials for the AWS provider?

**Comment by MichaelSweikata** [comment]
@ewbankkit I'm issued a local credential token under the [default] value for access and secret keys. They're tied to my personal IAM role, and it hasn't expired. 

When I run this plan, it's not just specifically to this resource (other things like the direct connect gateway, transit gateway, etc.). 

Under the same token, if I build new, it works.

**Comment by MichaelSweikata** [comment]
I believe that there is an issue with the AWS provider version 2.58 that had this resolved in version 2.6. Our usage was under 2.58:

> ├── provider.aws >= 2.58

I get the error:
> Error: error listing tags for Direct Connect transit virtual interface (arn:aws:directconnect:us-east-1::dxvif/dxvif-fguyo2xb): DirectConnectClientException: Invalid ARN format: arn:aws:directconnect:us-east-1::dxvif/dxvif-fguyo2xb

But, if I drop the specific version, it downloads 2.60

> │   ├── provider.aws 2.60

No issue.

**Comment by ewbankkit** [comment]
@MichaelSweikata Thanks for noticing that the documentation is out of date. I'll make sure that the list of resources affected by `skip_requesting_account_id` is up-to-date.
