### ISSUE TITLE
Provide way to update launch configuration (i.e., new ami) without destroying autoscale group or creating a new one

### ISSUE THREAD

**Issue by sean-abbott** [terraform-providers/terraform-provider-aws#1348]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_launch_configuration
- aws_autoscale_group

### Terraform Configuration Files
```hcl
data "aws_ami" "sem_latest" {
  most_recent = true

  filter {
    name   = "name"
    values = ["sem*"]
  }

  owners = ["*************"]
}

data "template_file" "sem_autoscale_script" {
  # the consulhost needs to be var-i-fied
  template = "${file("templates/sem_autoscale_cloudinit.tpl")}"
}

data "template_cloudinit_config" "sem_autoscale" {
  gzip          = false
  base64_encode = false

  part {
    filename     = "init.cfg"
    content_type = "text/cloud-config"
    content      = "${data.template_file.sem_autoscale_script.rendered}"
  }
}

resource "aws_launch_configuration" "semfake_medium" {
  name          = "semfake-medium"
  image_id      = "${data.aws_ami.sem_latest.id}"
  instance_type = "m4.xlarge"
  spot_price    = "0.07"
  user_data     = "${data.template_cloudinit_config.sem_autoscale.rendered}"
  key_name      = "cg_aws_sem"
}

resource "aws_autoscaling_group" "sem_semfake_medium" {
  launch_configuration = "${aws_launch_configuration.semfake_medium.name}"
  max_size             = 10
  min_size             = 1
  vpc_zone_identifier  = ["${data.terraform_remote_state.base.lan20_pub_id}"]

  tags = [{
    key                 = "role"
    value               = "torque_compute_node_semfake"
    propagate_at_launch = true
  }]
}
```

### Debug Output
Not a bug; advice or improved functionality request

### Panic Output
N/A

### Expected Behavior
I would really like terraform to be smart enough in this situation to follow a workflow that makes sense:
* create new launch config
* update autoscale group to use new launch config
* delete old launch config

### Actual Behavior
The launch config cannot be deleted because the autoscale group uses it. So I have to take two or more manual steps to change the AMI I use with an autoscale group, and I can't use the filters to make the choie of AMI anymore.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
N/A

**Comment by trung** [comment]
I think it's already there, have a look at https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

> Launch Configurations cannot be updated after creation with the Amazon Web Service API. In order to update a Launch Configuration, Terraform will destroy the existing resource and create a replacement. In order to effectively use a Launch Configuration resource with an AutoScaling Group resource, it's recommended to specify `create_before_destroy` in a lifecycle block. Either omit the Launch Configuration name attribute, or specify a partial name with `name_prefix`

**Comment by sean-abbott** [comment]
So it does, perfect, thank you so much!
