### ISSUE TITLE
AWS site to site VPN tunnel values reversed

### ISSUE THREAD

**Issue by thornowly** [terraform-providers/terraform-provider-aws#13487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version. 

Terraform v0.12.24
+ provider.aws v2.61.0

### Affected Resource(s)

* aws_vpn_connection

### Terraform Configuration Files

```
resource "aws_vpn_connection" "vpn" {
  customer_gateway_id = aws_customer_gateway.cgw.id
  transit_gateway_id  = var.tgw_id
  type                = aws_customer_gateway.cgw.type
  tunnel1_inside_cidr = "169.254.250.12/30"
  tunnel2_inside_cidr = "169.254.250.16/30"
  tunnel1_preshared_key = "tunnel1PSK"
  tunnel2_preshared_key = "tunnel2PSK"
}

resource "aws_customer_gateway" "cgw" {
  bgp_asn    = 64512
  type       = "ipsec.1"
  ip_address = aws_eip.publicEIP.public_ip
}
```
All code can be found at: https://github.com/thornowly/aws-transit-gateway-panfw 
there are a lot of dependant parts.

### Expected Behavior

Site to site VPN in AWS is configured with two tunnels
Tunnel 1 should be configured with the tunnel1_inside_cidr as detailed in the .tf file
Tunnel 2 should be configured with the tunnel2_inside_cidr as detailed in the .tf file

### Actual Behavior

The configuration of the VPN tunnels appears random. 
Occasionally it's configured correctly, often the Tunnel 1 CIDR is configured under Tunnel 2 and vice versa.

`terraform show `
displays the values as expected
```
    tunnel1_cgw_inside_address     = "169.254.250.18"
    tunnel1_inside_cidr            = "169.254.250.12/30"
    tunnel1_preshared_key          = (sensitive value)
    tunnel1_vgw_inside_address     = "169.254.250.17"
    tunnel2_cgw_inside_address     = "169.254.250.14"
    tunnel2_inside_cidr            = "169.254.250.16/30"
    tunnel2_preshared_key          = (sensitive value)
    tunnel2_vgw_inside_address     = "169.254.250.13"
    type                           = "ipsec.1"
```

The AWS console and AWS configuration is often reversed with tunnel 2 configured with tunnel 1 values.

### Steps to Reproduce

1. Configure aws transit gateway with a VPN attachment using Terraform code.
2. `terraform apply`
3. Apply is successful
4. Check IPsec VPN configuration in AWS (Console --> VPC --> Site-to-Site-VPN Connections --> Select the connection --> Select tab "Tunnel Details")
5. Compare the tunnel 1 configuration (outside IP address & inside IP address) and compare those values to the Terraform config and state.

### Important Factoids

The AWS environment is typical of most environments.

### References

* #0000

**Comment by ewbankkit** [comment]
@thornowly Thanks for raising this issue.
It has already been noticed in #396. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
