### ISSUE TITLE
aurora major upgrade - AllowMajorVersionUpgrade non-applicable for Aurora 

### ISSUE THREAD

**Issue by azhurbilo** [terraform-providers/terraform-provider-aws#13490]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

aws_rds_cluster

### Terraform Configuration Files

change "engine_version" from 9.6.12 -> 10.11

### Expected Behavior

Upgrade success

### Actual Behavior

Error

```
Error: Failed to modify RDS Cluster (aurora-XXX-test): InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.
	status code: 400, request id: f960fd8b-d24a-4124-8177-81cea45ab150
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Modifying.html#Aurora.Modifying.SettingsNotApplicable

The AWS Management Console doesn't allow you to modify these settings for Aurora

"AllowMajorVersionUpgrade"

**Comment by bflad** [comment]
Support for the `allow_major_version_upgrade` argument in the `aws_rds_cluster` resource has been merged and will release with version 3.8.0 of the Terraform AWS Provider, later this week. 👍
