### ISSUE TITLE
Add 'snapshot_tags' attribute to 'aws_ami_from_instance' resource

### ISSUE THREAD

**Issue by GeorgiSK** [terraform-providers/terraform-provider-aws#13493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm using terraform version "0.12.13" and aws provider version "2.41.0". When I create an AMI using aws_ami_from_instance resource, a snapshot is also created which can only be linked to the created AMI by it's description which mentions the AMI-ID. However if the AMI gets deregistered later, the snapshot is hard to identify. Hence adding support for setting snapshot tags when using the aws_ami_from_instance resource will be very useful

### New or Affected Resource(s)

* aws_ami_from_instance

### Potential Terraform Configuration

```hcl
resource "aws_ami_from_instance" "ami" {
  name = "SomeName"
  source_instance_id = "i-kmlkn34j5kn345dlsfkgmk345"

  tags = "${var.tags}"
  snapshot_tags = "${var.snapshot_tags}"
}
```

### References

* #0000

**Comment by bflad** [comment]
A new `aws_ec2_tag` resource for managing individual EC2 resource tags has been merged and will release with version 2.67.0 of the Terraform AWS Provider, later next week. This resource should help in this case, for example:

```hcl
# Example configuration in Terraform 0.12 and later syntax
resource "aws_ami_from_instance" "example" {
  name               = "example"
  source_instance_id = aws_instance.example.id
}

resource "aws_ec2_tag" "example" {
  resource_id = aws_ami_from_instance.example.root_snapshot_id
  key         = "Name"
  value       = "Hello World"
}
```

As with any Terraform 0.12.6 or later configuration, this resource can be combined with [`for_each` support](https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings) to manage multiple resource tags, if necessary.
