### ISSUE TITLE
Route53 Zone: Remove extraneous trailing period in `name` attribute

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Route53 API normalizes `name` in addition to `fqdn` in values to include a trailing period in this value. Many downstream APIs do not support the trailing period, which requires various workarounds in other resources. Currently, in the provider, the `fqdn` attribute already is returned with the trailing period removed, however, `name` and `domain_name` (used in other route53 resources) do not.

### New or Affected Resource(s)

* aws_route53_zone

**Comment by bflad** [comment]
Related: https://github.com/terraform-providers/terraform-provider-aws/issues/7501

**Comment by anGie44** [comment]
Related #3836
