### ISSUE TITLE
aws_ebs_volume forces new resource due to interpolated availability_zone variable

### ISSUE THREAD

**Issue by CpuID** [terraform-providers/terraform-provider-aws#1352]
### Terraform Version

Terraform v0.9.9

### Affected Resource(s)

- aws_ebs_volume
- aws_volume_attachment

### Terraform Configuration Files

```hcl
resource "aws_volume_attachment" "elasticsearch1-sdf-att" {
  device_name = "/dev/sdf"
  volume_id = "${aws_ebs_volume.elasticsearch1-sdf-vol.id}"
  instance_id = "${aws_instance.elasticsearch1.id}"
}

resource "aws_ebs_volume" "elasticsearch1-sdf-vol" {
  availability_zone = "${aws_instance.elasticsearch1.availability_zone}"
  size = 20
  type = "gp2"

  tags {
    Name = "elasticsearch1 VG ebs-xvdf"
    cluster = "elasticsearch"
  }
}

resource "aws_instance" "elasticsearch1" {
    ami = "${lookup(var.elasticsearch_aws_source_ami, var.region)}"
    instance_type = "i3.xlarge"

    subnet_id = "${var.subnet["1a"]}"
    vpc_security_group_ids = [ "${var.sg["default"]}" ]
    placement_group = "${aws_placement_group.log-ingest-e1a.id}"

    iam_instance_profile = "Elasticsearch"

    tags {
      Name = "elasticsearch1"
      cluster = "elasticsearch"
    }
}
```

### Debug Output

Can be provided on request.

### Panic Output

No panic, just unintended `plan` results.

### Expected Behavior

The `aws_ebs_volume` resource should have been detected and retained (already exists in tfstate), and no attempt made to force recreate.

### Actual Behavior

```
-/+ aws_ebs_volume.elasticsearch1-sdf-vol
    availability_zone: "us-east-1a" => "${aws_instance.elasticsearch1.availability_zone}" (forces new resource)
    encrypted:         "false" => "<computed>"
    iops:              "" => "<computed>"
    kms_key_id:        "" => "<computed>"
    size:              "20" => "20"
    snapshot_id:       "" => "<computed>"
    tags.%:            "2" => "2"
    tags.Name:         "elasticsearch1 VG ebs-xvdf" => "elasticsearch1 VG ebs-xvdf"
    tags.cluster:      "elasticsearch" => "elasticsearch"
    type:              "gp2" => "gp2"

+ aws_instance.elasticsearch1
    ami:                               "ami-xxxxxxxxx"
    associate_public_ip_address:       "<computed>"
    availability_zone:                 "<computed>"
    ebs_block_device.#:                "<computed>"
    ephemeral_block_device.#:          "<computed>"
    iam_instance_profile:              "Elasticsearch"
    instance_state:                    "<computed>"
    instance_type:                     "i3.xlarge"
    ipv6_address_count:                "<computed>"
    ipv6_addresses.#:                  "<computed>"
    key_name:                          "<computed>"
    network_interface.#:               "<computed>"
    network_interface_id:              "<computed>"
    placement_group:                   "log-ingest-e1a"
    primary_network_interface_id:      "<computed>"
    private_dns:                       "<computed>"
    private_ip:                        "<computed>"
    public_dns:                        "<computed>"
    public_ip:                         "<computed>"
    root_block_device.#:               "<computed>"
    security_groups.#:                 "<computed>"
    source_dest_check:                 "true"
    subnet_id:                         "subnet-xxxxxx"
    tags.%:                            "4"
    tags.Name:                         "elasticsearch1"
    tags.cluster:                      "elasticsearch"
    tenancy:                           "<computed>"
    volume_tags.%:                     "<computed>"
    vpc_security_group_ids.#:          "1"
    vpc_security_group_ids.xxxxxx: "sg-xxxxxxx"

+ aws_volume_attachment.elasticsearch1-sdf-att
    device_name:  "/dev/sdf"
    force_detach: "<computed>"
    instance_id:  "${aws_instance.elasticsearch1.id}"
    skip_destroy: "<computed>"
    volume_id:    "${aws_ebs_volume.elasticsearch1-sdf-vol.id}"
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

The `aws_instance` resources were terminated manually via the EC2 console prior to `plan`, which would have detected that the instances need replacing. That part is intended, but only a new `aws_volume_attachment` to the existing EBS volume should be sufficient. The previous and the new EC2 instance were located in the same AZ, and as such the availability_zone variable which triggered the new `aws_ebs_volume` should have been computed as unchanged.

*Applying here without human confirmation would have led to data loss*

### References

Possibly related to https://github.com/terraform-providers/terraform-provider-aws/issues/83

**Comment by radeksimko** [comment]
Hi Nathan,
based on the config attached I believe this is working as intended.

```hcl
resource "aws_ebs_volume" "elasticsearch1-sdf-vol" {
  availability_zone = "${aws_instance.elasticsearch1.availability_zone}"
```

Terraform doesn't know whether the volume needs re-provisioning because the instance doesn't exist (yet) and you're telling it to create a volume in AZ of that instance.

There's a couple of ways to get around this:

1. You could define AZ statically in `aws_ebs_volume`
2. If the main point of truth for AZ is subnet (I noticed you're passing subnet as a variable `${var.subnet["1a"]}`) then you can pass AZ as another variable, e.g. `${var.azs["1a"]}`.
3. If you don't want to modify things outside of this config at all (i.e. what variables are being passed in) then [`aws_subnet`](https://www.terraform.io/docs/providers/aws/d/subnet.html) data source ^s the easiest solution, see snippet of your modified config below.

```hcl
data "aws_subnet" "s" {
  id = "${var.subnet["1a"]}"
}

resource "aws_ebs_volume" "elasticsearch1-sdf-vol" {
  availability_zone = "${data.aws_subnet.s.availability_zone}"
  size = 20
  type = "gp2"

  tags {
    Name = "elasticsearch1 VG ebs-xvdf"
    cluster = "elasticsearch"
  }
}
```

I'm aware the behaviour may be confusing at first, but I hope it now makes more sense with the explanation.

Let me know if we can close this issue.

**Comment by CpuID** [comment]
I think I like the data source approach, thx very much :) Tested and verified that it doesn't force a recreate. I think my thinking was when TF is doing a refresh/plan it should have been able to deduce the AZ from the  resource relationships, but not a big issue.

My issues noted in https://github.com/terraform-providers/terraform-provider-aws/issues/1311 actually prevent me from using `aws_ebs_volume` anyway and I needed to use `ebs_block_device` on the `aws_instance` itself to workaround the lack of EBS volumes on boot.

**Comment by radeksimko** [comment]
> I think my thinking was when TF is doing a refresh/plan it should have been able to deduce the AZ from the resource relationships

In such case the resource would need to understand the relationship between

```
aws_instance.availability_zone <-> aws_instance.subnet_id <-> var.subnet_id
```

and be able to pre-compute the `availability_zone` based on other `subnet_id` + expose that. Right now we treat `Computed` fields as unknown (for the purpose of referencing) prior to creation, even though in many cases it is known.

It's not completely crazy idea and we might think about this at some point in the future, but we also need to be aware of users that do expect this behaviour - i.e. "if I taint this `aws_instance` I expect my EBS volume to be recreated too". It is a dangerous area, different people - different needs. Hopefully `plan` is there to avoid any significant surprises and prevent disasters though. 😄

**Comment by CpuID** [comment]
Makes sense, for sure :)
