### ISSUE TITLE
Tech debt: Add acceptance test PreCheck for attached Internet Gateway

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#13537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Certain resources (e.g. public Redshift clusters and RDS database instances) require an Internet Gateway to be associated with a VPC.
Add an acceptance test `PreCheck` function to skip relevant tests if this pre-condition is not met, rather than allowing the tests to fail.

### New or Affected Resource(s)

* `aws_redshift_cluster`
* `aws_db_instance`
* ...

### References

Related:
* #13260
* #13361

**Comment by bflad** [comment]
I think in these cases we should prefer to create a new VPC with the correct networking infrastructure as part of the test configuration, rather than trying to check/work with potentially shared infrastructure.

**Comment by ewbankkit** [comment]
Yes, agree that wherever possible the tests should be hermetic. The same applies to #13260.
I'll see if there are any cases where we really are testing public access via a default VPC.

**Comment by ewbankkit** [comment]
I'm going to close this one and roll it into solutions for https://github.com/terraform-providers/terraform-provider-aws/issues/13260.
