### ISSUE TITLE
Provider type not available for installtion

### ISSUE THREAD

**Issue by gopikrish8** [terraform-providers/terraform-provider-aws#13543]
Hi,

Getting below error when trying to launch terraform. 
was working yesterday.

================================
system@Kris-MBP vpc_and_ec2 % terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "type" not available for installation.

A provider named "type" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

---------
Terraform debug logs:
================

system@Kris-MBP vpc_and_ec2 % export TF_LOG=trace
system@Kris-MBP vpc_and_ec2 % terraform init
2020/05/28 13:58:21 [INFO] Terraform version: 0.12.26  
2020/05/28 13:58:21 [INFO] Go runtime version: go1.13.11
2020/05/28 13:58:21 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/05/28 13:58:21 [DEBUG] Attempting to open CLI config file: /Users/kris/.terraformrc
2020/05/28 13:58:21 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/05/28 13:58:21 [INFO] CLI command args: []string{"init"}

Initializing the backend...
2020/05/28 13:58:21 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/05/28 13:58:21 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/05/28 13:58:21 [DEBUG] New state was assigned lineage "59c7f2b7-6044-8f0d-c89f-06a5559c5130"
2020/05/28 13:58:21 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/05/28 13:58:21 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/05/28 13:58:21 [DEBUG] checking for provider in "."
2020/05/28 13:58:21 [DEBUG] checking for provider in "/usr/local/bin"
2020/05/28 13:58:21 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/05/28 13:58:21 [DEBUG] found provider "terraform-provider-aws_v2.63.0_x4"
2020/05/28 13:58:21 [DEBUG] found valid plugin: "aws", "2.63.0", "/Users/kris/Documents/Terraform/terraform_projects/vpc_and_ec2/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.63.0_x4"
2020/05/28 13:58:21 [DEBUG] checking for provisioner in "."
2020/05/28 13:58:21 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/05/28 13:58:21 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2020/05/28 13:58:21 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/05/28 13:58:21 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/05/28 13:58:21 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/05/28 13:58:21 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/05/28 13:58:21 [TRACE] statemgr.Filesystem: read nil snapshot
2020/05/28 13:58:21 [DEBUG] checking for provider in "."
2020/05/28 13:58:21 [DEBUG] checking for provider in "/usr/local/bin"
2020/05/28 13:58:21 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/05/28 13:58:21 [DEBUG] found provider "terraform-provider-aws_v2.63.0_x4"
2020/05/28 13:58:21 [DEBUG] found valid plugin: "aws", "2.63.0", "/Users/kris/Documents/Terraform/terraform_projects/vpc_and_ec2/.terraform/plugins/darwin_amd64/terraform-provider-aws_v2.63.0_x4"

2020/05/28 13:58:21 [DEBUG] plugin requirements: "aws"=""
2020/05/28 13:58:21 [DEBUG] plugin requirements: "type"=""
Initializing provider plugins...
2020/05/28 13:58:21 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/05/28 13:58:21 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
- Checking for available provider plugins...
2020/05/28 13:58:22 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/type/versions"
2020/05/28 13:58:22 [DEBUG] GET https://registry.terraform.io/v1/providers/-/type/versions
2020/05/28 13:58:22 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/type/versions
2020/05/28 13:58:22 [DEBUG] provider &{registry.terraform.io - type darwin amd64} not found

Provider "type" not available for installation.

A provider named "type" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
-------

Thanks,
Kris

**Comment by a1zk** [comment]
Hi @gopikrish8,
Could you share, please, your provider configuration?
And take a look on [all providers list] (https://www.terraform.io/docs/providers/index.html)
Thanks.

**Comment by gopikrish8** [comment]
HI a1zk,

Thanks for the response.

system@Kris-MBP vpc_and_ec2 % terraform providers
.
├── provider.aws
└── provider.type
=========
provider "aws" {
region = "${var.region}"
}

Thanks,

**Comment by gopikrish8** [comment]
finally it started working after I moved configuration files to different directory

**Comment by bflad** [comment]
It looks like this was resolved so I'm going to close this, but to followup, Terraform 0.12 and earlier will take any configuration containing something like the following:

```tf
resource "type_thing" "example" {
  # ...
}
```

And guess that it should download a non-existent provider named `type`.
