### ISSUE TITLE
StorageGateway.UpdateBandwidthRateLimit Api support

### ISSUE THREAD

**Issue by FireballDWF** [terraform-providers/terraform-provider-aws#13550]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enable setting bandwidth limits for Storage Gateway

### New or Affected Resource(s)

* aws_storagegateway_gateway

### References
* https://docs.aws.amazon.com/sdk-for-go/api/service/storagegateway/#StorageGateway.UpdateBandwidthRateLimit

**Comment by DrFaust92** [comment]
Hey @FireballDWF im going to address some storage gateway PR and take a look at this one as well. seems pretty straight forward.

**Comment by DrFaust92** [comment]
addressed in #13568

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.4.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
