### ISSUE TITLE
version v2.64.0 crashes on provisioning resource aws_autoscaling_group

### ISSUE THREAD

**Issue by drexler** [terraform-providers/terraform-provider-aws#13569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.10

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "notification-asg" {
  name = "${var.application_name}-asg"

  # Only one instance of the notification server is to run at all times!
  desired_capacity = 1
  max_size         = 1
  min_size         = 1

  vpc_zone_identifier = ["${var.private_subnets_ids}"]

  launch_template = {
    id      = "${aws_launch_template.notification.id}"
    version = "$$Latest"
  }

  tags = [
    {
      key                 = "Application"
      value               = "${var.target_application}"
      propagate_at_launch = true
    },
    {
      key                 = "CreatedBy"
      value               = "${var.resource_creator}"
      propagate_at_launch = true
    },
    {
      key                 = "Name"
      value               = "${var.application_name}"
      propagate_at_launch = true
    },
    {
      key                 = "Environment"
      value               = "${var.environment}"
      propagate_at_launch = true
    },
    {
      key                 = "Team"
      value               = "${var.team}"
      propagate_at_launch = true
    },
  ]
}
```

### Panic Output

https://gist.github.com/drexler/1f844a16ae25c38958315f4d0d2be28b
### Steps to Reproduce

1. `terraform plan`

### Important Factoids
Downgrading to version `2.62.0` of the Terraform AWS Provider works well. 

### References

* #0000

**Comment by ewbankkit** [comment]
@drexler That's for raising this issue.
It has already been noted in https://github.com/terraform-providers/terraform-provider-aws/issues/13549.
Could you please close this one and add any comments there?

**Comment by drexler** [comment]
@ewbankkit will do.
