### ISSUE TITLE
aws_autoscaling_group throws unexpected EOF error

### ISSUE THREAD

**Issue by cylin2000** [terraform-providers/terraform-provider-aws#13579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.10 

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "aws_autoscaling_group" "xxxxxx_auto_scale_nrt" {
  launch_configuration = "${aws_launch_configuration.xxxxxx_lc.id}"
  vpc_zone_identifier = ["${var.private_subnet_a_id}", "${var.private_subnet_b_id}"]
  min_size            = 2
  max_size            = 4
  desired_capacity    = 2
  target_group_arns   = ["${aws_lb_target_group.xxxxxx_alb_tr_gp.arn}"]
  health_check_grace_period = 2000
  health_check_type   = "ELB"

  depends_on = ["aws_db_instance.xxxxxx_rds"]

  tags = [
    {
      key                 = "application-id"
      value               = "${var.application-id}"
      propagate_at_launch = true
    },
    {
      key                 = "owner"
      value               = "${var.owner}"
      propagate_at_launch = true
    },
    {
      key                 = "group1"
      value               = "${var.group}"
      propagate_at_launch = true
    },
    {
      key                 = "primary"
      value               = "false"
      propagate_at_launch = true
    }
  ]
}

```

### Expected Behavior
Terraform will create autoscale group successfully

### Actual Behavior
Terraform throw unexpected EOF error

### Steps to Reproduce

1. `terraform plan`

### Workaround
This issue occurred about 4 days ago, we found terraform-provider-aws v2.64.0 released on that time, so we update main.tf to set provider version to 2.63.0 and then re-run terraform plan, the issue is gone. We think the upgrade of terraform-provider-aws could caused this issue.

### References

* #0000

**Comment by ewbankkit** [comment]
Hi @cylin2000  Thanks for raising this issue.
The problem has been noted in https://github.com/terraform-providers/terraform-provider-aws/issues/13549 and I'll close this one so as to consolidate discussion there.
