### ISSUE TITLE
AWS Autoscaling Group Resource Unexpected EOF

### ISSUE THREAD

**Issue by tarpanpathak** [terraform-providers/terraform-provider-aws#13573]
Hi, 

I'm hoping that this is the correct place for this issue. 

To adhere to a EC2 node rotation/patching policy, we randomly re-create instances in our AWS infrastructure. During the last rotation, we encountered an issue recently where a `terraform plan` showed that the `tags` defined in an AutoScaling Group resource would be "re-shuffled". Considering that the plan output seemed "normal", we ran a `terraform apply`. Since the apply, we have not been able to generate a successful `terraform plan` output against the same resources. This issue is preventing us from updating/modifying any of our existing AutoScaling Group resources. See details on the issue below. 

### Terraform Version

`0.11.10`

### Affected Resource(s)

* aws_autoscaling_group.asg

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "dcs_cron" {
  name                 = "asg"
  max_size             = "1"
  min_size             = "1"
  force_delete         = false
  launch_configuration = "${aws_launch_configuration.lc.name}"
  vpc_zone_identifier  = ["${data.terraform_remote_state.network.private_subnet_ids}"]

  lifecycle {
    create_before_destroy = true
  }

  tags = [
    {
      key                 = "foo"
      value               = "bar"
      propagate_at_launch = true
    },
  ]
}
```

### Panic Output

N/A

### Expected Behavior

A successful plan output. 

### Actual Behavior

```
Error: Error running plan: 1 error(s) occurred:

* aws_autoscaling_group.asg: 1 error(s) occurred:

* aws_autoscaling_group.asg: unexpected EOF
```

### Steps to Reproduce

We use a proprietary deployment process but the following steps should be enough to reproduce the issue. 

**Note**: Be sure to use the same Terraform version mentioned above. 

1. Create a Terraform module with a single `main.tf` file with the following contents: 
```
resource "aws_launch_configuration" "lc" {
  name_prefix = "lc"
  image_id = "<some_img>"
  instance_type        = "t2.micro"
  security_groups      = ["<some_security_group>"]
  user_data            = "<path/to/some/file>"
  key_name             = "<some_key>"

  root_block_device {
    volume_type           = "gp2"
    delete_on_termination = true
    volume_size           = "10"
  }

  lifecycle {
    create_before_destroy = true
  }
}
resource "aws_autoscaling_group" "asg" {
  name                   = "asg"
  max_size              = "1"
  min_size               = "1"
  force_delete         = false
  launch_configuration = "${aws_launch_configuration.lc.name}"
  vpc_zone_identifier  = ["<subnet_ids>"]

  lifecycle {
    create_before_destroy = true
  }

  tags = [
    {
      key                 = "foo"
      value               = "bar"
      propagate_at_launch = true
    },
  ]
}

resource "aws_security_group" "asg_sg" {
  name        = "asg-instance-sg"
  description = "Security Group for the ASG"
  vpc_id      = "<some_vpc_id>"
}
```

2. Run a `terraform plan` against this module. 

3. Run a `terraform apply` against this module. 

4. Add a new tag. 

5. Run a `terraform plan`. 

6. Run a `terraform apply`. 

7. Run a `terraform plan`. This should throw the "Unexpected EOF" error or the `tags` should get re-shuffled. 

### Important Factoids

N/A 

### References

N/A

### Additional Notes 

After some debugging, we have isolated this issue to the `tags` configuration in the corresponding Terraform module. Here's a sample tags` configuration: 
```
tags = [
    {
      key                 = "foo"
      value               = "bar"
      propagate_at_launch = true
    },
]
```
Removing the tags altogether from the autoscaling group resource in the module or using the following format resolves the issue. 
```
tag = { 
    key = "foo"
    bar = "bar"
    propagate_at_launch = true
}
```
We would like to understand the issue a bit better before moving forward with any changes to our modules.

**Comment by ewbankkit** [comment]
HI @tarpanpathak Thanks for raising this issue.
The problem has been noted in https://github.com/terraform-providers/terraform-provider-aws/issues/13549 and I'll close this one so as to consolidate discussion there.
