### ISSUE TITLE
Output ARN from `aws_ec2_traffic_mirror_target`

### ISSUE THREAD

**Issue by awilkins** [terraform-providers/terraform-provider-aws#13596]
### Description

Traffic mirror targets are frequently shared between accounts.

In order to do this you need to pass an ARN to `aws_ram_resource_association`, but the resource does not emit this attribute.

### New or Affected Resource(s)

* `aws_ec2_traffic_mirror_target`

### Potential Terraform Configuration

```hcl
# Workaround (you can see the ARN format here)
resource "aws_ram_resource_association" "traffic_mirror_target" {
  resource_share_arn = aws_ram_resource_share.example.arn
  resource_arn = format(
    "arn:aws:ec2:%s:%s:traffic-mirror-target/%s",
    data.aws_region.current.name,
    data.aws_caller_identity.transit.account_id,
    aws_ec2_traffic_mirror_target.example.id
  )
}

# Better
resource "aws_ram_resource_association" "traffic_mirror_target" {
  resource_share_arn = aws_ram_resource_share.example.arn
  resource_arn = aws_ec2_traffic_mirror_target.example.arn
}

```

**Comment by bflad** [comment]
Support for a new `arn` attribute on the `aws_ec2_traffic_mirror_target` resource has been merged and will release with version 2.67.0 of the Terraform AWS Provider, likely tomorrow. Thanks to @DrFaust92 for the implementation. 👍
