### ISSUE TITLE
provide nameservers in route53_zone data source

### ISSUE THREAD

**Issue by AlPee-DU** [terraform-providers/terraform-provider-aws#1359]
### Terraform Version
v0.10.0

### Affected Resource(s)
data.aws_route53_zone

### Expected Behavior
With the API/CLI for AWS it is possible to get the nameservers for a selected (public) hosted zone.

### Actual Behavior
Terraform does not provide the nameservers in a datasource (but in a regular ressource)

**Comment by saravanan30erd** [comment]
Fixed in PR #4336

**Comment by AlPee-DU** [comment]
Forgot this one... thx! :)
