### ISSUE TITLE
Panic in terraform-provide-aws-v0.1.3_x4 using 0.10.0 for S3 when lifecycle_rule present.

### ISSUE THREAD

**Issue by prigorctac** [terraform-providers/terraform-provider-aws#1361]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" "my_xyz_bucket" {
  bucket = "my_xyz_bucket"
  acl    = "private"

  lifecycle_rule {
    id      = "elb-log-east-30-ia-5yr-del"
    prefix  = "/"
    enabled = true

    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }

    expiration {
      days                         = 1825
      expired_object_delete_marker = 0
    }
  }

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "AWSConsole-AccessLogs-Policy-1435178610361",
  "Statement": [
    {
      "Sid": "AWSConsoleStmt-1435178610361",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::127311923021:root"
      },
      "Action": "s3:PutObject",
      "Resource": "arn:aws:s3:::my_xyz_bucket/*"
    }
  ]
}
POLICY
}
```

### Panic Output
https://gist.github.com/prigorctac/329d2c845985435bc1194952fc430e74

### Expected Behavior
Output plan

### Actual Behavior
Terraform Plan crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform plan ` or `terraform plan --target <s3 bucket resource with lifecycle_rule>`

### Important Factoids
Terraform with remote S3 state file, S3 buckets with lifecycle_rule.   We also use multiple remote state file data sources, but they are not used in the s3 bucket resources that crash.   

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- did not find anything related.

**Comment by Preston4tw** [comment]
I'm pretty sure merged commit https://github.com/terraform-providers/terraform-provider-aws/pull/1316 fixes your issue, it's just pending release. If you're comfortable with golang, you can test the fix and try building the plugin from head, see https://github.com/terraform-providers/terraform-provider-aws#developing-the-provider.

**Comment by prigorctac** [comment]
Thank you.   It would appear that it does and this is a duplicate.     I will close this one in favor or #1314
