### ISSUE TITLE
aws_batch_job_definition resource always shows destroy/create without any changes

### ISSUE THREAD

**Issue by RishikeshDarandale** [terraform-providers/terraform-provider-aws#13629]
`aws_batch_job_definition` reosurce is always shows destory/create without any changes to this resource. This was also preiously reported #11998 and fixed in #12000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
terraform --version
Terraform v0.12.26
+ provider.aws v2.65.0
```

### Affected Resource(s)

* aws_batch_job_definition

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {
    path = ".terraform/state/terraform.tfstate"
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_iam_role" "role" {
  name = "role-test"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
    {
        "Action": "sts:AssumeRole",
        "Effect": "Allow",
        "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
        }
    }
    ]
}
EOF
}

resource "aws_ecr_repository" "ecr" {
  name = "my-app"
}

resource "aws_batch_job_definition" "batch-job-definition" {
  name = "test-job-definition"
  type = "container"

  container_properties = <<CONTAINER_PROPERTIES
{
    "image": "${aws_ecr_repository.ecr.name}:image",
    "memory": 4096,
    "vcpus": 1,
    "jobRoleArn": "${aws_iam_role.role.arn}"
    "environment": [
      {
        "name": "ENVIRONMENT",
        "value": "test"
      }
   ]
}
CONTAINER_PROPERTIES
}
```

### Debug Output

https://gist.github.com/RishikeshDarandale/5f183623e095905ecd8af50c5b211d12

### Expected Behavior

Resource should not be always recreated.

### Actual Behavior

Resource is always recreated.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform plan`

### References

- #11998
- #12000

**Comment by ewbankkit** [comment]
@RishikeshDarandale Thanks for raising this.
I can reproduce this problem with an internal unit test:

```console
$ go test ./aws/internal/service/batch/equivalency
2020/06/05 10:51:15 [DEBUG] Canonical Batch Container Properties JSON are not equal.
First: {"environment":[{"name":"ENVIRONMENT","value":"test"}],"image":"123.dkr.ecr.us-east-1.amazonaws.com/my-app","jobRoleArn":"arn:aws:iam::123:role/role-test","memory":4096,"vcpus":1}
Second: {"command":[],"environment":[{"name":"ENVIRONMENT","value":"test"}],"image":"123.dkr.ecr.us-east-1.amazonaws.com/my-app","jobRoleArn":"arn:aws:iam::123:role/role-test","memory":4096,"vcpus":1}
--- FAIL: TestEquivalentBatchContainerPropertiesJSON (0.00s)
    --- FAIL: TestEquivalentBatchContainerPropertiesJSON/empty_command,_mountPoints,_resourceRequirements,_ulimits,_volumes (0.00s)
        container_properties_test.go:258: got false, expected true
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	0.005s
FAIL
```

**Comment by ewbankkit** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/13634 has been submitted to address this.

**Comment by bflad** [comment]
The above fix for this has been merged and will release with version 2.66.0 of the Terraform AWS Provider, later next week. 👍

**Comment by RishikeshDarandale** [comment]
Thanks @ewbankkit for quick resolution.

Is it the problem with only `command` property? What about the others like `volumes`, etc?

**Comment by ewbankkit** [comment]
@RishikeshDarandale We were already correctly handling the other array attributes (`volumes` etc.) when they were empty.
