### ISSUE TITLE
r/aws_apigatewayv2_stage: Perpetual diff when 'auto_deploy = true'

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#13633]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

AWS Provider v2.65.0.

### Affected Resource(s)

* `aws_apigatewayv2_stage`

### Terraform Configuration Files

From #13625:

```hcl
resource "aws_apigatewayv2_api" "sc_api" {
  name          = "lambda-sc-kicker-api"
  protocol_type = "HTTP"
}

# TODO: There is something weird about this integration.
# After this resource is deployed, detach it and then re-attach it in the console and it works fine.
# Must be some kind of missing property.
resource "aws_apigatewayv2_integration" "sc_api_integration" {
  api_id           = aws_apigatewayv2_api.sc_api.id
  integration_type = "AWS_PROXY"

  description            = "Lambda SC Kicker"
  integration_method     = "POST"
  integration_uri        = module.lambda_sc_kicker.lambda_sc_kicker_invoke_arn
  payload_format_version = "2.0"
}

resource "aws_apigatewayv2_route" "sc_api_create_route" {
  api_id    = aws_apigatewayv2_api.sc_api.id
  route_key = "POST /create"
  target    = "integrations/${aws_apigatewayv2_integration.sc_api_integration.id}"
}

resource "aws_apigatewayv2_stage" "sc_api_default_stage" {
  api_id      = aws_apigatewayv2_api.sc_api.id
  name        = "$default"
  auto_deploy = true
}

```

### Expected Behavior

After successful `terraform apply`, `terraform plan` should show no diffs.

### Actual Behavior

Perpetual diff:

```
  # aws_apigatewayv2_stage.sc_api_default_stage will be updated in-place
  ~ resource "aws_apigatewayv2_stage" "sc_api_default_stage" {
        api_id          = "ekmqhtlds3"
        arn             = "arn:aws:apigateway:us-west-2::/apis/ekmqhtlds3/stages/$default"
        auto_deploy     = true
      - deployment_id   = "y2dz0a" -> null
        id              = "$default"
        invoke_url      = "https://ekmqhtlds3.execute-api.us-west-2.amazonaws.com/"
        name            = "$default"
        stage_variables = {}
        tags            = {}

        default_route_settings {
            data_trace_enabled       = false
            detailed_metrics_enabled = false
            throttling_burst_limit   = 0
            throttling_rate_limit    = 0
        }
    }
```

### Important Factoids

The problem is not handling a computed `deployment_id` when `auto_deploy = true`.

**Comment by bvaradinov-c** [comment]
We see the same behavior.

**Comment by lxg** [comment]
But is this really a bug? AWS itself does assign a new ID on each deployment. If you make a new deployment, you get a new ID for the current deployment, and your state is updated.

**Comment by ewbankkit** [comment]
@lxg You are correct that in the case of `auto_deploy` stages the deployment is not managed by Terraform. We do not need the stage to try and update the deployment ID in these cases and so want to mark the `deployment_id` as `Computed`.
