### ISSUE TITLE
aws_cloudwatch_log_stream does not support import functionality

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [terraform-providers/terraform-provider-aws#13683]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it appears that it's impossible to import a aws_cloudwatch_log_stream resource.
`Error: resource aws_cloudwatch_log_stream doesn't support import`
I would like to request support be added for import to support this resource.

This is very helpful when importing existing architecture like a aws_kinesis_firehose_delivery_stream.

### New or Affected Resource(s)

* aws_cloudwatch_log_stream 

### Potential Terraform Configuration

n/a

### References

* https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_stream.html

**Comment by bflad** [comment]
Support for `aws_cloudwatch_log_stream` resource import has been merged and will release with version 2.67.0 of the Terraform AWS Provider, likely tomorrow. Thanks to @ewbankkit for the implementation. 👍
