### ISSUE TITLE
Add AWS CodeArtifact service support

### ISSUE THREAD

**Issue by jrobison-sb** [terraform-providers/terraform-provider-aws#13714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has a new service called [AWS CodeArtifact](https://aws.amazon.com/blogs/aws/software-package-management-with-aws-codeartifact/). It would be nice to get Terraform support for this.

### New or Affected Resource(s)

* aws_codeartifact_repository
* aws_codeartifact_domain

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/06/introducing-aws-codeartifact-a-fully-managed-software-artifact-repository-service/).
[User Guide](https://docs.aws.amazon.com/codeartifact/latest/ug/welcome.html).

Requires [AWS SDK v1.31.15](https://github.com/aws/aws-sdk-go/releases/tag/v1.31.15):
* https://github.com/terraform-providers/terraform-provider-aws/pull/13459

**Comment by ewbankkit** [comment]
Potential additional resources:

* `aws_codeartifact_domain_permissions_policy`
* `aws_codeartifact_repository_permissions_policy`
