### ISSUE TITLE
aws_ecs_capacity_provider can now be deleted

### ISSUE THREAD

**Issue by ziggythehamster** [terraform-providers/terraform-provider-aws#13722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has just added support for deleting ECS capacity providers. Prior to today, you couldn't delete a capacity provider, so Terraform would just delete it from state and leave it behind because ECS lacked the API.

### New or Affected Resource(s)

* aws_ecs_capacity_provider

### References

* https://github.com/aws/containers-roadmap/issues/632
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/document_history.html
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/asg-capacity-providers.html#asg-capacity-providers-delete-capacity-provider

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.32.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.32.0):
* https://github.com/terraform-providers/terraform-provider-aws/pull/13459

**Comment by bflad** [comment]
Support for the new deletion API has been merged and will release with version 2.67.0 of the Terraform AWS Provider, later this week. 👍
