### ISSUE TITLE
AWS Single Sign-On Resource

### ISSUE THREAD

**Issue by krathow** [terraform-providers/terraform-provider-aws#13755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a resource to manage AWS Single Sign-On, as per the newly aanounced support for integrating with Azure AD: [https://aws.amazon.com/blogs/aws/the-next-evolution-in-aws-single-sign-on/ ](url)

### New or Affected Resource(s)

AWS Single-Sign On

* aws_single_sign_on

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Hi @krathow 👋  Can you please point to the AWS CLI, AWS API Reference, or AWS Go SDK documentation that shows how these components can be created? For example, the [AWS Go SDK `sso` package does not implement this type of functionality](https://docs.aws.amazon.com/sdk-for-go/api/service/sso/). I believe this functionality is not publicly available for programmatic creation at the current time, which means that the Terraform AWS Provider cannot implement support for this.

**Comment by krathow** [comment]
Hi @bflad , you're absolutely right, I'm checking with AWS where they are in means of automation and wil reopen this issue once an appropriate API is available.

**Comment by mmerickel** [comment]
I'm not sure this should be closed... it may just not be possible to implement until the underlying libraries are updated but surely that's coming? I'd like to follow this, or another issue to monitor its progress anyway.

**Comment by krathow** [comment]
@mmerickel : yes, sounds good, I've got a case open with AWS to get notified once the API is available. I'll update this issue once it's available. For the mean time I'll keep this open

**Comment by christophetd** [comment]
@krathow Thanks for looking into this, it's definitely much needed! Did you get any timeline from the AWS side? It's unfortunate they chose to release such an important service without an API.

**Comment by krathow** [comment]
@christophetd unfortunately I did not get any information yet. I've escalated the topic again but did not get anything back. 
I keep on trying to get something...

**Comment by Computer15776** [comment]
It looks like account assignment has been made available in the [AWS Go SDK](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v13421-2020-09-10).

**Comment by jbscare** [comment]
How does this issue relate to #15108 ?

**Comment by bflad** [comment]
Hi folks 👋  Since #15108 has more concrete details relating to the SSO API released yesterday, I'm going to close this issue in preference of that one. Please 👍  upvote and subscribe there for further updates.

**Comment by sean-nixon** [comment]
@bflad I noticed this issue has been closed in favor of my issue. The API released yesterday only pertains to managing AWS SSO permission sets and assignments. It does not actually allow enabling AWS SSO or configuring any other AWS SSO settings such as integration with Azure AD. I wonder if this issue should still remain open to track the request for those features, even if there's no API available for them yet.

**Comment by bflad** [comment]
Great point, @sean-nixon 👍  Since there's nothing concrete about the implementation details of that particular portion of SSO support since it hasn't been released by AWS, there's nothing actionable for this project (and we have a lot of open, actionable items already 😉 ). I'm worried about having multiple SSO issues open and folks being confused what to follow for updates on particular functionality.

For anyone interested in the SSO functionality such as AzureAD, our best recommendation at this time is to contact AWS Support with a feature request asking for programmatic (API) support. That AWS service team can also reach out to the maintainers here through the Amazon Partner Network if they would like to collaborate ahead of any potential launch. Until it is announced publicly, our preference will be to not keep an issue open for functionality that cannot be implemented.
