### ISSUE TITLE
Issue creating an AWS API Gateway resource  & method  with a custom authorizer at the REST API root

### ISSUE THREAD

**Issue by proever** [terraform-providers/terraform-provider-aws#1379]
### Terraform Version
Terraform v0.10.0, v0.9.11

### Affected Resource(s)
- aws_api_gateway_resource, method
- list, element interpolation syntax?

### Terraform Configuration Files
```hcl

# get_resource_id module
resource "aws_api_gateway_resource" "custom_resource" {
  count = "${var.custom_resource_boolean}"
  parent_id = "${var.custom_resource_parent_id}"
  path_part = "${var.custom_resource_path}"
  rest_api_id = "${var.rest_api_id}"
}

output "resource_id" {
  value = "${element(list(var.rest_api_root_resource_id, aws_api_gateway_resource.custom_resource.id), var.custom_resource_boolean)}"
}

# ---

resource "aws_api_gateway_method" "http_method" {
  rest_api_id   = "${var.rest_api_id}"
  resource_id   = "${module.get_resource_id.resource_id}"
  http_method   = "${var.custom_resource_method}"
  authorization = "CUSTOM"
  authorizer_id = "${var.authorizer_id}"
}
```

the above config is supposed to create an aws_api_gateway_resource if custom_resource_boolean is 1 and return its ID, otherwise it returns the root ID of the api gateway in question. The way I accomplished this is with the element(list(a,b), bool) where bool is the boolean mentioned above. ~~This code works in v.0.9.11, but fails in v.0.10.0.~~

### Debug Output
[gist](https://gist.github.com/proever/78cb437b7c93ec3e5e966bcb0e4464b7)

### Expected Behavior
It should create a properly configured AWS API Gateway resource. 

### Actual Behavior
The following error is returned:
* aws_api_gateway_method.http_method: Error creating API Gateway Method: SerializationError: failed decoding REST JSON error response
caused by: invalid character '<' looking for beginning of value

**Comment by proever** [comment]
Looking through the attached log, the following lines jump out when searching for Serialization Error: 

```
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: {"apiKeyRequired":false,"authorizationType":"CUSTOM","authorizerId":"y0r719"}
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: -----------------------------------------------------
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: 2017/08/09 19:30:55 [DEBUG] [aws-sdk-go] DEBUG: Response apigateway/PutMethod Details:
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: ---[ RESPONSE ]--------------------------------------
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: HTTP/2.0 403 Forbidden
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: Content-Length: 130
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: Date: Thu, 10 Aug 2017 02:30:55 GMT
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: X-Amzn-Requestid: efca1a4b-7d73-11e7-8bbd-5f149ef0db2b
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: 
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: 
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: -----------------------------------------------------
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: 2017/08/09 19:30:55 [DEBUG] [aws-sdk-go] <AccessDeniedException>
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4:   <Message>Unable to determine service/operation name to be authorized</Message>
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: </AccessDeniedException>
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: 2017/08/09 19:30:55 [DEBUG] [aws-sdk-go] DEBUG: Validate Response apigateway/PutMethod failed, not retrying, error SerializationError: failed decoding REST JSON error response
```

It appears that the issue is coming from trying to attach a custom authorizer to the method.

**Comment by Ninir** [comment]
Hey @proever ,

Thanks for opening this issue.

Just a small question to be sure to get the problem right there: can you confirm that this **exact** configuration is working on 0.9.11 please?

As far as I can see, this is related to a configuration issue: `Unable to determine service/operation name to be authorized`, which the AWS SDK could have better handle.

Will run the acceptance test locally to check that the test creating the custom authorizer + method & so on is still ok.

**Comment by proever** [comment]
Hi @Ninir,

I was actually just about to give an update on this. After some more playing around, it turns out that this also doesn't work on 0.9.11. Sorry about the false alarm. I'll go ahead and change the issue title to reflect that.

That being said, the issue itself, although ultimately being caused by an AWS error (as far as I can tell), is in my opinion still being triggered by the terraform config snippets I included above, most notably because it works when the boolean is set to 1.

**Comment by Ninir** [comment]
Thanks for the feedback @proever !

Do you think you could provide your whole configuration, including modules?

If you want a working example on TF 0.10 + 0.1.4 provider, check this https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_sns_topic_subscription_test.go#L283: just checked and tests are passing.

In your case, I'm wondering if the issue doesn't come up with the configuration you have, i.e. `${module.get_resource_id.resource_id}`. I do think that your `aws_api_gateway_resource ` & `output` are ok, only the method resource is annoying me.

Looking at the debug output (first revision), below lines look weird to me:
```
---[ REQUEST POST-SIGN ]-----------------------------
2017/08/09 19:30:55 [DEBUG] plugin: terraform-provider-aws_v0.1.4_x4: PUT /restapis/0ejyrbbyxg/resources/methods/ANY
```

2 questions there:
Can you confirm that the REST API ID is `0ejyrbbyxg`?
What is the value behind `${module.get_resource_id.resource_id}`?

Thanks!

**Comment by proever** [comment]
Hi again @Ninir!

I've been through several apply/destroy cycles, so I can't confirm that the REST API ID is the one you mention above, but I compared the output from the command line: 

```
module.helloworld_protectedresource.aws_api_gateway_rest_api.protectedresource: Creation complete (ID: sxm7wrjte4)
```
to this line: 
```
2017/08/09 23:30:17 [DEBUG] plugin: terraform: PUT /restapis/sxm7wrjte4/resources/methods/ANY HTTP/1.1
```

and it does appear that they are the same. 

To your second question, I would love to tell you the value of ${module.get_resource_id.resource_id}, but I have not been able to figure out a good way of getting it, since the apply step always fails. terraform output gives me nothing, as far as I can tell (even if I specify the modules to step into) and I've also not had any luck with terraform console. 

By the way, just to let you know, I'm still running everything on terraform 0.9.11. I know that's not helping things but I haven't gotten around to re-upgrading. Let me know if you think it'll help debugging to upgrade. 

I've attached a zip of 2 directories, if you want to actually run it, run terraform plan from the authorizer subdirectorie first, then terraform plan in the hello world one. You'll need an s3 bucket to write to.

[test-list-element.zip](https://github.com/terraform-providers/terraform-provider-aws/files/1213871/test-list-element.zip)

**Comment by proever** [comment]
I've spent some more time looking through the logs, and it appears that the output interpolation is failing as follows: 

```
2017/08/10 15:31:49 [DEBUG] vertex 'root.module.helloworld_resource_with_auth.module.http_method.module.get_resource_id.output.resource_id': evaluating
2017/08/10 15:31:49 [WARN] Output interpolation "resource_id" failed: Resource 'aws_api_gateway_resource.custom_resource' not found for variable 'aws_api_gateway_resource.custom_resource.id'
```

It makes sense that it can't find the resource, since its count was set to 0 by the boolean being false:

```HCL
resource "aws_api_gateway_resource" "custom_resource" {
  count = "${var.custom_resource_boolean}"
  parent_id = "${var.custom_resource_parent_id}"
  path_part = "${var.custom_resource_path}"
  rest_api_id = "${var.rest_api_id}"
}
```

This then causes the creation of the method to fail and also the attachment of the authorizer to that method (in the AWS SDK). 

So to get to the point, the method I'm using to select one or the other resource_id (element (list (a, b), bool) is failing, somewhat silently. The reason I'm using this method is that I'm not sure how else to allow the user to select if they want to add the method to the base path or to a custom resource.

**Comment by proever** [comment]
At long last, I've figured this out. 

The solution was to address the aws_api_gateway_resource.custom_resource as a list of resources, because that is how terraform sees it internally, as soon as a count is set: 

```
value = "${coalesce(join("", aws_api_gateway_resource.custom_resource.*.id), var.rest_api_root_resource_id)}"
```

The key character above is the *. This tells terraform that you want a list of all the ids of the custom resources you've created. Of course there's only going to be 0 or 1 of them, but terraform doesn't know that; there could just as well be 15. The join ("", ...) command tells terraform to create a long string out of all the ids it finds, delimited in this case by nothing (""). Since the boolean is set to 0, there are 0 ids in that string anyways, so coalesce gets the first nonempty string, which is var.rest_api_root_resource_id. 

In the end, this was not a bug, but rather an issue on my end. I appreciate the help and the quick response from @Ninir. 

I do think there is room for improvement in how terraform handles this case. 

First of all, I think it would be helpful for terraform to realize when someone is trying to address an attribute of a list of resources, and throw a warning during the plan step. And secondly, in this particular case, the error message parsing of the aws_api_gateway_method resource could be improved, so that people see more than "SerializationError" in the console. 

Thanks for all the hard work!

**Comment by proever** [comment]
One last comment. While the change described above works when running it on a "clean" state (i.e. just having run terraform destroy), it fails when changing the boolean from true to false without first running a terraform destroy. So basically if a custom resource already existed, and you want to get rid of that, you have to run terraform destroy first.

It fails with the following warning:

```
2017/08/11 15:04:22 [WARN] Output interpolation "resource_id" failed: Resource 'aws_api_gateway_resource.custom_resource' does not have attribute 'id' for variable 'aws_api_gateway_resource.custom_resource.*.id'
```

I don't think this is the correct behavior here either.
