### ISSUE TITLE
API Gateway v2 is missing support for updating route key 

### ISSUE THREAD

**Issue by davidaah** [terraform-providers/terraform-provider-aws#13814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26

### Affected Resource(s)

* aws_apigatewayv2_route

### Terraform Configuration Files

Initial configuration:

```hcl
...
resource "aws_apigatewayv2_route" "test" {
  api_id    = aws_apigatewayv2_api.test.id
  route_key = "GET /mypath"

  target = "integrations/${aws_apigatewayv2_integration.test.id}"
}
...
```

Updated configuration:

```hcl
...
resource "aws_apigatewayv2_route" "test" {
  api_id    = aws_apigatewayv2_api.test.id
  route_key = "GET /mynewpath"

  target = "integrations/${aws_apigatewayv2_integration.test.id}"
}
...
```

### Expected Behavior

Route key should be updated

Confirm it is supported with AWS CLI: 

```
$ aws apigatewayv2 update-route --api-id <api id> --route-id <route id> --route-key "GET /mynewpath"

{
    "RouteId": "<route id>",
    "RouteKey": "GET /mynewpath",
    "Target": "integrations/<integration id>"
}
```

In the debug output it appears that the updated "route key" is not sent in the API payload. Additionally, looking at the source referenced below, it looks like the Update directive is missing a condition for `route_key`

### Actual Behavior

`Error: error updating API Gateway v2 route: BadRequestException: Invalid route name content specified.`

### Steps to Reproduce

1. `terraform apply` with initial route key
2. `terraform apply` with the new route key

### References

* https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_apigatewayv2_route.go#L162-L204

**Comment by divmgl** [comment]
I'm actually getting this with catch-all patterns. Aside from being broken on AWS, they're also broken through the API. For instance `ANY /{all+}` doesn't work.
