### ISSUE TITLE
Add AWS Glue Dev Endpoint resource

### ISSUE THREAD

**Issue by harichandanp** [terraform-providers/terraform-provider-aws#13818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add AWS Glue Development Endpoint resource

### New or Affected Resource(s)

* aws_glue_development_endpoint

### References
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html

**Comment by bflad** [comment]
Hi @harichandanp 👋  Thank you for submitting this. We have a previous feature request for this resource, https://github.com/terraform-providers/terraform-provider-aws/issues/3876, which you can 👍  and subscribe. To consolidate any discussions, I'm going to close this issue in preference of the existing one.
