### ISSUE TITLE
aws_route: better error handling for invalid TGW IDs

### ISSUE THREAD

**Issue by acdha** [terraform-providers/terraform-provider-aws#13830]
## Description

I noticed an area where error handling can be improved for `aws_route`: I accidentally used the `id` attribute of a `aws_ec2_transit_gateway_vpc_attachment` instead of the `transit_gateway_id` attribute but Terraform treats that as a temporary error and continues retrying it even though the invalid ID error can never change.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.26
+ provider.aws v2.66.0
+ provider.http v1.1.1
```

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway_vpc_attachment" "my_tgw" {
  vpc_id             = module.vpc.vpc_id
  transit_gateway_id = var.my_transit_gateway_id
  subnet_ids         = module.vpc.public_subnets
}

# TODO: file bug report for not handling error on incorrect transit_gateway_id

resource "aws_route" "my_tgw_peers" {
  for_each               = toset(concat(module.vpc.public_route_table_ids, module.vpc.private_route_table_ids))
  route_table_id         = each.key
  destination_cidr_block = "…"
  transit_gateway_id     = aws_ec2_transit_gateway_vpc_attachment.my_tgw.id
}
```

### Expected Behavior

Terraform would report the API error stating that the TGW ID was invalid immediately

### Actual Behavior

Terraform looped retrying until timed out, at which point it displayed the error

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@acdha Thanks for raising this issue.
https://github.com/terraform-providers/terraform-provider-aws/pull/13747, which will be released with the upcoming **v2.67.0**, has improved error handling on route creation. Could you please retest your scenario with that version when it's available?

**Comment by acdha** [comment]
Using a fresh build (current as of 94f95ea042592555e3d75d9dbd4856e4814f4e0e) manually installed as 2.67 I see the same retry cycle before displaying the error. Since the input is known before calling this operation, the only case I can think of where it could possibly make sense to wait would be racing RAM share acceptance but I would want to confirm that this is the error given in the case where a share is being completed.

```
aws_route.test_bogon: Creating...
aws_route.test_bogon: Still creating... [10s elapsed]
aws_route.test_bogon: Still creating... [20s elapsed]
aws_route.test_bogon: Still creating... [30s elapsed]
aws_route.test_bogon: Still creating... [40s elapsed]
aws_route.test_bogon: Still creating... [50s elapsed]
aws_route.test_bogon: Still creating... [1m0s elapsed]
aws_route.test_bogon: Still creating... [1m10s elapsed]
aws_route.test_bogon: Still creating... [1m20s elapsed]
aws_route.test_bogon: Still creating... [1m30s elapsed]
aws_route.test_bogon: Still creating... [1m40s elapsed]
aws_route.test_bogon: Still creating... [1m50s elapsed]

Error: Error creating route: InvalidTransitGatewayID.NotFound: The transitGateway ID 'tgw-attach-072af05ad4610c352' does not exist.
	status code: 400, request id: 91e8522c-c610-4056-900a-27aea7f27f75

  on vpc.tf line 245, in resource "aws_route" "test_bogon":
 245: resource "aws_route" "test_bogon" {
```

This 

```diff
diff --git a/versions.tf b/versions.tf
index 2213c0d..cdca9e3 100644
--- a/versions.tf
+++ b/versions.tf
@@ -1,7 +1,7 @@
 terraform {
   required_version = "~> 0.12.26"
   required_providers {
-    aws  = "~> 2.64"
+    aws  = "~> 2.67"
     http = "~> 1.1.1"
   }
 }
diff --git a/vpc.tf b/vpc.tf
index 02a3990..990136c 100644
--- a/vpc.tf
+++ b/vpc.tf
@@ -241,3 +241,9 @@ resource "aws_route" "loc_tgw_peers" {
   destination_cidr_block = each.value[1]
   transit_gateway_id     = aws_ec2_transit_gateway_vpc_attachment.my_tgw.transit_gateway_id
 }
+
+resource "aws_route" "test_bogon" {
+  route_table_id         = module.vpc.public_route_table_ids[0]
+  destination_cidr_block = "10.53.0.0/16"
+  transit_gateway_id     = aws_ec2_transit_gateway_vpc_attachment.my_tgw.id
+}
```

**Comment by ewbankkit** [comment]
The issue here is that route creation retries for 2 minutes if `InvalidTransitGatewayID.NotFound` is returned from the `CreateRoute` AWS API call:

https://github.com/terraform-providers/terraform-provider-aws/blob/6a66a259c634fa03b8fc72459ae19efa6cb395b1/aws/resource_aws_route.go#L277-L293

This was done to deal with eventual consistency issues when creating a Transit Gateway and then immediately creating a route that targets that new TGW.

The resource's default of 2 minutes can be [lowered](https://www.terraform.io/docs/configuration/resources.html#operation-timeouts):

```hcl
resource "aws_route" "example" {
  # ...

  timeouts {
    create = "20s"
  }
}
```
