### ISSUE TITLE
resource/aws_efs_mount_target: Terraform can not validate empty IPv4 address with 2.67.0 

### ISSUE THREAD

**Issue by jamestenglish** [terraform-providers/terraform-provider-aws#13845]
This was fixed in 2.66.0 but seems to have reemerged in 2.67.0
See: https://github.com/terraform-providers/terraform-provider-aws/issues/13626

**Comment by ewbankkit** [comment]
@jamestenglish Thanks for raising this issue.
Could you please add an example configuration that exhibits the problem?

**Comment by brettcat** [comment]
It happens with this module https://github.com/cloudposse/terraform-aws-efs

**Comment by bflad** [comment]
The Terraform module supports Terraform 0.12 syntax so it should be able to pass `null` properly into the `ip_address` argument without provider changes, however we will re-add support for `""` to keep backwards compatibility with other Terraform 0.11 code and track the empty string validation removal as part of https://github.com/terraform-providers/terraform-provider-aws/issues/13943

**Comment by bflad** [comment]
The validation regression fix for the `aws_efs_mount_target` resource has been merged and will release with version 2.69.0 of the Terraform AWS Provider, Thursday next week.
