### ISSUE TITLE
terraform import aws_storagegateway_gateway.example does not import gateway_ip_address property to state file

### ISSUE THREAD

**Issue by AlexisColes** [terraform-providers/terraform-provider-aws#13873]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.25
terraform-provider-aws_v2.67.0_x4

### Affected Resource(s)

aws_storagegateway_gateway

### Terraform Configuration Files

```hcl
resource aws_storagegateway_gateway sgw {  
    gateway_name          = "static_files"
    gateway_timezone      = "GMT"
    gateway_type          = "FILE_S3"
    smb_guest_password    = data.aws_ssm_parameter.smb_guest_password.value
    #gateway_ip_address   = aws_instance.sgw.private_ip
    #gateway_vpc_endpoint = data.aws_vpc_endpoint.sgw_endpoint.dns_entry[0].dns_name

    smb_active_directory_settings {
        domain_name = "foo.com"
        # username and password are only necessary when creating a gateway.  Insert credentials to create
        # this resource but do not check them in.  Leave as empty string for subsequent updates.
        username = ""
        password = ""
    }

    timeouts {
        create = "1m"
    }
}
```

### Expected Behavior

terraform imports the correct information from aws into the state 
terraform plan return  "No changes. Infrastructure is up-to-date."
terraform state show module.storage_gateway.aws_storagegateway_gateway.sgw shows values set for both gateway_ip_address and gateway_vpc_endpoint 

### Actual Behavior
terraform state show module.storage_gateway.aws_storagegateway_gateway.sgw is missing value for gateway_ip_address 
terraform plan wants to replace the resource.

### Steps to Reproduce

1. Due to this [issue](https://github.com/terraform-providers/terraform-provider-aws/issues/9920) we have created a storage gateway manually with the aws ui that matches the above configuration.  And this works ok with terraform-provider-aws_v2.44.0_x4.
2. upgrade to latest terraform-provider-aws_v2.67.0_x4
3. Uncomment gateway_ip_address   
4. Uncomment gateway_vpc_endpoint
5. terraform state rm aws_storagegateway_gateway.sgw 
6. terraform import module.storage_gateway.aws_storagegateway_gateway.sgw arn:aws:storagegateway:region:accountNumber:gateway/sgw-id

### References

* [pull](https://github.com/terraform-providers/terraform-provider-aws/pull/9966)
[issue](https://github.com/terraform-providers/terraform-provider-aws/issues/9920)

**Comment by DrFaust92** [comment]
Hey @AlexisColes,

`gateway_ip_address` cannot be retrieved with the storage gateway api and thus is passed to the state when creating one. import cannot populate `activation_key` or `gateway_ip_address`.

**Comment by AlexisColes** [comment]
Thanks for explaining why this is a problem.

What would you suggest is the best way to move forward from where we are.

At the moment we have just restricted the provider to v2.44.0 but this doesn't seem like a long term solution.

I guess we would rather not destroy and rebuild the gateway as we are providing a 24/7 service. 
 
I had a quick look at the state commands for a way to update the state with this value but could not see one, is there a way to do this do you know?

**Comment by DrFaust92** [comment]
you can  try adding the following to your resource:

```
ignore_changes = ["gateway_ip_address"]
```

**Comment by DrFaust92** [comment]
@AlexisColes, did you try the proposed solution?

**Comment by DrFaust92** [comment]
@bflad, opened https://github.com/terraform-providers/terraform-provider-aws/pull/14878 for doc update
