### ISSUE TITLE
aws_eks_node_group support user data

### ISSUE THREAD

**Issue by duythien** [terraform-providers/terraform-provider-aws#13887]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For currently, https://www.terraform.io/docs/providers/aws/r/eks_node_group.html it work good now, but I want to have a option add user data to provide when launching the instance, some thing like this https://www.terraform.io/docs/providers/aws/r/launch_configuration.html

### New or Affected Resource(s)

- user_data

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by marcincuber** [comment]
user_data is currently not an option from AWS perspective. They simply don't provide configuration option for user_data to be used with eks node groups. 

Before terraform aws provider can support this functionality, it might be worth you tracing the implementation issue -> https://github.com/aws/containers-roadmap/issues/596

**Comment by bflad** [comment]
Hi @duythien 👋  Thank you for submitting this, it would certainly be a nice addition!

As @marcincuber mentions above, this functionality is not supported by the EKS API, therefore we cannot implement support in the Terraform AWS Provider. Once the API implements this functionality, I would imagine by the ability to specify EC2 Launch Templates for EKS Node Groups, we can add it. 👍 

Please follow https://github.com/aws/containers-roadmap/issues/596 and/or open an AWS Support feature request.
