### ISSUE TITLE
aws_cloudfront_distribution.web_acl_id expects ARN, not ID

### ISSUE THREAD

**Issue by shinglyu** [terraform-providers/terraform-provider-aws#13902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.8
AWS provider 2.67

### Affected Resource(s)
* `aws_cloudfront_distribution`
* `aws_wafv2_web_acl`

### Terraform Configuration Files

```hcl
resource "aws_wafv2_web_acl" "example" {
  name        = "rate-based-example"
  description = "Example of a rate based statement."
  scope       = "CLOUDFRONT"

  default_action {
    allow {}
  }

  rule {
    name     = "rule-1"
    priority = 1

    action {
      block {}
    }

    statement {
      rate_based_statement {
        limit              = 10000
        aggregate_key_type = "IP"
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "friendly-rule-metric-name"
      sampled_requests_enabled   = false
    }
  }
  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}

resource "aws_cloudfront_distribution" "s3_distribution" {
  origin {
    // API Gateway
  }

  enabled             = true
  is_ipv6_enabled     = false
  // ...
  web_acl_id = aws_wafv2_web_acl.example.id // <<< This is the issue
}
```

### Expected Behavior
The `web_acl_id` should accept `aws_wafv2_web_acl.example.id`

### Actual Behavior
```
Error: error updating CloudFront Distribution (XXXXXXXXXX): InvalidWebACLId: Web ACL is not accessible by the requester.
	status code: 400, request id: 3cb75e23-79c0-4ab3-8b90-1234567890123456
```

**If I change it to `web_acl_id = aws_wafv2_web_acl.example.arn` it works.** 

So either the `web_acl_id` needs to be rename to `web_acl_arn` or the [documentation](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#top-level-arguments) needs to be updated.

### Steps to Reproduce

1. Create an aws_waf_v2_web_acl. (CLOUDFRONT scope, in us-east-1)
2. Create an aws_cloudfront_distribution that points to an API Gateway, with `web_acl_id = aws_wafv2_web_acl.example.id`
3. `terraform apply`

### Important Factoids
The IAM role I use to run `terraform apply` DO have the `waf:GetWebACL` permission so it's not related to that.

### References

* #0000

**Comment by bflad** [comment]
Relevant documentation pull request: https://github.com/terraform-providers/terraform-provider-aws/pull/13881

**Comment by simontabor** [comment]
Personally I wouldn't call this a documentation issue - a field named `blah_id` should accept the `id`, not an `arn`.

I shouldn't need to open the docs to know which value to set, or to migrate between WAFv1 and WAFv2, but totally understand this is probably a difficult change to make
