### ISSUE TITLE
Importing DynamoDB table with TTL Disabled causes Terraform to try to disable it again

### ISSUE THREAD

**Issue by gchamon** [terraform-providers/terraform-provider-aws#13923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.26
+ provider.aws v2.67.0
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "example" {
    billing_mode   = "PROVISIONED"
    hash_key       = "Path"
    id             = "example"
    name           = "example"
    range_key      = "Key"
    read_capacity  = 5
    stream_enabled = false
    tags           = {
        "Environment" = "prod"
        "Name"        = "example"
    }
    write_capacity = 5

    attribute {
        name = "Key"
        type = "S"
    }
    attribute {
        name = "Path"
        type = "S"
    }

    point_in_time_recovery {
        enabled = true
    }

    timeouts {}

    ttl {
        attribute_name = "TimeToExist"
        enabled        = false
    }
}
```

### Terraform state

```
$ terraform state show aws_dynamodb_table.example

# aws_dynamodb_table.example:
resource "aws_dynamodb_table" "example" {
    arn            = "arn:aws:dynamodb:us-east-1:123484351234:table/example"
    billing_mode   = "PROVISIONED"
    hash_key       = "Path"
    id             = "example"
    name           = "example"
    range_key      = "Key"
    read_capacity  = 5
    stream_enabled = false
    tags           = {
        "Environment" = "prod"
        "Name"        = "example"
    }
    write_capacity = 5

    attribute {
        name = "Key"
        type = "S"
    }
    attribute {
        name = "Path"
        type = "S"
    }

    point_in_time_recovery {
        enabled = true
    }

    timeouts {}

    ttl {
        attribute_name = "TimeToExist"
        enabled        = false
    }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Importing a dynamodb table with `terraform import aws_dynamodb_table.example example` when `example` has ttl disabled for `TimeToExist` attribute should result in an up-to-date plan

### Actual Behavior

Terraform plan tries to modify ttl with `attribute_name = "TimeToExist"`:

```
$ terraform plan -target=aws_dynamodb_table.example
# aws_dynamodb_table.example:
resource "aws_dynamodb_table" "example" {
    arn            = "arn:aws:dynamodb:us-east-1:123484351234:table/example"
    billing_mode   = "PROVISIONED"
    hash_key       = "Path"
    id             = "example"
    name           = "example"
    range_key      = "Key"
    read_capacity  = 5
    stream_enabled = false
      ~ tags           = {
          + "Environment" = "prod"
          + "Name"        = "example"
        }
        write_capacity = 5

        attribute {
            name = "Key"
            type = "S"
        }
        attribute {
            name = "Path"
            type = "S"
        }

        point_in_time_recovery {
            enabled = true
        }

        timeouts {}

      ~ ttl {
          + attribute_name = "TimeToExist"
            enabled        = false
        }
    }
```

### Steps to Reproduce

1. create a dynamodb table manually with aws console or cli
2. disable ttl for `TimeToExist`
2. create a resource of the same name in terraform. Make sure you add to the table resource:

```hcl
  ttl {
    attribute_name = "TimeToExist"
    enabled        = false
  }
```

3. import the table using `terraform import`
4. run `terraform plan`.

### Important Factoids

Using Terraform Cloud

### References

N/A

--------------------------

EDIT: aparently the tags are also being modified in spite of being correct

**Comment by alexsanderp** [comment]
+1

**Comment by DrFaust92** [comment]
after testing this, it seems that if ttl is set to disabled the aws are not returning the attribute_name value.
so one option is to omit the attribute_name value like so
```
 ttl {
    attribute_name = ""
    enabled        = false
  }
```

another option would be to play with `ignore_changes` but i would go for the first option. either way this is an AWS limitation.
