### ISSUE TITLE
new argument for data source: aws_outposts_outpost outpost_arn

### ISSUE THREAD

**Issue by FireballDWF** [terraform-providers/terraform-provider-aws#13929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for arn at argument as that can be derived aws_ec2_local_gateway_route_table but "id" can't without parsing.  Useful for if start with a coip_pool_id or lgw_rt and need to get to outpost attributes like AZ

### New or Affected Resource(s)

* aws_outposts_outpost

### Potential Terraform Configuration

```hcl
arn - (Optional) The arn of the Outpost.
```

### References

* https://www.terraform.io/docs/providers/aws/d/ec2_local_gateway_route_table.html
* https://www.terraform.io/docs/providers/aws/d/outposts_outpost.html

**Comment by bflad** [comment]
Support for `arn` as an argument in this data source has been merged and will release with version 3.5.0 of the Terraform AWS Provider, likely tomorrow. 👍  Thanks to @johnbarney for the implementation.
