### ISSUE TITLE
Feature Request: Data Source for aws_elasticache_replication_group

### ISSUE THREAD

**Issue by ftrossbach** [terraform-providers/terraform-provider-aws#1393]
Hi,

I'm currently using the resource aws_elasticache_replication_group to set up a Redis cluster in ElastiCache that has a different lifecycle than the applications that are using it. For configuration, I'd like to use a data source for this cluster so I can used pass the cluster endpoint(s) to other resources, but there is none yet.

I'm currently using AWS CLI to find it out before to set a Terraform variable
`aws elasticache describe-replication-groups --region eu-west-1 --replication-group-id my_id | jq '.ReplicationGroups[0].ConfigurationEndpoint'.Address'`, but of course a data source would be much nicer.

Cheers!

**Comment by atsushi-ishibashi** [comment]
Close

**Comment by radeksimko** [comment]
@atsushi-ishibashi thanks for the ping, closing.
