### ISSUE TITLE
aws_iam_user_login_profile.user.encrypted_password gives no output

### ISSUE THREAD

**Issue by hussfelt** [terraform-providers/terraform-provider-aws#1394]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_user_login_profile

### Debug Output
None, no crash

### Panic Output
None, no crash

### Expected Behavior
I should have got a base64 pgp encrypted password alongside the other credentials.

### Actual Behavior
The output from ```${aws_iam_user_login_profile.user.encrypted_password}``` is blank.

### Steps to Reproduce
This is an example plan that fails:

```
variable "region" {
    default = "us-east-1"
}

provider "aws" {
    region = "${var.region}"
    assume_role {
        role_arn     = "arn:aws:iam::1234567890:role/admin_access_role"
  }
}

resource "aws_iam_user" "user" {
  name = "user"
  path = "/"
  force_destroy = true
}

resource "aws_iam_access_key" "user" {
  user    = "${aws_iam_user.user.name}"
  pgp_key = "keybase:keybase_username"
}

resource "aws_iam_user_login_profile" "user" {
  user    = "${aws_iam_user.user.name}"
  pgp_key = "keybase:keybase_username"
}

output "password-user" {
  value = "${aws_iam_user_login_profile.user.encrypted_password}"
}

output "key-user" {
  value = "${aws_iam_access_key.user.id}"
}

output "secret-user" {
  value = "${aws_iam_access_key.user.encrypted_secret}"
}
```

### Important Factoids
Clean account, secret access key gives output!

### References
Possibly related to #780

**Comment by Ninir** [comment]
Closing as per the discussion in https://github.com/terraform-providers/terraform-provider-aws/issues/780#issuecomment-321841690
