### ISSUE TITLE
New Data source - aws_vpc_dhcp_options

### ISSUE THREAD

**Issue by wonderphil** [terraform-providers/terraform-provider-aws#1395]
Hi guys,

It bee really good to get a new data source for aws_vpc_dhcp_options.  I know you can get the ID of dhcp options if attached to VPC, but what if its not attached or you do not want to be dependent on the VPC that is attached.

It be great to have

`
data "aws_vpc_dhcp_options" "selected" {
  name         = "some_name"
  domain      = "domain_name"
}
`
having either filter as optional, but at lease one.

Thanks

**Comment by jnahelou** [comment]
+1

**Comment by sroux03** [comment]
+1

**Comment by bflad** [comment]
I'll be taking a look at implementing this in the coming days 👍

**Comment by bflad** [comment]
A new `aws_vpc_dhcp_options` data source will be available in version 1.24.0 of the AWS provider, likely releasing tomorrow. It supports lookup via `dhcp_options_id` and `filter`.

**Comment by sroux03** [comment]
It works like a charm !

**Comment by bflad** [comment]
This has been released in [version 1.24.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1240-june-21-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
