### ISSUE TITLE
aws_kinesis_firehose_delivery_stream for elasticsearch with extended_s3_configuration

### ISSUE THREAD

**Issue by walterd1969** [terraform-providers/terraform-provider-aws#13956]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26
+ provider.aws v2.67.0
+ provider.http v1.2.0
+ provider.local v1.4.0
+ provider.template v2.1.2

### Affected Resource(s)

aws_kinesis_firehose_delivery_stream for elasticsearch with extended_s3_configuration

### Terraform Configuration Files

```hcl
resource "aws_kinesis_firehose_delivery_stream" "CloudtrailsFirehose1ToElasticsearch" {
  name        = "${var.cloudtrail_firehose_1_name}"
  destination = "elasticsearch"

  server_side_encryption {
    enabled              = "true"
  }

  extended_s3_configuration {
    role_arn             = "${module.CloudTrailFirehose1Role.arn}"
    bucket_arn           = "${module.FirehoseFailedDeliveryBucket.arn}"
    error_output_prefix  = "cloudtrails/"
    buffer_size          = "${var.s3_buffer_size}"
    buffer_interval      = "${var.s3_buffer_interval}"
    compression_format   = "${var.s3_compression}"
    prefix               = "cloudtrails/"
    kms_key_arn          = "${module.ESKMS.key_arn}"

    cloudwatch_logging_options {
      enabled              = "true"
      log_group_name       = "/aws/kinesisfirehose/sdl_cloudtrail_firehose_1"
      log_stream_name      = "S3Delivery"
    }     
  }

  elasticsearch_configuration {
    domain_arn = "${module.Elasticsearch.arn}"
    role_arn   = "${module.CloudTrailFirehose1Role.arn}"
    index_name = "${var.cloudtrail_es_index_name}"
    
    type_name  = ""
    index_rotation_period = "OneDay"

    s3_backup_mode = "FailedDocumentsOnly"
    buffering_interval = "${var.buffer_interval}"
    buffering_size     = "${var.buffer_size}"
    retry_duration     = "300"

    vpc_config {
      role_arn           = "${module.CloudTrailFirehose1Role.arn}"
      security_group_ids = flatten(["${aws_security_group.firehose_es_sg.id}"])
      subnet_ids         = flatten(["${data.aws_subnet_ids.app1_subnet.ids}"])
    }   

    cloudwatch_logging_options {
      enabled              = "true"
      log_group_name       = "/aws/kinesisfirehose/sdl_cloudtrail_firehose_1"
      log_stream_name      = "ElasticsearchDelivery"
    }       
  }
}
```

### Expected Behavior

The need for "extended_s3_configuration" is driven by the need for "error_output_prefix".  I expected this to work, since extended_s3_configuration can be used in place of "s3_configuration".

### Actual Behavior

On "terraform apply" I get this error.
```
Error: When destination is elasticsearch, s3_configuration is required

  on firehose.tf line 82, in resource "aws_kinesis_firehose_delivery_stream" "CloudtrailsFirehose1ToElasticsearch":
  82: resource "aws_kinesis_firehose_delivery_stream" "CloudtrailsFirehose1ToElasticsearch" {

```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

NOTE: I tried using both "s3_configuration" and "extended_s3_configuration", but that doesn't work.
It seems I cannot use any extended_s3_configuration items for elasticsearch.

### References

* #0000

**Comment by rsclarke-vgw** [comment]
When the destination is set to `elasticsearch` the S3 backup configuration should be defined in a `s3_configuration` block and not `extended_s3_configuration`.

The issue seems related to adding `error_output_prefix` to the `s3_configuration` block which is raised in PR #13416

**Comment by bflad** [comment]
Hi folks 👋  As mentioned above, this functionality needs to be implemented in the existing `s3_configuration` configuration block as part of https://github.com/terraform-providers/terraform-provider-aws/issues/7997.

Please 👍  react and subscribe to that issue for further discussions and efforts.
