### ISSUE TITLE
aws_ebs_volume filter 'attachment.device_name' is invalid

### ISSUE THREAD

**Issue by igoratencompass** [terraform-providers/terraform-provider-aws#13969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.10
+ provider.aws v2.68.0
+ provider.local v1.4.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

```hcl
data "aws_ebs_volume" "ebs-volume" {
  filter {
    name   = "volume-type"
    values = ["gp2"]
  }

  filter {
    name   = "attachment.device_name"
    values = ["/dev/sde"]
  }

  most_recent = true
}
```

### Expected Behavior

Expect for `aws_ebs_volume` support the filter `attachment.xxxxxx` options as per https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-volumes.html

The corespondent AWS CLI command tested and certainly works:

```
$ aws ec2 describe-volumes --filters Name="volume-type",Values="gp2" Name="attachment.device",Values="/dev/sde" --region=eu-west-2
```

### Actual Behavior

Get error during apply:

```
Error: InvalidParameterValue: The filter 'attachment.device_name' is invalid
	status code: 400, request id: 2228647a-780a-4be0-826f-5a8b8fb878c2

  on modules/app/main.tf line 37, in data "aws_ebs_volume" "ebs-volume":
  37: data "aws_ebs_volume" "ebs-volume" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @igoratencompass 👋  We do not perform any modification of the filters when converting from the configuration to the API call and this appears to be a typo in your configuration, where `attachment.device` is `attachment.device_name` above. For example, this configuration works (by successfully calling the API):

```hcl
terraform {
  required_providers {
    aws = "2.68.0"
  }

  required_version = "0.12.26"
}

provider "aws" {
  region = "us-west-2"
}

data "aws_ebs_volume" "test" {
  filter {
    name   = "volume-type"
    values = ["gp2"]
  }

  filter {
    name   = "attachment.device"
    values = ["/dev/sde"]
  }

  most_recent = true
}
```

```console
$ terraform apply
data.aws_ebs_volume.test: Refreshing state...

Error: Your query returned no results. Please change your search criteria and try again.

  on main.tf line 13, in data "aws_ebs_volume" "test":
  13: data "aws_ebs_volume" "test" {
```

Hope this helps.

**Comment by igoratencompass** [comment]
thanks @bflad , no idea where did I pick the `device_name` from I could swear it was from the AWS CLI page but maybe I've been looking at outdated one :-/
