### ISSUE TITLE
Allow aws_client_vpn_endpoint to support multiple authentication_options

### ISSUE THREAD

**Issue by choonming** [terraform-providers/terraform-provider-aws#13983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking at the current aws_client_vpn_endpoint resource, I am able to create a CVPN endpoint but only with a single authentication option. The aws cli documentation shows that it is possible to create a list of authentication options instead of just one.

### New or Affected Resource(s)

* aws_ec2_client_vpn_endpoint

### Potential Terraform Configuration

```hcl
resource "aws_ec2_client_vpn_endpoint" "vpn" {
  description            = var.description
  server_certificate_arn = var.server_certificate_arn
  client_cidr_block      = var.client_cidr_block
  split_tunnel           = var.split_tunnel
  transport_protocol     = var.transport_protocol
  authentication_options  = [
    {
      type                = "directory-service-authentication"
      active_directory_id = var.active_directory_id
    }, 
    {
      type                       = "certificate-authentication"
      root_certificate_chain_arn = var.root_certificate_chain_arn
    }
  ]
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/ec2/create-client-vpn-endpoint.html

**Comment by gdavison** [comment]
Hi @choonming. What version of the Terraform AWS provider are you currently using? We added the ability to add a second authentication option in version 2.58.0, released April 16, 2020.

**Comment by choonming** [comment]
@gdavison I am able to create this now after upgrading the provider. Many thanks! I will remember to update the providers first before posting again! :)
