### ISSUE TITLE
Missing EC2 dependency when destroying OpsWorks stack

### ISSUE THREAD

**Issue by mclate** [terraform-providers/terraform-provider-aws#14]
When destroying OpsWorks cluster it seems like there is missing dependency: All OpsWorks objects should depend on OpsWorks instance, so that when stack is being destroyed, all instances are destroyed first and only then any other resources should be destroyed. Otherwise all sorts of weird behavior can happen (such as OpsWorks not being able to destroy instance because Terraform already destroyed its IAM role that allowed OpsWorks to act on EC2 instances)

### Terraform Version
`Terraform v.0.9.4`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_opsworks_stack
- aws_opsworks_instance
- aws_opsworks_*

### Terraform Configuration Files
Basic configuration for OpsWorks stack with some aws_opsworks_instance resources.

### Expected Behavior
Terraform shoud wait for all EC2 instances being destroyed before destroying any other aws_opswors_* resources

### Actual Behavior
aws_opsworks_* resources are being deleted regardless of whether aws_opsworks_instance has been destroyed or not.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Configure, build and apply OpsWorks stack without any aws_opsworks_instance resources
2. Destroy given stack - it's being destroyed as epected
3. Create same stack with one aws_opsworks_instance resource
4. Destroy stack - behavior undefined (race condition in resources being destroyed)

**Comment by bishtawi** [comment]
This is the same as #160.

I solved this bug by doing:

```
resource "aws_opsworks_instance" "bastion" {
  ...

  depends_on = [
    "aws_iam_role_policy.service",
  ]
}
```

**Comment by bflad** [comment]
Thanks for the note, @bishtawi 👍 That fix does seem appropriate -- any IAM Role permissions resources (such as `aws_iam_role_policy` and `aws_iam_role_policy_attachment`) need to explicitly have their dependency denoted with `depends_on` so Terraform properly orders creation and deletion operations.

If there are suggestions for improving the documentation (similar to what we did recently with [EKS](https://github.com/terraform-providers/terraform-provider-aws/pull/11092/files)), please feel free to create a new GitHub issue or submit a pull request and we'll take a look. 😄
