### ISSUE TITLE
IAM Role with policies created but not available for dependent resources

### ISSUE THREAD

**Issue by ciaranevans** [terraform-providers/terraform-provider-aws#14008]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

TF Version: `0.12.28`
Provider Version: `2.68.0`

### Affected Resource(s)

* aws_iam_policy_document
* aws_iam_role
* aws_iam_policy
* aws_iam_role_policy_attachment
* aws_sfn_state_machine

### Terraform Configuration Files

```hcl
data aws_iam_policy_document step-assume-role-policy {
    statement {
        sid = "AssumeRoleBatch"
        actions = ["sts:AssumeRole"]
        principals {
            identifiers = ["states.amazonaws.com"]
            type = "Service"
        }
    }
}

resource aws_iam_role role {
    name = "role"
    assume_role_policy = data.aws_iam_policy_document.step-assume-role-policy.json
    tags = var.tags
}

resource aws_iam_policy execution-policy {
    name = "execution-policy"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "batch:SubmitJob"
            ],
            "Resource": [
                "${var.job-definition}",
                "${var.job-queue}"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "batch:DescribeJobs",
                "batch:ListJobs"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "events:PutTargets",
                "events:PutRule",
                "events:DescribeRule"
            ],
            "Resource": [
                 "*"
            ]
        }
    ]
}
EOF
}

resource aws_iam_role_policy_attachment execution-policy {
    policy_arn = aws_iam_policy.execution-policy.arn
    role = aws_iam_role.role.name
}

resource aws_sfn_state_machine state-machine {
    name = "state_machine"
    definition = data.template_file.state-machine.rendered
    role_arn = aws_iam_role.role.arn
    tags = var.tags
}
```
### Expected Behavior

* IAM Role created
* IAM Policy created
* IAM Policy attached to Role
* Step Function created with Role

### Actual Behavior

* IAM Role created
* IAM Policy created
* IAM Policy attached to Role
* Step Function **not created**

Error output:

```
module.step-function.aws_iam_role_policy_attachment.execution-policy: Creation complete after 1s [id=role-20200701081442869700000006]

Error: Error creating Step Function State Machine: AccessDeniedException: 'arn:aws:iam::<BLANKED>:role/role' is not authorized to create managed-rule.
	status code: 400, request id: d215c4f0-61b6-470a-b08b-c8a77696895e

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It should be noted that doing a further `terraform apply` **after** the failure results in the Step Function being correctly deployed. 

I've also tried doing:

```hcl
resource time_sleep wait-1-min {
    depends_on = [aws_iam_role_policy_attachment.execution-policy]
    create_duration = "1m"
}

resource aws_sfn_state_machine state-machine {
    name = "state_machine"
    definition = data.template_file.state-machine.rendered
    role_arn = aws_iam_role.role.arn
    tags = var.tags
    depends_on = [
        time_sleep.wait-1-min,
    ]
}
```

Which works successfully after a **single** `terraform apply`. 

I can only assume this is due to IAM being eventually consistent, but I would expect Terraform to either retry or have some form of logic to ensure that the IAM is actually available before carrying on. If I make the State Machine depend on the role, I still see a failure. 

I'd rather not rely on a `wait` as the fix for this 😆

**Comment by bflad** [comment]
The fix to allow the `aws_sfn_state_machine` resource to retry IAM Role associated failures on creation has been merged and will release with version 2.69.0 of the Terraform AWS Provider, likely tomorrow. Thanks to @DrFaust92 for the implementation. 👍
