### ISSUE TITLE
AWS apigatewayv2 integrations - https endpoint (ServerNameToVerify)

### ISSUE THREAD

**Issue by msirovy** [terraform-providers/terraform-provider-aws#14015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

apigatewayv2 integration is not able to configure https endpoint because there is no way how to define parameter ServerNameToVerify.

### New or Affected Resource(s)

The aws api request should looks like this way
```
{
    "Items": [
        {
            "ConnectionType": "VPC_LINK",
            "IntegrationMethod": "ANY",
            "IntegrationType": "HTTP_PROXY",
            "IntegrationUri": "arn:aws:elasticloadbalancing:eu-central-1:XXXXXXXXX:listener/app/lb/d----------------4",
            "PayloadFormatVersion": "1.0",
            "TimeoutInMillis": 29000,


            "TlsConfig": {
                "ServerNameToVerify": "valid.domain.tld"
            }


        }
    ]
}
```

It allows me to use https lb etc.

### Potential Terraform Configuration

```hcl
resource "aws_apigatewayv2_integration" "my_api" {
    api_id                          = aws_apigatewayv2_api.api.id
    connection_id                   = aws_apigatewayv2_vpc_link.vpc_link.id
    connection_type                 = "VPC_LINK"
    integration_method              = "ANY"
    integration_type                = "HTTP_PROXY"
    integration_uri                 = aws_lb_listener.https.arn        
    passthrough_behavior            = "WHEN_NO_MATCH"
    payload_format_version          = "1.0"


    HTTPS_HOSTNAME.           = "valid.domain.tld"


    request_templates               = {}
    timeout_milliseconds            = 29000
}
```

**Comment by ewbankkit** [comment]
@msirovy Thanks for raising this issue.
It has already been noticed in #12971 (missing `tls_config` for `aws_apigatewayv2_integration`) and is being addressed in #13013. I will close this issue as a duplicate.
Please add any additional information to the linked issue.
