### ISSUE TITLE
Various EC2 resources: Tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#14011]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

##### 2020-06-30

> Added support for tag-on-create for CreateVpc, CreateEgressOnlyInternetGateway, CreateSecurityGroup, CreateSubnet, CreateNetworkInterface, CreateNetworkAcl, CreateDhcpOptions and CreateInternetGateway. You can now specify tags when creating any of these resources.

##### 2020-07-20

> Added support for tag-on-create for CreateVpcPeeringConnection and CreateRouteTable. You can now specify tags when creating any of these resources.

##### 2020-07-28

> Introduces support for tag-on-create capability for the following APIs: CreateVpnConnection, CreateVpnGateway, and CreateCustomerGateway.

##### 2020-06-30

* `aws_vpc`
* `aws_egress_only_internet_gateway`
* `aws_security_group`
* `aws_subnet`
* `aws_network_interface`
* `aws_network_acl`
* `aws_vpc_dhcp_options`
* `aws_internet_gateway`

##### 2020-07-20

* `aws_route_table`
* `aws_vpc_peering_connection`
* `aws_vpc_peering_connection_accepter`

##### 2020-07-28

* `aws_customer_gateway`
* `aws_vpn_connection`
* `aws_vpn_gateway`

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-vpc-resources-support-tag-on-create/).
[Announcement for Site-to-Site VPN resources](https://aws.amazon.com/about-aws/whats-new/2020/07/aws-site-to-site-vpn-supports-tagging-resources-creation-resource-level/).

##### 2020-06-30

Requires [AWS SDK v1.32.13](https://github.com/aws/aws-sdk-go/releases/tag/v1.32.13):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14000

##### 2020-07-20

Requires [AWS SDK v1.33.8](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.8):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14000

##### 2020-07-28

Requires [AWS SDK v1.33.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.14):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14000

**Comment by Firefishy** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/14114 is likely a related ticket.

**Comment by bflad** [comment]
Support for these has been merged and will release with version 3.3.0 of the Terraform AWS Provider, likely tomorrow. 👍
