### ISSUE TITLE
BadRequestException: Execution logs are not supported on protocolType HTTP

### ISSUE THREAD

**Issue by paliwalvimal** [terraform-providers/terraform-provider-aws#14010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_apigatewayv2_stage

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_stage" "stage" {
  api_id      = aws_apigatewayv2_api.api.id
  name        = var.tier
  auto_deploy = true
  description = "${var.tier} stage"

  tags = {
    Tier    = var.tier
    Project = var.project_name
    Group   = "backend"
    Module  = "app"
  }
}
```

### Expected Behavior

Should create/update API Gateway stage accordingly.

### Actual Behavior

Resource block fails during update with the below error as Terraform tries to add `logging_level` parameter to `default_route_settings` block which is not supported for HTTP API

```hcl
# aws_apigatewayv2_stage.stage will be updated in-place
  ~ resource "aws_apigatewayv2_stage" "stage" {
        api_id          = "xxxxxx"
        arn             = "arn:aws:apigateway:ap-south-1::/apis/xxxxxx/stages/dev"
        auto_deploy     = true
        description     = "dev stage"
        execution_arn   = "arn:aws:execute-api:ap-south-1:xxxxxx:xxxxxx/dev"
        id              = "dev"
        invoke_url      = "wss://xxxxxx.execute-api.ap-south-1.amazonaws.com/dev"
        name            = "dev"
        stage_variables = {}
        tags            = {
            "Group"   = "backend"
            "Module"  = "app"
            "Project" = "xxxxxx"
            "Tier"    = "dev"
        }

      ~ default_route_settings {
            data_trace_enabled       = false
            detailed_metrics_enabled = false
          + logging_level            = "OFF"
            throttling_burst_limit   = 0
            throttling_rate_limit    = 0
        }
    }
```

Fails with error: BadRequestException: Execution logs are not supported on protocolType HTTP

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@paliwalvimal Thanks for raising this issue.
It has already been noticed in https://github.com/terraform-providers/terraform-provider-aws/issues/13801 and is being addressed in https://github.com/terraform-providers/terraform-provider-aws/pull/13809. I will close this issue as a duplicated.
Please add any additional information to the linked issue.
