### ISSUE TITLE
apigateway v2 resource "aws_apigatewayv2_domain_name" missing target_domain_name output

### ISSUE THREAD

**Issue by karl-cardenas-coding** [terraform-providers/terraform-provider-aws#14049]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

AWS Provider 2.69

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_domain_name" "api" {
  domain_name = var.api-domain-name
  tags        = var.tags

  domain_name_configuration {
    certificate_arn = aws_acm_certificate.api-cert.arn
    endpoint_type   = "REGIONAL"
    security_policy = "TLS_1_2"
  }
  depends_on = [aws_acm_certificate.api-cert]
}

resource "aws_route53_record" "api-alias" {
  zone_id = data.aws_route53_zone.primary.zone_id
  name    = var.api-domain-name  
  type    = "A"
  ttl     = "60"
  records = ["${????????????????}-execute-api.${var.region}.amazonaws.com"] // This is where the target_domain is needed
  depends_on = [aws_apigatewayv2_domain_name.api]
}

```
### Expected Behavior

To be able to to continue to create the API Gateway life cycle through Terraform

### Actual Behavior

The `aws_apigatewayv2_domain_name` resource is not outputting the the target_domain id

**Comment by ewbankkit** [comment]
@karl-cardenas-coding Thanks for raising this issue.
The target domain name should be available at:

```hcl
"${aws_apigatewayv2_domain_name.api.domain_name_configuration.0.target_domain_name}"
```

I have opened #12920 to make this more clear in the documentation.

**Comment by karl-cardenas-coding** [comment]
@ewbankkit Awesome, and thank you for replying so quickly!
