### ISSUE TITLE
Organizations Backup policy support

### ISSUE THREAD

**Issue by AFriemann** [terraform-providers/terraform-provider-aws#14055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS added support for organization wide backup policies, support for those would be highly appreciated.

probably needs to be added here, but I'm a terrible Golang dev:

https://github.com/terraform-providers/terraform-provider-aws/blob/9900515b28b413505e5dd7c8d8ea258c59515f32/aws/resource_aws_organizations_policy.go#L49

### New or Affected Resource(s)

* aws_organizations_policy

### References

* https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup.html

**Comment by bflad** [comment]
Hi @AFriemann 👋  Thank you for submitting this and your intuition about where the code change needed to happen was correct. Submitted this on your behalf: https://github.com/terraform-providers/terraform-provider-aws/pull/14060

**Comment by AFriemann** [comment]
awesome, thank you @bflad ! :)

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.70.0 of the Terraform AWS provider, later this week. 👍
