### ISSUE TITLE
terraform_remote_state data source requires same version of terraform

### ISSUE THREAD

**Issue by craigedmunds** [terraform-providers/terraform-provider-aws#14056]
We have an issue at the moment whereby a 3rd party terraform state file that we use within our project has been produced by an upgraded version of terraform (0.12.26). We currently use terraform 0.12.24. Terraform is validating that these versions align and so currently all our applies are currently failing with the error:

state snapshot was created by Terraform v0.12.26, which is newer than current v0.12.24; upgrade to Terraform v0.12.26 or greater to work with this state

Terraform Version
We are running 0.12.24 and reading a state file that uses 0.12.26

`
data terraform_remote_state networks {
  backend = "s3"
  config = {
    bucket = var.source_state_bucket
    region = data.aws_region.current.name
    key    = var.source_networks_tfstate
  }
}
`

Expected Behavior
We don't want to be forced to upgrade when projects which we depend on upgrade themselves. Perhaps this validation should be optional, maybe by allowing one to specify that the check shouldn't take place:

`
data terraform_remote_state networks {
  backend = "s3"
  disable_version_check = true
  config = {
    bucket = var.source_state_bucket
    region = data.aws_region.current.name
    key    = var.source_networks_tfstate
  }
}
`

Actual Behavior
state snapshot was created by Terraform v0.12.26, which is newer than current v0.12.24; upgrade to Terraform v0.12.26 or greater to work with this state

This is also reported in the main terraform repo as I wasn't sure where it belongs https://github.com/hashicorp/terraform/issues/25487

**Comment by bflad** [comment]
Hi @craigedmunds 👋  Thank you for submitting this and sorry you are running into trouble here.

Terraform Providers, such as the Terraform AWS Provider, have no influence over this restriction. The logic that handles remote state handling and versioning is entirely upstream within Terraform core and its built-in `terraform` provider. Given that you already filed an issue there, our best recommendation would be to follow https://github.com/hashicorp/terraform/issues/25487. 👍
