### ISSUE TITLE
aws_cloudwatch_metric_alarm: Document PutMetricAlarm API for Anomaly detection based alarms

### ISSUE THREAD

**Issue by useafterfree** [terraform-providers/terraform-provider-aws#14066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.21
 aws      ">= 2.7.0" ## resolves to terraform-provider-aws_v2.68.0_x4 ??

### Affected Resource(s)

* aws_cloudwatch_metric_alarm

### Terraform Configuration Files
```
locals {
  lambdaMethods = ["bob"] ## List of methods we want to attach to
}

resource "aws_cloudwatch_metric_alarm" "lambda_duration_anomaly_alarms" {
  count = length(local.lambdaMethods)
  alarm_name                = "${local.lambdaMethods[count.index]}LambdaDurationAnomaly"
  comparison_operator       = "GreaterThanUpperThreshold" ### <------- out of band should be here
  evaluation_periods        = "1"
  threshold_metric_id       = "e1"
  alarm_description         = "This metric monitors lambda duration anomalous behavior"
  insufficient_data_actions = []
  treat_missing_data        = "notBreaching"
  alarm_actions = var.alarm_actions

  metric_query {
    id          = "e1"
    expression  = "ANOMALY_DETECTION_BAND(m1, 2)"
    label       = "Duration (Expected) (${local.lambdaMethods[count.index]})"
    return_data = "true"
  }

  metric_query {
    id          = "m1"
    return_data = "true"
    metric {
      metric_name = "Duration"
      namespace   = "AWS/Lambda"
      period      = "3600"
      stat        = "Maximum"
      unit        = "Milliseconds"

      dimensions = {
        FunctionName = "${local.lambdaMethods[count.index]}"
      }
    }
  }
}

```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
To be able to tell terraform to set outside of band detection to alarm

### Actual Behavior
It's impossible.

### Steps to Reproduce
`terraform plan; terraform apply`

```
Error: Updating metric alarm failed: ValidationError: 1 validation error detected: Value 'OutsideOfTheBand' at 'comparisonOperator' failed to satisfy constraint: Member must satisfy enum value set: [GreaterThanThreshold, LessThanThreshold, LessThanOrEqualToThreshold, GreaterThanOrEqualToThreshold]
```

**Comment by useafterfree** [comment]
I just learned that `LessThanLowerOrGreaterThanUpperThreshold` Will allow for this functionality!


Would it be possible to add this to the documentation? I might have time to make a PR.

**Comment by bflad** [comment]
Hi @useafterfree 👋  The documentation for the `aws_cloudwatch_metric_alarm` resource lives in this repository at  [`website/docs/r/cloudwatch_metric_alarm.html.markdown`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/cloudwatch_metric_alarm.html.markdown), if you would like to contribute an update.

**Comment by useafterfree** [comment]
> Hi @useafterfree 👋 The documentation for the `aws_cloudwatch_metric_alarm` resource lives in this repository at [`website/docs/r/cloudwatch_metric_alarm.html.markdown`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/cloudwatch_metric_alarm.html.markdown), if you would like to contribute an update.

It looks like it was added already in `5caa5ba`! Wow. How did I miss it?

![image](https://user-images.githubusercontent.com/35079898/86673410-7ff0f780-bfac-11ea-91a2-65aa73238c01.png)

https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html
