### ISSUE TITLE
Add support for import of ECS Service

### ISSUE THREAD

**Issue by alex-derzhi-sp** [terraform-providers/terraform-provider-aws#1406]
Currently, the aws_ecs_service resource does not support `import`.  This makes it difficult to migrate an ECS-centric deployment to be managed by Terraform.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
