### ISSUE TITLE
aws_iam_role role_name deprecation doesn't allow to use both syntaxes

### ISSUE THREAD

**Issue by dvishniakov** [terraform-providers/terraform-provider-aws#1408]
### Terraform Version 0.10.0
latest providers

### Affected Resource(s)
- aws_iam_role

### Terraform Configuration Files
```hcl
data "aws_iam_role" "service_role" {
  role_name = "test_role_name"
}
```

### Debug Output
Warnings:
  * module.XYZ.data.aws_iam_role.service_role: "role_name": [DEPRECATED] Use `name` instead
...
... error(s) occurred:
* module.XYZ.data.aws_iam_role.service_role: "name": required field is not set

### Expected Behavior
`role_name` should be properly deprecated by allowing to use it without requiring to set the new `name`

### Actual Behavior
Resource schema validation produces an error because `name` is required: https://github.com/terraform-providers/terraform-provider-aws/commit/a7f45e710d817e056bd9de7fdd147bfb01540547#diff-5d7b67112bde2aed1e41c623ab98ca9dR50
from this commit https://github.com/terraform-providers/terraform-provider-aws/commit/a7f45e710d817e056bd9de7fdd147bfb01540547

### Steps to Reproduce
`terraform plan`

FYI @Ninir

**Comment by Ninir** [comment]
Hey @dvishniakov 

Woops, this is a complete oversight there! I first combined `Required` & the `Removed` attributes and went for `Optional` and `Deprecated` afterwards.

FIxing right now!

Sorry for the noise :/

**Comment by Ninir** [comment]
Just throw a fix for that, and checked locally.

Again, sorry for the noise.. !

**Comment by dvishniakov** [comment]
Thank you for the fast fix, @Ninir !
