### ISSUE TITLE
AWS S3 Bucket Policy Documentation missing

### ISSUE THREAD

**Issue by flacito** [terraform-providers/terraform-provider-aws#1410]
https://www.terraform.io/docs/providers/aws/r/s3_bucket_policy.html

Not much there. Gonna have to go read the code to get it right.

**Comment by coingraham** [comment]
@flacito are you expecting something like https://www.terraform.io/docs/providers/aws/r/iam_group_policy_attachment.html ?

**Comment by flacito** [comment]
I guess it would be nice to have a functional policy instead of something like "#omitted".  Most of the resources are well-documented and create functional AWS artifact(s).  That's all.  I did figure out how to get it going from the the main [s3_bucket](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) documentation. So I'm good.

Go ahead and close if you think the page is OK.

**Comment by coingraham** [comment]
I'll look at doing a PR in reference to this Issue sometime this week and see what the devs think.

**Comment by flacito** [comment]
Wow thanks.  Tremendously responsive support!

**Comment by coingraham** [comment]
@flacito Take a look at my PR and see what you think.

**Comment by flacito** [comment]
Sorry couldn't get to it until now. Took a look. Great change.  

You guys are super responsive.   THANKS!
