### ISSUE TITLE
Acceptance test sweeper: `aws_cognito_user_pool` with dependency on domain causes error

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#14102]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource

* aws_cognito_user_pool

### Description

The sweeper fails with the error message

```
Error running Sweeper (aws_cognito_user_pool) in region (us-west-2): Error deleting Cognito User Pool tf-test-9207420729894523345: InvalidParameterException: User pool cannot be deleted. It has a domain configured that should be deleted first.
```

**Comment by bflad** [comment]
@gdavison we are consistently hitting this in both accounts -- is this work in progress or can someone pick this up?
