### ISSUE TITLE
aws_apigatewayv2_domain_name attributes and outputs

### ISSUE THREAD

**Issue by Skyfallz** [terraform-providers/terraform-provider-aws#14112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
 Hi,

I don't really get how we are supposed to get the target_domain_name on an apigatewayv2_domain_name (ie, for setting a CNAME on it). The target_domain_name is considered a computed argument (and I can see the value I need in the tfstate), but shouldn't it be an attribute instead ? Or is there a way to access a "computed" argument value ?

### New or Affected Resource(s)

* [apigatewayv2_domain_name](https://www.terraform.io/docs/providers/aws/r/apigatewayv2_domain_name.html)
hosted_zone_id - (Computed) The Amazon Route 53 Hosted Zone ID of the endpoint.
target_domain_name - (Computed) The target domain name. 

### Potential Terraform Configuration

```hcl
resource "aws_route53_record" "project" {
  zone_id = data.aws_route53_zone.project.zone_id
  name    = "www.project.org"
  type    = "CNAME"
  ttl     = "60"
  records = [
    aws_apigatewayv2_domain_name.project.target_domain_name
  ]
}

resource "aws_apigatewayv2_domain_name" "project" {
  domain_name = "www.project.org"

  domain_name_configuration {
    certificate_arn = data.aws_acm_certificate.project.arn
    endpoint_type   = "REGIONAL"
    security_policy = "TLS_1_2"
  }
}
```
does not work, as target_domain_name is not considered as attribute.

**Comment by ewbankkit** [comment]
@Skyfallz  Thanks for raising this issue.
The target domain name should be available at:

```hcl
"${aws_apigatewayv2_domain_name.api.domain_name_configuration.0.target_domain_name}"
```

I have opened #12920 to make this more clear in the documentation.

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/14049
* https://github.com/terraform-providers/terraform-provider-aws/issues/12892

**Comment by Skyfallz** [comment]
Just understood it by myself after reading the .tfstate file too, but thanks ! This indeed works.

Agreed that doc could be a little more explicit on this one, thanks for your work anyway !

**Comment by bflad** [comment]
The above documentation update has been merged and will deploy when we release version 2.70.0 of the Terraform AWS Provider later today. 👍
