### ISSUE TITLE
Terraform is not supporting Aurora Postgres DB creation

### ISSUE THREAD

**Issue by prabhakar81** [terraform-providers/terraform-provider-aws#1412]
Hi,

I am trying to create Aurora Postgres database using terraform but I don't see any engine parameter in aws_rds_cluster and if i give any value for that parameter then i keep on getting

Errors:

aws_rds_cluster.default: "engine": this field cannot be set
If i don't provide this parameter then it ends up creating Aurora MySQL database.

I had raised this issue https://github.com/hashicorp/terraform/issues/15803 under core but have been advised to raise it here. I am able to create Aurora Postgres database using Cloud Formation.

**Comment by stack72** [comment]
Hi @prabhakar81 

I just added the ability to set the `engine` in Terraform - but, the AWS SDK doesn't actually support creating postgres 

I am tracking this issue as https://github.com/aws/aws-sdk-go/issues/1470

When this is done, I will update the SDK

Paul

**Comment by sheldonkwok** [comment]
As of https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11231-2017-11-20

the sdk now supports postgres rds aurora

**Comment by vr001** [comment]
Have been reading about the issues around it. So, i believe now one can spin up a amazon aurora postgress compatible by setting engine=aurora-postgresql in aws_rds_cluster_instance resource. Correct me if I am wrong. Thanks.

**Comment by jacobwgillespie** [comment]
@vr001 you are correct, it is possible to launch PostgreSQL Aurora clusters by setting `engine = "aurora-postgresql"`.

**Comment by panuhorsmalahti** [comment]
It would be useful to document the possible engine values here:
https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html#engine

**Comment by vr001** [comment]
@panuhorsmalahti here we go. 
https://github.com/terraform-providers/terraform-provider-aws/pull/3768
My second PR (though its a doc change) !

**Comment by bflad** [comment]
The documentation is updated in master via the PR above and will release when we push out v1.12.0 of the AWS provider. 🎉  Thanks @vr001!
