### ISSUE TITLE
AISERVICES_OPT_OUT_POLICY not yet supported by aws_organizations enabled_policy_types attribute

### ISSUE THREAD

**Issue by dehuszar** [terraform-providers/terraform-provider-aws#14142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I see now that `BACKUP_POLICY` is hot off the presses in v2.70.0. Unfortunately, `aws_organizations` resource still does not support the `enabled_policy_types` value of `AISERVICES_OPT_OUT_POLICY`.

Attempts to run a plan utilizing this policy type produces the following errors:

```
Error: expected enabled_policy_types.0 to be one of [BACKUP_POLICY SERVICE_CONTROL_POLICY TAG_POLICY], got AISERVICES_OPT_OUT_POLICY

  on organizations.tf line 1, in resource "aws_organizations_organization" "org":
   1: resource "aws_organizations_organization" "org" {



Error: expected type to be one of [BACKUP_POLICY SERVICE_CONTROL_POLICY TAG_POLICY], got AISERVICES_OPT_OUT_POLICY

  on organizations.tf line 44, in resource "aws_organizations_policy" "ai_opt_out_policies":
  44: resource "aws_organizations_policy" "ai_opt_out_policies" {
```

### New or Affected Resource(s)

* aws_organizations

### Potential Terraform Configuration

```hcl
resource "aws_organizations_organization" "org" {
  feature_set = "ALL"
  enabled_policy_types = ["AISERVICES_OPT_OUT_POLICY"]
}

resource "aws_organizations_policy" "ai_opt_out_policies" {
  description = "Claims to Prevent AWS from getting nosey with our AI data to 'improve their services'"
  name = "ai-opt-out-policies"
  type = "AISERVICES_OPT_OUT_POLICY"

  content = <<CONTENT
{
  "services": {
    "default": {
      "opt_out_policy": {
        "@@operators_allowed_for_child_policies": ["@@none"],
        "@@assign": "optOut"
      }
    }
  }
}
CONTENT
}
```
### References

* [Current AWS Organizations SDK docs](https://docs.aws.amazon.com/organizations/latest/APIReference/API_EnablePolicyType.html#API_EnablePolicyType_RequestSyntax)

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.33.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.4):
* #14000

**Comment by shuheiktgw** [comment]
I've added support for `AISERVICES_OPT_OUT_POLICY ` https://github.com/terraform-providers/terraform-provider-aws/pull/14528

**Comment by bflad** [comment]
Support for managing these policies in the `aws_organizations_policy` resource has been merged and will release with version 3.2.0 of the Terraform AWS Provider, likely tomorrow. Thank you to @shuheiktgw for the implementation. 👍 

Since this also requires an adjustment to the `aws_organizations_organization` resource `enabled_policy_types` validation, I'm going to keep this issue open.

**Comment by shuheiktgw** [comment]
@bflad Thank you for pointing it out! I've created a PR to support AISERVICES_OPT_OUT_POLICY for `aws_organizations_organization`, so would you mind reviewing it, please? 🙏 

https://github.com/terraform-providers/terraform-provider-aws/pull/14650

**Comment by bflad** [comment]
Thanks so much, @shuheiktgw! Merged that one in as well so this support will all release with version 3.2.0, likely very shortly. 😄

**Comment by shuheiktgw** [comment]
@bflad Thank you for your fast review! 👍
