### ISSUE TITLE
Community Note

### ISSUE THREAD

**Issue by Juansbulbisful** [terraform-providers/terraform-provider-aws#14149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Hi @Juansbulbisful 👋  This feature request appears to be empty (just the original issue template), so I'm going to close it. If you have a feature request, please fill out the issue template with details. Please also note that we have been seeing random comments submitted by your account the last few days. You may want to verify that your account has not been compromised.
