### ISSUE TITLE
Can't use logging with aws_sfn_state_machine

### ISSUE THREAD

**Issue by kuhnboy** [terraform-providers/terraform-provider-aws#14186]
### Current Terraform Version

```
0.12.26
```

### Use-cases

Create cloud watch error logs for step functions

### Attempted Solutions

Look at documentation

### Proposal

Would be nice to have the logging configuration exposed in aws_sfn_state_machine.

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-loggingconfiguration.html

**Comment by DrFaust92** [comment]
duplicate of #12192
