### ISSUE TITLE
Amazon S3 buckets region lookup with FIPS endpoints will fail with dial tcp errors.

### ISSUE THREAD

**Issue by jasdel** [terraform-providers/terraform-provider-aws#14217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform's AWS Provider uses the aws-sdk-go's Amazon S3 client's [GetBucketLocation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html) to discover the AWS region of the user's Amazon S3 Bucket. This works fine for Buckets that are owned by the user, and when the user is using Terraform with a non-FIPS endpoint, (e.g. `s3.us-west-2.amazonaws.com`). But, if the user uses Terraform configured for a FIPS region like `s3-fips.us-east-1.amazonaws.com` attmpts to get the bucket's region will fail with an error, like:

```
Get https://s3-fips.us-east-1.amazonaws.com/testbucket?location=: dial tcp: lookup s3-fips.us-east-1.amazonaws.com: no such host
```
This error is caused by the `aws-sdk-go` Amazon S3 client's GetBucketLocation implementation. The SDK uses `path style` endpoint building pattern. This pattern puts the `BucketName` into the URI path. This is in conflict with S3 behavior for FIPS regions, which require the BucketName to be in the endpoint host prefix. This pattern is called `virtual host style`.

* Virtual host style: `bucketname.s3.us-west-2.amazonaws.com`
* Path style: `s3.us-west-2.amazonaws.com/bucketname`

Most of the SDKs customize the GetBucketLocation operation to use path style only, to address under documented error behavior. This makes the operation awkward to use when discovering the region of a bucket due to how virtual host style requests will return AWS signature errors when the request is made to the wrong region.

To address this issue the aws-sdk-go library created a [s3manager.GetBucketRegion](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#GetBucketRegion) utility. This utility allows discovery of a Bucket's region regardless of ownership, and is compatible with FIPS endpoints.

```go
	region, err := s3manager.GetBucketRegionWithClient(context.Background(), s3Client, "mybucket",
		func(r *request.Request) {
			r.Config.S3ForcePathStyle = aws.Bool(false)
		})
```

The extra functional option disabling path style is done to ensure that the call is compatible with FIPS endpoints.

### New or Affected Resource(s)

Looks like Terraform uses GetBucketLocation in 3 locations:
* [resource_aws_s3_bucket.go](https://github.com/terraform-providers/terraform-provider-aws/blob/96b93a820be442bc157fab0bd5b6a6b412b282e8/aws/resource_aws_s3_bucket.go)
* [resource_aws_s3_bucket_test.go](https://github.com/terraform-providers/terraform-provider-aws/blob/844f6b9bf03c505e272ed1e0d6db221d826216b7/aws/resource_aws_s3_bucket_test.go)
* [data_source_aws_s3_bucket.go](https://github.com/terraform-providers/terraform-provider-aws/blob/e3e065deda322c0e29bc071d2ba85fef801a4e04/aws/data_source_aws_s3_bucket.go)

If these were updated to use the `s3manager.GetBucketRegion` or `s3manager.GetBucketRegionWithClient` utility instead of `GetBucketLocation` operation users would be able to use Amazon S3 FIPS endpoints with Terraform's bucket region discovery.

### References

This is related to https://github.com/aws/aws-sdk-go/issues/3115 for AWS SDK for Go.

**Comment by bflad** [comment]
This change has been merged and will be released with version 3.0.0 of the Terraform AWS Provider, later this week. Thanks, @jasdel! 👍
