### ISSUE TITLE
Feature Request: encryption support for aws_efs_file_system

### ISSUE THREAD

**Issue by pmacdougall** [terraform-providers/terraform-provider-aws#1422]
EFS now supports encryption at rest via KMS and the latest Go SDK release supports it:
https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11025-2017-08-14

I realize it is brand new, but it just coincided with my starting to use it.

**Comment by stack72** [comment]
#1420

**Comment by Ninir** [comment]
Hey folks,

The feature has just been merged (Thanks for the follow-up Paul!

Closing!
