### ISSUE TITLE
redacted_fields attribute "single_header" for resource aws_wafv2_web_acl_logging_configuration does not support more than 1 item

### ISSUE THREAD

**Issue by jiwuh** [terraform-providers/terraform-provider-aws#14249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

-  Terraform version: 0.13.0

-  AWS Provider Version: 2.70.0

### Affected Resource(s)

* aws_wafv2_web_acl_logging_configuration

### Terraform Configuration Files

```hcl
resource "aws_wafv2_web_acl_logging_configuration" "example" {
  log_destination_configs = ["${aws_kinesis_firehose_delivery_stream.example.arn}"]
  resource_arn            = "${aws_wafv2_web_acl.example.arn}"
  redacted_fields {
    single_query {
      name = "user-agent"
    }
    single_query {
      name = "authorization"
    }
  }
}
```
### Expected Behavior
Both headers are added on the AWS console as shown below:
![image](https://user-images.githubusercontent.com/37252198/87946879-80a08800-ca9a-11ea-98af-34797407889b.png)

### Actual Behavior

An error is thrown statin that the attribute supports 1 item maximum.
![image](https://user-images.githubusercontent.com/37252198/87947148-d412d600-ca9a-11ea-89e5-8e4f9a5daaff.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by anGie44** [comment]
Hi @jiwuh, thank you for creating this issue! While only one `single_header` attribute can be declared within a `redacted_fields` block, it's possible to create repeated `redacted_fields` blocks. With the example you've provided, you can do something like:

```hcl 
resource "aws_wafv2_web_acl_logging_configuration" "example" {
  log_destination_configs = ["${aws_kinesis_firehose_delivery_stream.example.arn}"]
  resource_arn            = "${aws_wafv2_web_acl.example.arn}"
  redacted_fields {
    single_header {
      name = "user-agent"
    }
  } 

  redacted_fields {
    single_header {
      name = "authorization"
    }
  }
}
```
Looking at the snapshot of the console, unfortunately it does look a bit different from the WAFv2 API's structure but hopefully this example helps! If any further questions arise please let me know 😃

**Comment by jiwuh** [comment]
That worked @anGie44 thanks a bunch!
