### ISSUE TITLE
Support EC2 Transit Gateway VPN Attachments

### ISSUE THREAD

**Issue by christophetd** [terraform-providers/terraform-provider-aws#14287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Related to #6884, which was closed once the aws_ec2_transit_gateway_vpn_attachment _data source_ (not resource) was implemented.

Not being able to attach Transit Gateways to VPN connections is a deal breaker for automation as it requires to manually create the attachment via the AWS console, and will make the Terraform first run fail (since the data source aws_ec2_transit_gateway_vpn_attachment won't exist).

### New or Affected Resource(s)

* aws_ec2_transit_gateway_vpn_attachment

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/6884
https://www.terraform.io/docs/providers/aws/d/ec2_transit_gateway_vpn_attachment.html

**Comment by ewbankkit** [comment]
@christophetd Thanks for raising this issue.
A Transit Gateway can be attached to a VPN Connection via the `transit_gateway_id` attribute of the [`aws_vpn_connection`](https://www.terraform.io/docs/providers/aws/r/vpn_connection.html) resource.

**Comment by christophetd** [comment]
I missed that, thanks!
