### ISSUE TITLE
Terraform crash when parsing S3 CORS

### ISSUE THREAD

**Issue by llavaud** [terraform-providers/terraform-provider-aws#1429]
### Terraform Version
Terraform v0.10.1

### Affected Resource(s)
- s3

### Debug Output
https://gist.github.com/llavaud/fcd53cab03fb7581bb7b2d9a7bd537ef

### Panic Output
https://gist.github.com/llavaud/bd3c393a1f7b832c16e8f9a094d9d5e8

### Expected Behavior
not panic

### Actual Behavior
panic

### Steps to Reproduce
1. `terraform plan`

**Comment by apparentlymart** [comment]
Hi @llavaud! Sorry for this crash.

I believe this is related to a bug in Core version v0.10.1, which was fixed in the patch release v0.10.2 yesterday. Could you give this a try with v0.10.2 and see if that fixes the problem?

**Comment by llavaud** [comment]
Hello,

Yes it works with v0.10.2, thanks !
