### ISSUE TITLE
Cloudfront update to TLSv1.2_2019 failing 

### ISSUE THREAD

**Issue by Sginu** [terraform-providers/terraform-provider-aws#14295]
1 error occurred:
	* aws_cloudfront_distribution.s3_distribution: 1 error occurred:
	* aws_cloudfront_distribution.s3_distribution: error updating CloudFront Distribution (xxxxx): MalformedXML: 1 validation error detected: Value 'TLSv1.2_2019' at 'distributionConfig.viewerCertificate.minimumProtocolVersion' failed to satisfy constraint: Member must satisfy enum value set: [TLSv1.1_2016, SSLv3, TLSv1.2_2018, TLSv1_2016, TLSv1]
	status code: 400, request id: a70f5821-e811-4156-ba5s-a855f7e20e96

**Comment by rahulk94** [comment]
Looks like this will be included when https://github.com/terraform-providers/terraform-provider-aws/pull/14000 goes in. Check out `vendor/github.com/aws/aws-sdk-go/service/cloudfront/api.go` line 19487. Docs have already been updated in https://github.com/terraform-providers/terraform-provider-aws/pull/14152. Just gotta wait for the next release now.

**Comment by jeffnappi** [comment]
Looks like this has been resolved in the 3.1.0 release: https://github.com/terraform-providers/terraform-provider-aws/pull/14000#issuecomment-670783308

I was able to use 3.2.0 to use `TLSv1.2_2019` this issue can be closed.
