### ISSUE TITLE
The `aws_ecr_repository` data source doesn't work across accounts

### ISSUE THREAD

**Issue by tedivm** [terraform-providers/terraform-provider-aws#14327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_ecr_repository` data source doesn't work for cross account repositories, as it has no way to specify the account ID. The `aws_ecr_image` object does allow this, but doesn't have a way to get the repository out of it.

### New or Affected Resource(s)

* aws_ecr_repository

### Potential Terraform Configuration

```hcl
data "aws_ecr_repository" "service" {
  name = "ecr-repository"
  registry_id = "394802378"
}
```

### References

* #9947

**Comment by DrFaust92** [comment]
opened #14368 to address this
