### ISSUE TITLE
aws_wafv2_web_acl supports rate_based_statement, but aws_wafv2_rule_group does not

### ISSUE THREAD

**Issue by leecookson** [terraform-providers/terraform-provider-aws#14326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform version : 0.12.26
AWS provider version : 2.70.0

### Affected Resource(s)

* aws_wafv2_rule_group

### Terraform Configuration Files

```hcl
resource "aws_wafv2_rule_group" "rate_rule_group" {
  name     = "IPRateLimitWAFRuleGroup"
  scope    = "CLOUDFRONT"
  capacity = 5

  rule {
    name     = "IPRateLimitWAFRule"
    priority = 4

    action {
      count {}
    }

    statement {
      rate_based_statement {
        limit              = var.ip_rate_limit
        aggregate_key_type = "IP"
        }
      }
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform documentation indicates this statement type is not supported, so the result is expected relative to docs, but not to AWS functionality.  Since AWS supports this,  I expect it to be usable within `aws_wafv2_rule_group`.

https://docs.aws.amazon.com/cli/latest/reference/wafv2/create-rule-group.html

Search for RateBasedStatement

### Actual Behavior

```Error: Unsupported block type

  on ../../tf-waf-common/module/rate-limit-rule/module.tf line 57, in resource "aws_wafv2_rule_group" "rate_rule_group":
  15:       rate_based_statement {

Blocks of type "rate_based_statement" are not expected here.
```

### Steps to Reproduce

1. `terraform validate`

### Important Factoids

N/A

### References

* Issue #11175 suggests a structure that includes support for rate_based_statement

**Comment by anGie44** [comment]
Hi @leecookson, thank you for creating this issue! The PR linked above #14073 should address this discrepancy you are seeing in the `rule_group` resource (even though the PR only calls out the web_acl directly). A somewhat similar behavior https://github.com/terraform-providers/terraform-provider-aws/issues/14035 is reported on update of WebACLs such that the `rate_based_statement` is missing on update as well, though it is not reported at plan-time like you see here in the rule_group where the schema is missing this statement type.

**Comment by anGie44** [comment]
When adding support for this statement, seems to result in a similar response as https://github.com/aws/aws-cli/issues/5015

**Comment by anGie44** [comment]
When adding support for this statement, seems to result in a similar response as aws/aws-cli#5015 so it might not be feasible through the provider's use of the AWS SDK as expected (or even in the console, the configuration does pass validation but when comes the time to click the `Create Rule group` button, the same error message appears.
```
stderr:

        Error: Error creating WAFv2 RuleGroup: WAFInvalidParameterException: Error reason: A reference in your rule statement is not valid., field: RATE_BASED_STATEMENT, parameter: RateBasedStatement
        {
          RespMetadata: {
            StatusCode: 400,
            ...
          },
          Field: "RATE_BASED_STATEMENT",
          Message_: "Error reason: A reference in your rule statement is not valid., field: RATE_BASED_STATEMENT, parameter: RateBasedStatement",
          Parameter: "RateBasedStatement",
          Reason: "A reference in your rule statement is not valid."
        }
```

**Comment by anGie44** [comment]
hi again @leecookson! with the answer we got back from  aws/aws-sdk-go#3481, I'm going to close this as we're limited by the upstream service unfortunately, but if in the future support is added, feel free to revisit this one or re-open as needed.
