### ISSUE TITLE
aws_codebuild_project is missing a valid enivornment type (WINDOWS_SERVER_2019_CONTAINER)

### ISSUE THREAD

**Issue by RakeshCodeBase** [terraform-providers/terraform-provider-aws#14335]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aws_codebuild_project resource `environment type` currently only supports a value of `WINDOWS_CONTAINER` for the Windows ecosystem. but `WINDOWS_SERVER_2019_CONTAINER` should also be an option available to select the property (it is supported by aws-sdk-go).

The code in v2.70.0 that this applies to is:
```
155                         "type": {
156                             Type:     schema.TypeString,
157                             Required: true,
158                             ValidateFunc: validation.StringInSlice([]string{
159                                 codebuild.EnvironmentTypeLinuxContainer,
				       codebuild.EnvironmentTypeLinuxGpuContainer,
				       codebuild.EnvironmentTypeWindowsContainer,
				       codebuild.EnvironmentTypeArmContainer,
160                             }, false),
161                         },
```
### New or Affected Resource(s)

* aws_codebuild_project

### Potential Terraform Configuration

```
resource "aws_codebuild_project" "testing" {
  name          = var.build_project_name
  description   = "testing codebuild project"
  build_timeout = "5"
  service_role  = aws_iam_role.codebuild.arn

  artifacts {
    type                = "CODEPIPELINE"
  }

  environment {
    compute_type    = var.codebuild_compute_type
    image           = var.codebuild_build_image
    type            = "WINDOWS_SERVER_2019_CONTAINER"
    privileged_mode = "false"
  }

  source {
    type            = "CODEPIPELINE"
  }
}
```
### References
Requires AWS SDK [v1.33.8:](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.8)

* #14000

**Comment by bflad** [comment]
Support for this has been merged and will release with version 3.2.0 of the Terraform AWS Provider, later today. Thanks to @RakeshCodeBase for the implementation. 👍
