### ISSUE TITLE
[Documentation] Lifecycle -> Ignore Tags?

### ISSUE THREAD

**Issue by ben-turner** [terraform-providers/terraform-provider-aws#14371]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Current Documentation Website

### Affected Resource(s)
[Resource Tagging Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging)

### Terraform Configuration Files
N/A

### Debug Output
N/a

### Panic Output
N/A

### Expected Behavior
The documentation should use the `ignore_changes` field of the lifecycle object in examples.

### Actual Behavior
The documentation uses `ignore_tags` as a field of the lifecycle object in examples. This field doesn't seem to be documented anywhere else.

### Steps to Reproduce

1. Read [the tagging docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging).
2. Read [the terraform lifecycle docs](https://www.terraform.io/docs/configuration/resources.html#ignore_changes).
3. Notice the inconsistencies.

### Important Factoids

None

### References

None

**Comment by bflad** [comment]
Thank you for reporting this, @ben-turner. This [will be fixed here](https://github.com/terraform-providers/terraform-provider-aws/pull/14343/files#diff-276633a64304961fa13cb41d27b9256fR84) and deployed later this week when 3.0 is released. 👍
