### ISSUE TITLE
aws_route53_health_check regions no longer optional

### ISSUE THREAD

**Issue by wkral** [terraform-providers/terraform-provider-aws#1437]
When no `regions` argument is applied terraform attempts to use 0 regions. Documentation says the argument is optional but it seems not to work without it. 

### Terraform Version
0.10.0 and 0.10.1

### Affected Resource(s)
- aws_route53_health_check

### Expected Behavior
When no region property is provided all regions should be used as in previous versions.

### Actual Behavior
Terraform attempts to have 0 regions for the resource:

```
  ~ aws_route53_health_check.proxy-01-healthcheck
      regions.#:          "8" => "0"
      regions.1441947086: "us-west-2" => ""
      regions.2003110180: "us-east-1" => ""
      regions.2790541186: "eu-west-1" => ""
      regions.2948384242: "ap-southeast-2" => ""
      regions.3439004788: "us-west-1" => ""
      regions.917869640:  "ap-southeast-1" => ""
      regions.934703181:  "ap-northeast-1" => ""
      regions.987842296:  "sa-east-1" => ""
```
### Steps to Reproduce
```
resource "aws_route53_health_check" "proxy-01-healthcheck" {
    ip_address = "<redacted>"
    port = 80
    type = "TCP"
    failure_threshold = "3"
    request_interval = "10"
}
```
Previously created with version < 0.10.0

`terraform plan` shows output above.
`terraform apply` fails since API wont allow 0 regions.

### References
- #784 Recent change to make supplying a list of regions

**Comment by johanneswuerbach** [comment]
We also encountered this.

As a workaround you can specify `regions = ["us-west-2", "us-east-1", "eu-west-1", "ap-southeast-2", "us-west-1", "ap-southeast-1", "ap-northeast-1", "sa-east-1"]` in the resource.

**Comment by wkral** [comment]
@johanneswuerbach Thanks, we ended up doing the same thing eventually. Should have put it up to help others in the mean time while this gets fixed.

**Comment by bflad** [comment]
@johanneswuerbach / @wkral does this problem still exist?

**Comment by bflad** [comment]
Redirecting duplicate #1795 here.

**Comment by johanneswuerbach** [comment]
@bflad yes, not specifying health check regions will still try to write `0` regions and fails. (tested with provider.aws 1.7)

**Comment by bflad** [comment]
Does this only happen for existing resources? Do they happen to be from pre-0.1.3 of the AWS provider? I'm still not able to reproduce this with a new TCP healthcheck like the example configuration given with TCP and IP address.

I have a hunch that we need to add `Computed: true` to this attribute for the cases where Route53 is returning regions in its responses and yet its not defined in the Terraform configuration.

**Comment by bflad** [comment]
A caveat if `Computed: true` is set on the attribute is that Terraform will start ignoring manual console/CLI changes to `regions` if its not defined in the Terraform configuration.

Are you positive in each of these cases that `regions` or the healthcheck itself was never configured manually outside of Terraform? It seems odd that the Route53 API would only sometimes return the `regions` value. If it was configured manually at some point, it looks like you'll need to match the configuration in Terraform or use `ignore_changes` on the attribute at the moment.

Once we have a handle on how to consistently reproduce this, we can appropriately fix or suggest workarounds.

**Comment by bflad** [comment]
Has anyone determined a way to consistently reproduce this yet?

**Comment by bflad** [comment]
Closing due to lack of response. If someone figures out a reproduction case, we'll gladly take a look again. 👍
