### ISSUE TITLE
 Technical Debt Theme: Resolve Acceptance Test Failures (IAM)

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#14386]
### Description

This is a meta-issue which tracks the list of IAM Acceptance Tests which now consistently fail. The August-October 2020 [Roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/master/ROADMAP.md) for the AWS Provider includes a technical debt theme which decides an area of debt upon which we want to apply focus. 

The focus for this period is improving our Acceptance Test suite. This covers resolving failing and flaky tests. Our initial focus will be to resolve failing tests which exist within our [Core Service](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CORE_SERVICES.md) list.

## IAM Tests Currently Failing

- [x] `TestAccAWSIAMRole_basicWithDescription`
- [x] `TestAccAWSIAMServiceLinkedRole_CustomSuffix_DiffSuppressFunc`
- [x] `TestAccAWSIAMPolicy_basic`
- [x] `TestAccAWSIAMRolePolicy_invalidJSON`
- [ ] `TestAccAWSIAMGroupPolicyAttachment_basic` (will be fixed by SDK changes related to https://github.com/hashicorp/terraform-plugin-sdk/issues/531)
- [x] ~~`TestAccAWSKmsKey_Policy_IamServiceLinkedRole`~~ (no longer seems to consistently fail; passing in Gov Cloud & Commercial)
- [x] `TestAccAWSSpotFleetRequest_iamInstanceProfileArn`

**Comment by anGie44** [comment]
Closing w/remaining item on the list to be addressed by TF Plugin SDK change when that gets released/merged into provider.
