### ISSUE TITLE
error creating API Gateway v2 integration: BadRequestException

### ISSUE THREAD

**Issue by fremontandy** [terraform-providers/terraform-provider-aws#14391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

I'm new to terraform. In essence, I'm following https://github.com/terraform-providers/terraform-provider-aws/issues/14271 sample knowing "tls_config" is not available at the moment. My goal is to create API Gateway private integration with HTTP API targeting ALB with HTTPS listener (https://medium.com/swlh/aws-api-gateway-private-integration-with-http-api-and-a-vpc-link-602360a1cd84). It seems to be problematic the way I'm doing it. 

```hcl

resource "aws_apigatewayv2_vpc_link" "vpclink" {
  count = local.enabled ? 1 : 0
  name = "test"
  security_group_ids = [var.security_group]
  subnet_ids = length(data.aws_subnet_ids.private) > 0 ? data.aws_subnet_ids.private[count.index].ids : null
  tags = local.tags
}

resource "aws_apigatewayv2_api" "http" {
  count = local.enabled ? 1 : 0
  name = "test"
  protocol_type = "HTTP"
  tags = local.tags
  depends_on = [aws_apigatewayv2_vpc_link.vpclink]
}

resource "aws_apigatewayv2_integration" "http_integration" {
  count = local.enabled ? 1 : 0
  api_id = aws_apigatewayv2_api.http[count.index].id
  integration_type = "HTTP_PROXY"
  connection_type = "VPC_LINK"
  connection_id = aws_apigatewayv2_vpc_link.vpclink[count.index].id
  integration_uri = data.aws_lb.lb[count.index].arn
  integration_method = "ANY"
  timeout_milliseconds = 29000
  description = local.service_resource_name
}

```

### Expected Behavior

Expect to create an ALB private integration successfully. 

### Actual Behavior

Issue 1.
I'm getting the following error even though ARN is correct one. 
Error: error creating API Gateway v2 integration: BadRequestException: For VpcLink VPC_LINK, integration uri should be a valid ELB listener ARN or a valid Cloud Map service ARN.

Issue2.
Nowhere I can specify ALB listener. 

### Steps to Reproduce

1. `terraform apply`

### References

I am trying to transcript the following steps into script. 
https://medium.com/swlh/aws-api-gateway-private-integration-with-http-api-and-a-vpc-link-602360a1cd84

* #0000

**Comment by ewbankkit** [comment]
@fremontandy Thanks for raising this issue.
For a [private integration with an ALB](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-private.html#http-api-develop-integrations-private-ELB) the `integration_uri` attribute should be set to the ARN of the applicable Listener.
For example, using the [`aws_lb_listener` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lb_listener):

```hcl
data "aws_lb_listener" "example" {
  load_balancer_arn = data.aws_lb.lb[count.index].arn
  port              = 443
}

resource "aws_apigatewayv2_integration" "http_integration" {
  integration_uri = data.aws_lb_listener.example.arn
}
```

**Comment by fremontandy** [comment]
Thanks for the info, me not using aws_lb_listener was the problem. Looking forward to the upcoming release.
