### ISSUE TITLE
Standalone Acceptance Testing - Internal validation of the provider failed!

### ISSUE THREAD

**Issue by mubeta06** [terraform-providers/terraform-provider-aws#1440]
Hi there,

### Terraform Version
AWS Provider and Terraform Built from source

### Debug Output
https://gist.github.com/mubeta06/26efc01903938d591ca37cbf39d6cd25

### Expected Behavior
I expected the acceptance test to run as per when the acceptance test is ran from the AWS provider repo

### Actual Behavior
FAIL with error message indicating an Internal validation of the provider failed and to raise an issue.

### Steps to Reproduce
The code is here https://gist.github.com/mubeta06/b5e29694b8b1b5b5511f373ab5f85703
TF_ACC=1 go test -v .

### Important Factoids
I used govendor to vendor in all necessary dependencies including Terraform and the AWS Terraform Provider i.e. this repo.

**Comment by mubeta06** [comment]
Important Factoid. Vendor in precisely the version of terraform that the provider is to ensure great success.

**Comment by mubeta06** [comment]
I have narrowed this issue down to a particular commit in the hashicorp/terraform repo. https://github.com/hashicorp/terraform/commit/4acdc53a5646aef7fd1f5044ffb6c1380687344b#diff-963600beb10a8f212301293337045083 seems to break acceptance testing for this repo with the originally reported error message.

**Comment by paultyng** [comment]
Going to close this issue as the acceptance testing issues have since been worked out.
