### ISSUE TITLE
aws_cloud_watch_logs resource appends wildcard to ARN in output

### ISSUE THREAD

**Issue by GoldFlsh** [terraform-providers/terraform-provider-aws#14410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

                     
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.69.0

### Affected Resource(s)

* resource: aws_cloudwatch_log_group
* data: aws_cloudwatch_log_group

### Terraform Configuration Files

```hcl

resource "aws_cloudwatch_log_group" "log-group" {
  name = "my-log-group"
}

data "aws_cloudwatch_log_group" "log-group" {
  name = "my-log-group"
}

output "log-group-arn-resource" {
  value = aws_cloudwatch_log_group.log-group.arn
}

output "log-group-arn-data" {
  value = data.aws_cloudwatch_log_group.log-group.arn
}

```

### Expected Behavior

Expect output to be: 
`arn:aws:logs:{region}:xxxxxxxxxxxx:log-group:my-log-group`

### Actual Behavior

`arn:aws:logs:{region}:xxxxxxxxxxxx:log-group:my-log-group:*`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I would expect it to leave off the `:*` so it can be used in other resources, if a `:*` is needed for something, then the dev can know to add it instead of having to strip it off when it's in the way. 

For example, I am trying to use it in an IAM role where `:*` is not the appropriate format. 
https://docs.amazonaws.cn/en_us/IAM/latest/UserGuide/list_amazoncloudwatchlogs.html
```
arn:${Partition}:logs:${Region}:${Account}:log-group:${LogGroupName}
arn:${Partition}:logs:${Region}:${Account}:log-group:${LogGroupName}:log-stream:${LogStreamName}
```

To ensure the fix is backwards compatible, adding a new output with the strict arn would work. 

### References

* #0000

**Comment by bflad** [comment]
Hi @GoldFlsh 👋  Thank you for submitting this and its indeed frustrating behavior. Prior versions of the Terraform AWS Provider just passthrough the ARN value from the CloudWatch Logs API, which includes the `:*`. Version 3 of the Terraform AWS Provider will automatically trim this suffix from the API response. Please see the following for further tracking of this change, which should be happening shortly:

* https://github.com/terraform-providers/terraform-provider-aws/pull/14214
* https://github.com/terraform-providers/terraform-provider-aws/issues/13509

**Comment by GoldFlsh** [comment]
Great to hear, thank you for fixing this @bflad !
