### ISSUE TITLE
Support ECR server-side encryption

### ISSUE THREAD

**Issue by joe-hutchinson-cko** [terraform-providers/terraform-provider-aws#14414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS released [server-side encryption for ECR repositories](https://aws.amazon.com/blogs/containers/introducing-amazon-ecr-server-side-encryption-using-aws-key-management-system/) lets support it. 

### New or Affected Resource(s)

* [aws_ecr_repository](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository)

### Potential Terraform Configuration

```hcl
resource "aws_ecr_repository" "foo" {
  name                 = "bar"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  encryption_configuration {
    encryption_type  = "kms"
    kms_key          = "arn:aws:kms:us-west-2:123456789012:key/32aaa6ba-994d-4afa-8909-f35d97d24eb2"
  }
}
```

### References

* https://aws.amazon.com/blogs/containers/introducing-amazon-ecr-server-side-encryption-using-aws-key-management-system

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.33.15](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.15):

* #14000
