### ISSUE TITLE
aws_s3_bucket region cannot be set

### ISSUE THREAD

**Issue by relnetops** [terraform-providers/terraform-provider-aws#14430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

GitLab Pipeline (`image: hashicorp/terraform`)
```
$ terraform init
 Initializing the backend...
 Successfully configured the backend "s3"! Terraform will automatically
 use this backend unless the backend configuration changes.
 Initializing provider plugins...
 - Checking for available provider plugins...
 - Downloading plugin for provider "aws" (hashicorp/aws) 3.0.0...
```

Local
```
% terraform -v  
Terraform v0.12.29
+ provider.aws v3.0.0
```

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "https_bucket" {
  bucket = local.cloudfront_https_bucket_name
  acl    = var.acl
  region = var.aws_region

  versioning {
    enabled = var.versioning_enabled
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  tags = merge(local.tags, map("Name", local.cloudfront_https_bucket_name))
}
```

### Panic Output

```
 $ terraform plan -out plan-$ENV.txt
 Error: "region": this field cannot be set
   on s3.tf line 36, in resource "aws_s3_bucket" "https_bucket":
   36: resource "aws_s3_bucket" "https_bucket" {
```

### Expected Behavior

No changes. Infrastructure is up-to-date.

### Actual Behavior

Error: "region": this field cannot be set

### Steps to Reproduce

```
# update to latest terraform and aws provider:
terraform init

# run plan against unchanged config
terraform plan
```

### Important Factoids

GitLab pipeline uses the latest `hashicorp/terraform` image:

```yml
.plan:
  stage: test
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  script:
    - cd automation
    - terraform init
    - terraform workspace select $ENV
    - terraform plan -out plan-$ENV.tfplan
```

### References

* #14127 (?)

**Comment by bflad** [comment]
Hi @relnetops 👋  Thank you for filing this. Please note this is expected behavior in version 3.0.0 and later of the Terraform AWS Provider. The region of the bucket is determined by the region of the provider, similar to all other resources. Please see the [Version 3 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade) for more information.
