### ISSUE TITLE
Cannot use terraform AWS provider 3.0 with Terraform 0.12.29

### ISSUE THREAD

**Issue by queglay** [terraform-providers/terraform-provider-aws#14443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.12.29

### Affected Resource(s)

aws*

### Terraform Configuration Files

```hcl
provider "aws" {
  region = var.aws_region
  version = "~> 3.0"
}
```

### Debug Output
I am seeing this when I try to use aws provider version 3.0.0 with terraform 0.12.29
I attempted to remove the .terraform folder but the problem remained.

```
deployuser@ansiblecontrol:/deployuser$ rm -fr .terraform
deployuser@ansiblecontrol:/deployuser$ terraform init
Initializing modules...
- bastion in modules/bastion
- deadline in modules/deadline
- firehawk_init in modules/firehawk_init
- fsx in ansible/ansible_collections/firehawkvfx/fsx/terraform/fsx
- node in modules/node_centos
- softnas in ansible/ansible_collections/firehawkvfx/softnas/terraform/softnas
- storage_user in modules/storage_user
- vpc in modules/vpc
Downloading terraform-aws-modules/vpc/aws 2.44.0 for vpc.vpc...
- vpc.vpc in .terraform/modules/vpc.vpc/terraform-aws-vpc-2.44.0
- vpc.vpn in modules/vpn
- vpc.vpn.openvpn in modules/tf_aws_openvpn
- workstation in modules/workstation_pcoip

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...
- Downloading plugin for provider "random" (hashicorp/random) 2.3.0...

No provider "aws" plugins meet the constraint "~> 2.57,~> 3.0.0,~> 3.0.0".

The version constraint is derived from the "version" argument within the
provider "aws" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.


Error: no suitable version is available
```

I also inspected the module provider versions requested, and there seem to be no constraints that would prevent 3.0 from being used.

```
deployuser@ansiblecontrol:/deployuser$ terraform version
Terraform v0.12.29
deployuser@ansiblecontrol:/deployuser$ terraform providers
.
├── provider.aws ~> 3.0
├── provider.null ~> 2.0
├── provider.random ~> 2.0
├── module.bastion
│   ├── provider.aws (inherited)
│   └── provider.null (inherited)
├── module.deadline
│   └── provider.aws (inherited)
├── module.firehawk_init
│   └── provider.null (inherited)
├── module.fsx
│   ├── provider.aws (inherited)
│   └── provider.null (inherited)
├── module.node
│   ├── provider.aws (inherited)
│   ├── provider.null (inherited)
│   └── provider.random (inherited)
├── module.softnas
│   ├── provider.aws (inherited)
│   ├── provider.null (inherited)
│   └── provider.random (inherited)
├── module.storage_user
│   └── provider.aws (inherited)
├── module.vpc
│   ├── provider.aws
│   ├── provider.null (inherited)
│   ├── module.vpc
│       └── provider.aws ~> 2.57
│   └── module.vpn
│       └── module.openvpn
│           ├── provider.aws (inherited)
│           └── provider.null (inherited)
└── module.workstation
    ├── provider.aws (inherited)
    └── provider.null (inherited)
```

### Expected Behavior

The process terraform init should aquire terraform aws provider 3.0

### Actual Behavior

It complains as if the module version doesn't exist

### Steps to Reproduce

- remove .terraform folder
- terraform init

**Comment by pitthecat** [comment]
├── module.vpc
│       └── provider.aws ~> 2.57

This is the problem. You also have to update the provider inside the module

**Comment by queglay** [comment]
Thanks for your reply.  I'm unclear on how to do that.  I would have also thought the version constraint `~>` would mean anything later than that.  In any case I attempted to set it in the module where I refer to the aws vpc module.

```
provider "aws" {
  region = var.region
  version = "~> 3.0"
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
...
```
The version of the module itself (terraform-aws-modules/vpc/aws) doesn't go up to 3.0.

**Comment by DrFaust92** [comment]
```
~>: pessimistic constraint operator, constraining both the oldest and newest version allowed. For example, ~> 0.9 is equivalent to >= 0.9, < 1.0, and ~> 0.8.4, is equivalent to >= 0.8.4, < 0.9
```

the module has the following defined: 
```
  required_providers {
    aws = "~> 2.57"
  }
```

so 3.0.0 isnt support for it at the moment. this is not a provider issue so closing this.

**Comment by queglay** [comment]
But does that mean that AWS provider 3.0 can't create a VPC?  That's all the module tries to do.  It is a provider issue if you can't use the latest version of the provider to create a VPC.

**Comment by DrFaust92** [comment]
its not that vpc cant be created, the module cannot be used with the 3.0.0 provider.

see https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/478
https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/479

**Comment by queglay** [comment]
In case it helps anyone else, this example replaces the module with all of the components I needed for private and public subnets, routes and open vpn.  https://github.com/firehawkvfx/firehawk/blob/imp-vpc-cidr-blocks/modules/vpc/main.tf

This allowed me to update to 3.2.0.
