### ISSUE TITLE
Primary network interface is not provided for FSx (lustre), cannot mount onsite

### ISSUE THREAD

**Issue by queglay** [terraform-providers/terraform-provider-aws#14444]
Acquiring the primary network interface for FSx does not occur correctly with Terraform vs the AWS CLI (which does).

The primary interface is important, since there is more than one available, but the primary must be used to mount on prem.
https://docs.aws.amazon.com/fsx/latest/LustreGuide/mounting-on-premises.html

I'm guessing this is because the primary is some kind of load balancer.

According to that doc the primary in this case can be found with `aws fsx describe-file-systems`

This produces:
```
            "NetworkInterfaceIds": [
                "eni-03a2de807a87426b1", 
                "eni-01e3c19634c198b3b"
            ], 
```

So the primary would be eni-03a2de807a87426b1

However, the Terraform aws provider doesn't produce the same order:
```
1648[16:03:56] fsx_interface_ids = [
1649[16:03:56]   [
1650[16:03:56]     "eni-01e3c19634c198b3b",
1651[16:03:56]     "eni-03a2de807a87426b1",
1652[16:03:56]   ],
```

So its not possible using the terraform network list to determine the correct primary interface we would use to mount FSx onsite.

We have a need for aws_fsx_lustre_file_system attributes to respect the correct order or provide an additional attribute for the primary.

**Comment by ewbankkit** [comment]
@queglay Thanks for raising this issue.
It looks like it will be addressed by https://github.com/terraform-providers/terraform-provider-aws/pull/14314.

**Comment by queglay** [comment]
Thanks that's great to see!  I ended up using a custom data source bash script to work around it for now and it worked out too.

**Comment by DrFaust92** [comment]
Closing this as #14314 is merged.
