### ISSUE TITLE
Removal of deprecated attributes and existing state file

### ISSUE THREAD

**Issue by kimor79** [terraform-providers/terraform-provider-aws#14458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.0-rc1
+ provider registry.terraform.io/hashicorp/aws v3.0.0
+ provider registry.terraform.io/hashicorp/time v0.5.0
```

### Affected Resource(s)

so far:

* aws_region (datasource)
* aws_route53_zone
* aws_iam_role (datasource)
* aws_availability_zones (datasource)

### Terraform Configuration Files

```hcl
data "aws_region" "current" {}

resource "aws_route53_zone" "main" {
  lifecycle {
    ignore_changes = [vpc]
  }

  comment = local.vpc_name
  name    = local.domain_name
  tags    = local.tags
  vpc {
    vpc_id = aws_vpc.main.id
  }
}
```

### Expected Behavior

normal plan output

### Actual Behavior

```
Error: Invalid resource instance data in state

  on path/to/file/with/region_datasource line 1:
   1: data "aws_region" "current" {}

Instance
module.my-module.data.aws_region.current
data could not be decoded from the state: unsupported attribute "current".

Error: Invalid resource instance data in state

  on ../path/to/file/with/route53_zone_resource line 4:
   4: resource "aws_route53_zone" "main" {

Instance
module.my-module.aws_route53_zone.main data
could not be decoded from the state: unsupported attribute "vpc_id".
```

### Steps to Reproduce

1.  **Have an existing state file** (I don't know what version of the provider it was created with but I think it is 2.70.0)
1. `rm -fr .terraform`
1. `terraform init`
1. `terraform plan`

### Important Factoids

My state file has entries like below and it seems as though the existence of removed attributes from the provider causes terraform to get into a _stuck_ state. If I `state rm` the `data.aws_region` instances, terraform continues on but there are too many existing resources for me to `rm` them all or start with an empty state and `import`.

```
    {
      "module": "module.my-module",
      "mode": "data",
      "type": "aws_region",
      "name": "current",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"].my-module",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "current": null,
            "description": "US East (N. Virginia)",
            "endpoint": "ec2.us-east-1.amazonaws.com",
            "id": "us-east-1",
            "name": "us-east-1"
          }
        }
      ]
    },
```

### References

* #13398 ?

**Comment by ewbankkit** [comment]
@kimor79 Thanks for raising this issue.
It has already been noticed in #14431. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
