### ISSUE TITLE
DynamoDB replicas are not tagged

### ISSUE THREAD

**Issue by chonton** [terraform-providers/terraform-provider-aws#14460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.28
+ provider.aws v2.69.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "lab"
  region  = "us-east-1"
  version = "~> 2.61"
}

resource "aws_dynamodb_table" "vault" {
  name             = "duplicate-replica-tag-bug"
  billing_mode     = "PAY_PER_REQUEST"
  hash_key         = "Path"
  range_key        = "Key"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "Path"
    type = "S"
  }

  attribute {
    name = "Key"
    type = "S"
  }

  dynamic "replica" {
    for_each = ["us-west-2"]
    content {
      region_name = replica.value
    }
  }

  tags = {
    x = "x"
    y = "y"
  }
}
```

### Debug Output

https://gist.github.com/chonton/56719a1210410abcda4823d9d725e4c7

### Expected Behavior

Tags should be created on replicas as well as on the principal table

### Actual Behavior

Tags properly created on the principal table (in this sample, us-east-1); but no tags added to replica table (in this sample, us-west-2)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@chonton Thanks for raising this issue.
It has already been noticed in #14460. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
