### ISSUE TITLE
Importing lambda_alias sets function_name to ARN

### ISSUE THREAD

**Issue by terlar** [terraform-providers/terraform-provider-aws#14478]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.28
AWS Provider v2.70.0

### Affected Resource(s)

* aws_lambda_alias

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "test_lambda" {
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  handler       = "exports.test"

  source_code_hash = filebase64sha256("lambda_function_payload.zip")

  runtime = "nodejs12.x"
}

resource "aws_lambda_alias" "test_lambda_alias" {
  name             = "my_alias"
  description      = "a sample description"
  function_name    = aws_lambda_function.test_lambda.function_name
  function_version = "1"
}
```

### Expected Behavior

```sh
terraform state show aws_lambda_alias.test_lambda_alias
# aws_lambda_alias.test_lambda_alias:
resource "aws_lambda_alias" "test_lambda_alias" {
    arn              = "arn:aws:lambda:us-east-1:000000000000:function:lambda_function_name:my_alias"
    function_name    = "lambda_function_name"
    function_version = "1"
    id               = "arn:aws:lambda:us-east-1:000000000000:function:lambda_function_name:my_alias"
    name             = "my_alias"
}
```

### Actual Behavior

```sh
terraform state show aws_lambda_alias.test_lambda_alias
# aws_lambda_alias.test_lambda_alias:
resource "aws_lambda_alias" "test_lambda_alias" {
    arn              = "arn:aws:lambda:us-east-1:000000000000:function:lambda_function_name:my_alias"
    function_name    = "arn:aws:lambda:us-east-1:000000000000:function:lambda_function_name"
    function_version = "1"
    id               = "arn:aws:lambda:us-east-1:000000000000:function:lambda_function_name:my_alias"
    name             = "my_alias"
}
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform state rm aws_lambda_alias.test_lambda_alias`
3. `terraform import aws_lambda_alias.test_lambda_alias lambda_function_name/my_alias`

### References

Importing an aws_lambda_alias will set function_name to ARN. However this does not work together with `aws_lambda_provisioned_concurrency_config`. As per the specified ticket. 

* #11152

**Comment by bflad** [comment]
Hi @terlar 👋  Thank you for submitting this. This import behavior was fixed with [Version 3 of the Terraform AWS Provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_lambda_alias) since we consider changes like this to be breaking. Once upgraded, this automatic switch from name to ARN should no longer be an issue during import. 👍

**Comment by terlar** [comment]
Oh, what are the odds, sorry, should have checked that a new version was released, I just installed the latest one the other week, so wasn't aware of this. Thank you for fixing it!

**Comment by terlar** [comment]
BTW, that link doesn't work for me, just a white page, is it something wrong on my end? I see this for the whole https://registry.terraform.io
