### ISSUE TITLE
Can not reference ACM certificate domain_validation_options with AWS provider 3.0

### ISSUE THREAD

**Issue by mrobinet** [terraform-providers/terraform-provider-aws#14495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.12.29
+ provider.aws v3.0.0
```

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

terraform {
  required_version = "= 0.12.29"
  required_providers {
    aws = "~> 3.0"
  }
}

variable "zone_id" {
  description = "Hosted Zone ID"
  type        = string
}

resource "aws_acm_certificate" "cert" {
  domain_name               = "*.example.com"
  validation_method         = "DNS"
}

resource "aws_route53_record" "cert_validation" {
  name    = aws_acm_certificate.cert.domain_validation_options.0.resource_record_name
  type    = aws_acm_certificate.cert.domain_validation_options.0.resource_record_type
  zone_id = var.zone_id
  records = [aws_acm_certificate.cert.domain_validation_options.0.resource_record_value]
  ttl     = 60
}
```

### Debug Output

https://gist.github.com/mrobinet/4f8f05696f8947823f16a5ddc9268407

### Panic Output

No panic encountered.

### Expected Behavior

Terraform should be able to plan successfully with the DNS record referencing the validation options from the certificate.

### Actual Behavior

Received error regarding `domain_validation_options`. That value on the referenced certificate appears to be empty.

### Steps to Reproduce

1. `terraform init && terraform plan -var 'zone_id=<zone id>'`

### Important Factoids

Reverting provider version to 2.70 plans successfully.

### References

None

**Comment by ewbankkit** [comment]
@mrobinet Thanks for raising this issue.
With [v3.0.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#300-july-31-2020) of the provider (via #14199), `domain_validation_options` has changed from a list to a set.
You can use the [`tolist`](https://www.terraform.io/docs/configuration/functions/tolist.html) function to convert.

**Comment by mrobinet** [comment]
I had scanned the 3.0 upgrade docs, but somehow missed this. I found it upon taking a second look: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate

Closing this issue. Thanks for the quick response.
