### ISSUE TITLE
aws_workspaces_workspace replace (destroy/create) race condition

### ISSUE THREAD

**Issue by fweep** [terraform-providers/terraform-provider-aws#14517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.28

```
provider "aws" {
  version = "2.70.0"
}
```
### Affected Resource(s)

* aws_workspaces_workspace

### Terraform Configuration Files

```hcl
resource "aws_workspaces_workspace" "client_jstewart" {
  directory_id = aws_workspaces_directory.client.id
  bundle_id = data.aws_workspaces_bundle.client.id
  user_name = "jstewart"

  root_volume_encryption_enabled = true
  user_volume_encryption_enabled = true
  volume_encryption_key = aws_kms_alias.client_workspaces.arn

  workspace_properties {
    compute_type_name = "STANDARD"
    user_volume_size_gib = var.client_workspaces_user_volume_size
    root_volume_size_gib = var.client_workspaces_root_volume_size
    running_mode = "AUTO_STOP"
    running_mode_auto_stop_timeout_in_minutes = var.client_workspaces_auto_stop_timeout
  }

  tags = {
    Department = "wherescape-${var.environment_abbrv}-client"
  }
}
```

### Expected Behavior

Resource should be destroyed and re-created.

### Actual Behavior

Resource is destroyed, but re-create fails due to namespace still being in use.

```
module.wherescape.aws_workspaces_workspace.client_jstewart: Destroying... [id=ws-jc9p9tcss]
...
module.wherescape.aws_workspaces_workspace.client_jstewart: Still destroying... [id=ws-jc9p9tcss, 1m20s elapsed]
module.wherescape.aws_workspaces_workspace.client_jstewart: Destruction complete after 1m26s
module.wherescape.aws_workspaces_workspace.client_jstewart: Creating...
Error: workspace creation failed: A WorkSpace already exists for the specified user.
  on modules/wherescape/client_workspace_users.tf line 1, in resource "aws_workspaces_workspace" "client_jstewart":
   1: resource "aws_workspaces_workspace" "client_jstewart" {
```

If I immediately run the apply again, it succeeds. It seems that AWS or Terraform is not waiting for true completion of the destroy before it attempts to create.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Tensho** [comment]
@fweep Thank you for submitting this issue 🙇  Let me consult AWS Support regarding API eventual consistency first. Plan B will be adding retries for the failed workspace creation/termination attempts.

**Comment by Tensho** [comment]
>  This operation is **asynchronous** and returns before the WorkSpaces have been completely terminated. After a WorkSpace is terminated, the TERMINATED state is returned only briefly before the WorkSpace directory metadata is cleaned up, so this state is rarely returned. To confirm that a WorkSpace is terminated, check for the WorkSpace ID by using DescribeWorkSpaces. If the WorkSpace ID isn't returned, then the WorkSpace has been successfully terminated.

https://docs.aws.amazon.com/workspaces/latest/api/API_TerminateWorkspaces.html

I guess the workspace resource state waiter should be adjusted, but I still want to clarify this with AWS. Stay tuned.

**Comment by Tensho** [comment]
I've confirmed we have to switch to disappearing workspace ID instead of TERMINATED status with AWS Support. I'm going to fix current waiting behaviour the next week.
