### ISSUE TITLE
tests/resource/aws_ssm_maintenance_window_target: TestAccAWSSSMMaintenanceWindowTarget_resourceGroup Consistently Failing

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#14511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the following testing is failing:

```
=== CONT  TestAccAWSSSMMaintenanceWindowTarget_resourceGroup
TestAccAWSSSMMaintenanceWindowTarget_resourceGroup: testing.go:684: Step 0 error: errors during apply:
Error: ValidationException: AWS::EC2::INSTANCE, AWS::EC2::VPC are invalid resource group types
```

This appears to be newer validation by the SSM API. The SSM API reference still documents the all UPPERCASE values, however the SSM User Guide documents with Titlecase values. There is potential that updating `AWS::EC2::INSTANCE` to `AWS::EC2::Instance` and `AWS::EC2::VPC` to `AWS::EC2::Vpc` in the test configuration will fix the testing, otherwise a case should be opened with AWS Support to figure out the discrepancy and determine the fixes.

### Affected Resource(s)

* aws_ssm_maintenance_window_target

### Definition of Done

* `TestAccAWSSSMMaintenanceWindowTarget_resourceGroup` testing passes
* `website/docs/r/ssm_maintenance_window_target.html.markdown` example updated as appropriate
* On https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_RegisterTargetWithMaintenanceWindow.html#systemsmanager-RegisterTargetWithMaintenanceWindow-request-Targets page, click feedback link in top right corner and submit documentation discrepancy to the SSM service team

### References

* [SSM API Reference](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_RegisterTargetWithMaintenanceWindow.html#systemsmanager-RegisterTargetWithMaintenanceWindow-request-Targets)
* [SSM User Guide](https://docs.aws.amazon.com/systems-manager/latest/userguide/mw-cli-tutorial-targets-examples.html#mw-target-example-5)
* [Contributing Guide on Running/Writing Acceptance Testing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md)

**Comment by nikhil-goenka** [comment]
@bflad : Got the same error from console as well.
AWS::EC2::VPC are invalid resource group types
