### ISSUE TITLE
Allow rolling update on ASG

### ISSUE THREAD

**Issue by hauleth** [terraform-providers/terraform-provider-aws#1452]
This is just ping on old hashicorp/terraform#1552 issue

**Comment by trung** [comment]
@radeksimko i'm thinking of using this API: http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_SetInstanceHealth.html 
It may not be very performant for ASG which contains lots of instances and racing conditions would need to be taken care too.

What do you think?

**Comment by radeksimko** [comment]
Hi folks,
the main worry we have collectively in the maintainer's team is that we have no good way to store intermediate state and recover from partial failures.

The rolling update would require `X * Y` API calls (where `X` is number of instances and `Y` number of API calls per instance) and any of those API calls may fail and leave the ASG half-updated. Recovering from that is a non-trivial task. We'd probably need to track state of _each_ instance in the ASG, which might not scale very well, but there may be more unknowns.

We have also discussed the possibility of implementing this into Nomad which may be better suited for such functionality, but that discussion was so far only in the phase of theories.

I'm going to close this issue unless you have any specific suggestions on solutions. I appreciate the interest, but we have no plans to implement this any time soon so this issue would get stale without more concrete help (e.g. detailed proposal for solution with edge cases as above covered).

Thanks.

**Comment by trung** [comment]
Thanks for the explanation. 
I found this: https://groups.google.com/forum/#!msg/terraform-tool/7Gdhv1OAc80/iNQ93riiLwAJ which works for me as of now.
