### ISSUE TITLE
Cannot destroy security groups if they've been attached to an EMR cluster

### ISSUE THREAD

**Issue by fabiendelpierre** [terraform-providers/terraform-provider-aws#1454]
Hi folks,

### Terraform Version
v0.10.2

### Affected Resource(s)
- aws_security_group
- aws_security_group_rule (possibly)
- aws_emr_cluster

### Description of issue 
I will share my code farther down, but wanted to explain the issue I'm having in my own words.

Basically, I create a couple of SGs, then I tell an EMR cluster to use them as its primary SGs for the master and slave instances. The two SGs contain references to one another as I need to allow traffic between the two and within themselves. When doing a `terraform destroy`, Terraform destroys everything, until it reaches those two security groups, tries to delete them for 5 minutes and eventually returns the following error:
```
Error applying plan:

2 error(s) occurred:

* aws_security_group.foo-emr-slave (destroy): 1 error(s) occurred:

* aws_security_group.foo-emr-slave: DependencyViolation: resource sg-905feee0 has a dependent object
        status code: 400, request id: f28121c0-80db-4f71-ada3-24c22ffef0ee
* aws_security_group.foo-emr-master (destroy): 1 error(s) occurred:

* aws_security_group.foo-emr-master: DependencyViolation: resource sg-d454e5a4 has a dependent object                                                                                                          status code: 400, request id: 003f19a2-5cb6-4887-9b14-f0382cc33d3c
```
Now here's where it gets weird... this occurs **only** when I have an `aws_emr_cluster` included in my code. If I comment out the `aws_emr_cluster` resource and leave everything else alone, I can `terraform apply` and `terraform destroy` all day without getting the above error. So it only occurs when I have my `aws_emr_cluster` resource active, as I'm referencing the two SGs in the `ec2_attributes` section under the `emr_managed_master_security_group` and `emr_managed_slave_security_group` parameters.

You'll see in my code that I organized the rules using the `aws_security_group_rule` resource instead of in-line `ingress` or `egress` rules within `aws_security_group` resources, but the behavior was the same one way or the other (I originally had it with inline `ingress`/`egress` and changed it to see if it made a difference). I hoped that by defining individual rules, Terraform might attempt to delete the rules before deleting the security groups, which may have solved my issue, but alas...

Likewise you'll see that I've got separate rules for TCP, UDP and ICMP because I wanted to see if my usage of `-1` for "all protocols" was causing the problem, but that's also not the case.

I just haven't reverted yet to the simpler-looking code I originally had.

I have other rules in those security groups pointing to CIDR blocks, those rules get deleted fine, but the rules to the other SG don't get deleted. If, while `terraform destroy` is running, I manually delete all the rules from one of the two groups, Terraform immediately completes the destruction successfully. Likewise, if I wait until the error happens, I can go delete the security groups by deleting the remaining rules within and then deleting the SGs themselves.

If you're familiar with EMR, you'll know that it creates two managed security groups automatically if none are specified. I was originally doing just that since I didn't feel the need to manage the SGs myself, but If I recall correctly (I've been working on this for a few days), I went down this path because after creating the EMR cluster with Terraform, when I would run `terraform destroy`, everything would get deleted except the two security groups that the EMR service created for itself, and then Terraform was unable to delete the VPC. So I thought that by defining these security groups myself, I could work around that, but it has not worked out.

Hoping I'm not doing something horribly wrong here -- I've only been using Terraform for a couple of weeks.

### Terraform Configuration Files
Note my code provisions a VPC and everything inside it. I'm using m4.xlarge instances for EMR so feel free to edit the code to use less expensive instance types.
Tarball link: https://www.dropbox.com/s/i02d6onm3ctw3ln/emr-cluster.tar?dl=0

### Debug Output
Included as gzipped tarballs inside the tarball with the code. I included the trace/debug log for both `terraform apply` (which never gives me any issues) and `terraform destroy`, just in case.

### Expected Behavior
When running `terraform destroy` against a set of config files that provision a VPC and a bunch of things inside it, I expect everything to be gone after completion. (See above for details.)

### Actual Behavior
`terraform destroy` successfully destroys almost everything except two interdependent security groups, and as a consequence the VPC itself fails to get deleted. (See above for actual error.)

### Steps to Reproduce
For a _successful_ run:
1. Comment out the `aws_emr_cluster` section in the emr.tf file.
2. `terraform apply`
3. Once above is complete, `terraform destroy` -- **this should work fine**.

Then start over:
1. Uncomment the `aws_emr_cluster` section in the emr.tf file.
2. `terraform apply`
3. Once above is complete, `terraform destroy` -- **you should encounter my problem**.

### Important Factoids
None that I'm aware. This particular project I'm working on gives me a lot of liberty, since I get to set up the VPC from the ground up via Terraform, so I don't think I'm using anything weird.

Let me know if you have any questions!

**Comment by catsby** [comment]
Hey @fabiendelpierre ! I sincerely apologize for taking so long to get around to this. I'm looking into this now and wanted to send a quick "thank you" for the incredibly detailed bug report. I had actually heard of this issue from another source but couldn't reproduce, until I searched the issues and found yours! The config and steps provided do reproduce it, I can't thank you enough for all this information 😄 

Hopefully I can get this addressed sooner than later

**Comment by fabiendelpierre** [comment]
@catsby cool, thanks! In the end it turns out I didn't need to manage the EMR cluster for my project, because the project ultimately requires Data Pipeline, which takes care of provisioning EMR on its own. So this was all for (mostly) nothing for me. But I'm super glad the bug report is useful and that you were able to reproduce the issue!

**Comment by catsby** [comment]
So, the race was documented in https://github.com/terraform-providers/terraform-provider-aws/pull/1163 and I assume went out on the website around when it was merged... So it's a "known" thing in some sense. Seems when you give EMR the master/slave SGs instead of using the auto generated ones, EMR will then add required rules for you, and enforce them being there. Even removing them manually in the console will result in EMR restoring them :/ 

Looking into what to do about this. We may need to simply document (better) that EMR will do this and instruct users not to add rules that duplicate EMRs.

**Comment by catsby** [comment]
FWIW I've opened a PR to add a new attribute to `aws_security_group` called `revoke_rules_on_delete`, which will force the security group to revoke it's rules prior to deleting the group itself:

- https://github.com/terraform-providers/terraform-provider-aws/pull/2074

**Comment by fabiendelpierre** [comment]
Sounds good to me!

**Comment by catsby** [comment]
I'm going to close this for now; https://github.com/terraform-providers/terraform-provider-aws/pull/2074 has introduced a patch to `aws_security_group` to forcefully revoke rules to allow a Security Group to be destroyed.

**Comment by copumpkin** [comment]
@catsby I don't think #2074 actually fixes this does it? Or perhaps it's a regression? Either way, as I mentione over there I have an EMR cluster in 0.11.7 and all three SGs have `revoke_rules_on_delete = true` and the SG deletion fails consistently.
