### ISSUE TITLE
NLB Stickiness conflicts between UDP & TCP

### ISSUE THREAD

**Issue by sce81** [terraform-providers/terraform-provider-aws#14556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
0.12.28
AWS 3.0.0

### Affected Resource(s)

aws_lb_target_group

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
required to be present when using a TCP listener, required to be absent when using a UDP listener. 

  stickiness {
    enabled = false
    type = "lb_cookie"
  }

### Expected Behavior
should be able to add a TCP and UDP listener to an NLB using a count function. 

### Actual Behavior

presence of stickiness block is incompatible between TCP and UDP

either. 
Error: Network Load Balancers do not support Stickiness

or

Error: Error modifying Target Group Attributes: InvalidConfigurationRequest: The provided target group attribute is not supported

### Steps to Reproduce

add or remove stickiness block with TCP or UDP protocol

1. `terraform apply`

### References

* #0000

**Comment by YakDriver** [comment]
Thank you for bringing this to our attention. I'm closing this since a fix was released in v3.10.0 (#15295). If you continue to have issues, please let us know by opening a new issue.
