### ISSUE TITLE
resource/aws_rds_cluster_endpoint: Increase Default Create Timeout

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#14570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Given fairly consistent daily acceptance testing failures such as:

```
=== CONT  TestAccAWSRDSClusterEndpoint_tags
TestAccAWSRDSClusterEndpoint_tags: testing.go:684: Step 0 error: errors during apply:
Error: Error waiting for RDS Cluster Endpoint (reader-7926473369288959707) to be ready: timeout while waiting for state to become 'available' (last state: 'creating', timeout: 20m0s)
```

It appears the default `Create` timeout needs to be increased in the `aws_rds_cluster_endpoint` resource.

### Affected Resource(s)

* aws_rds_cluster_endpoint

### Definition of Done

- [x] Default timeout(s) updated in `aws/resource_aws_rds_cluster_endpoint.go`
- [ ] Timeout documentation updated in `website/docs/r/aws_rds_cluster_endpoint.html.markdown`
- [x] `TestAccAWSRDSClusterEndpoint_` testing passes

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/14384

**Comment by anGie44** [comment]
The timeout fix has been merged and will release with `v3.5.0` of the Terraform AWS Provider, expected out next Thurs.
