### ISSUE TITLE
aws_launch_template data source error setting network_interfaces for version 3.x

### ISSUE THREAD

**Issue by andreasterrius** [terraform-providers/terraform-provider-aws#14597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform 0.12.10 (also tested with 0.12.28)
* provider.aws: version = "~> 3.1"
* provider.external: version = "~> 1.2"
* provider.null: version = "~> 2.1"
* provider.template: version = "~> 2.1"

### Affected Resource(s)

aws_launch_template data source

### Terraform Configuration Files

```hcl
data "aws_launch_template" "current" {
  filter {
    name   = "launch-template-name"
    values = ["${var.name}-*"]
  }
}
```

### Debug Output
```
Error: error setting network_interfaces: network_interfaces.0.delete_on_termination: '' expected type 'bool', got unconvertible type 'string'

  on .terraform/modules/dir/data.tf line 13, in data "aws_launch_template" "current":
  13: data "aws_launch_template" "current" {
```
### Expected Behavior
Execpted no error

### Actual Behavior
```
Error: error setting network_interfaces: network_interfaces.0.delete_on_termination: '' expected type 'bool', got unconvertible type 'string'

  on .terraform/modules/dir/data.tf line 13, in data "aws_launch_template" "current":
  13: data "aws_launch_template" "current" {
```

### Steps to Reproduce

1. `terraform apply`

### References

Issue has been fixed here but not for version 3 it seems
https://github.com/terraform-providers/terraform-provider-aws/issues/12067

**Comment by anGie44** [comment]
The fix for this has been merged and will release with version 3.2.0 of the Terraform AWS Provider.
