### ISSUE TITLE
Terraform does not support event_bus_name in aws_cloudwatch_event_rule

### ISSUE THREAD

**Issue by vermdeep** [terraform-providers/terraform-provider-aws#14595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_cloudwatch_event_rule` does not support `event_bus_name` parameter. Also, terraform does not support creating a custom event bus.

### New or Affected Resource(s)

* aws_cloudwatch_event_rule
* aws_event_bus

### Potential Terraform Configuration

```hcl
resource "aws_event_bus" "custom_bus" {
  name = "custom-bus"
  tags = {}
}

resource "aws_cloudwatch_event_rule" "console" {
  name        = "capture-aws-sign-in"
  description = "Capture each AWS Console Sign In"

  event_pattern = <<EOF
{
  "detail-type": [
    "AWS Console Sign In via CloudTrail"
  ]
}
EOF
 event_bus_name = aws_event_bus.custom_bus.name
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/events/create-event-bus.html
* https://docs.aws.amazon.com/cli/latest/reference/events/put-rule.html

**Comment by jdheyburn** [comment]
TODO:

1. Create new resource `aws_cloudwatch_event_bus`
    1. Hooks onto [CreateEventBus](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchevents/#CloudWatchEvents.CreateEventBus)
2. Allow input for `event_bus_name` in `aws_cloudwatch_event_rule`
    1. [PutRuleInput](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatchevents/#CloudWatchEvents.PutRule)

**Comment by ewbankkit** [comment]
@vermdeep  Thanks for raising this issue.
The umbrella EventBridge issue is #9330. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
