### ISSUE TITLE
Kinesis Firehose Datadog Configuration support

### ISSUE THREAD

**Issue by saitotqr** [terraform-providers/terraform-provider-aws#14596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Amazon Kinesis Data Firehose now supports data delivery to Datadog
https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-kinesis-data-firehose-now-supports-data-delivery-to-datadog/

This update allows for data transfer from Kinesis Firehose to Datadog , but terraform-provider-aws v3 does not yet support this use case.

### New or Affected Resource(s)

- aws_kinesis_firehose_delivery_stream
    - datdog_configuration `new`

### References
- AWS News release
    - https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-kinesis-data-firehose-now-supports-data-delivery-to-datadog/
- AWS firehose docs
    - https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-datadog
- terraform `splunk_configuration`
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#splunk-destination

**Comment by ken5scal** [comment]
Anyone working on this? I may want to tackle on this

**Comment by bflad** [comment]
Hi folks 👋  Thank you for this feature request. The implementation details of this (similar to New Relic and MongoDB Atlas support) appear to require the implementation of HTTP endpoint configurations in the `aws_kinesis_firehose_delivery_stream` resource, which can be tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/14469.

Please 👍  react and subscribe to that issue for further discussions and efforts on this support.
