### ISSUE TITLE
aws_iam_role data resource causing problems with loading the terraform state

### ISSUE THREAD

**Issue by FredStober** [terraform-providers/terraform-provider-aws#14608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* data.aws_iam_role

### Terraform Configuration Files

data "aws_arn" "current_user" {
 arn = "...some valid ARN"
}

### Debug Output

2020/08/12 19:38:12 [ERROR] eval: *terraform.EvalModuleCallArgument, err: Invalid resource instance data in state: Instance data.aws_iam_role.current_user data could not be decoded from the state: unsupported attribute "assume_role_policy_document".
2020/08/12 19:38:12 [ERROR] eval: *terraform.EvalOpFilter, err: Invalid resource instance data in state: Instance data.aws_iam_role.current_user data could not be decoded from the state: unsupported attribute "assume_role_policy_document".
2020/08/12 19:38:12 [ERROR] eval: *terraform.EvalSequence, err: Invalid resource instance data in state: Instance data.aws_iam_role.current_user data could not be decoded from the state: unsupported attribute "assume_role_policy_document".

### Expected Behavior

After upgrading to terraform 0.13 I expected the old terraform state created with 0.12 to load

### Actual Behavior

Error message:
Instance data.aws_iam_role.current_user data could not be
decoded from the state: unsupported attribute "assume_role_policy_document".

### Steps to Reproduce

1.) Create state using terraform 0.12
2.) Run with terraform 0.13

### Important Factoids

The property was renamed from "assume_role_policy_document" to "assume_role_policy". This seems to break loading states created with the previous version.

* #0000

**Comment by bflad** [comment]
Hi @FredStober 👋  Thank you for reporting this and sorry you ran into trouble here. This issue should be resolved when Terraform CLI version 0.13.1 is released. Please see https://github.com/hashicorp/terraform/issues/25752 and its associated pull request for additional information.
