### ISSUE TITLE
Enable CMK encryption for aws_kinesis_firehose_delivery_stream

### ISSUE THREAD

**Issue by Naveenak05** [terraform-providers/terraform-provider-aws#14613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A feature request to enable the CMK encryption for `aws_kinesis_firehose_delivery_stream`.

Currently, aws_kinesis_firehose_delivery_stream resource only supports `server_side_encryption` but it would be nice if it supports CMK encryption as well. Add support for CMK (i.e., `kms_key_arn`/`kms_key_id`) to `server_side_encryption` configuration block.

### New or Affected Resource(s)

* `aws_kinesis_firehose_delivery_stream`

### References

*https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-kinesis-data-firehose-adds-support-for-customer-provided-keys-for-server-side-encryption/
*https://docs.amazonaws.cn/en_us/streams/latest/dev/getting-started-with-sse.html

**Comment by ewbankkit** [comment]
@Naveenak05 Thanks for raising this issue.
It has already been noticed in #11721. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
