### ISSUE TITLE
aws_availability_zones started proposing changes on each apply

### ISSUE THREAD

**Issue by vladimirtiukhtin** [terraform-providers/terraform-provider-aws#14623]
Just would like to reopen https://github.com/terraform-providers/terraform-provider-aws/issues/14405 as it seems got abandoned

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v3.1.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

### Affected Resource(s)

* aws_availability_zones

### Debug Output
<img width="727" alt="Screen Shot 2020-08-13 at 14 04 56" src="https://user-images.githubusercontent.com/15124334/90137795-051ab980-dd6e-11ea-8f1a-5cb6c4a70d23.png">

### Expected Behavior

No changes proposed

**Comment by bflad** [comment]
Hi @vladimirtiukhtin 👋  Sorry for the confusion here, while the `group_names` fix applied in Terraform AWS Provider version 3.1.0 was an actual issue, it was not the only issue occurring.

There was some unexpected changes with data source handling that occurred in the Terraform CLI version 0.13.0 release that are causing this additional data source output in addition to the unstable `id` attribute in the output. There are now larger tracking issues for both sides of this so to consolidate efforts and discussions, I'm going to close this in preference of them:

* https://github.com/hashicorp/terraform/issues/25812
* https://github.com/terraform-providers/terraform-provider-aws/issues/14579

Please upvote and subscribe to those for further updates. 👍
