### ISSUE TITLE
aws_kms_secrets data source prompts apply acceptance with no changes

### ISSUE THREAD

**Issue by jdw88** [terraform-providers/terraform-provider-aws#14625]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.0
+ provider registry.terraform.io/-/aws v3.1.0
+ provider registry.terraform.io/hashicorp/aws v3.1.0
```

### Affected Resource(s)

* data.aws_kms_secrets

### Terraform Configuration Files

```hcl
data "aws_kms_secrets" "shared" {
  for_each = var.shared_encrypted_secrets
  secret {
    name    = each.key
    payload = each.value
  }
}
```

### Expected Behavior

No changes/acceptance prompt

### Actual Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)

Terraform will perform the following actions:
  # data.aws_kms_secrets.shared["my_secret"] will be read during apply
  # (config refers to values not yet known)
 <= data "aws_kms_secrets" "shared"  {
      ~ id        = "2020-08-13 13:42:02.099568 +0000 UTC" -> "2020-08-13 13:42:07.251801 +0000 UTC"
        plaintext = {
            "my_secret" = "<my_secret>"
        }

        secret {
            context      = {}
            grant_tokens = []
            name         = "my_secret"
            payload      = "<encrypted_payload>"
        }
    }

Plan: 0 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
@jdw88 Thanks for raising this issue.
It has already been noticed in #14564. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
