### ISSUE TITLE
Acceptance tests do not seem to adopt local schema changes for development

### ISSUE THREAD

**Issue by shuheiktgw** [terraform-providers/terraform-provider-aws#14648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

- terraform v0.12.24
- terraform-provider-aws master 

### Expected Behavior

Acceptance tests adopt local schema changes when running.

### Actual Behavior

Acceptance tests ignore local schema changes when running.

### Steps to Reproduce

1. Pull the latest terraform-provider-aws and modify any `Schema`.
2. Run the acceptance tests related to the schema, and see accs ignore the changes

### Important Factoids

First I used terraform v0.12.24 and saw this behavior. After switching to v0.12.29, this seems not to happen anymore. I feel this issue occurred after updating Terraform Plugin SDK, but not pretty sure if that really is the case. 

If there is a dependency on the terraform version, it would be nice if we update [the documentation](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/DEVELOPMENT.md) for developers. Thank you! 👍

**Comment by ewbankkit** [comment]
@shuheiktgw Thanks for raising this issue.
The [Terraform Plugin SDK v2 Upgrade Guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#a-new-acceptance-testing-driver) does mention that v0.12.26 or greater of the Terraform CLI needs to be available, Agree that this provider's documentation should reflect that.

**Comment by shuheiktgw** [comment]
@ewbankkit Thank you for updating the document! 👍
