### ISSUE TITLE
aws_route_tables Data Source always changes during plan in Terraform 0.13.0

### ISSUE THREAD

**Issue by jvisker** [terraform-providers/terraform-provider-aws#14649]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route_tables data source

### Terraform Configuration Files

```hcl
terraform {
  required_version = "0.13.0"
}
provider "aws" {
  version = "3.1.0"
  region  = "us-west-2"
}
data "aws_route_tables" "test" {
  vpc_id   = "vpc-03c6fb17e2731fe4a"
}
```

### Expected Behavior

The plan should output `No changes. Infrastructure is up-to-date.` and that is what it does in 0.12.29.

### Actual Behavior
The plan outputs this:
```
data.aws_route_tables.test: Refreshing state... [id=terraform-20200813215940187300000001]
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 <= read (data resources)
Terraform will perform the following actions:
  # data.aws_route_tables.test will be read during apply
  # (config refers to values not yet known)
 <= data "aws_route_tables" "test"  {
      ~ id     = "terraform-20200813221652309700000001" -> "terraform-20200813221653565900000001"
        ids    = [
            "rtb-01b7fbeb35ab47df8",
        ]
        vpc_id = "vpc-035c4191dd1a8dda0"
    }
Plan: 0 to add, 0 to change, 0 to destroy.
```
It does not resolve after doing an apply.
### Steps to Reproduce

1. `terraform plan`

**Comment by bflad** [comment]
Hi @jvisker 👋  Thank you for reporting this and sorry you ran into trouble here.

There were some unexpected changes with data source handling that occurred in the Terraform CLI version 0.13.0 release that are causing this additional data source output in addition to the unstable `id` attribute in the output. There are now larger tracking issues for both sides of this so to consolidate efforts and discussions, I'm going to close this in preference of them:

* https://github.com/hashicorp/terraform/issues/25812
* https://github.com/terraform-providers/terraform-provider-aws/issues/14579

Please upvote and subscribe to those for further updates. 👍
