### ISSUE TITLE
aws_elasticsearch_domain ebs_options volume_type = "st1"

### ISSUE THREAD

**Issue by tlynchpin** [terraform-providers/terraform-provider-aws#14653]
https://github.com/terraform-providers/terraform-provider-aws/blob/e68b2cbd25fb5b116f5b9b02aeada038890d23e7/aws/resource_aws_elasticsearch_domain.go#L190

please add support for volume_type st1

**Comment by bflad** [comment]
Hi @tlynchpin 👋 

Neither the API model nor the API reference documentation for the Elasticsearch service show `st1` as an available EBS volume type for creating domains

* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createelasticsearchdomain
* https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/#ElasticsearchService.CreateElasticsearchDomain

Can you please point to the relevant documentation or show a successful AWS CLI command with this value?

**Comment by tlynchpin** [comment]
@bflad, sorry, my mistake, thanks for looking into it.
