### ISSUE TITLE
Support for Route53 CAA records

### ISSUE THREAD

**Issue by arkadiyt** [terraform-providers/terraform-provider-aws#1465]
Amazon has announced route53 support for certificate authority authorization (CAA) records:
https://forums.aws.amazon.com/ann.jspa?annID=4799

This issue is a feature request to add support for this record type.

### Terraform Version
```
$ terraform -v
Terraform v0.10.2
```
### Affected Resource(s)
- aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "example-com-caa" {
  zone_id = "${aws_route53_zone.example-com.zone_id}"
  name    = "example.com"
  type    = "CAA"
  ttl     = 300

  records = [
    "0 issue \"letsencrypt.org\"",
    "0 iodef \"mailto:caa@example.com\"",
  ]
}
```
### Debug Output
https://gist.github.com/arkadiyt/5b75f26fa1ec71ba847202de5d4970bc

### Panic Output
N/A

### Expected Behavior
Should have created a CAA record

### Actual Behavior
Threw an exception

### Steps to Reproduce
`terraform plan` or `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by gazoakley** [comment]
There's a validator in Terraform that checks the record type is one of a supported list:

https://github.com/terraform-providers/terraform-provider-aws/blob/ab0919122d08bf94fa1d4128da801a429827ed05/aws/validators.go#L802

**Comment by Ninir** [comment]
This has just been merged. Thanks again @gazoakley :)

**Comment by arkadiyt** [comment]
Thank you!

**Comment by gazoakley** [comment]
@Ninir Thanks for getting it reviewed quick 👍

**Comment by bflad** [comment]
Thanks for getting this in so quick!
