### ISSUE TITLE
aws_vpc_endpoint cidr_blocks output missing range

### ISSUE THREAD

**Issue by jprouten** [terraform-providers/terraform-provider-aws#14656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_vpc_endpoint

### Terraform Configuration Files

```hcl

provider "aws" {
  region = "eu-west-2"
}


resource "aws_vpc_endpoint" "s3" {
  vpc_id       = "vpc-xxxxxxxxxxxxxxxxxxxx"
  service_name = "com.amazonaws.eu-west-2.s3"
}


output "cidr" {
  value       = ["${aws_vpc_endpoint.s3.*.cidr_blocks}"]
}
```

### Expected Behavior

When the S3 Endpoint is created a Output of the CIDR Ranges should contain 3 ranges (for eu-west-2).
This has been true for the last few years.

### Actual Behavior

Only 2 Cidr ranges are included in the output.

### Steps to Reproduce

Run the above code to create an s3 endpoint, with the output.

1. `terraform apply`

### Important Factoids

Initially using:

Terraform Version - 0.11.14

AWS Provider - terraform-provider-aws_v2.69.0_x4

I have tested with the latest aws provider, and also tried with the latest terraform 0.12 version.

All have the same result.

AWS are still making the 3 subnets available, yet Terraform now only brings back 2 subnets and it used to bring back all 3.

* #0000

**Comment by ewbankkit** [comment]
Similar:

* https://github.com/terraform-providers/terraform-provider-aws/issues/12966

**Comment by ewbankkit** [comment]
The AWS provider uses the [`DescribePrefixLists`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribePrefixLists.html) EC2 API call to get the prefix lists for a service.

```console
$ aws --region eu-west-2 ec2 describe-prefix-lists
{
    "PrefixLists": [
        {
            "Cidrs": [
                "52.94.15.0/24"
            ],
            "PrefixListId": "pl-b3a742da",
            "PrefixListName": "com.amazonaws.eu-west-2.dynamodb"
        },
        {
            "Cidrs": [
                "52.95.150.0/24",
                "52.95.148.0/23"
            ],
            "PrefixListId": "pl-7ca54015",
            "PrefixListName": "com.amazonaws.eu-west-2.s3"
        }
    ]
}
```

returns 2 CIDR ranges.

**Comment by ewbankkit** [comment]
@jprouten Thanks for raising this issue.
The `cidr_blocks` attribute of the `aws_vpc_endpoint` resource returns the result of the `DescribePrefixLists` EC2 API call for the specified service and as the output above shows, this is currently the 2 values `52.95.150.0/24` and `52.95.148.0/23`.
I suggest contacting AWS Support with a query as to why the published IP ranges has 3 values for S3 in `eu-west-2`.

I have hit this kind of problem before in my own work and created a couple of Terraform providers to help with this.
[Here's a gist](https://gist.github.com/ewbankkit/6be9526f3c975c72972ce26986c58cc7) that shows how to use them to return a set containing the 3 values you are expecting.:

```console
$ terraform apply
data.get_file.aws_ip_ranges: Refreshing state...
data.jmespath_search.eu_west_2_s3: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

prefix_list = [
  "52.92.88.0/22",
  "52.95.148.0/23",
  "52.95.150.0/24",
]
```
