### ISSUE TITLE
AWS Lambda support for Java 8 (Corretto) and custom runtimes on Amazon Linux 2

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#14657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> You can now develop AWS Lambda functions using Java 8 (Corretto)
> You can now develop your AWS Lambda functions using custom runtimes on Amazon Linux 2

### New or Affected Resource(s)

* [`aws_lambda_function`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function)
* [`aws_lambda_layer_version`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version) plus corresponding data source

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "example" {
  runtime = "java8.al2"
}
```

### References

Announcements:

* [Java 8 (Corretto)](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-lambda-supports-java-8/)
* [Custom runtimes on Amazon Linux 2](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-lambda-supports-custom-runtimes-amazon-linux-2/)
* [Go on Amazon Linux 2](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-lambda-supports-go-amazon-linux-2/)

Requires [AWS SDK v1.34.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.3):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14523

Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/14601

**Comment by bflad** [comment]
Support for these new runtimes has been merged and will release with version 3.3.0 of the Terraform AWS Provider, later this week. Thanks to @ewbankkit for the implementation. 👍
