### ISSUE TITLE
Data Source: aws_ec2_instance_spot_price

### ISSUE THREAD

**Issue by yshemesh** [terraform-providers/terraform-provider-aws#14674]
Hi, 

Using the example from docs at: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_spot_price
I get the following error:
_**The provider provider.aws does not support data source "aws_ec2_instance_spot_price".**_

Is this implemented?

Thank you,
Yaniv

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @yshemesh 👋  Thank you for reporting this and sorry for any confusion here. The data source is actually named `aws_ec2_spot_price`, but the documentation is showing the (prior to release) `aws_ec2_instance_spot_price` naming.

For example, this should work on Terraform AWS Provider version 3.1.0 and later:

```terraform
data "aws_ec2_spot_price" "example" {
  instance_type     = "t3.medium"
  availability_zone = "us-west-2a"

  filter {
    name   = "product-description"
    values = ["Linux/UNIX"]
  }
}
```

If you or anyone is interested in fixing the documentation, the source code for the file can be found in this repository at: `website/docs/d/ec2_spot_price.html.markdown`. 👍
