### ISSUE TITLE
Error reported during autoscaling group creation

### ISSUE THREAD

**Issue by abelgana** [terraform-providers/terraform-provider-aws#14682]
I have the following error when trying to create an autoscaling group:

```
provider "registry.terraform.io/-/aws" produced
an invalid new value for .tags: length changed from 4 to 5.
```

**Comment by ewbankkit** [comment]
@abelgana Thanks for raising this issue.
It has already been noticed in #14085. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
