### ISSUE TITLE
Support setting  instance metadata on launch Configuration

### ISSUE THREAD

**Issue by vkperumal** [terraform-providers/terraform-provider-aws#14684]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Launched here: https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

### New or Affected Resource(s)

* aws_launch_configuration

**Comment by bflad** [comment]
Hi @vkperumal 👋  Thank you for submitting this. It appears there is already a feature request for this functionality with https://github.com/terraform-providers/terraform-provider-aws/issues/14621, so to consolidate discussions and efforts, I'm going to close this issue in preference of the existing one.
