### ISSUE TITLE
aws_s3_bucket_inventory attribute `bucket` documentation is confusing

### ISSUE THREAD

**Issue by nairb774** [terraform-providers/terraform-provider-aws#14708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_bucket_inventory

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_inventory

Documentation says:
> `bucket` - (Required) The name of the bucket where the inventory configuration will be stored.

which is partially confusing because the inventory configuration isn't really stored in the bucket. A slightly better wording might be to swap "stored" for "applied":

> `bucket` - (Required) The name of the bucket where the inventory configuration will be **applied**.

**Comment by bflad** [comment]
Hi @nairb774 👋  If you or anyone would like to adjust this documentation, the source file lives at `website/docs/r/s3_bucket_inventory.html.markdown` in this repository.
