### ISSUE TITLE
EKS Managed Node Groups Launch Template Support

### ISSUE THREAD

**Issue by marcincuber** [terraform-providers/terraform-provider-aws#14702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for Managed Node Groups Launch Template Support

### References

* See the launch [blog](https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/) and EKS [documentation](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html) for more details

**Comment by ewbankkit** [comment]
@marcincuber Thanks for raising this issue. It is being addressed in #14639, scheduled for release with v3.3.0 of the Terraform AWS Provider.

**Comment by bflad** [comment]
Support for the new `launch_template` configuration block has been merged and will release with version 3.3.0 of the Terraform AWS Provider, likely later today. 👍

**Comment by ngadkari** [comment]
Are there any plans on back porting this feature to v2.X AWS providers?

**Comment by bflad** [comment]
@ngadkari currently, no. We are only planning on potential backport of critical crash/security fixes at this time to the previous major version. I'll work with the team to ensure our backport policy is documented.
