### ISSUE TITLE
Documentation for the `aws_db_parameter_group` resource is unclear

### ISSUE THREAD

**Issue by VSpike** [terraform-providers/terraform-provider-aws#14721]
In the docs [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group#description) it says:

> `description` - (Optional) The description of the DB parameter group. Defaults to "Managed by Terraform".

For clarity and consistency it should say 
> (Optional, Forces new resource)

Looking at the source [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_db_parameter_group.go#L57) it's definitely the case that changing the description will force a new resource.

**Comment by anGie44** [comment]
This documentation update has been merged and will be in the `v3.9.0` release of the Terraform AWS Provider, likely out later today :)
