### ISSUE TITLE
Updates for aws_eks_node_group - launch template and custom AMI

### ISSUE THREAD

**Issue by LozanoMatheus** [terraform-providers/terraform-provider-aws#14737]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Recently, AWS announced the support for launch template and custom AMI via EKS node Group.

### New or Affected Resource(s)

* aws_eks_node_group

### Potential Terraform Configuration

```hcl
resource "aws_launch_template" "example" {
  name = var.lc_name
  ...
}

resource "aws_eks_node_group" "example" {
  cluster_name    = aws_eks_cluster.example.name
  node_group_name = "example"
  node_role_arn   = aws_iam_role.example.arn
  subnet_ids      = aws_subnet.example[*].id

  launch_template {
    name    = aws_launch_template.example.name ## or var.lc_name
    version = aws_launch_template.example.latest_version
    id      = aws_launch_template.example.id
  }

  ami_type = "AL2_x86_64"

  scaling_config {
    desired_size = 1
    max_size     = 1
    min_size     = 1
  }
}
```

### References

* [Amazon EKS managed node groups now support EC2 launch templates and custom AMIs
](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-managed-node-groups-now-support-ec2-launch-templates-custom-amis/)
* [Introducing launch template and custom AMI support in Amazon EKS Managed Node Groups](https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/)
* [AWS CLI - create-nodegroup](https://docs.aws.amazon.com/cli/latest/reference/eks/create-nodegroup.html)

**Comment by bflad** [comment]
Hi @LozanoMatheus 👋  Thank you for submitting this feature request. This is covered by the previous https://github.com/terraform-providers/terraform-provider-aws/issues/14702, so to consolidate efforts and discussions, I'm going to close this issue in preference of the existing one. Please 👍  upvote and subscribe there for further updates.
