### ISSUE TITLE
Service discovery namespace data source

### ISSUE THREAD

**Issue by mbamber** [terraform-providers/terraform-provider-aws#14739]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add an `aws_service_discovery_namespace` data source for obtaining information about both DNS and HTTP namespaces

### New or Affected Resource(s)

* `aws_service_discovery_namespace`

### Potential Terraform Configuration

```hcl
data "aws_service_discovery_namespace" "my_namespace" {
  id = "ns-..."
}
```

**Comment by ewbankkit** [comment]
@mbamber Thanks for raising this issue.
It has already been noticed in #6384. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by mbamber** [comment]
Sorry @ewbankkit! I thought I'd searched for a duplicate already, and couldn't see one. My mistake
