### ISSUE TITLE
AWS service integrations for HTTP APIs

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#14761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Customers can now create Amazon API Gateway HTTP APIs that route requests to AWS AppConfig, Amazon EventBridge, Amazon Kinesis Data Streams, Amazon SQS, and AWS Step Functions.

### New or Affected Resource(s)

* [`aws_apigatewayv2_integration`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_integration)

### Potential Terraform Configuration

```hcl
resource "aws_apigatewayv2_integration" "example" {
  api_id              = aws_apigatewayv2_api.example.id
  integration_type    = "AWS_PROXY"
  integration_subtype = "SQS-SendMessage"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/08/api-gateway-http-apis-adds-integration-with-five-aws-services/).
[Blog post](https://aws.amazon.com/blogs/compute/building-storage-first-applications-with-http-apis-service-integrations/).
[Developer Guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-aws-services.html).

Requires [AWS SDK v1.34.9](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.9):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14665

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.4.0 of the Terraform AWS provider, likely later today. Thanks to @ewbankkit for the implementation. 👍
