### ISSUE TITLE
aws_fsx_lustre_file_system specify custom KMS Key

### ISSUE THREAD

**Issue by cmbrad** [terraform-providers/terraform-provider-aws#14815]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

FSX for Lustre now supports using custom KMS keys for encryption at rest. Currently the resource always uses the default FSX key, but it would be good to allow specifying custom customer managed keys. Only valid where deployment_type = "PERSISTENT_1"

* aws_fsx_lustre_file_system

### Potential Terraform Configuration

```hcl
resource "aws_fsx_lustre_file_system" "fsx" {
   # ...
   kms_key_id= "alias of encryption key"
}
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/1218
* https://docs.aws.amazon.com/fsx/latest/LustreGuide/getting-started-step1.html
* https://docs.aws.amazon.com/fsx/latest/LustreGuide/encryption-at-rest.html
* https://docs.aws.amazon.com/fsx/latest/LustreGuide/FSXKMS.html
* https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystem.html

**Comment by bflad** [comment]
Support for the `kms_key_id` argument in the `aws_fsx_lustre_file_system` resource has been merged and will release with version 3.8.0 of the Terraform AWS Provider, later this week. Thanks to @nikhil-goenka for the implementation. 👍
