### ISSUE TITLE
resource/aws_ebs_volume: support io2 volume type

### ISSUE THREAD

**Issue by roberth-k** [terraform-providers/terraform-provider-aws#14817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have [introduced](https://aws.amazon.com/blogs/aws/new-ebs-volume-type-io2-more-iops-gib-higher-durability/) the `io2` volume type. On create, the `aws_ebs_volume` resource [currently rejects](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ebs_volume.go#L128) the `iops` attribute for volumes that are not `io1`.

Requires Go SDK 1.34.10.

### New or Affected Resource(s)

* aws_ebs_volume

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://aws.amazon.com/blogs/aws/new-ebs-volume-type-io2-more-iops-gib-higher-durability/
* https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ebs_volume.go#L128

**Comment by ewbankkit** [comment]
There should also be support across other resources where a volume type can be specified:

* `aws_ami`
* `aws_instance`
* `aws_launch_configuration`
* `aws_launch_template`
* `aws_spot_fleet_request`

**Comment by chriswahl** [comment]
In case folks are searching the web with the error code, this is what is returned via CLI:

```
Error: Error creating EC2 volume: InvalidParameterCombination: The parameter iops must be specified for io2 volumes.
        status code: 400, request id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
```

**Comment by bflad** [comment]
Going to re-open this until its supported across the other resources as mentioned above.

**Comment by bflad** [comment]
Support for the other EC2 resources has been merged and will release with version 3.5.0 of the Terraform AWS Provider, likely tomorrow. Thanks to @nikhil-goenka for the implementation. 👍

**Comment by julian3xl** [comment]
`Error: Error creating launch configuration: ValidationError: io2 is invalid. Valid volume types are standard, io1, gp2, st1 and sc1.
	status code: 400, request id: 6f40d1e2-1cbc-4e9e-bf4c-8d5c4687d1f1`

* provider.aws: version = "~> 3.7"
* provider.external: version = "~> 1.2"
* provider.helm: version = "~> 1.3"
* provider.kubernetes: version = "~> 1.13"
* provider.null: version = "~> 2.1"
* provider.template: version = "~> 2.1"

**Comment by bflad** [comment]
Hi @julian3xl 👋  That error is being returned by the Auto Scaling API. You may want to verify that you are in an [AWS Region that supports the new io2 Volume type](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-announces-gerneral-availability-of-new-provisioned-iops-volume-io2-for-amazon-ebs/):

> EBS io2 volumes are generally available in US East (Ohio), US East (N. Virginia), US West (N. California), US West (Oregon), Asia Pacific (Hong Kong), Asia Pacific (Mumbai), Asia Pacific (Seoul), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), Canada (Central), Europe (Frankfurt), Europe (Ireland), Europe (London), Europe (Stockholm), and Middle East (Bahrain) with more regions coming soon.

Or otherwise open an AWS Support case.

**Comment by julian3xl** [comment]
Cool! thanks @bflad, I'll request for support because I'm running at Ireland so initially it's supposed it should be available there.

**Comment by julian3xl** [comment]
Anyway, documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration#volume_type still doesn't say anything about io2 🤷‍♂️

**Comment by bflad** [comment]
Looks like the [Auto Scaling API Reference for EBS volume handling](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_Ebs.html) does not list `io2` yet as a valid value. The AWS service team will know best whether this support was intentionally not added (more movement towards encouraging usage of EC2 Launch Templates instead) or if this will be part of future Auto Scaling API releases.

**Comment by roberth-k** [comment]
AWS have deprecated Launch Configurations, so it's not surprising that it would lag in features. It's worth considering migrating to Launch Templates for immediate [`io2` support](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateEbsBlockDeviceRequest.html).

**Comment by julian3xl** [comment]
Hi guys, thanks both of you, finally I moved to launch templates and it worked.
