### ISSUE TITLE
aws_route53_zone_association_authorization resource got kicked out of aws provider following 3.2.0 (was in 3.1.0)

### ISSUE THREAD

**Issue by bashoKa** [terraform-providers/terraform-provider-aws#14825]
Hi

The aws_route53_zone_association_authorization resource got kicked out of the 3.2.0 and 3.3.0 releases of the AWS provider. Also it was released in 3.1.0.

Would guess wasn't intended? At least I didn't see something in the release notes?

best / thanks

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

`
terraform -v
Terraform v0.12.29
+ provider.aws v3.3.0
`
`
terraform -v
Terraform v0.12.29
+ provider.aws v3.2.0
`
works in:
`
terraform -v
Terraform v0.12.29
+ provider.aws v3.1.0
`

### Affected Resource(s)

* aws_route53_zone_association_authorization

### Debug Output

`
terraform validate

Error: Invalid resource type

  on main.tf line 99, in resource "aws_route53_zone_association_authorization" "this":
  99: resource "aws_route53_zone_association_authorization" "this" {

The provider provider.aws does not support resource type
"aws_route53_zone_association_authorization".

`

### Expected Behavior

`
terraform validate
Success! The configuration is valid.

`

### Actual Behavior
`
terraform validate

Error: Invalid resource type

  on main.tf line 99, in resource "aws_route53_zone_association_authorization" "this":
  99: resource "aws_route53_zone_association_authorization" "this" {

The provider provider.aws does not support resource type
"aws_route53_zone_association_authorization".

`

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### References

* #https://github.com/terraform-providers/terraform-provider-aws/pull/14215
* #https://github.com/terraform-providers/terraform-provider-aws/blob/v3.1.0/CHANGELOG.md

**Comment by DrFaust92** [comment]
i think the first in the change log is not the correct resource name? aws_route53_vpc_association_authorization is the the resource added.

**Comment by gdavison** [comment]
Hi @bashoKa. @DrFaust92's comment above is correct.

**Comment by ericksonrory** [comment]
Was this an expected removal, are we likely to see this added in a later release?
