### ISSUE TITLE
data-source/aws_rds_orderable_db_instance: New data source

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#14834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Relates #14882, Fixed by #14853 

### Description

Knowing which combinations of DB instance class, engine, engine version, and license model are available is non-trivial especially in GovCloud and other specialty partitions. For example, attempting to use a `t3.small` on GovCloud, a valid option for `us-west-2` in the standard partition, gives this error:

```
Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t3.small, Engine=mysql, EngineVersion=5.6.41, LicenseModel=general-public-license. For supported combinations of instance class and database engine version, see the documentation.
```

I envision something similar to `aws_ec2_instance_type_offering`.

### New or Affected Resource(s)

* aws_rds_orderable_db_instance

### Potential Terraform Configuration

```hcl
data "aws_rds_orderable_db_instance" "test" {
  availability_zone_group = "us-west-2-lax-1"
  db_instance_class = "db.t2.small"
  engine = "mysql"
  engine_version = "5.7"
  license_model = "general-public-license"

  preferred_instance_types = ["t3.micro", "t2.micro"]
}

resource "aws_db_instance" "source" {
  allocated_storage   = 5
  engine              = data.aws_rds_orderable_db_instance.test.engine    # "mysql"
  engine_version      = data.aws_rds_orderable_db_instance.test.engine_version    # "5.7.22"
  identifier          = "db-source"
  instance_class      = data.aws_rds_orderable_db_instance.test.instance_class    # "db.m3.medium"
  password            = "avoid-plaintext-passwords"
  username            = "tfacctest"
  skip_final_snapshot = true
}
```

### References

* [resource/db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance)
* [data-source/db_instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/db_instance)
* [data-source/ec2_instance_type_offering](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_instance_type_offering)

**Comment by bflad** [comment]
Looks like `Filter` isn't supported yet for [`DescribeOrderableDBInstanceOptions`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeOrderableDBInstanceOptions.html) 🙁 , so we will want to fallback to regular ole arguments, e.g.

```terraform
data "aws_rds_orderable_db_instance" "example" {
  # API supported examples
  availability_zone_group = "us-west-2-lax-1"
  db_instance_class = "db.t2.small"
  engine = "mysql"
  engine_version = "5.7"
  license_model = "general-public-license"

  # Cake icing
  preferred_db_instance_classes = ["db.t2.small", "db.t3.small"]
}
```
