### ISSUE TITLE
Feature request: please expose EBS volume ids in the aws_instance object

### ISSUE THREAD

**Issue by fields** [terraform-providers/terraform-provider-aws#1485]
Hi there,

### Terraform Version
0.10.2

### Affected Resource(s)
aws_instance

### Expected Behavior
I would like to be able to get the volume ids of EBS volumes attached to an aws instance, including the root volume.

My specific use case is that I want to create a cloudwatch event to make snapshots of the volumes on a regular schedule, and this requires the volume ids.

### Actual Behavior
This information is not available.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
