### ISSUE TITLE
Support AWS Athena

### ISSUE THREAD

**Issue by countergram** [terraform-providers/terraform-provider-aws#1486]
AWS Athena supports the creation of tables and named queries both which are persistent, configurable objects. It would be valuable to support them in Terraform so that a set of known tables and queries can be configured in an AWS environment without being manually added.

https://aws.amazon.com/documentation/athena/

**Comment by atsushi-ishibashi** [comment]
It might be a good idea to wait until AWS provides api to create database for Athena.

**Comment by betabandido** [comment]
@atsushi-ishibashi It is actually already possible to create a database by running a `CREATE DATABASE` query. Therefore, I wonder if Amazon is going to add soon any direct support in the SDK for creating a database, given there is already a way to do it.

**Comment by atsushi-ishibashi** [comment]
Done #1893

**Comment by radeksimko** [comment]
As mentioned we now support the following two resources:

 - [`athena_database`](https://www.terraform.io/docs/providers/aws/r/athena_database.html)
 - [`athena_named_query`](https://www.terraform.io/docs/providers/aws/r/athena_named_query.html)

I have explained some reasoning behind my inclination to _not_ supporting `athena_table` in https://github.com/terraform-providers/terraform-provider-aws/pull/1893#issuecomment-351300973

I'm going to close this issue now. If someone feels that `athena_table` is totally must have I'd recommend opening a new issue focused on that resource only and attach some use cases (which presumably aren't "data backup/recovery"). We can also monitor upvotes (interest) that way and understand how relevant/important it is for users.

Thanks all and especially @atsushi-ishibashi for getting it done! 🎉
