### ISSUE TITLE
aws_security_group_rule resource should take a list for the source_security_group_id parameter.

### ISSUE THREAD

**Issue by mrwacky42** [terraform-providers/terraform-provider-aws#1488]
### Terraform Version
0.9.11

### Affected Resource(s)
aws_security_group_rule

### Terraform Configuration Files
```hcl
resource "aws_security_group" "yucky" {
    name = "yucky"
    vpc_id = "vpc-1234abcd"
}

resource "aws_security_group_rule" "yucky" {
    security_group_id = "${aws_security_group.yucky.id}"
    type = "egress"
    from_port       = 8443
    to_port         = 8443
    protocol        = "tcp"
    source_security_group_id = ["sg-abcd1234", "sg-abcd4321"]
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I imported an AWS security group that was created by the AWS ElasticMapReduce console.
I cannot currently write Terraform code to match the imported resource.
I expect to be able to create a single rule with multiple "source" SGs just like I can via AWS API/console.

### Actual Behavior
> * aws_security_group_rule.yucky: source_security_group_id must be a single value, not a list

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
No

### References
I didn't find any.

**Comment by mrwacky42** [comment]
How embarrassing. I was reading the plan and state incorrectly.

**Comment by Vish7792** [comment]
I having the same issue. What do you mean when you said  "I was reading the plan and state incorrectly." ?

**Comment by mrwacky42** [comment]
@Vish7792 - I'm sorry to say I do not recall.
From the context, perhaps I was expecting to write a rule with multiple sources SGs, but what I really needed was multiple rules each with a single source.
