### ISSUE TITLE
aws_dynamodb_table does not track attribute type changes (any configuration)

### ISSUE THREAD

**Issue by val1715** [terraform-providers/terraform-provider-aws#14889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.16
```
### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```
resource "aws_dynamodb_table" "test_table" {
  name         = "test_table"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "id"

  attribute {
    name = "id"
    type = "S"
  }

}
```

State of created resource:
```
terraform state show aws_dynamodb_table.test_table
# aws_dynamodb_table.test_table:
resource "aws_dynamodb_table" "test_table" {
    arn            = "arn:aws:dynamodb:us-east-1:111111111111:table/test_table"
    billing_mode   = "PAY_PER_REQUEST"
    hash_key       = "id"
    id             = "test_table"
    name           = "test_table"
    read_capacity  = 0
    stream_enabled = false
    write_capacity = 0

    attribute {
        name = "id"
        type = "S"
    }
...
}

```

### Expected Behavior

Terraform should propose to **update** existing dynamoDB table or to **recreate** it. 

### Actual Behavior

Terraform shows there are no changes

### Steps to Reproduce

1. `terraform init` 
2. `terraform apply` to create resource from snippet above
3. check created dynanoDB table, type of its attributes. 
4. change type of attribute to other (e.g. from String to Number):
```
    attribute {
        name = "id"
        type = "N"
    }
```
5. check output from with `terraform plan` 
```
No changes. Infrastructure is up-to-date.
```
6. run `terraform apply` and check existing dynamoDB table attributes (no real changes also)

### Important Factoids

According to docs it is allowed 3 types : `N`, `S`, `B`. 
Terraform does not track changes to any combination changes of them. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table

### References

(similar but has wider scope - this one not related to GSI)
https://github.com/terraform-providers/terraform-provider-aws/issues/14476

**Comment by anGie44** [comment]
Closing as this Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/14476
