### ISSUE TITLE
DynamoDB backend: 400 Bad Request when creating new workspace

### ISSUE THREAD

**Issue by ALutchko** [terraform-providers/terraform-provider-aws#14896]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
0.12.29
3.3

### Affected Resource(s)
backend initialization

### Terraform Configuration Files
```hcl
provider "aws" {
  assume_role {
    role_arn     = var.assume_role_arn
    session_name = "eks_${local.environment}"
  }
  region  = var.region
  version = "~> 3.3"
}

terraform {
  backend "s3" {
    bucket  = "bucketname"
    key     = "my_key"
    encrypt = "true"
    region  = "eu-central-1"
    role_arn = "arn:aws:iam::11111111:role/my_role"
    dynamodb_table = "tf-remote-state-lock"
  }
}
```

### Debug Output
[on pastebin](https://pastebin.com/4sbuVj0S)

### Expected Behavior
new workspace created

### Actual Behavior
it fails with (quite misleading) error:

```
failed to lock s3 state: 2 errors occurred:
* ResourceNotFoundException: Requested resource not found
* ResourceNotFoundException: Requested resource not found
```

If I turn on TF_LOG=DEBUG then I see 400 Bad Request, details on pastebin link above
### Steps to Reproduce
run `terraform workspace new test`

### Important Factoids
backend is not on the same account as the target environment
I use TF_WORKSPACE variables, and if I just run `terraform init` it fails because the workspace does not exist yet and the value cannot be provided because the process runs in pipeline:

```
terraform init
Initializing modules...

Initializing the backend...

The currently selected workspace (test) does not exist.
  This is expected behavior when the selected workspace did not have an
  existing non-empty state. Please enter a number to select a workspace:
  
  1. default

  Enter a value: 

Error: Failed to select workspace: input not a valid number

```

### References
none known

Could you help, please?

**Comment by ALutchko** [comment]
I found the reason, but it still look like misbehavior or at least proper wrror message is needed:
`terraform workspace whatcoever` should rum only AFTER `terraform init`. If you have `TF_WORKSPACE` set up, you may have error during `tf init` saying that the workspace does not exist yet, so you may have temptation to rum `tf workspace new` before `tf init`. Don't do it, just set up `TF_WORKSPACE` only after `tf init`.

**Comment by gdavison** [comment]
Hi @ALutchko. This would be related to the `terraform` tool itself. You can create issues in that repo at https://github.com/hashicorp/terraform/issues
