### ISSUE TITLE
Ability to query delegation set from hosted zone

### ISSUE THREAD

**Issue by vrcsix** [terraform-providers/terraform-provider-aws#1491]
e.g. `data.aws_route53_zone.selected.delegation_set_id`. Possibly in combination with a separate data source that allows one to query further information using the id? I'll submit these if it sounds like a good idea.

**Comment by bflad** [comment]
A new `aws_route53_delegation_set` data source has been merged and will release with version 1.47.0 of the AWS provider, sometime later this week. 👍
