### ISSUE TITLE
aws_route53_record wont update.  Please provide triggers options for aws_route53_record

### ISSUE THREAD

**Issue by queglay** [terraform-providers/terraform-provider-aws#14914]
I have aws_route53_record resources that when the target IP of the record name changes, it wont update the record.  it would be really helpful if this resource type included triggers.  triggers help solve update dependency issues a lot and would be great in this circumstance.

I am using these versions:
Terraform v0.12.29
+ provider.aws v3.3.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.random v2.3.0

Is there any other way to trigger an update based on some value changing?

**Comment by gdavison** [comment]
Hi @queglay. `aws_route53_record` resources should definitely update when an argument changes. Can you provide a sample Terraform configuration that causes this error?

**Comment by queglay** [comment]
It's a large rollout but I can show the relevant components.  I should mention that it may also be possible that the custom data type (bash script) providing the ip may also be the cause.  Triggers to force that external data type to update could also be very helpful to see if that would fix it.

After I deploy, if I taint the fsx_storage resource and apply again, it gets replaced, but the record doesn't update.

My .tf file uses:
```

resource "aws_fsx_lustre_file_system" "fsx_storage" {
  count      = ( !var.sleep && ( local.fsx_enabled == 1 ) ) ? 1 : 0
  depends_on = [ null_resource.init_fsx ]
  
  import_path      = local.fsx_import_path
  export_path      = local.fsx_import_path
  storage_capacity = var.fsx_storage_capacity
  subnet_ids       = [ element( flatten( concat( var.subnet_ids, list("") ) ), 0 ) ]
  security_group_ids = concat( aws_security_group.fsx_vpc.*.id, aws_security_group.fsx_vpn.*.id, list("") )
  deployment_type  = "SCRATCH_2" # aws provider v3.0 only

  tags = var.common_tags
}

locals {
  id = element( concat( aws_fsx_lustre_file_system.fsx_storage.*.id, list("") ), 0)
}

output "id" {
  depends_on = [
    aws_fsx_lustre_file_system.fsx_storage,
  ]
  value = local.id
}

output "network_interface_ids" {
  value = aws_fsx_lustre_file_system.fsx_storage.*.network_interface_ids
}

# Terraform provider API does not list the primary interface in the correct order to obtain it.  so we use a custom data source to aquire the primary interface

data "external" "primary_interface_id" { # Why cant we use triggers here?
  count = local.fsx_enabled
  program = ["/bin/bash", "${path.module}/primary_interface.sh"]
  
  # Arbitrary map from strings to strings, passed to the external program as the data query.
  query = { 
    id = "${local.id}"
  }
}

locals {
  primary_interface = lookup( element( concat( data.external.primary_interface_id.*.result, list( map( "primary_interface", "" ) ) ), 0), "primary_interface", "" )
}

output "primary_interface" {
  value = local.primary_interface
}

data "aws_network_interface" "fsx_primary_interface" {
  count = local.fsx_enabled
  id = local.primary_interface
}

locals {
  fsx_private_ip = element( concat( data.aws_network_interface.fsx_primary_interface.*.private_ip, list("")), 0 )
}

resource "aws_route53_record" "fsx_record" {
  count   = local.fsx_enabled
  zone_id = var.private_route53_zone_id
  name    = var.fsx_hostname
  type    = "A"
  ttl     = 300
  records = [local.fsx_private_ip]
}
```

and primary_interface.sh:
```
#!/bin/bash

# Exit if any of the intermediate steps fail
set -e

# Extract arguments from the input into
# shell variables.
# jq will ensure that the values are properly quoted
# and escaped for consumption by the shell.
eval "$(jq -r '@sh "id=\(.id)"')"

primary_interface=$(aws fsx describe-file-systems | jq ".FileSystems[] | select(.FileSystemId == \"$id\") | .NetworkInterfaceIds[0]")

# Safely produce a JSON object containing the result value.
# jq will ensure that the value is properly quoted
# and escaped to produce a valid JSON string.

jq -n --arg primary_interface "$primary_interface" "{\"primary_interface\":$primary_interface}"
```

**Comment by gdavison** [comment]
Hi @queglay, I've checked out your example here, and I have a few comments.

1. To request that the `external` data source support triggers, you can create an issue on that [provider's issues page](https://github.com/hashicorp/terraform-provider-external/issues).

1. The [`null_resource`](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) looks like it might support your existing model, since it does support triggers.

1. However, Route 53 supports alias records, which would let you directly point a Route 53 DNS record at your FSX filesystem. AWS has an [example](https://docs.aws.amazon.com/fsx/latest/WindowsGuide/walkthrough05-file-system-custom-CNAME.html) describing this process.

I'm going to close this issue. If you run into any errors or have a feature request for the AWS provider, please open another issue. Another community resource for help with implementations is our [community forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws).
