### ISSUE TITLE
 Error: Missing required argument  The argument "region" is required, but was not set.

### ISSUE THREAD

**Issue by sudlo** [terraform-providers/terraform-provider-aws#14917]
I'm using Terraform version v0.13.1 and trying to run terraform plan i get the error message as  Error: Missing required argument  The argument "region" is required but was not set.

**Scenario:**

I am trying to deploy an instance. When I enter the terraform plan it spits out the following error.

`sudlo@ubuntu:~/01-sample-instance$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v3.4.0...
- Installed hashicorp/aws v3.4.0 (signed by HashiCorp)

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/aws: version = "~> 3.4.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
sudlo@ubuntu:~/01-sample-instance$ terraform plan
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1

Error: Missing required argument

The argument "region" is required but was not set.
`
I have checked every file, I have tried it on various examples found on Github and otherwise. Kindly help

**Comment by bflad** [comment]
Hi @sudlo 👋  Thank you for reporting this and sorry you are running into trouble here. You are not doing anything wrong. This appears to be related to an unexpected regression introduced in Terraform CLI version 0.13.1, which can be tracked upstream here: https://github.com/hashicorp/terraform/issues/26035

In the meantime, this particular issue can be worked around by including the AWS region in the Terraform configuration, e.g.

```terraform
provider "aws" {
  region = "us-east-1"
}

# ... existing configuration ...
```

This will prevent the "Enter a value" prompt from appearing. Please note that if you are using [multiple provider configurations](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations), the region configuration will need to be added to each provider configuration.

For further discussions and efforts with this issue, please 👍  and subscribe to https://github.com/hashicorp/terraform/issues/26035.
