### ISSUE TITLE
Terraform does not support the http-endpoint-destination-configuration for aws firehose create-delivery-stream.

### ISSUE THREAD

**Issue by ShivaSharm** [terraform-providers/terraform-provider-aws#14933]
I wanted to create an AWS Firehose Delivery Stream using Terraform but have been struggling as I understand that Terraform does not support the http-endpoint-destination-configuration for aws firehose create-delivery-stream yet.

AWS Doc link - https://docs.aws.amazon.com/cli/latest/reference/firehose/create-delivery-stream.html
Terraform Doc ink - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream

Could someone advise if we are working to add this feature in Terraform soon. Would be of great help.

**Comment by ewbankkit** [comment]
@ShivaSharm Thanks for raising this issue.
It has already been noticed in #14469. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
