### ISSUE TITLE
Cloudfront: Realtime Log Configuration

### ISSUE THREAD

**Issue by mwarkentin** [terraform-providers/terraform-provider-aws#14945]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS [just announced "real time logs" for Cloudfront](https://aws.amazon.com/about-aws/whats-new/2020/08/cloudfront-realtimelogs/). This allows you to associate a Kinesis Data Stream with a Cloudfront Distribution in order to send logs in real time to be processed or exported using Kinesis Firehose.

### New or Affected Resource(s)

* aws_cloudfront_realtime_log_config

### Potential Terraform Configuration

```hcl
resource "aws_cloudfront_realtime_log_config" "test" {
  # There can be multiple endpoints I think, could have 1 block per endpoint? Or would you have endpoints [ endpoint, endpoint, ...]?

  name = "test_realtime_log_config"
  sampling_rate = 50
  
  fields = [
    "timestamp",
    "c-ip",
    "time-to-first-byte",
    "sc-status",
  ]

  endpoint {
     stream_type = "Kinesis"
     kinesis_stream_config = {
       role_arn = aws_iam_role.test.arn
       stream_arn = aws_kinesis_data_stream.test.arn
     }
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/08/cloudfront-realtimelogs/
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/real-time-logs.html
* https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateRealtimeLogConfig.html
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/real-time-logs.html#understand-real-time-log-config-fields

**Comment by ewbankkit** [comment]
@mwarkentin Thanks for raising this issue.
It has already been noticed in #14944. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by mwarkentin** [comment]
@ewbankkit haha.. good timing, I did try to search first 😆
