### ISSUE TITLE
Terraform 0.13.1 crash on aws_cloudfront_distribution import

### ISSUE THREAD

**Issue by peterpakos** [terraform-providers/terraform-provider-aws#14986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.4.0
```

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_distribution" "default" {
  origin {
    domain_name = aws_s3_bucket.default.bucket_regional_domain_name
    origin_id   = "S3-${aws_s3_bucket.default.id}"

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.default.cloudfront_access_identity_path
    }
  }

  enabled             = true
  is_ipv6_enabled     = false
  default_root_object = "index.html"

  aliases = [var.bucket_name]

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3-${aws_s3_bucket.default.id}"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 0
    max_ttl                = 0

    lambda_function_association {
      event_type   = "origin-request"
      include_body = false
      lambda_arn   = "arn:aws:lambda:us-east-1:225237029829:function:s3-cdn:2"
    }
  }
```

### Debug Output

https://gist.github.com/peterpakos/83d322403fa4d9fb421f5e53392f32a3

### Panic Output

https://gist.github.com/peterpakos/9b0a15f84a5e1afb9b1c136288218782

### Expected Behavior

Terraform import command successful with Cloudfront Distribution successfully imported to the state file.

### Actual Behavior

Terraform import command crashed.

### Steps to Reproduce

1. `terraform import module.s3-cdn.aws_cloudfront_distribution.default E32EAQRW369ZYR`

### Important Factoids

Cloudfront Distribution E32EAQRW369ZYR contains 2 Origins:
* S3 Origin
* Custom Origin

It also has 2 Behaviours configured:
* Default (*) for Custom Origin
* Path `ui/*` for S3 Origin.

The latter Behaviour also has Lambda@Edge Function associated with `Viewer Request`.

### References

* #14798

**Comment by bflad** [comment]
Thank you so much for reporting this, @peterpakos! This may be due to changes related to the [CloudFront Cache Key and Origin Request Policies](https://aws.amazon.com/about-aws/whats-new/2020/07/cloudfront-cache-key-policy/) since the forwarded values within the cache behaviors can now be controlled with separate CloudFront components and those simply referenced in the cache behavior. Terraform AWS Provider support for that new functionality can be tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/14373.

This should be fixed by #14993, which will be merged shortly and released tomorrow with version 3.5.0 of the Terraform AWS Provider. 👍
