### ISSUE TITLE
Support for Glue Workflow Max Concurrency

### ISSUE THREAD

**Issue by ramziyassine** [terraform-providers/terraform-provider-aws#14994]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
`August 12, 2020` [Glue Added Support for max concurrency workflow runs](https://aws.amazon.com/about-aws/whats-new/2020/08/aws-glue-provides-ability-stop-restart-glue-workflows/). My team spins up all of our Data Lake workloads using Terraform. We want to specify the new parameter as it will add predictability to our workflows.

[This is supported in Boto3 now](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_workflow)
```python
response = client.create_workflow(
    Name='string',
    Description='string',
    DefaultRunProperties={
        'string': 'string'
    },
    Tags={
        'string': 'string'
    },
    MaxConcurrentRuns=123
)
```

### New or Affected Resource(s)

* aws_glue_workflow

### Potential Terraform Configuration

```hcl
resource "aws_glue_workflow" "example" {
  name = "example"
  description = ""
  max_concurrent_runs = 1 // Default is unlimited 
}
```

### References

* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_workflow
* https://aws.amazon.com/about-aws/whats-new/2020/08/aws-glue-provides-ability-stop-restart-glue-workflows/
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_workflow

**Comment by DrFaust92** [comment]
Handled in #14910

**Comment by ramziyassine** [comment]
> Handled in #14910

much appreciated @DrFaust92
