### ISSUE TITLE
aws_cloudwatch_log_metric_filter should support multiple metric_transformation blocks

### ISSUE THREAD

**Issue by austinbyers** [terraform-providers/terraform-provider-aws#1500]
The [`put_metric_filter` API call](http://boto3.readthedocs.io/en/latest/reference/services/logs.html#CloudWatchLogs.Client.put_metric_filter) supports multiple metricTransformations in a single filter, but Terraform does not.

### Terraform Version
`Terraform v0.10.2` with `aws-provider v0.1.4`

### Affected Resource
- [aws_cloudwatch_log_metric_filter](https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_metric_filter.html)

### Terraform Configuration File
```hcl
 provider "aws" {
   version = "= 0.1.4"
 }

 resource "aws_cloudwatch_log_metric_filter" "metric_filter" {
   name           = "MyAppAccessCount"
   pattern        = ""
   log_group_name = "${aws_cloudwatch_log_group.log_group.name}"

   metric_transformation {
     name      = "EventCount"
     namespace = "YourNamespace"
     value     = "1"
   }

   metric_transformation {
     name      = "EventCount2"
     namespace = "YourNamespace"
     value     = "2"
    }
 }

 resource "aws_cloudwatch_log_group" "log_group" {
   name = "MyApp/access.log"
 }
```

### Result
```
$ terraform plan
1 error(s) occurred:

* aws_cloudwatch_log_metric_filter.metric_filter: metric_transformation: attribute supports 1 item maximum, config has 2 declared
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by ryandeivert** [comment]
After some further investigation - it appears the boto3 API for this is misleading, and the constraint on metric transformations is actually 1. As seen by attempting to call `put_metric_filter` with multiple metric transformations in the list:

`
An error occurred (InvalidParameterException) when calling the PutMetricFilter operation: 1 validation error detected: Value '[com.amazonaws.logs.v20140328.MetricTransformation@bb6aa2, com.amazonaws.logs.v20140328.MetricTransformation@2f7de737]' at 'metricTransformations' failed to satisfy constraint: Member must have length less than or equal to 1
`

**Comment by austinbyers** [comment]
Closing since this is consistent with the [boto3 API](http://boto3.readthedocs.io/en/latest/reference/services/logs.html#CloudWatchLogs.Client.put_metric_filter). Thanks @ryandeivert for looking into it!
