### ISSUE TITLE
Support for Route 53 VPC Query Logging Configurations

### ISSUE THREAD

**Issue by kylehodgetts** [terraform-providers/terraform-provider-aws#15009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Since the 27th of August 2020, AWS now supports VPC DNS Query Logging in Route53 Resolvers.
This eliminates the need for any special setup within the VPC to handle this yourself.

It would be useful to have the Terraform resources to support this, for adding to vpc modules, for example.

### New or Affected Resource(s)

* aws_route53_vpc_query_logging_configuration

### Potential Terraform Configuration

```hcl

resource "aws_cloudwatch_log_group" "myloggroup" {...}
data "aws_vpc" "vpc1" {...}
...
data "aws_vpc" "vpcn" {...}

resource "aws_route53_vpc_query_logging_configuration" "example" {
    name = "example"
    destination { # only one destination block can be specified
        type = "cloud watch" # "cloud watch", "s3", "kinesis"
        name = aws_cloudwatch_log_group.myloggroup.name
    }
    vpc_ids = [
        aws_vpc.vpc1.id,
        ...
        aws_vpc.vpcn.id,
    ]

    tags = {...}
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-route-53-resolver-supports-vpc-dns-query-logging/

**Comment by ewbankkit** [comment]
@kylehodgetts Thanks for raising this issue.
It has already been noticed in #14877. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Comment by kylehodgetts** [comment]
@ewbankkit Ah I see. Thanks for linking it.
