### ISSUE TITLE
When will AWS SSO resource be supported? 

### ISSUE THREAD

**Issue by Leectan** [terraform-providers/terraform-provider-aws#15018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
Terraform supports for AWS SSO resource
```

### References

* #0000

**Comment by gdavison** [comment]
Hi @Leectan. Could you provide some more detail on what resources you'd like to see from Terraform support for AWS Single Sign-On, please?

Enabling and configuring AWS SSO requires manual steps in the AWS Console and the API operations in the AWS SDK seem to be related to authenticating with AWS SSO

**Comment by Leectan** [comment]
@gdavison Being able to assisgn users and permissions and possibly map the APIs that are provided by AWS. The intend is to fully deploy it using Terraform and not manually.

**Comment by gdavison** [comment]
Hi @Leectan. Unfortunately, the AWS API does not expose those operations, so the Terraform AWS provider is not able to configure AWS SSO. It needs to be done using the SSO Portal.

However, nearly everything else can be done using Terraform, either with the AWS provider or others. For example, the AWS provider can configure [AWS Organizations](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_account) and [Directory Services](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_directory). Terraform can also configure identity providers such as [Active Directory (in preview)](https://registry.terraform.io/providers/hashicorp/ad/latest/docs), [Azure AD](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs), and [Okta](https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs).

You might also be able to suggest to AWS that they add API access by opening a support request with AWS.

I'm going to close this issue. If there are more developments around this service, please open another issue.
