### ISSUE TITLE
Feature Request: import support for aws_sqs_queue_policy

### ISSUE THREAD

**Issue by boompig** [terraform-providers/terraform-provider-aws#1501]
Version: Terraform v0.10.2

Command run:

```
terraform import aws_sqs_queue_policy.queue_policy arn:aws:sqs:xxxxxxx/SQSDefaultPolicy
```

Current error message:

>Error importing: 1 error(s) occurred:
>
> * aws_sqs_queue_policy.queue_policy (import id: arn:aws:sqs:xxxxxxx/SQSDefaultPolicy): import aws_sqs_queue_policy.queue_policy (id: arn:aws:sqs:xxxxxxxx/SQSDefaultPolicy): resource aws_sqs_queue_policy doesn't support import

**Comment by bflad** [comment]
Submitted a PR to import via queue URL: #2544 

Similar note as #1495, we currently only write in support for importing via the underlying Terraform resource ID, which for SQS queues (and their policy) happens to be the queue URL. However other than additional effort, the ability to import via ARN could be added separately.
