### ISSUE TITLE
The ARN and ID is returning the same value for aws_secretsmanager_secret

### ISSUE THREAD

**Issue by LozanoMatheus** [terraform-providers/terraform-provider-aws#15024]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```text
Terraform v0.12.29
+ provider.aws v3.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_secretsmanager_secret

### Terraform Configuration Files

```hcl
resource "aws_secretsmanager_secret" "example" {
  name        = "/dev/test/token"
}

output "secret_id" {
  description = "AWS Resource id"
  value       = aws_secretsmanager_secret.example.id
}

output "secret_arn" {
  description = "AWS Resource id"
  value       = aws_secretsmanager_secret.example.arn
}
```

### Debug Output

```yaml
secret_arn = arn:aws:secretsmanager:<Region>:<Account_ID>:secret:/dev/test/token-123abc
secret_id = arn:aws:secretsmanager:<Region>:<Account_ID>:secret:/dev/test/token-123abc
```

### Panic Output

N/A

### Expected Behavior

```yaml
secret_arn = arn:aws:secretsmanager:<Region>:<Account_ID>:secret:/dev/test/token-123abc
secret_id = /dev/test/token-123abc
```

### Actual Behavior

Same as `Debug Output`.

### Steps to Reproduce

1. `terraform apply`

### References

I'm not sure if this is a real bug but would be nice if it could return the ARN and the friendly name of the secret.

"--secret-id  ... You can specify either the Amazon Resource Name (ARN) or the friendly name of the secret"
https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/get-secret-value.html
https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#API_GetSecretValue_RequestSyntax

**Comment by Thiago-Dantas** [comment]
That is documented at https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/secretsmanager_secret 
```
id - Amazon Resource Name (ARN) of the secret.
arn - Amazon Resource Name (ARN) of the secret.
```
you should be able to get what you want by using a replace on the arn along with the outputs of
```
data "aws_caller_identity" "current" {}
data "aws_region" "current" {}
```

**Comment by bflad** [comment]
Hi @LozanoMatheus 👋  Thank you for raising this. The answer above is generally the recommended way to check the expected output of the `id` attribute with Terraform AWS Provider resources.

One of the caveats with the `id` attribute in Terraform is that it historically has represented not only the `id` attribute that can be referenced by other Terraform configuration, but also an underlying resource identifier that is stored in the Terraform state. This will likely change in the future, but is not currently possible with the existing Terraform Plugin SDK.

Certain Terraform resources will store and use the "easier" or "more specific" identifier that is compatible with resource read/update/delete functionality to simplify the resource implementation. AWS overall uses two forms of identifiers (name/id and ARN) and a lot of AWS service APIs along with their Terraform AWS Provider resource counterparts lean towards the ARN as the more specific identifier.

Given this is the documented behavior of the resource and that changing it would need to be handled as a breaking change in a major version update, we will prefer to keep the current implementation and close out this issue. Although using the ARN is generally preferable in most cases, if you feel that there should be an additional `aws_secretsmanager_secret` attribute that contains the name and random suffix, please reach out and we can reopen this.

In addition to the above, another solution to extracting the name and suffix from the `aws_secretsmanager_secret` ARN would be to use the [`resource` attribute of the `aws_arn` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/arn) and strip the remaining `secret:` prefix.
