### ISSUE TITLE
aws_lb switch wihout service outage

### ISSUE THREAD

**Issue by Roxyrob** [terraform-providers/terraform-provider-aws#15031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/random v2.3.0

### Affected Resource(s)

* aws_lb

### Terraform Configuration Files

```hcl
locals {
  nlb_name = "${var.nlb_cfg.name}-${var.env_type}-"
}
resource "random_id" "rnd" {
  keepers = {
    nlb_name           = local.nlb_name
    internal               = var.nlb_cfg.internal
    enable_xzone_lb      = var.nlb_cfg.enable_cross_zone_load_balancing
    pubipaz1            = var.nlb_cfg.sub_eip_map.intaz1
    pubipaz2            = var.nlb_cfg.sub_eip_map.intaz2
  }
  byte_length = floor((32 - length(local.nlb_name)) / 2)
}

resource "aws_lb" "this" {
  name                            = substr("${local.nlb_name}${random_id.rnd.hex}", 0, 32)
  internal                         = var.nlb_cfg.internal
  load_balancer_type       = "network"
  enable_cross_zone_load_balancing = var.nlb_cfg.enable_cross_zone_load_balancing
  enable_deletion_protection             = var.nlb_cfg.enable_deletion_protection

  dynamic "subnet_mapping" {
    for_each = var.nlb_cfg.sub_eip_map
    content {
      subnet_id     = var.vpc_subnets[subnet_mapping.key].id
      allocation_id = subnet_mapping.value != "" ? var.eips[subnet_mapping.value].id : ""
    }
  }

 lifecycle {
    create_before_destroy = true
  }

  tags = merge(
    var.tags
  )
}

```

### Debug Output

[DEBUG] ALB create configuration: {
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   Name: "nlbweb1-devel-1fb3cfa11a4e413ea3",
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   SubnetMappings: [{
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       AllocationId: "eipalloc-0d11d11f1b1b1b11d",
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       SubnetId: "subnet-0d54545a1b3322111"
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     },{
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       SubnetId: "subnet-1e1b5a33e1af11111"
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     }],
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   Tags: [{
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       Key: "Environment",
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       Value: "hsdevel"
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     },{
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       Key: "Terraform",
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:       Value: "true"
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     }],
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   Type: "network"
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: }
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 2020/09/04 12:46:29 [DEBUG] [aws-sdk-go] DEBUG: Request elasticloadbalancing/CreateLoadBalancer Details:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: POST / HTTP/1.1
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Host: elasticloadbalancing.eu-south-1.amazonaws.com
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: User-Agent: aws-sdk-go/1.32.12 (go1.13.7; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.13.2 (+https://www.terraform.io)
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Content-Length: 386
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Authorization: ...
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Content-Type: application/x-www-form-urlencoded; charset=utf-8
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: X-Amz-Date: ...
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Accept-Encoding: gzip
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Action=CreateLoadBalancer&Name=nlbweb1-devel-1fb3cfa11a4e413ea3&SubnetMappings.member.1.AllocationId=eipalloc-0d11d11f1b1b1b11d&SubnetMappings.member.1.SubnetId=subnet-0d54545a1b3322111&SubnetMappings.member.2.SubnetId=subnet-1e1b5a33e1af11111&Tags.member.1.Key=Environment&Tags.member.1.Value=hsdevel&Tags.member.2.Key=Terraform&Tags.member.2.Value=true&Type=network&Version=2015-12-01
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: -----------------------------------------------------
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 2020/09/04 12:46:29 [DEBUG] [aws-sdk-go] DEBUG: Response elasticloadbalancing/DeleteListener Details:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: ---[ RESPONSE ]--------------------------------------
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: HTTP/1.1 200 OK
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Connection: close
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Content-Length: 250
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Content-Type: text/xml
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Date: ...
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: X-Amzn-Requestid: ...
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: -----------------------------------------------------
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 2020/09/04 12:46:29 [DEBUG] [aws-sdk-go] <DeleteListenerResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2015-12-01/">
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   <DeleteListenerResult/>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   <ResponseMetadata>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     <RequestId>...</RequestId>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   </ResponseMetadata>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: </DeleteListenerResponse>
[TRACE] eval: *terraform.EvalWriteState
[TRACE] EvalWriteState: removing state object for module.nlbweb1.aws_lb_listener.listener["nlbweb1_lsn_http"]
[TRACE] eval: *terraform.EvalApplyPost
[TRACE] eval: *terraform.EvalUpdateStateHook
[TRACE] [walkApply] Exiting eval tree: module.nlbweb1.aws_lb_listener.listener["nlbweb1_lsn_http"] (destroy)
[TRACE] vertex "module.nlbweb1.aws_lb_listener.listener[\"nlbweb1_lsn_http\"] (destroy)": visit complete
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 2020/09/04 12:46:30 [DEBUG] [aws-sdk-go] DEBUG: Response elasticloadbalancing/CreateLoadBalancer Details:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: ---[ RESPONSE ]--------------------------------------
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: HTTP/1.1 400 Bad Request
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Connection: close
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Content-Length: 305
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Content-Type: text/xml
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: Date: ...
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: X-Amzn-Requestid: ...
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: -----------------------------------------------------
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 2020/09/04 12:46:30 [DEBUG] [aws-sdk-go] <ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2015-12-01/">
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   <Error>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     <Type>Sender</Type>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     <Code>ResourceInUse</Code>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:     <Message>The allocation IDs are not available for use</Message>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   </Error>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:   <RequestId>...</RequestId>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: </ErrorResponse>
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4: 2020/09/04 12:46:30 [DEBUG] [aws-sdk-go] DEBUG: Validate Response elasticloadbalancing/CreateLoadBalancer failed, attempt 0/25, error ResourceInUse: The allocation IDs are not available for use
[DEBUG] plugin.terraform-provider-aws_v2.70.0_x4:  status code: 400, request id: ...
[DEBUG] module.nlbweb1.aws_lb.this: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating network Load Balancer: ResourceInUse: The allocation IDs are not available for use

### Expected Behavior

Using random name and create_before_apply I expect terraform to create new aws_lb and destroy old one (avoid service outage)

### Actual Behavior

It seems that allocation_id used for subnet_mapping is the critical point, terraform configuration returns:

Error: Error creating network Load Balancer: ResourceInUse: The allocation IDs are not available for use
        status code: 400, request id: ...

Is this by design ? Cannot be switched aws_lb without making service outage (or having more aws_lb balanced by route53) ?
 
### Steps to Reproduce

1. `terraform apply`
2. change aws_lb parameters in random_id keepers
3. `terraform apply`

**Comment by bflad** [comment]
Hi @Roxyrob 👋  Thank you for submitting this.

Given the error message, the documentation of the underlying [Elastic Load Balancing API](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Operations.html), and [this AWS Premium Support article](https://aws.amazon.com/premiumsupport/knowledge-center/elb-attach-elastic-ip-to-public-nlb/) it appears that this type of configuration update might not be possible without an outage. Our best recommendation in this case would be to confirm with AWS Support via a technical support case. Since it does not appear to be actionable within this project or Terraform to workaround this EIP allocation issue, I'm going to close this issue for now. If you or AWS Support does provide a method for performing this type of update, we can reopen this. 👍 

Some additional notes: 

Looking at the [`SetSubnets` API call](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SetSubnets.html) it may not allow any type of in-place update, given this note in the AWS documentation:

> When you specify subnets for a Network Load Balancer, you must include all subnets that were enabled previously, with their existing configurations, plus any additional subnets.

Quote from [Premium Support article](https://aws.amazon.com/premiumsupport/knowledge-center/elb-attach-elastic-ip-to-public-nlb/):

> Note: After you enable a subnet in an Availability Zone, you can't modify the setting. Only new Availability Zones or subnets can be added. Elastic IP addresses can be set for new Availability Zones when you edit the settings.

It does not appear there would be a way to remove subnet mappings with EIP allocations from an existing load balancer so Terraform could not provide the functionality.
