### ISSUE TITLE
aws required_providers block inconsistent behaviour with provider block

### ISSUE THREAD

**Issue by olenm** [terraform-providers/terraform-provider-aws#15042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0

### Affected Resource(s)

`provider "aws"` and  `terraform { required_providers { } }` `aws` block

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13"

  required_providers {

    aws-east-1 = {
      alias = "aws-east-1"
      source = "hashicorp/aws"

      region = "us-east-1"
      shared_credentials_file = "~/.aws/creds"
      profile                 = "aws-acnt-1"

    }

    aws-west-1 = {
      alias = "aws-west-1"
      source = "hashicorp/aws"

      region = "us-west-1"
      shared_credentials_file = "~/.aws/creds"
      profile                 = "aws-acnt-1"

    }

  }
}



resource "aws_s3_bucket" "s3-test-e" {
  provider = (aws-east-1)
  #provider = (aws.aws-east-1)
  #provider = (aws-east-1.aws-east-1)

  bucket = "otest-region-test-e"
  acl    = "private"
  force_destroy = true

  versioning {  enabled = false  }

}
output "s3-test-e__name"    {  value = aws_s3_bucket.s3-test-e.id  }
output "s3-test-e__region"  {  value = aws_s3_bucket.s3-test-e.region  }




resource "aws_s3_bucket" "s3-test-w" {
  provider = (aws-west-1)
  #provider = (aws-west-1.aws-west-1)

  bucket = "otest-region-test-w"
  acl    = "private"
  force_destroy = true
  versioning {  enabled = false  }
}
output "s3-test-w__name"    {  value = aws_s3_bucket.s3-test-w.id  }
output "s3-test-w__region"  {  value = aws_s3_bucket.s3-test-w.region  }



```

### Expected Behavior

- no prompt for regions using the "new" `terraform { required_providers { } }` provider method
- credential input in the above block to work

### Actual Behavior

```
... [DEBUG] command: asking for input: "provider.aws-east-1.region"
provider.aws-east-1.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value:
```

and credentials not taking (from `shared_credentials_file`, ect) -  (yes, the creds DO work via env-vars, but this is limited to 1 credential set)

### Steps to Reproduce

1. `terraform plan -out=theplan`

### Important Factoids

- Explicitly NOT using env-vars to set regions+creds; using s3 buckets to test region differentials. 
- creds are also not acceptable in the `terraform { required_providers {} }` block 
- assume_role is acceptable in the above block (seems inconsistent)

### References

maybe relative? 
https://github.com/terraform-providers/terraform-provider-aws/issues/9989

### workaround
using both `provider` and `terraform { required_providers { } }` gets the job done for now 

<details>
  <summary>expand code by clicking here</summary>
  
  ```hcl
terraform {
    required_version = ">= 0.13"

    required_providers {

      aws-east-1 = {
        alias = "aws-east-1"
        source = "hashicorp/aws"

        #region = "us-east-1"
        #shared_credentials_file = "~/.aws/creds"
        #profile                 = "aws-acnt-1"
      }

      aws-west-1 = {
        alias = "aws-west-1"
        source = "hashicorp/aws"

        #region = "us-west-1"
        #shared_credentials_file = "~/.aws/creds"
        #profile                 = "aws-acnt-1"
      }

      aws-west2-1 = {
        alias = "aws-west2-1"
        source = "hashicorp/aws"

        #region = "us-west-1"
        #shared_credentials_file = "~/.aws/creds"
        #profile                 = "aws-acnt-1"

        assume_role = {
          role_arn     = "arn:aws:iam::<redacted>:role/<redacted>"
          external_id  = "<redacted>"
        }
      }

    }
  }


  provider "aws" {
    alias = "aws-east-1"
    region = "us-east-1"

    shared_credentials_file = "~/.aws/creds"
    profile                 = "aws-acnt-1"
  }

  provider "aws" {
    alias = "aws-west-1"
    region = "us-west-1"

    shared_credentials_file = "~/.aws/creds"
    profile                 = "aws-acnt-1"
  }

  provider "aws" {
    alias = "aws-west2-1"
    region = "us-west-1"

    shared_credentials_file = "~/.aws/creds"
    profile                 = "aws-acnt-2"
  }







  resource "aws_s3_bucket" "s3-test-e" {
    #provider = (aws-east-1)
    provider = (aws.aws-east-1)  ## another oddity
    #provider = (aws-east-1.aws-east-1)

    bucket = "otest-region-test-e"
    acl    = "private"
    force_destroy = true

    versioning {  enabled = false  }

  }
  output "s3-test-e__name"    {  value = aws_s3_bucket.s3-test-e.id  }
  output "s3-test-e__region"  {  value = aws_s3_bucket.s3-test-e.region  }




  resource "aws_s3_bucket" "s3-test-w" {
    #provider = (aws-west-1)
    provider = (aws-west-1.aws-west-1)

    bucket = "otest-region-test-w"
    acl    = "private"
    force_destroy = true
    versioning {  enabled = false  }
  }
  output "s3-test-w__name"    {  value = aws_s3_bucket.s3-test-w.id  }
  output "s3-test-w__region"  {  value = aws_s3_bucket.s3-test-w.region  }




  resource "aws_s3_bucket" "s3-test2-w" {
    provider = (aws-west2-1.aws-west2-1)

    bucket = "otest-region-test2-w"
    acl    = "private"
    force_destroy = true
    versioning {  enabled = false  }
  }
  output "s3-test2-w__name"    {  value = aws_s3_bucket.s3-test2-w.id  }
  output "s3-test2-w__region"  {  value = aws_s3_bucket.s3-test2-w.region  }

  ```
</details>

**Comment by vikas027** [comment]
I am too trying to use multiple AWS profiles (defined in `~/.aws/credentials`) in Terraform 0.13.2 but can't get it working, even with the workaround suggested above

**Comment by bflad** [comment]
Hi @olenm 👋  Thank you for submitting this. At the current time, this functionality is not possible within Terraform and there is nothing that can be done within the Terraform AWS Provider (or any provider) to receive and handle any provider configuration within that top-level `terraform` configuration. The parsing and handling of that configuration is completely done by Terraform core and it does not pass any of that information to the associated provider during provider initialization.

If you are interested in this functionality, our best recommendation currently would be to submit a new feature request upstream in the [hashicorp/terraform repository](https://github.com/hashicorp/terraform/issues), outlining that you would like to be able to pass Terraform Provider configuration in the `required_providers` configuration to all providers of that type during provider initialization. Given there is nothing that can be implemented within the Terraform AWS Provider for this functionality right now, I'm going to close this, but if Terraform core begins supporting this type of configuration passing and we need to do anything within this codebase to support it, we can reopen this. 👍

**Comment by olenm** [comment]
Hello @bflad : to clarify, the keys/values within the aws-block within the `required_providers` are handled within the terraform repository itself ? 

So for multiple endpoints, should I be utilizing the `provider` block for aws or using the `required_providers` - I am now a little confused as the docs page pointed to this repository for the provider configuration (https://registry.terraform.io/providers/hashicorp/aws/latest/docs) 
It is especially confusing the docs state to use the `required_providers` for TF 0.13+ and `provider` block for TF 0.12 and below.

**Comment by bflad** [comment]
>  to clarify, the keys/values within the aws-block within the required_providers are handled within the terraform repository itself ?

Yes, however `source` and `version` were the only arguments intended to be supported within `required_providers` as this configuration handling is only used for Terraform Provider installation. Please see https://github.com/hashicorp/terraform/pull/26184 for future error messaging.

> So for multiple endpoints, should I be utilizing the provider block for aws or using the required_providers

One `required_providers` to specify the Terraform AWS Provider version to install and multiple `provider "aws"` configurations, each with the necessary region/endpoint configuration. See also: https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-configurations

**Comment by olenm** [comment]
@bflad awesome thank you much! 
I was anticipating the `required_providers` was going to replace and phase out the `provider` block due to the way the `How to use this provider` section had annotated things. 

Much appreciated!

**Comment by bflad** [comment]
@olenm your last comment with the additional `How to use this provider` context was very helpful! I apologize if I missed that before. I have reached out to the team that works on the Terraform Registry to further clarify that particular documentation since it does seem to be quite confusing at the moment.
