### ISSUE TITLE
aws_apigatewayv2_domain_name should support EDGE_OPTIMIZED

### ISSUE THREAD

**Issue by davidkarlsen** [terraform-providers/terraform-provider-aws#15047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_apigatewayv2_domain_name only supports `REGIONAL` but should support `EDGE_OPTMIZED` too.

### New or Affected Resource(s)

* aws_apigatewayv2_domain_name

### Potential Terraform Configuration

```hcl
resource "aws_apigatewayv2_domain_name" "domain" {
  depends_on = [aws_acm_certificate_validation.certificate_validation]
  domain_name = var.domain
  tags = var.common_tags
  domain_name_configuration {
    certificate_arn = aws_acm_certificate.certificate.arn
    endpoint_type = "REGIONAL" // OK
    #endpoint_type = "EDGE_OPTIMIZED" // fails
    security_policy = "TLS_1_2"
  }```

### References

https://aws.amazon.com/premiumsupport/knowledge-center/custom-domain-name-amazon-api-gateway/

**Comment by ewbankkit** [comment]
@davidkarlsen Thanks for raising this issue.
Currently only REST APIs ([`aws_api_gateway_domain_name`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_domain_name)) can use edge-optimized custom domain names.
The `aws_apigatewayv2` resources are used for WebSocket APIs and HTTP APIs.
