### ISSUE TITLE
Fix provider test for resource aws_spot_fleet_request

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#15062]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### 

This is a tracking issue to fix `TestAccAWSSpotFleetRequest_iamInstanceProfileArn` acceptance test by replacing the custom TestCheckFunc with resource.TestCheckResourceAttrPair():

```
--- FAIL: TestAccAWSSpotFleetRequest_iamInstanceProfileArn (282.40s)

    resource_aws_spot_fleet_request_test.go:391: 1 error occurred:
          * Check 3/3 error: Expected IamInstanceProfile input as ARN, got arn:aws-us-gov:iam::--OMITTED--:instance-profile/tf-test-profile1-tf-acc-test-823774108705333455
```

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
AWS v3.5.0

### Affected Resource(s)

* aws_spot_fleet_request

### References

* #15019

**Comment by bflad** [comment]
This test is passing currently, closing!
