### ISSUE TITLE
aws_autoscaling_group errors out on first run, completes on subsequent runs - attribute mismatch: availability_zones

### ISSUE THREAD

**Issue by zanthorn** [terraform-providers/terraform-provider-aws#1508]
### Terraform Version
Terraform v0.10.2

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "ecs-as" {
    availability_zones   = ["us-east-1a","us-east-1b"]
    name                 = "${aws_ecs_cluster.ecs.name}"
    min_size             = "${var.autoscale_min}"
    max_size             = "${var.autoscale_max}"
    desired_capacity     = "${var.autoscale_desired}"
    health_check_type    = "EC2"
    launch_configuration = "${aws_launch_configuration.ecs-lc.name}"
    vpc_zone_identifier  = ["${aws_subnet.ecs-1a.id}","${aws_subnet.ecs-1b.id}"]
    tag {
      key                 = "Name"
      value               = "${aws_ecs_cluster.ecs.name}"
      propagate_at_launch = true
    }
}
```

### Debug Output
I cannot run this again with the debug output since it only happens on the first run.
https://gist.github.com/zanthorn/a049ea59f5fdae31bd12bfe9becb091a

### Crash Output
NA

### Expected Behavior
Creates the autoscaling group on the first `terraform apply`

### Actual Behavior
Errors out due to attribute mismatch and is successfully created on the 2nd run with no changes to the terraform code.

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
Nothing special.

### References
NA

**Comment by andrewschleifer** [comment]
Remove the `availability_zones` from the `aws_autoscaling_group` definition as a work-around (since they can be derived from the `vpc_zone_identifier`). I've got some notes about the cause in https://github.com/terraform-providers/terraform-provider-aws/issues/1630.

**Comment by zanthorn** [comment]
Thanks @andrewschleifer! Makes sense and seems to be working without the `availibility_zones` set.
