### ISSUE TITLE
aws_db_parameter_group parameter updates not working in v2

### ISSUE THREAD

**Issue by jamesmharvey** [terraform-providers/terraform-provider-aws#15082]
Note: this is the same issue as https://github.com/terraform-providers/terraform-provider-aws/issues/13551 . This is a request to add it the fix, https://github.com/terraform-providers/terraform-provider-aws/pull/12112 , as a point release in the v2.x.x series, due to the number of breaking changes in v3.0.0

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.26

* provider.aws 2.70.0

### Affected Resource(s)

* aws_db_parameter_group

### Terraform Configuration Files

```hcl
resource "aws_db_parameter_group" "postgres_10" {
  name        = "psql-pg-test-10"
  family      = "postgres10"
  description = "Postgres parameter group test"

  lifecycle {
    create_before_destroy = true
  }

  parameter {
    name         = "rds.pg_stat_ramdisk_size"
    value        = 256
    apply_method = "pending-reboot"
  }
}
```

### Panic Output

N/A

### Expected Behavior

Parameter group value is updated

### Actual Behavior

Parameter group remains the same

The plan output looks like this:

```
      - parameter {
          - apply_method = "pending-reboot" -> null
          - name         = "rds.pg_stat_ramdisk_size" -> null
          - value        = "0" -> null
        }
      + parameter {
          + apply_method = "pending-reboot"
          + name         = "rds.pg_stat_ramdisk_size"
          + value        = "256"
        }
```

Reading the code, it sees this a removal of an old parameter and the addition of a new parameter, and then modifies the parameter group with the new value, and then resets the old parameter back to the existing value. Even swapping the order of those two operations would likely fix this issue

### Steps to Reproduce

1. Create an empty parameter group using terraform
2. Update the parameter group to use rds.pg_stat_ramdisk_size = 256

### Important Factoids

This has already been fixed in v3.3.0, but due to the number of breaking changes in v3.0.0, it's difficult to migrate from 2.70.0 to 3.0.0. This is a request to release a pointfix to 2.70.0 with the fix to this issue.

I realize this is a long shot, but I figured it's worth asking.

**Comment by sutharshan-sharma** [comment]
As @amesmharvey said upgrading to v3.3.0 cause many breaks + not all the modules are supported v.3.3.0 
Better if this get fixed in 2.70.0 provider version

**Comment by sulabhk** [comment]
We use provider v2.62 currently and do not want to unnecessarily migrate to 3.x given the added preparation and analysis required to get there. This should ideally have been working for 2.x too.

**Comment by gdavison** [comment]
Hi @jamesmharvey, @sutharshan-sharma, @sulabhk. In general, our policy is to make fixes and add new features to the current version. We understand this isn't ideal, but unfortunately we don't currently have the capacity to maintain multiple versions of the provider at the same time. We've recently [updated our FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#once-a-major-release-is-published-will-new-features-and-fixes-be-backported-to-previous-versions) to capture this.
