### ISSUE TITLE
Upgrade to 3.0 documentation does not indicate breaking change in aws_launch_template data source

### ISSUE THREAD

**Issue by arielpeltz** [terraform-providers/terraform-provider-aws#15094]
According to https://github.com/terraform-providers/terraform-provider-aws/issues/13410 there is a behaviour change in the data source so that if no match is found an error is raised.  This change is not documented in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade.

As a side note, the change does make sense but it should have been accompanied by having a data source like `aws_launch_templates` that can return an empty list.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/aws v3.5.0

### Affected Resource(s)

* aws_launch_template

### References

* #13410

**Comment by bflad** [comment]
Hi @arielpeltz 👋  Thank you for raising this. If you or anyone is interested in adding this to the Version 3 Upgrade Guide, its source can be found in the [`website/docs/guides/version-3-upgrade.html.markdown` file](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/guides/version-3-upgrade.html.md). 👍

**Comment by anGie44** [comment]
This documentation has been merged and will be reflected in `v3.8.0` of the Terraform AWS Provider, expected out later next week.
