### ISSUE TITLE
Ignore whitespace changes to aws_opsworks_stack custom_json

### ISSUE THREAD

**Issue by Velgus** [terraform-providers/terraform-provider-aws#15104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform:
```
0.13.1
```
Provider:
```
3.5.0
```
### Affected Resource(s)

* aws_opsworks_stack

### Expected Behavior

The plan ignores irrelevant whitespace changes in the stack custom JSON that might occur due to the way AWS parses the input.

### Actual Behavior

The plan includes the the stack resource with whitespace changes, even if nothing else is being changed. Eg.
```
 ~ custom_json                   = jsonencode( # whitespace changes
```

### Steps to Reproduce

1. Create an `aws_opsworks_stack` resource with input included for custom_json
2. `terraform apply`

### References

* Similar to terraform-providers/terraform-provider-azurerm [#5500](https://github.com/terraform-providers/terraform-provider-azurerm/issues/5500)

**Comment by bflad** [comment]
Hi @Velgus 👋  Thank you for raising this. Do you have an example `custom_json` configuration that causes this? What's interesting is that the resource just recently got an update in 3.5.0 that should have handled this (https://github.com/terraform-providers/terraform-provider-aws/pull/14886/files#diff-feed7af67735821f1b509208bdc18778R136).

**Comment by Velgus** [comment]
Ah, this was a mistake on my end - my apologies. Thank you for the clarification.
