### ISSUE TITLE
Provider accesses DescribeVpcClassicLink API calls when ClassicLink is disabled

### ISSUE THREAD

**Issue by ncarroll0488** [terraform-providers/terraform-provider-aws#15107]
### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.2
* -/aws: version = "~> 3.5.0"
* hashicorp/aws: version = "~> 3.5.0"
```

### Affected Resource(s)

* `aws_vpc`

### Terraform Configuration Files

```hcl
resource "aws_vpc" "vpc" {
  cidr_block                       = 203.0.113.0/24
  enable_classiclink               = false
  enable_classiclink_dns_support   = false
  assign_generated_ipv6_cidr_block = false
  tags = {
    Name        = format("%s-%s-igw", var.app_name, var.app_environment)
    Environment = var.app_environment
  }
}
```

### Debug Output

https://gist.github.com/ncarroll0488/fb18e7aeb31060d9161176171b341241

### Panic Output

N/A

### Expected Behavior

Terraform should not call out to `DescribeVpcClassicLink` when importing a VPC if ClassicLink has been explicitly disabled 

### Actual Behavior

Terraform calls out to `DescribeVpcClassicLink` when importing a VPC that has ClassicLink disabled

### Steps to Reproduce
1. Click-ops to create a VPC in AWS
1. Write out the aforementioned TF file and initialize your provider
1. Run `TF_LOG=debug terraform import aws_vpc.vpc vpc-yourvpcidhere`
1. You will see calls to `DescribeVpcClassicLink`

### Important Factoids

The account in question has explicitly disabled `*ClassicLink*` API calls in our IAM policy, however this is largely irrelevant - it simply changes the outcome of an API call that probably shouldn't happen in the first place.

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/pull/12808

**Comment by ewbankkit** [comment]
Currently only `UnsupportedOperation` is used as an indicator of ClassicLink being unavailable:

https://github.com/terraform-providers/terraform-provider-aws/blob/e67040b5897580572b6736642c1e5248bf2386ab/aws/resource_aws_vpc.go#L295-L303

It looks like `UnauthorizedOperation` needs to be added.

**Comment by bflad** [comment]
I'm not sure this is necessarily a bug. The Terraform resource needs to continually check the API call for drift detection. Also during import, the resource does not have access to any information in the configuration since its not provided by Terraform core.

**Comment by ncarroll0488** [comment]
On second consideration, I agree with @bflad . This is a normal part of drift detection and not a bug. I'll leave it up the experts to decide if `UnauthorizedOperation` requires special handling.
