### ISSUE TITLE
aws_route53_zone_association is unable to create/read/import associations from another account

### ISSUE THREAD

**Issue by hmrbarros** [terraform-providers/terraform-provider-aws#15100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0

### Affected Resource(s)

* aws_route53_zone_association

### Terraform Configuration Files

```hcl
resource "aws_route53_zone_association" "external-account-zone-association" {
  zone_id    = "AAAAAAAAAAAAAA"
  vpc_id     = "vpc-aaaaaaaaaaaaa" # VPC ID from another account
  vpc_region = "us-east-1"
}
```

### Debug Output

https://gist.github.com/hmrbarros/59f7401c331083e93850671bcc475983

### Panic Output
N/A

### Expected Behavior
Should be imported, the values are correct and the associations exists.
It's working on version 2.70 of the provider.

### Actual Behavior
```
Error: Cannot import non-existent remote object
```

### Steps to Reproduce
- `terraform import 'aws_route53_zone_association.zone_association["AAAAAAAAAAAAAA_vpc-aaaaaaaaaaaaa"]' 'AAAAAAAAAAAAAA:vpc-aaaaaaaaaaaaa'`

### Important Factoids
We have full permissions in the account that owns the Route53 Zone and no permissions in the account that owns the VPC.

Although the code here represents the issue when importing the resource, the same happens when creating a new resource in the same conditions.

If a state from 2.70 exists, 3.5 will ignore these resources that reference VPCs in another account

### References
N?A

**Comment by anGie44** [comment]
Hi @hmrbarros, thank you for creating this issue! Given the cross-account nature, I believe this stems from [changes](https://github.com/terraform-providers/terraform-provider-aws/blob/d4bb1be0fc757d66c3e589a8bbd3c15e3fdc832d/CHANGELOG.md) made in `v3.1.0` of the provider, whereby the API method was updated and an additional resource was added to handle references to a VPC in another account.

As you're experiencing this on resource creation in addition to import, I'd recommend following the example here to use the `route53_vpc_association_authorization` resource to link the `route53_zone_association` with the vpc in the alternate account: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_vpc_association_authorization 

If the same access denied error persists with this workaround, please let me know :)

**Comment by hmrbarros** [comment]
Hello @anGie44,

You are correct, it is `ListHostedZonesByVPC` that is creating the issue. 

Your suggestion works, I see were our problem lies, since these associations were done previously without terraform, we were able to import them to the provider that isn't the owner of the VPC.

Looking at both your example and AWS documentation this is a better way of doing things.
Thanks for the help, I'll close my PR and this issue. 🙏
