### ISSUE TITLE
 Instance market options are not supported with the launch template EKS terraform

### ISSUE THREAD

**Issue by indraindrajit71** [terraform-providers/terraform-provider-aws#15118]
Hello Team

I am trying to create an EKS cluster comprising of  spot instances:
Whenever it tries to create the "node group" (terraform apply, gives an error saying :
PS: no error is found while doing "terraform validate" or "terraform plan"

error: **error creating EKS Node Group (terraform-eks-demo:demo): InvalidParameterException: Instance market options are not supported with the launch template.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "1aefd74a-8d73-4e79-9639-c5c8833bed78"
  },
  Message_: "Instance market options are not supported with the launch template."
}**

Note: I created an aws launch template and trying to attach it with the eks node group:

```resource "aws_iam_role" "demo-node" {
  name = "terraform-eks-demo-node"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "demo-node-AmazonEKSWorkerNodePolicy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
  role       = aws_iam_role.demo-node.name
}

resource "aws_iam_role_policy_attachment" "demo-node-AmazonEKS_CNI_Policy" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  role       = aws_iam_role.demo-node.name
}

resource "aws_iam_role_policy_attachment" "demo-node-AmazonEC2ContainerRegistryReadOnly" {
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
  role       = aws_iam_role.demo-node.name
}

resource "aws_eks_node_group" "demo" {
  cluster_name    = aws_eks_cluster.demo.name
  node_group_name = "demo"
  node_role_arn   = aws_iam_role.demo-node.arn
  subnet_ids      = aws_subnet.demo[*].id
  launch_template {
        id      = aws_launch_template.demo.id
    version = "$Latest"
  }

    scaling_config {
    desired_size = 3
    max_size     = 3
    min_size     = 1
  }

  depends_on = [
    aws_iam_role_policy_attachment.demo-node-AmazonEKSWorkerNodePolicy,
    aws_iam_role_policy_attachment.demo-node-AmazonEKS_CNI_Policy,
    aws_iam_role_policy_attachment.demo-node-AmazonEC2ContainerRegistryReadOnly,
  ]
}

data "aws_ami" "amazon" {
  most_recent = true

  filter {
    name   = "name"
    values = ["amzn-ami-hvm-????.??.?.????????-x86_64-gp2"]
  }
  owners = ["amazon"] # Canonical
}

resource "aws_launch_template" "demo" {
  name                        = "demo"
  instance_type               = "m4.large"
  key_name                    = "gitlab"
  image_id                    = data.aws_ami.amazon.id
  security_group_names        = ["${aws_security_group.demo-cluster.id}"]

  network_interfaces {
    associate_public_ip_address = true
  }
  instance_market_options {
    market_type = "spot"
    spot_options {
      max_price = "0.0430"
      spot_instance_type = "one-time"
    }
  }
}
```

terraform Version details:

Terraform v0.12.24
+ provider.aws v3.5.0

can someone please help as what is being missed. I want the launch template to be attached with my node group.

**Comment by anGie44** [comment]
Hi @indradhanush, thank you for creating this issue! Reading along here: https://docs.aws.amazon.com/eks/latest/APIReference/API_LaunchTemplateSpecification.html it looks like in order to attach a launch template to an EKS Node group, the launch template configuration cannot include a reference to `RequestSpotInstances` thus I believe to get this configuration running, you'd have remove the `instance_market_options` configuration block from the `aws_launch_template` resource to be in-line with the EKS Node Group configuration requirements per AWS. 

Hope this recommendation helps! If you still come across issues while creating the EKS Node Group, please let me know :)

**Comment by indraindrajit71** [comment]
Thanks, @anGie44 
makes sense.
Closing this issue for now !!
