### ISSUE TITLE
EKS: Subnet order change forces replacement

### ISSUE THREAD

**Issue by hameno** [terraform-providers/terraform-provider-aws#15113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.6.0
+ provider registry.terraform.io/hashicorp/helm v1.2.4
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2

### Affected Resource(s)

* aws_eks_cluster

### Terraform Configuration Files

Using https://github.com/terraform-aws-modules/terraform-aws-eks so no direct example other than:

```hcl

data "aws_subnet_ids" "private_subnets" {
  vpc_id = var.vpc_id
  tags = {
    "Tier" = "private"
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "12.2.0"

  cluster_name    = var.eks_cluster_name
  cluster_version = var.eks_cluster_version
  subnets = data.aws_subnet_ids.private_subnets.ids
  vpc_id          = var.vpc_id
}
```

### Expected Behavior

The resource should not be marked as force re-create

### Actual Behavior

The resource was marked as force re-create. Plan output:

```
# module.XXX_eks.module.eks.module.node_groups.random_pet.node_groups["0"] must be replaced
+/- resource "random_pet" "node_groups" {
      ~ id        = "eager-mastodon" -> (known after apply)
      ~ keepers   = { # forces replacement
            "iam_role_arn"              = "arn:aws:iam::XXXXXX:role/XXXXXX"
            "instance_type"             = "t3.medium"
            "key_name"                  = ""
            "node_group_name"           = "XXXXXX-0"
            "source_security_group_ids" = ""
          ~ "subnet_ids"                = "subnet-1111111111|subnet-33333333333|subnet-22222222222" -> "subnet-1111111111|subnet-22222222222|subnet-33333333333"
        }
        length    = 2
        separator = "-"
    }
```

### Steps to Reproduce

Create EKS cluster using terraform-aws-modules/terraform-aws-eks with terraform-aws-modules/terraform-aws-vpc module output for subnets.
Switch to retrieving the subnets with aws_subnet_ids data source, causing the order of the subnets to change

### References

https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1006

* #0000

**Comment by hameno** [comment]
Note: As a workaround I did a manual reordering like this
```hcl
data "aws_subnet_ids" "private_subnets" {
  vpc_id = var.vpc_id
  tags = {
    "Tier" = "private"
  }
}
locals {
  private_subnets = tolist(data.aws_subnet_ids.private_subnets.ids)
}
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "12.2.0"
...
  subnets         = [
    element(local.private_subnets, 0),
    element(local.private_subnets, 2),
    element(local.private_subnets, 1)
  ]
...
}
```

**Comment by bflad** [comment]
Hi @hameno 👋  Thank you for raising this and sorry you are running into trouble here.

Is there additional output from the plan before the `random_pet` resource indicating an issue with a Terraform AWS Provider data source or resource? The example above only shows the `random_pet` resource difference, which would be managed outside this codebase, likely in the `terraform-aws-modules/eks` module. The Terraform AWS Provider maintainers here cannot provide guidance on configuration or module issues outside bugs or feature requests with Terraform AWS Provider data sources or resources.

For reference: The `aws_subnet_ids` data source returns EC2 Subnet identifiers in an unordered manner as the EC2 API does not guarantee ordering. The `aws_eks_cluster` resource `vpc_config` `subnet_id` argument accepts EC2 Subnet identifiers in an unordered manner as the EKS API is not concerned about the ordering.

Any modules working with the EC2 Subnets in this case would need to be coded in a manner accepting of ordering changes, e.g. potentially using the `sort()` function.

**Comment by hameno** [comment]
I was sent here by the maintainers of the aws/eks module, I don't really know the root cause 🤷‍♂️

**Comment by bflad** [comment]
Looks like an upstream module maintainer has responded and there's nothing to indicate the Terraform AWS Provider data sources or resources are doing anything incorrect here, so I'm going to close this for now. If more information can be provided on a specific issue with one of our data sources or resources, we can reopen this. 👍
