### ISSUE TITLE
aws_s3_bucket perpetual diff in lifecycle_rule expiration block

### ISSUE THREAD

**Issue by lijok** [terraform-providers/terraform-provider-aws#15138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
aws provider v3.5.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
resource aws_s3_bucket this {
  bucket              = var.name
  acl                 = "private"
  policy              = data.aws_iam_policy_document.this.json
  request_payer       = "BucketOwner"
  force_destroy       = false
  acceleration_status = "Enabled"

  lifecycle_rule {
    abort_incomplete_multipart_upload_days = 7
    enabled                                = true
    id                                     = "Clean up incomplete multipart uploads"
    tags                                   = {}
  }

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = [
      "GET",
      "HEAD",
      "POST",
      "PUT"
    ]
    allowed_origins = ["*"]
    expose_headers  = ["ETag"]
    max_age_seconds = 0
  }

  lifecycle {
    prevent_destroy = false
  }
}
```

### Debug Output

```hcl
  ~ resource "aws_s3_bucket" "this" {
        acceleration_status         = "Enabled"
        acl                         = "private"
        force_destroy               = false
        request_payer               = "BucketOwner"

        cors_rule {
            allowed_headers = [
                "*",
            ]
            allowed_methods = [
                "GET",
                "HEAD",
                "POST",
                "PUT",
            ]
            allowed_origins = [
                "*",
            ]
            expose_headers  = [
                "ETag",
            ]
            max_age_seconds = 0
        }

      ~ lifecycle_rule {
            abort_incomplete_multipart_upload_days = 7
            enabled                                = true
            id                                     = "Clean up incomplete multipart uploads"
            tags                                   = {}

          - expiration {
              - days                         = 0 -> null
              - expired_object_delete_marker = false -> null
            }
        }

        versioning {
            enabled    = true
            mfa_delete = false
        }
    }
```
### Actual Behavior

No matter how many times I apply, terraform plan keeps on outputting this diff
### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by anGie44** [comment]
Hi @lijok, thank you for creating this issue! This looks like a result from the upstream API, as it's returning `expiration` related information while not explicitly configured. A quick remedy in the meantime could be to explicitly add the `expiration` configuration block to your terraform config, assuming it's still inline with the overall resource configuration.

**Comment by LordMike** [comment]
I've just tried the workaround, and it seems to work. I cleared my lifecycle policies and let Terraform recreate them with this block:

```
  lifecycle_rule {
    id      = "Incomplete uploads"
    enabled = true

    abort_incomplete_multipart_upload_days = 7

    # Bug in terraform means we add this (https://github.com/terraform-providers/terraform-provider-aws/issues/15138)
    expiration {
      days                         = 0
      expired_object_delete_marker = false
    }
  }
```

I'm seeing what I hoped for in the S3 UI - no "delete after 0 days" rule. 👍
