### ISSUE TITLE
Importing AWS S3 buckets requires se:ListBucket permission

### ISSUE THREAD

**Issue by nimrodkor** [terraform-providers/terraform-provider-aws#15148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform version - 0.13.2
AWS provider version - 3.4

### Affected Resource(s)
* aws_s3_bucket

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" "state_bucket" {
  bucket = "bc-state-809694787632-us-east-1-hadards"
}
```

### Expected Behavior
The resource should have been imported

### Actual Behavior
The import fails, with this message:
```
Error: error reading S3 Bucket (bc-state-809694787632-us-east-1-hadards): Forbidden: Forbidden
	status code: 403, request id: FP1R5P1M7J4WBY6M, host id: CHffxtIOwzfmTyTsq04fsFgbnB232IiIs0xuH5Lkp9YdpsbDvhaW44XLf6KDui2cGCLEc+2OpgM=
```

### Steps to Reproduce

1. `terraform import aws_s3_bucket.state_bucket bc-state-809694787632-us-east-1-hadards`

### Important Factoids
I ran this using a role which has the `SecurityAudit` policy, and got this error. Once I added the privilege `s3:ListBucket`, I was able to import that bucket. However, I don't understand why that privilege is necessary - I can fully describe the bucket using the `SecurityAudit` permissions, and this specific privilege is very sensitive. Can the code be changed to not require this privilege?

I am open to writing it myself if you can point me to the right places!

**Comment by anGie44** [comment]
Hi @nimrodkor, thank you for creating this issue! The need for the privilege stems from the API method [`HeadBucket`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html) used when importing the bucket resource, seen here w/in the `resourceAwsS3BucketRead` method: https://github.com/terraform-providers/terraform-provider-aws/blob/4a717f87d2d996fc9b268456b5d206f9e8d583a4/aws/resource_aws_s3_bucket.go#L825 . Unfortunately, working around the error you're seeing in the provider would be tricky as the method is necessary to check the bucket exists and appropriate permissions are met.
