### ISSUE TITLE
enable encryption in aws efs

### ISSUE THREAD

**Issue by hamzasa** [terraform-providers/terraform-provider-aws#1514]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.9

### Affected Resource(s)
- aws_efs_file_system

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
enable encryption in EFS

### Actual Behavior
No option to enable encryption in EFS

**Comment by gazoakley** [comment]
@hamzasa This will feature in an upcoming release - see https://github.com/terraform-providers/terraform-provider-aws/issues/1422

**Comment by Ninir** [comment]
Hey @hamzasa 

@gazoakley is indeed right: https://github.com/terraform-providers/terraform-provider-aws/pull/1420 added it a few times ago. Will be part of the 1.0.0 release! 🎆 

Closing!

**Comment by hamzasa** [comment]
Thanks @gazoakley and @Ninir
