### ISSUE TITLE
Support for customer_owned_ipv4_pool for Outpost ALBs

### ISSUE THREAD

**Issue by davidschou** [terraform-providers/terraform-provider-aws#15147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature request is to add the ability to use **customer_owned_ipv4_pool** when creating an ALB in Outpost.  

![Screen Shot 2020-09-14 at 5 22 52 PM](https://user-images.githubusercontent.com/2050049/93150785-f26a0c00-f6ae-11ea-909b-93284451deef.png)

```
aws elbv2 create-load-balancer --name my-load-balancer --subnets <SUBNET> --scheme internal --customer-owned-ipv4-pool <COIP_POOL_ID>
```
https://docs.aws.amazon.com/cli/latest/reference/elbv2/create-load-balancer.html

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "test" {
  name                         = "test-lb-tf"
  internal                     = true
  load_balancer_type           = "application"
  security_groups              = [aws_security_group.lb_sg.id]
  subnets                      = [aws_subnet.public.*.id]
  customer_owned_ipv4_pool     = <COIP_POOL_ID>
}
```

### References

I couldn't find any issues relating to this.  Apologies if my searching was lacking and there is.

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 3.8.0 of the Terraform AWS Provider, next Thursday. Thanks to @johnbarney for the implementation. 👍
