### ISSUE TITLE
tests/resource/aws_dx_gateway_association: Occasional Timeout Errors on Destroy

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#15164]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Occasionally we will see test failures like the following:

```
=== CONT  TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount
TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount: resource_aws_dx_gateway_association_test.go:439: [INFO] Got non-empty plan, as expected
TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount: testing_new.go:22: WARNING: destroy failed, so remote objects may still exist and be subject to billing
TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount: testing_new.go:22: failed to destroy: terraform failed: exit status 1
stderr:
Error: Error waiting for VPN Gateway "vgw-03536ea6e83370462" to detach from VPC "vpc-0eb7ce1912697a59d": timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)
--- FAIL: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount (3066.89s)

=== CONT  TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount
TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount: testing_new.go:22: WARNING: destroy failed, so remote objects may still exist and be subject to billing
TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount: testing_new.go:22: failed to destroy: terraform failed: exit status 1
stderr:
Error: Error waiting for VPN Gateway "vgw-0e233bbbd69ea10fb" to detach from VPC "vpc-0d46b03aca616bf1b": timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)
--- FAIL: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount (3082.51s)
```

This would either suggest we need to increase the default detachment timeout and/or we can potentially remove the separate `aws_vpn_gateway_attachment` resource usage to see if it changes anything.

### Affected Resource(s)

* aws_dx_gateway_association

### Potential Terraform Configuration

```hcl
resource "aws_vpn_gateway" "test" {
  vpc_id = aws_vpc.test.id

  tags = {
    Name = %[1]q
  }
}
```

**Comment by ewbankkit** [comment]
Looking at the code, removing the `aws_vpn_gateway_attachment` resource and specifying `vpc_id` on the `aws_vpn_gateway` resource will potentially make the error occur more frequently as the `aws_vpn_gateway` resource has its own detachment implementation that has a 10 minute timeout 😄.

**Comment by bflad** [comment]
Getting both resources to a shared timeout constant in `aws/internal/service/ec2/waiter` would be nice. 👍
