### ISSUE TITLE
tests/provider: DB Proxy not currently supported on GovCloud

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#15175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

DB proxy acceptances tests should not be run in GovCloud since the feature is not currently supported there.

### New or Affected Resource(s)

* aws_db_proxy

### References

* #15174
* #15128

**Comment by bflad** [comment]
Similar? https://github.com/terraform-providers/terraform-provider-aws/issues/15141

**Comment by YakDriver** [comment]
@bflad Somehow @gdavison snuck in a duplicate before I submitted mine. 🤦
