### ISSUE TITLE
aws_apigatewayv2_authorizer is not sending required parameters for REQUEST authorizer

### ISSUE THREAD

**Issue by aleecevanderloop-disney** [terraform-providers/terraform-provider-aws#15181]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

0.13.2

### Affected Resource(s)

* aws_apigatewayv2_authorizer

### Terraform Configuration Files

```hcl
resource "aws_apigatewayv2_authorizer" "example" {
  api_id           = aws_apigatewayv2_api.example.id
  authorizer_type  = "REQUEST"
  authorizer_uri   = aws_lambda_function.lambda_function.invoke_arn
  identity_sources = ["$request.header.Auth"]
  name             = "example-authorizer"
}
```

### Debug Output

aws_apigatewayv2_authorizer.example: Creating...

Error: error creating API Gateway v2 authorizer: BadRequestException: AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer

### Expected Behavior

There is no option to pass in `authorizer-payload-format-version` and `enable-simple-responses` which are required by the amazon CLI to set up a REQUEST authorizer type.  

The documentation example is also incorrect - when passing in the identity source, something like `"$request.header.Auth"` should be passed in instead of the documented `"route.request.header.Auth"` example.  

### Actual Behavior

API Gateway error of `BadRequestException: AuthorizerPayloadFormatVersion is a required parameter for REQUEST authorizer` was returned.  

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment]
Hi @aleecevanderloop-disney, thank you for reporting this issue. Looking at the AWS [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html), it looks like creating an authorizer for lambda functions does indeed require the `authorizerPayloadFormatVersion` attribute in the API request, so to handle this in the provider, the resource will require the new attribute and need to be tested with an HTTP `aws_apigatewayv2_api` resource (currently our acceptance testing covers the case of HTTP APIs used with the `JWT` authorizer type, not `REQUEST`).

**Comment by aleecevanderloop-disney** [comment]
Thanks @anGie44 .  Could the `enable-simple-responses` value also be added to the resource as an optional attribute?  Without it, the authorizer will default to IAM policy and our team would like to be able to return simple responses.  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-authorizer.html#cfn-apigatewayv2-authorizer-enablesimpleresponses

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/15126
