### ISSUE TITLE
IOPs not ignored when volume_type != "io1" when instance read

### ISSUE THREAD

**Issue by fraenkel** [terraform-providers/terraform-provider-aws#1521]
### Terraform Version
v0.10.2

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
Here is the snippet that matters. The volume_type = "gp2" and volume_size = "50"
```hcl
...
root_block_device {
  ...
  volume_type = "${var.volume_type}"
  volume_size = "$(var.volume_size)"
  iops = "${var.volume_type == "io1" ? var.volume_iops : 100}"
}
```

### Debug Output
When I run terraform apply the second time, my instance is recreated because
```
root_block_device.0.iops:      "150" => "100" (forces new resource)
```
### Expected Behavior
No new resource should have been created.

### Actual Behavior
A new resource was created.

### Important Factoids
It seems that depending on the size of your gp2 disk, the iops changes. For smaller disks, the iops are set to 100. In my case, I am allocating 50Gbs which has an iops of 150.

Regardless, the bug seems to be an inconsistency when it comes to iops management. Given iops doesn't have any value when the type is not io1, we shouldn't be comparing the values at all.
The current test case is working because it matches the IOPs value that AWS provides. If one adjusts the value, the test case will fail.

**Comment by mrwacky42** [comment]
The plot thickens, because for `aws_launch_configuration`, if the volume type is gp2, the state shows `0` iops!

**Comment by fraenkel** [comment]
Yes, 0.9.6 did the "right" thing. It became a real issue once the switch to a provider happened. The code paths are different. I am working on a patch that is similar to how 0.9.6 handled it.
