### ISSUE TITLE
sso-admin api

### ISSUE THREAD

**Issue by dynnamitt** [terraform-providers/terraform-provider-aws#15219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for sso-admin api. https://docs.aws.amazon.com/cli/latest/reference/sso-admin/

I cannot find anywhere if this new api is planned for or supported already

### New or Affected Resource(s)

* aws_sso-admin_*

### References

go sdk page : https://docs.aws.amazon.com/sdk-for-go/api/service/ssoadmin/
awscli page : https://docs.aws.amazon.com/cli/latest/reference/sso-admin/index.html#cli-aws-sso-admin

**Comment by bflad** [comment]
Hi @dynnamitt 👋  Thank you for submitting this. Support for the SSO Admin APIs can be tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/15108. Please 👍  upvote and subscribe to that issue for further details.

**Comment by dynnamitt** [comment]
thanks
