### ISSUE TITLE
resource/aws_elasticsearch_domain: Support audit logging

### ISSUE THREAD

**Issue by reedloden** [terraform-providers/terraform-provider-aws#15217]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Elasticsearch Service now offers a detailed audit log of all Elasticsearch requests. Audit Logs allows customers to record a trail of all user actions, helping meet compliance regulations, improving the overall security posture and providing evidence for security investigations. 
>
> Amazon Elasticsearch Service Audit Logs allows customers to log all of their user activity on their Elasticsearch clusters, including keeping a history of user authentication success and failures, logging all requests to Elasticsearch, modifications to indices, recording incoming search queries and much more. Audit Logs provides a default configuration that covers a popular set of user actions to be tracked. Administrators can further configure and fine tune the settings to meet their needs. Audit Logs is integrated with Fine Grained Access Control, allowing you the ability to log access or modification requests to sensitive documents or fields, to meet any compliance requirements. Once configured, Audit Logs will be continuously streamed to CloudWatch Logs and can be further analyzed there. Audit Logs settings can be changed at any time and are automatically updated.

Requires aws/aws-sdk-go v1.34.26

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl
resource "aws_elasticsearch_domain" "example" {
  # .. other configuration ...

  log_publishing_options {
    cloudwatch_log_group_arn = aws_cloudwatch_log_group.example.arn
    log_type                 = "AUDIT_LOGS"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/09/audit-logs-launch/
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/audit-logs.htm

**Comment by reedloden** [comment]
Note this requires aws/aws-sdk-go v1.34.26 to actually work. https://github.com/terraform-providers/terraform-provider-aws/pull/15123

**Comment by anGie44** [comment]
Support for `AUDIT_LOGS` `log_type` has been added and will release with `v3.8.0` of the Terraform AWS Provider, likely out later today .
