### ISSUE TITLE
Error : Error: rpc error: code = Unavailable desc = transport is closing on aws_route53_record.ciao: Refreshing state.

### ISSUE THREAD

**Issue by bizmate** [terraform-providers/terraform-provider-aws#15216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Version
```
$ terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.7.0
+ provider registry.terraform.io/hetznercloud/hcloud v1.21.0
+ provider registry.terraform.io/rancher/rke v1.1.1

```

* aws_route53_record.rancher: Refreshing state

### Terraform Configuration Files

```hcl
resource "aws_route53_zone" "rancher" {
  name = "rancher.bizmate.space"
}

resource "aws_route53_record" "rancher" {
  zone_id = aws_route53_zone.rancher.zone_id
  name    = aws_route53_zone.rancher.name
  type    = "A"
  ttl     = "30"
  records = [ hcloud_server.proj-infra-k8s-servers[1].ipv4_address ]
}
```

### Debug Output

https://gist.github.com/bizmate/f1c700d4c27f3f87cd297702b2f38bfa

Shorter version below
```
$ terraform plan 
2020/09/18 03:14:23 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

hcloud_ssh_key.proj-infra-key: Refreshing state... [id=2076461]
hcloud_server.proj-infra-k8s-servers["1"]: Refreshing state... [id=7659097]
hcloud_server.proj-infra-k8s-servers["2"]: Refreshing state... [id=7659098]
hcloud_server.proj-infra-k8s-servers["3"]: Refreshing state... [id=7659099]
rke_cluster.proj_rke: Refreshing state... [id=5vbn849-7bc3-445e-94f4-f0126827c5e9]
2020/09/18 03:14:29 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/09/18 03:14:29 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
aws_route53_zone.rancher: Refreshing state... [id=Z00671vnvbDBWL9FQR]
aws_route53_record.rancher: Refreshing state... [id=Z006711vbnWL9FQR_rancher.user.space_A]

Error: rpc error: code = Unavailable desc = transport is closing

```

### Panic Output

omissis - i dont see a crash.log file

### Expected Behavior

terraform plan ends successful and displays possible actions as per functionality

### Actual Behavior

panic error even if i comment out the aws resource from the code

### Steps to Reproduce

terrform init
terraform plan

1. `terraform apply`

### Important Factoids

not sure
### References

none

**Comment by anGie44** [comment]
Hi @bizmate, thank you for creating this issue. Looking at the logs, its looks like the errors stem from the refresh of a resource that belongs to `terraform-provider-rke`.
```
rke_cluster.companys_rke: Refreshing state... [id=5380d849-7bc3-445e-94f4-f0126827c5e9]
2020-09-18T02:56:02.364+0100 [DEBUG] plugin.terraform-provider-rke_v1.1.1: 
2020-09-18T02:56:02.364+0100 [DEBUG] plugin.terraform-provider-rke_v1.1.1: goroutine 66 [running]:
2020-09-18T02:56:02.364+0100 [DEBUG] plugin.terraform-provider-rke_v1.1.1: github.com/rancher/terraform-provider-rke/rke.flattenRKEClusterNodes(0xc00011c000, 0x1, 0x4, 0xc000b7d2c0, 0x3, 0x3, 0x0, 0x0, 0xc000050310)
```
I would recommend opening a bug report w/in their provider repo @ https://github.com/rancher/terraform-provider-rke . Tracing back within that provider's code, looks like this PR introduced in `v1.1.1` made some changes that are linked to this panic report: https://github.com/rancher/terraform-provider-rke/pull/239.

**Comment by bizmate** [comment]
hi @anGie44 thank you for your reply, as terraform output was stopping at requests made toward AWS I though it was an AWS issue. I will need to be more careful reading logs next time.

**Comment by anGie44** [comment]
No worries @bizmate 👍 , glad to see there was a fix on their end!
