### ISSUE TITLE
Data source tls_certificate always changing on apply

### ISSUE THREAD

**Issue by iarlyy** [terraform-providers/terraform-provider-aws#15238]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
+ provider registry.terraform.io/-/aws v3.7.0
+ provider registry.terraform.io/-/tls v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.7.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0

### Affected Resource(s)

data source tls_certificate

### Terraform Configuration Files

```hcl
data "tls_certificate" "apps_cluster" {
  count = var.create ? 1 : 0
  url   = aws_eks_cluster.this[0].identity.0.oidc.0.issuer
}
```

### Expected Behavior

No code drift

### Actual Behavior

Code drift
```
      ~ id           = "2020-09-21 09:51:44.567075 +0000 UTC" -> "2020-09-21 09:51:48.400228 +0000 UTC"
```

### Steps to Reproduce

1. `terraform apply`

### References

* This problem seems to be very similar to what is happening to aws_kms_secrets (https://github.com/terraform-providers/terraform-provider-aws/issues/14564)

**Comment by gdavison** [comment]
Hi @iarlyy, the data source `tls_certificate ` is defined in the repository https://github.com/hashicorp/terraform-provider-tls. It looks like this issue has already been reported https://github.com/hashicorp/terraform-provider-tls/issues/79
