### ISSUE TITLE
Access Point not working correctly

### ISSUE THREAD

**Issue by MichaelLoveUSA** [terraform-providers/terraform-provider-aws#15248]
When following the terraform EFS/Access Point documentation (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_access_point), it says that there can be a posix_user and root_directory block that can be defined as part of the aws_efs_access_point resource. I am using AWS provider 2.7 (but I also tried the latest 3.7) and I am getting the following error:

Error: Unsupported argument

  on .terraform\modules\cirrusprint_server.efs\main.tf line 28, in resource "aws_efs_access_point" "root":
  28:   posix_user = {

An argument named "posix_user" is not expected here. Did you mean to define a
block of type "posix_user"?

It looks like there was some activity to address this, but I cannot tell if it was ever merged in. The documentation says it is available.

Here is my terraform:

```terraform
resource "aws_efs_access_point" "root" {
  file_system_id = "${aws_efs_file_system.cpaws.id}"
#  posix_uid = 51773
  posix_user = {
    gid = 52773
    uid = 51773
  }
#  root_directory = {
#    path = "/efs0"
#  }
  tags = {
    Name = "root"
  }
}
```

**Comment by gdavison** [comment]
Hi @MichaelLoveUSA 

This isn't the best error message from us, but what it's saying is that `posix_user` can't be assigned (`=`) a value, but can be defined as a block (`{ ... }`)

The following should work
```terraform
  posix_user {
    gid = 52773
    uid = 51773
  }
```
