### ISSUE TITLE
Support "AUDIT_LOGS" log_type for aws_elasticsearch_domain

### ISSUE THREAD

**Issue by epicfaace** [terraform-providers/terraform-provider-aws#15243]
This is now supported by https://godoc.org/github.com/aws/aws-sdk-go/service/elasticsearchservice.

**Comment by anGie44** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/15217

**Comment by anGie44** [comment]
Hi @epicfaace, this request is currently being tracked in https://github.com/terraform-providers/terraform-provider-aws/issues/15217 . I'm going to close this as a duplicate but thank you for creating the issue :)
