### ISSUE TITLE
r/kinesis_firehose_delivery_stream: documentation refers to incorrect value in description

### ISSUE THREAD

**Issue by StevenKGER** [terraform-providers/terraform-provider-aws#15251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Provider: 3.7.0

### Affected Resource(s)

* documentation of aws_kinesis_firehose_delivery_stream

### Incorrect value
https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/kinesis_firehose_delivery_stream.html.markdown#L360 (link maybe does not work due to markdown rendering)

![image](https://user-images.githubusercontent.com/22663042/93811435-6f1d5d00-fc50-11ea-9732-c13f5be43f18.png)

The marked reference in line 360 should be named `key_type` since it is named like it in line 359 and in the provider as well. (in `server_side_encryption` section)

**Comment by daisakuhazui** [comment]
I'd like to contribute to this, is there any concensus on the best way to handle this?

**Comment by angelabad** [comment]
Ops, sorry @daisakuhazui I didn't see your comment :-(
