### ISSUE TITLE
Cloudfront ignore_changes for specific nested arguments

### ISSUE THREAD

**Issue by mper0003** [terraform-providers/terraform-provider-aws#15264]
We are using custom headers to increase security in the communication between cloudfront and origin, as recommended by [aws](https://aws.amazon.com/about-aws/whats-new/2016/01/amazon-cloudfront-adds-new-origin-security-features/). The custom header is modified by a process outside of Terraform, so we need to add `ignore_changes` to `custom_headers`.  

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.2
provider registry.terraform.io/hashicorp/aws v3.7.0
### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

```hcl
resource "aws_cloudfront_distribution" "distribution" {
  origin {
    domain_name = var.default_origin_domain
    origin_id   = local.origin_id

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
    custom_header {
      name  = local.custom_header_name
      value = "replace-me"
    }
  }

  tags = local.common_tags

  enabled         = true
  is_ipv6_enabled = true
  comment         = local.name_prefix

  lifecycle {
    prevent_destroy = false
    ignore_changes  = [origin.0.custom_header]
  }

  logging_config {
    bucket = aws_s3_bucket.distribution_logs.bucket_domain_name
    prefix = local.name_prefix
  }

  aliases = formatlist("%s.${var.edge_domain}", var.edge_aliases)

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = local.origin_id
    compress         = true

    forwarded_values {
      query_string = true
      headers      = ["*"]

      cookies {
        forward = "all"
      }
    }

    viewer_protocol_policy = "https-only"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400

    lambda_function_association {
      event_type = "origin-request"
      lambda_arn = aws_lambda_function.edge_lambda.qualified_arn
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    acm_certificate_arn      = aws_acm_certificate.distribution.arn
    minimum_protocol_version = "TLSv1"
    ssl_support_method       = "sni-only"
  }
}

```

### Output

```
Error: Cannot index a set value

  on cloudfront.tf line 31, in resource "aws_cloudfront_distribution" "distribution":
  31:     ignore_changes  = [origin.0.custom_header]

Block type "origin" is represented by a set of objects, and set elements do
not have addressable keys. To find elements matching specific criteria, use a
"for" expression with an "if" clause.
```
### Expected Behavior

Custom header should have been ignored and terraform plan succeeded.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

1. We have tried variations of lifecycle `ignored_changes` described in the reference below, but none have worked.
2. We can't use `lifecycle {ignore_changes  = [origin]}` because we still need to modify other properties of the origin (i.e. `custom_origin_config`). 

### References

* #3819
* #15260

**Comment by gdavison** [comment]
Hi @mper0003. Unfortunately, this is a limitation of [Terraform itself](https://github.com/hashicorp/terraform), not the AWS provider. There isn't currently a way to index into a set, which is how the `origin` field is implemented. A [similar issue](https://github.com/hashicorp/terraform/issues/25524) was reported, but the [feedback](https://github.com/hashicorp/terraform/issues/25524#issuecomment-657811017) was that `ignore_changes` is not supported for set elements.

You've mentioned that you can't ignore `origin`, which would have been my suggestion. Is there a way that you can somehow insert the values from your external process into your Terraform configuration, either using input variables or an [external script using a `null_resource` and a `provisioner`](https://www.terraform.io/docs/provisioners/null_resource.html)?

You may also be able to find some suggestions in our forums at https://discuss.hashicorp.com/c/terraform-providers/tf-aws.

To encourage support for the feature, you might be able to add feedback on the issue mentioned above or create your own issue on the Terraform project.

**Comment by mper0003** [comment]
Thanks @gdavison for the response and suggestions. Ideally, we would want the custom header to be ignored by Terraform since we would use it to hold a secret. I will raise an issue in Terraform. Thanks!
