### ISSUE TITLE
aws_efs_mount_target takes longer than 10 minutes to deploy

### ISSUE THREAD

**Issue by jrobison-sb** [terraform-providers/terraform-provider-aws#15278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform version
Terraform v0.12.28
+ provider.aws v3.3.0
```

### Affected Resource(s)

* aws_efs_mount_target

### Terraform Configuration Files

```
resource "aws_efs_mount_target" "alpha" {
  file_system_id = aws_efs_file_system.foo.id
  subnet_id      = aws_subnet.alpha.id
}
```

### Expected Behavior

The mount target is created without any error in the `apply`.

### Actual Behavior

Sometimes, but not always, a mount target will take longer than [10 minutes](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_efs_mount_target.go#L151) to reach the `available` state. When that happens, the resource creation will timeout and the `apply` will fail.

### Steps to Reproduce

It's sporadic so it can't be reproduced on-demand, but when it happens the only step is just `terraform apply` while creating an `aws_efs_mount_target`.

**Comment by anGie44** [comment]
A fix to increase the create timeout has been merged and will release with `v3.8.0` of the Terraform AWS Provider, likely out later today.
