### ISSUE TITLE
Provider doesn't support resource: aws_db_proxy

### ISSUE THREAD

**Issue by javabrown** [terraform-providers/terraform-provider-aws#15294]
Trying to create aws_db_proxy. But getting error: `Error: aws_db_proxy.mydbproxy: Provider doesn't support resource: aws_db_proxy`

Following is my TF source code:
```
resource "aws_db_proxy" "mydbproxy" {
  name                   = "mydbproxy"
  debug_logging          = false
  engine_family          = "MYSQL"
  idle_client_timeout    = 1800
  require_tls            = true
  role_arn               = "${data.aws_iam_role.myrdsrole.arn}"
  vpc_security_group_ids = ["${data.aws_security_group.default.id}"]
  vpc_subnet_ids         = ["${data.aws_subnet.default.id}"]

  auth {
    auth_scheme = "SECRETS"
    description = "example"
    iam_auth    = "DISABLED"
    secret_arn  = ""
    username    = "example"
  }

  tags = {
    Name = "example"
    Key  = "value"
  }
}

resource "aws_db_proxy_default_target_group" "mydbproxytargetgroup" {
  connection_pool_config {
    connection_borrow_timeout    = 120
    init_query                   = "SET x=1, y=2"
    max_connections_percent      = 100
    max_idle_connections_percent = 50
    session_pinning_filters      = ["SELECT"]
  }

  db_proxy_name     = "${aws_db_proxy.mydbproxy.name}"
}
```

**Comment by gdavison** [comment]
Hi @javabrown, `aws_db_proxy` was added to the AWS provider in v3.5, released 3 September 2020. Can you run `terraform -v` to show the version of Terraform and the AWS provider you're using?

**Comment by javabrown** [comment]
Terraform v0.12.29

**Comment by gdavison** [comment]
Unfortunately, no. The AWS provider v3 needs Terraform 0.12 or higher.

We have guides for[ upgrading to 0.12](https://www.terraform.io/upgrade-guides/0-12.html) and [upgrading to 0.13](https://www.terraform.io/upgrade-guides/0-13.html) which give guidance on the changes.

Terraform 0.11.14 includes the command `terraform 0.12checklist` which will analyze your configuration and find anything that needs to change before using 0.12.

Terraform 0.12 also includes the command `terraform 0.12upgrade` which can update your configuration to use 0.12 syntax.

I'm going to close this issue. If you need more information on the upgrade process, our forums at https://discuss.hashicorp.com/c/terraform-providers/tf-aws are a great place to check out.
