### ISSUE TITLE
aws doesn't support two policies to be applied on the same efs file system - so aws provider shouldn't either

### ISSUE THREAD

**Issue by pviet-cohere** [terraform-providers/terraform-provider-aws#15318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_efs_file_system_policy

### Terraform Configuration Files

```hcl
resource "aws_efs_file_system" "fs" {
  creation_token = "fs"
}

resource "aws_efs_file_system_policy" "policy1" {
  file_system_id = aws_efs_file_system.fs.id
  policy = something
}

resource "aws_efs_file_system_policy" "policy2" {
  file_system_id = aws_efs_file_system.fs.id
  policy = something
}

```

### Expected Behavior

An error that doesn't allow two policies to be attributed to the same file system

### Actual Behavior

Applies first policy then overrides it with the second policy

### Steps to Reproduce

Make two policies that apply to the same filesystem in terraform

**Comment by gdavison** [comment]
Thanks for raising this issue, @pviet-cohere. Terraform doesn't track settings across resources in that way. To prevent this circumstance from occurring, you will need to specify the `aws_efs_file_system_policy` resource only once.

**Comment by gdavison** [comment]
Here's some more context on the design decision behind making this a separate resource: https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#adding-resource-policy-support.

There is some work on foundational work that would need to be done before the AWS Provider could implement this: https://github.com/hashicorp/terraform/issues/22094 and https://github.com/hashicorp/terraform-plugin-sdk/issues/224
