### ISSUE TITLE
running_mode_auto_stop_timeout_in_minutes argument documented as optional but is required

### ISSUE THREAD

**Issue by mschuchard** [terraform-providers/terraform-provider-aws#15314]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.12.29
AWS 2.70.0

### Affected Resource(s)

* aws_workspace

### Terraform Configuration Files

```terraform
resource "aws_workspaces_workspace" "example" {
  ...

  workspace_properties {
    ... # not containing running_mode_auto_stop_timeout_in_minutes argument
  }
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

[Documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace#running_mode_auto_stop_timeout_in_minutes) claiming argument is optional is correct.

### Actual Behavior

Not specifying `workspace_properties[0].running_mode_auto_stop_timeout_in_minutes` argument throws error on CREATE to API during apply of:

> Error: workspace creation failed: RunningModeAutoStopTimeoutInMinutes is not within permissible range

Resolved by specifying argument in resource config indicating it is actually required.

Please update documentation to indicate argument is required OR adapt the provider to compensate for the API being unable to allocate a reasonable default value here.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

n/a

### References

n/a

**Comment by gdavison** [comment]
Hi @mschuchard, thanks raising this. Can you provide more of your Terraform configuration and more of the error output to help evaluate this?

We have several acceptance test cases which don't specify `running_mode_auto_stop_timeout_in_minutes`, and [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-workspaces-workspace-workspaceproperties.html#aws-properties-workspaces-workspace-workspaceproperties-properties) says that the parameter is optional.

**Comment by Tensho** [comment]
Unfortunatly, couldn't reproduce this bug with the [`testAccWorkspacesWorkspaceConfig_WorkspacePropertiesB` configuration](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_workspaces_workspace_test.go#L443):
```
resource "aws_workspaces_workspace" "test" {
  bundle_id    = data.aws_workspaces_bundle.test.id
  directory_id = aws_workspaces_directory.test.id

  # NOTE: WorkSpaces API doesn't allow creating users in the directory.
  # However, "Administrator"" user is always present in a bare directory.
  user_name = "Administrator"

  workspace_properties {
    # NOTE: Compute type and volume size update not allowed within 6 hours after creation.
    running_mode = "ALWAYS_ON"
  }

  tags = {
    TerraformProviderAwsTest = true
  }
}
```

**Comment by mschuchard** [comment]
Ok, I can assume this is a bug with the AWS API itself, and not the AWS provider. I will continue to circumvent the bug with the API by specifying a value for the `workspace_properties[0].running_mode_auto_stop_timeout_in_minutes` argument until it is fixed.
Thanks for the information.

**Comment by Tensho** [comment]
@mschuchard Thank you for the feedback 🙇
