### ISSUE TITLE
AWS Backup support for VSS snapshots

### ISSUE THREAD

**Issue by gazoakley** [terraform-providers/terraform-provider-aws#15329]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Backup now supports application-consistent backups of Microsoft workloads running on EC2, via Microsoft’s Volume Shadow Copy Services (VSS). Customers can create, manage, and restore consistent backups of their Microsoft Windows Server instances and Microsoft applications (including SQL Server, Active Directory and Exchange Server) directly from the AWS Backup console. 

### New or Affected Resource(s)

* aws_backup_plan

### Potential Terraform Configuration

```hcl
resource "aws_backup_plan" "example" {
  name = "tf_example_backup_plan"

  advanced_backup_setting {
    backup_options = {
      WindowsVSS = "enabled"
    }
    resource_type = "EC2"
  }

  rule {
    rule_name         = "tf_example_backup_rule"
    target_vault_name = aws_backup_vault.test.name
    schedule          = "cron(0 12 * * ? *)"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/09/aws-backup-supports-application-consistent-backups-of-microsoft-workloads-on-ec2/
* https://docs.aws.amazon.com/aws-backup/latest/devguide/API_BackupPlanInput.html#Backup-Type-BackupPlanInput-AdvancedBackupSettings

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.34.30](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.30):

* https://github.com/terraform-providers/terraform-provider-aws/pull/15226
