### ISSUE TITLE
TagSpecifications not being used in resource_aws_ebs_volume

### ISSUE THREAD

**Issue by sbrinkmeyer** [terraform-providers/terraform-provider-aws#1533]
i have a use case of  iam policies that restrict volume creation and usage by a shared tenant account at aws

aws has released tagspecifications for instances and volumes in march of 2017.  part of this is the aws:requesttag and the ec2:resourcetag.

due to the implementation of the aws_ebs_volume.  if i have a restricted policy using the condition of aws:requesttag/Name, terraform will fail to create the volume as the api first creates the volume then applies the tags.  

### Expected Behavior
terraform resource creation of a volume, if tags for volume are passed in should be sent as part of the tagspecification so that aws:requesttags are configured

### Actual Behavior
the current code first creates the volume.  Upon successful creation of the volume, tags are subsequently applied

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a policy that limits assumed role create volume with a condition of "aws:RequestTag/Name" to a known value
2. create simple terraform file that creates a volume resource with requested tags one of which being Name set to known value
3. assume the aws role
4. terraform apply
5.  terraform run will fail

### References
can not find any open github issues.
here is the code block i'm referencing
- https://github.com/terraform-providers/terraform-provider-aws/blob/48fdbc0997746c9c226d36bf358d8884b176c0da/aws/resource_aws_ebs_volume.go#L75-L89
which is already using some of the updated go api 
- https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateVolumeInput.SetTagSpecifications

**Comment by Dogers** [comment]
Just to chime in!
This is exactly what we're hitting now - our policies require certain tags to be in place on creation or the request is rejected. For the time being we're creating the volumes manually and running a `terraform import` on them.

**Comment by bflad** [comment]
In version 1.44.0 of the AWS provider releasing later this week, the tagging has been switched from a call after the creation to a parameter during creation which should resolve this situation. 👍

**Comment by bflad** [comment]
This has been released in [version 1.44.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1440-november-14-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by antonakv** [comment]
There is a new bug after the fix. Tag appears twice in AWS API call. As tag and Tag! As a result "InvalidRequest". Well done.
