### ISSUE TITLE
Further increase ClientVpnAuthorizationRuleRevokedTimeout

### ISSUE THREAD

**Issue by Fuuzetsu** [terraform-providers/terraform-provider-aws#15349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.13.3
+ provider registry.terraform.io/carlpett/sops v0.5.2
+ provider registry.terraform.io/hashicorp/aws v3.6.0
```

### Affected Resource(s)

* aws_ec2_client_vpn_authorization_rule

### Terraform Configuration Files

See https://github.com/terraform-providers/terraform-provider-aws/issues/14156

This time, I'm running `terraform destroy` on my infra.

### Debug Output

```
Error: error revoking Client VPN authorization rule "cvpn-endpoint-089e6f16ac7d35398,10.1.0.0/16": timeout while waiting for resource to be gone (last state: 'revoking', timeout: 5m0s)
```

### Expected Behavior

Revocation completes and resource is destroyed.

### Actual Behavior

Revocation times out.

### Steps to Reproduce

This is just the same as https://github.com/terraform-providers/terraform-provider-aws/issues/14156 but needs a higher timeout still.

See https://github.com/terraform-providers/terraform-provider-aws/issues/14156 but this time destroy.

### Important Factoids

I'm in ap-northeast-1.

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/14156

**Comment by bflad** [comment]
This increase has been merged and will release with version 3.9.0 of the Terraform AWS Provider, likely later today. Thanks to @philnichol for the implementation. 👍
