### ISSUE TITLE
Specify VPC in neptune instance

### ISSUE THREAD

**Issue by rjay98** [terraform-providers/terraform-provider-aws#15343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would love to specify the `vpc` when spinning up a neptune cluster. Seems like the current instance only gets created under the default vpc.

### New or Affected Resource(s)

* aws_neptune_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_neptune_cluster" "default" {
  cluster_identifier                  = "neptune-cluster-demo"
  engine                              = "neptune"
  backup_retention_period             = 5
  preferred_backup_window             = "07:00-09:00"
  skip_final_snapshot                 = true
  iam_database_authentication_enabled = true
  apply_immediately                   = true
  vpc_id = ${var.aws_vpc_id}
}
```

### References

* #0000

**Comment by gdavison** [comment]
Thanks for raising this @rjay98.

It's not clear from the documentation, but the way to assign a Neptune cluster (and similarly for any other AWS database) to a VPC is to create an `aws_neptune_subnet_group` which references subnets from the VPC and then assign the subnet group to the Neptune cluster.

I'm going to close this issue, but I've created #15344 to fix our documentation.
