### ISSUE TITLE
Tech Debt: WAFv2 Regex Pattern Set AccTest Consistently failing due to resource limit

### ISSUE THREAD

**Issue by anGie44** [terraform-providers/terraform-provider-aws#15358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource Test(s)

* aws_wafv2_regex_pattern_set

### Test Output

```
TestAccAwsWafv2RegexPatternSet_Tags: resource_aws_wafv2_regex_pattern_set_test.go:164: Step 1/4 error: terraform failed: exit status 1
        
        stderr:
        
        Error: Error creating WAFv2 RegexPatternSet: WAFLimitsExceededException: AWS WAF couldn’t perform the operation because you exceeded your resource limit.
        
        
--- FAIL: TestAccAwsWafv2RegexPatternSet_Tags (16.47s)
```

### Important Factoids

* Max Number of regex sets per account per Region: 10
### References

* https://docs.aws.amazon.com/waf/latest/developerguide/limits.html

**Comment by philnichol** [comment]
Might be missing something but looks like there are less than 10 regex sets being created by this test.

Looking at the AWS doc linked in the issue, could the resource quota being hit be this one instead (maybe due to parallel test)?

Call type | Quota per account per Region
-- | --
Maximum number of calls to any individual Create, Put, or Update action, if no other quota is defined for it | One request per second

**Comment by anGie44** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/15857 and closed by #15860

**Comment by bflad** [comment]
Oh sorry I missed this 😅

**Comment by anGie44** [comment]
np @bflad ! thanks for the sweeper fix 💪
