### ISSUE TITLE
eks node group launch_template not working

### ISSUE THREAD

**Issue by farooqdevops** [terraform-providers/terraform-provider-aws#15353]
### Community Note
I am trying to use launch_template block with eks_node_group but getting  "Error:  Unsupported block type".

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.3
aws provider: 3.8.0

```
resource "aws_eks_node_group" "default_workers" {
  cluster_name    = aws_eks_cluster.default.name
  node_group_name = "${var.cluster_name}-default"
  node_role_arn   = aws_iam_role.worker_role.arn
  subnet_ids      = var.vpc_private_subnets
  instance_types  = [var.default_workers_instance_type]

  scaling_config {
    desired_size = var.desired_workers_count
    max_size     = var.max_workers_count
    min_size     = var.min_workers_count
  }

  launch_template {
    id      = aws_launch_template.default.id
    version = aws_launch_template.latest_version
  }
}
```

### Debug Output

Error: Unsupported block type

   in resource "aws_eks_node_group" "default_workers":
  14:   launch_template {

Blocks of type "launch_template" are not expected here.

Makefile:69: recipe for target 'plan' failed
make: *** [plan] Error 1

**Comment by gdavison** [comment]
Hi @farooqdevops, can you provide the full output of the `terraform version` command, please? I was able to create an EKS node group with a launch template.

**Comment by farooqdevops** [comment]
@gdavison  yes its same as already mentioned above:

`farooq@farooq-XPS-13-9370:~/github/SE-aws-infra$ terraform --version
Terraform v0.13.3`

**Comment by gdavison** [comment]
When you run `terraform version` does the output include the version of the AWS Provider? There should be several lines output from that command.

**Comment by farooqdevops** [comment]
@gdavison no terraform version command gives only one line output showing terraform version and doesn't show long output.

**Comment by gdavison** [comment]
Ah, you will have to run `terraform version` from the same directory as an initialized Terraform configuration. Then it will output the versions of all the providers included as well as their registry information.

**Comment by farooqdevops** [comment]
@gdavison i get this output when i run terraform version in same directory as initialized terraform configuration
`$ terraform version
Terraform v0.13.3
+ provider registry.terraform.io/-/archive v1.3.0
+ provider registry.terraform.io/-/aws v3.8.0
+ provider registry.terraform.io/-/external v1.2.0
+ provider registry.terraform.io/-/helm v1.3.1
+ provider registry.terraform.io/-/kubernetes v1.13.2
+ provider registry.terraform.io/-/null v2.1.2
+ provider registry.terraform.io/-/random v2.3.0
+ provider registry.terraform.io/-/template v2.1.2
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/helm v1.2.4
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.1.2`

**Comment by gdavison** [comment]
There's something weird going on with your setup. Your configuration is using both `provider registry.terraform.io/-/aws v3.8.0` and `provider registry.terraform.io/hashicorp/aws v2.70.0`. You may need to re-run `terraform init` and possibly use the `-upgrade` flag.

If that doesn't help, please open an issue with Terraform Core, since the tool itself manages provider versions and downloading.

**Comment by night-gold** [comment]
Hello @gdavison  ,

I've got the exact same issue with template and your answer seems to be the solution... I just want to give some precision on the error as I've seen something strange when I do terraform init. It's actually loading the aws provider 2 times. And I had a version issue with it, it was loading the 3.90 first and then the 2.x version and that seemed to overwrite the previous one, you get something like that:

```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of -/aws...
- Finding latest version of hashicorp/template...
- Finding latest version of hashicorp/aws...
- Installing -/aws v3.9.0...
- Installed -/aws v3.9.0 (signed by HashiCorp)
- Installing hashicorp/template v2.1.2...
- Installed hashicorp/template v2.1.2 (signed by HashiCorp)
- Installing hashicorp/aws v3.9.0...
- Installed hashicorp/aws v3.9.0 (signed by HashiCorp)

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* -/aws: version = "~> 3.9.0"
* hashicorp/aws: version = "~> 3.9.0"
* hashicorp/template: version = "~> 2.1.2"
```

I'm using terraform 0.13.2 and that is the terraform and provider conf, I updated the provider conf to have the same one as the terraform one and commenting the provider resource does not remove the 2 loading of the provider:

```
terraform {
  required_version = ">= 0.13.2, <= 0.14"
  backend "s3" {
    key = "21-eks/default.tfstate"
  }
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  version = "~> 3.0"
  region  = var.aws_region
}
```
