### ISSUE TITLE
Feature - EFS encryption data at rest now available

### ISSUE THREAD

**Issue by dcloud9** [terraform-providers/terraform-provider-aws#1536]
http://docs.aws.amazon.com/efs/latest/ug/encryption.html - Anyone fancy refactoring EFS to add encryption at rest. Happy to peer review.

**Comment by Ninir** [comment]
Hi @dcloud9 

https://github.com/terraform-providers/terraform-provider-aws/pull/1420 added the encryption plus the KMS stuff for that.
Is it what you are missing?

Thanks!

**Comment by dcloud9** [comment]
@Ninir, yes you're a 🌟. Thanks for the quick action on this feature. Hope it gets added on the next release.

**Comment by zerolaser** [comment]
@Ninir any update on when this efs encryption is going to be added on the release ?

**Comment by Ninir** [comment]
Hi @zerolaser 

This was added in 1.0.0, which was released on September 27, 2017.

If you are using Terraform 0.10.X, you may need to run: `terraform init -upgrade`

Tell us how it goes, Happy Terraforming!
