### ISSUE TITLE
aws_vpc - save the name of the vpc

### ISSUE THREAD

**Issue by uncodable** [terraform-providers/terraform-provider-aws#15368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the name to a VPC
![image](https://user-images.githubusercontent.com/32820112/94351186-3a454780-004e-11eb-8b14-5bc7a76a20d2.png)
Not supported currently from the docs (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc)

### New or Affected Resource(s)

* aws_vpc

### Potential Terraform Configuration

```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  name = "foobar"
}
```

At the min I've just been adding tags, but this seems an option to actually define the VPC name.

**Comment by dthvt** [comment]
Hi @uncodable - if you look at the AWS API for CreateVpc (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpc.html) you'll see that VPCs don't actually have names.  In practice, the Name column on the AWS console website is populated from the Name tag.  So all you need to do on your example code is capitalize `Name` in your tags in order for the console to display it automatically.

Cheers!

**Comment by uncodable** [comment]
@dthvt hey, thanks for that I was aware about naming them just wasn't 100% if it was a tag etc. But I will update that now on my end. Thanks again!
