### ISSUE TITLE
Terraform apply fails to configure AWS provider with shared credential file

### ISSUE THREAD

**Issue by DylanSp** [terraform-providers/terraform-provider-aws#15361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

`terraform apply` is failing to discover AWS credentials in ~/.aws/credentials.

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.8.0

### Affected Resource(s)

* aws_s3

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.8"
    }
  }
}

provider "aws" {
  profile = "idxdev"
  region  = "us-east-1"
}

resource "aws_s3_bucket" "example_bucket" {
  bucket = "example-tf-bucket"
}
```

### Debug Output

[`TF_LOG=trace terraform apply` output](https://gist.github.com/DylanSp/db977366e145532aff1f66563cb8778a).

### Expected Behavior

Terraform creates and shows an execution plan.

### Actual Behavior

`terraform apply` fails with "error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found".

### Steps to Reproduce

1. Create a new directory.
2. Put the configuration file above into `example.tf`.
3. `terraform init`
4. `terraform apply`

### References

Possible related issue: #12815

**Comment by dthvt** [comment]
I can't replicate this on terraform 0.13.1 w/ AWS v3.8.0.  Does it work for you on an earlier 0.13 version?

**Comment by DylanSp** [comment]
Just tried with version 0.13.1, same error.

**Comment by dthvt** [comment]
If you do `aws --profile idxdev ec2 describe-vpcs` from the directory, does it work correctly?

**Comment by gdavison** [comment]
Hi @DylanSp. Thank you for including the debug output. It looks like you're running Terraform on Windows. Is your AWS credentials file located at `%USERPROFILE%\.aws\credentials`? (Linux and macOS would be `$HOME/.aws/credentials`) If your shared credentials file is elsewhere, you'll also need to specify `shared_credentials_file`.

Also double-check that the profile is configured correctly in the shared credentials file. If the profile is not found in the file, it will display the same error.

**Comment by DylanSp** [comment]
@gdavison Explicitly specifying `shared_credentials_file` did the trick, thanks! I'm running on Windows, but using Git Bash; my shell was resolving ~/.aws/credentials to the correct directory, but Terraform apparently wasn't finding them without explicitly specifying the path.
