### ISSUE TITLE
Support adding CIDRs to existing VPC

### ISSUE THREAD

**Issue by atsushi-ishibashi** [terraform-providers/terraform-provider-aws#1537]
AWS release documentation is below.
https://aws.amazon.com/jp/about-aws/whats-new/2017/08/amazon-virtual-private-cloud-vpc-now-allows-customers-to-expand-their-existing-vpcs/

I'm looking for api documentation...

**Comment by bentterp** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateVpcCidrBlock.html

**Comment by atsushi-ishibashi** [comment]
Thank you!
I'll send PR👍

**Comment by sfrode** [comment]
@atsushi-ishibashi any progress?

**Comment by atsushi-ishibashi** [comment]
PR was already sent...
Btw, this feature will be merged👍
https://github.com/terraform-providers/terraform-provider-aws/pull/1568

I'll close this issue in order not to confuse anyone.
