### ISSUE TITLE
Creating/modifying multiple SQS queues with the same name doesn't fail

### ISSUE THREAD

**Issue by tonnydourado** [terraform-providers/terraform-provider-aws#15429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.28
+ provider.aws v3.8.0
```

### Affected Resource(s)

- `aws_sqs_queue`

### Terraform Configuration Files

```hcl
provider "aws" {
  region     = "eu-west-1"
}

// This will result in a single queue being created, and upon re-applying, 
// the visibility_timeout_seconds will change depending on which resource
// gets applied last:
resource "aws_sqs_queue" "first_queue" {
  name                       = "my-test-queue"
  visibility_timeout_seconds = 4 * 60
}

resource "aws_sqs_queue" "second_queue" {
  name                       = "my-test-queue"
  visibility_timeout_seconds = 5 * 60
}

// This, on the other hand, will always fail:
// resource "aws_s3_bucket" "b1" {
//   bucket = "test-bucket-for-testing-duplication"
//   acl    = "private"
// }

// resource "aws_s3_bucket" "b2" {
//   bucket = "test-bucket-for-testing-duplication"
//   acl    = "private"
// }
```

### Expected Behavior

One of the `aws_sqs_queue` resources should fail to apply.

### Actual Behavior

Both `aws_sqs_queue` resources are applied, only one queue is created, and if you have different attributes in the `aws_sqs_queue` resources, the actual queue changea non-deterministically, depending on which resource is applied last

### Steps to Reproduce

Applying the terraform code above always reproduces the issue

### Important Factoids

The [API documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html) for SQS says that passing the same parameters of an **existing** queue to `CreateQueue` will just return the existing queue, but in this case even changing other parameters, but not the name, only a single queue gets created.

**Comment by bflad** [comment]
Hi @tonnydourado 👋  Thank you for submitting this and sorry you ran into trouble here. Please note that this is unexpected behavior in Terraform resources and that this has been previously reported in #10824. To consolidate efforts and discussions, I'm going to close this issue in preference of the existing one. Please 👍  react and subscribe there for further updates.
