### ISSUE TITLE
web_acl_id property on the cloudfront_distribution incorrect using WAFv2

### ISSUE THREAD

**Issue by uncodable** [terraform-providers/terraform-provider-aws#15472]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* cloudfront_distribution

### Expected Behavior

Pass the ID instead of the ARN as the documentation says so (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#web_acl_id)

### Actual Behavior

When using `cloudfront_distribution` and want to assign a **WAFv2** to the distribution you use `web_acl_id` this in fact for WAFv2 isn't the ID and needs to be the ARN to be assigned to work. I found this by using a id from `aws_wafv2_web_acl.test.id` but works by doing `aws_wafv2_web_acl.test.arn` instead

**Comment by philnichol** [comment]
@uncodable appears in the aws sdk they've moved from ID to ARN when using WAFv2:

From the [AWS sdk docs](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/#DistributionConfig)
```
    // A unique identifier that specifies the AWS WAF web ACL, if any, to associate
    // with this distribution. To specify a web ACL created using the latest version
    // of AWS WAF, use the ACL ARN, for example arn:aws:wafv2:us-east-1:123456789012:global/webacl/ExampleWebACL/473e64fd-f30b-4765-81a0-62ad96dd167a.
    // To specify a web ACL created using AWS WAF Classic, use the ACL ID, for example
    // 473e64fd-f30b-4765-81a0-62ad96dd167a.
```

In the docs you linked it does mention that for WAFv2 you have to use ARN, but I get that the name is a bit misleading

**Comment by uncodable** [comment]
@philnichol yeh the `_id` is what throws it off, cheers for the reference.

**Comment by bflad** [comment]
If anyone would like to further clarify this argument's documentation, the source lives in `website/docs/r/cloudfront_distribution.html.markdown`

**Comment by philnichol** [comment]
@bflad Good point, I've raised #15511 that hopefully makes this a bit more clear.
@uncodable wasn't sure how to add you as a reviewer, but let me know if that's clearer or if it's still lacking on anything?
