### ISSUE TITLE
aws_s3_buckets datasource

### ISSUE THREAD

**Issue by ThinkBriK** [terraform-providers/terraform-provider-aws#15545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have a missing datasource form AWS S3 buckets : you cannot get a list of your account buckets via terraform at the moment.
The only existing datasource is _aws_s3_bucket_ and it does only support a single bucket by name.

We would need a filter to retrieve Buckets ARNs and Names list, especially usefull to harden S3 VPC endpoints and prevent data exfiltration (using a policy for our account bucket only for example).

### New or Affected Resource(s)

* data aws_s3_buckets

### Potential Terraform Configuration

```hcl
data aws_s3_buckets "supersecret_project_bucket" {
  filter {
    name   = "tag:Project"
    values = ["supersecret"]
  } 
  account = 111111111111
}

data "aws_iam_policy_document" "s3_restrict_to_account_buckets" {
  statement {
    sid = "S3RestrictWriteToSupersecretProjectBuckets"
    principals {
      identifiers = ["*"]
      type        = "*"
    }
    actions = [
      "s3:PutObject",
    ]
    effect    = "Allow"
    resources = formatlist("%s/*", data.aws_s3_buckets.arns)
  }
}

resource "aws_vpc_endpoint" "s3-gateway" {
  service_name = "com.amazonaws.${data.aws_region.current.name}.s3"
  vpc_id       = aws_vpc.vpc.id
  policy = data.awsaws_iam_policy_document.s3_restrict_to_account_buckets.json
}
```
* #0000

**Comment by ThinkBriK** [comment]
I guess the service label should be service/s3 :)

**Comment by anGie44** [comment]
Hi @ThinkBriK, thank you for creating this issue though it seems to be a duplicate of #15544. Is there any additional info regarding this data source not captured in the other issue?

**Comment by ThinkBriK** [comment]
Hi @anGie44,
It's a connection problem on my side that pushed me to create a duplicate issue, apologies, I close !!
Keep up the great job :+1:
