### ISSUE TITLE
Add support for "logConfiguration" in Batch "job-definition" 

### ISSUE THREAD

**Issue by shlomi-viz** [terraform-providers/terraform-provider-aws#15560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Allow to set `logConfiguration` section in Batch job definition.

### New or Affected Resource(s)

* aws_batch_job_definition

### Potential Terraform Configuration

```hcl
resource "aws_batch_job_definition" "job_definition" {
  name = "${var.job_definition_name}"
  type = "container"

  container_properties = "${data.template_file.job_definition.rendered}"

  timeout = {
    attempt_duration_seconds = "${var.attempt_duration_seconds}"
  }

  retry_strategy = {
    attempts = 2
  }

  log_configuration": {
    log_driver: "awslogs"
    "options": {
       "awslogs-region": "${var.region}", 
       "awslogs-group": "${var.group_name}",
    },
  }
}
```

### References

* https://aws.amazon.com/blogs/compute/custom-logging-with-aws-batch/
* https://docs.aws.amazon.com/cli/latest/reference/batch/register-job-definition.html

**Comment by philnichol** [comment]
To match the API I guess this could go within container_properties eg:
```
resource "aws_batch_job_definition" "test" {
  name = "tf_test_batch_job_definition"
  type = "container"

  container_properties = <<CONTAINER_PROPERTIES
{
    "command": ["ls", "-la"],
    "image": "busybox",
    "memory": 1024,
    "vcpus": 1,
    "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
            "awslogs-group": "example"
        }
    }
}
CONTAINER_PROPERTIES
}
```
Looks like because logConfiguration has to be flattened into it's own struct that doesn't currently work.
I'd like to have a go at it if that's alright?

**Comment by bflad** [comment]
Hi folks 👋  For clarity here, this is one of the places in the Terraform AWS Provider where it will automatically start working with AWS Go SDK updates we perform each week. If something is not working on version 3.10.0 or later of the Terraform AWS Provider, please reach out. 👍

**Comment by shlomi-viz** [comment]
Thanks @bflad, Is there any way to use it with version 2.7 and TF 0.11?

**Comment by bflad** [comment]
@shlomi-viz not in an officially supported release, please see the [backport policy in our FAQ](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/FAQ.md#once-a-major-release-is-published-will-new-features-and-fixes-be-backported-to-previous-versions). You can potentially pull the code from the `release/2.x` branch, update the AWS Go SDK (`go get github.com/aws/aws-sdk-go@v1.34.32`), custom build the provider (`go build`), and point Terraform to the custom version of the provider (the Terraform 0.11 documentation is no longer available on terraform.io, but it amounts to overwriting the existing provider binary or using the plugin cache directory), however the maintainers cannot provide additional assistance if you go that route.
