### ISSUE TITLE
WAFv2 with regex_pattern_set_reference_statement not working?

### ISSUE THREAD

**Issue by randled-re** [terraform-providers/terraform-provider-aws#15576]
AWS Provider 3.9 / 3.10

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.4
+ provider registry.terraform.io/-/aws v3.10.0
+ provider registry.terraform.io/hashicorp/aws v3.10.0

Tried 3.09 and terraform v0.12.28

### Affected Resource(s)

aws_wafv2_web_acl

### Terraform Configuration Files
```
resource "aws_wafv2_web_acl" "default" {

  name  = var.name
  scope = var.scope

  default_action {
    allow {}
  }
  rule {
    name     = "test"
    priority = 13
    action {
      count {}
    }
    override_action {
      none {}
    }
    statement {
      regex_pattern_set_reference_statement {
        arn = $REMOVED
        text_transformation {
          priority = 1
          type     = "NONE"
        }
      }
    }
  }
}
```
### Expected Behavior

able to plan / apply the regex statement with web_acl

### Actual Behavior

Error: Required attribute is not set

### Steps to Reproduce
 `terraform apply`

### Important Factoids

Tried setting action, override_action and neither with field_to_match {} and different text_transformation but still erroing
as per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl

Either its broken or i've missing something not in the terraform or AWS docs.

**Comment by stefan-lipinski** [comment]
What´s missing here are the visibility_config blocks (one inside the rule block and one for the resource).
I also struggled a lot to get it working. So I´m adding my configuration here that could help others.
`resource "aws_wafv2_ip_set" "default_ips" {
  name               = "WP_Allowed_IPs"
  description        = "WP Allowed IPs"
  scope              = "CLOUDFRONT"
  ip_address_version = "IPV4"
  addresses = [
    "192.168.1.1/32", 
    "102.168.1.2/32",
  ]
}

locals {
  regex_string = terraform.workspace == "production" ? ["/wp-admin", "/wp-login"] : ["/"]
}

resource "aws_wafv2_regex_pattern_set" "default_regex_pattern_set" {
  name        = "WP_Restricted_Paths"
  description = "Allow access to ${join(" and ", local.regex_string)} only for allowed IPs"
  scope       = "CLOUDFRONT"

  dynamic "regular_expression" {
    for_each = local.regex_string
    content {
      regex_string = regular_expression.value
    }
  }
}

resource "aws_wafv2_web_acl" "default_web_acl" {
  name  = "WP_Web_ACL"
  scope = "CLOUDFRONT"

  default_action {
    allow {}
  }

  rule {
    name     = "WP_Restricted_Paths"
    priority = 5

    action {
      block {}
    }

    statement {
      and_statement {
        statement {
          regex_pattern_set_reference_statement {
            arn = aws_wafv2_regex_pattern_set.default_regex_pattern_set.arn

            field_to_match {
              uri_path {}
            }

            text_transformation {
              priority = 1
              type     = "NONE"
            }
          }
        }

        statement {
          not_statement {
            statement {
              ip_set_reference_statement {
                arn = aws_wafv2_ip_set.default_ips.arn
              }
            }
          }
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "WP_Restricted_Paths"
      sampled_requests_enabled   = false
    }
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "WP_Web_ACL"
    sampled_requests_enabled   = false
  }
}

`
