### ISSUE TITLE
Pipeline token doesn't work

### ISSUE THREAD

**Issue by gauravachatrath** [terraform-providers/terraform-provider-aws#15595]
Hi,

When we give github token in aws codepipeline which is mandatory in aws provider 3.0

The pipeline works fine the first time only but not again. May you please help me fix this issue ?

**Comment by willzofsteel** [comment]
I am having something somewhat similar though in our case, the pipeline is created successfully but the Github source action fails even though we've used the same oauth token previously.
I did find this https://docs.aws.amazon.com/codepipeline/latest/userguide/appendix-github-oauth.html
So looks like AWS is getting rid of Oauth authentication but I can't seem to find terraform configs to replace the github oauth token for this new connection thing they want.

**Comment by willzofsteel** [comment]
Theres an issue already open on this: #15200
