### ISSUE TITLE
When I changed the volume size and volume type, it was not reflected in tfstate. Is this a bug? 

### ISSUE THREAD

**Issue by terachan-in-git** [terraform-providers/terraform-provider-aws#15596]
As the subject says. An event has occurred in which the changed contents are not reflected in tfstate. Is this a bug?
tfstate is stored in the s3 bucket.

**Comment by gdavison** [comment]
Hi @terachan-in-git, we'll need a lot more information to help out with this. Can you please resubmit this issue and fill out the information that is asked for in the issue template? We can then use that information to understand the problem.
