### ISSUE TITLE
Failing to change aws_route53_record.dns_record from weighted to simple 

### ISSUE THREAD

**Issue by molywitman** [terraform-providers/terraform-provider-aws#15622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

provider "aws" {
  // version lock
  version = "~> 2.6"
  // The AWS region in which all resources will be created
  region = var.aws_region
  // Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = [var.aws_account_id]
}

terraform {
  
  backend "s3" {}
 
  required_version = ">= 0.12"
}

##-----------------------------------------------------------------------------------------------------------------------
##  Use Edge as entry point to the service
##-----------------------------------------------------------------------------------------------------------------------

resource "aws_cloudfront_distribution" "edge_entry_point" {
  count = var.edge_entry_point ? 1 : 0
  origin {
    domain_name = var.alb_dns_name
    origin_id   = "${var.service_name}-${var.vpc_name}"

    custom_origin_config {
      http_port = 80
      https_port = 443
      origin_protocol_policy = "http-only"
      origin_ssl_protocols = ["TLSv1.2"]
    }
  }

  enabled             = true
  //is_ipv6_enabled     = true
  comment             = "Edge Entry Point For ${var.service_name}-${var.vpc_name}"

  aliases = [var.domain_name]

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = [ "HEAD", "GET" ]
    target_origin_id = "${var.service_name}-${var.vpc_name}"

    forwarded_values {
      headers  = ["*"]
      query_string = true

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    compress               = true
    min_ttl                = 0
    default_ttl            = 0
    max_ttl                = 0
  }

  price_class     = "PriceClass_100"

  viewer_certificate {
    ssl_support_method = "sni-only"
    iam_certificate_id = null
    acm_certificate_arn = element(concat(data.aws_acm_certificate.cert_fourth.*.arn,
    data.aws_acm_certificate.cert_fifth.*.arn,
    data.aws_acm_certificate.cert_third.*.arn,
    data.aws_acm_certificate.cert.*.arn,
    data.aws_acm_certificate.cert_secondary.*.arn),0)
  }
  restrictions {
    geo_restriction {
      restriction_type = "none"
      locations        = []
    }
  }
}
// ---------------------------------------------------------------------------------------------------------------------
// CREATE A DNS RECORD USING ROUTE 53 FOE EDGE
// ---------------------------------------------------------------------------------------------------------------------

locals {
  tmp_dm = split(".", var.domain_name)
  domain_name = "${local.tmp_dm[1]}.${local.tmp_dm[2]}"
  acm_certificate_domain_name = "*.${local.tmp_dm[1]}.${local.tmp_dm[2]}"
}

data "aws_route53_zone" "selected" {
  count = var.edge_entry_point  ? 1 : 0
  name =  local.domain_name
  tags = null
  private_zone = false
}

resource "aws_route53_record" "website" {
  count = var.edge_entry_point ? 1 : 0

  zone_id = data.aws_route53_zone.selected[0].zone_id

  name    = var.domain_name
  type    = "A"

  set_identifier = "edge-${var.service_name}-${var.vpc_name}"

  dynamic "weighted_routing_policy" {
    for_each = var.edge_weighted_numbers
    content {
      weight =  lookup(weighted_routing_policy.value, "weight")
    }
  }

  alias {
    name = element(
    concat(
    aws_cloudfront_distribution.edge_entry_point.*.domain_name
    ),
    0,
    )
    zone_id = element(
    concat(
    aws_cloudfront_distribution.edge_entry_point.*.hosted_zone_id,
    ),
    0,
    )
    evaluate_target_health = true
  }
}

provider "aws" {
  // version lock
  version = "~> 2.6"
  alias  = "east"
  region = "us-east-1"
}

data "aws_acm_certificate" "cert" {
  count    = var.create_route53_entry ? 1 : 0
  provider = aws.east

  domain   = local.acm_certificate_domain_name
  statuses = ["ISSUED"]
}

data "aws_acm_certificate" "cert_secondary" {
  count    = var.create_route53_entry_secondary ? 1 : 0
  provider = aws.east

  domain   = local.acm_certificate_domain_name
  statuses = ["ISSUED"]
}

data "aws_acm_certificate" "cert_third" {
  count    = var.create_route53_entry_third ? 1 : 0
  provider = aws.east

  domain   = local.acm_certificate_domain_name
  statuses = ["ISSUED"]
}

data "aws_acm_certificate" "cert_fourth" {
  count    = var.create_route53_entry_fourth ? 1 : 0
  provider = aws.east

  domain   = local.acm_certificate_domain_name
  statuses = ["ISSUED"]
}

data "aws_acm_certificate" "cert_fifth" {
  count    = var.create_route53_entry_fifth ? 1 : 0
  provider = aws.east

  domain   = local.acm_certificate_domain_name
  statuses = ["ISSUED"]
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

## aws_route53_record.dns_record[0] will be updated in-place
  ~ resource "aws_route53_record" "dns_record" {
        fqdn           = "a-ros.tabit-dev.com"
        id             = "Z189Y2MAF9B0HF_a-ros.tabit-dev.com_A_alb-fargate-rosapi-dev"
        name           = "a-ros.tabit-dev.com"
        records        = []
      - set_identifier = "alb-fargate-rosapi-dev" -> null
        ttl            = 0
        type           = "A"
        zone_id        = "Z189Y2MAF9B0HF"

        alias {
            evaluate_target_health = true
            name                   = "dev-alb-public-2014458383.eu-west-1.elb.amazonaws.com"
            zone_id                = "Z32O12XQLNTSW2"
        }

      - weighted_routing_policy {
          - weight = 0 -> null
        }
    }

  ## aws_route53_record.website[0] will be destroyed
  - resource "aws_route53_record" "website" {
      - fqdn           = "a-ros.tabit-dev.com" -> null
      - id             = "Z189Y2MAF9B0HF_a-ros.tabit-dev.com_A_edge-fargate-rosapi-dev" -> null
      - name           = "a-ros.tabit-dev.com" -> null
      - records        = [] -> null
      - set_identifier = "edge-fargate-rosapi-dev" -> null
      - ttl            = 0 -> null
      - type           = "A" -> null
      - zone_id        = "Z189Y2MAF9B0HF" -> null

      - alias {
          - evaluate_target_health = true -> null
          - name                   = "dbl6967e4lkv3.cloudfront.net" -> null
          - zone_id                = "Z2FDTNDATAQYW2" -> null
        }

      - weighted_routing_policy {
          - weight = 100 -> null
        }
    }

### Panic Output
Error: [ERR]: Error building changeset: InvalidChangeBatch: [RRSet with DNS name a-ros.tabit-dev.com., type A cannot be created as other RRSets exist with the same name and
type.]                                                                                                                                                                      
        status code: 400, request id: 693a581f-a66e-4a2b-a3af-82b3b21d5716                

I assume  that this set are failing  : 

 - set_identifier = "alb-fargate-rosapi-dev" -> null
.
      - weighted_routing_policy {
          - weight = 0 -> null
        }

### Expected Behavior
change aws_route53_record.dns_record from weighted to simple !

### Actual Behavior
Failing to change aws_route53_record.dns_record from weighted to simple 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by gdavison** [comment]
Hi @molywitman, the configuration seems to be missing some elements. I can't see the `resource "aws_route53_record" "dns_record"` being defined anywhere. Can you also show what is changing, whether it's input variables or Terraform configuration.

Also, this issue is hard to read. Can you please wrap the Terraform and console output with [code fences](https://github.github.com/gfm/#fenced-code-blocks) using three backticks (```) to start and end the blocks?

**Comment by molywitman** [comment]
The is not clear - i will create new one
