### ISSUE TITLE
aws_ec2_transit_gateway forced replacement

### ISSUE THREAD

**Issue by jered-miller** [terraform-providers/terraform-provider-aws#15620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.13.4

### Affected Resource(s)

* aws_ec2_transit_gateway

### Expected Behavior

Changing transit gateway options shouldn't be a destructive action, at least what I can tell from the API.  These options can be changed in the UI without destroying the resource.

### Actual Behavior

Changing transit gateway options for auto_accept_shared_attachments, default_route_table_association, default_route_table_propagation wants to delete the entire resource, and force a rebuild of all associated elements.

      ~ auto_accept_shared_attachments     = "enable" -> "disable" # forces replacement
        default_route_table_association    = "disable"
      ~ default_route_table_propagation    = "enable" -> "disable" # forces replacement

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment]
@jered-miller Thanks for raising this issue.
It has already been noticed in #15380. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.
