### ISSUE TITLE
FSX Lustre maximum retention is now 90 days

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#15655]
### Description

As with FSX Windows File Systems (#15636), the maximum retention for Lustre is 90 days

### New or Affected Resource(s)

* aws_fsx_lustre_file_system

### References

https://docs.aws.amazon.com/fsx/latest/LustreGuide/using-backups-fsx.html

**Comment by gdavison** [comment]
Absolutely! 😀 I didn't want to hold your other PR up, but our test queue was too long so I wasn't able to merge it anyway. You can create a new PR or add it to #15641

**Comment by philnichol** [comment]
Cheers! I'll update the existing PR shortly
