### ISSUE TITLE
Add validator for `aws_cloudwatch_event_target ` `input_transformer.input_paths` maximum size

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#15653]
According to https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_InputTransformer.html#API_InputTransformer_Contents, the  `input_transformer` `input_paths` map can have a maximum of 10 entries. There is no validation of this maximum, nor is this documented in Terraform documentation.

### Affected Resource

* aws_cloudwatch_event_target

### References

* Relates #10912

**Comment by philnichol** [comment]
@gdavison mind if I have a crack at this one?
