### ISSUE TITLE
Amazon EventBridge Schema Registry

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#15671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement support for the [EventBridge Schema Registry](https://docs.aws.amazon.com/eventbridge/latest/userguide/eventbridge-schemas.html)

### Potential New Resources

* aws_eventbridgeschema_discoverer
* aws_eventbridgeschema_registry
* aws_eventbridgeschema_resource_policy
* aws_eventbridgeschema_schema

### Potential New Data Sources

* aws_eventbridgeschema_registry
* aws_eventbridgeschema_schema

**Comment by bigkraig** [comment]
is this the same as #11088?

**Comment by gdavison** [comment]
Sure is :) I swear I searched for it
