### ISSUE TITLE
 NodeCreationFailure while running terraform

### ISSUE THREAD

**Issue by jatinder10884** [terraform-providers/terraform-provider-aws#15675]
Hi,
I am using terraform for spinning up AWS EKS Cluster. When I run my terraform modules it is creating the cluster and but It will fail to add the worker node to the cluster.

ERROR:
________________________________________________________________________________________
Error: error waiting for EKS Node Group (app-eks-prd:app-eks-prd_public_node_group) creation: NodeCreationFailure: Instances failed to join the kubernetes cluster. Resource IDs: [i-0b06c566c8c8f87d7]

Error: error waiting for EKS Node Group (app-eks-prd:app-eks-prd_private_node_group) creation: NodeCreationFailure: Instances failed to join the kubernetes cluster. Resource IDs: [i-08f30b68d972e7dbb]
________________________________________________________________________________________

Please let me know how I can resolve this issue

Thanks
Jatinder

**Comment by gdavison** [comment]
Hi @jatinder10884, there isn't enough information for us to look into this. Can you please re-submit this issue using our issue template and fill in the information needed?
