### ISSUE TITLE
terraform import aws_eip_association says that the remote object does not exist but it does.

### ISSUE THREAD

**Issue by trajano** [terraform-providers/terraform-provider-aws#15703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.11.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.0.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v2.2.0
+ provider registry.terraform.io/terraform-providers/acme v1.5.0
```

### Affected Resource(s)

* aws_eip_association

### Terraform Configuration Files

```hcl
resource "aws_eip_association" "production_eip" {
  # terraform import aws_eip_association.production_eip eipalloc-xxxxxx
  instance_id   = module.lj.manager_instance_ids[0]
  allocation_id = aws_eip.production_eip.allocation_id
}
```

### Steps to Reproduce

1. `terraform import aws_eip_association.production_eip eipalloc-XXXXXX`

yields
```
aws_eip_association.production_eip: Importing from ID "eipalloc-XXX"...
aws_eip_association.production_eip: Import prepared!
  Prepared aws_eip_association for import
aws_eip_association.production_eip: Refreshing state... [id=eipalloc-XXX]

Error: Cannot import non-existent remote object
````
### References

https://github.com/terraform-providers/terraform-provider-aws/issues/4876

**Comment by alexwlchan** [comment]
I’m not sure if this is significant, but the example in the [Terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip_association) uses a different-looking ID to the one you're using (emphasis mine):

> EIP Assocations can be imported using their **association ID**.
>
> <pre><code>$ terraform import aws_eip_association.test <strong>eipassoc</strong>-ab12c345</code></pre>

Since an EIP association exports both an association and an allocation ID, maybe you need to try the other one?

(I have no idea how you go about finding the association ID.)

**Comment by trajano** [comment]
Doh.
