### ISSUE TITLE
Changing name of MSK configuration fails when in use

### ISSUE THREAD

**Issue by dacreify** [terraform-providers/terraform-provider-aws#15831]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/-/aws v3.12.0
+ provider registry.terraform.io/hashicorp/aws v3.12.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
```

### Affected Resource(s)

* `aws_msk_configuration`

### Expected Behavior

Renaming requires replacement, so expected sequence is:

* New configuration created
* Cluster switched over to new configuration
* Old configuration deleted

### Actual Behavior

```
Error: error deleting MSK Configuration (arn:aws:kafka:us-east-1:XXXX:XXXX): BadRequestException: Configuration is in use by one or more clusters. Dissociate the configuration from the clusters.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "2198c712-56a9-408a-8050-0c18155597e2"
  },
  InvalidParameter: "arn",
  Message_: "Configuration is in use by one or more clusters. Dissociate the configuration from the clusters."
}
```

### Steps to Reproduce

1. `terraform apply`
2. Change `aws_msk_configuration` `name`
3. `terraform apply`

**Comment by bill-rich** [comment]
Hi @dacreify! Unfortunately, I don't believe this is possible. You could use `create_before_destroy` on the configuration resource, but then the new configuration will have the same name and be in conflict with the first. The best way I've found to deal with this is to create a new `msk_configuration` and switching all the clusters over to the new configuration.
