### ISSUE TITLE
Provide releases more often

### ISSUE THREAD

**Issue by dvishniakov** [terraform-providers/terraform-provider-aws#1592]
### Terraform Version
0.10.x

It's not possible to point terraform to the commit of a provider (AFAIK). Can you release it more often? There are changes and bug fixes which people wait but it's not clear how to get them.
Also, by releasing more often it will be easier to bisect when a regression was introduced

**Comment by leftathome** [comment]
+1 for this, I'm doing some encrypted-EFS module development, so a release would save me some time modifying my CI pipeline to use an unreleased plugin.

Is there something the community could do to make it easier to release more frequently?  More maintainers/reviewers, more comprehensive test coverage, improved release automation?

**Comment by bflad** [comment]
Previously we were doing a two-week release cadence. We're currently trying a weekly release cadence. At a certain point, we may provide nightly builds and potentially bake that mechanism into Terraform core, but there is no roadmap issue or timeline for that functionality in either core or the AWS provider. If you would like commit or automated nightly build support, I would suggest creating a separate issue and trying to gather 👍  upvotes on the original issue comment of that new issue to gain priority.

Given there is not a definition of done for this issue though, I'm going to close it. 😃
