### ISSUE TITLE
Question - no steps parameter on aws_emr_cluster

### ISSUE THREAD

**Issue by bacoboy** [terraform-providers/terraform-provider-aws#1593]
Looking at the [AWS EMR create-cluster CLI](http://docs.aws.amazon.com/cli/latest/reference/emr/create-cluster.html) documentation, one of the parameters you can pass is an array of `steps`.  This is missing from the terraform resource as far as I can tell.

Did I miss something?

**Comment by luckytaxi** [comment]
Same here. It's the very first thing I noticed. Without it, we may have to use the aws cli.

**Comment by aba182** [comment]
+1 Yes we can get a cluster up successfully but then we have to leverage AWS CLI to actually get the cluster to do anything. Is this function looking to come out anytime soon?

**Comment by AlexMaksimkin** [comment]
+1 Anyone plan to add this functional to provider? 
Issue was opened 6 month ago and still without any movements.

**Comment by bacoboy** [comment]
The workaround I've been using until this gets implemented is to make the awscli `add-steps` call in a provisioner block on the cluster resource.

Wait, it gets worse...  You can't reuse the identity of the aws provider so you have to deal with that.  Also, changes in steps won't trigger a delta on the cluster.  So you'll need to generate a checksum or something (like on the step json via a rendered template).  This way, when there is a change to the step, you force terraform into thinking there is a change to the cluster as well which results in a teardown and create.

**Comment by bflad** [comment]
I'll be working on a PR to implement this functionality. Related issues: #1714 and #1866

**Comment by bflad** [comment]
Support for configuring steps during cluster creation has been merged into master via #3673 and will release with v1.12.0 of the AWS provider, likely in about a week.

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
