### ISSUE TITLE
Adding Binary Resource on API Gateway forces new resource 

### ISSUE THREAD

**Issue by SmithKevin** [terraform-providers/terraform-provider-aws#1594]
Anyone have any insight on why adding a new Binary Resource forces a new resource?  Since this is the root of the gateway it causes Terraform to destroy and rebuild the entire gateway which is potentially hundreds of resources.  The AWS CLI and console can add it without any additional changes.
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-control-service-api.html  

Relevant PR is here https://github.com/hashicorp/terraform/pull/10776
Line of Code:
https://github.com/terraform-providers/terraform-provider-aws/blob/6c64d1569780b0c83e82bb74ca0fa7fd9a562c94/aws/resource_aws_api_gateway_rest_api.go#L37

Would removing this line be enough or do I need to write additional code to support this patch request?

**Comment by Ninir** [comment]
Hey @SmithKevin 

You are 100% right, updates should be possible. I assume it was not doable previously, and it is now.
Just pushed a code update for that :)

Sorry for the noise!
