### ISSUE TITLE
Update Data Source AWS Redshift Service

### ISSUE THREAD

**Issue by david-wells-1** [terraform-providers/terraform-provider-aws#1609]
Hi,

terraform-provider-aws update required for

data_source_aws_redshift_service_account.go

The following Redshift service accounts need to be added, as Redshift is now available in these regions:

eu-west-2    307160386991
sa-east-1     075028567923

**Comment by david-wells-1** [comment]
I have submitted an amendment which resolves this issue - this pull request has now been approved

**Comment by Ninir** [comment]
Thanks for taking care of that @david-wells-1 👍
