### ISSUE TITLE
[feature request] Add the description attribute to aws_security_group_rule rules

### ISSUE THREAD

**Issue by naveenb29** [terraform-providers/terraform-provider-aws#1612]
AWS added a new description field to SGs, wanted to add this feature to terraform's backlog.

https://t.co/TnkHCz1Lcn

**Comment by Ninir** [comment]
Hi @naveenb29 

Thanks for opening this issue!

However, there is already one to keep track of it [right here](1554). Thus, I'm gonna close this one and invite you to check the other one!

Thanks again :)
