### ISSUE TITLE
FEATURE REQUEST: Add support for EMR disk sizing

### ISSUE THREAD

**Issue by hylaride** [terraform-providers/terraform-provider-aws#1622]
Hi,

We currently use terraform to spin up EMR clusters.  We need more disk space, though!

There are two knobs that AWS provides.  root volume size (up to a max of 100GB) via `--ebs - root - volume - size 1` and then `EbsConfiguration":{"EbsBlockDeviceConfigs":[{"VolumeSpecification":{"SizeInGB":1000,"VolumeType":"gp2"},"VolumesPerInstance":1}],"EbsOptimized":true}` which is configured via the task/core node configs.

Can this be added directly via TF?

### Affected Resource(s)

* aws_emr_cluster
* aws_emr_instance_group

**Comment by hylaride** [comment]
I think I see you added support for it [here](https://github.com/terraform-providers/terraform-provider-aws/commits/master/aws/resource_aws_emr_cluster.go), but only for task instance groups.  Hadoop runs on the core nodes, and that's where most EMR tasks will need more disk space, unless I'm missing something?

**Comment by hylaride** [comment]
Also, I don't see if there was support added for setting root volume disk sizes.

**Comment by rolandjohann** [comment]
Root volume size has been implemented by #1375

**Comment by hylaride** [comment]
@rolandjohann  aha!  That's good to know. Hopefully EbsConfiguration is added as well!

**Comment by hylaride** [comment]
Huy guys!  Any idea if/when EbsConfiguration for core instances will be implemented?

**Comment by hylaride** [comment]
I just realized I was using the instance_group parameter wrong.  😝
