### ISSUE TITLE
Add support for security group rule descriptions

### ISSUE THREAD

**Issue by vamsirede** [terraform-providers/terraform-provider-aws#1634]
AWS has added new feature that allows customers to add a short description to individual security group rules.

https://aws.amazon.com/about-aws/whats-new/2017/08/simplify-management-of-security-groups-with-security-group-rule-descriptions/

**Comment by barnesm999** [comment]
There is an open PR for this: https://github.com/terraform-providers/terraform-provider-aws/pull/1587
