### ISSUE TITLE
Add support for new NLB

### ISSUE THREAD

**Issue by AncientCulture** [terraform-providers/terraform-provider-aws#1639]
Hi,

AWS ec2 has a new LB, the network load balancer (NLB). It is a replacement for the previous ELB. AWS recommends using the old ELB primary for AWS ec2-classic envs.

As the NLB works similar as the ALB (listener, target groups) and shares API calls implementation might be quick feasible.

Here the block post:
https://aws.amazon.com/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/

aws-go-sdk added support in version 1.10.40, which is alreadythe current version in vendor directory.

Cheers and thanks,
Nils

**Comment by AncientCulture** [comment]
oh and to be consistent the "old" elb may need to be renamed to CLB (classic load balancer) as this is the new name in AWS

**Comment by stack72** [comment]
@AncientCulture this is being taken care of in #1629

FWIW, classic load balancer is known as ELB in Terraform. Application load balancers were known as ALB but I have renamed those to load balancers as they can be either application or network

**Comment by Ninir** [comment]
Hi @AncientCulture 

@stack72 is right on that! :)
I would like to add that there is another thread keeping track of this issue [here](https://github.com/terraform-providers/terraform-provider-aws/issues/1618).

I am now going to close this one if you don't mind: if you want to comment & discuss, please do it on the thread! 👍 

Thanks!
