### ISSUE TITLE
aws_ecs_service treating validation errors as retryable

### ISSUE THREAD

**Issue by leftathome** [terraform-providers/terraform-provider-aws#1652]
### Terraform Version
Multiple, going back to at least 0.9.4.

### Affected Resource(s)
- aws_ecs_service

### Terraform Configuration Files
```hcl
# synthetic based on my code, probably works for anyone
data "aws_vpc" "default" {
  default = "true"
}

resource "aws_ecs_cluster" "app" {
  name = "foo-app"
}

resource "aws_alb_target_group" "foo" {
  name_prefix = "foo-"
  port = 80
  protocol = "HTTP"
  vpc_id = "${data.aws_vpc.default.id}"
}

resource "aws_ecs_service" "http_redirect" {
  name            = "http_redirect"
  cluster         = "${aws_ecs_cluster.app.id}"
  task_definition = "{}"
  desired_count   = "1"

  load_balancer {
    target_group_arn = "${aws_alb_target_group.foo.id}"
    container_name   = "foo-does-not-exist"
    container_port   = "80"
  }
}
```

### Debug Output
See: https://gist.github.com/leftathome/4ee48df948b2ff43330d04fbc9cb9ece

### Expected Behavior
Terraform should be interpreting the 400 responses as hard failures.  The run should fail immediately and bubble the 400 response back to the console.

### Actual Behavior
Terraform is treating the 400 responses as transient, retryable failures.  It waits ten seconds and retries, up to its retry limit (typically 2 minutes), and then reports the 400 error back to the console.

### Steps to Reproduce
Create an incomplete service that fails an AWS API validation check in any way.  Plug in a valid container definition and ALB register/deregister into the example above and it should work, as that's the only thing I've left out from scrubbing my code for public consumption.  The example code should yield at least one of the following two errors:
 * No such container name.
 * ALB target group specified is not part of any ALB.

**Comment by leftathome** [comment]
Also happens in `ecs_cluster` - to reproduce, try to destroy an ECS cluster with an active instance, regardless of whether or not it has any tasks.

I hit a ten-minute timeout on my run, which finally returned this error:
```
module.example_ecs.aws_ecs_cluster.app: Still destroying... (ID: arn:aws:ecs:us-west-2:x:cluster/y, 9m50s elapsed)
Error applying plan:

1 error(s) occurred:

* module.example_ecs.aws_ecs_cluster.app (destroy): 1 error(s) occurred:

* aws_ecs_cluster.app: ClusterContainsContainerInstancesException: The Cluster cannot be deleted while Container Instances are active or draining.
```

**Comment by s-maj** [comment]
I think this is intended otherwise TF would fail waiting for other resources to change state. See https://github.com/hashicorp/terraform/issues/2691.
