### ISSUE TITLE
Add Tags to aws_nat_gateway

### ISSUE THREAD

**Issue by certnew** [terraform-providers/terraform-provider-aws#1653]
Hi there,

Please add tags property to aws_nat_gateway resource.

### References
https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-vpc-nat-gateways-now-support-amazon-cloudwatch-monitoring-and-resource-tagging/

Thank you

**Comment by Ninir** [comment]
Hi @certnew,

This has already been taken care of in https://github.com/terraform-providers/terraform-provider-aws/pull/1625 and will be available in the next release! 👍 

Closing! :)
