### ISSUE TITLE
Crash Report aws_kinesis_firehose_delivery_stream

### ISSUE THREAD

**Issue by endzyme** [terraform-providers/terraform-provider-aws#1657]
Hi there,

### Terraform Version
Terraform Version: `v0.10.4`
Provider Version: `v0.1.4`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kinesis_firehose_delivery_stream

(Happens on one and also many of these definitions)

### Terraform Configuration Files
```hcl
resource "aws_kinesis_firehose_delivery_stream" "broken_tracking_autocomplete_stream" {
  name        = "tracking_autocomplete_stream"
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn           = "${aws_iam_role.firehose_delivery_role.arn}"
    prefix             = "tracking/autocomplete_stream/"
    buffer_interval    = 300
    buffer_size        = 5
    compression_format = "GZIP"
    bucket_arn         = "arn:aws:s3:::non-existant-bucket-broken"
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

*NOTE:* Crash log is 6MB so I am not including it. I can add later if it's needed.

### Panic Output
https://gist.github.com/endzyme/0e3474827f40ce15dd9b83c6886b4c21

### Expected Behavior
Should have provisioned a new firehose that doesn't exist.

### Actual Behavior
Sometimes get a: unexpected EOF error (see below) and sometimes get a terraform crash.
```
Error applying plan:

1 error(s) occurred:

* aws_kinesis_firehose_delivery_stream.broken_tracking_autocomplete_stream: 1 error(s) occurred:

* aws_kinesis_firehose_delivery_stream.broken_tracking_autocomplete_stream: unexpected EOF
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan && terraform apply`

### Important Factoids
This worked once but I had to update all the streams, after updating the streams it gave me the "unexpected EOF" error. I removed all the assets and applied then recreated the items again but got the EOF issue, tried a few more times then got the crash report. Crash report is not 100% reproducible.

### References
*N/A*

**Comment by cgarvis** [comment]
I was able to fix this by adding `processing_configuration` to my resource

```
resource "aws_kinesis_firehose_delivery_stream" "firehose" {
        name = "firehose"
        destination = "extended_s3"

        extended_s3_configuration {
                role_arn = "${aws_iam_role.firehose.arn}"
                bucket_arn = "${aws_s3_bucket.bucket.arn}"

                processing_configuration  = [
                    {
                        enabled = "false"
                    }
                ]
        }
}
```

**Comment by endzyme** [comment]
Was able to reproduce with this "workaround" -- Docs say optional on that param but apparently it is not optional. Thanks @cgarvis!

**Comment by matthew-lowe-izettle** [comment]
Adding `processing_configuration` fixed this for me too. I think that the [documentation](https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html#processing_configuration) needs to be updated, as it currently says its `Optional`.
