### ISSUE TITLE
aws_lambda_function versioning issue when publish = true

### ISSUE THREAD

**Issue by edmundcraske** [terraform-providers/terraform-provider-aws#1692]
Hi, I've just spotted an issue where we have changed the memory_size and timeout arguments to an aws_lambda_function at the same time as updating the source, so causing a new version to be published (as publish = true).

However, from reading the code, it seems that rather than publishing a new version (e.g. calling PublishVersion) separately once all changes have been made by terraform (as changing the code and changing the configuration are two separate calls - UpdateFunctionCode and UpdateFunctionConfiguration), a feature of UpdateFunctionCode is used to publish a new version as part of that call, but that call is made before UpdateFunctionConfiguration. In this case it would have worked had the calls been the other way around.

Having just taken a look through existing issues, I suppose this is sort of related to #601... For which the above fix would not work, as UpdateFunctionCode is not called at all and so the version is not updated. I would think it is best to call PublishVersion separately (and unconditionally, having called the Update function for the resource) after the updates have been made?

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.50.0 of the Terraform AWS Provider, later today. Thanks to @nemreid for the implementation. 👍 

Please note that this resource will now use a separate `PublishVersion` API call, so any restrictive IAM policies for the Terraform run may require updates.
