### ISSUE TITLE
Route53 Alias records modify on each terraform apply.

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-aws#1700]
### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "mywebsite" {
  zone_id = "${data.aws_route53_zone.k8.zone_id}"
  name    = "mywebsite.mydomain.com"
  type    = "A"

  alias {
    name                   = "${element(values(data.kubernetes_service.external-nginx.load_balancer_ingress[0]), 0)}"
    zone_id                = "${data.aws_elb_hosted_zone_id.elb.id}"
    evaluate_target_health = true
  }
}
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform should create the record once and afterwards running terraform plan should show no changes.

### Actual Behavior

Terraform plan always will show my Alias Records going from "true" to "false" but these changes are not made to route53.

```
  ~ aws_route53_record.mywebsite
      alias.2441962247.evaluate_target_health:  "true" => "false"
      alias.2441962247.name:                    "a345acf5f971211e790850afbb860d2a-245820010.us-west-2.elb.amazonaws.com" => ""
      alias.2441962247.zone_id:                 "Z1H1FL5HABSF5" => ""
      alias.~2595901456.evaluate_target_health: "" => "true"
      alias.~2595901456.name:                   "" => "${element(values(data.kubernetes_service.external-nginx.load_balancer_ingress[0]), 0)}"
      alias.~2595901456.zone_id:                "" => "Z1H1FL5HABSF5"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`
3. `terraform apply`
4. `terraform plan` see what I'm getting at?

**Comment by ColinHebert** [comment]
Relates to https://github.com/terraform-providers/terraform-provider-aws/issues/306

**Comment by shadycuz** [comment]
@ColinHebert You are correct, I will try to get around to looking into it this weekend. I'm guessing it's still relevant.

**Comment by shadycuz** [comment]
stale
