### ISSUE TITLE
Support for EFS encryption

### ISSUE THREAD

**Issue by sfrode** [terraform-providers/terraform-provider-aws#1705]
EFS recently got support for [encryption of data at rest](https://aws.amazon.com/blogs/aws/new-encryption-at-rest-for-amazon-elastic-file-system-efs/). It would be great if someone could update the _aws_efs_file_system_ resource with support for it.

Reference: https://docs.aws.amazon.com/efs/latest/ug/API_CreateFileSystem.html

**Comment by Ninir** [comment]
Hi @sfrode ,

https://github.com/terraform-providers/terraform-provider-aws/pull/1420 added the encryption plus the KMS stuff for that: it is to be released in the next version, a.k.a 1.0.0! 🎆 

Closing if you don't mind :)

Thanks!
