### ISSUE TITLE
Question: Expected Release of 1.0.0

### ISSUE THREAD

**Issue by shezaan** [terraform-providers/terraform-provider-aws#1708]
Hello,
I was wondering what the expected release schedule is for 1.0.0. There is a specific feature (EFS encryption) that seems to be part of that release.

**Comment by bflad** [comment]
Relatedly: #1592

**Comment by Ninir** [comment]
Hi folks,

Release 1.0.0 is out! Thank you for your patience, next ones will be released more often :)

Closing!

**Comment by shezaan** [comment]
Nice couldn't wait. Thanks for letting us know.
