### ISSUE TITLE
Feature Request: Descriptionf or egress/ingress on Security Groups

### ISSUE THREAD

**Issue by Bjorn121** [terraform-providers/terraform-provider-aws#1718]
AWS now supports adding Descriptions to specific rules on Security Groups.  Is it possible to add that in one of the future releases?

Source: [`Link`](https://aws.amazon.com/blogs/aws/new-descriptions-for-security-group-rules/)

**Comment by Ninir** [comment]
Hi @Bjorn121 

A work has already been started [here](https://github.com/terraform-providers/terraform-provider-aws/pull/1587).

An opened issue already exists for that [here](https://github.com/terraform-providers/terraform-provider-aws/issues/1554).

Closing to centralize & better keep tracks of comments!

Thanks :)
