### ISSUE TITLE
Not able to set empty `lambda_function_association` on cloudfront distributions

### ISSUE THREAD

**Issue by rarguelloF** [terraform-providers/terraform-provider-aws#1720]
### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
- aws_cloudfront_distribution

### Terraform Configuration Files
```hcl
resource "aws_cloudfront_distribution" "website_distribution" {
  # ...
  lambda_function_association = []
}
```

### Expected Behavior
The configuration should work and interpret this as not setting the `lambda_function_association` attribute at all, disabling all the lambda@edge triggers it previously had (or doing nothing if there were no triggers at all).

This is useful for being able to configure different cloudfront distributions with different lambdas (or no lambdas) and have more DRY configuration files.

### Actual Behavior
The configuration gives the following error:

```
1 error(s) occurred:

* aws_cloudfront_distribution.website_distribution: : invalid or unknown key: lambda_function_association
```

### Steps to Reproduce
1. `terraform plan`

**Comment by rarguelloF** [comment]
Ok, this was my mistake. I was trying to put `lambda_function_association ` outside `default_cache_behaviour`, which is where it belongs to.

**Comment by xenoterracide** [comment]
found this looking for my problem too... turns out the solution is the same... but suggests that a documentation improvement might be in order.

**Comment by xenoterracide** [comment]
yeah, I think I would have noticed it easier that way.
