### ISSUE TITLE
add ability to tag aws_nat_gateway resource resources

### ISSUE THREAD

**Issue by majormoses** [terraform-providers/terraform-provider-aws#1741]
AWS Nat Gateway supports aws tagging but the terraform resource does not. If I knew go better I would try to figure it out further but it looks like it;s supported in the sdk? https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateNatGatewayInput

**Comment by ewbankkit** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/1625.
