### ISSUE TITLE
type BOOL not being recognized by terraform for attribute type which is also the range key

### ISSUE THREAD

**Issue by dkc-bitsian** [terraform-providers/terraform-provider-aws#1746]
type 'BOOL' is not supported.
I set a range key to be an attribute which is of BOOL

aws_dynamodb_table.RO-dynamodb: AWS Error creating DynamoDB table: ValidationException: 1 validation error detected: Value 'BOOL' at 'attributeDefinitions.4.member.attributeType' failed to satisfy constraint: Member must satisfy enum value set: [B, N, S]

**Comment by dkc-bitsian** [comment]
type 'BOOL' is not supported.
I set a range key to be an attribute which is of BOOL

aws_dynamodb_table.RO-dynamodb: AWS Error creating DynamoDB table: ValidationException: 1 validation error detected: Value 'BOOL' at 'attributeDefinitions.4.member.attributeType' failed to satisfy constraint: Member must satisfy enum value set: [B, N, S]

**Comment by Ninir** [comment]
Hi @dkc-bitsian 

As exposed by the Validation error, could you use `B` instead of `BOOL` as type?
Tell us how it goes, thanks!

**Comment by paddycarver** [comment]
Hi there! It looks like the issue author hasn't replied in a while. In the interest of helping keep the repository clean to help identify the issues that require maintainers' attention, I'm going to close this issue out. If it still requires action, or if someone has interest in it being reopened, feel free to reply to the issue.

**Comment by atward** [comment]
@Ninir `B` is a bytebuffer, not a bool

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html

**Comment by dkc-bitsian** [comment]
@Ninir that will not work since as explained above it represent a bytebuffer
