### ISSUE TITLE
AWS CodeBuild using environment variables from EC2 Parameter Store

### ISSUE THREAD

**Issue by blaltarriba** [terraform-providers/terraform-provider-aws#1747]
Hi there,

I'm using Terraform to create a AWS CodeBuild project and I want to avoid to put environment variables as a text plain, instead I want to use variables stored at EC2 Parameter Store.

### Terraform Version
v0.10.0

### Affected Resource(s)
AWS CodeBuild
AWS EC2 Systems Manager Parameter Store

### Expected Behavior
Be able to use variables stored at EC2 Parameter Store as a environment variables of AWS CodeBuild project.

### Actual Behavior
Not supported.

**Comment by bflad** [comment]
Support for configuring environment variable `type = "PARAMETER_STORE"` has been merged into master and will release with v1.21.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
