### ISSUE TITLE
ValidationError: Cannot create aws_lb_ssl_negotiation_policy on existing ALB

### ISSUE THREAD

**Issue by christopher-demarco** [terraform-providers/terraform-provider-aws#1754]
### Terraform Version
```
% tf --version
Terraform v0.10.6
```

### Affected Resource(s)
- aws_lb_ssl_negotiation_policy

### Terraform Configuration Files
```hcl
provider "aws" { region = "us-east-1" }

resource "aws_default_subnet" "us-east-1a" { availability_zone = "us-east-1a" }
resource "aws_default_subnet" "us-east-1b" { availability_zone = "us-east-1b" }

resource "aws_alb" "wtf"{
  name = "wtf"
  subnets = [
    "${aws_default_subnet.us-east-1a.id}",
    "${aws_default_subnet.us-east-1b.id}",
  ]
}

resource "aws_lb_ssl_negotiation_policy" "wtf" {
  name = "wtf"
  load_balancer = "${aws_alb.wtf.id}"
  lb_port = 443
}

```

### Debug Output

https://gist.github.com/christopher-demarco/798bda68ad28aab298cfec1601a0f62c

### Expected Behavior

The policy should be created and attached to the referenced LB.

### Actual Behavior

The LB is created, but creation of the policy fails:

```
 aws_lb_ssl_negotiation_policy.wtf: Error creating Load Balancer Policy: ValidationError: LoadBalancer name cannot be longer than 32 characters
```

### Steps to Reproduce

1. `terraform apply`

**Comment by christopher-demarco** [comment]
Can confirm that this error exists at least as far back as v0.9.11 . . . any thoughts?

**Comment by christopher-demarco** [comment]
v0.9.6 does not support `aws_default_subnet`, so that's as far back as I've been able to go.
Error exists in v0.9.7.

**Comment by Ninir** [comment]
Hi @christopher-demarco,

As far as I can see, this is due to the attribute you are getting from `aws_alb.wtf.id`. The id you are using is [actually the ARN of the load balancer](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_alb.go#L190), thus being longer than its name.

What you want is the `name`, as in `aws_alb.wtf.name`.

Could you try with what I suggested and tell me how it goes?

Thanks!

**Comment by christopher-demarco** [comment]
Hmmm . . . I'm getting partial success with `.name` but now I need to make the target LB "active". Looking into this.

However, this is at *least* still a bug against the docs, because https://www.terraform.io/docs/providers/aws/r/lb_ssl_negotiation_policy.html shows using `.id`. ;-)

**Comment by christopher-demarco** [comment]
@Ninir, something's still wrong. Using `.name` now gives the AWS API response `LoadBalancerNotFound: There is no ACTIVE Load Balancer named 'wtf'`.

But the AWS console clearly shows a load balancer so named whose status is `active`. Are we sure that `.name` is the proper attribute?

**Comment by christopher-demarco** [comment]
Same result if I remove the manual "name" attribute and instead let TF generate a name. An `output` confirms that the `.name` attribute on the Resource matches what the negotiation_policy is trying to reference, and the LB instance which the AWS console lists as "active".

**Comment by christopher-demarco** [comment]
@Ninir or anybody else have any ideas about this? What am I missing here?

**Comment by Ninir** [comment]
Hi @christopher-demarco 

I may have found your issue there: you are using a Load Balancer of type Application, which works at the 7 layer (application).
However, you are trying to define an SSL policy which works at layer 4 (transport), so ELB until the [Network Load Balancer work](#1629) is merged.

When using an ALB, you can only select one of the predefined policies, which will be the thing you'll be looking for I guess.

> However, this is at least still a bug against the docs, because https://www.terraform.io/docs/providers/aws/r/lb_ssl_negotiation_policy.html shows using .id. ;-)

Indeed, but in this case, the `id` for ELB are names, whereas for ALB it is the ARN

Please try with an ELB and tell me how it goes :)

Thanks! 👍

**Comment by christopher-demarco** [comment]
The application architecture currently requires ALB, so trying with ELB is a non-starter.

I think you mis-linked the work to add SSL policy in ALB?

I've scratched my immediate itch by simply using a different AWS TLS policy, but it would be nice to know what kind of timeline to expect for the ability to add a custom policy to an ALB?

**Comment by Ninir** [comment]
Hey @christopher-demarco 

> I think you mis-linked the work to add SSL policy in ALB?

Right, updated it :)

> I've scratched my immediate itch by simply using a different AWS TLS policy, but it would be nice to know what kind of timeline to expect for the ability to add a custom policy to an ALB?

I think this is a no-go for now at least, since AWS states in its [documentation](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html): *Application Load Balancers do not support custom security policies.* 😓

**Comment by christopher-demarco** [comment]
OK, thanks!
