### ISSUE TITLE
[Error Reporting] AWS EFS Service is not available in this region

### ISSUE THREAD

**Issue by aakash-garg-olx** [terraform-providers/terraform-provider-aws#1756]
Hi there,

I have created the module to launch EFS, it was created successfully in Ireland Region `eu-west-1`, but when I tried to use the same in Singapore Region `ap-southeast-1`, it started creating EFS and went in the loop, as AWS EFS Service is still not available in Singapore Region.

So, I think it would be good if you throw the error like `Service is not available in this region` then it would be better as it appears that it is creating EFS, but actually it is not. It gets confusing sometimes.

**Comment by Ninir** [comment]
Hi @aakash-garg-olx,

As @radeksimko [explained it](https://github.com/terraform-providers/terraform-provider-aws/issues/1354#issuecomment-320598122) for a slightly different case but very related:

 > this is unfortunately a side effect of how AWS launches services into regions. Each endpoint is region-specific, e.g. email.us-west-2.amazonaws.com for us-west-2. The underlying SDK maps passed region to the appropriate endpoint hostname.
> 
> The reason Terraform let you wait is because it assumes the DNS is temporarily failing to resolve the hostname - which may be the case in some environments. Reducing DNS resolution timeout is a theoretical option here, but this would also affect users which have genuine temporary DNS failures so this may not be practical.
> 
> Neither Terraform or the underlying AWS SDK have knowledge of what regions are supported at any given time because this does change quite often. Maintaining a list of supported regions for every service while updating it every time AWS decides to launch a service into a new region would cause (IMO) unreasonable maintenance burden.
> 
> We however apply this approach to regions themselves to avoid the same issue if user has a typo in region name by maintaining a static list of regions. This was criticised in the past by some users questioning the reason for maintaining a static list, but I still believe it's ok to do it, because whole new regions aren't introduced every day or month, so the maintenance burden is fairly low. Secondly the chance of making a typo is high enough so the benefit of having static validation is justified and overweights the cons.
> 
> Sorry for the confusion coming from this behaviour, I hope the explanation makes sense.

For that reason we can't really help on anything here :-/ 

I'm now going to close this one if you don't mind. Tell me if you have any inputs that would help here, thanks!
