### ISSUE TITLE
aws_efs_file_system encrypted option erroring

### ISSUE THREAD

**Issue by daxroc** [terraform-providers/terraform-provider-aws#1768]
Hi there,

I'm attempting to create an encrypted EFS resource using

```
resource "aws_efs_file_system" "example" {
  creation_token = "state"
  encrypted         = true
  kms_key_id       = "..."
}
```

### Terraform Version
v0.10.6

### Affected Resource(s)
- aws_efs_file_system

### Expected Behavior
Expected plan to show new resource creation

### Actual Behavior
Error
```
terraform plan
2 error(s) occurred:

* aws_efs_file_system.example: : invalid or unknown key: encrypted
* aws_efs_file_system.example: : invalid or unknown key: kms_key_id
```

**Comment by Ninir** [comment]
Hi @daxroc 

Thanks for opening this issue. 1.0.0 was released yesterday (and including the feature you'd like to use), so I'm assuming you are using 0.1.4!

Can you provide the AWS provider version you are using?

**Comment by daxroc** [comment]
Yes upgrading the aws-provider to 1.0.0 solved my problem 

```
provider "aws" {
    version = "1.0.0"
    region = "${var.region}"
}
```
Then `terraform init`

Thanks for the reply @Ninir much appreciated!
