### ISSUE TITLE
Feature Request: AWS Shield Protection

### ISSUE THREAD

**Issue by countergram** [terraform-providers/terraform-provider-aws#1769]
I would like to be able to manage "protection" objects within AWS Shield so that I can declaratively add protections to my resources (which are also managed through Terraform)

**Comment by atsushi-ishibashi** [comment]
I'm developing this resource. But ShieldProtection requires ShiledSubscription and I'm having a trouble to find the way of activating shield advanced...
It costs $3,000 / month...

**Comment by countergram** [comment]
My company has it - how can I help?

**Comment by vianellod** [comment]
Hey, any progress on this one?

**Comment by grealish** [comment]
@atsushi-ishibashi  I maybe able to get you access to a test account to setup shield advanced as I have this subscription already ;)
Let me know how I can help

**Comment by atsushi-ishibashi** [comment]
This depends on the policy of the acceptance test🤔

**Comment by thakkerdhawal** [comment]
+1

**Comment by jcornell123** [comment]
How can we test this for the community?  @akataz

**Comment by iwasnobody** [comment]
+1

**Comment by akataz** [comment]
I've talked to Hashicorp Support and they said they need another company to test the PR before they can merge this, is there anyone with a Shield Advanced Subscription that can test this? @grealish @countergram

**Comment by bflad** [comment]
A new `aws_shield_protection` resource has been merged and will release with version 2.11.0 of the Terraform AWS Provider, likely tomorrow. 👍 

For future bug reports or feature requests with the Shield Advanced service, please submit a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose). Thanks!

**Comment by bflad** [comment]
The new `aws_shield_protection` resource has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
