### ISSUE TITLE
terraform_remote_state broken in 0.10.6

### ISSUE THREAD

**Issue by kurron** [terraform-providers/terraform-provider-aws#1787]
### Terraform Version
Terraform v0.10.6

### Affected Resource(s)
- terraform_remote_state

I have working module that was used with 0.10.3, saving its state in an S3 backend.  That state is referenced in another module via `terraform_remote_state`, which also works.  Once I upgraded to 0.10.6, things started to break.  Suddenly my downstream module is complaining about missing output variables: `Resource 'data.terraform_remote_state.vpc' does not have attribute 'vpc_id' for variable 'data.terraform_remote_state.vpc.vpc_id'`  Initially, I thought it might be an S3 issue but the debug logs show successful downloading of the state file.

If I point the downstream module to the 0.10.3 state file, it works fine.  I compared the two files and noticed that the JSON structure changed a little.

works:
```json
{
    "version": 3,
    "terraform_version": "0.10.3",
    "serial": 7,
    "lineage": "85ee82a9-fcaf-4110-a211-a19ce4ccc8fd",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {
                "vpc_id": {
                    "sensitive": false,
                    "type": "string",
                    "value": "vpc-013da467"
                },
```

broken:

```json
{
    "version": 3,
    "terraform_version": "0.10.6",
    "serial": 5,
    "lineage": "85d6530c-f86e-4b16-8c6b-bb2b26a94f93",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {},
            "depends_on": []
        },
        {
            "path": [
                "root",
                "vpc"
            ],
            "outputs": {
                "vpc_id": {
                    "sensitive": false,
                    "type": "string",
                    "value": "vpc-fb04769d"
                },
```

Notice that the first module's `outputs` key is empty? I've gone over the documentation and didn't find anything that suggested that I need to change the way that I output or import the state. Is this a bug or do I need to reconfigure my Terraform code?

### Debug Output
[Debug Log](https://gist.github.com/kurron/cd3ecf20b2051ef10b6c73409228768f)

### Panic Output
None.

### Expected Behavior
Downstream module should be able to access backend state after upgrading to 0.10.6.

### Actual Behavior
Downstream module can no longer find the desired output variables.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Running on Ubuntu 16.04.  Debug output shows no errors accessing the S3 file.

### References
- [upstream module](https://github.com/kurron/terraform-aws-vpc)
- [downstream module](https://github.com/kurron/terraform-aws-security-groups)

**Comment by ptierno** [comment]
I have experienced this issue as well. For me though it only happens when using the linux build in a docker container. The darwin build seems to work fine.

**Comment by kurron** [comment]
I've upgraded to `Terraform v0.10.7`, rebuilt the upstream module and the downstream module seems to behaving as expected now.

**Comment by kurron** [comment]
Apparently, I was mistaken.  My environment was in an incorrect state when I retested.  I had the downstream module pointing to the `0.10.3` state store, not the newly created `0.10.7` one.  The behavior still occurs and the empty `root` path still exists in the state file.

**Comment by kurron** [comment]
I have more details.  When I run apply from within the module itself, the generated state file has only a single entry in the `modules` list.  When applying the module in another folder, the output has two entries in the `module` list, with the first one being empty.

```
module "vpc" {
    source = "github.com/kurron/terraform-aws-vpc"
    <snip>
}
```
Based on [this statement in the documentation](https://www.terraform.io/docs/providers/terraform/d/remote_state.html#root-outputs-only),  I may have to re-cast the output in the code using the upstream module.  I'll experiment and report back.

**Comment by kurron** [comment]
That appears to have done the trick.  For anybody else who might trip over this, here is a working example.

```
terraform {
    backend "s3" {
        bucket = "my-bucket"
        key    = "us-west-2/development/networking/vpc/terraform.tfstate"
        region = "us-east-1"
    }
}

module "vpc" {
    source = "github.com/kurron/terraform-aws-vpc"
    region  = "us-west-2"
    <snip>
}

output "vpc_id" {
    value = "${module.vpc.vpc_id}"
}
<snip>
```
I must admit that I find it inconvenient to have to re-export the outputs from the imported module, but at least it works.
