### ISSUE TITLE
aws_security_group: Unsupported IP protocol "all" 

### ISSUE THREAD

**Issue by magnetik** [terraform-providers/terraform-provider-aws#1793]
Hi there,

### Terraform Version
Terraform v0.10.6 & provider 1.0.0

### Affected Resource(s)
- aws_security_group
- aws_security_group_rule

### Terraform Configuration Files
```hcl
resource "aws_security_group" "a-security-group" {
  name = "a-security-group"
  description = "Security group"
  ingress {
    from_port = 0
    to_port = 0
    protocol = "all"
    cidr_blocks = [
      "8.8.8.8"
    ]
  }
}
```

### Expected Behavior
As stated in the documentation, "all" is a valid value, so a security group should be created.

### Actual Behavior
Error : 

> Error authorizing security group ingress rules: InvalidParameterValue: Invalid value 'all' for IP protocol. Unknown protocol.

### Steps to Reproduce
1. `terraform plan`
1. `terraform apply`

**Comment by bbernays** [comment]
The documentation says that all is not a valid option for protocol.
If you want to use all you should use "-1"

Check out the documentation for more information

https://www.terraform.io/docs/providers/aws/r/security_group.html

**Comment by koooge** [comment]
#1661

**Comment by magnetik** [comment]
True, closing this as it's better explained there.
