### ISSUE TITLE
Manually entered IPv6 CIDR fails to validate in Security Group inline rule during `terraform plan`

### ISSUE THREAD

**Issue by jayed** [terraform-providers/terraform-provider-aws#1804]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- aws_security_group_rule

### Terraform Configuration Files
```hcl
variable "ipv6_digital_ocean" {
  type    = "list"
  default = ["2604:a880:800:a1::1774:5001/64"]
}

resource "aws_security_group" "default_private" {
  name        = "default-private"
  description = "default private subnets"
}

resource "aws_security_group_rule" "all_ingress_private" {
  security_group_id = "${aws_security_group.default_private.id}"
  type              = "ingress"
  from_port         = "0"
  to_port           = "0"
  protocol          = "-1"
  cidr_blocks       = ["10.100.0.0/16"]
  ipv6_cidr_blocks  = ["${var.ipv6_digital_ocean[0]}"]
}
```

### Debug Output
https://gist.github.com/jayed/882cca4bc71af5d681882c89a316d3e3

### Expected Behavior
The IPv6 CIDR should validate.

### Actual Behavior
* aws_security_group_rule.all_ingress_private: "ipv6_cidr_blocks.0" must contain a valid network CIDR, got "2604:a880:800:a1::1774:5001/64"

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
I looked into the aws provider code and found that [`validators.go`](https://github.com/terraform-providers/terraform-provider-aws/blob/f4b158ca67069ae395dd5d8c574ba4414361dcac/aws/validators.go#L426) uses Go's `net.ParseCIDR()` function. so I wrote a small program to test parsing my IPv6 block. 

```go
package main

import (
    "fmt"
    "net"
)

func main() {
    ipv6 := "2604:a880:800:a1::1774:5001/64"
    ip, ipnet, err := net.ParseCIDR(ipv6)
    if err != nil {
        fmt.Println("Error", ipv6, err)
    }
    fmt.Println(ipv6, " -> ip:", ip, " net:", ipnet)
}
```

The output is:
```
[jayed@cabernet /tmp]$ ./parse_ipv6
2604:a880:800:a1::1774:5001/64  -> ip: 2604:a880:800:a1::1774:5001  net: 2604:a880:800:a1::/64
```

The ipv6 cidr block appears to be valid...or at least parseable by the Go standard library. I admit I don't know much about Go or IPv6.

**Comment by jayed** [comment]
Oh! I did try it as a list variable, a string variable, and a raw string. Same results each time.

**Comment by remyje** [comment]
I am seeing this same issue.

**Comment by remyje** [comment]
I'm new to Go, but I think there are at least two problems happening in `validateCIDRNetworkAddress` here:

`
	if ipnet == nil || value != ipnet.String() {
`
So far, I've found two cases where this fails:

If the IPv6 CIDR is a network address and any of the hex digits are capitalized, such as `2001:DB8::/32` the string will be `2001:db8::/32` and so it will fail.

If the IPv6 CIDR is a host address, it fails because `value` (the IP) and `ipnet.String()` (the Network) will never match and aren't supposed to.  For IPv4 this is acceptable (in the context of Terraform) but CIDR notation for a IPv6 host address is valid.

**Comment by mskucherawy** [comment]
I may be mistaken but this seems to have reappeared in 0.11.8.  I'm unable to use "2620:010d:c080::/41" in the same resource as the original post.

The patch referenced as the fix seems not to be present in aws/validators.go on trunk at least.

**Comment by mskucherawy** [comment]
Actually I just discovered that the issue is the leading zero in the second octet group.  It's dropped by the parser, and since the string has therefore changed, Terraform considers it invalid.  Not quite the same as the original problem.
