### ISSUE TITLE
aws_db_event_subscription wont allow "all instances" and event categories without source_ids

### ISSUE THREAD

**Issue by KevinBrooke** [terraform-providers/terraform-provider-aws#1817]
### Terraform Version
0.10.7

### Affected Resource(s)
- aws_db_event_subscription

### Terraform Configuration Files
```hcl
resource "aws_db_event_subscription" "default" {
  name      = "RDS-events-${var.env}"
  sns_topic = "${aws_sns_topic.ops_notifications.arn}"
  source_type = "db-instance"
  event_categories = [
    "availability",
    "deletion",
    "failover",
    "failure",
    "low storage",
    "read replica",
    "recovery",
    "restoration",
  ]
  tags = "${var.tags}"
}
```

### Debug Output
Error applying plan:
1 error(s) occurred:
* aws_db_event_subscription.default: 1 error(s) occurred:
* aws_db_event_subscription.default: Modifying RDS Event Subscription RDS-events-prod failed: InvalidParameterCombination: If SourceType is null, Categories must also be null.
        status code: 400, request id: dadc1371-a9b5-11e7-887f-53dabc075f79

### Expected Behavior
Create an RDS event subscription for all db_instances but only for the specified categories.

### Actual Behavior
Failed -  "If SourceType is null, Categories must also be null."

### Steps to Reproduce
1. `terraform apply`

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
