### ISSUE TITLE
Question: Difference between aws_emr_instance_group and intance_group attribute within aws_emr_cluster

### ISSUE THREAD

**Issue by pradeepbhadani** [terraform-providers/terraform-provider-aws#1823]
Hi there,

Can someone provide more details on the difference between aws_emr_instance_group resource and intance_group attribute within aws_emr_cluster?

`aws_emr_instance_group` requires a cluster ID to attach to which means it can be attached to existing EMR cluster. And `aws_emr_cluster` already provides `instance_group` attribute. So what's the real use of `aws_emr_instance_group` resource?

Thanks

**Comment by Ninir** [comment]
Hi @pradeepbhadani 

As far as I checked, `aws_emr_instance_group` was renamed from `aws_emr_task_group` ([source](https://github.com/hashicorp/terraform/commit/dad6face2bd8dfcdff4f41b1edb0fed063655d17#diff-7ab4a6646303442332b8f110a8588c14)).

Those look the same: one has more attributes (computed), the other has an option to specify a bid price! 😄 

It could be an idea to refactor and mutualise this! 🚀

**Comment by DimDroll** [comment]
Would it make sense to add "instance_role" attribute to "aws_emr_instance_group" resource?
It would allow us to define groups in separate from cluster resource.

**Comment by nywilken** [comment]
Folks thanks for kicking off this discussion and apologies for any confusion around the separate resources for managing the EMR cluster instance groups. A new enhancement issue #7931 has been created to address this question and begin moving towards the use of `aws_emr_instance_group` for managing instance groups separately from the `aws_emr_cluster` resource. Please feel free to track and upvote that issue. 

In the meantime, I am going to close this issue. But if you feel that it should remain open please feel free to add a comment and I will gladly reopen.
