### ISSUE TITLE
Support roles through ~/.aws/config

### ISSUE THREAD

**Issue by cornfeedhobo** [terraform-providers/terraform-provider-aws#1834]
Hi there,

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- aws provider

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "us-east-1"
  profile = "account_i_get_access_to_through_a_role"
}
```

### Expected Behavior
A valid connection is created.

### Actual Behavior
`module.us_east_1.provider.aws: No valid credential sources found for AWS Provider.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Follow the [cli guide for assuming roles](http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html)
2. Set terraform to use the name you gave the profile
3. `terraform plan`

### Important Factoids
I think this is possible using the AWS SDK's "SharedCredentials" feature, but I haven't attempted anything to verify that.

Update: I think this is because the way the ChainProvider is resolved before a "Session" is attempted, which is where this would then succeed. I'll try and find time to mock something up to verify.

**Comment by ekini** [comment]
Clone of #1184

**Comment by cornfeedhobo** [comment]
Also tracking hashicorp/terraform#11734
