### ISSUE TITLE
aws_route thinks route_table_id is a modifyable resource - its not

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#1841]
Terraform 0.9.8

This is super important, as terraform basically leaves routes hanging around which completely screws with your networking setup. 

1. Set up an aws_route, with a route_table_id
2. Terraform it.
3. Now change the route to be a different route_table_id

A plan now makes this a modify step (~) - it should be a destroy and create step (-/+)

An apply will error saying it could not find the old routes, (its looking for them on the wrong wroute table), and will then remove them from the state file(!!!!) - the next plan/apply will just apply them on the new route table, leaving the old routes behind on the old route table... this will break your entire networking model and potentially the security of your networks. 

Really hope its been fixed since terraform 0.9.8 but havent had the chance to test yet - screwing up your networking is a pretty horrible thing for terraform to do!

If you're wondering why the route table might change, its because it may well come from a data source, and you've decided to change the VPC peering from A=>B, to A=>C - which is a common thing to do in e.g. blue-green type deployments

**Comment by bflad** [comment]
The fix for this has been merged into master and will release with version 1.25.0 of the AWS provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 1.25.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1250-june-27-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
