### ISSUE TITLE
alb_target_group doesn't report name conflict, instead returns already existing group

### ISSUE THREAD

**Issue by blckct** [terraform-providers/terraform-provider-aws#1842]
### Terraform Version
0.10.7

### Affected Resource(s)
- aws_alb_target_group

### Terraform Configuration Files
```hcl
resource "aws_alb_target_group" "foo" {
  port = 80
  protocol = "HTTP"
  vpc_id = "${data.aws_vpc.qux.id}"
  name = "test"
}

resource "aws_alb_target_group" "bar" {
  port = 80
  protocol = "HTTP"
  vpc_id = "${data.aws_vpc.qux.id}"
  name = "test"
}
```

### Expected Behavior
Terraform should report it can't create the resource because one with the same name already exists

### Actual Behavior
Terraform imports existing group into the resource causing unforseen issues.

**Comment by Ninir** [comment]
Hi @blckct 

So I just played a bit with this, and indeed it should be saying that the name already exists. However, AWS is not doing it when calling the API as far as I checked.

To be sure, I checked using the CLI with:

    $ aws elbv2 create-target-group  --name test --protocol HTTP --port 80 --vpc-id MY_VPC

When done more than once, it always return success, even though there is only one target group in the UI.

Thanks for letting us know though!

**Comment by Ninir** [comment]
#### Note for contributors:
I reached with AWS on that. Keeping this one opened since we should also handle it from a code POV:

```go
	resp, err := elbconn.CreateTargetGroup(params)
	if err != nil {
                # check for the the `DuplicateTargetGroupName` awsErr here
		return errwrap.Wrapf("Error creating LB Target Group: {{err}}", err)
	}
```

**Comment by blckct** [comment]
Yes, I know it's an API thing, I think I've seem the same behavior with cloudwatch alarams and some other places but this case is most troublesome of them.

**Comment by Ninir** [comment]
I got an answer from AWS about this. The [Elastic Load Balancing API is idempotent](http://docs.aws.amazon.com/cli/latest/reference/elbv2/index.html), meaning:

> All Elastic Load Balancing operations are idempotent, which means that they complete at most one time. If you repeat an operation, it succeeds.

Thus, an `DuplicateTargetGroupName` error would be thrown If we changed the protocol, port, or VPC, as in:
 
    $ aws elbv2 create-target-group --name test --protocol HTTP --port 80 --vpc-id VPC_ID 
    $ aws elbv2 create-target-group --name test --protocol HTTPS --port 80 --vpc-id VPC_ID 
    An error occurred (DuplicateTargetGroupName) when calling the CreateTargetGroup operation: A target group with the same name test exists, but with different settings

So I think this is something we can not deal with, unfortunately.

**Comment by blckct** [comment]
How about checking if it exists before creating it? Or adding a warning to the manual page?

**Comment by Ninir** [comment]
A warning would potentially be better. Adding custom logic prevents to have a global and similar behavior for every resources. This can even bring edge cases and more issues, so let's stick to the normal logic by adding a warning, what do you think? :)

**Comment by blckct** [comment]
If it's all that can be done, sure, a warning and/or a suggestion to use name_prefix instead of name.
