### ISSUE TITLE
Add support for Amazon side private ASN for aws_vpn_gateway

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#1859]
Add support for Amazon side private ASN for Virtual Private Gateways, [announced](https://aws.amazon.com/about-aws/whats-new/2017/10/now-you-can-configure-amazon-side-private-autonomous-system-number-for-your-virtual-private-gateway/) 10/10/2017.

**Comment by ewbankkit** [comment]
Need to modify
* `aws_vpn_gateway` [data source](https://www.terraform.io/docs/providers/aws/d/vpn_gateway.html)
* `aws_vpn_gateway` [resource](https://www.terraform.io/docs/providers/aws/r/vpn_gateway.html)

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
