### ISSUE TITLE
aws_elb resources export a DNS name that makes route53 change every apply

### ISSUE THREAD

**Issue by sysadmin1139** [terraform-providers/terraform-provider-aws#1865]
After investigation through #241 I've discovered where some of our continual applies come from.

This is with version 1.0 of the provider, though we've been seeing it as far back as Terraform 8.

```
  ~ aws_route53_record.ex-web-b
      alias.1871597309.evaluate_target_health:    "" => "true"
      alias.1871597309.name:                      "" => "lb-prod-web-ex-[redacted1].us-east-1.elb.amazonaws.com"
      alias.1871597309.zone_id:                   "" => "[redacted2]"
      alias.759637084.evaluate_target_health:     "true" => "false"
      alias.759637084.name:                       "lb-prod-web-ex-[redacted1].us-east-1.elb.amazonaws.com." => ""
      alias.759637084.zone_id:                    "[redacted3]" => ""
```
The from part of the diff has a trailing dot it, but the to part does not. Also, the zone-ids are different. This record is created from a resource like:

```
  alias {
    name = "${aws_elb.prod-web-ex.dns_name}"
    zone_id = "${aws_elb.prod-web-ex.zone_id}"
    evaluate_target_health = true
  }
```

This makes it seem like the elb resource is exporting a `dns_name` and `zone_id` that is always different than the data found in a Route53 record.

We've noticed that `aws_alb` resources don't do this for some reason.

**Comment by bflad** [comment]
@sysadmin1139 is this an issue still in recent versions of the AWS provider? 

For the trailing dot issue, we can probably augment the `DiffSuppressFunc` for the alias name (added in #3119) to also allow it to suppress if both entries with `strings.TrimSuffix()` match.

As for the zone ID issue, does using the ELB hosted zone ID available via the [`aws_elb_hosted_zone_id` data source](https://www.terraform.io/docs/providers/aws/d/elb_hosted_zone_id.html)) work better?

**Comment by spatrik** [comment]
I also had this problem when running version 1.12.0 of the AWS provider after upgrading från 0.1. Using the data source as you suggest works for me.

**Comment by sysadmin1139** [comment]
@bflad Just checked, that using that particular data source definitely works better. These diffs are so much cleaner now. With provider version 1.13.0 in, we're not getting the originally reported behavior either. So this looks fixed!
