### ISSUE TITLE
EFS encrypted is not recognized

### ISSUE THREAD

**Issue by assertnotnull** [terraform-providers/terraform-provider-aws#1886]
### Terraform Version
0.10.7

### Terraform Configuration Files
```hcl
resource "aws_efs_file_system" "salt_states" {
  creation_token = "salt-states"
  encrypted = true
  tags {
    Name = "SaltStates"
  }
}

resource "aws_efs_mount_target" "salt_states_mount" {
  file_system_id = "${aws_efs_file_system.salt_states.id}"
  count = 2
  subnet_id = "${element(var.subnets, count.index)}"
}

variable "subnets" {
  type = "list"
  default = [
    "subnet-#####1",
    "subnet-#####2"
  ]
}
```

### Expected Behavior
What should have happened?
Accept the encrypted key as per the documentation

### Actual Behavior
What actually happened?
Errors:

  * aws_efs_file_system.salt_states: : invalid or unknown key: encrypted

### Steps to Reproduce
1. `terraform init`
2. `terraform validate`

**Comment by abinashmeher999** [comment]
@assertnotnull What is the terraform-provider-aws plugin version number? The `encrypted` argument came with version 1.0.0. The plugin version can be found inside `.terraform/plugins/<os_architecture>`. The folder `.terraform` should be at the root of your terraform project where you did an init. Mine shows `terraform-provider-aws_v1.0.0_x4`.

**Comment by assertnotnull** [comment]
@abinashmeher999 I've looked up and it was 0.1.4. I've deleted the plugin folder and it works thank you!
