### ISSUE TITLE
aws_ssm_association Nested Parameter Arguments Validation Issue

### ISSUE THREAD

**Issue by braxtone** [terraform-providers/terraform-provider-aws#1889]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
aws_ssm_association

#### Broken script
```hcl
resource "aws_ssm_association" "install_rsat" {
  name = "AWS-RunPowerShellScript"
  targets = {
    key = "tag:host_type"
    values = ["type_of_hosts"]
  }

  parameters {
    command = [
      "Import-Module Servermanager",
      "Add-WindowsFeature RSAT-Role-Tools -IncludeAllSubFeature -Restart"
    ]
  }
}
```

#### Workaround
Shove the command into a one-liner and remove nested list from command key.

```hcl
resource "aws_ssm_association" "install_rsat" {
  name = "AWS-RunPowerShellScript"
  targets = {
    key = "tag:host_type"
    values = ["type_of_hosts"]
  }

  parameters {
    command = "Import-Module Servermanager -and Add-WindowsFeature RSAT-Role-Tools -IncludeAllSubFeature -Restart"
  }
}
```
### Debug Output
Will submit if needed, error message is:
```bash
$ terraform validate
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * module.ad_environment.aws_ssm_association.install_rsat: parameters (command): '' expected type 'string', got unconvertible type '[]interface {}'
```

### Panic Output
N/A

### Expected Behavior
The parameters[command] key should have taken an array of commands to run without erroring out.

### Actual Behavior
The validation responded with an error saying the expected variable type was a string, and not a list which the AWS API supports.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create terraform association resource like so:
```hcl
resource "aws_ssm_association" "install_rsat" {
  name = "AWS-RunPowerShellScript"
  targets = {
    key = "tag:host_type"
    values = ["type_of_hosts"]
  }

  parameters {
    command = "Import-Module Servermanager -and Add-WindowsFeature RSAT-Role-Tools -IncludeAllSubFeature -Restart"
  }
}
```

2. `terraform validate`

### Important Factoids
N/A

### References
It looks like someone else found this issue: https://github.com/mujina/SSM-Spike/blob/3405cbc9534c7056dcdd4753bf0408839dea84a3/terraform/main.tf#L152

**Comment by bflad** [comment]
Hi @braxtone 👋 Thank you for submitting this feature request.

There are a few things that would be getting in the way of implementation here:

* The Terraform Provider SDK currently only supports a single "simple" value type (e.g. floats, integers, strings) within a map. This restriction will likely be removed in the future but this is at least a few months out and will require the Terraform AWS Provider to only support Terraform 0.12 and later
* Even with the above implementation, the changing of the input will likely require operators to perform a configuration change to a separate argument

Given the complexity we have seen with similar changes in the past and the lack of upvotes on this issue, we are going to opt to close this for now, but please feel free to continue submitting feature requests!

For what it worth, Terraform 0.12 now reports this error a little friendlier:

```hcl
terraform {
  required_providers {
    aws = "2.20.0"
  }
  required_version = "0.12.5"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_ssm_association" "install_rsat" {
  name = "AWS-RunPowerShellScript"

  targets {
    key    = "tag:host_type"
    values = ["type_of_hosts"]
  }

  parameters = {
    command = [
      "Import-Module Servermanager",
      "Add-WindowsFeature RSAT-Role-Tools -IncludeAllSubFeature -Restart"
    ]
  }
}
```

Outputs:

```
$ terraform apply

Error: Incorrect attribute value type

  on main.tf line 20, in resource "aws_ssm_association" "install_rsat":
  20:   parameters = {

Inappropriate value for attribute "parameters": element "command": string
required.
```

**Comment by jfcantu** [comment]
Looks like I just barely missed the boat on this one to comment before it closed, but I'd like to add my support.

The workaround in the original post works for certain SSM documents like `AWS-RunPowerShellScript` where there's a way to accomplish what you need to do with a single string - it doesn't work for documents where AWS specifically requires that each parameter be a separate string. (In my case, I'm trying to pass DNS server IP addresses to the `AWS-JoinDirectoryServiceDomain` document, and there's no way to pass multiple IP addresses because you can only pass one string, and the string can only contain one IP.)

**Comment by braxtone** [comment]
Thanks for the update @bflad . While I'm a bit bummed to see this untouched and closed out after two years, I understand the complexity/benefit trade off and don't have an immediate need for this fix currently. Hopefully this shows up in search results and helps others, and is useful groundwork for the option you mentioned in the first roadmap workaround. Thanks for taking a look!

**Comment by ohmer** [comment]
Hi,

I agree that this is very crippling. If you have a non-string type to pass to an SSM document, you're screwed. 

```
resource "aws_directory_service_directory" "managed_ad" {
  name     = "example.com"
  password = "********"
  type     = "MicrosoftAD"
  edition  = "Standard"

  vpc_settings {
    vpc_id     = local.vpc_id
    subnet_ids = [local.subnet_a_id, local.subnet_b_id]
  }
}

resource "aws_ssm_association" "network_policy_servers_domain_join" {
  name             = "AWS-JoinDirectoryServiceDomain"
  association_name = "JoinDirectoryServiceDomain"

  parameters = {
    directoryId    = aws_directory_service_directory.managed_ad.id
    directoryName  = aws_directory_service_directory.managed_ad.name
    dnsIpAddresses = aws_directory_service_directory.managed_ad.dns_ip_addresses
  }

  targets {
    key    = "tag:aws:autoscaling:groupName"
    values = [aws_autoscaling_group.network_policy_servers.name]
  }
}
```

results in:
```
Error: Incorrect attribute value type

  on main.tf line 168, in resource "aws_ssm_association" "network_policy_servers_domain_join":
 168:   parameters = {

Inappropriate value for attribute "parameters": element "dnsIpAddresses":
string required.
```

I would love to see this backward incompatible change happening.
