### ISSUE TITLE
aws ses create-template 

### ISSUE THREAD

**Issue by lucidprogrammer** [terraform-providers/terraform-provider-aws#1921]
I was wondering if there is an implementation for "aws ses create-template"

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-personalized-email-api.html

**Comment by bflad** [comment]
I don't think this is supported yet. For reference, these are the Go AWS SDK docs: https://docs.aws.amazon.com/sdk-for-go/api/service/ses/#SES.CreateTemplate

**Comment by bflad** [comment]
I'll try to get a new resource submitted this weekend.

**Comment by bflad** [comment]
PR submitted: #2003

**Comment by lucidprogrammer** [comment]
@bflad tks for the quick response
