### ISSUE TITLE
failure to create aws_lb network load balancer resource

### ISSUE THREAD

**Issue by drnomolos42** [terraform-providers/terraform-provider-aws#1946]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
esolomon@olmint ~/github/onelogin-terraform-general/prod/haproxy $ terraform -v
Terraform v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lb

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_lb" "primary-nlb-3-subnets" {
  name                  = "primary-nlb"
  count                 = "${length(data.terraform_remote_state.vpc.vpc_subnets_pub) == 3 ? 1: 0}"
  internal              = false
  load_balancer_type    = "network"
  subnet_mapping {
    subnet_id = "${data.terraform_remote_state.vpc.vpc_subnets_pub[0]}"
    allocation_id = "${var.allocation_ids[0]}"
  }
  subnet_mapping {
    subnet_id = "${data.terraform_remote_state.vpc.vpc_subnets_pub[1]}"
    allocation_id = "${var.allocation_ids[1]}"
  }
  subnet_mapping {
    subnet_id = "${data.terraform_remote_state.vpc.vpc_subnets_pub[2]}"
    allocation_id = "${var.allocation_ids[2]}"
  }
}

```

### Debug Output
none

### Panic Output
none
### Expected Behavior

creating Network Load Balancer

### Actual Behavior
Resource never gets created. I've waited up to 20 minutes to see if it completes.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply tf.plan`

### Important Factoids
I've tried this in several AWS regions with the same behavior. The `count` conditional is a little hacky but necessary since we have a region with only two subnets active.

**Comment by drnomolos42** [comment]
likely it's same issue reported in a comment in https://github.com/terraform-providers/terraform-provider-aws/issues/1912 - using a subnet_mapping causes creation to hang indefinitely.

**Comment by radeksimko** [comment]
This was addressed in https://github.com/terraform-providers/terraform-provider-aws/pull/1956 which was merged and will be available in the next release.
