### ISSUE TITLE
Support switching VPC tenancy from Dedicated to Default

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#1955]
[Recently announced](https://aws.amazon.com/about-aws/whats-new/2017/10/switch-the-tenancy-of-your-vpc-from-dedicated-to-default-instantly/) ability to change the [`instance_tenancy`](https://www.terraform.io/docs/providers/aws/r/vpc.html#instance_tenancy) of an AWS VPC from `dedicated` to `default`.
Add support in Terraform.

**Comment by ewbankkit** [comment]
This isn't just as "simple" as removing `ForceNew: true` from the attribute's schema and handling the value change in `resourceAwsVpcUpdate()` as other changes to the attribute's value DO still force the resource to be recreated.
Looking for some other resource attribute that has similar behaviour or maybe we have to have a `SchemaForceNewFunc`???

**Comment by ewbankkit** [comment]
My guess is that https://github.com/hashicorp/terraform/pull/14887 should be the solution to the `ForceNew` issue. Some more research required...

**Comment by ewbankkit** [comment]
Yes, a `CustomizeDiff` function is what is required.

**Comment by bflad** [comment]
Support for this has been added via #2514 and will release with version 1.25.0 of the AWS provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 1.25.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1250-june-27-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
