### ISSUE TITLE
AWS missing "pseudo" parameters

### ISSUE THREAD

**Issue by rbirkby** [terraform-providers/terraform-provider-aws#1960]
Terraform v0.10.7

data_source_aws_partition.go implements the aws "partition" pseudo parameters. However, other pseudo parameters are missing. For example, URLSuffix - which is correlated to the partition - is not available within terraform.

For details of this and other pseudo parameters, see the [CloudFormation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-urlsuffix) documentation

**Comment by lorengordon** [comment]
There are already data sources to get the partition, the current region, and the account ID. URL Suffix is missing. The remaining pseudo parameters appear to be related specifically to CloudFormation and the stack in question.

I can take a stab at implementing an equivalent of URLSuffix. Would it be preferable as a new data source, or a new attribute of `data_source_aws_partition`?

**Comment by lorengordon** [comment]
Heh, so, slightly annoying. I'm not finding an API call that returns the URL Suffix. And CloudFormation isn't open source, so can't really see how they do it. Can maybe parse it out of an endpoint, but _which_ endpoint?

Looking at the other related data sources for inspiration...

* `data_source_aws_partition` gets the partition from the AWSClient struct, which is setup in config.go, where a few different methods are used to determine the partition
* `data_source_aws_caller_identity` gets the account_id from an API call to `sts.GetCallerIdentity()` (even though `accountid` is an attribute in the AWSClient struct? odd...)
* `data_source_aws_region` gets the current region from the AWSClient struct, which gets it from the Config struct, which gets it from the provider

**Comment by lorengordon** [comment]
Alright, got a first stab done, see https://github.com/terraform-providers/terraform-provider-aws/pull/5602.

**Comment by bflad** [comment]
Support for a new `dns_suffix` attribute in the `aws_partition` data source has been merged and will release with version 2.23.0 of the Terraform AWS Provider in the next day or two. Thanks to @lorengordon for the implementation. 👍
