### ISSUE TITLE
AWS provider cannot connect bind.  Perhaps because of corporate proxy

### ISSUE THREAD

**Issue by cfromm1911** [terraform-providers/terraform-provider-aws#1964]
Terraform appears to honor http_proxy and https_proxy environment variables, as provider downloads occur without issue.  However, terraform-provider-aws does not appear to honor them, as the provider crashes.  

The error seen in debug is "[ERR] plugin: plugin init: Couldn't bind plugin TCP listen"

I can't determine any other reason for the error.  Is this the case?

**Comment by theslloyd** [comment]
Experiencing a similar issue on a Windows VM. @cfromm1911 do you know what has been done to resolve this?

**Comment by cfromm1911** [comment]
My issue was in Bash for Windows and had an issue with the socket used by Terraform.  This has been resolved in later version of Bash for Windows.
