### ISSUE TITLE
Is there any documentation/implementation for aws ses create-template

### ISSUE THREAD

**Issue by AjayKumarJ** [terraform-providers/terraform-provider-aws#1981]
I am getting an following error in aws cli:
aws: error: argument operation: Invalid choice, valid choices are

I am following the link http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-personalized-email-api.html

**Comment by bflad** [comment]
I think this is a duplicate of #1921

**Comment by bflad** [comment]
PR submitted: #2003
