### ISSUE TITLE
Terraform should keep ec2 instance original state after type change

### ISSUE THREAD

**Issue by pszczekutowicz** [terraform-providers/terraform-provider-aws#1998]
When instance type is changed and terraform provisioning is performed on stopped ec2 instance after type change instance state is not preserved and instance is running.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
aws_instance

### Expected Behavior
When instance_type is changed on stopped machine it should not start after change.

### Actual Behavior
When instance_type is changed on stopped machine instance is started after change.

### Steps to Reproduce
1. create ec2 instance with type t2.nano using terraform 
2. stop instance manually or using aws cli 
3. change instance type to t2.micro using terraform
4. instance state is running

**Comment by bflad** [comment]
Relatedly, you may want to see this PR to implement stopped instance state handling: #1980

**Comment by artburkart** [comment]
I believe my PR would already already address this.
