### ISSUE TITLE
Major Bug - Apply any IAM policy to a role -> detaches IAM policy from ALL Roles in Account

### ISSUE THREAD

**Issue by tburt11** [terraform-providers/terraform-provider-aws#2014]
Hi there,

CRITICAL BUG - CHANGES EXISTING NON-TERRAFORM INFRASTRUCTURE.

This bug impacts ALL ROLES in the AWS account and removes policies without warning.  Most importantly, Roles that are unrelated, and Roles that are not terraformed are impacted.

_**UPDATE:**_
This bug also affects ANY terraform iam policies attached to more than one role.
1) run a plan that creates a policy and attaches to instance role.
2) run another plan that attaches the same policy to another instance role.
3) remove the policy from second plan and run terraform apply.
4) See that policy has been detached from the initial instance. (policy is not deleted)
Policy was attached to 2 instances.  Now attached to 0 instances.

### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
 - AWS Roles external to the Terraform Plan

### Terraform Configuration Files
```hcl
resource "aws_iam_policy_attachment" "readonly" {
  name                  = "${format("tf-%s-%s-%s", var.xxx_env, var.xxx_app, var.xxx_role)}"
  roles                 = ["${aws_iam_role.primary.name}"]
  policy_arn            = "arn:aws:iam::aws:policy/ReadOnlyAccess"
}

resource "aws_iam_policy_attachment" "lambda" {
  name                  = "${format("tf-%s-%s-%s", var.xxx_env, var.xxx_app, var.xxx_role)}"
  roles                 = ["${aws_iam_role.primary.name}"]
  policy_arn            = "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
}
```

### Expected Behavior
AWS canned policies should be attached to the role in the plan.
All other Roles in the Account should be unaffected.

### Actual Behavior
AWS canned policies **_are_** attached to the correct Role.
ALL OTHER ROLES IN THE ACCOUNT HAVE THIS POLICY DETACHED. 

### Steps to Reproduce
Create a plan that attaches the AWS canned policies above.
Create an instance and a Role by hand that includes the above canned policies in the Role.
Run the plan and create a new instance.  Note that the attached Role has the AWS canned policies.
View the Role that was created by hand and note that the AWS canned policies have been removed.

### Important Factoids
We have started to use Terraform in our infrastructure which is 98% not terraformed.
Running a Terraform Plan has affected every instance in our infrastructure, without warning, removing the ability to access AWS resources account wide.

**Comment by Jamie-BitFlight** [comment]
I'm having this issue too. 
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_iam_policy_attachment.ecs_autoscale_role_attach
      roles.2108517103: "ecsAutoscaleRole-qa" => ""
      roles.623758744:  "" => "ecsAutoscaleRole-dev"


Plan: 0 to add, 1 to change, 0 to destroy.

```

**Comment by Jamie-BitFlight** [comment]
Have a look at this https://github.com/terraform-providers/terraform-provider-aws/issues/1966
It explains that we were using the terraform resource wrong, and shows the right way.

**Comment by bflad** [comment]
For those finding this old issue which I'm going to close out now, we updated the resource documentation to very obviously display a big red warning message at the top. https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html

> WARNING: The aws_iam_policy_attachment resource creates exclusive attachments of IAM policies. Across the entire AWS account, all of the users/roles/groups to which a single policy is attached must be declared by a single aws_iam_policy_attachment resource. This means that even any users/roles/groups that have the attached policy via some mechanism other than Terraform will have that attached policy revoked by Terraform. Consider aws_iam_role_policy_attachment, aws_iam_user_policy_attachment, or aws_iam_group_policy_attachment instead. These resources do not enforce exclusive attachment of an IAM policy.

In almost all cases we tend to highly recommend using the separate [`aws_iam_group_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_group_policy_attachment.html), [`aws_iam_role_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_role_policy_attachment.html), and [`aws_iam_user_policy_attachment`](https://www.terraform.io/docs/providers/aws/r/iam_user_policy_attachment.html) resources.
