### ISSUE TITLE
Feature Request: Support for aws_rds_cluster or aws_db_cluster as a datasrouce

### ISSUE THREAD

**Issue by DougSven** [terraform-providers/terraform-provider-aws#2019]
Hi there,

I would like to request an additional datasource. It would be useful to have access to RDS Cluster data as a datasource. Simple use case is provisioning `aws_route53_record` using the `aws_rds_cluster.endpoint` or `aws_rds_cluster.reader_endpoint` outside of the scope in which the cluster is created.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
aws_rds_cluster

### Terraform Configuration Files
Projected Usage Example:
```hcl
data "aws_vpc" "selected" {
  tags {
      Name = "${var.vpc_name}"
  }
}

data "aws_route53_zone" "selected" {
  name         = "${var.zone_name}"
  vpc_id       = "${data.aws_vpc.selected.id}"
  private_zone = true
}

data "aws_db_cluster" "selected" {
  cluster_identifier = "${var.cluster_identifier}"
}

resource "aws_route53_record" "db_replica" {
  zone_id = "${data.aws_route53_zone.selected.zone_id}"
  name    = "${var.db_cname}"
  type    = "CNAME"
  ttl     = 300
  records = ["${data.aws_db_cluster.selected.reader_endpoint}"]
}
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
NA

### Actual Behavior
NA

### Steps to Reproduce
NA

### Important Factoids
NA

### References
NA

**Comment by bflad** [comment]
I will have a PR for this shortly.

**Comment by bflad** [comment]
PR submitted: #2070
