### ISSUE TITLE
Cycle when using template

### ISSUE THREAD

**Issue by joudaon** [terraform-providers/terraform-provider-aws#2035]
Hello I am using Terraform v0.10.7 with AWS Provider.

The affected resources are **resource "aws_instance" "frontal"** and **"data "template_file" "script"** 

```
resource "aws_instance" "frontal" {
  count                  = "${length(split(",", lookup(var.machine, "machinename")))}"
  ami                    = "ami-785db401"
  instance_type          = "t2.micro"
  vpc_security_group_ids = ["${var.securityGroup}"]
  key_name               = "${aws_key_pair.mykey.key_name}"

  user_data              = "${element(data.template_file.script.*.rendered, count.index)}"

  tags {
    Name = "${element(split(",", lookup(var.machine, "machinename")), count.index)}"
  }
  connection {
    user        = "${element(split(",", lookup(var.machine, "machinename")), count.index)}"
    private_key = "${file("${lookup(var.keys, "privateKey")}")}"
  }
}

data "template_file" "script" {
  count    = "${length(split(",", lookup(var.machine, "machinename")))}"
  template = "${file("${path.module}/cloudInit/${element(split(",", lookup(var.machine, "template")), count.index)}.tpl")}"

  vars {
    salt-master = "${aws_instance.frontal.0.private_ip}"
  }
}
```

I want to pass the privateIP of frontal1 aws_instance but the template is also declared in in aws_instance so I guess that´s why cycle is mentioned. This is the error:

> Error asking for user input: 1 error(s) occurred:
> * Cycle: module.machines.data.template_file.script, module.machines.aws_instance.frontal

But I need to make it work this way. 

The code can be checked here:

https://github.com/joudaon/terraform.git

Inside this go to terraform-salt folder. 

Note that ssh-keygen -f is neede to create keys.

Thank you.

**Comment by paddycarver** [comment]
Hi! Unfortunately, this is not a thing you can do: the IP isn't allocated until the server is created, and the server can't be created until the template is created. So if the template can't be created until the IP is allocated, we've got a bit of a catch-22 here. One option may to be use the [metadata server](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval) in your user_data script to retrieve the IP address as part of the startup of the instance.

**Comment by bflad** [comment]
Closing as this is not possible as described.
