### ISSUE TITLE
Feature Request - ARN attribute exported for aws_ssm_parameter resource and data source

### ISSUE THREAD

**Issue by ncraike** [terraform-providers/terraform-provider-aws#2041]
### Terraform Version

```
$ terraform -v
Terraform v0.10.7
```

### Affected Resource(s)
- aws_ssm_parameter resource
- aws_ssm_parameter data source

### Feature request
It would be useful for the `aws_ssm_parameter` resources and data sources to export an `arn` attribute for the created/selected SSM parameter.

ARNs are useful to reference the AWS resource [in IAM policies](http://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html), and if you're creating SSM parameters (eg to securely store sensitive data), it's likely you're also using IAM policies to limit access to the parameters by specific EC2 instances using IAM roles.

I'm aware that ARNs can be constructed manually from the account ID, region and parameter name, but it'd be nice not to have to do this by hand.

**Comment by bflad** [comment]
Personally could use this too. The SSM API doesn't return the ARN directly, but we can manually construct it inside the resource and data source using the connection metadata. I'll submit a PR shortly.

**Comment by bflad** [comment]
PR submitted: #2273
