### ISSUE TITLE
Better document (or better integrate) Vault with AWS provider authentication

### ISSUE THREAD

**Issue by rberlind** [terraform-providers/terraform-provider-aws#2056]
This is a suggested improvement on documentation.

Should the Authentication section of the AWS Provider doc discuss the use of Terraform's Vault Backend together with Vault's AWS Secret Backend as an additional option? It seems to me that this is an important authentication option when using Terraform to provision into AWS.

### Important Factoids
The page in question is: https://www.terraform.io/docs/providers/aws/index.html
The source is at: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/index.html.markdown

Terraform's Vault Backend is described under: https://www.terraform.io/docs/providers/vault/index.html

The Vault AWS Secret Backend is described under: https://www.vaultproject.io/docs/secrets/aws/index.html

**Comment by paultyng** [comment]
Been thinking about this internally, and I think the ideal situation for AWS would be to extend the provider to allow for a `vault` configuration, ie: 

```hcl
provider "aws" {
  vault {
    backend  = "foo"
    role         = "bar"
  }
}
```

This way, the requested Vault creds do not need to be persisted in state and the lease can be short lived. This pattern can be replicated for other providers.
