### ISSUE TITLE
aws_api_gateway_usage_plan rate_limit does not "take" the first time

### ISSUE THREAD

**Issue by kurron** [terraform-providers/terraform-provider-aws#2057]
### Terraform Version
Terraform v0.10.7

### Terraform Configuration Files
```hcl
terraform {
    required_version = ">= 0.10.7"
    backend "s3" {}
}

provider "aws" {
    region = "${var.region}"
}

resource "aws_api_gateway_api_key" "api_key" {
    name = "${var.key_name}"
    description = "${var.key_description}"
    enabled = true
}

resource "aws_api_gateway_usage_plan" "usage_plan" {
    name         = "${var.key_name}"
    description  = "Usage plan specific to the ${var.key_name} API key"
    quota_settings {
        limit  = "${var.quota_limit}"
        period = "${var.quota_period}"
    }
    throttle_settings {
        burst_limit = "${var.burst_limit}"
        rate_limit  = "${var.steady_state_limit}"
    }
    api_stages {
        api_id = "${var.api_gateway_id}"
        stage  = "${var.deployment_stage_name}"
    }
}

resource "aws_api_gateway_usage_plan_key" "usage_plan_key" {
    key_id        = "${aws_api_gateway_api_key.api_key.id}"
    key_type      = "API_KEY"
    usage_plan_id = "${aws_api_gateway_usage_plan.usage_plan.id}"
}
```

### Debug Output
Due to the nature of the reproduction scenario, I've lost my debug file but could try and create it if it is deemed important.

### Crash Output
None.

### Expected Behavior
The first `apply` of the module should set the `rate_limit` attribute to the specified value.

### Actual Behavior
The `rate_limit` attribute is set to 0.  

### Steps to Reproduce
1. `terraform init`
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`
1. `terraform apply`

You should notice that the second `apply` correctly sets the desired value.  You have to apply twice in order for the value to take.  The other attributes appear to be correctly on the first `apply`.

### Important Factoids
Running on Ubuntu 16.04

### References
None found.

**Comment by Ninir** [comment]
Hi @kurron 

Just threw a PR for that, sorry for the issue :)

**Comment by kurron** [comment]
Thanks for the fix, @Ninir .  If I rerun `teffaform init` will I automatically get the fix or do I have to wait for a release of the AWS provider?
