### ISSUE TITLE
Feature Request: EMR Custom AMI

### ISSUE THREAD

**Issue by pmacdougall** [terraform-providers/terraform-provider-aws#2075]
I'd like to be able to use a custom AMI for aws_emr_cluster resources, or perhaps

There's various reasons for wanting to use a custom AMI, but I'd like to have encrypted root volume for compliance.  Others may want to pre-install some packages.

http://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-custom-ami.html

**Comment by Ninir** [comment]
Hi @pmacdougall , 

this has been merged and will be released in 1.8.0.

Thanks for your patience and Happy Terraforming!

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
