### ISSUE TITLE
Support ElastiCache/Redis In-Transit and At-Rest Encryption

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#2087]
[Recently announced](https://aws.amazon.com/blogs/security/amazon-elasticache-now-supports-encryption-for-elasticache-for-redis/) support for in-transit and at-rest encryption for ElastiCache for Redis clusters.
Add support in Terraform.

**Comment by nathanielks** [comment]
@ewbankkit are you working on this? I'm getting started on this myself!

**Comment by nathanielks** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/2090

**Comment by ewbankkit** [comment]
No, just added it as an issue that I'd tackle sooner or later if nobody got to it first. Thanks for tackling this.

**Comment by nathanielks** [comment]
Surely! I've been looking for something I could contribute to and this looked like a great opportunity!

**Comment by yelvert** [comment]
It looks like this is already possible by using a custom parameter group, http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ParameterGroups.Redis.html.

**Comment by nathanielks** [comment]
@yelvert see https://github.com/terraform-providers/terraform-provider-aws/pull/2090 and https://github.com/terraform-providers/terraform-provider-aws/pull/2090#issuecomment-342309110. Just waiting on Review/Merge now!

**Comment by cog-qlik** [comment]
Any news about this PR?

**Comment by guybumbling** [comment]
I am very interested in progress on this effort. Looking forward to news of it's release. Thanks for taking on this task.

**Comment by LukaszTheProgrammer** [comment]
I saw that the encryption enhancement is on master so far. Any news when it will be released ?

**Comment by nathanielks** [comment]
@LukaszTheProgrammer Looking at the Changelog history, I can see releases averaging every week to 2 weeks. It shouldn't be too much longer! It's also possible to build master locally and use it sooner if you like!

**Comment by LukaszTheProgrammer** [comment]
Thanks for the info.

**Comment by jayudhandha** [comment]
@yelvert I have checked your suggestion [https://github.com/terraform-providers/terraform-provider-aws/issues/2087#issuecomment-344365352](Comment)
But it looks like there is not any specific option to enable the In-Transit/At-Rest encryption in Custom Parameter group.
Please guide!

**Comment by jayudhandha** [comment]
Any update on this?

**Comment by dave-receptiviti** [comment]
It would really be awesome to be able to terraform this part of the infrastructure (encryption is a prerequisite) :)

**Comment by nathanielks** [comment]
@dave-receptiviti @jayudhandha the changes were rolled out in 1.6, so it's officially supported now!

- at_rest_encryption_enabled - (Optional) Whether to enable encryption at rest.
- transit_encryption_enabled - (Optional) Whether to enable encryption in transit.
- auth_token - (Optional) The password used to access a password protected server. Can be specified only if transit_encryption_enabled = true.

https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html

**Comment by nathanielks** [comment]
Maintainers: this issue is resolved, so it can be closed!

**Comment by jayudhandha** [comment]
@nathanielks I am using 1.2 right now. 
Is there any changes that i need to take care if i am upgrading to 1.6?

**Comment by nathanielks** [comment]
@jayudhandha best bet would be to consult the changelog: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md

**Comment by bflad** [comment]
This was previously released in [version 1.6.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#160-december-18-2017) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by jl2501** [comment]
This is not yet available for AWS ElastiCache Redis w/out Cluster Mode Enabled?

**Comment by nathanielks** [comment]
@jl2501 correct, this is only for ElastiCache Replication Groups.
