### ISSUE TITLE
Add DNS name output to efs_file_system resource

### ISSUE THREAD

**Issue by endofcake** [terraform-providers/terraform-provider-aws#2104]
Hello.

According to the [documentation](https://www.terraform.io/docs/providers/aws/r/efs_file_system.html), the only attributes that are exported for `efs_file_system` resource are `id` and `kms_key_id`.

It would be very handy to also have the DNS name, as this is what's used to mount the file system. It's exposed as an attribute on [`efs_file_system` data source](https://www.terraform.io/docs/providers/aws/d/efs_file_system.html), but not on the resource.

Is there any reason this attribute is not available on the resource?

**Comment by Ninir** [comment]
Hi @endofcake 

The documentation is wrong on that and will be fixed in a PR i'm about to throw in. This will fix the documentation and provide the attribute both in the data source and resource!
