### ISSUE TITLE
Fetching Subnet_id's in the order of Availability_zones.

### ISSUE THREAD

**Issue by munusamy** [terraform-providers/terraform-provider-aws#2120]
Hello,

I am trying to fetch the subnet_id's on AWS with the Name Tag.

```
data "aws_subnet_ids" "selected" {
  vpc_id = "${var.vpc_id}"

  tags {
    Name = "zone*"
  }
}
```

The above code works fine but it fetches in random order.

say like.,

```
Outputs:

show = [
    subnet-xxx1c3,   # zone-1a
    subnet-xxxx65,   # zone-1c
    subnet-x03bxx,   # zone-1d
    subnet-xxfxxx9 . # zone-1b
]
```
I am using this order on the `aws_instance` to provision an instance and I tag the servers with "servers-${count.index + 1}".  

What happens here is, servers-04 provisions in zone-1b.

Basically I need something like,  servers-01 -> zone-1a, servers-02 -> zone-1b, ....

Any help is really appreciated.

Thank You,
Munu

**Comment by munusamy** [comment]
I got a workaround for this.

Fetch the subnet-id's of each availability_zones individually initially.

subnet-tag1,subnet-tag2...etc., are exact tag name for their respective subnets.

```
data "aws_subnet_ids" "1a" {
  vpc_id = "${aws_vpc.default.id}"

  tags {
    Name = "subnet-tag1"
  }
}

# collects the subnet_id of availability_zone - 1b
data "aws_subnet_ids" "1b" {
  vpc_id = "${aws_vpc.default.id}"

  tags {
    Name = "subnet-tag2"
  }
}

# collects the subnet_id of availability_zone - 1c
data "aws_subnet_ids" "1c" {
  vpc_id = "${aws_vpc.default.id}"

  tags {
    Name = "subnet-tag3"
  }
}

# collects the subnet_id of availability_zone - 1d
data "aws_subnet_ids" "1d" {
  vpc_id = "${aws_vpc.default.id}"

  tags {
    Name = "subnet-tag4"
  }
}
```

Then in your `aws_instance` resource add the below lines for the subnet_id's:

```
resource "aws_instance" "web" {
  count = 4
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
  subnet_id              = "${element(concat(data.aws_subnet_ids.1a.ids,data.aws_subnet_ids.1b.ids,data.aws_subnet_ids.1c.ids,data.aws_subnet_ids.1d.ids), count.index)}"

  tags {
    Name = "HelloWorld-${format("%02d", count.index + 1 )}"
  }
}
```
Here in this case, combination of `concat` and `element` does the magic.

I'm closing this issue for now.

Thank You,
Munu

**Comment by NSmeef** [comment]
I think this should be improved, the above solution isn't pretty, I've tried to apply `sort` to the data thats returns from `aws_subnet_ids` however doesn't seem to do anything. I am trying a nested interpolation however.

**Comment by rmsrohan** [comment]
Did we found any solution to this issue?
I have a usecase where my first 2 subnets are full, So we have added 2 new subnets under VPC.
Now as per count.index logic, most EC2's get created in 1st and 2nd subnet.
Since I am unable to sort subnets as per name tags, its hard to launch using manual indexing.

**Comment by lsapan** [comment]
For anyone still looking for a cleaner alternative, here's an option. This assumes you've named your subnets `internal-private-1a`, `internal-private-1b`, etc.

```
variable "azs" {
    type = "list"
    default = ["1a", "1b", "1c", "1d", "1e", "1f"]
}

data "aws_subnet" "internal_private" {
    count = 6
    vpc_id = "${data.aws_vpc.internal.id}"

    tags {
        Name = "internal-private-${element(var.azs, count.index)}"
    }
}
```

This guarantees order and lets you access other attributes about the subnets.

**Comment by pranj** [comment]
I ran into this as well, here is another workaround to use once you're fetched the unsorted list of subnet ids from the aws_subnet_ids resource.

https://github.com/terraform-providers/terraform-provider-aws/issues/3471#issuecomment-411912932
