### ISSUE TITLE
terraform-provider-aws 1.2 fails with "netrpc: connect: no such file or directory" on plan/apply when using with terraform 0.10

### ISSUE THREAD

**Issue by endemics** [terraform-providers/terraform-provider-aws#2121]
Hi,

We started seeing issues today with our CD pipeline today where the "terraform plan" and "terraform apply" commands started to fail with "netrpc: connect: no such file or directory".

Fixing the provider version to 1.1 using `version = "= 1.1"` fixed the issue, as well as using terraform 0.10.1 and above, so I believe it's related to the 1.2 release yesterday and similar to https://github.com/hashicorp/terraform/issues/15756

Should the requirements in Readme be updated to indicate that version 1.2 and beyond need terraform 0.10.1 and above instead of 0.10.x?

**Comment by aaomoware** [comment]
i second that.

im seeing the same issue:

```
➜  linux_amd64 git:(master) ✗ tf version          
Terraform v0.10.0

Your version of Terraform is out of date! The latest version
is 0.10.8. You can update by downloading from www.terraform.io
➜  linux_amd64 git:(master) ✗ ll                 
total 67M
-rwxr-xr-x 1 aaomoware aaomoware 159 Nov  2 10:38 lock.json
-rwxr-xr-x 1 aaomoware aaomoware 55M Nov  2 10:38 terraform-provider-aws_v1.2.0_x4
-rwxr-xr-x 1 aaomoware aaomoware 12M Nov  2 10:38 terraform-provider-consul_v1.0.0_x4
➜  linux_amd64 git:(master) ✗ 
```

**Comment by aaomoware** [comment]
@endemics 

tf upgrade resolved this issue for me

```
➜  env git:(master) ✗ tf version
Terraform v0.10.8

➜  env git:(master) ✗ ll .terraform/plugins/linux_amd64/
total 67M
-rwxr-xr-x 1 aaomoware aaomoware 159 Nov  2 10:52 lock.json
-rwxr-xr-x 1 aaomoware aaomoware 55M Nov  2 10:52 terraform-provider-aws_v1.2.0_x4
-rwxr-xr-x 1 aaomoware aaomoware 12M Nov  2 10:52 terraform-provider-consul_v1.0.0_x4
➜  env git:(master) ✗ 
```

**Comment by Yuxael** [comment]
Either update terraform to 0.10.8 or specifically set
```
provider aws {
    version = "1.1"
}
```
in all configurations because provider version 1.2 is not backward compatible with terraform <v0.10.8
👎

**Comment by bflad** [comment]
Given that this issue is related to very old provider/core versions from shortly after the provider split, I'm going to close this issue as most people should be on 0.10.8 or 0.11.x at this point. If someone does feel inclined to update documentation regarding this for some reason, we can certainly take a look.
