### ISSUE TITLE
Add ARN attribute to `aws_elb` resource

### ISSUE THREAD

**Issue by joshuaspence** [terraform-providers/terraform-provider-aws#2123]
It seems that the `aws_elb` resource doesn't output an `arn` attribute (whereas the `aws_lb` resource does). The use case for this is a custom Lambda function that we have written which takes a list of domains to generate certificates for using LetsEncrypt, as well as a list of ELB ARNs to use for updating certificates.

**Comment by bflad** [comment]
This is similar to #2261 for aws_ebs_volume where the API doesn't directly provide it, but we can manually construct it. PR incoming.

**Comment by bflad** [comment]
Submitted PR: #2272
