### ISSUE TITLE
Add support for Direct Connect Gateway

### ISSUE THREAD

**Issue by ungureanuvladvictor** [terraform-providers/terraform-provider-aws#2140]
AWS just released Direct Connect Gateway which enable cross-region VPC communication. Filing this issue to track the feature in the terraform AWS provider.

https://aws.amazon.com/blogs/aws/new-aws-direct-connect-gateway-inter-region-vpc-access/

**Comment by dontrebootme** [comment]
API Documentation: http://docs.aws.amazon.com/directconnect/latest/APIReference/API_CreateDirectConnectGateway.html

**Comment by ewbankkit** [comment]
Related: https://github.com/terraform-providers/terraform-provider-aws/pull/876.

**Comment by ewbankkit** [comment]
Probably need to address the 64-bit integer value problem identified here: https://github.com/terraform-providers/terraform-provider-aws/pull/1888.

**Comment by heycasey** [comment]
In addition to DX Gateway, having support for standard Direct Connect would also be sincerely appreciated.

**Comment by codyja** [comment]
Could use this too.

**Comment by chrisferry** [comment]
👍

**Comment by bflad** [comment]
New `aws_dx_gateway` and `aws_dx_gateway_association` resources are merged into master and will release with version 1.24.0 of the AWS provider, very shortly.

**Comment by bflad** [comment]
This has been released in [version 1.24.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1240-june-21-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
