### ISSUE TITLE
Terraform can't create RDS cluster instance

### ISSUE THREAD

**Issue by leodamasceno** [terraform-providers/terraform-provider-aws#2151]
Terraform version
```
➜  git terraform -v
Terraform v0.10.8
```

Terraform files:
- rds.tf:
```
resource "aws_rds_cluster_instance" "rds_cluster_instances" {
  engine               = "aurora-postgresql"
  count                = "${var.rds_instances_count}"
  identifier           = "${var.rds_cluster_name}-${count.index}"
  cluster_identifier   = "${aws_rds_cluster.rds_cluster.id}"
  instance_class       = "${var.rds_instance_type}"
}

resource "aws_db_subnet_group" "rds_private_db_subnet" {
  name        = "db-private-subnet"
  description = "Private subnets for RDS instance"
  subnet_ids  = [ "${aws_subnet.prod-private-subnet1.id}", "${aws_subnet.prod-private-subnet2.id}" ]
}

resource "aws_rds_cluster" "rds_cluster" {
  engine                  = "aurora-postgresql"
  cluster_identifier      = "${var.rds_cluster_name}"
  availability_zones      = "${var.rds_cluster_az}"
  vpc_security_group_ids  = ["${aws_security_group.application-rds-sg.id}"]
  database_name           = "${var.rds_db_name}"
  master_username         = "${var.rds_admin_user}"
  master_password         = "${var.rds_admin_pw}"
  db_subnet_group_name    = "${aws_db_subnet_group.rds_private_db_subnet.name}"
}
```

- vars.tf:
```
variable "rds_instances_count" {
  default = 1
}

variable "rds_cluster_name" {
  default = "application-db-cluster"
}
variable "rds_instance_type" {
  default = "db.t2.micro"
}

variable "rds_cluster_az" {
  default = ["us-east-1a", "us-east-1b"]
}

variable "rds_db_name" {
  default = "application_db"
}

variable "rds_admin_user" {
  default = "app_master"
}

variable "rds_admin_pw" {
  default = "ADMIN_PW"
}
```

Error:
```
Error: Error applying plan:

1 error(s) occurred:

* aws_rds_cluster_instance.rds_cluster_instances: 1 error(s) occurred:

* aws_rds_cluster_instance.rds_cluster_instances: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=aurora-postgresql, EngineVersion=9.6.3, LicenseModel=postgresql-license. For supported combinations of instance class and database engine version, see the documentation.
	status code: 400, request id: 9828fa34-bfa9-11e7-b50b-eb623c35da4b

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

It doesn't matter the instance type, I've tested it with t2.micro, t2.small, t2.medium, m4.large but it gives me the same error. I'm able to create an instance via AWS console so I can't understand why it complains about the combination.

**Comment by jpSimkins** [comment]
Error seems pretty clear:

> RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=aurora-postgresql, EngineVersion=9.6.3, LicenseModel=postgresql-license. For supported combinations of instance class and database engine version, see the documentation.

**Comment by damascenorakuten** [comment]
Hello @jpSimkins, thanks for your reply.

I'm able to create an EC2 instance (t2.micro) using aurora-postgresql via AWS Console but I can't do the same via via Terraform. That's what I'm trying to understand.

**Comment by leodamasceno** [comment]
I'm sorry @jpSimkins I actually meant RDS instance, not EC2 instance. Here's how I can create a RDS instance using the AWS CLI:
```
aws rds create-db-instance --db-instance-identifier pine-production --allocated-storage 1 --db-instance-class db.t2.small  --engine postgres --master-username test --master-user-password test12345678 --allocated-storage 10
```

**Comment by jpSimkins** [comment]
I can verify this issue. Still playing with it to see if I can find a solution

**Comment by jpSimkins** [comment]
Ok, so the issue here is terraform and the problem lies with the engine. 

Terraform is basically running: 
`aws rds create-db-instance --db-instance-identifier pine-production2 --allocated-storage 1 --db-instance-class db.t2.small  --engine aurora-postgresql --master-username test --master-user-password test12345678 --allocated-storage 10`

Which is giving the same error.

Note the difference of the engine: `aurora-postgresql` (terraform) and `postgres` (aws-cli)

**Comment by damascenorakuten** [comment]
The plan is actually to have a cluster. I've noticed what you said about the engine, I believe that's necessary for people using PostgreSQL. Can we tag it as a bug or improvement?

Thanks

**Comment by jpSimkins** [comment]
This is definitely not a bug but an improvement. Terraform does not support `postgres` as an available option for an RDS Cluster and AWS does. You will have to wait until the team can flag this appropriately.

Terraform does not offer all the options AWS does for the RDS Cluster so hopefully this will push them to implement it.

**Comment by bflad** [comment]
Looking at the conversation above from a few months ago, this seems to be related to confusion between using Aurora and non-Aurora for PostgreSQL. The two versions have different hardware requirements.

The original error about cluster instance sizing was generated by the RDS API when attempting to use an unsupported instance size. Due to the complexity of attempting plan-time validation (and its required maintenance when its updated upstream), its very unlikely that we would implement validation for this type of problem.

If someone feels inclined to note what (if any) documentation updates might be needed here, we can take a look, but this issue is fairly stale as-is and doesn't clarify a definition of done, so I'm going to close it. 👍

**Comment by anisjonischkeit** [comment]
Had a lot of trouble finding this but Aurora does actually support more than just `r4` types. This seems to be the list of instance types that work https://docs.amazonaws.cn/en_us/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html so the smallest instance for mysql seems to be a `db.t2.small` and a `db.t3.medium` for postgres
