### ISSUE TITLE
More than 1 security group from data source

### ISSUE THREAD

**Issue by lee5i3** [terraform-providers/terraform-provider-aws#2152]
I would like to be able to choose more than 1 security groups in my resources rather than knowing every single group I'm using, I was hoping to use the tags to get them all by tag, but looks like the data source aws_security_group only allows for 1..

Anyway to allow more than 1 security group returned or... a new aws_security_groups data source?

**Comment by bflad** [comment]
An [`aws_security_groups` data source](https://www.terraform.io/docs/providers/aws/d/security_groups.html) for querying multiple security groups was recently merged into master via #2947 released in [version 1.25.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1250-june-27-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
