### ISSUE TITLE
Undocumented 'id' field in data resource aws_caller_identity

### ISSUE THREAD

**Issue by tamsky** [terraform-providers/terraform-provider-aws#2163]
https://github.com/terraform-providers/terraform-provider-aws/commit/c72daf4c56c0e1bb21a543da97c538bb3dbcc6de#diff-0108aa7a65bdf3309a8a2e110ef60d34R28

``` diff
+	d.SetId(time.Now().UTC().String())
```

added an undocumented `id` attribute to the `data.aws_caller_identity` resource, which contains the current datetime.

This is unexpected.

Please either remove the attribute (it does not appear to be used anywhere else in the module or tests), or document it.

Thanks!

**Comment by drewsonne** [comment]
It's documented here https://www.terraform.io/guides/writing-custom-terraform-providers.html#implement-create

That resource is used by terraform internally to track resources. If it's blank/not there, the resource won't exist according to terraform.

**Comment by tamsky** [comment]
Indeed it is documented, I should have looked at the function definition + comment:

https://github.com/hashicorp/terraform/blob/master/helper/schema/resource_data.go#L244

I definitely learned something by way of your answer.
Thank you!
