### ISSUE TITLE
Feature Request: Please add s3 as an engine type for DMS endpoints

### ISSUE THREAD

**Issue by gevansBigG** [terraform-providers/terraform-provider-aws#2165]
Please add support for S3 as a dms endpoint. See: http://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html
https://github.com/aws/aws-sdk-go/blob/master/service/databasemigrationservice/api.go

Terraform Version: All

Affected Resource(s):aws_dms_endpoint

Expected Behavior:

User should be able to specify S3 as the engine_name argument. As a result of this, most of the other arguments will become optional, and some new arguments will need to be created: bucket_name, bucket_folder, table_structure and CDC path (optional).

**Comment by altay13** [comment]
Hey @gevansBigG this is already added and waiting for merge
https://github.com/terraform-providers/terraform-provider-aws/pull/1685

**Comment by bflad** [comment]
Support has been merged in via #1685 and #4447 and will release in v1.18.0 of the AWS provider in two days.

**Comment by bflad** [comment]
This has been released in [version 1.18.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1180-may-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
