### ISSUE TITLE
Add support for regional aws_api_gateway_rest_api

### ISSUE THREAD

**Issue by nchazin** [terraform-providers/terraform-provider-aws#2167]
AWS has announced regional (as opposed to edge-optimized) gateways:
https://docs.aws.amazon.com/apigateway/latest/developerguide/create-regional-api.html

**Comment by whyvez** [comment]
Would be open to help with this if I can get some guidance from a senior team member. Am also very interested in this feature.

**Comment by bflad** [comment]
Hi everyone! 👋  Looks like we have duplicate issues for this feature request. In order to consolidate discussion and any efforts, closing this issue in preference of #2195, which currently has much more discussion and some workarounds.
