### ISSUE TITLE
DynamoDB Create/Delete Table has Hardcoded Timeout

### ISSUE THREAD

**Issue by iceycake** [terraform-providers/terraform-provider-aws#2172]
### Terraform Version
v0.10.8 with aws 1.2.0

### Affected Resource(s)
- dynamodb

Creating and Deleting DynamoDB usually takes more than 5 minutes.  The correct implementation has hardcoded timeout.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
