### ISSUE TITLE
aws_codedeploy_deployment_group: deployment_style invalid key

### ISSUE THREAD

**Issue by geoff-kruss** [terraform-providers/terraform-provider-aws#2186]
### Terraform Version
0.10.8

### Affected Resource(s)
- aws_codedeploy_deployment_group

### Terraform Configuration Files
```hcl
resource "aws_codedeploy_deployment_group" "deployment_group" {
  app_name              = "${aws_codedeploy_app.codedeploy_app.name}"
  deployment_group_name = "Default"
  service_role_arn      = "${var.instance_role_arn}"
  autoscaling_groups    = ["${aws_autoscaling_group.autoscaling_group.name}"]

  deployment_style {
    deployment_option = "WITH_TRAFFIC_CONTROL"
  }
}
```

### Expected Behavior
I expect the deployment group to be created/updated with the `deployment_style` option.

### Actual Behavior
Terraform exits with the error: `invalid or unknown key: deployment_style`

### Steps to Reproduce
1. Create a deployment group as above
2. run `terraform plan`

Update: The issue appears to happen on modify only, not when creating a new deployment group.

**Comment by paddycarver** [comment]
What version of the AWS provider are you using?

**Comment by geoff-kruss** [comment]
Hi @paddycarver, currently using version 1.2.0 of the AWS provider. 

It should be noted that this failure happens when the deployment group already exists (ie. on modify). I've just realized that I haven't tested it in the event that terraform needs to create a new deployment group. 

I will try that and report back.

**Comment by paddycarver** [comment]
Hm, interesting. I've checked, and it looks like `deployment_style` was supported in 1.2.0, which was my first guess. A [debug log](https://www.terraform.io/docs/internals/debugging.html) would be incredibly helpful in figuring out exactly what's going wrong here.

**Comment by sharath-yml** [comment]
I had the same issue. Adding aws provider version (version = "~> 1.3") fixed it for me. 
This should be documented somewhere in the official documentation pages.

**Comment by bflad** [comment]
This looks like it was previously fixed awhile ago. Please open a new issue if you are having trouble.
