### ISSUE TITLE
Feature: S3 bucket-wide default encryption

### ISSUE THREAD

**Issue by reedloden** [terraform-providers/terraform-provider-aws#2196]
Announcement: https://aws.amazon.com/blogs/aws/new-amazon-s3-encryption-security-features/

AWS announced support for default encryption for S3 buckets (woo!).

Docs:
* http://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html
* http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketDELETEencryption.html
* http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETencryption.html
* http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTencryption.html

**Comment by samkk-nuna** [comment]
Hi folks — is there an estimate of when this will land? Very much interested in using this feature.

**Comment by jen20** [comment]
This landed in #2472 - it was manually merged so the issue didn't close automatically.
