### ISSUE TITLE
terraform plan updates blank("") diff

### ISSUE THREAD

**Issue by koooge** [terraform-providers/terraform-provider-aws#2199]
Hi there, `terraform plan` says which `"" -> ""` includes diff.  But I don't think so.

### Terraform Version
- Terraform v0.10.8
- terraform-provider-aws_v1.2.0_x4

### Terraform Configuration Files
```hcl
resource "aws_iam_policy_attachment" "foo" {
  name = "${lookup(var.foo, "${terraform.workspace}.name")}"
  policy_arn = "${lookup(var.foo, "${terraform.workspace}.policy_arn")}"
  groups = "${split(",", lookup(var.foo, "${terraform.workspace}.groups", ""))}"
  users = "${split(",", lookup(var.foo, "${terraform.workspace}.users", ""))}"
  roles = "${split(",", lookup(var.foo, "${terraform.workspace}.roles", ""))}"
}
```

### Expected Behavior
```
$ terraform plan
```
There is no change.

### Actual Behavior
```
 ~ module.aws_iam_policy_attachment.foo
      roles.#: "0" => "1"
      roles.0: "" => ""
      users.#: "0" => "1"
      users.0: "" => "".
```

**Comment by bflad** [comment]
@koooge what happens if you wrap your `split()` calls with `compact(split())`? https://www.terraform.io/docs/configuration/interpolation.html#compact-list-

**Comment by koooge** [comment]
@bflad There is no Diff. nice workaround 😇

**Comment by bflad** [comment]
I'm not sure its necessarily a workaround at the moment. There may be a Terraform core issue here that plan should remove empty string elements when its this type of schema or it just might be that we have to implement that functionality ourselves here. The provider maintainers will be more knowledgeable about this though. This is the attribute schema for reference (omitting extraneous `Optional: true`):

```hcl
&schema.Schema{
    Type:     schema.TypeSet,
    Elem:     &schema.Schema{Type: schema.TypeString},
    Set:      schema.HashString,
},
```

For what its worth glancing through the `aws_iam_policy_attachment` code, it does appear to have checks to ignore applying empty string elements (in `expandStringList`) so shouldn't be trying to attach those even with it showing the diff.
