### ISSUE TITLE
Feature request: S3 Cross-Region Replication with KMS

### ISSUE THREAD

**Issue by modax** [terraform-providers/terraform-provider-aws#2200]
Hi,

Just a couple of hours ago, AWS introduced S3 CRR with KMS support. It would nice to get this integrated into terraform (though it seems that support for it is lacking in AWS Go SDK)

https://aws.amazon.com/blogs/aws/new-amazon-s3-encryption-security-features/

**Comment by cornfeedhobo** [comment]
This would be awesome to see happen.

**Comment by cornfeedhobo** [comment]
Seriously? Three months with a PR just sitting there ready? 4 new releases and this still isn't addressed?

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
