### ISSUE TITLE
DependencyViolation error when destroying a subnet (hard fail) doesn't prevent it from being retried for 10 minutes

### ISSUE THREAD

**Issue by c2h5oh** [terraform-providers/terraform-provider-aws#2201]
### Terraform Version
v0.10.8 (32d32f8be33f4fc729773776e95a7a56a700e888)

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_subnet

### Debug Output
https://gist.github.com/c2h5oh/9ecfd060c9c24bdc6b4ba35caed7ae3f

### Expected Behavior
Subnet deletion fails immediately

### Actual Behavior
Despite error message `ec2/DeleteSubnet failed, not retrying` deleting the subnet will be retried for 10 minutes and the final error message will be incorrect: `Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 10m0s)`

### Steps to Reproduce
1. Create a subnet
2. Reference the subnet (in security group for example)
3. Attempt to destroy that subnet (but not whatever is referencing it)

**Comment by mdaniel** [comment]
I experienced this while trying to modify the `aws_security_group` used by `vpc_security_group_ids` of an `aws_db_instance` resource; two questions:
1. does the fact it also occurs on an `aws_security_group` resource mean that circumstance should have a new GH issue?
1. is the failure to understand the cyclic dependency related to this, or does it also need a new GH issue?
