### ISSUE TITLE
feature request: add association_name to aws_ssm_association

### ISSUE THREAD

**Issue by nbirnel** [terraform-providers/terraform-provider-aws#2205]
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
- aws_ssm_association

### Expected Behavior
AWS ssm associations have a "name" (the name of the document being associated) and an "association-name" (the name of the association itself). It would be useful to be able to include an association_name with an aws_ssm_association.

### Actual Behavior
association_name not supported

**Comment by orenmaor** [comment]
We need this too.

It looks like it's already in the SDK:
https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#CreateAssociationInput

    // Specify a descriptive name for the association.
    AssociationName *string `type:"string"`
