### ISSUE TITLE
aws_ssm_association doesn't work with shared SSM documentes

### ISSUE THREAD

**Issue by Fodoj** [terraform-providers/terraform-provider-aws#2210]
### Terraform Version

0.10.6

### Affected Resource(s)

- aws_ssm_association

### Terraform Configuration Files
```hcl
resource "aws_ssm_association" "patch-compliance" {
  provider            = "aws.us"
  name                = "arn:aws:ssm:us-east-1:XXXXXXXX:document/my-document-name"
  targets             = {
    key    = "tag:name=Env"
    values = ["prod"]
  }
  schedule_expression = "cron(0 1 0 ? * * *)"
}

```

### Expected Behavior

Terraform creates new ssm association and uses shared document, located in different AWS account

### Actual Behavior

```
* aws_ssm_association.patch-compliance: [ERROR] Error creating SSM association: ValidationException: 1 validation error detected: Value 'arn:aws:ssm:us-east-1:XXXXXXXXXXXX:document/my-document-name' at 'name' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9_\-.]{3,128}$
	status code: 400, request id: cb04f6fd-c3d5-11e7-8546-7b1e5b0e77d1
```

### Important Factoids

If I specify _only_ the name of the document, then Terraform says that document doesnt' exist at all.

**Comment by bflad** [comment]
@Fodoj is there documentation saying cross-account association should be supported somewhere? I don't think this behavior is currently allowed by the AWS API: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateAssociation.html#API_CreateAssociation_RequestSyntax

```
Name
The name of the Systems Manager document.

Type: String

Pattern: ^[a-zA-Z0-9_\-.]{3,128}$

Required: Yes
```

You likely will have to open an AWS support case if you want this functionality implemented.

**Comment by Fodoj** [comment]
You are right, it’s not supported on AWS level.

Am 14. Nov. 2017, 08:02 +0100 schrieb Brian Flad <notifications@github.com>:

**Comment by paddycarver** [comment]
As this is not really a bug in the provider, from what I can tell, and is more a case of missing functionality at the API level, I'm going to close this issue out. If you feel it should remain open, please feel free to reply to the issue and we can reopen it.
