### ISSUE TITLE
Feature: Add support for S3 Cross-Region Replication ACL Overwrite

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#2221]
One of the [newly](https://aws.amazon.com/blogs/aws/new-amazon-s3-encryption-security-features/) announced/released S3 features is Cross-Region Replication ACL Overwrite.
Add support for this to the `aws_s3_bucket` resource's `replication_configuration` attribute.

**Comment by ewbankkit** [comment]
Duplicated by https://github.com/terraform-providers/terraform-provider-aws/issues/3575.

**Comment by bflad** [comment]
Huge shout out to @jrstarke and @ewbankkit! I believe this functionality has been merged and will be released in version 1.40.0 of the AWS provider, likely later today. 🚀 

Please let me know if that's actually not the case, @ewbankkit. 😉

**Comment by ewbankkit** [comment]
Yes, this was the same as #3575.
