### ISSUE TITLE
Feature: Support AWS PrivateLink for AWS Services

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#2222]
[Newly](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-aws-privatelink-for-aws-services/) announced feature AWS PrivateLink for AWS Services.

**Comment by jen20** [comment]
This was completed in #2515 and landed in 35b273ec.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
