### ISSUE TITLE
user_data with variables - extra quotes?

### ISSUE THREAD

**Issue by TinajaLabs** [terraform-providers/terraform-provider-aws#2223]
Terraform v0.10.7

I'm trying to execute some commands with `user_data`.  I need to use the inline version so as to have access to the iterative `count.index` value.

Here's the code of interest:

```
locals {
  user_cmd_empty = ""
  user_cmd_if    = "    - touch /var/tmp/user_cmd_if.txt"
  user_cmd_pm    = "    - touch /var/tmp/user_cmd_pm.txt"
  user_cmd_ym    = "    - touch /var/tmp/user_cmd_ym.txt"
}

# ... more code here

resource "aws_instance" "this" {

  # ... more code here

  user_data = <<-EOF
    #cloud-config
    hostname: "${var.number_of_instances > 1 ? "${var.host_name}${format("%02d", count.index + 1)}.${var.instance_name}" : "${var.instance_name}" }"
    fqdn: "${var.number_of_instances > 1 ? "${var.host_name}${format("%02d", count.index + 1)}.${var.instance_name}" : "${var.instance_name}" }"
    manage_etc_hosts: true

    runcmd:
    - touch /var/tmp/HelloInThere.txt
    "${var.host_name == "if" ? "${local.user_cmd_if}" : "${local.user_cmd_empty}" }"
    EOF
}
```

What I end up with is something like the following:
```
    #cloud-config
    hostname: "yum.sys-a.ecm"
    fqdn: "yum.sys-a.ecm"
    manage_etc_hosts: true

    runcmd:
    - touch /var/tmp/HelloInThere.txt
    ""
```

**The problem is that the variables leave behind the double quotes.**

It works OK for the `hostname` and the `fqdn` but it chokes and aborts the entire cloud-init script with the empty double quotes.  It also chokes if there IS a touch command because the double quotes are included there as well.

BTW, just using the touch command as an example to see how this works.

**Is there a way to escape the double quotes out of the result?**

Thanks in advance,
Chris.

**Comment by TinajaLabs** [comment]
On the offending line:
```
"${var.host_name == "if" ? "${local.user_cmd_if}" : "${local.user_cmd_empty}" }"
```

I changed it to remove the quotes and the internal variable definitions like this:
```
"${var.host_name == "if" ? local.user_cmd_if : local.user_cmd_empty }"
```
It passed the `terraform validate` command and resolved the values correctly, but the double quotes still passed into the cloud-init config.

I also tried some basic escaping but it won't pass the terraform validate command:
```
\"${var.host_name == "if" ? local.user_cmd_if : local.user_cmd_empty }\"
```

This is a show stopper for me.  Is it not a reasonable expectation to use variables in the user_data?

Thanks for any advice,
Chris.

**Comment by bflad** [comment]
Your `"` in the heredoc are added inside there since heredoc is already a HCL string. Try changing your`"${...}"` to `${...}` inside the heredoc and I believe it should work as you expect.

For what its worth, here's how I would write your user_data configuration:
```
user_data = <<-EOF
    #cloud-config
    hostname: ${var.number_of_instances > 1 ? "${var.host_name}${format("%02d", count.index + 1)}.${var.instance_name}" : var.instance_name}
    fqdn: ${var.number_of_instances > 1 ? "${var.host_name}${format("%02d", count.index + 1)}.${var.instance_name}" : var.instance_name}
    manage_etc_hosts: true

    runcmd:
    - touch /var/tmp/HelloInThere.txt
    ${var.host_name == "if" ? local.user_cmd_if : local.user_cmd_empty}
EOF
```

**Comment by TinajaLabs** [comment]
Brian,
That worked.  I guess I should have figured that one out.  Seems so obvious now.

Thanks so much,
Chris.
