### ISSUE TITLE
ssm_maintenance_window_target should support multiple targets

### ISSUE THREAD

**Issue by srhaber** [terraform-providers/terraform-provider-aws#2225]
The SSM Maintenance Window Target resource can accept up to 5 different key/val tags.  However, the provider limits us to 1 key/val.

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_maintenance_window_target.go#L35

This should be a simple fix in theory (just change MaxItems to 5).

**Comment by atsushi-ishibashi** [comment]
Close

**Comment by radeksimko** [comment]
Addressed in #2361 - thanks @atsushi-ishibashi !
