### ISSUE TITLE
Load based configuration is not there in opsworks custom layer

### ISSUE THREAD

**Issue by rajugupta15** [terraform-providers/terraform-provider-aws#2228]
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
- aws_opsworks_custom_layer

Opsworks layer Load based configuration is not there in terraform.

### References
http://docs.aws.amazon.com/opsworks/latest/userguide/workinginstances-autoscaling-loadbased.html

**Comment by eduherraiz** [comment]
I prepared the necessary changes at: #3165

**Comment by commixon** [comment]
It would be nice if we had an update on this indeed
