### ISSUE TITLE
Unable to import aws_elasticache_security_group

### ISSUE THREAD

**Issue by notgary** [terraform-providers/terraform-provider-aws#2260]
### Terraform Version
Terraform v0.10.8
AWS Provider v1.2

### Affected Resource(s)
- `aws_elasticache_security_group`

### Terraform Configuration Files
```hcl
resource aws_elasticache_security_group "redis" {
  name = "redis"
  description = "redis"

  security_group_names = ["web", "app"]
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Resource was imported successfully

### Actual Behavior
```hcl
aws_elasticache_security_group.redis (import id: redis): import aws_elasticache_security_group.redis (id: redis): resource aws_elasticache_security_group doesn't support import
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an elasticache security group through the AWS console called `redis` with a description of `redis`.
2. `terraform import aws_elasticache_security_group.redis redis`

### Important Factoids
- EC2 Classic

**Comment by bflad** [comment]
Submitted PR #2277 which should add the import support, although I cannot verify via acceptance testing on my personal AWS account.
