### ISSUE TITLE
Support & character - aws_security_group into ingress/egress description

### ISSUE THREAD

**Issue by JulienChampseix** [terraform-providers/terraform-provider-aws#2278]
Hi there,

### Terraform Version
0.10.8.

### Affected Resource(s)
aws_security_group

### Request
Be able to use the **&** character into egress/ingress description

### Output error
* aws_security_group.slmp_elb_srv: "ingress.0.description" doesn't comply with restrictions ("^[A-Za-z0-9 \\.\\_\\-\\:\\/\\(\\)\\#\\,\\@\\[\\]\\+\\=\\;\\{\\}\\!\\$\\*]+$"): "Office & Home Location"

**Comment by bflad** [comment]
The fix for this validation has been merged and will release with version 2.42.0 of the Terraform AWS Provider, later this week. Thanks to @stefansundin for the implementation. 👍
