### ISSUE TITLE
Add NetworkConfiguration to ECS

### ISSUE THREAD

**Issue by atsushi-ishibashi** [terraform-providers/terraform-provider-aws#2294]
Required aws-sdk-go@v1.12.27

**Comment by atsushi-ishibashi** [comment]
This is undoubtedly useful 💪

**Comment by atsushi-ishibashi** [comment]
https://aws.amazon.com/blogs/news/introducing-cloud-native-networking-for-ecs-containers/

**Comment by dev-head** [comment]
My team needs this supported, watching issue for now.
