### ISSUE TITLE
aws_directory_service_directory only creates Enterprise MicrosoftAD Directories

### ISSUE THREAD

**Issue by bhechinger** [terraform-providers/terraform-provider-aws#2308]
### Terraform Version
`Terraform v0.10.8`

### Affected Resource(s)
Please list the resources as a list, for example:
`aws_directory_service_directory`

### Terraform Configuration Files
```hcl
resource "aws_directory_service_directory" "AD" {
  name     = "ad.${module.vars.region}.${module.vars.zone}"
  password = "SuperSecretPassw0rd"
  size     = "Standard"
  type     = "MicrosoftAD"

  vpc_settings {
    vpc_id     = "${module.vars.vpc_id}"
    subnet_ids = ["${module.vars.private_subnet}"]
  }
}
```

### Expected Behavior
A Microsoft AD Directory Service of size Standard should have been created.

### Actual Behavior
A Microsoft AD Directory Service of size Enterprise was created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Additional thoughts
The docs state that the options for size are Small and Large. I tried Small as well as Standard and in both cases I get an Enterprise sized service.

**Comment by lorengordon** [comment]
Pretty sure this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/2192

**Comment by bhechinger** [comment]
You are absolutely correct, my mistake for not searching better first. Sorry!
