### ISSUE TITLE
aws_elasticsearch_domain: vpc_options - subnet_ids asks for list but can only be a single value.

### ISSUE THREAD

**Issue by ccslamstack** [terraform-providers/terraform-provider-aws#2333]
AWS released the new VPC endpoint feature for ElasticSearch:
vpc_options:
subnet_ids - (Required) List of VPC Subnet IDs for the Elasticsearch domain endpoints to be created in.

This can only accept a single subnet-id currently, was this added as a list for future development for multiple subnet-id's?  

Also can an attribute be created to specify the vpc-id?

**Comment by rickrdvaughn** [comment]
Any reason this was closed without comment?  Definitely still a bug, which I just ran into.  At minimum documentation really should be updated to correctly state only a single subnet is supported!

**Comment by rajdev127** [comment]
@rickrdvaughn   enabling zone awareness will allow you to point to two or more subnets.

set   
cluster_config {
zone_awareness_enabled = true
} 

``If you enable zone awareness for your domain, Amazon ES places an endpoint into two subnets. The subnets must be in different Availability Zones in the same region. If you don't enable zone awareness, Amazon ES places an endpoint into only one subnet```

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html
