### ISSUE TITLE
Incorrect documentation for lb_target_group

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-aws#2343]
1.3.0 changelog claims `aws_lb_target_group` no longer has a default on matcher, but "200" is still documented:
https://www.terraform.io/docs/providers/aws/r/lb_target_group.html

Additionally, `timeout` default seems to be 10 now, not 5.

**Comment by wjglerum** [comment]
Like I mentioned here: https://github.com/terraform-providers/terraform-provider-aws/pull/2251 `path` is also not default anymore.

**Comment by jurajseffer** [comment]
I've also just noticed this change. The defaults have changed as follows:
```
health_check.0.healthy_threshold:   "5" => "3"
health_check.0.matcher:             "200" => ""
health_check.0.timeout:             "5" => "10"
health_check.0.unhealthy_threshold: "2" => "3"
```

**Comment by catsby** [comment]
Hey @jurajseffer could you possibly provide an example configuration that shows that diff, minus any secret info? I'd like to use it for a regression test to make sure our fix handles that. Thanks!

**Comment by catsby** [comment]
We're also going to track this in #2327 just so I can consolidate issues

**Comment by jurajseffer** [comment]
@catsby 
```
resource "aws_alb_target_group" "target" {
...
    health_check {
        path = "${var.health_check_path}"
    }
...
```
The above config had no changes planned under aws provider <1.3. After upgrade the same config showed [changes I posted earlier](https://github.com/terraform-providers/terraform-provider-aws/issues/2343#issuecomment-345245913)
