### ISSUE TITLE
Feature request: Option to skip EC2 recreation when user data changes

### ISSUE THREAD

**Issue by rarkins** [terraform-providers/terraform-provider-aws#2346]
### Terraform Version
0.11

### Affected Resource(s)
`aws_instance`, `aws_spot_instance_request`

### Expected Behavior
Terraform should give me the option to skip destroying and recreating EC2 instances if the only thing that has changed is user data. e.g. maybe I just add `apt-get install htop` - I really don't want to bring down a server to do that for me.

### Actual Behavior
Whenever I make any changes to EC2 user data, terraform needs to destroy and recreate the resources.

**Comment by bflad** [comment]
@rarkins the recommended way to handle this is implemented for any Terraform resource via lifecycle `ignore_changes`: https://www.terraform.io/docs/configuration/resources.html#ignore_changes

We use this in a large number of places for the same reason as you. This works for any attribute.

For example:
```hcl
resource "aws_instance" "example" {
  # ... other configuration ...
  lifecycle {
    ignore_changes = ["user_data"]
  }
}
```

Hope this helps.
