### ISSUE TITLE
Feature request: aws_efs_mount_target expose IP address as attribute reference

### ISSUE THREAD

**Issue by ivan-pinatti** [terraform-providers/terraform-provider-aws#2354]
Hi there,

Please add the IP address as an attribute reference for **aws_efs_mount_target** so it can be exposed as an output.

### Terraform Version
v0.10.8

### Affected Resource(s)
- aws_efs_mount_target

Cheers,

Ivan Pinatti

**Comment by Ninir** [comment]
Hi @ivan-pinatti 

You should already be able to use `aws_efs_mount_target.<name>.ip_address`. Just threw a PR clarifying the documentation.

Can you check it and tell me how it goes?

Thanks!

**Comment by ivan-pinatti** [comment]
Hi @Ninir, 

Worked like a charm, thanks for clarifying. 

The information wasn't available in the official documents page.

Thanks!

**Comment by Ninir** [comment]
@ivan-pinatti This will be ok once #2371 is merged :)

Thanks for letting us know and Happy Terraforming!
