### ISSUE TITLE
Cognito user pool lambda_config validation error

### ISSUE THREAD

**Issue by m1keil** [terraform-providers/terraform-provider-aws#2365]
### Terraform Version
Terraform v0.11.0
+ provider.aws v1.3.0

### Affected Resource(s)
- aws_cognito_user_pool

### Terraform Configuration Files
```hcl
resource "aws_cognito_user_pool" "pool" {
  name                = "${var.name}"
  username_attributes = ["email"]
  auto_verified_attributes = ["email"]
  
  schema {
    name = "family_name"
    required = "true"
    attribute_data_type = "String"
  }

  lambda_config {
    post_confirmation = "${var.post_conf_lambda_arn}"
  }

  lifecycle {
    prevent_destroy = "true"
  }
}
```

### Expected Behavior
Cognito user pool created with post confirmation trigger set to lambda function.

### Actual Behavior
Terraform fails with the following error:

```
Error: Error applying plan:

1 error(s) occurred:

* module.cognito.aws_cognito_user_pool.pool: 1 error(s) occurred:

* aws_cognito_user_pool.pool: Error creating Cognito User Pool: InvalidParameter: 7 validation error(s) found.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.CreateAuthChallenge.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.CustomMessage.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.DefineAuthChallenge.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.PostAuthentication.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.PreAuthentication.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.PreSignUp.
- minimum field size of 20, CreateUserPoolInput.LambdaConfig.VerifyAuthChallengeResponse.
```
It seems like Terraform expects all (8 in total) of the optional triggers to be defined?

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
My resource config is defined inside a module named "cognito" (explains the error above).

### References
- GH-232

**Comment by Ninir** [comment]
Hi @m1keil 

Just threw a PR for that. Sorry for the noise here!

**Comment by m1keil** [comment]
Cheers @Ninir!
Thank you again!

**Comment by Ninir** [comment]
Hey @m1keil 

You should be able to get the fix as we released 1.3.1! :)

Happy Terraforming!

**Comment by m1keil** [comment]
confirmed as fixed :+1:

**Comment by Ninir** [comment]
Nice to hear, thanks for the feedback :)
