### ISSUE TITLE
Default timeout for `aws_lb_target_group` health check isn't valid

### ISSUE THREAD

**Issue by joshuaspence** [terraform-providers/terraform-provider-aws#2366]
I don't know why #2251 changed the default value for the `timeout`, `healthy_threshold` and `unhealthy_threshold` parameters of the `health_check` block of the `aws_lb_target_group` resource, but the new default value for `timeout` of `10` seems to be invalid:

```
aws_lb_target_group.web_ui_http: Error modifying Target Group: ValidationError: Health check timeout '10' must be smaller than the interval '10'
```

**Comment by catsby** [comment]
Hey @joshuaspence sorry for the trouble. #2251 certainly introduced a few bugs/regressions and I'm trying to clean them up. The docs are a big crazy for these values:

 - http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

The valid value depends on if it's a Network Load Balancer (NLB) or Application Load Balancer (ALB), *and* if the health check is HTTPS, TCP, or HTTP.

If you let me know what you're making, I may be able to guide you, other than that your best best is those docs right now. Sorry!
