### ISSUE TITLE
aws_security_group_rule description not getting saved in state file

### ISSUE THREAD

**Issue by joshuabaird** [terraform-providers/terraform-provider-aws#2383]
Hi there,

### Terraform Version
0.10.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_security_group_rule

### Terraform Configuration Files
```hcl
resource "aws_security_group"  "rds-private" {
  name        = "tf-rds-private"
  description = "Allows access to private RDS instances"
  vpc_id      = "${aws_vpc.primary.id}"

  tags {
    "Name"    = "tf-rds-private"
    "Creator" = "Terraform"
  }
}

resource "aws_security_group_rule" "rds-private-inbound-ecs-main" {
  description              = "TCP inbound from main ECS"
  type                     = "ingress"
  from_port                = "5432"
  to_port                  = "5432"
  protocol                 = "tcp"
  source_security_group_id = "${aws_security_group.ecs_sg.id}"
  security_group_id        = "${aws_security_group.rds-private.id}"
}
```

### Debug Output
https://paste.fedoraproject.org/paste/G7pONhKHeNqk5hvdN8RJ0Q

### Expected Behavior
The SG rule should get created with the description defined in the aws_security_group_rule.

### Actual Behavior
The SG rule description does actually get applied, but the state file does not include the description which causes Terraform to try and re-apply the description on every subsequent plan/apply.

**Comment by garethpowell** [comment]
I'm seeing the same behaviour when the description is added as part of inline rule. Was really pleased to see the addition of this attribute as my boss wanted things to be clearer when looking at security groups in the AWS Console. On the second time apply is run, it produces the following error.

`aws_security_group.integration-alb-sg: Error revoking security group ingress rules: InvalidPermission.NotFound: The specified rule does not exist in this security group.
        status code: 400, request id: 70c721f2-7de7-4c2f-b37a-3aba3cbd31a8
`

**Comment by piersf** [comment]
@garethpowell did you manage to find any solution on or workaround for this?

**Comment by joshuabaird** [comment]
Yeah - this is still affecting us as well.
