### ISSUE TITLE
placement_group attribute is not always present on aws_instance

### ISSUE THREAD

**Issue by antonbabenko** [terraform-providers/terraform-provider-aws#2392]
Hi there,

### Terraform Version
```
Terraform v0.11.0
+ provider.aws v1.3.1
```

### Affected Resource(s)
- aws_instance

### Expected Behavior
`placement_group` is not set on `aws_instance` resource when it was not specified during creation, so we can't make generic output in a module [terraform-aws-ec2-instance](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance) like this:

```hcl
output "placement_group" {
  description = "List of placement groups of instances"
  value       = ["${element(concat(aws_instance.this.*.placement_group, list("")), 0)}"]
}
```

### Actual Behavior
```
* module.ec2.output.placement_group: Resource 'aws_instance.this' does not have attribute 'placement_group' for variable 'aws_instance.this.*.placement_group'
```

### Steps to Reproduce
1. `terraform apply`

**Comment by bflad** [comment]
Hi @antonbabenko, I can see in the provider code that we do omit setting `placement_group` during read so I think that is the source of the problem. It should be fairly simple to add in there. I can submit a PR.

**Comment by bflad** [comment]
PR submitted: #2398

**Comment by bflad** [comment]
Hopefully this solves your issue! 👍  If not, please reopen.

**Comment by antonbabenko** [comment]
Great! Also there is similar issue with ASG - https://github.com/terraform-providers/terraform-provider-aws/issues/2412
