### ISSUE TITLE
BucketRegionError when using new provider aliases

### ISSUE THREAD

**Issue by joshuaspence** [terraform-providers/terraform-provider-aws#2397]
I am seeing a very strange error using the new provider aliases feature added in Terraform 0.11. I am using version 1.3.0 of `terraform-providers-aws`. I have been able to reproduce the problem by following these steps:

1. Apply the following Terraform configuration.

```
provider "aws" {
  region = "ap-southeast-2"
}

provider "aws" {
  alias  = "use1"
  region = "us-east-1"
}

resource "aws_s3_bucket" "test" {
  provider = "aws.use1"
  region   = "us-east-1"
}
```

2. Change the Terraform configuration to this:

```
# main.tf
provider "aws" {
  region = "ap-southeast-2"
}

provider "aws" {
  alias  = "use1"
  region = "us-east-1"
}

module "s3_bucket" {
  source = "./s3_bucket"

  providers {
    aws = "aws.use1"
  }
}

# s3_bucket/main.tf
resource "aws_s3_bucket" "test" {}
```

3. Move the resources in the state file with `terraform state mv aws_s3_bucket.test module.s3_bucket.aws_s3_bucket.test`.

4. Run `terraform plan`, which fails with the following error:

```
aws_s3_bucket.test: Refreshing state... (ID: terraform-20171122002658518500000001)

Error: Error refreshing state: 1 error(s) occurred:

* module.s3_bucket.aws_s3_bucket.test: 1 error(s) occurred:

* module.s3_bucket.aws_s3_bucket.test: aws_s3_bucket.test: error reading S3 bucket "terraform-20171122002658518500000001": BucketRegionError: incorrect region, the bucket is not in 'ap-southeast-2' region
	status code: 301, request id: , host id: 
```

**Comment by bflad** [comment]
@joshuaspence in your case since you'd like to override the root aws.default provider, does it work if you add this inside your module?
```
provider "aws" {}
```

Ref: [Modules Documentation](https://www.terraform.io/docs/modules/usage.html#passing-providers-explicitly)

> At this time it is required to write an explicit proxy configuration block even for default (un-aliased) provider configurations when they will be passed via an explicit providers block

**Comment by joshuaspence** [comment]
I can't do that because the module will be used to create resources in multiple regions.

**Comment by bflad** [comment]
I can confirm that following your steps and making `s3_bucket/main.tf` this:

```
provider "aws" {}

resource "aws_s3_bucket" "test" {}
```

Is able to refresh during a plan just fine (see below). If I remove the empty provider block in the module, it goes back to 301'ing.

```
aws_s3_bucket.test: Refreshing state... (ID: terraform-20171122021427391300000001)

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.
```

> the module will be used to create resources in multiple regions

Can you please explain this in more detail or provide more of your configuration? This problem you mention is not given in your original description so I don't want to guess at a solution.

**Comment by joshuaspence** [comment]
Sure, let me explain... the code snippet was only intended to be a minimum example for reproducing the problem.

# Before
```
# main.tf
provider "aws" {
  profile = "systest"
  region  = "ap-southeast-2"
}

provider "aws" {
  alias   = "apse1"
  profile = "systest"
  region  = "ap-southeast-1"
}

provider "aws" {
  alias   = "use1"
  profile = "systest"
  region  = "us-east-1"
}

provider "aws" {
  alias   = "usw2"
  profile = "systest"
  region  = "us-west-2"
}

resource "aws_s3_bucket" "apse1" {
  provider = "aws.apse1"
}

resource "aws_s3_bucket" "apse2" {
  provider = "aws"
}

resource "aws_s3_bucket" "use1" {
  provider = "aws.use1"
}

resource "aws_s3_bucket" "usw2" {
  provider = "aws.usw2"
}
```

# After
```
# main.tf
provider "aws" {
  profile = "systest"
  region  = "ap-southeast-2"
}

provider "aws" {
  alias   = "apse1"
  profile = "systest"
  region  = "ap-southeast-1"
}

provider "aws" {
  alias   = "use1"
  profile = "systest"
  region  = "us-east-1"
}

provider "aws" {
  alias   = "usw2"
  profile = "systest"
  region  = "us-west-2"
}

module "apse1" {
  source = "./s3_bucket"

  providers {
    aws = "aws.apse1"
  }
}

module "apse2" {
  source = "./s3_bucket"

  providers {
    aws = "aws"
  }
}

module "use1" {
  source = "./s3_bucket"

  providers {
    aws = "aws.use1"
  }
}

module "usw2" {
  source = "./s3_bucket"

  providers {
    aws = "aws.usw2"
  }
}

# s3_bucket/main.tf
resource "aws_s3_bucket" "test" {}
```

This is still a simplified example... in reality, the module is called `vpc` rather than `s3_bucket` and it contains many resources.

**Comment by joshuaspence** [comment]
Sorry, I see the problem now. I misunderstood the documentation. The fact that itobly seemed to cause issues with S3 buckets led me to believe this was a bug.
