### ISSUE TITLE
ReadReplicaSourceDBInstanceIdentifier gets changed when an encrypted replica is created in the same zone as the master

### ISSUE THREAD

**Issue by pccowboy** [terraform-providers/terraform-provider-aws#2399]
### Terraform Version
0.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance.read_replica

### Debug Output
abbreviated sanitized highlighting the issue. gist.github.com/pccowboy/da206a602420fc28f691cb061a7fc181

### Expected Behavior
The `ReadReplicaSourceDBInstanceIdentifier` should be the same as the ARN that was passed in as the `SourceDBInstanceIdentifier`

### Actual Behavior
When we pass an ARN as the `SourceDBInstanceIdentifier` to create an encrypted read replica in the same zone as the encrypted master, the `ReadReplicaSourceDBInstanceIdentifier` is changed to just the database instance ID of the master.  This causes Terraform to report that the read replica needs to be delete and re-created on the next `terraform plan` run, as the `replicate_source_db` field no longer matches what was specified to create the replica.

Replicas created in zones *other* than the zone with the master are created with `ReadReplicaSourceDBInstanceIdentifier` set to the ARN that we specify.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

### References
- https://github.com/terraform-providers/terraform-provider-aws/pull/2386 (now closed, in favor of 3701)
- https://github.com/terraform-providers/terraform-provider-aws/pull/3701

**Comment by pccowboy** [comment]
Hello, looking for some feedback on the PR for this issue?

**Comment by pccowboy** [comment]
@radeksimko Hi, anything I can do to move PR 3701 along, so it can be merged in?

**Comment by petergoldstein** [comment]
👍

**Comment by hinling-whistle** [comment]
Just ran into the same problem. any update on this?
