### ISSUE TITLE
update aws_db_subnet_group/aws_db_parameter_group fail (with new resource required) 

### ISSUE THREAD

**Issue by hsvlz** [terraform-providers/terraform-provider-aws#2402]
### Terraform Version
Terraform v0.11.0
+ provider.aws v1.2.0
+ provider.template v1.0.0

### Affected Resource(s)
aws_db_instance (postgres)
aws_db_parameter_group
aws_db_subnet_group

### Debug Output
```
-/+ module.central-servers.aws_db_parameter_group.default (new resource required)
      id:                    "rds-pg" => <computed> (forces new resource)
      arn:                   "arn:aws:rds:eu-west-1:018597388725:pg:rds-pg" => <computed>
      description:           "Managed by Terraform" => "Managed by Terraform"
      family:                "postgres9.6" => "postgres9.6"
      name:                  "rds-pg" => "alba-rds-pg" (forces new resource)
      name_prefix:           "" => <computed>

-/+ module.central-servers.aws_db_subnet_group.postgresql_deployment (new resource required)
      id:                    "postgresql_deployment" => <computed> (forces new resource)
      arn:                   "arn:aws:rds:eu-west-1:018597388725:subgrp:postgresql_deployment" => <computed>
      description:           "Managed by Terraform" => "Managed by Terraform"
      name:                  "postgresql_deployment" => "alba_postgresql_deployment" (forces new resource)
      name_prefix:           "" => <computed>
      subnet_ids.#:          "2" => "2"
      subnet_ids.1695880707: "subnet-a1ccb8e8" => "subnet-a1ccb8e8"
      subnet_ids.3025816245: "subnet-f0187497" => "subnet-f0187497"
      tags.%:                "1" => "1"
      tags.Name:             "alba" => "alba"

  ~ module.central-servers.module.postgresql_deployment.aws_db_instance.postgresql
      db_subnet_group_name:  "postgresql_deployment" => "alba_postgresql_deployment"
      parameter_group_name:  "rds-pg" => "alba-rds-pg"
```

### Error
```
2 error(s) occurred:

* module.central-servers.aws_db_subnet_group.postgresql_deployment (destroy): 1 error(s) occurred:

* aws_db_subnet_group.postgresql_deployment: InvalidDBSubnetGroupStateFault: Cannot delete the subnet group 'postgresql_deployment' because at least one database instance: alba-deployment-db is still using it.
        status code: 400, request id: x
* module.central-servers.aws_db_parameter_group.default (destroy): 1 error(s) occurred:

* aws_db_parameter_group.default: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group rds-pg, so the group cannot be deleted
        status code: 400, request id: x
```

### Expected Behavior
- create a new aws_db_parameter_group, apply it to aws_db_instance then delete old aws_db_parameter_group
- create a new aws_db_subnet_group, apply it to aws_db_instance then delete old aws_db_subnet_group

### Actual Behavior
aws_db_parameter_group and aws_db_subnet_group are deleted first, hence dependency issue as in use by aws_db_instance

### Steps to Reproduce
`terraform apply`

**Comment by radeksimko** [comment]
Hi @hsvlz & @atsushi-ishibashi 
I believe this is working more-or-less as intended, but it's hard to tell for sure as I don't see any particular config attached to this issue which I could use to potentially reproduce the behaviour.

While it may look confusing in some contexts (like here), Terraform always deletes old resources before creating new ones if recreation is triggered. The main reason for this default behaviour is that most resources share some kind of namespace and need to have a unique name within that namespace. If the recreation was triggered by any field other than `name` this would make sense.

In general we advise users to use the `lifecycle` block to reverse the ordering of create/destroy operations and randomly generated name, e.g.

```hcl
# untested config, but should work :)

resource "random_string" "name" {
  length = 16
  special = false
  upper = false
}

resource "aws_db_subnet_group" "default" {
  name       = "main-${random_string.name.result}"
  subnet_ids = ["${aws_subnet.frontend.id}", "${aws_subnet.backend.id}"]
  lifecycle {
    create_before_destroy = true
  }
}
```

That said I think we could potentially make some changes in the core schema library and allow resource schemas define what makes resource unique and then make `create_before_destroy` default in certain cases where it makes sense. For that reason I added the upstream label.
