### ISSUE TITLE
Bug when RDS is update from storage type gp2 to io1

### ISSUE THREAD

**Issue by facos86test** [terraform-providers/terraform-provider-aws#2408]
Hi,

I am using the latest version of terraform. 
When I am updating my database from storage_type gp2 to io1, Terraform is incorrectly stopping when the RDS status is storage-optimization. Terraform quits instead of waiting for the process to finish.

```
module.rds.aws_db_instance.default: Modifying... (ID: db-service-data)
  allow_major_version_upgrade:       "" => "true"
  apply_immediately:                 "" => "true"
  engine_version:                    "5.6.27" => "5.6.37"
  final_snapshot_identifier:         "" => "db-service-data-finalsnapshot"
  iops:                              "0" => "1000"
  skip_final_snapshot:               "true" => "false"
  storage_type:                      "gp2" => "io1"
```

Message : 

`* aws_db_instance.default: unexpected state 'storage-optimization', wanted target 'available'. last error: %!s(<nil>)`

**Comment by bflad** [comment]
@facos86test thanks for the report! We do indeed keep a list of expected states in the resource: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_db_instance.go#L1042-L1043

```go
Pending: []string{"creating", "backing-up", "modifying", "resetting-master-credentials",
				"maintenance", "renaming", "rebooting", "upgrading", "configuring-enhanced-monitoring", "moving-to-vpc"},
```

Indeed `storage-optimization` is in this list: http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Status.html

I can submit a quick bugfix PR.

**Comment by facos86test** [comment]
Awesome thanks :-)
