### ISSUE TITLE
Task definitions continuously beening updated

### ISSUE THREAD

**Issue by kazeshini178** [terraform-providers/terraform-provider-aws#2417]
The issue that im experiencing is that terraform (or the aws provider) keeps trying to update my aws_ecs_task_definitions though nothing has changed in them. This causes our ecs service to continuously be updated with the "new" definition.

Our task definitions are read in from a JSON file as such:
```
resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = "${file("task-definitions/service-definition.json")}"
}
```
Only difference I have seen is the order of the environment variables and the inclusion of optional fields.

### Terraform Version
```
Terraform v0.11.0
+ provider.aws v1.3.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- aws_ecs_service
- aws_ecs_task_definition

### Expected Behavior
As the definition hasn't changed I should see an output of `Plan: 0 to add, 0 to change, 0 to destroy`.
This was the output I recieved with versions of Terraform 0.10.8 and 0.9.0

### Actual Behavior
I get the following output `Plan: 2 to add, 2 to change, 2 to destroy`

### Steps to Reproduce
1. Create `aws_ecs_service`
2. Create `aws_ecs_task_definition` linked to `aws_ecs_service`
3. `terraform plan`
4. `terraform apply`
5. `terraform plan`

### References
None from what I could find

**Comment by jurajseffer** [comment]
@kazeshini178 This usually happens when your rendered policy does not exactly equal the document saved in AWS. Retrieve it from AWS using CLI and compare with your rendered version. AWS often accept different syntax etc for legacy reasons but then modify it according to the new format which results in always pending change during plan.

**Comment by Puneeth-n** [comment]
Exactly my thoughts. Elasticsearch has the same issue. Checkout the solution I used for it [here](https://github.com/hashicorp/terraform/issues/3634#issuecomment-312816843)

**Comment by kazeshini178** [comment]
@Puneeth-n I have tried matching aws output like the suggested solution, but with each apply that I run the task definitions environment variables just keep swapping their order causing a pending change.

@jurajseffer checked the AWS CLI output which seems to match my task definition JSON file. Might be missing something. 
Though it doesn't explain why the previous versions mentioned didn't have this issue.

**Comment by Puneeth-n** [comment]
@kazeshini178  can you share your task definition? I will try to fix it. I might know where the problem might be coming from.

**Comment by kazeshini178** [comment]
@Puneeth-n here we go,
`[
    {
        "name": "service",
        "image": "eu-west-2.amazonaws.com/service:latest",
        "cpu": 10,
        "memory": 512,
        "essential": true,
        "mountPoints": [],
        "volumesFrom": [],
        "portMappings": [
            {
                "containerPort": 80,
                "hostPort": 2225,
                "protocol": "tcp"
            }
        ],
        "environment": [ 
            {
                "name": "Service_Username",
                "value": "cX6QTK2W83268Up"
            },
            {
                "name": "Account_Username",
                "value": "CIM"
            },
            {
                "name": "Service_URL",
                "value": "https://secure3.transunionafrica.com/crbws/ke?wsdl"
            },
            {
                "name": "Account_Industry",
                "value": "1346406"
            },  
            {
                "name": "ServerInstance",
                "value": "QA"
            },
            {
                "name": "Account_Code",
                "value": "2110"
            }
        ]
    }
]`

**Comment by Puneeth-n** [comment]
@kazeshini178 Can you check with v1.3.1 #2339

**Comment by kazeshini178** [comment]
@Puneeth-n Just updated to v1.4.0 like 5 minutes before the GitHub email :) 

This seems to have solved the issue after running `terraform apply` once more it no longer indicates a change on the next `terraform plan`. 

Thanks for the assistance :)
