### ISSUE TITLE
Terraform fails to create Aurora PostgreSQL RDS instance

### ISSUE THREAD

**Issue by aronneagu** [terraform-providers/terraform-provider-aws#2419]
Hi there,

I am trying to create and Aurora Postgresql db cluster. I have two resources, one to create the db cluster and another for the database instance. The DB cluster is being created but it fails to create the db instance, with error `invalidParameterCombination: Cannot find version 9.6.3 for aurora` 

### Terraform Version
```
Terraform v0.11.0
+ provider.aws v1.3.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_rds_cluster_instance.cluster_instances
- aws_rds_cluster.default

### Terraform Configuration Files
aurora.tf
```
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 1
  identifier         = "aurora-cluster-postgresql-instance-${count.index}"
  cluster_identifier = "${aws_rds_cluster.default.id}"
  instance_class     = "db.r4.large"
  db_subnet_group_name = "terraform-0081013bf510aede05fe4dc7f7"
}

resource "aws_rds_cluster" "default" {
  cluster_identifier = "aurora-cluster-postgresql"
  engine  = "aurora-postgresql"
  database_name      = "nxtdb"
  skip_final_snapshot = "true"
  master_username    = "nxtmaster"
  master_password    = "test1234"
  db_subnet_group_name = "terraform-0081013bf510aede05fe4dc7f7"
}
```
aws.tf
```
provider "aws" {
    access_key  = "${var.aws_access_key}"
    secret_key  = "${var.aws_secret_key}"
    region      = "${var.aws_region}"
}
```
variables.tf
```
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {
    default = "eu-west-1"
}
```

### Expected Behavior
Terraform to create one Aurora database instance for resource aws_rds_cluster_instance.cluster_instances

### Actual Behavior
Fails to create the RDS instance with the error 
```* aws_rds_cluster_instance.aurora_instances: 1 error(s) occurred:
* aws_rds_cluster_instance.aurora_instances: InvalidParameterCombination: Cannot find version 9.6.3 for aurora
```
This is the output doing terraform apply
```
aws_rds_cluster.default: Creating...
  apply_immediately:               "" => "<computed>"
  availability_zones.#:            "" => "2"
  availability_zones.1924028850:   "" => "eu-west-1b"
  availability_zones.3953592328:   "" => "eu-west-1a"
  backup_retention_period:         "" => "1"
  cluster_identifier:              "" => "aurora-cluster-postgresql"
  cluster_identifier_prefix:       "" => "<computed>"
  cluster_members.#:               "" => "<computed>"
  cluster_resource_id:             "" => "<computed>"
  database_name:                   "" => "nxtdb"
  db_cluster_parameter_group_name: "" => "<computed>"
  db_subnet_group_name:            "" => "terraform-0081013bf510aede05fe4dc7f7"
  endpoint:                        "" => "<computed>"
  engine:                          "" => "aurora-postgresql"
  engine_version:                  "" => "<computed>"
  kms_key_id:                      "" => "<computed>"
  master_password:                 "<sensitive>" => "<sensitive>"
  master_username:                 "" => "nxtmaster"
  port:                            "" => "<computed>"
  preferred_backup_window:         "" => "<computed>"
  preferred_maintenance_window:    "" => "<computed>"
  reader_endpoint:                 "" => "<computed>"
  skip_final_snapshot:             "" => "true"
  storage_encrypted:               "" => "false"
  vpc_security_group_ids.#:        "" => "<computed>"
aws_rds_cluster.default: Still creating... (10s elapsed)
aws_rds_cluster.default: Still creating... (20s elapsed)
aws_rds_cluster.default: Still creating... (30s elapsed)
aws_rds_cluster.default: Still creating... (40s elapsed)
aws_rds_cluster.default: Creation complete after 43s (ID: aurora-cluster-postgresql)
aws_rds_cluster_instance.cluster_instances: Creating...
  apply_immediately:            "" => "<computed>"
  auto_minor_version_upgrade:   "" => "true"
  availability_zone:            "" => "<computed>"
  cluster_identifier:           "" => "aurora-cluster-postgresql"
  db_parameter_group_name:      "" => "<computed>"
  db_subnet_group_name:         "" => "terraform-0081013bf510aede05fe4dc7f7"
  dbi_resource_id:              "" => "<computed>"
  endpoint:                     "" => "<computed>"
  engine:                       "" => "aurora"
  engine_version:               "" => "<computed>"
  identifier:                   "" => "aurora-cluster-postgresql-instance-0"
  identifier_prefix:            "" => "<computed>"
  instance_class:               "" => "db.r4.large"
  kms_key_id:                   "" => "<computed>"
  monitoring_interval:          "" => "0"
  monitoring_role_arn:          "" => "<computed>"
  port:                         "" => "<computed>"
  preferred_backup_window:      "" => "<computed>"
  preferred_maintenance_window: "" => "<computed>"
  promotion_tier:               "" => "0"
  publicly_accessible:          "" => "false"
  storage_encrypted:            "" => "<computed>"
  writer:                       "" => "<computed>"
Error: Error applying plan:

1 error(s) occurred:

* aws_rds_cluster_instance.cluster_instances: 1 error(s) occurred:

* aws_rds_cluster_instance.cluster_instances: InvalidParameterCombination: Cannot find version 9.6.3 for aurora
	status code: 400, request id: 6acdd126-8067-4c96-b682-dc5af6909a3f

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
`terraform apply`

I presume the error is talking about the database engine version, but the error is not very clear. If that is the case, then according to the documentation from AWS, http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html, the Postgresql engine 9.6.3 is supported. I am not particular and would be happy if it would work with *any* database engine. 

UPDATE: If I force the engine_version to be 9.6.1 in both the aws_rds_cluster and aws_rds_cluster_instance, with `  engine_version       = "9.6.1"` in both resource declarations, it seems that aws_rds_cluster_instance IS IGNORING the engine_version parameter. The error when doing terraform apply is 
```
* aws_rds_cluster_instance.cluster_instances: 1 error(s) occurred:
* aws_rds_cluster_instance.cluster_instances: InvalidParameterCombination: The engine version that you requested for your DB instance (9.6.1) does not match the engine version of your DB cluster (9.6.3)
```

**Comment by igrizzli** [comment]
I had same issue, to fix it you need set `engine  = "aurora-postgresql"` for `aws_rds_cluster_instance`

**Comment by aronneagu** [comment]
@igrizzli That fixed it. 
Its strange that I had to define `engine = "aurora-postgresql"` in both `aws_rds_cluster` in `aws_rds_cluster_engine`

**Comment by nsivakrishna** [comment]
when we run the terraform ,it is checking the latest rds instance from resource aws_rds_cluster_instance and getting the 9.6.6 but in aws_rds_cluste resource we 9.3 version so we are getting conflict for both resources .
add the version in both resources and it will run successfully.  

===================
resource "aws_rds_cluster" "default" {
................................................
................................................
 engine               = "aurora-postgresql"
  engine_version       = "9.6.3"

}

resource "aws_rds_cluster_instance" "aurora_instance" {
  ......................................
  ------------------------------
 
  engine               = "aurora-postgresql"
  engine_version       = "9.6.3"
}

version 9.6.3

**Comment by bflad** [comment]
This fix for not properly handling the `engine_version` attribute on normal creation of `aws_rds_cluster` resources (#4139) has been merged into master and will release with v1.14.1 of the AWS provider, likely tomorrow.

**Comment by rocketspacer** [comment]
Still persists in `v1.28.0`

**Comment by romatr** [comment]
Same for `1.39` 🤔

**Comment by bflad** [comment]
Hi @romatr 👋  Can you please fill out a new bug report issue with all the details from the issue template so we can help you troubleshoot? Thanks.

**Comment by romatr** [comment]
@bflad I resolved it with the example above having defined `engine` and  `engine_version` in both `aws_rds_cluster` and `aws_rds_cluster_instance`

**Comment by dsantanu** [comment]
I'm also having the very same issue, in spite of having  _**engine**_ and _**engine_version**_ in both aws_rds_cluster_instance and aws_rds_cluster. I'm keep getting:
`* aws_rds_cluster_instance.aurora_cluster_instance: InvalidParameterCombination: The engine version that you requested for your DB instance (10.4) does not match the engine version of your DB cluster (9.6.8).`

Anything am I missing here?

**Comment by dsantanu** [comment]
Looking further, I see Aurora PostgreSQL _v1.2_ supports PostgreSQL v9.6.8 and Aurora PostgreSQL _v2.0_ supports PostgreSQL v10.4 - does TF support _Aurora PostgreSQL v2.0_ yet? I'm using TF v0.11.7

-San

**Comment by bobdoah** [comment]
@dsantanu I'm seeing something which sounds very similar.
