### ISSUE TITLE
"no such host" / NXDOMAIN error. Terraform retries for more than an hour.

### ISSUE THREAD

**Issue by joernheissler** [terraform-providers/terraform-provider-aws#2427]
Hello!

Terraform took more than an hour to notice that a resource cannot be created.
In my opinion, this should have been an immediate error.

```
* aws_ses_domain_identity.sub: Error requesting SES domain identity verification:
    RequestError: send request failed
caused by: Post https://email.eu-central-1.amazonaws.com/:
    dial tcp: lookup email.eu-central-1.amazonaws.com on 127.0.0.1:53:
    no such host
```

`email.eu-central-1.amazonaws.com` does not exist, my dns server on 127.0.0.1 responds with NXDOMAIN.

### Terraform Version

```
Terraform v0.11.0
+ provider.aws v1.3.1
```

### Affected Resource(s)
- aws_ses_domain_identity

I assume that other resources are affected too.

### Terraform Configuration Files
```hcl
provider "aws" {
    region = "eu-central-1"
}

resource "aws_ses_domain_identityaws_ses_domain_identity" "sub" {
    domain = "test.example.net"
}
```

### Debug Output
https://gist.github.com/joernheissler/e256c0c7704d300ba4c2674575796293

### Expected Behavior
Immediate error.

### Actual Behavior
```
aws_ses_domain_identity.sub: Still creating... (1h18m40s elapsed)
```
And only then it failed.

### Steps to Reproduce
Try above configuration.

### Important Factoids
There is no SES service in eu-central-1. I neglected to select the correct region.

**Comment by bechtoldt** [comment]
I was able to fix this by setting the correct region... (eu-west-1 instead of eu-central-1)

Thanks for the hint!

**Comment by bechtoldt** [comment]
this issue duplicates #2427

**Comment by joernheissler** [comment]
Thanks, I must have missed that one.

**Comment by elisiano** [comment]
@arnoldbechtoldt could you please provide more details of where you specified the region?

**Comment by arnoldbechtoldt** [comment]
@elisiano either ~/.aws/credentials or in the provider definition
