### ISSUE TITLE
Feature: Support AWS PrivateLink for Private Connectivity

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#2460]
[Newly](https://aws.amazon.com/blogs/aws/aws-privatelink-update-vpc-endpoints-for-your-own-applications-services/) announced feature AWS PrivateLink for Private Connectivity.
Builds on https://github.com/terraform-providers/terraform-provider-aws/issues/2222.

**Comment by stevenayers** [comment]
Support added: https://github.com/terraform-providers/terraform-provider-aws/commit/35b273ec2f83f822ac26db93358b9e6b6bc9f5b0

**Comment by ewbankkit** [comment]
Yes, I think this issue can now be closed.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
