### ISSUE TITLE
Support t2.unlimited

### ISSUE THREAD

**Issue by zegl** [terraform-providers/terraform-provider-aws#2491]
Amazon recently announced a new flag for `t2` instances.

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html

### Terraform Version

`Terraform v0.11.0`

### Affected Resource(s)

- aws_instance

**Comment by luhn** [comment]
This option can also be implemented on `aws_launch_configuration`.  See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html#t2-auto-scaling-grp

**Comment by andyspiers** [comment]
The doc you have linked to says how to specify T2 unlimited using a launch-template (which is a brand new EC2 API construct) but it doesn't seem to be possible at all using launch-configurations (the thing that has been possible for years in the autoscaling API)

So to get T2 unlimited on autoscaled instances Terraform would need to support launch-templates, which has been requested in #2505

**Comment by kylelaverty** [comment]
@mrubin That change is in this PR: https://github.com/terraform-providers/terraform-provider-aws/pull/2619

**Comment by mrubin** [comment]
@kylelaverty Thanks!

**Comment by bflad** [comment]
Support for the `aws_instance` resource `credit_specification` argument has been merged into master and will release with v1.16.0 of the AWS provider, likely mid next week. Support for the new `aws_launch_template` resource (also supporting `credit_specification`) was released in v1.15.0 of the AWS provider. 🎉

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by repl-mike-roest** [comment]
@bflad I'm trying to make a module that supports t2.unlimited with a t2 class instance an also supports non t2 instances.  Making the specfication of cpu_credits to standard on a non t2 class instance_type doesn't work.  It seems right now to not be possible to have a module that creates an instance with t2.unlimited on when a t2 is requested and supports non t2 class instances.

**Comment by jayudhandha** [comment]
As per docs, To enable T2 unlimited using **aws_instance** resource of terraform we can do below things. (Correct me if i am wrong)

> credit_specification {
>            cpu_credits = "unlimited"
>   }

But how to enable T2 unlimited using **aws_launch_configuration** resoure of terraform?

**Comment by kylelaverty** [comment]
@jayudhandha Currently AWS does not support the unlimited flag for launch configurations so there is no way for terraform to implement this.

**Comment by andyspiers** [comment]
@jayudhandha - kylelaverty is correct in that AWS does not support T2.unlimited using Launch Configurations, however you can use Launch Templates instead. These were implemented in #2505 which is now merged and released. See https://www.terraform.io/docs/providers/aws/r/launch_template.html

**Comment by jayudhandha** [comment]
@andyspiers Thanks!
