### ISSUE TITLE
Spread Placement Groups for Amazon EC2

### ISSUE THREAD

**Issue by bentterp** [terraform-providers/terraform-provider-aws#2492]
This ws announced yesterday: https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-spread-placement-groups-for-amazon-ec2/

But the SDK documentation doesn't seem to have been updated yet.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#createPlacementGroup-property
> "Strategy — (String)
> The placement strategy.
> 
> Possible values include:
> "cluster"
> 

Similarly, it's not mentioned in the CLI documentation - but it seems to work:
`aws ec2 create-placement-group --group-name "spread1" --strategy "spread" --region eu-central-1`
Following that, the web console shows the expected result.

So the API is available even though the CLI/SDK documentation still hasn't been updated.

**Comment by bflad** [comment]
Hi @bentterp, looking at the current resource code we do not have a validation function on the `strategy` attribute which would prevent `spread` from working out of the box. 👍 

It does look like our [aws_placement_group resource documentation](https://www.terraform.io/docs/providers/aws/r/placement_group.html) could use an update to not specifically say:
> The only supported value is cluster

I will submit a PR to fix that up. Thanks!

**Comment by bflad** [comment]
Documentation PR: #2521
