### ISSUE TITLE
NAT Gateway Data Source not returning all attributes

### ISSUE THREAD

**Issue by colin-lyman** [terraform-providers/terraform-provider-aws#2531]
Using Terraform 0.10.6
Using AWS Provider 1.2

### Terraform Code used to replicate
```hcl
data "aws_nat_gateway" "natGateway" {
  vpc_id = "${data.aws_vpc.vpc.id}"
  tags {
    name = "Name"
    values = "NATGateway"
  }
}
```

### Expected Behavior
As per https://www.terraform.io/docs/providers/aws/d/nat_gateway.html expect public_ip and other address attributes to be returned as well as the actual behaviour.

### Actual Behavior - inside state file
```hcl
  "data.aws_nat_gateway.natGateway": {
                    "type": "aws_nat_gateway",
                    "depends_on": [
                        "data.aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "nat-xxx",
                        "attributes": {
                            "id": "nat-xxx",
                            "state": "available",
                            "subnet_id": "subnet-yyy",
                            "tags.%": "2",
                            "tags.name": "Name",
                            "tags.values": "NATGateway",
                            "vpc_id": "vpc-zzz"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                }
```

```
Error running plan: 1 error(s) occurred:

* aws_security_group.sg_name: 1 error(s) occurred:

* aws_security_group.sg_name: Resource 'data.aws_nat_gateway.natGateway' does not have attribute 'public_ip' for variable 'data.aws_nat_gateway.natGateway.public_ip'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue:
1. Copy data resource code above and use your own NAT Tag Name
2. `terraform apply`

**Comment by colin-lyman** [comment]
Using old Provider version changed to 1.5 and now working.

**Comment by bflad** [comment]
@colin-lyman which version of the Terraform AWS provider are you using? This looks like it was released in 1.4.0 on 11/29:
* https://github.com/terraform-providers/terraform-provider-aws/pull/2209
* https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#140-november-29-2017

You can check `terraform version`. See the [Provider Versions documentation](https://www.terraform.io/docs/configuration/providers.html#provider-versions) for more information if you're unfamiliar.

**Comment by bflad** [comment]
Ha, glad you found it!

**Comment by colin-lyman** [comment]
Thanks for the prompt reply anyway!
