### ISSUE TITLE
"wait_for_ready_timeout" not working for elasticbeanstalk environment.

### ISSUE THREAD

**Issue by fts-shelby-simpson** [terraform-providers/terraform-provider-aws#2532]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
- Terraform v0.11.0
- provider.aws v1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
-aws_elastic_beanstalk_application_version

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
#Provider
provider "aws" {
  #version = "~> 1.5"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
}

#S3 Bucket
resource "aws_s3_bucket" "eb_staging" {
  bucket_prefix = "verdantwebtech-automate-eb1"
}

#S3 Bucket Object
#take zipped folder from working directory and upload it to S3 as etag hashed file
resource "aws_s3_bucket_object" "eb_staging" {
  bucket = "${aws_s3_bucket.eb_staging.id}"
  key    = "v003"
  source = "${var.eb_source_stage_path}"
  etag   = "${md5(file("${var.eb_source_stage_path}"))}"
}

#Application
resource "aws_elastic_beanstalk_application" "mvc-verdant" {
  name        = "mvc-verdant"
  description = "mvc-verdant-desc"
}

#Application Version
resource "aws_elastic_beanstalk_application_version" "mvc_staging" {
  name        = "v003-mvc-verdant"
  application = "mvc-verdant"
  description = "app version staging mvc staging"
  bucket      = "${aws_s3_bucket.eb_staging.id}"
  key         = "${aws_s3_bucket_object.eb_staging.id}"
}

#Environment
resource "aws_elastic_beanstalk_environment" "mvc-staging" {
  #still timeout at 20....
  wait_for_ready_timeout  = "40m"
  name                = "mvc-staging"
  application         = "${aws_elastic_beanstalk_application.mvc-verdant.name}"
  solution_stack_name = "${var.eb_solution_stack}"
  version_label       = "${aws_elastic_beanstalk_application_version.mvc_staging.name}"
 
}
```

### Debug Output

https://gist.github.com/fts-smcleod/8a4a69cb3b39c388e60cf6592102102e
### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
Create new elasticbeanstalk environment using the given source bundle path in resource "aws_s3_bucket_object"
### Actual Behavior
What actually happened?
Timed out while trying to create elasticbeanstalk environment. I set "wait_for_ready_timeout = "40m"" but still times out at 20m. After timing out at 20m even with 40m setting,  I tried terraform apply without "aws_elastic_beanstalk_environment" resource. I then manually did this step in the AWS console. It took just over 20 minutes to setup before running an application update step.
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
No

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234
No

**Comment by stevegroner** [comment]
I am having the same issue.  I have the setting set to 45 mins and it failed at around 22 mins 50 seconds.  If there is a failed instance or two causing EB to have to recreate instances during build, this most likely always takes longer than 20 mins.  Can we please look into this one?  Thank you to all the folks who keep these tings moving forward.

**Comment by tamirble** [comment]
Same issue here... from aws provider version 1.11.0 to 1.25.0

Log:
module.elasticbeanstalk_echo_etl.aws_elastic_beanstalk_environment.etl_beanstalk_environment: Modifying... (ID: e-vqufqwpdyy)
  tags.%:    "1" => "2"
  tags.Name: "" => "devqa-echo-etl"
module.elasticbeanstalk_mathml.aws_elastic_beanstalk_environment.wiris_beanstalk_environment: Modifying... (ID: e-ffpjkwpdqe)
  tags.%:    "1" => "2"
  tags.Name: "" => "devqa-wiris-mathml"
module.elasticbeanstalk_echo_etl.aws_elastic_beanstalk_environment.etl_beanstalk_environment: Still modifying... (ID: e-vqufqwpdyy, 10s elapsed)
module.elasticbeanstalk_mathml.aws_elastic_beanstalk_environment.wiris_beanstalk_environment: Still modifying... (ID: e-ffpjkwpdqe, 10s elapsed)
Releasing state lock. This may take a few moments...

Error: Error applying plan:

2 error(s) occurred:

* module.elasticbeanstalk_mathml.aws_elastic_beanstalk_environment.wiris_beanstalk_environment: 1 error(s) occurred:


* aws_elastic_beanstalk_environment.wiris_beanstalk_environment: Error waiting for Elastic Beanstalk Environment (e-ffpjkwpdqe) to become ready: 2 error(s) occurred:

* 2018-07-02 07:10:36.75 +0000 UTC (e-ffpjkwpdqe) : Service:AmazonCloudFormation, Message:No updates are to be performed.
* 2018-07-02 07:10:37.292 +0000 UTC (e-ffpjkwpdqe) : Environment tag update failed.
* module.elasticbeanstalk_echo_etl.aws_elastic_beanstalk_environment.etl_beanstalk_environment: 1 error(s) occurred:

* aws_elastic_beanstalk_environment.etl_beanstalk_environment: Error waiting for Elastic Beanstalk Environment (e-vqufqwpdyy) to become ready: 2 error(s) occurred:

* 2018-07-02 07:10:36.832 +0000 UTC (e-vqufqwpdyy) : Service:AmazonCloudFormation, Message:No updates are to be performed.
* 2018-07-02 07:10:37.394 +0000 UTC (e-vqufqwpdyy) : Environment tag update failed.

**Comment by stevegroner** [comment]
I have had the same issue, the tagging issue appeared in v1.11 which is when tag updating was released.  This also introduced the issue with using the Name tag in an elastic beanstalk build.  If name is used it creates the issue, renaming Name to name resolves the issue, but it is not placing the value in the correct location.
