### ISSUE TITLE
SQS queues in govcloud don't support ListQueueTags

### ISSUE THREAD

**Issue by dotspec** [terraform-providers/terraform-provider-aws#2534]
Hi there,

### Terraform Version

Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.consul v1.0.0
+ provider.nomad v1.0.0
+ provider.template v1.0.0
+ provider.vault v1.0.0

### Affected Resource(s)
aws_sqs_queue

### Debug Output
Here's the super truncated version from the debug log.
https://gist.github.com/dotspec/d6663e4b7bc34690b9c037fba361fa8c

### Expected Behavior
What should have happened?

The plan should execute successfully.

### Actual Behavior
Like a lot of things in govcloud the SQS endpoint is lagging behind and queues in govcloud don't yet support tags causing any run with this resource to error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1) Create an aws_sqs_queue resource with the aws provider pointing to us-gov-west-1
2) 'terraform plan'
3) Sadness

### Important Factoids
Pinning my AWS provider version to 1.1.0 gets me past the error.

**Comment by bflad** [comment]
Submitted bugfix PR: #3376

**Comment by bflad** [comment]
And just like that its in master! This will be released with v1.10.0 of the AWS provider, likely next week. 🚀

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
