### ISSUE TITLE
Add support for Interface type of AWS VPC Endpoints

### ISSUE THREAD

**Issue by dforsber-p** [terraform-providers/terraform-provider-aws#2545]
Terraform supports `aws_vpc_endpoint`, but it seems it does not support[ Interface type of endpoints](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpce-interface.html), only gateway type of endpoints (s3, dynamodb).

**Comment by ewbankkit** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/2253.

**Comment by dforsber-p** [comment]
Duplicate.
