### ISSUE TITLE
Amazon GameLift support

### ISSUE THREAD

**Issue by Hinidu** [terraform-providers/terraform-provider-aws#2546]
Hello guys! Thank you for your work!
There are no resources for [Amazon GameLift](https://aws.amazon.com/gamelift) and I can't find any related issues or discussions here or in Google.
I would like to implement some GameLift resources and contribute them back if needed. I think I will have some questions especially because some of GameLift resources are immutable and can't be deleted - I didn't use any terraform resources with such properties before and I'm not sure what would be the convenient way to work with such resources.
Does anybody have some thoughts about it?

**Comment by Hinidu** [comment]
> If you could just sum up for every resources you would like to manage how this works on the AWS side, we would better help & guide you :)

Thanks for the feedback! I will post more detailed information about all types of resources that I need soon.

> If those are immutable, how can one object disappear on the AWS side? expiration?

For now matchmaking rule sets just can't be deleted and they are never expired AFAIK. It is quite new part of the service and they have the deletion feature in the backlog.

**Comment by alanmur** [comment]
Hello @Hinidu, I am a Solutions Architect at AWS and I support customers using Amazon GameLift. Please contact me by email at alanmur at amazon dot com for more help using Amazon GameLift. You can also view the documentation at: https://aws.amazon.com/documentation/gamelift/

**Comment by radeksimko** [comment]
@Hinidu FYI: We support `aws_gamelift_build` since [`1.8.0`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018) and I just opened #3327 for `aws_gamelift_fleet`.

Once that gets merged I have `aws_gamelift_alias` ready for PR in a branch. These 3 resources should give us at least some baseline to work with.

**Comment by Hinidu** [comment]
Hi @radeksimko! It looks very nice! Thank you very much!
We don't upload our builds to S3 before uploading them to GameLift but we can add this step for sure. Actually I didn't think whether we will actually upload game server builds using terraform but this opportunity looks interesting.
That's the list of GameLift resource types we are using now: builds, fleets, matchmaking rule sets, matchmaking configurations and queues.
Probably the hardest thing is that matchmaking rule sets are immutable and can't be deleted.
I hope I will have some time soon to use your new resources.

**Comment by bflad** [comment]
Hi Everyone 👋 

The Terraform AWS Provider currently supports multiple GameLift resources for managing this service:

- [`aws_gamelift_alias`](https://www.terraform.io/docs/providers/aws/r/gamelift_alias.html)
- [`aws_gamelift_build`](https://www.terraform.io/docs/providers/aws/r/gamelift_build.html)
- [`aws_gamelift_fleet`](https://www.terraform.io/docs/providers/aws/r/gamelift_fleet.html)
- [`aws_gamelift_game_session_queue `](https://www.terraform.io/docs/providers/aws/r/gamelift_game_session_queue.html)

For future feature requests and bug reports with this service, please submit new GitHub issues following the [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) and [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) issue templates for further triage. Thanks!
