### ISSUE TITLE
aws_cognito_user_pool documentation incorrect

### ISSUE THREAD

**Issue by rcaunt** [terraform-providers/terraform-provider-aws#2579]
The documentation for `aws_cognito_user_pool` is incorrect here:

https://www.terraform.io/docs/providers/aws/r/cognito_user_pool.html#max_value

The actual attribtues are: `min_length` and `max_length` i.e. *length* not *value*.

This is an issue for both String and Number Attribute Constraints.

**Comment by psyvision** [comment]
Ah you beat me to correcting my post saying it was just String and not Number that was wrong :)
