### ISSUE TITLE
import aws_rds_cluster_instance does not import attribute db_subnet_group_name

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#2594]
Terraform 0.11.0

importing a cluster:

terraform -config=resources import aws_rds_cluster_instance.foo df-database-foo

Imported most of the resource, however the resultant statefile has no "db_subnet_group_name" field - this one was omitted to be imported. 

This is for an aurora aws rds database

**Comment by bflad** [comment]
Thanks for the heads up, @gtmtech! I have submitted a bugfix PR for this: #2606

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
