### ISSUE TITLE
Cognito User Pool email_verification_message won't accept more than 2000 characters

### ISSUE THREAD

**Issue by pbracken** [terraform-providers/terraform-provider-aws#2600]
terraform v0.11.1
I am trying to import an html file into email_verification_message and am receiving the following error: "Error: module.cognito.aws_cognito_user_pool.users-pool: "email_verification_message" cannot be longer than 2000 characters"

I think the limit used to be 2000 but was changed to 20000 sometime in the past few months. For reference: http://docs.aws.amazon.com/cognito/latest/developerguide/limits.html

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
