### ISSUE TITLE
Add support for Event Selectors in CloudTrail

### ISSUE THREAD

**Issue by devonbleak** [terraform-providers/terraform-provider-aws#2602]
http://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-management-and-data-events-with-cloudtrail.html#logging-data-events

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudtrail

### Terraform Configuration Files
n/a - this would be an addition to the existing aws_cloudtrail resource

### Expected Behavior
I should be able to add S3 and Lambda data events to a cloudtrail

### Actual Behavior
No way to add these currently

**Comment by bflad** [comment]
Hi @devonbleak, we actually have an open issue for this already (#887) so I would suggest adding a 👍  there for the maintainers to prioritize this feature request in one place. Thanks!

**Comment by devonbleak** [comment]
Closing as a duplicate of #887
