### ISSUE TITLE
Support CloudWatch Log Group KMS Encryption

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#2605]
Amazon has announced support for KMS encryption of CloudWatch logs today: https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-cloudwatch-logs-now-supports-kms-encryption/

### Terraform Version

terraform 0.10+
terraform 1.5.0

### Affected Resource(s)

- `aws_cloudwatch_log_group`

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_log_group" "example" {
  # new configuration
  kms_key_id = "${aws_kms_key.example.id}"
  # additional configuration
}
```

### Expected Behavior

`kmsKeyId` added to `CreateLogGroup` input or call `AssociateKmsKey`/`DisassociateKmsKey` on update.

### Actual Behavior

New feature not supported.

### References

Underlying API support:
* http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogGroup.html#API_CreateLogGroup_RequestSyntax
* http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_AssociateKmsKey.html
* http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DisassociateKmsKey.html

**Comment by bflad** [comment]
Turns out this has been supported since AWS provider version 1.1.0: https://github.com/terraform-providers/terraform-provider-aws/pull/1751

Closing this out!

**Comment by giuseppeborgese** [comment]
Hello just test and 
`  kms_key_id = "${aws_kms_key.example.id}"
`
this doesn't work give back and error of key not found
instead the correct is
`  kms_key_id        = "${aws_kms_key.ssm.arn}"
`
this is also explained in the https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html 
`aws logs associate-kms-key --log-group-name my-log-group --kms-key-id "key-arn"`
