### ISSUE TITLE
Cloudwatch event target can't create multiple with same target_id

### ISSUE THREAD

**Issue by Fladrif** [terraform-providers/terraform-provider-aws#2610]
### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
aws_cloudwatch_event_target

### Terraform Configuration Files
```
resource "aws_cloudwatch_event_target" "first_notification" {
  rule      = "${aws_cloudwatch_event_rule.notification.name}"
  target_id = "SendToSQS"
  arn       = "${aws_sqs_queue.first_notifications.arn}"
}

resource "aws_cloudwatch_event_target" "second_notification" {
  rule      = "${aws_cloudwatch_event_rule.notification.name}"
  target_id = "SendToSQS"
  arn       = "${aws_sqs_queue.second_notifications.arn}"
}
```
### Expected Behavior
Expected to create two cloudwatch event targets to two different sqs queues

### Actual Behavior
Did create both, but when planning afterwards, terraform wouldn't recognize that there were two distinct targets. It would then attempt to change the "second_notification" target to "first_notification" for the "first_notification" resource name which would then result in two cloudwatch event targets to the "first_notification" queue. Further planning would then attempt to change the "first_notification" queue to "second_notification" for the "second_notification" resource. This would loop.

Essentially terraform doesn't have a way to recognize distinct cloudwatch event targets.

Thank you.

**Comment by bflad** [comment]
Hi @Fladrif! In this case, I believe you just want to omit setting `target_id` in those resources or set them to two different values. From the [aws_cloudwatch_event_target resource documentation](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_target.html#target_id): 
> (Optional) The unique target assignment ID. If missing, will generate a random, unique id.

Try that out and let us know how it goes. Thanks!

**Comment by Fladrif** [comment]
Thanks @bflad, that worked.
