### ISSUE TITLE
Terraform Destroy Requires Two Runs to Remove IAM Group with IAM Users

### ISSUE THREAD

**Issue by lostinthecloud** [terraform-providers/terraform-provider-aws#2614]
### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
- `aws_iam_group`
- `aws_iam_group_membership`
- `aws_iam_user`

### Terraform Configuration Files

groupdirectory/group_main.tf
```
resource "aws_iam_group" "group" {
  name = "example-group"
  path = "/"
}

resource "aws_iam_group_membership" "membership" {
  name = "example-group-membership"
  users = [ "${var.user_list}" ]
  group = "example-group"
} 
```

userdirectory/user_main.tf
```
data "template-file" "user_data" {
  vars {
    user_name = "${var.user_name}"
  }
}

resource "aws_iam_user" "user" {
  name = "${data.template-file.user_data.vars.user_name}"
  path = "/"
  force_destroy = false
}
```

moduledirectory/modulemain.tf
```
module "create-user" {
  source = "userdirectory"
  user_name = "user"
}

module "create-group" {
  source = "groupdirectory"
  group_user_list = [ "${module.create-user.user_name}" ]
} 
```

### Expected Behavior
Running `terraform destroy` once should remove the IAM Users, Group, and Group Membership with only one run

### Actual Behavior
Running `terraform destroy` the first time removes the `aws_iam_group_membership` and `aws_iam_user` but the `aws_iam_group` remains and the following error occurs:

```
module.create-group.aws_iam_group.group (destroy): 1 error(s) occurred:

aws_iam_group.group: Error deleting IAM Group example-group: DeleteConflict: Cannot delete entity, must remove users from group first.
status code: 409, request id: 
```

Running `terraform delete` a second time removes the group as well with no DeleteConflict
### Steps to Reproduce
1. Create a config that uses a module to create an `aws_iam_group` and associated `aws_iam_group_membership`. In that same config, use a module to create an `aws_iam_user` and add that user to the `aws_iam_group_membership` `user` list through the module that creates the group.

2. Run `terraform apply` to create the IAM Group, Membership, and User that is a member of the group

3. Run `terraform destroy` to get the DeleteConflict

4. Run `terraform destroy` a second time to successfully remove the IAM Group 

### Important Factoids
Doing the following removes all resources appropriately without getting the DeleteConflict:

1. After creating the IAM Group, Membership, and User, run the following:
```
terraform destroy -target=module.create-group.aws_iam_group_membership.users
```
2. Run `terraform destroy` a second time 

This still requires two `terraform delete` runs to get the appropriate behavior.

### References
[#3295 on Terraform](https://github.com/hashicorp/terraform/issues/3295)
[#3774 on Terraform](https://github.com/hashicorp/terraform/issues/3774)

**Comment by bflad** [comment]
@lostinthecloud does this work better if you tell Terraform the ordering of dependencies? e.g.
```
resource "aws_iam_group_membership" "membership" {
  name = "example-group-membership"
  users = [ "${var.user_list}" ]
  group = "${aws_iam_group.group.name}"
} 
```

The reference inside `group` here should tell Terraform to create group membership after the group is created as well as delete group membership before deleting the group itself. We might be able to perform some retries inside `aws_iam_group` to potentially catch this situation a little better, however adding the correct reference in your configuration should help your situation a lot better.

**Comment by lostinthecloud** [comment]
@bflad Thank you for this information. This resolves the issue. I am going to close this.
