### ISSUE TITLE
BUG?  s3 backend mapping/remote state not working? 

### ISSUE THREAD

**Issue by fewknow** [terraform-providers/terraform-provider-aws#2629]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform -v
Terraform v0.11.1
+ provider.aws v1.5.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- resource 'aws_launch_configuration.ecs' config: unknown resource 'data.terraform_remote_state.security' referenced in variable data.terraform_remote_state.security.ecs_internal_sg_id
- resource 'aws_launch_configuration.ecs' config: unknown resource 'data.terraform_remote_state.security' referenced in variable data.terraform_remote_state.security.consul_client_sg_id

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

```
# Providers

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.default_region}"
}

# Backend

terraform {
  required_version = ">=0.11.0"

  backend "s3" {
   bucket = "cv-terraform-backend"
   key = "security/terraform.tfstate"
   region = "us-east-1"


   dynamodb_table = "cv-terraform-state"
   workspace_key_prefix = "terraform-state"

 }
}
```

```
# Providers

provider "aws" {
  region = "${var.default_region}"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
}

# Backend

terraform {
  required_version = ">=0.11.0"

  backend "s3" {
   region = "us-east-1"
   bucket = "cv-terraform-backend"
   key = "cv/tools_utility"


   dynamodb_table = "cv-terraform-state"
   workspace_key_prefix = "terraform-state"

 }


 data "terraform_remote_state" "security" {
   backend = "s3"
   config {
     bucket = "cv-terraform-backend"
     key    = "terraform-state/development-security/security/terraform.tfstate"
     region = "us-east-1"
   }
 }

}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
I should be able to reference the remote state for security. 

### Actual Behavior
What actually happened?
Appears it can't see the remote state backend. 
This is the file that the remote state should be seeing.  I can download it and it is a correct. 

https://s3.amazonaws.com/cv-terraform-backend/terraform-state/development-security/security/terraform.tfstate

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init` I am just trying to init the state.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
https://github.com/hashicorp/terraform/issues/11682
https://github.com/hashicorp/terraform/issues/15358
https://github.com/hashicorp/terraform/pull/15370

I have referenced all of the above to try and figure this out.  I spend some time renaming a bunch of files because I thought maybe it needed to the be a terraform.tfstate filename.  I have followed the documentation here (https://www.terraform.io/docs/backends/types/s3.html) and setup my remote state following the documentation and set the key according to this.

```key - (Required) The path to the state file inside the bucket. When using a non-default workspace, the state path will be /workspace_key_prefix/workspace_name/key```

I am a previous Atlas user so I am just learning the s3 backend and remote states.  Hoping it is a simple mistake on my side.  Thanks for your time here.

**Comment by fewknow** [comment]
I found my dumb mistake.  As you can see above I put the remote resource in the same block as the terraform Backend.   After moving the data block out on its own everything works.

**Comment by prasaddabbiru** [comment]
@fewknow What did you do, I am facing the same issue. Can you share the modified code, what data block needs to be changed?

**Comment by fewknow** [comment]
@prasaddabbiru  Modified code 

```
# Providers

provider "aws" {
  region = "${data.terraform_remote_state.config.default_region}"
  profile = "${data.terraform_remote_state.config.run_env}"
}

# Backend

terraform {
  required_version = ">=0.11.0"

  backend "s3" {
   region = "us-east-1"
   bucket = "cv-terraform-backend"
   key = "tool/tool_utility"


   dynamodb_table = "cv-terraform-state"
   workspace_key_prefix = "terraform-state"

 }

}

### Terraform linked projects ###

data "terraform_remote_state" "config" {
  backend = "s3"
  config {
    bucket = "cv-terraform-backend"
    key    = "terraform-state/${var.workspace}-config/config/terraform.tfstate"
    region = "us-east-1"
  }
}
```


As you can see I had the remote state as part of the backend block.  I separated them and everything works.
