### ISSUE TITLE
Feature request: support specifying availbility_zone for aws_rds_cluster_instance

### ISSUE THREAD

**Issue by miracle2121** [terraform-providers/terraform-provider-aws#2642]
Hi, 

It seems like we cannot specify `availbility_zone` when creating Aurora instances, per [documentation](https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html). It would be super helpful to have this option because it's available on other kinds of RDS instances.

Thanks,
Ruobing

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
