### ISSUE TITLE
/29 CIDR Not Allowed In Security Group.

### ISSUE THREAD

**Issue by jgamblin** [terraform-providers/terraform-provider-aws#2651]
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.5.0

### Affected Resource(s)
aws_security_group

### Expected Behavior
Allow /29 in security group creation. 

### Actual Behavior
What actually happened?

Error: aws_security_group.SG_Baseline: "ingress.0.cidr_blocks.4" must contain a valid network CIDR, got "66.112.104.108/29"

![screen shot 2017-12-13 at 8 00 15 am](https://user-images.githubusercontent.com/8428124/33943056-8b441132-dfdd-11e7-9a1d-4546964369a6.png)

**Comment by jgamblin** [comment]
Actually this ended up being an issue on our end.

**Comment by phatman168** [comment]
I've got the same issue:

```
resource "aws_security_group_rule" "office_loc1_inbound_sgr" {
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["92.68.201.91/29"]
  security_group_id = "${data.aws_security_group.bastion_securitygroup_id.id}"
  description       = "my test description"
}
```

```
terraform plan

Error: aws_security_group_rule.office_loc1_inbound_sgr: "cidr_blocks.0" must contain a valid network CIDR, got "92.68.201.91/29"
```
```
This cidr is correct and i can add this using the aws api:
aws ec2 authorize-security-group-ingress --group-id ${SGID} --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "IpRanges": [{"CidrIp": "92.68.201.91/29", "Description": "my test description"}]}]'
```
Any help would be appreciated. Thanks

**Comment by chrisLaflamme** [comment]
@phatman168 I just ran into this and found out that there is a max of 6 `cidr_block` entries allowable in the `cidr_block` array.  For example, this threw the error you reported:
```
  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"

    cidr_blocks = [
      "XX.XX.XX.XX/26",
      "XX.XX.XX.XX/24",
      "XX.XX.XX.XX/24",
      "XX.XX.XX.XX/28",
      "XX.XX.XX.XX/32",
      "XX.XX.XX.XX/29",
      "XX.XX.XX.XX/29"
    ]
  }
```
Notice there are 7 blocks.  However, (with the last one removed) this works:
```
  ingress {
    from_port = 80
    to_port   = 80
    protocol  = "tcp"

    cidr_blocks = [
      "XX.XX.XX.XX/26",
      "XX.XX.XX.XX/24",
      "XX.XX.XX.XX/24",
      "XX.XX.XX.XX/28",
      "XX.XX.XX.XX/32",
      "XX.XX.XX.XX/29"
    ]
  }
```
Hopefully that helps you, or someone in the future.
