### ISSUE TITLE
Documentation resource aws_waf_rule is wrong

### ISSUE THREAD

**Issue by hegyre** [terraform-providers/terraform-provider-aws#2655]
Hi there,

### Terraform Version
N/A

### Affected Resource(s)
aws_waf_rule

### Terraform Configuration Files
```hcl
resource "aws_waf_rule" "waf_rule_pre_ca_cdn" {

  name        = "${var.project}-wafrule-pre-ca-cdn"
  metric_name = "${var.project}wafruleprecacdn"

  predicates {
    data_id = "${aws_waf_ipset.dcsie-wafipset-all-cdn.id}"
    negated = false
    type    = "IPSet"
  }

  predicates {
    data_id = "${aws_waf_ipset.waf_ipset_pre_ca_cdn.id}"
    negated = false
    type    = "IPMatch"
  }
```

### Debug Output
* aws_waf_rule.waf_rule_pre_ca_cdn: "predicates.0.type" must be one of IPMatch | ByteMatch | SqlInjectionMatch | SizeConstraint | XssMatch

### Expected Behavior
Terraform AWS Provider is fine, but the doc is wrong

### Actual Behavior
Doc is saying:
https://www.terraform.io/docs/providers/aws/r/waf_rule.html

Argument Reference:
predicates - (Optional) One of ByteMatchSet, IPSet, SizeConstraintSet, SqlInjectionMatchSet, or XssMatchSet objects to include in a rule.

Nested Blocks:
type - (Required) The type of predicate in a rule, such as ByteMatchSet or IPSet

It should be IPMatch, not IPSet, as per the example in the same doc.
Also, the Argument reference is IMHO wrong since it attempt a nested block, right ?

**Comment by apparentlymart** [comment]
Thanks for reporting this, @hegyre!

Indeed it does look like there are two problems here: the list of supported predicate types is not correct, and `predicates` should be documented as being a nested block which is documented separately below.
