### ISSUE TITLE
Route 53: Add name to Attribute Reference in docs

### ISSUE THREAD

**Issue by spanktar** [terraform-providers/terraform-provider-aws#2660]
The "name" attribute is not referenced in the docs, but works fine:
https://www.terraform.io/docs/providers/aws/r/route53_record.html#attributes-reference

```
output "(RDS) aws_route53_record.rds_aurora_mysql_cluster_endpoint_ro" {
  value ="${local.zone_id}_${aws_route53_record.rds_aurora_mysql_cluster_endpoint_ro.name}_CNAME"
}
```

outputs

```
aws_route53_record.rds_aurora_mysql_cluster_endpoint_ro 1234567890_spanky-mysql-ro_CNAME
```

which is great because the FQDN doesn't match the "name", which what I need

### Terraform Version
0.10.7

See also:
https://github.com/terraform-providers/terraform-provider-aws/issues/1031

**Comment by apparentlymart** [comment]
Hi @spanktar,

In general you can always reference any argument listed in "Argument Reference" as an attribute too. The "Attributes Reference" section discusses _additional_ attributes that can _only_ be referenced from interpolation expressions.

For some resources we have some text under the heading that attempts to clarify this ("The following additional attributes are exported:") but I notice that isn't true for `aws_route53_record`. We can update the docs for this resource to include that clarifying introduction, though indeed I'm sure there are other resources where this is true too and so this won't be solved fully-generally until a future point where more of the docs are being generated programmatically. This is a long-term goal, but not a current focus.

**Comment by spanktar** [comment]
Ah, that's good to know! Thanks. You can close this, but I think adding that info to the docs would be beneficial for future generations.

Cheers!
