### ISSUE TITLE
aws_elastic_beanstalk_environment SSHSourceRestriction setting causing modifications

### ISSUE THREAD

**Issue by mrubin** [terraform-providers/terraform-provider-aws#2682]
I have an `aws_elastic_beanstalk_environment` with the following settings. I just added the `SSHSourceRestriction` setting and it seems to be causing Terraform to think there's a change needed each time I run `plan`/`apply`.

```
 resource "aws_elastic_beanstalk_environment" "website" {
   setting {
     namespace = "aws:autoscaling:launchconfiguration"
     name = "SecurityGroups"
     value = "${aws_default_security_group.default.id},${aws_security_group.website.id}"
   }

   setting {
     namespace = "aws:autoscaling:launchconfiguration"
     name = "SSHSourceRestriction"
     value = "tcp, 22, 22, ${aws_security_group.bastion.id}"
 }
```

Output (with unrelated settings omitted):

```
  ~ aws_elastic_beanstalk_environment.website
      setting.1224657411.name:      "SSHSourceRestriction" => ""
      setting.1224657411.namespace: "aws:autoscaling:launchconfiguration" => ""
      setting.1224657411.resource:  "" => ""
      setting.1224657411.value:     "tcp,22,22,null" => ""
      setting.1507604600.name:      "" => "SSHSourceRestriction"
      setting.1507604600.namespace: "" => "aws:autoscaling:launchconfiguration"
      setting.1507604600.resource:  "" => ""
      setting.1507604600.value:     "" => "tcp, 22, 22, sg-44d4e131"


Plan: 0 to add, 1 to change, 0 to destroy.
```

Terraform version:

```
Terraform v0.11.1
+ provider.aws v1.5.0
```

**Comment by apparentlymart** [comment]
Hi @mrubin! Thanks for reporting this.

At first I thought this was a problem with the remote API normalizing the value to remove the spaces, but I see also that your `sg-44d4e131` is being replaced by `null` in the API response too.

I think the crux of this issue will be figuring out where that `null` is coming from, since it seems like something is going amiss here.

**Comment by mrubin** [comment]
I had taken the string verbatim from [the documentation](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html):

```
Example: tcp, 22, 22, 54.240.196.185/32

Example: tcp, 22, 22, my-security-group
```

I should try removing it, but agree that the `null` seems like a problem.

Thank you!

**Comment by mrubin** [comment]
Any updates on this?

**Comment by mrubin** [comment]
@apparentlymart Any updates on this?

**Comment by saxonww** [comment]
This is a longstanding issue, since at least https://github.com/hashicorp/terraform/issues/8950#issuecomment-250731768. Also referenced in #280, #555, and #1471.

The only good workaround is to use a CIDR mask instead of a security group, obviously that won't work for everyone though.

**Comment by mrubin** [comment]
Per AWS support, this is a known bug (that the support person was also able to reproduce). They don't have an ETA on when it will be addressed, but it will show up here: https://aws.amazon.com/releasenotes/?tag=releasenotes%23keywords%23aws-elastic-beanstalk

**Comment by debu99** [comment]
Any updates on this?

**Comment by neechbear** [comment]
I followed this up with our AWS earlier this month. It appears to have been fixed a few days ago, which is confirmed by my testing.

```
      setting.1234567890.name:                                              "" => "SSHSourceRestriction"
      setting.1234567890.namespace:                                         "" => "aws:autoscaling:launchconfiguration"
      setting.1234567890.resource:                                          "" => ""
      setting.1234567890.value:                                             "" => "tcp,22,22,sg-01234567890abcdef"
```

Additional apply did the right thing (i.e., it didn't make any further changes.
