### ISSUE TITLE
Requesting extended support for Kinesis Firehose Delivery Stream S3 Backup

### ISSUE THREAD

**Issue by KevinMellott91** [terraform-providers/terraform-provider-aws#2699]
When using the _aws_kinesis_firehose_delivery_stream_ resource type, you can configure a S3 backup for both Redshift (_redshift_configuration_) and Elasticsearch (_elasticsearch_configuration_) resources. However, it is currently not possible to configure a S3 backup location for S3 resource types.

Adding support for this within the _extended_s3_configuration_ type would be greatly appreciated.

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kinesis_firehose_delivery_stream
- extended_s3_configuration
- s3_backup_configuration

### Expected Behavior
The behavior would act the same as it does for the Redshift and Elasticsearch S3 backup configuration. This is a setting that allows ALL records received by Firehose to be archived in S3 (regardless of the transformation results).

### Actual Behavior
This configuration is not currently supported for the extended_s3_configuration resource type.

**Comment by bflad** [comment]
Support has been merged in via #2987 and will be released with v1.14.0 of the AWS provider, likely later this week. 🎉

**Comment by bflad** [comment]
This has been released in [version 1.14.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1140-april-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
