### ISSUE TITLE
aws_s3_bucket server_side_encryption_configuration key is not recognized

### ISSUE THREAD

**Issue by icornett** [terraform-providers/terraform-provider-aws#2704]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

- aws_s3_bucket

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" "sample-state-bucket" {
  bucket = "upwork-demo-${var.environmentName}"
  
  versioning {
    enabled = true
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm     = "aws:kms"
      }
    }
  }

  tags {
    Environment = "${var.environmentName}"
  }

  lifecycle {
    #    prevent_destroy = true
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
https://gist.github.com/icornett/2873038776bcf9be8211f4047e587e8c

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
S3 bucket should be created with encryption, per documentation
### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform plan`
### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by trung** [comment]
You are using a very old version of `terraform-provider-aws`: terraform-provider-aws_v1.3.1_x4
Please take the latest 1.6.0 which supports `server_side_encryption_configuration`

**Comment by icornett** [comment]
That does appear to be the case, so it's still a bug as the behavior is that it's supposed to be automatically upgraded if it wasn't explicitly defined, right?  I had to pin it to that version for it to download.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by trung** [comment]
By design it won't perform auto upgrade unless being asked. 
You can find out more info at https://www.terraform.io/docs/commands/init.html under Plugin Installation section

**Comment by jen20** [comment]
Hi @icornett, @trung is correct here - you'll need to update the provider with `terraform init` to a newer version. Thanks for opening an issue!

**Comment by richfromm** [comment]
I am using `Terraform v0.11.1` and `provider.aws v1.6.0`. I specified the latter with:
```
provider "aws" {
   version = "~> 1.6"
```

When running `terraform init`, I see it grabbing the requested version of the provider:
```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.6.0)...

Terraform has been successfully initialized!
```

But I still get the same error that was reported here:
```
invalid or unknown key: server_side_encryption_configuration
```
