### ISSUE TITLE
ALB target group defaults changed for healthy/unhealthy thresholds

### ISSUE THREAD

**Issue by wvidana** [terraform-providers/terraform-provider-aws#2712]
Hi,

So this commit changed the target group default parameters https://github.com/terraform-providers/terraform-provider-aws/commit/79467dc32944ceb42acaa60bb91da86fa974ef22

This makes _old_ code to have pending changes, when there are non. (By _old_ I mean code applied with aws provider <1.3 and revisited now on 1.6). Also the defaults mismatch with the official AWS API for Application Load Balancer.

Is it necessary to define here defaults? Not sure if the Go SDK can provide those or the API call can relay on leaving them empty. In example, the `UnhealthyThresholdCount` now is forced to be 3, when it used to be 2, and AWS official API defaults to 2 for ALB (though that gets tricky for network load balancers, which I guess was the reason of the change).

If there is no other way around it, I wouldn't mind on updating my module to _force_ my own default, though I would rather relay on official's AWS defaults, which differs between ALB and NLB. 

### Terraform Version
`Terraform v0.11.1`
`provider.aws: version = "~> 1.6"`

### Affected Resource(s)
- aws_alb_target_group

### Expected Behavior
No code changes -> no terraform changes

### Actual Behavior
`terraform plan` wants to make changes when there are no code changes.

### References
- Introduced in 1.3.0 https://github.com/terraform-providers/terraform-provider-aws/pull/2251
 - AWS API Reference (API Version 2015-12-01) https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

**Comment by woqer** [comment]
This PR https://github.com/terraform-providers/terraform-provider-aws/pull/2380 seems to fix it for matcher, path and timeout, but NOT for the healthy and unhealthy thresholds yet.
