### ISSUE TITLE
Feature request: Implement RoutingConfig in aws_lambda_alias

### ISSUE THREAD

**Issue by mryanmurphy** [terraform-providers/terraform-provider-aws#2736]
A recent update to AWS SDK allows an alias to specify multiple versions and weights to route requests to other than the FunctionVersion. 

Use case: This makes it trivial to minimize impact when cutting over between different versions of code within Lambda. Users of terraform would want to leverage this ability through the aws provider instead of manually.

http://docs.aws.amazon.com/lambda/latest/dg/lambda-traffic-shifting-using-aliases.html
http://docs.aws.amazon.com/lambda/latest/dg/API_CreateAlias.html#SSS-CreateAlias-request-RoutingConfig
http://docs.aws.amazon.com/lambda/latest/dg/API_UpdateAlias.html#SSS-UpdateAlias-request-RoutingConfig

**Comment by bflad** [comment]
This has been implemented into master via #3316 and will release with version 1.26.0 of the AWS provider, later this week! 🚀

**Comment by bflad** [comment]
This has been released in [version 1.26.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1260-july-04-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
