### ISSUE TITLE
Feature request: support API Gateway VPC Links

### ISSUE THREAD

**Issue by ChrisF987** [terraform-providers/terraform-provider-aws#2738]
AWS now has API Gateway VPC Links that connect to an internal Network Load Balancer, as per this link - https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-endpoint-integrations-with-private-vpcs/

It would be great to have this in terraform too.

**Comment by ewbankkit** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/2512

**Comment by ewbankkit** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/2511 I think.
