### ISSUE TITLE
d/aws_iam_server_certificate: add support for retrieving public key

### ISSUE THREAD

**Issue by trung** [terraform-providers/terraform-provider-aws#2742]
Currently the data source calling [API_ListServerCertificates](https://docs.aws.amazon.com/IAM/latest/APIReference/API_ListServerCertificates.html), however the response doesn't contain the `CertificateBody` which is the public key certificate nor `CertificateChain` which is the public key certificate chain.

Additional invocation to [API_GetServerCertificate](https://docs.aws.amazon.com/IAM/latest/APIReference/API_GetServerCertificate.html) would fill the gap.

The reason public key certificate is required is to [configure Back-end Instance Authentication](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-create-https-ssl-load-balancer.html) for ELB

Complement https://github.com/hashicorp/terraform/pull/7458

**Comment by trung** [comment]
PR #2749 merged

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
