### ISSUE TITLE
Support tagging of Elastic IP addresses

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#2744]
[Recently announced](https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-virtual-private-cloud-vpc-now-allows-customers-to-tag-their-elastic-ip-addresses/) support for tagging Elastic IP addresses.
Add support in Terraform.

**Comment by bflad** [comment]
Submitted PR #2768 which is dependent on AWSK SDK 1.12.53 (#2767)

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
