### ISSUE TITLE
Error configuring the backend "s3": Not a valid region: eu-west-3

### ISSUE THREAD

**Issue by pbramy** [terraform-providers/terraform-provider-aws#2745]
After rebuilding the plugin for region eu-west-3.
We are able to create ressources .
One problem is still open is the usage of the region eu-west-3 in the S3 backend 

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
S3 backend 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
terraform {
  backend "s3" {
    bucket = "deploystate"
    key    = "AWS/PARIS/tfstate"
    region = "eu-west-3"
  }
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
What should have happened?
We expect to use the S3 backend in the region eu-west-3

### Actual Behavior
What actually happened?
After rebuilding the plugin with the fix to introduce the eu-west-3, terrafrom apply is OK for ressources creation. 
Last problem is the S3 backend usage in the region.
 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

**Comment by jen20** [comment]
Hi @pbramy! Thanks for opening an issue. This is actually a bug with upstream Terraform, since the backends are contained there. I'll submit a pull request and link back to this issue, but unfortunately I can't merge it there.

**Comment by jen20** [comment]
In the meantime, you can use the `skip_region_validation` parameter on the back end to avoid hitting this error.

**Comment by pbramy** [comment]
@jen20 Thank a lot for your feedback. I tried the following in the main.tif without success.. Did I do wrong ?

main.tf 
terraform {
  backend "s3" {
    bucket = "deploystate"
    key    = "AWS/PSG/tfstate"
    region = "eu-west-3"
  }
}

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
  skip_region_validation = "true"
#  version    = "1.6"
}

**Comment by loivis** [comment]
`skip_region_validation = true`
instead of
`skip_region_validation = "true"`?

**Comment by jen20** [comment]
@loivis is correct here - the relevant code is: https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/backend.go#L139-L144 - you'll need a literal `true` instead of a quoted string.

**Comment by pbramy** [comment]
Dear all,
Something seems wrong in my configuration.. 
Terraform v0.11.1
+ provider.aws v1.6.0
+ provider.null v1.0.0
+ provider.template v1.0.0

plugin.
116256115 Dec 21 21:27 terraform-provider-aws_v1.6.0_x4

backend declaration... 
terraform {
  backend "s3" {
    bucket = "deploystate"
    key    = "AWS/PSG/tfstate"
    region = "eu-west-3"
    skip_region_validation = true
  }
}
and still the following error..
Error initializing new backend: Error configuring the backend "s3": 1 error(s) occurred:
* : invalid or unknown key: skip_region_validation

I moved the declaration in provider 
provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.region}"
  skip_region_validation = true
}
And get the error..

Error initializing new backend:
Error configuring the backend "s3": Not a valid region: eu-west-3

Last post for 2017... let's see if 2018 will be better..
Happy new year.

**Comment by Ninir** [comment]
Hi folks,

Regarding @pbramy's error, there are multiple things to note:

* `skip_region_validation` at the `terraform {}` configuration level, was merge in November 2017 (https://github.com/hashicorp/terraform/pull/16757) and is only present in Terraform 0.11.2 which is not yet released as per https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#readme (look for 16757)
* `skip_region_validation` at the `provider {}` configuration level (for AWS), was merged in January back in January 2017 (https://github.com/hashicorp/terraform/pull/11358)
* `eu-west-3` was merged recently in https://github.com/terraform-providers/terraform-provider-aws/pull/2707 and is only present in the AWS provider 1.6.1 which is not yet released.

Hope it helps and makes sense. We just need a bit more patience here :)

Happy Terraforming!

**Comment by pbramy** [comment]
Hi @Ninir,
Thanks you for your feedback and ready to wait Terraform 0.11.2 and AWS provider 1.6.1.
We are not stuck based on the github integration we performed previously !
We tested the relocation of an Oracle workload from eu-west-1 to eu-west-3 without any problem. We will adjust our setup when the versions will be out.
Thanx again and Happy New Year 2018 !

**Comment by tsellers-r7** [comment]
@Ninir - It looks like the only thing holding up the use of `eu-west-3` is the release of Terraform 0.11.2.  Is this correct?  If so, do you know if there is a scheduled release for this version or a way to determine the expected timeline?

Thanks.

**Comment by bflad** [comment]
Support for the eu-west-3 region in the S3 backend was released in [Terraform core 0.11.3](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0113-january-31-2018). Closing this out!
