### ISSUE TITLE
aws_route53_record does not generate diff if record exists but is missing in statefile.

### ISSUE THREAD

**Issue by anshprat** [terraform-providers/terraform-provider-aws#2760]
### Terraform Version
terraform -v
Terraform v0.11.1
+ provider.aws v1.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_record 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

in statefile a)

resource "aws_route53_record" "domain_txt_record" {
  provider = "aws.central"
  zone_id  = "${data.terraform_remote_state.dns.domaindotcom_zone_id}"
  name     = "domain.com"
  type     = "TXT"
  ttl      = "10"
  records  = ["record1","record2"]
}


in statefile b)

resource "aws_route53_record" "domain_spf_record" {
  provider = "aws.central"
  zone_id  = "${data.terraform_remote_state.dns.domaindotcom_zone_id}"
  name     = "domain.com"
  type     = "TXT"
  ttl      = "10"
  records  = ["record3"]
}

```

### Expected Behavior
When a particular record exists in route53 but is not known to the statefile in context, TF should be able to say that there is a diff.

### Actual Behavior
If the remote resource status is not present in the statefile, TF does not figure out that the resource actually exists, and just shows a new create action instead of a modify action. As a result, records are overwritten when applied.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1) Create a aws_route53_record  in a specific statefile. Do a tf apply.
2) Create a conflicting aws_route53_record  but in a different location and statefile. Do a tf plan / apply.

**Comment by jen20** [comment]
Hi @anshprat! I believe this is the correct course of action for Terraform - it will not attempt to modify things which are not under management. However, in this edge case, the create API will update an existing resource based no something Terraform does not know about. Taking management of the existing resource is something that would deviate from the rest of Terraform, though an apply-time check during Create to ensure we aren't overwriting anything may be valid. This really is a question for @catsby or @radeksimko, though.

**Comment by catsby** [comment]
Hello – @jen20 is correct in that this is correct behavior for Terraform, e.g. the state file is consulted to see if something exists, and unless something is found then no matching remote check is made. 

Some API services will return an error if you attempt to create a resource that matches a resource that already exists. It so happens that all create/update Route53 record calls go through a "change" call and not explicit create/update calls, which complicates this specific case. While we could possibly check before hand if matching record exists, I'm not sure we can assume that is the desire of the user (to see an error). 

In this case I think we could consider a change that introduced a check before hand, and returned an error if a matching record is found. That said, I don't believe the current behavior is wrong either.

I'm going to close this issue for now. Thank you for opening it and for discussion. If yourself or anyone else would like to send a pull request that does a check before hand we would certainly consider it.

Thanks!
