### ISSUE TITLE
aws_elb add support for vpc_id

### ISSUE THREAD

**Issue by samirspatel** [terraform-providers/terraform-provider-aws#2774]
It would be nice to have support to deploy an elastic load balancer into a VPC by specifying `vpc_id` as a parameter to `resource aws_elb`

**Comment by loivis** [comment]
`aws_elb` supports `subnets` argument, which is the scenario for vpc. If you want `vpc_id`, how do you want `elb` to decide which subnets to go?

**Comment by jen20** [comment]
Hi @samirspatel! The underlying API here takes subnet identifiers, as @loivis says - adding a VPC idea is probably not a good idea as it will deviate from the underlying API. If you only have a VPC ID, you can use an `aws_subnet` data source to find subnet IDs into which to deploy your ELB. Thanks for opening an issue here!
