### ISSUE TITLE
s3 logging as variable

### ISSUE THREAD

**Issue by AliGrab** [terraform-providers/terraform-provider-aws#2785]
Hello,

I'm trying to create generic S3 module so I can toggle S3 features on the referenced modules.
But I run out into this error which is not supposed to happen in the first place, because the `logging` type is map.

### Terraform Version
```
Terraform v0.11.1
+ provider.aws v1.6.0
```

### Affected Resource(s)
- aws_s3_bucket

### Terraform Configuration Files
```hcl
variable "logging" {
  default = {}
}

resource "aws_s3_bucket" "s3_foo" {
  bucket = "foo"

  logging = "${var.logging}"
}
```

### Debug Output
```
Error: aws_s3_bucket.s3_bucket: logging: should be a list
```

### Expected Behavior
It should pass and get the logging arguments from `logging` variable. 

### Actual Behavior
Getting an error because of the variable type.

### Steps to Reproduce
1. `terraform plan`

**Comment by loivis** [comment]
It should be a set of `logging` from code:
https://github.com/terraform-providers/terraform-provider-aws/blob/dddc588b53d0de7421040313d2ec7d54ca55bd4a/aws/resource_aws_s3_bucket.go#L185
Instead of using variable, try to set `logging` directly and `plan` will show this a bit more clear that it's really not a `map`.
```
      logging.#:                        "2"
      logging.3062530799.target_bucket: "target_bucket1"
      logging.3062530799.target_prefix: "target_prefix1"
      logging.3460139688.target_bucket: "target_bucket2"
      logging.3460139688.target_prefix: "target_prefix2"
```
So changing variable type to `list` should make it right.
```
variable "logging" {
  default = [{
    target_bucket = "target_bucket1"
    target_prefix = "target_prefix1"
  },
    {
      target_bucket = "target_bucket2"
      target_prefix = "target_prefix2"
    },
  ]
}
```

**Comment by jen20** [comment]
Hi @AliGrab! @loivis has the correct idea here - the syntax of HCL makes this appear like a map, but in fact is not. If you don't want to expose this to your module consumers, you could put the list in the assignment rather than the variable, too:

```hcl
logging = ["${var.logging}"]

...

variable "logging" {
  default = {
    target_bucket = "target_bucket1"
    target_prefix = "target_prefix1"
  }
}
```

**Comment by AliGrab** [comment]
Thank you @loivis and @jen20 for your help.
Really appreciate it.

**Comment by goforgold** [comment]
Is this possible to enable/disable logging based on the value of variable say `is_logging_enabled`?

Really can't figure this out. Need help!

**Comment by exolab** [comment]
@goforgold I realize this is a very late answer, maybe it helps someone else.
```
dynamic "logging" {
  for_each = var.logging_enabled == true ? [1] : []
  content {
    target_bucket = "your-bucket-name"
    target_prefix = "s3/${var.name}/"
  }
}
```
