### ISSUE TITLE
Removing the vpc_id attribute from aws_vpn_gateway does not detach it

### ISSUE THREAD

**Issue by cswingler** [terraform-providers/terraform-provider-aws#2799]
### Terraform Version
v0.11.1
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_vpn_gateway

### Terraform Configuration Files
```hcl
provider "aws" { 
  region = "us-east-1"
  profile = "sproutdev"
  shared_credentials_file = "~/.aws/credentials"
  allowed_account_ids = ["<removed>"] # important!

}
data "aws_caller_identity" "current" {}

output "dev_account_id" {
  value ="<removed>"
}

output "account_id" {
  value = "${data.aws_caller_identity.current.account_id}"
}

# Here's what we start with:
resource "aws_vpc" "cswingler_test_vpnc" {
  cidr_block           = "192.0.2.0/24"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags {
    Name = "cswingler_test_vpnc"
  }
}

resource "aws_customer_gateway" "cswingler_gateway_one" {
  bgp_asn    = 65000
  ip_address = "198.51.100.1"
  type       = "ipsec.1"

  tags {
    Name = "cswingler_gateway_one"
  }
}

resource "aws_vpn_gateway" "cswingler_test_vpnc" {
  # Commenting out because we're trying to move this attachment to cswingler_test_vpnc2 below:
  #vpc_id = "${aws_vpc.cswingler_test_vpnc.id}"

  tags {
    Name = "cswingler_test_vpnc"
  }
}

resource "aws_vpn_connection" "cswingler_test_vpnc" {
  customer_gateway_id = "${aws_customer_gateway.cswingler_gateway_one.id}"
  static_routes_only  = true
  type                = "ipsec.1"
  vpn_gateway_id      = "${aws_vpn_gateway.cswingler_test_vpnc.id}"

  tags {
    Name = "cswingler_test_vpnc"
  }
} 


# Create a new customer_gateway/vpn_gateway/vpn_connection set:
resource "aws_customer_gateway" "cswingler_gateway_two" {
  bgp_asn    = 65000
  ip_address = "198.51.100.2"
  type       = "ipsec.1"

  tags {
    Name = "cswingler_gateway_two"
  }
}

resource "aws_vpn_gateway" "cswingler_test_vpnc2" {
  vpc_id = "${aws_vpc.cswingler_test_vpnc.id}"

  tags {
    Name = "cswingler_test_vpnc2"
  }
}

resource "aws_vpn_connection" "cswingler_test_vpnc2" {
  customer_gateway_id = "${aws_customer_gateway.cswingler_gateway_two.id}"
  static_routes_only  = true
  type                = "ipsec.1"
  vpn_gateway_id      = "${aws_vpn_gateway.cswingler_test_vpnc2.id}"

  tags {
    Name = "cswingler_test_vpnc2"
  }
}

```

### Expected Behavior
Terraform should have detached the VPC from VPN connection `cswingler_test_vpnc`, then allowed me to attach it to `cswingler_test_vpnc2`.

### Actual Behavior
Terraform does not acknowledge the now deleted `vpc_id` on the VPC resource `cswingler_test_vpnc`, and tries to attach two VPN gateways to the same VPC, which is not legal in AWS.

### Steps to Reproduce
1. Create an `aws_customer_gateway`, `aws_vpn_gateway`, and `aws_vpn_connection`, and set the `vpc_id` attribute on the  `aws_vpn_gateway` resource to a VPC.
2. Create a second `aws_vpn_gateway`. 
3. Set the `vpc_id` attribute on the new `aws_vpn_gateway` to the same VPC as step 1, and comment out the `vpc_id` attribute on  the `aws_vpn_gateway` in step 1.
4. Run plan, you will see that the `aws_vpn_gateway` created in step 1 is unchanged, but the new one is going to get a VPC attachment.
5. Run apply, which will fail. 

### Plan output

https://gist.github.com/cswingler/34b465c12dcd0c8432ba5dc1f25b8c85

### Apply output

https://gist.github.com/cswingler/65b89785a9cb485aa23664338ffd7ea9

#### Error output:

```
Error: Error applying plan:

1 error(s) occurred:

* aws_vpn_gateway.cswingler_test_vpnc2: 1 error(s) occurred:

* aws_vpn_gateway.cswingler_test_vpnc2: InvalidVpcState: VPC vpc-e5fdd89d is currently attached to the Virtual Private Gateway
	status code: 400, request id: a2d1c659-d18b-4340-ab9f-74e7451ec3be

```

**Comment by atsushi-ishibashi** [comment]
`vpc_id` in `aws_vpn_gateway` is computed resource so it is set via `aws_vpn_connection`.
You can solve this problem by specifying only one `aws_vpn_connection` and changing `vpn_gateway_id` of it.

**Comment by cswingler** [comment]
The problem with that solution is rollback - if I delete the existing `aws_vpn_connection` I lose its private key, and if I end up having to swing the VPN connection I'm changing back to the old  connection, I have no way to do that without recreating a new `aws_vpn_connection` and supplying the new credentials to the other side of the VPN tunnel. 

It's definitely not ideal.

**Comment by loivis** [comment]
Did you try to set vpc_id to empty string like `vpc_id = ""`? It might do the trick according to below codes:
https://github.com/terraform-providers/terraform-provider-aws/blob/755e04d2b2c8660316f9477b9085b589a768a17c/aws/resource_aws_vpn_gateway.go#L107-L117
https://github.com/terraform-providers/terraform-provider-aws/blob/755e04d2b2c8660316f9477b9085b589a768a17c/aws/resource_aws_vpn_gateway.go#L167-L172
I tried to achieve similar logic if `vpc_id` is not set but didn't really get that.

**Comment by cswingler** [comment]
@loivis that indeed worked, thanks!

I assume this is the intended behavior?

**Comment by loivis** [comment]
It's the logic of current code. I think it's better to handle the scenario when `vpc_id` is unset afterwards.
