### ISSUE TITLE
Kibana Attribute Not available for elasticsearch 

### ISSUE THREAD

**Issue by fewknow** [terraform-providers/terraform-provider-aws#2802]
I want to be able to reference the Kibana endpoint for DNS or anything else I would like use it for later.  Currently there is only id, access_policies and domain_name that are attributes that are exported. 

Can we add kibana endpoint? 
$ terraform -version
Terraform v0.11.1
+ provider.aws v1.6.0

```
  id = esd-policy-dev-logs
  access_policies = {"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":"*"},"Action":"es:*","Resource":"arn:aws:es:us-east-********/*"}]}
  domain_name = dev-logs
```

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
