### ISSUE TITLE
aws_s3_bucket_policy saves resource to state even if 400 error received

### ISSUE THREAD

**Issue by sjauld** [terraform-providers/terraform-provider-aws#2819]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.11.1
+ provider.aws v1.6.0
```

### Affected Resource(s)
- aws_s3_bucket_policy

### Terraform Configuration Files
_Note:  the aws_s3_bucket_policy is using an ARN when it should be using ID._

```hcl
provider aws {
  region  = "ap-southeast-2"
  version = "~>1.6"
}

resource aws_s3_bucket "main" {
  bucket = "mega-test-bucket"
}

resource aws_s3_bucket_policy "derp" {
  bucket = "${aws_s3_bucket.main.arn}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Id": "MYBUCKETPOLICY",
  "Statement": [
    {
      "Sid": "IPAllow",
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::mega-test-bucket/*",
      "Condition": {
         "IpAddress": {"aws:SourceIp": "8.8.8.8/32"}
      }
    }
  ]
}
POLICY
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
When running `terraform apply`, the resource should fail to create and not be saved to state

### Actual Behavior
The resources fails to create and is saved to state. Subsequent plans fail because the resource cannot be deleted.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
