### ISSUE TITLE
There is no data source for SQS

### ISSUE THREAD

**Issue by nespera** [terraform-providers/terraform-provider-aws#2822]
Unlike S3 and SNS, there doesn't appear to be a way to look up SQS queues by name.

**Comment by alexwlchan** [comment]
There’s an open pull request to add this: https://github.com/terraform-providers/terraform-provider-aws/pull/2311

**Comment by bflad** [comment]
New data source has been merged into master and will release with v1.15.0 of the AWS provider, likely in a week.

**Comment by bflad** [comment]
This has been released in [version 1.15.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
