### ISSUE TITLE
Can't Specify Fargate Launch Type for Service Without A Load Balancer

### ISSUE THREAD

**Issue by tacchino** [terraform-providers/terraform-provider-aws#2827]
There doesn't appear to be a way to specify that a service should be launched as Fargate except for within a load balancer config block. This makes it impossible to launch a Fargate service that doesn't not require a load balancer.

**Comment by kl4w** [comment]
@tacchino I believe this was just an error in the documentation (which is addressed https://github.com/terraform-providers/terraform-provider-aws/commit/4fbf7db3f572c38933358af3e8bb5ab8c43115b4)
