### ISSUE TITLE
aws_api_gateway_stage Tag support

### ISSUE THREAD

**Issue by FireballDWF** [terraform-providers/terraform-provider-aws#2828]
The aws_api_gateway_stage resource should be enhanced to support the new Tag support documented at https://docs.aws.amazon.com/apigateway/api-reference/resource/stage/ and announced at https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-api-gateway-supports-tagging-api-stages/

**Comment by bflad** [comment]
This functionality has been merged into master and will release with v1.16.0 of the AWS provider, likely mid next week.
