### ISSUE TITLE
aws_service_discovery_private_dns_namespace missing last error

### ISSUE THREAD

**Issue by adamgotterer** [terraform-providers/terraform-provider-aws#2830]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_service_discovery_private_dns_namespace

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_service_discovery_private_dns_namespace" "internal" {
  name = "example.internal"
  description = "Default service discovery namespace"
  vpc = "${aws_vpc.default.id}"
}
```

### Debug Output
```
* module.vpc.aws_service_discovery_private_dns_namespace.internal: 1 error(s) occurred:

* aws_service_discovery_private_dns_namespace.internal: unexpected state 'FAIL', wanted target 'SUCCESS'. last error: %!s(<nil>)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior
An actual error message with debug information

### Actual Behavior
last error: %!s(<nil>)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by gomezsan** [comment]
This happened to me when trying to use terraform to create a namespace that already existed.

**Comment by adamgotterer** [comment]
I later figured out that was the issue when working directly with the AWS CLI

**Comment by stevenjack** [comment]
For anyone that stumbles across this, I also got the error when creating a namespace with a name that overlapped an existing private hosted zone. For example I already had:

`foo.bar.local`

as a private hosted zone, then tried to create a `aws_service_discovery_private_dns_namespace` with:

`foo.baz.bar.local`

which failed, if you try it using the CLI it just returns an operation id but the namespace doesn't get created and isn't show when listing namespaces.

**Comment by luisamador** [comment]
I've just hit the same issue.

**Comment by Dgmsa** [comment]
some solution?

**Comment by bflad** [comment]
Pull request submitted: #7118
