### ISSUE TITLE
aws_security_group_rule description validation is incorrect

### ISSUE THREAD

**Issue by snemetz** [terraform-providers/terraform-provider-aws#2831]
### Terraform Version
v0.11.1
aws v1.6.0

### Affected Resource(s)
- aws_security_group_rule
Could affect other places that have `description`, but was not tested

Setting the description to "" is not allowed by the validation regex and will give the error: 
"description" doesn't comply with restrictions ("^[A-Za-z0-9 \\.\\_\\-\\:\\/\\(\\)\\#\\,\\@\\[\\]\\+\\=\\;\\{\\}\\!\\$\\*]+$"): ""
But you can set it to " ", which will get converted to "". If you do this, terraform will then think there is a change every run.

Since "" is obviously allowed by AWS, the '+' in the regex should be changed to '*'
Also, should not allow a description of nothing but spaces if it is always going to be converted to an empty string

This will allow definitions to be created where the description is optional

### Expected Behavior
Setting description to "" should work

### Actual Behavior
Setting description to "" produces an error:
"description" doesn't comply with restrictions ("^[A-Za-z0-9 \\.\\_\\-\\:\\/\\(\\)\\#\\,\\@\\[\\]\\+\\=\\;\\{\\}\\!\\$\\*]+$"): ""

**Comment by jen20** [comment]
Hi @snemetz, thanks for opening an issue here; #2846 addresses this.

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
