### ISSUE TITLE
SQS Queue Name is not validated

### ISSUE THREAD

**Issue by sjauld** [terraform-providers/terraform-provider-aws#2835]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.11.1
+ provider.aws v1.6.0
```

### Affected Resource(s)
- aws_sqs_queue

### Terraform Configuration Files
```hcl
provider aws {
  region  = "ap-southeast-2"
  version = "~>1.6"
}

resource aws_sqs_queue "derp" {
  name   = "This-is-not-valid!!!!"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
```
$ terraform validate
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Error: aws_sqs_queue.derp: only alphanumeric characters and hyphens allowed in "name"
$ 
```

### Actual Behavior
```
$ terraform validate
$
```
### Steps to Reproduce
1. `terraform validate`

### Important Factoids
N/A

### References
N/A

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
