### ISSUE TITLE
Add flag for build-badge in CodeBuild

### ISSUE THREAD

**Issue by Quintok** [terraform-providers/terraform-provider-aws#2836]
https://docs.aws.amazon.com/sdk-for-go/api/service/codebuild/#CreateProjectInput

Should also export the url to the badge as an attribute reference.

**Comment by bflad** [comment]
Support for configuring a new `badge_enabled` argument has been merged into master and will release with v1.21.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
