### ISSUE TITLE
VPC resource will make EC2 Classic calls, causing Authentication Errors in CloudTrail

### ISSUE THREAD

**Issue by martinb3** [terraform-providers/terraform-provider-aws#2848]
### Terraform Version
0.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_vpc

### Expected Behavior
No errors in CloudTrail.

### Actual Behavior
We're seeing this error in CloudTrail:

```
{
    "eventVersion":"1.05",
    "userIdentity":{
        "type":"IAMUser",
        "principalId":"foo",
        "arn":"arn:aws:iam::123:user/foo",
        "accountId":"123",
        "accessKeyId":"...",
        "userName":"foo"
    },
    "eventTime":"2018-01-03T09:18:27Z",
    "eventSource":"ec2.amazonaws.com",
    "eventName":"DescribeVpcClassicLinkDnsSupport",
    "awsRegion":"eu-central-1",
    "sourceIPAddress":"8.9.10.11",
    "userAgent":"aws-sdk-go/1.12.48 (go1.9; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.11.0-beta1",
    "errorCode":"Client.AuthFailure",
    "errorMessage":"This request has bee administratively disabled.",
    "requestParameters":{
        "DescribeVpcClassicLinkDnsSupportRequest":{
            "VpcIds":{
                "tag":1,
                "content":"vpc-123"
            }
        }
    },
    "responseElements":null,
    "requestID":"...",
    "eventID":"...",
    "eventType":"AwsApiCall",
    "recipientAccountId":"123"
}
```

### Steps to Reproduce
`terraform apply` with any aws_vpc resource.

### References

I'm guessing this error is due to this section of the provider: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpc.go#L238-L257

This probably was introduced by https://github.com/terraform-providers/terraform-provider-aws/pull/1079/files. Pinging @radeksimko and @stack72 and @catsby since they were discussing it in that issue.

**Comment by radeksimko** [comment]
Hi @martinb3 
is it preventing you from successfully creating the VPC or is CloudTrail record the only thing that bothers you?

We do need to check whether this feature is available in the region and ideally do so without hard-coding regions (because these things may & will change as AWS changes APIs every day/week) which IMO justifies that API call.

We seem to have a check for this https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpc.go#L239-L245 although the error code/message looks different. 🤔

**Comment by martinb3** [comment]
Hi @radeksimko -- it's not preventing us from creating the VPC, but multiple tools are flagging the CloudTrail log entries in during a security audit. Is there a way to disable EC2 Classic support entirely, so this check doesn't happen? Perhaps an opt-in or opt-out approach for EC2 Classic support would be useful here.

**Comment by radeksimko** [comment]
I think we could theoretically leverage `supportedplatforms` from [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/config.go#L381-L390) which can also be disabled on the provider level in which case we have to have a "fallback decision", probably assume VPC-enabled account - i.e. no ClassicLink support.

However we do need to check whether these two things are even relevant. Does EC2Classic support in the account mean support of ClassicLink and vice versa? If not, then I'm afraid there isn't much we can do.

**Comment by martinb3** [comment]
> However we do need to check whether these two things are even relevant. Does EC2Classic support in the account mean support of ClassicLink and vice versa? If not, then I'm afraid there isn't much we can do.

I'm not sure if you're asking me or just thinking aloud, but I don't have any EC2 Classic accounts with which to test this. I don't know what percentage of folks using Terraform have EC2 Classic, but I'm guessing it's smaller than folks using VPCs. 🤔

**Comment by radeksimko** [comment]
> I'm not sure if you're asking me or just thinking aloud

I was merely suggesting a potential solution and whoever picks this up will most likely need to verify that theory.
