### ISSUE TITLE
Feature Request: Distribution in aws_cloudwatch_log_subscription_filter

### ISSUE THREAD

**Issue by jacknagz** [terraform-providers/terraform-provider-aws#2853]
### Terraform Version

Latest at time of writing (`0.11.1`)

### Affected Resource(s)
- aws_cloudwatch_log_subscription_filter

### Feature
As of the AWS-SDK-Go version 1.6.3, the CloudWatch Log Subscription filters API includes a flag to control how logs are sent to a AWS Kinesis Stream.  If `distribution` is set to `Random`, it will randomize the delivery of logs to each Kinesis shard to ensure an even throughput.   Else, if set to `ByLogStream`, will map to ENIs.

### Terraform Configuration Files
```hcl
resource "aws_cloudwatch_log_subscription_filter" "test_lambdafunction_logfilter" {
  name            = "test_lambdafunction_logfilter"
  role_arn        = "${aws_iam_role.iam_for_lambda.arn}"
  log_group_name  = "/aws/lambda/example_lambda_name"
  filter_pattern  = "logtype test"
  destination_arn = "${aws_kinesis_stream.test_logstream.arn}"
  distribution    = "Random"
}
```

### References
- https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutSubscriptionFilter.html
- https://github.com/aws/aws-sdk-go/releases/tag/v1.6.3

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
