### ISSUE TITLE
Please create the data source 'aws_mq_broker'

### ISSUE THREAD

**Issue by nestorbolivar** [terraform-providers/terraform-provider-aws#2856]
Error: data.aws_mq_broker.all: Provider doesn't support data source: aws_mq_broker

**Comment by bflad** [comment]
This has been added via #3163 and will release with v1.17.0 of the AWS provider, in about two days. 👍

**Comment by bflad** [comment]
This has been released in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
