### ISSUE TITLE
Support for aws_cognito_user_pool_group

### ISSUE THREAD

**Issue by et304383** [terraform-providers/terraform-provider-aws#2865]
This is a feature request to support Cognito user pool groups.

CloudFormation support:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html

It would be very beneficial to have this support in Terraform.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
