### ISSUE TITLE
d/lb_listener: possibility to get listener from load balancer and listener port

### ISSUE THREAD

**Issue by loivis** [terraform-providers/terraform-provider-aws#2885]
### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
- aws_lb_listener

### Terraform Configuration Files

Currently, we can only provide `arn` to get information of a listener and attached listener.
```hcl
data "aws_lb_listener" "default" {
    arn = "${var.listener_arn}"
}
```

For us, it's not so friendly because a listener arn is generated by aws and hard to get unless you know it someway.

Instead, it would be helpful if data source `aws_lb_listener` could accept arguments of loadbalancer and listener port.
```hcl
data "aws_lb" "default" {
  name     = "default-public"
}

data "aws_lb_listener" "default" {
  load_balancer_arn = "${data.aws_lb.default.arn}"
  port              = 443
}
```
In [aws sdk for go](https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#DescribeListenersInput), `DescribeListenersInput` also supports `LoadBalancerArn`. Maybe a few lines of codes are needed to match the port.

Although there is paginator as [DescribeListenersPages](https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#ELBV2.DescribeListenersPages), I don't think it's needed with limit of 50 listeners per load balancer.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
