### ISSUE TITLE
Can't import security_group_rule

### ISSUE THREAD

**Issue by pauldraper** [terraform-providers/terraform-provider-aws#2895]
This is an issue without a proposed solution.

Importing security_group_rule resources is unsupported.

This is particularly true if the way you want to import the rules (e.g. put some cidrs in a module, and others elsewhere) isn't the default terraform way.

I wind up writing go code by hand to mimic ipPermissionIDHash, and inserting that into the state by hand.

It would be nice if there were an easier way to import these resources.

**Comment by YakDriver** [comment]
@pauldraper Not sure if you're still looking for this functionality but I've submitted a PR to provide it.

**Comment by bflad** [comment]
Support for importing `aws_security_group_rule` resources has been merged and will release with version 1.40.0 of the AWS provider, likely middle of this week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.40.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1400-october-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
