### ISSUE TITLE
Feature Request: Amazon ElastiCache Redis Cluster Online Resizing

### ISSUE THREAD

**Issue by sakajunquality** [terraform-providers/terraform-provider-aws#2904]
AWS has recently [announced](https://aws.amazon.com/jp/blogs/aws/amazon-elasticache-update-online-resizing-for-redis-clusters/) that ElastiCache Redis Cluster can be resized online. 

Resizing clusters with resource [elasticache_replication_group](https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html) requires forcing a new resource.

Elasticache Cluster for Redis should be able to change its shards and replicas online without creating new resource.
This operation can be conducted with AWS Web Console.

**Comment by digitalray** [comment]
extremely helpful feature

**Comment by abrechon** [comment]
👍+1

**Comment by bflad** [comment]
Enhancement PR submitted: #3932

**Comment by bflad** [comment]
Support for adjusting the number of Cluster Mode Enabled Redis shards has been merged into master and will release with v1.14.0 of the AWS provider, likely later this week.

**Comment by bflad** [comment]
This has been released in [version 1.14.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1140-april-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by geof2001** [comment]
Will this be rolled up into support for cloudformation to manage resharding without replacement?

**Comment by bflad** [comment]
@geof2001 can you please explain what you're looking for? This project is not associated with AWS CloudFormation.
