### ISSUE TITLE
Add support for adding tags to Elastic IPs

### ISSUE THREAD

**Issue by bacoboy** [terraform-providers/terraform-provider-aws#2932]
EIPs can now have tags.  Opening a feature request to add to the `aws_eip` data source and resource.

Source: https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-virtual-private-cloud-vpc-now-allows-customers-to-tag-their-elastic-ip-addresses/

**Comment by bflad** [comment]
Hi @bacoboy! This feature has actually already landed in the `aws_eip` resource as part of #2768 and will be available in 1.7.0 which will be released 🔜 . The functionality for the `aws_eip` data source has not been implemented, but we would gladly accept a PR.

**Comment by Ruenzuo** [comment]
Duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/3423. Check also https://github.com/terraform-providers/terraform-provider-aws/pull/3525

**Comment by bacoboy** [comment]
This is not a dupe of #3423.  It was to add tags to the resource.   It _should_ be closed at this point.
#3423 is about using tags on the data source to find the eip -- this one was to set the tags on the resource.

**Comment by Ruenzuo** [comment]
@bacoboy the first comment referenced the data source and the resource, and by the time I read it the resource already had it. This issue should one closed now, as there are specific issues for the data source and a PR opened for that.
