### ISSUE TITLE
Support for AmazonSideASN for aws_vpn_gateway

### ISSUE THREAD

**Issue by robgil** [terraform-providers/terraform-provider-aws#2941]
AWS now supports the ability to define the ASN number on the AWS side. This is super handy for transit use cases.

### Terraform Version
TF: 0.11.1
AWS: 1.6.0

### Affected Resource(s)
aws_vpn_gateway

### References
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpn-gateway.html
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_vpn_gateway.go#L16-L40

**Comment by ewbankkit** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/1859.
Fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/1888.
