### ISSUE TITLE
Support for aws resource_group

### ISSUE THREAD

**Issue by af6140** [terraform-providers/terraform-provider-aws#2972]
Seems not supported yet, but available through api.
http://boto3.readthedocs.io/en/latest/reference/services/resource-groups.html

**Comment by joestump** [comment]
@bflad this requires bumping `aws-sdk-go` to `v1.15.56`. I've [stubbed out a schema](https://github.com/terraform-providers/terraform-provider-aws/compare/master...joestump:jstump-resource-groups) and started on a create, but ran into this dependency issue. Is there a flow for updating that beyond PR a `govendor` update?

**Comment by joestump** [comment]
This is fixed in #6217.

**Comment by bflad** [comment]
The initial `aws_resourcegroups_group` resource has been merged and will release with version 1.55.0 of the AWS provider, likely in the next few hours. The initial resource does not support resource tags for the group itself, for which I have created #7109. For other feature requests or bug reports, please create separate issues. Thanks!

**Comment by bflad** [comment]
This has been released in [version 1.55.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1550-january-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
