### ISSUE TITLE
RDS final snapshot ignored

### ISSUE THREAD

**Issue by TaiSHiNet** [terraform-providers/terraform-provider-aws#2982]
When deleting a RDS cluster, all automated snapshots are deleted, plus final snapshot is never performed.

I just deleted a DB which had `final_snapshot_identifier` specified and no snapshots remained (not daily automated, nor the final one)

Not sure if I have to do something to maintain them when performing `terraform destroy`

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.6.0

### Affected Resource(s)
aws_rds_cluster

**Comment by aeschright** [comment]
Hi @TaiSHiNet, thanks for letting us know about this behavior. If you'd like to report a bug, please [open a new issue using our bug report format](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). Make sure to include all of the requested details. For questions about Terraform and the AWS provider, use [our discussion forum](https://discuss.hashicorp.com/c/terraform-providers).
