### ISSUE TITLE
Add support for tagging Direct Connect resources

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#2989]
Direct Connection connections, LAGs and virtual interfaces can be tagged:
* https://docs.aws.amazon.com/directconnect/latest/UserGuide/using-tags.html

Add support to:
* [`aws_dx_lag`](https://www.terraform.io/docs/providers/aws/r/dx_lag.html) resource
* [`aws_dx_connection`](https://www.terraform.io/docs/providers/aws/r/dx_connection.html) resource

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
