### ISSUE TITLE
Unable to Create AWS Inspector Assessment Target

### ISSUE THREAD

**Issue by brandonstevens** [terraform-providers/terraform-provider-aws#3001]
It looks like there is a regression caused by AWS switching to a service-linked role for AWS Inspector. When creating an assessment target in a new AWS account, I get the following error:

```bash
$ terraform apply sandbox.plan 
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
Acquiring state lock. This may take a few moments...
module.account-main.aws_inspector_assessment_target.main: Creating...
  arn:                "" => "<computed>"
  name:               "" => "assessment target"
  resource_group_arn: "" => "arn:aws:inspector:us-west-2:123456789012:resourcegroup/0-oQkbM5jw"
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* module.account-main.aws_inspector_assessment_target.main: 1 error(s) occurred:

* aws_inspector_assessment_target.main: InvalidCrossAccountRoleException: Account 123456789012 does not have a cross-account access role
	status code: 400, request id: de2b1a96-fa25-11e7-9d10-ebb28bc60be0

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I'm also able to reproduce the issue using an existing acceptance test:

```bash
$ make testacc TESTARGS='-run=TestAccAWSInspectorTarget_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -run=TestAccAWSInspectorTarget_basic -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSInspectorTarget_basic
--- FAIL: TestAccAWSInspectorTarget_basic (14.96s)
	testing.go:513: Step 0 error: Error applying: 1 error(s) occurred:
		
		* aws_inspector_assessment_target.foo: 1 error(s) occurred:
		
		* aws_inspector_assessment_target.foo: InvalidCrossAccountRoleException: Account 123456789012 does not have a cross-account access role
			status code: 400, request id: a2875a4e-fa26-11e7-9158-2727bd1054a6
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	14.972s
GNUmakefile:18: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

AWS Inspector requires a service-linked role. When you first use AWS Inspector in the AWS Management Console, the Getting Started wizard automatically creates the role. The API call to create an assessment target fails if the role doesn't exist. Terraform does not automatically create the role.

### Terraform Version
```bash
$ terraform -v
Terraform v0.11.2
+ provider.archive v1.0.0
+ provider.aws v1.7.0
```

### Affected Resource(s)
- aws_inspector_assessment_target

**Comment by gutudumitru** [comment]
Its happening also to me:
Terraform v0.11.7
+ provider.aws v1.15.0

**Comment by brandonstevens** [comment]
I haven't run into this issue in a while and probably provisioned about 10 AWS Accounts since it was originally reported.

Actually, based on SDK docs (https://docs.aws.amazon.com/sdk-for-go/api/service/inspector/#Inspector.CreateAssessmentTarget), the API call to create an assessment target creates the service-linked role if it doesn't exist. I don't think this was originally the case, regardless, closing since it's no longer an issue.

> If the service-linked role (https://docs.aws.amazon.com/inspector/latest/userguide/inspector_slr.html) isn’t already registered, this action also creates and registers a service-linked role to grant Amazon Inspector access to AWS Services needed to perform security assessments.
