### ISSUE TITLE
aws_ecr_lifecycle_policy creation does not allow  variable assignment to countNumber parameter

### ISSUE THREAD

**Issue by proj4spes** [terraform-providers/terraform-provider-aws#3002]
aws_ecr_lifecycle_policy does not allow variable assignment to countNumber parameter.

here it is the code 

 variable "number" {
description = "a number"
default = 10
}
resource "aws_ecr_repository" "foo" {
name = "bar"
}

resource "aws_ecr_lifecycle_policy" "foopolicy" {
repository = "${aws_ecr_repository.foo.name}"

policy = <<EOF
{
"rules": [
{
"rulePriority": 1,
"description": "Expire images older than 14 days",
"selection": {
"tagStatus": "untagged",
"countType": "sinceImagePushed",
"countUnit": "days",
"countNumber": "${var.number}"
},
"action": {
"type": "expire"
}
}
]
}
EOF
}
THIS is THE RESULT 
1 error(s) occurred:

* aws_ecr_lifecycle_policy.foopolicy: 1 error(s) occurred:

* aws_ecr_lifecycle_policy.foopolicy: InvalidParameterException: Invalid parameter at 'LifecyclePolicyText' failed to satisfy constraint: 'Lifecycle policy valiation failure: instance type (string) does not match any allowed primitive type (allowed: ["integer"])
'
	status code: 400, request id: 5042a1bc-fa93-11e7-b3cc-c9977d1470fa

and here there is the trace showing that CountNumber is treated as a string

policy: "" => "{\n "rules": [\n {\n "rulePriority": 1,\n "description": "Expire images older than 14 days",\n "selection": {\n "tagStatus": "untagged",\n "countType": "sinceImagePushed",\n "countUnit": "days",\n "countNumber": "10"\n },\n "action": {\n "type": "expire"\n }\n }\n ]\n}\n"
registry_id: "" => ""
repository: "" => "bar"

**Comment by proj4spes** [comment]
aws_ecr_lifecycle_policy   does not allow variable assignment to countNumber parameter.

here it is the code :+1: variable "number" {
             description = "a number"
             default     = 10
}
resource "aws_ecr_repository" "foo" {
  name = "bar"
}

resource "aws_ecr_lifecycle_policy" "foopolicy" {
  repository = "${aws_ecr_repository.foo.name}"

  policy = <<EOF
{
    "rules": [
        {
            "rulePriority": 1,
            "description": "Expire images older than 14 days",
            "selection": {
                "tagStatus": "untagged",
                "countType": "sinceImagePushed",
                "countUnit": "days",
                "countNumber": "${var.number}"
            },
            "action": {
                "type": "expire"
            }
        }
    ]
}
EOF
}

and here there is the trace showing  that CountNumber is treated as a string



 policy:      "" => "{\n    \"rules\": [\n        {\n            \"rulePriority\": 1,\n            \"description\": \"Expire images older than 14 days\",\n            \"selection\": {\n                \"tagStatus\": \"untagged\",\n                \"countType\": \"sinceImagePushed\",\n                \"countUnit\": \"days\",\n                \"countNumber\": \"10\"\n            },\n            \"action\": {\n                \"type\": \"expire\"\n            }\n        }\n    ]\n}\n"
  registry_id: "" => "<computed>"
  repository:  "" => "bar"

**Comment by bflad** [comment]
Hi @proj4spes! Does it work if you modify your policy to be (note removal of quotes):

```json
"countNumber": ${var.number}
```

**Comment by proj4spes** [comment]
Thanks , anyway I believed  that "$t..."  were the only way to interpolate and the string to int would be automatically done ...(as in other cases ..) OK it runs as it would,,

**Comment by proj4spes** [comment]
Thanks , anyway I believed that "$t..." were the only way to interpolate and the string to int would be automatically done ...(as in other cases ..) OK it runs as it would,,

**Comment by bflad** [comment]
The lines between the `<<EOF` and `EOF` used here is the heredoc notation inside Terraform's configuration language and automatically interpolates variables. This is similar behavior to the heredoc notation in Bash shell scripts or Ruby. Think of it like `"`s being around the whole lines (so anything inside interpolates) and without requiring escaping for any quotes inside (for readability). 

We can likely improve the documentation here a little bit to explain this better in: https://www.terraform.io/docs/configuration/syntax.html

**Comment by bflad** [comment]
Closing as this appears to be resolved.
