### ISSUE TITLE
Add capability to update Elastic Beanstalk tags

### ISSUE THREAD

**Issue by robinbowes** [terraform-providers/terraform-provider-aws#3004]
### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
- aws_elastic_beanstalk_environment

In the documentation for `aws_elasticbeanstalk_environment` is the following (see https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_environment.html#tags )

> tags – (Optional) A set of tags to apply to the Environment. Note: at this time the Elastic Beanstalk API does not provide a programatic way of changing these tags after initial application

I'm not sure when it was added but the Elastic Beanstalk API now /does/ provide a programatic way of changing tags after initial application. See:

* https://docs.aws.amazon.com/cli/latest/reference/elasticbeanstalk/update-tags-for-resource.html
* https://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_UpdateTagsForResource.html

Would be good to get this functionality incorporated in the AWS provider.

**Comment by reflectivecode** [comment]
+1 I would love to see this implemented.

**Comment by bflad** [comment]
This functionality has been merged into master and will release with v1.11.0 of the AWS provider, likely next week.

**Comment by bflad** [comment]
This has been released in [version 1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
