### ISSUE TITLE
resource/aws_kinesis_firehose_delivery_stream: Crash

### ISSUE THREAD

**Issue by radeksimko** [terraform-providers/terraform-provider-aws#3005]
### Terraform Version

AWS `v1.7.0`

### Affected Resource(s)

- aws_kinesis_firehose_delivery_stream

### Panic Output

https://gist.github.com/voltechs/aa24f1fc400e7271981216a7f881c3f6

### Expected Behavior

Not crash.

### Actual Behavior

Crashed.

### References

- https://github.com/terraform-providers/terraform-provider-aws/issues/2772#issuecomment-357479946

**Comment by radeksimko** [comment]
Crashing line of code, just for context:

https://github.com/terraform-providers/terraform-provider-aws/blob/b9284490eff637460fef663794a496d363e19f10/aws/resource_aws_kinesis_firehose_delivery_stream.go#L198

**Comment by radeksimko** [comment]
@voltechs Although I know what's causing the crash I was unable to reproduce it, do you mind providing a snippet of your config for `aws_kinesis_firehose_delivery_stream` so we can turn it into a test and ensure this won't ever happen again?

Thanks.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.1](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#171-january-19-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

Please note we are tracking one additional crash relating to the (lack of) `prefix` of in a `s3_configuration` in #3071. Sorry for the trouble with this resource being quite complex and the acceptance testing quite lengthy.

@voltechs if you could reply back to https://github.com/terraform-providers/terraform-provider-aws/issues/3005#issuecomment-358624434 we would greatly appreciate it!
