### ISSUE TITLE
resource/aws_rds_cluster_instance: Unable to modify performance insights key without updating the "enable parameter

### ISSUE THREAD

**Issue by ColinHebert** [terraform-providers/terraform-provider-aws#3015]
When updating the KMS key used by performance insight on a cluster instance, the apply fails:

> InvalidParameterCombination: Can not set PerformanceInsightsKMSKeyId without EnablePerformanceInsights

This is due to changes in #2331, the code we currently have looks like this:

```
	if d.HasChange("performance_insights_enabled") {
		d.SetPartial("performance_insights_enabled")
 		req.EnablePerformanceInsights = aws.Bool(d.Get("performance_insights_enabled").(bool))
 		requestUpdate = true
 	}
 
 	if d.HasChange("performance_insights_kms_key_id") {
 		d.SetPartial("performance_insights_kms_key_id")
 		req.PerformanceInsightsKMSKeyId = aws.String(d.Get("performance_insights_kms_key_id").(string))
 		requestUpdate = true
 	}
 ```

Currently from the AWS perspective it makes no sense to have a partial `PerformanceInsightsKMSKeyId` without `EnablePerformanceInsights` being updated as well. Those two should be merged into the same condition.

cc @kwent, @Ninir

**Comment by kwent** [comment]
Is this something the user should actually be able to change after instance creation ?

**Comment by ColinHebert** [comment]
Indeed, you can change that setting from the UI.

**Comment by Ninir** [comment]
Hi @ColinHebert 

Thanks for raising this issue. Do you feel you could throw a PR for that?
It would help getting this fixed.

THanks!

**Comment by ageekymonk** [comment]
> InvalidParameterCombination: Can not set PerformanceInsightsKMSKeyId without EnablePerformanceInsights

This error is correct. @Ninir what do you want in PR for this ?

**Comment by bflad** [comment]
Hi folks 👋 While we were not sending both parameters during Performance Insights KMS Key ID updates, it also appears that updating the Performance Insights KMS Key ID is also not possible with any Aurora engine. RDS automatically assigns the default RDS KMS Key ID when enabling Performance Insights without specifying a custom key and attempting to update the KMS Key ID yields:

```
Error modifying DB Instance tf-acc-test-2133090011528324987: InvalidParameterCombination: You cannot change your Performance Insights KMS key
        	status code: 400, request id: 810434c5-abb7-46f8-9570-11b75f052724
```

I have submitted #9746 which adds covering acceptance testing to ensure the correct RDS API error is shown for all Aurora engines.

**Comment by bflad** [comment]
As mentioned above, there was nothing we could do in the resource to enable changing the Performance Insights KMS Key, however in version 2.25.0 of the Terraform AWS Provider releasing next week, the resource will now return the correct error message.
