### ISSUE TITLE
network_mode = "host" causes unmodified `ecs_task_definition` resources to recreate

### ISSUE THREAD

**Issue by davidvuong** [terraform-providers/terraform-provider-aws#3047]
### Terraform Version

Terraform v0.11.2 (AWS provider version 1.7)

### Affected Resource(s)

- aws_ecs_task_definition

### Expected Behavior

Running `terraform plan` shouldn't cause a recreate (`-/+`) to an unmodified `aws_ecs_task_definition` resource.

### Actual Behavior

The opposite. Every `terraform plan/apply` recreates the `ecs_task_definition`.

### Steps to Reproduce

1. Create an `ecs_task_definition` with `network_mode = "host"`
1. Run `terraform apply`
1. Without changing anything, run `terraform plan`

I'm almost certain the issue is due to `network_mode = "host"`. Removing this fixes the problem.

**Comment by bflad** [comment]
@davidvuong sorry you're having trouble! Can you please provide an example configuration or at least the full plan output so we can troubleshoot? Thanks.

**Comment by bflad** [comment]
Closing due to lack of response.
