### ISSUE TITLE
This default value doesn't match the documentation

### ISSUE THREAD

**Issue by bgiorgini** [terraform-providers/terraform-provider-aws#3075]
Documentation says:
```
healthy_threshold - (Optional) The number of consecutive health checks successes required before considering an unhealthy target healthy. Defaults to 5.
unhealthy_threshold - (Optional) The number of consecutive health check failures required before considering the target unhealthy. Defaults to 2.
```
But this commit changed the defaults to 3 for both values:
https://github.com/terraform-providers/terraform-provider-aws/blob/cf392ceda83710325dbf3a3a7d1eb463c81c0bf7/aws/resource_aws_lb_target_group.go#L166

Ref: @DaveBlooman

**Comment by loivis** [comment]
https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

I think 5/2 was there before as default values for application load balancer. But network loadbalancer has different default values. What's more, NLB requires unhealthy threshold the same as healthy threshold value. As we don't see load balancer type on target group creation, so setting the same value became solution here? @DaveBlooman 

Simply updating the documentation would be the way to remove confusion here.
