### ISSUE TITLE
CloudFront deletion seems to disable first when already disabled

### ISSUE THREAD

**Issue by spanktar** [terraform-providers/terraform-provider-aws#3077]
### Terraform Version
0.10.7-0.11.3

We create our CloudFront distributions (aws_cloudfront_distribution) as "disabled" by default (for testing). We've noticed that, even when 100% deployed and disabled, a Terraform destroy takes just as long as if they were enabled. If we go to the AWS Console before a destroy and perform a manual Delete, the distributions delete very quickly (1-2m), whereas a Terraform destroy takes 15m+.  What it *seems* like is Terraform is performing a "disable" action on the distro, even if it is already disabled (and AWS is respecting that for who knows why). 

To be clear, the distros are completely disabled, not disabling or updating (spinning circle in the UI).  They are fully deployed and disabled.

My suggestion is that TF check the state before performing "disable & delete" and only disable those which are currently enabled.

### Expected Behavior

A previously disabled CF distro should delete quickly.

### Actual Behavior

A previously disabled CF distro takes just as long to destroy as it would if it were enabled.

### Steps to Reproduce

Create 2 different cloudfront distributions, disabled by default.
Once they are fully deployed, delete one using the AWS Console, note the time it takes.
Once that has been deleted, run Terraform destroy on the remaining one, again noting the time.
Note the time difference and weep.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.1.0 of the Terraform AWS Provider, likely middle of this week. 👍

**Comment by spanky-R7** [comment]
That's great news, thanks!

**Comment by bflad** [comment]
This has been released in [version 2.1.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#210-march-07-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
