### ISSUE TITLE
missing support pre_token_generation in cognito_user_pool

### ISSUE THREAD

**Issue by loivis** [terraform-providers/terraform-provider-aws#3092]
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

`Pre token generation` was recently added as lambda trigger for cognito user pool

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
