### ISSUE TITLE
ECS service definition is missing AssignPublicIp property

### ISSUE THREAD

**Issue by afedulov** [terraform-providers/terraform-provider-aws#3098]
Support for network configuration has been added to aws_ecs_service:
https://github.com/terraform-providers/terraform-provider-aws/pull/2299/files

Only security_groups and subnets were added, but assign_public_ip property is missing:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html#cfn-ecs-service-awsvpcconfiguration-assignpublicip

This is a blocker for Fargate  to pull images from ECR, as it seems that public IP is required (maybe a bug):
https://github.com/aws/amazon-ecs-agent/issues/1128#issuecomment-352090244

### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
aws_ecs_service

### Terraform Configuration Files
```hcl
resource "aws_ecs_service" "myapp" {
  name            = "myapp"
  cluster         = "fargate"
  launch_type     = "FARGATE"
  network_configuration = {
    subnets = ["${aws_subnet.dev_demo.id}"]
    security_groups = ["${aws_security_group.ecs.id}"]
    assign_public_ip = "ENABLED"        <---- NOT SUPPORTED
  }
...
}
```

### Expected Behavior
Auto-assign public IP ENABLED  is applied

### Actual Behavior
Error: aws_ecs_service.myapp: network_configuration.0: invalid or unknown key: assign_public_ip

**Comment by panuhorsmalahti** [comment]
"This is a blocker for Fargate to pull images from ECR, as it seems that public IP is required"

Public IP is not required, as you can use NAT+IGW. However, assigning public ip should of course also be supported.

**Comment by afedulov** [comment]
@panuhorsmalahti I would appreciate if you could give me advice on how to achieve this here https://github.com/aws/amazon-ecs-agent/issues/1204

**Comment by bflad** [comment]
Please note the request for adding `assign_public_ip` to `aws_ecs_service` is #2873 and an open PR is #2559

**Comment by afedulov** [comment]
@bflad sorry, missed those.

**Comment by johnnorton** [comment]
I have finished up the PR and 🤞that everyone is happy,  Thanks for your patience.

**Comment by bflad** [comment]
This has been merged into master and will released with v1.9.0 of the AWS provider, hopefully later today.

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by sinahwz** [comment]
Upgrading the aws provider worked just fine. 
'terraform init -upgrade'

**Comment by sinahwz** [comment]
> Is 'assign_public_ip' implemented for the windows version also? I am still getting 'invalid or unknown key: assign_public_ip' error.
> I am running 'Terraform v0.11.10' on Windows.

Upgrading the aws provider worked just fine.
'terraform init -upgrade'
