### ISSUE TITLE
Wait until ECS deployment is complete?

### ISSUE THREAD

**Issue by bitbrain** [terraform-providers/terraform-provider-aws#3107]
Hello,

I have Terraform scripts which setup the following resources:

- Autoscaling Group
- Launch Configuration
- Application Load Balancer
- ECS cluster
- Service
- Task definition
- ECR repository

When I run the script, those resources get provisioned accordingly. However, when I want to update/deploy a service, is there a way to tell Terraform to wait until a health check is okay? (like in Elastic Beanstalk Deployments)

Right now, it will complete the `terraform apply` command, even if the service for some reason is unable to spawn new tasks into the cluster.

**Comment by scream314** [comment]
@bitbrain
AFAIK there is no such option for ECS.
I do not think it would be a good idea to handle this in Terraform as it can happen that the deployment is broken and the health check will never be okay.
I think this should be handled by the thing (script, your hand, CI, etc. ) invoking Terraform and wait until the service is successfully deployed.

**Comment by marcotesch** [comment]
I totaly agree with @scream314,

As of now CloudFormation has this feature and it is annoying when Infrastructure as Code interferes with your Container Scheduling Engine, in this case ECS. This would make your Terraform deployments in the worst case blocking/deadlocking. As you can't automatically recover from a non working ECS deployment, when it waits for the ECS service to reach a steady state.

**Comment by bitbrain** [comment]
Update: there is actually a `service-stable` command for ECS to wait for a service to become stable: you can use that for example within a `null_resource` to wait for a service to deploy successfully with good health:

https://docs.aws.amazon.com/cli/latest/reference/ecs/wait/services-stable.html

**Comment by ChristophP** [comment]
thanks for the tipp @bitbrain . Works like a charm.

**Comment by richardgavel** [comment]
While we could add the null_resource, it would be nice to mirror (as part of the ecs-service resource) the similar feature that is in the cloudfront distribution resource that will do a wait without the need for a null-resource . See https://github.com/terraform-providers/terraform-provider-aws/pull/8116

**Comment by dekimsey** [comment]
I feel this could be represented/handled via an ECS version of `aws_acm_certificate_validation`. That'd alleviate much of the issues that we run into in terms of simply _not knowing_ if the new version successfully stabilized.

A psudedo resource such as `aws_ecs_service_stable` or the like.

**Comment by strowk** [comment]
I think `wait_stable` on ecs resource would be better than doing the same in a separate resource. Shorter and makes sense.

**Comment by anGie44** [comment]
This feature has been merged and will release with `v3.13.0` of the Terraform AWS Provider, expected out later today. Thanks again @mmdriley for your contribution!

**Comment by dekimsey** [comment]
I neglected to think of this earlier, but will this handle resource timeouts properly? Generally speaking for us at least if the service didn't start in 3m time, something is quite broken.

```
  timeouts {
    create = "3m"
    delete = "5m"
  }
```
