### ISSUE TITLE
[Feature Request] Support for Content Encoding in API Gateway

### ISSUE THREAD

**Issue by paul-pop** [terraform-providers/terraform-provider-aws#3144]
Hi there,

AWS recently announced the possibility of configuring API Gateway to allow clients to request content to be compressed before being sent back in the response - better late than never :)

Reference: https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-api-gateway-supports-content-encoding-for-api-responses/

This would probably need a separate `aws_api_gateway_rest_api_settings` resource (similar to `aws_api_gateway_method_settings`) OR two configurations on the `aws_api_gateway_rest_api` resource:

- `content_encoding_enabled` - Flag to enable/disable
- `minimum_compression_size` - Minimum body size required for compression

**Comment by CumpsD** [comment]
Looking very much forward for this to be added!

**Comment by rog555** [comment]
+1

**Comment by chiragghag** [comment]
+1

**Comment by tolzhabayev** [comment]
+1

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
