### ISSUE TITLE
Bug: aws_alb_target_group Doesn't Set Attributes on Creation only Update (deregistration_delay)

### ISSUE THREAD

**Issue by jammerful** [terraform-providers/terraform-provider-aws#3152]
If you ack I will submit a PR with a fix.

### Terraform Version

terraform version: 0.11.1
terraform provider aws version: 1.5.1

Also tested with latest versions. See the faulty code below on master.

### Affected Resource

- aws_alb_target_group

### Terraform Configuration Files
```hcl
{
  "resource":[
    {
      "aws_alb_target_group":{
        "example-target-group":{
          "name":"example-target-group",
          "port":443,
          "protocol":"HTTP",
          "vpc_id":"vpc-xxxxxxxx",
          "deregistration_delay": 0
        }
      }
    }
  ]
}
```

### Expected Behavior
The ALB target group should have all attributes set on creation, in particular the `deregistration_delay`.

### Actual Behavior
Instead the `dereistration_delay` gets set to the default and successive terraform applies cause the resource to be modified. Sample output is attached below:

ALB Target Group Creation:
```
$ terraform apply -auto-approve
aws_alb_target_group.example-target-group: Creating...
  arn:                  "" => "<computed>"
  arn_suffix:           "" => "<computed>"
  deregistration_delay: "" => "0"
  health_check.#:       "" => "<computed>"
  name:                 "" => "example-target-group"
  port:                 "" => "443"
  protocol:             "" => "HTTP"
  stickiness.#:         "" => "<computed>"
  target_type:          "" => "instance"
  vpc_id:               "" => "vpc-xxxxxxx"
aws_alb_target_group.example-target-group: Creation complete after 0s (ID: arn:aws:elasticloadbalancing:us-east-1:.../example-target-group/b89b5741f81xxxxxx)
```

Terraform Plan after creation:
```
Terraform will perform the following actions:

  ~ aws_alb_target_group.example-target-group
      deregistration_delay: "300" => "0"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

Using the sample config above
1. `terraform apply`
2. `terraform apply/plan`

**Comment by fangli** [comment]
+1, I got this issue too.
Just created a new issue, I should mark it as duplicated.
https://github.com/terraform-providers/terraform-provider-aws/issues/4035

**Comment by fangli** [comment]
@catsby Yes I took a look at those lines too.
The problem is, even after created the lb target group with 0 deregistration delay, when we run terraform again, we still can't to get a expected resource settings.

And I'm curious why value 0 doesn't work while other values work.

So I just set this to 1 as a workaround.
