### ISSUE TITLE
Auto Scaling Group and Launch Config somehow referencing the default VPC

### ISSUE THREAD

**Issue by abdul-baki-cap** [terraform-providers/terraform-provider-aws#3167]
Hi,

I'm having problems where my EC2 instance creation (via ASG and Launch Config) is failing due to a mis-match between Security Group and Subnet ID.

The subnet terraform is trying to deploy the EC2 instance is: `subnet-7xxx3336`
But the subnets I assigned to the ASG are (from terraform plan):
```
      vpc_zone_identifier.#:              "2"
      vpc_zone_identifier.204084353:      "subnet-8xxxb3e0"
      vpc_zone_identifier.452190839:      "subnet-1xxx2666"
```

`subnet-7xxx3336` is assigned to the default VPC, but I'm not sure how and why it's being referenced. I'm using Security Group and Subnet IDs to ensure my custom VPC and resources within that VPC are found. 

 Security Group `sg-2axxx040` is located in the same custom VPC as the subnets assigned in the ASG.

I've googled and not found any bugs similar and I've read the documentation multiple times. Perhaps there's a parameter I've missed out in my config files?

### Terraform Version
terraform --version
Terraform v0.11.2
+ provider.aws v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_autoscaling_group
- aws_launch_configuration

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "aws_autoscaling_group" "asg_my_service" {
  name                      = "asg-${var.my_service_name}"
  max_size                  = "${var.asg_max}"
  min_size                  = "${var.asg_min}"
  desired_capacity          = "${var.asg_desired}"
  force_delete              = false
  launch_configuration      = "${aws_launch_configuration.lc_my_service.name}"
  target_group_arns         = ["${aws_lb_target_group.tg_my_service.arn}"]
  vpc_zone_identifier       = ["${data.aws_subnet.app_01.id}", "${data.aws_subnet.app_02.id}"]
  health_check_grace_period = "${var.health_check_grace_period}"
  health_check_type         = "${var.health_check_type}"

  tag {
    key                 = "Name"
    value               = "asg-${var.my_service_name}"
    propagate_at_launch = "true"
  }
}


resource "aws_launch_configuration" "lc_my_service" {
  name          = "lc-${var.my_service_name}"
  image_id      = "${lookup(var.my_service_amis, var.region)}"
  instance_type = "${var.instance_type}"

  security_groups = ["${aws_security_group.sg_my_service.id}"]
  #user_data       = "${file("userdata.sh")}"
  #key_name        = "${var.key_name}"

  lifecycle {
    create_before_destroy = true
  }
}

```

### Expected Behavior
Expected AWS to deploy EC2 instance to the Subnets listed in:
```
  vpc_zone_identifier       = ["${data.aws_subnet.app_01.id}", "${data.aws_subnet.app_02.id}"]
```

### Actual Behavior
```
Error: Error applying plan:

1 error(s) occurred:

* module.my_service.aws_instance.my_service: 1 error(s) occurred:

* aws_instance.my_service: Error launching source instance: InvalidParameter: Security group sg-2axxx040 and subnet subnet-7xxx3336 belong to different networks.
	status code: 400, request id: c106f65a-3xx2-43x9-a079-f502ca942eab

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce
1. Create custom VPC
2. Use Terraform to define an ASG with subnet ID of custom VPC  
3. Launch Config with EC2 security group ID
4. `terraform plan`, then `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by abdul-baki-cap** [comment]
I've not been able to replicate this error, I copied the code to a new dir and successfully ran `terraform apply`. I suspect a gremlin in my state file caused the problem. 

I'm closing the ticket as I was unable to replicate the error.

**Comment by bharat005** [comment]
facing the same issue...tried the workaround to change to new dir...it didn't work...somehow the LC Seem to point to default VPC and not the Custom VPC...

**Comment by omerh** [comment]
Same here:
using:
Terraform v0.11.5
+ provider.aws v1.10.0
+ provider.template v1.0.0
```
Terraform will perform the following actions:

  ~ module.consul.aws_autoscaling_group.autoscaling_group
      vpc_zone_identifier.#:          "2" => "1"
      vpc_zone_identifier.1220567639: "subnet-06e42e29" => ""
      vpc_zone_identifier.2701369772: "subnet-07701463" => ""
      vpc_zone_identifier.3792650336: "" => "subnet-07701463,subnet-06e42e29"

  ~ module.kafka.aws_autoscaling_group.autoscaling_group
      vpc_zone_identifier.#:          "2" => "1"
      vpc_zone_identifier.1220567639: "subnet-06e42e29" => ""
      vpc_zone_identifier.2701369772: "subnet-07701463" => ""
      vpc_zone_identifier.3792650336: "" => "subnet-07701463,subnet-06e42e29"

  ~ module.vault.aws_autoscaling_group.autoscaling_group
      vpc_zone_identifier.#:          "2" => "1"
      vpc_zone_identifier.1220567639: "subnet-06e42e29" => ""
      vpc_zone_identifier.2701369772: "subnet-07701463" => ""
      vpc_zone_identifier.3792650336: "" => "subnet-07701463,subnet-06e42e29"


Plan: 0 to add, 3 to change, 0 to destroy.
```
