### ISSUE TITLE
[Feature Request] Support for Cognito User Pools Federated Identities

### ISSUE THREAD

**Issue by kazeshini178** [terraform-providers/terraform-provider-aws#3178]
Hey,

The ability to include federated identities during creation of my user pool, would be pretty cool, would also allow me to remove the cloud stack that current append them after creation.

AWS CLI reference: https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/create-identity-provider.html

**Comment by evan-10e** [comment]
In service of feature parity I really hope this is something on the horizon.

**Comment by bflad** [comment]
A new `aws_cognito_identity_provider` resource will release with version 1.21.0 of the AWS provider later today. 👍

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
