### ISSUE TITLE
Once aws_volume_attachment is created without "skip_destroy = true" it can't be updated or skip_destroy in the future

### ISSUE THREAD

**Issue by c2h5oh** [terraform-providers/terraform-provider-aws#3183]
### Terraform Version
Terraform v0.11.2
+ provider.aws v1.8.0 also tested with v1.3.0, so I assume it applies to all versions in between

### Affected Resource(s)
- aws_volume_attachment

### Terraform Configuration Files

Original hcl used to create attachement
```hcl
resource "aws_volume_attachment" "my_att" {
  device_name = "/dev/xvdh"
  volume_id   = "my_volume_id"
  instance_id = "my_instance_id"
  skip_destroy = false
}
```
Updated hcl
```hcl
resource "aws_volume_attachment" "my_att" {
  device_name = "/dev/xvdh"
  volume_id   = "my_volume_id"
  instance_id = "my_instance_id"
  skip_destroy = true
}
```

### Expected Behavior
Attachment destruction should be skipped once HCL has been updated
OR
Attachment destruction skipping could be updated so it can be deleted later

### Actual Behavior
`skip_destroy = true` is ignored by destroy if changed after attachment has been created
`skip_destroy = true` can't be applied to existing resource `* aws_volume_attachment.my_attachment: doesn't support update`

### Steps to Reproduce
1. apply hcl with `skip_destroy = false`
2. change skip_destroy to false in hcl
3. terraform apply / terraform destroy

**Comment by bflad** [comment]
Hi @c2h5oh, sorry you're having trouble with this and thank you for reporting it. There is already an open issue for this bug (#1211) so in order to consolidate any discussions or fix efforts, I'm going to close this issue in preference of the earlier issue. I'd recommend adding 👍  to the other original issue comment as that's one way we help prioritize fixes across the provider.

**Comment by c2h5oh** [comment]
@bflad that covers half of the issue: not being able to update the attachment.

Second part is that you can't destroy attachment even if you update hcl to include `skip_destroy = true`
