### ISSUE TITLE
Elasticsearch: invalid or unknown key: encrypt_at_rest

### ISSUE THREAD

**Issue by karoldrazek** [terraform-providers/terraform-provider-aws#3205]
### Terraform Version
Terraform v0.11.2
+ provider.aws v1.7.0
+ provider.null v1.0.0

### Affected Resource
- aws_elasticsearch_domain

### Terraform Configuration Files
```hcl
resource "aws_kms_key" "es-key" {
  description             = "es-key"
}

resource "aws_elasticsearch_domain" "test" {
  domain_name           = "test"
  elasticsearch_version = "5.5"

  cluster_config {
    zone_awareness_enabled = true
    instance_count = 2
    instance_type = "c4.xlarge.elasticsearch"
  }

  ebs_options {
    ebs_enabled = true
    volume_type = "gp2"
    volume_size = 200
  }

  encrypt_at_rest {
    enabled    = true
  }
}
```

### Debug Output
https://gist.github.com/karoldrazek/a5408268d7e1d8c54608e4c355da4b2c

### Expected Behavior
I could provision elasticsearch domain using encryption at rest

### Actual Behavior
I'm getting error regarding invalid key

### Steps to Reproduce
1. terraform plan -target=aws_elasticsearch_domain.test

**Comment by bflad** [comment]
Hi @karoldrazek! The `aws_elasticsearch_domain` `encrypt_at_rest` enhancement was just released yesterday in [v1.8.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#180-january-29-2018) of the AWS provider however your version above notes v1.7.0. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
