### ISSUE TITLE
aws_alb_listener_rule optional conditions

### ISSUE THREAD

**Issue by Alberts00** [terraform-providers/terraform-provider-aws#3216]
### Terraform Version
+ Terraform v0.11.2
+ provider.aws v1.8.0

### Affected Resource(s)
- aws_alb_listener_rule

### Terraform Configuration Files
https://gist.github.com/Alberts00/3c8ea0acfa7a3ece6263c5908e8b4812#file-main-tf

### Expected Behavior
There is a possibility to NOT create a specific path or host rule if the condition value is empty.
The host-header should not be sent to AWS API at all since the condition does not apply.

### Actual Behavior
API request is sent to AWS, the API returns that the host/path must NOT be empty.

### Debug Output
https://gist.github.com/Alberts00/3c8ea0acfa7a3ece6263c5908e8b4812#file-error

### Steps to Reproduce
1. Download terraform configuration from [here](https://gist.github.com/Alberts00/3c8ea0acfa7a3ece6263c5908e8b4812#file-main-tf)
2. `terraform init`
3. `terraform apply`

### Important Factoids
I'm not entirely sure how exactly this should be fixed and as such I'm open to suggestions on what should be the correct approach.
The resource condition block was converted from list to set in hashicorp/terraform#13776.
The exact situation of inline blocks is discussed in hashicorp/terraform#14037.

As per [this](https://github.com/hashicorp/terraform/issues/5471#issuecomment-264675195) comment empty value should not create the condition.

### References
- hashicorp/terraform#13776
- hashicorp/terraform#14037

**Comment by leonfs** [comment]
Hi @Alberts00 - I've just saw this and I think I have a temporary solution for you. 

If the condition value is empty, either for `path` or `host`, you could use wildcards:
- `*` for path
- `*.*` for host 

Based on your posted example:
```
condition {
    field  = "path-pattern"
    values = ["${lookup(var.input[count.index], "path")} != "" ? lookup(var.input[count.index], "path") : "*"}]
  }
  condition {
    field  = "host-header"
    values = ["${lookup(var.input[count.index], "host")} != "" ? lookup(var.input[count.index], "host") : "*.*""} 
  }
```

Priority is a problem though, there is no value that could work as wildcard. But for that you could have too set of inputs, prioritised and non prioritised. In any case not ideal. Would be great if this bug could actually be fixed soon.

Best,
Leo
