### ISSUE TITLE
imported aws_alb shows diff access_logs

### ISSUE THREAD

**Issue by koooge** [terraform-providers/terraform-provider-aws#3222]
Hi there, I found issue about resource aws_alb.

### Terraform Version
```
Terraform v0.11.3
+ provider.aws v1.8.0
```

### Affected Resource(s)
- aws_alb

### Terraform Configuration Files
```hcl
resource "aws_alb" "foo-alb" {
  idle_timeout    = 60
  internal        = false
  name            = "foo-alb"
  security_groups = ["sg-xxxx"]
  access_logs {
    bucket = "bar"
    prefix = "buz"
    enabled = true
  }
  subnets         = ["subnet-xxxx", "subnet-yyyy"]

  enable_deletion_protection = false

  tags {
    "Name" = "foo-alb"
  }
}
```

### Debug Output
terraform plan
```
  ~ aws_alb.foo-alb
      access_logs.#:                   "0" => "1"
      access_logs.0.bucket:            "" => "bar"
      access_logs.0.enabled:           "" => "true"
      access_logs.0.prefix:            "" => "buz"
```

### Expected Behavior
terraform does not shows diff

### Actual Behavior
terraform shows diff

### Steps to Reproduce
1.  create ALB on aws management console with **Attributes** (access_log)
2. `terraform import aws_alb.fo-alb arn:aws:elasticloadbalancing:xxxxxx`
3. `terraform plan`

**Comment by bflad** [comment]
Hi @koooge, sorry you ran into this issue and thank you for the report. It looks like this has been already reported in #2969, so to consolidate the discussion and efforts, I'm going to close this issue in preference of the previous issue.
