### ISSUE TITLE
DynamoDB Import does not import TTL settings

### ISSUE THREAD

**Issue by endzyme** [terraform-providers/terraform-provider-aws#3235]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform `v0.10.4` && `.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.3.1_x4`

Import for dynamodb_table does not import the TTL setting.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_dynamodb_table

### Terraform Configuration Files
```hcl
n/a
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

```
N/A
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

```
n/a
```

### Expected Behavior
What should have happened?

Should Import the TTL from the dynamodb table.

### Actual Behavior
What actually happened?

Doesn't import the TTL into the statefile.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import aws_dynamodb_table.my_fancy_table TableName`

The result (if the table is configured with a ttl) will import with ttl => false. Then subsequent plans will show a pending change. When you apply it returns a 400 on the API call but still writes the state file with the TTL change so that and subsequent apply's will be OK.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform/issues/12530 didn't include import functionality

**Comment by bflad** [comment]
Hi @endzyme! Sorry you ran into this, but looks like it was fixed in #2452, which was released in [v1.6.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#160-december-18-2017). It looks like your version noted above is v1.3.1. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by endzyme** [comment]
Doh!! Thanks!
