### ISSUE TITLE
Need new data source for asg launch configuration

### ISSUE THREAD

**Issue by af6140** [terraform-providers/terraform-provider-aws#3245]
looks like it's not available

**Comment by madmax88** [comment]
Agreed. 

I have a specific use-case in mind, where I want to create a new launch configuration based on one created by another resource.

**Comment by af6140** [comment]
yes, with this, you can basically keep a configurable count/history of a launch configuration with terraform.

**Comment by bflad** [comment]
A new `aws_launch_configuration` data source has been merged into master via #3624 and will release with version 1.26.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.26.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1260-july-04-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
