### ISSUE TITLE
Feature request: Add aws_dx_hosted_private_virtual_interface resource

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#3251]
Add a `aws_dx_hosted_private_virtual_interface` resource to manage hosted Direct Connect private virtual interfaces. Also required is a  `aws_dx_hosted_private_virtual_interface_accepter` resource to manage the accepting side of the hosted virtual interface.

**Comment by ewbankkit** [comment]
Related to:
* https://github.com/terraform-providers/terraform-provider-aws/pull/876
* https://github.com/terraform-providers/terraform-provider-aws/issues/3248
* https://github.com/terraform-providers/terraform-provider-aws/issues/3249
* https://github.com/terraform-providers/terraform-provider-aws/issues/3250

**Comment by thakkerdhawal** [comment]
+1

**Comment by bflad** [comment]
The new resources below will be released with version 1.25.0 of the AWS provider, likely middle of this week:
* `aws_dx_hosted_private_virtual_interface`
* `aws_dx_hosted_private_virtual_interface_accepter`

**Comment by bflad** [comment]
This has been released in [version 1.25.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1250-june-27-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
