### ISSUE TITLE
data.aws_cloudformation_stack: name vs. id

### ISSUE THREAD

**Issue by jangrewe** [terraform-providers/terraform-provider-aws#3264]
Hi there,

### Terraform Version
TF: v0.11.3
AWS: v0.1.8

### Affected Resource(s)
Please list the resources as a list, for example:
- data.aws_cloudformation_stack

### Terraform Configuration Files
```hcl
data "aws_cloudformation_stack" "base" {
  name = "Base"
}
```

### Expected Behavior
TF makes the outputs of the CF stack with the name "Base" (which exists in the AWS account) available, e.g. `${data.aws_cloudformation_stack.base.outputs["HostedZoneName"]}`

### Actual Behavior
```
Error: Error refreshing state: 1 error(s) occurred:

* data.aws_cloudformation_stack.base: 1 error(s) occurred:

* data.aws_cloudformation_stack.base: data.aws_cloudformation_stack.base: Failed describing CloudFormation stack (Base): ValidationError: Stack with id Base does not exist
	status code: 400, request id: d6d6a7ec-0b49-11e8-aed7-b5d7ad34bf80
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
That error is technically true, there's no stack with the **id** `Base`, only one with the **name** `Base` - which is why i'm using the (only available) argument `name` for this data source.

**Comment by bflad** [comment]
@jangrewe hmm, I'm not sure what is happening for you here. The data source code looks correct according to the [CloudFormation API documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStacks.html), which says it works with name or ID:
```
name := d.Get("name").(string)
input := &cloudformation.DescribeStacksInput{
	StackName: aws.String(name),
}
```

Are you sure you are hitting the right region/account or not meaning to get information about a CloudFormation stack set?

**Comment by jangrewe** [comment]
Ah, good hint regarding the region! The CF stacks are actually created in a different region, that must be the issue...
Thanks! =)
