### ISSUE TITLE
Support for Cognito Identity Provider

### ISSUE THREAD

**Issue by mdolian** [terraform-providers/terraform-provider-aws#3279]
I believe the following documentation is no longer accurate.  I'm not sure when in the past an IAM SAML Provider was used as a Cognito Identity Provider, but Cognito now has it's own Identity Provider.  Please see the following API documentation:
https://www.terraform.io/docs/providers/aws/r/cognito_identity_pool.html

I don't believe Terraform has support for this at the moment.

**Comment by Ninir** [comment]
Hi @mdolian 

Thanks for reporting this!

Cognito Identity Pool is using Authentication providers which are one/many from: Cognito, Amazon, Facebook, Google+, Twitter / Digits, OpenID, SAML or a Custom one.
SAML do is a correct *authentication* provider. 

> ... Cognito now has it's own Identity Provider

I'm wondering if you are referring to the Cognito *authentication* provider, which is using Cognito User Pool plus an Application... 🤔 
Could you better explain what you have in mind, providing a news from the blog or documentation link?

Thanks!

**Comment by mdolian** [comment]
Sorry, I meant to include the actual API reference and forgot.  I believe this is where the gap exists:

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateIdentityProvider.html

**Comment by mdolian** [comment]
Did the above reply provide enough information?  I'm more curious to know if this is a gap or if I'm potentially just doing it wrong.  I wouldn't mind trying to work on adding this feature but I don't want to dive in unless it's confirmed that it's needed.  Thanks!

**Comment by Ninir** [comment]
Hey @mdolian 

Sorry for the late response. You can find the related SAML provider resource at https://www.terraform.io/docs/providers/aws/r/iam_saml_provider.html.

Thus, you should be able to use the [cognito identity pool](https://www.terraform.io/docs/providers/aws/r/cognito_identity_pool.html) freely and fully. 

Hope it fixes your issue!

**Comment by mdolian** [comment]
@Ninir 

The IAM SAML Provider is not supported in Cognito.  The example in your documentation above will produce an error.  I tried it out and that is what led me to finding the new Cognito Identity Provider.  

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateIdentityProvider.html

If you can point me to where Terraform creates the resource above, then that solves the issue.  I believe Terraform is missing it.

Thanks

**Comment by Ninir** [comment]
Hey @mdolian 

The IAM SAML provider *is* supported by Cognito, please see the related screenshot.

![saml](https://user-images.githubusercontent.com/855022/37276393-d8a3362a-25e1-11e8-9130-8ae4561b6ce4.jpg)

As you can see, I am able to select an IAM Saml provider already created. Also, our [Cognito Identity Pool test](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_cognito_identity_pool_test.go#L115) also ensures that this is passing.

Can you provide more details about your issue so that we can further debug? 

Thanks!

**Comment by rmzi** [comment]
@Ninir - It seems that Cognito _identity pools_ allow the use of IAM SAML Providers, but *_user pools_* have a separate identity provider that is not currently supported in TF. 

Here are the docs I've been referencing: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html

**Comment by mikkeldamsgaard** [comment]
I can confirm both @rmzi  and @mdolian, that it looks like terraform is missing support to create UserPoolIdentityProviders. The corresponding commandline commands to list and create the objects are

aws cognito-idp describe-identity-provider 
aws cognito-idp create-identity-provider 

The both requires user-pool-id as an argument.

The corresponding AWS documentation about these kind of pools are: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-configuring-federation-with-social-idp.html

**Comment by bflad** [comment]
For what its worth, there is an open pull request for a new `aws_cognito_identity_provider` resource here: https://github.com/terraform-providers/terraform-provider-aws/pull/3601

**Comment by bflad** [comment]
The new `aws_cognito_identity_provider` resource will release with v1.21.0 later today.

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by realvictorprm** [comment]
I'm not understanding from the docs, how I can specifiy the XML File for SAML providers. Is this a gap or do I miss something?

**Comment by cilindrox** [comment]
@realvictorprm take a look at this answer: https://github.com/terraform-providers/terraform-provider-aws/issues/4815#issuecomment-396898054

**Comment by orfin** [comment]
@realvictorprm you can pass content of XML file directly to MetadataFile property:

```
resource "aws_cognito_identity_provider" "example" {
  user_pool_id  = "${aws_cognito_user_pool.example.id}"
  provider_name = "example"
  provider_type = "SAML"

  provider_details = {
    MetadataFile = "${file('path/to/file.xml')}"
  }
}
```
