### ISSUE TITLE
Lack of support for Aurora MySQL 5.7

### ISSUE THREAD

**Issue by fabiendelpierre** [terraform-providers/terraform-provider-aws#3284]
**Edit: see comment below and feel free to close this**

Hi there,

AWS Aurora just added support for MySQL 5.7, but it appears Terraform does not.

https://aws.amazon.com/about-aws/whats-new/2018/02/amazon-aurora-is-compatible-with-mysql-5-7/

### Terraform Version
```$ terraform -v
Terraform v0.11.3
```

### Affected Resource(s)
- `aws_rds_cluster`

### Terraform Configuration Files

Something like this will reproduce the problem:

```hcl
resource "aws_rds_cluster" "my_db_cluster" {
  cluster_identifier_prefix = "my-cluster-"
  engine                    = "aurora-mysql"
  engine_version            = "5.7.12"
  database_name             = "mycluster"
  db_subnet_group_name      = "my-cluster-subnet-group"
  master_username           = "clusteradmin"
  master_password           = "password123"
  backup_retention_period   = "7"
  preferred_backup_window   = "07:00-09:00"
  skip_final_snapshot       = "true"
  vpc_security_group_ids    = ["my-cluster-security-group"]
}
```

### Expected Behavior
An Aurora MySQL 5.7 cluster should get provisioned.

### Actual Behavior
You get this error:
```
$ terraform apply

Error: aws_rds_cluster.artifactory_db_cluster: "engine" contains an invalid engine type "aurora-mysql". Valid types are either "aurora" or "aurora-postgresql".
```

### Steps to Reproduce
Try to set up a cluster using the values outlined here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/AuroraMySQL.Updates.20180206.html, then `terraform apply` using something like my example above.

**Comment by fabiendelpierre** [comment]
Never mind, I see https://github.com/terraform-providers/terraform-provider-aws/commit/b6f942490567e55f019139a5137f9f4d51742693 fixes that. When do you plan on releasing a new version of TF with this fix? Thanks!

**Comment by vancluever** [comment]
Hey @fabiendelpierre, we don't have a specific schedule for releases in providers, but if you look in the CHANGELOG, you can get a pretty good idea of how regularly updates go out and use that to gauge when you might see 1.9.0 released.

Thanks!

**Comment by charliecao77** [comment]
set items in both resourses aws_rds_cluster and aws_rds_cluster_instance
engine="aurora-mysql"
engine-version="5.7.12"

**Comment by cfullerton** [comment]
I am still getting "InvalidParameterCombination: Cannot find version 5.7.12 for aurora" also for anyone trying to copy paste the above, it is engine_version

**Comment by cfullerton** [comment]
5.7.12 works if you specify the engine as "aurora" instead of "aurora-mysyql"
