### ISSUE TITLE
AWS SNS: Add support for DeliveryPolicy in SNS topic subscriptions

### ISSUE THREAD

**Issue by ddcprg** [terraform-providers/terraform-provider-aws#3288]
Add support for `DeliveryPolicy` in SNS topic subscriptions.

See [SNS FAQ|https://aws.amazon.com/sns/faqs/] for details: *_What happens to Amazon SNS messages if the subscribing endpoint is not available?_*

### Terraform Version
All

### Affected Resource(s)
- aws_sns_topic_subscription

### Expected Behavior
The delivery policy should applied to the SNS subscription if the subscription is HTTP/S. Otherwise, it must be rejected.

### Actual Behavior
The attribute `delivery_policy` is there but is not implemented - only read after resource creation.

### References
#2916

**Comment by bflad** [comment]
The initial implementation of the `delivery_policy` argument has been merged and will release with version 1.39.0 of the AWS provider, likely middle of next week.
