### ISSUE TITLE
Feature request: Encryption at rest for DynamoDB

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#3298]
Encryption at rest [just released](https://aws.amazon.com/blogs/aws/new-encryption-at-rest-for-dynamodb/) for DynamoDB.
Add support to the `aws_dynamodb_table` data source and resource.

**Comment by ewbankkit** [comment]
Requires [v1.12.73](https://github.com/aws/aws-sdk-go/releases/tag/v1.12.73) of the AWS SDK for Go.

**Comment by satyanerella** [comment]
Would it be possible to know when this PR would be into the release.

**Comment by AlexCousens** [comment]
Would also very much like this feature ASAP please!
