### ISSUE TITLE
Error creating aws_lambda_permission: The statement id already exists.

### ISSUE THREAD

**Issue by mdsina** [terraform-providers/terraform-provider-aws#3312]
Hello, I've found an error when trying to redeploy my lambda function with changes only in permission

### Terraform Version
λ terraform -v
Terraform v0.11.3
+ provider.archive v1.0.0
+ provider.aws v1.8.0
+ provider.random v1.1.0

### Affected Resource(s)
- aws_lambda_permission

### Terraform Configuration Files
```hcl
resource "aws_lambda_permission" "with_sns" {
  statement_id   = "AllowExecutionFromSNS"
  action         = "lambda:InvokeFunction"
  function_name  = "${aws_lambda_function.lambda.arn}"
  principal      = "sns.amazonaws.com"
  source_arn     = "${var.sns}"
}
```

### Debug Output
N/A

### Crash Output
```
* module.crawler_us2.aws_lambda_permission.with_sns: 1 error(s) occurred:

* aws_lambda_permission.with_sns: [WARN] Error adding new Lambda Permission for <some_arn>, retrying: ResourceConflictException: The s
tatement id (AllowExecutionFromSNS) provided already exists. Please provide a new statement id, or remove the existing statement.
        status code: 409, request id: <request_id>
* module.crawler_asia.aws_lambda_permission.with_sns: 1 error(s) occurred:
```

### Expected Behavior
Function permission replaced 

### Actual Behavior
Cannot redeploy lambda function with defined permission

### Steps to Reproduce
1. `terraform apply`
2. make some minor change in permission
3. repeat first step

### Important Factoids
N/A

### References
N/A

**Comment by loivis** [comment]
According to [AWS API Reference](https://docs.aws.amazon.com/lambda/latest/dg/API_Reference.html), there are only `AddPermission` and `RemovePermission` available. Maybe this is why resource `aws_lambda_permission` doesn't support `update` from the beginning? Custom logic could be introduced to support `update`, but it would probably break the boundary of not managing existing resources?
With existing code, `ForceNew:     true` is set for all arguments. Did you try with `lifecycle { create_before_destroy = false }`?

**Comment by chriswolf-nrg** [comment]
I am having this same issue - I don't know what `ForceNew: true` is, but I tried editing my `*.tf` and adding `lifecycle { create_before_destroy = false }` and this did not solve `ResourceConflictException` upon attempting to add Lambda Permission.
