### ISSUE TITLE
Terraform 0.10.8 Not Working After AWS v1.9.0 Release

### ISSUE THREAD

**Issue by hikerspath** [terraform-providers/terraform-provider-aws#3314]
### Terraform Version
- Terraform v0.10.8

### Affected Resource(s)
- providers
- modules
- core

### Terraform Configuration Files
```hcl
terraform {
  backend "s3" {
    bucket = "REDACTED"
    key = "eu-west-1/main/logging_backend_dev.tfstate"
    region = "REDACTED"
  }
}
```

### Debug Output
- https://gist.github.com/hikerspath/ca14d27a72f5b5fd7b8150713be1eaed

### Expected Behavior
Expected to see a full run happen as it had 20min prior (before v1.9.0 was released).  Especially expected to see this work given that the module is still listed to support 0.10.x version (https://github.com/terraform-providers/terraform-provider-aws/blob/v1.9.0/README.md#requirements)

### Actual Behavior
Fails to initialize terraform (both plugins and modules) 

### Steps to Reproduce
1. `terraform init`

### Important Factoids
As Gist shows, you will find that we are current to 0.11.3 code-base, but our team supports others in the company at varied versions of terraform code. 

### References
N/A

**Comment by bflad** [comment]
@hikerspath hmmm I'm not able to reproduce this with the following:
* Download terraform 0.10.8 binary from: https://releases.hashicorp.com/terraform/0.10.8/
* Create a test S3 bucket for storing state (`bflad-3314-testing` below)
* Run this configuration:

```hcl
terraform {
  backend "s3" {
    bucket = "bflad-3314-testing"
    key    = "3314.tfstate"
    region = "us-east-1"
  }
}

provider "aws" {
  region  = "us-east-1"
  version = "1.9.0"
}

data "aws_region" "current" {}

output "region" {
  value = "${data.aws_region.current.name}"
}
```

```
./terraform init

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.9.0)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

./terraform apply
data.aws_region.current: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

region = us-east-1

./terraform version
Terraform v0.10.8

Your version of Terraform is out of date! The latest version
is 0.11.3. You can update by downloading from www.terraform.io/downloads.html

./terraform providers
.
└── provider.aws 1.9.0
```

**Comment by hikerspath** [comment]
Well, I couldn't run your exact code, but changed the bucket and everything worked.  Then I went through and checked prod code to see if that worked as well, and it did.  Would you be able to check something out for us though?   I was not the only one in my group that was having issues during that time, which prompted me to look a little deeper.

Hashicorp hosts its releases.hashicorp.com site off fastly.com and they had a service-outage during that exact timeframe.  Could it be possible that connectivity issues with fastly.com during that timeframe caused the following errors to be returned: 
- ``A provider named "provider" could not be found in the official repository.`` 
- ``A provider named "module" could not be found in the official repository.``

Below you will find the message from fastly.com once they realized their problems and a timeline of all the events surrounding this issue:
> We have received reports from a number of customers about intermittent TCP resets from NAT gateways in a popular cloud provider. We are working with the affected customers and the cloud provider to determine the cause. If you are currently experiencing similar issues we recommend opening a ticket with our customer support team, as well as the cloud provider for tracking purposes. 
- https://status.fastly.com/incidents/k3zzxnkz4vcd

Time                      | Activity
------------------------- | ------------------------------------------------
Feb 09, 2018 - 12:54 UTC  | Last Successful Run of Terraform on v0.10.8
Feb 09, 2018 - 17:16 UTC  | Fastly Issue Realized
Feb 09, 2018 - 18:37 UTC  | Fastly Issue Identified
Feb 09, 2018 - 20:49 UTC  | AWS Provider v1.9.0 Released
Feb 09, 2018 - 21:14 UTC  | First Unsuccessful Run of Terraform on v0.10.8
Feb 09, 2018 - 22:41 UTC  | Git Issue #3314 Created
Feb 10, 2018 - 15:03 UTC  | Fastly Fix Implemented, Monitoring Results
Feb 10, 2018 - 15:17 UTC  | Fastly Issue Resolved

With the above timeline, perhaps it is possible this would be the error message received if the repository were unreachable?  If that is the case, I would look to have the error message changed a bit to be more clear what exactly happened.

**Comment by bflad** [comment]
@hikerspath awesome investigative work. The code implementing the `init` command and plugin system lives upstream in the [Terraform core repository](https://github.com/hashicorp/terraform/), rather than here or in any of the providers themselves since the Terraform 0.10 core-provider split.

I'm not too familiar with the code implementing this subsystem, but I spent a few minutes trying to dig through the plugin handling code and couldn't figure out why its returning that.

My suggestion would be to close the issue here and reopen in https://github.com/hashicorp/terraform/ with the above information. The Terraform core team members and contributors will likely be able to help much better and theres nothing we can really implement here in the provider itself for this situation. 👍

**Comment by hikerspath** [comment]
I have opened a new issue, https://github.com/hashicorp/terraform/issues/17342 thanks for your guidance @bflad!
