### ISSUE TITLE
Enable encryption at rest feature for DynamoDB

### ISSUE THREAD

**Issue by bmacauley** [terraform-providers/terraform-provider-aws#3318]
AWS have finally released encryption at rest on DynamoDB
https://aws.amazon.com/blogs/aws/new-encryption-at-rest-for-dynamodb/

Can we enable this feature on aws_dynamodb_table ?

The Go SDK has already been updated...
https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#DynamoDB.CreateTable

**Comment by ewbankkit** [comment]
Duplicates https://github.com/terraform-providers/terraform-provider-aws/issues/3298.

**Comment by radeksimko** [comment]
Closing in favour of #3298 

Thanks.
