### ISSUE TITLE
adding support for data lookup of the resource aws_db_subnet_group

### ISSUE THREAD

**Issue by tasdikrahman** [terraform-providers/terraform-provider-aws#3326]
### Terraform Version

v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
- `aws_db_subnet_group`

**Comment by bflad** [comment]
Keeping this open since it has a decent following and a pull request that's in flight.

**Comment by anGie44** [comment]
The new data-source `db_subnet_group` has been merged and will release with `v3.4.0` of the Terraform AWS Provider, likely out later today.
