### ISSUE TITLE
Terraform fails because aws_cloudformation_stack attribute "outputs" are not available 

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-aws#3343]
### Terraform Version
`Terraform v0.11.3`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudformation_stack

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Terraform Outputs File
output "CSR1" {
  value = "${aws_cloudformation_stack.transit_vpc.outputs.CSR1}"
}

output "ID" {
  value = "${aws_cloudformation_stack.transit_vpc.id}"
}
```

```hcl
module "transit-vpc-main-account" {
  source = "../."

  cf_name     = "test-transit-vpc"
  csr_KeyName = "test-transit-vpc"

  # Default Transit VPC CF Template Parameters Values
  TerminationProtection = "No"
  PreferredPathTag      = "testvpc:preferred-path"
  SpokeTag              = "testvpc:spoke"
  SpokeTagValue         = "true"
  BgpAsn                = "65000"
  VpcCidr               = "100.64.127.224/27"
  PubSubnet1            = "100.64.127.224/28"
  PubSubnet2            = "100.64.127.240/28"
  CSRType               = "2x250Mbps"
  LicenseModel          = "LicenseIncluded"
  S3Prefix              = "vpnconfigs/"
  SendAnonymousData     = "Yes"
  CloudFormationPrefix  = ""
}
```
### Expected Behavior
Terraform should have created the Cloudformation Stack and then it should have created the outputs correctly. 

Maybe it should just issue a warning and not fail completely if outs puts are not valid.

### Actual Behavior
```
Error: Error running plan: 1 error(s) occurred:

* module.transit-vpc-main-account.output.CSR1: Resource 'aws_cloudformation_stack.transit_vpc' does not have attribute 'outputs.CSR1' for variable 'aws_cloudformation_stack.transit_vpc.outputs.CSR1'
```
### Steps to Reproduce
Try to create a Cloudformation stack with exports and use those as outputs.

### Important Factoids
I removed my outputs file, ran the apply, and placed the outputs file back, and the errors went away. I also used the terraform console command and indeed the "outputs" key was not available until after I ran apply and created the stack. Afterwards I could see the outputs. I also tried using depends_on and that didn't help either.

**Comment by chinthakagodawita** [comment]
As per hashicorp/terraform#7914, try using:
```hcl
# Terraform Outputs File
output "CSR1" {
  value = "${aws_cloudformation_stack.transit_vpc.outputs["CSR1"]}"
}
```

**Comment by shadycuz** [comment]
@chinthakagodawita 

That did the trick =). 

I did actually find that post before making mine and I tried it, but I must have fat fingered something. 

I'm trying to think of a way to elegantly explain this, and if I come up with something I will PR a documentation fix. 

Thanks!
