### ISSUE TITLE
Add Support For Lambda Alias Traffic Shifting

### ISSUE THREAD

**Issue by eggsbenjamin** [terraform-providers/terraform-provider-aws#3368]
Add support for Lambda Alias traffic shifting.

AWS introduced traffic shifting for Lambda Alias' in late 2017 where by a set proportion of events can be configured to go to a specified version of a lambda function with the remainder going to the version associated with the lambda alias. This affords phased rollouts/canary releases.

[Pull Request](https://github.com/terraform-providers/terraform-provider-aws/pull/3316) (__disclaimer__ - my PR)

https://aws.amazon.com/about-aws/whats-new/2017/11/aws-lambda-supports-traffic-shifting-and-phased-deployments-with-aws-codedeploy

https://docs.aws.amazon.com/lambda/latest/dg/API_AliasConfiguration.html

https://docs.aws.amazon.com/lambda/latest/dg/API_AliasRoutingConfiguration.html

https://docs.aws.amazon.com/lambda/latest/dg/lambda-traffic-shifting-using-aliases.html

**Comment by bflad** [comment]
This has been implemented into master via #3316 and will release with version 1.26.0 of the AWS provider, later this week! 🚀

**Comment by bflad** [comment]
This has been released in [version 1.26.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1260-july-04-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
