### ISSUE TITLE
Unable to update `aws_cognito_user_pool_client`

### ISSUE THREAD

**Issue by nick-woodward** [terraform-providers/terraform-provider-aws#3384]
### Terraform Version

v0.11.3

### Affected Resource(s)

Please list the resources as a list, for example:
- aws_cognito_user_pool_client

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_cognito_user_pool" "pool" {
  name = "dummy-user-pool"

  auto_verified_attributes = [
    "email"
  ]

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_cognito_user_pool_client" "client" {
  name = "client"

  user_pool_id = "${aws_cognito_user_pool.pool.id}"

  supported_identity_providers = ["COGNITO"]
  callback_urls = [
    "http://localhost"
  ]

  logout_urls = [
    "http://localhost"
  ]

  allowed_oauth_flows = ["implicit"]
  allowed_oauth_scopes = ["openid"]
  allowed_oauth_flows_user_pool_client = true
}
```

### Debug Output

https://gist.github.com/nick-woodward/0fddeaa7ba0cb6439de6aa0e25bd2e9a

### Expected Behavior

The client resource is update.

### Actual Behavior

Terraform fails to update the resource.

### Steps to Reproduce

1. `terraform apply` (using the above example)
2. Add `https://localhost` to the callback and logout url arrays
3. `terraform apply`

**Comment by nick-woodward** [comment]
If I'm not misreading this, I think the issue is with the following line of code.

https://github.com/terraform-providers/terraform-provider-aws/blob/2eb6e79bee0c32ef7df377c7641219dd6ad34065/aws/resource_aws_cognito_user_pool_client.go#L294

**Comment by bflad** [comment]
The fix for this has been merged into master and will be released with v1.12.0 of the AWS provider, likely end of next week. Thanks to @nick-woodward for the fix and apologies for the delay.

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by rprieto** [comment]
Thanks for raising this and for the fix! For other people (like me) who faced the issue with `v0.11.6`, I'm just copy-pasting the actual error from the Gist so the issue can be found when searching:

```
Error updating Cognito User Pool Client: InvalidParameterException
Invalid read attributes specified while updating a client
```

**Comment by chetanmelkani** [comment]
@rprieto It did not fix the `default_redirect_uri` issue. It still fails to update. I was just testing it in 1.12 version.

**Comment by scala-guy** [comment]
I'm getting similar error. I can't update allowed_oauth_flows_user_pool_client in resource aws_cognito_user_pool_client. I get following error:
  * aws_cognito_user_pool_client.client.1: Error updating Cognito User Pool Client: InvalidParameterException: AllowedOAuthFlows and AllowedOAuthScopes are required if user pool client is allowed to use OAuth flows.
        status code: 400, request id: bfeb42f0-8401-11e8-a33d-4388ccbed918
