### ISSUE TITLE
data.aws_elasticache_cluster.cluster_address missing - yet in docs

### ISSUE THREAD

**Issue by Wambosa** [terraform-providers/terraform-provider-aws#3386]
Here is a bug I ran into today. It may be that the docs are just out of sync or maybe redis clusters do not support the same functionality, however it appears to be a small bug where not all attributes such as `data.aws_elasticache_cluster.cluster_address` are being exported or made available. 

The workaround is currently to grab the nodes addresses directly instead with `"${data.aws_elasticache_cluster.steam_profiles.cache_nodes.0.address}, ${data.aws_elasticache_cluster.steam_profiles.cache_nodes.1.address}"`

### Terraform Version
0.11.3

### Affected Resource(s)
- aws_elasticache_cluster

### Debug Output

```
Resource 'data.aws_elasticache_cluster.my' does not have attribute 'cluster_address' for variable 'data.aws_elasticache_cluster.my.cluster_address'
```

### Expected Behavior
The [attribute cluster_address should exist per documentation](https://www.terraform.io/docs/providers/aws/d/elasticache_cluster.html#cluster_address)

### Steps to Reproduce
```
data "aws_elasticache_cluster" "my" {
  cluster_id = "my"
}

data "template_file" "cloud_init" {
  template = "... {{ elasticache_addy }}..."

  vars {
     elasticache_addy  = "${data.aws_elasticache_cluster.my.cluster_address}"
  }
}
```

### Important Factoids
it may be specific to redis clusters only?

### References
this issue was found with a quick google search, seems to be in the same spirit as this one
https://github.com/hashicorp/terraform/issues/1918

**Comment by bflad** [comment]
@Wambosa it does look like we try to set `cluster_address` if it exists:

https://github.com/terraform-providers/terraform-provider-aws/blob/075f4573ab7a26102a0876588e9345686f281000/aws/data_source_aws_elasticache_cluster.go#L205-L209

But as you surmised, this information is only available for Memcached clusters, as noted in the [Elasticache API documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CacheCluster.html):
> **ConfigurationEndpoint**
> Represents a Memcached cluster endpoint which, if Automatic Discovery is enabled on the cluster, can be used by an application to connect to any node in the cluster. 

Would you mind submitting a documentation PR for `website/docs/d/elasticache_cluster.html.markdown`? Might be worth checking the resource documentation in `website/docs/r/elasticache_cluster.html.markdown` too. 😄
