### ISSUE TITLE
Support for exporting Redshift cluster nodes and/or IP addresses

### ISSUE THREAD

**Issue by dnedev** [terraform-providers/terraform-provider-aws#3394]
Currently `aws_redshift_cluster` resources do not support exporting the cluster nodes. However it is already possible to get those back from AWS using the CLI. The cluster nodes are useful for determining the public and private IP addressed of the nodes.

While attaching an EIP seems like a possible workaround, it is quite limited when the cluster is not publicly accessible and deployed in a private subnet (which is the recommended way).

Here's a small example for to do that using the AWS CLI:
`aws redshift describe-clusters --cluster-identifier <cluster-identifier>`
https://docs.aws.amazon.com/redshift/latest/dg/load-from-host-steps-retrieve-key-and-ips.html

### Terraform Version
```Terraform v0.11.3
+ provider.aws v1.8.0
+ provider.template v1.0.0
```
### Affected Resource(s)
- `aws_redshift_cluster`

**Comment by russellsherman** [comment]
I'd like this as well, going to go ahead and take a crack at a PR
