### ISSUE TITLE
AWS Cognito user pool client does not allow USER_PASSWORD_AUTH as explicit_auth_flows

### ISSUE THREAD

**Issue by apv1** [terraform-providers/terraform-provider-aws#3397]
Hi,

It seems AWS Cognito app clients allows one more configuration option now. It's not possible to set USER_PASSWORD_AUTH for an app client with Terraform.

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
- aws_cognito_user_pool_client

### Terraform Configuration Files
```hcl
resource "aws_cognito_user_pool_client" "main" {
  name = "app"

  user_pool_id = "${aws_cognito_user_pool.main.id}"
  explicit_auth_flows = ["ADMIN_NO_SRP_AUTH", "USER_PASSWORD_AUTH"]
}
```

### Expected Behavior
Create an app client with desired options

### Actual Behavior
<pre>
Error: aws_cognito_user_pool_client.main: expected explicit_auth_flows.1 to be one of [ADMIN_NO_SRP_AUTH CUSTOM_AUTH_FLOW_ONLY], got USER_PASSWORD_AUTH
</pre>

**Comment by bflad** [comment]
This has been released in [version 1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
