### ISSUE TITLE
aws_ssm_parameter with association name seems to interfere with parameters and vice versa

### ISSUE THREAD

**Issue by mattsoftware** [terraform-providers/terraform-provider-aws#3407]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.8.0
+ provider.external v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)
- aws_ssm_association

### Terraform Configuration Files
```hcl
resource "aws_ssm_association" "test" {
    association_name = "Test"
    name = "AWS-RunAnsiblePlaybook"
    targets = [
        {
            key = "tag:Test"
            values = ["true"]
        }
    ]
    parameters {
        check = "False"
        playbook = <<EOF
- hosts: all
  become: true
  tasks:
  - name: set debug header
    copy:
      dest: /etc/nginx/conf.d/test.conf
      content: add_header "X-Debug" "Test" always;
      mode: 0644
    notify:
    - reload nginx
  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
EOF
    }
}
```

### Expected Behavior
SSM Assocation should have been updated with new ansible script and assocaition name when updated

### Actual Behavior
This varies.

a) On the first run everything goes as expected.

b) If for example the ansible script gets changed, and the terraform is re-run, the parameters will be completely empty

c) If run again (no further changes) then terraform will still detect a change, then do the update, the parameters will be there but the association name will be '-'

d) If run again (no further changes) then terraform will still detect a change, then do the update, the parameters will be empty again, but now the association name will be correct.

e) goto c

**Comment by mattsoftware** [comment]
As I use this feature for more things it seems that ANY change that happens, will either blow away the parameters, or blow away other parts. Not just the association_name but also the schedule_expression and any changes to tags

It seems like a bit of a blocker for me at the moment.

**Comment by gbish** [comment]
I'm getting a the same issue, and it certainly seems to be related to `association_name`.

```
resource "aws_ssm_association" "bastion" {
  name             = "${var.ssm_document_update_ssh_users}"
  association_name = "bastion-state-association"

  schedule_expression = "rate(1 hour)"

  targets {
    key    = "tag:Role"
    values = ["bastion"]
  }
}
```

In my config, I can either have an association name, or the schedule expression (slightly more important), not both.

**Comment by karnauskas** [comment]
I'm having similar problem. I have simple association to run remote shell script.

First run: plan and apply works as expected.
Second plan: shows change in `association_name: "" => "my-association-name"`. Applying this plan and got:`[ERROR] Error updating SSM association: InvalidParameters: Parameter "commands" requires a value.`

The association_name or commands haven't been changed in terraform definition. So far this is blocker for me.

**Comment by bflad** [comment]
The fix for passing all arguments during update has been merged into master and will release with version 1.34.0 of the AWS provider, likely later today.

**Comment by mattsoftware** [comment]
Confirmed, this works well, thank you @bflad, Very very happy :)
