### ISSUE TITLE
Error: provider.aws: assume_role: should be a list

### ISSUE THREAD

**Issue by riponbanik** [terraform-providers/terraform-provider-aws#3410]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.9.0

### Affected Resource(s)
All

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
terraform {
  backend "s3" {
    bucket = "xxxx"
    key = "terraform.tfstate"
    region = "ap-southeast-2"
  }
}

provider "aws" {
  region   = "${var.aws_region}"
  assume_role = "${var.workspace_iam_roles[terraform.workspace]}"
}

variable "workspace_iam_roles" {
  default = {
    dev    = "arn:aws:iam::x:role/role-system-admin"
    test   = "arn:aws:iam::x:role/role-system-admin"
    uat    = "arn:aws:iam::x:role/role-system-admin"
    pord   = "arn:aws:iam::x:role/role-system-admin"
  }
}

### Expected Behavior
What should have happened?
Running terraform.exe plan -var-file .\test.tfvars should generate the plan

### Actual Behavior
What actually happened?
It shows error - Error: provider.aws: assume_role: should be a list

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
a. terraform init 
b. terraform workspace new test
c. terraform plan

**Comment by loivis** [comment]
This is how it should look like
```
provider "aws" {
  region              = "eu-west-1"
  assume_role {
    role_arn = "arn:aws:iam::123456789012:role/role-name"
  }
}
```

check document [here](https://www.terraform.io/docs/providers/aws/index.html#assume-role)

**Comment by riponbanik** [comment]
Thanks @loivis it works!!!
