### ISSUE TITLE
AssociationDoesNotExist:

### ISSUE THREAD

**Issue by h4wkmoon** [terraform-providers/terraform-provider-aws#3416]
Hello,

We are facinf an issue where we can't plan or apply anything due to something that seems to be a bug regarding the refresh of aws_ssm_association.

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
aws_ssm_association

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
* Create an aws_ssm_association with Terraform. (plan, apply, the whole stuff)
* Manually delete it from AWS Console.
* Try to refresh, plan or apply and get the error

**Error reading SSM association: AssociationDoesNotExist: Association xxxx does not exist.**

### Workaround:
Remove item from state using "state rm" command.
```bash
terraform state rm aws_ssm_association.assocname
```

**Comment by bflad** [comment]
The fix for this has been merged into master and will release with v1.12.0 of the AWS provider, likely in about a week.

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
