### ISSUE TITLE
feature: new resource aws_cloudhsm_cluster, aws_cloudhsm

### ISSUE THREAD

**Issue by ewilde** [terraform-providers/terraform-provider-aws#3434]
Hi,

I couldn't find a resource to manage `cloud hsm v2` in the existing aws terraform provider. Looking at the [api docs](https://docs.aws.amazon.com/cloudhsm/latest/APIReference/Welcome.html) this looks quite straightforward.

Should I go ahead and submit a PR for this?

**Comment by bflad** [comment]
Support for the following has been merged and will release later today with version 1.41.0 of the AWS provider! 🎉 

* New Data Source: `aws_cloudhsm_v2_cluster`
* New Resource: `aws_cloudhsm_v2_cluster`
* New Resource: `aws_cloudhsm_v2_hsm`
