### ISSUE TITLE
r/ses_domain_mail_from improvements

### ISSUE THREAD

**Issue by sjauld** [terraform-providers/terraform-provider-aws#3445]
#2029 adds support for SES MAIL FROM resources. It would be great to output the required DNS records so we can use them directly. I'll work on this if no one else is doing it?

**Comment by sjauld** [comment]
Just as a note, this would actually be hard coded as it's not provided by the AWS API...

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html#region-mail-from

**Comment by sjauld** [comment]
We could even just leave a note in the docs to do something like this:

```
data aws_region "current" {}

resource aws_route53_record "bounce_mx" {
  zone_id = "${aws_route53_zone.mailer.zone_id}"
  name    = "${var.mail_from_subdomain}"
  type    = "MX"
  ttl     = "300"
  records = ["10 feedback-smtp.${data.aws_region.current.name}.amazonses.com"]
}
```

**Comment by bflad** [comment]
The current [`aws_ses_domain_mail_from` resource documentation](https://www.terraform.io/docs/providers/aws/r/ses_domain_mail_from.html) contains an example similar to the last comment above:

```hcl
resource "aws_ses_domain_mail_from" "example" {
  domain           = "${aws_ses_domain_identity.example.domain}"
  mail_from_domain = "bounce.${aws_ses_domain_identity.example.domain}"
}

# Example SES Domain Identity
resource "aws_ses_domain_identity" "example" {
  domain = "example.com"
}

# Example Route53 MX record
resource "aws_route53_record" "example_ses_domain_mail_from_mx" {
  zone_id = "${aws_route53_zone.example.id}"
  name    = "${aws_ses_domain_mail_from.example.mail_from_domain}"
  type    = "MX"
  ttl     = "600"
  records = ["10 feedback-smtp.us-east-1.amazonses.com"]           # Change to the region in which `aws_ses_domain_identity.example` is created
}
```

If you have further enhancement or documentation requests, please create a new GitHub issue. Thanks. 👍
