### ISSUE TITLE
aws_network_acl ingress / egress shouldn't require port details

### ISSUE THREAD

**Issue by alexjurkiewicz** [terraform-providers/terraform-provider-aws#3451]
aws_network_acl ingress & egress rule blocks unneccessarily require `to_port`/`from_port` to be specified, but these are only needed when `protocol` is tcp or udp.

Note that network_acl_rule makes these fields (correctly) as optional, and therefore isn't affected.

The AWS API spec is here: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkAclEntry.html

```
PortRange
TCP or UDP protocols: The range of ports the rule applies to.

Type: PortRange object

Required: No
```

### Terraform Version
0.11.3

### Affected Resource(s)
- AWS Network ACL: aws_network_acl

### Terraform Configuration Files
```hcl
resource "aws_network_acl" "test" {
  vpc_id = "XXX"

  # Allow ICMP
  ingress {
    protocol   = "icmp"
    rule_no    = 1
    action     = "allow"
    icmp_type  = "-1"
    icmp_code  = "-1"
    cidr_block = "0.0.0.0/0"
  }

  egress {
    protocol   = "icmp"
    rule_no    = 1
    action     = "allow"
    icmp_type  = "-1"
    icmp_code  = "-1"
    cidr_block = "0.0.0.0/0"
  }
```

### Expected Behavior
What should have happened?

### Actual Behavior
```
Error: aws_network_acl.test: "egress.0.from_port": required field is not set
Error: aws_network_acl.test: "egress.0.to_port": required field is not set
Error: aws_network_acl.test: "ingress.1.from_port": required field is not set
Error: aws_network_acl.test: "ingress.1.to_port": required field is not set
```

**Comment by alexjurkiewicz** [comment]
It appears this is a deliberate design decision. [Link to code](https://github.com/terraform-providers/terraform-provider-aws/blob/9da03132b3b18ca0ff395a68ed5e39942d84a162/aws/resource_aws_network_acl.go#L397)

```
// Protocol -1 rules don't store ports in AWS. Thus, they'll always
// hash differently when being read out of the API. Force the user
// to set from_port and to_port to 0 for these rules, to keep the
// hashing consistent.
```

**Comment by alexjurkiewicz** [comment]
This is also documented in the documentation:

```
protocol - (Required) The protocol to match. If using the -1 'all' protocol, you must specify a from and to port of 0.
```

Is it possible to change behaviour so that port doesn't have to be specified, in-line with the `aws_network_acl_rule` resource?

**Comment by alexjurkiewicz** [comment]
Also, I think there's a documentation gap -- the same logic should apply to ICMP right?

**Comment by bflad** [comment]
> Is it possible to change behaviour so that port doesn't have to be specified

Yes its possible, but it requires migrating the data in everyone's Terraform state from the old hashing to the new hashing so it does not show as a change. For examples of this in the past, see the files named `aws/*_migrate.go` and `aws/*_migrate_test.go`
