### ISSUE TITLE
Add gitCloneDepth to aws_codebuild_project

### ISSUE THREAD

**Issue by TaiSHiNet** [terraform-providers/terraform-provider-aws#3457]
Right now projects are being created with gitCloneDepth = 0 (which is basically "Full"), it would be great to add support for other values as documented:

https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html#CodeBuild-Type-ProjectSource-gitCloneDepth

**Comment by bflad** [comment]
Support for configuring `git_clone_depth` has been merged into master and will release with v1.21.0 of the AWS provider, likely middle of next week. 👍
