### ISSUE TITLE
Please export invoke_url for aws_api_gateway_stage

### ISSUE THREAD

**Issue by saxonww** [terraform-providers/terraform-provider-aws#3468]
### Terraform Version

Terraform v0.11.3
+ provider.aws v1.9.0

### Affected Resource(s)

aws_api_gateway_stage

### Expected Behavior

I'd like the invoke_url output by aws_api_gateway_deployment to be output here as well; each stage has its own invoke_url.

### Actual Behavior

No invoke_url is exported

### Steps to Reproduce

try to use "${aws_api_gateway_stage.name.invoke_url}"

**Comment by marcoreni** [comment]
Any update about this? Right now we have to use a workaround to get the `invoke_url`

**Comment by bflad** [comment]
`execution_arn` and `invoke_url` attributes are now available on the `aws_api_gateway_stage` resource via #3469 and will release with v1.16.0 of the AWS provider, likely tomorrow.

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
