### ISSUE TITLE
Terraform wants to unencrypt RDS replica after 2nd pass

### ISSUE THREAD

**Issue by hegyre** [terraform-providers/terraform-provider-aws#3470]
### Terraform Version
Tested with:
- Terraform 0.10.5 and AWS provider 1.1.0
- Terraform 0.11.3 and AWS provider 1.9.0

### Affected Resource(s)
- aws_db_instance

### Terraform Configuration Files
I put below only the usefull concerned paramers of the instance.
```hcl
# Initial master DB
resource "aws_db_instance" "db_prd_ca" {
  identifier                  = "${var.project}-db-prd-ca"
  # We do not create a default DB
  #name                        = "${var.project}-db-prd-ca"
  
  engine                      = "mysql"
  engine_version              = "5.6.37"
  instance_class              = "db.m4.large"
  storage_type                = "gp2"
  storage_encrypted           = true
  allocated_storage           = 250
  ...
}

# Replica DB
resource "aws_db_instance" "db_prd_ca_replica" {
  identifier                  = "${var.project}-db-prd-ca-replica"
  replicate_source_db         = "${aws_db_instance.db_prd_ca.id}"
  
  instance_class              = "db.t2.small"
  # We still need to specify the storage encryption just for Terraform, or else the 2nd pass, Terraform will try to set it to false
  #storage_encrypted           = true
  ...
}

```

### Expected Behavior
Since I did not specify the `storage_encrypted` parameter for the replica DB, and since the source DB is encrypted, Terraform should just ignore that parameter (like it does also for `allocated_storage`, `engine`, ...) instead of defaulting to false and trying to force unencrypt it.

### Actual Behavior
Terraform plan:
```
aws_db_instance.db_prd_ca_replica (new resource required)
...
id:                          "dcsnv-db-prd-ca-replica" => <computed> (forces new resource)
storage_encrypted:           "true" => "false" (forces new resource)
```

### Steps to Reproduce
You can test with the config above (Keep the Comment for `storage_encrypted` parameter           
1. `terraform apply` (in order to create the DB and its replica)
2. `terraform plan` (it will show you that it will try to re-create the replica unencrypted)

**Comment by bflad** [comment]
Hi @hegyre! 👋 Sorry for the slightly unexpected behavior here.

We might be able to mark this attribute as `Optional: true` and `Computed: true` here to fix this behavior for replica instances since it is derived from the parent instance. Does setting `storage_encrypted = true` on the replica have any adverse effects on creating/maintaining the resource?

**Comment by hegyre** [comment]
Hi @bflad 
Thanks for the fix suggestion !

Setting `storage_encrpyted = true` for maintening the resource or for creating it is fine, I've not noted any adverse effects.
