### ISSUE TITLE
aws_kinesis_stream resource vs data - attribute inconsistency

### ISSUE THREAD

**Issue by bacoboy** [terraform-providers/terraform-provider-aws#3476]
The [kinesis stream data source](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_kinesis_stream.go#L39) contains an `open_shards` attribute which is not in the [kinesis stream resource](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_kinesis_stream.go).

At first I thought this was an oversight.

I was converting a data reference to an imported terraform managed resource only to discover that my cloudwatch alarm couldn't find this attribute:

```
* aws_cloudwatch_metric_alarm.ds-customer-track-incomingrecords: Resource 'aws_kinesis_stream.ds-customer-track' does not have attribute 'open_shards' for variable 'aws_kinesis_stream.ds-customer-track.open_shards'
```

I see there is a [`shard_count`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_kinesis_stream.go#L134) which appears to be the number of open shards, but I guess there is a general inconsistency in naming between the resource and the data source that I haven't seen elsewhere.

Should the output attributes of these 2 match more closely like with `aws_dynamodb_table`, etc..?

**Comment by bflad** [comment]
Hi @bacoboy! 👋  It looks like this inconsistency arose due to the names of the parameter of the CreateStream API call (`ShardCount`) versus what the attribute returned by the DescribeStreamSummary API call (`OpenShards`).

**Comment by bacoboy** [comment]
Yea, doesn't seem like something to be fixed in terraform.  TF is matching the AWS universe.  Now that I think about it, it makes sense -- when you create a stream you have a desired `ShardCount`, but once opened, the number of open/closed shards depends on the state of things.

Gonna close this.
