### ISSUE TITLE
Documentation bug: aws_waf_rule contains incorrect predicates

### ISSUE THREAD

**Issue by completenovice** [terraform-providers/terraform-provider-aws#3486]
### Affected Resource(s)
- aws_waf_rule

The documentation states for predicates:
- predicates \- (Optional) One of ByteMatchSet, IPSet, SizeConstraintSet, SqlInjectionMatchSet, or XssMatchSet objects to include in a rule.

But when terraform plan is run the error:
```
Error: aws_waf_rule.waf_sqli_rule: "predicates.0.type" must be one of IPMatch | ByteMatch | SqlInjectionMatch | SizeConstraint | XssMatch
```

The documentation should reflect what is expected by the resource.

**Comment by loivis** [comment]
The inconsistency might come from [aws documentation](https://docs.aws.amazon.com/waf/latest/APIReference/API_Predicate.html). It looks like `ByteMatchSet` is the object name while `ByteMatch` is the object value?
