### ISSUE TITLE
Outputs of conditional resources crashes terraform  when changing count from 1 to 0, or from * to 0

### ISSUE THREAD

**Issue by ebarault** [terraform-providers/terraform-provider-aws#3498]
AWS_Provider: 1.9.0
Terraform: 0.11.3
---

hi, 

As per the various recommendations, I have the following configuration to manage outputs of my conditional resources:

```hcl
resource "aws_cloudwatch_log_group" "log_group" {
  count   = "${var.cloudwatch_log_group != 0 ? 1 : 0}"
  name    = "${local.cloudwatch_log_group_name}"
}

resource "aws_cloudwatch_log_stream" "log_stream" {
  count          = "${var.cloudwatch_log_group != 0 ? length(var.cloudwatch_log_streams) : 0}"
  name           = "${var.cloudwatch_log_streams[count.index]}"
  log_group_name = "${aws_cloudwatch_log_group.log_group.name}"
}

output "cloudwatch_log_group_arn" {
  value = "${element(concat(aws_cloudwatch_log_group.log_group.*.arn, list("")), 0)}"
}

output "cloudwatch_log_streams_arns" {
  value = "${compact(concat(aws_cloudwatch_log_stream.log_stream.*.arn, list("")))}"
}
```

While this works fine to compute the outputs initially, whatever the resource count (0, 1, or *), it fails when changing from 1 to 0, or from * to 0.

Say for example i created a log stream, or a log group, and then decides to remove it, terraform crashes with

```hcl
# example for cloudwatch_log_streams_arns
...
aws_iam_policy.cloudwatch_logs_access_policy: Destruction complete after 1s
Error: Error applying plan:

1 error(s) occurred:

* output.cloudwatch_log_group_arn: Resource 'aws_cloudwatch_log_group.log_group' does not have attribute 'arn' for variable 'aws_cloudwatch_log_group.log_group.*.arn'
```

```hcl
# example for aws_cloudwatch_log_stream
...
aws_cloudwatch_log_stream.log_stream: Destruction complete after 0s
Releasing state lock. This may take a few moments...
Error: Error applying plan:

1 error(s) occurred:

* output.cloudwatch_log_streams_arns: Resource 'aws_cloudwatch_log_stream.log_stream' does not have attribute 'arn' for variable 'aws_cloudwatch_log_stream.log_stream.*.arn'
```

Re-applying works with no issue.

To me it's kind of an additional issue on top of the rest, as the recommended fixes don't work.

**I'm very concerned as @brikis98 by such issues, as I have many places in my deployed modules where such configurations (which I nevertheless considered safe), could blow out when changing resources count.**

Any suggestion?
Is there a feature flag to prevent errors in output from popping until this is fixed? Couldn't have `TF_OUTPUT_ERRORS` introduced in #16204 working...

--- 
Linked to: https://github.com/hashicorp/terraform/issues/16726

cc: @danhart, @brikis98

**Comment by bflad** [comment]
Hi @ebarault! 👋 Is there a particular reason this issue was opened in this repository after the discussion that occurred in https://github.com/hashicorp/terraform/issues/16726? The underlying configuration problem described seems really like an upstream Terraform core issue and not provider specific. If you disagree, please let us know. Just trying to determine what type of fix or enhancement you would expect within the provider, if any, since Terraform core manages `output`s.

**Comment by jbardin** [comment]
Hi,

This is definitely a core issue. Moving discussion over to the terraform repo: https://github.com/hashicorp/terraform/issues/17425.
