### ISSUE TITLE
Error creating SES rule

### ISSUE THREAD

**Issue by anshprat** [terraform-providers/terraform-provider-aws#3509]
TF / AWS is throwing an error saying ses rule-set does not exist when that very rule set creation is the operation being carried out: (account id masked out)

### Terraform Version
terraform -v
Terraform v0.11.3
+ provider.aws v1.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ses_receipt_rule

> 
> + aws_ses_receipt_rule.catchall
>       id:                              <computed>
>       enabled:                         "true"
>       name:                            "stg-catchall"
>       rule_set_name:                   "default-rule-set"
>       scan_enabled:                    "true"
>       sns_action.#:                    "1"
>       sns_action.2676650771.position:  "3"
>       sns_action.2676650771.topic_arn: "arn:aws:sns:us-east-1:121212121212:stg-inbound-all-domains"
>       tls_policy:                      <computed>
> 
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> aws_ses_receipt_rule.catchall: Creating...
>   enabled:                         "" => "true"
>   name:                            "" => "stg-catchall"
>   rule_set_name:                   "" => "default-rule-set"
>   scan_enabled:                    "" => "true"
>   sns_action.#:                    "" => "1"
>   sns_action.2676650771.position:  "" => "3"
>   sns_action.2676650771.topic_arn: "" => "arn:aws:sns:us-east-1:121212121212:stg-inbound-all-domains"
>   tls_policy:                      "" => "<computed>"
> 
> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * aws_ses_receipt_rule.catchall: 1 error(s) occurred:
> 
> * aws_ses_receipt_rule.catchall: Error creating SES rule: RuleSetDoesNotExist: Rule set does not exist: default-rule-set
>     status code: 400, request id: masked
> 
> 
> 
> From TF Debug logs:
> 
>  Action=CreateReceiptRule&Rule.Actions.member.1.SNSAction.TopicArn=arn%3Aaws%3Asns%3Aus-east-1%3A121212121212%3Astg-inbound-all-domains&Rule.Enabled=true&Rule.Name=stg-catchall&Rule.ScanEnabled=true&RuleSetName=default-rule-set&Version=2010-12-01
> 2018-02-20T10:09:58.886+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: -----------------------------------------------------
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 2018/02/20 10:10:00 [DEBUG] [aws-sdk-go] DEBUG: Response email/CreateReceiptRule Details:
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: ---[ RESPONSE ]--------------------------------------
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: HTTP/1.1 400 Bad Request
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: Connection: close
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: Content-Length: 291
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: Content-Type: text/xml
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: Date: Tue, 20 Feb 2018 masked GMT
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: X-Amzn-Requestid: masked
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: -----------------------------------------------------
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: 2018/02/20 masked [DEBUG] [aws-sdk-go] <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:   <Error>
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:     <Type>Sender</Type>
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:     <Code>RuleSetDoesNotExist</Code>
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:     <Message>Rule set does not exist: default-rule-set</Message>
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:   </Error>
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4:   <RequestId>masked</RequestId>
> 2018-02-20T10:10:00.492+0530 [DEBUG] plugin.terraform-provider-aws_v1.9.0_x4: </ErrorResponse>
>

**Comment by oscr** [comment]
Hi @anshprat 

I believe that Terraforms behavior is correct. The error message `RuleSetDoesNotExist` is as you say because a the provided rule set doesn't exist. However the resource ` aws_ses_receipt_rule` isn't a rule set, it's a rule. I believe that the resource you're looking for is `aws_ses_receipt_rule_set`: https://www.terraform.io/docs/providers/aws/r/ses_receipt_rule_set.html 

I hope this helps you out!

**Comment by anshprat** [comment]
ah! makes sense, will test and update!

**Comment by bflad** [comment]
Closing as this appears to be answered above.
