### ISSUE TITLE
better docs about output variables for aws_opsworks_instance

### ISSUE THREAD

**Issue by 5c077yP** [terraform-providers/terraform-provider-aws#3547]
Hi there,

### Terraform Version

```bash
> terraform -v
Terraform v0.11.3
+ provider.aws v1.6.0
```

### Affected Resource(s)

- aws_opsworks_instance

### Expected Behavior

I was searching the terrarform docs to understand the output of the `aws_opsworks_instance` resource, as I needed the actual `ec2_instance_id`, so i could attach the instance manually to an ALB (not supported by OpsWorks itself). The docs don't mention it, but fortunately it's implemented 😄  and exposing a lot (maybe all?) attributes of the go aws sdk for the "describeInstances" call. Now i'm just wondering is this behaviour "undocumented" api and might be lost at any time? Otherwise maybe a link in the terraform docs to the code, or a small note that some more variable are exposed could be helpful.

### Actual Behavior

It's not documented but exists.

Thanks

**Comment by bflad** [comment]
The `ec2_instance_id` attribute was documented and published awhile ago 😅 https://www.terraform.io/docs/providers/aws/r/opsworks_instance.html#ec2_instance_id

If you are looking for anything else specific, please let us know.

**Comment by 5c077yP** [comment]
cool thanks, haven't checked this issue for a while 👍
