### ISSUE TITLE
Spot price should be optional in aws_spot_instance_request resource

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#3548]
In version 0.11.3, spot_price is **required**. However, according to the [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotInstances.html), the spot price is not required and defaults to the On-Demand price. This is _very convenient_ because you don't need to provide any price if you are willing to have the On-Demand price be your maximum price. (Of course, you are hoping to come in below that and usually you will.)

### Affected Resource(s)
- aws_spot_instance_request
- aws_spot_fleet_request

### Expected Behavior
You don't provide a `spot_price` and AWS will default to the On-Demand price (max price, not price you are necessarily going to pay).

### Actual Behavior
Throws an error because `spot_price` is required.

### Steps to Reproduce
1. Create an aws_spot_instance_request/aws_spot_fleet_request without spot_price
2. When you `terraform init`, error is thrown

**Comment by YakDriver** [comment]
@fredsig I created a new PR #4424 and updated this issue to also address SFRs.

**Comment by fredsig** [comment]
Thanks!

**Comment by bflad** [comment]
Per #4424 `spot_price` is now optional for `aws_spot_fleet_request` and `aws_spot_instance_request` -- this will be released in v1.18.0 of the AWS provider in about two days.

**Comment by bflad** [comment]
This has been released in [version 1.18.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1180-may-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
