### ISSUE TITLE
Add ability to import a certificate with aws_acm_certificate

### ISSUE THREAD

**Issue by grimm26** [terraform-providers/terraform-provider-aws#3560]
Please expand the `aws_acm_certificate` resource to support the ability to import an existing in-hand certificate, a la https://docs.aws.amazon.com/sdk-for-go/api/service/acm/#ACM.ImportCertificate

**Comment by bflad** [comment]
Interesting idea. Maybe this could be implemented via:
* New `certificate`, `certificate_chain`, and `private_key` attributes
* Use `CustomizeDiff` to fail plan time validation if one of the new attributes is defined but another one is missing OR if `validation_method` is missing
* Set `Optional: true` on `validation_method` attribute
* Set `ConflictsWith: []string{"private_key"}` on existing attributes `domain_name`, `subject_alternative_names`, and `validation_method`
* In the Create function, if `d.GetOk("private_key")` then call ImportCertificate

For the acceptance testing, we could probably get away with using the TLS provider to generate self-signed certificates to import

**Comment by mouellet-coveo** [comment]
This would be a really nice improvement since ACM seems to support the in-place update of the certificate.

**Comment by thisisthetechie** [comment]
Yes please, I'd like the ability to import my Certificates using Terraform, otherwise it's a mess of having to perform an outside API call to do it...

**Comment by mcolley73** [comment]
Yes, please. Otherwise we have to bounce out of terraform to do this elsewhere and then come back.

**Comment by bflad** [comment]
This is not a slight against anyone who posted here (I promise!), but we are now including the following note in our feature request issue template for the repository:

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

I have a feeling this probably would garner more community/maintainer attention if it were not for the current lack of 👍  reactions on the original issue above. The feature request certainly seems valuable. Unfortunately the upvotes on my comment do not show up in the top level GitHub issue sorting. 😄 

As I'm writing this I now feel like we should go back through all the old issues and add that note. It'd
 probably be very helpful especially for those not actively working with this project. 😅

**Comment by pemcconnell** [comment]
per:

>If you are interested in working on this issue or have submitted a pull request, please leave a comment

I currently have this working locally - just cleaning things up & ensuring it's all tested. PR should follow once it's ready for review

**Comment by kbuchsicf** [comment]
This would be a good addition!

**Comment by bflad** [comment]
Support for ACM importing of certificates (e.g. uploading them) has been merged and will release with version 1.54.0 of the AWS provider, very shortly. 👍

**Comment by bflad** [comment]
This has been released in [version 1.54.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1540-december-21-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
