### ISSUE TITLE
Only create a resource in a particular workspace

### ISSUE THREAD

**Issue by jonathan-kosgei** [terraform-providers/terraform-provider-aws#3565]
Is it possible to skip creating a resource depending on the workspace?

For example; Not creating route53 records if in the `test` workspace?

**Comment by loivis** [comment]
I guess you can use `count`?

**Comment by bflad** [comment]
If the solution is not as simple as the above, I would suggest re-opening this issue in https://github.com/hashicorp/terraform/ as the Terraform workspace functionality is in Terraform's core, not in the AWS (or any) specific provider. 👍

**Comment by jonathan-kosgei** [comment]
@loivis I'm not sure that'd work on a route53 resouce.
@bflad Thanks I'll do that.
