### ISSUE TITLE
aws_eip.nat_default: Failure associating EIP: AuthFailure: You do not have permission to access the specified resource.

### ISSUE THREAD

**Issue by hutger** [terraform-providers/terraform-provider-aws#3572]
Hi there,

### Terraform Version
$ terraform -v
Terraform v0.11.3
+ provider.aws v1.10.0

### Affected Resource(s)
aws_eip

### Terraform Configuration Files
```hcl
resource "aws_eip" "EIP_NAT_GW" {
    network_interface = "${aws_network_interface.IF_NAT_GW.id}"
    vpc               = true

    tags {
        "Name" = "EIP_NAT_GW"
    }
}

resource "aws_nat_gateway" "NAT-GW" {
    allocation_id = "${aws_eip.EIP_NAT_GW.id}"
    subnet_id = "${aws_subnet.SUBNET_X.id}"

    tags {
        "Name" = "NAT-GW"
    }
}
```

### Debug Output

1 error(s) occurred:

* aws_eip. EIP_NAT_GW: 1 error(s) occurred:

* aws_eip. EIP_NAT_GW: AuthFailure: You do not have permission to access the specified resource.
	status code: 400, request id: 7b370d25-66de-476c-8ccb

### Expected Behavior

Creates NAT and associates EIP with it. All consecutive runs should succeed.

### Actual Behavior
After the first run, all others fails.

### Steps to Reproduce
Execute ```terraform``` apply twice

**Comment by diogomatsubara** [comment]
Hi @bflad I got a similar issue (AuthFailure error) as reported here when I try to associate an EIP, through an aws_eip_association to a aws_nat_gateway instance. I'm trying to submit this PR https://github.com/starkandwayne/codex/pull/136 to the codex project and I got that error. I see that you marked the issue as bug on Feb so I wonder if you managed to confirm this is an actual bug in the terraform aws provider or if you need further debug details. I can provide more detailed debug info if it helps narrow down the issue.

**Comment by bflad** [comment]
Hi @diogomatsubara 👋  the maintainers try to do a quick pass on new issues/PRs when they first come in to help determine whether they are a bug/enhancement/question/misunderstanding and which service they're associated with to make them easier to find.

At second (quick again) glance, the above does look like a bug (plan should always succeed after a successful apply) or implies some missing documentation with respect to handling EIPs and NAT Gateways, I have not personally done any further investigation in this situation.

Extra debug logs would be helpful for the community or any maintainer who might look at/fix this though!

**Comment by diogomatsubara** [comment]
@bflad thanks for the quick response! [Here](https://gist.github.com/diogomatsubara/0e9ec300b348dbae37e9b38f5c468447) is the relevant log of the failure from terraform trace logs.

Another thing worth mentioning which is different from the OP, I got that failure with the first terraform apply using this [aws.tf](https://github.com/starkandwayne/codex/pull/136/files#diff-c1556942f1c2321d63b773a3304a1b2c) from the codex project. Today I'm going to narrow down the issue to a smaller tf config and will report back here. Or would be worth to file a separate issue as to not highjack @hutger bug report?

**Comment by diogomatsubara** [comment]
Another thing that is probably relevant, the user used to create/modify the resources have the  PowerUserAccess AWS policy attached which gives the user FullAccess for all EC2 resources.

**Comment by bflad** [comment]
Relevant pieces (cleaned output):

```
EIP association configuration: {
   AllocationId: "eipalloc-05f85ee8bd2333bda",
   NetworkInterfaceId: "eni-24074511"
}
...
Action=AssociateAddress&AllocationId=eipalloc-05f85ee8bd2333bda&NetworkInterfaceId=eni-24074511&Version=2016-11-15
...
<Response><Errors><Error><Code>AuthFailure</Code><Message>You do not have permission to access the specified resource.</Message></Error></Errors><RequestID>6d533c19-5840-42e2-84da-1ac9584a6f6e</RequestID></Response>
```

In the original issue report above I wonder if it works fine if you remove `network_interface` from the `aws_eip` configuration? 

@diogomatsubara does your configuration require the `aws_eip_association` resource for some reason? What happens if you remove it? Seems like the `aws_nat_gateway` resource should handle the association for you (same as `aws_lb` does in case of network load balancers).

**Comment by bflad** [comment]
Presuming the EIP is already managed by Terraform, it will not be released ("destroyed") unless the `aws_eip` resource is removed. disassociating != releasing

Its probably important to note that the configuration changes linked earlier in [aws.tf](https://github.com/starkandwayne/codex/pull/136/files#diff-c1556942f1c2321d63b773a3304a1b2c) are creating a new EIP unless you plan on importing it first. The EIP association should occur automatically with the creation of the `aws_nat_gateway` resource (although I'm not sure about the behavior if the EIP is already associated to something else). If you're trying to move the existing NAT instance public IP and its not already an EIP, I'm not sure thats possible.

**Comment by bflad** [comment]
Documentation PR submitted: #4675

**Comment by bflad** [comment]
Documentation updates for `aws_eip` and `aws_eip_association` resources will go out later today. 👍
