### ISSUE TITLE
S3 Cross-Account Cross-Region Replication with KMS

### ISSUE THREAD

**Issue by jrstarke** [terraform-providers/terraform-provider-aws#3575]
Hi there,

PR #2625, added support for Cross-Region Replication, but missed the `Account` and `AccessControlTranslation` attributes on the rules destination (https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#Destination). As such, when you replicate objects a bucket in a second account, by default they are inaccessible to that account, unless the objects ACL specifically granted access to the account before replication.

- GH-2200

**Comment by dforsber-p** [comment]
+1

**Comment by jnoss** [comment]
+1

**Comment by cornfeedhobo** [comment]
@jrstarke #2625 is merged! Let's kick these tires (and thank you)!

**Comment by jrstarke** [comment]
@cornfeedhobo #2625 gets cross region replication, but not the cross account replication (due to missing AccessControlTranslation (see #3577)

**Comment by ewbankkit** [comment]
This is the same issue as https://github.com/terraform-providers/terraform-provider-aws/issues/2221. I'll close that as a duplicate.

**Comment by bflad** [comment]
Huge shout out to @jrstarke and @ewbankkit! This functionality has been merged and will be released in version 1.40.0 of the AWS provider, likely later today. 🚀
