### ISSUE TITLE
support creating Aurora Postgres 10.1

### ISSUE THREAD

**Issue by aleksandersumowski** [terraform-providers/terraform-provider-aws#3583]
### Intro
Amazon just released for Postgres 10.1 on Aurora
https://forums.aws.amazon.com/ann.jspa?annID=5501

### Terraform Version
Terraform v0.11.3
+ provider.aws v1.10.0
+ provider.random v1.1.0

### Affected Resource(s)
- rds_cluster
- rds_cluster_instance

### Terraform Configuration Files
resource "aws_rds_cluster" "db_cluster" {
  cluster_identifier           = "${var.}-${terraform.workspace}-${var.db_identifier}"
  database_name                = ""
  master_password              = "${random_string.db_password.result}"
  master_username              = ""
  availability_zones           = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  backup_retention_period      = 5
  vpc_security_group_ids       = ["${aws_security_group.__db.id}"]
  storage_encrypted            = true
  db_subnet_group_name         = "${aws_db_subnet_group.__db.id}"
  engine                       = "aurora-postgresql"
  engine_version               = "10.1"
}

resource "aws_rds_cluster_instance" "db_cluster_instance" {
  count                        = 1
  identifier                   = "${var.}-${terraform.workspace}-${var.db_identifier}-${count.index}"
  cluster_identifier           = "${aws_rds_cluster._db_cluster.id}"
  instance_class               = "${var.db_instance_type}"
  db_subnet_group_name         = "${aws_db_subnet_group.manage_db.id}"
  performance_insights_enabled = true
  engine                       = "aurora-postgresql"
  engine_version               = "10.1"
}

Some parts removed for confidentiality reasons

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* aws_rds_cluster_instance.db_cluster_instance: 1 error(s) occurred:

* aws_rds_cluster_instance.db_cluster_instance: InvalidParameterCombination: The engine version that you requested for your DB instance (10.1) does not match the engine version of your DB cluster (9.6.3).
	status code: 400, request id: 7d0cb016-e440-4502-943b-526bb42bb88a

### Expected Behavior
Aurora Postgres 10.1 cluster instance should have been created

### Actual Behavior
cluster gets created, cluster_instance doesn't

### Steps to Reproduce
1. `terraform apply`

**Comment by petestorey26** [comment]
I'm afraid you're mistaken - re-read the AWS Blog post, it's Postgres 10.1 that's available on RDS, _not_ Aurora Postgres, which is still 9.6.3 only.

**Comment by aleksandersumowski** [comment]
@petestorey26 you're right. no Postgres 10 for Aurora yet. 9.6.6 is now available in Aurora but thats not a huge difference

**Comment by bflad** [comment]
@aleksandersumowski is it okay to close this issue or is there something you would like done differently with the provider in this case?

**Comment by aleksandersumowski** [comment]
it's ok to close it
