### ISSUE TITLE
IAM role resources: role.id is inconsistent

### ISSUE THREAD

**Issue by stmarier** [terraform-providers/terraform-provider-aws#3632]
### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
- aws_iam_role_policy
- aws_iam_role_policy_attachment
- possibly others

### Terraform Configuration Files
```
resource "aws_iam_role_policy_attachment" "managed_policies" {
  role = "${aws_iam_role.something.name}"
  [...]
}
---
resource "aws_iam_role_policy" "inline_policies" {
  role = "${aws_iam_role.something.id}"
  [...]
}
```

### Expected Behavior
Desired properties should IMO be a suffix of the parameter name.  For example, `role_arn`, `role_name`,  or`role_id` instead of `role`.  To me, `role` implies we are passing the role object, which would be really nice, but I don't think we are doing that.

Additionally, the role.id data as shown in state does not appear to actually be an IAM role id (it looks like it is just a duplicate of the friendly name), so I'm not sure why it's a property.  The actual role id appears to be tracked in the `unique_id` attribute.

If the role.id attribute is deprecated, usage of it should be removed from the documentation (`aws_iam_role_policy` resource).

### Actual Behavior
The role_policy resource has a documentation example that uses the `role.id` property, while the role_policy_attachment resource documentation uses the `role.name` property.  In state, these are both the same value.

### Important Factoids
Latest documentation (as far as I can tell) reflects this.

**Comment by aeschright** [comment]
Thanks for letting us know about this concern. We're now moving all questions and community discussions to our forum: https://discuss.hashicorp.com/c/terraform-providers

If there's still a remaining feature or documentation request, please [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) using the appropriate template.
