### ISSUE TITLE
using `compact` results in "vpc_security_group_ids: should be a list"

### ISSUE THREAD

**Issue by nathanielks** [terraform-providers/terraform-provider-aws#3647]
### Terraform Version
Terraform v0.11.3
+ provider.archive v1.0.0
+ provider.aws (unversioned)
+ provider.random v1.1.0
+ provider.template v1.0.0

I'm using a fork of provider.aws that's based on v0.10 (for https://github.com/terraform-providers/terraform-provider-aws/pull/3480), but I tested with vanilla terraform and the issue still exists.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_db_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

[rds.tar.gz](https://github.com/terraform-providers/terraform-provider-aws/files/1787322/rds.tar.gz)
```hcl
variable "security_groups" {
  type    = "list"
  default = []
}

# ... Other resources

resource "aws_db_instance" "mod" {
  vpc_security_group_ids = "${compact(concat(list(aws_security_group.mod.id), var.security_groups))}"

  ## Everything else
  # ...
}
```

Example module usage:
```hcl
module "rds" {
  source = "../modules/rds"

  name                  = "${var.name}"
  environment           = "${var.environment}"
  vpc_id                = "${data.terraform_remote_state.vpc.vpc_id}"
  vpc_cidr              = "${data.terraform_remote_state.vpc.cidr_range}"
  subnets               = ["${data.terraform_remote_state.vpc.internal_subnets}"]
  multi_az              = "${var.rds_multi_az}"
  apply_immediately     = "${var.rds_apply_immediately}"
  instance_class        = "${var.rds_instance_class}"
  allocated_storage     = "${var.rds_allocated_storage}"
  db_parameter_group    = "${var.rds_parameter_group}"
  ec2_security_group_id = "${module.cluster.cluster_security_group_id}"
  subnet_group_name     = "${var.rds_subnet_group}"
  engine                = "mysql"
  engine_version        = "${var.rds_engine_version}"
  storage_type          = "standard"
  multi_az              = "false"

  security_groups = ["${var.rds_security_group}"]

  publicly_accessible = true
  skip_final_snapshot = true

  master_username = "${var.rds_master_username}"
  master_password = "${data.aws_ssm_parameter.rds_master_password.value}"
  db_name         = "${var.rds_db_name}"
}
```

### Debug Output

https://gist.github.com/nathanielks/5ea00920b395e59c071a13ce7da30c63

### Expected Behavior
`compact` returns a list, so I would expect it to work. I also tried the following, to no avail:
```
  vpc_security_group_ids = ["${compact(concat(list(aws_security_group.mod.id), var.security_groups))}"]
```

### Actual Behavior
Terraform threw an error saying: `Error: module.rds.aws_db_instance.mod: vpc_security_group_ids: should be a list`. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Nothing crazy! 

### References
None!

**Comment by nathanielks** [comment]
I can reproduce this with `aws_instance`:

```
variable "region" {
  default = "us-east-1"
}

variable "name" {
  default = "tf-test-compact-list"
}

provider "aws" {
  region = "${var.region}"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

variable "security_groups" {
  type    = "list"
  default = []
}

resource "aws_security_group" "allow_all" {
  name        = "allow_all"
  description = "Allow all inbound traffic"

  ingress {
    from_port   = 0
    to_port     = 65535
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags {
    Name = "allow_all"
  }
}

resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  security_groups = "${compact(concat(list(aws_security_group.allow_all.id), var.security_groups))}"

  tags {
    Name = "${var.name}"
  }
}
```

**Comment by bflad** [comment]
Thanks for also creating the upstream Terraform issue https://github.com/hashicorp/terraform/issues/17514. I believe this issue does in fact belong upstream but please do let us know if its something AWS provider specific.

**Comment by nathanielks** [comment]
@bflad surely! I'm happy to fix it, but I'm unsure of a good place to start. Any direction would be helpful!

**Comment by bflad** [comment]
Closing to clean up some of the repository issues as this should be tracked (and will likely be fixed) upstream in Terraform core via https://github.com/hashicorp/terraform/issues/17514
