### ISSUE TITLE
aws_ecs_task_definition: Support Docker healthchecks

### ISSUE THREAD

**Issue by tomelliff** [terraform-providers/terraform-provider-aws#3691]
The AWS Go SDK [now supports Docker healthchecks on container definitions](https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11311-2018-03-08).

I think we just need to bump the vendored SDK to enable this because we validate the container definitions match the `ecs.ContainerDefinition` type.

**Comment by bflad** [comment]
Dependency PR: #3693 (it might be able to make it in before v1.11.0 is released)

**Comment by austinbutler** [comment]
Did it make it into 1.11? Doesn't seem to be working.
