### ISSUE TITLE
CodeDeploy to Lambda

### ISSUE THREAD

**Issue by agarstang** [terraform-providers/terraform-provider-aws#3692]
AWS CodeDeploy applications now support deploying to Lambda functions:
https://docs.aws.amazon.com/codedeploy/latest/userguide/applications-create-lambda.html

As of v1.10.0 setting the "compute platform" of a lambda function is not supproted.

# References
https://www.terraform.io/docs/providers/aws/r/codedeploy_app.html
#3368

**Comment by bflad** [comment]
The `aws_codedeploy_app` resource will include a new `compute_platform` attribute in version 1.24.0 of the AWS provider, likely releasing middle of next week.

**Comment by bflad** [comment]
This has been released in [version 1.24.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1240-june-21-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
