### ISSUE TITLE
aws_cloudtrail event_selector always shows as changed

### ISSUE THREAD

**Issue by jwperry** [terraform-providers/terraform-provider-aws#3697]
When running our Terraform, a newly created `aws_cloudtrail` object with `event_selector` defined seems to always show the `event_selector` properties as changes, even after they are applied. It seems to only be the `event_selector` properties. My team is running 0.10.7 right now, but I upgraded to 0.11.3 and saw the same thing happen. Appreciate any help or advice!

### Terraform Version
```
Terraform v0.10.7
Terraform v0.11.3
provider.aws ~> 1.10
```

### Affected Resource(s)
- aws_cloudtrail

### Terraform Configuration Files
```hcl
resource "aws_cloudtrail" "aws-console-logs" {
  name = "${var.env}-aws-console-logs"
  depends_on = ["aws_s3_bucket.aws-console-log-bucket"]
  s3_bucket_name = "${var.env}-sts-atlas-ec2-aws-console-logs"
  include_global_service_events = true
  is_multi_region_trail = true

  event_selector {
    read_write_type = "All"
    include_management_events = true
  }
}
```

### Expected Behavior
Once applied, the `event_selector` properties no longer show up as changes in `terraform plan`.

### Actual Behavior
The `event_selector` properties of this `aws_cloudtrail` resource continue to show up as changes when running a `terraform plan`, even after they've been applied:

```
Terraform will perform the following actions:

  ~ aws_cloudtrail.aws-console-logs
      event_selector.#:                           "0" => "1"
      event_selector.0.include_management_events: "" => "true"
      event_selector.0.read_write_type:           "" => "All"

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
Steps exactly as I've run them:
1. `terraform plan -state=terraform.tfstate.prod -var env=prod`
2. `terraform apply -state=terraform.tfstate.prod -var env=prod`
3. `terraform plan -state=terraform.tfstate.prod -var env=prod`

### Important Factoids
N/A

### References
N/A

**Comment by bflad** [comment]
@jwperry if you don't need to capture [CloudTrail data events](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-management-and-data-events-with-cloudtrail.html#logging-data-events) (e.g. S3 object/Lambda invocation events for specific buckets/functions), then you should not need to define the `event_selector` configuration. Removing it should get rid of your perpetual diff as well as properly enable CloudTrail in its basic configuration. 

We should probably adjust our documentation to cover the `event_selector` configuration as separately for data events.

Interestingly enough, that `event_selector` configuration is validating via the AWS SDK as well as the API is not returning an error. 😕 

https://github.com/terraform-providers/terraform-provider-aws/blob/33d5feb7b9ad9c5577d69ef669ff047560ae0f19/aws/resource_aws_cloudtrail.go#L433-L451

**Comment by jwperry** [comment]
@bflad Thanks for the quick reply! Good to know the `event_selector` isn't always necessary, I wasn't aware of that. In this case however, I think our team is looking to capture data events as well. Any other ideas?

**Comment by bflad** [comment]
@jwperry to log all S3 object operations across the account try this:

```hcl
  event_selector {
    read_write_type = "All"
    include_management_events = true

    data_resource {
      type   = "AWS::S3::Object"
      values = ["arn:aws:s3:::"]
    }
  }
```

Be sure to note the [CloudTrail service pricing for data events](https://aws.amazon.com/cloudtrail/pricing/) as well as the below in the [CloudTrail API documentation](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_DataResource.html):
> To log data events for all objects in all S3 buckets in your AWS account, specify the prefix as `arn:aws:s3:::`.
> Note
> This will also enable logging of data event activity performed by any user or role in your AWS account, even if that activity is performed on a bucket that belongs to another AWS account.

You can creating another `event_selector` for Lambda functions as well with `AWS::Lambda::Function` type and `arn:aws:lambda` value. A similar doucmentation note is in there about logging function invocations for other AWS accounts.

**Comment by jwperry** [comment]
@bflad  Hello Brian - sorry for the delay, wasn't able to address this for a few days. Thanks a lot for your help. Have discussed with my team and we've opted to remove the event selector as you originally suggested and not log data events. Thanks for the doc update and the clarification! Closing.
:+1:

**Comment by tsiq-tek** [comment]
This is actually still an issue I believe. Because in our case we don't want to log data events but we DO want to only log Write events. And to do that we have to define an event_selector{} with read_write_type = "WriteOnly". But when you do that you get perpetual diffs.

**Comment by tacchino** [comment]
Agree with the comment from @tsiq-tek. Defining an event selector on the resource even without data events does effect a change on the trail, it controls the read / write level for management events

![image](https://user-images.githubusercontent.com/1282397/43532815-63024da6-9581-11e8-9fe6-974885f7364a.png)

**Comment by ts-tek** [comment]
I've logged #5448 which addresses the scenario described by @tsiq-tek and @tacchino.

**Comment by markliederbach** [comment]
Note that #5448 has yet to be merged, which means this issue should not be considered closed.
