### ISSUE TITLE
aws_ecs_cluster config option cluster_name throws an error

### ISSUE THREAD

**Issue by mlcooper** [terraform-providers/terraform-provider-aws#3700]
### Terraform Version
```
Terraform v0.11.3
+ provider.aws v1.10.0
```

### Affected Resource(s)
- aws_ecs_cluster

### Terraform Configuration Files
```hcl
resource "aws_ecs_cluster" "foo" {
  cluster_name = "${ var.ecs_cluster_name }"
}

variable "ecs_cluster_name" {
  default = "cluster_foo"
}
```

### Debug Output
```
2018/03/09 13:05:25 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["name": required field is not set : invalid or unknown key: cluster_name]
2018/03/09 13:05:25 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["name": required field is not set : invalid or unknown key: cluster_name]
2018/03/09 13:05:25 [TRACE] [walkValidate] Exiting eval tree: aws_ecs_cluster.foo

Error: aws_ecs_cluster.foo: "name": required field is not set

Error: aws_ecs_cluster.foo: : invalid or unknown key: cluster_name
```
### Expected Behavior
Based on the documentation here, https://www.terraform.io/docs/providers/aws/d/ecs_cluster.html#cluster_name, I expected this resource to accept `cluster_name`.

### Actual Behavior
An error was produced:
```
invalid or unknown key: cluster_name
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by bflad** [comment]
Hi @mlcooper! 👋  Sorry you ran into trouble there. It appears you're looking at the [`aws_ecs_cluster` _data source_ documentation](https://www.terraform.io/docs/providers/aws/d/ecs_cluster.html), not the [`aws_ecs_cluster` _resource_ documentation](https://www.terraform.io/docs/providers/aws/r/ecs_cluster.html). You can find the difference between them described in the [configuration section of the documentation](https://www.terraform.io/docs/configuration/index.html).

In your case, the argument for the resource is just `name`:

```hcl
resource "aws_ecs_cluster" "foo" {
  name = "${var.ecs_cluster_name}"
}

variable "ecs_cluster_name" {
  default = "cluster_foo"
}
```

**Comment by mlcooper** [comment]
You are right; sorry about that confusion there...somehow I missed that when working with `aws_ecs_cluster`.
