### ISSUE TITLE
AWS Provider docs - Organizations page - formatting is broken - missing sidebar

### ISSUE THREAD

**Issue by kmcquade** [terraform-providers/terraform-provider-aws#3736]
https://www.terraform.io/docs/providers/aws/r/organizations_organization.html

![image](https://user-images.githubusercontent.com/3422255/37235307-9b284208-23cb-11e8-9f3e-cd4b6f4d0fff.png)

**Comment by bflad** [comment]
Thanks for this report! The fix is now live: https://www.terraform.io/docs/providers/aws/r/organizations_organization.html
