### ISSUE TITLE
locals are not loaded when applying tfplan for destory

### ISSUE THREAD

**Issue by sg21210** [terraform-providers/terraform-provider-aws#3740]
I noticed very weird, buggy operation.
1) Local variables are **not loaded** when applying tfplan for **destroy**.
(Instead of destroy, **update**, which does not contain destroy option, is okay)
2) terraform destroy **cannot specify the module** to destroy when the target options contain `data.terraform_remote_state` field. I'll make another issue for this.

### Terraform Version
v0.11.3
* aws provider: v1.11.0

### Affected Resource(s)
- data.terraform_remote_state
- locals

### Terraform Configuration Files
* site.tf
```hcl
provider "aws" {
  region = "${local.aws_region}"
}

terraform {
  backend "s3" {
     ...
  }
}
```
* locals.tf
```hcl
data "terraform_remote_state" "test" {
    backend = "s3"
    config {
       ...
    }
}

locals {
    aws_region = "${data.terraform_remote_state.test.site_region}"
    var1 = "${data.terraform_remote_state.test.var1}"
    ...
}
```
* other modules file. s3, ec2, ...
```hcl
module "s3-testbucket" {
  var = "${local.var1}"
  ...
}
```

### Expected Behavior
Destroy selected module after reading all the local variables

### Actual Behavior
```
Error: Error applying plan:

1 error(s) occurred:

* provider.aws: Not a valid region:
```

### Steps to Reproduce
1. `terraform plan -target=data.terraform_remote_state.test -target=module.s3-testbucket -destroy -out=test.tfplan`
2. `terraform apply test.tfplan`

You need to have **only one** .tf file. If you have more than one .tf file which refers the same terraform_remote_state, the module cannot be specified with `-target` option for the remote state.

### Important Factoids

- When I substitute `region = "${local.aws_region}"` in site.tf with `region = "${data.terraform_remote_state.aws_region}"`, then it **works!**
- When I enter `terraform destroy -target=module.s3-testbucket`, it works.
- When I follow the procedure after removing the destroy option, it also works.

**Comment by wobondar** [comment]
Same issue I had when i've tried to configure aws provider region from another module
main.tf:
```
provider "aws" {
  region  = "${module.config.region}"
}
module "config" {
  source = "../dev/aws/config"
}
```

"config" module:
```
variable "region" {
  type    = "string"
  default = "eu-west-1"
}
output "region" {
  value = "${var.region}"
}
```

`terraform init` – **OK**
`terraform validate` – **OK**
`terraform plan` – **ERROR**

error:
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: Not a valid region: 
```

versions:
```
Terraform v0.11.3
+ provider.aws v1.11.0
```

**Comment by sg21210** [comment]
I think this is unexpected behavior. With #3741 issue, the only way to destroy selected module is `terraform destroy -target=module.modulename`, which does not have `data.terraform_remote_state.name` option. Please check this issue.
