### ISSUE TITLE
Improve asymptotic efficiency of aws_kms_grant

### ISSUE THREAD

**Issue by copumpkin** [terraform-providers/terraform-provider-aws#3746]
As I described in [this comment](https://github.com/terraform-providers/terraform-provider-aws/pull/3038#issuecomment-371879090), I believe the asymptotic behavior in `aws_kms_grant` will get unpleasant for folks with quite a few grants (whether managed by terraform or not), which is not an uncommon situation.

I've come up with a slightly ugly workaround for the issue that makes looking up a KMS grant an `O(1)` operation again, at the cost of some hackiness. Because of the hackiness and this not being officially documented in AWS (although I do have a pending request with support to see how they feel about this), I think that even if my proposal is accepted, we should leave the current grant lookup code in place as a fallback. I'm not a fan of silently falling back on asymptotically worse behavior, but I'll take it if it can make the common case painless.

Anyway, here's the idea:

The `ListGrants` API call (which we already use to look up a single grant) supports pagination, but doesn't support any sort of grant lookup criterion (unlike many of the traditional AWS `Describe*` calls) beyond a limit to the number of results you want to see. If there are more results than you asked for, you get a magic pagination token that you pass back to the next `ListGrants` call and it'll give you new ones.

The hack lies in decomposing that pagination token. I noticed that `ListGrants` returned grants in lexicographic order by grant ID, and assumed that the easiest way to implement pagination in such a scheme would be to just include the last seen grant ID in the pagination token. And indeed, I un-base64'd the pagination token and sure enough the last grant ID was right there, embedded in a pretty simple (but not completely trivial) binary encoding containing the grant ID and key ID and nothing else.

So here's the lookup grant logic:

1. Take the grant ID you want to look up, and subtract 1 from its hex representation (because `ListGrants` shows grants strictly lexicographically greater than the last seen token)
2. Embed the result of 1 in a handcrafted pagination token
3. Base64
4. Call `ListGrants` with your custom token and a limit of 1
5. Enjoy a homegrown `GetGrant` API 🍾

As I said, this isn't documented so in theory AWS can break it, but in practice I doubt they will. Just in case though, it seems worthwhile leaving the current "list all grants" logic in place as a fallback (and it's trivial to detect if we need to fall back). Maybe spit out a warning that we're falling back to slow code so people don't suddenly get weirded out when their fast `terraform` invocation turns slow, but otherwise I think this is pretty safe. It's also, in my mind, vastly preferable to both the current asymptotically painful situation and the batch `ListGrants` sharing logic that would need to be implemented across resources to get a similar speedup without the hack.

Any thoughts? Tagging @paddycarver @bflad @paultyng @jammerful as the folks involved in the original `aws_kms_grant` review.

**Comment by paultyng** [comment]
This research is great, and I think definitely something to keep in mind. I am of course worried that it is potentially fragile as its an obfuscated parameter as is and not documented (or maybe it is)? I will try to run this specific thing down a little internally to see what would be the direction to go and provide some feedback. 

It may be useful to see some real world examples of problems here (or maybe a sample TF with the new resource) that demo's the issues? Hopefully people start using the resource and we will get some feedback.

**Comment by jammerful** [comment]
This is definitely worth implementing if AWS can commit to making the pagination token/marker stable.

**Comment by bflad** [comment]
Personally, I have opened a feature request support ticket with AWS Support asking for a new `GrantIds` filtering parameter on the `ListGrants` API call or a new `DescribeKeyGrants` API call. I would highly encourage others to do the same. 😄

**Comment by copumpkin** [comment]
TBC, I've also done that 😄 but API changes can take quite a while to take effect, if the service team even agrees that the change is warranted.

**Comment by jammerful** [comment]
@bflad Assuming we can get AWS to commit to not changing the structure of the pagination token/marker 
(I can sort that out), would a PR implementing the homegrown `DescribeGrant` call above be merged?

**Comment by bflad** [comment]
Hi @copumpkin 👋 Circling back to this one awhile later, thanks for filing it and all the research originally.

We are going to opt to close this feature request just due to lack of upstream KMS API support and documentation. We feel would be very risky for us to make assumptions about the API internals given that the KMS service team does not currently interact with this maintainer team regularly.

For future travelers, we would encourage filing AWS Support cases or talking with your AWS account managers to request improvements to the KMS API. If the KMS API does wind up implementing functionality that can help for this situation, we can absolutely take a look at a new feature request. 😄 Thanks all.
