### ISSUE TITLE
enable the delete timeout for aws_db_parameter_group and aws_db_subnet_group

### ISSUE THREAD

**Issue by sd0408** [terraform-providers/terraform-provider-aws#3752]
### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
aws_db_parameter_group
aws_db_subnet_group

When I run terraform destroy on my databases I always have to run it again after it fails the first time. The issue seems to be that the db parameter group and the db subnet group that are being destroyed are not waiting long enough for the databases in them to be destroyed. I'm guessing the timeout is 10min for destroy on those to resource types, and I cannot specify a destroy timeout for them. if The destroy timeout was specifiable then I would be able to set it to a longer and all would be good. 

### Expected Behavior
Either the parameter groups and db subnet groups should identify the terraform resources that they rely upon and automatically wait for those to be destroyed, or I should be able to increase the timeout on these to a point where their dependent databases are gone before they timeout. 

### Actual Behavior
Times out at 10 min and i have to rerun destroy

### Steps to Reproduce
1. Create a provisioner that created a parameter group, subnet group and a few RDS instances.
2. terraform apply that 
3. terraform destroy

**Comment by bflad** [comment]
@sd0408 can you provide the errors you're seeing please?

**Comment by sd0408** [comment]
Actually, 

I just figured out my problem. I was not properly defining the parameter_group and the db_subnet_group as dependencies so terraform didn't realize they were related to the db instances I was destroying with them. Thus they would try to destroy immedately and timeout before the db instances could destroy. 

Sorry about this. Closing
