### ISSUE TITLE
S3 permission error on aws_lambda_function with MultiFactorAuthPresent condition on user

### ISSUE THREAD

**Issue by maur1th** [terraform-providers/terraform-provider-aws#3761]
### Terraform Version
Terraform v0.11.3, v0.11.4
Provider version: 1.11

### Affected Resource(s)
- aws_lambda_function

### Terraform Configuration Files
```hcl
resource "aws_lambda_function" "events" {
  s3_bucket     = "bucket_name"
  s3_key        = "key"
  function_name = "test-tma"
  role          = "${aws_iam_role.lambda.arn}"
  handler       = "com.xxx.lambda.Main::handleRequest"
  runtime       = "java8"
}

data "aws_iam_policy_document" "lambda_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "lambda" {
  name               = "test-tma"
  assume_role_policy = "${data.aws_iam_policy_document.lambda_assume_role_policy.json}"
}
```

### Debug Output
https://gist.github.com/maur1th/f3ec074e5ba3380e1de90bf8917f702e

### Expected Behavior
Created Lambda

### Actual Behavior
`* aws_lambda_function.events: Error creating Lambda function: AccessDeniedException: Your access has been denied by S3, please make sure your request credentials have permission to GetObject for bucket_name/key. S3 Error Code: AccessDenied. S3 Error Message: Access Denied`

### Steps to Reproduce
`terraform apply`

### Important Factoids
The issue seems be linked to the calling user IAM permissions and specifically to a `aws:MultiFactorAuthPresent` condition:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": "*",
            "Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": true
                }
            }
        }
    ]
}
```
If the `Condition` object is removed, the configuration will pass. If an exception to the condition is added, the configuration will pass:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "*"
            ],
            "Resource": "*",
            "Condition": {
                "BoolIfExists": {
                    "aws:MultiFactorAuthPresent": true
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by bflad** [comment]
Hi @maur1th! 👋  Sorry you're running into trouble here. The error you're receiving is coming from the call to `CreateLambda` API. Does it work if you MFA before running Terraform?

**Comment by maur1th** [comment]
Hi @bflad Thanks for your quick response and sorry for the delay. Not sure to understand what you mean though: does it work if I log into the AWS Console with my browser using MFA before applying the Terraform configuration? If that's what you mean then no, it doesn't.

**Comment by bflad** [comment]
The AWS multi-factor authentication must usually be performed in the same command/terminal as the running Terraform process to work or the [appropriate multi-factor authentication configuration via environment variables or AWS CLI profile](https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/) must be set before calling Terraform. I do not believe we have native support for handling multi-factor (re-)authentication during Terraform commands, like physically accepting the input of MFA passcodes that rotate.

As a workaround or simplification of the process as it exists today, running a tool like https://github.com/makethunder/awsudo before calling Terraform can help (see bottom of its README for MFA configuration). Note: `awsudo` is provided as an example. I have never tried/used `awsudo` myself. There are probably other tools and those might be more adopted or suit your needs better.
