### ISSUE TITLE
Unable to apply or destroy: Error configuration for module.cacti_app_az_1.module.alb.provider.aws is not present

### ISSUE THREAD

**Issue by shonaran** [terraform-providers/terraform-provider-aws#3772]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.11.1
+ provider.aws v1.11.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume
.module.alb.data.aws_elb_service_account.main: configuration for module.cacti_app_az_1.module.alb.provider.aws is not present; a provider configuration block is required for all operations

### Expected Behavior
What should have happened?
I attempted to destroy the resources I created

### Actual Behavior
What actually happened?
Destroy failed with the above error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
terraform destroy -force -var-file=../application/variables/prod-reg1.tfvars
(This also happens with a terraform apply)

**Comment by loivis** [comment]
did you put provider configuration within the module?

**Comment by shonaran** [comment]
Yes. In the root, I placed the following:
provider "aws" {
  region = "${var.stackregion}"
}

provider "aws" {
  alias  = "moduleprovider"
  region = "${var.stackregion}"
}

At the top of main.tf, one layer below, I have:
provider "aws" {
  region = "${var.region}"
}
This applies to the ALB and ASG modules.

In a workspace that was created a while ago, I cannot apply or destroy.

If I create a new workspace, I can apply or destroy.

**Comment by shonaran** [comment]
I also upgraded to v 0.11.3. No difference.
Terraform v0.11.3
+ provider.aws v1.11.0
+ provider.template v1.0.0

**Comment by shonaran** [comment]
Update: When I create a new workspace and use terraform apply, I do not see this problem. If I make a change to the code to create a second server using terraform apply again, I get the error. If I try to destroy from an old workspace, I get the same error again
