### ISSUE TITLE
invalid or unknown key: reserved_concurrent_executions

### ISSUE THREAD

**Issue by shuqichen** [terraform-providers/terraform-provider-aws#3792]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
SHAC02NR4SLG3QD:stage chenshu$ terraform --version
Terraform v0.11.3
+ provider.aws v1.3.1
+ provider.template v1.0.0

### Affected Resource(s)
aws_lambda_function

### Terraform Configuration Files
resource "aws_lambda_function" "tr_event_trigger" {
  function_name = "${var.function_name_event_trigger}"
  handler = "index.handler"
  runtime = "nodejs6.10"
  s3_bucket = "${var.s3_bucket}"
  s3_key = "${var.s3_key_event_trigger}"
  role = "${var.lambda_role}"

  description = "Schedule calling Tr endpoint to trigger a tr event. created by terraform"
  reserved_concurrent_executions = 10
  // publish = true  // used to publish a new version
  timeout = **
  memory_size = **
  vpc_config {
    security_group_ids = ["${var.base_sg_id}","${var.tr_sg_id}"]
    subnet_ids = ["${var.lambda_subnet_1}","${var.lambda_subnet_2}","${var.lambda_subnet_3}"]
  }
}

### Debug Output

SHAC02NR4SLG3QD:stage chenshu$ terraform plan -target=module.lambda-180315

Error: module.lambda-180315.aws_lambda_function.tr_event_trigger: : invalid or unknown key: reserved_concurrent_executions

### Expected Behavior
I can use the reserved_concurrent_executions parameter in lambda function.

### Actual Behavior
Terraform returns invalid or unknown key: reserved_concurrent_executions.

### Steps to Reproduce

SHAC02NR4SLG3QD:stage chenshu$ terraform plan -target=module.lambda-180315

Error: module.lambda-180315.aws_lambda_function.tr_event_trigger: : invalid or unknown key: reserved_concurrent_executions

**Comment by loivis** [comment]
You might need to update provider-aws to a later version, better latest if no other constraint. `reserved_concurrent_executions` support was added in `1.6.0`.

**Comment by bflad** [comment]
Hi @shuqichen! 👋  Sorry you ran into trouble here. As @loivis mentioned, the `reserved_concurrent_executions` argument was added in [v1.6.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#160-december-18-2017). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

We have an issue in our backlog for versioning the Terraform documentation and I'll add a note referencing this issue to bump it up in priority.
