### ISSUE TITLE
AWS EIP: invalid or unknown key: tags

### ISSUE THREAD

**Issue by szczad** [terraform-providers/terraform-provider-aws#3793]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.6.0
+ provider.template v1.0.0

### Affected Resource(s)
- aws_eip

### Terraform Configuration Files
```hcl
resource aws_eip nat {
  vpc               = true
  network_interface = "${aws_network_interface.public}"

  tags {
    Name  = "NAT"
  }
}
```

### Debug Output
```sh
$ terraform validate                                             

Error: module.eu_west_adm_uat.aws_eip.nat: : invalid or unknown key: tags 
```

### Expected Behavior
Terraform should apply tags to EIP resource

### Actual Behavior
Error appears showing "tags" is unsupported key

### Steps to Reproduce
1. `terraform validate`

**Comment by bflad** [comment]
Hi @szczad 👋  Sorry you ran into trouble here. The `tags` argument for the `aws_eip` resource was added in [v1.7.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

We have an issue in our backlog for versioning the Terraform documentation and I'll add a note referencing this issue to bump it up in priority.

**Comment by szczad** [comment]
Yep. That solved the problem!
