### ISSUE TITLE
Apply/Destroy fails after upgrade to Terraform 0.11.4

### ISSUE THREAD

**Issue by caiges** [terraform-providers/terraform-provider-aws#3802]
After upgrading to 0.11.4, via the Docker image our `apply` and `destroy` fails. Reverting to 0.11.3 allows us to `apply` and `destroy` properly.

### Terraform Version
0.11.4

### Affected Resource(s)
I suspect this issue might affect other resources but our errors were specific to outputs that reference:
- aws_elb

### Terraform Configuration Files
```hcl

output "demo_elb_name" {
  value = "${aws_elb.demo.name}"
}

output "demo_elb_dns_name" {
  value = "${aws_elb.demo.dns_name}"
}
```

### Expected Behavior
An `apply` or `destroy` should succeed.

### Actual Behavior
`apply` or `destroy` fail with the following output:

```
Error: Error applying plan:

2 error(s) occurred:

* output.demo_server_elb_dns_name: Resource 'aws_elb.demo' does not have attribute 'dns_name' for variable 'aws_elb.demo.dns_name'

* output.demo_server_elb_name: Resource 'aws_elb.demo' does not have attribute 'name' for variable 'aws_elb.demo.name'
```

### Steps to Reproduce
1. `terraform apply` or `terraform destroy`.

**Comment by bflad** [comment]
Hi @caiges 👋 Sorry you're running into trouble here. I think we should probably keep this discussion continuing upstream in https://github.com/hashicorp/terraform/issues/17604 for now. I replied back there that I'm having trouble reproducing it with at least a simple S3 backend configuration so it might be a little harder to diagnose and triage depending on the details of your environment. 😕 

I'm going to close this issue for now as it _seems_ like it'll likely be something upstream in Terraform core, but we can absolutely reopen this if its anything particular about the AWS provider or S3 backend itself. Thanks.
