### ISSUE TITLE
AWS GameLift FleetType field not supported

### ISSUE THREAD

**Issue by timmersuk** [terraform-providers/terraform-provider-aws#3809]
Hi there,

AWS recently enhanced their [GameLift service](https://gamedev.amazon.com/forums/articles/67102/announcement-amazon-gamelift-fleetiq-spot-instance.html) by adding support for specifying a [FleetType](https://docs.aws.amazon.com/gamelift/latest/apireference/API_CreateFleet.html#API_CreateFleet_RequestSyntax) attribute on Fleet entities which allows GameLift fleet ec2 instances to be spun up using spot instances, but this field is not yet supported by Terraform, so we cannot take advantage of it.

It would be great if the GameLift resource could be updated to support this attribute.

### Terraform Version
0.11.4

### Affected Resource(s)
- aws_gamelift_fleet

**Comment by kosmodromov** [comment]
Hi,

@radeksimko Is there any chance to merge that PR?

**Comment by kevinpz** [comment]
Hi! Any news on this MR? Could I do something to help? This is something I would like to have!

**Comment by bflad** [comment]
Support for the new `fleet_type` argument on the `aws_gamelift_fleet` resource has been merged and will release with version 2.47.0 of the Terraform AWS Provider, tomorrow. Thanks to @kosmodromov for the implementation. 👍
