### ISSUE TITLE
Add support for YAML for defining SSM documents (aws_ssm_document)

### ISSUE THREAD

**Issue by ebekker** [terraform-providers/terraform-provider-aws#3810]
### Terraform Version
```
Terraform v0.11.3
+ provider.aws v1.10.0
```

### Affected Resource(s)
- `aws_ssm_document`

### Terraform Configuration Files
(n/a)

### Debug Output
(n/a)

### Panic Output
(n/a)

### Expected Behavior
Would like to be able to define SSM document content in *either* JSON or YAML format.

### Actual Behavior
When specified as YAML receiving `Error creating SSM document: InvalidDocumentContent: JSON not well-formed. at Line: 1, Column: 3` which confirms the resource documentation which states content should be JSON.

### Steps to Reproduce
1. create a TF config with an `aws_ssm_document` resource with `content` defined in YAML.
1. run `terraform apply`

### Important Factoids
(n/a)

### References
- Current `aws_ssm_document` docs for [content argument](https://www.terraform.io/docs/providers/aws/r/ssm_document.html#content)

**Comment by bflad** [comment]
Hi @ebekker 👋  great request! Looks like the SSM SDK supports YAML by having a separate parameter for `DocumentFormat`. We don't currently force JSON validation in the `content` attribute so should be fairly trivial to add! Let me double check for PRs or submit one real quick.

**Comment by bflad** [comment]
Enhancement PR: #3814

**Comment by ebekker** [comment]
Sweet!  Thanks!

**Comment by bflad** [comment]
Support has been merged into master and will release with v1.12.0 of the AWS provider, likely later this week. Happy Terraform'ing! 🎉

**Comment by bflad** [comment]
This has been released in [version 1.12.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
