### ISSUE TITLE
Terraform code to add multiple ssl certificates to ssl listener

### ISSUE THREAD

**Issue by luisamador** [terraform-providers/terraform-provider-aws#3843]
AWS ALB listener doesn't support more than one SSL certificate.

### Terraform Version
Any

### Affected Resource(s)
- aws_alb_listener

### References
- https://github.com/terraform-aws-modules/terraform-aws-alb/issues/26#issuecomment-374509027

**Comment by bflad** [comment]
Hi @luisamador 👋 We do actually support additional SSL certificates for ALBs via a new resource: [`aws_lb_listener_certificate`](https://www.terraform.io/docs/providers/aws/r/lb_listener_certificate.html), which was released in [v1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018). If you're not already on that version, please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

I'm going to keep this issue open to note that the documentation could use an update to reference the new resource.

**Comment by bflad** [comment]
Documentation updated via #3846
