### ISSUE TITLE
aws_cloudformation_stack import leaves state locked

### ISSUE THREAD

**Issue by martinssipenko** [terraform-providers/terraform-provider-aws#3845]
After successfully importing an existing `aws_cloudformation_stack` resource remote terraform state (s3 + dynamodb) is left locked, with following lock object:

```json
{
  "ID": "91b3101e-a3b1-a2f5-3bb5-111d64463927",
  "Operation": "OperationTypeInvalid",
  "Info": "",
  "Who": "user@user",
  "Version": "0.11.4",
  "Created": "2018-03-20T13:24:06.411822195Z",
  "Path": "path/to/tf/state/terraform.tfstate"
}
```
### Terraform Version
```sh
terraform -v
Terraform v0.11.4
+ provider.aws v1.11.0
```

### Affected Resource(s)
- aws_cloudformation_stack

**Comment by bflad** [comment]
@martinssipenko does this seem to describe your issue? https://github.com/hashicorp/terraform/issues/17624

**Comment by martinssipenko** [comment]
Yeah, looks like it's not `aws_cloudformation_stack` specific.

**Comment by eschwartz** [comment]
I have had the same issue with ECR repositories, security groups, and IAM roles
(in other words, I have not been able to import _anything_)
