### ISSUE TITLE
aws_autoscaling_group.asg: diffs didn't match during apply.

### ISSUE THREAD

**Issue by donbecker** [terraform-providers/terraform-provider-aws#3863]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.11.0

### Affected Resource(s)
- aws_autoscaling_group

### Debug Output
https://gist.github.com/donbecker/b341c46c84e47ae2c621584a3d4ac591

### Expected Behavior
ASG checksums should match

### Actual Behavior
Checksums didn't match

### Steps to Reproduce
1. `terraform apply`

**Comment by donbecker** [comment]
Rerunning ```terraform apply``` appears to have correctly created the ASG.

**Comment by donbecker** [comment]
Second occurrence: 

[https://gist.github.com/donbecker/f1fa9ad2c6baf5525d76a8162a72dfb8](url)

**Comment by donbecker** [comment]
It appears that the second ASG ended up repeatedly terminating and redeploying a new instance in 2a. 

Fully deleting and recreating seems to have fixed it and the error did not reoccur.

**Comment by donbecker** [comment]
I've duplicated the ASG code to use for a second piece of infrastructure. Clean run this morning (no preexisting resources) results in an error for both: 

[https://gist.github.com/donbecker/a6e1f14306a5b5d23969fe94f7142bed](url)

**Comment by donbecker** [comment]
@bflad That fixed it, thanks!

Apologies if I missed that in the docs somewhere...

**Comment by bflad** [comment]
@donbecker oh no, don't apologize! 😄  I have been meaning to fix the documentation and potentially that code too since its been lingering and causing issues for _a lot_ of folks. Submitting at least the documentation PR right now.
