### ISSUE TITLE
Feature Request: Resource for managing AWS Glue Crawlers

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#3875]
Split feature request from #1416. Please note there are relevant comments in #1416 about this feature request. For issues not immediately being worked on, please use :+1: upvotes on this original issue comment to help guage community interest.

### Terraform Version

```
terraform 0.10+
terraform-provider-aws (new feature)
```

### Affected Resource(s)

- `aws_glue_crawler`

### Terraform Configuration Files

```hcl
# New Resource - not implemented
resource "aws_glue_crawler" "example" {
  # ...
}
```

### Expected Behavior

Create, read, update, and delete support for AWS Glue crawlers.

### Actual Behavior

Resource not implemented.

### References

* https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-crawling.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#Glue.CreateCrawler

**Comment by darrenhaken** [comment]
Thanks @bflad 

Are you able to help further with the issue I was having a few weeks ago?

**Comment by darrenhaken** [comment]
Hi Brian,

I'll try that. I can pick this back up now, I was busy working on the GCP
TF.

**Comment by darrenhaken** [comment]
@cloudyparts I tried changing the role as you suggested but I still get:

```
--- FAIL: TestAccAWSGlueCrawler_basic (20.37s)
	testing.go:518: Step 0 error: Error applying: 1 error(s) occurred:

		* aws_glue_catalog_crawler.test: 1 error(s) occurred:

		* aws_glue_catalog_crawler.test: error creating Glue crawler: InvalidInputException: Service is unable to assume role arn:aws:iam::697329683179:role/AWSGlueServiceRoleDefault. Please verify role's TrustPolicy
			status code: 400, request id: a4f55ff2-4b19-11e8-8491-a9b7762b818e
```

**Comment by cloudyparts** [comment]
@darrenhaken I don't see anything apparent that would cause an 'assume role' error.   

That said I have had better luck with the `data.aws_iam_policy_document` resource as opposed to inline policies.  

You could try this => https://gist.github.com/cloudyparts/f7a80e940cf9648eb815bca6a0d43788

Note: I created this gist with code from my own modules which has no issues. (terraform=v0.11.7, terraform-provider-aws=1.16.0)

**Comment by darrenhaken** [comment]
@cloudyparts I tried your gist but it still failed, I wonder if there's an issue on the account. Thoughts?
I had set up an empty sandbox account to do testing on this.

**Comment by cloudyparts** [comment]
@darrenhaken it is difficult to understand the extent of the issue.  I would try creating a role manually in the console then referencing the role `arn` in your test.  See if you can get the crawler created...  - I am still puzzled by the error output...

Nothing should be assuming the Glue role except for the `glue service` when the crawler is invoked.  You are only creating the crawler ... not invoking it.

**Comment by darrenhaken** [comment]
@bflad yeah I'm still having trouble getting this working around the assume role. I thought I'd already opened a PR, I'll do that now.

I'm having to let others contribute too of course :)

**Comment by darrenhaken** [comment]
See https://github.com/terraform-providers/terraform-provider-aws/pull/4484

**Comment by bflad** [comment]
Kudos to @darrenhaken -- the new `aws_glue_crawler` resource is merged into master and will release later today. 🎉

**Comment by bflad** [comment]
This has been released in [version 1.24.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1240-june-21-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by darrenhaken** [comment]
@bflad thanks for the updates! Seems to all be working OK :)

**Comment by rehevkor5** [comment]
I was experiencing the same error as @darrenhaken ("InvalidInputException: Service is unable to assume role arn:aws:iam::00000000:role/AWSGlueServiceRole-foo. Please verify role's TrustPolicy"), and eventually I realized that this was because I was following the example in the documentation which recommends that you use the ".name" property of the IAM Role in order to populate the ".role" property of the aws_glue_crawler. However, I happened to use a non-default "path" on my IAM Role. Unfortunately, "aws_iam_role.name" does not include the path. It started working when I switched to referring to the Role by ARN instead.

I made this improvement to the docs as a result: https://github.com/terraform-providers/terraform-provider-aws/pull/6285
