### ISSUE TITLE
Feature Request: Resource for managing AWS Glue Partitions

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#3878]
Split feature request from #1416. For issues not immediately being worked on, please use :+1: upvotes on this original issue comment to help guage community interest.

### Terraform Version

```
terraform 0.10+
terraform-provider-aws (new feature)
```

### Affected Resource(s)

- `aws_glue_partition`

### Terraform Configuration Files

```hcl
# New Resource - not implemented
resource "aws_glue_partition" "example" {
  # ...
}
```

### Expected Behavior

Create, read, update, and delete support for AWS Glue partitions.

### Actual Behavior

Resource not implemented.

### References

* https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-partitions.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#Glue.CreatePartition

**Comment by stntmaniiac** [comment]
Any updates on this yet? I am stuck on creating partitions in AWS glue catalog table using terraform. Is there any way to do that?
