### ISSUE TITLE
Allow setting endpoint for EFS

### ISSUE THREAD

**Issue by joseph-stratoscale** [terraform-providers/terraform-provider-aws#3888]
### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
- resource_aws_efs_file_system.go
- provider.go
- config.go

### Terraform Configuration Files
aws-provider.tf file
provider "aws" {
    access_key = "access_key"
    secret_key = "secret_key"

    endpoints {
        ec2 = "https://10.0.0.1/api/v2/ec2"
        efs = "https://10.0.0.1/api/v2/aws/efs"
    }

    insecure = "true"
    skip_metadata_api_check = true
    skip_credentials_validation = true
    region = "us-east-1"
}

N/A

### Debug Output
[jwahba@localhost rds-simple]$ sudo ./terraform apply

Error: provider.aws: endpoints.0: invalid or unknown key: efs

### Panic Output
N/A

### Expected Behavior
Terraform provider should allow users to set efs endpoint

### Actual Behavior
Terraform provider doesn't allow users to set efs endpoint

### Steps to Reproduce
1- Set aws-provider efs endpoint
2- Run ./terraform apply

### Important Factoids
N/A

### References
This is a similar bug to 
https://github.com/terraform-providers/terraform-provider-aws/pull/2795/files

**Comment by joseph-stratoscale** [comment]
@bflad I have a branch with a commit to fix this enhancement.

**Comment by bflad** [comment]
The provider configuration for the custom EFS endpoint will release with v1.22.0 of the AWS provider, middle of this week.

**Comment by bflad** [comment]
This has been released in [version 1.22.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1220-june-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
