### ISSUE TITLE
StackOverflowException from remote-exec uploading a file

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#3889]
Using a remote-exec provisioner to upload a file to an S3 bucket from a Windows 2008 R2 server using a PowerShell script fails with a `StackOverflowException`. However, running the same script on the server works fine. It depends on the file size whether it fails or not. Running the PowerShell script on the server, files from 0-500MB work fine. Running from Terraform remote-exec provisioner, the script fails for files 17MB or larger. 

### Terraform Version
Terraform 0.11.5

### Affected Resource(s)
- aws_instance

### Terraform Configuration Files
```hcl
resource "aws_instance" "windows" {
  count                       = "1"
  ami                         = "ami-e935fc94" #base win 2008 R2 datacenter
  instance_type               = "t2.micro"

  connection {
    type     = "winrm"
    user     = "<username>"
    password = "<password>"
    timeout  = "30m"
  }

  provisioner "file" {
    source      = "windows/check_build.ps1"
    destination = "C:\\scripts\\check_build.ps1"
  }

  provisioner "remote-exec" {
    inline = [
      "powershell.exe -File C:\\scripts\\check_build.ps1"
    ]
  }
}
```
check_build.ps1:
```ps1
$f = new-object System.IO.FileStream C:\Temp\test.dat, Create, ReadWrite
$f.SetLength(40MB) #if this is reduced to 14MB, it works
$f.Close()
Write-Host (Get-Date -UFormat "%Y/%m/%d %T")
Write-S3Object -BucketName "mybucket" -Folder "C:\Temp" -KeyPrefix "20180322" -SearchPattern "*.dat"
```

### Debug Output
Note: The exact time that the upload took place is shown in output. Script displays the time right before upload. Nothing interesting happens in the debug log at that time.  
```
aws_instance.windows (remote-exec): 2018/03/22 15:10:50
aws_instance.windows (remote-exec): Process is terminated due to StackOverflowException.
```
[Debug gist](https://gist.github.com/YakDriver/8b9e7d3bf31a2f0ab76425d05144f626)

### Expected Behavior
The script launched by the remote-exec provisioner should upload the file to the S3 bucket.

### Actual Behavior
```
aws_instance.windows (remote-exec): Process is terminated due to StackOverflowException.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by bflad** [comment]
Hi @YakDriver do you know if this patch is installed on that AMI? https://support.microsoft.com/en-us/help/2842230/out-of-memory-error-on-a-computer-that-has-a-customized-maxmemorypersh

Reference: https://github.com/ansible/ansible/pull/10926/files

Otherwise maybe see if something like `MaxMemoryPerShellMB` needs to be increased?

**Comment by YakDriver** [comment]
@bflad Thanks for the suggestions. The hotfix doesn't appear to be installed but it works fine without in the local environment so unless absolutely necessary I'm not excited about patching all my brand new instances.

You second idea with `MaxMemoryPerShellMB` led me to find a very strange environment for the Terraform remote-exec launched script. A call to `Get-ChildItem WSMan:\localhost\Shell` yields an error: 
```
+ Get-ChildItem WSMan:\localhost\Shell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : ObjectNotFound: (WSMan:String) [Get-ChildItem], DriveNotFoundException 
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```
Normally, that would occur if PSRemoting hadn't been enabled but it has been and WinRM configured, otherwise it wouldn't have connected to remote-exec the script in the first place.

**Comment by bflad** [comment]
Just so you are aware, the `remote-exec` provisioner is actually in Terraform core here: 

https://github.com/hashicorp/terraform/blob/0c39b69d50ad6d54c4fe61d310cd45183dbf9b8c/builtin/provisioners/remote-exec/resource_provisioner.go#L1

Unfortunately, I have not been a Windows administrator for quite some time, so I do not know much more than my initial suggestions. This is really outside my wheel house at this point. 😄  Maybe someone else can chime in or its worthwhile to contact the [terraform-tool Google Group](https://groups.google.com/d/forum/terraform-tool). It might also get better answers from moving the issue to https://github.com/hashicorp/terraform as well.

**Comment by YakDriver** [comment]
If you run into this problem, the workaround for the [StackOverflowException is documented on StackOverflow](https://stackoverflow.com/questions/49435628/install-windows-hotfix-using-terraform-on-aws?noredirect=1#comment85873770_49435628).
