### ISSUE TITLE
aws_cloudwatch_metric_alarm failed decoding

### ISSUE THREAD

**Issue by pennyclip** [terraform-providers/terraform-provider-aws#3890]
Hi there,
Having an issue with cloudwatch_metric_alarm not decoding well. Has this issue with every alarm starting at ~1400 03/22

### Terraform Version
Terraform v0.11.3
+ provider.aws v1.11.0

### Affected Resource(s)
- aws_cloudwatch_metric_alarm

### Terraform Configuration Files
Here is a basic resource, but we have hundreds of alarms that are all producing the same error.
```hcl
resource "aws_cloudwatch_metric_alarm" "cpu-alarm" {
  count               = "${var.enable > 0 ? 1 : 0}"
  actions_enabled     = true
  alarm_name          = "${var.dbname}_alarm_cpu"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "10"
  metric_name         = "CPUUtilization"
  namespace           = "AWS/RDS"

  dimensions {
    DBInstanceIdentifier = "${var.dbname}"
  }

  period            = "240"
  statistic         = "Average"
  threshold         = "${var.cpu_utilization_threshold}"
  alarm_description = "This alarm monitors the cpu utilization for ${var.dbname}"

  alarm_actions             = ["${var.critical_topic_arn}"]
  ok_actions                = ["${var.critical_topic_arn}"]
  insufficient_data_actions = ["${var.critical_topic_arn}"]
}
```

### Debug Output
terraform apply returns
```
 * module.west.module.<redacted>_rds_cloudwatch.aws_cloudwatch_metric_alarm.cpu-alarm: 1 error(s) occurred:

* module.west.module.<redacted>_rds_cloudwatch.aws_cloudwatch_metric_alarm.cpu-alarm: aws_cloudwatch_metric_alarm.replication-lag-alarm: SerializationError: failed decoding Query response
caused by: parsing time "2018-03-22T12:56:07.392+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z" 
```

### Panic Output
N/A

### Expected Behavior
Should apply properly

### Actual Behavior
```
 * module.west.module.<redacted>_rds_cloudwatch.aws_cloudwatch_metric_alarm.cpu-alarm: 1 error(s) occurred:

* module.west.module.<redacted>_rds_cloudwatch.aws_cloudwatch_metric_alarm.cpu-alarm: aws_cloudwatch_metric_alarm.replication-lag-alarm: SerializationError: failed decoding Query response
caused by: parsing time "2018-03-22T12:56:07.392+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z" 
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Nothing special, doesn't seem to be a variable or an output we can control. 

### References
N/A

**Comment by bflad** [comment]
Thanks for the report and sorry you're running into trouble here. Usually errors like `SerializationError: failed decoding Query response` come from issues between the service API (CloudWatch API in this case) and the AWS SDK. Maybe something changed upstream in the CloudWatch service? I've opened an AWS Go SDK issue here: https://github.com/aws/aws-sdk-go/issues/1857

If you have an AWS support contract, I would also suggest opening a support case. This shouldn't be unique to just Terraform.

**Comment by bflad** [comment]
Seems related (external report): https://status.appoptics.com/incidents/nx7f1pjmcnrf

**Comment by bartodns** [comment]
Ran into the same issue, seems resolved now.

**Comment by bflad** [comment]
Going to close this out as it looks like it was resolved.
