### ISSUE TITLE
Feature request: support DynamoDB Continuous Backups and Point-In-Time Recovery (PITR)

### ISSUE THREAD

**Issue by maciejdrozdzowski** [terraform-providers/terraform-provider-aws#3927]
As per https://aws.amazon.com/blogs/aws/new-amazon-dynamodb-continuous-backups-and-point-in-time-recovery-pitr/.

**Comment by stuartgrice** [comment]
We could really use this in our environment

**Comment by bflad** [comment]
Required AWS SDK update submitted: #3930

**Comment by shopskyi** [comment]
+1

**Comment by bflad** [comment]
This has been released in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
