### ISSUE TITLE
AWS_KMS_GRANT missing operations

### ISSUE THREAD

**Issue by Timboo89** [terraform-providers/terraform-provider-aws#3946]
Hi,

just wanted to use aws_kms_grant for allowing an ASG to start instances with an encrypted root volume.
Therefore I need to add the permissions "kms:CreateGrant", "kms:ListGrants" and "kms:RevokeGrant" for the ASG service-role to the kms policy. Unfortunately TF does not allow the operations "ListGrants" and "RevokeGrant".

Please fix this small issue.

Thanks

### Terraform Version
v0.11.3

### AWS Provider version
v1.12.0

### Affected Resource(s)
- aws_kms_grant

### Terraform Configuration Files
```hcl
resource "aws_kms_key" "ecs" {
  description             = "ECS instance key"
  deletion_window_in_days = 10
  key_usage               = "ENCRYPT_DECRYPT"
  is_enabled              = true
  enable_key_rotation     = true
}

resource "aws_kms_grant" "ecs_asg" {
  name              = "ECS_ASG"
  key_id            = "${aws_kms_key.ecs.key_id}"
  grantee_principal = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
  operations        = ["CreateGrant", "ListGrants", "RevokeGrant"]
}
```

### Debug Output
```
Error: aws_kms_grant.ecs_asg: expected operations.1 to be one of [CreateGrant Decrypt DescribeKey Encrypt GenerateDataKey GenerateDataKeyWithoutPlaintext ReEncryptFrom ReEncryptTo RetireGrant], got ListGrants

Error: aws_kms_grant.ecs_asg: expected operations.2 to be one of [CreateGrant Decrypt DescribeKey Encrypt GenerateDataKey GenerateDataKeyWithoutPlaintext ReEncryptFrom ReEncryptTo RetireGrant], got RevokeGrant
```

### Expected Behavior
Well, just create the damn policy :-D

### Actual Behavior
Error message above

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by bflad** [comment]
Hi @Timboo89 👋  Sorry you're running into trouble here.

It looks like you are trying to specify [KMS IAM actions](https://docs.aws.amazon.com/kms/latest/developerguide/kms-api-permissions-reference.html) as KMS grant operations. Unfortunately, the two usages are slightly different. I wasn't easily able to find an authoritative KMS documentation source for the grant operations though. My best guess is that you will at least need to set the operation `Decrypt`.

Can you try that out and see how it goes?

If you can think of ways to improve the documentation in Terraform surrounding these concepts please let us know.

**Comment by Timboo89** [comment]
Hi @bflad 

I tried quite a bit ;-) The AWS support said, that I'd "only" need those three described above.
Well, they were wrong, didn't work. After a lot of trying I came to these actions as the minimum for an ASG to work:
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey",
                "kms:CreateGrant",
                "kms:ListGrants",
                "kms:RevokeGrant"

Well actually I didn't try to more specify ReEncrypt* and GenerateDataKey*
What kind of changes do you wish for the documentation? Like a howto use encrypted AMIs / AMIs with encrypted volumes?

**Comment by jammerful** [comment]
@bflad @Timboo89 You can see the list of valid operations here: https://docs.aws.amazon.com/cli/latest/reference/kms/create-grant.html

> Where valid values are:
>  Decrypt
>  Encrypt
>  GenerateDataKey
>  GenerateDataKeyWithoutPlaintext
>  ReEncryptFrom
>  ReEncryptTo
>  CreateGrant
>  RetireGrant
>  DescribeKey

**Comment by jammerful** [comment]
@Timboo89 There is a guide to using a CMK for AMI encryption here: https://aws.amazon.com/blogs/security/how-to-create-a-custom-ami-with-encrypted-amazon-ebs-snapshots-and-share-it-with-other-accounts-and-regions/

> This IAM user or role also needs to be able to perform the KMS DescribeKey, CreateGrant, GenerateDataKey and ReEncypt operations on the source account’s KMS CMK, cmkSource.

All of the above operations are supported by `aws_kms_grant`, note I'm not sure if you need both ReEncryptTo and ReEncryptFrom.

**Comment by bflad** [comment]
Closing due to lack of response -- if someone feels inclined to add the above documentation to the Terraform documentation we'll gladly take a look.
