### ISSUE TITLE
Add support for configuring CLI/API session durations on aws_iam_role

### ISSUE THREAD

**Issue by devonbleak** [terraform-providers/terraform-provider-aws#3969]
AWS has recently added a setting for specifying the maximum session duration of API/CLI credentials for a role: 
- https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html#id_roles_use_view-role-max-session
- https://docs.aws.amazon.com/IAM/latest/APIReference/API_UpdateRole.html
- https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html

### Terraform Version
All versions.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_iam_role

### Terraform Configuration Files
Recommend adding max_session_duration property to aws_iam_role
```hcl
resource "aws_iam_role" "role" {
  name = "role"
  max_session_duration = 43200
  assume_role_policy = <<EOF
    ...
EOF
}
```

### Expected Behavior
Role ends up with its max session duration as specified in code

### Actual Behavior
Property is not supported.

**Comment by bflad** [comment]
This has been released in [version 1.14.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1140-april-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
