### ISSUE TITLE
KMS encrypt variables for AWS Lambda [documentation improvement]

### ISSUE THREAD

**Issue by alex1x** [terraform-providers/terraform-provider-aws#3973]
From the docs in https://www.terraform.io/docs/providers/aws/r/lambda_function.html it's not clear how to use the encrypted variables in transit with the "helper" i.e. how to do this: https://docs.aws.amazon.com/lambda/latest/dg/tutorial-env_console.html

**Comment by alex1x** [comment]
Do you agree? I could write this up either as a guide like https://www.terraform.io/docs/providers/aws/guides/serverless-with-aws-lambda-and-api-gateway.html or as a longish note within the https://www.terraform.io/docs/providers/aws/r/lambda_function.html resource... I am gravitating towards guide (even though it won't be that long)... thoughts?

**Comment by slayer201** [comment]
Do we miss this "encrypt variables in transit" feature in terraform. Any idea how could this be achieved with terraform
