### ISSUE TITLE
Inconsistent API for AWS Region

### ISSUE THREAD

**Issue by cgarvis** [terraform-providers/terraform-provider-aws#3974]
Using the new aws_appsync_graphql_api, I assumed that the region for `user_pool_config` was configured using `region` like `aws_s3_bucket` and `aws_appsync_datasource.dynamodb_config`. Instead it uses `aws_region`. Why the inconsistency?

**Comment by bflad** [comment]
Pull request submitted to make `aws_region` optional (based on current resource region): #6138

**Comment by bflad** [comment]
This has been released in [version 1.41.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1410-october-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
