### ISSUE TITLE
TF complains about inexsting character - Error decoding JSON: invalid character '\\' after object key:value pair

### ISSUE THREAD

**Issue by joaoferrao** [terraform-providers/terraform-provider-aws#3983]
Hello, I'm launching task definition called "redash" in which one of the containers needs to have the below environment variable that should result in something like:

```postgresql//user:password@host:post/database```

I have tried 2 versions of these lines like so

*Try 1*
```
{
    "name": "REDASH_DATABASE_URL",
    "value": "${format("postgres://%s:%s@:%s:%s/%s", var.redash_to_postgres_username, var.redash_to_postgres_password, var.redash_to_postgres_host, var.redash_to_postgres_port, var.redash_to_postgres_database)}"
}
```

*Try 2*
```
{
    "name": "REDASH_DATABASE_URL",
    "value": "postgresql://${var.redash_to_postgres_username}:${var.redash_to_postgres_password}@${var.redash_to_postgres_host}:${var.redash_to_postgres_host}/${var.redash_to_postgres_database}"
}
```

Upon planning, both of them result in the following error:
```
* aws_ecs_task_definition.redash: ECS Task Definition container_definitions is invalid: Error decoding JSON: invalid character '\\' after object key:value pair
```

My problem  is that I have no such characters in this task definition/file so I'm not really sure what I should be solving. I only inserted these environment variables part of the task because this is the only "new" pattern comparing to other task definitions I have set up in the same infrastructure with terraform.

Any suggestions?

**Comment by raolivei** [comment]
I wonder how it would behave if the string comes from a secrets manager resource that contains `"\/` inside the secret...
