### ISSUE TITLE
Destroy of a security group that contained a Amazon-MQ instance in the past (also managed by TF) results in DependencyViolation

### ISSUE THREAD

**Issue by timboven** [terraform-providers/terraform-provider-aws#3992]
When you try to run a destroy on a terraform project that created a security group with a amazon mq - this destroy fails with DependencyViolation: resource sg-01f6c47b has a dependent object.
This due to the created network interfaces of AMQ that are still in the security group.

### Terraform Version
0.11.5

### Affected Resource(s)
combination of aws_security_group and aws_mq_broker.

### Expected Behavior
Destroy the objects that have been created before

### Actual Behavior
Network interfaces of AMQ are left behind and resulting in a failed destroy-run as the security group can not get destroyed

### Steps to Reproduce
1.  Use TF to create a security group and place a amazon mq inside this security group
2. Run a terraform destroy on what you created in step 1
--> DependencyViolation

**Comment by bflad** [comment]
@timboven do you know if the network interfaces eventually disappear (applying twice works) or if they are more permanently stuck?

**Comment by timboven** [comment]
@bflad I actually triest multiple times in a row before filing this ticket - to validate that it wasn't a race condition or timeout. So according to my test more permanently stuck

**Comment by timboven** [comment]
I have been testing some more with this and in another account this seems to work fine? I'll do some more testing with this - maybe it is a leftover of some messing around with permissions of before?
In that case the bug is a little bit different - in the beginning I could not destroy the AMQ because the policy-file didn't had the needed permissions configured for that. I added those, and I assumed that he was going to do the destroy again - but maybe that is the bug ...

So current working theory:
1) Create a AMQ
2) Try to destroy it but the role you're running this destroy with doesn't have the permissions to delete those created network interfaces (it has however the destroy-permission of AMQ)
--> Destroy fails due to missing permissions
3) Add those extra permissions
4) Run destroy again
--> Still fails (not because of missing permissions but because of some network interfaces that are still in the security group)

I'll try to dive some deeper in this and come back here if I have some more findings to share.

**Comment by bflad** [comment]
@timboven were you able to find out any additional details here?

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
