### ISSUE TITLE
Change amazon-MQ maintenance_window_start parameter to look more like RDS maintenance_window

### ISSUE THREAD

**Issue by kiwivogel** [terraform-providers/terraform-provider-aws#3994]
Hello, not sure if this is something that should be fixed but the format for defining maintenance windows for Amazon-MQ differs vastly from that of say RDS, would prefer these to be the same so I can use the same vars/settings across modules.

I guess this is due to the fact that you can only specify start for amq wheras db is the entire window but it's still rather annoying : /

**Comment by bflad** [comment]
Hi @kiwivogel 👋  In most cases we try to follow the upstream AWS SDK (and API). In this case, the MQ service does have it defined in a different way: https://docs.aws.amazon.com/sdk-for-go/api/service/mq/#WeeklyStartTime

See also the AWS CLI, which follows the same pattern as Terraform here: https://docs.aws.amazon.com/cli/latest/reference/mq/create-broker.html

I'm not sure if we would ever try to normalize these across resources as that is a large maintenance burden and could cause confusion for folks using other systems to talk to the service APIs or even just reading service documentation.

I would suggest talking to AWS Support if you have a complaint about the way they reference maintenance windows across their services.

**Comment by kiwivogel** [comment]
Noted, fair enough. Thanks for the quick response
