### ISSUE TITLE
Mismatch when importing inter-region VPC peering connection

### ISSUE THREAD

**Issue by carmas** [terraform-providers/terraform-provider-aws#4005]
Hi there,

### Terraform Version
Terraform v0.11.5
+ provider.aws v1.13.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_vpc_peering_connection

### Description of the issue
- We have an existing inter-region VPC peering connection
- We prepared Terraform code with the parameters to reflect it
- We then import the object via ```terraform import aws_vpc_peering_connection....```
- When we verify with ```terraform plan``` it notifies of  a mismatch in the ```accepters``` and ```requesters``` parameters (although we do not specify any of them, since they are listed as optional)

### Terraform Configuration Files
```
resource "aws_vpc_peering_connection" "pcxreq-1" {
  peer_region    = "us-west-1"
  peer_vpc_id    = "vpc-xxxxxxxx"
  peer_owner_id    = "NNNNNNN"
  vpc_id    = "${aws_vpc.main.id}"
 }

```

### Debug Output
```
Terraform will perform the following actions:
~ aws_vpc_peering_connection.pcxreq-1
     accepter.#:  "" => <computed>
     requester.#: "" => <computed>
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
What should have happened?

- We would expect the results of the ```terraform plan``` to show no mismatch vs. the imported object

### Actual Behavior
What actually happened?
```
Terraform will perform the following actions:
~ aws_vpc_peering_connection.pcxreq-1
     accepter.#:  "" => <computed>
     requester.#: "" => <computed>
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
- Create code to match the object (see code above)
- Import the object via "terraform import aws_vpc_peering_connection.pcxreq-1 <object_id>"
- Run "terraform plan"

Since "accepter" and "requester" blocks are optional, why is "terraform plan" showing a change if "terraform apply" is run?

Is it possible the "terraform import" command is not importing all the elements necessary?

**Comment by danballinger** [comment]
I am having the same problem.  Can I get an update on this or get it worked on?  This is causing problems with AWS' new inter-region peering and terraform.

Thanks.

**Comment by ewbankkit** [comment]
@carmas You are [correct](https://docs.aws.amazon.com/AmazonVPC/latest/PeeringGuide/vpc-peering-basics.html#vpc-peering-limitations) that cross-region VPC peerings do not support any of the `accepter` or `requester` options (DNS resolution or Classic Link connections). When the VPC peering connection is imported the EC2 API must be returning `false` for these attributes and those values are being written into the state file. Since there are no attributes set in the code, `terraform plan` is showing the diffs.
