### ISSUE TITLE
Look up kms_alias for a different region

### ISSUE THREAD

**Issue by dusty-stripe** [terraform-providers/terraform-provider-aws#4013]
Hey there, folks,

It seems like it would be useful to add support for the `aws_kms_alias` data source to look up the arn and key information for an alias for a different region. Since we can copy encrypted snapshots between regions using custom keys, we need to be able to configure IAM permissions for the key/alias and looking it up by alias name is much preferred to hardcoding the whole ARN.

This might look like attaching a `region` argument to the data source where `region` defaults to the provider region.

I recognize that looking up resources from other regions is somewhat weird, so this may be a non-starter. I can't think of any other resources off the top of my head that do this kind of thing.

**Comment by bflad** [comment]
@dusty-stripe you should be able to reference other regions by using [provider aliases](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances) in your Terraform configuration. e.g.

```hcl
# Assuming us-west-2 is a different region than our default
provider "aws" {
  alias   = "us-west-2"
  region = "us-west-2"
}

data "aws_kms_alias" "example" {
  provider = "aws.us-west-2"
  # ... other configuration ...
}
```

Can you try that out?

**Comment by dusty-stripe** [comment]
@bflad Oh, derp. Yeah, of course that should work. Thanks.
