### ISSUE TITLE
Support NodeJS v8.10.0 runtime in Lambda functions

### ISSUE THREAD

**Issue by clocked0ne** [terraform-providers/terraform-provider-aws#4019]
### Terraform Version
0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lambda_function

### Expected Behavior
Should successfully build with latest Node v8.10.0 runtime

### Actual Behavior
```
Error: module.babelfish_ref.aws_lambda_function.module_lambda: expected runtime to be one of [nodejs4.3 nodejs6.10 java8 python2.7 python3.6 dotnetcore1.0 dotnetcore2.0 nodejs4.3-edge go1.x], got nodejs8.10
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Change needs to be made here in terraform-provider-aws/aws/resource_aws_lambda_function.go

```
"runtime": {
	Type:     schema.TypeString,
	Required: true,
	ValidateFunc: validation.StringInSlice([]string{
		// lambda.RuntimeNodejs has reached end of life since October 2016 so not included here
		lambda.RuntimeNodejs43,
		lambda.RuntimeNodejs610,
		lambda.RuntimeJava8,
		lambda.RuntimePython27,
		lambda.RuntimePython36,
		lambda.RuntimeDotnetcore10,
		lambda.RuntimeDotnetcore20,
		lambda.RuntimeNodejs43Edge,
		lambda.RuntimeGo1X,
	}, false),
},
```

**Comment by bflad** [comment]
While the SDK hasn't been updated to support the new constant, we merged in support via #4020. It will be released with v1.14.0 of the AWS provider, likely later this week. 🎉
