### ISSUE TITLE
Add AWS Batch as a cloudwatch_event_target

### ISSUE THREAD

**Issue by mmircea16** [terraform-providers/terraform-provider-aws#4023]
This is a feature request.

AWS has recently added the ability to use an AWS Batch resource as the target of a cloudwatch event: https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-cloudwatch-events-now-supports-aws-batch-as-an-event-target/

This is confirmed by the AWS documentation: https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_Target.html as it now accepts a BatchParameters object

In Terraform we would need to add to the `cloudwatch_event_target` resource a `BatchParameters` corresponding field - maybe something like `batch_target`

**Comment by bflad** [comment]
Support has been merged into master via #4312 and will release with v1.16.0 of the AWS provider, likely in a few days.

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
