### ISSUE TITLE
Add support for ECS Service Discovery

### ISSUE THREAD

**Issue by kgraney** [terraform-providers/terraform-provider-aws#4025]
Recent AWS announcement:
https://aws.amazon.com/about-aws/whats-new/2018/03/introducing-service-discovery-for-amazon-ecs/

It's an additional parameter on `aws_ecs_service`.

**Comment by arledesma** [comment]
This issue should be closed as the work has been merged in #3906 and subsequently released.

**Comment by bflad** [comment]
Thanks @arledesma! Indeed this has been released in [version 1.15.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
