### ISSUE TITLE
aws_cloudwatch_event_permission silently fails to create parallel permissions

### ISSUE THREAD

**Issue by bhops** [terraform-providers/terraform-provider-aws#4031]
### Terraform Version
Terraform v0.11.5
+ provider.aws v1.13.0

### Affected Resource(s)
- aws_cloudwatch_event_permission

### Terraform Configuration Files
```hcl
resource "aws_cloudwatch_event_permission" "a" {
  principal    = "XXXXXXXXXXX"
  statement_id = "statement1"
  action       = "events:PutEvents"
}

resource "aws_cloudwatch_event_permission" "b" {
  principal    = "YYYYYYYYYY"
  statement_id = "statement2"
  action       = "events:PutEvents"
}
```

### Expected Behavior
Both CloudWatch event bus permissions should have been created

### Actual Behavior
Only one CloudWatch event bus permission was created, but terraform indicated that both were created.

### Important Factoids
This only seems to happen when creating multiple permissions at a time, a subsequent run of terraform successfully creates the 2nd permission. I am not able to 100% reproduce the issue, but it happens with reasonable frequency.

**Comment by dav009** [comment]
this is mentioned in https://github.com/terraform-providers/terraform-provider-aws/pull/2888

> There's also a peculiarity with the PutPermission API concurrency where two "parallel" operations will only write the last received entry, but it always returns 200 OKs for both requests. If there's a good solution for a resource-wide mutex, this would be a good place for one.

**Comment by dav009** [comment]
wanna get around this,   I guess adding `depends_on` would ensure calls to api are done sequentially?
