### ISSUE TITLE
aws_cloudtrail always reports a change for event_selector

### ISSUE THREAD

**Issue by roman-vynar** [terraform-providers/terraform-provider-aws#4040]
Terraform v0.11.5
provider.aws v1.13

TF always reports a change for `aws_cloudtrail` resource due to `event_selector` statement.
```
resource "aws_cloudtrail" "cloudtrail-general" {
  name                          = "cloudtrail-general"
  s3_bucket_name                = "foobar-bucket"
  is_multi_region_trail         = true
  include_global_service_events = true
  enable_log_file_validation    = true

  event_selector {
    read_write_type           = "All"
    include_management_events = true
  }
}
```

Once the above is created/re-applied there is a persistent change:
```
  ~ aws_cloudtrail.cloudtrail-general
      event_selector.#:                           "0" => "1"
      event_selector.0.include_management_events: "" => "true"
      event_selector.0.read_write_type:           "" => "All"
```
There shouldn't be any pending changes once the above is applied.

**Comment by roman-vynar** [comment]
Looks like it's not needed at all when I am not going to log neither S3 ops nor Lambda ones.

**Comment by catsby** [comment]
Thanks for following up! Do you believe this still to be a bug that simply doesn't affect you, or maybe just a documentation thing?
