### ISSUE TITLE
Passing an ARN to the value of a data_resource for creating an aws_cloudtrail generates exception

### ISSUE THREAD

**Issue by eangeeag** [terraform-providers/terraform-provider-aws#4043]
### Terraform Version
Terraform v0.11.2
+ provider.archive v1.0.0
+ provider.aws v1.13.0

### Affected Resource(s)
- aws_cloudtrail

### Terraform Configuration Files
```hcl
data "aws_s3_bucket" "data_bucket" {
  bucket = "data-bucket"
}

resource "aws_cloudtrail" "trail" {
  name                          = "a-name"
  s3_bucket_name                = "a-bucket"
  s3_key_prefix                 = "dev"
  include_global_service_events = false

  event_selector {
    read_write_type           = "All"
    include_management_events = false

    data_resource {
      type   = "AWS::S3::Object"
      values = ["${data.aws_s3_bucket.data_bucket.arn}"]
    }
  }
}
```

### Expected Behavior
Should apply correctly and configure `data-bucket` for data events in CloudTrail

### Actual Behavior
```
* aws_cloudtrail.tral: Error set event selector on CloudTrail (secrets): InvalidEventSelectorsException: Value arn:aws:s3:::data-bucket for DataResources.Values is invalid.
        status code: 400, request id: 3d4a1c48-2e26-4e4f-852e-573b902d18ed
```
If I add a trailing `/` to the bucket arn like this `values = ["${data.aws_s3_bucket.data_bucket.arn}/"]` it works fine

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out tplan` (Plan is ok)
2. `terrafrom apply tplan` (fails here)

**Comment by eangeeag** [comment]
@catsby Thanks for your response. You're right, this looks like a documentation issue rather than a bug itself.

**Comment by bflad** [comment]
Documentation update is merged and will go out next week 👍
