### ISSUE TITLE
WAF WebACL resources missing support for using Rule Groups

### ISSUE THREAD

**Issue by erikpaasonen** [terraform-providers/terraform-provider-aws#4052]
### Terraform Version
```
Terraform v0.11.5
+ provider.aws v1.13.0
```

### Affected Resource(s)
- aws_waf_rule_group
- aws_waf_web_acl
- aws_wafregional_rule_group
- aws_wafregional_web_acl

### Terraform Configuration Files
This is copied and pasted straight from the examples for `aws_waf_rule_group` and `aws_waf_web_acl`, just adapted to use the rule group.

``` HCL
resource "aws_waf_rule" "example" {
  name        = "example"
  metric_name = "example"
}

resource "aws_waf_rule_group" "example" {
  name        = "example"
  metric_name = "example"

  activated_rule {
    action {
      type = "COUNT"
    }

    priority = 50
    rule_id  = "${aws_waf_rule.example.id}"
  }
}

resource "aws_waf_web_acl" "waf_acl" {
  name        = "tfWebACL"
  metric_name = "tfWebACL"

  default_action {
    type = "ALLOW"
  }

  rules {
    action {
      type = "BLOCK"
    }

    priority = 1
    rule_id  = "${aws_waf_rule_group.example.id}"
    type     = "GROUP"
  }
}
```

### Debug Output
https://gist.github.com/erikpaasonen/83174454128c6ae05e6d0058d0b72a3a

### Expected Behavior
Terraform should create the WAF WebACL using the new rule group resource.

### Actual Behavior
Terraform aborts almost immediately because it is expecting a `type` of only `REGULAR` or `RATE_BASED`. It considers `GROUP` as invalid input.

### Important Factoids
Our team currently has the insertion of a managed rule group working using the AWS CLI. The AWS CLI supports the `GROUP` type. Here's the syntax for a known-good `updates` list entry for use with the AWS CLI:
``` json
{
    "Action": "INSERT",
    "ActivatedRule": {
        "Priority": 1,
        "RuleId": "my-known-good-rule-group-uuid",
        "OverrideAction": {
            "Type": "COUNT"
        },
        "Type": "GROUP"
    }
}
```

As mentioned in Issue #3172 , the `aws_waf_web_acl` and `aws_wafregional_web_acl` resources are missing support for `OverrideAction`. Once resolved, this issue is expected to resolve Issue #3172 at least for the hard-coded UUID use case.

I'm filing this particular issue as a bug now that v1.13.0 is live. But I believe this was simply an integration oversight when the new `aws_waf_rule_group` and `aws_wafregional_rule_group` resource types were recently introduced.

### References
PR #3898 
Issue #424 
Issue #3172 
https://docs.aws.amazon.com/cli/latest/reference/waf/update-web-acl.html#options

**Comment by bflad** [comment]
The `aws_wafregional_web_acl` resource support for rule type has been merged into master via #4978 and will release with version 1.25.0 of the AWS provider, likely middle of this week. Please note you _must_ configure this new attribute for `RATE_BASED` rules.

**Comment by warwick-mitchell** [comment]
It looks like the commit doesn't support Rule Groups which this issue is referring to. We need this to support the use of AWS Managed Ruleset Groups form the marketplace.

**Comment by bflad** [comment]
Oh whoops you are correct, this is a separate issue, it was just linked in the PR.

**Comment by mtaumike** [comment]
Will this be a part of v1.26.0 then?

I guess my actual big question is thus: When can we expect this feature to be implemented in this provider plugin?

**Comment by bflad** [comment]
It's not currently on my personal hit list and there are not currently any open WAF pull requests for the fix: https://github.com/terraform-providers/terraform-provider-aws/pulls?q=is%3Aopen+is%3Apr+label%3Aservice%2Fwaf

If someone is willing to submit a fix, the maintainers will be happy to take a look.

**Comment by bflad** [comment]
This should be fixed with #5053 which was just merged into master and will release with version 1.27.0 of the AWS provider, likely middle of this week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.27.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1270-july-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by davyt10** [comment]
Does anyone have a working example of using adding managed rules, using the above resource config I am getting an error.
resource "aws_wafregional_web_acl" "example" {
  name = "test"
  metric_name = "test"
    default_action {
    type = "BLOCK"
  }
  rules {
    # ... other configuration ...
    override_action {
       type = "NONE"
    }
    type = "GROUP"
    rule_id = "7ad2da1e-c2ce-49e7-9cc4-189171298654"
  }
}

1 error(s) occurred:

* module.mobile_api_waf.aws_wafregional_web_acl.example: : invalid or unknown key: rules

**Comment by davyt10** [comment]
I had tried that previously, its the same issue.

**Comment by warwick-mitchell** [comment]
priority is also a required argument looking at the documentation. And make sure you are requiring at least AWS provider 1.27.

**Comment by davyt10** [comment]
No luck! This is for a managed F5 rule that I wanted to add to the webacl, is it something related to this I am wondering?

**Comment by warwick-mitchell** [comment]
No I've done it successfully with the F5 managed rule. Make sure the rule_id is the correct one for the region you're targeting.

Here's the exact config I've used

resource "aws_wafregional_web_acl" "protected_web_acl" {
  name = "protected_web_acl"
  metric_name = "ProtectedWebACL"
  default_action {
    type = "ALLOW"
  }

  rule {
    override_action {
       type = "NONE"
    }
    priority = 10
    rule_id  = "${var.waf_ruleset_group}"
    type     = "GROUP"
  }
}

**Comment by davyt10** [comment]
Here is debug output.

2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: ---[ RESPONSE ]--------------------------------------
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: HTTP/1.1 400 Bad Request
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: Connection: close
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: Content-Length: 88
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: Content-Type: application/x-amz-json-1.1
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: Date: Wed, 22 Aug 2018 10:56:23 GMT
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: X-Amzn-Requestid: 02d4d683-a5fa-11e8-8347-xxxxxxxx
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe:
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe:
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: -----------------------------------------------------
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: 2018/08/22 **11:56:24 [DEBUG] [aws-sdk-go] {"__type":"WAFNonexistentItemException","message":"The referenced item does not exist."}**
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe: 2018/08/22 11:56:24 [DEBUG] [aws-sdk-go] DEBUG: Validate Response waf-regional/UpdateWebACL failed, not retrying, error WAFNonexistentItemException: The referenced item does not exist.
2018-08-22T11:56:24.659+0100 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4.exe:      status code: 400,

**Comment by davyt10** [comment]
OK that works, thanks!
