### ISSUE TITLE
Add application/x-x509-ca-cert as allowable MIME type for aws_s3_bucket_object

### ISSUE THREAD

**Issue by dalesit** [terraform-providers/terraform-provider-aws#4064]
We would like to store keys in an encrypted S3 bucket so that a provisioned Jenkins server is able to provision other instances without having to store the key in Git. Unfortunately, the auto-detected MIME type is application/x-x509-ca-cert which is not in the whitelist of allowable MIME types to read. 

Can workaround by installing awscli, but would be useful to have available directly from Terraform.

https://github.com/terraform-providers/terraform-provider-aws/issues/1323

https://github.com/hashicorp/terraform/issues/15474

**Comment by saravanan30erd** [comment]
@bflad whitelisted application/x-x509-ca-cert (#4298 ).
