### ISSUE TITLE
aws_waf_rate_based_rule resource missing support for RegexMatch predicates

### ISSUE THREAD

**Issue by kchristensen** [terraform-providers/terraform-provider-aws#4068]
With the addition of all the great new WAF support, we are experimenting with rate limiting login attempts on our site. The code provided below I would expect to work, and does, with the exception of the predicate on the rate based rule.

If I comment out the predicate section of the supplied code, and manually configure the rule in the console to use the match set and pattern set provided, Terraform wants to undo it, which is how I determined that `RegexMatch` is a valid predicate type:

```
  ~ aws_waf_rate_based_rule.rate_based_rule
      predicates.#:                 "1" => "0"
      predicates.892643636.data_id: "11ecd15c-f22f-480c-b0b0-ad28466d2e18" => ""
      predicates.892643636.negated: "false" => "false"
      predicates.892643636.type:    "RegexMatch" => ""
```

### Terraform Version
Terraform v0.11.5
+ provider.aws v1.13.0
+ provider.template v0.1.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_waf_rate_based_rule

### Terraform Configuration Files
```hcl
resource "aws_waf_regex_pattern_set" "regex_login" {
  name                  = "${var.env}-regex-login"
  regex_pattern_strings = ["/login"]
}

resource "aws_waf_regex_match_set" "regex_match_set" {
  depends_on = ["aws_waf_regex_pattern_set.regex_login"]
  name       = "${var.env}-regex-login"

  regex_match_tuple {
    field_to_match {
      type = "URI"
    }

    regex_pattern_set_id = "${aws_waf_regex_pattern_set.regex_login.id}"
    text_transformation  = "NONE"
  }
}

resource "aws_waf_rate_based_rule" "rate_based_rule" {
  depends_on  = ["aws_waf_regex_match_set.regex_match_set"]
  name        = "${var.env}-rate-limit-logins"
  metric_name = "RateLimitLogins"

  rate_key   = "IP"
  rate_limit = 2000

  predicates {
    data_id = "${aws_waf_regex_match_set.regex_match_set.id}"
    negated = false
    type    = "RegexMatch"
  }
}
```

### Expected Behavior
When associating a Regex Pattern set with a rate based rule, you would be able to specify the predicate type of "RegexMatch" to do rate limiting based on URI regex matching.

### Actual Behavior
Terraform errors out: ```Error: aws_waf_rate_based_rule.rate_based_rule: expected predicates.0.type to be one of [IPMatch ByteMatch SqlInjectionMatch SizeConstraint XssMatch GeoMatch], got RegexMatch```

**Comment by kchristensen** [comment]
And of course, this got fixed already since I typed this up. You guys!

**Comment by bflad** [comment]
Thanks for the report. It turns out `RegexMatch` predicate type validation was added to `aws_wafregional_rule` in #4046, but still missing from `aws_waf_rate_based_rule`, `aws_waf_rule`, and `aws_wafregional_rate_based_rule`. Submitted #4069 to fix that up. 👍
