### ISSUE TITLE
terraform support for data souce for aws_secrets_manager

### ISSUE THREAD

**Issue by phanindra2407** [terraform-providers/terraform-provider-aws#4073]
Hi,

AWS provided aws secret manager feature https://aws.amazon.com/about-aws/whats-new/2018/04/introducing-aws-secrets-manager/ . If see that https://github.com/terraform-providers/terraform-provider-aws/issues/4060 is already open for new resource. it would be great to add a data source so that other aws resources can use it to get required sensitive attributes

**Comment by catsby** [comment]
Thanks for requesting! I posted a request on #4060 to include the data source in that work as well, so I'm going to close this for now. You can go there an upvote if you haven't already.
