### ISSUE TITLE
aws_ecs_service should support multiple load balancers

### ISSUE THREAD

**Issue by jeffnappi** [terraform-providers/terraform-provider-aws#4089]
The ECS Service API supports multiple load balancers. There are cases where a service is running multiple containers that require separate target group registrations. The AWS endpoint supports multiples:

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html

It appears that it would be fairly straightforward to support. I am willing to implement it if it would be likely to get merged :)

**Comment by Puneeth-n** [comment]
@jeffnappi I think the API though accepts an array only allows 1 load balancer. Also from the aws console, I created a new service and it only allows me to add 1 load balancer. Tried it in `eu-west-1`

**Comment by bflad** [comment]
Unfortunately, this limitation has not changed: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_limits.html

```
Number of load balancers per service | 1
```

If/when ECS supports additional load balancers, we can surely update the code, but since there is nothing to do at the moment I am going to close this issue.

**Comment by Pucster** [comment]
I might be way off here but I can do something like:

aws_alb_target_group bla_tg
aws_alb_target_group bla_tg_two

aws_alb_listener bla_listener -> forwards to bla_listener and has load_balancer_arn = alb_1
aws_alb_listener bla_listener_two -> forwards to bla_tg_two and has load_balancer_arn = alb_2

however, in aws_ecs_service I can only use for load_balancer one of the bla_tg or bla_tg_two. Strangest thing is that I can link the newly created target group to the service and it actually works in a configuration that looks like this:

ALB_1 -> listener_A (on port X) -> forwards to bla_tg which targets a container deployed on ECS
ALB_2 -> listener_B (on port X) -> forwards to bla_tg2 which targets the same container on the same port

I have just tested this and it works. I am trying to implement two different endpoints (one "external" and one "internal" for the same ECS container) and it looks like this works or, as I said initially, I am completely off and missing a very obvious point.

**Comment by aterreno** [comment]
Just bumped into this as I need exactly the same thing, two containers running on the same service... 
Sadly only two votes on @ ryanschneider issue so far. I'll give it a go with @Pucster workaround...

**Comment by remarkpk** [comment]
It would appear that AWS added support to add an ECS service to multiple load balancers:

https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecs-services-now-support-multiple-load-balancer-target-groups/

**Comment by jacoor** [comment]
Right, I am waiting for this support in TF too.

**Comment by bflad** [comment]
Support for multiple `load_balancer` configuration blocks in the `aws_ecs_service` resource was previously released in [version 2.22.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2220-august-01-2019):
> resource/aws_ecs_service: Allow multiple `load_balancer` configuration blocks (support for multiple target groups) (#9411)

Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) for upgrading.

For any future issues with this functionality, please submit new GitHub issues following the [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) and [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) issue templates for further triage. Thanks.
