### ISSUE TITLE
Feature Request: Support CloudFront Field Level Encryption Profile

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#4098]
Recently the AWS SDK for Go has added support for managing CloudFront field level encryption profiles as first announced in: https://aws.amazon.com/about-aws/whats-new/2017/12/introducing-field-level-encryption-on-amazon-cloudfront/

Please vote on this issue by adding a :+1: reaction to the original issue to help prioritize interest. If you're interested in implementing this feature request, please comment below.

Prerequisite: aws-sdk-go v.1.13.26 (already merged)

### Terraform Version

terraform 0.10+

### New Resource(s)

- `aws_cloudfront_field_level_encryption_profile`

### Terraform Configuration Files

```hcl
# Example implementation, may change when developed
resource "aws_cloudfront_field_level_encryption_profile" "example" {
  comment = "" # optional
  encryption_entity { # required
    field_patterns = [] # required
    provider_id = "" # required
    public_key_id = "" # required
  }
  name = "" # required
}
```

### Expected Behavior

Resource creates, updates, and deletes CloudFront field level encryption profiles.

### Actual Behavior

New feature.

### References

* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/field-level-encryption.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/cloudfront/#CloudFront.CreateFieldLevelEncryptionProfile

**Comment by saravanan30erd** [comment]
I will start to work on this resource.
