### ISSUE TITLE
aws_codebuild_project: cache option unclear documentation

### ISSUE THREAD

**Issue by ebarault** [terraform-providers/terraform-provider-aws#4114]
### Affected Resource(s)
- aws_codebuild_project

Documentation states
```
cache supports the following:

location - (Required) The location where the AWS CodeBuild project stores cached resources.
Has to be an S3 bucket.
```

The `"Has to be an S3 bucket"` part is misleading as location can also include a path inside the S3 bucket.
For example, location can be `my-s3-bucket/path/to/cache`

Also, the config is not consistent with the `artifacts` config where the path inside the bucket can be specified either with the former syntax, or with the `path` option which does not exist in the cache config.

cc: @kaofelix, @bflad

**Comment by catsby** [comment]
I agree this is confusing. For the `Has to be an S3 bucket` part, I've opened https://github.com/terraform-providers/terraform-provider-aws/pull/4130 .  Care to take a look and 👍  / 👎  @ebarault ?

For the `location` attribute, I'm not 💯 on what to do... our documentation seems mostly inline with AWS's docs:

- https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectArtifacts.html

The difference I see is that we say that `artifacts.location` can be a path if `path` is not specified, but AWS does not say that:

> If type is set to S3, this is the name of the output bucket.

I suspect "output bucket" there is just assumed that a full path would work as well.

**Comment by ebarault** [comment]
ok, so the inconsistency between artifacts and cache API comes from AWS in the first place.
Probably terraform's API should stick to AWS API.

The console does propose a specific field for path, but they must aggregate bucket+path before calling the AWS API.

So it's mostly a doc issue, where the doc from AWS is not clear either.
Will take a look at #4130

**Comment by bflad** [comment]
#4130 was merged awhile ago that should have handled this 😄  If there's something else missing here, we can reopen this issue.
