### ISSUE TITLE
Don't Enforce DynamoDB's Indexes Creation

### ISSUE THREAD

**Issue by guessi** [terraform-providers/terraform-provider-aws#4123]
### Terraform Version
```
$ terraform -v
Terraform v0.11.6
+ provider.aws v1.14.0
```

### Affected Resource(s)
- aws_dynamodb_table

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "table_test" {
  name           = "table.test"
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "AAA"

  # table attributes
  attribute {
    name = "AAA"
    type = "S"
  }

  attribute {
    name = "BBB"
    type = "S"
  }

  attribute {
    name = "CCC"
    type = "S"
  }

  attribute {
    name = "DDD"
    type = "S"
  }

  # ttl
  ttl {
    attribute_name = "TimeToExist"
    enabled        = false
  }

  # global secondary index (GSI)
  global_secondary_index {
    name            = "GSI_BBB"
    hash_key        = "BBB"
    write_capacity  = 1
    read_capacity   = 1
    projection_type = "ALL"
  }

  # tag
  tags {
    env       = "dev"
    TerraForm = "true"
  }
}

```

### Debug Output
```

<skipped>

2018/04/09 16:27:17 [TRACE] Graph after step *terraform.AttachStateTransformer:

aws_dynamodb_table.table_test - *terraform.NodePlannableResourceInstance
2018/04/09 16:27:17 [DEBUG] ReferenceTransformer: "aws_dynamodb_table.table_test" references: []
2018/04/09 16:27:17 [TRACE] Graph after step *terraform.ReferenceTransformer:

aws_dynamodb_table.table_test - *terraform.NodePlannableResourceInstance
2018/04/09 16:27:17 [ERROR] root: eval: *terraform.EvalDiff, err: All attributes must be indexed. Unused attributes: ["CCC" "DDD"]
2018/04/09 16:27:17 [ERROR] root: eval: *terraform.EvalSequence, err: All attributes must be indexed. Unused attributes: ["CCC" "DDD"]
2018/04/09 16:27:17 [TRACE] [walkPlan] Exiting eval tree: aws_dynamodb_table.table_test

2018/04/09 16:27:17 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error running plan: 1 error(s) occurred:

* aws_dynamodb_table.table_test: 1 error(s) occurred:

* aws_dynamodb_table.table_test: All attributes must be indexed. Unused attributes: ["CCC" "DDD"]


2018-04-09T16:27:17.016+0800 [DEBUG] plugin: plugin process exited: path=/Users/kuole_mei/cyclops-infra/.terraform/plugins/darwin_amd64/terraform-provider-aws_v1.14.0_x4
```

### Panic Output
N/A

### Expected Behavior
Resource should be created without error

### Actual Behavior
Resource can't be created due to the following code lines:
[validators.go#L1725-L1739](https://github.com/terraform-providers/terraform-provider-aws/blob/v1.14.0/aws/validators.go#L1725-L1739)

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
- AWS DynamoDB

### References
- [GH-3194](https://github.com/terraform-providers/terraform-provider-aws/pull/3194)

**Comment by guessi** [comment]
false report, closed.

**Comment by MarkVLK** [comment]
@guessi unless I'm misunderstanding something, this issue is legitimate as I seem to be facing it now. I'm getting `All attributes must be indexed` error for the following configuration:

```
resource "aws_dynamodb_table" "dynamodb_table" {
  name           = "Asset_DB_TF"
  hash_key       = "Product"
  read_capacity  = 1
  write_capacity = 1

  server_side_encryption {
    enabled = true
  }

  attribute = [{
    name = "Product"
    type = "S"
  }, {
    name = "Contact"
    type = "S"
  }, {
    name = "Deployed"
    type = "S"
  }, {
    name = "Resource ID"
    type = "S"
  }, {
    name = "Version"
    type = "S"
  }]
}
```

Specifically:
> aws_dynamodb_table.cisco_dynamodb_table: All attributes must be indexed. Unused attributes: ["Contact" "Resource ID" "Deployed" "Version"]

**Comment by guessi** [comment]
@MarkVLK the reason why I close the issue is that I misunderstand how DynamoDB works, and I think you might misunderstand as well.

In your case, just like the error message suggested, simply remove the unused attributes and problem should solved.

Code Snippet:
```
resource "aws_dynamodb_table" "dynamodb_table" {
  name           = "Asset_DB_TF"
  hash_key       = "Product"
  read_capacity  = 1
  write_capacity = 1

  server_side_encryption {
    enabled = true
  }

  attribute = {
    name = "Product"
    type = "S"
  }
}
```

The other attributes would be created automatically while data write into DynamoDB, you don't need to define them in Terraform at creation time.

If you need a secondary index, you're probably looking at `global_secondary_index`.


References:
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.CoreComponents.html#HowItWorks.CoreComponents.PrimaryKey
- https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#global_secondary_index-1

**Comment by MarkVLK** [comment]
Ah ok, you're right. Reading a little more carefully in the [docs](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#attribute) too I see now that it says `Only required for hash_key and range_key attributes.`

The [boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.create_table) are a little more specific in their description:
`AttributeDefinitions: An array of attributes that describe the key schema for the table and indexes.`
