### ISSUE TITLE
Please allow dot in `aws_vpn_connection.tunnel*_preshared_key`

### ISSUE THREAD

**Issue by saiya** [terraform-providers/terraform-provider-aws#4169]
Hi, I encountered issue caused by validation mismatch between AWS and terraform.
It prevent us from creating aws_vpn_connection.

Could you fix this validation issue?

### Terraform Version

```
Terraform v0.11.6
+ provider.aws v1.14.0
```

### Affected Resource(s)

- aws_vpn_connection

### Terraform Configuration Files

```hcl
resource "aws_vpn_connection" "main" {
  # (snip)

  tunnel1_preshared_key = "example.preshared.key"
  tunnel2_preshared_key = "example.preshared.key"
}

```

### Expected Behavior

Able to use preshared_key that contains dot (".").

### Actual Behavior

Got following error, cannot create aws_vpn_connection resource:

```
Error: module.vpn.aws_vpn_connection.main: "tunnel2_preshared_key" can only contain alphanumeric and underscore characters
```

I think this behavior is caused by this code: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_vpn_connection.go#L571

### Steps to Reproduce

- Generate VPN pre-shared key with VPN appliance
- Write `aws_vpn_connection` resource
- `terraform plan`

### References

[AWS official document](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_VPN.html) says:

```
The PSK must be between 8 and 64 characters in length and cannot start with zero (0). Allowed characters are alphanumeric characters, periods (.), and underscores (_).
```

**Comment by bflad** [comment]
The fix for this will be released with v1.22.0 of the AWS provider, middle of this week.
