### ISSUE TITLE
Feature Request: Support resource policy when creating AWS api gateway

### ISSUE THREAD

**Issue by ben-poole** [terraform-providers/terraform-provider-aws#4171]
Amazon API Gateway Supports Resource Policies for APIs: https://aws.amazon.com/about-aws/whats-new/2018/04/amazon-api-gateway-supports-resource-policies/

CLI: ```aws apigateway create-rest-api \
    --name "api-name" \
    --policy "{\"jsonEscapedPolicyDocument\"}"```

Can this be supported in aws_api_gateway_rest_api?

### Terraform Version
terraform 0.10+

### Affected Resource(s)
aws_api_gateway_rest_api

### Terraform Configuration Files
Current:
```
resource "aws_api_gateway_rest_api" "MyDemoAPI" {
  name        = "MyDemoAPI"
  description = "This is my API for demonstration purposes"
}
```

Proposed:
```
resource "aws_api_gateway_rest_api" "MyDemoAPI" {
  name        = "MyDemoAPI"
  description = "This is my API for demonstration purposes"
  policy = "{\"jsonEscapedPolicyDocument\"}"
}
```

### References
* https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html
* https://aws.amazon.com/about-aws/whats-new/2018/04/amazon-api-gateway-supports-resource-policies/

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by marcoreni** [comment]
@bflad there seems to be an issue with the release.

After upgrading to 1.16.0 I'm getting `error unescaping policy: invalid syntax` error while running apply, even if I haven't declared a policy.

**Comment by bflad** [comment]
I would suggest opening a new issue filling out the template so we have details to troubleshoot. 👍 We'll likely need to see the debug logs from the SDK.

Admittedly the policy handling is a little strange to begin with:

https://github.com/terraform-providers/terraform-provider-aws/blob/6ef2184acfdf0ec330d5cfb35cf5ea7e51049fb2/aws/resource_aws_api_gateway_rest_api.go#L166-L172
