### ISSUE TITLE
Add support for aws_batch_job_definition timeout

### ISSUE THREAD

**Issue by hectcastro** [terraform-providers/terraform-provider-aws#4186]
### Affected Resource(s)

- `aws_batch_job_definition`

### Expected Behavior

The `aws_batch_job_definition` resource should support the newly added `timeout` attribute.

### Actual Behavior

The attribute is not present.

### Important Factoids

See:

- https://aws.amazon.com/about-aws/whats-new/2018/04/aws-batch-adds-support-for-automatic-termination-with-job-execution-timeout/
- https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#timeout

**Comment by bflad** [comment]
Prerequisite: AWS Go SDK v1.13.30+ (#4206)

**Comment by hectcastro** [comment]
👋

**Comment by bflad** [comment]
The enhancement for this has been merged in via #4386 and will release with v1.17.0 of the AWS provider tomorrow.

**Comment by bflad** [comment]
This has been released in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
