### ISSUE TITLE
Changes to aws_codedeploy_deployment_config resource should result in resource being destroyed and recreated

### ISSUE THREAD

**Issue by caramcc** [terraform-providers/terraform-provider-aws#4192]
Terraform attempts to make changes to `aws_codedeploy_deployment_config` resource, rather than destroy/recreate. AWS does not support updating this resource.

### Terraform Version
`0.10.8`
AWS provider version `1.4`

### Affected Resource(s)
- `aws_codedeploy_deployment_config`

### Terraform Configuration Files
[Example Usage resources](https://www.terraform.io/docs/providers/aws/r/codedeploy_deployment_config.html#example-usage)

### Expected Behavior
The deployment config is destroyed and recreated with the change reflected

### Actual Behavior
Apply fails with ` * aws_codedeploy_deployment_config.deployment_config: doesn't support update`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` to create a `aws_codedeploy_deployment_config` resource
1. modify the resource, e.g. set `minimum_healthy_hosts.value` to `1`. 
1. `terraform apply` again

**Comment by bflad** [comment]
Thanks for the report @caramcc! I have submitted a bugfix PR for this: #4194

**Comment by caramcc** [comment]
@bflad awesome, thanks!

I have a question about your PR: 

It's also not possible to modify the `deployment_configuration_name` field (not just the `minimum_healthy_hosts ` block), so changes to that field would also result in a failed apply.

Would it be feasible for a `name_prefix` option to be supported, like in the case of the `aws_launch_configuration` module, which also needs to be destroyed and recreated and (like this resource) is frequently referenced by name in other resources?

**Comment by bflad** [comment]
Sounds reasonable, I would create a separate issue for that enhancement. 😄  I won't personally have time to implement it, but maybe someone in the community will.

**Comment by bflad** [comment]
The force new resource fix is now merged into master and will release with v1.15.0 of the AWS provider. As I mentioned yesterday, I would suggest creating a new issue for supporting `name_prefix` 👍

**Comment by bflad** [comment]
This has been released in [version 1.15.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
