### ISSUE TITLE
aws_instance - Changing the size of the root block volume on a instance causes the instance to be destroyed and recreated

### ISSUE THREAD

**Issue by ChristopherGAndrews** [terraform-providers/terraform-provider-aws#4196]
This issue is detailed at length here (previous to the providers becoming their own repos):

https://github.com/hashicorp/terraform/issues/14445

```
$ terraform --version
Terraform v0.11.7
+ provider.aws v1.14.1
+ provider.null v1.0.0
```

Say you have and instance with a 

```
      root_block_device.#:                       "1" => "1"
      root_block_device.0.delete_on_termination: "false" => "false"
      root_block_device.0.volume_id:             "vol-0d0c01311126965f8" => <computed>
      root_block_device.0.volume_size:           "40" => "41" (forces new resource)
      root_block_device.0.volume_type:           "gp2" => "gp2"
```

This issue is a huge pain if you have servers that cannot be destroyed and recreated at will, especially the Windows based images .  The current work flow now is:

1. Change the size of the root ebs volume outside of terraform
2. Edit the TerraForm files to reflect the new number
3. Apply the new TerraForm file to update the state files

The change does not require or force a reboot.  It does require that you tell the OS to expand the volume.  There is no expectation that TerraForm will be required to tell the OS of the change, just like changing the instance type with TerraForm doesn't force the instance to reboot.

It would be nice to have a root volume size increase not require that extra non-TerraForm step of manually interacting with the AWS console or cli.

**Comment by igozali** [comment]
I've read the original issue in the Terraform repo, and it's been 2 years since that discussion. Could it be that the situation's changed enough that we could actually implement the fix safely now, as mentioned in [the comment](https://github.com/hashicorp/terraform/issues/14445#issuecomment-403220906) in that issue?

**Comment by next-jesusmanuelnavarro** [comment]
> The change does not require or force a reboot. It does require that you tell the OS to expand the volume. There is no expectation that TerraForm will be required to tell the OS of the change, just like changing the instance type with TerraForm doesn't force the instance to reboot.

Well, changing the instance type with Terraform **does** force a reboot (at least on amazon linux instances).  That's in fact the origin of #6781.
