### ISSUE TITLE
vpc_endpoint_route_table_association is impossible to import

### ISSUE THREAD

**Issue by eredi93** [terraform-providers/terraform-provider-aws#4243]
`vpc_endpoint_route_table_association` does not have an import functionality.
when you import `aws_route_table` and it creates `aws_route_table_association` in the state file, importing `aws_vpc_endpoint` should do the same

**Comment by aries1980** [comment]
This is a dupe of https://github.com/terraform-providers/terraform-provider-aws/issues/561 .

**Comment by bflad** [comment]
This does appear to be a duplicate of #561 so closing this in preference of the earlier issue. 👍
