### ISSUE TITLE
terraform return error reporting StatusCode: "Succesful"

### ISSUE THREAD

**Issue by Raffaello** [terraform-providers/terraform-provider-aws#4250]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.7

### Affected Resource(s)
- aws_autoscaling_group

### Terraform Configuration Files
```hcl
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
It should create and create the resource. (it actualy does, but it is failing in "Still creating..." phase)

### Actual Behavior
```
14:48:01 
14:48:01 Error: Error applying plan:
14:48:01 
14:48:01 1 error(s) occurred:
14:48:01 
14:48:01 * module.xxx.aws_autoscaling_group.service-ag: 1 error(s) occurred:
14:48:01 
14:48:01 * aws_autoscaling_group.service-ag: "asg-xxxxxx": Waiting up to 10m0s: Need at least 1 healthy instances in ELB, have 0. Most recent activity: {
....
14:48:01   StatusCode: "Successful"
14:48:01 }
14:48:01 
14:48:01 Terraform does not automatically rollback in the face of errors.
14:48:01 Instead, your Terraform state file has been partially updated with
14:48:01 any resources that successfully completed. Please address the error
14:48:01 above and apply again to incrementally change your infrastructure.
14:48:01 
````

And the instance is attached and healthy after few seconds.

is a symptom of corrupted tfstate file?

**Comment by Raffaello** [comment]
anyway i do not think it is strictly a terraform issue and it is not a tfstate that i confirmed reusing the module in a different environment, 
However, 
this ticket my lead to have a better error reporting to better clearly understand what is wrong, because here is quite misleading why is failing.

**Comment by MartinCerny-awin** [comment]
@Raffaello Could you please share your solution as I am experiencing the same issue.

**Comment by MartinCerny-awin** [comment]
I have found out that my problem was with wrong Health check configuration. I've verified the health check manually on ec2 instance and it was not working as expected.
