### ISSUE TITLE
Delay EC2 instance destroy until cloud-init finishes using create_before_destroy

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-aws#4254]
I have two EC2 instances associated with a network load balancer. Whenever I rebuild the base AMI for the instances and apply, Terraform creates two new instances first *(because I am using: `lifecycle { create_before_destroy = true }`)* however it does both instances at the same time, which causes a short blimp in downtime as both get destroyed at the same time.

Secondly because we use `user_data` and provide a script that take around 15 seconds to bootstrap the EC2 instances, this also causes additional downtime.

Is there a way to delay the destroy until after `user_data` is finished executing? I believe currently the destroy happens as soon as AWS acknowledges the new instance is up, but not after cloud-init has actually finished executing.

**Comment by radeksimko** [comment]
Hi @nodesocket 
correct me if I'm wrong, but the only way to detect whether user_data/cloud-config finished provisioning is to check existence of a file on the instance. This means Terraform would need to know how to SSH/WinRM into the instance - which in practice means knowing what OS is running there, how is it configured etc. This is nearly impossible to detect reliably.

Even if we were able to detect it and used SSH auth defined by the user it's still not something we'd typically expect Terraform to do. The best practice in this area is to use e.g. [Packer](https://www.packer.io/docs/builders/amazon.html) to bake a provisioned image and then use that image - which also has the advantage of shortening startup time.

For that reason I'm going to close the issue, but do let me know if you need to discuss this further or if I misunderstood your use-case/problem.

**Comment by nodesocket** [comment]
@radeksimko for the reply. Isn't there still slight downtime even if I don't do any instance configuration via cloud-init because Terraform deletes the old instances as soon as the new instances are the "running" state in AWS. In my experience "running" does not mean the instance is fully booted and all services started. How all others handling this?

A proposal, what if there was an option for `create_before_destroy` that takes a http endpoint. This endpoint has to return a 200 status code before Terraform does the destroy.

**Comment by nodesocket** [comment]
Terraform actually does not do the destroy until `cloud-init` finishes. The solution then is to create a health check script loop and check the health of the server and call it from `cloud-init`.
