### ISSUE TITLE
Bug: OAuthToken should appear as `<sensitive>` in plan/apply output

### ISSUE THREAD

**Issue by Stretch96** [terraform-providers/terraform-provider-aws#4261]
### Terraform Version
v0.11.7

### Affected Resource(s)
- aws_codebuild_project

The `OAuthToken` is currently output in the logs from `terraform plan` and `terraform apply` (As a new or modified resource)

There isn't currently a way for a developer to set variables as `sensitive` and apparently should be considered a bug if the `provider` doesn't ensure it appears as `<sensitive>`

### References
- https://github.com/hashicorp/terraform/issues/16643

**Comment by bflad** [comment]
This was merged into master via #4284 and will release with v1.16.0 of the AWS provider, likely in a few days.

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
