### ISSUE TITLE
Statefile push failure due to proxy issues, how to retry 

### ISSUE THREAD

**Issue by harkamals** [terraform-providers/terraform-provider-aws#4280]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
- terraform apply

### Debug Output
Error: Error loading state: RequestError: send request failed
caused by: Get https://my-statefiles.s3.eu-west-1.amazonaws.com/?prefix=env%3A%2F: Service Unavailable

### Expected Behavior
Statefiles pushed to S3 bucket

### Actual Behavior
Failed to push state, potentially due to http proxy server issues.
Is there a way to specify "retry" ?!

### Steps to Reproduce
terraform apply

**Comment by bflad** [comment]
Hi @harkamals 👋  Sorry you ran into trouble here. 

The state and S3 backend handling is mostly managed by the core Terraform code and you'll want to file this issue upstream at: https://github.com/hashicorp/terraform/

I'd have our Github bot automatically migrate this issue but it currently only understands how to migrate issues from core -> provider and not the other way around (provider -> core).

If those maintainers in turn push this issue back as an issue with the AWS provider code used by the backend, we can reopen this issue. 👍
