### ISSUE TITLE
Feature Request: Batch job queue as target for aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by gheine** [terraform-providers/terraform-provider-aws#4281]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
aws_cloudwatch_event_target

### Expected Behavior
Similar to eg. `ecs_target`, aws_cloudwatch_event_target should support AWS Batch jobs. See https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-cloudwatch-events-now-supports-aws-batch-as-an-event-target/

### Actual Behavior
Currently batch jobs can't be invoked from cloudwatch events.

### Steps to Reproduce
`

**Comment by jessegonzalez** [comment]
duplicates #4023

**Comment by bflad** [comment]
This has been released in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
