### ISSUE TITLE
Referencing global resources between regions

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-aws#4292]
I have two AWS regions each independent Terraform directories using their own S3 Terraform backend. The problem is there are shared resources _(global)_ between the two regions such as IAM and S3 buckets. Is there a a way to get a resource reference from another Terraform provider/directory?

Here is my directory structure:

```
terraform
    environments
        eu-central-1
            .terraform
            terraform.tf
            provider.tf
            ...
        us-west-2
            .terraform
            terraform.tf
            provider.tf
            ...
```

**Comment by loivis** [comment]
Does data source satisfy your case? Or it's more complicated? With data source, it doesn't matter where you've created the resource, or even if it's not created by terraform.
