### ISSUE TITLE
Data Source Route 53 Zone has attribute name_servers

### ISSUE THREAD

**Issue by genevieve** [terraform-providers/terraform-provider-aws#4334]
Hey y'all, would you accept a PR to return the name servers from the delegation set that is returned for a found route53 hosted zone?

[This request](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_route53_zone.go#L100) returns a [delegation set](https://github.com/terraform-providers/terraform-provider-aws/blob/master/vendor/github.com/aws/aws-sdk-go/service/route53/api.go#L9218) for a hosted zone and that delegation set contains the name servers.

We would like to be able to get an existing hosted zone, add records to it, and continue to have the name servers as an output.

**Comment by catsby** [comment]
Seems totally reasonable 👍 , I believe we'd accept that for sure

**Comment by bflad** [comment]
This has been released in [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
