### ISSUE TITLE
Launch configuration error on plan

### ISSUE THREAD

**Issue by nwhite-sf** [terraform-providers/terraform-provider-aws#4335]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_launch_configuration

### Expected Behavior
Terraform plan should have run and identified that the instance type associated with the launch configuration's instance_type had changed.

### Actual Behavior
The following error was displayed instead:

Error: module.foo.module.etcd.module.asg_foo.aws_launch_configuration.launch_config: expected length of name to be in the range (1 - 255), got 

### Important Factoids
I knew this Terraform had successfully worked in the recent past so I suspected the AWS provider.  I stepped back the AWS provider version from the current version 1.15.0 until Terraform plan worked as expected and the first version it worked at 1.13.0 so this looks like it was introduced by 1.14.0.

**Comment by catsby** [comment]
Hey! Can you give me a sample configuration that demonstrates this? There was some validation changes introduced for the `name` attribute, but they only change was ensuring that `name` was at least a single character in length, if provided at all, which was introduced here in #4037 : 

- https://github.com/terraform-providers/terraform-provider-aws/pull/4037/files#diff-7f375080e2a41c3ea0427081a64e5549R36

I tried this out locally and indeed only got validation errors if my configuration looks like this, which is technically valid in 1.3.0:

```hcl
resource "aws_launch_configuration" "foobar" {
  name = ""

  image_id = "ami-dfc39aef"
  [... other things ...]
}
```

**Comment by mildwonkey** [comment]
Hi! Since there hasn't been a response in awhile, I'm going to close this out, but if you are still experiencing this, feel free to reply below and we can open this back up and take a look. Thanks!

**Comment by nwhite-sf** [comment]
That's fine. It does look like this was the result of us setting the launch_config name to "" was in the past had not produced an error.
