### ISSUE TITLE
aws_appautoscaling_policy uses ftstate/cached arn instead of new one

### ISSUE THREAD

**Issue by rkr-kununu** [terraform-providers/terraform-provider-aws#4340]
It appears that aws_appautoscaling_policy has a bug, where as it uses the arn stored in the tfstate (on S3) for any downstream dependencies (mainly aws_cloudwatch_metric_alarm) as opposed to using the newly generated arn.

### Terraform Version
We're using terraform-provider-aws v1.15.0 with terraform v0.10.8 (I cannot quickly update it ATM)

### Affected Resource(s)
- aws_appautoscaling_policy
- any down stream dependencies (ie: aws_cloudwatch_metric_alarm)
- potentially aws_appautoscaling_target
- potentially aws_spot_fleet_request

### Terraform Configuration Files
Unfortunately, I cannot paste in a full working example.  I stumbled upon this bug while noticing that our `aws_cloudwatch_metric_alarm.alarm_actions` needed to have `terraform apply` ran twice, if the `aws_appautoscaling_policy` had changed.  I wasn't able to construct a suitable unit test.

After digging through the `tfstate` I noticed that if the `aws_appautoscaling_policy` changes and an in-place update is *not* possible, a new ARN is generated.  Yet, the _old_ ARN was being passed into the `aws_cloudwatch_metric_alarm.alarm_actions` (I confirmed this by look at the tfstate).

During a second run of `terraform apply`, TF would notice that the `aws_cloudwatch_metric_alarm.alarm_actions` would need to be updated (as the `aws_appautoscaling_policy.arn` now had the new ARN).

### Expected Behavior
TF would properly set the `aws_cloudwatch_metric_alarm.alarm_actions` to the current arn for `aws_appautoscaling_policy.arn`.

### Actual Behavior
The `aws_cloudwatch_metric_alarm.alarm_actions` were set to an old `aws_appautoscaling_target.resource_id` (for my case referred to cancelled `aws_spot_fleet_request.id`)

### References

- GH-14427
- GH-968
- GH-2878

**Comment by catsby** [comment]
Hey thanks for writing in! Is it possible to share the `aws_cloudwatch_metric_alarm` configuration or at least the relevant `alarm_actions` block?

**Comment by bflad** [comment]
Closing due to lack of response -- if this is still an issue please reply back with the requested information. Thanks!
