### ISSUE TITLE
aws_secretsmanager_secret unable to set rotation.

### ISSUE THREAD

**Issue by hgallo0** [terraform-providers/terraform-provider-aws#4349]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- aws_secretsmanager_secret

### Terraform Configuration Files
```hcl
resource "aws_secretsmanager_secret" "secrets" {
  description = "${var.secrets_description}"

  kms_key_id = "${aws_kms_key.kmskey.arn}"              l
  name       = "${var.aws_env_name}/${var.secrets_name}"

  rotation_enabled = true

  rotation_rules {
    automatically_after_days = 7
  }
}
```

### Expected Behavior
module.kms.aws_secretsmanager_secret.secrets: Applying...

### Actual Behavior
Error: module.kms.aws_secretsmanager_secret.secrets: "rotation_enabled": this field cannot be set

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
none

### References
none

**Comment by bflad** [comment]
Hi @hgallo0 👋 

`rotation_enabled` is just an exported attribute, not an argument you can pass into the resource.

As noted in the [`aws_secretsmanager_secret` resource rotation example](https://www.terraform.io/docs/providers/aws/r/secretsmanager_secret.html#rotation-configuration), adding `rotation_lambda_arn` will enable rotation. Removing that argument will disable rotation.

```hcl
resource "aws_secretsmanager_secret" "rotation-example" {
  name                = "rotation-example"
  rotation_lambda_arn = "${aws_lambda_function.example.arn}"

  rotation_rules {
    automatically_after_days = 7
  }
}
```

The Secrets Manager service [requires a Lambda function to perform rotation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html):

> Because each service or database can have a unique way of configuring its secrets, Secrets Manager uses a Lambda function that you can customize to work with whatever database or service that you choose. You customize the Lambda function to implement the service-specific details of how to rotate a secret.

You will need to follow the Secrets Manager user guide documentation to install or configure your own Lambda function.

Hope this helps.

**Comment by hgallo0** [comment]
Thanks @bflad.
