### ISSUE TITLE
aws_cloudwatch_metric_alarm: AWS Console sets different default value for datapointsToAlarm

### ISSUE THREAD

**Issue by zommerfelds** [terraform-providers/terraform-provider-aws#4350]
### Terraform Version
0.10.1
No locked plugin version.

### Affected Resource(s)
- aws_cloudwatch_metric_alarm

### Terraform Configuration Files
```hcl
resource "aws_cloudwatch_metric_alarm" "jvm_memory_pressure" {
  alarm_name = "bla bla"
  alarm_description = "High percentage of the Java heap used"
  namespace = "AWS/ES"
  metric_name = "JVMMemoryPressure"
  statistic = "Maximum"
  comparison_operator = "GreaterThanThreshold"
  threshold = 75
  evaluation_periods = 1
  period = 60
  alarm_actions = ["${var.monitoring_topic_arn}"]
  dimensions {
    ClientId = "${data.aws_caller_identity.current.account_id}"
    DomainName = "my domain name"
  }
}
```

### Steps to Reproduce
1. `terraform apply`
1. Log in to the AWS console => CloudWatch => select the alarm => Modify => Save Changes
1. `terraform plan`

### Expected Behavior
No changes to `datapoints_to_alarm` expected.

### Actual Behavior
`datapoints_to_alarm 1 => 0`

If you look at the alarm history, saving via the UI sets `datapointsToAlarm` to 1. If you run `terraform apply`, it removes the field entirely.

I'm not sure if this is really a "bug" or not, but it would be nice if Terraform knew that `datapointsToAlarm: 1` is the same as not being present. Or maybe set to `1` as the default so it's consistent with the AWS console.

We encountered this issue when someone was inspecting the alarm, clicked "Save Changes" and didn't expect anything to change, but our CI process (which runs `plan`) warned of changes.

**Comment by paulbrice** [comment]
We have experienced the same issue. An alarm was created in the console then imported to Terraform, the config was built out the same as all the other metrics not explicitly defining `datapoints_to_alarm`. The next time a `terraform plan` was run an update was going to be actioned in the apply.

`datapoints_to_alarm 10 => 0`

State Post Import:
```
aws_cloudwatch_metric_alarm.foobar_metric_3:
  id = terraform-elb-latency-alarm-3
  actions_enabled = true
  alarm_actions.# = 0
  alarm_description = This metric monitors ELB latency
  alarm_name = terraform-elb-latency-alarm-3
  comparison_operator = GreaterThanOrEqualToThreshold
  **datapoints_to_alarm = 10**
  dimensions.% = 1
  dimensions.LoadBalencerName = test-lb-tf
  evaluate_low_sample_count_percentiles = evaluate
  evaluation_periods = 10
  extended_statistic = p90
  insufficient_data_actions.# = 0
  metric_name = Latency
  namespace = AWS/ELB
  ok_actions.# = 0
  period = 60
  statistic =
  threshold = 0.8
  treat_missing_data = notBreaching
  unit =
```

State Post Apply:
```
aws_cloudwatch_metric_alarm.foobar_metric_3:
  id = terraform-elb-latency-alarm-3
  actions_enabled = true
  alarm_actions.# = 0
  alarm_description = This metric monitors ELB latency
  alarm_name = terraform-elb-latency-alarm-3
  comparison_operator = GreaterThanOrEqualToThreshold
  **datapoints_to_alarm = 0**
  dimensions.% = 1
  dimensions.LoadBalencerName = test-lb-tf
  evaluate_low_sample_count_percentiles = evaluate
  evaluation_periods = 10
  extended_statistic = p90
  insufficient_data_actions.# = 0
  metric_name = Latency
  namespace = AWS/ELB
  ok_actions.# = 0
  period = 60
  statistic =
  threshold = 0.8
  treat_missing_data = notBreaching
```

**Comment by sean-zou** [comment]
+1

**Comment by edy-chan** [comment]
We are still seeing this issue with Terraform 0.11.11
any idea why?

**Comment by serdardalgic** [comment]
I also see the same behaviour with those versions:

```
% terraform --version
Terraform v0.11.11
+ provider.archive v1.0.3
+ provider.aws v1.41.0
+ provider.template v1.0.0
```
The "untouched" aws_cloudwatch_metric_alarms are set to 0, but the ones I changed via AWS console are set to 1, and terraform plan foresee the 1 => 0 change for them.
