### ISSUE TITLE
Error Creating AWS Launch Template using block_device_mappings with EBS

### ISSUE THREAD

**Issue by brianpham** [terraform-providers/terraform-provider-aws#4356]
Hi there,
### Terraform Version
Terraform v0.11.7
+ provider.aws v1.15.0

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_aws_launch_template
- block_device_mappings w/ ebs

### Terraform Configuration Files
```resource "aws_launch_template" "staging" {
  name = "staging_server"
  description = "2018-04-24"
  image_id = "ami-9e2685e3"
  instance_type = "c4.2xlarge"

  network_interfaces {
    subnet_id = "subnet-67d4b87c"
    associate_public_ip_address = true
    security_groups = ["sg-3e47bd12"]
    delete_on_termination = true
  }

  block_device_mappings {
    "device_name" = "/dev/sdb"
    "ebs" {
      "volume_size" = "40"
      "volume_type" = "gp2"
      "iops" = 3000,
      "delete_on_termination" = true
    }
  }

  placement {
    availability_zone = "us-west-2b"
  }

  iam_instance_profile {
    arn = "arn:aws:iam::825035904621:instance-profile/server"
  }

  monitoring {
    enabled = true
  }

  instance_initiated_shutdown_behavior = "stop"
  disable_api_termination = true
  ebs_optimized = true
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
AWS launch templates get created

### Actual Behavior
Failed to create launch templates

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
None

**Comment by bflad** [comment]
Hi @brianpham 👋  Sorry you ran into trouble. 

There was specifically a fix for the EBS handling in the `aws_launch_template` resource (#4321) that was just released yesterday in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018).

Can you try upgrading your provider to see if the newer version works? Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by storeyio** [comment]
Hi,

I can confirm that using version 1.16.0 still results in errors. In my case, using:

`
  block_device_mappings {
    device_name = "/dev/sda1"
    ebs {
      volume_size = 40
      delete_on_termination = true
    }
  }
`
Results in an "iops" value of 0 being written to state and when attempting to launch an instance using the created launch template, it errors because:

> The parameter iops is not supported for gp2 volumes.

**Comment by brianpham** [comment]
Upgrading to 1.16.0 of the AWS provider worked for me.

Thanks!
