### ISSUE TITLE
AWS Longer resource id's (terraform affect)

### ISSUE THREAD

**Issue by agerro** [terraform-providers/terraform-provider-aws#4360]
Might not be an issue, but I was wondering how (and if) there will be any problems with AWS introducing new, longer resource id's? Will that affect what terraform sees as reality in AWS, compared to it's own state file for example?

**Comment by bflad** [comment]
Hi @agerro 👋  Thanks for asking!

We have had the longer IDs enabled in our daily acceptance testing AWS account for awhile now without issue. It only affects new resources and we do not currently perform any specific validation against the ID formatting returned from the AWS APIs. We do not anticipate any changes required within the provider or in Terraform configurations.

Please do reach out if you find something specific though. 😄

**Comment by agerro** [comment]
Thansk for reply.

So, if I have in my state for an instance have "vpc-xxxxxxx" as meta data, but in reality AWS has changed to a longer id ("vpc-xxxxxxxxxxxxxxxxx"), wouldn't that make terraform think that there is a difference between state and reality i.e. re-create the machine? 
Or, if we have data sources for our vpc's that point to a shorter id?

**Comment by bflad** [comment]
Amazon will not update existing IDs. The change only applies to new resources.

https://aws.amazon.com/blogs/compute/longer-resource-ids-in-2018-for-amazon-ec2-amazon-ebs-and-amazon-vpc/

> You can continue using the existing eight-character IDs for your existing resources, which won’t change and will continue to be supported. Only new resources will receive the 17-character IDs and only after you opt in to the new format.
