### ISSUE TITLE
Include ability to request headers with ses_identity_notification_topic

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-aws#4376]
[ses_identity_notification_topic](https://www.terraform.io/docs/providers/aws/r/ses_identity_notification_topic.html) does not appear to offer the ability to request headers with notifications.

This functionality is presented in the web console as:

![image](https://user-images.githubusercontent.com/900469/39350656-24fc967c-4a42-11e8-961f-1d2255d0434e.png)

And is available via the AWS cli command [`aws ses set-identity-headers-in-notifications-enabled`](https://docs.aws.amazon.com/cli/latest/reference/ses/set-identity-headers-in-notifications-enabled.html) (unfortunately it's not part of [`set-identity-notification-topic`](https://docs.aws.amazon.com/cli/latest/reference/ses/set-identity-notification-topic.html) which might be why it didn't make it into Terraform!)

Is this possible?

**Comment by bflad** [comment]
Seems like a new attribute called `include_original_headers` on that existing resource would be appropriate to make the second API call. SDK docs: https://docs.aws.amazon.com/sdk-for-go/api/service/ses/#SES.SetIdentityHeadersInNotificationsEnabled

**Comment by daniel-white** [comment]
any updates on this?

**Comment by bflad** [comment]
Support for the new `include_original_headers` argument on the `aws_ses_identity_notification_topic` resource has been merged and will release with version 2.15.0 of the Terraform AWS Provider. Thanks, @vaskevich!
