### ISSUE TITLE
Feature request: RDS log export to Cloudwatch for Aurora

### ISSUE THREAD

**Issue by mfield** [terraform-providers/terraform-provider-aws#4400]
### Affected Resource(s)
- aws_rds_cluster_instance

### References
- #3056 requests the same feature for `aws_db_instance`

From #3056:

AWS just added support to export mysql/mariadb logs directly to cloudwatch logs. It'd be great to be able to configure the entire process end to end in Terraform.

https://aws.amazon.com/about-aws/whats-new/2018/01/now-publish-log-files-from-amazon-rds-for-mysql-and-mariadb-to-amazon-cloudwatch-logs/
https://aws.amazon.com/blogs/database/monitor-amazon-rds-for-mysql-and-mariadb-logs-with-amazon-cloudwatch/
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html#USER_LogAccess.MySQLDB.PublishtoCloudWatchLogs
https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput.SetEnableCloudwatchLogsExports

**Comment by bflad** [comment]
Support for the new `enable_cloudwatch_logs_exports` argument has been merged into master via #4875 and will release with version 1.24.0 of the AWS provider, likely tomorrow.
