### ISSUE TITLE
AWS integration with Swagger does not seem to consider basePath

### ISSUE THREAD

**Issue by arichiardi** [terraform-providers/terraform-provider-aws#4402]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- aws_api_gateway_rest_api

### Terraform Configuration Files
```hcl
resource "aws_api_gateway_rest_api" "rest_api" {
  name        = "${local.full_prefix}-ep-cloud-api"
  description = "${local.api_title}"
  body        = "${data.template_file.swagger_template.rendered}"
}
```

```json
...swagger...
 "basePath": "prod",
 "schemes": [
    "https"
  ],
...
```

### Expected Behavior
In the AWS Api Gateway I see:
```
Auth: NONE
ARN: arn:aws:execute-api:region:accountId:apiId/*/POST/my-endpoint
```

But I think I should see:

`ARN: arn:aws:execute-api:region:accountId:apiId/*/POST/prod/my-endpoint`

where the `prod` is read from the Swagger's `basePath`, according to https://swagger.io/docs/specification/2-0/api-host-and-base-path.

### Actual Behavior
What actually happened?

### Steps to Reproduce
Try a `swagger.json` with `basePath` set.

### Important Factoids
There are workarounds I think, still worth signaling.

**Comment by bflad** [comment]
Hi @arichiardi 👋 Sorry you're running into trouble here. Does Swagger's `basePath` work with the AWS CLI? If not, you might want to open an AWS support case.

**Comment by bflad** [comment]
Correct, we just upload the JSON to the API:

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_rest_api.go#L113-L123

Given this looks like broken functionality of the API Gateway API, I'm going to close this issue for now but do not hesitate to reply back if there's something amiss with the provider handling here.

**Comment by arichiardi** [comment]
Perfect thank you

**Comment by mattetherton** [comment]
I also encountered this issue and was able to find a work around by adding the basePath to each individual path. 

e,g
`    "paths": {
        "/v1/example": {
`

However, according to the AWS CLI it is possible for the basePath to actually have an effect by using a parameter.

`aws apigateway import-rest-api --parameters basepath=prepend --body`

For details: https://forums.aws.amazon.com/thread.jspa?messageID=885830&tstart=0

@bflad would you mind reviewing?
