### ISSUE TITLE
Unable to use `ebs_block_device` attribute of `aws_instance` resource

### ISSUE THREAD

**Issue by joshuaspence** [terraform-providers/terraform-provider-aws#4404]
The documentation for the `aws_instance` resource suggests that the `ebs_block_device` attribute can be used with `ebs_block_device.0.volume_id`:

> For any `root_block_device` and `ebs_block_device` the `volume_id` is exported. e.g. `aws_instance.web.root_block_device.0.volume_id`.

This works fine for `root_block_device`, since it is implemented as `schema.TypeList`, but it doesn't work for `ebs_block_device`, which is implemented as `schema.TypeSet`. As such, the only way to access the volume ID of an EBS blocked device created inline in the `aws_instance` resource is to manually compute the hash (e.g. `aws_instance.test.ebs_block_device.4023988449.volume_id`). Alternatively, a workaround is to use the `aws_ebs_volume` data source, like so:

```
data "aws_ebs_volume" "test" {
  filter {
    name   = "attachment.device"
    values = ["/dev/xvdf"]
  }

  filter {
    name   = "attachment.instance-id"
    values = ["${aws_instance.test.*.id[count.index]}"]
  }

  count = "${var.instance_count}"
}
```

**Comment by llibicpep** [comment]
Got into the same issue
