### ISSUE TITLE
aws_iam_user_login_profile does not taint/recreate properly

### ISSUE THREAD

**Issue by sfdc-jd** [terraform-providers/terraform-provider-aws#4412]
### Terraform Version

Terraform v0.11.7
+ provider.aws v1.14.1

### Affected Resource(s)
- aws_iam_user_login_profile

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_iam_user" "main" {
  name          = "${var.username}"
  path          = "/staff/${var.memberof}/"
  force_destroy = true
}

resource "aws_iam_user_login_profile" "main" {
  user                    = "${aws_iam_user.main.name}"
  password_reset_required = true
  pgp_key                 = "${var.pgp_key}"
}

resource "aws_iam_user_policy_attachment" "minimum" {
  user       = "${aws_iam_user.main.name}"
  policy_arn = "${var.base_policy_arn}"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
When the user resource and login profile is tainted or completely deleted, the login profile should be recreated.

### Actual Behavior
If the login profile is deleted, it is not recreated at all. If it is tainted, it is not re-created, but left in place.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
We are running in EC2 Classic, but this is an IAM resource.

**Comment by bflad** [comment]
Hi @sfdc-jd 👋 Sorry you ran into this unexpected behavior. I believe this issue is very similar (if not a duplicate) to #3856. To consolidate efforts and discussions, I'm going to close this issue in preference of the earlier one. Thanks for reporting this!
