### ISSUE TITLE
Promotion of db_instance read replica

### ISSUE THREAD

**Issue by cfromm1911** [terraform-providers/terraform-provider-aws#4419]
Trying to work with promoting read replicas to standalone.  I'm having two issues that seem like bugs.

First, the read replica has a backup_retention_period overrided to 0, even when a backup_retention_period > 0 is provided. This makes sense as a read replica isn't backed up.  However,  if I attempt to promote a read replica, I would remove the source_db_arn and supply a backup_retention_period.  Doing so prompts an error:

"DB Backups not supported on a read replica for engine postgres"

This is, obviously, a weakness inherited from the AWS API, as the instance cannot take a backup_retention_period until its completely promoted.   This forces me to promote in two applys.  First, remove the source_db_arn and, then second apply to set a proper backup.  My point is that the provider manages the opposite condition.  I believe the provider should handle the two step process.  This 2 step is compounded because the step to set a proper backup cannot be done immediately, as the instance is not in an available state, because its promoting.

Second issue is on the previous leader/master/primary object.  If I try to assign it a source_db_arn, I get the error "cannot elect new source database for replication.  I don't understand the call for this error.  The object should now be tainted and replaced with a new instance that is a read replica.  As a workaround, I am manually tainting before my apply, but I believe the provider should handle.

Chris

**Comment by cfromm1911** [comment]
Do not agree that this is an enhancement.  Promotion of a read-replica should be as simple as removing the source_db_arn from previous replica and adding source_db_arn to the previous primary.  Here's what I have to do:

```
mkdir replica
cp -r !(replica) replica/
cd replica
terraform init -input=false -backend-config="key=${asv}/${dbName}/${env}/${primaryRegion}/terraform.tfstate" -backend-config="bucket=${configBucket}" -get-plugins=false
#1st Apply on Replica to remove ARN from Previous Replica
terraform apply -input=false -auto-approve -var-file=tfvars.json -var "region=${primaryRegion}" -var 'backup_period="{${env.toLowerCase()}=0}"'
#Switch to Primary
cd ..
terraform init -input=false -backend-config="key=${asv}/${dbName}/${env}/${alternateRegion}/terraform.tfstate" -backend-config="bucket=${configBucket}" -get-plugins=false
#Destroy Primary.  This shouldnt be required.
terraform destroy -input=false -force -var-file=tfvars.json -var "region=${alternateRegion}"
#Switch back to replica
cd replica
# 2nd Apply to set appropriate backup windows
terraform apply -input=false -auto-approve -var-file=tfvars.json -var "region=${primaryRegion}"
arn=\$(terraform output ${primaryRegion}_arn)
#Switch to primary 
cd ..
# Apply to create a new replica
terraform apply -input=false -auto-approve -var-file=tfvars.json -var "region=${alternateRegion}" -var "primary_arn=\$arn" -var 'backup_period="{${env.toLowerCase()}=0}"'
```
It would be much easier to use Amazon API myself.  I think that's what Terraform is designed to avoid.

**Comment by nywilken** [comment]
Hi @cfromm1911 thanks for opening up this issue in order to help us best track it I am going to close it and link to it from the related issue #6749. Any additional comments or feedback should be added to the referenced issue.
