### ISSUE TITLE
Add ability to register, and manage registrations of, domains through Route 53

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-aws#4435]
I would love to be able to manage registration of domains through Terraform. Initial resource creation would mean registration, and then ongoing management could include contacts, settings like autorenew and domain locking, and of course nameserver delegation (this last part has an existing issue at https://github.com/terraform-providers/terraform-provider-aws/issues/88).

The relevant Go SDK documentation is here:
https://docs.aws.amazon.com/sdk-for-go/api/service/route53domains/

_I thought this would have been requested already; I've had a good search and couldn't find it. Please accept my apologies if I am creating duplication!_

**Comment by bflad** [comment]
Hi @tdmalone 👋  I have updated the title and labels for #88. Thanks for pointing that issue out when creating this one. Let's consolidate this discussion and effort to the earlier issue that already has some followers. 

I definitely could have used this level of domain management in my previous role!

Unfortunately the testing is going to be a pain with this service (real public domains == $$) and will likely require usage of the [`route53domainsiface` SDK package](https://docs.aws.amazon.com/sdk-for-go/api/service/route53domains/route53domainsiface/), which is something we don't do anywhere else in the project at the moment.
