### ISSUE TITLE
terraform should force new resource when updating security groups of EMR

### ISSUE THREAD

**Issue by pradeepbhadani** [terraform-providers/terraform-provider-aws#4451]
Hi there,

AWS Console does not support adding/removing Security Groups on the fly. Looks like Security Groups can be added/removed when creating EMR. Refer: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-additional-sec-groups.html

Current AWS provider run `terraform plan` and `terraform apply` without fail, when I try to increase the number of Security Group from 1 to 2 in `additional_master_security_groups`. But If I check the `Additional Security Group` for an EMR in AWS console, it will still have only 1 security group (which was added during EMR cluster creation).
Now, If re-run `terraform plan` it will still show something like
```
 ~ aws_emr_cluster.emr_test
      ec2_attributes.additional_master_security_groups:                   "sg-234" => "sg-234,sg-567"
```
 
### Terraform Version
terraform v 0.11.7

### Affected Resource(s)
- aws_emr_cluster

### Terraform Configuration Files

Create EMR cluster with following:
```hcl
resource "aws_emr_cluster" "test_emr" {
  name          = "test-emr"
  release_label = "emr-5.13.0"
  applications  = ["Hadoop", "Hive", "HCatalog"]
  service_role  = "${var.service_role}"

  ec2_attributes {
    key_name                          = "${var.key_name}"
    subnet_id                         = "${var.subnet_id}"
    emr_managed_master_security_group = "${var.emr_managed_master_security_group}"
    additional_master_security_groups = "${var.add_sg1}"
    emr_managed_slave_security_group  = "${var.emr_managed_slave_security_group}"
    additional_slave_security_groups  = "${var.add_sg1}"
    service_access_security_group     = "${var.service_access_security_group}"
    instance_profile                  = "${var.instance_profile}"
  }

  instance_group {
    instance_role  = "MASTER"
    instance_count = 1
    instance_type  = "${var.instance-type}"
    name           = "Master instance group"

    ebs_config {
      iops                 = "${var.ebs-iops}"
      size                 = "${var.ebs-size}"
      type                 = "io1"
      volumes_per_instance = "1"
    }
  }

  lifecycle {
    create_before_destroy = "true"
  }
}
```

Update `additional_master_security_groups`
```hcl

resource "aws_emr_cluster" "test_emr" {
  name          = "test-emr"
  release_label = "emr-5.13.0"
  applications  = ["Hadoop", "Hive", "HCatalog"]
  service_role  = "${var.service_role}"

  ec2_attributes {
    key_name                          = "${var.key_name}"
    subnet_id                         = "${var.subnet_id}"
    emr_managed_master_security_group = "${var.emr_managed_master_security_group}"
    additional_master_security_groups = "${var.add_sg1},${var.add_sg2}"
    emr_managed_slave_security_group  = "${var.emr_managed_slave_security_group}"
    additional_slave_security_groups  = "${var.add_sg1}"
    service_access_security_group     = "${var.service_access_security_group}"
    instance_profile                  = "${var.instance_profile}"
  }

  instance_group {
    instance_role  = "MASTER"
    instance_count = 1
    instance_type  = "${var.instance-type}"
    name           = "Master instance group"

    ebs_config {
      iops                 = "${var.ebs-iops}"
      size                 = "${var.ebs-size}"
      type                 = "io1"
      volumes_per_instance = "1"
    }
  }

  lifecycle {
    create_before_destroy = "true"
  }

}
```

### Expected Behavior
Either terraform should fail with complain that Security Groups cannot be added or removed on the fly or force a new EMR cluster

### Actual Behavior
Terraform plan and apply do not fail or add a Security Group to EMR cluster

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with a first code snippet (having one additional master security group)
2. update code to have 2 additional master security group
3. Re-run `terraform apply`, this won't change the security groups on EMR cluster.
4. Do `terraform taint && terraform apply` to recreate cluster, this will add second additional master security group.

NOTE: terraform should force new EMR cluster if  values of  `emr_managed_master_security_group`, `additional_slave_security_groups`, `emr_managed_slave_security_group`, `additional_slave_security_groups` and `service_access_security_group` change as EMR cannot update security group on the fly.

Thanks,
Pradeep

**Comment by saravanan30erd** [comment]
@pradeepbhadani are you still facing the issue with latest version?

**Comment by pradeepbhadani** [comment]
@saravanan30erd  I faced this issue with `terraform 0.11.7` which is latest version as of now as per https://www.terraform.io/downloads.html
