### ISSUE TITLE
aws_secretsmanager_secret recreate

### ISSUE THREAD

**Issue by becrsh** [terraform-providers/terraform-provider-aws#4467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

provider.aws v1.17.0

### Affected Resource(s)

* aws_secretsmanager_secret

### Terraform Configuration Files

```hcl
resource "aws_secretsmanager_secret" "mongo_root" {
  name        = "${local.common_tags["Project"]}/MongoDB_root_Credential"
  description = "Credential for Admin User for MongoDB"

  tags = "${local.common_tags}"

}
```
### Output

* aws_secretsmanager_secret.mongo_root: error creating Secrets Manager Secret: ResourceExistsException: The operation failed because the secret CapeCloud/MongoDB_root_Credential already exists.
	status code: 400, request id: 9fba0380-51d2-11e8-9d5d-25c00ab77b23

### Expected Behavior

After a destroy and apply the secret should be recreated

### Actual Behavior

Error is given that the secret already exists

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. `terraform apply`

### Important Factoids

In the documentation it is stated that secrets are not immediately deleted. Perhaps adding a name_prefix to the resource could solve this issue? See: https://docs.aws.amazon.com/secretsmanager/latest/userguide/manage_delete-restore-secret.html

**Comment by bflad** [comment]
Pull request submitted with support of the new `ForceDeleteWithoutRecovery` parameter for `DeleteSecret`: #5583

**Comment by bflad** [comment]
This has been released in [version 1.33.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1330-august-22-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by garyp** [comment]
Can you please add `name_prefix` support to `aws_secretsmanager_secret` as well? For some use cases we want the extra protection that `recovery_window_in_days > 0` provides, so we don't accidentally blow away an important secret. In those cases it'd be helpful to use `name_prefix` to still allow a new version of the secret to be deleted before the old version has expired.

**Comment by bflad** [comment]
Hi @garyp 👋  Great idea -- I would suggest opening a new feature request instead of commenting on a closed one so it can properly accounted for and potentially implemented. 👍

**Comment by garyp** [comment]
@bflad Yes good point :) Created https://github.com/terraform-providers/terraform-provider-aws/issues/6054.
