### ISSUE TITLE
Documentation for ECS service ordered_placement_strategy is confusing

### ISSUE THREAD

**Issue by austinbutler** [terraform-providers/terraform-provider-aws#4474]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
                                                                                                                                                                    
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.aws v1.17.0
+ provider.mysql v1.1.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_ecs_service

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/4390

### Problem

The documentation says `placement_strategy` is deprecated, so use `ordered_placement_strategy` instead. But then in `ordered_placement_strategy` it says "The maximum number of placement_strategy blocks is 5."

I'm assuming you shouldn't use any `placement_strategy` blocks since it's deprecated. But then I wonder how to define multiple placement strategy rules with the new `ordered_placement_strategy`. Do I make multiple blocks `ordered_placement_strategy` or do I put multiple type, field pairs into the one `ordered_placement_strategy` block? I'm sure I will figure it out via trial and error, but it definitely feels like the documentation is wrong.

**Comment by Puneeth-n** [comment]
you can pass it like:

```hcl
ordered_placement_strategy = [
  {
    "type"  = "spread"
    "field" = "attribute:ecs.availability-zone"
  },
  {
    "field" = "memory"
    "type"  = "binpack"
  },
]
```

**Comment by austinbutler** [comment]
Funny enough since opening this, I tried it like this:

```tf
  ordered_placement_strategy {
    type  = "spread"
    field = "attribute:ecs.availability-zone"
  }

  ordered_placement_strategy {
    type  = "spread"
    field = "instanceId"
  }
```

And it seems to have worked: "Strategy spread(attribute:ecs.availability-zone), spread(instanceId)" shows in the console, which I think is right?

**Comment by Puneeth-n** [comment]
@austinbutler They are both right :) It's just a matter of preference :)

**Comment by bflad** [comment]
Fix for the documentation can be found here: #4477

**Comment by bflad** [comment]
Sorry you ran into any confusion here. The documentation fix will release tomorrow. As noted above, both HCL syntaxes are correct for using the `ordered_placement_strategy` attribute.

**Comment by austinbutler** [comment]
Thanks for the swift response!
