### ISSUE TITLE
data source aws_ssm_parameter returns string for StringList type.

### ISSUE THREAD

**Issue by mshenhera** [terraform-providers/terraform-provider-aws#4499]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 0.11.7

provider.aws v1.13.0

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

```hcl
resource "aws_ssm_parameter" "my_subnets" {
  name      = "/my/my_subnets"
  type      = "StringList"
  overwrite = true
  value     = "1.1.1.1,2.2.2.2"
}

data "aws_ssm_parameter" "my_subnets" {
  name = "/my/my_subnets"
}

output "subnets_string" {
 value = "${data.aws_ssm_parameter.my_subnets.value}"
}

output "subnets_list" {
  value = "${split(",", data.aws_ssm_parameter.private_subnets.value)}"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

data source aws_ssm_parameter returns list for StringList type.

### Actual Behavior

data source aws_ssm_parameter returns string for StringList type.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by bflad** [comment]
The data source is currently following the behavior of the SSM API to return a string value, regardless of parameter type: https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#Parameter

Terraform's schema does not support multiple types for the same attribute, so to support this a separate attribute (`value_list`?) would have to be optionally created when the parameter type is `StringList`. The operator would then need to know when to use the new attribute.

**Comment by saravanan30erd** [comment]
submitted PR: #4969

**Comment by bflad** [comment]
The documentation for the data source will be updated with the release of version 1.25.0 of the AWS provider to include mention of using `split()` to achieve what is necessary when working with `StringList` parameters. 

For full reasoning of only introducing the documentation update instead of code enhancement (like I mentioned above), please see: https://github.com/terraform-providers/terraform-provider-aws/pull/4969#issuecomment-399952934
