### ISSUE TITLE
Documentation contains incorrect type for route53_record's multivalue_answer_routing_policy attribute

### ISSUE THREAD

**Issue by rhenning** [terraform-providers/terraform-provider-aws#4519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_route53_record

### Important Factoids

The documentation for `aws_route53_record` indicates that `multivalue_answer_routing_policy` is a block, but [code and examples indicate that it is a boolean](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_route53_record.go#L224).

### References

* #4520

**Comment by rhenning** [comment]
Here's a PR for fixing the docs: #4520

**Comment by bflad** [comment]
The documentation update will be released with v1.19.0 of the AWS provider, likely middle of next week. Thanks for finding and fixing this!

**Comment by rhenning** [comment]
No problem @bflad. Thanks to Hashicorp and Terraform for changing the way we think about infrastructure.
