### ISSUE TITLE
ECS Container Definition Invalid Container name

### ISSUE THREAD

**Issue by machine-dxc** [terraform-providers/terraform-provider-aws#4528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.18.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_ecs_task_definition
* aws_ecs_service

### Terraform Configuration Files

Task Definition
```
resource "aws_ecs_task_definition" "task" {
  family                = "${var.service_name}"
  container_definitions = "${var.ecs_task_container_definitions}"
  task_role_arn         = "${aws_iam_role.ecs_task.arn}"
  network_mode          = "${var.ecs_task_definition_network_mode}"
}
```

ECS Service
```
resource "aws_ecs_service" "service" { 
  name            = "${var.service_name}"
  cluster         = "${var.ecs_cluster_arn}"
  task_definition = "${aws_ecs_task_definition.task.arn}"
  iam_role = "${aws_iam_role.ecs_service_scheduler.arn}"

  desired_count                      = "${var.desired_number_of_tasks}"
  deployment_maximum_percent         = "${var.deployment_maximum_percent}"
  deployment_minimum_healthy_percent = "${var.deployment_minimum_healthy_percent}"
  health_check_grace_period_seconds  = "${var.health_check_grace_period_seconds}"

  placement_strategy {
    type  = "${var.placement_strategy_type}"
    field = "${var.placement_strategy_field}"
  }

  placement_constraints {
    type       = "${var.placement_constraint_type}"
    expression = "${var.placement_constraint_expression}"
  }

  load_balancer {
    target_group_arn = "${data.template_file.alb_target_group_arn.rendered}"
    container_name   = "${var.alb_container_name}"
    container_port   = "${var.alb_container_port}"
  }

  lifecycle {
    ignore_changes = ["desired_count"]
  }
}
```
Container Definition
client=test
environment=dev
base_image_name = <ACCOUNT_ID>.dkr.ecr.< REGION >.amazonaws.com/< REPO >/< IMAGE >
base_image_tag = latest
```
[
    {
        "name": "${client}-${environment}-Base",
        "image": "${base_image_name}:${base_image_tag}",
        "cpu": 0,
        "memoryReservation": 256,
        "essential": true,
        "portMappings": [
            {"containerPort": 3000, "protocol": "tcp"},
            {"containerPort": 3443, "protocol": "tcp"}
        ],
        "environment": [
            {"name" : "CONFIG", "value" : "/home/omni/config/config.json"}
        ],
        "volumesFrom": [
            {
              "sourceContainer": "${client}-${environment}-Config",
              "readOnly": null
            }
        ]
    },
  ]
```

### Debug Output
https://gist.github.com/machine-dxc/646f7cee28b9cc1dc52fe9a4cc63e5c8

### Expected Behavior
The ecs service should have been successfully created

### Actual Behavior
Cannot deploy due to errors with the container name not matching the require format ^[a-zA-Z0-9\-_]+$. 
My guess is that the '/' is in the name of the image (which is required to find the image)

### Steps to Reproduce

1. `terraform apply`

**Comment by machine-dxc** [comment]
Hi @bflad 

Here is a link to the debug log
https://gist.github.com/machine-dxc/b749f23139b5579ea96fdacc600f14c9

I am using a seperate module for just the container definition and in the output returns a template file rendered.

Would this cause any issue?

Thanks

**Comment by bflad** [comment]
I believe in your `aws_ecs_service` resource, the `load_balancer` `container_name` should be something like `${client}-${environment}-Base`, not `ContainerName: "1234567890.dkr.ecr.< REGION >.amazonaws.com/< REPO >/< IMAGE >",`

**Comment by machine-dxc** [comment]
Hi @bflad 

THANK YOU!!!

I would like to suggest improved error logging for this. I had no idea that it was the load balancer that was causing the issue.
