### ISSUE TITLE
Support pagination for data source aws_autoscaling_groups with filters

### ISSUE THREAD

**Issue by yurygoncharuk** [terraform-providers/terraform-provider-aws#4531]
Hi there,

I have a lot of autoscaling groups(ASG) in my account. When I try to get a list of these ASGs I get only first 50 groups.
I created the [issue](https://github.com/terraform-providers/terraform-provider-aws/issues/4422) for it and guys released the fix. The fix works well until you began to use any filter. In a case with filter I get only 50 ASG again

Terraform v0.11.7
Provider.aws: version = 1.18

Thank you!

**Comment by bflad** [comment]
Bugfix PR submitted: #4535

**Comment by saravanan30erd** [comment]
#4536

**Comment by bflad** [comment]
Andddd the fix for the filtering is in as well. Sorry for the trouble before! This part will release with v1.19.0 of the AWS provider later this week.

**Comment by bflad** [comment]
This has been released in [version 1.19.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1190-may-16-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
