### ISSUE TITLE
api_gateway_method authorization_scopes

### ISSUE THREAD

**Issue by tomjanne** [terraform-providers/terraform-provider-aws#4532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It shall be possible to set "authorization_scopes" inside "api_gateway_method" when "authorization" is set to "COGNITO_USER_POOLS"

### New or Affected Resource(s)

* aws_api_gateway_method

### References

* #0000

**Comment by bflad** [comment]
The new `authorization_scopes` argument in the `aws_api_gateway_method` resource will be released with v1.22.0 of the AWS provider later this week 🎉

**Comment by bflad** [comment]
This has been released in [version 1.22.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1220-june-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
