### ISSUE TITLE
sns topic subscription invalid or unknown key: filter policy

### ISSUE THREAD

**Issue by A114397** [terraform-providers/terraform-provider-aws#4538]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

I am currently running **v0.9.11**; *updating the code-base to work with > **v0.11** is a work in progress...*

### Affected Resource(s)

* aws_sns_topic_subscription

### Terraform Configuration Files

```hcl
resource "aws_sns_topic_subscription" "sns-topic" {
  topic_arn = "arn:aws:sns:${var.region}:${var.account_number}:${var.sns_topic_name}"
  protocol  = "sqs"
  endpoint  = "${aws_sqs_queue.sqs-queue.arn}"

  filter_policy = <<EOF
  {
    "key": [{"prefix":"${var.prefix_filter}"}]
  }
  EOF
}
```

### Terraform Plan

```
1 error(s) occurred:

* module.sns_asg.module.sqs_queue.aws_sns_topic_subscription.sns-topic: : invalid or unknown key: filter_policy
```

### Expected Behavior

- according the to [docs](https://www.terraform.io/docs/providers/aws/r/sns_topic_subscription.html#filter_policy) this should deploy an sns topic subscription with a filter policy
- I'm at a loss for why this error occurs

### Actual Behavior
- Receive an error message of `invalid or unknown key: filter_policy`
- I can't find any documentation around this error
- Removing the filter policy from the `sns_topic_subscription` code plans and applies as intended

### References

I've checked [here](https://github.com/terraform-providers/terraform-provider-aws/issues/2916) and the associated links for some help understanding the problem.  I've checked my provider; it includes the updates referenced.

**Comment by edward-agarwala** [comment]
👍

**Comment by bflad** [comment]
Terraform 0.10 split providers like AWS, Google, etc. away from the core code and versioning, [announcement here](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10). Using the `filter_policy` functionality will require upgrading to at least 0.10+ of Terraform core along with at least [version 1.9.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading the provider.
