### ISSUE TITLE
The documentation for cloudfront_origin_access_identity is referencing a module that doesn't exist.

### ISSUE THREAD

**Issue by kitsunde** [terraform-providers/terraform-provider-aws#4541]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue

The documentation seem to be referencing the custom output of a module `${module.names.s3_endpoint_arn_base`. Presumably it should be the s3 buckets ARN instead.

### References

* https://www.terraform.io/docs/providers/aws/r/cloudfront_origin_access_identity.html

**Comment by bflad** [comment]
Documentation update pull request submitted: #4578
