### ISSUE TITLE
🚀 Feature Request: Make the PGP key in aws_iam_user_login_profile optional

### ISSUE THREAD

**Issue by glenjamin** [terraform-providers/terraform-provider-aws#4564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The PGP password encryption functionality forces me to interact with keys and extra encryption steps, while my state file also contains lots of other secrets which are just as sensitive without these additional steps.

In our case, we're only using this to set the initial user passwords, which are flagged for immediate change - so it's not important to us to keep them encrypted in the state file anyway. In practice we immediately decrypt the value and send it over.

This also creates some churn when different people use the same terraform workspace, as they all need to provide their own PGP key, which in turn causes each resource to be modified. It looks like the code has no `Update` handler, so I presume this means that the password remains unreadable until the original person reappears with the PGP key.

### New or Affected Resource(s)

* aws_iam_user_login_profile

### Potential Terraform Configuration

```hcl
# n/a
```

### References

* If #4412 is fixed then the PGP key changes could be problematic if it forces a new password unexpectedly.

**Comment by zytek** [comment]
In contrast, `pgp_key` in `aws_iam_access_key` **is** optional. This should be consistent.  I would opt for making in also optional in `aws_iam_user_login_profile`
