### ISSUE TITLE
Requesting: aws_redshift_cluster.hostname

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-aws#4566]
https://www.terraform.io/docs/providers/aws/r/redshift_cluster.html

aws_redshift_cluster has an `endpoint` member, but no `hostname` member. So when just the hostname (without the port) is required as a terraform reference, we have to get `endpoint` and strip the port which is super ugly.

**Comment by bflad** [comment]
A `dns_name` attribute will be available on the `aws_redshift_cluster` resource in v1.21.0 of the AWS provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
