### ISSUE TITLE
Imported aws_rds_instance don't update due to DBInstanceIdentifier wrong value

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [terraform-providers/terraform-provider-aws#4607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform version: 0.11.7
+ provider.aws v1.19.0

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/tomaszkrzyzanowski/0ee7adeb4f1add2dd410a278b44e9ef7

### Panic Output

```Error: Error applying plan:

1 error(s) occurred:

* module.test.aws_db_instance.rds_instance: 1 error(s) occurred:

* aws_db_instance.rds_instance: Error modifying DB Instance arn:aws:rds:eu-central-1:ACCOUNT_ID:db:stage: InvalidParameterValue: The parameter DBInstanceIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
        status code: 400, request id: <REQUEST_ID>

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

Terraform perform update on db instance correctly

### Actual Behavior

Terraform fails when try to modify aws_db_instance - terraform value - `id` from state for `aws_db_instance` variable `DBInstanceIdentifier` but due to import issue it contains `arn` instead of `identifier`

Eg:
1. Example values from build from scratch db instance using TF
```
"id": "foobar",
"identifier": "foobar"
```

2. Example values from imported rds_instance:
```
"id": "arn:aws:rds:eu-central-1:ACCOUNT_ID:db:foobar",
"identifier": "foobar"
```

### Steps to Reproduce

1. Create DB instance from AWS Web Console
2. Import DB to terraform
3. Try to modify instance - eg. hit to newer version

**Comment by ewbankkit** [comment]
Closing as duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/997.
