### ISSUE TITLE
Provider cannot assume role in ap-northeast-2

### ISSUE THREAD

**Issue by visit1985** [terraform-providers/terraform-provider-aws#4619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.19.0

### Affected Resource(s)

* provider.aws

### Terraform Configuration Files

```hcl
provider "aws" {

  # when changed to a different region this config works
  region = "ap-northeast-2"

  profile = "lps"

  assume_role {
    # belongs to a different account than the IAM user used in the profile
    role_arn = "arn:aws:iam::999999999999:role/sts-admin"
  }

  version = "~> 1.0"
}

resource "aws_cloudwatch_log_group" "test" {
  name = "test"
}
```

### Debug Output

https://gist.github.com/visit1985/712d56046defded7b32d88026a24449f

### Expected Behavior

The given configuration should work in all public regions, but it doesn't work in ap-northeast-2.

### Actual Behavior

```
Error: Error running plan: 1 error(s) occurred:

* provider.aws: The role "arn:aws:iam::999999999999:role/sts-admin" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

The role assumed in the provider belongs to a different account than the IAM user used in the profile.
If the region in line 3 is changed to any other public region, the configuration can be planned and applied without issues.

**Comment by bflad** [comment]
Hi @visit1985 👋  I do not believe we do anything region specific in the code with assuming roles.

https://github.com/terraform-providers/terraform-provider-aws/blob/fb8dc32d1ffca73d79e4bcac99d8afa6e20c59db/aws/auth_helpers.go#L184-L243

Have you double checked that STS is not disabled in that region for that account? [More information](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html) In the console > IAM > Account Settings > Security Token Service regions

Are you able to assume the cross-account role in the region via the AWS CLI?

**Comment by visit1985** [comment]
Hi @bflad, I was able to reproduce the issue via AWS CLI.

```
$ aws sts assume-role --profile lps --region ap-northeast-2 --role-arn arn:aws:iam::999999999999:role/sts-admin --role-session-name test

An error occurred (RegionDisabledException) when calling the AssumeRole operation: STS is not activated in this region for account:999999999999. Your account administrator can activate STS in this region using the IAM Console.
```

The strange thing is, we have all the STS endpoints disabled except Virginia and it still works for all other regions, except ap-northeast-2. :confused:

I'll open a support request at AWS. Thanks!

**Comment by Zordrak** [comment]
This is because ap-northeast-2 (and 3) are for some reason not using the global sts endpoint, and something you're doing (maybe a region denying SCP?) is preventing use of a regional STS endpoint.

See this:
```
# for region in $(aws ec2 describe-regions --region eu-west-1 | jq -r '.Regions[] | .RegionName'); do aws sts get-caller-identity --region ${region} --debug 2>&1 | \grep 'new HTTPS connection' | \grep -oe 'sts.*amazonaws.com' | awk -v r="${region}" '{printf("%-15s: %s\n", r, $0)}'; done
```

```
eu-north-1     : sts.amazonaws.com
ap-south-1     : sts.amazonaws.com
eu-west-3      : sts.amazonaws.com
eu-west-2      : sts.amazonaws.com
eu-west-1      : sts.amazonaws.com
ap-northeast-2 : sts.ap-northeast-2.amazonaws.com
ap-northeast-1 : sts.amazonaws.com
sa-east-1      : sts.amazonaws.com
ca-central-1   : sts.amazonaws.com
ap-southeast-1 : sts.amazonaws.com
ap-southeast-2 : sts.amazonaws.com
eu-central-1   : sts.amazonaws.com
us-east-1      : sts.amazonaws.com
us-east-2      : sts.amazonaws.com
us-west-1      : sts.amazonaws.com
us-west-2      : sts.amazonaws.com
```
