### ISSUE TITLE
CodeBuild cache location doesn't honor aws resource dependency correctly

### ISSUE THREAD

**Issue by salvianreynaldi** [terraform-providers/terraform-provider-aws#4639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.20.0
+ provider.null v1.0.0
+ provider.random v1.2.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_codebuild_project

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ap-southeast-1"
}

locals {
  service_name   = "my_service"
  product_domain = "my_team"
}

module "my_service_release_build" {
  source         = "github.com/salvianreynaldi/terraform-aws-codebuild-traveloka-backend-release.git?ref=6bdb91e3ece3fc8e1a36b9ef6b225ef538c361ae"
  service_name   = "${local.service_name}"
  product_domain = "${local.product_domain}"
  description    = "${local.product_domain}'s ${local.service_name} release builds"

  build_commands = [
    "./gradlew :my-service:uploadDistTar",
  ]

  github_repository_url = "https://github.com/traveloka/my-service-repository.git"
}


# terraform-aws-codebuild-traveloka-backend-release.git?ref=6bdb91e3ece3fc8e1a36b9ef6b225ef538c361ae
...
resource "aws_codebuild_project" "this" {
  name          = "${local.name}"
  description   = "${var.description}"
  service_role  = "${module.codebuild_role.role_name}"
  build_timeout = "${var.timeout}"

  artifacts {
    type = "NO_ARTIFACTS"
  }

  cache {
    type     = "S3"
    location = "${aws_s3_bucket.cache.id}/${local.name}"
  }

  environment {
    compute_type = "${var.compute_type}"
    image        = "aws/codebuild/java:openjdk-8"
    type         = "LINUX_CONTAINER"
  }

  source {
    type      = "GITHUB"
    location  = "${var.github_repository_url}"
    buildspec = "${data.template_file.buildspec.rendered}"
  }

  tags {
    "Service"       = "${var.service_name}"
    "ProductDomain" = "${var.product_domain}"
    "Environment"   = "management"
  }
}
...
```

### Expected Behavior

The plan step completed successfully
```
Plan: X to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

### Actual Behavior

this error appears:
```
Error: Error running plan: 1 error(s) occurred:

* module.my_service_release_build.aws_codebuild_project.this: 1 error(s) occurred:

* module.my_service_release_build.aws_codebuild_project.this: cache location is required when cache type is "S3"
```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

- the steps above succeed if we change `"${aws_s3_bucket.cache.id}/${local.name}"` to `"somehardcodedstring/${local.name}"` in [terraform-aws-codebuild-traveloka-backend-release](https://github.com/salvianreynaldi/terraform-aws-codebuild-traveloka-backend-release/blob/6bdb91e3ece3fc8e1a36b9ef6b225ef538c361ae/main.tf#L13) module
- changing to `"${module.cache_bucket_name.name}/${local.name}"` doesn't fix the issue

**Comment by jrobison-sb** [comment]
I got bit by this one too. As suggested by the title, it's a problem with figuring out the resource dependencies. If you build your S3 bucket and apply, then subsequently modify CodeBuild to use that bucket for caching in a separate `apply`, then `"${aws_s3_bucket.cache.id}"` will work. YMMV if a two-step apply is more or less desirable than hardcoding a string as the OP mentioned.

Terraform v0.11.8
+ provider.aws v1.33.0

**Comment by KadenLNelson** [comment]
specifying `bucket` instead of `bucket_prefix` seems to fix this issue for me

```
resource "aws_s3_bucket" "codebuild" {
  bucket = "${local.identifier}-codebuild-bucket"
```

**Comment by bflad** [comment]
Hi folks 👋 We're not able to find the referenced modules in GitHub, so we're not able to reproduce this issue with the example configuration. Given the version of Terraform and the resource logic is very outdated in the original post here, please try this in more recent versions of Terraform and the Terraform AWS Provider.

If you are still encountering issues with Terraform 0.12 and later, please feel free to open a new [Bug Report](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) following the issue template for further triage. Thanks!
