### ISSUE TITLE
Backtrack is not enabled aurora

### ISSUE THREAD

**Issue by cemo** [terraform-providers/terraform-provider-aws#4640]
I have tried to create a cluster but have an error about backtrack parameter.

```
* aws_rds_cluster.aurora_cluster-main-v1: error creating RDS cluster: InvalidParameterValue: Backtrack is not enabled for the aurora-mysql engine.
```

**Comment by bflad** [comment]
Ah, I might have accidentally included `aurora-mysql` in the resource documentation for this! https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#backtrack_window

The [RDS documentation for backtrack states](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/AuroraMySQL.Managing.Backtrack.html):
> Backtracking is only supported for Aurora MySQL 5.6. It is not supported for Aurora MySQL 5.7. Because of this limitation, you can't restore a snapshot of an Aurora MySQL 5.6 DB cluster with Backtrack enabled to Aurora MySQL 5.7, and you can't perform point-in-time recovery on an Aurora MySQL 5.6 DB cluster with Backtrack enabled to restore the DB cluster to Aurora MySQL 5.7.

Aurora MySQL 5.6 is `aurora` and Aurora MySQL 5.7 is `aurora-mysql`.

I'll submit a pull request to fix our documentation right now.
