### ISSUE TITLE
/29 CIDR Not Working Correctly In Security Group Rules

### ISSUE THREAD

**Issue by phatman168** [terraform-providers/terraform-provider-aws#4641]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.19.0

### Affected Resource(s)

aws_security_group_rule

### Terraform Configuration Files

```hcl

resource "aws_security_group_rule" "office_loc1_inbound_sgr" {
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["92.68.201.91/29"]
  security_group_id = "${data.aws_security_group.bastion_securitygroup_id.id}"
  description       = "my test description"
}

```

### Expected Behavior

Allow /29 in security group rule creation

### Actual Behavior

Error: aws_security_group_rule.office_loc1_inbound_sgr: "cidr_blocks.0" must contain a valid network CIDR, got "92.68.201.91/29"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When changing cidr to a standard network block (ending .0), it works: 92.68.201.0/29

Also when creating via aws api, it works so no problem with the cidr:

`aws ec2 authorize-security-group-ingress --group-id ${SGID} --ip-permissions '[{"IpProtocol": "tcp", "FromPort": 22, "ToPort": 22, "IpRanges": [{"CidrIp": "92.68.201.91/29", "Description": "my test description"}]}]'`

### References

* #0000

**Comment by drsolaris** [comment]
That CIDR is not valid. Try here: https://ipduh.com/ip/cidr/

The closest valid CIDR is 92.68.201.88/29

**Comment by phatman168** [comment]
Thanks drsolaris, I'll double check all the ranges i have. Much appreciated.

**Comment by phatman168** [comment]
Thanks again drsolaris for your quick response, changing the cidr to the correct range identified by https://ipduh.com/ip/cidr/ works perfectly fine, we also double checked the IP addresses provided and there was just some miscommunication. Many thanks again.
