### ISSUE TITLE
Support for cloudwatch_event_rule_pattern

### ISSUE THREAD

**Issue by benfortuna** [terraform-providers/terraform-provider-aws#4652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is no support for variable interpolation in cloudwatch event rule patterns, which means resource references must be hard-coded in the pattern. e.g

```
resource "aws_cloudwatch_event_rule" "my_cw_event_rule" {
  name = "my-cw-event-rule"
  event_pattern = <<EOF
{
  "source": [
    "aws.codecommit"
  ],
  "detail-type": [
    "CodeCommit Repository State Change"
  ],
  "resources": [
    "arn:aws:codecommit:ap-southeast-2:xxxxxxxxx:my-repo"
  ],
  "detail": {
    "event": [
      "referenceCreated",
      "referenceUpdated"
    ],
    "referenceType": [
      "branch"
    ],
    "referenceName": [
      "develop"
    ]
  }
}
EOF
}
```

### New or Affected Resource(s)

It would be useful to have a new resource similar to the `aws_iam_policy_document` specification:

* aws_cloudwatch_event_rule_pattern

### Potential Terraform Configuration

```hcl
data "aws_cloudwatch_event_rule_pattern" "my_cw_event_rule_pattern" {
  "source": ["aws.codecommit"]
  "detail-type": [
    "CodeCommit Repository State Change"
  ],
  "resources": [
    "${aws_codecommit_repository.my-repo.arn}"
  ],
  "detail": {
    "event": [
      "referenceCreated",
      "referenceUpdated"
    ],
    "referenceType": [
      "branch"
    ],
    "referenceName": [
      "develop"
    ]
  }
}

resource "aws_cloudwatch_event_rule" "my_cw_event_rule" {
  name = "my-cw-event-rule"
  event_pattern = "${data.aws_cloudwatch_event_rule_pattern.my_cw_event_rule_pattern.json}"
}
```

### References

None

**Comment by mousedownmike** [comment]
In case anyone else ends up here with the same issue.  You **CAN** get interpolation as long as you're OK with a really long and excessively escaped string.  

Building on the original post, you can do the following:
```hcl
resource "aws_cloudwatch_event_rule" "my_cw_event_rule" {
  name = "my-cw-event-rule"
  event_pattern ="{\"source\":[\"aws.codecommit\"],\"detail-type\":[\"CodeCommit Repository State Change\"],\"resources\":[\"${aws_codecommit_repository.my-repo.arn}\"],\"detail\":{\"event\":[\"referenceCreated\",\"referenceUpdated\"],\"referenceType\":[\"branch\"],\"referenceName\":[\"develop\"]}}"
}
```

I've confirmed that works with the following:
```bash
$ terraform version
Terraform v0.12.7
+ provider.aws v2.25.0
```
Phew!

**Comment by tomelliff** [comment]
Can you not just put the JSON in a heredoc (as suggested in the [documentation for the `aws_cloudwatch_event_rule`](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_rule.html) instead of having all that awkward escaping?

**Comment by mousedownmike** [comment]
Thanks @tomelliff, I didn't realize the heredoc would do interpolation (or even that those blocks were called heredocs!).  Revising the example above with a heredoc pattern gets you:
```hcl

resource "aws_cloudwatch_event_rule" "my_cw_event_rule" {
  name = "my-cw-event-rule"
  event_pattern = <<PATTERN
{
  "source" : [
    "aws.codecommit"],
  "detail-type": [
    "CodeCommit Repository State Change"],
  "resources": [
    "${data.aws_codecommit_repository.my-repo.arn}"],
  "detail": {
    "event" : ["referenceCreated","referenceUpdated"],
    "referenceType":["branch"],
    "referenceName":["develop"]}
}
PATTERN
}
```

**Comment by benfortuna** [comment]
Yes agreed. Not sure if this was possible when I created the issue but can definitely now use interpolation in the original example:

```
resource "aws_cloudwatch_event_rule" "my_cw_event_rule" {
  name = "my-cw-event-rule"
  event_pattern = <<EOF
{
  "source": [
    "aws.codecommit"
  ],
  "detail-type": [
    "CodeCommit Repository State Change"
  ],
  "resources": [
    "${data.aws_codecommit_repository.my-repo.arn}"
  ],
  "detail": {
    "event": [
      "referenceCreated",
      "referenceUpdated"
    ],
    "referenceType": [
      "branch"
    ],
    "referenceName": [
      "develop"
    ]
  }
}
EOF
}
```

**Comment by gdavison** [comment]
Hi @benfortuna, and thank you for the suggestion. One of the features of the data source `aws_iam_policy_document` is that it supplies default values and error checking to the policy document. The event pattern for EventBridge/CloudWatch Events does not need the extra checking, as it is straight JSON.

As suggested by @tomelliff, heredocs support interpolation.

In addition, Terraform 0.12 introduced the [`object` data type](https://www.terraform.io/docs/configuration/types.html#object-) which can be passed to [`jsonencode()`](https://www.terraform.io/docs/configuration/functions/jsonencode.html), e.g.

```terraform
resource "aws_cloudwatch_event_rule" "my_cw_event_rule" {
  name = "my-cw-event-rule"
  event_pattern = jsonencode(
    {
      source      = ["aws.codecommit"],
      detail-type = ["CodeCommit Repository State Change"],
      resources   = [data.aws_codecommit_repository.my-repo.arn],
      detail = {
        event = [
          "referenceCreated",
          "referenceUpdated",
        ],
        referenceType = [
          "branch",
        ],
        referenceName = [
          "develop",
        ],
      }
    }
  )
}
```

Either of these approaches can be used for complex event patterns.

Thanks again for the suggestion.
