### ISSUE TITLE
aws_ecs_service InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.

### ISSUE THREAD

**Issue by mozowski** [terraform-providers/terraform-provider-aws#4657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
aws_ecs_service

### Terraform Configuration Files

```
resource "aws_ecs_service" "ecs" {
  name            = "${var.cluster_name}"
  cluster         = "${aws_ecs_cluster.ecs.id}"
  desired_count   = "${var.service_desired_count}"
  iam_role        = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS"
  task_definition = "${aws_ecs_task_definition.service.arn}"
  deployment_maximum_percent = "${var.service_deployment_maximum_percent}"
  deployment_minimum_healthy_percent = "${var.service_deployment_minimum_healthy_percent}"

  ordered_placement_strategy {
    type  = "binpack"
    field = "cpu"
  }

  load_balancer {
    elb_name = "${var.service_elb_name}"
    target_group_arn = "${aws_lb_target_group.prometheus-lb.arn}"
    container_name   = "${format("prometheus-%s", var.envAbbreviation)}"
    container_port   = "${var.container_port}"
  }

  placement_constraints {
    type       = "memberOf"
    expression = "attribute:ecs.availability-zone in [eu-west-1a, eu-west-1b, eu-west-1c]"
  }
  network_configuration {
    subnets = ["${data.aws_subnet_ids.env_private_subnet_ids.ids}"]
    security_groups = ["${data.aws_security_group.prometheus_sg.name}"]
    assign_public_ip = false
  }
}

resource "aws_iam_service_linked_role" "servicerole" {
  aws_service_name = "ecs.amazonaws.com"
}
```

### Panic Output

`aws_ecs_service.prometheus-server: InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.`

### Expected Behavior

aws_ecs_service accepts service linked role as documented on AWS ecs section
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html

### Actual Behavior

aws_ecs_service iam_role parameter does not recognise servce linked role

**Comment by bflad** [comment]
@mozowski can you please provide the full `aws_ecs_service` configuration and/or debug logs? The extra details are likely relevant here (using or not using `load_balancers`/`service_registries`, on Fargate, etc).

**Comment by mozowski** [comment]
@bflad yes, those are important information. I have updated configuration snippet.

**Comment by bflad** [comment]
For what its worth, this error is coming from the ECS API, not Terraform, so likely points to a misconfiguration or a change in behavior with the ECS service:

```
InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.
```

The [ECS CreateServiceInput SDK documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#CreateServiceInput) states for the `Role` parameter (what we map to under the hood):

```
    // The name or full Amazon Resource Name (ARN) of the IAM role that allows Amazon
    // ECS to make calls to your load balancer on your behalf. This parameter is
    // only permitted if you are using a load balancer with your service and your
    // task definition does not use the awsvpc network mode. If you specify the
    // role parameter, you must also specify a load balancer object with the loadBalancers
    // parameter.
    //
    // If your account has already created the Amazon ECS service-linked role, that
    // role is used by default for your service unless you specify a role here.
    // The service-linked role is required if your task definition uses the awsvpc
    // network mode, in which case you should not specify a role here. For more
    // information, see Using Service-Linked Roles for Amazon ECS (http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html)
    // in the Amazon Elastic Container Service Developer Guide.
    //
    // If your specified role has a path other than /, then you must either specify
    // the full role ARN (this is recommended) or prefix the role name with the
    // path. For example, if a role with the name bar has a path of /foo/ then you
    // would specify /foo/bar as the role name. For more information, see Friendly
    // Names and Paths (http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names)
    // in the IAM User Guide.
    Role *string `locationName:"role" type:"string"`
```

That documentation seems to suggest that you shouldn't include the IAM role in your configuration, even if that is what it maps to under the hood. Can you try just removing that line from the `aws_ecs_service` resource configuration? If that works, we should probably add some additional SDK verbiage into the Terraform documentation for that argument.

**Comment by jun06t** [comment]
I've met the same problem.
As @bflad said I removed the ``iam_role`` from ``aws_ecs_service``.
Then it works!!
BTW, AWS Web console shows the service linked role.

**Comment by bflad** [comment]
Documentation PR submitted: #4673

**Comment by bflad** [comment]
Updated documentation for the `iam_role` argument in the `aws_ecs_service` resource will release with v1.21.0 of the AWS provider sometime later this week.

**Comment by sashanka-kandala** [comment]
I am getting this error when i try to attach a custom iam role.
Trying to create ecs service with alb and provided a custom iam role with ecsservicerolepolicy.
launchtype:ec2
networkmode: bridge

```* aws_ecs_service.ecs: InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.```

**Comment by jdautomate** [comment]
I had the exact same problem:
resource "aws_ecs_service" "vault" {
  name            = "vault"
  cluster         = "vault-consul"
  task_definition = "${aws_ecs_task_definition.vault.arn}"
  desired_count   = 2
  #iam_role        = "${data.aws_iam_role.service_role.arn}"
 
  load_balancer {
    target_group_arn = "${aws_alb_target_group.vault.arn}"
    container_name   = "vault"
    container_port   = 8200
  }

  network_configuration {
    security_groups = ["${aws_security_group.vault-ecs-sg.id}"]
    subnets         = ["${data.aws_subnet.ecs_subnet1.id}", "${data.aws_subnet.ecs_subnet2.id}"]
  }

  launch_type = "FARGATE"
}

You can see that the iam_role parameter is commented out, this fixed the issue.
