### ISSUE TITLE
aws_instance UnauthorizedOperation bug

### ISSUE THREAD

**Issue by kullcrom** [terraform-providers/terraform-provider-aws#4664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.0
aws provider - v1.20.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
# Create OpsMan instance
resource "aws_instance" "opsman_az1" {
    ami = "${var.opsman_ami}"
    availability_zone = "${var.aws_az1}"
    instance_type = "${var.opsman_instance_type}"
    key_name = "${var.aws_key_name}"
    vpc_security_group_ids = ["${aws_security_group.directorSG.id}"]
    subnet_id = "${var.InfraSubnet_az1}"
    private_ip = "${var.opsman_ip_az1}"
    root_block_device {
        volume_size = 100
    }
    tags {
        Name = "${var.prefix}-OpsMan az1"
        "DCIO" = "${var.tags_default_dcio}"
        "BISO" = "${var.tags_default_biso}"
        "Product Owner" = "${var.tags_default_product_owner}"
        "Cost Center" = "${var.tags_default_cost_center}"
        "BrIT Number" = "${var.tags_default_brit_number}"
        "Environment" = "${var.tags_ec2_environment}"
    }
}

resource "aws_route53_record" "opsman_record_set" {
    zone_id = "${var.opsman_zone_id}"
    name = "${var.opsman_domain_or_ip_address}"
    type = "A"
    ttl = "300"
    records = ["${var.opsman_ip_az1}"]
}
```

### Debug Output
https://gist.github.com/kullcrom/280d6c244251b5b1a104c0306a91ffce

### Expected Behavior
It should create the appropriately configured ec2 instance. 

### Actual Behavior
The instance is created; however, Terraform still produces an error causing the build to fail. I have all necessary IAM permissions to perform ec2 instance creation.
```
Error: Error applying plan:

1 error(s) occurred:

* aws_instance.opsman_az1: 1 error(s) occurred:

* aws_instance.opsman_az1: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 7df4fb0d-d87f-46bb-a991-fd58a2b240c0
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @kullcrom 👋 sorry that you ran into trouble here and that the error message was less than helpful for pointing you in the right direction for where this issue is occurring for you.

That error message is coming from the EC2 API, so the EC2 service thinks the credentials you're using within Terraform are missing some form of IAM permissions.

You might want to try running Terraform with [debug logging](https://www.terraform.io/docs/internals/debugging.html) enabled to see if you can't find the exact API call thats generating the error. e.g. `TF_LOG=DEBUG terraform apply`

**Comment by kullcrom** [comment]
Hi @bflad, thanks for the quick response. I will add the debug command. However, I think there may be something else going on here because I have all ec2 (`ec2:*`) permissions for these credentials.

**Comment by kullcrom** [comment]
Hi @bflad, the only errors that I'm seeing in the debug output have to do with security group egress. It says that I am not authorized to perform RevokeSecurityGroupEgress, which is incorrect because, as I said, I have all EC2 permissions. Also, it doesn't show any errors related to `aws_instance.opsman_az1`, which is the only error Terraform provides when `terraform apply` fails.

```
2018-05-25T21:25:34.910Z [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: 2018/05/25 21:25:34 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
2018-05-25T21:25:34.910Z [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: <Response><Errors><Error><Code>InvalidPermission.NotFound</Code><Message>The specified rule does not exist in this security group.</Message></Error></Errors><RequestID>28316199-d627-4cf8-a38a-22f90447967c</RequestID></Response>
2018-05-25T21:25:34.911Z [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: 2018/05/25 21:25:34 [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/RevokeSecurityGroupEgress failed, not retrying, error InvalidPermission.NotFound: The specified rule does not exist in this security group.
2018-05-25T21:25:34.911Z [DEBUG] plugin.terraform-provider-aws_v1.20.0_x4: 	status code: 400, request id: 28316199-d627-4cf8-a38a-22f90447967c
```

**Comment by bflad** [comment]
Since the error messages between the AWS SDK and Terraform are reporting conflicting things, I'm having a hard time discerning what is happening here without seeing the debug log. Can you please create a gist and add that here? It'd also be helpful to see the full `terraform plan` output. If you are worried about any sensitive data, it can be encrypted with the [HashiCorp GPG Key](https://keybase.io/hashicorp).

**Comment by kullcrom** [comment]
Hi @bflad I've included the gist link to the debug logs. It also contains the terraform plan output. Thank you for looking into this.

**Comment by bflad** [comment]
@kullcrom as far as I can tell from the debug log, the EC2 API does not think the provided credentials have `ec2:DescribeInstanceCreditSpecifications` or there is some bug in the EC2 API itself.

```
2018/05/30 15:11:40 [DEBUG] [aws-sdk-go] DEBUG: Response ec2/DescribeInstanceCreditSpecifications Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Connection: close
Transfer-Encoding: chunked
Date: Wed, 30 May 2018 15:11:39 GMT
Server: AmazonEC2


-----------------------------------------------------
2018/05/30 15:11:40 [DEBUG] [aws-sdk-go] <?xml version='1.0' encoding='UTF-8'?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>46002310-0e51-4f21-99ef-100739c97477</RequestID></Response>
2018/05/30 15:11:40 [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/DescribeInstanceCreditSpecifications failed, not retrying, error UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 46002310-0e51-4f21-99ef-100739c97477
2018/05/30 15:11:40 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* aws_instance.opsman_az1: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 46002310-0e51-4f21-99ef-100739c97477
```

I would suggest opening an AWS Support case if you really believe the permissions are correctly there for the credentials.

The `InvalidPermission.NotFound` errors you see in the debug log are related to logic in the `aws_security_group` resource that tries to remove the default egress 0.0.0.0/0 rule as documented in the [`NOTE on Egress rules` part of the `aws_security_group` documentation](https://www.terraform.io/docs/providers/aws/r/security_group.html) and can be ignored.

**Comment by kullcrom** [comment]
Hi @bflad, that was the one! It turns out that my `ec2:*` was replaced by individual permissions and that one was missing. Thanks for all of your help. I really appreciate it!
