### ISSUE TITLE
I cannot create a resource aws_ses_domain_identity

### ISSUE THREAD

**Issue by engharb** [terraform-providers/terraform-provider-aws#4695]
### Terraform Version
```
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.aws v1.15.0
```
### Affected Resource(s)

* aws_ses_domain_identity

### Terraform Configuration Files

```hcl
## Create SES
resource "aws_ses_domain_identity" "ses_abc" {
  domain = "${var.ses_domain}"
}
resource "aws_ses_domain_dkim" "ses_dkim" {
  domain = "${aws_ses_domain_identity.ses_abc.domain}"
}
resource "aws_route53_zone" "ses_main_zone" {
  name = "${var.ses_domain}"
}
resource "aws_route53_record" "dkim_amazone_verification_record" {
  count = 3
  name = "${element(aws_ses_domain_dkim.ses_dkim.dkim_tokens, count.index)}._domainkey.${var.ses_domain}"
  type = "CNAME"
  zone_id = "${aws_route53_zone.ses_main_zone.id}"
  ttl = "600"
  records = ["${element(aws_ses_domain_dkim.ses_dkim.dkim_tokens, count.index)}.dkim.amazonses.com"]
}
```

### Actual Behavior

I want to create my ses_domain and it get the following 
```
aws_ses_domain_identity.ses_abc: Still creating... (10m0s elapsed)
```

I stuck here and no progress. Do you have any idea if I missed something in the configuration?

After one hour I got the following error
```
Error: Error applying plan:

2 error(s) occurred:

* aws_cognito_user_pool.abc: 1 error(s) occurred:

* aws_cognito_user_pool.abc: sms_verification_message cannot be set to nil
* aws_ses_domain_identity.ses_abc: 1 error(s) occurred:

* aws_ses_domain_identity.ses_abc: Error requesting SES domain identity verification: RequestError: send request failed
caused by: Post https://email.eu-central-1.amazonaws.com/: dial tcp: lookup email.eu-central-1.amazonaws.com on 192.168.178.1:53: no such host

```

One more thing is that: how can I define the region of the created ses i.e eu-west-1 in configuration?

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @engharb 👋  Sorry you ran into trouble here -- there's a few things going on.

Most importantly, AWS Simple Email Service (SES) is not supported in the `eu-central-1` region. The documentation for supported regions can be found here: https://docs.aws.amazon.com/general/latest/gr/rande.html#ses_region

I also noticed you're running version 1.15.0 of the AWS provider. In [version 1.18.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1180-may-10-2018) we updated some error handling logic of the provider to more quickly return `no such host` errors, which generally is the case for missing service endpoints. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

> One more thing is that: how can I define the region of the created ses i.e eu-west-1 in configuration?

If you're working with the AWS provider in a single region, you can override the "default" provider region via the `AWS_DEFAULT_REGION` environment variable or this `provider` configuration block:

```hcl
# No alias is defined here, so it configures the "default" provider
# Personally I would also recommend the version argument too :)
provider "aws" {
  region = "eu-west-1"
}
```

Or if you're trying to work with multiple regions, you'll need to create `provider` configuration(s) with `alias` and tell the resources to use that specific provider alias. For example:

```hcl
provider "aws" {
  alias  = "eu-west-1" # This name can be whatever you choose
  region = "eu-west-1"
}

# This resource will use the eu-west-1 region provider
resource "aws_ses_domain_identity" "ses_abc" {
  provider = "aws.eu-west-1"

  domain = "${var.ses_domain}"
}
```

For more information:
* Configuring the AWS provider: https://www.terraform.io/docs/providers/aws/index.html
* Configuring resources to use provider aliases: https://www.terraform.io/docs/configuration/resources.html#provider
