### ISSUE TITLE
Consolidate import_*_test.go files into resource_*_test.go files

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#4705]
Semi-related to #4676 

There are currently over 1000 files in the `aws` package directory. The `import_*_test.go` files, which were originally created to hold resource import tests, are inconsistently used between resources with many new resources/tests simply just implementing the additional import `TestCase`. For now, let's just lift and shift the existing import tests from those `import_*_test.go` files into their equivalent `resource_*_test.go` files.

At some point we may want to consider migrating the "import" tests into just a new `TestCase` in their "regular" test counterparts so we are not continually spinning up twice the infrastructure and time just to test importing a (duplicate) resource.

**Comment by ewbankkit** [comment]
To reduce the number of source files in the `aws` directory we could also consolidate the much smaller number of `*_migrate.go` and `*_migrate_test.go` files.
