### ISSUE TITLE
Add Cognito User Pools support to aws_lb_listener_rule 

### ISSUE THREAD

**Issue by rzfoxify** [terraform-providers/terraform-provider-aws#4711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently AWS released a feature that allows to authenticate users from ALB through Cognito.

### New or Affected Resource(s)

aws_lb_listener_rule

### References

* https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/

**Comment by bflad** [comment]
Just so there's no confusion, we'll treat this issue as complementary to the `aws_lb_listener` request (#4707) and this one can be for `aws_lb_listener_rule` 👍

**Comment by drsolaris** [comment]
Is there any movement on this? Would love to use it.

**Comment by bflad** [comment]
Thanks to @atsushi-ishibashi and @mikael-lindstrom, initial support for Cognito and OIDC authentication in `aws_lb_listener` and `aws_lb_listener_rule` has been merged in and will release with version 1.40.0 of the AWS provider, likely middle of this week. 🎉

**Comment by bflad** [comment]
This has been released in [version 1.40.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1400-october-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
