### ISSUE TITLE
Support Neptune

### ISSUE THREAD

**Issue by atsushi-ishibashi** [terraform-providers/terraform-provider-aws#4713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_neptune_cluster
* aws_neptune_cluster_instance
* aws_neptune_subnet_group
* aws_neptune_parameter_group
* aws_neptune_cluster_parameter_group
* aws_neptune_event_subscription

### Potential Terraform Configuration

```hcl
resource "aws_neptune_cluster" "example" {
  cluster_identifier = "example"
  engine = "neptune"
  engine_version = "1.0.1"
  cluster_parameter_group_name = "${aws_neptune_cluster_parameter_group.example.name}"
  subnet_group_name = "${aws_neptune_subnet_group.example.name}"
  database_name = "database"
  master_username = "user"
  master_password = "password"
  ...

}

resource "aws_neptune_cluster_instance" "example" {
  identifier = "example"
  cluster_identifier = "${aws_neptune_cluster.example.id}"
  engine = "neptune"
  instance_class = "db.m4.large"
  ...

}

resource "aws_neptune_subnet_group" "example" {
  name = "example"
  description = "example description"
  subnet_ids = ["${aws_subnet.frontend.id}", "${aws_subnet.backend.id}"]
}

resource "aws_neptune_parameter_group" "example" {
  name = "example"
  family = "example"
  description = "example description"
}

resource "aws_neptune_cluster_parameter_group" "example" {
  name = "example"
  family = "example"
  description = "example description"
}

resource "aws_neptune_event_subscription" "example" {
  name = "example"
  sns_topic = "${aws_sns_topic.example.arn}"
  source_type = "db-instance"
  source_ids = ["${aws_neptune_cluster_instance.example.id}"]
  event_categories = [
    "creation",
    "failover",
    ...
  ]
}
```

### Order

1. `aws_neptune_parameter_group`,`aws_neptune_cluster_parameter_group`,`aws_neptune_subnet_group`
2. `aws_neptune_cluster`
3. `aws_neptune_cluster_instance`
4. `aws_neptune_event_subscription`

**Comment by dav009** [comment]
opened PR for `aws_neptune_parameter_group`  https://github.com/terraform-providers/terraform-provider-aws/pull/4724

**Comment by saravanan30erd** [comment]
@atsushi-ishibashi @dav009 I would like to work on `aws_neptune_subnet_group`, anyone working on this?

**Comment by atsushi-ishibashi** [comment]
@saravanan30erd I'm not👍

**Comment by dav009** [comment]
@saravanan30erd  go for it 👍.
 I will  address the requested changes in the open PR soon 🙇

**Comment by saravanan30erd** [comment]
@atsushi-ishibashi @bflad It looks like both RDS and Neptune using same resource `DB Subnet Group` for subnet groups, so I think we can use the same resource `aws_db_subnet_group` with just updating document, any thoughts?

**Comment by bflad** [comment]
@saravanan30erd each service requires its own connection/endpoint and resource handling will likely vary between the two. Definitely create separate resources even if they look very similar.

**Comment by saravanan30erd** [comment]
@atsushi-ishibashi @dav009 I am working on `aws_neptune_cluster_parameter_group`

**Comment by bflad** [comment]
For those following along:
* `aws_neptune_parameter_group` resource: released in version 1.23.0 (enhanced with `arn` and `tags` in 1.24.0)
* `aws_neptune_cluster_parameter_group` resource: released in version 1.24.0
* `aws_neptune_subnet_group` resource: released in version 1.24.0

**Comment by saravanan30erd** [comment]
@dav009 I am working on `aws_neptune_cluster`

**Comment by angelinatquach** [comment]
@saravanan30erd  do you have an expected completion date? Great work so far btw! Really appreciating the rapid development.

**Comment by saravanan30erd** [comment]
@angelinatquach I am expecting to finish this resource in before next release.

**Comment by austinkelleher** [comment]
We are using Neptune too and really looking forward to seeing this implemented. Thanks for your work on this @saravanan30erd!

**Comment by saravanan30erd** [comment]
@bflad still two resources are remaining `aws_neptune_cluster_instance` and `aws_neptune_event_subscription`, I am working on aws_neptune_cluster_instance.

**Comment by bflad** [comment]
I'll be picking up `aws_neptune_event_subscription` this week. 👍

**Comment by saravanan30erd** [comment]
@bflad I already started and on the half way :)-

**Comment by bflad** [comment]
@saravanan30erd even better! 😄

**Comment by bflad** [comment]
As of version 1.31.0 of the AWS provider, releasing shortly, all the above mentioned resources have been implemented. 🎉  For future bug reports and feature requests, please submit separate issues so we have a clear definition of done. Thanks!
