### ISSUE TITLE
aws_ami doesn't ever return tags as output

### ISSUE THREAD

**Issue by lc-nyovchev** [terraform-providers/terraform-provider-aws#4715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
provider.aws v1.21.0

### Affected Resource(s)

* aws_ami

### Terraform Configuration Files

```
main.tf

provider "aws" {
  region = "${var.dest_ami_region}"
}

data "aws_ami" "ami_search" {
  most_recent = true
  name_regex = "mycompany-ubuntu-xenial-16.04-cassandra3-hvm-*"
  owners = ["xyz"]
}

output.tf

output "some" {
  value = "${length(data.aws_ami.ami_search.tags)}"
}


```
any attempts to interpolate the tags:

`value = "${data.aws_ami.ami_search.tags.ASD}" //where this is an existing tag`

`value = "${data.aws_ami.ami_search.tags["ASD"]}" //doesn't work either`

fails

The ASD tag actually exists on the image.

### Expected Behavior

The aws_ami task can actually get the tags that are defined on the ami

### Actual Behavior

The tags are a zero length map

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- checked that the terraform user HAS the right to describe tags, as a matter of fact it has ec2.*

```

**Comment by blckct** [comment]
Have you tried `lookup(data.aws_ami.ami_search.tags, "ASD")`?

**Comment by lc-nyovchev** [comment]
hey @blckct thanks for the suggestion, actually it turned out to be wrong account.

The reason was I was using two steps -> aws_ami to search the ami and aws_ami_copy to copy it to a different account, but the provider I was for the aws_ami was the wrong provider.

In short, I had two steps:

aws_ami to copy from a "build" account
aws_ami_copy to copy to a "child" account

But the aws provider I was using was only one, the "child" provider, but the module organization didn't allow me to see that clearly, and the "child" provider couldn't access the tags of the "build" account.
When I split that into two steps, each with a separate provider, it started working again.

Thanks for the time!
