### ISSUE TITLE
 Can not set certificate with aws_codebuild_project?

### ISSUE THREAD

**Issue by ryou1173** [terraform-providers/terraform-provider-aws#4742]
## Description
In aws code build, when the source type is github enterprise, It is necessary to set the github enterprise certificate,
I can not set a certificate & github enterprise access token in aws_codebuild_project of terraform.
Is there any solution?

## Affected Resource
aws_codebuild_project

**Comment by tkbky** [comment]
afaik, the access token can only set from the console, and not from the API. It would be a 1-time setup that connects the CodeBuild & Github account.

I'm happy to help to extend `aws_codebuild_project` resource to support the setting of `certificate`.

**Comment by tkbky** [comment]
@bflad I've made a PR for this issue but I'm still figuring out the acceptance testing part, it needs a Github enterprise account & access to an s3 bucket for the certificate. Help needed.

**Comment by bflad** [comment]
This has been released in [version 1.40.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1400-october-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
