### ISSUE TITLE
aws_sqs_queue, fifo and name_prefix not working

### ISSUE THREAD

**Issue by ssaarinen** [terraform-providers/terraform-provider-aws#4747]
Using name_prefix adds timestamp suffix to queue name but should also add '.fifo' to the end of fifo queue name.

**Comment by bflad** [comment]
The enhancement here has been merged into master and will release with version 1.25.0 of the AWS provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 1.25.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1250-june-27-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
