### ISSUE TITLE
Availability Zone should be defined for VPC Glue connections

### ISSUE THREAD

**Issue by smphhh** [terraform-providers/terraform-provider-aws#4762]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.11.7`

### Affected Resource(s)

* aws_glue_connection

### Expected Behavior

Availability Zone should be defined in API calls creating or updating Glue connections. See the [API documentation](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-connections.html#aws-glue-api-catalog-connections-PhysicalConnectionRequirements). Note that the documentation says that the field will be deprecated in the *future*, but is required for now.

### Actual Behavior

Trying to run any Glue job using a connection created with Terraform fails with the following error:
`JobName:xxx and JobRunId:xxx failed to execute with exception CONNECTION_LIST_CONNECTION_WITH_AZ_NULL xxx`. The same error is also produced when using the "Test connection" functionality in Glue console.

### Steps to Reproduce

Create a Glue connection in a VPC using Terraform, select the connection in AWS Glue console connection list and press the "Test connection" button.

**Comment by bflad** [comment]
Support for the `availability_zone` argument has been added via #5039 and will release with version 1.27.0 of the AWS provider, likely middle of this week.

**Comment by bflad** [comment]
This has been released in [version 1.27.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1270-july-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
