### ISSUE TITLE
Codepipeline OAuthToken property inside source configuration should be sensitive

### ISSUE THREAD

**Issue by manemarron** [terraform-providers/terraform-provider-aws#4768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.22.0

### Affected Resource(s)

* aws_codepipeline

### Terraform Configuration Files

```hcl
resource "aws_codepipeline" "pipeline" {
  # ...
  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "ThirdParty"
      provider         = "GitHub"
      version          = "1"
      output_artifacts = ["code"]

      configuration {
        Owner                = "owner"
        Repo                 = "repo"
        Branch               = "master"
        PollForSourceChanges = false
        OAuthToken           = "<REDACTED>"
      }
    }
  }
}
```

### Expected Behavior

`stage.0.action.0.configuration.OAuthToken` should appear as sensitive in terraform plan and apply

### Actual Behavior

`stage.0.action.0.configuration.OAuthToken` value is shown in plan and apply.

### Steps to Reproduce

1. `terraform plan -out=plan`
2. `terraform apply plan`

### References

* #4261 : Related to this issue, but for codepipeline

**Comment by fishfacemcgee** [comment]
@gdavison Your PR #14175 claims to fix this issue, but as far as I can tell, nothing has changed with the GitHub OAuth Token being treated as sensitive in that PR.

**Comment by fishfacemcgee** [comment]
Alternatively, if any advice could be provided around using `ignore_changes` to limit handling around the OAuth token exclusively, that'd at least be a good workaround. Right now, we have to ignore the whole configuration block, which means changing branch and the like has to be done by hand.
