### ISSUE TITLE
Getting Started with AWS EKS: Failed to restart kube-proxy

### ISSUE THREAD

**Issue by brandonstevens** [terraform-providers/terraform-provider-aws#4793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -version
Terraform v0.11.8-dev (0cc9e050ecd4a46ba6448758c2edc0b29bef5695+CHANGES)
+ provider.aws v1.22.0
+ provider.http v1.0.1
+ provider.null v1.0.0
+ provider.random v1.3.1
```

### Affected Resource(s)

* [Getting Started with AWS EKS](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html)

### Terraform Configuration Files

```hcl
locals {
  eks_node_userdata = <<USERDATA
#!/bin/bash -xe

CA_CERTIFICATE_DIRECTORY=/etc/kubernetes/pki
CA_CERTIFICATE_FILE_PATH=$CA_CERTIFICATE_DIRECTORY/ca.crt
mkdir -p $CA_CERTIFICATE_DIRECTORY
echo "${aws_eks_cluster.main.certificate_authority.0.data}" | base64 -d >  $CA_CERTIFICATE_FILE_PATH
INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
sed -i s,MASTER_ENDPOINT,${aws_eks_cluster.main.endpoint},g /var/lib/kubelet/kubeconfig
sed -i s,CLUSTER_NAME,${local.name},g /var/lib/kubelet/kubeconfig
sed -i s,REGION,${data.aws_region.current.name},g /etc/systemd/system/kubelet.service
sed -i s,MAX_PODS,20,g /etc/systemd/system/kubelet.service
sed -i s,MASTER_ENDPOINT,${aws_eks_cluster.main.endpoint},g /etc/systemd/system/kubelet.service
sed -i s,INTERNAL_IP,$INTERNAL_IP,g /etc/systemd/system/kubelet.service
DNS_CLUSTER_IP=10.100.0.10
if [[ $INTERNAL_IP == 10.* ]] ; then DNS_CLUSTER_IP=172.20.0.10; fi
sed -i s,DNS_CLUSTER_IP,$DNS_CLUSTER_IP,g /etc/systemd/system/kubelet.service
sed -i s,CERTIFICATE_AUTHORITY_FILE,$CA_CERTIFICATE_FILE_PATH,g /var/lib/kubelet/kubeconfig
sed -i s,CLIENT_CA_FILE,$CA_CERTIFICATE_FILE_PATH,g  /etc/systemd/system/kubelet.service
systemctl daemon-reload
systemctl restart kubelet kube-proxy
USERDATA
}
```

### Console Logs

```
cloud-init[3887]: + systemctl restart kubelet kube-proxy
[   13.947396] cloud-init[3887]: Failed to restart kube-proxy.service: Unit not found.
```
Full logs: https://gist.github.com/brandonstevens/4ac65970e3d0234ffc36f7f0a78dab34

### Expected Behavior

No cloud-init errors

### Actual Behavior

The user data script errors. This has no impact since it errors on the last command in the script.

### Steps to Reproduce

1. Run through the linked Getting Started with AWS EKS and launch the nodes.

### Important Factoids

AMI: eks-worker-v20 (ami-73a6e20b)

The lack of a _kube-proxy_ service on nodes is supported by AWS docs: [aunching Amazon EKS Worker Nodes](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html), specifically the linked CFN template https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/amazon-eks-nodegroup.yaml

### Description

I noticed the error while working on some unrelated troubleshooting. The error doesn't have any impact on setting up the cluster and nodes.

**Comment by kanaskaa** [comment]
I see aws-node pod is in crashloopbackoff and kube-dns hung in COntainercreating state.

NAMESPACE     NAME                       READY     STATUS              RESTARTS   AGE
kube-system   aws-node-7dm5t             1/1       Running             1          1m
kube-system   kube-dns-7cc87d595-vjdn6   0/3       ContainerCreating   0          4m
kube-system   kube-proxy-ttjkq           1/1       Running             0          1m

**Comment by bflad** [comment]
Great catch @brandonstevens -- your documentation fix will go out today or tomorrow when version 1.23.0 of the AWS provider is released.
