### ISSUE TITLE
aws_route_table: route.#: "(any number)" => "0" is not detected

### ISSUE THREAD

**Issue by heycasey** [terraform-providers/terraform-provider-aws#4796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.22.0
```
### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

```hcl
variable "defprefix" {
  description = "Default gateway used for routing"
  default = "0.0.0.0/0"
}

variable "prvprefix" {
  description = "List of private prefixes for routing"
  type = "list"
  default = ["10.0.0.0/8", "172.16.0.0/12"]
}

resource "aws_vpc" "thisvpc" {
  cidr_block = "10.123.0.0/18"
}

resource "aws_vpn_gateway" "thisvgw" {
  vpc_id = "${aws_vpc.thisvpc.id}"
}

resource "aws_route_table" "thisprvrtb" {
  vpc_id = "${aws_vpc.thisvpc.id}"
  route {
    cidr_block = "${var.defprefix}"
    gateway_id = "${aws_vpn_gateway.thisvgw.id}"
  }
  route {
    cidr_block = "${var.prvprefix[0]}"
    gateway_id = "${aws_vpn_gateway.thisvgw.id}"
  }
  route {
    cidr_block = "${var.prvprefix[1]}"
    gateway_id = "${aws_vpn_gateway.thisvgw.id}"
  }
}
```

### Expected Behavior

After initially applying the above script, commenting out all the `route` arguments in the `aws_route_table` resource and re-applying the script, Terraform should remove all the routes in the route table.

### Actual Behavior

Terraform does not detect the change:
`No changes. Infrastructure is up-to-date.`

### Steps to Reproduce

1. `terraform apply`
2. Comment out any one of the routes. Re-run `terraform apply`. Terraform will detect the change.
3. Comment out all but one of the routes. Re-run `terraform apply`. Terraform will detect the change.
3. Comment out all routes. Re-run `terraform apply`. Terraform will not detect the change.

**Comment by amkuchta** [comment]
@heycasey I ran into the same issue today - the "workaround" was to completely destroy the route table, then recreate it without the routes.  It worked, but it's clunky.
