### ISSUE TITLE
Not able to create auto-scaling group with custom vpc on AWS

### ISSUE THREAD

**Issue by ethicalmohit** [terraform-providers/terraform-provider-aws#4801]
I was trying to spin up complete aws basic infrastructure with a launch configuration and the auto-scaling group but terraform is giving error while spinning up the autoscaling group in the custom vpc.

### Terraform Version

terraform -v
Terraform v0.11.4
+ provider.aws v1.22.0

### Affected Resource(s)

terraform -v
Terraform v0.11.4
+ provider.aws v1.22.0

### Terraform Configuration Files

```hcl
https://github.com/ethicalmohit/zox/tree/master/aws_setup
```

### Debug Output

https://gist.github.com/ethicalmohit/ee5d1af7c526421a5517ed4d77aa3db1

### Expected Behavior

It should create an autoscaling group in the same subnet which is mentioned in the vpc_zone_identifier.

### Actual Behavior

It has not created any ASG.

### Steps to Reproduce

Create ASG with the file mentioned in this gist : https://gist.github.com/ethicalmohit/d6e351498c6c33bb8db2d8dd0726b2f6

1. `terraform apply`

### Important Factoids

No

* #0000

**Comment by avengers009** [comment]
As we are creating VPC on fly we need to comment out availability zone and it works.

or you can use below, if you already have created VPC.
```hcl
resource "aws_autoscaling_group" "web-asg" {

       availability_zones   = ["${split(",", var.availability_zones)}"]
       vpc_zone_identifier  = ["${var.subnets_id_vpc}"]
       name                 = "${var.Environment}-web_asg"
      .........}
```

**Comment by bflad** [comment]
@avengers009 is spot on here, commenting or removing `availability_zones` here should make this work as expected. The warnings about specifying both attributes are fairly recent so apologies if you ran into this before those updates happened in the documentation. Please do let us know if the documentation can be improved more though!

**Comment by ketzacoatl** [comment]
Using `provider.aws: version = "~> 1.27"`, I am still running into the ASG failing and reporting itself. I'm using the latest AWS provider. After TF fails, I can re-run the plan/apply to get the ASG to go through just fine.

**Comment by bflad** [comment]
@ketzacoatl can you please provide your configuration and the error message? If its similar to the above, commenting/removing `availability_zones` when `vpc_zone_identifier` is already configured will fix the issue.

**Comment by ketzacoatl** [comment]
@bflad sure, I am using the `asg` module seen here: https://github.com/fpco/terraform-aws-foundation/blob/master/modules/asg/main.tf

`availability_zones` is in use, but `vpc_zone_identifier` is not.
