### ISSUE TITLE
aws_lambda_invocation: cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by DJAlPee** [terraform-providers/terraform-provider-aws#4808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

> terraform -v
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.aws v1.22.0
+ provider.dns v2.0.0
+ provider.http v1.0.1
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)

data "aws_lambda_invocation"

### Terraform Configuration Files

```hcl
data "http" "ip_ranges" {
  url = "https://ip-ranges.amazonaws.com/ip-ranges.json"
}

data "template_file" "invoke" {
  template = "${file("${path.module}/data/init.json")}"

  vars {
    md5hash = "${md5(data.http.ip_ranges.body)}"
  }
}

data "aws_lambda_invocation" "invoke" {
  function_name = "UpdateCloudFrontIps"

  input = "${data.template_file.invoke.rendered}"
}
```

init.json
```json
{
  "Records": [
    {
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:aws:sns:EXAMPLE",
      "EventSource": "aws:sns",
      "Sns": {
        "SignatureVersion": "1",
        "Timestamp": "1970-01-01T00:00:00.000Z",
        "Signature": "EXAMPLE",
        "SigningCertUrl": "EXAMPLE",
        "MessageId": "95df01b4-ee98-5cb9-9903-4c221d41eb5e",
        "Message": "{\"create-time\": \"yyyy-mm-ddThh:mm:ss+00:00\", \"synctoken\": \"0123456789\", \"md5\": \"${md5hash}\", \"url\": \"https://ip-ranges.amazonaws.com/ip-ranges.json\"}",
        "Type": "Notification",
        "UnsubscribeUrl": "EXAMPLE",
        "TopicArn": "arn:aws:sns:EXAMPLE",
        "Subject": "TestInvoke"
      }
    }
  ]
}
```

### Expected Behavior

No JSON error

### Actual Behavior

Error: Error applying plan:

1 error(s) occurred:

* data.aws_lambda_invocation.invoke: data.aws_lambda_invocation.invoke: json: cannot unmarshal array into Go value of type map[string]interface {}

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Maybe the issue is related because of the "nested" json as a string in "message"

I'm using the lambda mentioned in this blog:
https://aws.amazon.com/de/blogs/security/how-to-automatically-update-your-security-groups-for-amazon-cloudfront-and-aws-waf-by-using-aws-lambda/

**Comment by spandey0202** [comment]
I have a similar issue while running the aws_lamdba_invocation api.

**Comment by spandey0202** [comment]
I have a similar issue while running the aws_lamdba_invocation api.
data "aws_lambda_invocation" "xxxx" {
  function_name = "${aws_lambda_function.lambda_function.function_name}"
  #trigger_once  = true

  input = <<JSON
{
		
  "key3": "value3",
  "key2": "value2",
  "key1": "value1"

}
JSON
}

**Comment by stephencoe** [comment]
I was also having this problem, I enabled `TF_LOG=debug` and noticed it was the output of the lambda which was a JSON string that was causing the issue for me

**Error in the response**
```
2018-07-28T21:51:13.581+0100 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: 2018/07/28 21:51:13 [DEBUG] [aws-sdk-go] "{\"Fail\": \"Unable to import users\"}"
2018/07/28 21:51:13 [ERROR] root.users: eval: *terraform.EvalReadDataApply, err: data.aws_lambda_invocation.run_setup: json: cannot unmarshal string into Go value of type map[string]interface {}
2018/07/28 21:51:13 [ERROR] root.users: eval: *terraform.EvalSequence, err: data.aws_lambda_invocation.run_setup: json: cannot unmarshal string into Go value of type map[string]interface {}
2018/07/28 21:51:13 [TRACE] [walkApply] Exiting eval tree: module.users.data.aws_lambda_invocation.run_setup
```
**Original**
```
def handler(event, context):
   ...
    message = {'foo':'bar'}
    return json.dumps(message)
```

After changing this and removing the `json.dumps` the invocation was successful

**Comment by GElkayam** [comment]
Having the exact same issue with probably the same AWS code.
Another thing is the fact it fails on every plan, and invokes the lambda on every plan.

**Comment by bflad** [comment]
Hi folks 👋 The `aws_lambda_invocation` data source expects proper JSON syntax in its `input` and the Lambda response. Since this issue was opened, Terraform 0.12 was released with [`jsonencode()`](https://www.terraform.io/docs/configuration/functions/jsonencode.html) and [`jsondecode()`](https://www.terraform.io/docs/configuration/functions/jsondecode.html) functions which may help with JSON <-> HCL conversions to guarantee correctness.

If you are still experiencing problems with this data source and proper JSON objects, please open a new GitHub issue and we will take a fresh look. Thanks.
