### ISSUE TITLE
Error creating Cognito Identity Provider: InvalidParameterException: At least one of the MetadataURL or MetadataFile should be provided.

### ISSUE THREAD

**Issue by alvarolinarescabre** [terraform-providers/terraform-provider-aws#4815]
Hi,

I deploy the AWS Congnito User Pool Identity Provider using the Terraform module **aws_cognito_identity_provider**

Whe I run "apply" I received this message: **Error creating Cognito Identity Provider: InvalidParameterException: At least one of the MetadataURL or MetadataFile should be provided.**

In AWS docs say [this options "ProviderDetails" is required](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateIdentityProvider.html), but I don't see on Terraform module where I put that.

## Terraform Version
Terraform v0.11.7
+ provider.aws v1.22.0

## Affected Resource
+ aws_cognito_identity_provider

## Terraform Configuration Files
```
resource "aws_cognito_identity_provider" "cognito_identity_provider" {
  user_pool_id  = "us-east-1_abc123"
  provider_name = "Azure"
  provider_type = "SAML"

  provider_details {
    authorize_scopes       = "email,openid,aws.cognito.signin.user.admin"
    client_id              = "123456789abc" 
    client_secret          = "123456789abc987654"
  }

  attribute_mapping {
    email = "email"
  }
}
```

## Expected Behavior
Create the Cognito Identity Provider resource

## Actual Behavior
Not create the Cognito Identity Provider resource

## Steps to Reproduce
1. ```terraform apply```

```
Error: Error applying plan:

1 error(s) occurred:

* module.cognito_identity_provider.aws_cognito_identity_provider.cognito_identity_provider: 1 error(s) occurred:

* aws_cognito_identity_provider.cognito_identity_provider: Error creating Cognito Identity Provider: InvalidParameterException: At least one of the MetadataURL or MetadataFile should be provided.
        status code: 400, request id: 123456789abcde
```

**Comment by alvarolinarescabre** [comment]
Finally I find the lost option..... the rigth way is that:

```
provider_details {
    MetadataFile = "${file(saml.xml)}"
  }
```

but it send this messages error:

```
An error occurred (InvalidParameterException) when calling the CreateIdentityProvider operation: Invalid XML
```
When uses this file on AWS Console works fine, but when I try with this aws cli command:
```
aws cognito-idp
 create-identity-provider --user-pool-id eu-west-1_abc123 --provider-name=Azure --provider-type SAML --provider-details file://./saml/details.json --attribute-mapping email=http://s
chemas.xmlsoap.org/ws/2005/05/identity/claims/name
```
same error...

The problem it's not Terraform instead is aws cli service with Cognito Identity Federation.

I open a case on AWS Support and waiting for response...

That is all for the moment...

**Comment by alvarolinarescabre** [comment]
AWS response....

The "issue" is the MetadataFile MUST receive the XML and not the file...

Example:

```
"MetadataFile": "<?xml version=\"1.0\" encoding=\"utf-8\"?><EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\" ID=\"_ac691a85-cfd9-4a21-a802-16f4f79fad39\" entityID=\"https://sts.windows.net/9c72562b-8077-4c0f-8444-ae87fb3a1fbb/\">...</IDPSSODescriptor></EntityDescriptor>"
}
```
But you need change the "/" on xml file, like this:
```
cat azure_origin.xml | awk '{ gsub(/"/,"\\\"") } 1' | tr -d "\n\r" > azure_new.xml
```

To me this is ugly ;P

I solvent using MetadataURL and put the Microsoft Azure path:
```
provider_details {
    MetadataURL = "https://login.microsoftonline.com/<TenantDomainName>/FederationMetadata/2007-06/FederationMetadata.xml"
  }
```

And it's work with terraform....

Case close :D

**Comment by jgournet** [comment]
For anyone arriving here with more or less the same issue, a solution to use the metadata xml file is to do:
`data "template_file" "metadata_tpl" {
  template = file("${path.module}/metadata.xml.tpl")
}

resource "aws_cognito_identity_provider" "SAML" {
  user_pool_id  = aws_cognito_user_pool.pool.id
  provider_name = "${local.resource_prefix}"
  provider_type = "SAML"

  provider_details = {
    MetadataFile = data.template_file.metadata_tpl.rendered
  }
}
`
hope this helps

**Comment by alvarolinarescabre** [comment]
Thanks :D
