### ISSUE TITLE
Pass list of security groups into a data source

### ISSUE THREAD

**Issue by jtravell** [terraform-providers/terraform-provider-aws#4819]
**What specific changes need to be made to the code below in order to get Terraform to output the security groups that are associated with the VPC that is associated with the OpsWorks Stack that gets created in the following code?**  
  
Here is the error message that is currently generated when `terraform apply` is run:  

    Error: Error running plan: 2 error(s) occurred:

    * data.aws_security_group.selected: 1 error(s) occurred:

    * data.aws_security_group.selected: 
    Resource 'data.aws_vpc.selected' does not have attribute 'default_security_group_id' 
    for variable 'data.aws_vpc.selected.default_security_group_id'

    * output.vpc_security_group_id: Resource 'data.aws_vpc.selected' 
    does not have attribute 'default_security_group_id' 
    for variable 'data.aws_vpc.selected.default_security_group_id'

And here is the code that generates the error above when `terraform apply` is run:  

    #Create stack 
    resource "aws_opsworks_stack" "main" {
      name                         = "MyLinuxDemoStack"
      region                       = "${var.region}"
      service_role_arn = "${var.serviceRoleARN}" 
      default_instance_profile_arn = "${var.instanceProfileARN}"
      default_availability_zone = "${var.availability_zone}"
      use_custom_cookbooks = "1"
      configuration_manager_name = "Chef"
      configuration_manager_version = "12"

      custom_cookbooks_source = {
      	type = "archive"
     	url = "https://s3.amazonaws.com/opsworks-demo-assets/opsworks-linux-demo-cookbooks-nodejs.tar.gz"
      }
 
    }

    #Create custom layer 
    resource "aws_opsworks_custom_layer" "demolayer" {
      name       = "MyLinuxDemoLayer"
      short_name = "demo"
      stack_id   = "${aws_opsworks_stack.main.id}"
      auto_assign_public_ips = "1"
    }

    #Put the VPC into a variable so that its constituent information can be retrieved
    data "aws_vpc" "selected" {
      id = "${aws_opsworks_stack.main.vpc_id}"
    }

    #Create an output variable for the default security group id in the vpc
    output "vpc_security_group_id" {
      value = "${data.aws_vpc.selected.default_security_group_id}"
    }  
  
    #Extract the security group into an variable
    data "aws_security_group" "selected" {
      id = "${data.aws_vpc.selected.default_security_group_id}"
    }  
  
    #Create an output variable for the security group name
    output "vpc_security_group_name" {
      value = "${data.aws_security_group.selected.name}"
    }

**Comment by mildwonkey** [comment]
@jtravell have you tried using the `aws_security_group` data source? I believe something like this would work:

```hcl
data "aws_security_group" "selected" {
    vpc_id =  "${aws_opsworks_stack.main.vpc_id}
    name = "default"
}
```

Reference: https://www.terraform.io/docs/providers/aws/d/security_group.html

**Comment by bflad** [comment]
Closing due to lack of response.
