### ISSUE TITLE
Error creating Cognito Identity Provider: InvalidParameterException: Provider example cannot be of type Google.

### ISSUE THREAD

**Issue by mmritesh** [terraform-providers/terraform-provider-aws#4822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem
I am referring to an example provided on [terraform-docs](https://www.terraform.io/docs/providers/aws/r/cognito_identity_provider.html) to create an identity provider on Cognito user pool with social media provider (Google).

even on following all the syntax recommended by docs. it still continue giving the exception as mentioned above. 

> Provider example cannot be of type Google
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.21.0

```
also tried with ` provider.aws v1.22.x`

### Affected Resource(s)

`aws_cognito_identity_provider`

### Terraform Configuration Files

```
variable "region" {
  default = "us-east-1"
}

provider "aws" {
  version = "1.21.0"   // Requires at least this version to support 'aws_cognito_user_group'
  region  = "${var.region}"
}

resource "aws_cognito_user_pool" "example" {
  name                      = "example-pool"
  auto_verified_attributes  = ["email"]
}

resource "aws_cognito_identity_provider" "example_provider" {
  user_pool_id  = "${aws_cognito_user_pool.example.id}"
  provider_name = "example"
  provider_type = "Google"

  provider_details {
    authorize_scopes  = "email"
    client_id         = "your client_id"
    client_secret     = "your client_secret"
  }

  attribute_mapping {
    email    = "email"
    username = "sub"
  }
}
```
### Debug Output

```
aws_cognito_user_pool.example: Refreshing state... (ID: us-east-1_gTCtYDeju)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_cognito_identity_provider.example_provider
      id:                                <computed>
      attribute_mapping.%:               "2"
      attribute_mapping.email:           "email"
      attribute_mapping.username:        "sub"
      provider_details.%:                "3"
      provider_details.authorize_scopes: "email"
      provider_details.client_id:        "your client_id"
      provider_details.client_secret:    "your client_secret"
      provider_name:                     "example"
      provider_type:                     "Google"
      user_pool_id:                      "us-east-1_gTCtYDeju"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_cognito_identity_provider.example_provider: Creating...
  attribute_mapping.%:               "" => "2"
  attribute_mapping.email:           "" => "email"
  attribute_mapping.username:        "" => "sub"
  provider_details.%:                "" => "3"
  provider_details.authorize_scopes: "" => "email"
  provider_details.client_id:        "" => "your client_id"
  provider_details.client_secret:    "" => "your client_secret"
  provider_name:                     "" => "example"
  provider_type:                     "" => "Google"
  user_pool_id:                      "" => "us-east-1_gTCtYDeju"

Error: Error applying plan:

1 error(s) occurred:

* aws_cognito_identity_provider.example_provider: 1 error(s) occurred:

* aws_cognito_identity_provider.example_provider: Error creating Cognito Identity Provider: InvalidParameterException: Provider example cannot be of type Google.
	status code: 400, request id: 3b0c6ffb-6eef-11e8-9539-2d838a958e54

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Expected Behavior

It should create the provider with google here:
![image](https://user-images.githubusercontent.com/19407167/41345606-d247d70c-6f21-11e8-8c1f-3d64c7a9a5b7.png)

### Actual Behavior

Throws exception: 

> Error creating Cognito Identity Provider: InvalidParameterException: Provider example cannot be of type Google.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

resource `aws_cognito_identity_provider` seems to be introduced in  v1.21.0 when referred to [issues/3279](https://github.com/terraform-providers/terraform-provider-aws/issues/3279)

**Comment by jkiyo** [comment]
Was having the same problem here, it worked setting the provider_name = "Google" as well.
Dunno if this is the expected behavior...

**Comment by bflad** [comment]
The [`aws_cognito_identity_provider` resource](https://www.terraform.io/docs/providers/aws/r/cognito_identity_provider.html) documentation was corrected recently for this error.

**Comment by sasitha** [comment]
I have encountered the same error with AWS CDK. Once I set the `providerName` and `providerType` both to `Google` it worked fine. Hopefully, the AWS CDK team would fix this in the future :)
