### ISSUE TITLE
Please implement aws_servicediscovery_register_instance

### ISSUE THREAD

**Issue by gladiatr72** [terraform-providers/terraform-provider-aws#4835]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In reference to #2561, @apparentlymart states:

> In practice, I suspect that many users will not use Terraform for RegisterInstance and DeregisterInstance because this would instead be done using EC2 autoscaling lifecycle hooks (or equivalent for ECS, etc) to dynamically adapt as instances come and go, but they seem simple enough that it wouldn't hurt to implement them for cases where EC2 instances and other network-accessible services (ELBs, etc) are statically allocated.

Here's my idea as to why it would be justifiable to include these bits in the terraform AWS provider:

**note**:  _instance_, in the context of the AWS _servicediscovery_ service, refers to a _member_ of a servicediscovery service rather than the more typical AWS usage as shorthand for an _EC2 instance_.

Without access to these functions, it is not possible to include service endpoints (e.g.: s3, rds, elasticache, etc) within a servicediscovery service as it pertains to the terraform state.  

While it would still be possible to add such endpoints using non-terraform methods, doing so introduces untracked dependencies that make terraform less useful than it might otherwise be.

### Comments

I have started sussing out possible methods of utilizing socat proxy containers to stand-in for this deficiency; regardless, it is an additional complexity that should not be necessary.

I think the philosophy shared somewhere within the terraform-community repository applies aptly: When laying out a module to encompass a terraform provider service, go ahead and add all of the attributes as outputs of the module--you never know when you or someone else might need them!

Thanks for your time, and thank you for a 9/10 star project (I'm very much looking forward to the release of the new parser!)

**Comment by deleted** [comment]
This appears to be duplicated by #8568.

**Comment by bflad** [comment]
Thanks for the note, @deleted 👍 Since the newer feature request includes a lot more details about the potential solution and has more upvotes, I'm going to close this issue to consolidate discussions and efforts into that issue. Please follow/upvote #8568 for updates.
