### ISSUE TITLE
Issue with creating db_snapshot

### ISSUE THREAD

**Issue by darrylmendez** [terraform-providers/terraform-provider-aws#4836]
I have the below rds provisioning script. I am trying to copy an existing rds oracle instance in us-east-1 into a new instance at us-east-2 using aws_db_snapshot.

```hcl
resource "aws_db_subnet_group" "oracle-subnet" {
  name        = "oracle-subnet"
  description = "RDS subnet group"
  subnet_ids  = ["${aws_subnet.main-private-1.id}", "${aws_subnet.main-private-2.id}"]
}

resource "aws_db_parameter_group" "oracle-parameters" {
  name        = "oracle-db-parameters"
  family      = "oracle-ee-12.1"
  description = "Oracle DB parameter group"
}

data "aws_db_snapshot" "db_snapshot" {
  most_recent            = true
  db_instance_identifier = "${var.db-instance-identifier-snapshot}"
}

resource "aws_db_instance" "oracle" {
  allocated_storage       = "${var.rds_allocated_storage}"
  engine                  = "${var.rds_oracle_engine}"
  engine_version          = "${var.rds_engine_version}"
  iops                    = "${var.rds_iops}"
  instance_class          = "${var.rds_instance_class}"
  identifier              = "${var.rds_identifier}"
  name                    = "${var.rds_db_name}"
  username                = "${var.rds_user}"
  password                = "${var.rds_password}"
  db_subnet_group_name    = "${aws_db_subnet_group.oracle-subnet.name}"
  snapshot_identifier     = "${data.aws_db_snapshot.db_snapshot.id}"
  parameter_group_name    = "${aws_db_parameter_group.oracle-parameters.name}"
  multi_az                = "false"
  vpc_security_group_ids  = ["${aws_security_group.allow-oracle.id}"]
  storage_type            = "${var.rds_storage_type}"
  backup_retention_period = "${var.rds_backup_retention}"
  availability_zone       = "${aws_subnet.main-private-1.availability_zone}"
  skip_final_snapshot     = "${var.skip_final_snapshot}"

  tags {
    Name = "${var.app-db-instance-name}"
  }
}
```

However I am getting the below error on terraform plan
data.aws_db_snapshot.db_snapshot: Your query returned no results. Please change your search criteria and try again.

**Comment by darrylmendez** [comment]
Hi all, I've found a workaround by adding the hard coding the snapshot identifier in the resource "aws_db_instance". However it would have ideal if the latest snapshot is picked without hard coding. I' haven't tested it, but terraform plan does not complain any more.

**Comment by radeksimko** [comment]
Hi @darrylmendez 
thanks for reporting the bug.

Based on the limited info from clipped screenshots it looks like Terraform has crashed, in which case it usually stores a log in `crash.log` in the current working directory. Do you mind providing us this file if this is the case? Please note, that it _may_ contain some sensitive data, so we recommend encrypting it first using our GPG key available at http://keybase.io/hashicorp

**Comment by avengers009** [comment]
data "aws_db_snapshot" "db_snap" {
    most_recent = true
    db_instance_identifier = "db-foobar"
}

resource "aws_db_instance" "db_stg" {
  instance_class       = "db.t2.micro"
  identifier           = "db-stg-foo"
  username             = "xxx"
  password             = "xxx"
  db_subnet_group_name = "foo-sub-name"
  snapshot_identifier  = "${data.aws_db_snapshot.db_snap.id}"
  vpc_security_group_ids = ["sg-9fd4999"]
  skip_final_snapshot = true
}


This is working for me, and its taking latest snapshot. In your code, you have mentioned everything, above parameters are enough to spin the instance from snapshot.

**Comment by avengers009** [comment]
`data "aws_db_snapshot" "db_snap" {
most_recent = true
db_instance_identifier = "db-foobar"
}

resource "aws_db_instance" "db_stg" {
instance_class = "db.t2.micro"
identifier = "db-stg-foo"
username = "xxx"
password = "xxx"
db_subnet_group_name = "foo-sub-name"
snapshot_identifier = "${data.aws_db_snapshot.db_snap.id}"
vpc_security_group_ids = ["sg-9fd4999"]
skip_final_snapshot = true
}`

**Comment by mildwonkey** [comment]
@darrylmendez if hardcoding is working, but not the variable, can we validate that the value you have in  `"${var.db-instance-identifier-snapshot}"` is correct?

**Comment by darrylmendez** [comment]
Hi @avengers009,
So for some reason it's not working for me. Is it because the source RDS is in us-east-1(N. Virginia) and target RDS in us-east-2 (Ohio)

**Comment by darrylmendez** [comment]
@mildwonkey - I have checked the hard coding is not working either... Only that it get's through the terraform plan without errors..

![image](https://user-images.githubusercontent.com/17715580/41734412-745af3c8-754c-11e8-9479-4d7bf6b4136e.png)

**Comment by mildwonkey** [comment]
Aha!

@darrylmendez - 
>  Is it because the source RDS is in us-east-1(N. Virginia) and target RDS in us-east-2 (Ohio)

I think you found the  problem - I'm pretty confident that the RDS snapshot needs to be in the same region. Copy the snapshot first (or find/create a snapshot in the same region).
