### ISSUE TITLE
Docs: Importing aws_lightsail_instance resource

### ISSUE THREAD

**Issue by mathewpeterson** [terraform-providers/terraform-provider-aws#4847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.22.0

### Affected Resource(s)

* aws_lightsail_instance

### Terraform Configuration Files

```hcl
resource "aws_lightsail_instance" "customer" {
  name              = "my-customer"
  availability_zone = "us-east-1a"
  blueprint_id      = "ubuntu_16_04_1"
  bundle_id         = "nano_1_0"
  key_pair_name     = "default"
}
```

```bash
terraform import  aws_lightsail_instance.customer arn:aws:lightsail:us-east-1:<account_number>:Instance/<id>
```

### Expected Behavior

Resource should be imported. 

Instead of using the `arn`, the `name` identifier works as expected.

```bash
terraform import  aws_lightsail_instance.customer my-customer
```

### Actual Behavior

```text
Error: aws_lightsail_instance.customer (import id: arn:aws:lightsail:us-east-1:<account_number>:Instance/<id>): 1 error(s) occurred:

* import aws_lightsail_instance.customer result: arn:aws:lightsail:us-east-1:<account_number>:Instance/<id>: import aws_lightsail_instance.customer (id: arn:aws:lightsail:us-east-1:<account_number>:Instance/<id>): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

### Steps to Reproduce

1. `terraform import  aws_lightsail_instance.customer arn:aws:lightsail:us-east-1:<account_number>:Instance/<id>`

### References

* https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/lightsail_instance.html.markdown#import

**Comment by bflad** [comment]
The documentation update has been merged into master via #4951 and will release with version 1.25.0 of the AWS provider, likely middle of next week.
