### ISSUE TITLE
API Gateway Swagger/Terraform resource policy consistency

### ISSUE THREAD

**Issue by danieladams456** [terraform-providers/terraform-provider-aws#4872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.23.0
```

### Affected Resource(s)
* `aws_api_gateway_rest_api`

#### api_gateway.tf
```hcl
resource "aws_api_gateway_rest_api" "api" {
  name        = "${var.api_gateway_name}"
  description = "${var.api_gateway_description}"
  body        = "${file("${path.module}/api_definition.yml")}"

  endpoint_configuration {
    types = ["REGIONAL"]
  }

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": "*",
      "Action": "execute-api:Invoke",
      "Resource": "*",
      "Condition": {
        "IpAddress": {
          "aws:SourceIp": "12.34.45.0/19"
        }
      }
    }
  ]
}
EOF
}
```
#### api_definition.yml
```yml
swagger: "2.0"
info:
  version: "1"
  title: "openIDAuthorizationCodeFlowHelperAPI"
paths:
  /code:
    post:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:REDACTED:function:openIDAuthorizationCodeFlowHelper/invocations"
        httpMethod: "POST"
        type: "aws_proxy"
  /token:
    get:
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:REDACTED:function:openIDAuthorizationCodeFlowHelper/invocations"
        httpMethod: "POST"
        type: "aws_proxy"
x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
  - Effect: "Allow"
    Principal: "*"
    Action: "execute-api:Invoke"
    Resource: "*"
    Condition:
      IpAddress:
        aws:SourceIp: "23.45.67.0/19"

```

### Expected Behavior
Single place to set the API Gateway policy

### Actual Behavior
Swagger definition is followed on first `apply` and then Terraform configuration tries to correct it
```
  ~ module.api_gateway.aws_api_gateway_rest_api.api
      policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"execute-api:Invoke\",\"Resource\":\"*\",\"Condition\":{\"IpAddress\":{\"aws:SourceIp\":\"23.45.67.0/19\"}}}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": \"*\",\n      \"Action\": \"execute-api:Invoke\",\n      \"Resource\": \"*\",\n      \"Condition\": {\n        \"IpAddress\": {\n          \"aws:SourceIp\": \"12.34.45.0/19\"\n        }\n      }\n    }\n  ]\n}\n"
```

### Steps to Reproduce
1. `terraform apply`
2. verify IP in resource policy from Swagger doc
3. `terraform apply`
4. verify IP in resource policy from Terraform config
5. `terraform apply`
6. verify no change since resource policy settles on Terraform config

### Workarounds
I realize this seems to be an issue on the [AWS side](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/restapi-import/) since the API Gateway import sets all properties stored in the definition file.  At the time of the `plan` stage, without a lot of yaml parsing logic it is impossible to know whether the API Gateway resource policy will change from the "desired" Terraform definition.  I don't see a clean solution other than auto-triggering the feedback loop again on the resource after the `body` attribute is set.

Here are the options I see in the current state.  They are probably good enough if no one else can think up a more elegant solution:

1. Run `apply` twice on any changes to the Swagger doc
2. Try to keep the two policies in sync so after every `apply` it has the correct policy

**Comment by danieladams456** [comment]
I figured out a workaround where using a JSON swagger definition you can include the same file into the definition as well as Terraform.  This will keep them in sync.  It does not work for yaml, but I found out JSON is easier to programmatically generate anyway.

```hcl
resource "aws_api_gateway_rest_api" "api" {
  name        = "${var.api_gateway_name}"
  description = "${var.api_gateway_description}"
  body        = "${data. template_file.renderer.result.rendered}"

  policy = "${file("${path.module}/data/api_resource_policy.json")}"
}

data "template_file" "renderer" {
  template = "${file("${path.module}/data/api_template.json")}"

  vars {
    api_gateway_name          = "${var.api_gateway_name}"
    lambda_handler_invoke_arn = "${var.lambda_handler_invoke_arn}"
    api_gateway_policy        = "${file("${path.module}/data/api_resource_policy.json")}"
  }
}
```

I think I can close this issue based on the workaround.

**Comment by alister26** [comment]
Needed to compose you a very little word to thank you yet again regarding the nice suggestions you’ve contributed here.

<a href="http://www.zerobugacademy.com/aws-training-in-chennai">aws training in chennai</a>

<a href="http://www.zerobugacademy.com/aws-training-in-chennai">advanced aws training in chennai</a>

<a href="http://www.zerobugacademy.com/aws-training-in-chennai">aws training in velachery</a>
