### ISSUE TITLE
aws_lb_listener should return dns_name

### ISSUE THREAD

**Issue by rayterrill** [terraform-providers/terraform-provider-aws#4899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_lb_listener should be able to return dns_name?

### New or Affected Resource(s)

* aws_lb_listener

**Comment by antonbabenko** [comment]
Hi @rayterrill !

`aws_lb_listener` does not have DNS name available in response from AWS API ([see sample response of describe listener](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeListeners.html)).

In fact, DNS name is available as attribute of [aws_lb resource](https://www.terraform.io/docs/providers/aws/r/lb.html#dns_name).

This issue can be closed.

**Comment by rayterrill** [comment]
How did I miss this. Thanks @antonbabenko. Sorry for the extra issue my friend. :(

**Comment by antonbabenko** [comment]
You are welcome! It is my pleasure to be a [Terraform gardener](https://www.terraform.io/docs/providers/aws/events/gardening-summer-2018.html) today. :)
