### ISSUE TITLE
aws_autoscaling_schedule sets max/min capacity to 0 rather than -1 by default

### ISSUE THREAD

**Issue by paulcdejean** [terraform-providers/terraform-provider-aws#4930]
The default should be "-1" (as in the scheduled action doesn't change max or min capacity), however it instead sets these to 0 which is silly.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @paulcdejean 👋 Sorry you're running into trouble here.

Can you please provide an example configuration that fails so we can reproduce and fix the issue you are seeing? Thanks.

**Comment by bflad** [comment]
Closing due to lack of response.
