### ISSUE TITLE
aws_internet_gateway does not destroy

### ISSUE THREAD

**Issue by carsoni** [terraform-providers/terraform-provider-aws#4947]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.24.0
+ provider.template v1.0.0
```

### Terraform Configuration Files

```
https://www.dropbox.com/s/b0j8go4di33i6yc/igw_issue.tar.gz?dl=0
```

### Crash Output

```
No crash - just endless "Still Destroying"
```

### Expected Behavior

```
The internet gateway should be destroyed when terraform destroy is called
```

### Actual Behavior

```
The internet gateway is not destroyed. I waited 20 minutes
```

### Steps to Reproduce

```

1. `terraform init`
2. `terraform apply`
3. Although I'm not sure of the relevance I performed the following steps prior to 
calling destroy...
5. ssh to machine
6. sudo -s
7. ls /dev/data/volume1
8. exit
9. logout
10. Then...
11. terraform destroy

```

### Additional Context

```

1. You'll need to run 'ssh-keygen -f mykey' in the directory you extract the zip.
2. I think this issue may have something to do with the fact that the ebs volume is mounted
 to the instance as I have run another set of scripts (exactly the same but with no auto mount) 
 where I manually mount the volume and prior to that mounting the igw can be destroyed but 
not afterwards ( I tested this twice)

```

### References

```
- #3747
```

**Comment by duckfez** [comment]
I would get a terraform debug log of this.  See https://www.terraform.io/docs/internals/debugging.html.  

My suspicion is that the EBS volume attachment won't unattach because the filesystem is mounted and you don't have `force_detach = true` set.  When the EBS can't detach, then you have a series of knock-on effects resulting in the igw not being able to be deleted because there's still an active instance with a public IP.

**Comment by duckfez** [comment]
I also kinda suspect that there may not be obvious dependency graph vertices from your EBS volume / instance to the IGW to give terraform the hint that "instances must be destroyed first", but I'll need to test that.

**Comment by carsoni** [comment]
Your `force_detach = true` on the aws_volume_attachment solved the issue. I can understand why this happened now as well.

Thanks for your help

**Comment by duckfez** [comment]
Awesome.  Any objection to closing this?

**Comment by carsoni** [comment]
@duckfez  No objections. All good. I suspect the original 3747 issue caused the creation of the force_detach flag and that my "bug" was more an RTFM scenario. 
Thanks again for the help

**Comment by bflad** [comment]
Closing given the above.
