### ISSUE TITLE
New resource: aws_dx_bgp_peer

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#4961]
Add a resource to manage Direct Connect BGP peers on a specified virtual interface.
This completes the initial set of Direct Connect resource listed in https://github.com/terraform-providers/terraform-provider-aws/pull/876#issuecomment-336928504.

**Comment by bflad** [comment]
The new resource has been merged into master and will release with version 1.37.0 of the AWS provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 1.37.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1370-september-19-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
