### ISSUE TITLE
Amazon Pinpoint

### ISSUE THREAD

**Issue by marcoreni** [terraform-providers/terraform-provider-aws#4990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Pinpoint has been available for a while, even if only in in `us-east-1`.

Is it possible to add support for it into Terraform?

### New or Affected Resource(s)

I tried to extract a list of the resources that TF should support, taken from the aws-sdk-go api reference.

Basic resources:
* `aws_pinpoint_app` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/5956
* `aws_pinpoint_campaign`
* `aws_pinpoint_segment`
* `aws_pinpoint_event_stream` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6069

Channels: 
* `aws_pinpoint_adm_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6038
* `aws_pinpoint_apns_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/5956
* `aws_pinpoint_apns_sandbox_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6233
* `aws_pinpoint_apns_voip_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6234
* `aws_pinpoint_apns_voip_sandbox_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6235
* `aws_pinpoint_baidu_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6111
* `aws_pinpoint_email_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6110
* `aws_pinpoint_gcm_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6089
* `aws_pinpoint_sms_channel` :white_check_mark: https://github.com/terraform-providers/terraform-provider-aws/pull/6088

### References

* https://aws.amazon.com/about-aws/whats-new/2016/12/introducing-amazon-pinpoint/
* https://aws.amazon.com/blogs/mobile/mobile-analytics-is-moving-to-amazon-pinpoint/
* (SDK) https://docs.aws.amazon.com/sdk-for-go/api/service/pinpoint/

**Comment by bflad** [comment]
The first resource, `aws_pinpoint_app` has been merged and will release with version 1.39.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
The following resources have been released in [version 1.40.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1400-october-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

* `aws_pinpoint_adm_channel`
* `aws_pinpoint_baidu_channel`
* `aws_pinpoint_email_channel`
* `aws_pinpoint_event_stream`
* `aws_pinpoint_gcm_channel`
* `aws_pinpoint_sms_channel`

Special shout out to @marcoreni who has been helping get these implemented!

**Comment by tonyxiao** [comment]
What about the integration between cognito and pinpoint? Is that possible?


![image](https://user-images.githubusercontent.com/696842/55379224-2b212000-54d1-11e9-9f83-387357826836.png)

**Comment by nywilken** [comment]
Hi @tonyxiao thanks for bringing up this ask. Can you please open up a new issue with your request for the cognito and pinpoint integration to help us track the request and effort appropriately. 

In the meantime, I am going to close this issue to avoid future requests getting lost in the thread.
