### ISSUE TITLE
New resource: Amazon Macie S3 Association

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#4992]
Amazon Macie administrative APIs [recently](https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-macie-releases-administrative-APIs-to-enable-IT-management-workflow-automation/) released.
Add initial support with an Amazon Macie S3 Association resource.

**Comment by vpadronblanco** [comment]
Is this being worked on? If not, I will get to it

**Comment by ewbankkit** [comment]
@vpadronblanco Yes, I have started on this, I'll push soon.

**Comment by bflad** [comment]
This has been released in [version 1.28.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1280-july-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
