### ISSUE TITLE
Blocking: aws_lb_listener.tls: expected protocol to be one of [http https tcp], got TLS

### ISSUE THREAD

**Issue by Broussard98** [terraform-providers/terraform-provider-aws#5013]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.25.0
+ provider.external v1.0.0
+ provider.null v1.0.0
+ provider.template v1.0.0

### Affected Resource(s)

resource aws_aws_lb_listener

### Terraform Configuration Files

```hcl
resource "aws_lb_listener" "tls" {
  count = "${var.allow-tls ? 1 : 0}"

  load_balancer_arn = "${aws_lb.nlb.arn}"
  port              = "${var.tls-listener-port}"
  protocol          = "TLS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-2017-01"

  certificate_arn   = "${data.aws_acm_certificate.tls-cert.arn}"

  default_action {
    type             = "forward"
    target_group_arn = "${aws_lb_target_group.tls.arn}"
  }
  # This is here because aws_autoscaling_group.web_servers depends on this resource and sets create_before_destroy to true
  lifecycle {
    create_before_destroy = true
  }
}
```

### Panic Output

Error: module.nlb.aws_lb_listener.tls: expected protocol to be one of [http https tcp], got TLS

* aws_lb_listener.tls: Error creating LB Listener: ValidationError: Listener protocol 'HTTPS' must be one of 'TLS, TCP'

### Expected Behavior

One of HTTPS or TLS should work

### Actual Behavior

If I use TLS, terraform plan throws error "got TLS"
If I use HTTPS, terraform apply throws error "must be one of 'TLS, TCP'"

**Comment by Broussard98** [comment]
Got it figured out. Network Load Balancers only support TCP listeners

**Comment by Yaowenjie** [comment]
@Broussard98 
Just a reminder, `Network Load Balancers only support TCP listeners` could be a little bit misleading. Because if you add `certificate_arn` attribute for it, HTTPS could also work. :)

**Comment by tgrimault** [comment]
The documentation says it is supposed to support TLS: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html#cfn-elasticloadbalancingv2-listener-protocol
