### ISSUE TITLE
Windows version of config

### ISSUE THREAD

**Issue by jtravell** [terraform-providers/terraform-provider-aws#5022]
Someone needs to create a version of the config for Windows boxes.  The paths to files like `/var/lib/kubelet/kubeconfig` needs to change to `C:\Users\username\.kube\config`, for example.  
  
One location where this needs to occur is in the `locals` section of `eks-worker-nodes.tf`, but this issue is pernicious and needs to be addressed throughout the sample files.  
  
Please reply here when this is done so that I can evaluate the code I downloaded from this example to make sure I got it correctly.  Also so you can alert others who read this.

**Comment by tdmalone** [comment]
@jtravell I'm not affiliated with Hashicorp or Terraform, but I just thought to mention that as this is an open source project, you (or anyone) can submit changes via pull requests (including to documentation) - so I'm sure you'd be welcome to submit these changes yourself for review. It's important to remember that software available for 'free' doesn't confer that support is also available for free, so it might be worth adjusting your expectations as your writing is likely to come across abrasive to the maintainers of the project.

**Comment by bflad** [comment]
Hi @jtravell 👋 Thank you for submitting this.

The EKS Getting Started Guide and the example Terraform configuration derived from that guide were created to match the recommended setup as described in the [AWS EKS Worker Nodes documentation](https://docs.aws.amazon.com/eks/latest/userguide/worker.html), which is currently based on using an Amazon Linux 2 AMI. From briefly reinvestigating the AWS documentation, it appears that official Windows support with EKS may still be in [Public Preview](https://github.com/aws/containers-roadmap/tree/master/preview-programs/eks-windows-preview) as announced back in [March 2019](https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-eks-opens-public-preview-of-windows-container-support/).

The Terraform team here at HashiCorp does not currently have any plans to create a new Windows-based guide or example Terraform configuration at least until the offering is generally available, so I'm going to close this issue for now, however at any point we would accept any community contributions in so far as they keep the existing Amazon Linux 2 configuration working as it does today.
