### ISSUE TITLE
aws_appautoscaling_target role_arn is ignored or doesn't work

### ISSUE THREAD

**Issue by jrobison-sb** [terraform-providers/terraform-provider-aws#5023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.aws v1.22.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_appautoscaling_target

### Terraform Configuration Files

```
resource "aws_appautoscaling_target" "myapp" {
  max_capacity       = 10
  min_capacity       = 4
  resource_id        = "service/${aws_ecs_cluster.default.name}/${aws_ecs_service.myapp.name}"
  role_arn           = "${aws_iam_role.ecs_autoscaling_role.arn}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

```

### Debug Output

I'm hesitant to post this publicly since it's 92,000 lines, so I couldn't possibly verify that there's no sensitive information here, and since the issue is reproducible on-demand. If a debug log is needed, please point me to the specific parts of the log that I should paste.

### Panic Output

No panic.

### Expected Behavior

The aws_appautoscaling_target resource should be created using the expected `role_arn`.

### Actual Behavior

The aws_appautoscaling_target resource is created, but the role is set to the default `arn:aws:iam::1234567890:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService`.

Then since the target isn't using the role Terraform told it to use, Terraform will prompt for this to be changed upon every `apply`.

### Steps to Reproduce

Build the resource that I pasted above, then:

1. `terraform apply`
2. Run an `aws application-autoscaling describe-scalable-targets --service-namespace ecs` and see that the RoleARN is the default `AWSServiceRoleForApplicationAutoScaling_ECSService` role from Amazon, not the role I built myself.
3. Run an apply again and again and see that Terraform keeps trying and failing to set this role.

**Comment by Tiny-wlx** [comment]
Hi @bflad 

Is this bug fix?
I have the same issue with Terraform v0.11.14 and provider.aws v1.60.0

Thanks

**Comment by aeschright** [comment]
I'm able to reproduce this issue on Terraform 0.12.8 and AWS provider 2.28 with the following config:

```
resource "aws_ecs_cluster" "test" {
  name = "test_cluster"
}

resource "aws_ecs_task_definition" "task" {
  family = "test"

  container_definitions = <<EOF
[
    {
        "name": "busybox",
        "image": "busybox:latest",
        "cpu": 10,
        "memory": 128,
        "essential": true
    }
]
EOF
}

resource "aws_ecs_service" "service" {
  name            = "test"
  cluster         = "${aws_ecs_cluster.test.id}"
  task_definition = "${aws_ecs_task_definition.task.arn}"
  desired_count   = 1

  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 50
}

resource "aws_appautoscaling_target" "target" {
  service_namespace  = "ecs"
  resource_id        = "service/${aws_ecs_cluster.test.name}/${aws_ecs_service.service.name}"
  role_arn           = "${aws_iam_role.ecs_autoscaling_role.arn}"
  scalable_dimension = "ecs:service:DesiredCount"
  min_capacity       = 1
  max_capacity       = 3
}

resource "aws_iam_role" "ecs_autoscaling_role" {
  name = "test_role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
```

**Comment by masterjg** [comment]
Same here. Looks like **role_arn** isn't set properly and on each apply terraform tries to update the **aws_appautoscaling_target** resource due to this field...

**Comment by gawbul** [comment]
@aeschright any update on when this might expect to be fixed? We are hitting an issue in production due to this bug 😞

**Comment by VincentHokie** [comment]
At the moment I'm going with adding the following to the `aws_appautoscaling_target`

```
lifecycle {
    ignore_changes = [role_arn]
  }
```

while this issue is pending.

**Comment by bennettp123** [comment]
This seems relevant: http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/application-autoscaling-service-linked-roles.html

In particular:
```
- Application Auto Scaling automatically creates the SLR in your account when you call RegisterScalableTarget or PutScalingPolicy if you have the IAM CreateServiceLinkedRole permission.
- Application Auto Scaling will preferentially use the SLR after it is available in the account, even if RegisterScalableTarget is called with an IAM Role.
```

So one workaround is to make sure the account has CreateServiceLinkedRole, or create it elsewhere, and then remove the `roleArn` attribute.

**Comment by bflad** [comment]
Hi folks 👋 As mentioned above, this appears to be (newer) expected behavior according to the [AWS Documentation](https://docs.aws.amazon.com/autoscaling/application/userguide/security_iam_service-with-iam.html#security_iam_service-with-iam-roles):

> With the introduction of service-linked roles, several legacy service roles are no longer required. If you specify a legacy service role for any other service (for example, Amazon ECS or Spot Fleet), Application Auto Scaling ignores it. Instead, it uses a service-linked role. If this role doesn't exist, you must have permissions to create it or a permission error occurs.

Since this behavior is controlled by AWS, I have changed the labeling of this issue to a documentation fix and will submit an update shortly.
