### ISSUE TITLE
d/aws_vpc: Additional IPv4 CIDR blocks

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#5042]
The `aws_vpc` data source should return any additional IPv4 CIDR blocks associated with the VPC.
Related to:
* https://github.com/terraform-providers/terraform-provider-aws/pull/3723

**Comment by bflad** [comment]
In version 1.27.0 of the AWS provider, releasing middle of next week, the `aws_vpc` data source will now have a `cidr_block_associations` list attribute available. Thanks @kl4w!

**Comment by bflad** [comment]
This has been released in [version 1.27.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1270-july-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
