### ISSUE TITLE
aws_ssm_maintenance_window_task missing task_invocation_parameters

### ISSUE THREAD

**Issue by ianrayns** [terraform-providers/terraform-provider-aws#5045]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unable to set invocation parameters on SSM maintenance task

### New or Affected Resource(s)

* aws_ssm_maintenance_window_task

### References

* [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindowtask.html#cfn-ssm-maintenancewindowtask-taskinvocationparameters)
* [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/ssm/register-task-with-maintenance-window.html)

**Comment by bflad** [comment]
Support for a new `task_invocation_parameters` configuration block in the `aws_ssm_maintenance_window_task` resource has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected later this week. Thanks to @kterada0509 for the implementation work. 👍
