### ISSUE TITLE
CodeBuild webhook secret is empty

### ISSUE THREAD

**Issue by salvianreynaldi** [terraform-providers/terraform-provider-aws#5085]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`terraform --version`

Terraform v0.11.7
+ provider.aws v1.26.0
+ provider.github v1.1.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_codebuild_webhook
* github_repository_webhook

### Terraform Configuration Files

```hcl

resource "aws_codebuild_webhook" "this" {
  project_name  = "<my-build-project-name>"
  branch_filter = "(master|release/*)"
}

resource "github_repository_webhook" "this" {
  active     = true
  events     = ["push"]
  name       = "web"
  repository = "<my-repository>"

  configuration {
    url          = "${aws_codebuild_webhook.this.payload_url}"
    secret       = "${aws_codebuild_webhook.this.secret}"
    content_type = "json"
    insecure_ssl = false
  }
}

output "codebuild_secret" {
  value = "${aws_codebuild_webhook.this.secret}"
}

output "codebuild_url" {
  value = "${aws_codebuild_webhook.this.payload_url}"
}

```

### Expected Behavior

One terraform GitHub Webhook is created (by terraform), and it's working

### Actual Behavior

first time plan result:
```bash
  + aws_codebuild_webhook.this
      id:                <computed>
      branch_filter:     "(master|release/*)"
      payload_url:       <computed>
      project_name:      "<my-build-project-name>"
      secret:            <computed>
      url:               <computed>

  + github_repository_webhook.this
      id:                <computed>
      active:            "true"
      configuration.%:   <computed>
      events.#:          "1"
      events.1597642340: "push"
      name:              "web"
      repository:        "<my-repository>"
      url:               <computed>

```

subsequent plans (repeating over and over by executing `terraform plan`)
```bash
  ~ github_repository_webhook.this
      configuration.%:      "3" => "4"
      configuration.secret: "" => ""
```
two github webhooks are created:
- One is created by CodeBuild (It's `aws_codebuild_webhook` that creates the webhook. The same thing happens if we check `Rebuild every time a code change is pushed to this repository` in CodeBuild settings GUI)
- the other (`github_repository_webhook`-created) GitHub webhook is not working because the secret is empty. The URL is set properly

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

I'm authenticating CodeBuild to GitHub using a GitHub user in my GitHub organization. The user need to be added as my repository admin, because if it's not CodeBuild will complain that it cannot find the repository when creating the webhook (via GUI / using `aws_codebuild_webhook`). Is this behaviour expected?

**Comment by bflad** [comment]
Hi @salvianreynaldi 👋 Sorry you are running into this confusing behavior. AWS CodeBuild appears to work in different ways depending on which type of source you are working with (GitHub or GitHub Enterprise).

When working with regular GitHub (github.com):
* CodeBuild uses its granted OAuth permissions to automatically manage creating and deleting the webhook in GitHub. Manually creating the GitHub webhook (e.g. via `github_repository_webhook`) is not necessary.
* CodeBuild does not ever provide the `secret` value via API response during webhook creation/read.

When working with GitHub Enterprise (GHE):
* CodeBuild project webhooks must be manually created in GitHub Enterprise (e.g. via `github_repository_webhook`).
* CodeBuild only provides the `secret` value via API during webhook creation.

If there are some improvements to the [`aws_codebuild_webhook` resource documentation](https://www.terraform.io/docs/providers/aws/r/codebuild_webhook.html), please let us know.

**Comment by bflad** [comment]
I have submitted #5088 to further clarify the observed behaviors with CodeBuild webhook API.

**Comment by bflad** [comment]
Hi @salvianreynaldi -- I marked #5088 to close this issue since it should cover the additional documentation about the differences in behaviors between source types. If you have ideas for other improvements to the documentation (since this really relates to how the CodeBuild API works), please reach out. Thanks!

**Comment by salvianreynaldi** [comment]
Thanks @bflad for the clarifications! I've suspected that `github_repository_webhook` is actually not needed. However, does it mean that we can't have a codified custom webhook (like editing the events that triggers the created webhook)? CodeBuild-created webhook will enable the `push` and `pull_request` events

**Comment by bflad** [comment]
Due to how the CodeBuild API works, you have to import the GitHub webhook into Terraform after creation. I would open an AWS support case if you would like the CodeBuild API to better handle this functionality (e.g. allowing you to skip GitHub webhook management and always returning the CodeBuild webhook secret so it can be managed more easily outside CodeBuild)
