### ISSUE TITLE
Unsetting ser_de_info.name from aws_glue_catalog_table results in error

### ISSUE THREAD

**Issue by f0rk** [terraform-providers/terraform-provider-aws#5094]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_glue_catalog_table

### Terraform Configuration Files

before:

```hcl
    ser_de_info {
      name = "OrcSerDe"
      serialization_library = "org.apache.hadoop.hive.ql.io.orc.OrcSerde"
    }
```

after:

```hcl
    ser_de_info {
      serialization_library = "org.apache.hadoop.hive.ql.io.orc.OrcSerde"
    }
```

### Debug Output

```
  storage_descriptor.0.ser_de_info.0.name: "OrcSerDe" => ""
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* aws_glue_catalog_table.daily_claims: 1 error(s) occurred:

* aws_glue_catalog_table.daily_claims: Error updating Glue Catalog Table: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, UpdateTableInput.TableInput.StorageDescriptor.SerdeInfo.Name.
```

### Expected Behavior

name should be deleted.

### Actual Behavior

name is set to empty.

**Comment by rgosh001** [comment]
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_glue_catalog_table.go#L141

even if i don't add the name, it still says it's required as well. Even though the source code shows it's a optional input parameter

**Comment by brandonwbrown** [comment]
is there any harm in adding the name?

**Comment by franciscocpg** [comment]
I'm facing the same problem.

The docs (both [terraform](https://www.terraform.io/docs/providers/aws/r/glue_catalog_table.html#name-2) and [AWS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-serdeinfo.html#cfn-glue-table-serdeinfo-name)) states that it's an optional field.

Why is it validating minimum field size?

**Comment by justinnaldzin** [comment]
> is there any harm in adding the name?

You can add a placeholder name of at least one character in your terraform config.  But Glue Crawlers will unset/remove the serde name.  So every terraform plan will see this as a change.  And you can't add the serde name to the lifecycle: ignore_changes block because as mentioned above, the SDK requires it.
