### ISSUE TITLE
aws_batch_compute_environment always submits desired_vcpus although optional

### ISSUE THREAD

**Issue by ploh** [terraform-providers/terraform-provider-aws#5097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform core 0.11.3
aws provider 1.25.0

### Affected Resource(s)

* aws_batch_compute_environment

### Terraform Configuration Files

```hcl
resource "aws_batch_compute_environment" "this" {
  compute_environment_name = "my_compute_env"

  compute_resources {
    max_vcpus = "100"
    min_vcpus = "0"
    ...
```

### Expected Behavior
Planning and applying an unchanged configuration should not show / apply any changes, let alone produce errors

### Actual Behavior
`terraform plan` shows
```
  ~ module.batch.aws_batch_compute_environment.this
      compute_resources.0.desired_vcpus: "10" => "0"
```

`terraform apply` fails with
```
* module.main.module.batch.aws_batch_compute_environment.this: 1 error(s) occurred:

* aws_batch_compute_environment.this: : Manually scaling down compute environment is not supported.  Disconnecting job queues from compute environment will cause it to scale-down to minvCpus.
```

### Steps to Reproduce

1. `terraform apply` to create the compute environment
1. Log in to the AWS web console and manually set the _desired vcpus_ to 10
1. `terraform apply` again, without changing the configuration at all

### Probable cause

The [terraform documentation](https://www.terraform.io/docs/providers/aws/r/batch_compute_environment.html#desired_vcpus) says that `desired_vcpus` is an optional parameter. The [AWS Batch API documentation](https://docs.aws.amazon.com/batch/latest/APIReference/API_UpdateComputeEnvironment.html) also lists it as optional. But it seems that terraform is somehow not honoring this and always sets the desired_vcpus when making the AWS API call, even if the optional parameter is _not_ given in the terraform configuration.

I found [a line in the terraform-provider-aws source code](https://github.com/terraform-providers/terraform-provider-aws/blob/455093e92d78aebc8f94abf076e025a4094a2707/aws/resource_aws_batch_compute_environment.go#L349) that could mean that could cause the `desired_vcpus` to be always submitted just like `min_vcpus` and `max_vcpus`. But my understanding of the terraform source code is far too little to be sure.

**Comment by bflad** [comment]
Hi @ploh 👋 Thanks for submitting this and sorry you are running into trouble.

We actually have two open issues for this already:
* https://github.com/terraform-providers/terraform-provider-aws/issues/4671
* https://github.com/terraform-providers/terraform-provider-aws/issues/4788

And an in progress pull request to fix it: https://github.com/terraform-providers/terraform-provider-aws/pull/4855

In order to consolidate discussions and efforts with the bug fix, I'm going to close this and #4788 to the earliest report, #4671. 👍
