### ISSUE TITLE
aws_codebuild_project should allow for the insertion of build commands

### ISSUE THREAD

**Issue by dgranville** [terraform-providers/terraform-provider-aws#5101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When configuring a CodeBuild project through the AWS console, it is possible to either specify a buildspec.yml file or directly insert the build commands into the project.  This latter option appears to be missing from the current *aws_codebuild_project* resource.

A new attribute called *build_command* can be made available in the *source* code block of the *aws_codebuild_project* resource.

### New or Affected Resource(s)

aws_codebuild_project

### Potential Terraform Configuration

```hcl
resource aws_codebuild_project "template" {
  name = "${var.project_name}"
  service_role = "${aws_iam_role.template.arn}"

  artifacts {
    type = "CODEPIPELINE"
  }

  source {
    type = "CODEPIPELINE"
    build_command = "ls && pwd && echo 'hello world'"
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "aws/codebuild/ubuntu-base:14.04"
    type         = "LINUX_CONTAINER"
  }

}

```

### References

See item 13, "For Build specification..."
* https://docs.aws.amazon.com/codebuild/latest/userguide/how-to-create-pipeline.html#how-to-create-pipeline-console

**Comment by bflad** [comment]
Hi @dgranville 👋  Are you aware of how this is differently implemented in the CodeBuild API beyond what is implemented with the `buildspec` argument for the `aws_codebuild_project` resource? 

* https://www.terraform.io/docs/providers/aws/r/codebuild_project.html#buildspec
* https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSource.html

**Comment by dgranville** [comment]
I don't work directly with the AWS APIs, so I can't answer that question for you.  However, I have attempted to pass a command string (as in the example above) to the buildspec argument of the aws_codebuild_project resource and I get this error when executing the pipeline:

stat /codebuild/output/src085454753/src/ls && pwd && echo 'hello world': no such file or directory

So looks like the string as passed is interpreted by the AWS API as the buildspec.yml file location.

**Comment by Vermyndax** [comment]
@dgranville Did you ever figure out a workaround for this? I'm trying to implement a terraform module that would use a prepacked buildspec.yml for a common CodeBuild configuration and I'm struggling with this. The docs aren't clear about what we can do with this buildspec property either. I was thinking to maybe do something like an input a la aws_iam_role_policy but I'm not sure if that would work. In my use case, requiring a buildspec.yml file at the root of a git repo wouldn't work out.

**Comment by sean-abbott** [comment]
So, the buildspec thing as implemented here you can just create a template file that has an aws buildspec.yml and read that in, like `buildspec           = "${file("templates/recommendation_engine_buildspec.yml")}"`

The basic example works fine for me on that one.

If you simply pass it a file path relative to the top level of your primary source, it should use that.

**Comment by bflad** [comment]
Hi folks 👋 It appears that when you fill in CodeBuild web console with build commands, it is creating a small, valid buildspec file for you. Having created a test project with build commands set to `echo "testing"`, here is the API output:

```json
{
    "projects": [
        {
            "source": {
                "buildspec": "version: 0.2\n\nphases:\n  build:\n    commands:\n       - echo \"testing\"\n",
            },
```

To match this in Terraform with heredoc syntax:

```hcl
resource "aws_codebuild_project" "example" {
  # ... other configuration ...

  source {
    # ... other configuration ...

    buildspec = <<BUILDSPEC
version: 0.2

phases:
  build:
    commands:
       - echo "testing"
BUILDSPEC
  }
}
```

Which can be substituted with [`file()`](https://www.terraform.io/docs/configuration/functions/file.html), [`templatefile()`](https://www.terraform.io/docs/configuration/functions/templatefile.html), or even completely HCL with [`yamlencode()`](https://www.terraform.io/docs/configuration/functions/yamlencode.html) if you wish:

```hcl
resource "aws_codebuild_project" "example" {
  # ... other configuration ...

  source {
    # ... other configuration ...

    buildspec = yamlencode({
      version = "0.2"

      phases = {
        build = {
          commands = [
            "echo \"testing\""
          ]
        }
      }
    })
  }
}
```

We would likely not want to introduce complexity into the Terraform resource to disambiguate the buildspec from the API as being simple commands versus a more defined buildspec file to allow two separate arguments in the Terraform resource. Given that, I'm going to close this feature request for now.

If you would prefer this was documented in the resource documentation please create a GitHub issue or submit the change at https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/codebuild_project.html.markdown and we'll take a further look. 👍 

Thanks again for this feature request.
