### ISSUE TITLE
Create aws_egress_only_internet_gateway data source

### ISSUE THREAD

**Issue by bstopp** [terraform-providers/terraform-provider-aws#5103]
### Description
The title says it all. There's a resource to create EIG, but no way to look up existing ones.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_egress_only_internet_gateway

### Potential Terraform Configuration

```hcl
data "aws_egress_only_internet_gateway" "eig" {
  filter {
    name = "attachment.vpc-id"
    values = ["${data.aws_vpc.selected.id}"]
  }
}
```

**Comment by bstopp** [comment]
As a note on this issue, it is likely that it isn't possible to support it fully until the EC2 API is updated to allow for filtering/lookups. Appears that right now, the responses contain all EIG resources:

[API Docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeEgressOnlyInternetGateways.html)

Which is really unfortunate.

**Comment by saravanan30erd** [comment]
@bstopp yes, correct. Now we can only get the other values(attached vpc,..) based on EIG input which is not match your requirement.
