### ISSUE TITLE
create aurora instance error with audit logs enabled

### ISSUE THREAD

**Issue by iwasnobody** [terraform-providers/terraform-provider-aws#5121]
should be related to "enabled_cloudwatch_logs_exports = ["audit"]"
### Terraform Version

Terraform v0.11.7
+ provider.aws v1.26.0

### Affected Resource(s)

aws_rds_cluster_instance

### Terraform Configuration Files
resource "aws_rds_cluster" "web" {
  provider = "aws.${var.project}"
  cluster_identifier      = "${var.project}-${var.env}-web-db"
  availability_zones      = "${var.aws_az}"
  database_name           = "web"
  master_username         = "XXXX"
  master_password         = "XXXXXXX" 
  backtrack_window        = 259200
  backup_retention_period = 5
  port = 3306
  vpc_security_group_ids  = ["${aws_security_group.web_db.id}"]
  storage_encrypted       = true
  db_subnet_group_name    = "${aws_db_subnet_group.db_net.id}"
  db_cluster_parameter_group_name = "${aws_rds_cluster_parameter_group.web.id}"
  engine = "aurora"
  enabled_cloudwatch_logs_exports = ["audit"]
  skip_final_snapshot = true
  tags {
      Name = "${var.project}-${var.env}-web-cluster"
  }
}
resource "aws_rds_cluster_instance" "web_instances_master" {
  provider = "aws.${var.project}"
  promotion_tier     = 0
  count              = 1
  identifier         = "${var.project}-${var.env}-web-db"
  cluster_identifier = "${aws_rds_cluster.web.id}"
  instance_class     = "db.r3.4xlarge"
  db_subnet_group_name = "${aws_db_subnet_group.db_net.id}"
  db_parameter_group_name = "${aws_db_parameter_group.web.id}"
  auto_minor_version_upgrade = false
  tags {
      Name = "${var.project}-${var.env}-web-instance"
  }
}
resource "aws_rds_cluster_instance" "web_instances_reader1" {
  provider = "aws.${var.project}"
  promotion_tier     = 1
  count              = 1
  identifier         = "${var.project}-${var.env}-web-db-reader1"
  cluster_identifier = "${aws_rds_cluster.web.id}"
  instance_class     = "db.r3.4xlarge"
  db_subnet_group_name = "${aws_db_subnet_group.db_net.id}"
  db_parameter_group_name = "${aws_db_parameter_group.web.id}"
  auto_minor_version_upgrade = false
  tags {
      Name = "${var.project}-${var.env}-web-instance"
  }
}

### Actual Behavior

* aws_rds_cluster_instance.web_instances_reader1: 1 error(s) occurred:

* aws_rds_cluster_instance.web_instances_reader1: unexpected state 'configuring-log-exports', wanted target 'available'. last error: %!s(<nil>)
* aws_rds_cluster_instance.web_instances_master: 1 error(s) occurred:

* aws_rds_cluster_instance.web_instances_master: unexpected state 'configuring-log-exports', wanted target 'available'. last error: %!s(<nil>)

**Comment by bflad** [comment]
Hi @iwasnobody 👋  Thanks for submitting this and sorry for the trouble.

Currently, we explicitly check the RDS instance status when performing create/update/delete operations to try and catch when they are complete. When RDS adds new functionality, sometimes they add a new status which the code is not expecting yet. We may switch up the logic at some point to only look for error conditions but for now we can add `configuring-log-exports` as an expected status.

I have a branch with the code update ready, I'm just running acceptance testing on it now. 👍

**Comment by bflad** [comment]
Pull request submitted: #5124

**Comment by bflad** [comment]
The fix for this has been merged into master and will release with version 1.27.0 of the AWS provider, likely middle of this week.

**Comment by bflad** [comment]
This has been released in [version 1.27.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1270-july-11-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by iwasnobody** [comment]
Many thx
