### ISSUE TITLE
Add resource timeout to aws_lambda_function

### ISSUE THREAD

**Issue by SVT125** [terraform-providers/terraform-provider-aws#5129]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm unable to create an `aws_lambda_function` in `eu-central-1` from a 46 MB zip file stored in an EC2 node in `us-west-2`. The same configuration below worked for creating the Lambda function in `us-west-2`, but only when I've come to `eu-central-1` does Terraform time out. I've linked a similar pull request that describes this problem below.

I tried seeing if I could specify a resource timeout (as I assume this is because it's a decently large file + it's a cross-region upload from a local file), but it seems `aws_lambda_function` doesn't support timeouts - this would be greatly appreciated in lieu of this cross-region scenario.

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.26.0
```

### Affected Resource(s)

`aws_lambda_function`

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "upload" {
  filename         = "../../lambda.zip"
  function_name    = "${var.lambda_name}"
  role             = "${aws_iam_role.upload.arn}"
  handler          = "index.handler"
  source_code_hash = "${base64sha256(file("../../lambda.zip"))}"
  runtime          = "nodejs6.10"
  memory_size      = "512"
}
```

### Debug Output

https://gist.github.com/SVT125/15d13b93e369f4612099b49d6fe3b116

### Expected Behavior

The lambda function should've been created within the timeout.

### Actual Behavior

Function creation timed out after 90s.

### Steps to Reproduce

1. `terraform apply`

### References

Another issue which has almost exactly the same problem: https://github.com/pulumi/pulumi-cloud/issues/468

**Comment by oonisim** [comment]
Is using S3 bucket a workaround for this?

**Comment by casertap** [comment]
I am sure using a S3 bucket is a workaround but I think aws_lambda_function should definitely implement custom timeouts.
A simple google search revealed so many people facing this issue. Myself included.

+1
