### ISSUE TITLE
EKS public/ private subnets (load balancers / worker nodes)

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-providers/terraform-provider-aws#5130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [`aws_eks_cluster`](https://www.terraform.io/docs/providers/aws/r/eks_cluster.html) resource in its current configuration does not allow for provisioning of worker nodes to one set of subnets (typically private subnets) while also allowing for load balancers to be provisioned to a separate set of subnets (public subnets) as per [here](https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html). The resource should have provisions that make the distinction between:
1. A list of subnets where worker nodes will be provisioned (i.e. - private facing subnets)
2. A list of subnets where load balancers will be provisioned (i.e. - public facing subnets)

### New or Affected Resource(s)

* aws_eks_cluster

**Comment by bflad** [comment]
Hi @bryantbiggs 👋 You may find the [EKS Getting Started Guide](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html) as a useful reference here.

Configuring Kubernetes worker nodes is not handled by the EKS service and currently left as an exercise to the operator to fit their environment. The `aws_eks_cluster` resource is only intended for managing the Kubernetes control plane, as defined by the EKS API. With respects to the available VPC configuration for EKS clusters, here is the [EKS SDK documentation](https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#VpcConfigRequest):

```
    // Specify one or more security groups for the cross-account elastic network
    // interfaces that Amazon EKS creates to use to allow communication between
    // your worker nodes and the Kubernetes control plane.
    SecurityGroupIds []*string `locationName:"securityGroupIds" type:"list"`

    // Specify subnets for your Amazon EKS worker nodes. Amazon EKS creates cross-account
    // elastic network interfaces in these subnets to allow communication between
    // your worker nodes and the Kubernetes control plane.
    //
    // SubnetIds is a required field
    SubnetIds []*string `locationName:"subnetIds" type:"list" required:"true"`
```

The AWS provider does not limit you from using any of the following resources (among others) to self-manage worker nodes:
* [`aws_autoscaling_group` resource](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html) - an example of this in the EKS Getting Started Guide
* [`aws_instance` resource](https://www.terraform.io/docs/providers/aws/r/instance.html)
* [`aws_spot_instance_request` resource](https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html)
* [`aws_spot_fleet_request` resource](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html)

If you would like the EKS service to support managing worker nodes, you will need to open an AWS support case for that feature request. The EKS team has previously noted that there may be some upcoming potential improvements in this regard on their roadmap.

Beyond that, managing Kubernetes itself within EKS to use separate subnets is likely outside the guidance the maintainers will be able to provide here as we try to limit this repository to bugs or feature requests for the provider code itself. I would suggest reaching out to some of the other available [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html) for questions like that.

Please let us know if you have any additional questions or if the documentation can be improved. Thanks!

**Comment by bryantbiggs** [comment]
Hello @bflad  - thank you for the feedback. I understand that EKS does not manage the worker nodes, only the communication between the master nodes and the worker nodes. Where with the issue was, where in the configuration does EKS discover the intended subnets (i.e. - public subnets) for provisioning internet facing resources like load balancers and gateways. The configuration sets up the connection between the control plan and the subnets where worker nodes will be provisioned (again, those resources are handled outside of the EKS domain), but where does the control plane get the information on the non-worker node subnets where load balancers and gateways can be created. 

In hindsight, I think this more of a question to AWS since I just tried creating a cluster through the ui console and it only asks for subnets where worker nodes will be provisioned (it did not ask where I would like the load balancers and gateways to be provisioned). I will play around more with the EKS service and see where its actually putting resources and reach out to AWS support if necessary - my apologies for the unnecessary issue!

**Comment by chrissnell** [comment]
@bryantbiggs did you ever figure out a solution to this?  It is the responsibility of the Kube control plane to instantiate ELBs and I don't see how it would differentiate between public and private subnets attached.   Have you tried creating both public and private subnets and attaching them to the `aws_eks_cluster` and seeing if the control plane does the smart thing, using the public subnet for public ELBs and the private for private ELBs?
