### ISSUE TITLE
S3 Inventory - Output Bucket Policy Not Created

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-providers/terraform-provider-aws#5137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`v0.11.7`

### Affected Resource(s)

* aws_s3_bucket_inventory

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "test" {
  bucket = "my-tf-test-bucket"
}

resource "aws_s3_bucket" "inventory" {
  bucket = "my-tf-inventory-bucket"
}

resource "aws_s3_bucket_inventory" "test-prefix" {
  bucket = "${aws_s3_bucket.test.id}"
  name   = "DocumentsWeekly"

  included_object_versions = "Current"

  schedule {
    frequency = "Weekly"
  }

  filter {
    prefix = "documents/"
  }

  destination {
    bucket {
      format = "ORC"
      bucket_arn = "${aws_s3_bucket.inventory.arn}"
      prefix = "inventory"
    }
  }
}
```

### Expected Behavior
When adding an inventory configuration to an S3 bucket, a bucket policy should be generated and applied to the output bucket so that S3 is given permission to write the generated output to that location.

### Actual Behavior
No bucket policy is generated/applied to the output bucket which results in an `Access Denied` in the S3 inventory settings (can be seen by navigating to the S3 bucket inventory settings through the console ui - shown below)
<img width="382" alt="image" src="https://user-images.githubusercontent.com/10913471/42508943-5111b200-8418-11e8-8fef-ac23f92fb45b.png">

### Steps to Reproduce

1. `terraform apply`
2. Navigate the the output bucket and view its bucket policy - the necessary policy is not provided. Conversely, wait for S3 to trigger the inventory scan and the `Access Denied` message will appear in the S3 inventory settings through the console ui.

Note: If you set up the inventory configuration manually through the console ui, you will see the message regarding the successful creation of the bucket policy and you can navigate to the output bucket and see the policy there as well.

### References
See [here](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/configure-inventory.html) under `Destination Bucket Policy`

An example policy generated when setting the inventory configuration through the console ui is shown below;
```json
{
    "Version": "2012-10-17",
    "Id": "S3-Console-Auto-Gen-Policy-1531223912192",
    "Statement": [
        {
            "Sid": "S3PolicyStmt-DO-NOT-MODIFY-1531223912192",
            "Effect": "Allow",
            "Principal": {
                "Service": "s3.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::copilot.my-tf-inventory-bucket/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control",
                    "aws:SourceAccount": "xxxxxxxxxxxx"
                },
                "ArnLike": {
                    "aws:SourceArn": "arn:aws:s3:::my-tf-test-bucket"
                }
            }
        }
    ]
}
```

**Comment by bflad** [comment]
Hi @bryantbiggs 👋 Thanks for writing this up.

For background, the AWS provider is for the most part written to be a 1:1 mapping of Terraform resources to API "objects" which follows the general design philosophy of Terraform to provide a declarative configuration of those API objects. This allows operators to have really good flexibility in resource configuration as we try to fully match the underlying API and reduces the maintainer burden of managing our own abstractions.

The AWS console is written in certain situations so it can simplify behavior across multiple API services and calls. This looks like an example of the console trying to do that, where it helps guide you through a full S3 inventory setup by handling multiple pieces of S3 functionality (S3 buckets, S3 bucket policies, and S3 bucket inventory configurations, which are all separate according to the API). Other examples of the console doing this include when it makes required IAM roles optional, where under the hood it automatically creates IAM service roles on your behalf.

Within Terraform, we handle higher level abstractions like these via [Terraform modules](https://www.terraform.io/docs/configuration/modules.html). We likely would not accept something into the provider that tries to combine S3 bucket policy and S3 bucket inventory functionality. Conflicting management of the same API objects generally leads to operator confusion and poor user experience.

Please let us know if you have any questions.

**Comment by bryantbiggs** [comment]
Hello @bflad  - thank you for that insight. That all makes perfect sense; in that case I think I will open a PR to update the `aws_s3_inventory` documentation to make it more clear that a bucket policy on the output bucket is required for the service to work as desired.
