### ISSUE TITLE
Unable to update allowed_oauth_flows_user_pool_client in aws_cognito_user_pool_client

### ISSUE THREAD

**Issue by scala-guy** [terraform-providers/terraform-provider-aws#5140]
### Terraform Version

Terraform v0.10.8
AWS Provider 1.21.0

### Affected Resource(s)
aws_cognito_user_pool_client

* aws_XXXXX

### Expected Behavior

The attribute allowed_oauth_flows_user_pool_client should have been updated from false to true.

### Actual Behavior
Threw error like this:

* aws_cognito_user_pool_client.client.1: Error updating Cognito User Pool Client: InvalidParameterException: AllowedOAuthFlows and AllowedOAuthScopes are required if user pool client is allowed to use OAuth flows.
        status code: 400, request id: bfeb42f0-8401-11e8-a33d-4388ccbed918

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Here are the inputs in my main.tf

resource "aws_cognito_user_pool_client" "client" {
  count = "${var.num_of_clients}"

  name                         = "${element(var.userpoolclients, count.index)}"
  user_pool_id                 = "${aws_cognito_user_pool.pool.id}"
  supported_identity_providers = ["${aws_cognito_identity_provider.provider.provider_name}"]
  callback_urls                = ["${var.callback_url["${element(var.userpoolclients, count.index)}"]}"]
  logout_urls                  = ["${var.logout_url["${element(var.userpoolclients, count.index)}"]}"]
  allowed_oauth_flows          = ["${var.allowed_oauth_flow["${element(var.userpoolclients, count.index)}"]}"]
  allowed_oauth_scopes         = ["${var.allowed_oauth_scope["${element(var.userpoolclients, count.index)}"]}"]
  write_attributes             = "${var.writeattributes}"
  refresh_token_validity       = "${var.num_of_days}"
  **allowed_oauth_flows_user_pool_client = "${var.oauth_flow_enabled}"**
}

**Input values of Oauth flow and Oauth scope** 

  allowed_oauth_flow = {
    "testapp"              = ["implicit", "code"]
  allowed_oauth_scope = {
    "testapp"              = ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"]

  oauth_flow_enabled    = true

* #0000

**Comment by bflad** [comment]
This is _likely_ fixed due to a change just merged to properly pass all defined attributes during update of `aws_cognito_user_pool_client`. That fix will release with version 1.32.0 of the AWS provider, likely middle of next week. If its not fixed with the upcoming version, we can reopen this. 👍
