### ISSUE TITLE
Add bgp_auth_key and customer_address as attributes for aws_dx_private_virtual_interface and aws_dx_public_virtual_interface

### ISSUE THREAD

**Issue by heycasey** [terraform-providers/terraform-provider-aws#5163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kudos to @ewbankkit on the hard work to make these resources a reality.

I am hoping that the following can be added as attributes for export:

* bgp_auth_key
* amazon_address
* customer_address

If these arguments are not specified (bgp_auth_key for ipv4/ipv6, amazon_address and customer_address for ipv6), then they will be auto generated by AWS. Therefore, having those values for use in other scripts would be ideal.

### New or Affected Resource(s)

* [aws_dx_private_virtual_interface](https://www.terraform.io/docs/providers/aws/r/dx_private_virtual_interface.html)
* [aws_dx_public_virtual_interface](https://www.terraform.io/docs/providers/aws/r/dx_public_virtual_interface.html)
* [aws_dx_hosted_private_virtual_interface](https://www.terraform.io/docs/providers/aws/r/dx_hosted_private_virtual_interface.html)
* [aws_dx_hosted_public_virtual_interface](https://www.terraform.io/docs/providers/aws/r/dx_hosted_public_virtual_interface.html)

### Potential Terraform Configuration

```hcl
# Proposed usage

output "prvvif_bgpauthkey" {
  value = "${aws_dx_private_virtual_interface.prvvif.bgp_auth_key}"
}

output "prvvif_awsaddr" {
  value = "${aws_dx_private_virtual_interface.prvvif.amazon_address}"
}

output "prvvif_custaddr" {
  value = "${aws_dx_private_virtual_interface.prvvif.customer_address}"
}
```

### References

* #3248 
* #3249 
* #3250 
* #3251

**Comment by bflad** [comment]
👋  @heycasey (I'm so used to putting Hi in front of names!) -- sorry if there is any confusion here from the documentation. We generally have been changing the verbiage under the `## Attributes` header to say: `In addition to all arguments above, the following attributes are exported:` since for almost all resources, any of the arguments that might get filled in by the API are available to be referenced later on.

Can you confirm if any of these attributes do not actually work? Thanks!

**Comment by heycasey** [comment]
@bflad, looks like those arguments are indeed exportable as attributes. I just tried it, and it works great!
