### ISSUE TITLE
aws_volume_attachment: Should include a note that there are very strict rules for the "device_id" field

### ISSUE THREAD

**Issue by ElectricWarr** [terraform-providers/terraform-provider-aws#5180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I spent some time today on a silly mistake with an invalid value in the `device_id` field of an `aws_volume_attachment`.

I figure it will save others time if we can update the documentation to link directly to [the AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html#available-ec2-device-names) which covers the actual rules, and add a brief note to mention that there _are_ particularly strict rules.

This may be common Linux/AWS domain knowledge, but searching for the error message didn't immediately turn up anything.

### New or Affected Resource(s)

* aws_volume_attachment

**Comment by tomelliff** [comment]
What did you attempt to do and what error message did you get back when you applied it?
