### ISSUE TITLE
GovCloud API for DescribeInstanceCreditSpecificationsRequest breaks aws_instance resource for GovCloud

### ISSUE THREAD

**Issue by renbeynolds** [terraform-providers/terraform-provider-aws#5185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

It appears that the AWS API no longer returns UnsupportedOperation.

### Terraform Version

* Terraform: 11.7
* AWS Provider: 1.16.0 - 1.27.0 (tested each of them)

### Affected Resource(s)

* aws_instance

### Debug Output

Terraform Debug Output: https://gist.github.com/renbeynolds/9686fdcb9367ca1393235a9993aa2635
AWS Cloud Trail Event: https://gist.github.com/renbeynolds/36c891245379be4891907ec6b316e55d

### Expected Behavior

`terraform refresh` should complete successfully

### Actual Behavior

`terraform refresh`  eventually (~1.5hrs) times out with 500 error

### Steps to Reproduce

1. Create an `aws_instance` resource
2. `terraform apply`
2. `terraform refresh`

### Suggestion
Edit https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_instance.go to error handle more generically.

**Comment by bflad** [comment]
Yikes. Please submit AWS Support tickets regarding this if you haven't done so already. 😖 

While we might be able to get something shimmed into the AWS provider, the quickest response will be getting the EC2 API team to fix the API.

**Comment by bflad** [comment]
Is this still an issue for anyone? Looks like it might have resolved itself.

**Comment by renbeynolds** [comment]
Just confirmed and the issue seems to have been resolved! Verified working with 1.27.0
