### ISSUE TITLE
Terraform aws instance state change

### ISSUE THREAD

**Issue by raghuarss** [terraform-providers/terraform-provider-aws#5213]
I would like to know if we have any option to change the state of AWS EC2 instance using Terraform from stop to running and vice versa. 

Till my knowledge we have an option to deploy an instance and by default the instance will start running. I don't see any terraform code that helps the engineer to start/stop the instance. If we do have.. please guide.

**Comment by bflad** [comment]
Hi @raghuarss 👋  Thanks for writing this up! We actually have some issues already open requesting this functionality: #22, #190, and #569

To consolidate any efforts and discussion, I'm going to close this one in preference of those. 👍
