### ISSUE TITLE
Fix the access policy JSON in the ES domain docs

### ISSUE THREAD

**Issue by vikramjakhr** [terraform-providers/terraform-provider-aws#5232]
Add the comma(,) after Resource key value pair in elasticsearch domain access policy doc.

https://github.com/terraform-providers/terraform-provider-aws/commit/0a84a62df499be84b6b5493fa470c9210c815ecc#diff-6cfb192f210b8a4ba2d2d7dbc0961677

**Comment by bflad** [comment]
Thanks for the heads up @vikramjakhr -- documentation fix pull request submitted: #5296
