### ISSUE TITLE
aws_ecr_lifecycle_policy is flagged for recreation every single plan/apply despite no actual changes present in code.

### ISSUE THREAD

**Issue by kiwivogel** [terraform-providers/terraform-provider-aws#5233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.26.0
+ provider.template v1.0.0
+ provider.terraform v1.0.2

```

### Affected Resource(s)

* aws_ecr_lifecycle_policy

### Terraform Configuration Files

```hcl
resource "aws_ecr_repository" "repo" {
  count = "${length(var.ecr_repositories)}"
  name  = "REDACTED/${element(var.ecr_repositories, count.index)}"
}

resource "aws_ecr_lifecycle_policy" "cleanup_policies" {
  count      = "${length(var.ecr_repositories)}"

  repository = "${element(aws_ecr_repository.repo.*.name, count.index)}"
  policy     = <<EOF
{
    "rules": [
        {
            "rulePriority": 2,
            "description": "Keep last 50 experimental images",
            "selection": {
                "tagStatus": "tagged",
                "tagPrefixList": ["x_"],
                "countType": "imageCountMoreThan",
                "countNumber": 50
            },
            "action": {
                "type": "expire"
            }
        },
        {
            "rulePriority": 1,
            "description": "Keep last 100 normal images",
            "selection": {
                "tagStatus": "tagged",
                "tagPrefixList": ["20"],
                "countType": "imageCountMoreThan",
                "countNumber": 100
            },
            "action": {
                "type": "expire"
            }
        }
    ]
}
EOF
}

resource "aws_ecr_repository_policy" "repository_policy" {
  count      = "${length(var.ecr_repositories)}"

  repository = "${element(aws_ecr_repository.repo.*.name, count.index)}"
  policy     = <<EOF
{
	"Version": "2008-10-17",
	"Statement": [{
		"Sid": "PullECRImages",
		"Effect": "Allow",
		"Principal": {
			"AWS": ["REDACTED"]
		},
		"Action": ["ecr:BatchGetImage", "ecr:ListImages", "ecr:GetDownloadUrlForLayer", "ecr:BatchCheckLayerAvailability"]
	}]
}
EOF
}
```
+ a tfvars file containing 
```
ecr_repositories = [
    REDACTED, list of 127 arbitrary image names.
]
``` 

### Expected Behavior

Terraform plan should return
```
Plan: 0 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

Terraform returns 
```
Plan: 127 to add, 0 to change, 127 to destroy.
```
[gist of 'changes' found for one of 127 resources](https://gist.github.com/kiwivogel/1f344f0de4a3a6bd851973e48f4815d2)
actual tag/repo name obviously redacted but they are not changed anyway.
### Steps to Reproduce
1. Run a plan with above configuration 

### Important Factoids

The code above worked fine for aws_ecr_repository_policy, but when using the same setup with the aws_ecr_lifecycle_policy it forces recreation of all 127 policies 
```hcl
 count      = "${length(var.ecr_repositories)}"
 repository = "${element(aws_ecr_repository.repo.*.name, count.index)}"
``` 

### References

* #0000

**Comment by kiwivogel** [comment]
Yup. Solves it. Want me do add the note in the documentation?

**Comment by bflad** [comment]
Your documentation note will go out with version 1.30.0 of the AWS provider next week. 👍
