### ISSUE TITLE
Support performance insights on PostgreSQL RDS (non-aurora)

### ISSUE THREAD

**Issue by fields** [terraform-providers/terraform-provider-aws#5259]
Hi - 

Performance insights for non-aurora PostgreSQL RDS databases is now in GA. 

https://aws.amazon.com/about-aws/whats-new/2018/04/rds-performance-insights-on-rds-for-postgresql/

It would be great if this could be added to the resource definition.

Thanks!

**Comment by yuriipolishchuk-finsight** [comment]
Is there any update on that?

**Comment by aodj** [comment]
What's the status of this issue? 2 closed PR's and 1 (relevant) open PR with no end in sight.

**Comment by bflad** [comment]
Support for performance insights configuration with the `aws_db_instance` resource has been merged and will release with version 2.12.0 of the Terraform AWS Provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 2.12.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2120-may-24-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
