### ISSUE TITLE
terraform forces new resource for stopped ec2 instance with "associate_public_ip_address = true"

### ISSUE THREAD

**Issue by stszap** [terraform-providers/terraform-provider-aws#5265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.25.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "v1.25.0"
  region  = "us-east-2"
  profile = "<profile name>"

  assume_role = {
    role_arn = "arn:aws:iam::<account id>:role/Terraform"
  }
}

resource "aws_instance" "current" {
	ami                         = "ami-5e8bb23b"
  instance_type               = "t2.nano"
  associate_public_ip_address = true
}
```

### Expected Behavior

Do nothing.

### Actual Behavior

Terraform tries to recreate ec2 instance.

```
Terraform will perform the following actions:

-/+ aws_instance.current (new resource required)
      id:                           "i-01a78d9e8d341adb2" => <computed> (forces new resource)
      ami:                          "ami-5e8bb23b" => "ami-5e8bb23b"
      associate_public_ip_address:  "false" => "true" (forces new resource)
      availability_zone:            "us-east-2c" => <computed>
      ebs_block_device.#:           "0" => <computed>
      ephemeral_block_device.#:     "0" => <computed>
      get_password_data:            "false" => "false"
      instance_state:               "stopped" => <computed>
      instance_type:                "t2.nano" => "t2.nano"
      ipv6_address_count:           "" => <computed>
      ipv6_addresses.#:             "0" => <computed>
      key_name:                     "" => <computed>
      network_interface.#:          "0" => <computed>
      network_interface_id:         "eni-06f64be782f5bef8f" => <computed>
      password_data:                "" => <computed>
      placement_group:              "" => <computed>
      primary_network_interface_id: "eni-06f64be782f5bef8f" => <computed>
      private_dns:                  "ip-172-31-33-169.us-east-2.compute.internal" => <computed>
      private_ip:                   "172.31.33.169" => <computed>
      public_dns:                   "" => <computed>
      public_ip:                    "" => <computed>
      root_block_device.#:          "1" => <computed>
      security_groups.#:            "1" => <computed>
      source_dest_check:            "true" => "true"
      subnet_id:                    "subnet-a326d2ef" => <computed>
      tenancy:                      "default" => <computed>
      volume_tags.%:                "0" => <computed>
      vpc_security_group_ids.#:     "1" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

If you create a ec2 instance with "associate_public_ip_address" set to "true", then stop it and run `terraform apply` then terrafrom tries to recreate the instance,  If you start the instance again then `terraform apply` returns an empty plan as it should. I suspect that it is due to the fact that there is no way to get back the value of  "AssociatePublicIpAddress" ec2 api option and terraform just looks if instance has a public ip. 

* #0000

**Comment by mrballcb** [comment]
Add to your instances which you know are going to be stopped:
```
  lifecycle {
    ignore_changes = ["associate_public_ip_address"]
  }
```
...then terraform plan and terraform apply will not trigger if the public ip address is not set (because it's off and doesn't have a public IP).

If your complaint is that it should always ignore it because the state is powered off, I guess that's a feature request and not just a bug report, depending on your definition of "performs as expected".

**Comment by stszap** [comment]
I think ideally tarraform would be able to determine that an ec2 instance was created with `associate_public_ip_address: true` even when the instance is stoped and just leave it be, but it's probably almost impossible with current aws api. Thank you for the workaroud, it solves the probblem for me. I will close the issue then.
