### ISSUE TITLE
New datasource request: aws_launch_template

### ISSUE THREAD

**Issue by Defozo** [terraform-providers/terraform-provider-aws#5272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Datasource that returns AWS launch template.

### New Resource

* aws_launch_template

### Potential Terraform Configuration

Similar to aws_launch_configuration: https://terraform.io/docs/providers/aws/d/launch_configuration.html

**Comment by bflad** [comment]
The new `aws_launch_template` data source has been merged and will release with version 1.40.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.40.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1400-october-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
