### ISSUE TITLE
AWS instance gets recreated after each run

### ISSUE THREAD

**Issue by peterhorvath** [terraform-providers/terraform-provider-aws#5302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform version
Terraform v0.11.7
+ provider.aws v1.24.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "aws-ec2-dxm-dev-mgmt-jmp01a-cc1" {
  ami = "${data.aws_ami.aws-ami-dxm-dev-cc1.id}"
  instance_type = "t2.micro"
  key_name = "ssh-dxm-dev"
  associate_public_ip_address = false
  availability_zone = "ca-central-1a"
  subnet_id = "${aws_subnet.aws-sn-dxm-dev-mgmt-jmp01a-cc1.id}"
  security_groups = [ "${data.aws_security_group.aws-sg-dxm-dev-mgmt-jmp01-cc1.id}" ]
  
  tags = {
    Name = "jmp0001-aws-mgmt-cc1.dev.dxm.xxxx.com"
    Terraform = "true"
    Environment = "dev"
  }
}
```

### Expected Behavior

Terraform should have a state for instance and should not try to recreate the instance every time.

### Actual Behavior

Terraform wants to recreate the instance because of the ID and security group seems not to be associated according to terraform

```hcl
-/+ aws_instance.aws-ec2-dxm-dev-mgmt-jmp01a-cc1 (new resource required)
      id:                           "i-033830d895977b9ec" => <computed> (forces new resource)
      ami:                          "ami-00870a64" => "ami-00870a64"
      associate_public_ip_address:  "true" => <computed>
      availability_zone:            "ca-central-1a" => "ca-central-1a"
      ebs_block_device.#:           "1" => <computed>
      ephemeral_block_device.#:     "0" => <computed>
      get_password_data:            "false" => "false"
      instance_state:               "running" => <computed>
      instance_type:                "t2.micro" => "t2.micro"
      ipv6_address_count:           "" => <computed>
      ipv6_addresses.#:             "0" => <computed>
      key_name:                     "ssh-dxm-dev" => "ssh-dxm-dev"
      network_interface.#:          "0" => <computed>
      network_interface_id:         "eni-511b800f" => <computed>
      password_data:                "" => <computed>
      placement_group:              "" => <computed>
      primary_network_interface_id: "eni-511b800f" => <computed>
      private_dns:                  "ip-10-128-0-174.ca-central-1.compute.internal" => <computed>
      private_ip:                   "10.128.0.174" => <computed>
      public_dns:                   "ec2-xx-xx-xx-xx.ca-central-1.compute.amazonaws.com" => <computed>
      public_ip:                    "xx.xx.xx.xx" => <computed>
      root_block_device.#:          "1" => <computed>
      security_groups.#:            "0" => "1" (forces new resource)
      security_groups.1065083510:   "" => "sg-5a612531" (forces new resource)
      source_dest_check:            "true" => "true"
      subnet_id:                    "subnet-042a9e6c" => "subnet-042a9e6c"
      tags.%:                       "3" => "3"
      tags.Environment:             "dev" => "dev"
      tags.Name:                    "jmp0001-aws-mgmt-cc1.dev.dxm.xxx.com" => "jmp0001-aws-mgmt-cc1.dev.dxm.xxx.com"
      tags.Terraform:               "true" => "true"
      tenancy:                      "default" => <computed>
      volume_tags.%:                "0" => <computed>
      vpc_security_group_ids.#:     "1" => <computed>
```

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @peterhorvath 👋 

Does the Terraform plan difference go away if you use the `vpc_security_group_ids` attribute instead of `security_groups`?

Unfortunately the EC2 API has some confusing overlap between API parameter naming with EC2-Classic (`security_groups`) and VPC (`vpc_security_group_ids`). When working in a VPC setup, like it appears you are with `subnet_ids`, the API will sometimes accept the older parameter but always return it in the correct spot, which Terraform notes as a difference that requires recreating the EC2 instance since it cannot be updated in EC2-Classic.

Please let us know and if you have any documentation suggestions. Thanks!

**Comment by peterhorvath** [comment]
Indeed it resolved it! Thanks!
