### ISSUE TITLE
REGIONAL (not edge) aws_api_gateway_domain_name - Err msg Cert must exist in us-east-1

### ISSUE THREAD

**Issue by tburt11** [terraform-providers/terraform-provider-aws#5305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

+ Terraform v0.11.0
+ provider.aws v1.27.0

### Affected Resource(s)

* aws_api_gateway_domain_name

### Terraform Configuration Files

resource "aws_api_gateway_rest_api" "primary" {
  name          = "${local.api_name}"
  description   = "API for ${var.xxx_vpc}"
  endpoint_configuration {
    types     = [ "REGIONAL" ]
  }
}

resource "aws_api_gateway_domain_name" "primary" {
  domain_name = "tfapi-${var.xxx_env}.${var.xxx_account}.xxx.com"
  certificate_arn        = "${data.aws_acm_certificate.primary.arn}"
}

data "aws_acm_certificate" "primary" {
  domain   = "tfapi-${var.xxx_env}.${var.xxx_env}.xxx.com"
  types = ["AMAZON_ISSUED"]
  most_recent = true
}

### Expected Behavior

Creation of REGIONAL api gateway resource with Custom Domain Name

### Actual Behavior

ERROR

aws_api_gateway_domain_name.primary: Error creating REGIONAL API Gateway Domain Name: 

BadRequestException: Invalid certificate ARN: arn:aws:acm:us-west-2:XXXXXXXXX:certificate/XXXXXXX-280e-4f94-a20b-44a9c711efbb. Certificate must be in 'us-east-1'.

### Steps to Reproduce

Configure a REGIONAL api gateway and try to assign a domain name.

### Important Factoids

Provider responds with assertion that cert must be in 'us-east-1' which is NOT TRUE for a Regional api-gateway.  A REGIONAL api-gateway requires the cert be in the local region.

BadRequestException: Invalid certificate ARN: arn:aws:acm:us-west-2:XXXXXXXXX:certificate/XXXXXXX-280e-4f94-a20b-44a9c711efbb. Certificate must be in 'us-east-1'.

If a cert is present in us-east-1 as well as local region, then an Edge Optimized Custom Domain Name is created (should be regional) and the Domain fails to initialize.

### References

* #0000

**Comment by bflad** [comment]
Hi @tburt11 👋 

FYI [triple backticks will format code blocks in GitHub](https://guides.github.com/features/mastering-markdown/) to make them more readable.

Looking at your configuration above, it looks like `endpoint_configuration` is missing from here, which would default to creating an `EDGE` domain name:

```hcl
resource "aws_api_gateway_domain_name" "primary" {
  domain_name = "tfapi-${var.xxx_env}.${var.xxx_account}.xxx.com"
  certificate_arn = "${data.aws_acm_certificate.primary.arn}"
}
```

If you add it, does this work as expected? e.g.

```hcl
resource "aws_api_gateway_domain_name" "primary" {
  domain_name = "tfapi-${var.xxx_env}.${var.xxx_account}.xxx.com"
  certificate_arn = "${data.aws_acm_certificate.primary.arn}"
  endpoint_configuration {
    types = [ "REGIONAL" ]
  }
}
```

**Comment by tburt11** [comment]
Good catch..  I did not know the type needs defining in two places.

**Comment by bflad** [comment]
Closing as this should be fixed with the above configuration update. If its not resolved, please let us know. 👍
