### ISSUE TITLE
Resource "aws_ecs_task_definition" shows as modified each time terraform is applied

### ISSUE THREAD

**Issue by geeshans** [terraform-providers/terraform-provider-aws#5323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.28.0
### Affected Resource(s)

aws_ecs_task_definition

### Terraform Configuration Files

```hcl
resource "aws_ecs_task_definition" "web" {
  family                   = "web"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "${var.web_fargate_cpu}"
  memory                   = "${var.web_fargate_memory}"
  container_definitions    = "${data.template_file.web_task_definition.rendered}"
  execution_role_arn       = "${aws_iam_role.ecs_execution_role.arn}"
  

}

resource "aws_ecs_task_definition" "app" {
  family                   = "app" 
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "${var.app_fargate_cpu}"
  memory                   = "${var.app_fargate_memory}"
  container_definitions    = "${data.template_file.app_task_definition.rendered}"
  execution_role_arn       = "${aws_iam_role.ecs_execution_role.arn}"
}

```

### Expected Behavior

No resources should show as changed

### Actual Behavior

aws_ecs_task_definition shows as modified which in turn rebuild that resource

```
-/+ aws_ecs_task_definition.app (new resource required)
      id:                                  "app" => <computed> (forces new resource)
      arn:                                 "arn:aws:ecs:us-east-1:496391058917:task-definition/app:38" => <computed>
```
### Steps to Reproduce

1. `terraform apply`

### References
* #2417

**Comment by bflad** [comment]
Hi @geeshans 👋  Sorry you are running into unexpected behavior.

It looks like the `terraform plan` output might be cutoff above. Can you please post the rest of it? The details (likely a change in `container_definitions`) are important for helping troubleshoot your issue. If it is `container_definitions`, it might be worthwhile to also see your configuration for `data "template_file" "app_task_definition"`.

Thanks!

**Comment by fabian-dev** [comment]
Your container definitions' portMapping config misses the hostPort. This issue is a duplicate of #3401

**Comment by geeshans** [comment]
Yes adding a `hostPort` which needs to be same as the `containerPort` when using `networkMode=awsvpc` fixed the issue. 

```
    "portMappings": [
      {
        "hostPort": 80,
        "containerPort": 80,
        "protocol": "tcp"
      }
```

Thank you!
