### ISSUE TITLE
data source aws_eip is failing with "multiple Elastic IPs matched; use additional constraints to reduce matches to a single Elastic IP

### ISSUE THREAD

**Issue by michael-c-jones** [terraform-providers/terraform-provider-aws#5333]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.7

### Affected Resource(s)

* aws_eip data source

### Terraform Configuration Files

```hcl
data "aws_eip" "connect_nlb" {
  count = "${length(var.eips)}"
  id = "${element(var.eips, count.index)}"
}
```

### Debug Output
```
* module.connect_app_static.data.aws_eip.connect_nlb[0]: data.aws_eip.connect_nlb.0: multiple Elastic IPs matched; use additional constraints to reduce matches to a single Elastic IP
* module.connect_app_static.data.aws_eip.connect_nlb[2]: data.aws_eip.connect_nlb.2: multiple Elastic IPs matched; use additional constraints to reduce matches to a single Elastic IP
* module.connect_app_static.data.aws_eip.connect_nlb[3]: data.aws_eip.connect_nlb.3: multiple Elastic IPs matched; use additional constraints to reduce matches to a single Elastic IP
* module.connect_app_static.data.aws_eip.connect_nlb[1]: data.aws_eip.connect_nlb.1: multiple Elastic IPs matched; use additional constraints to reduce matches to a single Elastic IP
```

### Expected Behavior
Terraform should return only one aws_eip data source

### Actual Behavior
Errors, noted above.

### Steps to Reproduce
This issue suddenly occurred today, 7/25/18.  Terraform runs with the same version and provider functioned as expected for approximately six months, up to 7/24/18.

Everywhere (22 locations) I use the aws_eip data source now exhibit this error, which appears to be triggered from this code:

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_eip.go#L52-L54

### Important Factoids
The most important factoid here is the fact that this error suddenly happened on the morning of 7/25/18, and it happens verywhere I use the aws_eip data source.  No other changes in terraform or aws provider versions correlate with the appearance of this defect.  It appears to be a change in how the aws APIs are functioning.

If I use this command
```
aws ec2 describe-addresses --filters Name=allocation-id,Values=eipalloc-XXXX
```
I get this output, containing only one address:
```
{
    "Addresses": [
        {
            "PublicIp": "34.195.XXX.XXX",
            "AllocationId": "eipalloc-XXXXXXXX",
            "AssociationId": "eipassoc-XXXXXXXX",
            "Domain": "vpc",
            "NetworkInterfaceId": "eni-XXXXXXXX",
            "NetworkInterfaceOwnerId": "XXXXXXXXXXXX",
            "PrivateIpAddress": "10.XXXXXX.XXX"
        }
    ]
}

```

### References

* #0000

**Comment by rv-aburdine** [comment]
This looks related to #5330

**Comment by michael-c-jones** [comment]
bingo.  Inconsistent output and two ip addresses:

```{
    "Addresses": [
        {
            "InstanceId": "",
            "PublicIp": "50.XXX.XXX.XXX",
            "Domain": "standard"
        },
        {
            "InstanceId": "",
            "PublicIp": "50.XXX.XXX.XXX",
            "Domain": "standard"
        },
        {
            "PublicIp": "34.195.XXX.XXX",
            "AllocationId": "eipalloc-XXXXXX",
            "AssociationId": "eipassoc-XXXXXXXX",
            "Domain": "vpc",
            "NetworkInterfaceId": "eni-XXXXXXXX,
            "NetworkInterfaceOwnerId": "XXXXXXXXX",
            "PrivateIpAddress": "10.XXX.XXX.XXX"
        }
    ]
}
```

**Comment by michael-c-jones** [comment]
This does appears to be related to 5330.  Works again now.

**Comment by bflad** [comment]
Since it appears this was resolved upstream in the API, going to close this issue out. 👍
