### ISSUE TITLE
data amq broker needs to have list of broker names 

### ISSUE THREAD

**Issue by mnikhil-git** [terraform-providers/terraform-provider-aws#5343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have activeMQ running in active-standby mode. I need a data resource to get the list of broker names.
 
### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Hi @mnikhil-git 👋  Can you please provide a sample configuration of what you are looking for?

**Comment by bflad** [comment]
Closing due to lack of response.
