### ISSUE TITLE
aws_lambda_event_source_mapping for SQS creates an invalid mapping

### ISSUE THREAD

**Issue by repl-sean-heintz** [terraform-providers/terraform-provider-aws#5354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.0
+ provider.aws v1.26.0

### Affected Resource(s)

* aws_lambda_function
* aws_lambda_event_source_mapping
* aws_sqs_queue

### Terraform Configuration Files

https://github.com/repl-sean-heintz/terraform-sqs-lambda-issue

Minimum viable repro.

### Debug Output

https://gist.github.com/repl-sean-heintz/fc3171e319516d386f67c73413c2e729

### Expected Behavior

1. The lambda is created successfully.
2. The queue is created successfully.
3. A single event-source mapping is created which connects SQS to the lambda with a batch size of 1 and a state of "enabled".

### Actual Behavior

(Please ignore the useless censorship)

1. An extra event-source mapping is created and visible in the UI:
![image](https://user-images.githubusercontent.com/24462801/43285923-bc3434be-90dd-11e8-9d6a-33f63a136a4d.png)

2. The event-source mapping cannot be deleted manually:
![image](https://user-images.githubusercontent.com/24462801/43285899-aa63ca88-90dd-11e8-9c90-efa849401d9a.png)

3. The invalid event-source mapping does not appear in the CLI:
![image](https://user-images.githubusercontent.com/24462801/43286378-0dfdfb76-90df-11e8-9ebb-7fbd5b272796.png)

4. On future deployments of the terraform, the **valid** event-source mapping can end up in a "disabled" state with no indication in the logs. This is intermittent and cannot be reliably reproduced.

### Steps to Reproduce

1. Check out the reproduction repository.

2. `terraform apply`

3. Validate the state of the event-source-mapping in the AWS UI.

**Comment by cdornsife** [comment]
I think the `aws_lambda_permission` is your problem. I am pretty sure it adds a mapping. Remove the 
 resource "aws_lambda_permission" "platform_operations" and try it again.
