### ISSUE TITLE
RDS create from snapshot results in "InvalidParameterValue: The parameter ResourceName must be provided and must not be blank." error

### ISSUE THREAD

**Issue by scottmoomaw** [terraform-providers/terraform-provider-aws#5360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.7

### Affected Resource(s)

* aws_db_instance

### Expected Behavior

RDS instance created from snapshot

### Actual Behavior

* aws_db_instance.your_name_here: 1 error(s) occurred:
* aws_db_instance.your_name_here: InvalidParameterValue: The parameter ResourceName must be provided and must not be blank.
status code: 400, request id: 0c2c6a32-ae88-434e-bc5a-7a6242f6bee7
### Steps to Reproduce

1. Upgrade aws-provider to 1.29.0
2. `terraform apply`

### Important Factoids

There is a defect in version 1.29.0 of the aws-provider that causes failure of RDS creation becasue of error copying tags.  The 1.29.0 version attempts to use an empty 'ResourceName=' value in a query.  This behavior does not occur if you lock the aws-provider to version 1.28.0.

* #0000

**Comment by tinyzimmer** [comment]
This happened to me on testing my RDS module against the newest provider version. The database instances were created, but the module ultimately failed out with the same error posted above.

Reverting to provider 1.28 solves the issue for me as well.

**Comment by fantomc0der** [comment]
I just bumped into this issue a minute ago in v0.10.8. I have an existing RDS instance in Terraform that's been working fine for a while and attempted adding a property for "snapshot_identifier" which points to the ARN of the shared snapshot with the account. In order to test it, I started to deploy a fresh RDS instance from its root module after verifying the planning looked good (all adds, no errors). It seemed like it was working as it remained processing for around 20min until it errored on  "aws_db_instance.primary: InvalidParameterValue: The parameter ResourceName must be provided and must not be blank."

**Comment by fantomc0der** [comment]
Thanks for the quick response. Pinned my AWS Provider to 1.28.0 and worked as expected.

**Comment by bflad** [comment]
Fix verified and submitted: #5370

**Comment by bflad** [comment]
The fix for this has been merged into master and will release with version 1.30.0 of the AWS provider, likely on Wednesday. 👍

**Comment by bflad** [comment]
This has been released in [version 1.30.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1300-august-02-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
