### ISSUE TITLE
Missed "UpdatePolicy" Attribute in resource "aws_autoscaling_group"

### ISSUE THREAD

**Issue by ozbillwang** [terraform-providers/terraform-provider-aws#5361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Missed `UpdatePolicy` Attribute in resource `aws_autoscaling_group`

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-replacingupdate

### New or Affected Resource(s)

* aws_autoscaling_group

### Potential Terraform Configuration

```hcl
"UpdatePolicy" : {
  "AutoScalingReplacingUpdate" : {
    "WillReplace" : Boolean
  }
}

"UpdatePolicy" : {
  "AutoScalingRollingUpdate" : {
    "MaxBatchSize" : Integer,
    "MinInstancesInService" : Integer,
    "MinSuccessfulInstancesPercent" : Integer
    "PauseTime" : String,
    "SuspendProcesses" : [ List of processes ],
    "WaitOnResourceSignals" : Boolean
  }
}

```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-replacingupdate

* #0000

**Comment by ozbillwang** [comment]
I have the feeling, that this issue has been identified before, so someone worked around it with a CFN template.

https://github.com/terraform-providers/terraform-provider-aws/issues/4577

https://github.com/terraform-providers/terraform-provider-aws/issues/4432

https://github.com/terraform-providers/terraform-provider-aws/issues/5273

**Comment by bflad** [comment]
Hi @ozbillwang 👋 Can you point to the [API reference documentation](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/Welcome.html) for which 
 API actions/parameters would handle this? I feel like the last time I looked this up, it seemed like this was something only built into CloudFormation and not part of the API, but maybe I missed it or the situation has changed.

**Comment by ozbillwang** [comment]
@bflad 

Thanks to point this. I have confirmed with AWS via support ticket. This feature is only in Cloudformation, not in API currently, a ticket had been raised to API team to add this feature, but not sure when it can be implemented.

This UpdatePolicy calls API to adjust desired capacity, so we have to use Cloudformation template in Terraform currently, otherwise,  frequently adjust desired capacity (for example, increase 2, wait, decrease 2, until all instances to be replaced with new setting).
