### ISSUE TITLE
aws_spot_fleet_request does not support security_groups

### ISSUE THREAD

**Issue by junaid18183** [terraform-providers/terraform-provider-aws#5362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The SecurityGroups parameter is not supported in launch_specification section of the "aws_spot_fleet_request" while the AWS API/CLI supports it.

If we omit it the instances get attached to the default security group

### New or Affected Resource(s)

aws_spot_fleet_request

### Potential Terraform Configuration
```hcl
provider "aws" {
}

resource "aws_spot_fleet_request" "spot" {
  iam_fleet_role      = "arn:aws:iam::123456789123:role/aws-ec2-spot-fleet-tagging-role"
  allocation_strategy = "lowestPrice"
  #allocation_strategy = "diversified"
  target_capacity     = 16
  valid_until         = "2019-11-04T20:44:20Z"


  launch_specification {
    instance_type             = "c5.4xlarge"
    ami                       = "ami-b75a6acb"
    key_name                  = "mykey"
    iam_instance_profile_arn  = "arn:aws:iam::123456789123:instance-profile/ecs_instance_role-ap-southeast-1"
    availability_zone         = "ap-southeast-1a"
    subnet_id                 = "subnet-123456789123"
    weighted_capacity         = 16
    security_groups          = [ "sg-123456789123" ]

    tags {
      Name = "ECS-Cluster-Node"
    }
  }
}

```
$ terraform plan

Error: aws_spot_fleet_request.spot: launch_specification.0: invalid or unknown key: security_groups

### References
https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html

The CLI for spot-fleet Launch specification supports "SecurityGroups"

https://docs.aws.amazon.com/cli/latest/reference/ec2/request-spot-fleet.html

**Comment by junaid18183** [comment]
Apparently its a configuration issue, the right key to be used is - vpc_security_group_ids not the security_groups

**Comment by JIoJIaJIu** [comment]
I've faced with the same issue
`vpc_security_group_ids` works well. It would be great if you extend [your documentation](https://www.terraform.io/docs/providers/aws/r/spot_fleet_request.html#launch_specification) with the info  rather then link to aws docs where [GroupIds](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetLaunchSpecification.html) are using
