### ISSUE TITLE
Tags cannot be updated on redis aws_elasticache_replication_group resources

### ISSUE THREAD

**Issue by mikefodor** [terraform-providers/terraform-provider-aws#5366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

\> ./terraform -v
Terraform v0.11.7
\+ provider.aws v1.29.0

### Affected Resource(s)

* aws_elasticache_replication_group

### Terraform Configuration Files

```hcl
provider "aws" {
  shared_credentials_file = "CREDENTIAL_FILE"
  profile                 = "AWS_PROFILE"
  region                  = "us-east-1"
}

resource "aws_elasticache_replication_group" "test-redis" {
  replication_group_id          = "test-redis"
  replication_group_description = "test-redis"
  node_type                     = "cache.t2.medium"
  engine                        = "redis"
  engine_version                = "3.2.4"
  parameter_group_name          = "default.redis3.2"
  port                          = 6379
  number_cache_clusters         = 1 
  automatic_failover_enabled    = false

  security_group_ids = ["${var.redis-sg}"]
  subnet_group_name  = "${aws_elasticache_subnet_group.default.name}"

  tags {
    Name        = "TestRedis"
    Environment = "Dev"
    CostCenter  = "Cost"
    tagone      = "oldtag1"
    tagtwo      = "oldtag2"
    tagthree    = "oldtag3"
  }
}

resource "aws_elasticache_subnet_group" "default" {
  name       = "test-subnet"
  subnet_ids = ["SUBNET-ID1", "SUBNET-ID2"]
}
```

### Debug Output

https://gist.github.com/mikefodor/b41dc4ad06897b66355366babd0e8e05

### Expected Behavior

The Tags on existing cache clusters in the aws_elasticache_replication_group should be updated with the new values.

### Actual Behavior

When applying changes to the tags on the aws_elasticache_replication_group the tags on the 
Terraform behaves like it applied the change but no change was made in AWS

```
aws_elasticache_replication_group.test-redis: Modifying... (ID: test-redis)
  tags.tagone:   "oldtag1" => "newtag1"
  tags.tagthree: "oldtag3" => "newtag3"
  tags.tagtwo:   "oldtag2" => "newtag2"
aws_elasticache_replication_group.test-redis: Still modifying... (ID: test-redis, 10s elapsed)
aws_elasticache_replication_group.test-redis: Still modifying... (ID: test-redis, 20s elapsed)
aws_elasticache_replication_group.test-redis: Modifications complete after 20s (ID: test-redis)
```

If new cache clusters are created in this aws_elasticache_replication_group they have the old set of tags.  The tags only get applied on the initial creation of the aws_elasticache_replication_group.  To apply a new set of tags appears to require destroying and rebuilding the aws_elasticache_replication_group.

### Steps to Reproduce

1. `terraform apply`
2. Modify tags in the redis-test.tf file
3. `terraform apply` 
### References

* #5064
I'm aware of the issue with elasticache tagging on cross accounts but this doesn't seem related.  Cross account roles are not being used in this case and there are no errors generated by terraform when trying to create or modify the resources.

**Comment by bflad** [comment]
This is semi-related to #1615 -- the Elasticache API and Terraform treat the underlying Elasticache clusters as separate resources compared to the top level replication group.

**Comment by mangobatao** [comment]
@bflad but the first time you create the replication group it will be populated to the underlying clusters, do you have any workaround for this?

**Comment by rneu31** [comment]
Running into the same issue myself. @bflad @mangobatao have either of you found a workaround? Appreciate it.

**Comment by rneu31** [comment]
Running into the same issue myself. @bflad @mangobatao have either of you found a workaround? Appreciate it.

**Comment by zhangxin511** [comment]
@bflad @mikefodor  I am experiencing related problem: https://github.com/terraform-providers/terraform-provider-aws/issues/5021

I tried to destroy and applied a new one, the problem is able to workaround. I am using an older version though:
```
λ terraform version
Terraform v0.11.14
+ provider.aws v2.24.0

Your version of Terraform is out of date! The latest version
is 0.12.6. You can update by downloading from www.terraform.io/downloads.html
```

**Comment by mangobatao** [comment]
@zhangxin511 what's your workaround? can you share the details?

**Comment by zhangxin511** [comment]
@mangobatao Sorry for confuse you, I mean by run `terraform destroy` and `terraform apply`, the tags will be "updated". The problem of this bug is tags can only by added first time the terraform applied.

**Comment by ryndaniels** [comment]
Hi @mikefodor - as noted [here](https://github.com/terraform-providers/terraform-provider-aws/issues/1615#issuecomment-527963971), this functionality isn't supported by the AWS API right now, and since we as a general rule are only committing to providing the same functionality supported by the underlying APIs, this ability to modify tags isn't something that we're planning to add right now.

**Comment by BenMusch** [comment]
Does this same issue apply to `aws_elasticache_cluster` resources?
