### ISSUE TITLE
Enforce AWS-defined tag restrictions

### ISSUE THREAD

**Issue by philbal611** [terraform-providers/terraform-provider-aws#5369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Similar to [Azure](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags), aws has defined [restrictions](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/allocation-tag-restrictions.html) on user defined tags. It would be helpful if Terraform checked against user defined tags in aws resources the same way it [checks](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/tags.go#L48) against tags defined in azurerm resources.

### New or Affected Resource(s)

* all tag supporting resources

### References

* #0000

**Comment by bflad** [comment]
@philbal611 this logic should be handled per AWS service. Those specific restrictions may only apply to the billing service(s) since it is specifically in the billing service documentation.

**Comment by bflad** [comment]
Ah, sorry I mistaking billing for budgets -- I would still caution against global tagging restrictions due to potential differences in AWS service implementations.

**Comment by philbal611** [comment]
Ahhh understood. I'm writing Sentinel policies to enforce a tagging taxonomy for both providers and noticed that with azurerm resources were caught before planning. As long as it's handled somewhere! Thanks.
