### ISSUE TITLE
Data Source for RDS Event Categories

### ISSUE THREAD

**Issue by pmacdougall** [terraform-providers/terraform-provider-aws#5374]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a Data Source to lookup RDS Event Categories.  This could be used to pass values into aws_db_event_subscription.

### New or Affected Resource(s)

* aws_rds_event_category

**Comment by saravanan30erd** [comment]
I ll work on this datasource.

**Comment by bflad** [comment]
Support for a `aws_db_event_categories` data source has been merged and will release with version 1.38.0 of the AWS provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 1.38.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1380-september-26-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
