### ISSUE TITLE
Select a Range of Elements from a List

### ISSUE THREAD

**Issue by Xtigyro** [terraform-providers/terraform-provider-aws#5375]
Is there a way to select a range of elements from a list in Terraform?

For example - if we have:

`[a, bb, ccc, dddd, eeeee]`

How can the first 3 elements be selected?

`a, bb, ccc`

And then the 4th and 5th elements?

`dddd, eeeee`

**Comment by bflad** [comment]
@Xtigyro similar to #5382, closing this issue. See also: https://github.com/terraform-providers/terraform-provider-aws/issues/5382#issuecomment-408891435

FYI, in the development branch for the next major version of Terraform (0.12), the built-in function pages are already split out: https://github.com/hashicorp/terraform/tree/v0.12-dev/website/docs/configuration/functions
