### ISSUE TITLE
Unexpected result from data_source_aws_db_instance

### ISSUE THREAD

**Issue by stephencoe** [terraform-providers/terraform-provider-aws#5400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* data_source_aws_db_instance

### Terraform Configuration Files

```hcl
data "aws_db_instance" "db_example" {
  db_instance_identifier = "my-db"
}

resource "aws_dms_endpoint" "this" {
  ...
  server_name   = "${element(split(":", data.aws_db_instance.db_example.endpoint), 0)}" # removing the port in order to use the endpoint as the server name
  port          = "${data.aws_db_instance.db_example.port}"
}
```

### Expected Behavior

The endpoint return value shouldn't contain the port since its available through another output value

```hcl
data "aws_db_instance" "db_example" {
  db_instance_identifier = "my-db"
}

resource "aws_dms_endpoint" "this" {
  ...
  server_name   = "${data.aws_db_instance.db_example.endpoint}"
  port          = "${data.aws_db_instance.db_example.port}"
}
```

### Actual Behavior

The endpoint contains the port as its been appended on the end https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_db_instance.go#L273

**Comment by bflad** [comment]
Hi @stephencoe 👋 The [`address` attribute](https://www.terraform.io/docs/providers/aws/d/db_instance.html#address) has just the server name. Would updating the documentation for the `address` and `endpoint` attributes to clarify what they contain be sufficient here?

**Comment by stephencoe** [comment]
Hi @bflad, yes I think that would be enough in this case. Thanks for pointing it out 🌮

**Comment by bflad** [comment]
Documentation PR submitted: #5402
