### ISSUE TITLE
aws_lambda_invocation

### ISSUE THREAD

**Issue by charles-d-burton** [terraform-providers/terraform-provider-aws#5403]
### Terraform Version
# v0.11.7

* aws_lambda_invocation

### Terraform Configuration Files

```hcl
data "aws_lambda_invocation" "sync_artifacts" {
  function_name = "${data.terraform_remote_state.lambda_sync.function_name}"

  input = <<JSON
{
  "source_bucket": {
    "bucket_name": "${data.terraform_remote_state.s3_artifacts.bucket_name}",
    "prefix": "mf-player/",
    "strip_prefix": true
  },
  "destination_bucket": {
    "bucket_name": "${aws_s3_bucket.mf-player.id}"
  }
}
JSON
}
```

### Debug Output

018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: ---[ RESPONSE ]--------------------------------------
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: HTTP/2.0 200 OK
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: Content-Length: 29
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: Content-Type: application/json
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: Date: Tue, 31 Jul 2018 15:07:53 GMT
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: X-Amz-Executed-Version: $LATEST
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: X-Amzn-Remapped-Content-Length: 0
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: X-Amzn-Requestid: 7e2f27ce-94d3-11e8-b3c1-61d194ada76e
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: X-Amzn-Trace-Id: root=1-5b607b47-281a49e6cde97c441d201692;sampled=0
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4:
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4:
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: -----------------------------------------------------
2018-07-31T09:07:53.956-0600 [DEBUG] plugin.terraform-provider-aws_v1.29.0_x4: 2018/07/31 09:07:53 [DEBUG] [aws-sdk-go] "{\"proccessed_objects\":18}"
2018/07/31 09:07:53 [ERROR] root: eval: *terraform.EvalReadDataApply, err: data.aws_lambda_invocation.sync_artifacts: json: cannot unmarshal string into Go value of type map[string]interface {}
2018/07/31 09:07:53 [ERROR] root: eval: *terraform.EvalSequence, err: data.aws_lambda_invocation.sync_artifacts: json: cannot unmarshal string into Go value of type map[string]interface {}
2018/07/31 09:07:53 [TRACE] [walkRefresh] Exiting eval tree: data.aws_lambda_invocation.sync_artifacts

### Expected Behavior
It should exit cleanly, the object I'm returning from Lambda is valid JSON.  I've tried returning it as both a string and []byte  Here's the relevant snippet of code:
```go
        var result Result
	result.ProcessedObjects = numObjects
	data, err := json.Marshal(&result)
	if err != nil {
		return err.Error()
	}
	log.Println(string(data))
	return data
```

### Actual Behavior
It's failing to unmarshal the []byte into a json object

### Steps to Reproduce
Create a lambda function in Go, return either a []byte or string of valid json.

1. `terraform apply`

### Important Factoids
I've tried returning a string and []byte, additionally I've returned the error as an error code and as a string.  The data that is coming back is valid JSON and the function is executing perfectly, in fact it's doing exactly what it should do.  I'm wondering if this is just a documentation issue because there is nothing on how the Lambda function itself should be configured.

**Comment by bflad** [comment]
Related: #4808

**Comment by charles-d-burton** [comment]
Definitely, I read that one but the python solution isn't clear to me(not really a huge python person) so I'm not really sure how I should be formatting the JSON returned from Go.

**Comment by charles-d-burton** [comment]
I reviewed the provider code too and I'm not seeing a reason why it shouldn't unmarshal that json object either.

**Comment by charles-d-burton** [comment]
I think I have a patch that should resolve this for all cases.  What looks to be happening to me is that Lambda is adding escapes to the return value, one solution is to put strong quotes around the string return value.  I also have a provider patch that can handle both escaped and unescaped JSON.

**Comment by charles-d-burton** [comment]
Using Go I've tried to return every type of data I can think of and it doesn't work. If I send back valid JSON Lambda adds escapes to it, if I send back JSON like this:
```json
'{"key":"value"}'
```json
Lambda still adds escapes, I can't seem to find any way that this works using Go.

**Comment by charles-d-burton** [comment]
Alright, so it turns out that an undocumented/not clearly documented feature of Lambda support for Golang is that it automatically runs any non-error return through json marshaling.  Meaning that if you marshal a struct to json it marshals it again before returning it to the caller. If you return an object reference that has json fields defined it marshals it correctly.  For instance:
```go
var result Result
result.ProcessedObjects = numObjects
return &result
```

**Comment by bflad** [comment]
Since this issue appears to have been resolved awhile ago by fixing the response, I'm going to close it. If there are issues with the data source for proper JSON inputs and responses, please open a new GitHub issue and we'll take a fresh look. 👍
