### ISSUE TITLE
AWS SSM DoesNotExistException for missing Maintenance Window

### ISSUE THREAD

**Issue by jseiser** [terraform-providers/terraform-provider-aws#5412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

➜ terraform -v
Terraform v0.11.7
+ provider.aws v1.29.0

### Terraform Configuration Files

```hcl
# Scan MW Window
resource "aws_ssm_maintenance_window" "scan_window" {
  count    = "${var.is_patching}"
  name     = "${var.customer}-${var.project}-${var.environment}-patch-maintenance-scan-mw"
  schedule = "${var.scan_maintenance_window_schedule}"
  duration = "${var.maintenance_window_duration}"
  cutoff   = "${var.maintenance_window_cutoff}"
}

# Install MW Window
resource "aws_ssm_maintenance_window" "install_window" {
  count    = "${var.is_patching}"
  name     = "${var.customer}-${var.project}-${var.environment}-patch-maintenance-install-mw"
  schedule = "${var.install_maintenance_window_schedule}"
  duration = "${var.maintenance_window_duration}"
  cutoff   = "${var.maintenance_window_cutoff}"
}
```

### Expected Behavior

Terraform should re-create the missing maint. window

### Actual Behavior

```
* module.network.aws_ssm_maintenance_window.scan_window: 1 error(s) occurred:

* module.network.aws_ssm_maintenance_window.scan_window: aws_ssm_maintenance_window.scan_window: DoesNotExistException: Maintenance window mw-0967d3367d6166725 does not exist
	status code: 400, request id: 26b96960-0ec1-48d1-828a-c12d1fad40cf
* module.network.aws_ssm_maintenance_window.install_window: 1 error(s) occurred:

* module.network.aws_ssm_maintenance_window.install_window: aws_ssm_maintenance_window.install_window: DoesNotExistException: Maintenance window mw-0029976ce921415ef does not exist
	status code: 400, request id: c1dab474-986f-468b-8ef5-993aac875c05
```

### Steps to Reproduce

1. `terraform plan`

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/4612#issuecomment-408166433
* #0000

**Comment by bflad** [comment]
The fix for this has been merged into master and will release with version 1.30.0 of the AWS provider, likely middle of next week. 👍
