### ISSUE TITLE
aws_instance parse error: expected expression but found "."

### ISSUE THREAD

**Issue by jtravell** [terraform-providers/terraform-provider-aws#5469]
> _**What specific code would need to be written in order to successfully add a new free-standing Amazon Linux 2 EC2 instance to [this sample cluster](https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started) that is NOT part of the auto-scaling group?**_

The free-standing EC2 instance needs to be accessible by the worker nodes.  
  
When I try to add such a new EC2 instance, it breaks with the following:
  
    Error: Error loading C:\projects\terraform\kubernetes-cluster-aws-example\eks-worker-nodes.tf:   
    Error reading config for aws_instance[al2]: parse error at 1:38: expected expression but found "."
  
Here is the code that is breaking:  
  
    data "aws_ami" "amazon-linux-2" {
        most_recent = true

        filter {
          name   = "owner-alias"
          values = ["amazon"]
        }

        filter {
          name   = "name"
          values = ["amzn2-ami-hvm*"]
        }

        owners      = ["xxxxxxxxxxx"] # Amazon acount id

    }

    resource "aws_instance" "al2" {
        ami           = "${data.aws_ami.amazon-linux-2.image_id}"
        instance_type               = "t2.micro"
        vpc_security_group_ids      = ["${aws_security_group.demo-node.id}"]
        subnet_id = ["${element(split(",", aws_subnet.demo*.id), 0)}"]
        depends_on = ["aws_eks_cluster.demo"]
    }

I have tried many different syntax options for the first line inside the `aws_instance.al2` block, but they all throw the same error so inexplicably that this seems like a bug.

**Comment by blckct** [comment]
You're missing a dot: `aws_subnet.demo*.id` should be `aws_subnet.demo.*.id`.

**Comment by bflad** [comment]
Hi @jtravell 👋  As @blckct mentioned, you're missing a period in the reference. If you're going off this EKS example code:

https://github.com/terraform-providers/terraform-provider-aws/blob/4ff0dd359f77d858caa87119a1962d92e647d68a/examples/eks-getting-started/vpc.tf#L20-L33

I suspect that you're really trying to fetch only one of the two that are created (as the [`subnet_id` argument for the `aws_instance` resource is not a list](https://www.terraform.io/docs/providers/aws/r/instance.html#subnet_id)), in which you'll need to reference it via `subnet_id = "${aws_subnet.demo.*.id[0]}"`.

Please note that we keep the issue tracker in this GitHub repository strictly for bug reports and feature requests in the AWS provider and not for general questions. For that reason I'm going to close this issue. While the few people who watch this repository may be able to answer simple questions, you will likely have better luck with the other [community resources](https://www.terraform.io/docs/extend/community/index.html).
