### ISSUE TITLE
Update EKS Getting Started Guide and Example for Worker Node bootstrap.sh

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#5483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At some point (if it hasn't happened already), the latest version of the published EKS worker node AMI will switch from manually configuring Kubernetes files in the `user_data` to using a new `bootstrap.sh` script. When this is released, we should update the following to match and stay up to date:
* `examples/eks-getting-started/eks-worker-nodes.tf`
* `website/docs/guides/eks-getting-started.html.markdown`

### Affected Guide

* [EKS Getting Started Guide](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html)

### Potential Terraform Configuration

```hcl
# Example configuration update, details may change before AMI release
locals {
  demo-node-userdata = <<USERDATA
#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh --b64-cluster-ca '${aws_eks_cluster.demo.certificate_authority.0.data}' --apiserver-endpoint '${aws_eks_cluster.demo.endpoint}' '${var.cluster-name}'
USERDATA
}
```

### References

* https://github.com/awslabs/amazon-eks-ami/pull/16

**Comment by Ghazgkull** [comment]
The new EKS-optimized AMI is now available according to https://aws.amazon.com/about-aws/whats-new/2018/08/new-amazon-eks-optimized-ami-and-cloudformation-template-for-worker-node-provisioning/

It looks like they also changed the naming convention for the AMI with this update, which will require an update to the getting started guide as well. From `eks-worker-vXX` to `amazon-eks-node-vXX`.
