### ISSUE TITLE
Feature Request: RDS Aurora Engine Mode (Serverless Support)

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#5503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Tucked away in the [v1.15.9 AWS SDK update](https://github.com/aws/aws-sdk-go/releases/tag/v1.15.9) is this tidbit:
> Launch RDS Aurora Serverless

Briefly looking at the SDK changes, it looks like this is supported via a new `EngineMode` parameter for `DBCluster` and its create/restore from snapshot inputs.

### New or Affected Resource(s)

* aws_rds_cluster

### Potential Terraform Configuration

```hcl
# Potential implementation, may change during development
resource "aws_rds_cluster" "example" {
  # ... other configuration ...
  engine_mode = "" # provisioned or serverless
}
```

### References

* https://docs.aws.amazon.com/sdk-for-go/api/service/rds/

**Comment by bflad** [comment]
I don't mind tackling this one. Looks like `EngineMode` is already in API responses: `<EngineMode>provisioned</EngineMode>`

**Comment by bflad** [comment]
PR submitted: #5507

**Comment by bflad** [comment]
Support for this has been merged in and will release with version 1.32.0 of the AWS provider, later this week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.32.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1320-august-16-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by facundo-guerrero-olx** [comment]
There is a bug here, When you try to apply Aurora in Singapore fail, because don't support the engine mode parameter.

**Comment by adrianomelo** [comment]
Using `engine = "aurora"` instead of `engine = "aurora-mysql"` solved the problem described by @giannisbetas for me.

**Comment by giannisbetas** [comment]
Hi @adrianomelo 
For aurora `5.6.10ann` you need to set `engine = "aurora"`.
For aurora `5.7.12` you need to set `engine = "aurora-mysql"` and `engine_version: "5.7.12"`.

@bflad thanks for your help :)

**Comment by mmell** [comment]
Creating a new Aurora database in the [AWS console](https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#launch-dbinstance:s3-import=false) displays this information:
```
Edition

MySQL 5.6-compatible
Aurora Serverless and Parallel Query capacities are only available with this edition.
```

In other words, it says that Aurora's serverless mode requires `engine_version` matching `MySQL 5.6`.

**Comment by jsrice7391** [comment]
Still cannot get around this one. Any help would be great.
```terraform
provider "aws"{
  version = "~>2"
}

module "serverless_aurora_cluster" {
  name              = "cool_database"
  database_name     = "microbiome"
  engine            = "aurora" 
  engine_version    = "5.6.10"
  auto_pause        = true
}
```
