### ISSUE TITLE
%!s(<nil>) error when trying to create a aws service discovery private dns namespace

### ISSUE THREAD

**Issue by MrLarssonJr** [terraform-providers/terraform-provider-aws#5532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
aws provider v1.31.0

### Affected Resource(s)

* aws_service_discovery_private_dns_namespace

### Terraform Configuration Files

```hcl
resource "aws_service_discovery_private_dns_namespace" "xray-daemon" {
  name = "hoge.example.local"
  vpc = "${data.aws_vpc.core.id}"
}
```

### Expected Behavior

A service discover private dns namespace should've been created or a proper error message.

(The corresponding aws cli command succeeds: `aws servicediscovery create-private-dns-namespace --name hoge.example.local --vpc $myVPC`

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* aws_service_discovery_private_dns_namespace.xray-daemon: 1 error(s) occurred:

* aws_service_discovery_private_dns_namespace.xray-daemon: unexpected state 'FAIL', wanted target 'SUCCESS'. last error: %!s(<nil>)
```

### Steps to Reproduce

1. `terraform apply`

### References

* #2830 - seem to get the same error message as me. Their suggestion of colliding/overlapping namespaces didn't help me. Tried a bunch of different. That the command succedes from the aws cli also indicates that this isn't the problem.

**Comment by MrLarssonJr** [comment]
The runner running terraform was missing permission route53:CreateHostedZone resulting in the missing error message.

**Comment by bflad** [comment]
Pull request submitted: #7118
