### ISSUE TITLE
aws_acm_certificate_validation - Multi-Account Support

### ISSUE THREAD

**Issue by Xtigyro** [terraform-providers/terraform-provider-aws#5545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A way to validate an AWS ACM certificate using DNS Validation when the Hosted Zones are hosted in different AWS accounts.

Use case: if you have different Hosted Zones in two different AWS accounts:
(1) `.com` in the first account;
(2) `.io` in your second account.

And you need the issued certificate to be used in both accounts - because in the first one you host your Staging environment and in the second one you host your Production environment.

### New or Affected Resource(s)

aws_acm_certificate_validation

### Potential Terraform Configuration

A good beginning might be to let it pass successfully when not all FQDN's are included - it now errors with "Missed records". In that way the correct FQDN's can be sliced and used in the different iterations.

**Comment by bflad** [comment]
Hi @Xtigyro 👋 

The `aws_acm_certificate_validation` resource only needs access to the ACM certificate (to check if its reached the `ISSUED` status) and can work with DNS records in any AWS account or even external DNS providers. The ACM service is performing the DNS validation so Terraform does not participate in that process.

If you need to setup multiple AWS providers in the same Terraform configuration (e.g. to talk to multiple AWS accounts for the DNS records themselves), be sure to check out: https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances

That said, I believe ACM certificates cannot be shared across AWS accounts (this is an ACM service limitation) so you will want to double check what you are trying to accomplish is actually possible. Its likely that you will need to create ACM certificates in both AWS accounts.

**Comment by Xtigyro** [comment]
Hi Brian - yes, I think you're right. Thank you!

Actually, the problem comes from the step before that - putting the AWS Route53 records using different accounts and the inability to interpolate within the "provider" attribute. That's a different story though.

Thank you and good night!
Miro
