### ISSUE TITLE
data.aws_storagegateway_local_disk : no results found for query

### ISSUE THREAD

**Issue by undercover1769** [terraform-providers/terraform-provider-aws#5589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

$ terraform -v
Terraform v0.11.8

### Affected Resource(s)

* aws_storagegateway_local_disk

### Terraform Configuration Files

```hcl
resource "aws_instance" "fg_instance" {
  ami                    = "ami-0de87dd1829f3d12e"
  instance_type          = "m5.2xlarge"
  availability_zone      = "eu-west-2a"
  key_name               = "${var.instance_key_name_test}"
  subnet_id              = "${element(var.private_subnets_ids_test, count.index)}"
  vpc_security_group_ids = ["sg-1", "sg-2", "sg-3"]
}

resource "aws_ebs_volume" "sdb" {
  availability_zone = "eu-west-2a"
  size              = 150
  type              = "gp2"
}

resource "aws_volume_attachment" "sdb_attach" {
  device_name  = "/dev/sdb"
  volume_id    = "${aws_ebs_volume.sdb.id}"
  instance_id  = "${aws_instance.fg_instance.id}"
  skip_destroy = false
}

resource "aws_storagegateway_gateway" "fg" {
  gateway_ip_address = "${aws_instance.fg_instance.private_ip}"
  gateway_name       = "my_fg"
  gateway_timezone   = "GMT"
  gateway_type       = "FILE_S3"
}

data "aws_storagegateway_local_disk" "fg_disk" {
  disk_path   = "${aws_volume_attachment.sdb_attach.device_name}"
  gateway_arn = "${aws_storagegateway_gateway.fg.arn}"
}

resource "aws_storagegateway_cache" "fg_cache" {
  disk_id     = "${data.aws_storagegateway_local_disk.fg_disk.id}"
  gateway_arn = "${aws_storagegateway_gateway.fg.arn}"
}

```
### Expected Behavior

File Gateway should be created with the attached volume added as a cache disk

### Actual Behavior

The File Gateway is created and activated and all OK, but the Terraform apply ends with the following error:

```Error: Error applying plan:

1 error(s) occurred:

* data.aws_storagegateway_local_disk.fg_disk: data.aws_storagegateway_local_disk.fg_disk: no results found for query, try adjusting your search criteria
```

I can still then go into the AWS console and add the cache disk manually without any errors.

### Steps to Reproduce

1. `terraform apply`

### References

```aws_storagegateway_gateway.fg:
  id = arn:aws:storagegateway:eu-west-2:123456789012:gateway/sgw-1234567
  activation_key = 
  arn = arn:aws:storagegateway:eu-west-2:123456789012:gateway/sgw-1234567
  gateway_id = sgw-1234567
  gateway_ip_address = 1.1.1.1
  gateway_name = my_fg
  gateway_timezone = GMT
  gateway_type = FILE_S3
  medium_changer_type = 
  smb_active_directory_settings.# = 0
  smb_guest_password = 
  tape_drive_type = 
aws_volume_attachment.sdb_attach:
  id = vai-1558009518
  device_name = /dev/sdb
  instance_id = i-06202ffc79ebd30cd
  skip_destroy = false
  volume_id = vol-0a01f79981869d914
```

```{
    "Gateways": [
        {
            "GatewayId": "sgw-1234567",
            "GatewayARN": "arn:aws:storagegateway:eu-west-2:123456789012:gateway/sgw-1234567",
            "GatewayName": "my_fg",
            "GatewayOperationalState": "ACTIVE",
            "GatewayType": "FILE_S3"
        }
    ]
}```

'''$ aws storagegateway list-local-disks --gateway-arn  arn:aws:storagegateway:eu-west-2:123456789012:gateway/sgw-1234567
{
    "GatewayARN": "arn:aws:storagegateway:eu-west-2:123456789012:gateway/sgw-1234567",
    "Disks": [
        {
            "DiskSizeInBytes": 161061273600,
            "DiskAllocationType": "AVAILABLE",
            "DiskPath": "/dev/nvme1n1",
            "DiskStatus": "present",
            "DiskId": "pci-0000:00:1f.0",
            "DiskNode": "/dev/sdb"
        }
    ]
}


* #0000

**Comment by bflad** [comment]
Hi @undercover1769 👋  Thanks for the detailed writeup here!

I have a hunch that this has to do with [NVMe EBS Volumes](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html) on the `m5` instance family.

Does this happen to work if you adjust your `aws_volume_attachment` resource configuration to `device_name = "/dev/nvme1n1"`?

```hcl
resource "aws_volume_attachment" "sdb_attach" {
  device_name  = "/dev/nvme1n1"
  volume_id    = "${aws_ebs_volume.sdb.id}"
  instance_id  = "${aws_instance.fg_instance.id}"
  skip_destroy = false
}
```

Besides that potential configuration change (which we should likely add documentation for with the data source), it looks like we might want to also support looking up local disks via `DiskNode` instead of just `DiskPath`:

```
aws_volume_attachment.sdb_attach:
...
  device_name = /dev/sdb
```

```
data "aws_storagegateway_local_disk" "fg_disk" {
  disk_path   = "${aws_volume_attachment.sdb_attach.device_name}"
```

```
    "Disks": [
        {
...
            "DiskPath": "/dev/nvme1n1",
...
            "DiskNode": "/dev/sdb"
        }
    ]
```

The Storage Gateway documentation is fairly sparse on what values to actually expect in the `DiskId`, `DiskNode`, and `DiskPath`: https://docs.aws.amazon.com/storagegateway/latest/APIReference/API_Disk.html

Most of the Storage Gateway resource development was done against `m4.xlarge` instance types so its interesting to see how the `m5` instance type family differs here. Thanks again for thorough report above. 👍

**Comment by undercover1769** [comment]
Hi bflad,

Thanks for the swift response, very interesting you think it's the M5, as the other issue I logged on here recently (https://github.com/terraform-providers/terraform-provider-aws/issues/5182) was looked into by AWS Support eventually and that turned out to be caused by M5, as it ended up being fine on M4...

Will test it over the weekend and get back to you!

Cheers,
Dave

**Comment by undercover1769** [comment]
Hi bflad,

Just tested that with:

```
device_name  = "/dev/nvme1n1"
```

```* aws_volume_attachment.sdb_attach: [WARN] Error attaching volume (vol-0a66eef758d43b92a) to instance (i-0ee49c1daaff9ce9f), message: "Value (/dev/nvme1n1) for parameter device is invalid. /dev/nvme1n1 is not a valid EBS device name.", code: "InvalidParameterValue"
```

Whole thing listed here in case I've mistyped anything as I knew I should have gone to the pub

```
resource "aws_ebs_volume" "sdb" {
  availability_zone = "eu-west-2a"
  size              = 150
  type              = "gp2"
}

resource "aws_volume_attachment" "sdb_attach" {
  device_name  = "/dev/nvme1n1"
  volume_id    = "${aws_ebs_volume.sdb.id}"
  instance_id  = "${aws_instance.fg_instance.id}"
  skip_destroy = false
}

resource "aws_storagegateway_gateway" "fg" {
  gateway_ip_address = "${aws_instance.fg_instance.private_ip}"
  gateway_name       = "fg_test"
  gateway_timezone   = "GMT"
  gateway_type       = "FILE_S3"
}

data "aws_storagegateway_local_disk" "fg_disk" {
  disk_path   = "${aws_volume_attachment.sdb_attach.device_name}"
  gateway_arn = "${aws_storagegateway_gateway.fg.arn}"
}

resource "aws_storagegateway_cache" "fg_cache" {
  disk_id     = "${data.aws_storagegateway_local_disk.fg_disk.id}"
  gateway_arn = "${aws_storagegateway_gateway.fg.arn}"
}
```

Cheers!

**Comment by bflad** [comment]
Ah, bummer. In the meantime, then it looks like you might have to workaround this by hardcoding the `disk_path` and ensure proper ordering with `depends_on`. 😅  e.g.

```
data "aws_storagegateway_local_disk" "fg_disk" {
  depends_on = ["aws_volume_attachment. sdb_attach"]

  disk_path   = "/dev/nvme1n1"
  gateway_arn = "${aws_storagegateway_gateway.fg.arn}"
}
```

The good news though is that I have submitted a pull request for the data source to accept `disk_node` with acceptance testing that verifies it should work in this case. 👍  https://github.com/terraform-providers/terraform-provider-aws/pull/5595

With that support we'll be able to do the following, which should work as expected in your case:

```hcl
data "aws_storagegateway_local_disk" "fg_disk" {
  disk_node   = "${aws_volume_attachment.sdb_attach.device_name}"
  gateway_arn = "${aws_storagegateway_gateway.fg.arn}"
}
```

**Comment by bflad** [comment]
The `disk_node` support for `aws_storagegateway_local_disk` has been released in [version 1.33.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1330-august-22-2018). Give it a shot and let us know if it doesn't solve this problem.

Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by undercover1769** [comment]
Worked great, many thanks for the swift turnaround Brian! 👍

```
data.aws_storagegateway_local_disk.fg_disk: Refreshing state...
aws_storagegateway_cache.fg_cache: Creating...
  disk_id:     "" => "pci-0000:00:1f.0"
  gateway_arn: "" => "arn:aws:storagegateway:eu-west-2:123456789012:gateway/sgw-1234567F"
aws_storagegateway_cache.fg_cache: Creation complete after 1s (ID: arn:aws:storagegateway:eu-west-2:062851...:gateway/sgw-1234567:pci-0000:00:1f.0)

Apply complete! Resources: 11 added, 0 changed, 0 destroyed.
```

**Comment by 123BLiN** [comment]
It seems it is not documented well here https://www.terraform.io/docs/providers/aws/d/storagegateway_local_disk.html
it took me some time to find this issue and understand that I need to use disk_node instead of disk_path

**Comment by arashnh11** [comment]
Same here. Took me a while to reach to this repo... was digging with disk_id for a while as stated here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/storagegateway_local_disk
And just realized the device name/disk id/path mismatch. 
It would be great to update the upstream document.
