### ISSUE TITLE
aws_storagegateway_smb_file_share fails with parse error at 1:6: expected "}" but found ":"

### ISSUE THREAD

**Issue by kittu225** [terraform-providers/terraform-provider-aws#5597]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version 0.11.8

### Affected Resource(s)

* aws_v1.31.0

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
resource "aws_storagegateway_gateway" "test-sgw" {
  gateway_ip_address = "10.1.1.10"
  gateway_name       = "test-sgw"
  gateway_timezone   = "GMT+5:30"
  gateway_type       = "FILE_S3"

  smb_active_directory_settings {
  domain_name        = "corp.test.com"
  username           = "test"
  password           = "test#123"
  }
}

resource "aws_storagegateway_smb_file_share" "test-sgw-smb" {
  	gateway_arn    = "${aws_storagegateway_gateway.test-sgw.arn}"
  	location_arn   = "${arn:aws:s3:::testsgwbucket}"
  	role_arn       = "${aws_iam_role.test-smb-role.arn}"
}

##################Role policy######################

resource "aws_iam_role" "test-smb-role" {
  name = "test-smb-role"

  assume_role_policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketLocation",
                "s3:GetBucketVersioning",
                "s3:ListBucket",
                "s3:ListBucketVersions",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": "arn:aws:s3:::testsgwbucket",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::testsgwbucket/*",
            "Effect": "Allow"
        }
    ]
 }
EOF
}
```
### Debug Output

Error in Terraform Plan stage

Error loading configuration: Error loading /home/testing/SGW-Test.tf: Error reading config for aws_storagegateway_smb_file_share[test-sgw-smb]: parse error at 1:6: expected "}" but found ":"

### References

* #0000

**Comment by bflad** [comment]
Hi @kittu225 👋  Sorry you're running into trouble here.

This line looks suspicious in your Terraform configuration:

```
location_arn   = "${arn:aws:s3:::testsgwbucket}"
```

Did you mean to add the `${` and `}` for Terraform to interpolate the value in the configuration there? If so, you are likely looking for something like `location_arn = "${data.aws_s3_bucket.XXX.arn}"` when referencing a [`aws_s3_bucket` data source](https://www.terraform.io/docs/providers/aws/d/s3_bucket.html) or `location_arn = "${aws_s3_bucket.XXX.arn}"` when referencing a [`aws_s3_bucket` resource](https://www.terraform.io/docs/providers/aws/d/s3_bucket.html). If you're looking to hardcode the ARN (we generally recommend using the data source instead to verify its existence), you can remove the `${` and `}`. 😄 

As for the confusing error messaging you received there, the [next major version of Terraform](https://www.hashicorp.com/blog/terraform-0-1-2-preview) should be able to properly report the actual filename and position of syntax errors in a much more helpful manner. See also: https://github.com/hashicorp/terraform/issues/16665 👍 

Hope this helps!

**Comment by kittu225** [comment]
Thanks for the update @bflad I have removed the ${ }  and its good now. Since its not report exact position of syntax error i couldn't analyze it.
Good to hear about the Major version.
