### ISSUE TITLE
Support `name` field for s3_bucket_notification

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-aws#5604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an [`s3_bucket_notification`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_notification.html), the name is auto-generated by Terraform:

![image](https://user-images.githubusercontent.com/900469/44317376-407e9800-a474-11e8-92cc-3daf694726f5.png)

It would be nice to be able to specify a custom name in Terraform.

(FWIW, I did try it, just in case it was a documentation bug: `Error: aws_s3_bucket_notification.test: : invalid or unknown key: name`)

### New or Affected Resource(s)

* [`aws_s3_bucket_notification`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_notification.html)

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_notification" "test" {
  name   = "my-notification"
  bucket = "my-bucket"

  lambda_function {
    lambda_function_arn = "arn:aws........."
    events              = ["S3:ObjectCreated:*"]
  }
}
```

**Comment by bflad** [comment]
@tdmalone does the `Name` in the console correspond to the [`id` field within each `lambda_function`](https://www.terraform.io/docs/providers/aws/r/s3_bucket_notification.html#id-2) for example?

```hcl
resource "aws_s3_bucket_notification" "test" {
  bucket = "my-bucket"

  lambda_function {
    id                  = "my-notification"
    lambda_function_arn = "arn:aws........."
    events              = ["S3:ObjectCreated:*"]
  }
}
```

It appears we generate the ID in the following code here, which matches what you see:

https://github.com/terraform-providers/terraform-provider-aws/blob/da16007d2364267300019b32e0830d6e07078a65/aws/resource_aws_s3_bucket_notification.go#L251-L256

**Comment by tdmalone** [comment]
Sorry for the delay in responding - and thanks for outlining that.
I did indeed miss it; I was looking in the top level resource!
