### ISSUE TITLE
CloudWatch Alarms do not support custom statistics

### ISSUE THREAD

**Issue by rafalcieslak** [terraform-providers/terraform-provider-aws#5608]
The ` aws_cloudwatch_metric_alarm` resource does not support custom statistics.

According to the documentation:

> statistic - (Optional) The statistic to apply to the alarm's associated metric. Either of the following is supported: SampleCount, Average, Sum, Minimum, Maximum

This is correct in most cases, as most metrics have only these statistics available. However, there is at least one exception: Application Load Balancer metrics support custom percentile statistics, e.g. `p99.5` or `p90`.

This is specifically useful for monitoring e.g. whether 99% of your users (requests) are processed within, say, 100 ms. Link to AWS docs explaining these metrics: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html#metric-statistics

I can configure an alarm using such percentile statistics using AWS console just fine:

![aws-alarm-p90](https://user-images.githubusercontent.com/6637987/44336964-62c6e480-a479-11e8-93fa-0ab31ec0460e.png)

However, I cannot do the same using terraform, for an obvious reason: 

```
aws_cloudwatch_metric_alarm.alarm: Creating metric alarm failed: \
  ValidationError: 1 validation error detected: Value 'p90' at 'statistic' failed to satisfy constraint: \
    Member must satisfy enum value set: [Maximum, SampleCount, Sum, Minimum, Average]
``` 

My proposed solution would be to allow using `Custom` as a value to `statistic`, in which case the actual value would be taken from a new `custom_statistic` argument, which would be less restrictive. This approach would be similar to how it's done in AWS console:

```
resource "aws_cloudwatch_metrics_alarm" "example" {
    [...]
    statistic = "Custom"
    custom_statistic = "p99"
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gazoakley** [comment]
@rafalcieslak It looks like Terraform already supports this (although it's known as `extended_statistic` to match the naming from the CloudWatch API): https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html#extended_statistic

**Comment by rafalcieslak** [comment]
@gazoakley Thank you, this is exactly what I was looking for.
