### ISSUE TITLE
Import aws_autoscaling_schedule (just not documented?)

### ISSUE THREAD

**Issue by four43** [terraform-providers/terraform-provider-aws#5617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to be able to import this resource. The [docs page](https://www.terraform.io/docs/providers/aws/r/autoscaling_schedule.html) doesn't have any information on importing, and access to ARNs via AWS Console isn't available.

### New or Affected Resource(s)

* aws_autoscaling_schedule

### Potential Terraform Configuration

`terraform import aws_autoscaling_schedule.old_us_schedule arn:::::`

### References

https://www.terraform.io/docs/providers/aws/r/autoscaling_schedule.html

**Comment by bflad** [comment]
Support for importing `aws_autoscaling_schedule` resources has been merged and will release with version 2.11.0 of the Terraform AWS Provider, likely later this week. 👍 Thanks @taxpon!

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by four43** [comment]
Thanks all, this will be great!
