### ISSUE TITLE
r/aws_dynamodb_table: Support 11/15/2018 Server-Side Encryption enhancements

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#5637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Looking at the release notes for [AWS SDK v1.15.16](https://github.com/aws/aws-sdk-go/releases/tag/v1.15.16):

> service/dynamodb: Updates service API and documentation
> Added SSESpecification block to update-table command which allows users to modify table Server-> Side Encryption. Added two new fields (SSEType and KMSMasterKeyId) to SSESpecification block used by create-table and update-table commands. Added new SSEDescription Status value UPDATING

Add support for these enhancements to the `aws_dynamodb_table` resource and data source.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/5619
* https://github.com/terraform-providers/terraform-provider-aws/pull/3303
* https://github.com/terraform-providers/terraform-provider-aws/issues/3298

**Comment by ewbankkit** [comment]
Potentially adapt some refactoring applied in https://github.com/terraform-providers/terraform-provider-aws/pull/5508?

**Comment by ewbankkit** [comment]
Proposed syntax:

Enhance [`aws_dynamodb_table.server_side_encryption`](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#server_side_encryption) attribute with `sse_type` and `kms_master_key_id` nested fields.

For example:

```hcl
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name           = "GameScores"

  server_side_encryption {
    enabled           = true
    sse_type          = "KMS"
    kms_master_key_id = "${aws_kms_key.a.id}"
  }
}
```

**Comment by ewbankkit** [comment]
After [the 11/15/2018 announcement](https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-dynamodb-encrypts-all-customer-data-at-rest/) this issue has been re-titled to implement these changes.

**Comment by reggielamson** [comment]
Do you have a time frame for implementing this by chance?

**Comment by ewbankkit** [comment]
Closed. Replaced by https://github.com/terraform-providers/terraform-provider-aws/issues/7498.
