### ISSUE TITLE
Example for aws_security_group_rule in documentation is inconsistent

### ISSUE THREAD

**Issue by drzero42** [terraform-providers/terraform-provider-aws#5640]
The documentation for `aws_security_group_rule` has the following example:

```
resource "aws_security_group_rule" "allow_all" {
  type            = "ingress"
  from_port       = 0
  to_port         = 65535
  protocol        = "tcp"
  cidr_blocks     = ["0.0.0.0/0"]
  prefix_list_ids = ["pl-12c4e678"]

  security_group_id = "sg-123456"
}
```

In the **Argument Reference** just below it, it says that `prefix_list_ids` is only valid for `egress`. In the example the type is `ingress`, but `prefx_list_ids` is specified.

This example should probably be modified :)

**Comment by chaspy** [comment]
>it says that prefix_list_ids is only valid for egress

Is it true?
I didn't find the fact in the document https://www.terraform.io/docs/providers/aws/r/security_group_rule.html 🤔

**Comment by bflad** [comment]
@chaspy thanks for the note -- the documentation was recently updated with https://github.com/terraform-providers/terraform-provider-aws/pull/10067.

If there are further documentation feature requests or bug reports, please create a new GitHub issue. 👍
