### ISSUE TITLE
Add example S3 bucket integration for api_gateway_integration

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-aws#5652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

See this article on integrating S3 with API Gateway: https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-s3.html

It would be nice to have an example replicating this in Terraform.

**Comment by HashedDan** [comment]
I am very interested in working on this issue. Feel free to reach out if there are any specifics that would be helpful for me to know! Thanks!

**Comment by HashedDan** [comment]
I have the configuration for listing all the S3 buckets of a the API caller complete. It is fairly robust so I have added it to the examples folder. The AWS article also details how to add GET, PUT, DELETE calls on a bucket. I would be happy to add these functions to the configuration, but it will result in an even larger example. I believe the configuration for just listing the S3 buckets demonstrates nearly all of the resources that would be required for the GET, PUT, and DELETE calls, but I would be happy to add that portion if desired. Let me know what you prefer!
