### ISSUE TITLE
aws_api_gateway_vpc_link - Not able to import resource in another AWS tenant/account

### ISSUE THREAD

**Issue by rayterrill** [terraform-providers/terraform-provider-aws#5655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.32.0
+ provider.windns (unversioned)

### Affected Resource(s)

aws_api_gateway_vpc_link.api_vpclink

### Terraform Configuration Files

```hcl
#configure the gis AWS Provider
provider "aws" {
  alias = "gis"
  region = "us-west-2"
  assume_role {
    role_arn     = "arn:aws:iam::MYACCOUNTID:role/OrganizationAccountAccessRole"
    session_name = "terraform"
  }
}

#build a vpc link pointing from api gateway to our load balancer. this will allow us to route incoming api requests to our vm in our vpc
resource "aws_api_gateway_vpc_link" "api_vpclink" {
  provider = "aws.gis"
  name = "gisapi"
  target_arns = ["${aws_lb.api.arn}"]
}
```

### Debug Output

https://gist.github.com/rayterrill/79f74975caca9037e2fbd628cc994fa5

### Expected Behavior

Should import resource

### Actual Behavior

Reports back that the vpc link cannot be found. I wonder if it's not handling the account switch correctly? The API call appears to be using my root account credentials, not the temporary credentials the assume_role functionality should provision?

```
terraform import aws_api_gateway_vpc_link.api_vpclink 0kndy4
aws_api_gateway_vpc_link.api_vpclink: Importing from ID "0kndy4"...
aws_api_gateway_vpc_link.api_vpclink: Import complete!
  Imported aws_api_gateway_vpc_link (ID: 0kndy4)
aws_api_gateway_vpc_link.api_vpclink: Refreshing state... (ID: 0kndy4)

Error: aws_api_gateway_vpc_link.api_vpclink (import id: 0kndy4): 1 error(s) occurred:

* import aws_api_gateway_vpc_link.api_vpclink result: 0kndy4: import aws_api_gateway_vpc_link.api_vpclink (id: 0kndy4): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using the assume_role functionality to "switch" to the child tenant where this api gateway lives.

### References

* #0000

**Comment by bflad** [comment]
Does it happen to work if you add the [`-provider` flag](https://www.terraform.io/docs/commands/import.html#provider-provider) to your `terraform import` command? e.g.

```
terraform import -provider=aws.gis aws_api_gateway_vpc_link.api_vpclink 0kndy4
```

**Comment by rayterrill** [comment]
@bflad Yep - that indeed works which also gets me past my issue.

**Comment by bflad** [comment]
Great to hear. I'm going to close this issue then unless you feel the documentation can be improved. 👍

**Comment by bflad** [comment]
There is an upstream issue regarding reading the provider from configuration during import: https://github.com/hashicorp/terraform/issues/17139
