### ISSUE TITLE
CodeBuild - Project - Artifacts - Add encryptionDisabled configuration option

### ISSUE THREAD

**Issue by jtaylormayfield** [terraform-providers/terraform-provider-aws#5656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to add an "encryption_disabled" boolean to the aws_codebuild_project artifacts block. The CodeBuild API ProjectArtifacts data type supports an "encryptionDisabled" option that disables artifact encryption for builds targeting S3 buckets.

The parameter documentation is here: [ProjectArtifacts](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectArtifacts.html#CodeBuild-Type-ProjectArtifacts-encryptionDisabled)

### New or Affected Resource(s)

* aws_codebuild_project

### Potential Terraform Configuration

```hcl
resource "aws_codebuild_project" "example" {
  ...
  artifacts {
    encryption_disabled = true
    location  = "some-bucket-name"
    name = "/"
    packaging = "NONE"
    type      = "S3"
  }
  ...
}
```

**Comment by bflad** [comment]
This has been released in [version 1.34.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1340-august-30-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
