### ISSUE TITLE
d/aws_subnet_ids Unexpected interpolation of tags

### ISSUE THREAD

**Issue by stephencoe** [terraform-providers/terraform-provider-aws#5658]
When using the data source for `subnet_ids` with a map variable it appears that the variable interpolation is including the default value in the map rather than overwriting it

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.7

### Affected Resource(s)

* aws_subnet_ids

### Terraform Configuration Files

```hcl
variable "vpc_name" {
  type = "string"
}

variable "subnet_tags" {
  type        = "map"
  default = {
    Tier = "Private"
  }
}

data "aws_vpc" "this" {
  filter {
    name   = "tag:Name"
    values = ["${var.vpc_name}"]
  }
}

data "aws_subnet_ids" "private" {
  vpc_id = "${data.aws_vpc.this.id}"
  tags   = "${var.subnet_tags}"
}

```
**tfvars**
```
vpc_name = "production-vpc"
subnet_tags = {
  environment = "production"
  network = "private"
}
```

### Debug Output
```

plugin.terraform-provider-aws_v1.33.0_x4: 2018/08/23 10:01:23 [DEBUG] Matching ^aws: with environment
plugin.terraform-provider-aws_v1.33.0_x4: 2018/08/23 10:01:23 [DEBUG] Matching ^aws: with network
plugin.terraform-provider-aws_v1.33.0_x4: 2018/08/23 10:01:23 [DEBUG] Matching ^aws: with Tier
plugin.terraform-provider-aws_v1.33.0_x4: 2018/08/23 10:01:23 [DEBUG] DescribeSubnets {
plugin.terraform-provider-aws_v1.33.0_x4:   Filters: [
plugin.terraform-provider-aws_v1.33.0_x4:     {
plugin.terraform-provider-aws_v1.33.0_x4:       Name: "vpc-id",
plugin.terraform-provider-aws_v1.33.0_x4:       Values: ["vpc-XXXXXX"]
plugin.terraform-provider-aws_v1.33.0_x4:     },
plugin.terraform-provider-aws_v1.33.0_x4:     {
plugin.terraform-provider-aws_v1.33.0_x4:       Name: "tag:environment",
plugin.terraform-provider-aws_v1.33.0_x4:       Values: ["production"]
plugin.terraform-provider-aws_v1.33.0_x4:     },
plugin.terraform-provider-aws_v1.33.0_x4:     {
plugin.terraform-provider-aws_v1.33.0_x4:       Name: "tag:network",
plugin.terraform-provider-aws_v1.33.0_x4:       Values: ["private"]
plugin.terraform-provider-aws_v1.33.0_x4:     },
plugin.terraform-provider-aws_v1.33.0_x4:     {
plugin.terraform-provider-aws_v1.33.0_x4:       Name: "tag:Tier",
plugin.terraform-provider-aws_v1.33.0_x4:       Values: ["Private"]
plugin.terraform-provider-aws_v1.33.0_x4:     }
plugin.terraform-provider-aws_v1.33.0_x4:   ]
plugin.terraform-provider-aws_v1.33.0_x4: }

```

### Expected Behavior
Find the subnets using the specified tags without the variable default value

### Actual Behavior
Unable to find the subnets as the default value was included in the filter when interpolated

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by stephencoe** [comment]
Providing a simplified test scenario

**main.tf**
```
variable "subnet_tags" {
  type        = "map"
  default = {
    Tier = "Private"
  }
}

output "subnet_tags" {
  value = "${var.subnet_tags}"
}
```
**tfvars**
```
subnet_tags = {
  environment = "production"
  network = "private"
}
```

**Outputs:**
```
subnet_tags = {
  Tier = Private
  environment = production
  network = private
}
```

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
