### ISSUE TITLE
Add missing policies to EKS example

### ISSUE THREAD

**Issue by smaslennikov** [terraform-providers/terraform-provider-aws#5669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `aws_eks_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

These three policies seem to be required for provisioning an NLB (following [this](https://kubernetes.github.io/ingress-nginx/deploy/#aws) guide, deploying [this](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/aws/service-nlb.yaml) service):

      * ec2:DescribeAccountAttributes
      * ec2:DescribeInternetGateways
      * iam:CreateServiceLinkedRole

### Expected Behavior

NLB is provisioned.

### Actual Behavior

Ingress service throws errors of lack of authorization.

### Steps to Reproduce

1. `terraform apply`
2. Provision the [NLB ingress service](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/aws/service-nlb.yaml)

**Comment by bflad** [comment]
Closing as discussed in #5670 👍
