### ISSUE TITLE
Depends on not working for aws_cloudwatch_log_subscription_filter 

### ISSUE THREAD

**Issue by LauraZhouYu** [terraform-providers/terraform-provider-aws#5695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.33

### Affected Resource(s)

aws_cloudwatch_log_subscription_filter
### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

resource "aws_rds_cluster" "default" {
  cluster_identifier = "${var.env_name}-aurora-cluster"
  master_username    = "${var.master_user}"

  master_password = "${random_string.password.result}"

  # master_password = "${var.master_password}"

  backup_retention_period         = "${var.backup_retention_period}"
  db_subnet_group_name            = "${aws_db_subnet_group.db_subnet_group.name}"
  db_cluster_parameter_group_name = "${aws_rds_cluster_parameter_group.cluster-pg.name}"
  final_snapshot_identifier       = "${var.env_name}-aurora-cluster-snapshot"
  apply_immediately               = "${var.apply_immediately}"
  vpc_security_group_ids          = ["${aws_security_group.aurora_sg.id}"]
  engine                          = "${var.instance_engine_type}"
  engine_version                  = "${var.instance_engine_version}"
  storage_encrypted               = "${var.storage_encrypted}"
  kms_key_id                      = "${var.kms_key_id}"
  backup_retention_period         = "${var.backup_retention_period}"
  enabled_cloudwatch_logs_exports = "${var.enabled_cloudwatch_logs_exports}"
}

...

resource "aws_cloudwatch_log_subscription_filter" "subscription_filter" {
  name            = "${var.env_name}"
  role_arn        = "${aws_iam_role.role.arn}"
  log_group_name  = "/aws/rds/cluster/${aws_rds_cluster.default.cluster_identifier}/audit"
  filter_pattern  = ""
  destination_arn = "${aws_kinesis_stream.kinesis.arn}"
  count = "${aws_rds_cluster.default.enabled_cloudwatch_logs_exports[0] == "audit" ? 1 : 0}"
  depends_on = ["aws_rds_cluster.default"]
}

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* aws_cloudwatch_log_subscription_filter.subscription_filter: 1 error(s) occurred:

* aws_cloudwatch_log_subscription_filter.subscription_filter: ResourceNotFoundException: The specified log group does not exist.
	status code: 400, request id: 3a1b8c58-aa41-11e8-8243-73dcd6df7ae2

### Expected Behavior

subscription filter works after creating cloud watch log group
### Steps to Reproduce
TF cannot find the cloud watch log group at the first run time, even though in AWS UI the log group is there and rds audit logs stay in the log group. Kinesis subscription works effectively at the second run time.

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Closing due to lack of response.

**Comment by jkhalid** [comment]
Hello ,
I am having the same issue

I created the cloudwatch group early in my script

      // create a cloudwatch log group
resource "aws_cloudwatch_log_group" "NotifyFraudLambda" {
  name = "NotifyFraudLambda"
}

//allow cloudwatch for lambda
resource "aws_lambda_permission" "cloudwatch_allow" {
  statement_id  = "cloudwatch_allow_splunk"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.lambda-NotifyFraudLambda.arn}"
  principal     = "lambda.amazonaws.com"
}
//forward to splunk
resource "aws_cloudwatch_log_subscription_filter" "test_lambdafunction_logfilter" {
  name            = "test_lambdafunction_logfilter"
  log_group_name  = "/aws/lambda/NotifyFraudLambda"
  filter_pattern  = ""
  destination_arn = "arn:aws:logs:us-east-1:XXXXXXXXXX:destination:XXXXXXX-cloudwatch-lambda-destination-us-east-1"
}
Terraform fails : aws_cloudwatch_log_subscription_filter.test_lambdafunction_logfilter: ResourceNotFoundException: The specified log group does not exist.
	status code: 400, request id: e7f5226d-c5e3-11e8-8255-d76a5a3b2d7e
but
when I have the log group manually created in the console everything works correctly .

**Comment by LauraZhouYu** [comment]
Thanks Brian! That helps!
