### ISSUE TITLE
Allow to opt out aws_ac_certificate from Certificate Transparency Logging

### ISSUE THREAD

**Issue by gfa** [terraform-providers/terraform-provider-aws#5696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow to opt out `aws_ac_certificate` from Certificate Transparency Logging 

By default ACM certs are published in transparency logs, for private certificates we want to avoid that.
Default should be kept publishing the certs

### New or Affected Resource(s)

 aws_acm_certificate

### Potential Terraform Configuration

```hcl
resource "aws_acm_certificate" "cert" {
  domain_name       = "example.com"
  validation_method = "DNS"
  transparency = "DISABLED"
}
```

### References

https://docs.aws.amazon.com/acm/latest/userguide/acm-bestpractices.html#best-practices-transparency

**Comment by nywilken** [comment]
@gfa thanks for opening up this request. I am closing this issue in favor of #6789. Please feel free to add any new comments or votes there.
