### ISSUE TITLE
 aws_api_gateway_integration reapplying each time

### ISSUE THREAD

**Issue by stafot** [terraform-providers/terraform-provider-aws#5697]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
`0.11.8`

###Terraform Provider Version
`1.33`

### Affected Resource(s)

* aws_api_gateway_integration

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_integration" "get_root_integration" {
  rest_api_id             = "${aws_api_gateway_rest_api.data_feed.id}"
  resource_id             = "${aws_api_gateway_rest_api.data_feed.root_resource_id}"
  http_method             = "${aws_api_gateway_method.get_root_method.http_method}"
  integration_http_method = "GET"
  type                    = "MOCK"
}
```

### Expected Behavior

Apply successfully.

### Actual Behavior

Asks for reapply everytime and forces new resource because of `integration_http_method`. If you import it the value in `terraform.tfstate` is empty while should be `GET`. Even if you manually patch `terraform.tfstate` and assign to   `integration_http_method` `GET` as value, still every time ask to replace the resource. 

### Steps to Reproduce

1. Update to provider `1.33`
2. `terraform apply`

### Notes

Worked as expected till `1.32`. Possibly related with https://github.com/terraform-providers/terraform-provider-aws/pull/5568

**Comment by bflad** [comment]
Hi @stafot 👋  Is setting `integration_http_method` required when using type `MOCK`? What happens if you remove it?

Previous to 1.33.0 of the AWS provider, the resource was not attempting to detect drift from API Gateway for the `integration_http_method` attribute. Now it is reading that information back from the API. It might be that API Gateway accepts the extraneous parameter, but does not return it since it is not applicable.

**Comment by stafot** [comment]
@bflad Thanks for your fast response. You are right it is not a bug on your end but a wrong declaration of mine. Seems that `MOCK` type is mutually excluded with `integration_http_method`, sets it to empty string and not one of the valid values for `integration_http_method` (`GET`, `POST`, etc.) which makes sense to me. Thank for help me clarifying the issue. It might need a small improvement on  resource documentation (https://www.terraform.io/docs/providers/aws/r/api_gateway_integration.html) for this because current is not as clear as it could be for this. Anyway this is very minor.
