### ISSUE TITLE
Terraform plan stop at aws_ssm_parameter

### ISSUE THREAD

**Issue by at-bachhuynh** [terraform-providers/terraform-provider-aws#5717]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
$terraform -v 
Terraform v0.11.8

### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Finish Terraform Plan

### Actual Behavior
Hang at:
nal)
aws_cloudwatch_metric_alarm.database_disk_free_readreplica_c: Refreshing state... (ID: alarm-circle-DatabaseServerFreeStorageSpace-db-replica-c-01)
aws_cloudwatch_metric_alarm.database_memory_free_readreplica_c: Refreshing state... (ID: alarm-circle-DatabaseServerFreeableMemory-db-replica-c-01)
aws_cloudwatch_metric_alarm.database_disk_queue_readreplica_c: Refreshing state... (ID: alarm-circle-DatabaseServerDiskQueueDepth-db-replica-c-01)
aws_cloudwatch_metric_alarm.database_connection_readreplica_c: Refreshing state... (ID: alarm-circle-DatabaseServerConnection-db-replica-c-01)
aws_cloudwatch_metric_alarm.database_cpu_readreplica_a: Refreshing state... (ID: alarm-circle-DatabaseServerCPUUtilization-circle-circle-db-replica-a-01)
aws_ssm_parameter.batch-database_read-user: Refreshing state... (ID: /circle-batch-config/database_read.user)
aws_cloudwatch_metric_alarm.database_connection_readreplica_a_external: Refreshing state... (ID: alarm-circle-DatabaseServerConnection-db-replica-a-01-external)
aws_cloudwatch_metric_alarm.database_connection_readreplica_a: Refreshing state... (ID: alarm-circle-DatabaseServerConnection-db-replica-a-01)
aws_ssm_parameter.database_read-user: Refreshing state... (ID: /circle-api-config/database_read.user)
aws_cloudwatch_metric_alarm.database_disk_queue_readreplica_a: Refreshing state... (ID: alarm-circle-DatabaseServerDiskQueueDepth-db-replica-a-01)
aws_ssm_parameter.admin-database_read-user: Refreshing state... (ID: /circle-admin-config/database_read.user)
aws_cloudwatch_metric_alarm.database_disk_free_readreplica_a: Refreshing state... (ID: alarm-circle-DatabaseServerFreeStorageSpace-db-replica-a-01)
aws_cloudwatch_metric_alarm.database_memory_free_readreplica_a: Refreshing state... (ID: alarm-circle-DatabaseServerFreeableMemory-db-replica-a-01)
aws_route53_health_check.readreplica_c: Refreshing state... (ID: 2a707d3a-f8a5-4b9c-a4b9-07ca8e812825)
aws_ssm_parameter.batch-database_master-host: Refreshing state... (ID: /circle-batch-config/database_master.host)
aws_ssm_parameter.database_master-host: Refreshing state... (ID: /circle-api-config/database_master.host)
aws_ssm_parameter.admin-database_master-host: Refreshing state... (ID: /circle-admin-config/database_master.host)
aws_route53_health_check.readreplica_a: Refreshing state... (ID: 9c2fb394-3509-4644-96ab-8234838d80f8)
aws_route53_record.readreplica_c: Refreshing state... (ID: Z2OCSDUEVB5DIW_read_CNAME_replica-c-01)
aws_route53_record.readreplica_a: Refreshing state... (ID: Z2OCSDUEVB5DIW_read_CNAME_replica-a-01)
aws_ssm_parameter.batch-database_read-host: Refreshing state... (ID: /circle-batch-config/database_read.host)
aws_ssm_parameter.database_read-host: Refreshing state... (ID: /circle-api-config/database_read.host)
aws_ssm_parameter.admin-database_read-host: Refreshing state... (ID: /circle-admin-config/database_read.host)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by dav009** [comment]
it seems it was indeed related to AWS api issues. plans/applies are working ok for me now

**Comment by bflad** [comment]
Hi @at-bachhuynh 👋  Sorry you are running into trouble here.

Are you able to [enable debug logging](https://www.terraform.io/docs/internals/debugging.html) and see what the AWS SDK is getting hung up on? If its having trouble with a certain API call and entering a retry loop, you will be able to see it in those debugs logs (or feel free to pass them along here in a [Gist](https://gist.github.com/) and we can take a look).

Its probably worth knowing your AWS provider version as well since we've recently fixed some behavior with the `aws_ssm_parameter` resource, if it is something related to that resource in particular. You can get that via: `terraform -v` or `terraform providers` in the directory you are running Terraform.

**Comment by bflad** [comment]
Closing due to lack of response.
