### ISSUE TITLE
Additional ECS parameters for CloudWatch events target

### ISSUE THREAD

**Issue by dalen** [terraform-providers/terraform-provider-aws#5722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has silently added support for a bunch of new parameters on ECS targets, for example setting the launch type to Fargate etc. It would be good if terraform supported this.

New attributes in the API are:
 * Group
 * LaunchType
 * NetworkConfiguration
 * PlatformVersion

### New or Affected Resource(s)

* aws_cloudwatch_event_target

### References

* https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_EcsParameters.html

**Comment by dalen** [comment]
Now they have added it to their blog as well: https://aws.amazon.com/about-aws/whats-new/2018/08/aws-fargate-now-supports-time-and-event-based-task-scheduling/

**Comment by mspike** [comment]
a terrible but working "workaround", for the time is to create a null_resource, with local-exec provisioner, calling the aws-cli to put the last piece into the puzzle:

`resource "null_resource" "workaround" {
    depends_on = ["aws_iam_role_policy.ecs_events_run_task_with_any_role"]
    provisioner "local-exec" {
    command = <<EOM
  AWS_PROFILE='${var.profile}'
  aws events put-targets \
    --rule "${aws_cloudwatch_event_rule.<RESOURCE>.name}" \
    --targets='Id=1,Arn=${aws_ecs_cluster.<CLUSTER>.arn},RoleArn=${aws_iam_role.<ROLE>.arn},EcsParameters={TaskDefinitionArn=${aws_ecs_task_definition.<TASK>.arn},TaskCount=1,LaunchType=FARGATE,NetworkConfiguration={awsvpcConfiguration={Subnets=[<SUBNET>],SecurityGroups=[<SG>],AssignPublicIp=DISABLED}}}'
EOM
  }
}`

Again, terrible, but works till this gets implemented. (as long as you have an up to date aws cli installed and you define the "AWS_PROFILE" or authenticate in some other way.

**Comment by bflad** [comment]
Support for the new ECS parameters has been merged and will release with version 1.39.0 of the AWS provider, likely middle of next week. 👍
