### ISSUE TITLE
Resource aws_emr_cluster doesn't support import

### ISSUE THREAD

**Issue by AliGrab** [terraform-providers/terraform-provider-aws#5724]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We'd like to import our existing EMR clusters into terraform

### New or Affected Resource(s)

*  aws_emr_cluster 

### Potential Terraform Configuration

terraform import aws_emr_cluster.emr-test-cluster j-XXXXXXXXXXXXX

### References

* https://www.terraform.io/docs/providers/aws/r/emr_cluster.html

**Comment by bflad** [comment]
Good news, there is already an open pull request for this functionality: #4488

**Comment by bflad** [comment]
Support for resource import has been merged and will release with version 1.56.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.56.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1560-january-16-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
