### ISSUE TITLE
Cannot create rds aurora cluster in ap-southeast-1c

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [terraform-providers/terraform-provider-aws#5725]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
▶ terraform version
Terraform v0.11.1
+ provider.aws v1.33.0

### Affected Resource(s)
```
Error: Error applying plan:

1 error(s) occurred:

* aws_rds_cluster.trx_service_postgres_dev: 1 error(s) occurred:

* aws_rds_cluster.trx_service_postgres_dev: error creating RDS cluster: InvalidVPCNetworkStateFault: Availability zone '[ap-southeast-1c]' is unavailable in this region, please choose another zone set.
        status code: 400, request id: 47b789f7-69d3-47ac-b5e2-bf4a35c80c11

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Terraform Configuration Files
```hcl
variable "singapore_availability_zones" {
    type = "list"
    description = "Run the EC2 Instances in these Availability Zones"

    default = ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
}

resource "aws_rds_cluster_instance" "trx_service_postgres_dev" {
    provider = "aws.singapore"
    count = 2

    identifier         = "name"
    cluster_identifier = "name"
    engine = "aurora-postgresql"
    instance_class     = "db.r4.xlarge"
    db_subnet_group_name = "name"
    availability_zone = "${element(var.singapore_availability_zones, count.index)}"

    tags {
        Name = "postgres"
    }
}
```

### Expected Behavior
RDS Cluster created and can support ap-southeast-1c

### Actual Behavior
ap-southeast-1c is not supported

### References

* #0000

**Comment by bflad** [comment]
Hi @LieAlbertTriAdrian 👋 

The error you are seeing: `InvalidVPCNetworkStateFault: Availability zone '[ap-southeast-1c]' is unavailable in this region, please choose another zone set.` is being returned from the RDS API. It may be possible that the RDS service in that region does not support all availability zones. Can you confirm with AWS Support that this specific availability zone should be usable with RDS?

**Comment by LieAlbertTriAdrian** [comment]
Hey looks like it's because I haven't created subnet in ap-southeast-1c, so it's resolved by creating it. Thanks!
