### ISSUE TITLE
aws_cloudwatch_dashboard dashboard_body parameter should be computed

### ISSUE THREAD

**Issue by lfshr** [terraform-providers/terraform-provider-aws#5729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_cloudwatch_dashboard

### Terraform Configuration Files

```hcl
variable "dashboard" {}
resource "aws_cloudwatch_dashboard" "mydash" {
  dashboard_name = "foo"
  dashboard_body = "${dashboard}"
}
```

### Expected Behavior

Terraform creates the dashboard, and ignores any incoming changes from Azure (formatting or otherwise)

### Actual Behavior

Terraform tries to apply the dashboard on subsequent applies. Despite there being no change.

### Steps to Reproduce

Run the terraform a few times with dashboard_body provided.

### References

* https://stackoverflow.com/questions/52067675/terraform-apply-keeps-changing-things-even-though-no-tf-files-have-changed

**Comment by aeschright** [comment]
Hi @lfshr, thanks for taking the time to report this! Since you don't have a Terraform or AWS provider version listed, I'm going to close the issue for now. If it's still happening on Terraform 0.12 and the latest provider version, please let us know by opening a new bug report issue with the requested details.
