### ISSUE TITLE
IoT Rule Firehose Action - add separator property

### ISSUE THREAD

**Issue by bdoepf** [terraform-providers/terraform-provider-aws#5733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS IoT Core's topic rule Firehose action has a 'separator' property which is currently not supported by the terraform aws provider.

### New or Affected Resource(s)

* aws_iot_topic_rule

### References

* https://docs.aws.amazon.com/iot/latest/developerguide/iot-rule-actions.html#firehose-rule
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-firehoseaction.html
* https://www.terraform.io/docs/providers/aws/r/iot_topic_rule.html

**Comment by bflad** [comment]
Support for this has been merged into master and will release with version 1.36.0 of the AWS provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 1.36.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1360-september-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
