### ISSUE TITLE
ecr_registry: repositry_url output doesn't support china/gov region

### ISSUE THREAD

**Issue by ofirnn** [terraform-providers/terraform-provider-aws#5741]
### Terraform Version
0.11.3

### Affected Resource(s)

* aws_ecr_repository

### Terraform Configuration Files

output "e2e_ecr_url" {
  value = "${aws_ecr_repository.attribution-cf-e2e.repository_url}"
}

### Expected Behavior

URL ends with com.cn for cn-north-1 region

### Actual Behavior
URL ends with com for cn-north-1 region

### Steps to Reproduce
Create ECR repository in china
Try to output the URL

**Comment by ofirnn** [comment]
https://github.com/terraform-providers/terraform-provider-aws/blob/269f4095e9c285fbc0468805a350ee0938a2e4d9/aws/resource_aws_ecr_repository.go#L103

**Comment by bflad** [comment]
I have submitted a bug fix pull request for this resource to use the `RepositoryUri` attribute from the API (was not available when the resource was first created) instead of building it ourselves: #5748

**Comment by bflad** [comment]
The fix for this has been merged into master and will release with version 1.35.0 of the AWS provider, likely middle of next week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.35.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1350-september-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
