### ISSUE TITLE
Altering imported Lambda function resource results in a `diffs didn't match during apply` error

### ISSUE THREAD

**Issue by bleggett** [terraform-providers/terraform-provider-aws#5742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.8

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```hcl
# Deploy the function with the correct role.
resource "aws_lambda_function" "proxyfunc" {
  function_name    = "${var.env_prefix}-proxyfunc"
  role             = "${aws_iam_role.lambda-role.arn}"
  handler          = "proxyfunc.handler"
  runtime          = "nodejs8.10"

  lifecycle {
    ignore_changes = [
      "function_name",
      "runtime",
      "handler"
    ]
  }
}

```
Have to use `ignore_changes` here, because I only want to update the function role for the existing function, and those 3 fields are required if I do not ignore them.

### Debug Output
https://gist.github.com/bleggett/48dbc654c9e0f295e2a1a6ac997a1276

`diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.`

### Expected Behavior
Given a preexisting Lambda function named `test-func`

running 
```
terraform import --function-name test-func
terraform apply -var env_prefix=fubar
```
should result in the function being imported, and the existing resource should be updated with the new role.
### Actual Behavior

`terraform input` succeeds, `terraform apply` fails with the above diff exception.

### Steps to Reproduce

```
terraform import --function-name test-func
terraform apply -var env_prefix=fubar
```

**Comment by bleggett** [comment]
More info by following the below steps:

1. Running `terraform input` on the Lambda function works.

2. Running `terraform plan` succeeds and but does **NOT** show the correct set of changes for the lambda function (the lambda role is **NOT** updated)

3. Running `terraform apply` immediately after that fails with the same diff out of sync exception as before.

4. Running  `terraform plan` immediately after that succeeds and **DOES** show the correct set of changes for the lambda function (the lambda role **IS** updated)

5. And running `terraform apply` a second time immediately after the above step succeeds without a diff exception and performs the correct operation.

**Comment by bleggett** [comment]
After some more investigation I am inclined to think this is an issue with core Terraform, and not this provider, though I lack the insight into the codebase to be sure of that.

**Comment by aeschright** [comment]
Hi @bleggett ! Unfortunately the message you saw isn't enough for us to go on to investigate the error. The debugging situation should be improved if you upgrade to Terraform 0.12 and the latest AWS provider. If you still see an error in this situation, please open a new bug report and we'll dig into it. Thanks!
