### ISSUE TITLE
aws_eks_cluster: Add support for Platform Version attribute

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#5796]
Amazon recently added support for EKS [platform versions](https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html).
Add a new computed attribute `platform_version` to the `aws_eks_cluster` data source and resource.

**Comment by ewbankkit** [comment]
Depends on:
* https://github.com/terraform-providers/terraform-provider-aws/pull/5753

**Comment by bflad** [comment]
Support for this new attribute in the data source and resource has been merged into master and will release with version 1.35.0 of the AWS provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 1.35.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1350-september-06-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
