### ISSUE TITLE
Error destroying Lambda@Edge function

### ISSUE THREAD

**Issue by amerani** [terraform-providers/terraform-provider-aws#5818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
▶ terraform -v
Terraform v0.11.8
+ provider.aws v1.35.0
```

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "fn" {
    function_name = "${var.function_name}"
    runtime = "nodejs8.10"
    handler = "index.handler"
    role = "arn:aws:iam::462291994574:role/service-role/lambda-s3-read-only"
    source_code_hash = "${base64sha256(file("function.zip"))}"
    filename = "function.zip"
    publish = true
}

resource "aws_cloudfront_distribution" "dist" {
    default_cache_behavior {
        ....
        lambda_function_association {
            event_type = "viewer-response"
            lambda_arn = "${aws_lambda_function.fn.qualified_arn}"
        }
    }
}
```

### Expected Behavior

Should have destroyed Lambda function after CloudFront Distribution was destroyed and had disassociated the function

### Actual Behavior
S3 Bucket and CloudFront Distribution was destroyed but not the Lambda function
```
* aws_lambda_function.fn (destroy): 1 error(s) occurred:

* aws_lambda_function.fn: Error deleting Lambda Function: InvalidParameterValueException: Lambda was unable to delete arn:aws:lambda:us-east-1:462291994574:function:static-site-proxy:3 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.
	status code: 400, request id: 8dcbd1ee-b46d-11e8-816b-bdd2ab6f41bc
```

### Steps to Reproduce

1. `terraform apply`

**Comment by amerani** [comment]
Oops! Just realized the replica function takes a while to delete. If it doesn't in a few hours I'll reopen

**Comment by eschwartz** [comment]
The function does _not_ delete itself after a few hours. You need to rerun `terraform destroy`, several hours after your CloudFront distribution is destroyed.

**Comment by LevinDmytro2** [comment]
Is it possible to realize waiting  for removal of replicas, for example, through a timeout function, so that the terraform itself checks the fact of deleting replicas and then complete without error?
