### ISSUE TITLE
CodePipeline / CodeBuild should support multiple Source inputs

### ISSUE THREAD

**Issue by jrobison-sb** [terraform-providers/terraform-provider-aws#5826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS now supports multiple Source inputs for CodePipeline and CodeBuild. Terraform AWS provider should support this as well. Please see:

https://aws.amazon.com/about-aws/whats-new/2018/08/aws-codebuild-adds-ability-to-create-build-projects-with-multiple-input-sources-and-output-artifacts/

https://docs.aws.amazon.com/codebuild/latest/userguide/sample-pipeline-multi-input-output.html

### New or Affected Resource(s)

* aws_codepipeline
* aws_codebuild_project

### Potential Terraform Configuration

N/A

### References

* https://aws.amazon.com/about-aws/whats-new/2018/08/aws-codebuild-adds-ability-to-create-build-projects-with-multiple-input-sources-and-output-artifacts/
* https://docs.aws.amazon.com/codebuild/latest/userguide/sample-pipeline-multi-input-output.html

**Comment by bflad** [comment]
Support for `secondary_sources` and `secondary_artifacts` for the `aws_codebuild_project` resource has been merged into master and will release with version 1.38.0 of the AWS provider, likely middle of next week.

**Comment by marcoreni** [comment]
@bflad In order to fully support multiple source/artifacts we must also change codepipeline, so this shohuld stay open until then...

**Comment by bflad** [comment]
This has been released in [version 1.38.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1380-september-26-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
