### ISSUE TITLE
aws_lb does not ignore empty values in security_groups list

### ISSUE THREAD

**Issue by jeohist** [terraform-providers/terraform-provider-aws#5836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.8

### Affected Resource(s)

* aws_lb

### Terraform Configuration Files

```hcl
resource "aws_lb" "foobar_lb" {
  security_groups = ["${var.foo}", "${var.bar}"]
}

variable "foo" {
  default = "sg-abcdabcd"
}

variable "bar" {
  default = ""
}
```

### Expected Behavior

aws_lb resource "foobar_lb" should be created (or modified) with just sg-abcdabcd attached, like this:
```resource.aws_lb.foobar_lb
      security_groups.#:          "" => "1"
      security_groups.1234512345: "" => "sg-abcdabcd"
```

### Actual Behavior

aws_lb resource "foobar_lb" is created like this:

```resource.aws_lb.foobar_lb
      security_groups.#:          "" => "2"
      security_groups.0:          "" => ""
      security_groups.1234512345: "" => "sg-abcdabcd"
```

This is also the case in the state file. security_groups.0 will always be null and will always get modified in any future plans and applies. 

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @jeohist 👋 

In this scenario, you will likely want to utilize the [`compact()` interpolation function](https://www.terraform.io/docs/configuration/interpolation.html#compact-list-), e.g. something like

```hcl
resource "aws_lb" "foobar_lb" {
  security_groups = ["${compact(list(var.foo, var.bar)}"]
}
```

Can you give this a shot and let us know how it goes?
