### ISSUE TITLE
KMS encryption at rest for Elastic Search Domain Resource Forces a New Resource 

### ISSUE THREAD

**Issue by anuragsernapally** [terraform-providers/terraform-provider-aws#5839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.7

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```
resource "aws_elasticsearch_domain" "es" {
  domain_name           = "${var.es_domain_name}"
  elasticsearch_version = "${var.es_version}"

  #### Encryption not enabled for t2,r3 and m3 type instances
  encrypt_at_rest {
    enabled = "${var.es_encryption_value}"
    kms_key_id = "${length(var.es_kms_key) > 0 ? var.es_kms_key : data.aws_kms_alias.foo.arn}"
  }

  cluster_config {
    instance_type            = "${var.es_instance_type}"
    instance_count           = "${var.es_instance_count}"
    dedicated_master_enabled = "${var.es_dedicated_master}"
    dedicated_master_type    = "${var.es_master_type}"
    dedicated_master_count   = "${var.es_master_count}"
    zone_awareness_enabled   = "${var.es_zone_awareness}"   # Zone awareness enablement should be done only if number of instances > 1
  }

  access_policies = "${data.template_file.es_access_policies.rendered}"

  vpc_options {
    security_group_ids = ["${aws_security_group.lz_es_sg.id}"]
    subnet_ids         = ["${var.es_subnet_ids}"]
  }

  ebs_options {
    ebs_enabled = "${var.es_ebs_option}"
    volume_type = "${var.es_volume_type}"
    volume_size = "${var.es_volume_size}"
  }

  snapshot_options {
    automated_snapshot_start_hour = "${var.es_snapshot_start}"
  }

  cognito_options {
    enabled          = "${var.es_cognitomode_enabled}"
    user_pool_id     = "${var.es_cognito_userpool_id}"
    identity_pool_id = "${var.es_cognito_identity_pool_id}"
    role_arn         = "${var.cognito_role_arn}"
  }

  advanced_options {
    "rest.action.multi.allow_explicit_index" = "xxx"
    "indices.fielddata.cache.size"           = "xx"
    "indices.query.bool.max_clause_count"    = "xxxx"
  }

  tags = "${merge(local.common_tags,var.tags)}"
}

```

### Expected Behaviour
```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
### Actual Behavior

```
      encrypt_at_rest.0.enabled:                               "true" => "true"
      encrypt_at_rest.0.kms_key_id:                            "arn:aws:kms:eu-central-1:xxxxxxxxxxxx:key/e97275b2-df99-4a8e-893c-592223d38714" => "arn:aws:kms:eu-central-1:xxxxxxxxxxx:alias/es2" (forces new resource)
      endpoint:                                                "vpc-lz-elasticsearch-test-jflqqo54zbu5ezx4taedqvjyn4.eu-central-1.es.amazonaws.com" => 
```

### Steps to Reproduce

1. `terraform apply`
Creates a new elastic search domain
2. `terraform apply`

### Important Factoids

*  Terraform resource document mentions that only when VPC options forces new resource creation
* Running terraform apply second time ideally should not create or delete any resources but should only update the configuration.
* This issue might cause loss of data when repoduced these steps unknowingly.

**Comment by bflad** [comment]
Hi @anuragsernapally 👋 

Does the difference go away if you reference the [`target_key_arn` attribute](https://www.terraform.io/docs/providers/aws/d/kms_alias.html#target_key_arn) instead of `arn` from the `aws_kms_alias` data source? Many AWS services automatically convert the KMS alias ARN to its corresponding KMS key ARN for resources that use KMS keys, but allow KMS aliases as input.

**Comment by anuragsernapally** [comment]
Hi @bflad , Thanks for the response.
The issue has been fixed and what you have said is perfectly correct. 
#FIX for the issue
```
  encrypt_at_rest {
    enabled    = "${var.es_encryption_value}"
   kms_key_id = "${length(var.es_kms_key) > 0 ? var.es_kms_key : data.aws_kms_alias.es.**target_key_id**}"
  }
```
