### ISSUE TITLE
aws_s3_bucket_object eventual consistency error after object creation

### ISSUE THREAD

**Issue by bpiper** [terraform-providers/terraform-provider-aws#5841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.10.8

### Affected Resource(s)

* aws_s3_bucket_object

### Expected Behavior

Resource creation successful.

### Actual Behavior

aws_s3_bucket_object.foo: Failed to get object tags (bucket: some-bucket, key: /foo): NoSuchKey: The specified key does not 

As is generally the case with eventual consistency issues, this only happens sometimes.

### Steps to Reproduce

Just define a standard S3 bucket object like so and run apply:

```
resource "aws_s3_bucket_object" "foo" {
  bucket = "some-bucket"
  key    = "/foo"
  source = "${path.module}/foo"
  etag   = "${md5(file("${path.module}/foo"))}"
}
```

This seems like just another Terraform AWS eventual consistency issue.  The resource is doing a HeadObject and a GetObjectTagging immediately after the PutObject.  In this particular case that I encountered, it was the GetObjectTagging request that hit a 404.  I have seen explicit retry logic used by other resources to accommodate eventual consistency, but there doesn't appear to be any in `resource_aws_s3_bucket_object.go`.  Resources absolutely should be reading after write to ensure they are in a consistent state, but this needs to be done with some sort of retry/timeout logic.

**Comment by bflad** [comment]
The fix for this is merged and will release with version 1.56.0 of the Terraform AWS provider, likely in the next day or two. 👍
