### ISSUE TITLE
Replace Usage of validateMaxLength() with validation.StringLenBetween()

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#5861]
Usage such as:

```go
ValidateFunc: validateMaxLength(2048),
```

Should be replaced with the upstream provider SDK function directly:

```
ValidateFunc: validation.StringLenBetween(0, 2048),
```

To remove the unnecessary indirection. 😄 

Documentation: https://godoc.org/github.com/hashicorp/terraform/helper/validation#StringLenBetween

**Comment by saravanan30erd** [comment]
@bflad I would like to help on this, I will start to work on this if you didn't start yet.

**Comment by bflad** [comment]
Go for it!
