### ISSUE TITLE
AWS ElasticSearch domain recreated on every run if KMS Key Alias is provided for encryption at rest

### ISSUE THREAD

**Issue by chirillc** [terraform-providers/terraform-provider-aws#5871]
I am facing an issue with Terraform v0.11.8 when AWS ElasticSearch domain is being recreated on every `terraform apply` run.
This issue only exists if I am using KMS key Alias for encryption at rest.
If KMS key id ARN used instead, the issue does not exist.

This is the code snippet:

```
resource "aws_kms_key" "elasticsearch_data_kms_key" {
  description   = "KMS key used to encrypt data stored on ElasticSearch"
 
  tags {
    Environment = "qa"
    Application = "saas"
  }
}

resource "aws_kms_alias" "elasticsearch_data_kms_key_alias" {
  name          = "alias/qa-saas-elasticsearch-data-kms-key"
  target_key_id = "${aws_kms_key.elasticsearch_data_kms_key.key_id}"
}

resource "aws_elasticsearch_domain" "clientapp_elasticsearch" {  
  domain_name = "qa-saas"
  elasticsearch_version = "6.3"  

  encrypt_at_rest {
    enabled = "true"
    kms_key_id = "${aws_kms_alias.elasticsearch_data_kms_key_alias.id}"
  }
  ...
}
```

`terraform plan` output:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ aws_elasticsearch_domain.clientapp_elasticsearch (new resource required)
      id:  "arn:aws:es:ca-central-1:xxx:domain/qa-saas-clientapp" => <computed> (forces new resource)
      advanced_options.%: "1" => <computed>
      arn: "arn:aws:es:ca-central-1:xxx:domain/qa-saas-clientapp" => <computed>
      cluster_config.#:                                           "1" => "1"
      cluster_config.0.dedicated_master_count:                    "3" => "3"
      cluster_config.0.dedicated_master_enabled:                  "true" => "true"
      cluster_config.0.dedicated_master_type:                     "m4.large.elasticsearch" => "m4.large.elasticsearch"
      cluster_config.0.instance_count:                            "2" => "2"
      cluster_config.0.instance_type:                             "m4.large.elasticsearch" => "m4.large.elasticsearch"
      cluster_config.0.zone_awareness_enabled:                    "true" => "true"
      domain_id:                                                  "xxx/qa-saas-clientapp" => <computed>
      domain_name:                                                "qa-saas-clientapp" => "qa-saas-clientapp"
      ebs_options.#:                                              "1" => "1"
      ebs_options.0.ebs_enabled:                                  "true" => "true"
      ebs_options.0.volume_size:                                  "100" => "100"
      ebs_options.0.volume_type:                                  "gp2" => "gp2"
      elasticsearch_version:                                      "6.3" => "6.3"
      encrypt_at_rest.#:                                          "1" => "1"
      encrypt_at_rest.0.enabled:                                  "true" => "true"
      encrypt_at_rest.0.kms_key_id:                               "arn:aws:kms:ca-central-1:xxx:key/c3d7741d-1d81-4bb4-9e6b-947e54ad2937" => "alias/qa-saas-elasticsearch-data-kms-key" (forces new resource)

```

If I understand the output correctly, `kms_key_id` parameter forces new resource, although same KMS key alias is used every time.

**Comment by bflad** [comment]
Hi @chirillc 👋  Sorry you are running into trouble here.

This issue should go away if you use the [`target_key_arn` attribute](https://www.terraform.io/docs/providers/aws/r/kms_alias.html#target_key_arn) in your reference for the `kms_key_id` argument instead of `id`, e.g.

```
kms_key_id = "${aws_kms_alias.elasticsearch_data_kms_key_alias.target_key_arn}"
```

Can you try that out and let us know? Thanks!

**Comment by chirillc** [comment]
@bflad the issue does go away, although I cannot use `target_key_arn` in my scenario as for CMKs with imported key material a new KMS Key ID is generated once it's rotated manually.
https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html#rotate-keys-manually

Recommended approach is to re-point KMS Key Alias to new Key Id, hence there's need to use key alias instead of ARN.

**Comment by bflad** [comment]
@chirillc you will likely need to make a choice in how you want to handle this situation in the configuration.

If an Elasticsearch domain was created using an "old" KMS key ID, then you need to continue referencing the old ID as there is currently no way to update an Elasticsearch domain KMS key ID as far as I can tell from the SDK documentation: https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/#UpdateElasticsearchDomainConfigInput

If you would like Terraform to instead ignore the change for the attribute, you can use the [lifecycle configuration block `ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes), e.g.

```hcl
resource "aws_elasticsearch_domain" "clientapp_elasticsearch" {
  # ... other configuration ...

  lifecycle {
    ignore_changes = ["encrypt_at_rest.0.kms_key_id"]
  }
}
```

In that case, Terraform will not show the update for the attribute, but if the resource is recreated it will be use the latest KMS key ID pointed to by the alias.

**Comment by tracypholmes** [comment]
Hi @chirillc! Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. It looks like you've gotten some great feedback in this thread. Please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
