### ISSUE TITLE
EKS-Getting-Started page is outdated

### ISSUE THREAD

**Issue by cazorla19** [terraform-providers/terraform-provider-aws#5880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Doesn't matter, it's about the docs

### Affected Resource(s)

* `aws_eks_cluster` and its components

### Terraform Configuration Files

I'm reporting about [EKS Getting Started Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/guides/eks-getting-started.html.md) as a documentation component.

What are the problems about:

1. Community AMI name prefix has been changed from `eks-worker-*` to `amazon-eks-node-*`

2. Userdata for get the node joining cluster is totally different. Instead of making script itself you just need to run the built-in-image script. Smth like:

```
#!/bin/bash -xe

# Bootstrap and join the cluster
/etc/eks/bootstrap.sh --b64-cluster-ca '${cluster_auth_base64}' --apiserver-endpoint '${endpoint}' --kubelet-extra-args '${kubelet_extra_args}' '${cluster_name}'
```

User adjust might not be clear, and time for cluster setup will be mostly wasted. So, I'll personally rewrite infrastructure, leaving this issue mostly for history and PR attachment.

### Expected Behavior

EKS cluster is up and running with no need to connect and debug EC2 instances.

### Actual Behavior

Terraform couldn't find the latest AMI image and reports an error.

After fixing issue #1: nodes can actually join the cluster, but DNS configuration is hecked up, so the deployments will not properly work on cluster by missing `cluster-dns` settings.

### Steps to Reproduce

Just go through this guide again from scratch.

### Important Factoids

Nothing special for account/resource, issue is common for everybody.

**Comment by cazorla19** [comment]
Please, assign me to the issue.

**Comment by cazorla19** [comment]
@bflad oh, I've checked your commit and it seems like you're doing the same thing I'd like to! Then this issue doesn't make sense. Sorry for confusion, I'll close it and track your today release then :)

**Comment by bflad** [comment]
@cazorla19 no worries! Thanks for your interest in fixing the documentation! 😄
