### ISSUE TITLE
Resource aws_ecs_repository_policy doesn't support import

### ISSUE THREAD

**Issue by mcqj** [terraform-providers/terraform-provider-aws#5921]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.8
provider.aws v1.35.0

### Affected Resource(s)
aws_ecs_service

### Terraform Configuration Files
```hcl
Not relevant
```

### Debug Output
Error: aws_ecr_repository_policy.cross-account-pull (import id: *****): import aws_ecr_repository_policy.cross-account-pull (id: *****): resource aws_ecr_repository_policy doesn't support import

### Expected Behavior
import succeeds without error

### Actual Behavior
Error as above

### Steps to Reproduce
try to import aws_ecs_service_policy

**Comment by madarve** [comment]
Your Debug ouput corresponds to another resource: `aws_ecr_repository` and not `aws_ecs_service` as the title suggests. which one is the correct ?

**Comment by mcqj** [comment]
Indeed it should read ecr

**Comment by bflad** [comment]
Support for importing `aws_ecr_repository_policy` resources has been merged and will release with version 2.3.0 of the Terraform AWS Provider, likely middle of this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
