### ISSUE TITLE
Documentation Missing info possibly: r/aws_instance

### ISSUE THREAD

**Issue by jz-wilson** [terraform-providers/terraform-provider-aws#5923]
On the webpage: [https://www.terraform.io/docs/providers/aws/r/instance.html](https://www.terraform.io/docs/providers/aws/r/instance.html)

ebs_block_device does not show all available volume types like it does on:
[https://www.terraform.io/docs/providers/aws/r/ebs_volume.html](https://www.terraform.io/docs/providers/aws/r/ebs_volume.html)

Just letting you know! Keep up the great work guys!

**Comment by jasonrojas** [comment]
```
$ terraform -version
Terraform v0.11.8
+ provider.aws v1.36.0
```
Upgraded to the latest tf and aws-provider and the issue still exists.

**Comment by tracypholmes** [comment]
Hi, @jz-wilson - thank you for letting us know! The documentation has been updated and should be published around the middle of next week.
