### ISSUE TITLE
aws_instance data source should expose "user_data" content 

### ISSUE THREAD

**Issue by zytek** [terraform-providers/terraform-provider-aws#5927]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws_instance data source exposes `user_data` only as hash. There is no option to view/save/use original script. This seems inconsistent with original resource meaning of `user_data`

### New or Affected Resource(s)

* data source aws_instance

### Proposed solution

Apart from `user_data` attribute we could expose `user_data_script` or `user_data_content`.
The original field name should be called `user_data_hash` IMHO but that would be a breaking change, so probably not worth it.

**Comment by zytek** [comment]
I can work on this issue, please comment on variable naming.

**Comment by saravanan30erd** [comment]
@zytek If you change the existing attr name `user_data` to `user_data_hash`, it will affect the existing tf configuration. I think it's better to just add new attr for actual content and `user_data_content` looks more relevant to me.

**Comment by bflad** [comment]
Pull request submitted to optionally return the Base64 encoded data into a `user_data_base64` attribute: #8001

**Comment by bflad** [comment]
The above support has been merged in and will release with version 2.3.0 of the Terraform AWS Provider, likely in the next day or two.

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
