### ISSUE TITLE
How to enable logging for AWS AppSync APIs

### ISSUE THREAD

**Issue by yerriswamykonanki** [terraform-providers/terraform-provider-aws#5937]
I am trying to enable logging for AppSync API, but I didn't find any parameters for the aws_appsync_graphql_api resource.
Could anyone help me out in this?
Thanks in advance.

**Comment by bflad** [comment]
Pull request submitted to support logging configuration: #6138

**Comment by bflad** [comment]
This has been released in [version 1.41.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1410-october-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
