### ISSUE TITLE
MediaConvert Documentation

### ISSUE THREAD

**Issue by lkhari** [terraform-providers/terraform-provider-aws#5943]
We can see the implementation of MediaConvert [here](https://github.com/terraform-providers/terraform-provider-aws/tree/master/vendor/github.com/aws/aws-sdk-go/service/mediaconvert), but there isn't any documentation on the terraform website.

Is it going to be published soon or is it available on any other repository?

**Comment by bflad** [comment]
Hi @lkhari 👋 

The `vendor` directory is special for Go language projects (like this project): https://golang.org/cmd/go/#hdr-Vendor_Directories

It just means we only performed the very first step in supporting any sort of AWS MediaConvert resources or datasources within this Terraform provider. While the AWS Go SDK code was pulled in via #2481 I don't immediately see other GitHub issues that are feature requests for this AWS service. Can you please update the title and issue description for what you are looking for? Thanks.
