### ISSUE TITLE
README.md build instructions not working

### ISSUE THREAD

**Issue by ChBi89** [terraform-providers/terraform-provider-aws#5951]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue description

I am trying to build the unaltered terraform provider for aws using the description in README.md.
I would like to start contributing to terraform as I very regularly use it. But I have problems getting started to even build the code without changes.

```
ubuntu@ip-172-31-87-247:~/go/src/github.com/terraform-providers/terraform-provider-aws$ make build
==> Checking that code complies with gofmt requirements...
go install
unexpected directory layout:
        import path: github.com/hashicorp/terraform/plugin
        root: /home/ubuntu/go/src
        dir: /home/ubuntu/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin
        expand root: /home/ubuntu/go/src
        expand dir: /home/ubuntu/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin
        separator: /
GNUmakefile:10: recipe for target 'build' failed
make: *** [build] Error 1
```

### Terraform Version
```
ubuntu@ip-172-31-87-247:~$ terraform -v
Terraform v0.11.8
```

### Go Version
```
ubuntu@ip-172-31-87-247:~$ go version
go version go1.11 linux/amd64
```

### Go Env
```
ubuntu@ip-172-31-87-247:~$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build881481085=/tmp/go-build -gno-record-gcc-switches"
```

### Expected Behavior

I expect to be able to use the commands inside README.md and get to an working build.

### Important Factoids

I am running on an AWS EC2 Instance with Ubuntu 16.04 which has been empty created for that purpose. Go is the latest version downloaded today from the website.

**Comment by WhileLoop** [comment]
Try running it in `/home/ubuntu/go/src/github.com/terraform-providers/terraform-provider-aws/` instead of `/home/ubuntu/go/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin`

**Comment by ChBi89** [comment]
Hey WhileLoop,
That is where I have been running it. The issue description code box shows I am in that path.
`ubuntu@ip-172-31-87-247:~/go/src/github.com/terraform-providers/terraform-provider-aws$ make build`

**Comment by tracypholmes** [comment]
Hi, @ChBi89 👋  Are you still having an issue?

**Comment by bflad** [comment]
Closing due to lack of response. Please reach out if you are still having trouble. 👍
