### ISSUE TITLE
Cognito User Groups Configuration causing toggle between MFA and auto verified attributes

### ISSUE THREAD

**Issue by mattbryce93** [terraform-providers/terraform-provider-aws#5964]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.22.0
+ provider.http v1.0.1
+ provider.template v1.0.0

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

```hcl
resource "aws_cognito_user_pool" "user_pool" {
  name = "development-cognito-agents"
  schema = {
      attribute_data_type = "String"
      name                = "email"
      required            = true
      string_attribute_constraints {
        min_length = 6
        max_length = 32
    }
  }

  password_policy = {
      minimum_length = 10
      require_lowercase = true
      require_numbers   = true
      require_symbols   = false
      require_uppercase = true
  }
  admin_create_user_config = {
      allow_admin_create_user_only = false
  }
  verification_message_template = {
      default_email_option = "CONFIRM_WITH_CODE"
  }
  auto_verified_attributes = ["email"]
  mfa_configuration        = "OPTIONAL"
}
```
### Expected Behavior

A user pool should have been created with MFA set to optional and email selected as an attribute to be verified on sign up

### Actual Behavior

The user pool toggles between applies from having the MFA set to Optional and email not being selected for verification. To having MFA set to Off and the email being selected for verification.

### CLI output (these are the outputs for 2 terraform plan commands run subsequently after applying the config once in between and once before).
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.cognito-user-pool.aws_cognito_user_pool.user_pool[0]
      auto_verified_attributes.#:         "0" => "1"
      auto_verified_attributes.881205744: "" => "email"

  ~ module.cognito-user-pool.aws_cognito_user_pool.user_pool[1]
      auto_verified_attributes.#:         "0" => "1"
      auto_verified_attributes.881205744: "" => "email"

  ~ module.cognito-user-pool.aws_cognito_user_pool.user_pool[2]
      auto_verified_attributes.#:         "0" => "1"
      auto_verified_attributes.881205744: "" => "email"


Plan: 0 to add, 3 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.cognito-user-pool.aws_cognito_user_pool.user_pool[0]
      mfa_configuration: "OFF" => "OPTIONAL"

  ~ module.cognito-user-pool.aws_cognito_user_pool.user_pool[1]
      mfa_configuration: "OFF" => "OPTIONAL"

  ~ module.cognito-user-pool.aws_cognito_user_pool.user_pool[2]
      mfa_configuration: "OFF" => "OPTIONAL"


Plan: 0 to add, 3 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**Comment by bflad** [comment]
Hi @mattbryce93 👋 A fix for perpetual updates to the `aws_cognito_user_pool` resource was previously released in [version 1.32.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1320-august-16-2018) and has been available in all releases since. Can you try upgrading your AWS provider version and letting us know if it still occurs after an `apply` on the newer version?

Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by mattbryce93** [comment]
@bflad sure thing! I'll be able to test this tomorrow and will post an update after!

**Comment by mattbryce93** [comment]
Hi @bflad that's worked perfectly! Changed it over to 
```
provider "aws" {
  region  = "${lookup(var.aws_region,terraform.workspace)}"
  version = "~> 1.32.0"
}
```
And it has updated perfectly as originally expected. Thank you for your help!
