### ISSUE TITLE
Elasticsearch Service Node-to-Node encryption

### ISSUE THREAD

**Issue by smelchior** [terraform-providers/terraform-provider-aws#5966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS Elasticsearch Service now supports node-to-node encryption:
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ntn.html

### New or Affected Resource(s)

* aws_elasticsearch_domain

### References

* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/ntn.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/elasticsearchservice/#CreateElasticsearchDomainInput (NodeToNodeEncryptionOptions)

**Comment by saravanan30erd** [comment]
I will work on this.

**Comment by bflad** [comment]
Support for this via a new `node_to_node_encryption` argument has been merged and will release with version 1.39.0 of the AWS provider, likely middle of next week.

**Comment by smelchior** [comment]
perfect, thanks a lot!
