### ISSUE TITLE
only "default" aws profile works

### ISSUE THREAD

**Issue by decmaxn** [terraform-providers/terraform-provider-aws#5987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.aws v1.37.0

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
  profile = "myprofile"
}

terraform {
  backend "s3" {
    bucket  = "mybucket"
    key     = "test/my.tfstate"
    region  = "us-east-1"
  }
}
...
```

### Debug Output
terraform init
```hcl
Initializing modules...
- module.vpc

Initializing the backend...

Error configuring the backend "s3": No valid credential sources found for AWS Provider.
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

### Expected Behavior

```hcl
Initializing modules...
- module.vpc

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
```

### Actual Behavior
According to https://www.terraform.io/docs/providers/aws/#shared-credentials-file, it should use "myprofile", but it doesn't 

### Steps to Reproduce

I have multiple aws profiles in ~/.aws/ folder properly setup including "myprofile", but there is no default profile. 

### Walk around
 If I rename "myprofile" to "default", it will work. 

* #0000

**Comment by bflad** [comment]
Hi @decmaxn 👋  Sorry for some confusion here! It looks like the error messaging is only partially correct in its advice. While the S3 backend in Terraform shares the same authentication code as the AWS provider, the two configurations are currently separate.

Can you try adding `profile = "myprofile"` to your `backend "s3"` configuration? More information: https://www.terraform.io/docs/backends/types/s3.html#profile

**Comment by decmaxn** [comment]
Thank you, it works! Now it looks like this. 
```hcl
provider "aws" {
  region = "us-east-1"
  profile = "myprofile"
}

terraform {
  backend "s3" {
    bucket  = "mybucket"
    key     = "test/my.tfstate"
    region  = "us-east-1"
    profile = "myprofile"
  }
}
...
