### ISSUE TITLE
Terraform failing while provisioning windows 2012 servers error executing "C:/Temp/terraform_49955316.cmd": Command has already been closed

### ISSUE THREAD

**Issue by cskalyan** [terraform-providers/terraform-provider-aws#6018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by cskalyan** [comment]
I am trying to provision Windows 2012 R2 AWS EC2 Instances. As part of the launch, Instance is getting rebooted multiple times, as the AMI I am using to launch the instance was taken after completing sysprep on the instance. When using terraform for provision and launch an instance, I keep getting this error. When the Instance is completely up and when I try to perform a terraform apply again, I get a message that Instance resource is tainted and would be destroyed and relaunched again which should not be the behavior

error executing "C:/Temp/terraform_49955316.cmd": Command has already been closed

**Comment by nitehawks** [comment]
I am having same issue

**Comment by aeschright** [comment]
Hi @cskalyan , without your Terraform config and debug logs, we aren't able to investigate this. If it's still happening on the newest Terraform and AWS provider versions, please open a new bug report and include all of the requested information. Thanks for taking the time to report the error.
