### ISSUE TITLE
Is there a way to set the latest computed version to be the Default value in `resource aws_launch_template` ?

### ISSUE THREAD

**Issue by rohityadav-agilets** [terraform-providers/terraform-provider-aws#6019]
Is there a way to set the latest computed version to be the Default value in `resource aws_launch_template` ?

**Comment by rohityadav-agilets** [comment]
@bflad Is this feature already part of terraform `v0.12.0` ?

**Comment by rohityadav-agilets** [comment]
@apparentlymart Do you know if this is possible in `v0.12` ?

**Comment by bflad** [comment]
@rohityadav-agilets this enhancement will be specific to the AWS provider and the `aws_launch_template` resource. It looks like we have a previous issue for this already (#4655) and pull request (#5225) so to consolidate discussions and efforts, I'm going to close this issue in preference of those.
