### ISSUE TITLE
aws_dx_connection accepted lower bandwiths

### ISSUE THREAD

**Issue by wonderphil** [terraform-providers/terraform-provider-aws#6043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow for other connection speeds for aws direct connect.  I.e. 500Mbps

Currently, I have two connections that are 500Mbps but cant use terraform to manage because it requires either [1Gbps 10Gbps]

### New or Affected Resource(s)

aws_dx_connection

### Potential Terraform Configuration

```hcl
resource "aws_dx_connection" "connection_1" {
  name = "V1C33309"
  bandwidth = "500Mbps"
  location = "EqLD5"
}
```

**Comment by ewbankkit** [comment]
From the [Direct Connect FAQS](https://aws.amazon.com/directconnect/faqs/):
> Q. What connection speeds are supported by AWS Direct Connect?
>
> 1Gbps and 10Gbps ports are available. Speeds of 50Mbps, 100Mbps, 200Mbps, 300Mbps, 400Mbps, and 500Mbps can be ordered from any APN partners supporting AWS Direct Connect. Read more about APN Partners supporting AWS Direct Connect.

**Comment by wonderphil** [comment]
Sorry should of put that in.  Work around is I have configured by hand, then imported to terraform, then added
```
lifecycle {
    ignore_changes = ["bandwidth"]
  }
```

**Comment by bflad** [comment]
The additional speeds will be allowed in version 1.39.0 of the AWS provider, likely releasing later today.
