### ISSUE TITLE
AWS Peering connection and accepter issue when both are in same region

### ISSUE THREAD

**Issue by bmurray3** [terraform-providers/terraform-provider-aws#6044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

pTFE using Terraform version 0.11.7

### Affected Resource(s)

aws_vpc_peering_connection
aws_vpc_peering_connection_accepter

### Terraform Configuration Files

```hcl
provider "aws" {
    alias = "hub01"
    region = "${var.hub01_region}"
}
provider "aws" {
    alias = "spoke01"
    region = "${var.spoke01_region}"
}
resource "aws_vpc" "hub01" {
    provider        = "aws.hub01"
    cidr_block      = "${var.hub01_cidr}"
}
resource "aws_vpc" "spoke01" {
    provider        = "aws.spoke01"
    cidr_block      = "${var.spoke01_cidr}"
}
resource "aws_vpc_peering_connection" "hub1spoke1" {
    provider = "aws.hub01"
    depends_on = ["aws_vpc.hub01","aws_vpc.spoke01"]
    vpc_id = "${aws_vpc.hub01.id}"
    peer_vpc_id = "${aws_vpc.spoke01.id}"
    peer_region = "${var.spoke01_region}"
    auto_accept = false
    accepter {
        allow_remote_vpc_dns_resolution = true
    }
    requester {
        allow_remote_vpc_dns_resolution = true
    }
}
resource "aws_vpc_peering_connection_accepter" "hub1spoke1" {
    provider = "aws.spoke01"
    depends_on  = ["aws_vpc.hub01","aws_vpc.spoke01","aws_vpc_peering_connection.hub1spoke1"]
    vpc_peering_connection_id = "${aws_vpc_peering_connection.hub1spoke1.id}"
    auto_accept = true
}
```
### Expected Behavior

Regardless of the hub and spoke regions, the peering connections should be created, then accepted. Both VPCs are in the same account.

### Actual Behavior

1) When the hub and spoke regions are different (i.e. us-east-1 and us-west-1) the peering connection is created but in "pending acceptance" and the script fails with the same error as in the 2nd scenario. A second run of the script will complete the acceptance. 
2) When the hub and spoke regions are the same (both providers region = us-west-1 for example) the script fails on every run with the following 

* aws_vpc_peering_connection.hub1spoke1: Unable to modify peering options. The VPC Peering Connection "xxx" is not active. Please set `auto_accept` attribute to `true`, or activate VPC Peering Connection manually.

### Important Factoids

* VPCs are linked to the same account. A default provider is also set, but is not referenced.
* It has been suggested that we add a null_resource with a 'sleep 60' to resolve scenario 1. While that may be a workaround, it still does not resolve both scenarios. 
* the depends_on doesn't seem to actually do anything to prevent the accepter side from attempting to execute.
* In the apply, I find in the output that the message that it is creating the peering connection starts, but it does not send the normal 'Creation complete after XXs'

Receive this -> 'aws_vpc_peering_connection.hub2spoke1: Creating...'
but lacks this -> 'aws_vpc_peering_connection.hub2spoke1: Creation complete after 5s'

* #0000

**Comment by ewbankkit** [comment]
I would normally suggest using the [`aws_vpc_peering_connection_options`](https://www.terraform.io/docs/providers/aws/r/vpc_peering_options.html) resource which decouples setting the peering options from the peering creation (added via https://github.com/terraform-providers/terraform-provider-aws/pull/3909) but modifying VPC Peering Connection Options is not supported for cross-region VPC peering connections.
So `terraform apply` on

```hcl
provider "aws" {
  alias  = "hub01"
  region = "${var.hub01_region}"
}

provider "aws" {
  alias  = "spoke01"
  region = "${var.spoke01_region}"
}

resource "aws_vpc" "hub01" {
  provider   = "aws.hub01"
  cidr_block = "${var.hub01_cidr}"
}

resource "aws_vpc" "spoke01" {
  provider   = "aws.spoke01"
  cidr_block = "${var.spoke01_cidr}"
}

resource "aws_vpc_peering_connection" "hub1spoke1" {
  provider = "aws.hub01"

  //depends_on  = ["aws_vpc.hub01", "aws_vpc.spoke01"]
  vpc_id      = "${aws_vpc.hub01.id}"
  peer_vpc_id = "${aws_vpc.spoke01.id}"
  peer_region = "${var.spoke01_region}"
  auto_accept = false

  // accepter {
  //   allow_remote_vpc_dns_resolution = true
  // }

  // requester {
  //   allow_remote_vpc_dns_resolution = true
  // }
}

resource "aws_vpc_peering_connection_accepter" "hub1spoke1" {
  provider = "aws.spoke01"

  //depends_on                = ["aws_vpc.hub01", "aws_vpc.spoke01", "aws_vpc_peering_connection.hub1spoke1"]
  vpc_peering_connection_id = "${aws_vpc_peering_connection.hub1spoke1.id}"
  auto_accept               = true
}

resource "aws_vpc_peering_connection_options" "hub1" {
  provider = "aws.hub01"

  # As options can't be set until the connection has been accepted
  # create an explicit dependency on the accepter.
  vpc_peering_connection_id = "${aws_vpc_peering_connection_accepter.hub1spoke1.id}"

  requester {
    allow_remote_vpc_dns_resolution = true
  }
}

resource "aws_vpc_peering_connection_options" "spoke1" {
  provider = "aws.spoke01"

  vpc_peering_connection_id = "${aws_vpc_peering_connection_accepter.hub1spoke1.id}"

  accepter {
    allow_remote_vpc_dns_resolution = true
  }
}
```

gives

```
Error: Error applying plan:

2 error(s) occurred:

* aws_vpc_peering_connection_options.hub1: 1 error(s) occurred:

* aws_vpc_peering_connection_options.hub1: Error modifying VPC Peering Connection Options: OperationNotPermitted: Modifying VPC peering connection options AllowDnsResolutionFromRemoteVpc, AllowEgressFromLocalClassicLinkToRemoteVpc, AllowEgressFromLocalVpcToRemoteClassicLink is not supported for cross-region VPC peering connections
	status code: 400, request id: ce5c2d5c-6c23-45be-a0cb-051ee9e89316
* aws_vpc_peering_connection_options.spoke1: 1 error(s) occurred:

* aws_vpc_peering_connection_options.spoke1: Error modifying VPC Peering Connection Options: OperationNotPermitted: Modifying VPC peering connection options AllowDnsResolutionFromRemoteVpc, AllowEgressFromLocalClassicLinkToRemoteVpc, AllowEgressFromLocalVpcToRemoteClassicLink is not supported for cross-region VPC peering connections
	status code: 400, request id: 8f28b167-ff07-48e6-8d22-a8761e9208b4
```

**Comment by ewbankkit** [comment]
I think we can certainly improve the documentation around this.

**Comment by bmurray3** [comment]
Thank you for the quick reply. Based on what you have identified, I am under the assumption that there is currently no solution. I did confirm that once I drop the connector options I am able to successfully complete the peering.
Is this a provider limitation in Terraform, or is this an actual AWS limitation? Trying to understand the path forward. 
Thanks

**Comment by paultyng** [comment]
@bmurray3 this looks like an AWS error message / limitation as far as I can tell, we are not returning this.

I was able to track down [some docs](https://docs.aws.amazon.com/vpc/latest/peering/modify-peering-connections.html):
> You cannot enable DNS resolution support for an inter-region VPC peering connection.

**Comment by hegyre** [comment]
Hi guys,

Is it possible to re-open this issue, or at least update the doc ?
Since AWS now supports Inter-regin DNS resolution (see [Announcing Support for DNS Resolution over Inter-Region VPC Peering](https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-support-for-dns-resolution-over-inter-region-vpc-peering/))

**Comment by paultyng** [comment]
@hegyre we prefer new issues to be created, behavior can change a lot when almost a year has passed.
