### ISSUE TITLE
Upgrading the  Aurora PostgreSQL engine version

### ISSUE THREAD

**Issue by phani308** [terraform-providers/terraform-provider-aws#6045]
Hello,

Upgrading the Aurora PostgreSQL engine version is destroying and recreating the instance . I want to upgrade my exisitng instance to higher version available without destroying the existing instance . please let me  know if i can do this through terraform or not possible with current versions of terraform. plan copied below

module.aurora.aws_rds_cluster.aurora_cluster [31m[1m(new resource required)[0m
      id:                                "xxxxxxxx" => <computed>
      apply_immediately:                 "true" => "true"
      arn:                               "xxxxxxx" => <computed>
      availability_zones.#:              "x" => <computed>
      backup_retention_period:           "15" => "15"
      cluster_identifier:                "xxxxxx" => "xxxxxx"
      cluster_identifier_prefix:         "" => <computed>
      cluster_members.#:                 "1" => <computed>
      cluster_resource_id:               "cluster-xxxxx" => <computed>
      database_name:                     "xxxxx" => "xxxxx"
      db_cluster_parameter_group_name:   "xxxxxxxxx" => "xxxxxxxx"
      db_subnet_group_name:              "xxxx" => "xxxxx"
      endpoint:                          "xxxxxx" => <computed>
      engine:                            "aurora-postgresql" => "aurora-postgresql"
      engine_mode:                       "provisioned" => "provisioned"
      engine_version:                    "9.6.8" => "9.6.9" [31m(forces new resource)[0m

@jbardin @antonbabenko

**Comment by bflad** [comment]
Hi @phani308 👋  We actually just merged support for this with #5010, which will be released with version 1.40.0 of the AWS provider likely middle of next week. 👍
