### ISSUE TITLE
provider.aws error when / is in keyid

### ISSUE THREAD

**Issue by bmurray3** [terraform-providers/terraform-provider-aws#6050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version 0.11.7
AWS provider version 1.38.0

### Affected Resource(s)

All AWS resources - authentication issue

### Expected Behavior

Authentication with a secret key which contains a / is allowed.

### Actual Behavior

Starting with the latest AWS provider version, getting a new error which was not seen before, using the same credentials. "MySecret/StillMySecret" is a standin for my actual secret which contains a / character as part of the string.
 
provider.aws: error validating provider credentials: error calling sts:GetCallerIdentity: IncompleteSignature: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'MySecret/StillMySecret/20181002/us-east-1/sts/aws4_request'
	status code: 400, request id: xxx-xx-xx-xx-xxx

### Steps to Reproduce

1. Generate an IAM access key which has a / in the secret key. 
2. Run any Terraform code with an AWS provider

.

### Important Factoids

Non-working is in pTFE. Same code is fine using open source exe. Here are the versions in each

Not working (pTFE)
Terraform v0.11.7
2018/10/02 16:49:58 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2018/10/02 16:49:58 [DEBUG] found provider "terraform-provider-aws_v1.38.0_x4"
2018/10/02 16:49:58 [DEBUG] found provider "terraform-provider-null_v1.0.0_x4"

Working (terraform.exe)
Terraform v0.11.7
+ provider.aws v1.36.0
+ provider.null v1.0.0

* #0000

**Comment by bmurray3** [comment]
I believe this can be closed.
After additional testing this appears to have been a glitch in pTFE. I added a version tag the provider to force it down to 1.36 and the issue persisted. I then created a new Access ID - which interestingly enough also had 2 /'s in the secret key - and everything worked. I returned the workspace to the original Access ID and the workspace returned to a working condition - no errors. I've been in contact with Hashi directly regarding the glitch.

**Comment by OJFord** [comment]
@bmurray3 Thanks for noting the workaround. This is still an issue (at least in v0.11.14, I didn't try 0.12.x) though, could you please re-open?

Just ran into this with remote state in S3.

```
Error configuring the backend "s3": error validating provider credentials: error calling sts:GetCallerIdentity: IncompleteSignature: [...] not a valid key=value pair (missing equal-sign) [...]
```

**Comment by bflad** [comment]
Hi @OJFord 👋 The S3 Backend is maintained in the upstream Terraform Core repository. If you have a bug report for that functionality, I would suggest opening a issue there with the template details so those maintainers can have a look: https://github.com/hashicorp/terraform/issues/new/choose

I'm going to lock this issue, only to encourage fresh bug reports. 👍
