### ISSUE TITLE
Failure registering instances with ELB when using aws_elb_attachment

### ISSUE THREAD

**Issue by achachw** [terraform-providers/terraform-provider-aws#6056]
I am creating a network load balancer, and trying to attach some instances to it through aws_elb_attachment resource.
My network loadbancer's name is : nlb-test1

Terraform logs says : 

` Creation of the resource 1 (aws_elb_attachment) !`
 `elb:      "" => "arn:aws:elasticloadbalancing:eu-west-1:1234512345:loadbalancer/net/nlb- 
  test1/1234512345"
`
`instance: "" => "i-007224e80040000"
`
### Actual Behaviour

As a result i am getting a validation Error from aws sdk error : 
`aws_elb_attachment.0: Failure registering instances with ELB: ValidationError: LoadBalancer name cannot be longer than 32 characters`

### Expected Behaviour
The instance should be attached to that Network loadBalancer

Am i missing something or there is an issue with aws_elb_attachment ?

terraform provider version : v1.38.0

**Comment by achachw** [comment]
Hi @bflad and thank you for your quick answer.
Indeed, it was a little be confusing for me :)
it is working as expected now by using aws_lb_target_group_attachment resource.

**Comment by bflad** [comment]
Great! I pushed a documentation update to cross-link the `aws_elb_attachment` and `aws_lb_target_group_attachment` resource pages -- hopefully we can help future travelers! 😄
