### ISSUE TITLE
aws_storagegateway_local_disk no results found for query

### ISSUE THREAD

**Issue by ksiadz** [terraform-providers/terraform-provider-aws#6098]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.8
+ provider.aws v1.39.0
```

### Affected Resource(s)

aws_storagegateway_local_disk

### Terraform Configuration Files

None

### Debug Output

https://gist.github.com/ksiadz/fa38e1ecb8651f72c50aa1fa905a25e2

### Expected Behavior

I try to get disk id using data object "aws_storagegateway_local_disk" in order to choose disk aws_storagegateway_cache for storage gateway.

### Actual Behavior

It can not find it.
module.storage_gateway.data.aws_storagegateway_local_disk.test: data.aws_storagegateway_local_disk.test: no results found for query, try adjusting your search criteria

### Steps to Reproduce

```
data "aws_storagegateway_local_disk" "test" {
//  disk_path   = "${aws_volume_attachment.storage_gateway_server_cache_disk_attach.device_name}"
  disk_path   = "/dev/sdb"
//  gateway_arn = "${aws_storagegateway_gateway.imagenet_sgw.arn}"
  gateway_arn = "arn:aws:storagegateway:eu-west-1:XXXXX:gateway/sgw-XXX"
}
```

1. tried both the uncommented option and commented one. The gateway arn as a string was copy pasted from aws cli listing gateways.
2. `terraform apply`

**Comment by bflad** [comment]
Hi @ksiadz 👋  Sorry you are running into trouble.

My guess is that `disk_path` may not line up exactly with how the Storage Gateway API returns the device names. Different instance types will return different results. You have two options for trying to determine it: the AWS CLI or enabling Terraform debug logging.

Via the AWS CLI [storagegateway list-local-disks](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/list-local-disks.html) command, e.g.

```
$ aws storagegateway list-local-disks --gateway-arn arn:aws:storagegateway:eu-west-1:XXXXX:gateway/sgw-XXX
```

Via [enabling Terraform debug logging](https://www.terraform.io/docs/internals/debugging.html), e.g. 

```
$ TF_LOG=debug terraform plan
```

In that output you can search for the AWS response from `ListLocalDisks`. Hope this helps!

**Comment by bflad** [comment]
Closing due to lack of response.
