### ISSUE TITLE
Security Configuration Support for AWS Glue Terraform

### ISSUE THREAD

**Issue by matthewhenricks** [terraform-providers/terraform-provider-aws#6099]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there doesn't appear a way to associate Security Configurations with AWS Glue Jobs. Would it be possible to add a `security_configuration` variable that allows this to be set.

### New or Affected Resource(s)

aws_glue_job.security_configuration

* aws_XXXXX

### Potential Terraform Configuration

```hcl
    resource "aws_glue_job" "job_example" {
      name               = "glue_job"
      role_arn           = "${aws_iam_role.glue_trust.arn}"
      allocated_capacity = 5

      default_arguments = {
          "--INPUT_TABLE" = "job_1"
          "--TempDir"     = "s3://${var.env}.analytics/tmp/job"
          "--job-bookmark-option"    = "job-bookmark-enable"
          "--enable-metrics"         = true
       }

      max_retries = 0
      timeout     = 60 # one hour
      **security_configuration = "SecurityConfigurationName"**

      command {
         name            = "glueetl"
         script_location = "s3://${var.env}.analytics/${aws_s3_bucket_object.job_1.id}"
      }
    }
```

### References

* #0000

**Comment by bflad** [comment]
Support for a `security_configuration` argument on the `aws_glue_job` resource has been merged and will release with version 1.42.0 of the AWS provider, likely in a few days. As for a new resource to manage Glue security configurations themselves, I have created a feature request here: #6286

**Comment by jkhalid** [comment]
@matthewhenricks @bflad @evanphx  @benburkert  

For Glue Jobs there is a provision to add pure python libraries (like a zip file) that are included in the execution .
While creating a job it appears under the security configuration as "python library path"
Where can i specify this in terraform definition 

I want to link an entire zip folder to that path. I can do it manually but dont seem to see that option in terraform. I am  aware of the 
default_arguments but that only allows individual files

resource "aws_glue_job" "x-feed-terraform" {
    name = "x-feed"
    role_arn = "${var.IAM_ROLE}"
    allocated_capacity = "${var.DPU}"
    max_retries = 3
    timeout = 1000
    command {
        script_location = "s3://${var.S3_BUCKET}${var.FEED_SCRIPT}"
            }
  default_arguments {
    extra-py-files = "s3://${var.S3_BUCKET}/syndication_libs/x1.py, s3://${var.S3_BUCKET}/folder/ftp_utils.py, s3://${var.S3_BUCKET}/folder/x2.py, s3://${var.S3_BUCKET}/folder/x3.py"
  }
}

as you see i have 3 extra python files and in future could have more. i wanted them to be in a .zip file which could be linked to the job by place it in an s3 bucket and providing the link to that s3 bucket in the "python library path". 
This is possible manually but I cannot figure how to do it in terraform.

**Comment by matthewswain** [comment]
Hi @jkhalid,

I don't believe that the Python library path is currently supported by Terraform. I would create a GitHub issue and have a go at adding it, but based on this documentation I'm not sure it's supported by the AWS API either: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-jobs-job.html#aws-glue-api-jobs-job-CreateJob

**Comment by jkhalid** [comment]
Hi @matthewswain 

Thank you for responding. I tried a hit and trial method . i was reading the documentation 
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html

where i came across the below paramter
--extra-py-files  —  S3 path(s) to ..........

I modified the terraform code to 

resource "aws_glue_job" "x-feed-terraform" {
name = "x-feed"
role_arn = "${var.IAM_ROLE}"
allocated_capacity = "${var.DPU}"
max_retries = 3
timeout = 1000
command {
script_location = "s3://${var.S3_BUCKET}${var.FEED_SCRIPT}"
}
default_arguments {
 "--extra-py-files" = "s3://${var.S3_BUCKET}/abcd/libs.zip"
}
}

This seems to be working correctly. However I would request the developers to update their online documentation regarding these paramters
