### ISSUE TITLE
InvalidGroupId.Malformed. EC2 Error Message: Invalid id: (expecting "sg-...") - But 'id' has sg-

### ISSUE THREAD

**Issue by guybumbling** [terraform-providers/terraform-provider-aws#6104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.37.0
+ provider.template v1.0.0

### Affected Resource(s)
IAM Polciy and adding existing EC2 SecurityyGroup from Existing VPC created in separate stand-up with separate state file. Referencing SecurityGroup, and Subnets with ARN as a variable

* aws_lambda_function

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
---------------
variables.tf : 
```
...
  variable "cypress-redis-lambda-subnet-1a" {
    default = "arn:aws:ec2:us-east-1:redacted:subnet/subnet-09a4041922ea5a07e" 
}
  variable "cypress-redis-lambda-subnet-1b" {
    default = "arn:aws:ec2:us-east-1:redacted:subnet/subnet-044b416cc9ecc1f3d" 
}
  variable "cypress-redis-lambda-sg" {
    default = "arn:aws:ec2:us-east-1:redacted:security-group/sg-0226c17131bc870f0"  
  }
...
```
------------------
lambda.tf
```
resource "aws_lambda_function" "c5-cypress-redis-update-v2" {
...
  vpc_config {
    subnet_ids         = ["${var.cypress-redis-lambda-subnet-1a}", "${var.cypress-redis-lambda-subnet-1b}"]
    security_group_ids = ["${var.cypress-redis-lambda-sg}"]
  }
...
}
```
------------------------

### Debug Output
Nothing written to TF_LOG_PATH with TF_LOG set to DEBUG
$ echo $TF_LOG_PATH
/home/<redacted_user>/terraform_policy.log
$ echo $TF_LOG
DEBUG

### Panic Output
NA

### Expected Behavior
I expected that the variable values provided for resource ARNs for subnets and SecurityGroups would be used by 'lambda.tf' to add to the SecurityGroup to Lambda Function configuration, which is what appears to have Occurred. But, and error on the ARN for the SecurityGroup was reported as below:

### Actual Behavior
Where the ARN values for the Subnets did get used and accepted, the ARN for the SecurityGroups did not.  Below error output received on apply:
Error: Error applying plan:

2 error(s) occurred:

* module.c5_module.aws_lambda_function.c5-cypress-redis-update-v2: 1 error(s) occurred:

* aws_lambda_function.c5-cypress-redis-update-v2: Error modifying Lambda Function Configuration c5-cypress-dev-redis-update-v2: InvalidParameterValueException: Error occurred while DescribeSecurityGroups. EC2 Error Code: InvalidGroupId.Malformed. EC2 Error Message: Invalid id: "arn:aws:ec2:us-east-1:redacted:security-group/sg-0226c17131bc870f0" (expecting "sg-...")
        status code: 400, request id: da555d50-cc1f-11e8-bc17-cbab88360bc6
* module.c5_module.aws_lambda_function.c5-cypress-redis-update: 1 error(s) occurred:

* aws_lambda_function.c5-cypress-redis-update: Error modifying Lambda Function Configuration c5-cypress-dev-redis-update: InvalidParameterValueException: Error occurred while DescribeSecurityGroups. EC2 Error Code: InvalidGroupId.Malformed. EC2 Error Message: Invalid id: "arn:aws:ec2:us-east-1:redacted:security-group/sg-0226c17131bc870f0" (expecting "sg-...")
        status code: 400, request id: da562089-cc1f-11e8-8e93-bb90e32ba937

### Steps to Reproduce

1. `terraform apply`
2. 'yes'

### References

* #0000

**Comment by ryndaniels** [comment]
@guybumbling thanks for taking the time to open this issue! It looks like the problem is that you are providing a full ARN for your `cypress-redis-lambda-sg`, where the API expects just the ID. I was able to get this configuration to work using similar to the following instead:
```
variable "cypress-redis-lambda-sg" {
    default = "sg-0226c17131bc870f0"  
}
```
If you run into further problems with this, feel free to open another issue. Thanks!
