### ISSUE TITLE
Unable to define custom catalog_id for aws_glue_catalog_database

### ISSUE THREAD

**Issue by JamiKarvanen** [terraform-providers/terraform-provider-aws#6108]
It seems that it's not possible to create aws_glue_catalog_database resource with catalog_id defined. If That attribute is omitted, the database is created successfully with the default catalog_id (aws account id). If the catalog_id is defined, I get AccessDeniedException, although the user has all the necessary permissions regarding glue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.8 (also tested with v0.11.9)

### Affected Resource(s)

* aws_glue_catalog_database

### Terraform Configuration Files

```hcl
resource "aws_glue_catalog_database" "test_database" {
  name        = "test_database"
  description = "Database for testing purposes"
  catalog_id = "my_own_custom_id"
  location_uri = "${var.aws_glue_catalog_location}"
}
```

### Debug Output

* aws_glue_catalog_database.test_database: Error creating Catalog Database: AccessDeniedException: User: <redacted> is not authorized to perform: glue:CreateDatabase on resource: *

### Expected Behavior

The resource was created with defined catalog_id

### Actual Behavior

AccessDeniedException

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by JamiKarvanen** [comment]
After looking at the AWS Console UI and Glue API documentation, it seems that the catalog_id is not meant to be user-definable, but always bound to the AWS account id.

**Comment by ryndaniels** [comment]
Hi @JamiKarvanen - thanks for taking the time to open this issue. If I understand correctly, are you trying to _define_ a custom catalog ID for your `aws_glue_catalog_database`? The `catalog_id` field in this resource allows you to create a new database in an _existing_ data catalog that isn't your default one, but not to simply declare a custom catalog ID. If I'm misunderstanding what you're trying to do, please provide us some more details on the other catalog you are trying to use here so we can troubleshoot further. Thanks!

**Comment by bflad** [comment]
Closing due to lack of response.
