### ISSUE TITLE
Using provider = all in aws_security_group_rule with from_port and to_port results in SG with port range of ALL vs the ports specified

### ISSUE THREAD

**Issue by rayterrill** [terraform-providers/terraform-provider-aws#6114]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.39.0

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

```hcl
resource "aws_security_group_rule" "DynamicRPC" {
  provider = "aws.sharedservices"
  type            = "ingress"
  from_port       = 49152
  to_port         = 65535
  protocol        = "all"
  cidr_blocks     = ["10.0.0.0/8","172.0.0.0/8"]

  security_group_id = "${aws_security_group.DELETEME.id}"
}
```

### Debug Output

https://gist.github.com/rayterrill/c5f7e80a284d3e536ace4d1a44a29827

### Expected Behavior

I believe this should create a rule with protocol = all but the specific port range.

### Actual Behavior

Creates a rule with protocol = all and port range = all.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

* #0000

**Comment by rayterrill** [comment]
@bflad Creating separate TCP and UDP steps is exactly what we did to work around. Yep - I can try to engage with AWS support.

My coworker showed me this and I was like DANG that is BAD.

**Comment by rayterrill** [comment]
@bflad Missed one of your questions. No it doesn't ever appear to resolve to what was requested, and in fact we stumbled across it because we were getting the Terraform error where you have overlapping security group rules. This actually wasn't true in our Terraform configuration, but because the request was getting translated into all ports, subsequent requests for rules targeting the same source ips threw errors. We just happened to stumble onto it.

**Comment by rayterrill** [comment]
@bflad talked with our AWS resources, and they're noting this is expected behavior which is sort of mind boggling - because ICMP doesn't make sense with ports, but is included in protocol = all, they're just dropping the ports configuration entirely.

Really - I think the API should disallow a port configuration section with protocol = all.

Any chance at a minimum we can update the documentation to warn about this scenario? Terraform is probably the wrong place to "fix" this, given that it's the API that's making this happen - confirmed the AWS CLI has the same behavior.

**Comment by bflad** [comment]
We'll gladly accept a PR for a documentation update in this scenario. While we likely wouldn't want to completely error out if you provide this configuration (currently the only option we have), after some of the protocol changes occurring in Terraform 0.12, we may be able to provide warning messages to operators. 👍
