### ISSUE TITLE
Resource 'data.aws_vpc.production' does not have attribute 'main_route_table_id'

### ISSUE THREAD

**Issue by ricktbaker** [terraform-providers/terraform-provider-aws#6120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.39.0

Looking up another VPC:

```
# Get Production VPC
data "aws_vpc" "production" {
  filter {
    name = "tag:Name"
    values = ["company-production"]
  }
}
```

Then trying to reference the main_route_table_id

```
# Create a route rule to route traffic to eks vpc
resource "aws_route" "prod_to_eks" {
  count                     = "${var.peer_production_vpc}"
  route_table_id            = "${data.aws_vpc.production.main_route_table_id}"
  destination_cidr_block    = "${aws_vpc.default.cidr_block}"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.to_production.id}"
}
```

Results in: Resource 'data.aws_vpc.production' does not have attribute 'main_route_table_id'

It's definitely finding the VPC because I am using the .id and cidr_block attribute elsewhere.

**Comment by bflad** [comment]
Support for the `main_route_table_id` attribute on the `aws_vpc` data source has been merged and will be released with version 1.42.0 of the AWS provider, sometime in the next few days.
