### ISSUE TITLE
aws_network_interface with private_ips_count does not set primary ip correctly / the ip is ignored if used as primary interface for instance

### ISSUE THREAD

**Issue by buec011** [terraform-providers/terraform-provider-aws#6125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.40.0

### Affected Resource(s)

* aws_network_interface

### Terraform Configuration Files

```hcl
variable "flavor" {
  default = "t2.micro"
}

variable "subnetid" {
  default = "subnet-12345678"
}

variable "image" {
  default = "unset"
}

resource "aws_network_interface" "nic0" {
  private_ips_count = "1"
  subnet_id         = "${var.subnetid}"
}

resource "aws_instance" "instance" {
  ami           = "${var.image}"
  instance_type = "${var.flavor}"

  network_interface {
    network_interface_id = "${aws_network_interface.nic0.id}"
    device_index         = 0
  }
}

output "01_all_configured_ips" {
  value = "${aws_network_interface.nic0.private_ips}"
}

output "02_primary_ip" {
  value = "${aws_instance.instance.private_ip}"
}

```

### Expected Behavior

If we create a network interface via aws_network_interface and obtain an ip adress by using
private_ips_count = "1"
the obtained ip should be used if we create an aws instance with this interface
So the output resources above should match, e.g.:

```
01_all_configured_ips = [
    10.18.9.51
]
02_primary_ip = 10.18.9.51
```

### Actual Behavior

The ip from the network interface is ignored, instead an additional ip will be added to the interface and used as primary ip. The ip obtained via private_ips_count is still there as secondary ip.

So the output resource above will show, e.g.:
```
01_all_configured_ips = [
    10.18.9.51,
    10.18.9.242
]
02_primary_ip = 10.18.9.242
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by gwvandesteeg** [comment]
Yes,

The variable is misnamed (and/or the documentation is incomplete) it doesn't create primary IPs, it only creates private Secondary IPs.

**Comment by buec011** [comment]
CLosed because dublicate

**Comment by buec011** [comment]
> I suggest that at least the docs should be updated [1]
> private_ips_count - (Optional) Number of private IPs to assign to the ENI.
> --> private_ips_count - (Optional) Number of secondary private IPs to assign to the ENI, in addition to the primary ip that is automatically assigned, if private_ip or private_ips is not used.
> 
> [1] https://www.terraform.io/docs/providers/aws/r/network_interface.html

It looks like this has been fixed:
https://github.com/terraform-providers/terraform-provider-aws/pull/8353
