### ISSUE TITLE
Resource 'aws_iam_role_policy.example_policy' does not have attribute 'name'

### ISSUE THREAD

**Issue by bakshi-gulam** [terraform-providers/terraform-provider-aws#6144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.aws v1.40.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_iam_role_policy

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "example_bucket" {
}

resource "aws_iam_role" "example_role" {
  name = "example-role"

  assume_role_policy = <<EOF
{  
  "Version": "2012-10-17",
  "Statement": [
    {  
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "example_role_policy" {
  role = "${aws_iam_role.example_role.id}"

  policy = <<EOF
{
  "Id": "Policy1539344357144",
  "Version": "2012-10-17",
  "Statement": [
    { 
      "Sid": "Stmt1539344320966",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "${aws_s3_bucket.example_bucket.arn}/*"
    }
  ]
}
EOF
}
```

### Expected Behavior

$ terraform state show aws_iam_role_policy.example_role_policy
id     = example-role:terraform-2018xxxxxxxxxxxxxxxxxxxxxxxxx
**name = terraform-2018xxxxxxxxxxxxxxxxxxxxxxxxx**
policy = {
  "Id": "Policy1539344357144",
  "Version": "2012-10-17",
  "Statement": [
    { 
      "Sid": "Stmt1539344320966",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::terraform-2018xxxxxxxxxxxxxxxxxxxxxxxxx/*"
    }
  ]
}
role   = example-role

### Actual Behavior

$ terraform state show aws_iam_role_policy.example_role_policy
id     = example-role:terraform-2018xxxxxxxxxxxxxxxxxxxxxxxxx
policy = {
  "Id": "Policy1539344357144",
  "Version": "2012-10-17",
  "Statement": [
    { 
      "Sid": "Stmt1539344320966",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::terraform-2018xxxxxxxxxxxxxxxxxxxxxxxxx/*"
    }
  ]
}
role   = example-role

### Steps to Reproduce

1. save the code as .tf and issue `terraform apply`

**Comment by saravanan30erd** [comment]
will work on it.
