### ISSUE TITLE
Refactor some validators

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6147]
I've noticed a couple of validator refactorings that should simplify the code:
* Replace [`validateStringIn`](https://github.com/terraform-providers/terraform-provider-aws/blob/efcbb7cd91a3fdfaa92769275cc4fc7927a185fe/aws/validators.go#L1779) with [`validation.StringInSlice`](https://github.com/hashicorp/terraform/blob/7b55d1640efda8faead1b548fc20264ddfa15a68/helper/validation/validation.go#L76) (and then remove `validateStringIn`)
* Replace our [`validateJsonString`](https://github.com/terraform-providers/terraform-provider-aws/blob/efcbb7cd91a3fdfaa92769275cc4fc7927a185fe/aws/validators.go#L646) with [`validation.ValidateJsonString`](https://github.com/hashicorp/terraform/blob/7b55d1640efda8faead1b548fc20264ddfa15a68/helper/validation/validation.go#L231) (and then remove `validateJsonString`)

**Comment by bflad** [comment]
Thanks for this @ewbankkit! Will you be handling these? I'm also submitting a PR right now for replacing `validateRFC3339TimeString` usage with upstream `validation.ValidateRFC3339TimeString`

**Comment by ewbankkit** [comment]
Yes, I can do this.

**Comment by ewbankkit** [comment]
Can also replace [`validateIntegerInRange`](https://github.com/terraform-providers/terraform-provider-aws/blob/c121f7cecf7506aa81817edf0c70b1dd464ae9e0/aws/validators.go#L344) with [`validators.IntBetween`](https://github.com/hashicorp/terraform/blob/86e6481cc661b2ba694d353aab6d11838c066c7c/helper/validation/validation.go#L18) (and then remove `validateIntegerInRange`)
