### ISSUE TITLE
Error creating API Gateway: BadRequestException: Configuring API Key Source is not currently supported.

### ISSUE THREAD

**Issue by paul-env** [terraform-providers/terraform-provider-aws#6148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws v1.25.0

### Affected Resource(s)

aws_api_gateway_rest_api

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_rest_api" "api" {
  name        = "API - ${terraform.workspace}"
  description = "${terraform.workspace} - https://${aws_api_gateway_domain_name.main.domain_name}/${terraform.workspace}"
  binary_media_types = ["*/*", "image/jpeg", "image/png"]
}
```

### Debug Output

Do you want to perform these actions in workspace "ci"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.apigateway.aws_api_gateway_rest_api.api: Creating...
  api_key_source:           "" => "HEADER"
  binary_media_types.#:     "0" => "3"
  binary_media_types.0:     "" => "*/*"
  binary_media_types.1:     "" => "image/jpeg"
  binary_media_types.2:     "" => "image/png"
  created_date:             "" => "<computed>"
  description:              "" => "ci -  https://ci.api.domain.com/ci"
  endpoint_configuration.#: "" => "<computed>"
  execution_arn:            "" => "<computed>"
  minimum_compression_size: "" => "-1"
  name:                     "" => "API - ci"
  root_resource_id:         "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* module.apigateway.aws_api_gateway_rest_api.api: 1 error(s) occurred:

* aws_api_gateway_rest_api.api: Error creating API Gateway: BadRequestException: Configuring API Key Source is not currently supported.
        status code: 400, request id: b158b59b-cf34-11e8-9a9c-9f5859b759d5

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior

This was working fine until last week.   Something has changed.  We'd expect the result to be a created API.

### Steps to Reproduce

1. `terraform destroy`
2. `terraform apply`

**Comment by paul-env** [comment]
updated the provider, still no joy.


Initializing the backend...


Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.40.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.40"


Error: Error applying plan:

1 error(s) occurred:

* module.apigateway.aws_api_gateway_rest_api.api: 1 error(s) occurred:

* aws_api_gateway_rest_api.api: Error creating API Gateway: BadRequestException: Configuring API Key Source is not currently supported.
        status code: 400, request id: 47fe6e76-cfbf-11e8-b13c-69169d4c3b49

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by NSmithUK** [comment]
I'm also seeing this issue, but only in `us-west-1`. It seems fine in all other regions.

**Comment by choongchay** [comment]
I tried this workaround and it works for me:

1. Set terraform provider to `1.21`
2.` terraform apply` to create the resources
3. Add `api_key_source  = "XAPIKEY_HEADER"` to your `aws_api_gateway_rest_api` resources and swap your terraform provider back to the latest (or desired) version
4. Wait for AWS to fix this issue, then remove the api_key_source.

**Comment by bflad** [comment]
Has anyone reached out to AWS Support regarding this? If we're doing something wrong in the Terraform resource, it would be really good to know. Thanks!

**Comment by paul-env** [comment]
@choongchay - that did the trick, thanks for helping us with that.

@bflad   I have reached out through AWS premium support, and this was their reply I just got.

> Thank you for contacting AWS Premium Support. My name is XXXXXXXX and I will be assisting you with this case today.
> 
> I understand that you are receiving 'BadRequestException' error while creating an API using Terraform as well as AWS CLI in the 'us-west-1' region. 
> Please accept our apologies for the inconvenience it is causing.
> 
> I tried to replicate the same error on my end and was able to, using the AWS CLI command :
> 
>     >> aws apigateway create-rest-api --name 'Simple PetStore (AWS CLI)' --region us-west-1 --api-key-source HEADER
> 
> However, when I tried to create the API in other regions e.g. ‘us-east-1’ for testing purpose, the command worked just fine and the API got created in my environment. Additionally, while testing, the API got created in the ‘us-west-1’ region itself using the CLI command when I did not provide the 'api-key-source’ parameter.
>     >> aws apigateway create-rest-api --name 'Simple PetStore (AWS CLI)' --region us-west-1
> 
> So, in order to find out the exact cause behind this, I have reached out to our internal API Gateway team with this information as they are better equipped to answer these behaviors. Rest assured, I will update the case as soon as I receive any information from them.
> 
> Meanwhile, please feel free to reach back to us if you have any additional queries or concerns. We will be glad to assist you.

**Comment by dav009** [comment]
my team had the same issue in Tokyo region (ap-northeast-1) yesterday. 
It seems to be fixed today.

**Comment by choongchay** [comment]
works for me now too

**Comment by bflad** [comment]
Since there hasn't been any recent activity on this issue, it seems the AWS service team fixed this issue upstream and I'm going to close this. If there is actually anything wrong in the Terraform AWS Provider, please open a new GitHub issue. Thanks!
