### ISSUE TITLE
Feature Request: Directly Set RDS Parameter Group During Restore

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#6163]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

v1.15.55 of the AWS Go SDK now supports:

Setting `DBClusterParameterGroupName` directly when performing the following API actions:
* `RestoreDBClusterFromSnapshot`
* `RestoreDBClusterToPointInTime`

Setting `DBParameterGroupName` directly when performing the following API actions:
* `RestoreDBInstanceFromDBSnapshot`
* `RestoreDBInstanceToPointInTime`

This will remove the `ModifyDBCluster`/`ModifyDBInstance` calls currently required after restore, which should provide a speed increase as well as reduced chance for failure.

### New or Affected Resource(s)

* `aws_db_instance`
* `aws_rds_cluster`

### Potential Terraform Configuration

No changes required.

### References

* https://github.com/aws/aws-sdk-go/releases/tag/v1.15.55

**Comment by bflad** [comment]
Dependency update PR: #6164

**Comment by saravanan30erd** [comment]
@bflad can I take this?

**Comment by bflad** [comment]
This has been released in [version 1.41.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1410-october-18-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
