### ISSUE TITLE
Hiring an Engineering Manager and Engineer to work on the AWS Provider at HashiCorp

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-aws#6165]
Interested in working on this provider full time? We are hiring an [Engineer](https://grnh.se/138dabe91) and [Engineering Manager](https://grnh.se/be9122491) at HashiCorp! All engineering positions at HashiCorp are remote, currently we are hiring in the US, Canada, France, Germany, and the UK.

Feel free to reach out to me if you have any questions: ptyng@hashicorp.com

**Comment by tracypholmes** [comment]
Yeah....I think this can be closed @paultyng

**Comment by nywilken** [comment]
Solved!
