### ISSUE TITLE
can't create multihomed ec2 instance with a security group - Error: aws_instance : "network_interface": conflicts with vpc_security_group_ids

### ISSUE THREAD

**Issue by ddimas-quant** [terraform-providers/terraform-provider-aws#6166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.aws v1.40.0

### Affected Resource(s)

aws_instance
aws_security_group
aws_network_interface

### Terraform Configuration Files

```hcl
resource "aws_network_interface" "rtr1_eth0" {
  subnet_id = "${aws_subnet.network_subnet_1.id}"
  tags {
    Name = "rtr1_eth0"
  }
  depends_on = ["aws_subnet.network_subnet_1"]
}

resource "aws_network_interface" "rtr1_eth1" {
  subnet_id = "${aws_subnet.network_subnet_4.id}"
  tags {
    Name = "rtr1_eth1"
  }
  depends_on = ["aws_subnet.network_subnet_4"]
}

resource "aws_security_group" "allow_all" {
  name        = "allowed_traffic"
  description = "Allowed inbound traffic"
  vpc_id      = "${aws_vpc.network.id}"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
  }
  tags {
    Name = "allow_all"
  }
}

resource "aws_instance" "rtr1" {
  ami = "ami-421a22rd"
  instance_type = "c4.large"
  vpc_security_group_ids = ["${aws_security_group.allow_all.id}"]
  network_interface {
    network_interface_id = "${aws_network_interface.rtr1_eth0.id}"
    device_index = 0
  }
  network_interface {
    network_interface_id = "${aws_network_interface.rtr1_eth1.id}"
    device_index = 1
  }
}
```

### Debug Output
https://gist.github.com/ddimas-quant/fe30b523da1d902d573be9c6717722f9

### Expected Behavior
expected ec2 instance to be created as intended (2 nics, one in each subnet, SG applied onto instance)

### Actual Behavior
terraform error: 
```
Error: aws_instance.rtr1: "network_interface": conflicts with vpc_security_group_ids
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
i'm not using the default VPC

### References

* #0000

**Comment by gwvandesteeg** [comment]
Security groups are assigned to interfaces not EC2 instances (form my understanding), as such you need to assign the security groups to the created interfaces.  When you look at the EC2 instance in the Management Console, it then tells you only the security groups assigned to the primary interface.

**Comment by dmitrievav** [comment]
This is the fix:

```
--- old        2019-08-02 17:04:15.000000000 +0200
+++ new 2019-08-02 17:06:05.000000000 +0200
@@ -1,5 +1,6 @@
 resource "aws_network_interface" "rtr1_eth0" {
   subnet_id = "${aws_subnet.network_subnet_1.id}"
+  security_groups = ["${aws_security_group.allow_all.id}"]
   tags {
     Name = "rtr1_eth0"
   }
@@ -8,6 +9,7 @@

 resource "aws_network_interface" "rtr1_eth1" {
   subnet_id = "${aws_subnet.network_subnet_4.id}"
+  security_groups = ["${aws_security_group.allow_all.id}"]
   tags {
     Name = "rtr1_eth1"
   }
@@ -40,7 +42,6 @@
 resource "aws_instance" "rtr1" {
   ami = "ami-421a22rd"
   instance_type = "c4.large"
-  vpc_security_group_ids = ["${aws_security_group.allow_all.id}"]
   network_interface {
     network_interface_id = "${aws_network_interface.rtr1_eth0.id}"
     device_index = 0
```

**Comment by bflad** [comment]
Thanks @gwvandesteeg and @dmitrievav, those answers look correct here. Since this appears to be behavior of the EC2 API and not Terraform itself, I'm going to close this.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
