### ISSUE TITLE
How to create SRV record in Route53 with Terraform

### ISSUE THREAD

**Issue by hh2001** [terraform-providers/terraform-provider-aws#6181]
Dear support,

I am trying to create SRV record in our AWS account with Terraform but I did not find any guide on it. I found in the DNS Provider branch and it is saying it is not available right now. 

Can you let me know if we can do it or not? 

Thank you very much.

Regards,

Harvey

**Comment by bflad** [comment]
Hi, @hh2001! 👋 I believe you are looking for the [`aws_route53_record` resource](https://www.terraform.io/docs/providers/aws/r/route53_record.html):

```hcl
resource "aws_route53_record" "example" {
  name    = "_example.${aws_route53_zone.example.name}"
  records = ["example"]
  ttl     = "300"
  type    = "SRV"
  zone_id = "${aws_route53_zone.example.zone_id}"
}
```

Hopefully this leads you on the right track. 😄 

If you have any further questions, I would suggest reaching out on some of the other [Terraform community forums](https://www.terraform.io/docs/extend/community/index.html) where there are many more people watching and able to help. This GitHub issue tracker is only watched by Terraform code maintainers and generally for bug reports or feature requests with the Terraform AWS provider. 👍

**Comment by mzhaase** [comment]
The documentation is lacking here. SRV records have special fields that other records do not have. It is not clear at all how to set them.

Fields srv records use: priority, weight, port, target, service, proto, name.

Here is how the value needs to be set:

<priority> <weight> <port> <name>._<proto>

Maybe this can be added as an example to the docs.
