### ISSUE TITLE
How to set the security group for an aws_neptune_cluster_instance?

### ISSUE THREAD

**Issue by aaron-collier** [terraform-providers/terraform-provider-aws#6199]
I see the `vpc_security_group_ids` on a cluster (https://www.terraform.io/docs/providers/aws/r/neptune_cluster.html#vpc_security_group_ids) but not on a cluster instance (https://www.terraform.io/docs/providers/aws/r/neptune_cluster_instance.html) so "default" is always been assigned. 

Is there a step I'm missing?

**Comment by bflad** [comment]
Hi @aaron-collier 👋 I don't believe you're missing anything -- the [Neptune `CreateDBInstance` API supports a parameter called `DBSecurityGroups`](https://docs.aws.amazon.com/sdk-for-go/api/service/neptune/#CreateDBInstanceInput):

> ```
>  // A list of DB security groups to associate with this DB instance.
>  //
>  // Default: The default DB security group for the database engine.
>  DBSecurityGroups []*string `locationNameList:"DBSecurityGroupName" type:"list"`
> ```

While the resource is not currently wired up for it. It certainly can be added though. 👍

**Comment by bflad** [comment]
What's interesting is that the API also lists `VpcSecurityGroupIDs` with this description:

> ```
>     // A list of EC2 VPC security groups to associate with this DB instance.
>     //
>     // Not applicable. The associated list of EC2 VPC security groups is managed
>     // by the DB cluster. For more information, see CreateDBCluster.
>     //
>     // Default: The default EC2 VPC security group for the DB subnet group's VPC.
>     VpcSecurityGroupIds []*string `locationNameList:"VpcSecurityGroupId" type:"list"`
> ```

**Comment by saravanan30erd** [comment]
@bflad will add both.

**Comment by saravanan30erd** [comment]
@bflad Looks like we can't use `vpc_security_group_ids` for neptune instance as of now.
```
* aws_neptune_cluster_instance.test: error creating Neptune Instance: InvalidParameterCombination: The requested DB Instance will be a member of a DB Cluster. Set vpc security group for the DB Cluster.
```
Getting above error when I tried to set it for instance.

**Comment by bflad** [comment]
Given the above conversation from awhile ago, it appears that VPC Security Groups must be set at the cluster-level in the API. If this has since changed since, please open a new feature request and we'll take a fresh look. 👍
