### ISSUE TITLE
Support IoT ATS endpoints and make them default

### ISSUE THREAD

**Issue by rafaljanicki** [terraform-providers/terraform-provider-aws#6213]
Hello,

AWS has changed the default behavior of IoT certificates and by default they use an ATS certificate root instead of the previous Verisign. However, the default endpoint returned by CLI is the Verisign hence it breaks on connection (more details: https://aws.amazon.com/blogs/iot/aws-iot-core-ats-endpoints/ ). 

The `aws_iot_endpoint` data provider should allow for a flag if the ATS endpoint should be requested or the old one.

**Comment by bflad** [comment]
Pull request submitted: #6215

**Comment by bflad** [comment]
Support for an `endpoint_type` argument has been merged and will release with version 1.42.0 of the AWS provider, likely in the next day or two. To maintain backwards compatibility with existing configurations, it will remain unset and return the region default endpoint, but can be explicitly set to `endpoint_type = "iot:Data-ATS"` to always return the Amazon Trust Services certificate endpoint.

**Comment by bflad** [comment]
This has been released in [version 1.42.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1420-october-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
