### ISSUE TITLE
terraform not assigning private ip to nat gateway both on creation and on modification

### ISSUE THREAD

**Issue by devoops13** [terraform-providers/terraform-provider-aws#6223]
### terraform version

terraform -v
Terraform v0.11.8

### actual code 

variable "nat_gw_ip_st" {
  default = "10.119.20.161"
}

resource "aws_nat_gateway" "nat_gw" {
  allocation_id = "${aws_eip.nat.id}"
  subnet_id = "${aws_subnet.subnet.0.id}"
  private_ip = "${var.nat_gw_ip_st}"
  depends_on = ["aws_internet_gateway.internet_gateway"]
  tags {
    Name = "${local.prefix}:nat-gw"
  }
}

### terraform output

aws_nat_gateway.nat_gw: Modifying... (ID: nat-041b6751664f1f305)
  private_ip: "10.119.20.161" => "10.119.0.11"

### observed behavior

private ip of the nat gateway is still  10.119.20.161

### expected behavior

ip of the gateway should be 10.119.0.11

**Comment by bflad** [comment]
Hi @devoops13 👋 Sorry for the trouble.

It appears the Terraform resource is incorrectly allowing `private_ip` to be configurable. The [resource itself](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_nat_gateway.go) only reads the information from the API and the [EC2 CreateNatGateway API call](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNatGateway.html) does not actually allow configuration of the private IP of a NAT Gateway.

I will submit a pull request to remove `private_ip` as configurable in Terraform.

**Comment by devoops13** [comment]
can I retrieve the value of the ip with aws_nat_gateway.nat_gw.private_ip ?

**Comment by saravanan30erd** [comment]
@devoops13 yes

**Comment by bflad** [comment]
The fix for Terraform to return an error when attempting to configure these arguments (they will remain available as read-only attributes) has been merged and will release with version 1.42.0 of the AWS provider, likely today or tomorrow.

**Comment by bflad** [comment]
This has been released in [version 1.42.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1420-october-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
