### ISSUE TITLE
issue with aws_dx_gateway and amazon_side_asn

### ISSUE THREAD

**Issue by sharathdoge** [terraform-providers/terraform-provider-aws#6242]
Hello Team,

I'd like to thank the community for all the hard work that's gone into this incredible provider!

We've run into an issue with the aws_dx_gateway resource while creating one using the Amazon Legacy ASN '7224'

`"amazon_side_asn" ("7224") must be in the range 64512 to 65534 or 4200000000 to 4294967294`
We had run into a similar bug while creating an aws_vpn_gateway resource using this ASN:
https://github.com/terraform-providers/terraform-provider-aws/issues/5441 

Appreciate your support!

Thanks in advance!

**Comment by ewbankkit** [comment]
OK, this should be easy to fix; we'll just have one Amazon-side ASN validation function `validateAmazonSideAsn` shared by both `aws_dx_gateway` and `aws_vpn_gateway`.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 1.42.0 of the AWS provider, likely today or tomorrow. 👍

**Comment by sharathdoge** [comment]
@bflad @ewbankkit 
Many thanks!

**Comment by dhermans** [comment]
hi,
tried this today but had some issues - on 1.31 before I was getting:

14:28:14 Error: module.my-vpc.aws_dx_gateway.my-dx-gateway: "amazon_side_asn" ("7224") must be in the range 64512 to 65534 or 4200000000 to 4294967294 

On 1.42 the plan now succeeds but fails on deploy:
10:01:53 Error: Error applying plan:
10:01:53 
10:01:53 1 error(s) occurred:
10:01:53 
10:01:53 * module.my-vpc.aws_dx_gateway.my-dx-gateway: 1 error(s) occurred:
10:01:53 
10:01:53 * aws_dx_gateway.my-dx-gateway: Error creating Direct Connect gateway: DirectConnectClientException: 7224 is not a valid value for Amazon Side ASN
10:01:53   status code: 400, request id: e6126331-e217-11e8-b16a-a51952d67b7b

any ideas?

**Comment by dhermans** [comment]
you can't create in the console so suspect it's an AWS backend limitation

**Comment by ewbankkit** [comment]
@dhermans As I understand it you can't create new DX Gateways (or VPN Gateways) with the legcay ASN `7224`, only import and then modify existing resources with that ASN. I may be wrong though.

**Comment by dhermans** [comment]
HI @ewbankkit  - thanks - think you're right - raised a ticket with them. Odd they allow 7224 on virtual private gateway but not dx gateway.
