### ISSUE TITLE
Fails to provision resources for WAF because of ApiGateway error

### ISSUE THREAD

**Issue by lolcookie** [terraform-providers/terraform-provider-aws#6250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.9

### Affected Resource(s)

* aws_api_gateway_deployment.ApiGatewayBadBotStage

### Terraform Configuration Files

```hcl
Used the code at this repo: https://github.com/cerbo/aws-waf-security-automation/issues/1

There is discussion here: https://github.com/cerbo/aws-waf-security-automation/issues/1


# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/lolcookie/470168f4ecae686f3aa56906409d58d6

### Steps to Reproduce

Follow the readme instructions at https://github.com/cerbo/aws-waf-security-automation/issues/1

Note: aws_api_gateway_deployment resource has a dependency on aws_api_gateway_method resource, but it still does not waits till its creation

**Comment by interisti** [comment]
Seems to fix the issue: https://github.com/cerbo/aws-waf-security-automation/pull/7

**Comment by aeschright** [comment]
Since this is an issue related to using another package, and is reported as fixed there, I'm going to close this. Please go ahead and open a new bug report with your full config file if problems continue. Thanks!
