### ISSUE TITLE
Automating the Amazon EBS Snapshot Lifecycle through Terraform

### ISSUE THREAD

**Issue by srideviraman1407** [terraform-providers/terraform-provider-aws#6255]
I have a requirement to take EBS volume as snapshots for Daily,weekly,Monthly and Yearly basis.
Would like to implement in Amazon EBS Snapshot Lifecycle through Terraform.

Is there any code in Terraform to implement AWS DLM ?

**Comment by bflad** [comment]
Hi @srideviraman1407 👋 Thanks for submitting this! We have an open feature request for this support (#5176) and pull request to implement the `aws_dlm_lifecycle_policy` resource (#5558). To consolidate any discussion and efforts I'm going to close this issue in preference of the previous issue and pull request. 👍
