### ISSUE TITLE
Terraform destroy should probably destroy EMR's mysterious extra resources

### ISSUE THREAD

**Issue by copumpkin** [terraform-providers/terraform-provider-aws#6259]
It seems like whenever I create an EMR cluster, it quietly behind the scenes creates an `AWS-ElasticMapReduce-${cluster id}` for me, with no clear linkage back to the EMR cluster. If I terminate the cluster, the queue sticks around.

It's not beautiful, but it seems like `terraform destroy` should probably get rid of this queue. Unfortunately because there's no strong linkage back to the original resource, it's sort of by convention.

It also appears that EMR can quietly create SDB domains and another queue for EMRFS inconsistencies.

**Comment by bflad** [comment]
In our acceptance testing account which creates and destroys ~17 EMR clusters daily and doesn't have SQS queues cleaned up automatically via an acceptance test sweeper, I was only able to find 1 lingering `AWS-ElasticMapReduce-*` SQS queue from a few months ago. Maybe they are asynchronously cleaned up.

We try very hard to not avoid cross-resource/service cleanup unless its causing a specific issue. Beyond requiring potentially unexpected API permissions, it also requires guessing or re-implementation of AWS service logic.

Other than the SQS queues and SDB domains lingering for some time and presumably consuming quota, are there specific errors by not immediately deleting these?

**Comment by copumpkin** [comment]
Hmm, I’m confused then because in my testing of EMR with terraform over the past few weeks I seem to have accumulated a few dozen SQS queues, and have seen no evidence of them getting cleaned up at all. I’ll check my CloudTrail to see if anything matching that pattern has been deleted by unusual principals though.

No immediate bad outcomes other than what you said, and a general sense of uncleanliness that comes from my clusters leaving junk behind :) feel free to close the ticket if it’s not a good fit for TF’s approach, but I figured I’d ask.

**Comment by copumpkin** [comment]
@bflad ah, I think I see what's going on. Does your testing account create the EMR cluster's service role as well, or just the cluster? If the role is persistent, that's I think what it uses to clean up the queue.

In my case, I have terraform create the service role for me, which means that when I run terraform destroy, the role EMR would use to delete the queue (probably) gets killed before they get a chance to clean up the queue. Not sure if it's asynchronous or if a well-placed `depends_on` would help.

**Comment by aeschright** [comment]
Hi @copumpkin! Since it sounds like you found a way to address your problem, I'm going to close this issue. If you continue to have problems, please open a new bug report and include the requested config items. Thanks!
