### ISSUE TITLE
budgets_budget reports it doesn't support import but the docs say it does

### ISSUE THREAD

**Issue by xM8WVqaG** [terraform-providers/terraform-provider-aws#6278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash                                                                                                                                              
Terraform v0.11.7
+ provider.aws v1.40.0
```

### Affected Resource(s)

* aws_budgets_budget

### Terraform Configuration Files

```bash
terraform import aws_budgets_budget.myBudget "123456789012:My Budget"
```
or

```bash
terraform import aws_budgets_budget.myBudget 123456789012:test-terraform
```

### Expected Behavior

Terraform should have imported my budget.

### Actual Behavior

```
aws_budgets_budget.myBudget: Importing from ID "123456789012:My Budget"...

Error: aws_budgets_budget.myBudget (import id: 123456789012:My Budget): import aws_budgets_budget.myBudget (id: 123456789012:My Budget): resource aws_budgets_budget doesn't support import
```
Same if you attempt to import a budget that doesn't include a space in its name.

### Steps to Reproduce

1. Attempt to import an existing budget.

### References

The manual says you can use import on budgets. <https://www.terraform.io/docs/providers/aws/r/budgets_budget.html>

**Comment by bflad** [comment]
Hi @xM8WVqaG 👋 Thanks for submitting this and sorry for the trouble. There is already an open issue (#6180) and pull request (#6226) for this so to consolidate efforts and discussion, I am going to close this in preference of those. 👍

**Comment by xM8WVqaG** [comment]
I'll try and use my eyes first next time before posting. Thanks for responding to me.
