### ISSUE TITLE
AWS Route53 Record - Cannot Import Record With Underscore in Set ID, Cannot Remove Weighted Routing Policy from Record

### ISSUE THREAD

**Issue by jwshields** [terraform-providers/terraform-provider-aws#6298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```$ terraform -v
Terraform v0.11.7
+ provider.aws v1.41.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "clustermaster_region" {
  count          = "${var.region_record != 1 ? 0 : 1}"
  depends_on     = ["aws_autoscaling_group.asg"]
  zone_id        = "${module.info.route53["zone_id"]}"
  name           = "${var.dnsrecord}${var.short_region}"
  ttl            = "60"
  type           = "A"
  set_identifier = "${var.dnsrecord}${var.short_region}_${count.index}"
  records        = ["${data.aws_instance.clustermaster.private_ip}"]

  weighted_routing_policy {
    weight = 5
  }
}
```

The intention of this resource block is that it is only created if `region_record` is set to 1, and, when creating, it'll create a record like `mysubdomainusw2.example.com` or `subdomainuse1.example.com`

### Debug Output

https://gist.github.com/jwshields/1b881c58cb5abab00cf6988a54529d63

### Panic Output

N/A

### Expected Behavior

Terraform should import the resource.

### Actual Behavior

Terraform did not import the resource.

### Steps to Reproduce

1. Create a Terraform aws_route53_record resource, configure it with a set_identifier & a routing policy (Use an underscore in the Set ID)
2. Attempt to remove the routing policy from the record
3. Terraform will fail to remove the policy
3.1. This part seems related to #4429 & #1668 and what has caused me to attempt to import the record
3.2. The record is no longer associated in my TF state file
4. Attempt to import the record
4.1. `terraform import module.deployment.aws_route53_record.clustermaster_region[0] REDACTED_clustermasterusw2.REDACTED.REDACTED_A_clustermasterusw2_0`
5. The import will fail

### Important Factoids

N/A
Record was created, assigned a routing policy, attempted removal of policy, failure, attempted import of resource, failure.

### References

This seems to tie into multiple issues, but the core one being the underscore imports.
I've found a number of issues regarding both problems that I am experiencing here;

Cannot import record with an underscore:
* #771
* #603

These two issues note that you cannot import a record with an underscore in the *name* field.
They do not appear to address if the underscore is in the `set_identifier`
The commit which resolved those two: https://github.com/terraform-providers/terraform-provider-aws/commit/2556b00727e36e7f00cfc99d9b6e9002364d7946

Cannot change routing policy on record to simple:
* #4429
* #1668

These two issues appear to touch on what I was experiencing and why I was attempting to import the already created resource.
When removing the routing policy, the set_identifier is removed, and TF cannot find the record, and so it fails and removes the item from the state file;

___
Further runs of `terraform plan` result in output where Terraform wants to create a new resource in AWS, while not taking the old one into account, if I were to apply the plan, the apply would fail due to the resource already existing.

**Comment by bflad** [comment]
Import support for `aws_route53_record` resources with underscores was completed quite awhile ago in version 0.1.2 of the Terraform AWS Provider. The fix for removing `weighted_routing_policy` from existing records has been merged and will release with version 2.22.0 of the Terraform AWS Provider, tomorrow. Thanks to @heimweh for the fix implementation. 👍
