### ISSUE TITLE
EC2 recovery alarm creation fails with AWS provider

### ISSUE THREAD

**Issue by sampritavh** [terraform-providers/terraform-provider-aws#6300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
* TERRAFORM_VERSION=0.11.10
* provider.aws: version = "~> 1.41"

### Affected Resource(s)

* aws_cloudwatch_metric_alarm
### Terraform Configuration Files

This is just a snippet. 
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "aws_cloudwatch_metric_alarm" "autorecover" {
  alarm_name          = "ec2-autorecover-alarm-${count.index}"
  namespace           = "AWS/EC2"
  evaluation_periods  = "5"
  count               = "${var.count}"
  period              = "60"
  alarm_description   = "This metric auto recovers EC2 instances"
  alarm_actions       = ["arn:aws:automate:${var.region}:ec2:recover"]
  statistic           = "Minimum"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  threshold           = "1"
  metric_name         = "StatusCheckFailed_System"

  dimensions {
    InstanceId = "${element(aws_instance.this.*.id, count.index)}"
  }
}
```

### Debug Output
Fails with this error: 
```
module.ec2.aws_cloudwatch_metric_alarm.autorecover: "alarm_actions.0" doesn't look like a valid ARN ("^arn:[\\w-]+:([a-zA-Z0-9\\-])+:([a-z]{2}-(gov-)?[a-z]+-\\d{1})?:(\\d{12})?:(.*)$"): "arn:aws:automate:us-east-1:ec2:recover
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Most likely because of this change: https://github.com/terraform-providers/terraform-provider-aws/commit/1626ab174578166348625a0f50a86b15e2f61a85 
### References

* #0000

**Comment by tomelliff** [comment]
This looks to be a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/6203 which has a merged fix in https://github.com/terraform-providers/terraform-provider-aws/pull/6206 and should be released soon.

**Comment by sampritavh** [comment]
thanks @tomelliff . Closing this now
