### ISSUE TITLE
aws_lambda_function does not persist kms_key_arn unless at least one environment variable included

### ISSUE THREAD

**Issue by rberlind** [terraform-providers/terraform-provider-aws#6366]
The aws_lambda_function does not persist the kms_key_arn unless at least one environment variable is included.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
$terraform -v
Terraform v0.11.10
+ provider.aws v1.42.0

### Affected Resource(s)
* aws_lambda_function

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.11.10"
}

variable "aws_region" {
  description = "AWS region"
  default = "us-east-1"
}

variable "lambda_function_name" {
  description = "name of Lambda function"
  default = "roger-test-lambda"
}

variable "aws_account_id" {
  description = "ID of your AWS account"
  default = "753646501470"
}

variable "iam_role_name" {
  description = "name of IAM role"
  default = "roger-lambda-role"
}

variable "iam_basic_execution_policy" {
  description = "name of basic execution policy"
  default = "roger-basic-lambda-policy"

}

variable "iam_vpc_access_policy" {
  description = "name of vpc access policy"
  default = "roger-lambda-vpc_access-policy"
}

variable "kms_key" {
  description = "arn of KMS key"
  default = "arn:aws:kms:us-east-1:<account>:key/<kms_key>"
}

variable "security_group_id" {
  description = "ID of security group"
  default = "sg-0787742bcf636219f"
}

variable "subnet_id" {
  description = "ID of subnet"
  default = "subnet-0d18b4a4c737d6a48"
}

variable "iam_kms_lambda_policy" {
  description = "name of KMS Lambda policy"
  default = "roger-lambda-kms-policy"
}

provider "aws" {
  region = "${var.aws_region}"
}

resource "aws_iam_role" "role_for_lambda" {
  name = "${var.iam_role_name}"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow"
    }
  ]
}
EOF
}

resource "aws_iam_policy" "lambda_basic_execution" {
    name        = "${var.iam_basic_execution_policy}"
    description = "A basic lambda policy"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:${var.aws_region}:${var.aws_account_id}:log-group:*:*"
        }
    ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "attach_basic_lambda" {
    role       = "${aws_iam_role.role_for_lambda.name}"
    policy_arn = "${aws_iam_policy.lambda_basic_execution.arn}"
}

resource "aws_iam_policy" "lambda_kms" {
    name        = "${var.iam_kms_lambda_policy}"
    description = "A kms lambda policy"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kms:*"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "attach_kms_lambda" {
    role       = "${aws_iam_role.role_for_lambda.name}"
    policy_arn = "${aws_iam_policy.lambda_kms.arn}"
}

resource "aws_iam_policy" "lambda_vpc_access" {
    name        = "${var.iam_vpc_access_policy}"
    description = "A lambda vpc access policy"
    policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "attach_lambda_vpc_access" {
    role       = "${aws_iam_role.role_for_lambda.name}"
    policy_arn = "${aws_iam_policy.lambda_vpc_access.arn}"
}

resource "aws_lambda_function" "test_lambda" {
  filename         = "app.zip"
  function_name    = "${var.lambda_function_name}"
  role             = "${aws_iam_role.role_for_lambda.arn}"
  handler          = "app.handler"
  source_code_hash = "${base64sha256(file("app.zip"))}"
  runtime          = "python2.7"
  kms_key_arn      = "${var.kms_key}"

  vpc_config {
    subnet_ids = ["${var.subnet_id}"]
    security_group_ids = ["${var.security_group_id}"]
  }

}

output "kms_key_arn" {
  value = "${aws_lambda_function.test_lambda.kms_key_arn}"
}
```

### Debug Output
https://gist.github.com/rberlind/404b98eb782418d83e8c4b61a528642d

### Expected Behavior

I had expected the kms_key_arn to be saved with my new AWS Lambda function and show up when I accessed the lambda function in the AWS Console, scrolled down to the environment variables section, and clicked on the arrow next to "encryption configuration" to see the encryption configuration of the Lambda function.  But it was not there.  Additionally, the kms_key_arn output did not have a value.

Note that lines 6,733, 6,756, and 6,780 all show "KMSKeyArn":null.

The trace log also shows some HTTP 400 responses with X-Amzn-Errortype: InvalidParameterValueException along with "The role defined for the function cannot be assumed by Lambda."  However, I think this is an unrelated error since I also see them when I do include an environment variable in which case Terraform does save the kms_key_arn to the lambda function.

### Actual Behavior

The kms_key_arn was not saved to the Lambda function and the kms_key_arn output was empty. However, if I do include at least one environment variable inside the aws_lambda_function resource, then the kms_key_arn IS saved to the lambda function.

In contrast, when I do include an environment variable like this:
```
  environment {
    variables = {
      my_secret = "AQICAHhj5kWyeprUqLbu+1gkK2UeO5WuwRcjaI/IG27Us8zBRwHH745dQMacM8zkqhaRNB7cAAAAbDBqBgkqhkiG9w0BBwagXTBbAgEAMFYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/QPGAjv5Ak2faX6aAgEQgCm+snwc3SmmGGpAc6kahKKnOCZFWkg4hA3OpYt7Pp0yDGb9JYJJjDX9Nw=="
    }
  }
```
I do see the kms_key_arn saved to the lambda function and I do see it in the output. Additionally, the trace log shows "KMSKeyArn":"arn:aws:kms:us-east-1:<account>:key/<kms_key>" where I have redacted the actual AWS account ID and kms_key ARN.

Here is a gist with good trace log: https://gist.github.com/rberlind/0b1eb971cfce9030f5a3ab1683f33405

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @rberlind 👋 Thank you for reporting this. I was able to confirm the same undocumented behavior with the Lambda API, even today. Since this is an oddity with the API, for now it seems best to at least document the behavior. In that regard, I have submitted #10850. If this is continually problematic for practitioners, we can decide then if further action is necessary within Terraform.

**Comment by rberlind** [comment]
Thanks @bflad
