### ISSUE TITLE
Hyphens in profile names of AWS credentials file causes current AWS provider to fail

### ISSUE THREAD

**Issue by alienth** [terraform-providers/terraform-provider-aws#6415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.10

aws 0.42.0, 0.43.0

### Expected Behavior

terraform should be able to use AWS credential files containing hyphenated profile names, like `aws-cli` does.

### Actual Behavior

Having any profile names containing hyphens results in the following exception:

```
* provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider
```

### Steps to Reproduce

1. Have a profile name in your AWS credentials file with a hyphen in it.
1. Try to do any `plan` on any terraform config using the latest AWS provider.

### Important Factoids

Anyone using https://github.com/broamski/aws-mfa will encounter this, as that utility creates hyphens in the profile names.

### References

Created https://github.com/aws/aws-sdk-go/issues/2263 to track the issue upstream.

**Comment by alienth** [comment]
Turns out this was actually a syntax error. Under the old SDK, it was silently ignored. It noisily fails under the new one, breaking all profiles: https://github.com/aws/aws-sdk-go/issues/2263#issuecomment-437510327

**Comment by bflad** [comment]
Hi @alienth 👋 Thanks so much for reporting that upstream and here! Just to followup, it looks like they were able to revert the change in behavior and that update was a part of AWS Go SDK v1.15.74 and pulled into the AWS provider via https://github.com/terraform-providers/terraform-provider-aws/pull/6439 (releasing in our next update, version 1.44.0).
