### ISSUE TITLE
Support for Data Resource for aws_ssm_document

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#6418]
I would like to reuse existing AWS Managed SSM Documents.. I can currently run the below cli command to get the existing AWS-GatherSoftwareInventory ssm document. It would be nice to reuse this managed document using the data resource as apposed to creating a brand new document

`aws ssm get-document --name "AWS-GatherSoftwareInventory"`

**Comment by saravanan30erd** [comment]
will work on this

**Comment by bflad** [comment]
A new `aws_ssm_document` data source has been merged and will release with version 1.47.0 of the AWS provider, sometime later this week. 👍

**Comment by bflad** [comment]
This was released (4 days ago) in [version 1.47.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1470-november-26-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
