### ISSUE TITLE
resource/aws_codebuild_project: Migrate Attributes From TypeSet to TypeList

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#6427]
## Details

There are quite a few bugs related to attribute handing (especially `artifacts`) caused by the `Set` hashing. We should convert the `Type: schema.TypeSet` and `MaxItems: 1` attributes to `schema.TypeList` to simplify how they work in the resource and testing. We can do it before a major version upgrade if we don't consider the attribute references changing from `source.#####.X` to `source.0.X` a real breaking change.

## References

After the above change, these can hopefully be easier to close with covering acceptance tests:

* #755
* #2050
* #2431
* #5703
* #6127
* #6129 
* #6214

**Comment by vibhuyadav** [comment]
I am assuming #6643 might also belong to this list. Correct me if I am wrong

**Comment by DrFaust92** [comment]
@bflad, is this still relevant? does this relate to the `environment` block?

**Comment by anGie44** [comment]
The fix for this has been merged and will release with `v2.64.0` of the Terraform AWS Provider, expected in this week's release.
