### ISSUE TITLE
aws_iam_instance_profile returning "non existent" attribute "role"

### ISSUE THREAD

**Issue by dfduarte** [terraform-providers/terraform-provider-aws#6429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Scenario

I'm facing a weird issue where the AWS provider can't recognize the "role" attribute when defining a new IAM role. Am I doing something wrong or can we consider this a bug?

### Terraform Version

$ terraform version

Terraform v0.11.8
+ provider.aws v1.43.2
+ provider.template v1.0.0

### Affected Resource(s)

* aws_iam_instance_profile

### Terraform Configuration Files

```
resource "aws_iam_role" "gitlab-role" {
  name               = "gitlab-role"
  assume_role_policy = "${file("templates/assumerole.json")}"
}

resource "aws_iam_policy" "policy" {
  name = "gitlab-servers-policy"
  policy = "${file("templates/gitlabpolicy.json")}"
}

resource "aws_iam_role_policy_attachment" "gitlab-role-attachment" {
  role      = "${aws_iam_role.gitlab-role.name}"
  policy_arn = "${aws_iam_policy.policy.arn}"
}

data "aws_iam_instance_profile" "gitlab-instance-profile" {
  role  = "${aws_iam_role.gitlab-role.name}"
  name  = "gitlab_instance_profile"
}
```

### Expected Behavior

Terraform must apply the TF files

### Actual Behavior

Error: data.aws_iam_instance_profile.gitlab-instance-profile: : invalid or unknown key: roles

Or even

Error: data.aws_iam_instance_profile.gitlab-instance-profile: : invalid or unknown key: role

### Steps to Reproduce

1. Generate a TF file with the IAM definitions above
2. Run the usual flow (`terraform init, plan, apply`. It should trigger the message at the plan step)

### Important Factoids

I can't find the reference for `role` or `roles` in the source code. Maybe has been removed?
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_iam_instance_profile.go

However, the test references it

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_iam_instance_profile_test.go

**Comment by pvanbuijtene** [comment]
Why are you using a data source? ;)

**Comment by ryndaniels** [comment]
Hi @dfduarte - thanks for taking the time to open this! As @pvanbuijtene mentioned, it looks like you are using a data source instead of a resource for `aws_iam_instance_profile`. If you want to create that profile, you'll want to use a resource instead, which does accept the `role` argument. If you run into further problems, please feel free to open a new issue! 🙂
