### ISSUE TITLE
extend aws_ssm_maintenance_window_task resource to accept name, description, task-parameters and Document version.

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#6431]
based on the cli options, https://docs.aws.amazon.com/cli/latest/reference/ssm/register-task-with-maintenance-window.html

You can set a name, description to the automation task.

Moreover, I am using task type AUTOMATION to start/stop instances. We need to be able to pass InstanceId via task parameters which currently the resource doesn't support.

**Comment by sunilkumarmohanty** [comment]
I think this is a duplicate of #5762

**Comment by bflad** [comment]
Name and description have been merged in and will release with version 1.44.0 of the AWS provider, likely tomorrow.

**Comment by bflad** [comment]
Support for a new `task_invocation_parameters` configuration block in the `aws_ssm_maintenance_window_task` resource has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected later this week. Thanks to @kterada0509 for the implementation work. 👍
