### ISSUE TITLE
aws_launch_template block_device_mappings destroy_on_termination defaults to `false`, against documentation

### ISSUE THREAD

**Issue by in4mer** [terraform-providers/terraform-provider-aws#6434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.10
aws v1.31.0
null v1.0.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

```
data "null_data_source" "ebs_info" {
  inputs = {
    count = "1"
    devices = ""
  }
}

resource "aws_launch_template" "template_name" {
  ...
block_device_mappings {
  device_name = "/dev/xvdf"
  no_device = "${data.null_data_source.ebs_info.inputs.count < 1 ? true : false}"
  ebs {
    volume_size = "123"
    volume_type = "gp2"
  }
}

block_device_mappings {
  device_name = "/dev/xvdg"
  no_device = "${data.null_data_source.ebs_info.inputs.count < 2 ? true : false}"
  ebs {
    volume_size = "123"
    volume_type = "gp2"
  }
}
...
}

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```
aws_launch_template.mongodump-worker:
  id = lt-12345
  arn = arn:aws:ec2:us-west-2:lol-no:launch-template/lt-12345
  block_device_mappings.# = 8
  block_device_mappings.0.device_name = /dev/xvdb
  block_device_mappings.0.ebs.# = 0
  block_device_mappings.0.no_device = false
  block_device_mappings.0.virtual_name = ephemeral0
  block_device_mappings.1.device_name = /dev/xvdc
  block_device_mappings.1.ebs.# = 0
  block_device_mappings.1.no_device = true
  block_device_mappings.1.virtual_name = ephemeral1
  block_device_mappings.2.device_name = /dev/xvdd
  block_device_mappings.2.ebs.# = 0
  block_device_mappings.2.no_device = true
  block_device_mappings.2.virtual_name = ephemeral2
  block_device_mappings.3.device_name = /dev/xvde
  block_device_mappings.3.ebs.# = 0
  block_device_mappings.3.no_device = true
  block_device_mappings.3.virtual_name = ephemeral3
  block_device_mappings.4.device_name = /dev/xvdf
  block_device_mappings.4.ebs.# = 1
  block_device_mappings.4.ebs.0.delete_on_termination = false
  block_device_mappings.4.ebs.0.encrypted = false
  block_device_mappings.4.ebs.0.iops = 0
  block_device_mappings.4.ebs.0.kms_key_id = 
  block_device_mappings.4.ebs.0.snapshot_id = 
  block_device_mappings.4.ebs.0.volume_size = 80
  block_device_mappings.4.ebs.0.volume_type = gp2
  block_device_mappings.4.no_device = false
  block_device_mappings.4.virtual_name = 
  block_device_mappings.5.device_name = /dev/xvdg
  block_device_mappings.5.ebs.# = 1
  block_device_mappings.5.ebs.0.delete_on_termination = false
  block_device_mappings.5.ebs.0.encrypted = false
  block_device_mappings.5.ebs.0.iops = 0
  block_device_mappings.5.ebs.0.kms_key_id = 
  block_device_mappings.5.ebs.0.snapshot_id = 
  block_device_mappings.5.ebs.0.volume_size = 80
  block_device_mappings.5.ebs.0.volume_type = gp2
  block_device_mappings.5.no_device = true
  block_device_mappings.5.virtual_name = 
  block_device_mappings.6.device_name = /dev/xvdh
  block_device_mappings.6.ebs.# = 1
  block_device_mappings.6.ebs.0.delete_on_termination = false
  block_device_mappings.6.ebs.0.encrypted = false
  block_device_mappings.6.ebs.0.iops = 0
  block_device_mappings.6.ebs.0.kms_key_id = 
  block_device_mappings.6.ebs.0.snapshot_id = 
  block_device_mappings.6.ebs.0.volume_size = 80
  block_device_mappings.6.ebs.0.volume_type = gp2
  block_device_mappings.6.no_device = true
  block_device_mappings.6.virtual_name = 
  block_device_mappings.7.device_name = /dev/xvdi
  block_device_mappings.7.ebs.# = 1
  block_device_mappings.7.ebs.0.delete_on_termination = false
  block_device_mappings.7.ebs.0.encrypted = false
  block_device_mappings.7.ebs.0.iops = 0
  block_device_mappings.7.ebs.0.kms_key_id = 
  block_device_mappings.7.ebs.0.snapshot_id = 
  block_device_mappings.7.ebs.0.volume_size = 80
  block_device_mappings.7.ebs.0.volume_type = gp2
  block_device_mappings.7.no_device = true
  block_device_mappings.7.virtual_name = 

```

### Expected Behavior
https://www.terraform.io/docs/providers/aws/r/launch_template.html states that the default behavior should be ebs{} defaults to destroy_on_termination = true.

That is not the case.

### Actual Behavior
ebs{ destroy_on_termination = false } is set for all EBS volumes attached to instance from aws_launch_template

### Steps to Reproduce
See above config

### References

* #6433

**Comment by paultyng** [comment]
I have edited your issue to address the tone. We expect kind discourse. We accept criticism and are happy to respond, but criticism can be delivered constructively without expletives and what may feel like attacks. Bugs are going to happen, and I can appreciate that they can be frustrating.

There have been recent updates to this resource per the commit history (its only 11 months old, and the AWS service is [less than a year old](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-launch-templates-for-amazon-ec2-instances/) as well). Its possible this is a regression, or the docs are wrong (as the template nature of this means a lot of the flags are passthroughs from the original AMI's, so making defaults kinda tricky). The code does not show any default for this attribute: https://github.com/terraform-providers/terraform-provider-aws/blob/93d980498618ee520f6914204300ec578ee12571/aws/resource_aws_launch_template.go#L91-L100

Without digging in further though its hard to know which side the problem is on, docs or code.

Unfortunately now there is nothing that automatically syncs up flags in code with text in documentation, although its something we are hoping to tackle relatively soon to at least ensure without manual checking that the two are in sync.

**Comment by nywilken** [comment]
Circling back into this issue it appears that the error is in the documentation. The default value for `delete_on_termination` for root volumes is `true`. But it is `false` (or in the provider unset) for all other attached EBS volumes. I submitted PR #10625 to update the default value to `false`, as set by the AWS API, and added a link to the AWS documentation for preserving volumes on instance termination.

**Comment by in4mer** [comment]
@nywilken Fantastic, thank you.  Luckily that error only cost us a few thousand dollars, so glad we could get it taken care of so it doesn't affect others.
