### ISSUE TITLE
Feature request: CopyTags option for DLM

### ISSUE THREAD

**Issue by hryamzik** [terraform-providers/terraform-provider-aws#6442]
There's a `CopyTags` option mentioned in [docs](https://aws.amazon.com/blogs/aws/new-lifecycle-management-for-amazon-ebs-snapshots/) but I don't see a way to set it with terraform.

Related to #5176.

**Comment by bflad** [comment]
This enhancement has been merged and will release with version 1.44.0 of the AWS provider, likely later today or tomorrow. 👍

**Comment by bflad** [comment]
This has been released in [version 1.44.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1440-november-14-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
