### ISSUE TITLE
Add the name and description fields in terraform when creating SSM Maintenance window targets

### ISSUE THREAD

**Issue by nbrys** [terraform-providers/terraform-provider-aws#6471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Add the name and description fields in terraform when creating SSM Maintenance window targets

The console allows to add a name and description to tasks. Terraform doesn't support these 2 fields.

aws_ssm_maintenance_window_target
Potential Terraform Configuration
resource "aws_ssm_maintenance_window_target" "window_target" {
  name                  = ""
  description           = ""
}

* #0000

**Comment by nbrys** [comment]
PR is created: https://github.com/terraform-providers/terraform-provider-aws/pull/6472

**Comment by e-moshaya** [comment]
owner information would also be useful

![image](https://user-images.githubusercontent.com/44640934/54703211-3880f680-4b30-11e9-92f4-248060e81b46.png)

**Comment by nywilken** [comment]
Hi @e-moshaya thanks for bubbling up this issue. Support for creating maintenance window targets with the inclusion of `owner_information` is already possible with the Terraform resource. If you are interested in all three attributes then please thumbsup the issue. I will ping the author of the linked PR to see if they have bandwidth to work on getting it merged.

**Comment by e-moshaya** [comment]
documentation hasn't been updated with the new attributes

https://www.terraform.io/docs/providers/aws/r/ssm_maintenance_window_target.html

**Comment by nywilken** [comment]
The enhancement to the `aws_ssm_maintenance_window_target` resource has been merged and will be released with version 2.12.0 of the Terraform AWS provider, later this week.

**Comment by bflad** [comment]
This has been released in [version 2.12.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2120-may-24-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
