### ISSUE TITLE
S3 Block Public Access

### ISSUE THREAD

**Issue by oarmstrong** [terraform-providers/terraform-provider-aws#6489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Released yesterday is the functionality to block public access on S3 objects on the account level and the bucket level. We should implement this within the existing bucket resource as well as implement a new resource for the account-level settings.

https://aws.amazon.com/blogs/aws/amazon-s3-block-public-access-another-layer-of-protection-for-your-accounts-and-buckets/

I'm happy to take a stab at this over the weekend.

### New or Affected Resource(s)

* aws_s3_bucket
* aws_s3_block_public_access (proposed new)

**Comment by ewbankkit** [comment]
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6484

**Comment by oarmstrong** [comment]
I'm going to work on this this evening. Hopefully I'll have something worthy of initial implementation comments soon.

**Comment by acburdine** [comment]
@oarmstrong have you had a chance to look at this yet? Would totally be willing to pick it up if not 😄

**Comment by oarmstrong** [comment]
@acburdine unfortunately I've been busy so this slipped off my list. I'm still happy to do it but no idea when I'll really be able to get around to it (weekend maybe). If you want to pick it up instead please feel free! :)

**Comment by acburdine** [comment]
@oarmstrong ok! I'll look into it today.

**Comment by cwyl02** [comment]
Hey guys, looks like the account level public access block has been added per MR above. But is the support for bucket level public access block included?

**Comment by bflad** [comment]
The `aws_s3_account_public_access_block` resource has been released in [version 1.53.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1530-december-20-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

The bucket level support still needs to be reviewed and potentially adjusted in #6607.

**Comment by bflad** [comment]
The `aws_s3_bucket_public_access_block` resource has now been merged as well, thanks to @acburdine!

We were anticipating cutting 1.54.0 in early January after our end of year break, but this one might be good to get out today beforehand due to popularity... more soon. 😄
