### ISSUE TITLE
Feature request: IAM user and group tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6492]
Tagging for IAM users and groups [recently released](https://github.com/aws/aws-sdk-go/releases/tag/v1.15.77).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6484

**Comment by bflad** [comment]
Support for tagging IAM users and IAM roles has been merged in and will release with version 1.46.0 of the AWS provider, likely late today or tomorrow.

**Comment by bflad** [comment]
This has been released in [version 1.46.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1460-november-20-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
