### ISSUE TITLE
Feature request: DirectConnect virtual interface logical redundancy

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6493]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

DirectConnect virtual interface [logical redundancy](https://aws.amazon.com/directconnect/faqs/#Logical_Redundancy_Support) [recently released](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-direct-connect-launches-logical-redundancy-over-a-single-vir/).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6484

**Comment by ewbankkit** [comment]
It looks like:
* Add compute `has_logical_redundancy` attribute to `aws_dx_connection` and `aws_dx_lag` resources
* The BGP Peer APIs now take and return a BGP Peer ID - Previously we synthesized an ID

**Comment by bflad** [comment]
Support for these attributes has been merged and will release with version 2.2.0 of the Terraform AWS Provider, shortly.

**Comment by bflad** [comment]
This has been released in [version 2.2.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#220-march-15-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
