### ISSUE TITLE
 aws_security_group.default: InvalidAction: The action or operation requested (Resource type sg is invalid) is invalid.

### ISSUE THREAD

**Issue by MisderGAO** [terraform-providers/terraform-provider-aws#6496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.45.0

### Affected Resource(s)

* aws_security_group

### Terraform Configuration Files

```hcl
resource "aws_security_group" "default" {
  vpc_id = "${aws_vpc.vpc_test.id}"

  ingress {                                  #ingress bug reported on github
    protocol  = "-1"
    from_port = 0
    to_port   = 0
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags {
        Name = "sg_terraform"
    }
}
```
### Debug Output

```hcl
 + aws_security_group.default
      id:                                   <computed>
      arn:                                  <computed>
      description:                          "Managed by Terraform"
      egress.#:                             "1"
      egress.482069346.cidr_blocks.#:       "1"
      egress.482069346.cidr_blocks.0:       "0.0.0.0/0"
      egress.482069346.description:         ""
      egress.482069346.from_port:           "0"
      egress.482069346.ipv6_cidr_blocks.#:  "0"
      egress.482069346.prefix_list_ids.#:   "0"
      egress.482069346.protocol:            "-1"
      egress.482069346.security_groups.#:   "0"
      egress.482069346.self:                "false"
      egress.482069346.to_port:             "0"
      ingress.#:                            "1"
      ingress.482069346.cidr_blocks.#:      "1"
      ingress.482069346.cidr_blocks.0:      "0.0.0.0/0"
      ingress.482069346.description:        ""
      ingress.482069346.from_port:          "0"
      ingress.482069346.ipv6_cidr_blocks.#: "0"
      ingress.482069346.prefix_list_ids.#:  "0"
      ingress.482069346.protocol:           "-1"
      ingress.482069346.security_groups.#:  "0"
      ingress.482069346.self:               "false"
      ingress.482069346.to_port:            "0"
      name:                                 <computed>
      owner_id:                             <computed>
      revoke_rules_on_delete:               "false"
      tags.%:                               "1"
      tags.Name:                            "sg_terraform"
      vpc_id:                               "${aws_vpc.vpc_test.id}"
```
### Panic Output

Error: Error applying plan:

1 error(s) occurred:

* aws_security_group.default: 1 error(s) occurred:

* aws_security_group.default: InvalidAction: The action or operation requested (Resource type sg is invalid) is invalid. Verify that the action is typed correctly.
	status code: 400, request id: 353d5de3-053c-40b7-b01b-7e3a7a53dbd3

### Actual Behavior

I tested ingress and egress separately, which result following behaviors:

•	Apply only ingress part, no bug is reported and ingress rule is successfully created and configured, no egress created.

•	Apply only egress part, bug is reported but egress rule is successfully created, ingress rule is created but not correctly configured.

### Steps to Reproduce

1. `terraform apply`

### References

* #1920

**Comment by ryndaniels** [comment]
Hi @MisderGAO 👋 Thanks for taking the time to file this issue. One thing I notice in your config is that you'll want to have an `=` when defining the `tags` in the security group:

```
tags = {
     Name = "sg_terraform"
}
```

With that change made, I'm able to run a `terraform apply` with the config you provided successfully using the latest versions of Terraform and the AWS Terraform Provider. Could you check if you are still seeing this issue with the latest versions yourself? Thanks! 🙂

**Comment by ryndaniels** [comment]
Going to go ahead and close this as we haven't heard back in a couple weeks - if you're still running into issues with the updated config, please let us know. Thanks! 🙂
