### ISSUE TITLE
Cannot import aws_elastictranscoder_preset with VideoCodecOptions

### ISSUE THREAD

**Issue by mbamber** [terraform-providers/terraform-provider-aws#6539]
The imports for `aws_elastictranscoder_preset` resources are failing if the configuration uses a `VideoCodecOptions` block.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```Terraform v0.11.8
+ provider.aws v1.46.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* `aws_elastictranscoder_preset`

### Expected Behavior

The resource should have been imported completely

### Actual Behavior

The `VideoCodecOptions` settings are omitted from the imported state

### Steps to Reproduce

1. `terraform import aws_elastictranscoder_preset.preset <preset_id>`

**Comment by bflad** [comment]
Thanks for the fix @mbamber, it will be included with version 1.47.0 of the AWS provider, releasing sometime this week.

**Comment by bflad** [comment]
This was released (4 days ago) in [version 1.47.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1470-november-26-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
