### ISSUE TITLE
Feature Request: Route53 Resolver Rule

### ISSUE THREAD

**Issue by gazoakley** [terraform-providers/terraform-provider-aws#6550]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* `aws_route53_resolver_rule`

### Potential Terraform Configuration

```hcl
resource "aws_route53_resolver_rule" "example" {
  name                 = "example"
  domain_name          = "example.com"
  resolver_endpoint_id = "..."
  rule_type            = "FORWARD"

  target_ip {
    ip   = "123.45.67.89"
    port = 1234
  }

  tags {
    Foo = "Barr"
  }
}
```

### References

* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverRule.html
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_GetResolverRule.html
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_UpdateResolverRule.html
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_DeleteResolverRule.html

**Comment by gazoakley** [comment]
I'm planning to work on this unless anyone else has already started (also mentioned in #6525)

**Comment by videte47** [comment]
+1

**Comment by nywilken** [comment]
The `aws_route53_resolver_rule` resource has been merged and will release with version 2.2.0 of the Terraform AWS Provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 2.2.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#220-march-15-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by egarbi** [comment]
I really don't understand why target_ip has been implemented as a block.
This leads to some limitations when you are trying to add different numbers of IPs in a module.
Example, suppose That I need 2 IPs on testing environment but 4 in prod. I would like to hack the module as below:
```
resource "aws_route53_resolver_rule" "double" {
  count                = "${length(split(",", lookup(var.forwarding_rules[0], "ips"))) == 2 ? length(var.forwarding_rules) : 0}"
  domain_name          = "${lookup(var.forwarding_rules[count.index], "domain_name")}"
  name                 = "${lookup(var.forwarding_rules[count.index], "name")}"
  rule_type            = "${lookup(var.forwarding_rules[count.index], "rule_type")}"
  resolver_endpoint_id = "${aws_route53_resolver_endpoint.outbound.id}"

  target_ip {
    ip = "${element(split(",", lookup(var.forwarding_rules[count.index], "ips")),0)}"
  }

  target_ip {
    ip = "${element(split(",", lookup(var.forwarding_rules[count.index], "ips")),1)}"
  }

  tags = "${var.tags}"
}

resource "aws_route53_resolver_rule" "quad" {
  count                = "${length(split(",", lookup(var.forwarding_rules[0], "ips"))) == 4 ? length(var.forwarding_rules) : 0}"
  domain_name          = "${lookup(var.forwarding_rules[count.index], "domain_name")}"
  name                 = "${lookup(var.forwarding_rules[count.index], "name")}"
  rule_type            = "${lookup(var.forwarding_rules[count.index], "rule_type")}"
  resolver_endpoint_id = "3994439382"

  target_ip {
    ip = "${element(split(",", lookup(var.forwarding_rules[count.index], "ips")),0)}"
  }

  target_ip {
    ip = "${element(split(",", lookup(var.forwarding_rules[count.index], "ips")),1)}"
  }

  target_ip {
    ip = "${element(split(",", lookup(var.forwarding_rules[count.index], "ips")),2)}"
  }

  target_ip {
    ip = "${element(split(",", lookup(var.forwarding_rules[count.index], "ips")),3)}"
  }
}
```
so, if you need 2 ips, you pass ips value as a string of 2 element, and if you need 4 you pass 4 elements as string. Ugly.
Also if you look into Cloudformation templates, target_ips are passed as a list and port is not needed.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53resolver-resolverrule.html#cfn-route53resolver-resolverrule-targetips
Why did you decide to implement this with ports and blocks?

**Comment by ASethi93** [comment]
cant we apply count on the target Ip's ? also this module creates the forwarding rule only what if one has to create a sys type
