### ISSUE TITLE
assume_role leads to EKS cluster being instantiated in wrong account

### ISSUE THREAD

**Issue by infracaninophile** [terraform-providers/terraform-provider-aws#6559]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
% terraform -v
Terraform v0.11.10
+ provider.aws v1.46.0
+ provider.http v1.0.1
```

### Affected Resource(s)

* aws_eks_cluster
-- we're using the module from https://github.com/WesleyCharlesBlake/terraform-aws-eks

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "${var.region}"
  allowed_account_ids = [ "${var.account_id}" ]

  assume_role = {
    role_arn     = "arn:aws:iam::${var.account_id}:role/${var.iam_role}"
    session_name = "staging"
  }
}
```
```hcl
terraform {
  required_version = ">= 0.10.0"

  backend "s3" {
    encrypt        = true
    bucket         = "gigaclear-terraform-state"
    role_arn       = "arn:aws:iam::54XXXXXXXXXX:role/TerraformAdminRole"
    dynamodb_table = "gigaclear-terraform-lock"
    region         = "eu-west-1"
    key            = "staging/tfstate"
  }
}
```
```hcl
# EKS Terraform module

module "eks" {
  source             = "../modules/eks"
  cluster-name       = "staging"
  aws-region         = "eu-west-1"
  node-instance-type = "m4.large"
  desired-capacity   = "2"
  max-size           = "4"
  min-size           = "1"
  vpc-subnet-cidr    = "10.0.0.0/16"
}
```
We have a multiple account setup at AWS with user logins defined in the main account and a number of sub-accounts accessed by role-switching.  `~/.aws/config` looks like:

```
[profile administration]
region = eu-west-1
role_arn = arn:aws:iam::54XXXXXXXXXX:role/TerraformAdminRole
source_profile = default
[profile production]
region = eu-west-1
role_arn = arn:aws:iam::71XXXXXXXXXX:role/TerraformAdminRole
source_profile = default
[profile staging]
region = eu-west-1
role_arn = arn:aws:iam::85XXXXXXXXXX:role/TerraformAdminRole
source_profile = default
[default]
region = eu-west-1
```
and `~/.aws/credentials` has just the aws_access_key_id and aws_secret_access_key for the default profile.

### Expected Behavior

We expected an EKS cluster to be instantiated in our aws-systems-staging account

### Actual Behavior

The cluster is instantiated in our main account.  However, testing by spinning up a simple t2.micro instance results in that being created in the correct account.

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @infracaninophile 👋 Sorry for the delayed response here as we're going through the issue backlog. Hopefully you were able to get this resolved awhile ago.

We are not aware of any specific behavior difference with EKS resources in comparison to others with respect to `assume_role` usage. We would recommend verifying that all modules are correctly using your configured provider via [passing providers explicitly](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly). e.g.

```hcl
# EKS Terraform module

module "eks" {
  source             = "../modules/eks"
  cluster-name       = "staging"
  aws-region         = "eu-west-1"
  node-instance-type = "m4.large"
  desired-capacity   = "2"
  max-size           = "4"
  min-size           = "1"
  vpc-subnet-cidr    = "10.0.0.0/16"

  providers = {
    aws = "aws"
  }
}
```

If you are still experiencing this issue on recent versions of Terraform CLI (0.12+) and the Terraform AWS Provider (2+), please reach out in a new issue and we'll be happy to take a fresh look. 👍
