### ISSUE TITLE
Race condition when creating kms key alias leads to 'Resource x does not have attribute y for variable'

### ISSUE THREAD

**Issue by AndreuPlata** [terraform-providers/terraform-provider-aws#6560]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
* 0.11.3

### Aws Provider Version
* 1.40.0

### Affected Resource(s)

* aws_kms_alias

### Debug Output
* https://gist.github.com/AndreuPlata/e336dd0bcd47e2349aa1d7eae14293b4

### Expected Behaviour

Terraform should have waited for the kms alias to be created

### Actual Behaviour

* Terraform sent a request to create the alias
* it immediately after sent a get aliases request to find the created kms alias
* it did not find it (potential aws delay/eventual consistency)
* removed the alias from the state file which broke all future references to this resource

### Steps to Reproduce

This is hard to reproduce as it is not consistently happening. We believe there is a race condition between terraform requesting the list of aliases and aws confirming alias creation

* Create a kms key and alias
* Have an output referencing that alias.name and alias.arn
* Use that output in a different resource

**Comment by bflad** [comment]
Fix submitted: #7907

**Comment by nywilken** [comment]
The fix has been merged and will release with version 2.2.0 of the Terraform AWS Provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 2.2.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#220-march-15-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
