### ISSUE TITLE
Feature request: Route 53 Resolver endpoint resource

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6563]
Add a Route 53 Resolver endpoint resource.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6525

**Comment by ewbankkit** [comment]
Suggested syntax:

```hcl
resource "aws_route53_resolver_endpoint" "foo" {
  direction = "INBOUND"
  name      = "terraform-testacc-r53-resolver-foofoo"

  security_group_ids = [
    "${aws_security_group.sg1.id}",
    "${aws_security_group.sg2.id}",
  ]

  ip_address {
    subnet_id = "${aws_subnet.sn1.id}"
  }

  ip_address {
    subnet_id = "${aws_subnet.sn3.id}"
    ip        = "10.0.64.4"
  }

  tags {
    Env = "Prod"
  }
}
```

**Comment by dahui** [comment]
+1

I would also like to see the resources related to other pieces of the R53 Resolver functionality added, such as rule creation and VPC assignment to said rules for outgoing forwarders.

**Comment by jankarltommy** [comment]
I agree, the way I've worked around this was adding local exec that invoked the aws cli commands for the resolver endpoints and rules.

**Comment by rekz1** [comment]
+1

**Comment by JadyLiu** [comment]
@jankarltommy would you please share more information about how you run aws-cli in local exec?

**Comment by jankarltommy** [comment]
@JadyLiu 

Here is what I cooked up to create the resolver endpoint through Terraform:
```
############################
#Vars
#############################
variable "creator-request-id" {
  type = "string"
  description = "A unique string that identifies the request"
  default = "terraform-created"
}


variable "direction" {
  type = "string"
  description = "The direction for the endpoint, possible values are: INBOUND or OUTBOUND"
}

variable "subnet-ids" {
  type = "list"
  description = "the subnet"
}

variable "security-groups" {
  type = "list"
  description = "The security groups associated with the provided subnets"
}

variable "ip-addresses" {
  type = "list"
  description = "The list of IP address to associate for the subnet - if non-dynamic is desired"
}

variable "endpoint-name" {
  type = "string"
  description = "A friendly name that lets you easily find a configuration in the Resolver dashboard in the Route 53 console"
}

variable "profile" {
  type = "string"
  description = "The AWS CLI profile to use"
}

variable "tags" {
  type = "string"
  description = "A list of the tag keys and values that you want to associate with the endpoint."
  // Syntax Key=string,Value=string ...
  // Example Key=owner,Value=John Doe,Key=terraform_managed,Value=true
}
############################
# Resources
############################
data "template_file" "log_name" {
  template = "${path.module}/output.log"
}

data "local_file" "createEndpoint" {
  filename = "${data.template_file.log_name.rendered}"
  depends_on = ["null_resource.createEndpoint"]
}

resource "null_resource" "createEndpoint" {
  provisioner "local-exec" {
    command = "aws route53resolver create-resolver-endpoint --creator-request-id terraform-created --security-group-ids ${local.security-groups} --direction ${var.direction} --ip-addresses ${local.ip-list} --name ${var.endpoint-name} --tags ${var.tags} --profile ${var.profile} > ${data.template_file.log_name.rendered}"
  }
}


data "template_file" "ips" {
  count = "${length(var.subnet-ids)}"
  template = "SubnetId=${var.subnet-ids[count.index]},Ip=${var.ip-addresses[count.index]} "
}

data "template_file" "security-groups" {
  count = "${length(var.security-groups)}"
  template = "${var.security-groups[count.index]} "
}

locals {
  ip-list = "${join(" ",data.template_file.ips.*.rendered)}"
  security-groups = "${join(" ",data.template_file.security-groups.*.rendered)}"
}
############################
# Outputs
############################
output "file" {
  value = "${data.template_file.log_name.rendered}"
}

output "log" {
  value = "${data.local_file.createEndpoint.content}"
}
```
This will allow you create the endpoints, I did something very similar for the other cli commands. The catch here is that you need to make sure your aws access & secret keys are set along with a `~/.aws/config` file. This is why there is a variable for the profile. In my pipeline I do the following:

```
- export AWS_ACCESS_KEY_ID=$TERRAFORM_ACCESS_KEY
- export AWS_SECRET_ACCESS_KEY=$TERRAFORM_SECRET_KEY
- export AWS_DEFAULT_REGION="us-east-1"
- export TF_IN_AUTOMATION=true
- export AWS_CONFIG_FILE=$AWS_CONFIG_FILE

- curl -s --request GET   //LOCATION WHERE MY CONFIG FILE IS
```
The other catch is that the endpoint id is not something that is available after executing the command, rather the entire output as a whole is stored. I suppose the resolverId could be grepped through another local exec that reads the local_file and stores it into another file, which we then output again. I'm not a big fan of this solution but it's a temporary solution until we have a route53resolver. Hope this helps!

**Comment by logichard** [comment]
Any update of this? We need this too. :)

**Comment by hotdawg789** [comment]
Any updates? getting off DNS servers and looking to implement this across 200+ aws accounts.

**Comment by dbsysteluk-stuartlupton** [comment]
So very interested in this

**Comment by JuanOI** [comment]
Really looking forward to this (+ all R53 Resolver related resources)

**Comment by surfingsimbo** [comment]
+1

**Comment by nywilken** [comment]
This resource has been merged and will release with version 2.1.0 of the Terraform AWS Provider.

**Comment by bflad** [comment]
This has been released in [version 2.1.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1600-february-22-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by pjain17** [comment]
Hi, Thank you so much for adding the aws_route53_resolver_endpoint in v2.1.0.
I tried using the aws_route53_resolver_endpoint but it errors out saying that that it requires 2 IP addresses even though I have provided it. Even if I don't add the IP addresses as those are optional, it errors out. Any pointers regarding this? Also When will the 2.3.x version be released with outbound rule association?
Thanks!
```
resource "aws_route53_resolver_endpoint" "route53_resolver_in" {
  name      = "Inbound_EP"
  direction = "INBOUND"

  security_group_ids = [
    "${aws_security_group.kubernetes_control.id}"
  ]

  ip_address {
    subnet_id = "${aws_subnet.kubernetes_control_sub.id}"
    ip = "10.43.60.21"
  }

  ip_address {
    subnet_id = "${aws_subnet.kubernetes_control_sub.id}"
    ip = "10.43.50.21"
  }

  tags {
    Owner = "${var.owner}"
    Name = "Inbound_endpoint"
  }
}
```
ERROR: ```* aws_route53_resolver_endpoint.route53_resolver_in: error creating Route53 Resolver endpoint: InvalidRequestException: [RSLVR-00400] Resolver endpoint need to have at least 2 IP addresses.
status code: 400, request id: 29c6f1e0-9d36-4ed3-8a42-b0d5932bebe4```

**Comment by an-sush** [comment]
@pjain17 can you try two unique subnet_ids? 
Also aws provided 2.2.0 already supports rules and rule associations.

I have a question though. Why is there a mandate to use 2 IP addresses/subnets? Why can't we just select one and create a resolver? By using AWS UI console, it allows to create resolver with one subnet/ip

**Comment by ewbankkit** [comment]
@pjain17 See https://github.com/terraform-providers/terraform-provider-aws/issues/7950#issuecomment-473439150 as to why we are currently using just `subnet_id` (and not including `ip`) to define uniqueness for the `ip_address` attribute.

**Comment by ewbankkit** [comment]
@an-sush There was a discussion around this during the review of the PR, see https://github.com/terraform-providers/terraform-provider-aws/pull/6574#pullrequestreview-208664306. Even though the API says that the minimum number of IPs is 1 we found that an error returned with less than 2.
I'll check via the console.

**Comment by nywilken** [comment]
@pjain17 thanks for reporting the issue, and @an-sush @ewbankkit thanks for helping out. Commenting on closed issues makes it difficult to track the thread. Would you mind opening a new issue or adding your comments to the already open issue #7050, as they are all related.

**Comment by ewbankkit** [comment]
@an-sush In the us-west-2 Console I see the text

> To improve reliability, Resolver requires that you specify two IP addresses for DNS queries. We recommend that you specify IP addresses in two different Availability Zones. After you add the first two IP addresses, you can optionally add more in the same or different Availability Zones.
