### ISSUE TITLE
Feature request: AWS Transfer for SFTP service

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6584]
New AWS Transfer for SFTP service [just announced](https://aws.amazon.com/about-aws/whats-new/2018/11/aws-transfer-for-sftp-fully-managed-sftp-for-s3/).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6585

**Comment by walterheck** [comment]
This would be super great to have, we have more than one client happy to get started on this yesteryear :)

**Comment by binhoul** [comment]
Just expecting

**Comment by dschwinn** [comment]
+1

**Comment by sstarcher** [comment]
@ojongerius looks like #6639 was merged

**Comment by ojongerius** [comment]
Who's up for the other resources? 😄

**Comment by bflad** [comment]
A new `aws_transfer_user` resource has been merged and will release with version 1.53.0 of the AWS provider, likely tomorrow.

**Comment by sstarcher** [comment]
Excellent work everyone just missing the ssh_key now.

**Comment by bflad** [comment]
And just like that, the last new `aws_transfer_ssh_key` resource has been merged for release tomorrow with version 1.53.0 of the AWS provider. 😄 Shout out to @kterada0509 here.

For any additional feature requests, bugs, etc. please create new issues. Thanks!
