### ISSUE TITLE
data source for aws_cloudfront_distribution

### ISSUE THREAD

**Issue by BernhardBerbuir** [terraform-providers/terraform-provider-aws#6586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Data sources exist for most resource types, but not for a `aws_cloudfront_distribution`.

My use case is that I create a aws_cloudfront_distribution in one environment and want to create CNAMEs at an other environment (each environment has its own set of terraform files and state file).

### New or Affected Resource(s)

* aws_cloudfront_distribution (data source)

### Potential Terraform Configuration

It would be useful to reference a data source by tags.

### References

* none

**Comment by leonfs** [comment]
I would probably add that a data source for `aws_cloudfront_origin_access_identity` would be great too.

**Comment by ddumitru-gpsw** [comment]
datasource for `aws_cloudfront_origin_access_identity` is also  useful to reference in a s3 bucket policy

**Comment by lulubobst** [comment]
Can we get an ETA for these changes by chance, not sure how releases work here?

**Comment by dpetzold** [comment]
I have a PR open here https://github.com/terraform-providers/terraform-provider-aws/pull/6468. Its pretty old now and has gone stale. I'll see if I can update it.

**Comment by bflad** [comment]
Support for a new `aws_cloudfront_distribution` data source has been merged and will release later this week with version 2.57.0 of the Terraform AWS Provider. Thanks to @dpetzold for the implementation. 👍 

For further enhancements to this data source or requests for new data sources, please create new, individual feature requests.
