### ISSUE TITLE
Feature request: Support S3 Intelligent-Tiering storage class

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6588]
S3 [Intelligent-Tiering storage class](https://aws.amazon.com/s3/storage-classes/#Variable_access) [just announced](https://aws.amazon.com/about-aws/whats-new/2018/11/s3-intelligent-tiering/).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6585

**Comment by ewbankkit** [comment]
Affects `aws_s3_bucket` and `aws_s3_bucket_object` resources.

**Comment by bflad** [comment]
Support for `INTELLIGENT_TIERING` validation has been merged in for the `aws_s3_bucket` and `aws_s3_bucket_object` resources, which will release with version 1.51.0 of the AWS provider, likely middle of this week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.51.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1510-december-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
