### ISSUE TITLE
Add tagging support for IAM Users and Roles

### ISSUE THREAD

**Issue by devonbleak** [terraform-providers/terraform-provider-aws#6596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It appears tags have been (silently?) added to some IAM resources.  Looking at the Go SDK looks like it's Users and Roles.

### New or Affected Resource(s)

* aws_iam_user
* aws_iam_role

### Potential Terraform Configuration

Similar to other resources that support tags:

```hcl
resource "aws_iam_user" "tf_test" {
  name              = "tf-test"
  force_destroy = true

  tags {
    key1 = "value1"
    key2 = "value2"
  }
}

resource "aws_iam_role" "tf_test" {
  name = "tf-test"
  
  tags {
    key1 = "value1"
    key2 = "value2"
  }
}
```

**Comment by tdmalone** [comment]
Not quite silently - https://aws.amazon.com/about-aws/whats-new/2018/11/aws_manage_iam_users_and_roles_by_using_tags/

Can I ask why this is closed though?
