### ISSUE TITLE
r/ecs_service: add propagate_tags attribute

### ISSUE THREAD

**Issue by kl4w** [terraform-providers/terraform-provider-aws#6601]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* add `propagate_tags` attribute

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource aws_ecs_service test {
  name            = "test"
  task_definition = "${aws_ecs_task_definition.test.arn}"

  tags = {
    tag-key = "tag-value"
  }

  propagate_tags = "SERVICE"
}
```

### References

* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-propagateTags

**Comment by bflad** [comment]
Support for the `propagate_tags` argument has been merged and will release with version 1.51.0 of the AWS provider, likely later today. 👍
