### ISSUE TITLE
aws_elasticsearch_domain create an IAM policy so that an Elasticsearch Service instance can write logs to a given log group

### ISSUE THREAD

**Issue by luisamador** [terraform-providers/terraform-provider-aws#6606]
Currently, there's no way to specify a policy for granting access from an Elasticsearch instance to a CloudWatch log group:

"* aws_elasticsearch_domain.es_vpc: ValidationException: The Resource Access Policy specified for the CloudWatch Logs log group blah-search-slow-non-prod does not grant sufficient permissions for Amazon Elasticsearch Service to create a log stream. Please check the Resource Access Policy."

https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html#log_publishing_options

https://aws.amazon.com/blogs/database/viewing-amazon-elasticsearch-service-slow-logs/

**Comment by bflad** [comment]
#6680 was merged and is published in the documentation. Please reach out if something else was needed here.
