### ISSUE TITLE
aws_security_group rules idempotency bug

### ISSUE THREAD

**Issue by voroniys** [terraform-providers/terraform-provider-aws#6608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.48.0

### Affected Resource(s)

aws_security_group
aws_security_group_rule

### Terraform Configuration Files

```hcl
resource "aws_security_group" "sg-app" {
  name        = "${upper(var.dns_name)}-APP"
  description = "Security group for ${upper(var.dns_name)} application layer"
  vpc_id      = "${aws_vpc.main.id}"

  # SSH access
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${data.aws_vpc.mgt.cidr_block}"]
  }
  # outbound internet access
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
resource "aws_security_group_rule" "allow_local_subnet" {
  count           = "${var.testing}"
  type            = "ingress"
  from_port       = 0
  to_port         = 65535
  protocol        = "tcp"
  cidr_blocks     = ["${aws_subnet.subnet-APP.cidr_block}"]
  security_group_id = "${aws_security_group.sg-app.id}"
}
```
### Expected Behavior

Security group is created containing 2 rules

### Actual Behavior

The rule which is defined in the `resource "aws_security_group_rule"` is flipping each terraform run - one tun it is created, next one it is removed

### Steps to Reproduce

1. `terraform apply` on the code above.

**Comment by bflad** [comment]
Hi @voroniys 👋 Sorry for the trouble.

As noted at the top of the [`aws_security_group` resource](https://www.terraform.io/docs/providers/aws/r/security_group.html) and [`aws_security_group_rule` resource](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html) documentation pages:
> **NOTE on Security Groups and Security Group Rules:** Terraform currently provides both a standalone Security Group Rule resource (a single `ingress` or `egress` rule), and a Security Group resource with `ingress` and `egress` rules defined in-line. At this time you cannot use a Security Group with in-line rules in conjunction with any Security Group Rule resources. Doing so will cause a conflict of rule settings and will overwrite rules.

You'll need to decide which configuration style suits your environment best by either having all ingress rules defined in your `aws_security_group`, e.g.

```hcl
resource "aws_security_group" "sg-app" {
  name        = "${upper(var.dns_name)}-APP"
  description = "Security group for ${upper(var.dns_name)} application layer"
  vpc_id      = "${aws_vpc.main.id}"

  # SSH access
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${data.aws_vpc.mgt.cidr_block}"]
  }
  # local subnet
  ingress {
    from_port       = 0
    to_port         = 65535
    protocol        = "tcp"
    cidr_blocks     = ["${aws_subnet.subnet-APP.cidr_block}"]
  }
  # outbound internet access
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group_rule" "allow_local_subnet" {
  count           = "${var.testing}"
  type            = "ingress"

  security_group_id = "${aws_security_group.sg-app.id}"
}
```

Or if you would rather keep the ingress rules all separate via `aws_security_group_rules` resources:

```hcl
resource "aws_security_group" "sg-app" {
  name        = "${upper(var.dns_name)}-APP"
  description = "Security group for ${upper(var.dns_name)} application layer"
  vpc_id      = "${aws_vpc.main.id}"

  # outbound internet access
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group_rule" "allow_ssh_access" {
  count           = "${var.testing}"
  type            = "ingress"
  from_port       = 22
  to_port         = 22
  protocol        = "tcp"
  cidr_blocks     = ["${data.aws_vpc.mgt.cidr_block}"]
  security_group_id = "${aws_security_group.sg-app.id}"
}

resource "aws_security_group_rule" "allow_local_subnet" {
  count           = "${var.testing}"
  type            = "ingress"
  from_port       = 0
  to_port         = 65535
  protocol        = "tcp"
  cidr_blocks     = ["${aws_subnet.subnet-APP.cidr_block}"]
  security_group_id = "${aws_security_group.sg-app.id}"
}
```

Since this is a documented limitation, I'm going to close this issue for now.
