### ISSUE TITLE
Feature request: Support S3 S3 Cross-Region Replication to Glacier

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6611]
S3 Cross-Region Replication to Glacier [just announced](https://aws.amazon.com/about-aws/whats-new/2018/11/s3-glacier-api-simplification/).

**Comment by bflad** [comment]
Support for this has been merged in and will release with version 1.51.0 of the AWS provider, likely in the next day or two. 👍

**Comment by bflad** [comment]
This has been released in [version 1.51.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1510-december-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
