### ISSUE TITLE
Feature request: Support VPC sharing

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6630]
> With VPC sharing, you can now allow multiple accounts in the same AWS Organization to launch their application resources, like EC2 instances, RDS databases, and Redshift clusters into shared, centrally managed VPCs.

[User Guide](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6624

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6527

**Comment by bflad** [comment]
The following enhancements have been merged and will release with version 1.51.0 of the AWS provider, likely in the next day or two. 👍 Thanks @ewbankkit! 

* data-source/aws_internet_gateway: Add `owner_id` attribute
* data-source/aws_route_table: Add `owner_id` attribute
* data-source/aws_subnet: Add `availability_zone_id` argument and `owner_id` attribute
* data-source/aws_subnet: Use API provided `arn` attribute
* data-source/aws_vpc: Add `owner_id` attribute
* data-source/aws_vpc_dhcp_options: Add `owner_id` attribute
* resource/aws_default_network_acl: Add `owner_id` attribute
* resource/aws_default_route_table: Add `owner_id` attribute
* resource/aws_default_subnet: Add `owner_id` attribute
* resource/aws_default_vpc: Add `owner_id` attribute
* resource/aws_default_vpc_dhcp_options: Add `owner_id` attribute
* resource/aws_internet_gateway: Add `owner_id` attribute
* resource/aws_network_acl: Add `owner_id` attribute
* resource/aws_route_table: Add `owner_id` attribute
* resource/aws_subnet: Add `availability_zone_id` argument and `owner_id` attribute
* resource/aws_subnet: Use API provided `arn` attribute
* resource/aws_vpc: Add `owner_id` attribute
* resource/aws_vpc_dhcp_options: Add `owner_id` attribute
