### ISSUE TITLE
Unable to use existing IAM server certificate with API Gateway domain

### ISSUE THREAD

**Issue by austinbutler** [terraform-providers/terraform-provider-aws#6635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```txt
Terraform v0.11.10
+ provider.archive v1.1.0
+ provider.aws v1.49.0
+ provider.mysql v1.1.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_iam_server_certificate
* aws_api_gateway_domain_name

### Terraform Configuration Files

```hcl
resource "aws_iam_server_certificate" "staging" {
  name              = "staging"
  certificate_body  = "${file("staging/cert-public.pem")}"
  certificate_chain = "${file("staging/cert-chain.pem")}"
  private_key       = "${file("staging/cert-private.secret.pem")}"
  path              = "/cloudfront/staging/"
}

resource "aws_api_gateway_domain_name" "staging" {
  domain_name = "staging.api.example.com"
  regional_certificate_arn = "${aws_iam_server_certificate.staging.arn}"

  endpoint_configuration {
    types = ["REGIONAL"]
  }
}
```

### Debug Output

There's quite a lot of info I'd have to sanitize, so I haven't included this, but if it is necessary let me know.

### Expected Behavior

Terraform creates an `aws_api_gateway_domain_name` with the `regional_certificate_arn` pointed to  an existing `aws_iam_server_certificate`.

### Actual Behavior

Received an error stating the certificate's vendor should be ACM instead of IAM. I also tried without specifying `REGIONAL` and changing `regional_certificate_arn` to just `certificate_arn` and received the same error.

```txt
aws_api_gateway_domain_name.staging: Error creating API Gateway Domain Name: BadRequestException: Invalid certificate ARN: arn:aws:iam::471442147469:server-certificate/cloudfront/staging/staging. Vendor should be 'acm'.
	status code: 400, request id: e70ccac8-f36d-11e8-8462-0957470e402e
```

What's confusing is that the [docs state](https://www.terraform.io/docs/providers/aws/r/api_gateway_domain_name.html#certificate_name): "The unique name to use when registering this certificate as an IAM server certificate. Conflicts with certificate_arn, regional_certificate_arn, and regional_certificate_name. Required if certificate_arn is not set." That leads me to believe I should be able to use an existing IAM server certificate.

So not sure if this is an issue with the docs, an issue with the implementation in this provider, or just me doing something wrong.

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @austinbutler 👋 Sorry for any confusion. 

API Gateway only supports referencing AWS Certificate Manager certificate ARNs, not IAM server certificates, in this manner. Here is the [API Gateway API Reference](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/domainname-create/), which states:
> **regionalCertificateArn**
> The reference to an AWS-managed certificate that will be used by regional endpoint for this domain name. AWS Certificate Manager is the only supported source.

In your situation, I believe you'll just want to upload the certificate directly, e.g.

```hcl
resource "aws_api_gateway_domain_name" "example" {
  certificate_body          = "${file("staging/cert-public.pem")}"
  certificate_chain         = "${file("staging/cert-chain.pem")}"
  certificate_private_key   = "${file("staging/cert-private.secret.pem")}"
  domain_name               = "staging.api.example.com"
  regional_certificate_name = "staging"

  endpoint_configuration {
    type = "REGIONAL"
  }
}
```

To make our documentation better with regards to referencing ACM certificates versus uploaded certificate usage, I have submitted #6678 to clarify the examples and arguments as well as add the missing `AWS Certificate Manager is the only supported source.` sentence in the `certificate_arn` and `regional_certificate_arn` arguments.

Hope this helps!

**Comment by austinbutler** [comment]
Thanks you! The only part I am still a little unclear on is how if you upload a certificate within `aws_api_gateway_domain_name`, according to the Terraform docs (before and after this PR) it will be registered as an "an IAM server certificate". Perhaps that's just inconsistency on AWS' part, but at least with your PR I think it's more clear what the limitations are.
