### ISSUE TITLE
Support EC2 Hibernate Options 

### ISSUE THREAD

**Issue by plombardi89** [terraform-providers/terraform-provider-aws#6638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The ability to Hibernate On-Demand EC2 instances was released today: https://aws.amazon.com/blogs/aws/new-hibernate-your-ec2-instances/

It would be nice to enable this feature through Terraform created instances. It can only be done when an instance is created: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Hibernate.html#enabling-hibernation

### New or Affected Resource(s)

* aws_instance
* maybe launch configurations?

**Comment by jalessio** [comment]
Potentially related announcement from AWS:
https://aws.amazon.com/about-aws/whats-new/2019/05/enable-ec2-hibernation-without-specifying-encryption-intent/

> Hibernating your Amazon EC2 Instances is now easier then ever. You can now enable Amazon Elastic Block Store (EBS) Encryption by Default, to ensure all new EBS volumes created in your account are encrypted. To enable Hibernation, you no longer have to create an encrypted copy of the Amazon Machine Image (AMI) before launching an instance. Alternatively, you can also now specify encryption intent at launch (with unencrypted AMI or snapshot) and enable hibernation at the same time (see [link](https://aws.amazon.com/about-aws/whats-new/2019/05/enable-hibernation-on-ec2-instances-when-launching-with-an-ami-without-an-encrypted-ebs-snapshot/)).

**Comment by agassner** [comment]
I'd add launch template as affected resources too.

**Comment by bflad** [comment]
Support for `hibernation_options` in the `aws_launch_template` resource and data source has been merged and will release with version 2.56.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for finishing this up. 👍
