### ISSUE TITLE
aws_codepipeline should not require oauth token for public repos

### ISSUE THREAD

**Issue by stephenlawrence** [terraform-providers/terraform-provider-aws#6646]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a user, I would like to utilize the GitHub source in my pipeline "Build" stage for my public repository without having to create and specify the github oauth token value since tokens are generally used for private repositories and it would also move this module into parity with the aws_codebuild module which does not require a token to create a build project.

### New or Affected Resource(s)

* aws_codepipeline

### Potential Terraform Configuration

```hcl
configuration {
        OAuthToken           = ""
}
```

**Comment by bflad** [comment]
Related: #2796

**Comment by bflad** [comment]
Hi folks 👋 The requirement for an OAuth token with GitHub sources in CodePipeline comes from the service itself. e.g. when completely omitted, the CodePipeline API returns this error:

```
InvalidActionDeclarationException: Action configuration for action 'Source' is missing required configuration 'OAuthToken'
```

In this case, I do not believe there is anything we can do in Terraform to workaround this API requirement. Please reach out to AWS via a Support Case or talk your AWS account managers if you would like to submit a feature request to potentially have the requirement removed.
