### ISSUE TITLE
Please add support for import for iam_user_group_membership

### ISSUE THREAD

**Issue by rwolfson** [terraform-providers/terraform-provider-aws#6698]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `iam_user_group_membership` AWS resource does not currently support import. It would be great if it could be added, to help facilitate converting a live IAM environment to Terraform without disruption.

### New or Affected Resource(s)

* `aws_iam_user_group_membership`

### Potential Terraform Configuration

N/A

### References

* https://www.terraform.io/docs/providers/aws/r/iam_user_group_membership.html

**Comment by goforgold** [comment]
+1

**Comment by bflad** [comment]
Support for importing `aws_iam_user_group_membership` resources has been merged and will be released with version 2.6.0 of the Terraform AWS Provider, later this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
