### ISSUE TITLE
ECS managed tags are not applied in AWS 

### ISSUE THREAD

**Issue by buuren** [terraform-providers/terraform-provider-aws#6700]
### Terraform Version

```# > terraform -v
Terraform v0.11.10
+ provider.aws v1.50.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "service" {
  name                               = "${var.project}-${var.service["APPLICATION_TYPE"]}"
  cluster                            = "${data.terraform_remote_state.idms-services.ecs_cluster_arn}"
  task_definition                    = "${aws_ecs_task_definition.task_definition.family}:${max("${aws_ecs_task_definition.task_definition.revision}", "${data.aws_ecs_task_definition.task_definition.revision}")}"
  desired_count                      = "${var.desired_count}"
  deployment_minimum_healthy_percent = 50
  deployment_maximum_percent         = 200
  enable_ecs_managed_tags            = true

  ordered_placement_strategy {
    type  = "binpack"
    field = "cpu"
  }

  tags {
    Name        = "${var.project}-ecs-${var.environment}"
    role        = "${var.service["APPLICATION_TYPE"]}"
    project     = "${var.project}"
    owner       = "${var.owner}"
    department  = "${var.department}"
    environment = "${var.environment}"
    sla         = "${var.sla}"
    created     = "${var.created}"
  }
}
```

### Debug Output

``` aws_ecs_service.service
      enable_ecs_managed_tags: "false" => "true"
```
### Actual Behavior

enable_ecs_managed_tags does not  change to true

### Steps to Reproduce

Recently AWS added posibility to modify ECS resource tags. 

Feature request: https://github.com/terraform-providers/terraform-provider-aws/issues/6542
Commit: https://github.com/terraform-providers/terraform-provider-aws/pull/6544/commits
Changelog: https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1470-november-26-2018

It seems like it does not properly set the enable_ecs_managed_tags attribute

1. create terraform template to create "aws_ecs_service" resource
2. specify that you want to enable ecs managed tags by using "enable_ecs_managed_tags            = true"
3. run terraform apply
4. You cant see that option in UI, but you can run terraform apply again and will notice that terraform wants to change this value again, which means it was not properly added in the first terraform apply

**Comment by tomelliff** [comment]
Have you enabled the longer ECS ARNs for the IAM role/user you are running this under? ECS tags require this to be enabled for it to work for some reason as mentioned in [the docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html):

> Important
>
> To use this feature, it requires that you opt-in to the new Amazon Resource Name (ARN) and resource identifier (ID) formats. For more information, see Amazon Resource Names (ARNs) and IDs.

**Comment by buuren** [comment]
Hello @tomelliff.

I have opted-in for new ECS ARN's globally via root account a while back already. I'm sure that's not that the problem because otherwise terraform would throw an error that this particular option requires some changes on aws account side.

In my case, both plan and apply finishes successfully, but when when you view ecs_service metadata via amazon api, the necessary option remains intact.

**Comment by buuren** [comment]
Upon further experimentation the culprit was hiding in another configuration option called **propagate_tags** which apparently must be used in combination with  **enable_ecs_managed_tags** for the latter to be applied correctly.

I will close this report.
