### ISSUE TITLE
placement_group not being used in resource_aws_spot_fleet_request.go

### ISSUE THREAD

**Issue by sowmitranalla** [terraform-providers/terraform-provider-aws#6713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.50.0
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

* the launch specification in aws_spot_fleet_request. referenced in [resource_aws_spot_fleet_request.go](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_spot_fleet_request.go#L221) 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I would expect, by placing a placement_group name in the launch specification, the instances in the spot fleet get placed into a placement group. 

### Actual Behavior

placement_group setting isn't set at all, basically ignore. I also don't see `placement_group` being used at all in the provider. 

### Steps to Reproduce

launch specification: 
```
launch_specification {
    ami                      = "${var.ecs_instance_ami}"
    instance_type            = "${var.spot_fleet_instance_type2}"
    iam_instance_profile_arn = "${var.iam_instance_profile_arn}"
    key_name                 = "${var.key_name}"
    user_data                = "${var.user_data}"
    subnet_id                = "${element(var.subnet_ids, 0)}"
    vpc_security_group_ids   = ["${var.security_groups}"]
    placement_group          = "${var.placement_group_name}"

    tags {
      Name            = "${var.asg_name}"
      Environment     = "${var.environment}"
      ...
      RetentionPeriod = "14"
    }
  }
```

### References

* #0000

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.30.0 of the Terraform AWS Provider, later this week.
