### ISSUE TITLE
resource/aws_ssm_maintenance_window_task: Name/Description validation errors

### ISSUE THREAD

**Issue by thrinadh238** [terraform-providers/terraform-provider-aws#6715]
I am using 0.10.8 version of terraform. we created SSM maintenance window with this version a while ago. I tried running same code before 2 days but i got error, please find the error below. I find provider.aws version has been upgraded.we used to use version 1.48 but now it was upgraded to 1.50. we tried degrading version to 1.48 and it worked. Please advise us on this issue. Is it a bug of new version???

 module.ssm.aws_ssm_maintenance_window_task.task_install_patches: 1 error(s) occurred:

* aws_ssm_maintenance_window_task.task_install_patches: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTaskWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTaskWithMaintenanceWindowInput.Name.

**Comment by thrinadh238** [comment]
Hi Team,
Is there any update on above issue.

**Comment by tomelliff** [comment]
It doesn't look like there have been any changes to this resource since the `name` and `description` fields were added back in `1.44.0`: https://github.com/terraform-providers/terraform-provider-aws/commits/master/aws/resource_aws_ssm_maintenance_window_task.go

Can you share the Terraform code you've written that causes this issue? Is it happening on the plan or the apply?

**Comment by thrinadh238** [comment]
Do you mean that the name and description became mandatory fields, or are they still optional?

This is what we have in the module regarding scan and install tasks. 

The Plan does not fail, apply fails and throws when provider is 1.50, but not 1.48


    minimum field size of 1, RegisterTaskWithMaintenanceWindowInput.Description.
    minimum field size of 3, RegisterTaskWithMaintenanceWindowInput.Name.

------
resource "aws_ssm_maintenance_window_task" "task_scan_patches" {
  window_id        = "${aws_ssm_maintenance_window.scan_window.id}"
  task_type        = "RUN_COMMAND"
  task_arn         = "AWS-ApplyPatchBaseline"
  priority         = 1
  service_role_arn = "${aws_iam_role.ssm_mw_role.arn}"
  max_concurrency  = "${var.max_concurrency}"
  max_errors       = "${var.max_errors}"

  targets {
    key    = "WindowTargetIds"
    values = ["${aws_ssm_maintenance_window_target.target_scan.*.id}"]
  }

  task_parameters {
    name   = "Operation"
    values = ["Scan"]
  }

  logging_info {
    s3_bucket_name = "${aws_s3_bucket.ssm_patch_log_bucket.id}"
    s3_region      = "${var.region}"
  }
}

----

AND

------
resource "aws_ssm_maintenance_window_task" "task_install_patches" {
  window_id        = "${aws_ssm_maintenance_window.install_window.id}"
  task_type        = "RUN_COMMAND"
  task_arn         = "AWS-ApplyPatchBaseline"
  priority         = 1
  service_role_arn = "${aws_iam_role.ssm_mw_role.arn}"
  max_concurrency  = "${var.max_concurrency}"
  max_errors       = "${var.max_errors}"

  targets {
    key    = "WindowTargetIds"
    values = ["${aws_ssm_maintenance_window_target.target_install.*.id}"]
  }

  task_parameters {
    name   = "Operation"
    values = ["Install"]
  }

  logging_info {
    s3_bucket_name = "${aws_s3_bucket.ssm_patch_log_bucket.id}"
    s3_region      = "${var.region}"
  }
}
----

**Comment by tomelliff** [comment]
Any chance you can either add the other resources and variable definitions mentioned or remove the references to them if not required? Doing that makes it much easier for others to be able to run a complete but minimal test case.

**Comment by Dkochkerian** [comment]
We will try to create a tf file with no/minimal dependancies and post it here tomorrow.

**Comment by thrinadh238** [comment]
Please find the terraform code below which we are using to create SSM maintenance window task

We are using modules to create the resources. Please find the module attached below.

module "ssm" {
  source  = /.module/
  region  = "${var.region}"
  appname = "${var.appname}"
}
-------

Please find the error below

 module.ssm.aws_ssm_maintenance_window_task.task_scan_patches: 1 error(s) occurred:

* aws_ssm_maintenance_window_task.task_scan_patches: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTaskWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTaskWithMaintenanceWindowInput.Name.

* module.ssm.aws_ssm_maintenance_window_task.task_install_patches: 1 error(s) occurred:

* aws_ssm_maintenance_window_task.task_install_patches: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTaskWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTaskWithMaintenanceWindowInput.Name.

* module.ssm.aws_ssm_patch_group.scan_patchgroup[0]: 1 error(s) occurred:



[module.zip](https://github.com/terraform-providers/terraform-provider-aws/files/2674073/module.zip)

**Comment by YakDriver** [comment]
@thrinadh238 @tomelliff @Dkochkerian @lorengordon @userhas404d Please see/👍 #7186 which fixes this bug.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 1.59.0 of the Terraform AWS Provider, in the next hour or so.

**Comment by bflad** [comment]
This has been released in [version 1.59.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1590-february-14-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by Dkochkerian** [comment]
Looks like the issue returned in version 2.15
Can you please check?

* module.ssm.aws_ssm_maintenance_window_target.target_scan[0]: 1 error(s) occurred:

* aws_ssm_maintenance_window_target.target_scan.0: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTargetWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTargetWithMaintenanceWindowInput.Name.

* module.ssm.aws_ssm_maintenance_window_target.target_scan[1]: 1 error(s) occurred:

* aws_ssm_maintenance_window_target.target_scan.1: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTargetWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTargetWithMaintenanceWindowInput.Name.

* module.ssm.aws_ssm_maintenance_window_target.target_install: 1 error(s) occurred:

* aws_ssm_maintenance_window_target.target_install: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTargetWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTargetWithMaintenanceWindowInput.Name.

* module.ssm_inspector.aws_ssm_maintenance_window_target.target_install: 1 error(s) occurred:

* aws_ssm_maintenance_window_target.target_install: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTargetWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTargetWithMaintenanceWindowInput.Name.

**Comment by Dkochkerian** [comment]
Just checked on my end, works with aws provider 2.11.0, but breaks starting 2.12.0. 
Please verify and fix.

**Comment by Dkochkerian** [comment]
Looks like this issue is back. 

Just checked on my end, works with aws provider 2.11.0, but breaks starting 2.12.0.
Please verify and fix.

**Comment by bflad** [comment]
Hi @Dkochkerian 👋 This issue was for the `aws_ssm_maintenance_window_task` resource while your output is showing the `aws_ssm_maintenance_window_target` resource. My suggestion would be to follow #8791, which seems relevant to your issue.
