### ISSUE TITLE
Feature request: S3 Inventory Apache Parquet format reports

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6728]
[Recently announced](https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-s3-announces-parquet-output-format-for-inventory/) support for Apache Parquet output format for S3 Inventory reports.
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6722

**Comment by bflad** [comment]
Support for this has been merged in and will release with version 1.51.0 of the AWS provider, likely later today. 👍

**Comment by bflad** [comment]
This has been released in [version 1.51.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1510-december-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
