### ISSUE TITLE
DynamoDB On-Demand doesn't work with GSIs

### ISSUE THREAD

**Issue by sbogacz** [terraform-providers/terraform-provider-aws#6736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.51.0
```

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "lvs" {
  name = "lvs-${var.environment}"
  tags = "${var.tags}"

  hash_key  = "Account"
  range_key = "SortKey"

  billing_mode = "PAY_PER_REQUEST"

  # Streams have to be enabled for DynamoDB global table
  # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_reqs_bestpractices.html
  stream_enabled = true

  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "Account"
    type = "S"
  }

  attribute {
    name = "SortKey"
    type = "S"
  }

  attribute {
    name = "AccountOffering"
    type = "S"
  }

  attribute {
    name = "CancelStatus"
    type = "S"
  }

  global_secondary_index {
    name            = "GSI"
    hash_key        = "CancelStatus"
    range_key       = "AccountOffering"
    projection_type = "KEYS_ONLY"
  }
}
```

### Expected Behavior

I expected to be able to create a DynamoDB table with the new PAY_PER_REQUEST billing option set, and use the table with GSIs.

### Actual Behavior

I tried to not specify the read and write capacity units for my GSIs, but that led to the following error at the plan phase, since the schema marks the provisioned throughput arguments as required:

```
Error: module.lvs.module.lvs_table_region1.aws_dynamodb_table.lvs: "global_secondary_index.0.read_capacity": required field is not set
```

When I tried to specify a dummy value, it fails the call to the AWS DynamoDB API:

```
* module.lvs.module.lvs_table_region3.aws_dynamodb_table.lvs: 1 error(s) occurred:

* aws_dynamodb_table.lvs: ValidationException: One or more parameter values were invalid: ProvisionedThroughput should not be specified for index: GSI when BillingMode is PAY_PER_REQUEST
	status code: 400, request id: 1IVRLJOG48QHPG3FO4UAJUV347VV4KQNSO5AEMVJF66Q9ASUAAJG
```

### Steps to Reproduce

With no capacity specified in the GSI it fails at plan time.

With dummy capacity values specified it fails at apply time.

**Comment by LiborVilimekMassive** [comment]
Confirming the same issue

**Comment by AntonBazhal** [comment]
@bflad I don't understand why this issue is not labelled as a bug and not prioritized accordingly. It essentially makes `billing_mode` feature impossible to use.

**Comment by Hinidu** [comment]
There is a workaround for this issue: https://github.com/terraform-providers/terraform-provider-aws/issues/6632#issuecomment-445323845
I've just tried it and looks like it works.

**Comment by Hinidu** [comment]
There is a workaround for this issue: https://github.com/terraform-providers/terraform-provider-aws/issues/6632#issuecomment-445323845

**Comment by macbutch** [comment]
The workaround does not appear to always work. Our integration tests spin up a new stack on each run and they always fail to create the table. We will be stuck with provisioned capacity for now (at least for our integration tests).

**Comment by sbogacz** [comment]
@macbutch the workaround would only work on successive applies I think. The PR I opened above (#6737 ) should fix the issue.

**Comment by LiborVilimekMassive** [comment]
@macbutch - yea, I use workaround around that workaround :) - first created table and indexes with provisioned capacity, then run again with changed it to on-demand and set the 0 as read/write capacity.

Then terraform throw few errors, but it works and table and indexes are on-demand.

**Comment by donglaizhang** [comment]
> There is a workaround for this issue: [#6632 (comment)](https://github.com/terraform-providers/terraform-provider-aws/issues/6632#issuecomment-445323845)

This solution works for me, set read/write capacity to "0" in GIS when applied 'pay_per_request'.

Thanks.

**Comment by bflad** [comment]
Support for on-demand billing with global secondary indices has been merged and will release with version 1.52.0 of the AWS provider, likely later today. 👍

**Comment by bflad** [comment]
This has been released in [version 1.52.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by brikis98** [comment]
Just hit this issue with version 1.52.0 of the AWS provider. Code:

```hcl
resource "aws_dynamodb_table" "foo" {
  name         = "foo"
  billing_mode = "PAY_PER_REQUEST"

  hash_key = "id"

  "attribute" {
    name = "id"
    type = "S"
  }

  attribute {
    name = "userName"
    type = "S"
  }

  global_secondary_index {
    name               = "UserNameGlobalIndex"
    hash_key           = "userName"
    projection_type    = "ALL"
  }
}
```

Log output:

```
$ terraform apply

...

* provider.aws: version = "~> 1.52"

...

Error: Error applying plan:

1 error(s) occurred:

* aws_dynamodb_table.foo: 1 error(s) occurred:

* aws_dynamodb_table.foo: InvalidParameter: 1 validation error(s) found.
- missing required field, UpdateTableInput.GlobalSecondaryIndexUpdates[0].Update.ProvisionedThroughput.
```

One wrinkle in our use case: our DynamoDB table was already created with `billing_mode` set to `PROVISIONED` and we updated it to `PAY_PER_REQUEST`, removing the `read_capacity` and `write_capacity` settings everywhere. Not sure if that triggers a different code path / bug?

**Comment by brikis98** [comment]
Note that the workaround in https://github.com/terraform-providers/terraform-provider-aws/issues/6632#issuecomment-445323845 (setting read and write capacity to 0 in GIS) solved it in our situation too.

**Comment by LiborVilimekMassive** [comment]
@brikis98 - have you tried to run it twice? Had similar problem, but it disappeared next time I run it.

I suppose it was just because it was still PROVISIONED when these fields missing as changing to on-demand takes a while (still the Terraform should know what to do in such case)
