### ISSUE TITLE
Feature request: Support AWS Global Accelerator

### ISSUE THREAD

**Issue by Alberts00** [terraform-providers/terraform-provider-aws#6739]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During Re:Invent 2018 [AWS Global Accelerator](https://aws.amazon.com/global-accelerator/) was announced. This feature request is for implementing resources for it in Terraform AWS provider.

### New or Affected Resource(s)

* [aws_accelerator](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateAccelerator.html) - Creates global accelerator
* [aws_accelerator_endpoint_configuration](https://docs.aws.amazon.com/global-accelerator/latest/api/API_EndpointConfiguration.html) -  Included in aws_accelerator_endpoint_group to workaround inability to include dynamic blocks in Terraform.
* [aws_accelerator_endpoint_group](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateEndpointGroup.html) -  An endpoint group which maps to listener from aws_accelerator_listener
* [aws_accelerator_listener](https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateListener.html) - A listener which maps to aws_accelerator

### Question about dynamic blocks
Let me know what are the AWS provider guidelines regarding working around Terraform dynamic blocks. Since the new Terraform release is just around the corner, do you think it makes sense to create the aws_accelerator_endpoint_configuration meta-resource (does not directly map to AWS API)?

### References

* [Global Accelerator API documentation](https://docs.aws.amazon.com/global-accelerator/latest/api/API_Operations.html)

**Comment by bflad** [comment]
The first resource for managing the accelerator itself, `aws_globalaccelerator_accelerator`, has been merged and will release with version 1.56.0 of the Terraform AWS provider, likely in the next day or two. 👍

**Comment by bflad** [comment]
The new `aws_globalaccelerator_accelerator` resource has been released in [version 1.56.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1560-january-16-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by bflad** [comment]
The `aws_globalaccelerator_listener` resource has been merged and will release with version 2.2.0 of the Terraform AWS Provider, shortly.

**Comment by bflad** [comment]
The `aws_globalaccelerator_listener` resource has been released in [version 2.2.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#220-march-15-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by bflad** [comment]
Hi folks 👋 Since general "Support AWS Service X" issues tend to become a collect-all for random feature requests and bug reports, I'm going to close this issue out just to prevent that problem now. There is already a new separate issue to support managing Global Accelerator Endpoint Groups via a new `aws_globalaccelerator_endpoint_group` resource, which can be upvoted and tracked here: https://github.com/terraform-providers/terraform-provider-aws/issues/7965

For other Global Accelerator feature requests and bug reports, please file new GitHub issue(s). Thanks! 👍
