### ISSUE TITLE
Feature request: Amazon MQ tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6740]
Amazon MQ resource tagging [announced](https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-mq-now-supports-resource-tagging/).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6734

**Comment by bflad** [comment]
Support for tags with the MQ service has been merged and will release with version 1.57.0 of the Terraform AWS provider, likely very shortly.
