### ISSUE TITLE
Deletion of cloudwatch log subscription filter fails

### ISSUE THREAD

**Issue by Puneeth-n** [terraform-providers/terraform-provider-aws#6759]
Deletion of cloudwatch log subscription filter fails if cloudwatch log group has been already deleted. This can happen when there is a race condition between deleting cloudwatch log group and cloudwatch log subscription filter.

When a cloudwatch log group is deleted, it also deletes the subscription filter.

```hcl
resource "aws_cloudwatch_log_group" "lambda_log_group" {
  name              = "/aws/lambda/foo"
  retention_in_days = 90
}

resource "aws_cloudwatch_log_subscription_filter" "lambda_cloudwatch_subscription" {
  name            = "foo"
  log_group_name  = "/aws/lambda/foo"
  filter_pattern  = ""
  destination_arn = "some_arn"
}
```

**Comment by bflad** [comment]
This has been released in [version 1.52.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
