### ISSUE TITLE
aws_canonical_user_id display_name returns empty string in some regions

### ISSUE THREAD

**Issue by johnctitus** [terraform-providers/terraform-provider-aws#6762]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.11.10
+ provider.aws v1.51.0
```

Also tested on Terraform v0.11.8 with same results.

### Affected Resource(s)

- `aws_canonical_user_id`

### Terraform Configuration Files

```hcl
variable "region" {}

provider "aws" {
  version = "~> 1.2"
  region  = "${var.region}"
}

data "aws_canonical_user_id" "current" {}

output "aws_canonical_user_id"{
  value = "${data.aws_canonical_user_id.current.display_name}"
}

output "region"{
  value = "${var.region}"
}
```

### Expected Behavior

Output for `aws_canonical_user_id` should have a result similar to the following from one of the affected regions

```
Outputs:

aws_canonical_user_id = my_actual_canonical_display_name
region = us-east-2
```

### Actual Behavior
Output for `aws_canonical_user_id` returns an empty string from one of the affected regions

```
Outputs:

aws_canonical_user_id =
region = us-east-2
```

### Steps to Reproduce

Deploy the sample code using one of the following commands:

-  `terraform apply -var 'region=ap-northeast-2' `
-  `terraform apply -var 'region=ap-south-1' `
-  `terraform apply -var 'region=ca-central-1' `
-  `terraform apply -var 'region=eu-central-1' `
-  `terraform apply -var 'region=eu-west-2' `
-  `terraform apply -var 'region=us-east-2' `

### References

* None found

**Comment by bflad** [comment]
Looks like we need to include a note in the Terraform documentation: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTServiceGET.html

> ** DisplayName**
>
> Bucket owner's display name.
>
> **Important**
> This value is only included in the response in the US East (N. Virginia), US West (N. California), US West (Oregon), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), EU (Ireland), and South America (São Paulo) regions.
