### ISSUE TITLE
Add support for Policy Documents for ECR Lifecycle Policies

### ISSUE THREAD

**Issue by Ray-B** [terraform-providers/terraform-provider-aws#6765]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would be good to allow ECR lifecycle policies to make use of IAM policy document data blocks. 

This would allow for policies to be validated (fail as early as possible), rather than having to wait until an apply to see if they are valid, etc.

Perhaps an iam policy document isn't the best resource? Do we need a different one?

### New or Affected Resource(s)
Data aws_iam_policy_document
Resource aws_ecr_lifecycle_policy

### Potential Terraform Configuration

Example:
```hcl
resource "aws_ecr_lifecycle_policy" "neato-lifecycle-policy" {
  repository = "${aws_ecr_repository.neato-repository.name}"

  policy = "${data.aws_iam_policy_document.neato-repository-lifecycle-policy-doc.json}"
}

data "aws_iam_policy_document" "neato-repository-lifecycle-policy-doc" {
  rules = [
    {
      rulePriority = 10
      description  = "Keep last 25 master images"

      selection = {
        tagStatus     = "tagged"
        tagPrefixList = ["m-"]
        countType     = "imageCountMoreThan"
        countNumber   = 50
      }

      action = {
        type = "expire"
      }
    },
  ]
}
```

**Comment by bflad** [comment]
Likely relevant 😉 https://github.com/terraform-providers/terraform-provider-aws/pull/6133

**Comment by Ray-B** [comment]
yep, looks like a duplicate. Closing
