### ISSUE TITLE
aws_autoscaling_group diffs didn't match during apply, target_group_arns.# mismatch

### ISSUE THREAD

**Issue by vivan-niche** [terraform-providers/terraform-provider-aws#6768]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform v11.10
provider.aws v1.51.0

### Affected Resource(s)

* `aws_autoscaling_group`
* specifically, the attribute `target_group_arns`

### Terraform Configuration Files

```hcl
resource "aws_lb_target_group" "service_api_tg" {
  count      = "${var.api_accessible ? 1 : 0}"
  name       = "${var.service_name}-nlb-tg"
  port       = "${var.port}"
  stickiness = []                              #workaround for default that does not apply to NLB target groups

  protocol = "TCP"
  vpc_id   = "${var.vpc_id}"
}

resource "aws_lb_listener" "backend_api_listener" {
  load_balancer_arn = "${var.nlb_arn}"
  port              = "${var.port}"
  count             = "${var.api_accessible ? 1 : 0}"
  protocol          = "TCP"

  default_action {
    type             = "forward"
    target_group_arn = "${join("",aws_lb_target_group.service_api_tg.*.arn)}"
  }
}

resource "aws_autoscaling_group" "service_asg" {
  lifecycle {
    create_before_destroy = true
  }

  depends_on           = ["aws_lb_listener.backend_api_listener", "aws_lb_target_group.service_api_tg"]
  name                 = "${aws_launch_configuration.service_lc.name}"
  launch_configuration = "${aws_launch_configuration.service_lc.name}"
  desired_capacity     = "${var.min_nodes}"
  min_size             = "${var.min_nodes}"
  max_size             = "${var.max_nodes}"
  min_elb_capacity     = "${var.min_nodes}"

  vpc_zone_identifier = ["${split(",", var.private_subnet_ids)}"]

  # load_balancers       = ["${var.elb_id}"]

  target_group_arns = ["${compact(list("${aws_alb_target_group.service_tg.arn}","${join("",aws_lb_target_group.service_api_tg.*.arn)}"))}"]
  health_check_grace_period = 600
  health_check_type         = "ELB"
  termination_policies      = ["OldestInstance"]
  tag {
    key                 = "Name"
    value               = "${var.name}"
    propagate_at_launch = true
  }
  tag {
    key                 = "Department"
    value               = "${var.tag_department}"
    propagate_at_launch = true
  }
  tag {
    key                 = "Lifecycle"
    value               = "${var.tag_lifecycle}"
    propagate_at_launch = true
  }
  tag {
    key                 = "Account"
    value               = "${var.tag_account}"
    propagate_at_launch = true
  }
  tag {
    key                 = "Application"
    value               = "${var.tag_application}"
    propagate_at_launch = true
  }
  tag {
    key                 = "db_type"
    value               = "${var.tag_db_type}"
    propagate_at_launch = true
  }
}
```

### Debug Output

https://gist.github.com/vivan-niche/3106cefd94a81d093b92c21ecf3d2848

### Panic Output
N/A

### Expected Behavior
After spinning up an environment successfully with `var.api_accessible` set to `true`, the `backend_api_listener`, `backend_api_listener` are both created successfully, and the `target_group_arns` list on the `aws_autoscaling_group` correctly has two target groups.  

When running an apply with `var.api_accessible` set to false, I would expect the first two resources to not be created, and the `target_group_arns` list to just have the first entry.  This is what I see reflected when I do `terraform plan`, and before the confirmation step in an `apply`.  I would expect `terraform apply` to correctly apply these changes.

### Actual Behavior
After spinning up an environment successfully with `var.api_accessible` set to `true`, the `backend_api_listener`, `backend_api_listener` are both created successfully, and the `target_group_arns` list on the `aws_autoscaling_group` correctly has two target groups.  

When running an apply with `var.api_accessible` set to false, I would expect the first two resources to not be created, and the `target_group_arns` list to just have the first entry.  `terraform apply` produces the expected changes before the confirmation step, however proceeding produces the error output in the gist above, and the autoscaling group's target groups are not modified.  

Running `terraform apply` a second time produces the same correct diff before the confirmation step, and proceeding with the apply works successfully.  

### Steps to Reproduce

1. run `terraform apply` with `var.api_accessible=true`
2. run `terraform apply` with `var.api_accessible=false`
2. run `terraform apply` with `var.api_accessible=false` a second time

### References
There are several other github issues in both the `terraform` and `terraform-aws-provider` repos with a very similar error with `aws_autoscaling_group` and "diffs didn't match", but they are all related to the use of availability zones as well as vpc zones, which doesn't apply to my situation.  For all of those reports, the "mismatch reason" points to `availability_zones` while mine points to `target_group_arns.#`

**Comment by aeschright** [comment]
Hi @vivan-niche , unfortunately on Terraform pre-0.12 it's hard to debug this kind of error because the logs don't give us much. If you update to the newest Terraform and AWS provider releases and you're still seeing this, we'd like you to open a new bug report so we can look into it. Make sure to include the requested details. Thanks so much for taking the time to report this problem!
