### ISSUE TITLE
Terraform throws error when deleting lambda permission after lambda function has been deleted

### ISSUE THREAD

**Issue by Puneeth-n** [terraform-providers/terraform-provider-aws#6769]
Terraform throws an error when there is a race condition between deleting lambda function and deleting lambda permission and it tries to delete a lambda permission after the lambda function has been already deleted.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 1.52.0 of the AWS provider, later this week.

**Comment by bflad** [comment]
This has been released in [version 1.52.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
