### ISSUE TITLE
aws_launch_template network interfaces associate_public_ip_address default should not be set

### ISSUE THREAD

**Issue by stanb** [terraform-providers/terraform-provider-aws#6777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.10
+ provider.aws v1.51.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

```hcl
variable "sandbox_id" {}
variable "owner" {}
variable "key_name" {}

provider "aws" {
  region = "eu-west-1"
}

data "aws_availability_zones" "available" {}

locals {
  timestamp =  "${timestamp()}"  
}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
  tags = {
    Name = "${var.sandbox_id}-vpc"
    Owner = "${var.owner}"
  }
}

resource "aws_subnet" "public-subnet1" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.0.0.0/24"
  map_public_ip_on_launch = true
  availability_zone = "${data.aws_availability_zones.available.names[0]}"
  tags = {
    Name = "${var.sandbox_id}-public-subnet1"
    Owner = "${var.owner}"
  }
}

resource "aws_subnet" "public-subnet2" {
  vpc_id = "${aws_vpc.vpc.id}"
  cidr_block = "10.0.1.0/24"
  map_public_ip_on_launch = true
  availability_zone = "${data.aws_availability_zones.available.names[1]}"
  tags = {
    Name = "${var.sandbox_id}-public-subnet2"
    Owner = "${var.owner}"
  }
}

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.vpc.id}"
  tags = {
    Name = "${var.sandbox_id}-public-igw"
    Owner = "${var.owner}"
  }
}

resource "aws_route_table" "route_table" {
  vpc_id = "${aws_vpc.vpc.id}"
  route = {
    gateway_id = "${aws_internet_gateway.igw.id}"
    cidr_block = "0.0.0.0/0"
  }
  tags = {
    Name = "${var.sandbox_id}-rt"
    Owner = "${var.owner}"
  }
}

resource "aws_route_table_association" "rta_subnet1" {
  route_table_id = "${aws_route_table.route_table.id}"
  subnet_id = "${aws_subnet.public-subnet1.id}"
}

resource "aws_route_table_association" "rta_subnet2" {
  route_table_id = "${aws_route_table.route_table.id}"
  subnet_id = "${aws_subnet.public-subnet2.id}"
}

resource "aws_security_group" "sg_ssh" {
  name = "ssh_sg"
  description = "Enable SSH access via port 22"
  vpc_id = "${aws_vpc.vpc.id}"

  ingress {
    protocol = "tcp"
    from_port = 22
    to_port = 22
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    protocol = "-1"
    from_port = 0
    to_port = 0
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags = {
    Name = "${var.sandbox_id}-ssh-sg"
    Owner = "${var.owner}"
  }
}

resource "aws_network_interface" "nic" {
  subnet_id = "${aws_subnet.public-subnet1.id}"
  security_groups = ["${aws_security_group.sg_ssh.id}"]
}

resource "aws_eip" "eip" {
  vpc = true
  network_interface = "${aws_network_interface.nic.id}"
}

resource "aws_launch_template" "launch_template" {
  name     = "${var.sandbox_id}-lt"
  key_name = "${var.key_name}"
  image_id = "ami-0773391ae604c49a4"
  
  instance_market_options {
    spot_options {
      spot_instance_type = "persistent"
    }
    market_type="spot"
  }
  
  network_interfaces {
    device_index = 0
    network_interface_id = "${aws_network_interface.nic.id}"
  }
  network_interfaces {
    device_index = 1
    subnet_id = "${aws_subnet.public-subnet1.id}"
  }
  
  # user_data = "${base64encode()}"
  
  tag_specifications {
    resource_type = "instance"
    tags {
      Name = "${var.sandbox_id}-instance"
      Owner = "${var.owner}"
    }
  }
}

resource "aws_ec2_fleet" "fleet" {
  launch_template_config {
    launch_template_specification {
      launch_template_id = "${aws_launch_template.launch_template.id}"
      version            = "${aws_launch_template.launch_template.latest_version}"
    }
    # allow to choose from several instance types if there is no spot capacity for some type
    override {
      instance_type = "t2.micro"
    }
    override {
      instance_type = "t3.micro"
    }
    override {
      instance_type = "t3.small"
    }
  }

  target_capacity_specification {
    default_target_capacity_type = "spot"
    total_target_capacity = 1
  }
}

output "instance_public_ip" {
  value = "${aws_eip.eip.public_ip}"
}

output "describe_fleet_history" {
  value = "aws ec2 describe-fleet-history --fleet-id ${aws_ec2_fleet.fleet.id} --start-time "
}
```

### Debug Output

https://gist.github.com/stanb/d2a7bf361727b224d9be497554b576b7#file-debug-log
### Expected Behavior

Launch template created with two network interfaces definitions: 
device 0 - attached to predefined network interface;
device 1 - attached to subnet
Both network interfaces **should not** have Auto-assign public IP set at all.
When EC2 fleet created it should succeed to launch instance from this launch template.

### Actual Behavior

Launch template created with two network interfaces but device 1 nic have Auto-assign public IP set to false.
When EC2 spot fleet starts it fails to launch instance with following error:
The associatePublicIPAddress parameter cannot be specified when launching with multiple network interfaces

### Steps to Reproduce

1. `terraform apply -var "sandbox_id=test1" -var "owner=<_owner_>" -var "key_name=<_key-name_>"`
key-name is a name of key-pair, the pem file located at ~/.aws/ direcory

2. copy and run describe_fleet_history output   
for example:
`aws ec2 describe-fleet-history --fleet-id fleet-ed51ab81-feea-42f5-a322-0697c461ca35 --start-time 2018-12-08T10:58:27.000Z`

### References

* It behaves same with aws cloudformation  
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-networkinterface.html#cfn-ec2-launchtemplate-networkinterface-associatepublicipaddress
You should not specify AssociatePublicIpAddress in definition of network interface for launch template with several network interfaces. Otherwise the fleet will fail to launch instances with same error: The associatePublicIPAddress parameter cannot be specified when launching with multiple network interfaces.

**Comment by ryndaniels** [comment]
Hi @stanb - thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. Could you give this a try with the latest versions yourself and let us know if you are still running into this issue?

**Comment by stanb** [comment]
Hi @ryndaniels. 
I tried it right now with  Terraform v0.12.8 + provider.aws v2.28.1. Also upgraded module to 0.12. And I got same behavior. Problem reproduced.
Did you run step 2? Fleet is created by terraform but the fleet defined wrong so that it fails to launch instances because of error "The associatePublicIPAddress parameter cannot be specified when launching with multiple network interfaces"

**Comment by ryndaniels** [comment]
@stanb ahhh yes, I am seeing that with step 2 now, sorry for missing that earlier! I think I have an idea of where to start with this, so I'll keep this issue updated with progress!
