### ISSUE TITLE
Ingestion of latest go aws-sdk breaks deletion of apigate Deployments with an empty "stage name"

### ISSUE THREAD

**Issue by CyrusNajmabadi** [terraform-providers/terraform-provider-aws#6806]
See https://github.com/terraform-providers/terraform-provider-aws/pull/6771#issuecomment-446036739 for more details.

The problem here is that the latest go aws-sdk added more stringent argument checking in https://github.com/aws/aws-sdk-go/pull/2323

However, terraform makes calls into the sdk with legal data that causes errors to happen that terraform cannot handle.

For example, if an apigateway Deployment is created with an empty "stage_name" (which is legal), then the call here will fail: https://github.com/terraform-providers/terraform-provider-aws/blob/aca3429ae6e4861846e648712069e1b6cf3f1fae/aws/resource_aws_api_gateway_deployment.go#L179-L186

The problem is that this code is only resilient to hearing back about `apigateway.ErrCodeNotFoundException`.  However, the latest version of aws will now return: ErrParamMinLen

**Comment by CyrusNajmabadi** [comment]
Tagging @Puneeth-n @bflad .  This regression was introduced yesterday with https://github.com/terraform-providers/terraform-provider-aws/pull/6771.

**Comment by bflad** [comment]
@CyrusNajmabadi thank you for creating a separate issue. I am working on this currently.

**Comment by bflad** [comment]
Fix submitted: #6807 

For what its worth, the mentioned AWS Go SDK change occurred in v1.16.0 of the SDK, not v1.16.2: 
* https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v1160-2018-12-05
* https://github.com/terraform-providers/terraform-provider-aws/pull/6734
