### ISSUE TITLE
Add support for region eu-north-1

### ISSUE THREAD

**Issue by dagingaa** [terraform-providers/terraform-provider-aws#6818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new Stockholm region is released, and has the identifier `eu-north-1`

```
        {
            "Endpoint": "ec2.eu-north-1.amazonaws.com",
            "RegionName": "eu-north-1"
        },
```

We should add support for this new region, however, I don't know enough about the aws provider to do so myself.

### References
Currently this hasn't been posted on either the AWS blog, but the region shows up in the aws-cli when running `aws ec2 describe-regions` as well as on the [AWS Regions and Endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html) page.

**Comment by pberswe** [comment]
terraform -v
```
Terraform v0.11.10
+ provider.aws v1.51.0
+ provider.template v1.0.0
```

Code;
```
provider "aws" {
	region = "eu-north-1"
}

```
terraform apply
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: Not a valid region: eu-north-1


```

**Comment by ewbankkit** [comment]
Requires https://github.com/terraform-providers/terraform-provider-aws/pull/6815.

**Comment by ewbankkit** [comment]
We'll also need to add support for `eu-north-1` to various data sources such as [`aws_elb_service_account`](https://www.terraform.io/docs/providers/aws/d/elb_service_account.html).
I've noticed that we need to update these for a number of recently added regions so I'll open another issue to go through, check and fix where necessary.

**Comment by bflad** [comment]
@ewbankkit this list may or may not be up to date: https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#new-region

**Comment by include** [comment]
Hi,

I am using skyp_validation = true with 1.51 but still fails. Any clue? 10x

```

provider "aws" {
  version                 = "~> 1.51"
  alias                   = "staging"
  profile                 = "foobar-stg"
  region                  = "eu-north-1"
  skip_region_validation  = true
  allowed_account_ids     = ["555555555"]
  shared_credentials_file = "~/.aws/credentials"
}
```

**Comment by bflad** [comment]
This has been released in [version 1.52.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by dagjsolheim** [comment]
this is still a (big) problem, generates lot of frustration.
terraform version
Terraform v0.11.13
+ provider.aws v2.11.0
+ provider.template v2.1.2
skip_region_validation = true or skip_region_validation = true does not help.

**Comment by ewbankkit** [comment]
@dagjsolheim Can you provide output please?
