### ISSUE TITLE
Update data sources that return per-region AWS system information for new regions

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6832]
Various data sources such as [`aws_elb_service_account`](https://www.terraform.io/docs/providers/aws/d/elb_service_account.html) return information for each AWS region. I notice that these have become out of date as new AWS regions have been brought online recently.
Go through and update to incorporate all AWS regions.

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6818

**Comment by bflad** [comment]
Done as part of #6836. Since not all AWS services are available at the launch of every new region, its certainly possible to miss things when they later do.

**Comment by bflad** [comment]
This has been released in [version 1.52.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
