### ISSUE TITLE
Feature request: aws_ssm_resource_group

### ISSUE THREAD

**Issue by claydanford** [terraform-providers/terraform-provider-aws#6834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please create resource for SSM Resource Group which groups resources via query. This helps with cross account SSM management. Very helpful with patching.

### New or Affected Resource(s)

* aws_ssm_resource_group

### Potential Terraform Configuration

```hcl
resource "aws_ssm_resource_group" "name" {
  group_criteria = "AWS::EC2::Instance"
  name = "Webserver-Group"
  description = "Webserver description"
  type = "tag"

  filter {
    name   = "Name"
    values = ["WebServers"]
  }

  tags {
    Name = "WebServers"
  }
}
```

### References

[https://aws.amazon.com/blogs/mt/centralized-multi-account-and-multi-region-patching-with-aws-systems-manager-automation/](https://aws.amazon.com/blogs/mt/centralized-multi-account-and-multi-region-patching-with-aws-systems-manager-automation/)

* #0000

**Comment by bflad** [comment]
Initial Resource Group support is being implemented in #6217. At first glance, I'm unsure if this specific feature request requires separate SSM updates.

**Comment by claydanford** [comment]
Looks like SSM does not need it's own resource. When I enter the resource group page from console home, it brings me to system manager resource groups. Will reopen if #6217 does not resolve after merging to master.

**Comment by fh** [comment]
I am part of the team behind AWS Resource Groups - I can confirm that #6217 should solve your need here. While Resource Groups and Systems Manager share a console, there is no SSM-specific requirement to use Resource Groups.
