### ISSUE TITLE
aws_emr_cluster errors when we initialize instance_count=0 

### ISSUE THREAD

**Issue by keerthi-penmatsa** [terraform-providers/terraform-provider-aws#6837]
From Terraform official documentation, 
https://www.terraform.io/docs/providers/aws/r/emr_cluster.html, instance count is an optional parameter:
instance_count - (Optional) Target number of instances for the instance group 

However, when I set it to 0 or when instance_count is omitted altogether, I get error from Terraform

### Terraform Version

0.10.7

### Affected Resource(s)

* aws_emr_cluster

### Terraform Configuration Files

```hcl
resource "aws_emr_cluster" "cluster" {
  count         = "${var.create_cluster}"
  name          = "${lower(var.emr_name)}"
  release_label = "${var.emr_release_label}"
  applications  = "${var.emr_applications}"

  visible_to_all_users              = true
  keep_job_flow_alive_when_no_steps = true
  log_uri                           = "${var.emr_log_uri}"

  ec2_attributes {
    subnet_id = "${var.emr_subnet_id}"
    key_name  = "${var.keyname}"

    additional_master_security_groups = "${var.enable_adhoc ? module.emr_sg.sg_id : var.master_extra_sgs}"

    additional_slave_security_groups = "${var.enable_adhoc ? module.emr_sg.sg_id : var.slave_extra_sgs}"
    instance_profile                 = "${var.emr_instance_profile}"
  }

  instance_group {
      instance_role = "MASTER"
      instance_type = "m5.xlarge"
      instance_count = "1"
      bid_price = "0.30"
      ebs_config {
        size = "40"
        type = "gp2"
        volumes_per_instance = 1
      }
  }

  instance_group {
      instance_role = "CORE"
      instance_type = "m5.xlarge"
      instance_count = "0"
      bid_price = "0.30"
      ebs_config {
        size = "40"
        type = "gp2"
        volumes_per_instance = 1
      }
      autoscaling_policy  = "${data.template_file.autoscaling_policy.rendered}"
  }

  ebs_root_volume_size = "${var.emr_root_volume}"
  lifecycle {
    ignore_changes = ["instance_group"]
  }
configurations = "${var.asg_policy ? data.template_file.glue_configuration.rendered : data.template_file.configuration.rendered}"
service_role = "${var.emr_service_role}"
autoscaling_role = "${var.asg_policy ? var.autoscaling_role : ""}"
}
```

### Expected Behavior

Cluster should create a single MASTER node without a CORE node. 

### Actual Behavior
<Error>
aws_emr_cluster.cluster: ValidationException: An instance group must have at least one instance.>

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aeschright** [comment]
Hi @keerthi-penmatsa! Per the docs, this appears to be the correct behavior. At least one instance is required, and omitting the argument will cause it to be set to the default of `1`. I'm going to close the issue, but please open a new bug report if you continue to encounter problems. Thanks!
