### ISSUE TITLE
New Data Resource for AWS Organization 

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#6842]
Would be nice to have a data resource to list all accounts under the organization

https://docs.aws.amazon.com/cli/latest/reference/organizations/list-accounts.html

**Comment by tdmalone** [comment]
See also:
https://github.com/terraform-providers/terraform-provider-aws/issues/571
https://github.com/terraform-providers/terraform-provider-aws/pull/2530
https://github.com/terraform-providers/terraform-provider-aws/pull/3604
https://github.com/terraform-providers/terraform-provider-aws/pull/4384
https://github.com/terraform-providers/terraform-provider-aws/pull/4688
https://github.com/terraform-providers/terraform-provider-aws/pull/7038

**Comment by bflad** [comment]
In addition to tracking just support for fetching all Organization account IDs, this issue will be used for tracking adding the `aws_organizations_organization` data source in general as part of closing #571 shortly. 👍 There is a high probability that both will be implemented under the same data source. 👍

**Comment by sshvetsov** [comment]
Would love to see `aws_organizations_organization` data source, since being able to to extract Organization ID from any child account, allows to leverage the [global policy condition key](see https://aws.amazon.com/about-aws/whats-new/2018/05/principal-org-id/) `aws:PrincipalOrgID` in various resource (e.g. S3) and IAM Role trust policies.

**Comment by bflad** [comment]
Support for a new `aws_organizations_organization` data source has been merged and will release with version 2.21.0 of the Terraform AWS Provider, in about a week. 🎉

This new data source has a few modes of operation:

* If used in an account that is not part of an Organization, it will return an error
* If used within an Organization but outside the master account, it will return the Organization ID, ARN, and master account ID information
* In used within the Organization master account, it will return all the arguments and attributes available in the `aws_organizations_organization` resource including all member account information such as account ARNs and account IDs

We want to thank everyone for being patient through this whole process while we evaluated use cases and special thanks to @alucillo, @brandonstevens, @breser, @nirhaas, and @scottwinkler for their various contributions with this functionality!

**Comment by bflad** [comment]
This has been released in [version 2.21.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2210-july-25-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests, documentation updates, or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
