### ISSUE TITLE
terraform aws_kinesis_analytics_application resource shows diff in code(sql query part) even if it is unchanged

### ISSUE THREAD

**Issue by rupeshshah4706** [terraform-providers/terraform-provider-aws#6852]
Description - terraform aws_kinesis_analytics_application resource shows diff in code even if it is unchanged.

We are deploying kinesis analytics application using terraform provider, We have deployed it successfully. And then we haven't changed the provider code afterwards.

But still, In successive tf plans, It shows that code(sql query part) of kinesis analytics application is changed.

**Comment by bflad** [comment]
Hi @rupeshshah4706 👋 Thank you for reporting this and sorry you are running into trouble here.

Can you please provide the `terraform plan` output you are seeing? Your `aws_kinesis_analytics_application` resource configuration would be helpful as well.  These will allow us to determine if a fix is possible and hopefully create a matching test to fix the issue more permanently. Please feel free to redact any private information as necessary.

**Comment by rupeshshah4706** [comment]
Hi @bflad 

I have provided the **terraform plan** output and aws_kinesis_analytics_application resource configuration.

`module.xxxx.aws_kinesis_analytics_application.ops-mon-outage-alert-application
    code:                                          CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" ("time" TIMESTAMP, "status" varchar(8), "PARTITION_KEY" varchar(6));CREATE OR REPLACE PUMP "DESTINATION_PUMP1" AS INSERT INTO "DESTINATION_SQL_STREAM" SELECT STREAM ROWTIME, 'CRITICAL' as status, "PARTITION_KEY" FROM (SELECT STREAM SUM("xx") AS "yy", "PARTITION_KEY" from "MyInApplicationStream_001" WINDOWED BY STAGGER (PARTITION BY PARTITION_KEY RANGE INTERVAL '30' MINUTE)) WHERE "yy" = 0; CREATE OR REPLACE PUMP "DESTINATION_PUMP2" AS INSERT INTO "DESTINATION_SQL_STREAM" SELECT STREAM ROWTIME, 'OK' as status, "PARTITION_KEY" FROM (SELECT STREAM SUM("xx") AS "yy", "PARTITION_KEY" from "MyInApplicationStream_001" WINDOWED BY STAGGER (PARTITION BY PARTITION_KEY RANGE INTERVAL '30' MINUTE)) WHERE "yy" > 0;
                                                   -
`
This comes as a diff whenever I do **terraform plan**

aws_kinesis_analytics_application resource configuration --
`resource "aws_kinesis_analytics_application" "xxxxx" {
  name = "mss_${var.environment}_${var.region}_xxxxx"

  inputs {
    name_prefix = "MyInApplicationStream"
    kinesis_stream {
      resource_arn = "${aws_kinesis_stream.xxxxx-stream.arn}"
      role_arn     = "${data.aws_iam_role.xxxxx_iam_role.arn}"
    }
    parallelism {
      count = 1
    }
    schema {
      record_columns {
        mapping = "$.xxxxx"
        name     = "xxxxx"
        sql_type = "INTEGER"
      }
      record_columns{
        mapping = "$.xxxxx"
        name = "xxxxx"
        sql_type ="INTEGER"
      }
      record_columns{
        mapping = "$.xxxxx"
        name = "xxxxx"
        sql_type ="INTEGER"
      }
      record_encoding = "UTF-8"
      record_format {
        mapping_parameters {
          json {
            record_row_path = "$"
          }
        }
      }
    }
  }

  code =  "CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" ("time" TIMESTAMP, "status" varchar(8), "PARTITION_KEY" varchar(6));CREATE OR REPLACE PUMP "DESTINATION_PUMP1" AS INSERT INTO "DESTINATION_SQL_STREAM" SELECT STREAM ROWTIME, 'CRITICAL' as status, "PARTITION_KEY" FROM (SELECT STREAM SUM("xx") AS "yy", "PARTITION_KEY" from "MyInApplicationStream_001" WINDOWED BY STAGGER (PARTITION BY PARTITION_KEY RANGE INTERVAL '30' MINUTE)) WHERE "yy" = 0; CREATE OR REPLACE PUMP "DESTINATION_PUMP2" AS INSERT INTO "DESTINATION_SQL_STREAM" SELECT STREAM ROWTIME, 'OK' as status, "PARTITION_KEY" FROM (SELECT STREAM SUM("xx") AS "yy", "PARTITION_KEY" from "MyInApplicationStream_001" WINDOWED BY STAGGER (PARTITION BY PARTITION_KEY RANGE INTERVAL '30' MINUTE)) WHERE "yy" > 0"

  outputs{
    name = "DESTINATION_SQL_STREAM"
    kinesis_stream{
      resource_arn = "${aws_kinesis_stream.xxxxx-stream.arn}"
      role_arn = "${data.aws_iam_role.xxxxx_iam_role.arn}"
    }
    schema{
      record_format_type = "JSON"
    }
  }

  cloudwatch_logging_options{
    log_stream_arn = "${aws_cloudwatch_log_stream.xxxxx-app-cloudwatch-stream.arn}"
    role_arn = "${data.aws_iam_role.xxxxx_iam_role.arn}"
  }
}`

**Comment by rupeshshah4706** [comment]
Hi @bflad 

Have you got chance to look at this request, any pointers to debug further will be helpful.

**Comment by bflad** [comment]
Hi @rupeshshah4706, I’m personally on holiday for the next week, but maybe someone else can look in the meantime.

**Comment by rupeshshah4706** [comment]
Hi @bflad 

I hope you had a great timeout, Is it possible for you to look at this request.

**Comment by kl4w** [comment]
Hi @rupeshshah4706 This is something I've noticed when I first created the resource (and forgot to mention) that you need a "\n" at the end of the `code` attribute. When I add that to the end of your query, I get no changes to subsequent plans. 

I haven't really looked into whether this is a quirk with the provider or with AWS yet. Should this be added to documentation? @bflad

**Comment by rupeshshah4706** [comment]
Thank you @kl4w
