### ISSUE TITLE
Error configuring the backend "s3": Not a valid region: eu-north-1

### ISSUE THREAD

**Issue by include** [terraform-providers/terraform-provider-aws#6854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.52.0

### Affected Resource(s)

Initializing the backend...

### Terraform Configuration Files

```hcl
# Remote State Backend Configuration
terraform {
  backend "s3" {
    bucket = "foobar-tf-remotestate-eu-north-1-staging"
    key    = "terraform.tfstate"
    region = "eu-north-1"
  }
}
# Remote State data source
data "terraform_remote_state" "network" {
  backend = "s3"
  config {
    bucket = "foobar-tf-remotestate-eu-north-1-staging"
    key    = "terraform.tfstate"
    region = "eu-north-1"
  }
}

```

### Debug Output

```sh
➜ terraform init
Initializing modules...
- module.vpc-stg

Initializing the backend...

Error configuring the backend "s3": Not a valid region: eu-north-1

Please update the configuration in your Terraform files to fix this error
then run this command again.
```
### Panic Output

```
➜ TF_LOG=debug terraform init
2018/12/14 12:53:10 [INFO] Terraform version: 0.11.10
2018/12/14 12:53:10 [INFO] Go runtime version: go1.11.1
2018/12/14 12:53:10 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.10/bin/terraform", "init"}
2018/12/14 12:53:10 [DEBUG] Attempting to open CLI config file: /Users/include/.terraformrc
2018/12/14 12:53:10 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2018/12/14 12:53:10 [INFO] CLI command args: []string{"init"}
2018/12/14 12:53:10 [DEBUG] command: loading backend config file: /Users/include/Documents/WORK/TARBASE/dev-clients/foobar/foobar-administrative/devops/terraform/eu-north-1-staging
Initializing modules...
- module.vpc-stg

Initializing the backend...
2018/12/14 12:53:10 [DEBUG] command: no data state file found for backend config
2018/12/14 12:53:10 [DEBUG] New state was assigned lineage "ccad1337-f157-2d03-94d1-434c5776325b"
2018/12/14 12:53:10 [INFO] Building AWS region structure
2018/12/14 12:53:10 [DEBUG] plugin: waiting for all plugin processes to complete...

Error configuring the backend "s3": Not a valid region: eu-north-1

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

### Expected Behavior

Create S3 bucket with remote state file.

### Actual Behavior

Exited without creating bucket.

### Steps to Reproduce

1. `terraform init`

**Comment by gazoakley** [comment]
Looks related to this: https://github.com/hashicorp/terraform/issues/19632

@include: You could try using the `skip_region_validation` option until a fix is in place: https://www.terraform.io/docs/backends/types/s3.html#skip_region_validation

**Comment by bflad** [comment]
Hi @include 👋 As mentioned above, the changes required (mainly updating the AWS Go SDK dependency) need to happen upstream in Terraform core, where the [S3 backend code](https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3) currently is located. Please subscribe to the upstream issue, https://github.com/hashicorp/terraform/issues/19632, for further updates. 

Since there is nothing to do in the Terraform AWS provider, I'm going to close this issue.

**Comment by kmarinov7** [comment]
> @gazoakley but I am using `skip_region_validation = true` but does not work.
Hi,

You need to add quotes on true i.e.

'skip_region_validation = "true" '
