### ISSUE TITLE
Adding support for lambda targets in alb target groups

### ISSUE THREAD

**Issue by lanmalkieri** [terraform-providers/terraform-provider-aws#6858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS recently announced that lambda functions can be invoked directly by ALB's. Would be great for terraform to have this functionality. 
https://aws.amazon.com/blogs/networking-and-content-delivery/lambda-functions-as-targets-for-application-load-balancers/

### New or Affected Resource(s)
https://www.terraform.io/docs/providers/aws/r/lb_target_group.html
specifically `target_type`

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group" "test" {
  name     = "tf-lambda-lb-tg"
  target_type = "lambda_function"
  lambda_arn = "arn"
}
```

**Comment by sunilkumarmohanty** [comment]
Duplicate of #6693

**Comment by lanmalkieri** [comment]
Ah ok couldn't find any open. Will close.
