### ISSUE TITLE
`aws_autoscaling_group` does not have attribute `availability_zones` per documentation

### ISSUE THREAD

**Issue by dayglojesus** [terraform-providers/terraform-provider-aws#6860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.52.0
```

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "foo" {
  name                 = "foo"
  min_size             = 1
  desired_capacity     = 1
  max_size             = 1

  vpc_zone_identifier  = [
    "subnet-aaaaaaaa",
    "subnet-bbbbbbbb",
  ]
}

output "foo_az" {
  value = "${aws_autoscaling_group.foo.availability_zones}"
}
```

### Debug Output

https://gist.github.com/dayglojesus/b6ef2f9a17db42229cdcb7a4744d779d

### Expected Behavior

The exported value (`availability_zones`) should be available per the documentation...
https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#availability_zones

### Actual Behavior

Terraform produced an error indicating the attributes was present.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Reproducable in versions as far back as `1.41`

Thanks!

**Comment by sunilkumarmohanty** [comment]
I was able to replicate the problem. The problem seems to be that when `vpc_zone_identifier` are specified, `availability_zones` is getting suppressed.
I have a quick fix for this. @bflad : Could you please help confirm, is it required to set `DiffSuppressFunc` for `availability_zones`.

**Comment by tomelliff** [comment]
This could be clearer in the documentation but, as mentioned in the [argument reference](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#availability_zones) the `availability_zones` argument and attribute are only for EC2 Classic accounts, not VPC.

**Comment by aeschright** [comment]
It looks like this restriction is now noted in that part of the documentation, so I'm going to close this issue. Thanks for the help verifying it!
