### ISSUE TITLE
Cross Region Pipelines

### ISSUE THREAD

**Issue by EdisonHarada** [terraform-providers/terraform-provider-aws#6871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As AWS launched the Cross Region Pipelines, we don't need to create one pipeline per region or use lambdas to deploy in another region.

We can just simply create one pipeline and S3 buckets in the other regions, so the own pipeline would copy the artifacts and deploy it in other regions.

The unique way to implement that today is using AWS CLI.
Here is the doc: https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-create-cross-region.html

### New or Affected Resource(s)

* aws_codepipeline

### Potential Terraform Configuration

N/A

### References

* https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-create-cross-region.html

**Comment by bflad** [comment]
Due to the change of the underlying API implementation for this functionality, the Terraform AWS Provider can unexpectedly crash if a pipeline is manually configured with cross-region support outside Terraform. See also: #7573

**Comment by edmundcraske** [comment]
It seems like quite a few people are running into crashes as per #7573 due to making changes to a terraform-managed CodePipeline in the AWS Console - I'm assuming that they have updated the Console to automatically set all pipelines as cross-region. I don't know if anyone's actively looking at this or what it would take to fix this, but it looks like it is becoming a little bit more than a nice-to-have!

**Comment by dalesit** [comment]
The change can be as little as someone changing the branch in the source stage, but using the console as it is just needed to push a hotfix or something transitory. If it is done in the console, it breaks Terraform.

**Comment by pedroo21** [comment]
Is this feature still on track? 
AWS posted this change on Nov 12, 2018. It's been 8 months since Terraform hasn't provided support for one of the most helpful code-pipeline features.

**Comment by bflad** [comment]
The functionality for this was merged in via #12549 however GitHub was having issues at the time so closing manually.
