### ISSUE TITLE
Documentation for ecs_task_definition conflicts for cpu parameter

### ISSUE THREAD

**Issue by mlcooper** [terraform-providers/terraform-provider-aws#6879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

N/A - Issue with documentation

### Affected Resource(s)

* ecs_task_definition

### Steps to Reproduce

1. Documentation for `cpu` here, https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html#cpu, says that for `FARGATE` the field is required.
2. However, on the AWS side, in this document, https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html, under `cpu` it says:
```
This field is optional for tasks using the Fargate launch type...
```

### References

* #0000

**Comment by tracypholmes** [comment]
Hi, @mlcooper ! I attempted to create this resource with `FARGATE` minus `cpu`, and I got this error: `ClientException: Fargate requires that 'cpu' be defined at the task level.`. However, it appears this is also the case for the `memory` parameter. As such, it appears the AWS documentation is incorrect.

I'm closing this but if you feel like it doesn't address your issue then feel free to reopen. Thanks for bringing this to our attention!
