### ISSUE TITLE
aws_vpcs data source results in error when there are zero VPCs

### ISSUE THREAD

**Issue by erikpaasonen** [terraform-providers/terraform-provider-aws#6882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
``` hcl
Terraform v0.11.10
+ provider.aws v1.52.0
```

### Affected Resource(s)
* aws_vpcs

### Terraform Configuration Files
```hcl
data "aws_vpcs" "current" {}

resource "aws_security_group" "mysecuritygroups" {
  count = "${length(data.aws_vpcs.current.ids)}"
  ...
}

resource "aws_flow_log" "myvpcflowlogs" {
  count = "${length(data.aws_vpcs.current.ids)}"
  ...
}
```

### Debug Output
https://gist.github.com/erikpaasonen/0b781bce7680bd7663574084bf687a88

### Expected Behavior
Terraform should run to completion successfully and create zero resources where `data "aws_vpcs"` was used as the `count` value.

### Actual Behavior
``` bash
Error: Error refreshing state: 1 error(s) occurred:

* data.aws_vpcs.current: 1 error(s) occurred:

* data.aws_vpcs.current: data.aws_vpcs.current: no matching VPC found
```

### Steps to Reproduce
1. `terraform init`
1. `terraform apply`

### Important Factoids
Our use case for `data "aws_vpcs"` is to run the same set of region-specific Terraform code in every AWS region. Our Terraform stack is separate/distinct from our VPC bootstrap stack. It seems wasteful to create a custom data source just so that our team can handle the zero-VPC use case.

### References
* #3984

**Comment by tperelle** [comment]
👍

**Comment by ryndaniels** [comment]
Hi @erikpaasonen! This is actually the expected behavior of data sources - it is by design that they return an error if there are zero results. If you'd like to discuss this as a design principle, the [upstream terraform repository](https://github.com/hashicorp/terraform) would be the best place for you to do that. Thanks! 🙂
