### ISSUE TITLE
Allow PlatforVersion to be specified in aws_ecs_service for FARGATE

### ISSUE THREAD

**Issue by shanmugakarna** [terraform-providers/terraform-provider-aws#6897]
FARGATE supports multiple platform versions. It would be great if have that option configurable via Terraform `aws_ecs_service`
**PlatformVersion** on https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.CreateService

Not sure if this is already present and docs need update ?

**Comment by bflad** [comment]
Support for a new `platform_version` argument to the `aws_ecs_service` resource has been merged and will release with version 1.53.0 of the AWS provider, likely tomorrow.
