### ISSUE TITLE
Unable to run the networking example - unknown variable referenced

### ISSUE THREAD

**Issue by xni06** [terraform-providers/terraform-provider-aws#6900]
How exactly am I supposed to run the [networking](https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/networking) example? These are the steps that I have taken: 

1. `git clone https://github.com/terraform-providers/terraform-provider-aws`
1. `cd terraform-provider-aws/examples/networking`
1. `export TF_VAR_access_key="sdfsdfsdf"`
1. `export TF_VAR_secret_key="ergwtehwrth"`
1. `terraform init`

Here's the output

```
Initializing modules...
- module.us-east-1
- module.us-west-2
- module.us-east-1.primary_subnet
- module.us-east-1.secondary_subnet
- module.us-west-2.primary_subnet
- module.us-west-2.secondary_subnet

Error: resource 'aws_vpc.main' config: unknown variable referenced: 'region_numbers'; define it with a 'variable' block

Error: resource 'aws_subnet.main' config: unknown variable referenced: 'az_numbers'; define it with a 'variable' block

Error: resource 'aws_subnet.main' config: unknown variable referenced: 'az_numbers'; define it with a 'variable' block

Error: resource 'aws_vpc.main' config: unknown variable referenced: 'region_numbers'; define it with a 'variable' block

Error: resource 'aws_subnet.main' config: unknown variable referenced: 'az_numbers'; define it with a 'variable' block

Error: resource 'aws_subnet.main' config: unknown variable referenced: 'az_numbers'; define it with a 'variable' block
```

What am I doing wrong? I've tried the [two-tier](https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/two-tier) example and that works OK.

**Comment by aliasgharnezamabadi** [comment]
#

**Comment by tracypholmes** [comment]
Closing in favor of #8059.
