### ISSUE TITLE
aws_batch_compute_environment  invalid or unknown key: spot_iam_fleet_role 

### ISSUE THREAD

**Issue by af6140** [terraform-providers/terraform-provider-aws#6928]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.11

### Affected Resource(s)

* aws_batch_compute_environment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

Error: module.batch_env_managed.aws_batch_compute_environment.managed_spot: : invalid or unknown key: spot_iam_fleet_role

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aeschright** [comment]
Hi @af6140! Sorry you ran into this issue. Without your config file and more details, we don't have enough to dig into why this might be happening. I'm going to close the issue, but if you're still having problems please open a new bug report and include the items mentioned. Thanks!
