### ISSUE TITLE
aws_eks_cluster: Expand documentation on version argument

### ISSUE THREAD

**Issue by lachlancooper** [terraform-providers/terraform-provider-aws#6933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.52.0
```

### Affected Resource(s)

* `aws_eks_cluster`

### Description

The documentation for the `version` argument states `Desired Kubernetes master version. If you do not specify a value, the latest available version is used.` However, the latest version only appears to be used when a cluster resource is created. For existing clusters, if no value is specified Terraform will not attempt a version update.

The version argument was only added recently, so this behaviour may be desirable to avoid unintended updates, but it does not match the documentation.

Additional documentation clarifying Terraform's behaviour in situations presumably not supported by AWS, such as version downgrades, would also be valuable.

### Terraform Configuration Files

```hcl
resource "aws_eks_cluster" "main" {
  name     = "${var.eks_cluster_name}"
  role_arn = "${aws_iam_role.eks_cluster.arn}"

  vpc_config {
    security_group_ids = ["${aws_security_group.control_plane.id}"]

    subnet_ids = [
      "${aws_subnet.az_1_private_subnet.id}",
      "${aws_subnet.az_2_private_subnet.id}",
      "${aws_subnet.az_3_private_subnet.id}",
    ]
  }
}
```

### Expected Behavior

Running a plan of this configuration (with no version specified) against an existing cluster running Kubernetes version 1.10 should have planned an update to the latest available, 1.11.

### Actual Behavior

No changes were planned.

### Steps to Reproduce

1. Provision a cluster explicitly running version 1.10.
1. Remove the version argument from the configuration.
1. `terraform apply`

**Comment by bflad** [comment]
A documentation update has been merged and will release with version 2.1.0 of the Terraform AWS Provider, likely in the next day or two.
