### ISSUE TITLE
Launch ec2 instance using launch template

### ISSUE THREAD

**Issue by rohityadav225** [terraform-providers/terraform-provider-aws#6948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_instance

### Potential Terraform Configuration

```hcl
resource "aws_instance" "myapp" {
  ami                     = "${var.ami}"
  instance_type           = "${var.instance_type}"
  key_name                = "${var.key_name}"
  user_data_base64        = "${base64encode(data.template_file.user-data.rendered)}"
  iam_instance_profile    = "${var.iam_instance_profile}"
  monitoring              = "${var.enable_monitoring}"
  
  launch_template = {
    id      = "${aws_launch_template.app.id}"
    version = "${aws_launch_template.version}"
  }
}
```

### References

* https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RunInstancesInput
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html#launch-instance-from-launch-template

**Comment by bflad** [comment]
Hi @rohityadav225 👋 Thanks for submitting this. It looks like there is already an open issue (#4264) and pull request (#4543) for this functionality. To consolidate discussions and efforts, I'm going to close this issue in preference of the previous issue. 👍
