### ISSUE TITLE
Support for AWS Client VPN

### ISSUE THREAD

**Issue by qrevel** [terraform-providers/terraform-provider-aws#6949]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS just released a new VPN service that works with OpenVPN-based clients

### References

https://aws.amazon.com/about-aws/whats-new/2018/12/introducing-aws-client-vpn-to-securely-access-aws-and-on-premises-resources/

**Comment by slapula** [comment]
I'd like to take a shot at this but if someone has something already written up don't wait for me.

**Comment by slapula** [comment]
I submitted #7009 which provides a resource that manages AWS Client VPN endpoints.  If anyone wants to provide some additional testing, it would be much appreciated.

**Comment by slapula** [comment]
@bflad this issue still needs #7030 as well

**Comment by bflad** [comment]
Whoops sorry, the PR for the `aws_ec2_client_vpn_endpoint` resource was marked to close this, reopening. 😅 That resource has been merged and will release with version 1.58.0 of the Terraform AWS provider, likely middle of this week.

There is a followup PR for an `aws_ec2_client_vpn_network_association` resource which will get reviewed later today.

**Comment by slapula** [comment]
Oh wow, I never realized that...  Thanks! You learn something new everyday.

**Comment by bflad** [comment]
The `aws_ec2_client_vpn_network_association` resource has also been merged and will release with version 1.58.0 of the Terraform AWS provider, very shortly.

For any additional feature requests or bug reports, please open a new issue. Thanks!

**Comment by bflad** [comment]
The new `aws_ec2_client_vpn_endpoint` and `aws_ec2_client_vpn_network_association` resources have been released in [version 1.58.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1580-february-08-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by dimisjim** [comment]
> The `aws_ec2_client_vpn_network_association` resource has also been merged and will release with version 1.58.0 of the Terraform AWS provider, very shortly.
> 
> For any additional feature requests (e.g. a resource to manage Client VPN Routes) or bug reports, please open new issue(s). Thanks!

Hi @bflad. Is there any new resource for adding routes and authorization rules?
Thanks.

EDIT: I have seen that there is a pull request regarding the authorization ingresses: https://github.com/terraform-providers/terraform-provider-aws/pull/7564 but I haven't found anything relevant to the Routes creation
