### ISSUE TITLE
Include "provided" runtime into the lambda function

### ISSUE THREAD

**Issue by admssa** [terraform-providers/terraform-provider-aws#6950]
Include ["provided" runtime](https://docs.aws.amazon.com/en_us/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax) in to the lambda function to allow use [custom runtime](https://docs.aws.amazon.com/en_us/lambda/latest/dg/runtimes-custom.html).

> Runtime
The runtime version for the function.
Type: String
Valid Values: 
nodejs | nodejs4.3 | nodejs6.10 | nodejs8.10 | java8 | python2.7 | python3.6 | python3.7 | dotnetcore1.0 | dotnetcore2.0 | dotnetcore2.1 | nodejs4.3-edge | go1.x | ruby2.5 | provided
Required: Yes

Tried to use, but got:
`Error: module.kubernetes.module.logging.aws_lambda_function.es-cleaner: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 go1.x java8 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 python2.7 python3.6], got provided`

* aws_lambda_function

### Potential Terraform Configuration

```
resource "aws_lambda_function" "es-cleaner" {

....
  runtime          = "provided"
...
}
```

### References

["provided" runtime](https://docs.aws.amazon.com/en_us/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax)
 [custom runtime](https://docs.aws.amazon.com/en_us/lambda/latest/dg/runtimes-custom.html).

**Comment by bflad** [comment]
Hi @admssa 👋 We recently released validation support for the `provided`, `python3.7` and `ruby2.5`, runtimes in [version 1.51.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1510-december-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading. 👍

**Comment by admssa** [comment]
@bflad oh, sorry, guys. I haven't noticed that. I thought i have the latest version
