### ISSUE TITLE
Can't create more than one association per AWS instance

### ISSUE THREAD

**Issue by wschult23** [terraform-providers/terraform-provider-aws#6954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.archive v1.1.0
+ provider.aws v1.36.0
+ provider.external v1.0.0
+ provider.random v2.0.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_instance
* aws_ssm_association

### Terraform Configuration Files

```hcl
resource "aws_instance" "Test" {

  ami                    = "${var.image_id}"
  instance_type          = "${var.instance_type}"
  key_name               = "${var.key_name}"
  iam_instance_profile   = "${var.instance_profile}"
  subnet_id              = "${var.subnet_id}"
  vpc_security_group_ids = ["${var.security_group_id}"]

  root_block_device {
    volume_size           = "${var.volume_size}"
    volume_type           = "gp2"
    delete_on_termination = true
  }
}

resource "aws_ssm_association" "associate_ssm_ad_domain" {
  name       = "AWS-JoinDirectoryServiceDomain"
  instance_id = "${aws_instance.Test.id}"

  parameters = {
    directoryId = "${var.directory_id}",
    directoryName = "${var.directory_name}",
  }
}

resource "aws_ssm_association" "cloudwatch_assoc" {
  name        = "AWS-ConfigureCloudWatch"
  instance_id = "${aws_instance.Test.id}"

  parameters = {
    status     = "Enabled"
    properties = <<DOC 
    {
    "IsEnabled": true,
    "EngineConfiguration": {
        "PollInterval": "00:00:05",
        "Components": [
            {
                "Id": "ApplicationEventLog",
                "FullName": "AWS.EC2.Windows.CloudWatch.EventLog.EventLogInputComponent,AWS.EC2.Windows.CloudWatch",
                "Parameters": {
                    "LogName": "Application",
                    "Levels": "1"
                }
            },
            {
                "Id": "CloudWatchLogEvents",
                "FullName": "AWS.EC2.Windows.CloudWatch.CloudWatchLogsOutput,AWS.EC2.Windows.CloudWatch",
                "Parameters": {
                    "Region": "eu-central-1",
                    "LogGroup": "TestServer",
                    "LogStream": "TestEC2Instance"
                }
            }
        ],
        "Flows": {
            "Flows": [
                "(ApplicationEventLog),CloudWatchLogEvents"
            ]
        }
    }
}
DOC
  }
}
```

### Expected Behavior

Within the AWS console I'm able to assign more than one association to an instance. It should be possible to do this in terraform as well.

### Actual Behavior

Terraform is unable to apply the plan.

```
Error: Error applying plan:

1 error(s) occurred:

* module.instance_tableau.aws_ssm_association.associate_ssm_ad_domain: 1 error(s) occurred:

* aws_ssm_association.associate_ssm_ad_domain: [ERROR] Error creating SSM association: AssociationAlreadyExists:
        status code: 400, request id: e6328e21-f217-4f70-806d-7495e27bca8a
```
### Steps to Reproduce

1. `terraform apply`

**Comment by tomelliff** [comment]
Looking at [this AWS forums thread](https://forums.aws.amazon.com/thread.jspa?threadID=245656) it looks like the document association needs to use the [`targets`](https://www.terraform.io/docs/providers/aws/r/ssm_association.html#targets) parameter instead of `instance_id`.

Can you test that that works for you? If so that should probably be documented better. I'm also not sure if the `targets` and `instance_id` should be conflicting in the Terraform resource schema but I've not used SSM that much beyond Parameter Store and Run Command.

**Comment by wschult23** [comment]
Thats the solution. Not obvious but it works if you replace
`instance_id = "${aws_instance.Test.id}"`

with

`  targets {
    key = "InstanceIds"
    values = ["${var.instance_id}"]
  }`
