### ISSUE TITLE
when aws_vpc_dhcp_options_association is destroyed, the dhcp option of the vpc is set to none

### ISSUE THREAD

**Issue by superwg** [terraform-providers/terraform-provider-aws#6974]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.10

### Affected Resource(s)

* aws_vpc_dhcp_options_association

### Terraform Configuration Files

```hcl
resource "aws_vpc_dhcp_options_association" "dns_resolver" {
  vpc_id          = "${aws_vpc.foo.id}"
  dhcp_options_id = "${aws_vpc_dhcp_options.foo.id}"
}
```

### Expected Behavior

After the resource is destroyed. dhcp option should be set to the default vpc dhcp option

### Actual Behavior

After the resource is destroyed, dhcp option is set to none.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### References

* #0000

**Comment by bflad** [comment]
Hi @superwg 👋 I think we may require some additional details to determine what is happening here. 

Currently the Terraform resource code explicitly sets the DHCP Options back to `default` when the resource is being destroyed:

https://github.com/terraform-providers/terraform-provider-aws/blob/9de61bad2e8a0cefc67f58da4ce2c6878553401c/aws/resource_aws_vpc_dhcp_options_association.go#L84-L96

Can you please show (AWS CLI, AWS console screenshot, etc.) what you mean by "dhcp option is set to none"?

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
