### ISSUE TITLE
Request New DATA resource for get-bucket-policy

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#6977]
I would like to make a request to add a new data resource to get bucket policy which I could currently do using the following cli:

https://docs.aws.amazon.com/cli/latest/reference/s3api/get-bucket-policy.html

Would be good to have data resource for aws_s3_bucket_policy

data "aws_s3_bucket_policy" "policy" {
  arn = "arn:aws:s3:::<bucket name>"
}

https://www.terraform.io/docs/providers/aws/r/s3_bucket_policy.html

**Comment by ryndaniels** [comment]
Hi @e-moshaya! 👋 Thanks for this request! Could you give us a bit more information as to what your use case is for this data source? Understanding how you'd like to use this will help us be able to figure out the best way to move forward. Thanks!

**Comment by ryndaniels** [comment]
Hey @e-moshaya - since it's been two weeks without a response, we're going to go ahead and close this, but if you do have a use case you can share with us in the future, feel free to re-open this. Thanks! 🙂
