### ISSUE TITLE
Feature Request: Assign multiple rules to waf acl

### ISSUE THREAD

**Issue by awworrell** [terraform-providers/terraform-provider-aws#6990]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the UI in AWS, one can add more than one rule to a WAF ACL. In terraform, the rule id must be a single value and cannot be a list. Please modify terraform to be able to include a list of rules per ACL so that a user can create multiple rules and assign them to the same ACL via that list.

### New or Affected Resource(s)

* aws_waf_web_acl

### Potential Terraform Configuration

```hcl
module "web_acl" {
  source = "module/wafacl/aws"
  waf_acl_name = "web_acl"
  waf_acl_metric_name = "WebAcl"
  default_action_type_assignment = "ALLOW"
  rules_action_type_assignment = "BLOCK"
  rule_priority = 1
  rule_id = ["${module.waf_rule.id}"]
  rule_type_assignment = "REGULAR"
  version = "1.0.0"
}
```

### References

* #0000

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
