### ISSUE TITLE
terraform can not create EC2 instance - no default VPC id

### ISSUE THREAD

**Issue by sabya2018** [terraform-providers/terraform-provider-aws#6994]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tomelliff** [comment]
@sabya2018 You should edit your issue to include a minimal, complete, verifiable example along with the exact error you get. The issue template should help show you what you should include for anyone to be able to help you with your issue.

**Comment by bflad** [comment]
Hi @sabya2018 👋 As mentioned above, we'll need some additional information to help you troubleshoot. The bug report content from https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md has all the details we will need. Thanks.

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
