### ISSUE TITLE
Rename instance_interruption_behaviour attribute in v2.0.0

### ISSUE THREAD

**Issue by stefansundin** [terraform-providers/terraform-provider-aws#7006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Proposal: in `aws_spot_fleet_request` and `aws_spot_instance_request`, rename `instance_interruption_behaviour` to `instance_interruption_behavior` in v2.0.0.

The current name does not match the AWS API, and it is inconsistent with `aws_launch_template`, which is using the proper name. I think it makes sense to resolve this inconsistency in v2.0.0.

I was reading through the Provider Version 2 Upgrade Guide, and I think this request is similar to many of the things already in there.

I could attempt to submit a PR if this is given the Ok. I just don't know which branch is currently used for v2.0.0 development. `v2.0.0-dev` seems to be a month old? And do I just rename it 

### Affected Resources

* `aws_spot_instance_request`
* `aws_spot_fleet_request`

**Comment by tomelliff** [comment]
This was briefly discussed in https://github.com/terraform-providers/terraform-provider-aws/pull/1986 but the breaking change was dropped from that PR in the end and I didn't get around to raising the PR to add the breaking change to fix the naming because I've moved away from individual spot requests since then.

**Comment by nywilken** [comment]
Hi @stefansundin apologies for any frustration here. I reviewed the pull request associated with this issue and, unfortunately could not approve it. Renaming attributes has a [detailed process](https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-rename) that needs to be followed, and can have a large impact on operators down stream. I left more details around this particular issue on your PR. 

Thanks for your help and contributions to the provider. Apologies again for any frustration here and we will take extra precautions to prevent this situation in the future.

**Comment by stefansundin** [comment]
@nywilken Here's an idea. Create the `v3.0.0` tag and assign it to this issue so that this won't be forgotten again. I know it's probably some time before v3.0.0 will be needed, but by just closing this issue you are guaranteeing it will be forgotten (or a more likely scenario is that someone else will open a duplicate of this issue, taking more of your time).
