### ISSUE TITLE
Silently fails to upgrade Elasticache Redis cluster from 3.2 to 5.0

### ISSUE THREAD

**Issue by fubar** [terraform-providers/terraform-provider-aws#7010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.local v1.1.0
+ provider.random v2.0.0
+ provider.tls v1.2.0
```

### Affected Resource(s)

* aws_elasticache_replication_group

### Terraform Configuration Files

```hcl
resource "aws_elasticache_replication_group" "redis_cluster" {
  replication_group_id = "redis-cluster"
  replication_group_description = "Redis Cluster"
  engine_version = "5.0.0"
  node_type = "${var.redis_instance_type}"
  port = 6379
  parameter_group_name = "default.redis5.0.cluster.on"
  automatic_failover_enabled = true
  cluster_mode {
    replicas_per_node_group = 0
    num_node_groups = 1
  }
  security_group_ids = ["${aws_security_group.redis_cluster_security_group.*.id}"]
  subnet_group_name = "redis-cluster-subnet-group"
}
```

### Debug Output

```
Terraform will perform the following actions:

  ~ module.foo.aws_elasticache_replication_group.redis_cluster
      engine_version:       "3.2.10" => "5.0.0"
      parameter_group_name: "default.redis3.2.cluster.on" => "default.redis5.0.cluster.on"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.foo.aws_elasticache_replication_group.redis_cluster: Modifying... (ID: redis-cluster)
  engine_version:       "3.2.10" => "5.0.0"
  parameter_group_name: "default.redis3.2.cluster.on" => "default.redis5.0.cluster.on"
module.foo.aws_elasticache_replication_group.redis_cluster: Still modifying... (ID: redis-cluster, 10s elapsed)
module.foo.aws_elasticache_replication_group.redis_cluster: Still modifying... (ID: redis-cluster, 20s elapsed)
module.foo.aws_elasticache_replication_group.redis_cluster: Still modifying... (ID: redis-cluster, 30s elapsed)
module.foo.aws_elasticache_replication_group.redis_cluster: Modifications complete after 32s (ID: redis-cluster)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behavior

Changes are applied

### Actual Behavior

Changes are not applied, but output indicates they were.
A subsequent `terraform refresh` and `terraform apply` makes it want to do the same change again, with the same result.

### Steps to Reproduce

1. Create a `aws_elasticache_replication_group` with
   ```hcl
   engine_version = "3.2.10"
   parameter_group_name = "default.redis3.2.cluster.on"
   ```
2. `terraform apply`
3. Change the values to "5.0.0" and "default.redis5.0.cluster.on"
4. `terraform apply`

### References

* Might be related to #1615

**Comment by bflad** [comment]
Also submitted an `aws_elasticache_replication_group` resource documentation update to make the API default behavior and usage of `apply_immediately` more apparent: #7027

**Comment by fubar** [comment]
Ah, I wasn't aware that `terraform apply` is subject to the maintenance windows as it appeared that it was making the change immediately, and I wasn't aware of the `apply_immediately` flag in this context either. Your addition to the docs should help, thanks for that @bflad !

I had already deleted and recreated the resource in two steps so I can't test it, but consider this issue solved.

Thanks!
