### ISSUE TITLE
Unable to terraform elasticsearch domain within existing vpc

### ISSUE THREAD

**Issue by elizajanus** [terraform-providers/terraform-provider-aws#7022]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.11
+ provider.aws v1.54.0

### Affected Resource(s)
aws_elasticsearch_domain
vpc_options

### Terraform Configuration Files

```
resource "aws_elasticsearch_domain" "elastic_domain" {
  domain_name           = "*********-es"
  elasticsearch_version = "6.2.4"

  cluster_config {
    instance_type = "r4.large.elasticsearch"
  }

  snapshot_options {
    automated_snapshot_start_hour = 23
  }

 advanced_options {
    "rest.action.multi.allow_explicit_index" = "true"
  }

  tags = {
    Domain = "********-ES"
  }

    access_policies = <<POLICY
  {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "es:*"
      ],
      "Resource": "arn:aws:es:us-east-1:5***********:domain/*********-es/*"
    }
  ]
}
POLICY

  ebs_options {
    ebs_enabled = true
    volume_type = "gp2"
    volume_size = 10
  }

  vpc_options {
    vpc_id             = "${data.terraform_remote_state.production_vpc.production_vpc_id}"
    subnet_ids         = ["${data.terraform_remote_state.production_vpc.private_subnet_ids.5}"]
    security_group_ids = ["${data.terraform_remote_state.production_sec.prodinternal}, ${data.terraform_remote_state.production_sec.*********}, ${data.terraform_remote_state.production_sec.********}, ${data.terraform_remote_state.production_sec.natgw}, ${data.terraform_remote_state.production_sec.registry}"]
  }

  log_publishing_options {
    cloudwatch_log_group_arn = "${aws_cloudwatch_log_group.elastic_logs.arn}"
    log_type                 = "INDEX_SLOW_LOGS"
  }
}
```
full file with sensitive info removed: https://gist.github.com/elizajanus/81bf61f8a0ae2499165b6f0ba6fb2621

vpc outputs file: https://gist.github.com/elizajanus/3d660870b85e50d396a6d79fb20f34d5

### Debug Output

https://gist.github.com/elizajanus/ed28d432491b519aae3f7175f462a701

### Expected Behavior
I expect terraform to create an elasticsearch domain within our already existing vpc using the vpc id. 

### Actual Behavior

If I specify vpc_options.0.vpc_id, I get the error:
Error: aws_elasticsearch_domain.elastic_domain: "vpc_options.0.vpc_id": this field cannot be set

If I comment out the vpc_id field and use terraform plan, the value of vpc_options.0.vpc_id is "computed", and we do not want to create a new vpc.

I also see errors that the s3 key does not exist. I checked s3 and the key is there. There are also "Resource state not found" errors that may have to do with the s3 error.

### Steps to Reproduce

terraform plan or terraform apply

### References
N/A
https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html

**Comment by elizajanus** [comment]
I ran terraform apply without the vpc_id field and it somehow created the cluster in the correct vpc, possibly based on the specified subnet id. I'm not sure if this is part of the expected functionality, but I think this should be clarified in the docs.

**Comment by bflad** [comment]
Hi @elizajanus 👋 Sorry for any confusion.

The `vpc_id` attribute you see in the plan output is because we provide the value returned by the [AWS Elasticsearch API](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html) during `DescribeElasticsearchDomain`. It cannot be set in Terraform configurations since it is not supported in `CreateElasticsearchDomain`/`UpdateElasticsearchDomainConfig` and its value is inferred by `subnet_ids` since subnets are inherently part of a VPC.

Terraform providers (like the Terraform AWS provider) do not have the ability to change the plan output for the attribute in this scenario, but if there is a specific Terraform resource documentation update you would like to see, the page lives in the repository here: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/elasticsearch_domain.html.markdown

**Comment by elizajanus** [comment]
Excellent, thank you!

**Comment by aeschright** [comment]
It sounds like the problem was resolved, so I'm going to close this issue. If you're still having problems, please open a new bug report. Thanks!
