### ISSUE TITLE
AWS Codebuild Import Source Credentials

### ISSUE THREAD

**Issue by vibhuyadav** [terraform-providers/terraform-provider-aws#7025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
This feature will add the ability to connect using a token with Bitbucket and Github so the provisioned projects have the Oauth token available already. It should eliminate the manual step of connecting codebuild project to the respective SCM.

### New or Affected Resource(s)

* aws_codebuild_project
* aws_codebuild_webhook

### References

* AWS API - https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ImportSourceCredentials.html
* AWS API - https://docs.aws.amazon.com/codebuild/latest/APIReference/API_DeleteSourceCredentials.html

**Comment by bflad** [comment]
A new `aws_codebuild_source_credential` resource has been merged, which can be used to manage these credentials within CodeBuild. It will release with version 2.22.0 of the Terraform AWS Provider, tomorrow. 👍 Thanks to @kterada0509 for the implementation.
