### ISSUE TITLE
Support for X-Ray Sampling Rules

### ISSUE THREAD

**Issue by jaygorrell** [terraform-providers/terraform-provider-aws#7028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS xray allows for creating sampling rules and groups to manipulate the data stream. It would be nice to support this configuration in TF.

### New or Affected Resource(s)

* aws_xray (new)

### References

https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sampling.html

**Comment by dedoussis** [comment]
Have submitted this PR: #8535

**Comment by bflad** [comment]
A new `aws_xray_sampling_rule` resource has been merged and will release with version 2.10.0 of the Terraform AWS Provider, likely later today. Thanks, @dedoussis! 🎉

**Comment by bflad** [comment]
This has been released in [version 2.10.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2100-may-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by joebowbeer** [comment]
What about groups?
