### ISSUE TITLE
Amazon FSx Support

### ISSUE THREAD

**Issue by Jeeppler** [terraform-providers/terraform-provider-aws#7035]
Amazon FSx is a service which was launched during AWS re:Invent 2018. They announced two different services as part of FSx: [Amazon FSx for Windows File Server](https://aws.amazon.com/blogs/aws/new-amazon-fsx-for-windows-file-server-fast-fully-managed-and-secure/) and [Amazon FSx for Lustre](https://aws.amazon.com/blogs/aws/new-amazon-fsx-for-lustre/).

Both services allow AWS users to create network shares using either [Windows File Server (SMB)](https://aws.amazon.com/fsx/windows/) or [Lustre](https://aws.amazon.com/fsx/lustre/). 

I was unable to find any resources associated with FSx in the official Terraform AWS provider documentation. Additionally, I was unable to find either a pull requests or issues related to FSx. I was wondering if somebody is working on Terraform AWS resources for FSx? 

I do not have an imitate need for FSx, that is the reason why I did not create a feature request.

**Comment by slapula** [comment]
I can take a shot at this.  This looks like it will behave very similarly to the EBS resources.

**Comment by slapula** [comment]
I just added a PR to add support and a file system resource.  If anyone wants to test it and provide feedback, it would be much appreciated.  These acceptance tests take... so... long... ugh.

**Comment by tkidd77** [comment]
I need this support for a client's project ASAP. Looking forward to it!

**Comment by mbonig** [comment]
@tkidd77 If you can manage working with a custom-built provider, I suggest you take a look at https://github.com/rackerlabs/simple-provider-cicd.

**Comment by Jeeppler** [comment]
@tkidd77 you can also review the pull request @slapula and make sure it will end up in the AWS provider. That is probably the easiest.

**Comment by eewolfe** [comment]
When is aws_fsx_file_system going to be available as part of standard terraform?

**Comment by uzairjawed** [comment]
Is there any update? When is it going to be available?

**Comment by dbsysteluk-stuartlupton** [comment]
we are desperate for this

**Comment by vitbyst** [comment]
Please, I need it!

**Comment by bflad** [comment]
Hi folks 👋 Initial support for managing FSx in the Terraform AWS Provider has been merged with the following two new resources:

* **New Resource:** `aws_fsx_lustre_file_system`
* **New Resource:** `aws_fsx_windows_file_system`

These will be released with version 2.24.0 in the next day or two. Special shout out to @slapula who did great work in making this happen. 🎉
