### ISSUE TITLE
Tech debt: Consistently handle overlapping resource tags when updating

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Prompted by https://github.com/terraform-providers/terraform-provider-aws/pull/6911#discussion_r242696623 which references https://github.com/terraform-providers/terraform-provider-aws/pull/5108.
Ensure that we are consistently handling overlapping resource tags when updating a resource.
Because each AWS service has its own types and methods for resource tagging, code has been copy-pasted and is now inconsistent.

**Comment by ewbankkit** [comment]
This brings up the bigger issue of making tag handling functions generic via Go [reflection](https://golang.org/pkg/reflect/).

**Comment by bflad** [comment]
I really don't want to start any sort of flame war on the subject, but I think a few of the maintainers are strongly opposed to reflection. 😅 Type assertion (via creating our own generic type, call it something like `keyValueResourceTag`, that can be implemented easily for each of the AWS Go SDK service types, and paring down our functions to just those operations with our type) is more likely to be accepted.

**Comment by ewbankkit** [comment]
I wasn't expressing any preference or opinion 😄.
For this issue I'd like to identify and fix the services which are inconsistent WRT overlapping tags. This will give us a known good state from which to explore a generic solution.

**Comment by ewbankkit** [comment]
| Service | Source File | Correct |
| - | - | - |
| Amazon API Gateway | `tags_apigateway.go`<br/>`diffTagsGeneric()` | ❌|
| AWS Auto Scaling | `autoscaling_tags.go` | ❌|
| AWS Certificate Manager (ACM) | `tagsACM.go` | ❌|
| AWS Certificate Manager (ACM) Private Certificate Authority (CA) | `tagsACMPCA.go` | ❌|
| Amazon CloudFront | `tagsCloudFront.go` | ❌|
| AWS CloudHSM v2 | `resource_aws_cloudhsm2_cluster.go`<br/>`diffTagsGeneric()` | ❌|
| AWS CloudTrail | `tagsCloudtrail.go` | ❌|
| AWS Direct Connect | `tagsDX.go` | ❌|
| AWS Directory Service | `tagsDS.go` | ❌|
| Amazon DynamoDB | `tags.go`<br/>`diffTagsDynamoDb()` | ❌|
| Amazon DynamoDB Accelerator (DAX) | `tagsDAX.go` | ❌|
| Amazon EC2 | `tags.go`<br/>`diffTags()` | ✅|
| AWS Elastic Beanstalk | `tagsBeanstalk.go` | ❌|
| Amazon ElastiCache | `tagsEC.go` | ❌|
| Amazon Elastic Container Registry (ECR) | `tagsECR.go` | ✅|
| Amazon Elastic Container Service (ECS) | `tagsECS.go` | ✅|
| Amazon Elastic File System (EFS) | `tagsEFS.go` | ❌|
| AWS Elastic Load Balancing (ELB) | `tagsELB.go` | ❌|
| AWS Elastic Load Balancing (ELB) v2 | `tags.go`<br/>`diffElbV2Tags()` | ❌|
| Amazon Elasticsearch Service | `tags_elasticsearchservice.go` | ❌|
| AWS Identity and Access Management (IAM) | `tagsIAM.go` | ✅|
| AWS Key Management Service (KMS) | `tagsKMS.go` | ❌|
| Amazon Kinesis | `tags_kinesis.go` | ❌|
| Amazon Kinesis Data Firehose | `tagsKinesisFirehose.go` | ❌|
| AWS Lambda | `tagsLambda.go`<br/>`diffTagsGeneric()` | ❌|
| AWS License Manager | `tagsLicenseManager.go` | ❌|
| Amazon Neptune | `tagsNeptune.go` | ❌|
| AWS OpsWorks | `tagsOpsworks.go`<br/>`diffTagsGeneric()` | ❌|
| Amazon Relational Database Service (RDS) | `tagsRDS.go` | ❌|
| Amazon Redshift | `tagsRedshift.go` | ❌|
| Amazon Route 53 | `tags_route53.go` | ❌|
| Amazon S3 | `s3_tags.go` | ❌|
| AWS Secrets Manager | `tagsSecretsManager.go` | ❌|
| Amazon Simple Queue Service (SQS) | `resource_aws_sqs_queue.go`<br/>`diffTagsGeneric()`| ❌|
| AWS Step Functions | `tagsSfn.go` | ✅|
| AWS Systems Manager | `tagsSSM.go` | ❌|
| AWS Transfer for SFTP | `tagsTransfer.go` | ✅|

**Comment by ewbankkit** [comment]
Note that some of these _diffTags_ functions may not be needed as the underlying AWS API doesn't deal with tag set differences but instead just deletes all tags and applies a tag set, e.g. for S3:
https://github.com/terraform-providers/terraform-provider-aws/blob/9a2ba295b2f1ccbb54fc2c62a31312962f362da1/aws/s3_tags.go#L25-L28 and https://github.com/terraform-providers/terraform-provider-aws/blob/9a2ba295b2f1ccbb54fc2c62a31312962f362da1/aws/s3_tags.go#L36-L45.

**Comment by ewbankkit** [comment]
We need to also consider the issues brought up in https://github.com/terraform-providers/terraform-provider-aws/issues/7323, https://github.com/terraform-providers/terraform-provider-aws/pull/7342 for those APIs that don't deal with tag set differences but may have system tags.

**Comment by ewbankkit** [comment]
I will close this issue when https://github.com/terraform-providers/terraform-provider-aws/pull/10018 is merged as the functionality that PR implements will fix this for all existing services and new services in the future.

**Comment by ewbankkit** [comment]
I'm closing this issue in favor of https://github.com/terraform-providers/terraform-provider-aws/issues/10688, implementation of which will ensure overlapping tags are handled correctly.
