### ISSUE TITLE
Feature Request: Include members in attributes of aws_iam_group data source

### ISSUE THREAD

**Issue by maxenglander** [terraform-providers/terraform-provider-aws#7076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the `aws_iam_group` data source yields the group `arn`, `path` and `group_id`. I would like to also be able to retrieve the members of this group, e.g.

### New or Affected Resource(s)

Only the `aws_iam_group` would be affected.

### Potential Terraform Configuration

```hcl
data "aws_iam_group" "my-group" {
  name = "operations"
}

resource "some_other_resource" "my-resource" {
  count = "${length(data.aws_iam_group.my-group.members)}"
  user_arn = "${lookup(data.aws_iam_group.my-group.members[count.index], "arn")}"
  user_id = "${lookup(data.aws_iam_group.my-group.members[count.index], "user_id")}"
  user_name = "${lookup(data.aws_iam_group.my-group.members[count.index], "user_name")}"
}
```

**Comment by bflad** [comment]
Support for a new `users` attribute in the `aws_iam_group` data source has been merged and will release with version 2.36.0 of the Terraform AWS Provider, Thursday next week. Thanks to @kterada0509 for the implementation. 👍
