### ISSUE TITLE
Feature request: Support Amazon DocumentDB

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Amazon DocumentDB [announced](https://aws.amazon.com/blogs/aws/new-amazon-documentdb-with-mongodb-compatibility-fast-scalable-and-highly-available/).

**Comment by okonon** [comment]
@ewbankkit this is awesome and thanks for staying on top of announcements - long awaited feature for us

**Comment by fewstera** [comment]
I think I've made PRs for everything that's needed so far, just waiting for reviews and the code merging.

**Comment by okonon** [comment]
Nice! good to hear!

**Comment by bflad** [comment]
The new `aws_docdb_subnet_group` resource has been released in [version 1.56.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1560-january-16-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by okonon** [comment]
Thanks @bflad

**Comment by jasseri** [comment]
Everything seems to be ready. Do you have a date set for the next release? BTW, great work on getting the support implemented so fast after the DocumentDB announcement. :+1:

**Comment by yardensachs** [comment]
I believe we are waiting for @fewstera to come back from vacation.

**Comment by okonon** [comment]
@ewbankkit could you please review related PRs by any chance?

**Comment by mikeakala** [comment]
Is there a planned date to release this feature ?

**Comment by rossmckelvie** [comment]
Also waiting for this

**Comment by Alexandre-io** [comment]
Same here

**Comment by agurha** [comment]
Same here

**Comment by bflad** [comment]
Hi folks 👋 Just FYI that normally we include the following in our issue templates to help with prioritizing as we cannot prioritize on comments. I will add this to the original issue above to prevent any confusion and reduce noise for potential followers.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bflad** [comment]
I will provide a review for the `aws_docdc_cluster` resources today.

**Comment by bflad** [comment]
The `aws_docdb_cluster` and `aws_docdb_cluster_snapshot` resources have been merged and will release with version 1.58.0 of the Terraform AWS provider, very shortly. 

The last remaining open pull request for the `aws_docdb_cluster_instance` resource has received an initial review.

**Comment by bflad** [comment]
The `aws_docdb_cluster` and `aws_docdb_cluster_snapshot` resources have been released in [version 1.58.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1580-february-08-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by bflad** [comment]
Many thanks to @kterada0509 and @fewstera, the initial support for managing AWS DocumentDB resources in Terraform has been merged with the latest addition of the `aws_docdb_cluster_instance` resource, releasing in version 1.59.0 of the Terraform AWS Provider middle of this week.

Since generic "support service X" issues tend to not have a clear definition of done and the majority of resource management use cases should be covered in version 1.59.0 of the Terraform AWS Provider, I'm going to close this issue to encourage additional GitHub issues for any bug reports or feature requests. 🚀

**Comment by bflad** [comment]
The above has been released in [version 1.59.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1590-february-14-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
