### ISSUE TITLE
terraform template provider kill python process

### ISSUE THREAD

**Issue by ahujarajesh** [terraform-providers/terraform-provider-aws#7116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

#/opt/terraform/terraform -v 
Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
data "aws_ami" "ami" {

  filter {
    name   = "name"
    values = ["<AMI_NAME>"]
  }

}

resource "aws_instance" "foo" {
    ami = "${data.aws_ami.ami.id}"
    instance_type = "m5.4xlarge"
    key_name = "<env>-<role>"
    subnet_id  = "subnet-xxxxxxx"
    vpc_security_group_ids = ["sg-xxxxxxx"]
    iam_instance_profile = "<env>_<role>"
    user_data = "${data.template_file.template_foo.rendered}"
    root_block_device {
        delete_on_termination = true
    }
    tags {
        "Name" = "${format("%v-%v","foo", "<role>")}"
        "env" = "<env>"
        }
    volume_tags {
        "Name" = "${format("%v-%v","foo", "<role>")}"
        "env" = "<env>"
        }

    provisioner "local-exec" {
        command = "sudo ${path.cwd}/accept_saltkey.sh foo"
      }

    provisioner "local-exec" {
        when = "destroy"
        command = "sudo salt-key -y -d foo"
      }
}


#USERDATA
data "template_file" "template_foo" {
    template = "${file("userdata_foo.sh.tmpl")}"
    vars {
        hostname = "foo"
        saltmaster = "XXX.XX.XX.XX"
        env = "<ENV>"
        role = "<role>"
    }
}
```

### Panic Output
```hcl
# netstat -plnt
Active Internet connections (only servers)
Proto    Recv-Q     Send-Q    Local Address           Foreign Address         State       PID/Program name
tcp        0      0           0.0.0.0:22              0.0.0.0:*               LISTEN      2022/sshd       
tcp        0      0           0.0.0.0:4505            0.0.0.0:*               LISTEN      2640/python     
tcp        0      0           0.0.0.0:4506            0.0.0.0:*               LISTEN      2646/python     
tcp        0      0           0.0.0.0:443             0.0.0.0:*               LISTEN      64465/terraform-pro
tcp        0      0           0.0.0.0:8080            0.0.0.0:*               LISTEN      2476/python        

lsof -p 64465
COMMAND     PID USER   FD   TYPE             DEVICE  SIZE/OFF     NODE NAME
terraform 64465 root  cwd    DIR              202,1         0   680072 /opt/nodes/dynamic-nodes-ca-central-1/48255-foo (deleted)
terraform 64465 root  rtd    DIR              202,1      4096        2 /
terraform 64465 root  txt    REG              202,1 101366592   676601 /opt/terraform/plugin/terraform-provider-aws_v1.54.0_x4
terraform 64465 root    0u   CHR                1,3       0t0     1029 /dev/null
terraform 64465 root    2w  FIFO                0,8       0t0 12462519 pipe
terraform 64465 root    3u   CHR                1,3       0t0     1029 /dev/null
terraform 64465 root    4w  FIFO                0,8       0t0 12486738 pipe
terraform 64465 root    5w  FIFO                0,8       0t0 12486739 pipe
terraform 64465 root    6r  FIFO                0,8       0t0 12484686 pipe

```

### Expected Behavior

Terraform Provider should kill the python process running on port 443

### Actual Behavior

When Python process Called Terraform init, terraform template provider killed the python Process running on port 443 and terraform started listening on 443 port.

### Steps to Reproduce

Below Are the Details:
1.  We have a python server process running on 443.
2. When ever we need to Spawn a new instance based on our decision engine, It requests to python process running on 443 to spawn a new node.
3. So this tasks usually runs fine, but sometimes terraform template Provider kills the python server process and starts listening on port 443.
4. This issue occurs after terraform init command.

### References

* #0000

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
