### ISSUE TITLE
duplicate regions

### ISSUE THREAD

**Issue by jessefarinacci** [terraform-providers/terraform-provider-aws#7119]
https://github.com/terraform-providers/terraform-provider-aws/blob/6e8d5945203bd1432cfffc3399e8c75caa64dbb7/examples/count/variables.tf#L9-L12

several duplicate region names, looks like missing us-east-2.

**Comment by tomelliff** [comment]
Hi @jessefarinacci, I'm not sure I see what you mean here, these all look like different region names to me.

Also this is not meant to be an exhaustive list of regions as there are currently 16 regions available and is just an example of how to lookup a specific AMI in different regions.

A better, more modern example for this might rely on AMIs being tagged or named similarly in each region and then use the `aws_ami` data source instead but that goes a bit beyond the intention of this particular example which is to show creating multiple instances and registering them all with a load balancer:

https://github.com/terraform-providers/terraform-provider-aws/blob/6e8d5945203bd1432cfffc3399e8c75caa64dbb7/examples/count/main.tf#L27-L28

**Comment by jessefarinacci** [comment]
I apologize, I made a mistake. Thanks for that updated example!
