### ISSUE TITLE
Dynamo Lock Contention and HTTP 400 Error

### ISSUE THREAD

**Issue by vchokshi** [terraform-providers/terraform-provider-aws#7135]
Terraform v0.11.11
+ provider.aws v1.55.0

Problem: When using Terraform with Dynamo to have a shared lock file, if we create contention the HTTP 400 response to the second terraform apply command throws an error and and exit code of 1. 

Enhancement Suggestion: The user should receive a warning that TF was unable to continue due to an existing lock, and TF should should exit gracefully.

Steps to reproduce: 
1. Setup a shared lock with AWS Dynamo
2. in one shell, terraform apply
3. in a second shell, terraform apply.

See the error in the second shell

`Error: Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
	status code: 400, request id: L7JC2DIC4O79L0JGC9SC4Q2NCRVV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        ad45f03d-8b49-35d0-0128-6f1a403cfd7f
  Path:      <omitted>/terraform.tfstate
  Operation: OperationTypeApply
  Who:       vchokshi@iot4.net
  Version:   0.11.11
  Created:   2019-01-14 19:30:34.548419 +0000 UTC
  Info:
`
I'd be happy to look into fixing this if the community agrees and someone can help me get started! 

Vihar
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Hi @vchokshi 👋 Thanks for reporting this and sorry you are running into trouble.

Are you referring the [S3 backend with DynamoDB locking](https://www.terraform.io/docs/backends/types/s3.html)? Currently the backend and state locking code/issues for that actually live upstream in these respectively:
* https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3
* https://github.com/hashicorp/terraform/issues?q=is%3Aopen+is%3Aissue+label%3Abackend%2Fs3

I'd recommend closing this issue and opening one upstream, but please let me know if I missed something. 👍

**Comment by vchokshi** [comment]
👋@bflad. 🙏. 

[Issue #20000](https://github.com/hashicorp/terraform/issues/20000)
