### ISSUE TITLE
Error deleting EC2 Transit Gateway: IncorrectState: tgw-xxxxxxxxxxxxx has non-deleted Transit Gateway Attachments

### ISSUE THREAD

**Issue by piersf** [terraform-providers/terraform-provider-aws#7196]
### Terraform Version
`Terraform v0.11.11`
`AWS Provider version 1.54.0`

### Affected Resource(s)

* aws_ec2_transit_gateway
* aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files

modules/transit_gateway/main.tf:
```
resource "aws_ec2_transit_gateway" "transit_gateway" {
  amazon_side_asn = "${var.amazon_side_asn}"
  auto_accept_shared_attachments = "${var.auto_accept_shared_attachments}"
  default_route_table_association = "${var.default_route_table_association}"
  default_route_table_propagation = "${var.default_route_table_propagation}"
  description = "${var.description}"
  dns_support = "${var.dns_support}"
  tags = "${var.tags}"
  vpn_ecmp_support = "${var.vpn_ecmp_support}"
}
```
modules/transit_gateway/vars.tf
```
variable "description" { }

variable "amazon_side_asn" {
  default = "xxxxx"
}

variable "auto_accept_shared_attachments" {
  default = "disable"
}

variable "default_route_table_association" {
  # AWS default
  default = "enable"
}

variable "default_route_table_propagation" {
  # AWS default
  default = "enable"
}

variable "dns_support" {
  # AWS default
  default = "enable"
}

variable "tags" {
  type = "map"
}

variable "vpn_ecmp_support" {
  # AWS default
  default = "enable"
}
```

modules/transit_gateway_attachment/main.tf:
```
resource "aws_ec2_transit_gateway_vpc_attachment" "transit_gateway_vpc_attachment" {
  subnet_ids         = ["${var.subnet_ids}"]
  transit_gateway_id = "${var.transit_gateway_id}"
  vpc_id             = "${var.vpc_id}"
  dns_support		 = "${var.dns_support}"
  ipv6_support		 = "${var.ipv6_support}"
  tags 				 = "${var.tags}"
  transit_gateway_default_route_table_association = "${var.transit_gateway_default_route_table_association}"
  transit_gateway_default_route_table_propagation = "${var.transit_gateway_default_route_table_propagation}"
}
```
modules/transit_gateway_attachment/vars.tf:
```
variable "subnet_ids" {
  type = "list"
}

variable "transit_gateway_id" { }

variable "vpc_id" { }

variable "dns_support" {
  #AWS default
  default = "enable"
}

variable "ipv6_support" {
  #AWS default
  default = "disable"
}

variable "tags" {
  type = "map"
}

variable "transit_gateway_default_route_table_association" {
  #AWS default
  default = "true"
}

variable "transit_gateway_default_route_table_propagation" {
  #AWS default
  default = "true"
}
```

apps/myapp/main.tf:
```
module "transit_gateway" {
  source = "../modules/transit-gateway"
  amazon_side_asn = "xxxxx"
  description = "Transit Gateway"
  #default_route_table_association = "disable"
  default_route_table_propagation = "disable"
  tags = "${map("Name", "TGW", "Created", "dd-mm-yyyy")}"
}

module "transit_gateway_vpc_attachment" {
  source = "../modules/transit-gateway-vpc-attachment"
  subnet_ids = "${module.vpc.private_subnets}"
  transit_gateway_id = "${module.transit_gateway.id}"
  vpc_id = "${module.vpc.vpc_id}"
  tags = "${map("Name", "Attachment", "Created", "dd-mm-yyyy")}"
}
```

### Expected Behavior

Whenever i remove the above configuration from file apps/myapp/main.tf and run `plan|apply` both resource should be deleted successfully.

### Actual Behavior

What is actually happening is that Terraform fails saying that the TGW resource has non-deleted attachments. I think that the Transit Gateway resource is getting deleted at the same time or before the Transit Gateway Attachment has been deleted. The error is:

`aws_ec2_transit_gateway.transit_gateway: error deleting EC2 Transit Gateway: IncorrectState: tgw-xxxxxxxxxxxx has non-deleted Transit Gateway Attachments.`

The attachment gets deleted successfully but not the Transit Gateway.  The if I run `apply` again, the Transit Gateway resource gets deleted too.
Without knowing how the code works, i think there might be some kind of a race condition here. 

### Steps to Reproduce
1. Create the resources as above.
2. Remove after the two module calls.
1. Run `terraform apply`

**Comment by dbektas** [comment]
Hi @piersf 

terraform does not support module dependencies. If there is no specific reason for you to call creation of these two resources as a separate modules, I would put it in one single module and there you could specify dependencies between resources.

ex. for aws_ec2_transit_gateway:
`depends_on = ["aws_ec2_transit_gateway_vpc_attachment"]`

**Comment by piersf** [comment]
Closing. I'm not seeing this issue anymore after verifying dependencies between modules as explained above. I must not have had the dependencies set properly between the modules.
