### ISSUE TITLE
Data sources don't return more than one TypeSet's

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-aws#7198]
### Terraform Version

0.11.11

### Affected Resource(s)

* aws_instance data source
* aws_launch_configuration data source

### Terraform Configuration Files

```hcl
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "test" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "kshcherban-test"
  }

  ebs_block_device {
     device_name = "/dev/sdf"
     volume_size = 10
   }
   ebs_block_device {
     device_name = "/dev/sdg"
     volume_size = 20
     volume_type = "gp2"
   }
}

data "aws_instance" "test" {
  instance_id = "${aws_instance.test.id}"
}

output "instance" {
  value = "${aws_instance.test.ebs_block_device}"
}

output "data" {
  value = "${data.aws_instance.test.ebs_block_device}"
}
```

### Debug Output

```
Outputs:

data = [
    {
        delete_on_termination = 1,
        device_name = /dev/sdg,
        encrypted = 0,
        iops = 100,
        snapshot_id = ,
        volume_id = vol-014032926148b41b2,
        volume_size = 20,
        volume_type = gp2
    }
]

instance = [
    {
        delete_on_termination = 1,
        device_name = /dev/sdf,
        encrypted = 0,
        iops = 0,
        snapshot_id = ,
        volume_id = vol-061fe03c49cda6742,
        volume_size = 10,
        volume_type = standard
    },
    {
        delete_on_termination = 1,
        device_name = /dev/sdg,
        encrypted = 0,
        iops = 100,
        snapshot_id = ,
        volume_id = vol-014032926148b41b2,
        volume_size = 20,
        volume_type = gp2
    }
]
```

### Expected Behavior

data source should return the same amount of block devices

### Actual Behavior

data source returns only one device of two

### Important Factoids

Test are written incorrectly:

* https://github.com/terraform-providers/terraform-provider-aws/blob/3f3977866dc3c682fbf8bb584d5263849e00135f/aws/data_source_aws_launch_configuration_test.go#L27 - `ebs_block_device.#` must be `2`
* https://github.com/terraform-providers/terraform-provider-aws/blob/3f3977866dc3c682fbf8bb584d5263849e00135f/aws/data_source_aws_instance_test.go#L101 - data source should be checked, not the resource.

There are only two cases found. I assume there are more, and this pattern should be revised for other data sources or resources.

**Comment by ryndaniels** [comment]
Hi @kayrus - thanks for opening this bug report, and huge thanks for the work you did to discover the issue with the `Set` function! That link you found was the key to figuring out how to fix this! 👍 We've submitted a fix to the Terraform SDK [here](https://github.com/hashicorp/terraform/pull/22719) that will resolve this issue. As you also correctly noted, the tests for this data source do need some fixing as well, so I'm going to be working on getting that out the door here shortly. So this issue should be resolved soon and thanks again for your `Set` function sleuthing! 🙂
