### ISSUE TITLE
aws_route53_record failover set_identifier modification error

### ISSUE THREAD

**Issue by in4mer** [terraform-providers/terraform-provider-aws#7199]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.11
aws 1.56

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```
resource "aws_route53_record" "snafu" {
  set_identifier = "fu_bar"
  name .= "ze_germans"
  type = "CNAME"
  ttl = 10
  health_check_id = "thpbhphtphtpbhptt"
  failover_routing_policy {
    type = "PRIMARY"
  }
  records = [ "${aws_instance.raspberry_pi.tags.Name}.super-sekrit-dermane.it" ]
}
```

### Debug Output

I'm just sliiiide by this one..

### Panic Output

didn't crash

### Expected Behavior

When changing the set_identifier, the record should be deleted and then recreated with the new set_identifier

### Actual Behavior

TF attempts to destroy and re-create the record, and fails.  Due to a lack of adult supervision, the record itself appears to be completely removed from the TF state on failure.  Any attempts to plan around this resource only advise that it will be created as it does not yet exist.  Attempting to apply this plan generates low-level harrumphing and throat clearing as the creation invariably fails with "Oh, this already exists."

### Steps to Reproduce

1. Create a record with a set_identifier
2. Change the set identifier
3. Apply the change
4. Bask in the warm glow of terse AWS API error messages saying your change-request failed due to a missing JSON attribute or something
5. Plan again
6. Remark in a shocked voice how the record no longer needs to be modified, only created!
7. Start going to church again

### Important Factoids

* I'm not sure how I got here
* I lost the output from the first failure from the aws api as it fell off my scroll buffer, and I don't want to have to delete these records by hand again so they can be re-created so the brunt of the output is left as an exercise to the reader

### References

* TCP/IP Illustrated, Vol. 1-3

**Comment by paultyng** [comment]
I edited this issue as well to address tone, this is the last warning, no attacks. This repository isn't an open mic. I'll let others respond to the content of the bug report.
