### ISSUE TITLE
AWS API Gateway resource: invalid or unknown key: tags

### ISSUE THREAD

**Issue by MohamedWaly** [terraform-providers/terraform-provider-aws#7218]
Terraform Version
Terraform v0.11.11

provider.aws v1.9.0

Affected Resource(s)
aws_api_gateway_resource

Terraform Configuration Files

resource "aws_api_gateway_resource" "api_method_resource" {
  rest_api_id = "${var.api_id}"
  parent_id   = "${var.resource_id}"
  path_part   = "${var.url_path}"
  tags = "${merge(
      local.common_tags,
      map(
      "Name", "${var.env}_api_method_resource"
    ))}" 
}

Debug Output

$ terraform validate                                             

Error: aws_api_gateway_resource.api_method_resource: : invalid or unknown key: tags

Expected Behavior
Terraform should apply tags to API Gateway resource

Actual Behavior

Error appears showing "tags" is unsupported key

 Steps to Reproduce

terraform validate

**Comment by ewbankkit** [comment]
@MohamedWaly `aws_api_gateway_resource` resources cannot be tagged directly but will inherit tags from the associated `aws_api_gateway_rest_api` resource. See https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-tagging-supported-resources.html.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8744

**Comment by bflad** [comment]
Support for `aws_api_gateway_rest_api` resource tagging has been merged and will release with version 2.37.0 of the Terraform AWS Provider, by Thursday next week. 👍
