### ISSUE TITLE
Feature request: Add SnapshotSchedules for Redshift

### ISSUE THREAD

**Issue by SMR39** [terraform-providers/terraform-provider-aws#7228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Redshift API has added new calls to create periodic snapshots for the cluster and this is not supported by the provider yet. 

`CreateSnapshotSchedule: `https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateSnapshotSchedule.html
`DescribeSnapshotSchedules: `https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeSnapshotSchedules.html
`ModifyClusterSnapshotSchedule:` https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyClusterSnapshotSchedule.html
`DescribeStorage: `https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeStorage.html 
`DeleteSnapshotSchedule:`
https://docs.aws.amazon.com/redshift/latest/APIReference/API_DeleteSnapshotSchedule.html

Would really appreciate if these features can be added.

**Comment by bflad** [comment]
Two new resources have been merged to support managing this functionality:
* `aws_redshift_snapshot_schedule`
* `aws_redshift_snapshot_schedule_association`

Which will be released with version 2.23.0 of the Terraform AWS Provider in the next day or two. Thanks to @kterada0509 for the implementation.
