### ISSUE TITLE
Provider is appending a time stamp onto an aws_route_53_health_check reference_name causing an error on apply.

### ISSUE THREAD

**Issue by ebower12** [terraform-providers/terraform-provider-aws#7248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
AWS Provider v1.54.0 

### Affected Resource(s)

`aws_route_53_health_check`

### Terraform Configuration Files

```
resource "aws_route53_health_check" "volker-health-check" {
  reference_name        = "${var.domain} status"
  fqdn                  = "${var.domain}"
  port                  = 443
  type                  = "HTTPS"
  failure_threshold     = "3"
  request_interval      = "30"
}

resource "aws_cloudwatch_metric_alarm" "volker-health-check-alarm" {
  alarm_name          = "Volker Domain Status"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = "1"
  metric_name         = "HealthCheckStatus"
  namespace           = "AWS/Route53"
  period              = "60"
  threshold           = "1"
  statistic           = "Minimum"
  alarm_actions       = ["${aws_sns_topic.volker-health-check-topic.arn}"]
  dimensions {
    HealthCheckId = "${aws_route53_health_check.volker-health-check.id}"
  }
}

resource "aws_sns_topic" "volker-health-check-topic" {
  name = "volker-domain-status"
}
```

### Debug Output

https://gist.github.com/ebower12/a7b1587bf00f7b6baf432943310e1da0

### Panic Output

None that I could find

### Expected Behavior

Terraform stood up my health check, metric alarm, and sns topic.

### Actual Behavior

Terraform is appending a timestamp onto my health check reference_name resulting in a value of `staging.volker.candidlabs.io status-terraform-20190122200019880700000001` that exceeds the max length for that field, causing the apply to fail with the error

```
* module.health-checks.aws_route53_health_check.volker-health-check: 1 error(s) occurred:

* aws_route53_health_check.volker-health-check: InvalidInput: Invalid XML ; cvc-maxLength-valid: Value 'staging.volker.candidlabs.io status-terraform-20190122200019880700000001' with length = '72' is not facet-valid with respect to maxLength '64' for type 'HealthCheckNonce'.
	status code: 400, request id: 5873c542-1e80-11e9-8f99-b1eb6ac0391b
```

If I remove the `reference_name` field all together the apply builds with no issues.

### Steps to Reproduce

1. Configure a `aws_route_53_health_check` resource with a `reference_name` property
2. `terraform apply`

### Important Factoids

None

### References

None

**Comment by Freyert** [comment]
I think this may be expected behavior: https://github.com/terraform-providers/terraform-provider-aws/blob/ece3969f4bd669f52ad5d381bf183d87c9f8ee27/aws/resource_aws_route53_health_check.go#L294-L296

**Comment by timoguin** [comment]
This seems like something that could be solved with plan-time validation. At the least, this behavior should be added to the documentation for the `aws_route53_health_check` resource so it isn't a surprise.

**Comment by ebower12** [comment]
Apologies, I haven't checked in on this issue in quite a while. The explanation @Freyert gave makes sense to me. I'll close this issue.
