### ISSUE TITLE
Terraform plan encounters certificate error using AWS ec2

### ISSUE THREAD

**Issue by mog01** [terraform-providers/terraform-provider-aws#7250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

% terraform -v
2019/01/22 21:16:20 [INFO] Terraform version: 0.11.11
2019/01/22 21:16:20 [INFO] Go runtime version: go1.11.4
2019/01/22 21:16:20 [INFO] CLI args: []string{"/usr/local/bin/terraform", "-v"}
2019/01/22 21:16:20 [DEBUG] Attempting to open CLI config file: /home/moggie/.terraformrc
2019/01/22 21:16:20 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.11.11
2019/01/22 21:16:20 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=freebsd&signature=a92f73c4-c949-8eef-ac00-8392612cd2e5&version=0.11.11: x509: certificate signed by unknown authority
+ provider.aws v1.56.0

### Affected Resource(s)

* aws_ec2

### Terraform Configuration Files

% cat main.tf
provider "aws" {
        region = "eu-west-2"
        max_retries = 1
        #skip_credentials_validation = true
}

resource "aws_instance" "HelloTest" {
        ami = "ami-0cd3dfa4e37921605"
        instance_type = "t2.micro"
}

### Debug Output

https://gist.github.com/mog01/35ecbb0a7541012001d34b8e325bb8c6

### Expected Behavior

Expected it to output a plan description.

### Actual Behavior

Hangs if max retry is left as default. Or, when max retry is set to 1, produces the error output shown above.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Not that I know of. This is my first ever try at using Terraform.

### References

Possibly this:

https://github.com/hashicorp/terraform/issues/10779

Thank you in advance for your time and consideration!

**Comment by mog01** [comment]
Found out this was being caused by missing root_ca certs. Sorry for the noise.

**Comment by built2order** [comment]
@mog01 - How did you resolve this issue? Installing the certificate in your keychain or somewhere locally on your disk?
