### ISSUE TITLE
Cognito pool: SMS configuration required when it isn't.

### ISSUE THREAD

**Issue by leynebe** [terraform-providers/terraform-provider-aws#7261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v1.54.0
+ provider.local v1.1.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

```hcl
resource "aws_cognito_user_pool" "pool" {
  name = "${local.cognitoUserPoolName}"

	username_attributes = ["email"]
	auto_verified_attributes = ["email"]

  admin_create_user_config {
    allow_admin_create_user_only = true
    unused_account_validity_days = 7
  }

	verification_message_template {
		default_email_option = "CONFIRM_WITH_CODE"
	}

  mfa_configuration = "ON"

  password_policy {
    minimum_length    = 8
    require_symbols   = false
    require_numbers   = true
    require_lowercase = false
    require_uppercase = true
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = false
    name                     = "email"
    required                 = true

    string_attribute_constraints {
      min_length = 5
      max_length = 100
    }
  }
}
```

### Debug Output

```
* module.AWS-deployCognito.aws_cognito_user_pool.pool: 1 error(s) occurred:

* aws_cognito_user_pool.pool: Error creating Cognito User Pool: InvalidParameterException: SMS configuration is required when MFA is required/optional and phone_number is selected for auto verification
	status code: 400, request id: 83f2eca0-1eff-11e9-bae5-f7f46f65b4e1
```

### Expected Behavior

The Cognito pool should have been created with MFA ON and WITHOUT sms configurations. This can be done manually by ticking the `Time-based One-time Password` when configuring MFA. We also have an MFA app that generates a QR code which can be scanned by an app like Google Authenticator on your phone to authenticate yourself with in addition to the cognito user pool. So SMS or SNS isn't needed in our case.

### Actual Behavior

Terraform throws an error than SMS configuration is required when MFA is set to ON and phone_number is selected for auto verification even though phone_number is not set to be automatically verified.

### Steps to Reproduce

1. `terraform apply`

**Comment by franzwong** [comment]
I think it should be AWS problem. I tried with cloudformation and I had the same error.

```yaml
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "ON"
```

**Comment by cat-turner** [comment]
I have the same issue.

**Comment by mcgalcode** [comment]
I also ran into this.

**Comment by aeschright** [comment]
Hi folks! Sorry to hear you ran into this issue. From the [AWS support conversation](https://github.com/aws/aws-cli/issues/3876#issuecomment-456998093) linked above, it sounds like this is the default.

> When you set MfaConfiguration as ON or OPTIONAL during CreateUserPool API, it assumes that you're using SMS as MFA. If you want to use TOTP, you need to use SetUserPoolMfaConfig API.

From looking at our code, it doesn't appear that this part of the API has been implemented, and there's an earlier [feature request for the functionality](https://github.com/terraform-providers/terraform-provider-aws/issues/5420), so I'm going to close this issue and encourage you to add your 👍 there.
