### ISSUE TITLE
I need to add multiple block_device_mappings in aws_launch_template or multiple listeners to aws_elb.

### ISSUE THREAD

**Issue by vivekgkwd** [terraform-providers/terraform-provider-aws#7276]
An example would be a quicker way to explain.
I need to add multiple block_device_mappings in aws_launch_template module or multiple listeners to aws_elb module, depending on the variables I pass.
There is no way to do that.
So I have to keep the number of listeners or volumes to be fixed while writing a custom module using the resource blocks.
This is not a valid syntax :
```hcl
 resource "aws_launch_template" "lt" {
  name = "${var.Name}-lt"

  block_device_mappings {
    count = "${length(keys(var.ebs_data))}"
    device_name = "${element(keys(var.ebs_data), count.index)}"
    ebs {
      volume_size = "${element(values(var.ebs_data), count.index)}"
    }
  }
}
```
And this creates multiple launch templates :
```hcl
 resource "aws_launch_template" "lt" {
  name = "${var.Name}-lt"
  count = "${length(keys(var.ebs_data))}"

  block_device_mappings {
    
    device_name = "${element(keys(var.ebs_data), count.index)}"
    ebs {
      volume_size = "${element(values(var.ebs_data), count.index)}"
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by jwhitcraft** [comment]
Just to share, you can do it like this:

```terraform
resource "aws_launch_template" "test" {
  name_prefix = "${format("%s-lt-", "blabla")}"

  block_device_mappings = [
    {
      device_name = "/dev/sda1"

      ebs = [{
        volume_size           = "64"
        delete_on_termination = true
        volume_type           = "gp2"
      }]
    },
    {
      device_name = "/dev/sdb1"

      ebs = [{
        volume_size           = "64"
        delete_on_termination = true
        volume_type           = "gp2"
      }]
    },
  ]
}
```

**Comment by dawidmalina** [comment]
@jwhitcraft It was working in terraform 0.11 but when i'm now trying to migrate my code to 0.12 i have fallowing error:
```
Error: Unsupported argument

  on ../../../modules/test/main.tf line 175, in resource "aws_launch_template" "salt_master":
 175:   block_device_mappings = [

An argument named "block_device_mappings" is not expected here. Did you mean
to define a block of type "block_device_mappings"?
```

Do you have a clue how this should be configured in terraform 0.12?

My code looks like this:
```
  block_device_mappings = [
    {
      device_name = "/dev/sda1"

      ebs = {
        volume_size = var.VOLUME_SIZE
        volume_type = var.VOLUME_TYPE
        encrypted = true
        kms_key_id = var.KMS_KEY_ID
      }
    },
    {
      device_name = "/dev/xvdf"

      ebs = {
        volume_size = var.DOCKER_VOLUME_SIZE
        volume_type = var.DOCKER_VOLUME_TYPE
        encrypted   = true
        kms_key_id  = var.KMS_KEY_ID
      }
    }
  ]
```

**Comment by jwhitcraft** [comment]
@dawidmalina I have not upgraded that bit of code to terraform 0.12 yet.

**Comment by dawidmalina** [comment]
Looks like you just need to duplicate this sections:
```
block_device_mappings {
  device_name = "/dev/sda1"

  ebs = {
    volume_size = var.VOLUME_SIZE
    volume_type = var.VOLUME_TYPE
    encrypted = true
    kms_key_id = var.KMS_KEY_ID
  }
}

block_device_mappings {
  device_name = "/dev/xvdf"

  ebs = {
    volume_size = var.DOCKER_VOLUME_SIZE
    volume_type = var.DOCKER_VOLUME_TYPE
    encrypted   = true
    kms_key_id  = var.KMS_KEY_ID
  }
}
```

**Comment by jmcguffee** [comment]
This is probably a bit late on this, but you could use dynamics with Terraform 0.12 I found an article that described how to do this https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/
```hcl
dynamic "block_device_mappings" {
    for_each = [for volume in var.additional_volumes: {
      device_name = lookup(volume, "device_name", "" )
      delete_on_termination = lookup(volume, "delete_on_termination", false)
      encrypted = lookup(volume, "encrypted", false)
      volume_size = lookup(volume, "volume_size", 30)
      volume_type = lookup(volume, "volume_type", "gp2")
    }]
    content {
      device_name = block_device_mappings.value.device_name
      ebs {
        delete_on_termination = block_device_mappings.value.delete_on_termination
        encrypted = block_device_mappings.value.encrypted
        volume_size = block_device_mappings.value.volume_size
        volume_type = block_device_mappings.value.volume_type
      }
    }
  }
```

**Comment by ipeacocks** [comment]
@jmcguffee could you share how your `additional_volumes` structure looks?

**Comment by bflad** [comment]
Hi folks 👋  This issue is resolved in Terraform 0.12 and later, which supports new functionality in the configuration language aimed at solving problems like these. The new [`dynamic` block syntax](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) can be used to dynamically generate configuration blocks and their arguments. Given that there is a general configuration language fix for these situations, I'm going to close this issue. You all are welcome to continue the discussion here for a bit longer, although our automation will lock this conversation at some point.

If you're looking for general assistance with how to implement `dynamic` in this situation, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.

**Comment by jmcguffee** [comment]
Sorry I was busy this weekend @ipeacocks 
```
[
   {
       "device_name" = "value"
       "delete_on_termination" = false
       "encrypted" = true
       "volume_size" = 10
       "volume_type" = "gp2"
   }
   ...
]
```

**Comment by ipeacocks** [comment]
Thank you @jmcguffee.
