### ISSUE TITLE
r/ecs_service: change load_balancer to list

### ISSUE THREAD

**Issue by kl4w** [terraform-providers/terraform-provider-aws#7315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would like to modify the `load_balancer` attribute to `TypeList` instead of `TypeSet`: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ecs_service.go#L151

This would be useful for CodeDeploy blue/green deployments so you can easily put an `ignore_changes` lifecycle on the `target_group_arn` as it will switch between the 2 target groups you create with the deployment group

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource aws_lb_target_group blue {}

resource aws_lb_target_group green {}

resource aws_codedeploy_deployment_group ecs {
  load_balancer_info {
    target_group_pair_info {
      target_group {
        name = "${aws_lb_target_group.blue.name}"
      }

      target_group {
        name = "${aws_lb_target_group.green.name}"
      }
    }
  }
}

resource aws_ecs_resource codedeploy {
  deployment_controller {
    type = "CODE_DEPLOY"
  }

  load_balancer {
    target_group_arn = "${aws_lb_target_group.green.arn}"
  }

  lifecycle {
    ignore_changes = ["load_balancer.0.target_group_arn"]
  }
}
```

### References

* https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-groups-create-ecs.html
* https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ecs_service.go#L151

**Comment by msmith-hpe** [comment]
There is also a preview program active for defining multiple loadbalancers in an ECS service: https://github.com/aws/containers-roadmap/tree/master/preview-programs/ecs-multipletg-service

Would be nice to remove the MaxItems parameter to support this for people who have opted in.

**Comment by msmith-hpe** [comment]
Nevermind, just found https://github.com/terraform-providers/terraform-provider-aws/issues/9285

**Comment by bflad** [comment]
Hi folks 👋 Thank you for your interest here.

Many of the workarounds from this time this was submitted were around the lack of ECS Service supporting multiple load balancer configurations in the API. Back in August of last year ([version 2.22.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2220-august-01-2019)), support for multiple `load_balancer` configuration blocks in the `aws_ecs_service` resource was released. That functionality should negate the need for this type of breaking change. If you need to ignore these changes still, using `ignore_changes` with just the `load_balancer` argument (covering any load balancer changes) should suffice.

If there are are still lingering features or issues with the setup, please create a new GitHub issue. Thanks.
