### ISSUE TITLE
Add support for TLS on NLB

### ISSUE THREAD

**Issue by richardgavel** [terraform-providers/terraform-provider-aws#7317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the TLS related resources on network load balancers. 

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

Existing properties exist for use in an ALB. (I'm assuming Terraform will block trying to use these properties on an NLB).

### References

https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/

**Comment by tecnobrat** [comment]
I believe the requirement here is to add TLS as an allowed type on the `aws_lb_listener` resource.

This is the error I get now:

`Error: aws_lb_listener.nlb_443: expected protocol to be one of [HTTP HTTPS TCP], got TLS`

**Comment by luhn** [comment]
Also need to add TLS protocol type to `aws_lb_target_group`.

**Comment by oelbrenner** [comment]
👍

**Comment by ewbankkit** [comment]
Requires https://github.com/terraform-providers/terraform-provider-aws/pull/7331.

**Comment by bflad** [comment]
Pull request submitted: #7338

**Comment by bflad** [comment]
Support for the `TLS` protocol has been merged for the `aws_lb_listener` and `aws_lb_target_group` resources. It will release with version 1.57.0 of the Terraform AWS provider, very shortly. 🚀

**Comment by bflad** [comment]
This has been released in [version 1.57.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1570-january-26-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
