### ISSUE TITLE
Shortcut for "egress all"

### ISSUE THREAD

**Issue by chadasapp** [terraform-providers/terraform-provider-aws#7319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'm pretty sure this sounds trivial, but I can't tell you how many times I find myself copy+pasting the _exact_ same thing for an "egress-everything" rule. For example, given the following:

```hcl
resource "aws_security_group_rule" "example" {
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = "${aws_security_group.example.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}
```

You may end up applying that to tons and tons of security groups. And the only two things you change are the attached security group and resource name. It's sooooo much copy+paste boilerplate. Yeah, you could abstract it into a module, but the logical overhead of that hardly seems worth it.

### New or Affected Resource(s)
* aws_security_group_rule

### Potential Terraform Configuration

Imagine a new resource that handles this (extremely common) scenario for us! 

```hcl
resource "aws_security_group_egress_all_rule" "example" {
    security_group_id = "${aws_security_group.example.id}"
}
```

Admittedly, I haven't poked at the AWS provider code yet, but I can't imagine it'd be hard as long as this new resource could subclass the existing one and fill in most of the fields for us.

**Comment by sunilkumarmohanty** [comment]
I think the same can be easily achieved through the use of modules. Creating a separate resource for a specific configuration might not be idle as there would be expectation to create similar resources in the future. Moreover, modules are meant for theses scenarios.
