### ISSUE TITLE
Documentation Typo Report

### ISSUE THREAD

**Issue by jescalan** [terraform-providers/terraform-provider-aws#7321]
I was emailed the following report about apparent typos in the docs, but I think it may have ended up in the wrong hands. Regardless, copying it here in case anyone can take care of it!

![](https://hashicorp.intercom-mail.com/i/o/98949937/2d224e18c441a07ed2291395/image003.png)

![](https://hashicorp.intercom-mail.com/i/o/98949938/25f2f9a972a1badb0e090598/image002.png)

![](https://hashicorp.intercom-mail.com/i/o/98949939/cf9ee8213b884125225c4986/image005.png)

**Comment by jescalan** [comment]
This was the entirety of the message I got, and I can't really answer any followups, as I am not deeply familiar with terraform or the aws provider -- if you'd like I can trace back the email down it's forwarding path and try to find the original author?

**Comment by nywilken** [comment]
@jescalan thanks again for the help with this issue. I went ahead and submitted a fix for the `source_arn` typo to close out this issue. If you find out more details feel free to open up a new issue.
