### ISSUE TITLE
Feature request: Support Amazon WorkLink

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Amazon WorkLink [announced](https://aws.amazon.com/blogs/aws/amazon-worklink-secure-one-click-mobile-access-to-internal-websites-and-applications/).

New resources:
* [x] [`aws_worklink_fleet`](https://github.com/terraform-providers/terraform-provider-aws/pull/7345)
* [ ] [`aws_worklink_website_certificate_authority_association`](https://github.com/terraform-providers/terraform-provider-aws/pull/7459)

**Comment by bflad** [comment]
Keeping this open as I presume an additional resource (e.g. `aws_worklink_website_certificate_authority_association`) that handles [`AssociateWebsiteCertificateAuthority`](https://docs.aws.amazon.com/worklink/latest/api/API_AssociateWebsiteCertificateAuthority.html) has been created.

**Comment by bflad** [comment]
A new `aws_worklink_website_certificate_authority_association` resource has been merged and will release with version 2.6.0 of the Terraform AWS Provider later today. 👍

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For additional feature requests or bug reports with WorkLink functionality, please open new GitHub issues.
