### ISSUE TITLE
Support Apache Flink runtime for Kinesis Analytics

### ISSUE THREAD

**Issue by parismorali** [terraform-providers/terraform-provider-aws#7332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment it is not possible to provision a Kinesis Analytics application based on Apache Flink java app.
It would be great if TF provided an option to allow this setup.

### New or Affected Resource(s)

Presumably this would be implemented as an extension of aws_kinesis_analytics_application

* aws_kinesis_analytics_application

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_analytics_application" "test_application" {
  name = "kinesis-analytics-application-test"
  runtime= "flink-1.6"

  s3_bucket = "my-jars-bucket"
  s3_object = "my-flink-app.jar"
}
```

**Comment by ziggythehamster** [comment]
I think the proposed configuration will have to end up also having a few more sections ([CloudFormation reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalyticsv2-application.html)):

```hcl
property_group {
  id = "something"

  properties {
    key = "value"
  }
}

flink_application_configuration {
  checkpoint_configuration {
  }
  parallelism_configuration {
  }
}
```

Probably more. They structured this in a goofy way.

**Comment by jurgenweber** [comment]
this would be very handy to have in the provider, anything we can do to push it along?

**Comment by efeller** [comment]
+1
