### ISSUE TITLE
Allow setting session duration when assuming a role

### ISSUE THREAD

**Issue by hamstah** [terraform-providers/terraform-provider-aws#7333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using `assume_role` the default session of 15 mins is used (the go sdk default value).
For long running apply/plan the credentials sometime expire as the session is too short.

### New or Affected Resource(s)

* provider

### Potential Terraform Configuration

```hcl
provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::123456789012:role/SomeRole"
    session_duration = 3600
  }
}
```

### References

* https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/#AssumeRoleProvider

**Comment by bflad** [comment]
Hi folks 👋  Support for this (`duration_seconds` argument in the provider `assume_role` configuration block) has been merged and will release with version 3.0.0 of the Terraform AWS Provider, likely in about two weeks.
