### ISSUE TITLE
aws_lambda_event_source_mapping creation fails intermittently

### ISSUE THREAD

**Issue by macbutch** [terraform-providers/terraform-provider-aws#7384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.8
Your version of Terraform is out of date! The latest version is 0.11.11. 

$ terraform init
Initializing modules...
// ... snip
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "null" (1.0.0)...
- Downloading plugin for provider "template" (1.0.0)...
- Downloading plugin for provider "aws" (1.57.0)...
- Downloading plugin for provider "external" (1.0.0)...
 Terraform has been successfully initialized!
```

OK; I don't think it's necessarily related but I can update the Terraform version and report back.

### Affected Resource(s)

Fails to create aws_lambda_event_source_mapping in combination with:

* aws_lambda_function
* aws_sqs_queue

### Terraform Configuration Files

This is somewhat abbreviated:

```hcl
resource "aws_iam_role" "iam_for_lambda" {
  name = "lambda"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow"
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy" "lambda_policy" {
  name = "lambda_policy"
  role = "${aws_iam_role.iam_for_lambda.id}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    // ... snip!
    {
      "Effect": "Allow",
      "Action": [
        "sqs:SendMessage",
        "sqs:ReceiveMessage",
        "sqs:DeleteMessage",
        "sqs:GetQueueAttributes",
        "sqs:ChangeMessageVisibility"
      ],
      "Resource": "${aws_sqs_queue.outgoing_events.arn}"
    },
    {
      "Effect": "Allow",
      "Action": [
        "sqs:ListQueues"
      ],
      "Resource": "*"
    }
  ]
}
POLICY
}

resource "aws_lambda_function" "webhook" {
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  # ... snip!
}

resource "aws_sqs_queue" "outgoing_events" {
  name = "outgoing-events"

  // don't attempt reprocessing for 90s
  visibility_timeout_seconds = 90

  // message retained for 1 day
  message_retention_seconds = 86400

  max_message_size            = 2048
  delay_seconds               = 0
  fifo_queue                  = false
  content_based_deduplication = false
}

resource "aws_lambda_event_source_mapping" "outgoing_events" {
  event_source_arn = "${aws_sqs_queue.outgoing_events.arn}"
  function_name    = "${aws_lambda_function.webhook.arn}"
}
```

### Expected Behavior

Expect all the resources to be created with messages sent to SQS triggering lambda invocations.

### Actual Behavior

Sometimes it applies successfully, sometimes we get this failure:

```
Error: Error applying plan:

1 error(s) occurred:

* module.lambdas.aws_lambda_event_source_mapping.outgoing_events: 1 error(s) occurred:

* aws_lambda_event_source_mapping.outgoing_events: Error creating Lambda event source mapping: InvalidParameterValueException: The provided execution role does not have permissions to call ReceiveMessage on SQS status code: 400, request id: 5dea4a45-2480-11e9-af6e-0573653a937e
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I would like to do more testing but adding this to my lambda resource appears to work around the issue. I'd prefer not to but it's certainly something I can live with for now.

```
resource "aws_lambda_function" "webhook" {
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  # ... snip!

  provisioner "local-exec" {
    # wait for lambda permissions to compplete
    command = "sleep 30"
  }

}
```

**Comment by macbutch** [comment]
Just updating to note - the sleep seems to help but is unreliable, possibly needs to be longer.

**Comment by camlow325** [comment]
It might be interesting to see if the problem goes away if you use this:

```tf
resource "aws_lambda_event_source_mapping" "outgoing_events" {
  event_source_arn = "${aws_sqs_queue.outgoing_events.arn}"
  function_name = "${aws_lambda_function.webhook.arn}"
  depends_on = ["aws_iam_role_policy.lambda_policy"]
}
```

If the race failure is due to the policy sometimes not being setup before the mapping can be created, creating this extra dependency may help. We're going to try something similar to see if it helps in our environment.

**Comment by DrFaust92** [comment]
Hey, 

This may have been solved by https://github.com/terraform-providers/terraform-provider-aws/commit/38fdb97ba82df74a04d50f2085f49391eb6fff76

another way to address this is as @camlow325 suggests and explicitly depend on the role policy. (there might still be some IAM eventual consistency issues there as well)

Im closing this for now as the necessary retry logic for this exists , if a doc update is needed please open a PR to address this.
