### ISSUE TITLE
Request: aws_sns_topic should provide a "name" output 

### ISSUE THREAD

**Issue by jolexa** [terraform-providers/terraform-provider-aws#7399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

By default, `aws_sns_topic` generates a random name. The problem with this is there is only a way to get the arn from the provided outputs and some other resources (like aws_cloudtrail) expect a name

```hcl
resource "aws_sns_topic" "default" { }

resource "aws_cloudtrail" "trail" {
  name                             = "default"
  sns_topic_name = "${aws_sns_topic.default.name}"
  <snip>
}
```

**Comment by grimm26** [comment]
aws_sns_topic already supports a name output:
```
> $ cat main.tf
provider "aws" {}

resource "aws_sns_topic" "default" {}

output "id" {
  value = "${aws_sns_topic.default.id}"
}

output "name" {
  value = "${aws_sns_topic.default.name}"
}
> $ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_sns_topic.default
      id:     <computed>
      arn:    <computed>
      name:   <computed>
      policy: <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_sns_topic.default: Creating...
  arn:    "" => "<computed>"
  name:   "" => "<computed>"
  policy: "" => "<computed>"
aws_sns_topic.default: Creation complete after 0s (ID: arn:aws:sns:us-east-2:643927032162:terraform-20190208155401197700000001)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

id = arn:aws:sns:us-east-2:643927032162:terraform-20190208155401197700000001
name = terraform-20190208155401197700000001
```

**Comment by jolexa** [comment]
Ah, shoot. I guess I didn't catch the [documentation](https://www.terraform.io/docs/providers/aws/r/sns_topic.html#attributes-reference) properly.
> In addition to all arguments above, the following attributes are exported:

and thought only `id` & `arn` was supported!

Thanks @grimm26
