### ISSUE TITLE
aws_ebs_volume & aws_volume_attachment force new resources on every run

### ISSUE THREAD

**Issue by amkuchta** [terraform-providers/terraform-provider-aws#7407]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```shell
Terraform v0.11.11
+ provider.aws v1.57.0
```

### Affected Resource(s)

* aws_ebs_volume
* aws_volume_attachment

### Terraform Configuration Files
*__Note:__ This is a subset of the configuration file - there are multiple pairs of `aws_ebs_volume` and `aws_volume_attachment` being created, and all are configured identically to those shown below (with different resource names, obviously).*
```hcl
resource "aws_ebs_volume" "ndc2_50_xvdf" {
    availability_zone = "REDACTED"
    size              = "50"
    type              = "gp2"
    encrypted         = true
    kms_key_id        = "${data.terraform_remote_state.kms_keys_mo1.kms_key_alias_mo1_infra_ctxe_ugw1b_arn}"
    
    tags = {
        Name     = "ndc2-50 Customer Data Drive"
        Customer = "REDACTED"
        Project  = "REDACTED"
    }
}

resource "aws_volume_attachment" "ndc2_50_xvdf_attachment" {
    device_name = "xvdf"
    volume_id   = "${aws_ebs_volume.ndc2_50_xvdf.id}"
    instance_id = "${data.terraform_remote_state.ec2_encrypted_mo1.ec2_ndc2_50_encrypted_id}"
}
```

### Debug Output
[Debug Output](https://gist.github.com/amkuchta/48b9da7bd1b116b06d3ae5c186d55f1d)

### Panic Output
* N/A

### Expected Behavior

After running the initial `terraform apply`, the above referenced devices are created.  Running `terraform plan` immediately afterwards (with absolutely no modification to the `*.tf` file) should return `no changes`.

### Actual Behavior
Terraform wants to destroy and recreate the above resources on every run, even after no changes have been made to the `*.tf` file

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`
3. Curse audibly (optional)

### Important Factoids
* Running in AWS GovCloud

### References
* N/A

**Comment by Erouan50** [comment]
Hi!

I have the same issue without the attachment. Here is my very simplified infra:
```hcl
provider "aws" {
  version = "~> 2.20.0"
  region = "eu-west-1"
}

resource "aws_kms_key" "test" {}

resource "aws_kms_alias" "test" {
  name = "alias/my_alias"
  target_key_id = aws_kms_key.test.id
}

resource "aws_ebs_volume" "test" {
  availability_zone = "eu-west-1a"
  encrypted = true
  kms_key_id = aws_kms_alias.test.arn
  size = 8
}
```
The first apply creates the volume, but if I do a plan after Terraform wants to re-create it with the arn of the key and not the alias one:

```
$ ../commons/bin/terraform apply
aws_kms_key.test: Refreshing state... [id=046bd8fd-b3f2-4bb9-a39b-1efe7193dd20]
aws_kms_alias.test: Refreshing state... [id=alias/my_alias]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ebs_volume.test will be created
  + resource "aws_ebs_volume" "test" {
      + arn               = (known after apply)
      + availability_zone = "eu-west-1a"
      + encrypted         = true
      + id                = (known after apply)
      + iops              = (known after apply)
      + kms_key_id        = "arn:aws:kms:eu-west-1:162314847236:alias/my_alias"
      + size              = 8
      + snapshot_id       = (known after apply)
      + type              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_ebs_volume.test: Creating...
aws_ebs_volume.test: Still creating... [10s elapsed]
aws_ebs_volume.test: Creation complete after 11s [id=vol-05b26e72a2fa269a4]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

$ terraform plan
aws_kms_key.test: Refreshing state... [id=046bd8fd-b3f2-4bb9-a39b-1efe7193dd20]
aws_kms_alias.test: Refreshing state... [id=alias/my_alias]
aws_ebs_volume.test: Refreshing state... [id=vol-05b26e72a2fa269a4]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_ebs_volume.test must be replaced
-/+ resource "aws_ebs_volume" "test" {
      ~ arn               = "arn:aws:ec2:eu-west-1:162314847236:volume/vol-05b26e72a2fa269a4" -> (known after apply)
        availability_zone = "eu-west-1a"
        encrypted         = true
      ~ id                = "vol-05b26e72a2fa269a4" -> (known after apply)
      ~ iops              = 0 -> (known after apply)
      ~ kms_key_id        = "arn:aws:kms:eu-west-1:162314847236:key/046bd8fd-b3f2-4bb9-a39b-1efe7193dd20" -> "arn:aws:kms:eu-west-1:162314847236:alias/my_alias" # forces replacement
        size              = 8
      + snapshot_id       = (known after apply)
      - tags              = {} -> null
      ~ type              = "standard" -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```
I'm using the version 0.12 of Terraform and the version 2.20 of the AWS provider.

**Comment by amkuchta** [comment]
@Erouan50 your post led me to a workaround (thanks!)

Adding the following code to my `aws_ebs_volume` block solved the problem:

```json
lifecycle {
  ignore_changes = [ "kms_key_id" ]
}
```

It looks like the issue has something to do with the call to the KMS Key - telling it to ignore that prevents the recreation.

**Comment by ryndaniels** [comment]
Hi @amkuchta - thanks for taking the time to file this issue, and glad to hear that you were able to find the `ignore_changes` workaround for this. That would be the recommended workaround for this issue, given how the aliasing works under the hood. As such, we're going to go ahead and close this issue out, but please feel free to open another if you run into further problems!
