### ISSUE TITLE
InvalidClientTokenId: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by TommyKTheDJ** [terraform-providers/terraform-provider-aws#7418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.57.0
+ provider.random v2.0.0
+ provider.template v2.0.0
+ provider.tls v1.2.0
```

### Affected Resource(s)

Anything AWS - the issue is with the provider authentication.

### Terraform Configuration Files

```hcl
provider "aws" {
  shared_credentials_file = "${var.shared_credentials_file}"
  region                  = "${var.region}"
  profile                 = "${var.profile}"
  assume_role {
    role_arn = "${var.role_arn}"
  }
}
```

### Debug Output

https://gist.github.com/TommyKTheDJ/5353d40f8e373dcb4aa5063549c17964

### Expected Behavior

`terraform plan -out=plan` should work

### Actual Behavior

```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: The role "arn:aws:iam::accountnumber:role/FullAdmin" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid
```

### Steps to Reproduce

1. Use `saml2aws login` to authenticate and get temporary STS token with details auto-saved to ~/.aws/credentials
1. `terraform plan -out=plan`

### References

I've looked at quite a few similar issues, but none have quite had the same config and the resolutions for them haven't worked for me.

**Comment by TommyKTheDJ** [comment]
Note - I have replaced the real account number with `accountnumber` in the submission above and the gist.

**Comment by nywilken** [comment]
Hi @TommyKTheDJ I tested the provided Terraform configuration, using my credentials, to verify authenticating via a role. I've seen this particular error occur when there is no [trust relationship](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_manage_modify.html) between the user and the role that is trying to be assumed. 

Have you tried confirming that the credentials given by the saml2aws login have permission to assume the role in question?

**Comment by TommyKTheDJ** [comment]
@nywilken well, I am able to use the aws cli assuming that role, so would assume the answer is yes - I will double check though.

**Comment by TommyKTheDJ** [comment]
Update: I suspect this is an issue with compliance checks our central team have instigated - I am investigating with them.

**Comment by TommyKTheDJ** [comment]
OK, so this has been resolved.  Basically, because `saml2aws login` already handles the assuming of the role, that is not required within the .tf file.  So the below example works no problem: 
```
provider "aws" {
  shared_credentials_file = "${var.shared_credentials_file}"
  region                  = "${var.region}"
  profile                 = "${var.profile}"
}
```
Where `~/.aws/credentials` contains:
```
[saml]
aws_access_key_id        = <access_key_id>
aws_secret_access_key    = <access_key>
aws_session_token        = <token>
aws_security_token       = <token>
x_principal_arn          = arn:aws:sts::xxxxx:assumed-role/RoleName/Login
x_security_token_expires = <expiration_date/time>
```

**Comment by TommyKTheDJ** [comment]
Closing as this is not a bug or issue.

**Comment by nywilken** [comment]
@TommyKTheDJ thanks for updating the issue with the details around your investigation. I'm happy to hear that you were able to narrow down the issue. Please feel free to reach back out if you run into any other issues using the AWS provider.

**Comment by YugandharaP** [comment]
Hii,

I am getting this error.
I am trying to set access key and secret key in environment variable(windows OS)
------------------------------------------------------------------------

Error: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: 56afabf0-bcd5-11e9-bbec-5b509b30c4d6

  on main.tf line 1, in provider "aws":
   1: provider "aws" {

need help,
Thanks
