### ISSUE TITLE
Doesn't update GSI id when re-building a missing table w/ GSI

### ISSUE THREAD

**Issue by xanderflood** [terraform-providers/terraform-provider-aws#7420]
We had a dynamodb table with a GSI, and that GSI was (deliberately) deleted from the AWS console. We then did a `terraform apply` to re-build it, which succeeded. However, by recreating the table, the ID of the GSI changed. Terraform kept the original GSI ID in the statefile, so that on all subsequent plans/applies would see that the GSI ID was not correct, and attempt to delete and rebuild the GSI.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.3
AWS-provider v1.57.0

### Affected Resource(s)

* `dynamodb_terraform` with a `global_secondary_index` block

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "dynamodb-table" {
  name         = "test-table"
  billing_mode = "PAY_PER_REQUEST"

  hash_key = "UUID"

  attribute {
    name = "UUID"
    type = "S"
  }

  attribute {
    name = "CreatedDateUTC"
    type = "S"
  }

  global_secondary_index {
    name            = "CreatedAtIndex"
    hash_key        = "CreatedDateUTC"
    range_key       = "UUID"
  }
}
```

### Expected Behavior

The AWS provider should, after rebuilding the table w/ GSI, update the table's terraform state to reflect the GSI's new ID.

### Actual Behavior

The GSI ID remains unchanged, and so terraform repeatedly attempts to destroy and rebuild the GSI to reconcile the difference.

### Steps to Reproduce

1. `terraform apply` using the sample config provided above
2. Delete the resulting table or its GSI manually from the AWS console
3. `terraform apply` to rebuild it
4. `terraform plan` to see that terraform now detects erroneous changes, and wants to modify the table

**Comment by bflad** [comment]
Hi @xanderflood 👋 Sorry you are running into trouble here. Can you please provide the `terraform plan` output you are seeing? I'm having a hard time reproducing this issue.

Here's what I'm trying in our testing framework (using a test configuration that was previously available):

```
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name = "test"
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "TestTableHashKey"

  attribute {
    name = "TestTableHashKey"
    type = "S"
  }

  attribute {
    name = "TestTableGSIKey"
    type = "S"
  }

  global_secondary_index {
	name 			= "TestTableGSI"
	hash_key        = "TestTableGSIKey"
    projection_type = "KEYS_ONLY"
  }
}
```

With the following test sequence:
* Create table with GSI
* External table deletion
* Ensure table wants to be recreated
* Recreate table with GSI
* Expect no differences

The above is passing without issue. Please let us know, thanks!

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
