### ISSUE TITLE
Loadbalancer creation error message incorrectly specifies Application

### ISSUE THREAD

**Issue by jhmartin** [terraform-providers/terraform-provider-aws#7452]
When the aws_lb resource experiences an error response from AWS, it emits an error `Error creating Application Load Balancer`  even if the resource was a Network loadbalancer. This causes confusion.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
provider.aws v1.56.0

### Affected Resource(s)

* aws_lb

### Terraform Configuration Files

```
resource "aws_lb" "cms" {
  name                             = "${var.cluster_name}"
  internal                         = true
  load_balancer_type               = "network"
  enable_cross_zone_load_balancing = true
  subnets                          = ["${data.aws_subnet_ids.asg_subnets.ids}"]
}
```

### Expected Behavior

When the error occurs, state that the error occurred by either stating the specific type of loadbalancer or leave it ambiguous.

aws_lb.cms: Error creating Network Load Balancer: TooManyLoadBalancers: The maximum number of load balancers has been reached

### Actual Behavior

aws_lb.cms: Error creating Application Load Balancer: TooManyLoadBalancers: The maximum number of load balancers has been reached

### References

https://github.com/terraform-providers/terraform-provider-aws/blob/b38299d8ee00d00afc2142f882d581280a2f8a69/aws/resource_aws_lb.go#L266 seems to to be the errant line. It should either drop the `Application` qualifier or interpolate the type specified at https://github.com/terraform-providers/terraform-provider-aws/blob/b38299d8ee00d00afc2142f882d581280a2f8a69/aws/resource_aws_lb.go#L226.

**Comment by bflad** [comment]
The adjustment to return "application" or "network" in the error message based on the load balancer type has been merged and will release with version 1.59.0 of the Terraform AWS Provider, likely middle of this week.
