### ISSUE TITLE
terraform recreate resource 'aws_cognito_user_pool' every time setting required attributes

### ISSUE THREAD

**Issue by gsanchez-uz** [terraform-providers/terraform-provider-aws#7502]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v1.58.0
+ provider.local v1.1.0
+ provider.null v2.0.0

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

```hcl
//--- User Pool ---//
resource "aws_cognito_user_pool" "eks-user-pool" {
  name                     = "${var.eks_name}"
  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]

  verification_message_template {
    default_email_option = "CONFIRM_WITH_CODE"
    email_subject        = "Your verification code"
    email_message        = "Your verification code is {####}. "
  }

  admin_create_user_config {
    allow_admin_create_user_only = false
    unused_account_validity_days = 90

    invite_message_template {
      email_subject = "Your temporary password"
      email_message = "Your username is {username} and temporary password is {####}. "
      sms_message   = "Your username is {username} and temporary password is {####}. "
    }
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    name                     = "name"
    required                 = true
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    name                     = "email"
    required                 = true
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = true
    name                     = "metadata"
    required                 = false

    string_attribute_constraints {
      min_length = 1
      max_length = 2048
    }
  }

  password_policy {
    minimum_length    = 8
    require_lowercase = true
    require_numbers   = true
    require_uppercase = true
  }

  tags {
    Name    = "${var.eks_name}"
    env     = "${var.env}"
    service = "cognito"
  }
}
```

### Expected Behavior

Terraform creates a Cognito User Pool with Required Attributes 'email' and 'name' selected and it doesn't change anything if I run 'terraform apply' again..

### Actual Behavior

Terraform creates a Cognito user pool with Required Attributes 'email' and 'name' selected and it recreates (destroy-create) another Cognito User Pool each time I run 'terraform apply'.
It is like Terraform doesn't get User Pool from terraform.tfstate.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### References

* #0000

**Comment by johncblandii** [comment]
See https://github.com/terraform-providers/terraform-provider-aws/issues/4036

**Comment by nywilken** [comment]
@gsanchez-uz thanks for opening up this issue. I hope that the comment from @johncblandii  was helpful in resolving your issue. If not, the issue here is due to the missing `string_attribute_constraints` block for schema attributes of type `String`. Given the current implementation of the resource we can't mark the `string_attribute_constraint` as required, but it is indeed needed when defining schema attributes of type `String`. Otherwise, each subsequent `terraform apply` will result in recreation. FWIW this issue is also true for `number_attribute_constraints` and attributes of type `Number`.

I created #7808 to update the documentation with this information up until a fix is put in place.

**Comment by nywilken** [comment]
Documentation was added in #7808  to highlight this requirement.
