### ISSUE TITLE
apigatewayv2 (API Gateway with WebSockets) support

### ISSUE THREAD

**Issue by mcmillan** [terraform-providers/terraform-provider-aws#7514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment, we don't have support for the "new" form of API Gateway with WebSocket support. It's [supported by the Go SDK](https://docs.aws.amazon.com/cli/latest/reference/apigatewayv2/index.html) – I'm happy to have a go at implementing the relevant resources, but before I do so, is anyone else working on something similar?

**Comment by mbonig** [comment]
Duplicate? https://github.com/terraform-providers/terraform-provider-aws/issues/7004

**Comment by bflad** [comment]
Hi @mcmillan 👋 Thanks for submitting this feature request. As noted above we have a previous issue for tracking this functionality, so to consolidate efforts and discussions, I'm going to close this issue. Please upvote/subscribe to #7004.
