### ISSUE TITLE
iam user login profile: Lacking permissions lead to erratic behavior

### ISSUE THREAD

**Issue by fbreckle** [terraform-providers/terraform-provider-aws#7518]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.11

aws provider version: 1.58.0

### Affected Resource(s)

* aws_iam_user_login_profile

### Description of the bug

For least privilege, I iteratively run `terraform apply` and add the required missing permissions to the iam policy until the `terraform apply` succeeds.

When doing this for user and initial-password creation (via the aws_iam_user_login_profile resource), I noticed that at one point `terraform apply` succeeds but an initial password is not set.
After some testing, I found that this behavior occurs when the terraform is run without the `iam:GetLoginProfile` permissions.

### Expected Behavior

Terraform should not report creation of the resource as successful. Instead it should show the error message.

### Actual Behavior

Terraform succeeds, but the encrypted_password property is empty.

### Steps to Reproduce

Create a aws_iam_user_login_profile resource with a user/role that does not have the aws permission "iam:GetLoginProfile" and `terraform apply`.

### References

* #7519

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 1.59.0 of the Terraform AWS Provider, in the next hour or so. 👍

**Comment by bflad** [comment]
This has been released in [version 1.59.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1590-february-14-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
