### ISSUE TITLE
Dollar sign $ in security group cannot be found by name in data source

### ISSUE THREAD

**Issue by nitrocode** [terraform-providers/terraform-provider-aws#7532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.11

### Affected Resource(s)

* aws_security_groups

### Terraform Configuration Files

```hcl
data "aws_security_groups" "MyOfficeSSH" {
  filter {
    name   = "group-name"
    values = ["MyOffice$SSH"]
    # values = ["MyOffice\$SSH"] # this does not work either
    # values = ["MyOffice\\$SSH"] # this does not work either
    # values = ["MyOffice\\\$SSH"] # this does not work either
    # values = ["MyOffice\\\\$SSH"] # this does not work either
  }
}
```

In AWS Console -> EC2 -> Security Groups, if I search for the same, I cannot find it but if I escape the dollarsign I can find it e.g. `"MyOffice\$SSH"`. Escaping it in terraform does not work.

### Expected Behavior

Security group should have been found

### Actual Behavior

No security group was found

### Steps to Reproduce

1. `terraform apply`

### Workaround

To avoid a new security group ID

1. Change the tag Name's value
2. Filter on the `tag:Name` instead of `group-name`

```
data "aws_security_groups" "MyOfficeSSH" {
  filter {
    name   = "tag:Name"
    values = ["MyOfficeSSH"]
  }
}
```

**Comment by nywilken** [comment]
@nitrocode thanks for the provided configuration and sorry that you are having trouble with the data source query. While there isn't support for the creation of security groups containing the `$` character in the group name, the data resource should support it when querying. 

Just to rule out any bugs I went ahead and tested this query against a couple of test security groups. 

```
> terraform apply 
var.group_name
  Enter a value: allow$TEST

data.aws_security_groups.test: Refreshing state...
data.aws_security_group.selected: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

group_ids = [
    sg-0b4fed14956947bf2
]
group_name = allow$TEST

> terraform apply                                                                                     
var.group_name
  Enter a value: MyOffice$SSH

data.aws_security_groups.test: Refreshing state...
data.aws_security_group.selected: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

group_ids = [
    sg-0c9856b163073a4da
]
group_name = MyOffice$SSH
````

A good general workaround, if you are unable to match against the exact name, would be to try using the glob operator `*` within the group-name filter. 

```
data "aws_security_groups" "MyOfficeSSH" {
  filter {
    name   = "group-name"
    values = ["MyOffice*SSH"]
  }
}
```

**Comment by nitrocode** [comment]
That's strange that it wasn't working for me. I removed the $ sign and its working correctly now. I'll keep the asterisk glob operator in mind if I see that again. Thank you.
