### ISSUE TITLE
New resource: AWS Elemental MediaConvert

### ISSUE THREAD

**Issue by cdeneen-peloton** [terraform-providers/terraform-provider-aws#7533]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New resource(s) for AWS Elemental MediaConvert

### New or Affected Resource(s)

AWSElementalMediaConvert

**Comment by bflad** [comment]
Hi folks 👋 A new `aws_media_convert_queue` resource has been merged and will release with version 2.42.0 of the Terraform AWS Provider, next week. Thanks to @kterada0509 for the implementation there. 👍 

These types of "support X service" issues tend to lack a clear definition of done, so we are going to opt to close this issue in preference of specific resource/data source/feature request asks going forward with the MediaConvert service. I pre-created the following that may be of interest:

* Feature Request: MediaConvert Certificate Resource #11186
* Feature Request: MediaConvert Job Template Resource #11189
* Feature Request: MediaConvert Preset Resource #11190

If there is anything else you are looking for with this service, please feel free to file a new [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) following the issue template. Thanks!
