### ISSUE TITLE
Add support for Kinesis Custom Amazon S3 Prefixes

### ISSUE THREAD

**Issue by jinhokong** [terraform-providers/terraform-provider-aws#7548]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Feb 12, 2019, it seems that Kinesis Custom Amazon S3 Prefixes are supported but it does not seem to have been added to Terraform. I want you to add it.

### New or Affected Resource(s)

* aws_kinesis_firehose_delivery_stream
https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_firehose_delivery_stream" "extended_s3_stream" {
  name        = "terraform-kinesis-firehose-extended-s3-test-stream"
  destination = "extended_s3"

  extended_s3_configuration {
    role_arn   = "${aws_iam_role.firehose_role.arn}"
    bucket_arn = "${aws_s3_bucket.bucket.arn}"
    s3_custom_prefix ="year=YYYY/month=MM/day=DD"  # MayBe?

    processing_configuration {
      enabled = "true"

      processors {
        type = "Lambda"

        parameters {
          parameter_name  = "LambdaArn"
          parameter_value = "${aws_lambda_function.lambda_processor.arn}:$LATEST"
        }
      }
    }
  }
}
```

### References

https://aws.amazon.com/ko/about-aws/whats-new/2019/02/amazon-kinesis-data-firehose-announces-support-for-custom-amazon-s3-prefixes/

**Comment by mannbiher** [comment]
Hi, This is already supported using existing prefix property. Please note you need to add error_output_prefix   also if you specify custom prefix. E.g.
https://docs.aws.amazon.com/firehose/latest/APIReference/API_ExtendedS3DestinationConfiguration.html
https://docs.aws.amazon.com/firehose/latest/dev/s3-prefixes.html

`
prefix = "year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/"

error_output_prefix = "error/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/"
`
