### ISSUE TITLE
if you change the lb target group dont was recreated

### ISSUE THREAD

**Issue by rafilkmp3** [terraform-providers/terraform-provider-aws#7581]
if you change the name of LB it will be recreated mbut the Target group associated cant be migrated to new lb 

steps to reproduce 

1 create a lb, listerner rule and target group 
2 change the lb name and face a dead end 

```
aws_lb_listener_rule.listerner_rule: Error creating LB Listener Rule: TargetGroupAssociationLimit: Target group 'arn:aws:elasticloadbalancing:sa-east-1:<>ACOUNTNUMBER>:targetgroup/tg-poetica-ge/77578dc53ae2e7c8' cannot be associated with more than one load balancer
        status code: 400, request id: 5e73b736-314f-11e9-9ae6-e9bcf0ff8a5b
```

**Comment by aeschright** [comment]
Hi @rafilkmp3 👋 Sorry you ran into problems there! Without the version of Terraform you're using and your config file, we're unable to investigate this. I'm closing the issue, but if you're still seeing problems, please open a new bug report and make sure to include all of the requested details. Thanks!
