### ISSUE TITLE
Checking/Un-checking Remove Encryption on Codebuild Artifacts does not count towards the delta

### ISSUE THREAD

**Issue by vibhuyadav** [terraform-providers/terraform-provider-aws#7582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform Enterprise
### Affected Resource(s)

* aws_codebuild_project

### Expected Behavior

checking and unchecking encryption is not detected in codebuild artifacts by terraform

### Actual Behavior

Should detect the change

**Comment by bflad** [comment]
The fixes for having the `aws_codebuild_project` resource `artifacts` configuration block perform better drift detection and updates have been merged and will release with version 2.22.0 of the Terraform AWS Provider, tomorrow. 👍
