### ISSUE TITLE
ValidationError when using CloudWatch alarm with count ( AND alarm_actions !! )

### ISSUE THREAD

**Issue by antoiner77** [terraform-providers/terraform-provider-aws#7590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version 
Last version available (MacOs)

### Affected Resource(s)

* aws_cloudwatch_metric_alarm
* aws_route53_health_check

### Terraform Configuration Files

```hcl
resource "aws_route53_health_check" "default" {
  count = "${length(var.aws_route53_health_check_fqdns)}"

  failure_threshold = "3"
  fqdn              = "${element(slice(split("/", element(var.aws_route53_health_check_fqdns, count.index)), 0, 1), 0)}"
  measure_latency   = true
  port              = 443
  request_interval  = "30"
  resource_path     = "/${join("/", slice(split("/", element(var.aws_route53_health_check_fqdns, count.index)), 1, length(split("/", element(var.aws_route53_health_check_fqdns, count.index)))))}"
  type              = "${var.aws_alb_listener_protocol}"
}

resource "aws_cloudwatch_metric_alarm" "alarm" {
  provider = "aws.global"
  count               = "${length(var.aws_route53_health_check_fqdns)}"
  alarm_name          = "${aws_route53_health_check.default.*.id[count.index]}-TTFB"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "2"
  metric_name         = "TimeToFirstByte"
  namespace           = "AWS/Route53"
  period              = "60"
  statistic           = "Average"
  threshold           = "200"
  alarm_description   = "Check on endpoint TTFB"
  alarm_actions         = ["${aws_sns_topic.default.arn}"]
  dimensions = {
    HealthCheckId = "${aws_route53_health_check.default.*.id[count.index]}"
  }
}
```

### Debug Output

```
Error: Error applying plan:

3 error(s) occurred:

* aws_cloudwatch_metric_alarm.alarm[0]: 1 error(s) occurred:

* aws_cloudwatch_metric_alarm.alarm.0: Updating metric alarm failed: ValidationError: 
	status code: 400, request id: 908bbf82-3362-11e9-a5af-0100cf55d728
* aws_cloudwatch_metric_alarm.alarm[2]: 1 error(s) occurred:

* aws_cloudwatch_metric_alarm.alarm.2: Updating metric alarm failed: ValidationError: 
	status code: 400, request id: 908f1b55-3362-11e9-b581-29b3b7435e7c
* aws_cloudwatch_metric_alarm.alarm[1]: 1 error(s) occurred:

* aws_cloudwatch_metric_alarm.alarm.1: Updating metric alarm failed: ValidationError: 
	status code: 400, request id: 9090efd6-3362-11e9-a2aa-419ea3af7bfc

```

### Expected Behavior

All alarm should have been created with the SNS action, It work without the alarm_actions 

### Actual Behavior

If I set alarm_actions to the SNS Topic, it failed

### Steps to Reproduce

try it with the code here, define var.aws_route53_health_check_fqdns with 3 or more domain name

1. `terraform apply`

**Comment by aeschright** [comment]
Hi @antoiner77 👋 Sorry you ran into problems there. The error message you have doesn't give us much to go on, so to debug this I think you'll have to upgrade to Terraform 0.12 which has better error reporting. If you're still seeing the problem when using the current versions of Terraform and the AWS provider, please open a new bug report so we can investigate. Thanks!
