### ISSUE TITLE
Diffs didn't match during apply

### ISSUE THREAD

**Issue by sandor11** [terraform-providers/terraform-provider-aws#7595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`0.11.11`

### Affected Resource(s)

Data Sources
`aws_elb`

Resources
`aws_load_balancer_listener_policy`

### Terraform Configuration Files

```hcl
data "aws_elb" "default" {
  name = "${aws_elastic_beanstalk_environment.default.load_balancers.0}"
}

resource "aws_load_balancer_policy" "https" {
  load_balancer_name = "${aws_elastic_beanstalk_environment.default.load_balancers.0}"
  policy_name        = "${var.stack_name}-${var.env_name}-elb-https-policy"
  policy_type_name   = "SSLNegotiationPolicyType"

  policy_attribute = {
    name  = "Reference-Security-Policy"
    value = "ELBSecurityPolicy-2016-08"
  }
}

resource "aws_load_balancer_listener_policy" "https" {
  load_balancer_name = "${aws_elastic_beanstalk_environment.default.load_balancers.0}"
  load_balancer_port = 443

  policy_names = [
    "${aws_load_balancer_policy.https.policy_name}",
  ]
}
```

### Debug Output

https://gist.github.com/sandor11/6d75e0e7639ddf25354efe8864e3f91c

### Expected Behavior

In this case I was expecting terraform to simply update an RDS instance which is in another part of the stack. There were NO changes made to this area of the config, haven't been for some time. We have started seeing this in a few different environments, we have no explanation as no one is making any changes.

### Actual Behavior

It appears as though Diff One, has not found anything related to load_balancer_name, which is not explainable. And then even now, in diff two, it has decided this is an error. Why would there not be an attempt to simply move the infrastructure to the declared state? I add attributes to other resources without a problem... how has this become out of sync?

### Steps to Reproduce

Honestly, we are experiencing the issue intermittently, so reproduction is not really possible. I would be happy to understand what this error even means, any why we are seeing it to begin with.

### Important Factoids

Importantly, we cannot simply run this again to fix the problem. This will actually now get stuck in a deployment loop where the old load balancer cannot be found, causing another error, and the entire application deployments get stuck. I previously got around this by editing the .tfstate file MANUALLY! and applying the new load balancer names. This cannot be good, and we have no want to continue that, besides we then need to rename a lot of the application stack to get the right mix of resource destroy/create.

Also worth noting, we have ben running terraform for about 8 months now, with almost no issue. So we hope to find out what we are doing which might be causing this issue.

**Comment by aeschright** [comment]
Hi @sandor11 👋 Unfortunately, in versions of Terraform pre-0.12 that error doesn't really give us enough information to know what's happening -- I can see that's annoying for you too! If you upgrade to the most recent Terraform and AWS provider releases and hit this again, please open a new bug report with the details. I'm closing this since there's no further action. Thanks!
