### ISSUE TITLE
Redshift node number change doesn't use elastic resize

### ISSUE THREAD

**Issue by rednuht** [terraform-providers/terraform-provider-aws#7599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.57.0
```

### Affected Resource(s)

* aws_redshift_cluster

### Expected Behavior

According to [the API](https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#Redshift.ResizeCluster) elastic resize should be the default resize method. One would expect modification of `number_of_nodes` that is within the conditions for an elastic resize to actually trigger an elastic resize.

### Actual Behavior

Classic resize was triggered.

### Steps to Reproduce

Simply change the `number_of_nodes` and do `terraform apply`.

**Comment by aeschright** [comment]
Hi @rednuht ! Thanks for reporting this problem. Do you have a config you can share that demonstrates the issue?

**Comment by aeschright** [comment]
Since we didn't receive a response, I'm going to close this issue. If there's still a problem that hasn't been addressed, please open a new bug report and include the requested details. Thanks!
