### ISSUE TITLE
r/aws_ec2_client_vpn_endpoint: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging `aws_ec2_client_vpn_endpoint` resources added in [AWS SDK v1.16.35](https://github.com/aws/aws-sdk-go/releases/tag/v1.16.35).

**Comment by bflad** [comment]
Support for `tags` with the `aws_ec2_client_vpn_endpoint` resource has been merged and will release with version 2.1.0 of the Terraform AWS Provider, likely middle of this week.

**Comment by bflad** [comment]
This has been released in [version 2.1.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#210-march-07-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
