### ISSUE TITLE
Multiple destinations for S3 bucket replications

### ISSUE THREAD

**Issue by vibhuyadav** [terraform-providers/terraform-provider-aws#7610]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To have one S3 bucket have multiple replications

### New or Affected Resource(s)

* aws_s3_bucket

### Potential Terraform Configuration

```
resource "aws_s3_bucket" "abcd_bucket" {
  bucket        = "${var.artifacts_bucket_name}-${var.aws_account_alias}-${var.aws_account_region}"
  region        = "${var.aws_account_region}"
  acl           = "private"
  force_destroy = true

  versioning {
    enabled = true
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        kms_master_key_id = "${aws_kms_alias.cmk-main-alias.arn}"
        sse_algorithm     = "aws:kms"
      }
    }
  }

  replication_configuration {
    role = "${aws_iam_role.replication-role.arn}"

    rules {
      id     = "replication-rule"
      priority = "1"
      status = "Enabled"

      destination {
        bucket        = "${aws_s3_bucket.replicated-bucket.arn}"
        replica_kms_key_id = "${aws_kms_alias.cmk-replicated-alias.arn}"
        storage_class = "STANDARD"
      }
      source_selection_criteria {
        sse_kms_encrypted_objects {
          enabled = true
        }
      }
    }

    rules {
      id     = "replication-rule-us-west-1"
      status = "Enabled"

      destination {
        bucket        = "${aws_s3_bucket.replicated-bucket-us-west-1.arn}"
        storage_class = "STANDARD"
      }
    }

    rules {
      id     = "replication-rule-us-west-2"
      status = "Enabled"

      destination {
        bucket        = "${aws_s3_bucket.replicated-bucket-us-west-2.arn}"
        storage_class = "STANDARD"
      }
    }
  }
}
```

Currently running above results in Error:
```
aws_s3_bucket.abcd_bucket: Error putting S3 replication configuration: InvalidRequest: The destination bucket must be same for all rules
```

**Comment by bflad** [comment]
Hi @vibhuyadav 👋 Thanks for submitting this.

The error you are receiving there is from the S3 API and seems to represent an unsupported S3 Bucket configuration. The [S3 Cross-Region Replication documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-add-config.html#crr-config-optional-dest-config) briefly mentions this limitation:

> In the destination configuration, you specify the bucket where you want Amazon S3 to replicate objects. You can configure CRR to replicate objects from one source bucket to one destination bucket. If you add multiple rules in a replication configuration, all of the rules must identify the same destination bucket.

Since the Terraform AWS Provider resource is limited by the available S3 service functionality in this case, there is nothing to be done for this feature request and I'm going to close this issue for now. You will need to reach out to AWS Support or a Technical Account Manager (if you have one) to submit a feature request to the S3 service. If the service functionality is changed later to support this, we can reopen this issue. 👍

**Comment by vibhuyadav** [comment]
Thanks @bflad ! You are right. I will have to find out a way to replicate to multiple buckets in multiple regions in another fashion. (Hint - S3A -> S3B -> S3C -> S3D)

**Comment by bfung** [comment]
There's no daisy chaining of bucket replication: https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-troubleshoot.html
```
Amazon S3 doesn't replicate an object in a source bucket that is a replica created by another replication configuration. For example, if you set replication configuration from bucket A to bucket B to bucket C, Amazon S3 doesn't replicate object replicas in bucket B to bucket C.
```
