### ISSUE TITLE
terraform(v 0.11.11) says "missing authentication token" inconsistently while creating aws resources

### ISSUE THREAD

**Issue by karsschumi** [terraform-providers/terraform-provider-aws#7613]
terraform says "missing authentication token" while creating aws resources even though i have provided accs key and secret key in the aws provider.

again if i run the same, it works but sometimes it fails
_It is not a consistent issue, its an intermittent one please find the log below_
---------------------------------------------------------------------------------------------
C:\Users\karhc\SkynetTerraform\terraform-aws-awsgateway>terraform plan

Warning: aws_api_gateway_api_key.MyDemoKey: "stage_key": [DEPRECATED] Since the API Gateway usage plans feature was launched on August 11, 2016, usage plans are now required to associate an API key with an API stage

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_api_gateway_rest_api.MyDemoAPI: Refreshing state... (ID: p040o0gyeh)
aws_api_gateway_resource.MyDemoResource: Refreshing state... (ID: jfngf3)
aws_api_gateway_method.MyDemoMethod: Refreshing state... (ID: agm-p040o0gyeh-jfngf3-POST)
aws_api_gateway_integration.MyDemoIntegration: Refreshing state... (ID: agi-p040o0gyeh-jfngf3-POST)
aws_lambda_permission.apigw_lambda: Refreshing state... (ID: AllowExecutionFromAPIGateway)
aws_api_gateway_deployment.MyDemoDeployment: Refreshing state... (ID: 4d5i4p)

Error: Error refreshing state: 1 error(s) occurred:

* aws_api_gateway_deployment.MyDemoDeployment: 1 error(s) occurred:

* aws_api_gateway_deployment.MyDemoDeployment: aws_api_gateway_deployment.MyDemoDeployment: **MissingAuthenticationTokenException**: Missing Authentication Token
        status code: 403, request id: 48f3e35d-34f7-11e9-bd3c-fd306a7935e2

C:\Users\karhc\SkynetTerraform\terraform-aws-awsgateway>terraform plan

Warning: aws_api_gateway_api_key.MyDemoKey: "stage_key": [DEPRECATED] Since the API Gateway usage plans feature was launched on August 11, 2016, usage plans are now required to associate an API key with an API stage

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_api_gateway_rest_api.MyDemoAPI: Refreshing state... (ID: p040o0gyeh)
aws_api_gateway_resource.MyDemoResource: Refreshing state... (ID: jfngf3)
aws_api_gateway_method.MyDemoMethod: Refreshing state... (ID: agm-p040o0gyeh-jfngf3-POST)
aws_lambda_permission.apigw_lambda: Refreshing state... (ID: AllowExecutionFromAPIGateway)
aws_api_gateway_integration.MyDemoIntegration: Refreshing state... (ID: agi-p040o0gyeh-jfngf3-POST)
aws_api_gateway_deployment.MyDemoDeployment: Refreshing state... (ID: 4d5i4p)
aws_api_gateway_usage_plan.MyUsagePlan: Refreshing state... (ID: foxll4)
aws_api_gateway_api_key.MyDemoKey: Refreshing state... (ID: jr923ihgo5)

Error: Error refreshing state: 1 error(s) occurred:

* aws_lambda_permission.apigw_lambda: 1 error(s) occurred:

* aws_lambda_permission.apigw_lambda: aws_lambda_permission.apigw_lambda: MissingAuthenticationTokenException: Missing Authentication Token
        status code: 403, request id: 4faa7b8e-34f7-11e9-898f-25f8660d258f

C:\Users\karhc\SkynetTerraform\terraform-aws-awsgateway>terraform plan

Warning: aws_api_gateway_api_key.MyDemoKey: "stage_key": [DEPRECATED] Since the API Gateway usage plans feature was launched on August 11, 2016, usage plans are now required to associate an API key with an API stage

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: error validating provider credentials: error calling sts:GetCallerIdentity: MissingAuthenticationToken: Request is missing Authentication Token
        status code: 403, request id: 59506cf6-34f7-11e9-8546-438e64a0c26f

C:\Users\karhc\SkynetTerraform\terraform-aws-awsgateway>terraform plan

Warning: aws_api_gateway_api_key.MyDemoKey: "stage_key": [DEPRECATED] Since the API Gateway usage plans feature was launched on August 11, 2016, usage plans are now required to associate an API key with an API stage

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_api_gateway_rest_api.MyDemoAPI: Refreshing state... (ID: p040o0gyeh)
aws_api_gateway_resource.MyDemoResource: Refreshing state... (ID: jfngf3)
aws_api_gateway_method.MyDemoMethod: Refreshing state... (ID: agm-p040o0gyeh-jfngf3-POST)
aws_api_gateway_integration.MyDemoIntegration: Refreshing state... (ID: agi-p040o0gyeh-jfngf3-POST)
aws_lambda_permission.apigw_lambda: Refreshing state... (ID: AllowExecutionFromAPIGateway)
aws_api_gateway_deployment.MyDemoDeployment: Refreshing state... (ID: 4d5i4p)
aws_api_gateway_usage_plan.MyUsagePlan: Refreshing state... (ID: foxll4)
aws_api_gateway_api_key.MyDemoKey: Refreshing state... (ID: jr923ihgo5)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_api_gateway_integration_response.MyDemoIntegrationResponse
      id:                                 <computed>
      http_method:                        "POST"
      resource_id:                        "jfngf3"
      response_templates.%:               "1"
      response_templates.application/xml: "#set($inputRoot = $input.path('$'))\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<message>\n    $inputRoot.body\n</message>\n"
      rest_api_id:                        "p040o0gyeh"
      status_code:                        "200"

  + aws_api_gateway_method_response.200
      id:                                 <computed>
      http_method:                        "POST"
      resource_id:                        "jfngf3"
      rest_api_id:                        "p040o0gyeh"
      status_code:                        "200"

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

C:\Users\karhc\SkynetTerraform\terraform-aws-awsgateway>
C:\Users\karhc\SkynetTerraform\terraform-aws-awsgateway>terraform plan

Warning: aws_api_gateway_api_key.MyDemoKey: "stage_key": [DEPRECATED] Since the API Gateway usage plans feature was launched on August 11, 2016, usage plans are now required to associate an API key with an API stage

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_api_gateway_rest_api.MyDemoAPI: Refreshing state... (ID: p040o0gyeh)
aws_api_gateway_resource.MyDemoResource: Refreshing state... (ID: jfngf3)
aws_api_gateway_method.MyDemoMethod: Refreshing state... (ID: agm-p040o0gyeh-jfngf3-POST)
aws_api_gateway_integration.MyDemoIntegration: Refreshing state... (ID: agi-p040o0gyeh-jfngf3-POST)
aws_lambda_permission.apigw_lambda: Refreshing state... (ID: AllowExecutionFromAPIGateway)

Error: Error refreshing state: 1 error(s) occurred:

* aws_api_gateway_integration.MyDemoIntegration: 1 error(s) occurred:

* aws_api_gateway_integration.MyDemoIntegration: aws_api_gateway_integration.MyDemoIntegration: **MissingAuthenticationTokenException: Missing Authentication Token**
        status code: 403, request id: a776d51d-34f7-11e9-89e3-4f42376c009b

**Comment by kapilt** [comment]
per https://stackoverflow.com/questions/48955987/missing-authentication-token-on-unauthenticated-method

terraform needs to recreate the deployment whenever its constituent parts (methods, etc) change.

**Comment by aeschright** [comment]
Hi @karsschumi 👋 Sorry you ran into problems there. Without your config file there we can't look into the problem further, so I'm going to close the issue. If you're still having trouble, please open a new bug report and make sure to include all of the requested details. Thanks!
