### ISSUE TITLE
Terraform AWS provider fails with data.aws_redshift_service_account.main: Unknown region ("us-gov-east-1")

### ISSUE THREAD

**Issue by unixengineer** [terraform-providers/terraform-provider-aws#7629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.11
+ provider.aws v1.59.0
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.template v2.0.0

### Affected Resource(s)
aws_redshift_service_account

### Terraform Configuration Files

```hcl
data "aws_redshift_service_account" "main" {}
```

### Debug Output

Error: Error refreshing state: 1 error(s) occurred:

* module.aws_logs.data.aws_redshift_service_account.main: 1 error(s) occurred:

* module.aws_logs.data.aws_redshift_service_account.main: data.aws_redshift_service_account.main: Unknown region ("us-gov-east-1")

### Expected Behavior

Should have got the account ID

### Actual Behavior

Errors out:
data.aws_redshift_service_account.main: Unknown region ("us-gov-east-1")

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Region is US-gov-east-1.

**Comment by bflad** [comment]
Pull request submitted: #7635

**Comment by bflad** [comment]
Support for the AWS GovCloud (US) regions in this data source has been merged and will release with version 2.1.0 of the Terraform AWS Provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 2.1.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#210-march-07-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
