### ISSUE TITLE
Investigate Upstream AppMesh API Changes

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#7659]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Potentially Affected Resource(s)

* aws_appmesh_mesh
* aws_appmesh_route
* aws_appmesh_virtual_node
* aws_appmesh_virtual_router

### Description

AWS has publicly announced potentially breaking changes to the AppMesh service API: https://github.com/awslabs/aws-app-mesh-examples/issues/92

We will need to investigate the proposed upstream changes and determine a path forward for the existing Terraform AWS Provider resources.

**Comment by bflad** [comment]
@ewbankkit you are likely interested in this ☝️

**Comment by bcelenza** [comment]
I'd be happy to pull request the required changes for AWS App Mesh. 

I would also love to understand how this change impacts current users of the Terraform integration with App Mesh, and will keep an eye on this issue during the comment period.

**Comment by ewbankkit** [comment]
We should probably start with a note in the documentation stating that the [`aws_appmesh_virtual_node`](https://www.terraform.io/docs/providers/aws/r/appmesh_virtual_node.html) and [`aws_appmesh_virtual_router`](https://www.terraform.io/docs/providers/aws/r/appmesh_virtual_router.html) resources will change in an upcoming release and link to the AWS GH issue.

**Comment by ewbankkit** [comment]
@bcelenza I'm totally happy for you to do the PR/collaborate as necessary.

**Comment by bcelenza** [comment]
Thanks @ewbankkit! Opened a PR for the doc changes.

**Comment by ewbankkit** [comment]
I added some [comments](https://github.com/awslabs/aws-app-mesh-examples/issues/92#issuecomment-467061031) to the announcement.

My thoughts:
* Add a new `aws_appmesh_virtual_service` resource (with `terraform import` functionality as Amazon have already created these)
* Modify the `aws_appmesh_virtual_node` and `aws_appmesh_virtual_router` resources with the relevant changes. State migration should be straightforward

My only concerns are around the short deprecation notice. I don't think we can follow the [published best practice](https://www.terraform.io/docs/extend/best-practices/deprecations.html) of doing a major release just for this and I'm not sure how this fits in with the provider _v2.0.0_ release timetable, but App Mesh is a preview service so there really should be reduced expectations around API stability.

**Comment by bcelenza** [comment]
Agree with your thoughts. I've read through the best practices, hoping to confirm my assumptions below.

Using VirtualNode as an example of a resource:

* `spec.serviceDiscovery.dns.serviceName` to `hostname` appears to be supported via [Renaming a Required Attribute](https://www.terraform.io/docs/extend/best-practices/deprecations.html#renaming-a-required-attribute)?
* `spec.backends` does not have a clear migration path given the structure change. Does Terraform have a mechanism for this sort of migration? It would be safe to assume that a string passed would be interpreted as a VirtualService name.

**Comment by ewbankkit** [comment]
@bcelenza Terraform has robust [state migration](https://www.terraform.io/docs/extend/resources.html#state-migrations) functionality so we should be able to rewrite state files created with the initial API version into a format that reflects the new API version:
* `service_name` -> `hostname`
* `backends` changes from list of `virtual_service`s which are themselves a simple map with a single `virtual_service_name` string element

We should be able to find an suitable example in the code.

**Comment by ewbankkit** [comment]
Additional proposed API changes:
* https://github.com/awslabs/aws-app-mesh-examples/issues/94

**Comment by ewbankkit** [comment]
@bcelenza Is there a newer API model JSON with the latest proposed changes?

**Comment by bcelenza** [comment]
@ewbankkit Not yet -- we're still waiting for the last pieces of VirtualRouter listeners to reach production before we distribute an updated JSON. ETA Tuesday of next week, if I had to guess.

**Comment by bcelenza** [comment]
Updated Go SDK is now available as [v1.17.13](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.13).

**Comment by ewbankkit** [comment]
@bcelenza I am working right now on a draft PR based on the original `app-mesh-2019-01-25.trial.json` model changes. I'll rebase it on the new AWS SDK.

**Comment by bcelenza** [comment]
@ewbankkit that's great. keep in mind your JSON file doesn't have the VirtualRouter listeners example. Might be worth jumping over to the new Go SDK because of that.

**Comment by ewbankkit** [comment]
Will do, just wanted to get my current WIP pushed: https://github.com/terraform-providers/terraform-provider-aws/pull/7858.

**Comment by ewbankkit** [comment]
@bcelenza To clarify dependencies (I saw some error messages during testing):
* If a virtual service has a virtual node or virtual router provider then that virtual node or virtual router cannot be deleted before virtual service is deleted, correct?
* The dependency graph is then
  * _Mesh_ => _Virtual Node_ => _Virtual Service_  or
  * _Mesh_ => _Virtual Router_ => _Virtual Service_

**Comment by bcelenza** [comment]
> @bcelenza To clarify dependencies (I saw some error messages during testing):
> 
> * If a virtual service has a virtual node or virtual router provider then that virtual node or virtual router cannot be deleted before virtual service is deleted, correct?
> * The dependency graph is then
>   
>   * _Mesh_ => _Virtual Node_ => _Virtual Service_  or
>   * _Mesh_ => _Virtual Router_ => _Virtual Service_

That's correct, the Virtual Service must be deleted before it's provider (VirtualNode or VirtualRouter). The thinking behind this is that the same actor in an organization likely owns both the Virtual Service and its providers, so it is there to protect them from creating an unintended outage of their own service.

**Comment by bflad** [comment]
These changes will go out in version 2.3.0 of the Terraform AWS Provider middle of next week unless we decide to release this as a 3.0.0 due to the breaking changes.

In the future, we may decide to relegate Public Preview and Beta APIs to separate Terraform AWS Provider(s) to prevent this situation in the future.

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
