### ISSUE TITLE
AWS provider will not build against latest Terraform v0.12.0-dev modules due to error in r/aws_glue_crawler

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#7661]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.0-dev

### Affected Resource(s)

* aws_glue_crawler

### Expected Behavior

```console
$ go build
$
```

### Actual Behavior

```console
$ go build
# github.com/terraform-providers/terraform-provider-aws/aws
aws/resource_aws_glue_crawler.go:369:47: cannot convert *crawlerInput (type glue.CreateCrawlerInput) to type glue.UpdateCrawlerInput
```

### Steps to Reproduce

```console
$ cd $GOPATH/src/github.com/terraform-providers
$ git clone https://github.com/terraform-providers/terraform-provider-aws.git
$ cd terraform-provider-aws
$ go get -u github.com/hashicorp/terraform@16823f43d
$ go build
go: finding github.com/hashicorp/terraform v0.12.0-alpha4.0.20190225213247-16823f43deec
# github.com/terraform-providers/terraform-provider-aws/aws
aws/resource_aws_glue_crawler.go:369:47: cannot convert *crawlerInput (type glue.CreateCrawlerInput) to type glue.UpdateCrawlerInput
```

### Important Factoids

Working with Terraform v0.12.0-dev and compiling AWS provider with latest go modules.

**Comment by YakDriver** [comment]
Complete details on how I encounter this error are here: https://medium.com/@dirk.avery/terraform-0-12-development-a-step-by-step-guide-to-get-running-with-providers-cea87082ad54

**Comment by bflad** [comment]
The fix for this has been merged. 🚀
