### ISSUE TITLE
r/aws_athena_workgroup: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging [Amazon Athena Workgroups](https://github.com/terraform-providers/terraform-provider-aws/issues/7650) added in [AWS SDK v1.17.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.4):

> This release adds tagging support for Workgroups to Amazon Athena. Use these APIs to add, remove, or list tags on Workgroups, and leverage the tags for various authorization and billing scenarios.

**Comment by ewbankkit** [comment]
[Here's](https://aws.amazon.com/about-aws/whats-new/2019/02/athena_support_for_tags/) the announcement.

**Comment by bflad** [comment]
The new `aws_athena_workgroup` resource has been merged including tagging support and will release with version 2.19.0 of the Terraform AWS Provider, likely later today. 👍

**Comment by bflad** [comment]
This has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
