### ISSUE TITLE
AWS Glue resources: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7668]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging AWS Glue resources added in [AWS SDK v1.17.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.4):

> AWS Glue adds support for assigning AWS resource tags to jobs, triggers, development endpoints, and crawlers. Each tag consists of a key and an optional value, both of which you define. With this capacity, customers can use tags in AWS Glue to easily organize and identify your resources, create cost allocation reports, and control access to resources.

Affected resources:
* [x] [`aws_glue_crawler`](https://www.terraform.io/docs/providers/aws/r/glue_crawler.html) - https://github.com/terraform-providers/terraform-provider-aws/pull/10805
* [ ] `aws_glue_dev_endpoint` - https://github.com/terraform-providers/terraform-provider-aws/pull/7895
* [x] [`aws_glue_job`](https://www.terraform.io/docs/providers/aws/r/glue_job.html) - https://github.com/terraform-providers/terraform-provider-aws/pull/9866
* [x] [`aws_glue_trigger`](https://www.terraform.io/docs/providers/aws/r/glue_trigger.html)

**Comment by ewbankkit** [comment]
Announcement:
* https://aws.amazon.com/about-aws/whats-new/2019/03/aws-glue-now-supports-resource-tagging/

**Comment by shrimats** [comment]
What is the status of this ticket? Is someone working on this - tagging glue resources (supported by AWS since Feb)

**Comment by yozamacs** [comment]
I would like to work on it if no one else has started (and it seems like no one has...)

**Comment by yozamacs** [comment]
Hi! If someone could take a look at what I started on this issue in https://github.com/terraform-providers/terraform-provider-aws/pull/9866 I would really appreciate it!

**Comment by bflad** [comment]
Hi folks 👋 Tagging support has been added to released Terraform resources, including `aws_glue_job` and `aws_glue_trigger`, which will release later today with version 2.39.0 of the Terraform AWS Provider. For additional feature requests or bug reports with Glue tagging functionality (e.g. tagging support in the unreleased `aws_glue_dev_endpoint` resource), please create new GitHub issues. Thanks. 👍
