### ISSUE TITLE
AWS Step Functions resources: Add support for tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging AWS Step Functions resources during creation added in [AWS SDK v1.17.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.4):

> This release adds support for tag-on-create. You can now add tags when you create AWS Step Functions activity and state machine resources. For more information about tagging, see AWS Tagging Strategies.

**Comment by bflad** [comment]
Support for tagging on creation with the `aws_sfn_activity` and `aws_sfn_state_machine` resources has been merged and will release with version 2.11.0 of the Terraform AWS Provider, likely in the next day or two. Thanks, @Jukie!

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
