### ISSUE TITLE
r/aws_directory_service_directory: Add support for tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging AWS Directory Service directories during creation added in [AWS SDK v1.17.1](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.1):

> This release adds support for tags during directory creation (CreateDirectory, CreateMicrosoftAd, ConnectDirectory).

**Comment by bflad** [comment]
Support for tagging on creation with the `aws_directory_service_directory` resource has been merged and will release with version 2.17.0 of the Terraform AWS Provider, likely later this week. Thanks, @kterada0509!

**Comment by bflad** [comment]
This has been released in [version 2.17.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2170-june-28-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
