### ISSUE TITLE
CognitoUserPool schema name length limited to 20 instead of 32

### ISSUE THREAD

**Issue by jalvarezferr** [terraform-providers/terraform-provider-aws#7726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.11

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

```
resource "aws_cognito_user_pool" "pool" {
    provider = "aws"
    
	name= "${var.projectName}-${local.environment}-Users"
	admin_create_user_config {
	   allow_admin_create_user_only= false
	   unused_account_validity_days= 7
	}
	auto_verified_attributes = ["email"]
	mfa_configuration= "OFF"
	password_policy {
	   minimum_length= 6
	   require_lowercase= true
	   require_numbers= true
	   require_symbols= false
	   require_uppercase= true
	}
	schema = [
	  {
	     name= "preferred_username"
	     attribute_data_type= "String"
	     developer_only_attribute= false
	     mutable= true
	     required= true
	     string_attribute_constraints {
	        min_length= 0
	        max_length= 2048
	     }
 	  },
   	  {
	     name= "custom:validation_date"
	     attribute_data_type= "String"
	     developer_only_attribute= false
	     mutable= true
	     required= false
	     string_attribute_constraints {
	        min_length= 1
	        max_length= 256
	     }
 	  }
   ]
   verification_message_template {
	   default_email_option= "CONFIRM_WITH_LINK"
	   email_message= "Tu código de verificación es {####}."
	   email_message_by_link = "Pulsa el enlace para verificar tu correo {##Click Here##}"
	   email_subject= "Tu código de verificación"
	   email_subject_by_link = "Verificación de correo"
	   sms_message= "Tu código de verificación es {####}."
	}
	tags = [
	   {
	     "Key" = "Name"
	     "Value"="MyWapp-${local.environment}"
	   }
	]
}
```
### Expected Behavior

User pool schema attribute names up to 32 characters long are accepted as per the AWS documentation (under Custom Attributes):

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html

### Actual Behavior

Error: module.pre.aws_cognito_user_pool.pool: "schema.11.name" cannot be longer than 20 character

### Steps to Reproduce

1. `terraform plan`

* #0000

**Comment by jalvarezferr** [comment]
"custom:" prefix is added authomaically at pool creation, the available length should be 25.

**Comment by nywilken** [comment]
Hi @jalvarezferr as per the API reference documentation the maximum allowed number of characters for the attribute name is 20 https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SchemaAttributeType.html. 

While it is possible that the maximum will support a number slightly closer to 25 we generally avoid going against the documented values unless we find that the defined constraints is less than was is documented (e.g maximum length is actually lower than 20). I am going to close this issue for now. 

If you believe this is a bug please feel free to open a new issue with a supporting configuration and, if possible, links indicating that upping the maximum to 25 will not conflict with any prefixes that may be automatically added at pool creation. 

Thanks
