### ISSUE TITLE
configurations_json: javax.jdo.option.ConnectionPassword (forces new resource) each time

### ISSUE THREAD

**Issue by ivan-verizon** [terraform-providers/terraform-provider-aws#7733]
### Terraform Version

Terraform v0.11.11
+ provider.aws v1.60.0

### Affected Resource(s)

* aws_emr_cluster

### Terraform Configuration Files

```hcl
configurations_json = EOF
[
  {
    "Classification": "spark-hive-site",
    "Properties": {
      "javax.jdo.option.ConnectionUserName": "hive",
      "javax.jdo.option.ConnectionPassword": "some_pass",
      "hive.metastore.connect.retries": "15"
    }
  }
]
```

### Debug Output
"javax.jdo.option.ConnectionPassword\":\"********\"...
"javax.jdo.option.ConnectionPassword\":\"some_pass\"... 

### Expected Behavior

No changes. Infrastructure is up-to-date.

### Actual Behavior

(forces new resource)

### Steps to Reproduce

Define in: configurations_json
1. "javax.jdo.option.ConnectionPassword": "some_pass"
2. `terraform apply`
3. terraform plan

### Important Factoids
If I'm changing the password after `terrafrom apply` to ********. 
Behavior is expected - No changes. Infrastructure is up-to-date.

### References

* #0000

**Comment by aeschright** [comment]
Hi @ivan-verizon 👋 We'll need more context with your config for someone to look into this -- otherwise we might be making incorrect guesses. Would you open a new bug report that includes all of the relevant sections of your config, plus the full debug output? Thanks!

**Comment by ivanfavi** [comment]
I have the same issue if you look at the configurations in the EMR console you could see the password provided is replaced by `"********"` (it is encrypted in some way by amazon). I just updated the password provided by terraform for this value `"********"`

```
      "Classification": "hive-site",
      "Properties": {
        "javax.jdo.option.ConnectionURL": "jdbc:mysql://hive-mestatore.us-west-2.rds.amazonaws.com:3306/hive-db?createDatabaseIfNotExist=true",
        "javax.jdo.option.ConnectionDriverName": "org.mariadb.jdbc.Driver",
        "javax.jdo.option.ConnectionUserName": "hive-user",
        "javax.jdo.option.ConnectionPassword": "********"
      }
    },
```

Then terraform plan/apply didn't ask to replace the existing EMR cluster. This is a jugaard but I didn't found another approach to solve it. Maybe providing a bootstrap to set the password during the provisioning could avoid this issue but increase the complexity a bit.
