### ISSUE TITLE
resource_aws_spot_fleet_request does not catch InvalidSpotFleetRequestConfig errors

### ISSUE THREAD

**Issue by gileri** [terraform-providers/terraform-provider-aws#7740]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
provider.aws v1.60.0

### Affected Resource(s)

* aws_spot_fleet_request

### Terraform Configuration Files

```hcl
provider "aws" {
	region = "eu-central-1"
}

data "aws_ami" "ecs" {
  most_recent = true

  filter {
    name   = "name"
    values = ["amzn-ami*amazon-ecs-optimized"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["591542846629"] # Amazon
}
data "aws_iam_policy_document" "spot_fleet" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["spotfleet.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "spot_fleet" {
  name = "spot_fleet"
  assume_role_policy = "${data.aws_iam_policy_document.spot_fleet.json}"
}

data "aws_iam_policy" "spot_fleet" {
  arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole" # Amazon Managed policy
}

resource "aws_iam_role_policy_attachment" "spot_fleet" {
    role       = "${aws_iam_role.spot_fleet.name}"
    policy_arn = "${data.aws_iam_policy.spot_fleet.arn}"
}

resource "aws_spot_fleet_request" "ecs" {
  iam_fleet_role       = "${aws_iam_role.spot_fleet.arn}"
  wait_for_fulfillment = true
  target_capacity      = 1

  lifecycle {
    ignore_changes        = ["valid_until"]
  }

  launch_specification {
    ami                       = "${data.aws_ami.ecs.image_id}"
    availability_zone         = "eu-central-1a"
    iam_instance_profile      = "ecsInstanceRole"
    instance_type             = "invalid.instancetype"
  }
}
```

### Debug Output

https://gist.github.com/gileri/5646b92fe86fcd89350f82e90fca86f6
### Expected Behavior

Resource creation should abort immediately on non-retryable InvalidSpotFleetRequestConfig, such as when an EC2 instance type is not available on this region.

### Actual Behavior

Terraform keep retrying `ec2/RequestSpotFleet` until `apply` timeout.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Due to differences on EC2 instance types between regions, invalid `launch_configuration` can happen quite easily.

**Comment by bflad** [comment]
The fix to ensure the `aws_spot_fleet_request` resource is only retrying on IAM eventual consistency errors has been merged and will release with version 3.0.0 of the Terraform AWS Provider, in about a week.
