### ISSUE TITLE
Amazon Pinpoint resources: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7741]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging Amazon Pinpoint resources added in [AWS SDK v1.17.6](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.6):

> This release adds support for the Amazon Resource Groups Tagging API to Amazon Pinpoint, which means that you can now add and manage tags for Amazon Pinpoint projects (apps), campaigns, and segments.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/4990

**Comment by bflad** [comment]
Support for tagging `aws_pinpoint_app` resources has been merged and will release with version 2.22.0 of the Terraform AWS Provider, tomorrow. 👍 Thanks to @faishal for the implementation.
