### ISSUE TITLE
Feature Request - Add support for LAMBDA in aws_ssm_maintenance_window_task resource

### ISSUE THREAD

**Issue by fitzplb** [terraform-providers/terraform-provider-aws#7746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Similar to #4408 
I could do with support for registering a Lambda task with a maintenance window. In fact the current implementation uses 

```
TaskParameters={
        'string': {
            'Values': [
                'string',
            ]
        }
    },
```

Which has been deprecated in favour of 

```
    TaskInvocationParameters={
        'RunCommand': {
            'Comment': 'string',
            'DocumentHash': 'string',
            'DocumentHashType': 'Sha256'|'Sha1',
            'NotificationConfig': {
                'NotificationArn': 'string',
                'NotificationEvents': [
                    'All'|'InProgress'|'Success'|'TimedOut'|'Cancelled'|'Failed',
                ],
                'NotificationType': 'Command'|'Invocation'
            },
            'OutputS3BucketName': 'string',
            'OutputS3KeyPrefix': 'string',
            'Parameters': {
                'string': [
                    'string',
                ]
            },
            'ServiceRoleArn': 'string',
            'TimeoutSeconds': 123
        },
        'Automation': {
            'DocumentVersion': 'string',
            'Parameters': {
                'string': [
                    'string',
                ]
            }
        },
        'StepFunctions': {
            'Input': 'string',
            'Name': 'string'
        },
        'Lambda': {
            'ClientContext': 'string',
            'Qualifier': 'string',
            'Payload': b'bytes'
        }
    },
```

Implementing this would provide support for all 4 types of task

### New or Affected Resource(s)

* resource_aws_ssm_maintenance_window_task.go

### References

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.register_task_with_maintenance_window

**Comment by bflad** [comment]
Support for a new `task_invocation_parameters` configuration block in the `aws_ssm_maintenance_window_task` resource has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected later this week. Thanks to @kterada0509 for the implementation work. 👍
