### ISSUE TITLE
Update aws_dlm_lifecycle_manager intervals

### ISSUE THREAD

**Issue by blckct** [terraform-providers/terraform-provider-aws#7749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
[AWS now allows for shorter intervals in the lifecycle manager](https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-data-lifecycle-manager-adds-support-for-shorter-backup-interv), currently they are hardcoded to 12 or 24: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_dlm_lifecycle_policy.go#L69

### New or Affected Resource(s)

* aws_resource_aws_dlm_lifecycle_policy

**Comment by bflad** [comment]
Support for these additional intervals has been merged and will release with version 2.1.0 of the Terraform AWS Provider, likely middle of next week.

**Comment by bflad** [comment]
This has been released in [version 2.1.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#210-march-07-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
