### ISSUE TITLE
Add Inspector assessment template as a cloudwatch_event_target

### ISSUE THREAD

**Issue by kimor79** [terraform-providers/terraform-provider-aws#7776]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Cloudwatch events can trigger the run of an Inspector assessment template. It would be nice if that trigger can be defined in terraform

### New or Affected Resource(s)

cloudwatch_event_target

**Comment by jecnua** [comment]
Hi @kimor79 
At the moment you can already trigger an assessment template via cloudwatch events. Maybe I misunderstood your request but just in case I didn't try looking at this:

https://gist.github.com/wokamoto/c8362fa35909b5360f04cae9ebd81400

(gist is not mine).

Hope it helps,
F.

**Comment by kimor79** [comment]
Yes, that does help. I misread the docs somehow. Thanks!
