### ISSUE TITLE
Is terraform resources support for Enhanced Fan-Out Using the Kinesis Data Streams available

### ISSUE THREAD

**Issue by rupeshshah4706** [terraform-providers/terraform-provider-aws#7793]
Is the support available for registering stream consumer? I guess presently it has to be done through aws web console, aws cli command or KCL2.0

**Comment by bflad** [comment]
Hi @rupeshshah4706 👋 Thanks for writing in. Support for Kinesis Stream Consumers is not available currently, but we do have an open issue (https://github.com/terraform-providers/terraform-provider-aws/issues/7611) and pull request (https://github.com/terraform-providers/terraform-provider-aws/pull/6565) for this support. To consolidate efforts and discussions, I'm going to close this issue in preference of the previous ones. 👍

**Comment by elrob** [comment]
Looks like it's still in the works: https://github.com/terraform-providers/terraform-provider-aws/pull/10487
