### ISSUE TITLE
Resource aws_vpc_dhcp_options should trim trailing . from domain_name

### ISSUE THREAD

**Issue by rlees85** [terraform-providers/terraform-provider-aws#7800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v0.11.7
* AWS Provider 2.0.0

### Affected Resource(s)

* aws_vpc_dhcp_options

### Terraform Configuration Files

```hcl
resource "aws_vpc_dhcp_options" "scope" {
  domain_name         =   "${coalesce(join("", aws_route53_zone.private.*.name), format("%v.%v", data.aws_region.scope.name, var.dhcp_options_domain_fallback_suffix))}"
  domain_name_servers = [ "${var.dhcp_options_dns_servers                                                                                                             }" ]

  tags {
    VPC    = "${var.name                                                                                                                                }"
    Name   = "${var.name}-${var.dhcp_options_name                                                                                                       }"
    Owner  = "${var.owner                                                                                                                               }"
    Domain = "${coalesce(join("", aws_route53_zone.private.*.name), format("%v.%v", data.aws_region.scope.name,var.dhcp_options_domain_fallback_suffix))}"
    Region = "${data.aws_region.scope.name                                                                                                              }"
  }
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

The output of the route53_zone name to be accepted into the `domain_name` for DHCP options.

### Actual Behavior

There is now a trailing dot, that the DHCP option set resource accepts but breaks all DHCP clients.

Similar: 
https://github.com/terraform-providers/terraform-provider-aws/issues/6535
https://github.com/terraform-providers/terraform-provider-aws/issues/6389

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jeffery** [comment]
Hi @rlees85 Did you manage to get a workaround for the manipulation of the end dot in the `var.dhcp_options_dns_servers` list?

**Comment by rlees85** [comment]
Its `domain_name` I had issues with, I was trying to use the output of `route53_zone` directly in this field. For now I am using something like:

```
replace(join("", aws_route53_zone.private.*.name), "/\\.$/", "")
```

With is a simple regex that removes any `.` if and only if it is at the end of the string.

**Comment by anGie44** [comment]
Hi @rlees85, thanks again for creating this issue! With the proposed changes in #14220  to remove the trailing period in Route53 Zone resources, resources like `aws_vpc_dhcp_options` should behave as expected when using the `name` attribute of the `aws_route53_zone` resource as input to `domain_name`.  The bug-fix will land in the upcoming Provider release of `v3.0.0` 😃
