### ISSUE TITLE
`aws_s3_bucket_object` metadata key name incorrect

### ISSUE THREAD

**Issue by chanhht** [terraform-providers/terraform-provider-aws#7810]
### Terraform Version
Terraform v0.11.11
+ provider.aws v2.0.0
+ provider.null v2.1.0

### Affected Resource(s)

* aws_s3_bucket_object

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ap-southeast-1"
}

data "aws_s3_bucket_object" "test" {
  bucket = "test-terraform-s3-bucket-object"
  key = "test"
}

resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "aws s3api head-object --bucket 'test-terraform-s3-bucket-object' --key 'test' --query 'Metadata'"
  }
}

output "metadata" {
  value = "${data.aws_s3_bucket_object.test.metadata}"
}
```

### Expected Behavior

The output of `data.aws_s3_bucket_object.test.metadata` key name should be the same as aws cli and aws S3 console (e.g. `test` )
```
metadata = {
  test = Test Bucket Object 
}
```

### Actual Behavior

The key name automatic capitalize the first letter (e.g. `Test` instead of `test` )
```
metadata = {
  Test = Test Bucket Object
}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
Use-defined metadata keys are stored in lowercase:
* https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#UserMetadata

**Comment by chanhht** [comment]
Thank @ewbankkit for the doc, then clearly the Metadata keys returned should be in lowercase.

**Comment by ewbankkit** [comment]
Yes, I'll try and dig in to this when I get time.

**Comment by ewbankkit** [comment]
It looks like there is an underlying issue with the AWS SDK: https://github.com/aws/aws-sdk-go/issues/445.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/1945

**Comment by chanhht** [comment]
Thanks, I think the issue has been noticed before and PR is ready. In the meanwhile, since the metadata key always is lowercase, I do a workaround by casting to lowercase.
