### ISSUE TITLE
Can't associate Route 53 Zone with multiple VPCs with AWS provider 2.0

### ISSUE THREAD

**Issue by hazmeister** [terraform-providers/terraform-provider-aws#7812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.10.8

### Affected Resource(s)

* aws_route53_zone
* aws_route53_zone_association

### Terraform Configuration Files

```hcl
resource "aws_route53_zone" "gc-internal-com" {
  name    = "gc.internal.com"
  comment = "Alias for talking to other team"

  vpc {
    vpc_id = "vpc-aaaaaaa1"
  }
}

resource "aws_route53_zone_association" "ref" {
  vpc_id  = "vpc-aaaaaaa2"
  zone_id = "${aws_route53_zone.gc-internal-com.zone_id}"
}

resource "aws_route53_zone_association" "inf" {
  vpc_id  = "vpc-aaaaaaa3"
  zone_id = "${aws_route53_zone.gc-internal-com.zone_id}"
}
```

### Expected Behavior

One private Route 53 zone should be attached to multiple VPCs.

### Actual Behavior

Every other terraform apply removes or re-applies the VPC associate for the `aws_route53_zone_association` resources.

```
Terraform will perform the following actions:

  ~ aws_route53_zone.gc-internal-com
      vpc.#:                 "3" => "1"
      vpc.bbbbbbb3.vpc_id: "vpc-aaaaaaa3" => ""
      vpc.bbbbbbb2.vpc_id: "vpc-aaaaaaa2" => ""
      vpc.bbbbbbb1.vpc_id:  "vpc-aaaaaaa1" => "vpc-aaaaaaa1"
```

Provider version 1.60.0 does not exhibit the problem.
### Steps to Reproduce

1. `terraform apply`

**Comment by ewbankkit** [comment]
This looks like the same as https://github.com/terraform-providers/terraform-provider-aws/issues/7805.

**Comment by hazmeister** [comment]
Apologies, you are correct- I started creating the ticket last week, and didn't look again before submitting.

**Comment by ewbankkit** [comment]
@hazmeister Could you please close this issue? Thanks.
