### ISSUE TITLE
AWS Elemental MediaPackage resources: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging AWS Elemental MediaPackage resources added in [AWS SDK v1.17.10](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.10):

> This release adds support for user-defined tagging of MediaPackage resources. Users may now call operations to list, add and remove tags from channels and origin-endpoints. Users can also specify tags to be attached to these resources during their creation. Describe and list operations on these resources will now additionally return any tags associated with them.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6958

**Comment by bflad** [comment]
Support for `aws_media_package_channel` resource `tags` has been merged and will release with version 2.3.0 of the Terraform AWS Provider, likely middle of this week.

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
