### ISSUE TITLE
AWS Storage Gateway resources: Add support for tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging AWS Storage Gateway resources on creation added in [AWS SDK v1.17.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.17.11):

> ActivateGateway, CreateNFSFileShare and CreateSMBFileShare APIs support a new parameter: Tags (to be attached to the created resource). Output for DescribeNFSFileShare, DescribeSMBFileShare and DescribeGatewayInformation APIs now also list the Tags associated with the resource.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/5618
* https://github.com/terraform-providers/terraform-provider-aws/issues/943

**Comment by bflad** [comment]
Support for tagging Storage Gateway resources (on creation) has been merged and will release with version 2.35.0 of the Terraform AWS Provider, Thursday. Thanks to @DrFaust92 for the implementation work here. 👍
