### ISSUE TITLE
aws_cloudwatch_metric_alarm unable to associate to custom metrics

### ISSUE THREAD

**Issue by finferflu** [terraform-providers/terraform-provider-aws#7834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`1.60.0`

### Affected Resource(s)

* `aws_cloudwatch_metric_alarm`

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "low_disk_space_warn" {
  alarm_name          = "asg-low-disk-space-warn-${terraform.workspace}"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = "${var.low_disk_space_eval_periods}"
  metric_name         = "DiskSpaceUtilization"
  namespace           = "System/Linux"

  dimensions {
    AutoScalingGroupName = "${module.asg.this_autoscaling_group_name}"
    MountPath            = "/"
    FileSystem           = "/dev/xvda1"
  }

  period            = "${var.low_disk_space_period}"
  statistic         = "Maximum"
  threshold         = "${var.low_disk_space_warn_threshold}"
  alarm_description = "Disk utilisation >= ${var.low_disk_space_warn_threshold}%"
  alarm_actions     = ["${aws_sns_topic.warning_alarms.arn}"]
}
```

### Debug Output

I will provide debug output if needed.

### Expected Behavior

The alarm should be associated with the existing metric in CloudWatch.

### Actual Behavior

The alarm is associated to an empty/non-existing metric. I can manually search and set the actual metric via AWS Console, once Terraform has created the alarm, and I can see two metrics by the same name, with the selected one being empty. I have also attempted to delay the creation of the alarm for one minute after the ASG comes to life, to allow enough time for the custom metric to be pushed to CloudWatch to no avail. Please see screenshot.

<img src="https://i.imgur.com/Ub5DUYW.png" />

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @finferflu 👋 Are you able to determine the difference if you manually fix the CloudWatch Metric Alarm in the console and use `terraform import` to see the difference with your configuration?

**Comment by finferflu** [comment]
@bflad thanks very much for getting back to me so quickly. These are the differences shown in `terraform plan` after fixing the alert manually:

```
  ~ aws_cloudwatch_metric_alarm.low_disk_space_crit
      dimensions.FileSystem: "" => "/dev/xvda1"
      dimensions.Filesystem: "/dev/xvda1" => ""
      period:                "300" => "600"
```

Yours was a really valid troubleshooting tip, and I got to fix the error (i.e. `FileSystem` should have been `Filesystem`).
