### ISSUE TITLE
aws_instance creation failure is not reported properly

### ISSUE THREAD

**Issue by EugeniuZ** [terraform-providers/terraform-provider-aws#7836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
provider.aws: version = "~> 2.0"

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "import_master" {
  ...
  user_data  = "${data.template_file.bootstrap.rendered}"
}

# route 53 record

resource "aws_route53_record" "master" {
  zone_id = "${var.route53_zone_id}"
  name    = "name"
  type    = "A"
  ttl     = "120"
  records = ["${aws_instance.import_master.private_ip}"]
}
```

### Expected Behavior

The error should mention the user_data content is too big as I saw in the logs when running terraform apply with TF_LOG=error

```
2019/03/06 17:22:02 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [expected length of user_data to be in the range (0 - 16384), got #!/bin/bash ...
```

### Actual Behavior

```
Error: Error running plan: 1 error(s) occurred:

* aws_route53_record.master: 1 error(s) occurred:

* aws_route53_record.master: Resource 'aws_instance.import_master' not found for variable 'aws_instance.import_master.private_ip'
```

### Steps to Reproduce

1. `terraform plan`

**Comment by bflad** [comment]
Hi @EugeniuZ 👋 Thanks for reporting this and sorry for this confusing behavior. 😖 This class of bug was actually handled upstream in Terraform (https://github.com/hashicorp/terraform/issues/18129) and fixed in Terraform 0.12-alpha4 and later. Since this was fixed in Terraform core and is not related to something we can fix in the Terraform AWS Provider, I'm going to close this issue. 👍
