### ISSUE TITLE
Can't create an aws_acm_certificate

### ISSUE THREAD

**Issue by tomaratyn** [terraform-providers/terraform-provider-aws#7845]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.11
+ provider.aws v1.60.0
```

Also same results with:

```
$ terraform -v
Terraform v0.11.11
+ provider.aws v2.0.0
```

### Affected Resource(s)

* aws_acm_certificate

### Terraform Configuration Files

```hcl
variable "aws_access_key_id" {}
variable "aws_secret_key" {}
variable "region" { default = "us-west-1" }

provider "aws" {
  alias = "prod"

  region = "${var.region}"
  access_key = "${var.aws_access_key_id}"
  secret_key = "${var.aws_secret_key}"
}

resource "aws_acm_certificate" "cert" {
  domain_name       = "foo.example.com"
  validation_method = "DNS"

  tags {
    project = "foo"
  }

  lifecycle {
    create_before_destroy = true
  }

}
```

### Debug Output

https://gist.github.com/tomaratyn/b24c9f2912e444297c92c8f72a0939fe

### Panic Output

N/A

### Expected Behavior

A plan to create a certificate is show/run.

### Actual Behavior

Ignores variables values provied

### Steps to Reproduce

1. `terraform init`
2. put variable values in `vars.tfvars`
3. `terraform plan -var-file=vars.tfvars`

### Important Factoids

On a mac? 

### References

N/A

* #0000

**Comment by yld** [comment]
The logs says _No valid credential sources found for AWS Provider._

**Comment by tomaratyn** [comment]
@yld, yes, but the credentials were in `vars.tfvars`.

**Comment by aeschright** [comment]
Hi @tomaratyn -- sorry you ran into this! We fixed a set of authentication bugs in a recent release that may have been what you were seeing. If you update to the latest version of Terraform and the AWS provider and it's still failing, please open a new bug report. Make sure to include the log and a sanitized version of that input file. Thanks!
