### ISSUE TITLE
Process to get new feature PR Reviewed

### ISSUE THREAD

**Issue by jzbruno** [terraform-providers/terraform-provider-aws#7854]
Hello,

I have a new feature PR #2616 that has been around for over a year. It adds support for Amazon Lex resources. I was hoping to get some insight into what the process is to get it reviewed? Any help would be greatly appreciated.

Jack

**Comment by cipherzzz** [comment]
I'd love to see [this](https://github.com/terraform-providers/terraform-provider-aws/pull/2616) merged as well - we need it!

**Comment by tracypholmes** [comment]
Closing in favor of #905 as you've already gotten feedback @jzbruno
