### ISSUE TITLE
default security group always attached to instance limiting to 4 SG's per instance.

### ISSUE THREAD

**Issue by tburt11** [terraform-providers/terraform-provider-aws#7856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.0
+ provider.aws v1.60.0

### Affected Resource(s)

ec2 instances
security groups

### Expected Behavior

EC2 instance created with 5 defined SG's attached.

### Actual Behavior

EC2 instance created with 4 defined SG's attached plus the default SG.
Plus the aws error:

aws_network_interface_sg_attachment.custom: SecurityGroupsPerInterfaceLimitExceeded: The maximum number of security groups per interface has been reached.

### Steps to Reproduce

Create 5 independent SG's
Create an ec2 plan to instantiate an ec2 instance with the 5 independent SG's attached.

### Important Factoids

Amazon limits the number of security groups that can be attached to an instance to 5.

This limit (5) can be hard to accommodate in a large enterprise.

When an instance is instantiated, Amazon REQUIRES that a security group be defined, and in the absence of a defined security group, the default SG is added.

Because TF instantiates the instance before ADDING the SG's, every instance created by terraform MUST HAVE THE DEFAULT SG ATTACHED.

This means that the maximum defined SG's that can be attached to an instance is 4 not 5.  A very significant reduction.

The docs should clearly explain this limitation.  Indeed, this fact alone could influence the decision to choose terraform vs. cloudformation.

An option to remove the default SG during instance creation would be most ideal.  This would allow use of the full 5 SG resources allowed by AWS.

**Comment by dannyleesmith** [comment]
Hi @tburt11, 

stumbled across this and thought I'd reach out. I've not experienced this at all working with Terraform and EC2. Do you have any code examples you can share that could be used to test your situation?

A recent AWS feature release that may be of interest to you as well on a similar topic: https://forums.aws.amazon.com/ann.jspa?annID=6599

Cheers,

-- Danny

**Comment by aeschright** [comment]
Hello! Since I don't see an attached Terraform config we could use to verify the issue, I'm going to close this. If you're still seeing a problem, using the most recent versions of Terraform and the AWS provider, please open a new bug report. Be sure to include all of the requested items. Thanks!
