### ISSUE TITLE
aws provider does not appear to support --task-invocation-parameters for aws_ssm_maintenance_window_task resource

### ISSUE THREAD

**Issue by onedumslack** [terraform-providers/terraform-provider-aws#7870]
aws provider does not appear to support --task-invocation-parameters for aws_ssm_maintenance_window_task resource.  It does support the now deprecated --task-parameters which does not appear to support the needed complex json structures that the newer --task-invocation-parameters supports for automation docs.

**Comment by bflad** [comment]
Support for a new `task_invocation_parameters` configuration block in the `aws_ssm_maintenance_window_task` resource has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected later this week. Thanks to @kterada0509 for the implementation work. 👍
