### ISSUE TITLE
Is it possible to change aws_region for different resources?

### ISSUE THREAD

**Issue by amitsh728** [terraform-providers/terraform-provider-aws#7879]
Hello,
I am trying to write a terraform configuration which would act as a recovery plan in case of downtime. Our current setup is in us-west-2 and in case of any disaster, we would use us-east-1 to recover our complete setup using terraform.
I am looking for the options to make use of multiple AWS regions in my terraform config files. Once use-case could be: 
(1) taking the snapshot of rds from us-west-2 -> (2) copy the snapshot to us-east-1 -> (3) restore the rds in us-east-1.
When I tried to implement it in terraform, I could not find any option to change the region as per resources. I am currently planning to perform the tasks of snapshot taking and copying to a different region using bash script, but is it possible to do this using terraform, which would reduce the human interaction and improve our RTO?

**Comment by antoniocostantini** [comment]
Hello amitsh728, do you have try to use alias for different providers? Ref: https://www.terraform.io/docs/configuration-0-11/providers.html#multiple-provider-instances

**Comment by amitsh728** [comment]
Exactly what I was looking for... Thanks Antonio.
