### ISSUE TITLE
Support Rust runtime in Lambda functions

### ISSUE THREAD

**Issue by dnagir** [terraform-providers/terraform-provider-aws#7889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Lambda supports Rust runtime but it is not possible to deploy it with terraform as we get the error:

```
Error: module.hello.aws_lambda_function.fn: expected runtime to be one of
[dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 go1.x java8 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 provided python2.7 python3.6 python3.7 ruby2.5], got rust
```

### New or Affected Resource(s)

* aws_lambda_function

### References

* #6656 (Ruby support was added as an example)

**Comment by bflad** [comment]
Hi @dnagir 👋 Thanks for submitting this. Was Rust added as a standard Lambda runtime? As of this writing its not listed in the Lambda documentation: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

Lambda supports custom runtimes via: https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html

**Comment by dnagir** [comment]
I think this can be closed. Just need to use `provided` runtime for Rust.
