### ISSUE TITLE
AWS Elastic Beanstalk resources: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging AWS Elastic Beanstalk resources added in [AWS SDK v1.18.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.18.0):

> Elastic Beanstalk added support for tagging, and tag-based access control, of all Elastic Beanstalk resources.

**Comment by bflad** [comment]
Support for the `tags` argument has been merged for the `aws_elastic_beanstalk_application` and `aws_elastic_beanstalk_application_version` resources, releasing in version 2.11.0 of the Terraform AWS Provider, likely later today. 👍

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
