### ISSUE TITLE
data aws_elasticsearch_domain support

### ISSUE THREAD

**Issue by Clete2** [terraform-providers/terraform-provider-aws#7899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform should support `data "aws_elasticsearch_domain"` to get attributes for an existing domain.

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl
data "aws_elasticsearch_domain" "example" {
  name = "example-domain"
}
```

**Comment by kterada0509** [comment]
I working on this issue.

**Comment by ScriptMyJob** [comment]
@kterada0509 any update?
