### ISSUE TITLE
Tech debt: Replace 'validateAny' and 'validateIntegerInSlice' with upstream 'validation.Any' and 'validation.IntInSlice'

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

After the merging of https://github.com/terraform-providers/terraform-provider-aws/pull/7874 we can now replace `validateAny()` https://github.com/terraform-providers/terraform-provider-aws/blob/97596eefb71281379b3f80119556051bf3374d1a/aws/validators.go#L27-L41 with `validation.Any()` https://github.com/terraform-providers/terraform-provider-aws/blob/97596eefb71281379b3f80119556051bf3374d1a/vendor/github.com/hashicorp/terraform/helper/validation/validation.go#L33-L47 and `validateIntegerInSlice()` https://github.com/terraform-providers/terraform-provider-aws/blob/97596eefb71281379b3f80119556051bf3374d1a/aws/validators.go#L593-L608 with `validators.IntInSlice()` https://github.com/terraform-providers/terraform-provider-aws/blob/97596eefb71281379b3f80119556051bf3374d1a/vendor/github.com/hashicorp/terraform/helper/validation/validation.go#L108-L125.

Related:
* https://github.com/hashicorp/terraform/pull/20337
* https://github.com/terraform-providers/terraform-provider-aws/pull/6156
* https://github.com/terraform-providers/terraform-provider-aws/pull/6183

**Comment by richardjennings** [comment]
I have opened a PR https://github.com/terraform-providers/terraform-provider-aws/pull/8479
