### ISSUE TITLE
aws_api_gateway_integration using aws service fails

### ISSUE THREAD

**Issue by harkamals** [terraform-providers/terraform-provider-aws#7916]
### Terraform Version
0.11.8, aws provider v2.1.0

### Affected Resource(s)
aws_api_gateway_integration

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_integration" "pricing" {
  rest_api_id = "${aws_api_gateway_rest_api.pricing-terraform.id}"
  resource_id = "${aws_api_gateway_method.proxy.resource_id}"
  http_method = "${aws_api_gateway_method.proxy.http_method}"

  integration_http_method = "ANY"
  type                    = "AWS"

  uri = "arn:aws:apigateway:eu-west-1:ec2:action/DescribeSpotPriceHistory"
}
```
### Expected Behavior
It should create api integration using AWS service / DescribeSpotInstanceHistory

### Actual Behavior
* aws_api_gateway_integration.pricing: 1 error(s) occurred:

* aws_api_gateway_integration.pricing: Error creating API Gateway Integration: BadRequestException: Role ARN must be specified for AWS integrations
        status code: 400, request id: f0ec6aaf-4570-11e9-8f12-f31e8fe2bdf4

### Steps to Reproduce
`terraform apply`

**Comment by mkrishnan-tc** [comment]
I have similar issue while making use of AWS Integration for S3. When is this likely to be added to provider?

**Comment by kitdarko** [comment]
I had this issue when creating a kinesis integration.

You can resolve it by providing the IAM role ARN under the integration's "credentials" parameter.

i.e.:
```
resource "aws_api_gateway_integration" "example_integration" {
  credentials = "${aws_iam_role.example_role.arn}"
```

**Comment by aeschright** [comment]
Hi @harkamals 👋 Sorry you ran into trouble with this. As the comment above says, the error indicates you will need to add credentials for this particular integration. I'm going to close the issue, but please open a new bug report if you continue to encounter problems. Thanks!
