### ISSUE TITLE
Support aws_route53_zone_association Resource Import

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#7964]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_route53_zone_association` resource does not currently implement import, so it is difficult to migrate existing infrastructure into Terraform or split up `aws_route53_zone` VPC associations into their own resources.

### New or Affected Resource(s)

* `aws_route53_zone_association`

### References

* https://www.terraform.io/docs/providers/aws/r/route53_zone_association.html

**Comment by bflad** [comment]
Pull request submitted: #7966

**Comment by grimm26** [comment]
In my experience when I have imported zones with existing associations, you can just add the association resource and it applies just fine over the existing association.

**Comment by bflad** [comment]
@grimm26 that behavior sounds like a bug. Terraform resources should generally avoid "assuming" management over existing infrastructure unless imported into the Terraform state.

**Comment by bflad** [comment]
Support for `aws_route53_zone_association` resource import has been merged and will release with version 2.3.0 of the Terraform AWS Provider, likely in the next day or two.

**Comment by bflad** [comment]
This has been released in [version 2.3.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#230-march-21-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by borgstrom** [comment]
@bflad This caused breaking changes for anyone working around missing cross-account route53 association while waiting on #2005 

If you have done authorization and association across account out-of-band (i.e. using the AWS CLI) this change causes those associations to now want to be removed when you pick up the new version of the provider.

For now we're going to ensure we don't pick up the 2.3.0 version of the provider, but I'm curious your thoughts on how we can move forward?  Can we get a solution to #2005, or some how change this resource to NOT remove existing associations added out of band like before?

**Comment by borgstrom** [comment]
Oops.  I commented on the wrong issue.  Moving my comment to #7966.
