### ISSUE TITLE
Support for global-accelerator endpoint-group 

### ISSUE THREAD

**Issue by atoonk** [terraform-providers/terraform-provider-aws#7965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Now that there is terraform support for  ```aws_globalaccelerator``` and ```aws_globalaccelerator_listener```  I think the only thing missing is support for ```global-accelerator endpoint-group```.  Looks like without that, creating a global accelerator using terraform won't be possible.

So I'd love to have the ability to create an  global accelerator using terraform. For that we need global-accelerator endpoint-group support.

### New or Affected Resource(s)

https://docs.aws.amazon.com/global-accelerator/latest/api/API_CreateEndpointGroup.html

**Comment by bflad** [comment]
There is a work in progress pull request for this new resource, which can be found here: https://github.com/terraform-providers/terraform-provider-aws/pull/7005

**Comment by jamengual** [comment]
Thanks for that work, Global accelerators without  global-accelerator endpoint-groups are useless so this is very key.

**Comment by bflad** [comment]
A new `aws_globalaccelerator_endpoint_group` resource has been merged and will release with version 2.16.0 of the Terraform AWS Provider, likely tomorrow. 👍 Thanks to @gazoakley for the initial implementation and @john-delivuk for helping get this across the finish line.

**Comment by bflad** [comment]
This has been released in [version 2.16.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2160-june-20-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
