### ISSUE TITLE
IAM instance roles not available for cloud-init

### ISSUE THREAD

**Issue by trajano** [terraform-providers/terraform-provider-aws#7999]
### Terraform Version

$ terraform -v
Terraform v0.11.11
+ provider.aws v2.1.0 (or 2.2.0)
+ provider.template v1.0.0
+ provider.tls v1.2.0

### Affected Resource(s)

* aws_instance
* aws_iam_role

### Terraform Configuration Files

https://registry.terraform.io/modules/trajano/swarm-aws/docker/2.3.2

Just changed from AWS 2.1 to AWS 2.2 in the samples and the instance credentials do not appear to be present during cloud init but works when you run the same script inside and `curl`ing the meta data shows the instance ID.  So it appears to be a timing issue because it works with a `t3.micro` but not a `t3.small` which is a slightly faster machine.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Everything should be provisioned correctly.

### Actual Behavior

I get an error saying missing credentials when invoking boto3 in cloud-init

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aeschright** [comment]
Hi @trajano 👋 We need the specific relevant parts of your config in the bug report and the full debug output to follow up on this. If you're still encountering a problem, please open a new issue with that information. Thanks!
