### ISSUE TITLE
aws_codebuild_webhook does not support filterGroups

### ISSUE THREAD

**Issue by confiq** [terraform-providers/terraform-provider-aws#8012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.kubernetes v1.5.2
+ provider.local v1.1.0
+ provider.null v2.1.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_codebuild_webhook

### Terraform Configuration Files

```hcl
resource "aws_codebuild_webhook" "_" {
  project_name  = "${aws_codebuild_project.devops.name}"
  branch_filter = "^refs/heads/master$"
}
```

### Expected Behavior

There is no `filterGroups` in Terraform
### References

https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateWebhook.html#CodeBuild-CreateWebhook-request-filterGroups

-------------------------

Terraform does not support codebuild filterGroups params. I was looking at [Go AWS SDK](https://github.com/aws/aws-sdk-go/blob/master/service/codebuild/api.go#L365) and it's supported but terraform aws provider [does not support it](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codebuild_webhook.go#L23). 
According to the [AWS docs](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_CreateWebhook.html#CodeBuild-CreateWebhook-request-filterGroups) we should use filter. 

> 🗒 It is recommended that you use filterGroups instead of branchFilter.

So far I'm forced to use branchFilter but filterGroup is much more powerful

**Comment by bflad** [comment]
Hi @confiq 👋 Thanks for submitting this. There is a previously created feature request for this, #7503, so to consolidate discussions and efforts I am going to close this issue in preference of the earlier one. Please feel free to 👍 upvote and subscribe there.

**Comment by confiq** [comment]
Hi, I did search but I could not find the issue
