### ISSUE TITLE
aws_route53_resolver_rule creation failure

### ISSUE THREAD

**Issue by aperigault** [terraform-providers/terraform-provider-aws#8014]
### Terraform Version

Terraform v0.11.13
Provider v2.2.0

### Affected Resource(s)

* aws_route53_resolver_rule
* aws_route53_resolver_rule_association

### Debug Output

```
2019-03-19T15:26:13.451+0100 [DEBUG] plugin.terraform-provider-aws_v2.2.0_x4: 2019/03/19 15:26:13 [DEBUG] [aws-sdk-go] {"__type":"InternalServiceErrorException","Message":"[RSLVR-00201] Internal Service Error, please retry your request. Trace ID: \"1-5c90fc04-ce099ee45f3ebff60269b964\""}
2019-03-19T15:26:13.451+0100 [DEBUG] plugin.terraform-provider-aws_v2.2.0_x4: 2019/03/19 15:26:13 [DEBUG] [aws-sdk-go] DEBUG: Validate Response Route53Resolver/AssociateResolverRule failed, not retrying, error InternalServiceErrorException: [RSLVR-00201] Internal Service Error, please retry your request. Trace ID: "1-5c90fc04-ce099ee45f3ebff60269b964"
2019-03-19T15:26:13.451+0100 [DEBUG] plugin.terraform-provider-aws_v2.2.0_x4:   status code: 400, request id: b78b7c30-2e8c-4a0c-a904-b99ebc4fc77c
```

```
Error: Error applying plan:

2 error(s) occurred:
* aws_route53_resolver_rule_association.internal[15]: 1 error(s) occurred:

* aws_route53_resolver_rule_association.internal.15: error creating Route 53 Resolver rule association: InternalServiceErrorException: [RSLVR-00201] Internal Service Error, please retry your request. Trace ID: "1-5c90fc04-fd1942aed75e61a618e3cef6"
	status code: 400, request id: 52b3187c-33dd-4549-ad93-982ffc8a4200
* aws_route53_resolver_rule_association.internal[6]: 1 error(s) occurred:

* aws_route53_resolver_rule_association.internal.6: error creating Route 53 Resolver rule association: InternalServiceErrorException: [RSLVR-00201] Internal Service Error, please retry your request. Trace ID: "1-5c90fc04-ce099ee45f3ebff60269b964"

```

### Expected Behavior

When an AWS API error occurred, terraform retry to create object.

### Actual Behavior

When I attempt to create an aws_route53_resolver_rule or an aws_route53_resolver_rule_association, randomly this error occurred. AWS API seems to return a mysterious "Internal Service Error" and terraform don't "retry later". Is it an expected behavior ?

**Comment by bflad** [comment]
It appears the Route 53 Resolver service is returning these types of errors with a 400 HTTP status instead of the typical 5XX HTTP status. It would probably be best to reach out through an AWS Support case or an [issue upstream in the AWS Go SDK library](https://github.com/aws/aws-sdk-go/issues) to see if the Route 53 Resolver service team can correct the error on the server side or have the AWS Go SDK properly retry automatically in this situation.

We might be able to also workaround this within the provider, but generally we prefer to let the service team and/or AWS Go SDK library fix the problem to reduce any chances of bugs, regressions, or other future maintenance problems with customizing our AWS client code.

**Comment by egarbi** [comment]
I hit the same and open a support case with AWS:
From them: "I'm continuously following up with our Route53 Service Team to get an update on your case. 
This process takes time, which I, unfortunately, do not have insight into and am waiting for an update from our Service Team."
So, it seems it will take some time for them to fix this

**Comment by egarbi** [comment]
From AWS:
```
The fix will be implemented for all regions and all AZ by Friday (17th of May). 
Depending on the region/AZ that you are working in, it may be available earlier in the week.
```

**Comment by egarbi** [comment]
I was told by AWS Route53 Team that this issue hasn't been resolved but mitigated. After that, I have redeployed everything and this time all ran smoothly.

**Comment by bflad** [comment]
Given that this error does not seem to be affecting a large portion of practitioners and seems related to the Route 53 Resolver service itself, I'm going to opt to close this issue. It does not seem like we should expend extra effort in attempting to add code (at the risk of bugs, regressions, or other future maintenance problems with customizing our AWS client code) for a very intermittent API issue that the AWS service team should resolve or provide better guidance via the error messaging. 👍

**Comment by JadyDJ** [comment]
We experience the same again ? 
`2019-06-24T21:21:52.197Z [DEBUG] plugin.terraform-provider-aws_v2.16.0_x4: 2019/06/24 21:21:52 [DEBUG] [aws-sdk-go] {"__type":"InternalServiceErrorException","Message":"[RSLVR-00200] Internal Service Error, trace ID: \"1-5d113ef0-7caf29e93e45ba6fe3a8a5ed\""}
2019-06-24T21:21:52.197Z [DEBUG] plugin.terraform-provider-aws_v2.16.0_x4: 2019/06/24 21:21:52 [DEBUG] [aws-sdk-go] DEBUG: Validate Response Route53Resolver/CreateResolverEndpoint failed, attempt 0/25, error InternalServiceErrorException: [RSLVR-00200] Internal Service Error, trace ID: "1-5d113ef0-7caf29e93e45ba6fe3a8a5ed"
2019-06-24T21:21:52.197Z [DEBUG] plugin.terraform-provider-aws_v2.16.0_x4: 	status code: 400, request id: 4ad52bbb-8def-4005-8bf8-8e4dcb44f554`

**Comment by bflad** [comment]
@JadyDJ you’ll want to reach out to AWS Support
