### ISSUE TITLE
aws_athena_named_query resource support for workgroup

### ISSUE THREAD

**Issue by ndimiduk** [terraform-providers/terraform-provider-aws#8016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_athena_named_query` resource does not allow specification of the workgroup in which the named query is to be stored. Named Queries are created in the account default workgroup only.

### New or Affected Resource(s)

* aws_athena_named_query

### Potential Terraform Configuration

This would be an additional string field on the existing resource.

### References

* https://docs.aws.amazon.com/athena/latest/APIReference/API_CreateNamedQuery.html

**Comment by bflad** [comment]
Support for the new `workgroup` argument in the `aws_athena_named_query` resource has been merged and will release with version 2.20.0 of the Terraform AWS Provider, later today. 👍 Thanks to @paulhudson for the implementation.

**Comment by nywilken** [comment]
The enhancement to the `aws_athena_named_query` resource, has been released in [version 2.20.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2200-july-19-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this resource, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
