### ISSUE TITLE
aws_codebuild_project: CodeBuild Project resource does not allow custom Docker images.

### ISSUE THREAD

**Issue by jkodroff** [terraform-providers/terraform-provider-aws#8028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The CodeBuild Project resource does not appear to allow the use of a custom Docker Image (https://www.terraform.io/docs/providers/aws/r/codebuild_project.html#compute_type), which is a feature present in CodeBuild (https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments/).   CodeBuild can pull from ECR (my use case) or any Docker registry.

This capability would presumably go in the `environment` block of `aws_codebuild_project`.

### New or Affected Resource(s)

* aws_codebuild_project

**Comment by rahulk94** [comment]
For what its worth, it appears you can pull a docker image from DockerHub (or maybe public registries in general) just fine. Perhaps the documentation is just out of date/incorrect? Although I haven't tested with an image from AWS ECR.

I've tested creating a CodeBuild with the following and it executes as expected.
```(sh)
resource "aws_codebuild_project" "codebuild_plan_project" {
  name          = "${var.code_pipeline_name}_plan"
  build_timeout = "15"
  service_role  = "${aws_iam_role.codebuild_plan_role.arn}"

  artifacts {
    type = "CODEPIPELINE"
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "hashicorp/terraform:0.11.14"
    type         = "LINUX_CONTAINER"
  }

  source {
    type = "CODEPIPELINE"

    buildspec = <<BUILD_SPEC
version: 0.2

phases:
  build:
    commands:
      - echo "Starting Codebuild"
      - terraform --version
      - terraform init
      - terraform plan
      - echo "Codebuild done"

BUILD_SPEC
  }
}
```

**Comment by bflad** [comment]
Documentation update submitted: #9268
