### ISSUE TITLE
r/aws_cloudwatch_event_rule: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[Support](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEvents-Tagging.html#supported-resources) for tagging [`aws_cloudwatch_event_rule`](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_rule.html) resources added in [AWS SDK v1.19.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.0):

> Added 3 new APIs, and one additional parameter to the PutRule API, to support tagging of CloudWatch Events rules.

**Comment by bflad** [comment]
Support for managing `aws_cloudwatch_event_rule` tags has been merged and will release with version 2.4.0 of the Terraform AWS Provider, likely later today.

**Comment by bflad** [comment]
This has been released in [version 2.4.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#240-march-29-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
