### ISSUE TITLE
Release 2.1.0 (commit #7794) introduces serious and problematic performance degradation for CloudFront Distribution updates

### ISSUE THREAD

**Issue by m-dunbar** [terraform-providers/terraform-provider-aws#8073]
Provisioner release 2.1.0 (#7794 appears to be the relevant commit related to CloudFront distributions) introduces a significant workflow problem with timing for CloudFront Distribution updates.

Prior to this change, updating an origin path, for example, took seconds to complete. Now, however, the TF apply sits and waits until propagation throughout the CloudFront edge network completes.  This in turn destroys automated workflows. 

Prior to 2.1.0, a CloudFront Distribution update (for example, an origin path change), the portion of a TF apply related to making and registering the change in distribution configuration took, on average, 2 seconds to complete.  Beginning with release 2.1.0, the same CloudFront distribution update time increases to an average of 20 plus minutes, with peak times of over an hour and 20 plus minutes.

It would be nice if a significant change like this included a boolean attribute added (comparable to the 'retain_on_destroy' boolean, but for updates) to allow users to _choose_ whether or not to wait for distribution propagation, or to move on as soon as the change is reflected, as was the behavior prior to release 2.1.0 (#7794).

**Comment by Nowaker** [comment]
There seems to be a technical reason why this was changed: https://github.com/terraform-providers/terraform-provider-aws/commit/286f294cde5eb5c94f742ab1d0f14c6166d07ec0

That said, the disruption caused by 30min+ wait times is massive. For long-waiting resources like this, a boolean switch or a virtual entity like [aws_acm_certification_validation](https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html) should be introduced instead.

**Comment by bflad** [comment]
I will have a pull request posted for this later today.

**Comment by bflad** [comment]
Pull request submitted: #8116

**Comment by Nowaker** [comment]
Awesome work, thanks a million @bflad.

**Comment by m-dunbar** [comment]
Thanks guys!  This will help a lot!

**Comment by bflad** [comment]
A new `wait_for_deployment` argument (defaulting to `true`, set to `false` to skip waiting) for the `aws_cloudfront_distribution` resource has been merged and will release with version 2.5.0 of the Terraform AWS Provider later this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.5.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#250-april-05-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
