### ISSUE TITLE
Add data source for GuardDuty Detector ID in remote acct

### ISSUE THREAD

**Issue by erikpaasonen** [terraform-providers/terraform-provider-aws#8084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We're using the new `aws_guardduty_invite_accepter` resource that was just released. Our hub and spoke model means that the master account GuardDuty detector is created via a different Terraform stack than the stack that runs in each spoke account. We need to lookup the detector ID from the hub account in each region (detector ID value is different per region). We can implement this using a custom data source, it's a simple AWS CLI command. Would be nice to have a Terraform built-in data source to handle this.

### New or Affected Resource(s)

* `aws_guardduty_detector` (as a data source)

### Potential Terraform Configuration

```hcl
data "aws_guardduty_detector" "master_acct" {
  provider = "aws.master_acct"
}

resource "aws_guardduty_member" "spoke_acct" {
  account_id         = "${aws_guardduty_detector.member.account_id}"
  detector_id        = "${data.aws_guardduty_detector.master_acct.id}"
  email              = "required@example.com"
  invite             = true
}
```

### References

* #2489 
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/guardduty.html#GuardDuty.Client.list_detectors

**Comment by bflad** [comment]
The new `aws_guardduty_detector` data source has been merged and will release with version 2.39.0 of the Terraform AWS Provider, by Thursday. Thanks to @DanielRis for the implementation. 👍
