### ISSUE TITLE
CodePipeline action configuration support for Arrays

### ISSUE THREAD

**Issue by gbish** [terraform-providers/terraform-provider-aws#8095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From my dig around in the CodePipeline source, I can see (from what I can tell) that the configuration section of an action only supports strings. This limits you to 1 of 3 options when applying Capabilities to a CloudFormation deploy.

I am currently working around this by ignoring the changes to the `Capabilities` config option and setting the 2nd capability manually, although this feels bad 😬 

The Capabilities that can be set when performing a create/update stack operation are covered here: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html

It is listed in the docs as: `Type: Array of strings`

Sadly I'm nowhere near competent enough in Go to understand the complexities or any glaring issues in allowing a `configuration` block to support arrays.

### Terraform Version

```
Terraform v0.11.13
+ provider.archive v1.1.0
+ provider.aws v2.3.0
```

### Affected Resource(s)

* aws_codepipeline

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "pipeline_bucket" {
  bucket = "pipeline-bucket"
}

resource "aws_s3_bucket" "lambda_bucket" {
  bucket = "lambda-bucket"
}

resource "aws_codebuild_project" "build" {
  name          = "build"
  description   = "Build the CloudFormation template to be deployed"
  build_timeout = "5"
  service_role  = "${aws_iam_role.codebuild_role.arn}"

  artifacts {
    name = "source"
    type = "CODEPIPELINE"
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "infrastructureascode/aws-cli:latest"
    type         = "LINUX_CONTAINER"

    environment_variable {
      name  = "BUCKET"
      value = "${aws_s3_bucket.stripe_data.bucket}"
    }
  }

  source {
    buildspec = "buildspec.yml"
    type      = "CODEPIPELINE"
  }
}

resource "aws_codepipeline" "pipeline" {
  name     = "sample-pipeline"
  role_arn = "${aws_iam_role.codepipeline_role.arn}"

  artifact_store {
    location = "${aws_s3_bucket.pipeline_bucket.bucket}"
    type     = "S3"
  }

  stage {
    name = "Source"

    action {
      name             = "Source"
      category         = "Source"
      owner            = "ThirdParty"
      provider         = "GitHub"
      version          = "1"
      output_artifacts = ["source"]

      configuration {
        Owner  = "repo-owner"
        Repo   = "repo-name"
        Branch = "master"
      }
    }
  }

  stage {
    name = "Build"

    action {
      name             = "Build"
      category         = "Build"
      owner            = "AWS"
      provider         = "CodeBuild"
      input_artifacts  = ["source"]
      output_artifacts = ["cfn"]
      version          = 1

      configuration {
        ProjectName = "${aws_codebuild_project.build.name}"
      }
    }
  }

  stage {
    name = "Deploy"

    action {
      name            = "Deploy"
      category        = "Deploy"
      owner           = "AWS"
      provider        = "CloudFormation"
      input_artifacts = ["cfn"]
      version         = 1

      configuration {
        ActionMode   = "CREATE_UPDATE"
        Capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
        RoleArn      = "${aws_iam_role.cloudformation_role.arn}"
        StackName    = "my-cfn-stack"
        TemplatePath = "cfn::output_sam.yaml"
      }
    }
  }
}
```

### Expected Behavior

CodePipeline resource is created with 2 Capabilities for the deploy action (CloudFormation)

### Actual Behavior

```
aws_codepipeline.pipeline: stage.2.action.0.configuration (Capabilities): '' expected type 'string', got unconvertible type '[]interface {}'
```

### Steps to Reproduce

1. `terraform apply`

**Comment by jkodroff** [comment]
@apparentlymart If you or one of the other maintainers could let us know if there's any workaround for this in HCL, it would be greatly appreciated.

**Comment by jkodroff** [comment]
@gbish The AWS docs are not at all clear about this, but this works:

```
      configuration {
        ActionMode     = "REPLACE_ON_FAILURE"
        Capabilities   = "CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM"
        OutputFileName = "CreateStackOutput.json"
        RoleArn        = "${aws_iam_role.cloudformation_service_role.arn}"
        StackName      = "MyStack"
        TemplatePath   = "build_output::sam-templated.yaml"
      }
```

Here's where I figured it out: https://stackoverflow.com/a/53642822/549

@apparentlymart I think you can probably close this.  I'll add a more thorough example to the resource's docs.

**Comment by gbish** [comment]
@jkodroff I believe I did try that, and it applies successfully, but when I went and inspected the capabilities on the pipeline, only the first one was present. I will give it another spin and see what happens.

Cheers for looking at this.

**Comment by gbish** [comment]
Yes, I've just tried your suggestion @jkodroff and it worked, I think I might have put in a space last time which was probably a bit silly in hindsight.

A docs improvement will be (hopefully) greatly appreciated.

Thanks again.

**Comment by jkodroff** [comment]
@gbish I only "looked" at it because I was facing exactly the same problem.  ;)

The PR to improve the docs is now live.
