### ISSUE TITLE
AWS App Mesh tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As part of AWS App Mesh [GA](https://aws.amazon.com/about-aws/whats-new/2019/03/aws-app-mesh-is-now-generally-available/), resource tagging is [enabled](https://github.com/aws/aws-app-mesh-roadmap/issues/19).

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.19.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.3): https://github.com/terraform-providers/terraform-provider-aws/pull/8098.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6707

**Comment by ewbankkit** [comment]
* [ ] [`aws_appmesh_mesh`](https://github.com/terraform-providers/terraform-provider-aws/pull/8111)
* [ ] `aws_appmesh_route`
* [ ] `aws_appmesh_virtual_node`
* [ ] `aws_appmesh_virtual_router`
* [ ] `aws_appmesh_virtual_service`

**Comment by bflad** [comment]
Support for `aws_appmesh_mesh` tagging has been merged and will release with version 2.17.0 of the Terraform AWS Provider. The other resources are pending implementation. 👍

**Comment by bflad** [comment]
Tagging support for all the above resources has been merged and will be released with version 2.19.0 of the Terraform AWS Provider, likely later this week. Thanks, @kterada0509!

**Comment by bflad** [comment]
This has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
