### ISSUE TITLE
AWS Transfer for SFTP service PrivateLink support

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

AWS Transfer for SFTP service PrivateLink support released:

> This release adds PrivateLink support to your AWS SFTP server endpoint, enabling the customer to access their SFTP server within a VPC, without having to traverse the internet. Customers can now can create a server and specify an option whether they want the endpoint to be hosted as public or in their VPC, and with the in VPC option, SFTP clients and users can access the server only from the customer's VPC or from their on-premises environments using DX or VPN. This release also relaxes the SFTP user name requirements to allow underscores and hyphens.

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.19.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.3): https://github.com/terraform-providers/terraform-provider-aws/pull/8098.
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6584

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.6.0 of the Terraform AWS Provider later today. 👍

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
