### ISSUE TITLE
r/aws_s3_bucket_object: Add support for Glacier Deep Archive storage class

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Amazon S3 Glacier Deep Archive storage class [announced](https://aws.amazon.com/about-aws/whats-new/2019/03/aws-storage-gateway-service-integrates-tape-gateway-with-amazon-s3-glacier-deeparchive-storage-class/).

**Comment by ewbankkit** [comment]
Requires [AWS SDK v1.19.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.3): https://github.com/terraform-providers/terraform-provider-aws/pull/8098.

**Comment by bflad** [comment]
Support for using `DEEP_ARCHIVE` with the `aws_s3_bucket` and `aws_s3_bucket_object` resources has been merged and will release with version 2.4.0 of the Terraform AWS Provider, later today. 👍

**Comment by bflad** [comment]
This has been released in [version 2.4.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#240-march-29-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
