### ISSUE TITLE
aws_route53_resolver_endpoint does not support count 

### ISSUE THREAD

**Issue by JadyDJ** [terraform-providers/terraform-provider-aws#8117]
We try to create dns resolver endpoint in multiple AZs(Subnets) by using the code below:

```
variable "subnet_ids" {
    description = "Protected subnet ID"
    type = "list"
    default = ["subnet-1234", "subnet-2345", "subnet-3456"]
}

resource "aws_route53_resolver_endpoint" "outbound_endpoint" {
    name      = "djif-outbound-test"
    direction = "OUTBOUND"

    security_group_ids = [
        "${var.dns_resolver_sg}"
    ]

    ip_address {
        subnet_id = "${element(var.subnet_ids, count.index)}" 
    }
}
```

Meet with errors: 

> aws_route53_resolver_endpoint.outbound_endpoint: ip_address: attribute supports 2 item as a minimum, config has 1 declared

Please help

**Comment by ewbankkit** [comment]
@JadyDJ It looks like you'll need you'll need to do

```hcl
resource "aws_route53_resolver_endpoint" "outbound_endpoint" {
    name      = "djif-outbound-test"
    direction = "OUTBOUND"

    security_group_ids = [
        "${var.dns_resolver_sg}"
    ]

    ip_address {
        subnet_id = "${element(var.subnet_ids, 0)}" 
    }
    ip_address {
        subnet_id = "${element(var.subnet_ids, 1)}" 
    }
    ip_address {
        subnet_id = "${element(var.subnet_ids, 2)}" 
    }
}
```

**Comment by JadyDJ** [comment]
Thank you, I use `${var.subnet_ids[0]}` which is similar as your suggestion

**Comment by nywilken** [comment]
Hi @JadyDJ I’m happy to hear @ewbankkit was able to help provide guidance with your question. I’m going to mark this as resolved by closing it. If you believe there is an issue to be addressed here please feel free to comment or open a new issue with any additional details.

**Comment by Duchynko** [comment]
We're facing the same problem, even with the 0.12 dynamic nested blocks.

```
dynamic "ip_address" {
    for_each = var.subnet_ids
    content {
      subnet_id = ip_address.value
    }
  }
```

**Error: ip_address: attribute supports 2 item as a minimum, config has 1 declared**

While passing list(string) with only 1 element (1 subnet_id). However, if we pass more than 1 subnet_id, everything works as expected.
