### ISSUE TITLE
Add EXTERNAL to deployment_controller of ECS Service

### ISSUE THREAD

**Issue by atsushi-ishibashi** [terraform-providers/terraform-provider-aws#8133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_ecs_service

### References

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentController.html

**Comment by adenot** [comment]
Any update on this? Very keen to have this feature as currently using CodeDeploy for "blue-green" deployments and it's not great.

**Comment by BensamV** [comment]
This will be great

**Comment by bflad** [comment]
Support for external deployments has been merged and will release with version 2.68.0 of the Terraform AWS Provider, later this week. Thank you to @atsushi-ishibashi and @kumarappan-arumugam for the implementation work. :+1:
