### ISSUE TITLE
Add QuickSight support

### ISSUE THREAD

**Issue by jrobison-sb** [terraform-providers/terraform-provider-aws#8146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice if Terraform supported [AWS QuickSight](https://aws.amazon.com/quicksight/). Support for this service has been part of aws-sdk-go as of [1.15.80](https://github.com/aws/aws-sdk-go/commit/57d992f58b7e092da10921050426717f7944bd42#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR15)

### New or Affected Resource(s)

* [aws_quicksight_group](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateGroup.html)
* [aws_quicksight_user](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_RegisterUser.html)
* [aws_quicksight_dashboard](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_GetDashboardEmbedUrl.html)
* and so on... the above are only mentioned as possible examples of how this might be supported.

Thanks to anyone who can make this happen.

**Comment by nywilken** [comment]
The new `aws_quicksight_group` resource, has been released in [version 2.20.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2200-july-19-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this resource, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!

**Comment by mjgpy3** [comment]
Note that QuickSight dashboard URLs (as linked above) are ephemeral (signed/secured to logged-in user and only valid for 5 minutes). So, they're probably not the kind of thing that should be managed via terraform.

**Comment by bflad** [comment]
Hi everyone 👋 A new `aws_quicksight_user` resource has been merged (#10401) which will release in version 2.33.0 of the Terraform AWS Provider, Thursday. Thanks to @mjgpy3 for the implementation there. 😄 

Given that the two initial new resource asks have been completed and since these "support service" feature requests tend to have increasing scope over time, we are going to opt to close this GitHub issue to encourage future feature requests and bug reports to be handled separately in targeted new GitHub issues. Thank you!
