### ISSUE TITLE
Add Import Support for aws_cloudwatch_log_subscription_filter

### ISSUE THREAD

**Issue by connor-tyndall** [terraform-providers/terraform-provider-aws#8147]
### Terraform Version

At least up to v0.11.13

### Affected Resource(s)
    aws_cloudwatch_log_subscription_filter

### Expected Behavior

Running the import command for these resources should update the state.

### Actual Behavior

Message `resource <resource> doesn't support import.`

**Comment by bflad** [comment]
Support for importing `aws_cloudwatch_log_subscription_filter` resources has been merged and will release with version 2.5.0 of the Terraform AWS Provider, likely later today. 👍

**Comment by bflad** [comment]
This has been released in [version 2.5.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#250-april-05-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
