### ISSUE TITLE
bid_price parameter for the Master instance group in EMR

### ISSUE THREAD

**Issue by BillelGuerfa** [terraform-providers/terraform-provider-aws#8153]
The instance_group section of EMR Cluster documentation says: 

> bid_price - (Optional) If set, the bid price for each EC2 instance in the instance group, expressed in USD. By setting this attribute, the instance group is being declared as a Spot Instance, and will implicitly create a Spot request. Leave this blank to use On-Demand Instances. **bid_price can not be set for the MASTER instance group**, since that group must always be On-Demand

However, I believe this is outdated since the Master instance group can be on spot instances.
Please update the documentation page if this is not a mistake on my side :) 
Link : https://www.terraform.io/docs/providers/aws/r/emr_cluster.html#instance_group-1

**Comment by nywilken** [comment]
Thanks for reporting this issue! Documentation fix submitted in https://github.com/terraform-providers/terraform-provider-aws/pull/8160
