### ISSUE TITLE
Cognito Pinpoint integration

### ISSUE THREAD

**Issue by tonyxiao** [terraform-providers/terraform-provider-aws#8156]
Migrated over from #4990 

Cognito now can integrate with Pinpoint for out-of-box analytics. It would be great to have this support in terraform. 

![image](https://user-images.githubusercontent.com/696842/55379224-2b212000-54d1-11e9-9f83-387357826836.png)

**Comment by nikitacr7** [comment]
Hello @bflad @tonyxiao,

Do you have any updates on this? 

Best regards,
Nikita.

**Comment by bflad** [comment]
Support for an `analytics_configuration` configuration block in the `aws_cognito_user_pool_client` resource has been merged and will release with version 2.54.0 of the Terraform AWS Provider, later this week. Thanks to @DrFaust92 for the implementation. 👍
