### ISSUE TITLE
Question: Idempotent instance provision

### ISSUE THREAD

**Issue by tracyhanke** [terraform-providers/terraform-provider-aws#8163]
**Description**
Hi,

Currently in my use case, I've encountered a situation that terraform-provider-aws seems not to handle properly, so I've tried to figure out my own solution, trying to get some review and suggestions here.

Use case: When we trying to launch instances with terraform, process might be interrupted unexpectedly before state file is properly written, but after RPC calls are sent (power off, os crash, etc.).
In that case, there will be "orphan" instances provisioned in aws, but untracked by terraform state file. If I try to restart the provision, there will be another instance provisioned in aws, so 2 in total, which is incorrect from my perspective. To solve this, I don't want to import infrastructure manually after interruption, so I want terraform-provider-aws code to handle this situation.

Solution: Use `tag:Name` as identifier, when we trying to create an instance, firstly we find if there are unterminated instances with same `Name` tag existing in aws. If so, import info and return (skip creating).

**Modified Code**
```go
diff --git a/aws/resource_aws_instance.go b/aws/resource_aws_instance.go
index 21635731d..19c7ffee6 100644
--- a/aws/resource_aws_instance.go
+++ b/aws/resource_aws_instance.go
@@ -551,6 +551,36 @@ func resourceAwsInstanceCreate(d *schema.ResourceData, meta interface{}) error {
 
   tagsSpec := make([]*ec2.TagSpecification, 0)
 
+  // check duplicate tag block, treat "Name" as unique tag key
+  if v, ok := d.GetOk("tags"); ok {
+    if name, nameOk := v.(map[string]interface{})["Name"]; nameOk {
+      // start finding instance with same tag
+      opts := &ec2.DescribeInstancesInput{
+        Filters: []*ec2.Filter{
+          {
+            Name:   aws.String("tag:Name"),
+            Values: []*string{aws.String(name.(string))},
+          },
+        },
+      }
+      resp, err := conn.DescribeInstances(opts)
+
+      if err != nil {
+        return errors.New("Error when trying fetching existing instance info")
+      }
+      if len(resp.Reservations) != 0 {
+        for _, reservation := range resp.Reservations {
+          for _, instance := range reservation.Instances {
+            if *instance.State.Name != "terminated" {
+              d.SetId(*instance.InstanceId)
+              return resourceAwsInstanceUpdate(d, meta)
+            }
+          }
+        }
+      }
+    }
+  }
```
**Steps to Reproduce**
1. `terraform init`
2. `terraform apply -auto-approve`
3. press `ctrl-c` twice before state file is written
4. `terraform apply -auto-approve`

**Output before**
2 instances with same name `demo_1` provisioned in aws
**Output after**
only 1 instance provisioned in aws
**Terraform Version**
0.11.13
**AWS Provider Version**
modified from provider.aws 2.4.0
**Affected Resources**
aws.instance
**Terraform Configuration Files**
```terraform
resource "aws_instance" "demo_1" {
  ami = "ami-06397100adf427136"
  instance_type = "t2.micro"
  security_groups = ["default"]
  tags = [
    {
      Name = "demo_1"
    }
  ]
}
```

**Comment by nywilken** [comment]
Hi @tracyhanke thanks for your question. In order for Terraform to manage the infrastructure in question it must be successfully written to the state file. This is to prevent Terraform from modifying or destroying unmanaged resources.  In the case you mention, Terraform is not aware of any existing state so it believes, according to its state, that the infrastructure needs to be created. This is the ideal situation for the `terraform import` command. As it is an explicit action to bring the said infrastructure under management. 

The solution you mention is essentially trying to do an auto import based off the query, but would introduce other issues as it is not the provider that determines to create or update a resource but Terraform Core based off the existing state. In addition to the latter, if a previous Terraform run failed or was interrupted, leaving dangling resources, it is not safe to assume that the infrastructure is in the correct state. 

The preferred order of operations here would be 
```
terraform import aws_instance.demo_1 <demo_1-instance-id>
terraform refresh # pull in latest instance configuration
terraform apply
```
Thanks again for bringing up the questions, and proposal.

**Comment by nywilken** [comment]
I'm going close this issue for now, but if you think I closed the issue prematurely or if you believe this is an issue please comment and I can open the issue back up.

**Comment by tracyhanke** [comment]
Hi @nywilken,

Thanks for your response, and I still want to have some follow-up discussion with you.

Let's say in my use case, I've assumed that `tag:Name` is unique in my deployment environment, so that I don't expect to see any two instances with same `Name` tag. Meanwhile, let's suppose I'm careful enough that I won't deploy different resources with same `Name` tag unless my deployment is unexpected interrupted and I need to restart deployment.
Considering your suggestion, I've changed my workflow into:
**before creating any instance, I check if there exists instances with same Name tag. If so, I ~~import those instances into state file and do nothing~~ destroy those instances, and continue creation as planned.**

How about this? Do you think it's a good idea?
