### ISSUE TITLE
Cloudwatch event ECS Target can't be passed as a variable when used as a module

### ISSUE THREAD

**Issue by avallecillac** [terraform-providers/terraform-provider-aws#8167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.13
+ provider.aws v2.4.0
+ provider.template v2.1.0

### Affected Resource(s)
* aws_cloudwatch_event_target

### Terraform Configuration Files

```hcl

variable "ecs_target" {
  type = "map"
}

resource "aws_cloudwatch_event_rule" "ecs" {
  name                = "CloudwatchRuleName"
  description         = "Runs ecs scheduled tasks"
  schedule_expression = "cron(0 14 ? * MON *)"
  is_enabled          = "true"
}

resource "aws_cloudwatch_event_target" "ecs_target" {
  rule     = "${aws_cloudwatch_event_rule.ecs.name}"
  arn      = "my_cluster_arn"
  role_arn = "role_arn"

  ecs_target = ${var.ecs_target}
}
Above resources are in a file as a module. Let's say in the path: "cloudwatch_events/main.tf

module "my_cloudwatch_ecs_target" {
  source  = "cloudwatch_events/"
  ecs_target = {
    task_definition_arn = "my_task_definition_arn"
    task_count         = 1
  }
}

```

### Debug Output
Error: module.my_cloudwatch_ecs_target.aws_cloudwatch_event_target.ecs_target: ecs_target: should be a list

### Expected Behavior

ecs_target values must be passed correctly. Documentation specifies ecs_target is a map not a list. 

### Actual Behavior
When running terraform plan it throws the error described above. 
The weird behavior is that if you pass a map directly to the resource it works.
```hcl
resource "aws_cloudwatch_event_target" "ecs_target" {
  rule     = "${aws_cloudwatch_event_rule.ecs.name}"
  arn      = "my_cluster_arn"
  role_arn = "role_arn"

  ecs_target = {
    task_definition_arn = "my_task_definition_arn"
    task_count         = 1
  }
}
```
But no when it's from a variable.

### Steps to Reproduce
Try passing ecs_target as a variable it should fail saying -> ecs_target: should be a list
1. terraform plan

**Comment by corymhall** [comment]
I think you need to do something like this:

```
module "my_cloudwatch_ecs_target" {
  source  = "cloudwatch_events/"
  ecs_target = [
    {
      task_definition_arn = "my_task_definition_arn"
      task_count         = 1
    }
  ]
}
```

The `ecs_target` variable is of type `TypeList` so if you are passing the value as a variable, that variable has to be a list type as well.

**Comment by avallecillac** [comment]
I tried as you said and got this error:
Error: module.test.aws_cloudwatch_event_target.ecs_target: ecs_target: should be a list

Also tried passing a map but wrapping it up with "[ ]" in the resource:
```hcl
resource "aws_cloudwatch_event_target" "ecs_target" {
  rule     = "${var.var3}"
  arn      = "${var.var1}"
  role_arn = "${var.var2}"

  ecs_target = [
     "${var.ecs_target}"
  ]
}
```
And it throws:
Error: module.test.aws_cloudwatch_event_target.ecs_target: "ecs_target.0.task_definition_arn": required field is not set

**Comment by corymhall** [comment]
Did you also update the type of your `ecs_target` variable? I was able to get it to work with this configuration
`Module invocation`
```
module "my_cloudwatch_ecs_target" {
  source  = "cloudwatch_events/"
  ecs_target = [
    {
      task_definition_arn = "my_task_definition_arn"
      task_count         = "1"
    }
  ]
}
```

`module config`
```
variable "ecs_target" {
  description = "description"
  default     = []
  type        = "list"
}

resource "aws_cloudwatch_event_target" "ecs_target" {
  rule     = "${aws_cloudwatch_event_rule.ecs.name}"
  arn      = "my_cluster_arn"
  role_arn = "role_arn"

  ecs_target = "${var.ecs_target}"
}

```

**Comment by avallecillac** [comment]
Can you provide your terraform and aws provider versions please.

**Comment by corymhall** [comment]
aws provider version `2.6.0`
terraform version `0.11.13`

**Comment by aeschright** [comment]
Hi @avallecillac , did the last suggestion above resolve your issue?

**Comment by bflad** [comment]
Closing due to lack of response. If you are still having issues on recent versions of Terraform CLI (0.12+) and the Terraform AWS Provider, please create a new issue and we will take a fresh look. Thanks.
