### ISSUE TITLE
Support for eks control pane logs

### ISSUE THREAD

**Issue by mukgupta** [terraform-providers/terraform-provider-aws#8204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added support for eks control pane logs(https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html) Can we add it to aws_eks_cluster resource. 

### New or Affected Resource(s)

* aws_eks_cluster

### References

* https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html
* https://aws.amazon.com/about-aws/whats-new/2019/04/amazon-eks-now-delivers-kubernetes-control-plane-logs-to-amazon-/

**Comment by ewbankkit** [comment]
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8196

**Comment by ewbankkit** [comment]
I can work on this today if nobody else is.

**Comment by MarcusNoble** [comment]
I'd like to take a stab at it this if it's ok :)

**Comment by ewbankkit** [comment]
@MarcusNoble Sure, go ahead.

**Comment by bflad** [comment]
This has been released in [version 2.6.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
