### ISSUE TITLE
Enable Access Logs for NLB

### ISSUE THREAD

**Issue by mbamber** [terraform-providers/terraform-provider-aws#8208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the `aws_lb` resource does not allow enabling of access logs. It would be really helpful if access logs could be enabled via terraform for Network Load Balancers 

### New or Affected Resource(s)

* aws_lb

**Comment by ewbankkit** [comment]
Documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html.

**Comment by mbamber** [comment]
But TF doesn't support this yet, no?

**Comment by bflad** [comment]
@mbamber correct, the `aws_lb` resource currently ignores configuring NLB access logs. I'm currently working on removing that. 👍

**Comment by mbamber** [comment]
Thanks for this @bflad - Looking forward to seeing this merged 👍

**Comment by bflad** [comment]
Support for NLB access logs has been merged and will release with version 2.8.0 of the Terraform AWS Provider, likely later this week. 👍

**Comment by nywilken** [comment]
This has been released in [version 2.8.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#280-april-26-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For additional feature requests or bug reports with WorkLink functionality, please open new GitHub issues.
