### ISSUE TITLE
aws_security_group_rule description validation rejects '&' when it's accepted by the AWS web console

### ISSUE THREAD

**Issue by nodakai** [terraform-providers/terraform-provider-aws#8217]
> Error: module.fra.module.default-sg.aws_security_group_rule.consul-tcp[6]: "description" doesn't comply with restrictions ("^[A-Za-z0-9 \\.\\_\\-\\:\\/\\(\\)\\#\\,\\@\\[\\]\\+\\=\\;\\{\\}\\!\\$\\*]*$"): "DNS/TCP from (...snip...) H&F"

https://github.com/terraform-providers/terraform-provider-aws/blob/4e9b7c787588267797a3eabaf2b39bec6dc016d9/aws/validators.go#L1886

**Comment by aeschright** [comment]
Hi @nodakai 👋 It sounds like you might have found an issue, but there isn't enough information in your report for us to look into it. If you can provide a configuration that will demonstrate the error and your full output log, please open a new bug report with those details. Thank you!

**Comment by nodakai** [comment]
Are you a new junior hire or something? You don’t seem to have much experiences with this product. I even pointed out which line of the source code is problematic.

I’m on mobile now
