### ISSUE TITLE
aws_securit_group_rule doesn't honor complete security group name

### ISSUE THREAD

**Issue by rverma-nikiai** [terraform-providers/terraform-provider-aws#8231]
This is intentionally created as a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/159 to gain some traction from contributors and reviewers

**Comment by aeschright** [comment]
Hi @rverma-nikiai -- I appreciate that this issue is important to you, but adding a duplicate makes it harder for us to track and resolve things. I'm going to close it in order to redirect efforts to the original issue. We'll continue to work through the backlog. Thanks!
