### ISSUE TITLE
Creating lambda function on first apply fails on IAM eventual consistency

### ISSUE THREAD

**Issue by vroy** [terraform-providers/terraform-provider-aws#8248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
❯ terraform -v
Terraform v0.11.11
+ provider.aws v1.49.0
+ provider.template v2.1.0
```

### Affected Resource(s)

* aws_lambda_function

### Expected Behavior

The function to be created successfully, eventually.

### Actual Behavior

The function fails to create with an error such as:

```
* aws_lambda_function.launch_connector: Error creating Lambda function: InvalidParameterValueException: The provided execution role does not have permissions to call SendMessage on SQS
	status code: 400, request id: 3e4b6f87-574d-11e9-902b-d3347aae84d4
* aws_iam_policy.launch_connector: 1 error(s) occurred:
```

This is an action that is already retried, but it seems like a minute is not sufficient. We user terraform workspaces extensively for developer workspaces and used to see this error semi-regularly in us-east-1 until we increased the timeout to 3 minutes.

**Comment by ryndaniels** [comment]
Hi @vroy! Thanks for letting us know about this problem! In order to help us better investigate this, could you edit this issue to include the relevant parts of your Terraform configuration? If you're able to give this a try with the most recent versions of Terraform and of the AWS Provider, and let us know if you're still seeing this error, that would be helpful as well. Thanks! 🙂

**Comment by vroy** [comment]
Our configuration is akin to this: https://gist.github.com/vroy/96b0cdcbbb86e91d38b51414b6294fe7

The problem we run into is is the equivalent of removing the `aws_iam_role_policy_attachment` resource. This is because changes in IAM can take a while to propagate.

What we were seeing in some cases, when AWS was slower than usual, is that would be retried for more than one minute, but the IAM resources **always** existed in the end. Increasing the timeout on our fork improved the situation and we have yet to see this problem again.

```
aws_iam_role_policy_attachment.example: Creating...
aws_iam_role_policy_attachment.example: Creation complete after 0s [id=example-20190911120730304700000001]
aws_lambda_function.example: Still creating... [10s elapsed]
aws_lambda_function.example: Creation complete after 17s [id=example]
```

```
❯ ag '(Validate Response lambda\/CreateFunction|\[TRACE\] Waiting)' debug.log
768:2019-09-11T09:07:29.877-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:29 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/CreateFunction failed, attempt 0/25, error InvalidParameterValueException: The role defined for t
he function cannot be assumed by Lambda.
774:2019-09-11T09:07:29.877-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:29 [TRACE] Waiting 500ms before next try
938:2019-09-11T09:07:30.535-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:30 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/CreateFunction failed, attempt 0/25, error InvalidParameterValueException: The role defined for t
he function cannot be assumed by Lambda.
944:2019-09-11T09:07:30.535-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:30 [TRACE] Waiting 1s before next try
970:2019-09-11T09:07:31.694-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:31 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/CreateFunction failed, attempt 0/25, error InvalidParameterValueException: The role defined for t
he function cannot be assumed by Lambda.
976:2019-09-11T09:07:31.694-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:31 [TRACE] Waiting 2s before next try
1002:2019-09-11T09:07:33.853-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:33 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/CreateFunction failed, attempt 0/25, error InvalidParameterValueException: The role defined for
the function cannot be assumed by Lambda.
1008:2019-09-11T09:07:33.853-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:33 [TRACE] Waiting 4s before next try
1034:2019-09-11T09:07:38.044-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:38 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/CreateFunction failed, attempt 0/25, error InvalidParameterValueException: The provided executio
n role does not have permissions to call SendMessage on SQS
1040:2019-09-11T09:07:38.044-0300 [DEBUG] plugin.terraform-provider-aws_v2.27.0_x4: 2019/09/11 09:07:38 [TRACE] Waiting 8s before next try
```

**Comment by ryndaniels** [comment]
Hi @vroy - thanks for the configuration example and additional information! Yes, these sorts of intermittent timeout issues are a known problem - especially around IAM resources. Increasing the timeouts is generally what we recommend in cases like this, so since you said that is working for you know, I'm going to go ahead and close this, but please feel free to open another issue if you run into further problems!

**Comment by vroy** [comment]
This is working for us with the patch applied in #8249
