### ISSUE TITLE
Revert website sidebar navigation change

### ISSUE THREAD

**Issue by robbruce** [terraform-providers/terraform-provider-aws#8252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Website Sidebar navigation is now harder to use, during development would often find resources by searching on the page by name.

Now that submenu's have been used, resources cannot be found by the browser.

### New or Affected Resource(s)

Website navigation

**Comment by jeff-french** [comment]
I like the new change. Would like to see a search bar at the top of the navbar to filter resources, however, by clicking the "Expand / Collapse All" link at the very top you can still search using the browser's find feature just like before.

**Comment by nfagerlund** [comment]
Hello! The new design has an "expand/collapse all" control which will expand the sidebar into its old form without reloading the page. Could we convince you to try that for a little while and see if that meets your cmd-F needs? 

Here's how we were thinking when we made this change:

use case | before change | after change
--|--|--
cmd-F for things | works fine | requires one extra click, then works fine
browsing sidebar for things | impossible | works fine

It's a tradeoff, but the gain/loss for the two use cases was pretty unbalanced. 

We're also hoping to add some filtering/searching functionality in the future, which would make this much nicer.

**Comment by robbruce** [comment]
Agree that the sidebar menu was getting messy, especially the data sources not being categorised.

Maybe add a short cut to expand/collapse all? It would just help those who operate quickly by keypresses. So sequence would become

|use case|before change|after change|
|--|--|--|
|cmd-F for things|works fine|shortcut or click, then works fine|
|browsing sidebar for things|impossible|works fine|

**Comment by bflad** [comment]
Related to the data source categorization, we'll likely handle that via #8225 😄

**Comment by nfagerlund** [comment]
@robbruce We're considering a filter field that can activate on `/`, like the search fields on github/gmail/twitter/etc.

https://github.com/hashicorp/terraform-website/pull/750

**Comment by bflad** [comment]
Filterable navigation is now live: https://www.terraform.io/docs/providers/aws/index.html

Browsing and typing `/` the `instance` yields:

<img width="476" alt="Screen Shot 2019-04-12 at 8 16 50 AM" src="https://user-images.githubusercontent.com/189114/56036661-660a2b80-5cfb-11e9-8373-3e261a646113.png">

**Comment by nywilken** [comment]
I believe this has been addressed in the latest sidebar changes. I am going to close this issue, but if future sidebar changes become a problem please feel free to open a new issue. All the best.
