### ISSUE TITLE
backend s3 does not source the region

### ISSUE THREAD

**Issue by deitch** [terraform-providers/terraform-provider-aws#8256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

`backend "s3"` (which is in terraform core, but uses credentials code from aws provider, according to @apparentlymart )

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {
    bucket = "terraform-tfstate-s3-test"
    key    = "test.tfstate"
    encrypt = true
    dynamodb_table = "terraform-lock-s3-test"
    profile = "backend-test"
  }
}
```

FYI, my `~/.aws/config` includes the following:

```toml
[profile backend-test]
aws_access_key_id=******
aws_secret_access_key=*****
region=us-east-1
```

### Debug Output

https://gist.github.com/deitch/3e7dac801c4f316ec322b38a0990a425

### Expected Behavior

It should have sourced the `region` from the `profile`.

### Actual Behavior

It did not source the region, asking me for it.

This problem goes away if I do one of the following:

* explicitly set `region = <region>` in the `backend` config
* set `AWS_DEFAULT_REGION` env var

However, it shouldn't need to.

### Steps to Reproduce

1. Create a directory
2. Put in the `main.tf` file from above
3. Create a profile with appropriate credentials and region in your `~/.aws/config` 
4. `terraform init .`

### Important Factoids

Note that it _does_ appear to be sourcing the credentials from the profile in `~/.aws/config` , but not the region.

### References

See thread beginning [here](https://github.com/hashicorp/terraform/issues/15188#issuecomment-481322495) from https://github.com/hashicorp/terraform with @apparentlymart

**Comment by nywilken** [comment]
Hi @deitch thank you for bringing over this thread from the Terraform repo. This is a duplicate issue of #7750. I recommend that we comment there so that all parties are in the know. For now, I am going to label and close this issue.

**Comment by deitch** [comment]
Thanks @nywilken. I did do a search before opening, but missed it. I’ll subscribe to that one.
