### ISSUE TITLE
Feature request: "worker type" and "number of workers" arguments on aws_glue_job resource

### ISSUE THREAD

**Issue by vasili-zolotov** [terraform-providers/terraform-provider-aws#8257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Glue team has introduced new worker types to support memory intensive and ML workloads on Glue. This brings the requirement to support "worker type" and "number of workers" agrumnets on the aws_glue_job resource.

See the announcement: https://aws.amazon.com/about-aws/whats-new/2019/04/aws-glue-now-supports-additional-configuration-options-for-memory-intensive-jobs/

### New or Affected Resource(s)

* aws_glue_job

### Potential Terraform Configuration

```hcl
resource "aws_glue_job" "job_id" {
  name                        = "job-name"
  worker_type             = "G.1X"
  number_of_workers = 10
  # other arguments
}
```

### References

* N/A

**Comment by bflad** [comment]
Support for the `number_of_workers` and `worker_type` arguments to the `aws_glue_job` resource has been merged and will release in version 2.39.0 of the Terraform AWS Provider, likely tomorrow. Thanks to @Zambonilli for the implementation. 👍
