### ISSUE TITLE
Support multiple aws_lb_listener_rule condition values

### ISSUE THREAD

**Issue by tolleiv** [terraform-providers/terraform-provider-aws#8266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.13

### Affected Resource(s)

* aws_lb_listener_rule

### Terraform Configuration Files

```hcl
resource "aws_lb_listener_rule" "source_ip_rule" {
  listener_arn = "${var.listener_arn}"
  priority     = 99

  action {
    type             = "forward"
    target_group_arn = "${var.targetgroup_arn}"
  }
  condition {
    field  = "source-ip"
    values = ["1.2.3.4/32","5.6.7.8/32"]
  }
}
```
### Expected Behavior

Terraform should create a listener rule with a source-ip condition containing the two values.

### Actual Behavior

```
Error: aws_lb_listener_rule.host_nicotua_management: condition.0.values: attribute supports 1 item maximum, config has 2 declared
````

### Steps to Reproduce

1. `terraform validate`

### References

This behaviour was introduced within https://github.com/hashicorp/terraform/issues/12983 but the assumption made back then is only true for some of the various condition types. Others (like the source-ip) support multiple values.

* https://github.com/hashicorp/terraform/issues/12983

Official documentation:

* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#listener-rules

**Comment by AlexeiBlue** [comment]
Just ran into the same issue for source-ip, weird that values is an array but then the documentation says a maximum of 1 can be defined.

**Comment by amaziagur** [comment]
Ran into same issue (with different exception)

same terraform version @tolleiv (v0.11.13)
used the following code:

` condition {
        field  = "source-ip"
        values = ["1.2.3.4/32"]
    }`

and got the following exception:

```
ValidationError: 'Values' is not supported for a condition of type 'source-ip
```
i saw on aws documentation the usage of `source-ip` field, but
for some reason i didn't saw on terraform official documentation the use of it -> https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html
and ides what im doing wrong here?

**Comment by pyranja** [comment]
`source_ip` and multiple condition values are new ALB features, that are not yet supported. Progress is tracked on https://github.com/terraform-providers/terraform-provider-aws/issues/8126

**Comment by tolleiv** [comment]
Thx @pyranja - I'll close this one then.
