### ISSUE TITLE
Add rate expression in backup_plan schedule argument

### ISSUE THREAD

**Issue by dimisjim** [terraform-providers/terraform-provider-aws#8269]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

schedule argument in aws_backup_plan resource does not accept aws' "rate" expressions, just cron ones
https://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html
### New or Affected Resource(s)

* aws_backup_plan

### Potential Terraform Configuration

```hcl
schedule = "rate(1 day)"
```

Pinging @bflad and @slapula as they were the ones involved in the development of this resource.

**Comment by nywilken** [comment]
Hi @dimisjim thanks for opening up this issue. Unfortunately, the rate expression is not supported by the AWS Backup API so this is not something that we can support at this time. I recommend opening up an issue with AWS support requesting this feature. 

If rate expressions get added in the future the current implementation of the resource should support it without change. 

I’m going to close this issue, but if you find that you are running into issues with current supported implementation please feel free to open a new issue.
