### ISSUE TITLE
Terraform 0.12.0 Beta with AWS Provider 2.6.0?

### ISSUE THREAD

**Issue by Jumblemuddle** [terraform-providers/terraform-provider-aws#8310]
I see that's a 1.60 version of the AWS provider that's compatible with Terraform 0.12.0-beta1, however is it possible to use the new 2.6.0 version with the beta? I'd like to try out the new syntax and whatnot, however I require feature from v2.6.0.

**Comment by mutt13y** [comment]
I tested this and it does not work. I get
````
Failed to instantiate provider "aws" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
````
also see https://github.com/hashicorp/terraform/issues/19416

Annoying because I hit a bug in 1.60

**Comment by nywilken** [comment]
Hi @Jumblemuddle @mutt13y the latest Terraform AWS provider release 2.7.0 should help here. Please feel free to pull it down via `terraform init` and give it a run. 

Please report any unexpected behavior in new GitHub issues (Terraform core: https://github.com/hashicorp/terraform/issues or Terraform AWS Provider: https://github.com/terraform-providers/terraform-provider-aws/issues) (#8366)
