### ISSUE TITLE
Support aws_elasticsearch_domain advanced_options in terraform 0.12.0-beta1 broken

### ISSUE THREAD

**Issue by lscheidler** [terraform-providers/terraform-provider-aws#8332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.0-beta1
+ provider.aws v2.6.0

### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

```hcl
variable "domain" {
  default = "tf-test"
}

data "aws_vpc" "selected" {
}

data "aws_subnet_ids" "selected" {
  vpc_id = "${data.aws_vpc.selected.id}"
}

data "aws_region" "current" {}

data "aws_caller_identity" "current" {}

provider "aws" {
  version = "~> 2.0"

  region = "eu-central-1"
}

resource "aws_security_group" "es" {
  name        = "elasticsearch-${var.domain}"
  description = "Managed by Terraform"
  vpc_id      = "${data.aws_vpc.selected.id}"

  ingress {
    from_port = 443
    to_port   = 443
    protocol  = "tcp"

    cidr_blocks = [
      "${data.aws_vpc.selected.cidr_blocks}",
    ]
  }
}

resource "aws_iam_service_linked_role" "es" {
  aws_service_name = "es.amazonaws.com"
}

resource "aws_elasticsearch_domain" "es" {
  domain_name           = "${var.domain}"
  elasticsearch_version = "6.3"

  cluster_config {
    instance_type = "m4.large.elasticsearch"
  }

  vpc_options {
    subnet_ids = [
      "${data.aws_subnet_ids.selected.ids[0]}",
      "${data.aws_subnet_ids.selected.ids[1]}",
    ]

    security_group_ids = ["${aws_security_group.es.id}"]
  }

  advanced_options {
    "rest.action.multi.allow_explicit_index" = "true"
  }

  access_policies = <<CONFIG
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "es:*",
            "Principal": "*",
            "Effect": "Allow",
            "Resource": "arn:aws:es:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:domain/${var.domain}/*"
        }
    ]
}
CONFIG

  snapshot_options {
    automated_snapshot_start_hour = 23
  }

  tags {
    Domain = "TestDomain"
  }

  depends_on = [
    "aws_iam_service_linked_role.es",
  ]
}
```

### Expected Behavior

```
$ terraform validate
$ echo $?
0
```

### Actual Behavior

```
$ terraform validate
Error: Invalid argument name

  on main.tf line 60, in resource "aws_elasticsearch_domain" "es":
  60:     "rest.action.multi.allow_explicit_index" = "true"

Argument names must not be quoted.
```

### Steps to Reproduce

1. `terraform validate`

**Comment by bflad** [comment]
Hi @lscheidler 👋 Sorry you are running into trouble here. Does running the [`terraform 0.12upgrade` command](https://www.terraform.io/docs/commands/0.12upgrade.html) fix the configuration correctly? See also the: https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-configuration

I believe in this case even manually changing the configuration to something like the below (adding the equals sign to `advanced_options` should help:

```hcl
resource "aws_elasticsearch_domain" "es" {
  # ... other configuration ...

  advanced_options = {
    "rest.action.multi.allow_explicit_index" = "true"
  }
}
```

Can you please try either of those out and let us know? I'll submit the resource documentation update to add the equals sign in the example as it compatible with both Terraform 0.11 and 0.12.

**Comment by lscheidler** [comment]
Hi @bflad, no problem, was testing my configuration with  Terraform 0.12 to prepare it for migration, when Terraform 0.12 is released.

The equals sign and terraform 0.12upgrade seems to fix the issue, because the new error message is
```
Error: failed to load provider "aws": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```
because the plugin is not yet compatible with Terraform 0.12.

**Comment by mendhak** [comment]
@bflad  `terraform 0.12upgrade`  doesn't modify that line.   It still remains as

    advanced_options = {
    "rest.action.multi.allow_explicit_index" = "true"
  }


Removing the quotes results in 

> A managed resource "rest" "action" has not been declared in my_module_name


Leaving the quotes results in

> Error: Invalid argument name
>  on analyser/elasticsearch_fganalyser.tf line 94, in resource "aws_elasticsearch_domain" "my_module_name":
>   94:     "rest.action.multi.allow_explicit_index" = "true"
> Argument names must not be quoted.

Please help, what can we do?

**Comment by bflad** [comment]
This upstream Terraform Core issue looks relevant here: https://github.com/hashicorp/terraform/issues/21402

**Comment by shellshock1953** [comment]
I have the same issue.
0.12upgrade does not change this line. 
Cant guess any workaround.

**Comment by bflad** [comment]
The original issue appears to be resolved by adding an equals sign for the `advanced_options` argument, e.g.

```hcl
resource "aws_elasticsearch_domain" "example" {
  # ... other configuration ...

  advanced_options = {
    "rest.action.multi.allow_explicit_index" = "true"
  }
}
```

Any lingering issues with `terraform 0.12upgrade` not handling syntax conversion correctly should be submitted upstream as a [bug report to the Terraform CLI repository](https://github.com/hashicorp/terraform/issues/new?template=bug_report.md), as the Terraform AWS Provider codebase has no influence over the command's behavior. 👍
