### ISSUE TITLE
data source aws_launch_template could be filtered on tags and create-time

### ISSUE THREAD

**Issue by nitrocode** [terraform-providers/terraform-provider-aws#8367]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to filter my launch templates using create-time and tags and that seems supported by the API

https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-launch-templates.html

The name would have to switched to optional so we can find stuff by tag.

### New or Affected Resource(s)

* `aws_launch_template`

### Potential Terraform Configuration

```hcl
data "aws_launch_template" "default" {
  tags {
    "ami"           = "ami-12983912839"
    "instance-type" = "r5"
  }
}
```

**Comment by bflad** [comment]
Support for finding by `tags` on the `aws_launch_template` data source has been merged and will release with version 2.55.0 of the Terraform AWS Provider, likely later today. Thanks to @DrFaust92 for the implementation. 👍 

If you're still interested in creation time, please submit a new feature request. Thanks!
