### ISSUE TITLE
aws_db_instance seemingly ignores backup_retention_period

### ISSUE THREAD

**Issue by smaslennikov** [terraform-providers/terraform-provider-aws#8380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v1.49.0
```

### Affected Resource(s)

* `aws_db_instance`

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "master" {
  identifier         = "master"
  instance_class     = "db.m4.large"

  engine             = "postgres"
  engine_version     = "9.6.9"

  allocated_storage  = 20
  username           = "master"
  password           = "uselesspassword"

  db_subnet_group_name = "${aws_db_subnet_group.default.name}"
}

resource "aws_db_instance" "replica" {
  identifier         = "replica"
  instance_class     = "db.m4.large"

  engine             = "postgres"
  engine_version     = "9.6.9"

  replicate_source_db = "${aws_db_instance.master.identifier}"
  backup_retention_period = 5

  db_subnet_group_name = "${aws_db_subnet_group.default.name}"
}
...
```

### Debug Output

```
* aws_db_instance.replica: Error creating DB Instance: InvalidDBInstanceState: Automated backups are not enabled for this database instance. To enable automated backups, use ModifyDBInstance to set the backup retention period to a non-zero value.
        status code: 400, request id: ...
```

It will take me some time to sanitize the full debug output - do let me know if it's needed.

### Expected Behavior

Replica should have been created

### Actual Behavior

* `aws_db_instance.replica: Error creating DB Instance: InvalidDBInstanceState: Automated backups are not enabled for this database instance. To enable automated backups, use ModifyDBInstance to set the backup retention period to a non-zero value.`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

According to [documentation](https://www.terraform.io/docs/providers/aws/r/db_instance.html#backup_retention_period), `backup_retention_period` is to be `> 0` for replicas. It is, but the resource still fails to create.

**Comment by catherinetcai** [comment]
The AWS docs do specify that Postgres read replicas don't do automated backups, only manual snapshots.

Also looking at [AWS SDK Go](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceReadReplicaInput), it seems like you need to enable automated backups on the master instance, not the replica.

**Comment by smaslennikov** [comment]
@catherinetcai You're right, backups do need to be specified on the master. However, that didn't work until I recreated the master with the right setting: modification didn't fly.

This is the code that worked in the end:

```
resource "aws_db_instance" "master" {
  identifier         = "master"
  instance_class     = "db.m4.large"

  engine             = "postgres"
  engine_version     = "9.6.9"

  allocated_storage  = 20
  username           = "master"
  password           = "uselesspassword"
  skip_final_snapshot = true
  backup_retention_period = 5

  db_subnet_group_name = "${aws_db_subnet_group.default.name}"
}

resource "aws_db_instance" "replica" {
  identifier         = "replica"
  instance_class     = "db.m4.large"

  engine             = "postgres"
  engine_version     = "9.6.9"

  replicate_source_db = "${aws_db_instance.master.identifier}"
}
...
```
