### ISSUE TITLE
Support requester-managed Interface VPC Endpoints

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[AWS SDK v1.19.13](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.13), merged in https://github.com/terraform-providers/terraform-provider-aws/pull/8381, added support for _requester-managed Interface VPC Endpoints_:
> This release adds support for requester-managed Interface VPC Endpoints (powered by AWS PrivateLink). The feature prevents VPC endpoint owners from accidentally deleting or otherwise mismanaging the VPC endpoints of some AWS VPC endpoint services.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/2253

**Comment by ewbankkit** [comment]
This looks like the addition of 2 _Computed_ boolean attributes:
* `manages_vpc_endpoint` to the `aws_vpc_endpoint_service` data source and resource
* `requester_managed` to the `aws_vpc_endpoint` data source and resource

**Comment by bflad** [comment]
This has been merged as part of #8674 and will release with version 2.16.0 of the Terraform AWS Provider, likely tomorrow. 👍

**Comment by bflad** [comment]
This has been released in [version 2.16.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2160-june-20-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
