### ISSUE TITLE
tf apply failure when creating elasticache cluster with tags

### ISSUE THREAD

**Issue by zapman449** [terraform-providers/terraform-provider-aws#8389]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.2
AWS Provider version v1.60.0_x4

### Affected Resource(s)

aws_elasticache_replication_group

### Terraform Configuration Files

```hcl
locals {
  elasticache_clustered_tags = {
    "Name" = "cluster_redis"
    "Role" = "clustered redis (video)"
  }
}

resource "aws_elasticache_replication_group" "elasticache_clustered" {
  count = "${var.toggle}"

  replication_group_id          = "${var.apollo_realm}-cl"
  replication_group_description = "Clustered Redis"
  node_type                     = "cache.r4.large"
  engine                        = "redis"
  engine_version                = "4.0.10"
  parameter_group_name          = "${var.elasticache_clustered_parameter_group}"
  port                          = 6379
  automatic_failover_enabled    = true
  auto_minor_version_upgrade    = true

  cluster_mode {
    num_node_groups         = "1"
    replicas_per_node_group = "0"
  }

  security_group_ids = [
    <<SG_LIST_HERE>>
  ]

  lifecycle {
    ignore_changes = ["engine_version"]
  }

  subnet_group_name        = "${var.elasticache_common_subnet_group_name}"
  snapshot_retention_limit = 0
  maintenance_window       = "Sun:02:00-Sun:03:00"
  apply_immediately        = true

  tags = "${merge(var.standard_tags, local.elasticache_clustered_tags)}"
}
```

### Apply error message:

```
Error: Error applying plan:

1 error(s) occurred:

* module.apollo.aws_elasticache_replication_group.elasticache_clustered: 1 error(s) occurred:

* aws_elasticache_replication_group.elasticache_clustered: Error creating Elasticache Replication Group: InvalidParameterValue: Tagging not available right now. Please try your query without tags.
	status code: 400, request id: 71b5188f-62e4-11e9-99d7-e70a8465e38b
```

### Expected Behavior

Create the cluster with the tags, in one step.

### Actual Behavior

If the `tags` line is included, the error above occurs, and the apply fails.  If you comment out the `tags` line, and plan/apply, it works.  Then when you uncomment the tags and re-run plan/apply, it works.

### Steps to Reproduce

See Actual Behavior

### Important Factoids

There used to be an elasticache tagging bug associated with assume-role.  We are doing cross-account assume-role here, but the original issue is gone. ( #5021 )

### References

n/a

**Comment by zapman449** [comment]
We tested with provider v2.7 as well.  Same issue

**Comment by zapman449** [comment]
It non clustered works fine with tags as well.

**Comment by Jukie** [comment]
This is an aws error, not terraform but it appears to be from having special characters '(' or ')' in your tags. I can't find any clear documentation for elasticache but here's an excerpt from [ec2 docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html). I found the same description on other services too.

>Although EC2 allows for any character in its tags, other services may be more restrictive. Generally allowed characters are: letters, numbers, and spaces representable in UTF-8, and the following characters: + - = . _ : / @. These characters may not be allowed by more restrictive services.

**Comment by Jukie** [comment]
I was able to successfully apply a similar template without`()`.
```
locals {
  elasticache_clustered_tags = {
    "Name" = "cluster_redis"
    "Role" = "clustered redis"
  }
}
variable "standard_tags" {
  default = {
    "somekey" = "somevalue"
  }
}

resource "aws_elasticache_replication_group" "bar" {
	replication_group_id = "tf-test123456s"
	replication_group_description = "test description"
	node_type = "cache.t2.micro"
	number_cache_clusters = 1
	port = 6379
        subnet_group_name = "sg-group-1"
        tags = "${merge(var.standard_tags, local.elasticache_clustered_tags)}"
}
```

**Comment by zapman449** [comment]
Confirmed, and thank you.  That's frustrating, but it is what it is.

**Comment by bflad** [comment]
This issue appears it was resolved by updating the Terraform configuration with valid tag values. Since AWS does not document the valid values in the [Elasticache API Reference](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_Tag.html), we would be hesitant to introduce our own validation. Our best suggestion here would be to encourage the AWS service team to document the valid values (e.g. the feedback link in the bottom right corner of the previous link) or improve the API error messaging (e.g. support case). 👍
