### ISSUE TITLE
aws_vpc removing tags added by EKS 

### ISSUE THREAD

**Issue by jaksonwkr** [terraform-providers/terraform-provider-aws#8392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
provider.aws v2.7.0

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

```hcl
locals {
  azs = ["us-east-1c", "us-east-1f"]
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "subnets" {
  count             = 2
  cidr_block        = "${cidrsubnet(aws_vpc.vpc.cidr_block, 2, count.index)}"
  vpc_id            = "${aws_vpc.vpc.id}"
  availability_zone = "${element(local.azs, count.index)}"
}

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.vpc.id}"
}

resource "aws_route_table" "routetable1" {
  vpc_id = "${aws_vpc.vpc.id}"

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = "${aws_internet_gateway.igw.id}"
  }
}

resource "aws_route_table_association" "routetable_association" {
  count          = 2
  subnet_id      = "${aws_subnet.subnets.*.id[count.index]}"
  route_table_id = "${aws_route_table.routetable1.id}"
}

resource "aws_eks_cluster" "k8s" {
  name     = "k8s"
  role_arn = "arn:aws:iam::***:role/eks-role-test"

  vpc_config {
    subnet_ids = ["${aws_subnet.subnets.*.id}"]
  }
}

```

EKS role was previous created.

### Debug Output

https://gist.github.com/jaksonwkr/997e34946f13f49e53639137b443b596

### Expected Behavior

Ignore tags with key prefix kubernetes.io/cluster/*

### Actual Behavior

Remove tags prefix from VPC and subnets

```
➜  teste terraform apply
aws_vpc.vpc: Refreshing state... (ID: vpc-0dc7cf3f568940332)
aws_subnet.subnets[0]: Refreshing state... (ID: subnet-035141c728f9f6f81)
aws_subnet.subnets[1]: Refreshing state... (ID: subnet-00f7fbe5b44468126)
aws_internet_gateway.igw: Refreshing state... (ID: igw-01ddd6588f4d84b89)
aws_route_table.routetable1: Refreshing state... (ID: rtb-0c4e023044f267fec)
aws_eks_cluster.k8s: Refreshing state... (ID: k8s)
aws_route_table_association.routetable_association[0]: Refreshing state... (ID: rtbassoc-0c19585338f408763)
aws_route_table_association.routetable_association[1]: Refreshing state... (ID: rtbassoc-0e4dc5be142840ed6)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_subnet.subnets[0]
      tags.%:                         "1" => "0"
      tags.kubernetes.io/cluster/k8s: "shared" => ""

  ~ aws_subnet.subnets[1]
      tags.%:                         "1" => "0"
      tags.kubernetes.io/cluster/k8s: "shared" => ""

  ~ aws_vpc.vpc
      tags.%:                         "1" => "0"
      tags.kubernetes.io/cluster/k8s: "shared" => ""


Plan: 0 to add, 3 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:    
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by bflad** [comment]
Hi @jaksonwkr 👋 Thanks for the report and sorry for the trouble here.

The behavior with managing the Kubernetes tags in this fashion is to be expected. Terraform resources that manage AWS resource tags presume management of all tags except AWS-internal managed tags beginning with `aws:`.

For this situation, there are two Terraform configuration possibilities you can use to handle the planned difference within Terraform -- you can either define the tag configuration as outlined in the [EKS Getting Started Guide](https://learn.hashicorp.com/terraform/aws/eks-intro) or use the [`lifecycle` configuration block `ignore_changes` argument that is available to all Terraform resources](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to ignore the problematic difference. Examples below:

```hcl
# Configuring the tags to match the difference
resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"

  tags = "${
    map(
     "kubernetes.io/cluster/k8s", "shared",
    )
  }"
}

# Or: Ignore the tags differences
resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"

  lifecycle {
    ignore_changes = ["tags.%", "tags.kubernetes.io/cluster/k8s"]
  }
}
```

Hope this helps!

**Comment by jaksonwkr** [comment]
@bflad Thank you, I didn't know about this feature of the lifecycle.

**Comment by jaksonwkr** [comment]
> Hi @jaksonwkr  Thanks for the report and sorry for the trouble here.
> 
> The behavior with managing the Kubernetes tags in this fashion is to be expected. Terraform resources that manage AWS resource tags presume management of all tags except AWS-internal managed tags beginning with `aws:`.
> 
> For this situation, there are two Terraform configuration possibilities you can use to handle the planned difference within Terraform -- you can either define the tag configuration as outlined in the [EKS Getting Started Guide](https://learn.hashicorp.com/terraform/aws/eks-intro) or use the [`lifecycle` configuration block `ignore_changes` argument that is available to all Terraform resources](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to ignore the problematic difference. Examples below:
> 
> ```terraform
> # Configuring the tags to match the difference
> resource "aws_vpc" "vpc" {
>   cidr_block = "10.0.0.0/16"
> 
>   tags = "${
>     map(
>      "kubernetes.io/cluster/k8s", "shared",
>     )
>   }"
> }
> 
> # Or: Ignore the tags differences
> resource "aws_vpc" "vpc" {
>   cidr_block = "10.0.0.0/16"
> 
>   lifecycle {
>     ignore_changes = ["tags.%", "tags.kubernetes.io/cluster/k8s"]
>   }
> }
> ```
> 
> Hope this helps!

There's a limitation with this approach, as specified at [documentation](https://www.terraform.io/docs/configuration-0-11/resources.html#ignore_changes) it can not be a prefix + wildcard (*).

This doesn't solve the problem completely because I'm using a module that creates the EKS cluster, and the name of the cluster is dynamic depending on the environment (dev or prod), I can hard code all the possibilities to workaround but I think this is not pretty good. 

Maybe if ignore_changes supports regex it would be very good.

**Comment by bflad** [comment]
@jaksonwkr this upstream Terraform issue captures enhancements to `ignore_changes`: https://github.com/hashicorp/terraform/issues/5666
