### ISSUE TITLE
Amazon MSK tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of [AWS SDK v1.19.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.14), merged in https://github.com/terraform-providers/terraform-provider-aws/pull/8381, AWS MSK Kafka clusters support resource tagging.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6653
* https://github.com/terraform-providers/terraform-provider-aws/pull/8357

**Comment by bflad** [comment]
Support for tagging `aws_msk_cluster` resources was merged with the initial implementation of the resource, which is releasing in version 2.12.0 of the Terraform AWS Provider, likely tomorrow. 👍
