### ISSUE TITLE
Feature request: Update aws_lb_listener_rule to support new conditions

### ISSUE THREAD

**Issue by facundovictor** [terraform-providers/terraform-provider-aws#8441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The listener rules support new conditions, as explained from aws cli man:
```json
          [
            {
              "Field": "string",
              "Values": ["string", ...],
              "HostHeaderConfig": {
                "Values": ["string", ...]
              },
              "PathPatternConfig": {
                "Values": ["string", ...]
              },
              "HttpHeaderConfig": {
                "HttpHeaderName": "string",
                "Values": ["string", ...]
              },
              "QueryStringConfig": {
                "Values": [
                  {
                    "Key": "string",
                    "Value": "string"
                  }
                  ...
                ]
              },
              "HttpRequestMethodConfig": {
                "Values": ["string", ...]
              },
              "SourceIpConfig": {
                "Values": ["string", ...]
              }
            }
            ...
          ]
```

### New or Affected Resource(s)
aws_alb_listener_rule
aws_lb_listener_rule

### Potential Terraform Configuration

```hcl
resource "aws_lb_listener_rule" "myrule" {
  listener_arn = "${aws_lb_listener.mylistener.arn}"

  action {
    type = "redirect"

    redirect {
      port        = "443"
      protocol    = "HTTPS"
      status_code = "HTTP_301"
    }
  }

  # NOTE: Here I'm only adding conditions that are new!

  condition {
    field  = "http-header"
   
    # This would be optional
    values = ["my-header-value"] 

    # Optional: for when using http-header"
    http_header_name = "header-name"
  }

  condition {
    field  = "http-request-method"
   
    # This would be optional
    values = ["my-http-method"] 
  }

  condition {
    field  = "query-string"
   
    # This would be optional
    query_string_values = {
      key1 = "value1"
      key2 = "value2"
    }
  }

  condition {
    field  = "source-ip"

    # This would be optional
    values = ["10.0.0.1"] 
  }
}
```

### References
https://aws.amazon.com/blogs/aws/new-advanced-request-routing-for-aws-application-load-balancers/

**Comment by ewbankkit** [comment]
I think this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/8126.

**Comment by facundovictor** [comment]
Thanks @ewbankkit closing this one as duplicate of #8126

**Comment by kalyanreddy7833** [comment]
@facundovictor  : hi , i couldn't see any new condition for path-pattern which supports multiple values. can you help me with an example. Appreciate for your help.
