### ISSUE TITLE
r/aws_dynamodb_table: Add support for tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for tagging Amazon DynamoDB tables during creation added in [AWS SDK v1.19.18](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.18):

> This update allows you to tag Amazon DynamoDB tables when you create them. Tags are labels you can attach to AWS resources to make them easier to manage, search, and filter.

**Comment by ewbankkit** [comment]
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8440

**Comment by ewbankkit** [comment]
Announcement:
* https://aws.amazon.com/about-aws/whats-new/2019/04/now-you-can-tag-amazon-dynamodb-tables-when-you-create-them/

**Comment by bflad** [comment]
Support for tagging on creation (where available) has been implemented and will release with version 2.11.0 of the Terraform AWS Provider, likely middle of this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
