### ISSUE TITLE
Amazon SNS topic tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of [AWS SDK v1.19.19](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.19), AWS SNS topics support resource tagging:

> With this release AWS SNS adds tagging support for Topics.

**Comment by ewbankkit** [comment]
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8456

**Comment by ewbankkit** [comment]
API docs:
* https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html

**Comment by bflad** [comment]
Support for the new `tags` argument on the `aws_sns_topic` resource has been merged and will release with version 2.11.0 of the Terraform AWS Provider, likely later this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
