### ISSUE TITLE
Add Blacklisting to aws_availability_zones Data Source

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#8462]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `aws_availability_zones` data source is great for creating reusable Terraform configurations across AWS Regions. There are a few use cases where it might make sense to purposefully blacklist certain Availability Zones by name or zone ID.

#### Use Case 1: New Availability Zone Launches

When AWS adds a new Availability Zone, there is an increasing possibility that all services and functionality might not be available from day 1. Providing a blacklist is a quick way to prevent initial provisioning issues until all functionality can be verified.

#### Use Case 2: Known Missing Availability Zone Features

While all Availability Zones across a Region are generally similar, there have been observed cases where this is not true. Many AWS service APIs do not have a query for whether specific functionality exists per Availability Zone. e.g.

* Missing EC2 Instance types
* No EC2 Transit Gateway support

#### Use Case 3: Colocation of Services

Infrastructures may be using Availability Zone IDs to colocate networking for speed or reduction in inter-AZ data transfer costs.

#### Use Case 4: Purchased Availability Zone Reserved Capacity

Certain AWS services allow purchasing reserved capacity at a discounted price. Some of these reservations are based on Availability Zone.

### Affected Data Source

* `aws_availability_zones`

### Potential Terraform Configuration

```hcl
data "aws_availability_zones" "by_name" {
  blacklisted_names = ["us-west-2d"]
}

data "aws_availability_zones" "by_zone_id" {
  blacklisted_zone_ids = ["usw2-az4"]
}
```

**Comment by nywilken** [comment]
The enhancement to the `aws_availability_zones` data source has been merged and will be released with version 2.9.0 of the Terraform AWS provider.
