### ISSUE TITLE
Terraform v11 upgrade forces new resource for Oracle RDS when re-running terraform without new changes

### ISSUE THREAD

**Issue by jameelgit** [terraform-providers/terraform-provider-aws#8481]
Upgraded Terraform version from 10 to 11 when running Oracle RDS plan terraform forces new resource each time when there is no changes.
-/+ module.xxxxx (new resource required)
      id:                                "oracle-rds" => <computed> (forces new resource)

**Comment by nywilken** [comment]
Hi @jameelgit sorry to hear about the unexpected behaviour here. In order for us to best help with this issue could you please provide a redacted configuration to reproduce the issue along with the version of the AWS provider being used. Executing the command `terraform version` in the directory were you you are running your `terraform apply` from should print all the relevant information to the console. 

If you could provide the output of `terraform plan`, stripped of any sensitive information,  that would help give insight into what changes are being reported.

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the requested information if you would like to continue with triage for this issue.
