### ISSUE TITLE
AWS Greengrass Groups and Cores Support

### ISSUE THREAD

**Issue by Ycallaer** [terraform-providers/terraform-provider-aws#8498]
Hi,
I have been going through the documentation but can't seem to find any reference on how to use terraform in combination with AWS greengrass.
I am mainly looking in the creation of Greengrass Groups and cores.
Is this currently supported ?

**Comment by bflad** [comment]
Hi @Ycallaer 👋 The Terraform AWS Provider does not currently support [AWS IoT Greengrass](https://aws.amazon.com/greengrass/). I have updated this issue to reflect the feature request. 👍

**Comment by kfleischmann** [comment]
This feature would be also for a great value. +1  for Implementation.

**Comment by kenned-dk** [comment]
Hi
Hope you guys can support AWS greengrass soon, it would be nice to deploy an end to end IoT enviroment with terraform👍
Thanks

**Comment by bflad** [comment]
Hi folks 👋 

There has been some work done to expand out this feature request per resource to match our template, so to consolidate efforts and discussions we are going to close out this issue and would suggest following and upvoting these (👍 reaction on the issue descriptions) going forward if you are interested in this support:
* [New Resource: `aws_greengrass_core_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10865)
* [New Resource: `aws_greengrass_connector_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10866)
* [New Resource: `aws_greengrass_device_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10867)
* [New Resource: `aws_greengrass_function_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10870)
* [New Resource: `aws_greengrass_group`](https://github.com/terraform-providers/terraform-provider-aws/issues/10873)
* [New Resource: `aws_greengrass_logger_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10869)
* [New Resource: `aws_greengrass_resource_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10872)
* [New Resource: `aws_greengrass_subscription_definition`](https://github.com/terraform-providers/terraform-provider-aws/issues/10871)
