### ISSUE TITLE
LambdaFunctionRegexp does not support us-gov-west-1

### ISSUE THREAD

**Issue by aboutte** [terraform-providers/terraform-provider-aws#851]
### Terraform Version
0.9.8

### Affected Resource(s)
- lambda

### Expected Behavior
Lamabda created successfully in us-gov-west-1

### Actual Behavior
```
aws_lambda_permission.subscribe_cloudwatch_log_groups_to_lambda_per: Invalid ARN or otherwise unable to get qualifier from ARN ("arn:aws-us-gov:lambda:us-gov-west-1:367654045940:function:cloudwatch_logs_to_consolidated_s3_bucket")
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running in AWS us-gov-west-1

### References
The regex [here](https://github.com/terraform-providers/terraform-provider-aws/blob/b8d4e1570fc43a2acee6b6e47f63c9db6b067fa2/aws/resource_aws_lambda_permission.go#L18) supports us-west-2, us-east-1, etc but does not support us-gov-west-1.

sample us-east-1 arn for lambda:

```
arn:aws:lambda:us-east-1:036975226382:function:subscribe_cloudwatch_log_groups_to_lambda
```

sample us-gov-west-1 arn for lambda:

```
arn:aws-us-gov:lambda:us-gov-west-1:367654045940:function:cloudwatch_logs_to_consolidated_s3_bucket
```

**Comment by Ninir** [comment]
Related to https://github.com/terraform-providers/terraform-provider-aws/pull/16

**Comment by radeksimko** [comment]
@Ninir sorry for jumping the gun on this one - feel free to re-review the linked PR 😅 

Anyway, it's now merged, so I'm closing this issue. 🎉

**Comment by Ninir** [comment]
@radeksimko No worries :) It seemed good to me, needed to run the tests locally and see whether there were oversights or no. Still, thanks! :)
