### ISSUE TITLE
How to create glue_job of type=sparc ?

### ISSUE THREAD

**Issue by itdataguy** [terraform-providers/terraform-provider-aws#8526]
It looks like glue_job resource does not yet support setting type=sparc?  Is this possible through default_arguments?  

As per: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html

I tried setting   

> default_arguments = {
>     "--enable-glue-datacatalog" = "true"
>   }

looking for some magic here or an update to this provider.

**Comment by rsgoshtasbi** [comment]
Assuming you mean have terraform updates to have possible a `type` field for `aws_glue_job` to either specify Spark or Python shell? Because I'm running into this problem right now.

With etl-language set as "spark" then python shell by default should not be set which is causing issues in the glue console:
![Glue Console Screen Shot](https://user-images.githubusercontent.com/45042692/57315524-9cdc2300-70a8-11e9-92f1-8880f88e6346.png)

**Comment by rsgoshtasbi** [comment]
@itdataguy I found the solution. It was very minor detail but what you need to do is set the following in the command json:
```
command {
   name = "glueetl"
   script_location = "${var.script_location}"
}
```

Name has to be either glueetl or pythonshell. If its not one of those, by default it sets it to pythonshell

**Comment by itdataguy** [comment]
@rsgoshtasbi Thank you for this.  I also just stumbled on this after resorting to terraform induces cloud formation.  Thank you for sharing the secret sauce :) 

In case terraform module is not up to the task, you can save this workaround.

> resource "aws_cloudformation_stack" "network" {
  name = "${local.name}-glue-job"

  template_body = <<STACK
{
  "Resources" : {
    "MyJob": {
      "Type": "AWS::Glue::Job",
      "Properties": {
        "Command": {
          "Name": "glueetl",
          "ScriptLocation": "s3://${local.bucket_name}/jobs/${var.job}"
        },
        "ExecutionProperty": {
         "MaxConcurrentRuns": 2
        },
        "MaxRetries": 0,
        "Name": "${local.name}",
        "Role": "${var.role}"
      }
    }
  }
}
STACK
}

**Comment by rsgoshtasbi** [comment]
Awesome, thanks @itdataguy. Glad we figured out these solutions. Let's go ahead and close out this issue 🥇
