### ISSUE TITLE
Unable to use imported keypair with aws_launch_configuration

### ISSUE THREAD

**Issue by mrjfox** [terraform-providers/terraform-provider-aws#8529]
Hi 

It appears that i am unable to use aws_launch_configuration (aka ALC) with an imported aws keypair and i have no issue importing the key only using it with ALC. 

**1) Successful import**

```
terraform import aws_key_pair.imported_key imported_key
aws_key_pair.imported_key: Importing from ID "imported_key"...
aws_key_pair.imported_key: Import complete!
  Imported aws_key_pair (ID: imported_key)
aws_key_pair.imported_key: Refreshing state... (ID: imported_key)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**2) It then fails on terraform plan**
```
terraform plan

Error: aws_key_pair.imported_key: "public_key": required field is not set
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws 2.8.0
* terraform 0.11.13

### Terraform Configuration Files

Have excluded the rest of the terraform manifest, only included the parts used.

```hcl
terraform {
  backend "local" {
      path = "./terraform.tfstate"
    }
}

resource "aws_key_pair" "imported_key" {
  key_name   = "imported_key"
}

resource "aws_launch_configuration" "master-ap-southeast-2c-masters-example-com" {
  name_prefix                 = "master-ap-southeast-2c.masters.example-com-"
  image_id                    = "ami-04481c741a0311bbb"
  instance_type               = "t2.medium"
  key_name                    = "${aws_key_pair.imported_key.id}"
  iam_instance_profile        = "${aws_iam_instance_profile.masters-example-com.id}"
  security_groups             = ["${aws_security_group.masters-example-com.id}"]
  associate_public_ip_address = true
  user_data                   = "${file("${path.module}/data/aws_launch_configuration_master-ap-southeast-2c.masters.example-com_user_data")}"

  root_block_device = {
    volume_type           = "gp2"
    volume_size           = 64
    delete_on_termination = true
  }

  lifecycle = {
    create_before_destroy = true
  }

  enable_monitoring = false
}
```

### Expected Behavior

I expect to be able to use the import keypair

When importing, terraform asks to define the keypair meaning:
```
resource "aws_key_pair" "imported_key" {
  key_name   = "jareds-eks-test"
}
```

### Actual Behavior

I complaints due to the lack of public key.

### Steps to Reproduce

1. `terraform init`
2. `terraform import #See above
3. `terraform plan`

### References

* #0000

**Comment by eramirez51** [comment]
+1

**Comment by bflad** [comment]
Hi folks 👋 Sorry for this frustrating issue. We are tracking this problem in the earlier #1092, which you can follow for updates. As a workaround for imported key pairs you can setup your configuration similar to the below:

```hcl
resource "aws_key_pair" "example" {
  key_name   = "example"
  public_key = ""

  lifecycle {
    ignore_changes = ["public_key"]
  }
}
```
