### ISSUE TITLE
Can't use `tags` attribute data sources

### ISSUE THREAD

**Issue by artburkart** [terraform-providers/terraform-provider-aws#853]
### Terraform Version
```
$ terraform -v
Terraform v0.9.8
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance
- aws_ebs_volume
- possibly others? didn't check

I guess I should mention it might be a problem across providers depending on whether other providers use similar tag implementations.

### Terraform Configuration Files
I've made a gist with a README here: https://gist.github.com/artburkart/5916ea45390bf2050e1f97f15c9a7dcd

I'll also paste my configs here:

```
provider "aws" {
  region = "us-east-1"
}

data "aws_instance" "dummy" {
  instance_id = "i-3c6e8abc"
}

variable "use_null_resource" {
  default = 0
}

resource "null_resource" "null" {
  triggers {
    Name = "foo"
  }
}

resource "aws_instance" "instance" {
  ami                    = "${data.aws_instance.dummy.ami}"
  instance_type          = "${data.aws_instance.dummy.instance_type}"
  subnet_id              = "${data.aws_instance.dummy.subnet_id}"
  vpc_security_group_ids = ["${data.aws_instance.dummy.vpc_security_group_ids}"]
  # tags                   = "${var.use_null_resource == 0 ? data.aws_instance.dummy.tags : null_resource.null.triggers}"
  # tags                   = "${data.aws_instance.dummy.tags}"
  tags                   = "${null_resource.null.triggers}"
}

data "aws_ebs_volume" "dummy" {
  most_recent = true
}

resource "aws_ebs_volume" "ebs_vol" {
  availability_zone = "us-east-1"
  size              = 40
  # tags              = "${var.use_null_resource == 0 ? data.aws_ebs_volume.dummy.tags : null_resource.null.triggers}"
  # tags              = "${data.aws_ebs_volume.dummy.tags}"
  tags              = "${null_resource.null.triggers}"
}
```

### Debug Output
I'll provide some upon request, but I think the snippet I provided should be sufficient for reproduction and the output isn't too helpful, since there aren't any API issues here.

### Expected Behavior
I should be able to write this:

```
  tags = "${data.aws_instance.dummy.tags}"
```

### Actual Behavior
Because the tags on the data source are interpreted as a list of maps, they're not compatible with the `tags` attribute as defined.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Nothing atypical about setup. It's not an AWS account-related conundrum. One thing worth noting is that no matter how I try accessing the values of the tags in the `data.aws_instance.dummy.tags` field, I get the length of the list back.

For example:

```
"${data.aws_instance.dummy.tags.*} => "5"
"${data.aws_instance.dummy.tags.0} => "5"
"${data.aws_instance.dummy.tags.0.Name} => "5"
```

I think this has something to do with terraform not unpacking the value correctly when creating the data source, so it ends up not being compatible with the `aws_instance` resource because terraform doesn't play nicely with lists of maps.

I don't know `go` very well, but I think this problem might have something to do with terraform converting a set of hashes to a list of hashes in this file: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_common_schema.go#L21-L33

### References
I was told to open this issue here: https://github.com/hashicorp/terraform/issues/2042#issuecomment-307269934

**Comment by Ninir** [comment]
Hey @artburkart 

I think this is something we can do by updating the code & adding a schema migration. Will check how we can do that soon :)
