### ISSUE TITLE
Blocks of type "route" are not expected here

### ISSUE THREAD

**Issue by sgript** [terraform-providers/terraform-provider-aws#8542]
Hi there,

Recently we upgraded from 0.11 to 0.12 Beta 1. A member of my team has the version:
```Terraform v0.12.0-beta1
+ provider.aws v1.60.0-dev20190216h00-dev
```

And when he runs his execution plan, all seems to work. However, when I run the same, I get the error:
```
Error: Unsupported block type

  on ../../modules/aws/route_table/main.tf line 4, in resource "aws_route_table" "route_table":
   4:   route {

Blocks of type "route" are not expected here. Did you mean to define argument
"route"? If so, use the equals sign to assign it a value.
```
And I am running the versions:
```
Terraform v0.12.0-beta1
+ provider.aws v2.9.0
```

However, I have tried to pin my provider block to use the version we have had success with but it's not being found (perhaps I set it incorrectly?). I've also tried to pin it to 1.60.0  (non dev), but it then tells me:
```
Provider version 2.7.0 is the earliest compatible version. Select it with
the following version constraint:

	version = "~> 2.7"
```

In relation to the actual error we're seeing (see above - "route" not being expected), here's the problematic code:
```
resource "aws_route_table" "route_table" {
  vpc_id = "${var.vpc_id}"

  route {
    cidr_block = "${var.cidr_block}"
    gateway_id = "${var.gateway_id}"
  }

  tags = {
    Name = "${var.environment}-${uuid()}"
  }
}
```

This is called twice:

```
module "route-table" {
  source ="../../aws/route_table"
  environment = "${var.environment}"

  vpc_id = "${module.vpc.id}"
  cidr_block = "0.0.0.0/0"
  gateway_id = "${module.internet_gateway.id}"
}

module "route-table-nat" {
  source ="../../aws/route_table"
  environment = "${var.environment}"

  vpc_id = "${module.vpc.id}"
  cidr_block = "0.0.0.0/0"
  gateway_id = "${module.nat_gateway.id}"
}
```

I don't see the issue here, could someone shed some light into what this might be?

Thanks.

**Comment by bflad** [comment]
Hi @sgript 👋 Sorry you are running into trouble here. 

There have been some significant changes in this area for both Terraform core between v0.12.0-beta1 -> v0.12.0-beta2 and the Terraform v0.12 compatible Terraform AWS Provider between the beta1 development snapshots and v2.7.0+. Instructions on installing the second beta of Terraform v0.12 can be found on the HashiCorp blog: https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta-2 Once on the second beta, you can install the Terraform AWS Provider "normally" via `terraform init`. The `aws_route_table` resource `route` syntax handling should work as expected once both Terraform and the provider are updated.

If you still run into issues with Terraform v0.12.0-beta2 and v2.7.0+ of the Terraform AWS Provider, please do reach out and we can investigate further.
