### ISSUE TITLE
aws_codebuild_project can't take an namespace_type for NO_ARTIFACTS

### ISSUE THREAD

**Issue by tedder** [terraform-providers/terraform-provider-aws#8554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
v0.11.13
+ provider.aws v2.9.0
```

### Affected Resource(s)
* aws_codebuild_project

### Terraform Configuration Files
Here's a minimal standalone test:
```
data "aws_iam_policy_document" "assume_codebuild" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["codebuild.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "builder" {
  name_prefix        = "ted_cb_bldr_"
  assume_role_policy = "${data.aws_iam_policy_document.assume_codebuild.json}"
}

resource "aws_codebuild_project" "build" {
  name        = "test"
  description = "ted test"

  source {
    type            = "GITHUB"
    location        = "https://github.com/terraform-providers/terraform-provider-aws.git"
    git_clone_depth = 1
  }

  artifacts {
    type           = "NO_ARTIFACTS"
    namespace_type = ""             # experiment with this, eg "" or NONE
    location       = ""
    path           = ""
  }

  environment {
    compute_type = "BUILD_GENERAL1_LARGE"
    image        = "python:3-stretch"
    type         = "LINUX_CONTAINER"
  }

  service_role = "${aws_iam_role.builder.arn}"
}
```

### Debug Output
N/A; I don't think it is helpful.

### Panic Output
N/A; I don't think it is helpful.

### Expected Behavior
With non-S3 artifact types, including NO_ARTIFACTS, I should be able to specify some value for namespace_type without failing.

### Actual Behavior
Sample failures for "empty string" and "NONE". Note the case of "NONE" doesn't fail until runtime (e.g., `terraform apply`)
```
## empty string, eg ""
$ terraform plan
Error: module.test_project.aws_codebuild_project.build: expected artifacts.0.namespace_type to be one of [NONE BUILD_ID], got 

## NONE
$ terraform apply

* aws_codebuild_project.build: Error creating CodeBuild project: InvalidInputException: Invalid artifacts: artifact type NO_ARTIFACTS should have null namespace
```

### Steps to Reproduce

1. `terraform plan` and/or `terraform apply`

### Important Factoids
The ["namespace_type" validation](https://github.com/terraform-providers/terraform-provider-aws/blob/49f665406c02e2b47e812db458ba8ec447e05922/aws/resource_aws_codebuild_project.go#L54) only allows NONE or BUILD_ID here, and those are only valid for S3 projects.

The ["expand" method](https://github.com/terraform-providers/terraform-provider-aws/blob/49f665406c02e2b47e812db458ba8ec447e05922/aws/resource_aws_codebuild_project.go#L589) will probably handle the empty-string version of this if validation was loosened, but an even better fix would be to fill it only in the 'S3' case, [similar to how EncryptionDisabled is set a few lines up](https://github.com/terraform-providers/terraform-provider-aws/blob/49f665406c02e2b47e812db458ba8ec447e05922/aws/resource_aws_codebuild_project.go#L571).

So, suggested fixes:
1. Update validation to take an empty string.
2. Only pass the namespace for artifact_type=S3.

**Comment by bflad** [comment]
Hi @tedder 👋 This issue is resolved in Terraform 0.12, which supports new functionality in the configuration language aimed at solving problems like these. The new [`null` value](https://www.terraform.io/docs/configuration/expressions.html#null) can be used to omit arguments as if they were not defined in the configuration at all. For doing similar with configuration blocks, please see the new [`dynamic` block syntax](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks).

For example, given this configuration:

```hcl
terraform {
  required_providers {
    aws = "2.21.1"
  }
  required_version = "0.12.5"
}

provider "aws" {
  region = "us-east-2"
}

resource "aws_iam_role" "test" {
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow",
      Principal = {
        Service = "codebuild.amazonaws.com"
      }
    }]
  })
}

resource "aws_iam_role_policy" "test" {
  role = aws_iam_role.test.name

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents",
        ]
        Effect   = "Allow",
        Resource = ["*"]
      },
      {
        Action = [
          "ec2:CreateNetworkInterface",
          "ec2:CreateNetworkInterfacePermission",
          "ec2:DescribeDhcpOptions",
          "ec2:DescribeNetworkInterfaces",
          "ec2:DeleteNetworkInterface",
          "ec2:DescribeSubnets",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeVpcs",
        ]
        Effect   = "Allow"
        Resource = "*"
      },
      {
        Action   = ["s3:*"],
        Effect   = "Allow",
        Resource = "*"
      },
    ]
  })
}

resource "aws_codebuild_project" "test" {
  name         = "test"
  service_role = "${aws_iam_role.test.arn}"

  artifacts {
    namespace_type = null
    type           = "NO_ARTIFACTS"
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image        = "2"
    type         = "LINUX_CONTAINER"
  }

  source {
    location = "https://github.com/hashicorp/packer.git"
    type     = "GITHUB"
  }
}
```

Successfully applies. Enjoy! 🚀
