### ISSUE TITLE
Caching on API Gateway does not work for path parameters

### ISSUE THREAD

**Issue by betabandido** [terraform-providers/terraform-provider-aws#856]
When enabling caching on an API that uses path parameters (or query strings) it is necessary to create a cache key for the parameter (or query string). But, Terraform currently does not seem to allow to set cache keys. If caching is enabled for a given method (something currently possible to do with Terraform), the same cached value will be returned no matter whether the path parameter value is the same or not.

In `resourceAwsApiGatewayIntegrationCreate` method the method integration is created but both `CacheKeyParameters` and `CacheNamespace` are set to `nil`:

```
	_, err := conn.PutIntegration(&apigateway.PutIntegrationInput{
		HttpMethod: aws.String(d.Get("http_method").(string)),
		ResourceId: aws.String(d.Get("resource_id").(string)),
		RestApiId:  aws.String(d.Get("rest_api_id").(string)),
		Type:       aws.String(d.Get("type").(string)),
		IntegrationHttpMethod: integrationHttpMethod,
		Uri:                 uri,
		RequestParameters:   aws.StringMap(parameters),
		RequestTemplates:    aws.StringMap(templates),
		Credentials:         credentials,
		CacheNamespace:      nil,
		CacheKeyParameters:  nil,
		PassthroughBehavior: passthroughBehavior,
		ContentHandling:     contentHandling,
	})
```
(see code at https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_api_gateway_integration.go#L153)

Additionally, when trying to enable caching for a path parameter in the AWS console (after an API has been created by Terraform) the operation fails. This might be related to using `nil` in the `PutIntegration` call.

We are working on a pull request to provide a working solution. Any help would be appreciated.

### Terraform Version

Terraform v0.9.8

The issue seems to be present in the master branch too.

### Affected Resource(s)
aws_api_gateway_integration

**Comment by betabandido** [comment]
Enabling caching does **not** properly work even for very simple use cases (such as when having path parameters or query strings). So, IMHO I would not say this is just an "enhancement."

We have created a pull request to fix this issue. Hopefully it can make it into the next release :)

**Comment by Ninir** [comment]
Hi @betabandido 

As your PR was merged, and mine about [the documentation](https://github.com/terraform-providers/terraform-provider-aws/pull/1602/files) will be too soon I hope, could you tell me if you are still having this issue or is it all resolved?

Thanks!

**Comment by betabandido** [comment]
@Ninir 

Oh, the issue was already fixed with the proposed PR. I suppose we just forgot to close the issue. I will do it now.

Thanks for the documentation! It was on my backlog, but I couldn't find the time to do it yet.

**Comment by Ninir** [comment]
@betabandido No worries, thanks for your quick response :)

(and cheers for the work made! 😄 )

**Comment by bubunyo** [comment]
I don't know if this the right place to say this, but anytime include the cache keys in the integrations resource, the enable cache check box is not enabled by default. how do I enable that checkbox with terraform?
