### ISSUE TITLE
terraform apply updates/removes one of the security rule on SG

### ISSUE THREAD

**Issue by dragonknight88** [terraform-providers/terraform-provider-aws#8572]
I deployed EKS cluster with terraform following from [Intro to EKS](https://learn.hashicorp.com/terraform/aws/eks-intro#overview). 

**Steps:**
1. Provision EKS cluster with tf
2. Update ASG
3. terraform apply

**Env:**
terraform: 0.11.13
OS: mac
Provider: aws
Service: eks

**Expected behavior:**
Terraform should identify only ASG for updates/change

**Current behavior:**
Terraform updates worker node security rule by removing the Master to Worker node 443 ingress rule

Right now I am experiencing behavior where TF updates an SG by removing below rule.

> resource "aws_security_group_rule" "eks-cluster-ingress-node-https" {
        description = "Allow pods to communicate with the cluster API Server"
        from_port = 443
        to_port = 443
        protocol = "tcp"
        security_group_id = "${aws_security_group.eks_master_cluster_sg.id}"
        source_security_group_id = "${aws_security_group.eks_worker_node_sg.id}"
        type = "ingress"
}

I encountered above security rule getting updated but quite worried if it's not the same every time. It brings down the whole cluster, marking nodes out-of-service on LB

**Comment by bflad** [comment]
Hi @dragonknight88 👋 In order to triage this issue, we would need to see the full Terraform configuration and output from `terraform plan`. Can you please provide this information? Thanks.

**Comment by bflad** [comment]
Closing due to lack of response.
