### ISSUE TITLE
[Documentation] AWS route_53_zone association documentation should reflect that manual steps are required when associating a zone with a VPC in a different account.

### ISSUE THREAD

**Issue by hdpoe** [terraform-providers/terraform-provider-aws#8593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform version
Terraform v0.11.13
+ provider.aws v2.9.0
```
### Affected Resource(s)

* aws_route53_zone_association

### Terraform Configuration Files
N/A
### Debug Output
N/A

### Panic Output

N/A
### Expected Behavior

The aws_route53_zone_association resource documentation would clearly indicate that creating an association between a zone and vpc that are in different accounts requires additional out of band steps.

### Actual Behavior

Currently the documentation on the aws_route53_zone_association does not make clear that you can't use this resource without first performing a `CreateVpcAssociationAuthorization` for cross account VPC associations. which leads to confusion for users when they attempt to perform a vpc zone association between differing accounts.

### Steps to Reproduce

N/A

### References
* [AWS documentation on to perform using the aws cli](https://aws.amazon.com/premiumsupport/knowledge-center/private-hosted-zone-different-account/)
* [Pull request for resource that will perform the authorization for cross account access](https://github.com/terraform-providers/terraform-provider-aws/pull/2005)

**Comment by tdmalone** [comment]
Related: #384 and #585

**Comment by chaspy** [comment]
Seems to have already addressed ☺️ 
https://www.terraform.io/docs/providers/aws/r/route53_zone_association.html

**Comment by dbektas** [comment]
It seems that what is addressed is only the association, not the Authorization for the association.

**Comment by bflad** [comment]
Hi folks 👋  Releasing with version 3.1.0 of the Terraform AWS Provider (later today), manual steps will no longer be necessary to setup cross-account Route 53 VPC Associations. 👍  See the `aws_route53_vpc_association_authorization` resource documentation when the release goes out.
