### ISSUE TITLE
"profile" option in aws provider config block does not work

### ISSUE THREAD

**Issue by max-rocket-internet** [terraform-providers/terraform-provider-aws#8603]
The `profile` option for the AWS provider does not work.

### Terraform Version

```
$ terraform version
Terraform v0.11.13
+ provider.aws v2.8.0
```

### Steps to Reproduce

AWS terraform provider block defined like this:

```hcl
provider "aws" {
  version = ">= 2.6.0"
  region  = "eu-west-1"

  profile = "test"

  allowed_account_ids = [
    "6666666666666",
  ]
}
```

And related auth files like this...

`~/.aws/credentials`:

```
[test]
aws_access_key_id=<my access key>
aws_secret_access_key=<my secret key>
```

`~/.aws/config`:

```
[profile test]
region=eu-west-1
```

Run `terraform init`

### Expected Behavior

`terraform init` would use the valid profile correctly

### Actual Behavior

But `terraform init` fails:

```
$ TF_LOG=DEBUG terraform init
2019/05/10 16:01:35 [INFO] Terraform version: 0.11.13
2019/05/10 16:01:35 [INFO] Go runtime version: go1.12
2019/05/10 16:01:35 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.13/bin/terraform", "init"}
2019/05/10 16:01:35 [DEBUG] Attempting to open CLI config file: /Users/max.williams/.terraformrc
2019/05/10 16:01:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/05/10 16:01:35 [INFO] CLI command args: []string{"init"}
2019/05/10 16:01:35 [DEBUG] command: loading backend config file: /xxx/xxxx/xxxx
Initializing modules...
- module.aurora1
- module.aurora2
- module.bastion_vpc1
- module.datadog_logs
- module.eu01_stg
2019/05/10 16:01:35 [DEBUG] found local version "3.0.0" for module terraform-aws-modules/eks/aws
2019/05/10 16:01:35 [DEBUG] found local version "4.0.0" for module terraform-aws-modules/eks/aws
2019/05/10 16:01:35 [DEBUG] found local version "4.0.1" for module terraform-aws-modules/eks/aws
2019/05/10 16:01:35 [DEBUG] found local version "4.0.2" for module terraform-aws-modules/eks/aws
2019/05/10 16:01:35 [DEBUG] matched "terraform-aws-modules/eks/aws" version 4.0.2 for 4.0.2
- module.icash_domains_01
- module.ses
- module.vpc1

Initializing the backend...
2019/05/10 16:01:35 [INFO] Building AWS region structure
2019/05/10 16:01:35 [INFO] Building AWS auth structure
2019/05/10 16:01:35 [INFO] Setting AWS metadata API timeout to 100ms
2019/05/10 16:01:36 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
2019/05/10 16:01:41 [DEBUG] plugin: waiting for all plugin processes to complete...

Error configuring the backend "s3": No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider

Please update the configuration in your Terraform files to fix this error.
If you'd like to update the configuration interactively without storing
the values in your configuration, run "terraform init".
```

### Important Factoids

Running an AWS CLI command and specifying the profile works. For example `aws --profile=test s3 ls`.

I cat't set the `AWS_PROFILE` environment variable so this is not a work around.

### References

There seems to be a lot of related issues that are similar but not identical:

- https://github.com/terraform-providers/terraform-provider-aws/issues/7750
- https://github.com/terraform-providers/terraform-provider-aws/issues/4245
- https://github.com/terraform-providers/terraform-provider-aws/issues/8052
- https://github.com/terraform-providers/terraform-provider-aws/issues/5251

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kipkoan** [comment]
The provider block does not get used for the backend configuration. You have to specify the profile again there: https://www.terraform.io/docs/backends/types/s3.html#profile

**Comment by max-rocket-internet** [comment]
Ah, you mean in the S3 backend configuration. That still doesn't work for me but on further investigation we are assuming another role in profile, there's no actual credentials there. So I think this issue is already covered in https://github.com/terraform-providers/terraform-provider-aws/issues/5251 and https://github.com/terraform-providers/terraform-provider-aws/issues/8052

But if we use `aws_access_key_id` and `aws_secret_access_key` there then it does work. Thanks for the tip @kipkoan.
