### ISSUE TITLE
aws_route53_record timeout

### ISSUE THREAD

**Issue by amgohan** [terraform-providers/terraform-provider-aws#8607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
* Terraform : 0.11.13
* aws_provider : 1.60

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "app-r53" {
  zone_id = "${module.zone_private.zone_id}"
  name    = "app${var.feature_name_suffix}.${var.environment_tag}.${var.product_name}.${var.dns_zone_private}"
  type    = "A"

  alias {
    name                   = "${lower(aws_lb.app-lb.dns_name)}"
    zone_id                = "${aws_lb.app-lb.zone_id}"
    evaluate_target_health = true
  }
}

output "app-dns" {
  value = "${aws_route53_record.app-r53.name}"
}
```

### Expected Behavior

We never get route53 timeout error when we were using terraform 0.11.11
We expect at least to be able to configure the timeout

### Actual Behavior

```hcl
aws_route53_record.app-r53: Still destroying... (ID: xxx, 29m40s elapsed)
aws_route53_record.app-r53: Still destroying... (ID: xxx, 29m50s elapsed)
aws_route53_record.app-r53: Still destroying... (ID: xxx, 30m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* aws_route53_record.app-r53 (destroy): 1 error(s) occurred:

* aws_route53_record.app-r53: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 30m0s)
```

### Steps to Reproduce

1. `terraform destroy`

**Comment by bflad** [comment]
I believe this issue was related to a Route 53 API outage, in which changes were not being published. There's not much more the Terraform resources can do in these cases, as it appears to properly return an error saying that the change is still pending within Route 53 after the timeout.
