### ISSUE TITLE
r/aws_kinesis_analytics_application: Add support for resource tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

[`aws_kinesis_analytics_application`](https://www.terraform.io/docs/providers/aws/r/kinesis_analytics_application.html) resources now support [resource tags](https://docs.aws.amazon.com/kinesisanalytics/latest/java/how-tagging.html):

> Kinesis Data Analytics APIs now support tagging on applications.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8574

**Comment by bflad** [comment]
Support for the `tags` argument on the `aws_kinesis_analytics_application` resource has been merged and will release with version 2.11.0 of the Terraform AWS Provider, likely tomorrow. 👍

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
