### ISSUE TITLE
AWS CodePipeline tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8650]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of  [AWS SDK v1.19.31](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.31) AWS CodePipeline resources can be tagged:
> This feature includes new APIs to add, edit, remove and view tags for pipeline, custom action type and webhook resources. You can also add tags while creating these resources.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8649

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_codepipeline`](https://www.terraform.io/docs/providers/aws/r/codepipeline.html)
* [`aws_codepipeline_webhook`](https://www.terraform.io/docs/providers/aws/r/codepipeline_webhook.html)

**Comment by bflad** [comment]
Support for managing tags with the `aws_codepipeline` and `aws_codepipeline_webhook` resources has been merged and will release with version 2.16.0 of the Terraform AWS Provider, likely later this week. 👍 

Since #8123 is pending review, please ask in that pull request for the tagging functionality or create a new top level issue once the new resource has been merged. Thanks.

**Comment by bflad** [comment]
This has been released in [version 2.16.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2160-june-20-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
