### ISSUE TITLE
aws_ec2_transit_gateway_vpc_attachment failing when transit_gateway_id is not known at apply time

### ISSUE THREAD

**Issue by cheribral** [terraform-providers/terraform-provider-aws#8651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.0-beta2
+ provider.aws v2.10.0
+ provider.external v1.1.0
+ provider.tls v2.0.0-dev20190216h00-dev

### Affected Resource(s)
aws_ec2_transit_gateway_vpc_attachment

### Terraform Configuration Files
*Parent module*
```hcl
resource aws_ec2_transit_gateway "sec_main" {
  provider                       = aws.sec
  auto_accept_shared_attachments = "enable"
  description                    = "${var.data.prefix} ${var.data.cluster}"
}
resource aws_ram_resource_share "sec2fleet" {
  provider                  = aws.sec
  name                      = "sec2fleet"
  allow_external_principals = true
}
resource "aws_ram_resource_association" "tg" {
  provider           = aws.sec
  resource_arn       = aws_ec2_transit_gateway.sec_main.arn
  resource_share_arn = aws_ram_resource_share.sec2fleet.id
}


data "aws_caller_identity" "sec" {
  provider = aws.sec
}
data "aws_caller_identity" "fleet" {
  provider = aws.fleet
}
resource "aws_ram_principal_association" "sec2fleet" {
  provider           = aws.sec
  principal          = data.aws_caller_identity.fleet.account_id
  resource_share_arn = aws_ram_resource_share.sec2fleet.id
}

// The association above must be manually accepted before this works
data "aws_ec2_transit_gateway" "fleet" {
  depends_on = [
    aws_ec2_transit_gateway.sec_main
  ]
  provider = aws.fleet
  filter { 
    name   = "owner-id"
    values = [data.aws_caller_identity.sec.account_id]
  }
}

// Set up VPC and various subnets etc.
module "apps" {
  providers = { aws = aws.fleet }
...
  transit_gateway = data.aws_ec2_transit_gateway.fleet.id
}

```
*Child module*
```hcl
...
resource "aws_ec2_transit_gateway_vpc_attachment" "transit_connection" {
  count = length(var.private_subnets) > 0 ? 1 : 0
  subnet_ids = aws_subnet.private_subnets.*.id
  transit_gateway_id = var.transit_gateway
  vpc_id             = aws_vpc.main.id
}
...
```

### Expected Behavior
The state would apply successfully once the ID is known.
 
### Actual Behavior
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.side_b.data.aws_ec2_transit_gateway.fleet: Refreshing state...
module.side_a.data.aws_ec2_transit_gateway.fleet: Refreshing state...
...
Error: Provider produced inconsistent final plan

When expanding the plan for
module.side_a.module.apps.aws_ec2_transit_gateway_vpc_attachment.transit_connection[0]
to include new values learned so far during apply, provider "aws" produced an
invalid new value for .transit_gateway_id: was cty.StringVal(""), but now
cty.StringVal("tgw-05f7c0ef855b1dd66").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
...
...
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

The transit gateway is created in the same run in another account and shared with the account in question.  It requires two runs because the created resource must be accepted manually until #7601 is fixed.  On the second run, the ID of the accepted transit gateway is found using the `aws_ec2_transit_gateway` data source.

**Comment by bflad** [comment]
Hi @cheribral 👋 Sorry you ran into this. There have been some significant changes to the behavior of Terraform core between `v0.12.0-beta2` and the currently latest [`v0.12.0-rc1`](https://www.hashicorp.com/blog/releasing-terraform-0-12-0-rc1). Are you able to confirm this issue is still present using rc1? Thanks.

**Comment by cheribral** [comment]
Apologies, I hadn't noticed that there was an rc1 release.  Unfortunately, yes the issue is still present using that version.

**Comment by bflad** [comment]
Ah, bummer. Its a shame that the error is not too helpful here, but looking a little more closely at your configuration above, I do see the usage of `depends_on` with the data source:

```hcl
data "aws_ec2_transit_gateway" "fleet" {
  depends_on = [
    aws_ec2_transit_gateway.sec_main
  ]
  provider = aws.fleet
  filter { 
    name   = "owner-id"
    values = [data.aws_caller_identity.sec.account_id]
  }
}
```

Buried in our data source configuration documentation and certainly easy to miss is the section on [Data Resource Dependencies](https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies):

> Data resources have the same dependency resolution behavior as defined for managed resources.
> 
> In particular, the depends_on meta-argument is also available within data blocks, with the same meaning and syntax as in resource blocks.
> 
> However, due to the data resource behavior of deferring the read until the apply phase when depending on values that are not yet known, using depends_on with data resources will force the read to always be deferred to the apply phase, and therefore a configuration that uses depends_on with a data resource can never converge.
> 
> Due to this behavior, we do not recommend using depends_on with data resources.

The error message you are receiving may also be related to this recommendation. To remove the usage of `depends_on`, it generally best to switch to a direct reference if possible, and it looks like the [`aws_ec2_transit_gateway` resource has an `owner_id` attribute](https://www.terraform.io/docs/providers/aws/r/ec2_transit_gateway.html#owner_id) available for this case. e.g.

```hcl
data "aws_ec2_transit_gateway" "fleet" {
  provider = aws.fleet
  filter { 
    name   = "owner-id"
    values = [aws_ec2_transit_gateway.sec_main.owner_id]
  }
}
```

While this won't fix the issue of the manual acceptance (as you found, the feature request: #7601), this could potentially eliminate the `Error: Provider produced inconsistent final plan` error in this case. Hope this helps!

**Comment by cheribral** [comment]
Removing the depends_on fixes the problem!  Thank you for catching that.  I even remember reading that section before, but obviously had not remembered it well enough.  I was curious about the config never converging, but hadn't thought of tying it to the depends_on.  

Even after reading that a paragraph about dependencies a couple times now, I'm still not entirely clear how finding the value during the apply phase is different from a first run (ie nothing set up yet so no values are known) in terms of the final plan, but I'm happy to go with "Don't do that" :) 
Cheers!
