### ISSUE TITLE
aws_cloudwatch_metric_alarm broken "tags" argument

### ISSUE THREAD

**Issue by nehalraf** [terraform-providers/terraform-provider-aws#8653]
### Terraform Version
Terraform v0.11.13
+ provider.archive v1.2.2
+ provider.aws v2.10.0
+ provider.local v1.2.2
+ provider.template v2.1.2

### Affected Resource(s)
aws_cloudwatch_metric_alarm

### Terraform Configuration Files

 	

```hcl
resource "aws_cloudwatch_metric_alarm" "appsrunning" {
  alarm_name                = "appsrunning-alarm-dp"
  comparison_operator       = "LessThanThreshold"
  evaluation_periods        = "2"
  metric_name               = "AppsRunning"
  namespace                 = "AWS/ElasticMapReduce"
  period                    = "300"
  statistic                 = "Sum"
  threshold                 = "5"
  alarm_description         = "Applications submitted to YARN are running."
  insufficient_data_actions = []
   alarm_actions = [
        "...."
     ]
   ok_actions = [
        "...."
     ]
  dimensions {
    JobFlowId = "clusterid"
  }
  tags {
  	Priority = "P1"
  	DataCenter = "core-0"
  	}
}
```

### Debug Output
```
module.emr-core-02.aws_cloudwatch_metric_alarm.appsrunning: Creating...
  actions_enabled:                       "" => "true"
  alarm_actions.#:                       "" => "1"
  alarm_actions.3954655195:              "" => "......."
  alarm_description:                     "" => "Applications submitted to YARN are running."
  alarm_name:                            "" => "appsrunning-alarm-dp"
  arn:                                   "" => "<computed>"
  comparison_operator:                   "" => "LessThanThreshold"
  dimensions.%:                          "" => "1"
  dimensions.JobFlowId:                  "" => "j-XXXXXXX"
  evaluate_low_sample_count_percentiles: "" => "<computed>"
  evaluation_periods:                    "" => "2"
  metric_name:                           "" => "AppsRunning"
  namespace:                             "" => "AWS/ElasticMapReduce"
  ok_actions.#:                          "" => "1"
  ok_actions.3954655195:                 "" => "......"
  period:                                "" => "300"
  statistic:                             "" => "Sum"
  tags.%:                                "" => "2"
  tags.DataCenter:                       "" => "core-0"
  tags.Priority:                         "" => "P1"
  threshold:                             "" => "5"
  treat_missing_data:                    "" => "missing"
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Expected Behavior
When alert is created in CloudWatch I should see Tags

### Actual Behavior
CloudWatch Create Alarm json (from Cloudwatch Alarm history tab) didnt get tags filed
```
{
  "type": "Create",
  "createdAlarm": {
    "alarmConfigurationUpdatedTimestamp": "2019-05-15T23:43:44.538+0000",
    "namespace": "AWS/ElasticMapReduce",
    "insufficientDataActions": [],
    "threshold": 5,
    "stateUpdatedTimestamp": "2019-05-15T23:43:44.538+0000",
    "metricName": "AppsRunning",
    "alarmActions": [
      "....."
    ],
    "comparisonOperator": "LessThanThreshold",
    "alarmName": "appsrunning-alarm-dp",
    "stateValue": "INSUFFICIENT_DATA",
    "evaluationPeriods": 2,
    "alarmArn": ".......",
    "alarmDescription": "Applications submitted to YARN are running.",
    "actionsEnabled": true,
    "statistic": "Sum",
    "dimensions": [
      {
        "value": "j-XXXXXXXXXXXX",
        "name": "JobFlowId"
      }
    ],
    "period": 300,
    "treatMissingData": "missing",
    "okactions": [
      "........"
    ]
  },
  "version": "1.0"
}
```

* #0000

**Comment by bflad** [comment]
Hi @nehalraf 👋 Sorry you are running into this situation. Where is that particular JSON output coming from? It looks different than the debugging output provided by the AWS Go SDK, which is what would be included within the Terraform AWS Provider itself. If it is a system external to AWS, it may need to be updated for tagging support.

The tagging support added to the `aws_cloudwatch_metric_alarm` resource as part of #8168 appears to be doing all the correct code logic and testing required with AWS to verify that tags are set during the `PutMetricAlarm` API call and read back into the Terraform state with `ListTagsForResource`. Can you verify that another `terraform plan` after the resource creation of the shows no differences (e.g. no `tags` updates) and trying to find tagging information outside of Terraform either via the [`aws cloudwatch list-tags-for-resource` CLI command](https://docs.aws.amazon.com/cli/latest/reference/cloudwatch/list-tags-for-resource.html) or AWS console correctly lists the tags? Thanks.

**Comment by nehalraf** [comment]
Thanks @bflad I see tags from cli. Closing ticket. Regards

$ aws cloudwatch list-tags-for-resource --resource-arn arn:aws:cloudwatch:us-west-2:xxxxxxxxxxxxxxx:alarm:appsrunning-alarm-dp
{
    "Tags": [
        {
            "Key": "Priority",
            "Value": "P1"
        }, 
         .........
    ]
}
