### ISSUE TITLE
Feature request: aws_dynamodb_table autoscaling support

### ISSUE THREAD

**Issue by sharebear** [terraform-providers/terraform-provider-aws#866]
[People are just noticing](https://www.reddit.com/r/aws/comments/6h9ayj/when_did_dynamodb_autoscaling_go_live/) that Amazon quietly released autoscaling support for dynamodb tables.

This is definitely a feature I'm going to be using and should be configurable via Terraform.

Docs: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.html

**Comment by jpbochi** [comment]
They announced this on their blog yesterday. See https://aws.amazon.com/blogs/aws/new-auto-scaling-for-amazon-dynamodb/
