### ISSUE TITLE
Update aws_sns_topic to support tags

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#8666]
https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-sns-adds-support-for-cost-allocation-tags/

sns topics now supports tags. aws_sns_topic resource needs updating to support tags

**Comment by ewbankkit** [comment]
@e-moshaya This has already been addressed via https://github.com/terraform-providers/terraform-provider-aws/issues/8460, https://github.com/terraform-providers/terraform-provider-aws/pull/8468 and will be in the upcoming v2.11.0 provider release.
Thanks.

**Comment by bflad** [comment]
This has been released in [version 2.11.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2110-may-17-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
