### ISSUE TITLE
Add ECS as a cloudwatch_event_target 

### ISSUE THREAD

**Issue by dcosson** [terraform-providers/terraform-provider-aws#871]
This is a feature request.

AWS recently added the ability to run ECS Tasks based on Cloudwatch Event triggers http://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html

In Terraform, I believe this would map to a [cloudwatch_event_target](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_target.html), which is the way that you currently set a lambda function to run based on a cloudwatch event trigger.

**Comment by radeksimko** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/977 was merged and will be part of the next release.
