### ISSUE TITLE
Support additional authentication providers in Appsync

### ISSUE THREAD

**Issue by acburdine** [terraform-providers/terraform-provider-aws#8715]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Announced [here](https://aws.amazon.com/about-aws/whats-new/2019/05/aws-appsync-now-supports-configuring-multiple-authorization-type/), Appsync now supports specifying additional auth methods. The aws_appsync_graphql_api resource should be updated to allow configuring of these additional auth methods.

### New or Affected Resource(s)

* aws_appsync_graphql_api

### Potential Terraform Configuration

```hcl
resource "aws_appsync_graphql_api" "example" {
  authentication_type = "AWS_IAM"
  name = "example"

  additional_authentication_provider {
    authentication_type = "API_KEY"
  }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2019/05/aws-appsync-now-supports-configuring-multiple-authorization-type/

There's a PR open already that should fix this issue: #8587 Opening an issue for greater visibility/tracking.

**Comment by bflad** [comment]
Support for `additional_authentication_provider` configuration blocks in the `aws_appsync_graphql_api` resource has been merged and will release with version 2.30.0 of the Terraform AWS Provider, later this week. Thanks to @acburdine for the implementation. 👍
