### ISSUE TITLE
Incorrect UserAgent is provided for AWS calls

### ISSUE THREAD

**Issue by natefaerber** [terraform-providers/terraform-provider-aws#8730]
The provider generates a UserAgent string based on the Terraform it happened to be compiled against.  It doesn't accurately reflect the Terraform version that the user is using.

For example, despite only having Terraform 0.11.14 installed:
* v2.8.0 of the provider will report Terraform 0.12.0-beta2
* v2.11.0 of the provider will report Terraform 0.12.0-rc1

This doesn't cause functional issue that I can see.  It is only a problem if you are auditing (via CloudTrail) the UserAgent string to ensure that the correct version of Terraform is being used.

`aws/config.go` is where the string is generated at build time.

```
                UserAgentProducts: []*awsbase.UserAgentProduct{
                        {Name: "APN", Version: "1.0"},
                        {Name: "HashiCorp", Version: "1.0"},
                        {Name: "Terraform", Version: terraform.VersionString()},
                },
```

`terraform.VersionString()` will return whichever version of Terraform was vendored for that release.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

* CloudTrail Audits

### Terraform Configuration Files

Anything with AWS resource.

### Expected Behavior

`Terraform/0.11.14` should be reported in UserAgent

### Actual Behavior

Incorrect version of Terraform is reported:

`"userAgent": "aws-sdk-go/1.19.30 (go1.12.2; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.0-rc1",`

### Steps to Reproduce

With any AWS resource.

1. `terraform apply`
2. See CloudTrail event

### References

* https://github.com/hashicorp/terraform/blob/v0.11.14/version/version.go#L14
* https://github.com/hashicorp/terraform/issues/5020

**Comment by bflad** [comment]
Hi folks 👋  Sorry this was not closed earlier, but this was likely resolved right around when we migrated to the standalone Terraform Plugin SDK. The behavior after that point should be that Terraform 0.11 and earlier show user agent of `Terraform/0.11+compatible` and accurate `Terraform/X.Y.Z` for Terraform 0.12 and later based on versioning sent over gRPC. I can confirm this with a quick local test on Terraform AWS Provider 2.69.0 and Terraform 0.12.28:

```
2020-07-07T09:26:10.468-0400 [DEBUG] plugin.terraform-provider-aws_v2.69.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2020-07-07T09:26:10.468-0400 [DEBUG] plugin.terraform-provider-aws_v2.69.0_x4: POST / HTTP/1.1
2020-07-07T09:26:10.468-0400 [DEBUG] plugin.terraform-provider-aws_v2.69.0_x4: Host: ec2.us-east-1.amazonaws.com
2020-07-07T09:26:10.468-0400 [DEBUG] plugin.terraform-provider-aws_v2.69.0_x4: User-Agent: aws-sdk-go/1.32.12 (go1.13.7; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.28 (+https://www.terraform.io)
```
