### ISSUE TITLE
Amazon API Gateway additional resource tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8744]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of  [AWS SDK v1.19.36](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.36) additional Amazon API Gateway resources can be tagged:
> This release adds support for tagging of Amazon API Gateway resources.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8742

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-api-gateway-now-supports-tag-based-access-control-tags-additional-resources/).
[Developer guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-tagging-supported-resources.html).

[`aws_api_gateway_stage`](https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html) resources already supported resource tags - https://github.com/terraform-providers/terraform-provider-aws/pull/2858.

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_api_gateway_api_key`](https://www.terraform.io/docs/providers/aws/r/api_gateway_api_key.html)
* [`aws_api_gateway_client_certificate`](https://www.terraform.io/docs/providers/aws/r/api_gateway_client_certificate.html)
* [`aws_api_gateway_domain_name`](https://www.terraform.io/docs/providers/aws/r/api_gateway_domain_name.html)
* [`aws_api_gateway_rest_api`](https://www.terraform.io/docs/providers/aws/r/api_gateway_rest_api.html)
* [`aws_api_gateway_usage_plan`](https://www.terraform.io/docs/providers/aws/r/api_gateway_usage_plan.html)
* [`aws_api_gateway_vpc_link`](https://www.terraform.io/docs/providers/aws/r/api_gateway_vpc_link.html)

**Comment by bflad** [comment]
Resource tagging with API Gateway resources that support it directly ([others inherit tags from parent resources](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-tagging-supported-resources.html)) has now been merged. Tagging for the last remaining resource in this feature request, `aws_api_gateway_rest_api`, will release with version 2.37.0 of the Terraform AWS Provider, by Thursday next week. Thanks to @stephentyellis and @DrFaust92 for their implementations. 🚀

**Comment by bflad** [comment]
Please note that due to some strange behavior with GitHub's Squash and Merge functionality, the `aws_api_gateway_usage_plan` tagging enhancements will go out in version 2.42.0 of the Terraform AWS Provider.
