### ISSUE TITLE
ACM domain_validation_options output not stable

### ISSUE THREAD

**Issue by edulop91** [terraform-providers/terraform-provider-aws#8747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.11

### Affected Resource(s)

aws_acm_certificate

### Terraform Configuration Files

Using this [module](https://github.com/chanzuckerberg/cztack/blob/master/aws-acm-cert/main.tf#L13)

### Expected Behavior

I expect that the domain_validation_options remain stable between terraform runs when there are neither code changes nor aws console changes.

### Actual Behavior
The order of items in aws_acm_cert.x.domain_validation_options seems to be unstable. If we are creating other resources using a `count` on this list ([example](https://github.com/chanzuckerberg/cztack/blob/master/aws-acm-cert/main.tf#L28)) then we get spurious diffs. 

first run:
```
[
  {
    "domain_name": "F",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "A",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "B",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "C",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "D",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "E",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  }
]
```

second run:
```
[
  {
    "domain_name": "A",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "B",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "C",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "D",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "E",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  },
  {
    "domain_name": "F",
    "resource_record_name": "<redacted>",
    "resource_record_type": "CNAME",
    "resource_record_value": "<redacted>"
  }
]
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by edulop91** [comment]
Realize the terraform 0.12 for_each might actually fix this

**Comment by blimmer** [comment]
For those looking for a workaround -

```tf
locals {
  zonemap = "${zipmap(aws_route53_zone.hosted-zones.*.name, aws_route53_zone.hosted-zones.*.zone_id)}"
}
```

and then in your R53 record block:

```tf
resource "aws_route53_record" "domain-validations" {
  count = "${length(var.domain_names)}"
  zone_id = "${lookup(local.zonemap, "${lookup(aws_acm_certificate.cert.domain_validation_options[count.index], "domain_name")}.")}"
}
```

**Comment by tdmalone** [comment]
Possible duplicate of #8531

**Comment by edulop91** [comment]
Closing since duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/8531
