### ISSUE TITLE
Support for X-Ray Groups and Encryption

### ISSUE THREAD

**Issue by joebowbeer** [terraform-providers/terraform-provider-aws#8749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS xray allows for creating groups and configuring encryption. It would be nice to manage these in TF.

### New or Affected Resource(s)

* aws_xray

### Resources

* https://docs.aws.amazon.com/xray/latest/devguide/xray-api-configuration.html
* https://aws.amazon.com/blogs/developer/deep-dive-into-aws-x-ray-groups-and-use-cases/

### References

* #7028

**Comment by rmccarthy-ellevation** [comment]
Do we know if this is a thing or will be a thing in the future?

**Comment by DrFaust92** [comment]
addressed group resource in #13597

looking at encryption config as well.

**Comment by DrFaust92** [comment]
XRay Encryption Config address in #13600

**Comment by bostrowski13** [comment]
seems like this is done?  would love to have this soon!  thanks for your work!

**Comment by jbigtani** [comment]
Looks like linkage between issue and PR is missing. It does not show on the right hand side. 
https://github.com/terraform-providers/terraform-provider-aws/pull/13600
@DrFaust92 if you fix this it might help.

**Comment by DrFaust92** [comment]
Thanks @jbigtani, added.

**Comment by bflad** [comment]
Support for the following two new resources has been merged and will release with version 3.4.0 of the Terraform AWS Provider, likely later today.

* `aws_xray_encryption_config`
* `aws_xray_group`

Thanks to @DrFaust92 for the implementation. 👍
