### ISSUE TITLE
Add support for AWS DDB Auto-Scaling

### ISSUE THREAD

**Issue by robert-stuttaford** [terraform-providers/terraform-provider-aws#875]
https://aws.amazon.com/blogs/aws/new-auto-scaling-for-amazon-dynamodb/

**Comment by Ninir** [comment]
Hi @robert-stuttaford 

This feature has already been suggested lately [in another issue](https://github.com/terraform-providers/terraform-provider-aws/issues/866).
Closing this one in favor of the other one. Thanks for opening this issue!
