### ISSUE TITLE
2.12.0 - error saving tags for SSM Maintenance Window

### ISSUE THREAD

**Issue by emalihin** [terraform-providers/terraform-provider-aws#8762]
### Terraform Version
0.11.14

### Affected Resource(s)
* aws_ssm_maintenance_window

### Terraform Configuration Files
```
resource "aws_ssm_maintenance_window" "w" {
  name     = "${var.prefix}maintenance-window"
  schedule = "cron(0 0 7 ? * MON *)"
  duration = 3
  cutoff   = 1
}
```

### Debug Output
```
Error: Error refreshing state: 1 error occurred:
	* module.aws_account.aws_ssm_maintenance_window.w: 1 error occurred:
	* module.aws_account.aws_ssm_maintenance_window.w: aws_ssm_maintenance_window.w: error saving tags for SSM Maintenance Window (mw-xxxxxxxxxxx): Error retrieving tags for SSM resource: mw-xxxxxxxxxxx
```

### Expected Behavior
Plan should run to completion, as it did yesterday with provider version 2.11.0

### Actual Behavior
Plan fails with above error on all AWS accounts, since we re-use a module

### Steps to Reproduce
1. `terraform plan` on existing SSM Maintenance Windows

**Comment by emalihin** [comment]
In fact, rolling back aws provider to version `2.11.0`, while using the same terraform version `0.11.14` does not work any more either! 

Comparing tfstate yesterday vs today shows 0 changes too.

Will talk to AWS support.

**Comment by bflad** [comment]
Hi folks 👋 Sorry for this frustrating behavior. Hopefully AWS Support can shed some light if it is indeed an API issue. Our error message in this situation looks to be lacking troubleshooting information though, which does not help either. From our side, I'll add error code information to our error messaging here.

While things get sorted out on both ends, you may find it helpful (and required if AWS Support needs the API request IDs), to enable [debug logging](https://www.terraform.io/docs/internals/debugging.html) with Terraform, e.g. `TF_LOG=debug terraform plan`, which in there will show all the API requests and their responses/error codes.

**Comment by emalihin** [comment]
Thank you for responding and debug suggestion @bflad! I'm currently chatting to AWS support. So far I've only seen this CloudTrail event:

```
  	 errorCode:	 UnrecognizedClientException	
  	 errorMessage:	 An unknown error occurred	
  	 eventID:	 xxxx	
  	 eventName:	 ListTagsForResource	
  	 eventSource:	 ssm.amazonaws.com 	
  	 eventTime:	 2019-05-24T10:50:47Z	
  	 eventType:	 AwsApiCall	
  	 eventVersion:	 1.05	
  	 recipientAccountId:	 xxxx	
  	 requestID:	 xxxx
```
Will try to run tf plan in debug mode and provide update.

**Comment by emalihin** [comment]
There appears to be an issue with SSM API `list-tags-for-resource` endpoint in eu-west-1 specifically.

Awaiting update/resolution from AWS and will post then.

**Comment by sjones-sot** [comment]
Debug output shows: `UnrecognizedClientException: The security token included in the request is invalid.`

**Comment by emalihin** [comment]
aws cli shows the same err, AWS are aware and on our case.

**Comment by jeandek** [comment]
AWS Support has told me that the issue with their API is resolved and I have confirmed it for myself.

I think they broke maintenance window targets too, but I haven't investigated it yet...

**Comment by emalihin** [comment]
Same, fix confirmed by AWS and terraform apply now works. Closing the issue - unrelated to tf aws provider.
