### ISSUE TITLE
aws_security_group v0.12 fails

### ISSUE THREAD

**Issue by michaeljs1990** [terraform-providers/terraform-provider-aws#8786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Broken Version
```
Terraform v0.12.0
+ provider.aws v2.12.0
```
Working Version
```
Terraform v0.11.13
+ provider.aws v2.12.0
```

### Affected Resource(s)

* aws_security_group

### Terraform Configuration Files

```json
{
	"aws_security_group": {
		"dev-alb": {
			"description": "Load balancer",
			"egress": [{
				"cidr_blocks": [
					"0.0.0.0/0"
				],
				"from_port": 0,
				"protocol": "-1",
				"to_port": 0
			}],
			"ingress": [{
					"cidr_blocks": [
						"0.0.0.0/0"
					],
					"description": "HTTPS",
					"from_port": 443,
					"protocol": "tcp",
					"to_port": 443
				},
				{
					"cidr_blocks": [
						"0.0.0.0/0"
					],
					"description": "HTTP",
					"from_port": 80,
					"protocol": "tcp",
					"to_port": 80
				}
			],
			"tags": {
				"Creator": "terraform",
				"Environment": "dev",
				"Name": "dev-alb"
			},
			"vpc_id": "${aws_vpc.dev.id}"
		}
	}
}
```

### Expected Behavior

It should apply just as it does in the previous version of terraform.

### Actual Behavior

It fails and throws the following erros.
```
Error: Incorrect attribute value type

  on terraform.tf.json line 614, in resource.aws_security_group.dev-alb:
 614:             "ingress": [

Inappropriate value for attribute "ingress": element 0: attributes
"ipv6_cidr_blocks", "prefix_list_ids", "security_groups", and "self" are
required.
```

This makes no sense to me prefix_list_ids is only for VPC endpoints.... Which I am not trying to use.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I use JSON not HCL for config. This shouldn't matter as you posted a blog a while back about JSON being a first class citizen.

**Comment by michaeljs1990** [comment]
Not sure if this is actually an issue with core or an issue with this modules interaction with v0.12. I have a feeling it's the latter but will leave that to someone with more experience to decide.

**Comment by grahamjenson** [comment]
We are having this problem as well when we use the terraform JSON. There are a few strange things about this problem:

1. It does not happen to every `ingress` or `egress`.
2. As mentioned above it requires attributes like `description` which an egress does not even support

**Comment by bflad** [comment]
Hi folks 👋

The `aws_security_group` resource `ingress` and `egress` configuration blocks are using a special schema within Terraform 0.12 that is allowing them to still accept a zero value to purposefully remove their configuration as was possible in Terraform 0.11 (e.g. ensure all ingress rules are removed). The resource documentation tries to point this out by linking to https://www.terraform.io/docs/configuration/attr-as-blocks.html

In particular, the [In JSON syntax section](https://www.terraform.io/docs/configuration/attr-as-blocks.html#in-json-syntax) tries to outline some of the restrictions of this schema mode. In Terraform 0.12, it is now required to explicitly declare each argument in JSON, even it is optional in configuration block syntax. The new `null` value can be passed to satisfy this constraint, e.g.

```json
{
    "resource": {
        "aws_security_group": {
            "example": {
                "ingress": [
                    {
                        "cidr_blocks": [
                            "0.0.0.0/0"
                        ],
                        "description": "HTTPS",
                        "from_port": 443,
                        "ipv6_cidr_blocks": null,
                        "prefix_list_ids": null,
                        "protocol": "tcp",
                        "security_groups": null,
                        "self": null,
                        "to_port": 443
                    }
                ],
                "vpc_id": "${aws_vpc.example.id}"
            }
        },
        "aws_vpc": {
            "example": {
                "cidr_block": "10.0.0.0/16"
            }
        }
    }
}
```

The above JSON configuration applies successfully in Terraform 0.12. 

For reference, these special schema configurations can be found in the code base by searching for attributes with `SchemaConfigModeAttr` and the current list is:
* `aws_default_route_table` resource `route` configuration block
* `aws_emr_cluster` resource `step` configuration block and nested `hadoop_jar_step` configuration block
* `aws_network_acl` resource `ingress` and `egress` configuration blocks
* `aws_security_group` resource `ingress` and `egress` configuration blocks

This list should hopefully not change too much we understand the optional -> required arguments does represent a breaking change in JSON syntax. As we learn more about Terraform 0.12 upgrades and usage patterns though, we may consider other configuration blocks in future updates of the Terraform AWS Provider. If any of these changes do occur in a release, they will be highlighted in the `NOTES` section of the `CHANGELOG` for the update.

This configuration language design decision occurred upstream in [Terraform Core](https://github.com/hashicorp/terraform), so for any further discussion or feature requests about the JSON syntax and its changes, you will need to open an issue there. Hope this helps though!

**Comment by michaeljs1990** [comment]
Thanks for the in depth explanation on this one @bflad. I have many questions about this decision but will take it over to core 😄

**Comment by krobertson** [comment]
@bflad does this mean that when you have tooling that wraps Terraform's JSON format, it needs to be updated to support 0.12 changes. Will doing this break compatibility with 0.11?

**Comment by bflad** [comment]
@krobertson I'm not familiar enough with the differences between Terraform 0.11 and 0.12 JSON formats to comment on that. I'd recommend trying it out and if you have issues, asking upstream. 👍
