### ISSUE TITLE
IAM group policy "does not support import"

### ISSUE THREAD

**Issue by yamamo429** [terraform-providers/terraform-provider-aws#8788]
Terraform 0.12.0
provider.aws ~> 1.17

Action:
Importing a existing aws_iam_group as stated in the following documentation:
https://www.terraform.io/docs/providers/aws/r/iam_group_policy.html

Result:
Error: resource aws_iam_group_policy doesn't support import

This issue might be similar to #8785 .

**Comment by lucioveloso** [comment]
I guess the command should be similar like the `import aws_iam_user_policy`:

`terraform import aws_iam_group_policy.<resource name> <group name>:<aws group policy name>`

Does it make sense?

**Comment by yamamo429** [comment]
I'm looking forward to #9217 merged in the near future！

**Comment by bflad** [comment]
Support for `aws_iam_group_policy` resource import has been merged and will release with version 2.18.0 of the Terraform AWS Provider, very shortly. Thanks, @lucioveloso!

**Comment by bflad** [comment]
This has been released in [version 2.18.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2180-july-05-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
