### ISSUE TITLE
Using stage variables in OpenAPI specification of AWS API Gateway

### ISSUE THREAD

**Issue by mjarosie** [terraform-providers/terraform-provider-aws#8790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.archive v1.2.1
+ provider.aws v1.60.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_api_gateway_rest_api
* aws_api_gateway_stage

### Terraform Configuration Files

template.tpl containing OpenAPI specification:
```
{
    "openapi": "3.0.1",
    "info": {
        "title": "${gateway_name}",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://api.example.com/test"
        }
    ],
    "paths": {
        "/v1/test": {
            "get": {
                "responses": {
                    "200": {
                        "description": "200 response"
                    }
                },
                "x-amazon-apigateway-integration": {
                    "uri": "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/$${stageVariables.lambda_function_test_arn}/invocations",
                    "passthroughBehavior": "when_no_templates",
                    "httpMethod": "POST",
                    "type": "aws_proxy",
                    "responses": {
                        "default": {
                            "statusCode": "200"
                        }
                    }
                }
            }
        }
    }
}
```

Terraform configuration:
```hcl
data "template_file" "_" {
  template = "${file("./template.tpl")}"

  vars = {
    aws_region = "${var.aws_region}"
  }
}

resource "aws_api_gateway_rest_api" "_" {
  name           = "test_api"
  api_key_source = "HEADER"

  body = "${data.template_file._.rendered}"
}

resource "aws_api_gateway_stage" "_" {
  stage_name    = "test"
  rest_api_id   = "${aws_api_gateway_rest_api._.id}"
  variables     = {
    lambda_function_test_arn = "...some Lambda ARN..."
  }
}
```

### Expected Behavior

After running `terraform apply` the API Gateway should reference the stage variable instead of having a specific Lambda hardcoded (see [this](https://aws.amazon.com/blogs/compute/using-api-gateway-stage-variables-to-manage-lambda-functions/) article for details on how to do it manually).

### Actual Behavior

Instead I'm getting this error:

```
* aws_api_gateway_rest_api._: error updating API Gateway specification: BadRequestException: Errors found during import:
        Unable to put integration on 'GET' for resource at path '/v1/test': Invalid lambda function
        status code: 400, request id: xxxxxx
```

### Steps to Reproduce

1. `terraform apply`

### References

* https://aws.amazon.com/blogs/compute/using-api-gateway-stage-variables-to-manage-lambda-functions/
* https://github.com/hashicorp/terraform/issues/6463
* https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html
* https://docs.aws.amazon.com/apigateway/latest/developerguide/aws-api-gateway-stage-variables-reference.html
* https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#stagevariables-template-reference

**Comment by mjarosie** [comment]
I have upgraded AWS provider to v2.12.0
The issue still persists.

**Comment by mjarosie** [comment]
Issue resolved - as it turns out the integration URL has to be **EXACTLY** like this: 

```
"uri": "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/arn:aws:lambda:**${aws_region}**:${aws_account_id}:function:$${stageVariables.lambda_function_name}/invocations",
```

Hence, substituting the whole ARN of lambda instead of just name part (like in my initial example) doesn't work, even though as far as I understand it should be escaped to exactly the same value...

It's mentioned [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/aws-api-gateway-stage-variables-reference.html#stage-variables-in-integration-lambda-functions), but I think that the documentation contains an error as it still returned errors when I didn't include ${aws_region} in the second part of the URL (the part of the URL above in bold), so the following example (taken from mentioned documentation page) **did not** work for me:

arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda::<account_id>:function:${stageVariables.<function_variable_name>}/invocations

**Comment by bflad** [comment]
Hi @mjarosie 👋 Sorry you ran into trouble here.

Just to clarify, are you expecting a documentation change with the [Terraform AWS Provider](https://www.terraform.io/docs/providers/aws/index.html)? The GitHub issues in this repository are only regarding this software and its documentation, which is unaffiliated with AWS and the AWS service teams themselves. If you would like to provide feedback to the specific the AWS service team on their documentation (e.g. on docs.aws.amazon.com), I believe the correct method is to use the Feedback button on the bottom right of those documentation pages.

Please let us know. Thanks.

**Comment by mjarosie** [comment]
Hi @bflad Sure, as it turns out it's not a problem with the content of this repository! :tada: I have just added a comment instead of just closing the issue so that when anyone else runs into this kind of problem, he/she'll find a solution here :relaxed: I'm happy to close the issue and forward the problem to AWS. Cheers!
