### ISSUE TITLE
aws_lb_target_group failed to enable health check

### ISSUE THREAD

**Issue by yongzhang** [terraform-providers/terraform-provider-aws#8802]
terraform version: 0.11.14
plugin version: 2.12.0
aws_lb_target_group failed to enable health check, but actually health check is working:
![image](https://user-images.githubusercontent.com/15604715/58534517-21404280-821e-11e9-95a9-92650d3772d1.png)

code:
```
resource "aws_lb_target_group" "kubeingress_public" {
  name     = "whatever"
  port     = 80
  protocol = "HTTP"
  vpc_id   = "whatever"

  health_check {
    interval            = "whatever"
    path                = "whatever"
    port                = "whatever"
    healthy_threshold   = "whatever"
    unhealthy_threshold = "whatever"
    matcher             = "whatever"
  }

}
```

terraform apply:
```
Terraform will perform the following actions:

  ~ aws_lb_target_group.kubeingress_public
      health_check.0.enabled: "false" => "true"

  ~ aws_lb_target_group.kubeingress_public_api
      health_check.0.enabled: "false" => "true"


Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_lb_target_group.kubeingress_public: Modifying... (ID: xxx)
  health_check.0.enabled: "false" => "true"
aws_lb_target_group.kubeingress_public_api: Modifying... (ID: xxx)
  health_check.0.enabled: "false" => "true"
aws_lb_target_group.kubeingress_public_api: Modifications complete after 1s (ID: xxx)
aws_lb_target_group.kubeingress_public: Modifications complete after 1s (ID: xxx)

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.
```

terraform apply again:
```
Terraform will perform the following actions:

  ~ aws_lb_target_group.kubeingress_public
      health_check.0.enabled: "false" => "true"

  ~ aws_lb_target_group.kubeingress_public_api
      health_check.0.enabled: "false" => "true"


Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:

```

**Comment by sidewinder12s** [comment]
I believe I also just hit this one as well. Applies, modifications complete, health check appears in console but Terraform keeps reporting it as off.

**Comment by andreitchaltsev** [comment]
I got the same issue. Running `apply` repeatedly still shows the change 
```
  ~ aws_lb_target_group.target_group_new
      health_check.0.enabled: "false" => "true"
```
If I manually fix the .tfstate the next `refresh` breaks it again.

An additional note is that the issue manifests itself only in China AWS (I tried Beijing region).
US regions does not have this issue.

**Comment by hiscal2015** [comment]
@hiscal2015 Confirm I'm using AWS China, I did not know global account will not hit this issue.

**Comment by hiscal2015** [comment]
> I got the same issue. Running `apply` repeatedly still shows the change
> 
> ```
>   ~ aws_lb_target_group.target_group_new
>       health_check.0.enabled: "false" => "true"
> ```
> 
> If I manually fix the .tfstate the next `refresh` breaks it again.
> 
> An additional note is that the issue manifests itself only in China AWS (I tried Beijing region).
> US regions does not have this issue.

Confirm I'm using AWS China, I did not know global account will not hit this issue.

**Comment by sidewinder12s** [comment]
Can also confirm I was using Beijing. Wonder what's different, but not the first weird thing I've run into in China.

**Comment by hakro** [comment]
I also confirm that I have this issue, in Beijing. At each plan or a apply, the "enabled" value of the TG group heath check is detected as false, so there is always "3 to change".
Explicitly specifying "enabled = true" doesn't change anything.

Terraform v0.12.7
+ provider.aws v2.26.0


![healthcheck](https://user-images.githubusercontent.com/3624853/65130467-c6fe0400-d9fd-11e9-8a4d-16ad5da7d212.png)

**Comment by yongzhang** [comment]
> I also confirm that I have this issue, in Beijing. At each plan or a apply, the "enabled" value of the TG group heath check is detected as false, so there is always "3 to change".
> Explicitly specifying "enabled = true" doesn't change anything.
> 
> Terraform v0.12.7
> 
> * provider.aws v2.26.0
> 
> ![healthcheck](https://user-images.githubusercontent.com/3624853/65130467-c6fe0400-d9fd-11e9-8a4d-16ad5da7d212.png)
> 
> [EDIT]
> After updating the AWS Provider to v.2.28, it worked fine. There are no more changes to be made on the plan of the apply.
> 
> I ran this command to update the provider :
> `terraform init -upgrade`

I guess AWS China fixed their API issue maybe, now I have no issues by change nothing...
