### ISSUE TITLE
[ECS] Support for Scheduled Tasks (cron) ECS Tasks

### ISSUE THREAD

**Issue by gregeinfrank** [terraform-providers/terraform-provider-aws#881]
Hi, 

Amazon recently announced the introduction of [Scheduled ECS Tasks](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html) - which we would find very useful and prevent us from having to [jump through hoops](https://www.fin.com/eng-blog/how-to-build-a-robust-scheduled-task-service-in-aws-using-cloudwatch-lambda-dynamodb-ecs) to get scheduled tasks to run on ECS

It would be awesome to be able to start creating these and managing them through Terraform. Sorry if this is a duplicate issue and thank you!

**Comment by radeksimko** [comment]
Hi @gregeinfrank 
I believe that the AWS Console UI steps mentioned in the dev guide are just covering existing API functionality which Terraform already supports. Specifically CloudWatch Events.

Have looked at https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_target.html and other relevant resources? As far as I can see there's no new ECS API for "scheduled tasks". All you seem to need is ECS Task Definition + ECS cluster and CloudWatch Event Rule + CloudWatch Event Target + relevant IAM resources.

**Comment by gregeinfrank** [comment]
@radeksimko I must have missed that - I will look into cloudwatch_event_target and see if I can schedule ECS tasks from there. Thanks

**Comment by anthonyagresta** [comment]
@radeksimko @gregeinfrank 
I tried this today, and it looks like there's a new set of `EcsParameters` options that are required in order for your target to run an ECS task.
It needs to pass in the ECS cluster ARN for the regular `Arn` parameter, but there's a separate `TaskDefinitionArn` and `TaskCount` that need to be provided in `EcsParameters` to tell it what to run on that cluster.

Looking at the source and documentation, it doesn't look like the resource can send these in its current state.
It looks like it'd be really similar to how the `run_command_targets` argument works now.

JSON Syntax example in the AWS CLI docs: <http://docs.aws.amazon.com/cli/latest/reference/events/put-targets.html>

**Comment by anthonyagresta** [comment]
related: #871

**Comment by radeksimko** [comment]
@anthonyagresta You're right, thanks for the effort in figuring out what's missing 👍 

Re-labelling as enhancement. PRs welcomed 😉

**Comment by radeksimko** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/977 was merged and will be part of the next release.

**Comment by theduke** [comment]
@anthonyagresta I was struggling with the exact same thing (albeit in Ansible, not terraform), and your comment here helped me figure things out.

Big cheers for that!

**Comment by joshuamkite** [comment]
So Amazon have just announced and released [Amazon ECS Adds Daemon Scheduling](https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-ecs-adds-daemon-scheduling/). Please could we have support for this attribute in Terraform?

**Comment by thomasbiddle** [comment]
@joshuamkite Sounds like that should be an entirely separate issue.
