### ISSUE TITLE
AWS CodeCommit repository tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of  [AWS SDK v1.19.41](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.41) AWS CodeCommit respositories can be tagged:
> This release adds APIs that allow adding and removing tags to a repository, and viewing tags for a repository. It also enables adding tags when creating a repository.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8810

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_codecommit_repository`](https://www.terraform.io/docs/providers/aws/r/codecommit_repository.html)

**Comment by bflad** [comment]
Support for managing tags in the `aws_codecommit_repository` resource has been merged and will release with version 2.18.0 of the Terraform AWS Provider, likely in the next day. Thanks, @sunilkumarmohanty!

**Comment by bflad** [comment]
This has been released in [version 2.18.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2180-july-05-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
