### ISSUE TITLE
Support for Data Sources for aws_backup* resources

### ISSUE THREAD

**Issue by martcollins** [terraform-providers/terraform-provider-aws#8822]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There don't seem to be Data Sources for aws_backup* resources.  Can't see any mention of them in the docs.  Have only wanted to use the aws_backup_vault data source so far, but the others might also be useful.

### New or Affected Resource(s)

* aws_backup_vault
* aws_backup_plan
* aws_backup_selection

### Potential Terraform Configuration

E.g. something like this:

```hcl
data "aws_backup_vault" "test-vault" {
  name = "TestVault"
}

data "aws_backup_plan" "test-plan" {
  name = "TestPlan"
}

data "aws_backup_selection" "test-selection" {
  name = "TestSelection"
}
```

### References

* #8821

**Comment by slapula** [comment]
I can take a stab at this.

**Comment by bflad** [comment]
@anGie44 what version is this going to be released in and in what timeframe?

**Comment by anGie44** [comment]
These changes will be in `v2.60.0` of the Terraform AWS Provider, expected to be released this week
