### ISSUE TITLE
S3 Backend: Shared Credentials File not working

### ISSUE THREAD

**Issue by maiconbaumx** [terraform-providers/terraform-provider-aws#8832]
### Terraform Version

Terraform v0.12.0
+ provider.aws v2.13.0

### Affected Resource(s)

Terraform Backend for S3.

### Terraform Configuration Files

```hcl
// Terraform Backend
terraform {
  backend "s3" {
    bucket                  = "<bucket-name>"
    region                  = "<region>"
    key                     = "<key-name>"
    workspace_key_prefix    = "<workspace-prefix>"
    shared_credentials_file = "<path-to-credentials>"
  }
}
```

### Debug Output

> 2019/06/02 10:33:41 [INFO] Terraform version: 0.12.0
> 2019/06/02 10:33:41 [INFO] Go runtime version: go1.12.4
> 2019/06/02 10:33:41 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/0.6.0/versions/0.12.0/terraform", "init"}
> 2019/06/02 10:33:41 [DEBUG] Attempting to open CLI config file: /var/root/.terraformrc
> 2019/06/02 10:33:41 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
> 2019/06/02 10:33:41 [INFO] CLI command args: []string{"init"}
> 2019/06/02 10:33:41 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
> Initializing modules...
> 2019/06/02 10:33:41 [DEBUG] Module installer: begin terraform_backend
> 2019/06/02 10:33:41 [TRACE] ModuleInstaller: Module installer: terraform_backend <nil> already installed in ../iac-aws-s3
> 2019/06/02 10:33:41 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json
> 
> Initializing the backend...
> 2019/06/02 10:33:41 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 324847137
> 2019/06/02 10:33:41 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
> 2019/06/02 10:33:41 [DEBUG] New state was assigned lineage "5682097b-f5f1-dc5f-9cc6-687f3da817aa"
> 2019/06/02 10:33:41 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
> 2019/06/02 10:33:41 [INFO] Setting AWS metadata API timeout to 100ms
> 2019/06/02 10:33:42 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
> 
> Error: No valid credential sources found for AWS Provider.
> 	Please see https://terraform.io/docs/providers/aws/index.html for more information on
> 	providing credentials for the AWS Provider

### Expected Behavior

Get the AWS Credentials file in the specified path.

### Actual Behavior

Trying to get AWS Credentials file from default path (~/.aws/credentials) which don't have a set of credentials.

### Steps to Reproduce

1. `terraform init`

### References

Based on this documentation: https://www.terraform.io/docs/backends/types/s3.html#shared_credentials_file

**Comment by ewbankkit** [comment]
@maiconbaumx Because of the way that the Terraform code is currently structured, the S3 backend is part of the main Terraform repository - https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3.

**Comment by danil-smirnov** [comment]
Confirming the issue with
```
Terraform v0.12.24
+ provider.aws v2.56.0
```
~/.aws/credentials is checked, `shared_credentials_file` seems ignored

**Comment by IvanMoucha** [comment]
Confirming the same:

`Terraform v0.12.24
+ provider.aws v2.56.0`

`shared_credentials_file` is not working
`profile` is working (it's possible to choose the profile from default credential file)

**Comment by dkossako** [comment]
Same here:
Initializing the backend...

> 2020/07/03 09:33:06 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 1962679397
> 2020/07/03 09:33:06 [TRACE] Preserving existing state lineage "a9910ed3-457b-4aa6-2875-a2bdd2a43ac7"
> 2020/07/03 09:33:06 [TRACE] Preserving existing state lineage "a9910ed3-457b-4aa6-2875-a2bdd2a43ac7"
> 2020/07/03 09:33:06 [TRACE] Meta.Backend: working directory was previously initialized for "s3" backend
> 2020/07/03 09:33:06 [TRACE] Meta.Backend: using already-initialized, unchanged "s3" backend configuration
> 2020/07/03 09:33:06 [INFO] Setting AWS metadata API timeout to 100ms
> 2020/07/03 09:33:08 [INFO] Ignoring AWS metadata API endpoint at default location as it doesn't return any instance-id
> 2020/07/03 09:33:08 [INFO] Attempting to use session-derived credentials

```
provider "aws" {
  region = "us-west-2"
  shared_credentials_file = "~/.terraform.d/credentials/911day.org.aws"
}
```

```
Terraform version: 0.12.28  
Go runtime version: go1.12.13
```

**Comment by bflad** [comment]
Hi folks 👋  Thank you for reporting this and sorry you ran into trouble. As mentioned above, issues with the Terraform S3 Backend currently must be handled in the [hashicorp/terraform repository](https://github.com/hashicorp/terraform) for triage as that is where maintainers of that code would expect to find issues. Given that I cannot transfer this issue across GitHub organizations, unfortunately all I can do is encourage you to do is create a new issue there if there are still problems and I'm going to close this here as unactionable. That being said, Terraform 0.13.0-beta2 includes many changes to the Terraform S3 Backend handling of authentication and AWS shared credentials/configuration files, so it may be best to try on that version or later to see if things are already resolved.
