### ISSUE TITLE
Add support for server host key to aws_transfer_server resource

### ISSUE THREAD

**Issue by stuartgrice** [terraform-providers/terraform-provider-aws#8836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS Transfer service just got a new feature that allows users to set their SSH host key.

This setting is valuable if you are trying to lift and shift an existing SFTP Server to the AWS service. see https://aws.amazon.com/blogs/storage/lift-and-shift-migration-of-sftp-servers-to-aws/ for details.

It would be great for the provider to support this feature.

### New or Affected Resource(s)

A potential implementation would be an additional optional parameter of `host-key` on the `aws_transfer_server` resource.

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Support for a new `host_key` argument has been merged and will release with version 2.50.0 of the Terraform AWS Provider, shortly. Thanks to @kterada0509 for the implementation. 👍
