### ISSUE TITLE
Ensure correct VIF type during import of Direct Connect Virtual Interfaces

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [`aws_dx_private_virtual_interface`](https://www.terraform.io/docs/providers/aws/r/dx_private_virtual_interface.html), [`aws_dx_public_virtual_interface`](https://www.terraform.io/docs/providers/aws/r/dx_private_virtual_interface.html) and [`aws_dx_transit_virtual_interface`](https://github.com/terraform-providers/terraform-provider-aws/pull/8522) all support resource import via `terraform import`. As the same underlying [AWS Direct Connect API call](https://docs.aws.amazon.com/directconnect/latest/APIReference/API_DescribeVirtualInterfaces.html) is used in all cases, it is possible to import e.g. a transit VIF as a private VIF. The API returns a `VirtualInterfaceType` property so we should check that this has the correct value before allowing the import to succeed.

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8841

**Comment by ewbankkit** [comment]
Verifying correct VIF type while importing `aws_dx_transit_virtual_interface`, `aws_dx_hosted_transit_virtual_interface` and `aws_dx_hosted_transit_virtual_interface_accepter` implemented in https://github.com/terraform-providers/terraform-provider-aws/pull/8522 and https://github.com/terraform-providers/terraform-provider-aws/pull/8523 respectively.

**Comment by bflad** [comment]
This has been implemented for `aws_dx_private_virtual_interface` and `aws_dx_public_virtual_interface` via #9572 and will release with version 2.40.0 of the Terraform AWS Provider, later this week.
