### ISSUE TITLE
0.12 aws_dynamodb_table "Insufficient attribute blocks" from syntax suggested by documentation

### ISSUE THREAD

**Issue by milieu** [terraform-providers/terraform-provider-aws#8861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

This has been tried on Terraform 0.12.0, 0.12.1, and 0.12.0-rc1 by installing with `tfenv`.
```
Terraform v0.12.0-rc1
+ provider.aws v2.13.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_dynamo_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "cool_table_name" {
  name         = "MyCoolTable"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "examplePartitionKey"
  range_key    = "exampleSortKey"

  # Terraform docs recommend ignoring these
  # Specifying these values will cause a permadiff
  lifecycle {
    ignore_changes = [
      "read_capacity",
      "write_capacity",
    ]
  }
  attribute = [
    {
      name = "examplePartitionKey"
      type = "S"
    },
    {
      name = "exampleSortKey"
      type = "S"
    },
    {
      name = "exampleGSISortKey"
      type = "S"
    },
  ]

  global_secondary_index {
    name = "exampleIndex"

    hash_key        = "examplePartitionKey" # partition key of the GSI
    range_key       = "exampleGSISortKey"       # sort key of the GSI
    projection_type = "ALL"
  }
  tags = {
    Environment = "dev"
  }
}
```

### Expected Behavior

Going from 0.11.14 to 0.12.x Terraform this resource should still be able to `terraform apply` without changes, according to the [documentation](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html) saying

> Notes: attribute can be lists

[Reference to doc in github](https://github.com/terraform-providers/terraform-provider-aws/blob/f329cc925d4b679a1de120a2a28bce48a14a8e2a/website/docs/r/dynamodb_table.html.markdown#L66)

Actually using the regular `attribute { key = "val" }` blocks do work.

### Actual Behavior

```
Error: Insufficient attribute blocks

  on  line 0:
  (source code not available)

At least 1 "attribute" blocks are required.


Error: Unsupported argument

  on main.tf line 19, in resource "aws_dynamodb_table" "cool_table_name":
  19:   attribute = [

An argument named "attribute" is not expected here. Did you mean to define a
block of type "attribute"?
```

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`

**Comment by bflad** [comment]
Hi @milieu 👋 Sorry for the trouble there. Indeed the documentation does need to be updated to remove the Terraform 0.11 workaround syntax of assigning a list of maps to that argument.

**Comment by bflad** [comment]
Documentation update submitted: #8878
