### ISSUE TITLE
Update aws glue documentation with new format

### ISSUE THREAD

**Issue by marceloneil** [terraform-providers/terraform-provider-aws#8877]
It seems like the examples found on https://www.terraform.io/docs/providers/aws/r/glue_catalog_table.html no longer work for terraform v0.12.1 with provider.aws v2.13.0

`columns`, `partition_keys`, `parquet.compression` and possibly more parameters need to be updated to follow the new format.

Here is an example of what this format looks like: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_glue_catalog_table_test.go#L384, found from issue #8414

**Comment by bflad** [comment]
Documentation update submitted: #8879
