### ISSUE TITLE
AWS Organizations account tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8896]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of  [AWS SDK v1.19.45](https://github.com/aws/aws-sdk-go/releases/tag/v1.19.45) AWS Organization accounts can be tagged:
> You can tag and untag accounts in your organization and view tags on an account in your organization.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8864

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_organizations_account`](https://www.terraform.io/docs/providers/aws/r/organizations_account.html)

**Comment by bflad** [comment]
Pull request submitted: #9202

**Comment by bflad** [comment]
Support for tagging with the `aws_organizations_account` resource has been merged and will release with version 2.19.0 of the Terraform AWS Provider, likely later this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
