### ISSUE TITLE
Update aws_organizations_organization to output accounts excluding master

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#8903]
Based on documentation, https://www.terraform.io/docs/providers/aws/r/organizations_organization.html you can output the list off account ids via aws_organizations_organization resources by referencing:

"${lookup(aws_organizations_organization.root.accounts[count.index], "id")}"

However, I am trying to create resources for member accounts to accept invitations from the master account and therefore the resource needs to loop through all account ids for member accounts. Is there any way you can output accounts excl master?

**Comment by bflad** [comment]
Submitted pull request to add a new `non_master_accounts` attribute: https://github.com/terraform-providers/terraform-provider-aws/pull/8926

**Comment by bflad** [comment]
Support for a new `non_master_accounts` attribute (similar to the existing `accounts` attribute) has been merged and will release with version 2.16.0 of the Terraform AWS Provider, likely later this week. 👍

**Comment by e-moshaya** [comment]
awsome thanks @bflad 👍

**Comment by bflad** [comment]
This has been released in [version 2.16.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2160-june-20-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
