### ISSUE TITLE
Possibility of renaming an DB Instance

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-aws#8904]
I have been looking at how Terraform could allow the functionality (that the AWS console allows) of renaming DB Instances.

Basically, the problem is that the ID of the resource is set as the DB Instance Identifier, therefore if that identifier changes then Terraform will ForceNew. Which is as expected. All read operations use `d.Id()` as the DB Identifier to pass to the API. 

Do you think it's even possible to implement functionality because of how `d.Id()` is used for reads or should we just not even explore the possibility? I remember when I was working at HashiCorp, I looked into this but I can't remember why I abandoned the attempt...

**Comment by bflad** [comment]
Off the top of my head, I know there are a few resources that implement `d.SetId(/* new ID */)` when an update requires a change to the resource identifier, but I'm not sure of the caveats. 😄 I do not remember seeing adverse affects and the [Go documentation for the function does not call out anything](https://godoc.org/github.com/hashicorp/terraform/helper/schema#ResourceData.SetId), but that certainly does not mean its 100% supported.

We actually do have an (old!) existing feature request for this, https://github.com/terraform-providers/terraform-provider-aws/issues/507, so my suggestion is if we are wanting to go down this route, to further track this there. I'm going to proactively close this issue in preference of that one. 👍
