### ISSUE TITLE
aws_config_config_rule InsufficientPermissionsException

### ISSUE THREAD

**Issue by simran-ssk** [terraform-providers/terraform-provider-aws#8908]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

* aws_config_config_rule

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "lambda_iamsync_role" {
  name               = "LambdaIamsyncRole"
  path               = "/service-role/"
  description        = "Role for Lambda Function Used to Sync IAM Users to DynamoDb Table"
  assume_role_policy = "${data.aws_iam_policy_document.lambda_iamsync_role.json}"
  tags               = "${module.lambda_iamsync_role_label.tags}"
}

resource "aws_iam_policy" "iamsync_lambda" {
  name   = "IamsyncLambda"
  policy = "${data.aws_iam_policy_document.iamsync_lambda.json}"
}

resource "aws_iam_policy" "iamsync_lambda_basic_execution_role" {
  name   = "IamsyncLambdaBasicExecutionRole"
  policy = "${data.aws_iam_policy_document.iamsync_lambda_basic_execution.json}"
}

resource "aws_iam_role_policy_attachment" "iamsync_lambda" {
  role       = "${aws_iam_role.lambda_iamsync_role.name}"
  policy_arn = "${aws_iam_policy.iamsync_lambda.arn}"
}

resource "aws_iam_role_policy_attachment" "iamsync_lambda_basic_execution" {
  role       = "${aws_iam_role.lambda_iamsync_role.name}"
  policy_arn = "${aws_iam_policy.iamsync_lambda.arn}"
}

resource "aws_iam_role_policy_attachment" "aws_config_rules_execution_role" {
  role       = "${aws_iam_role.lambda_iamsync_role.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSConfigRulesExecutionRole"
}

resource "aws_lambda_function" "iamsync" {
  filename                       = "../lambdas/iamsync/iamsync.zip"
  function_name                  = "iamsync"
  description                    = "Syncs IAM users with a pathprefix of /iamsync/ to corresponding dynamodb"
  role                           = "${aws_iam_role.lambda_iamsync_role.arn}"
  handler                        = "iamsync.lambda_handler"
  source_code_hash               = "${filebase64sha256("../lambdas/iamsync/iamsync.zip")}"
  runtime                        = "python3.6"
  memory_size                    = 128
  timeout                        = 30
  reserved_concurrent_executions = 50
  tags                           = "${module.lambda_iamsync_lambda_label.tags}"
}

resource "aws_config_config_rule" "iamsync_change" {
  name        = "iamsync-change"
  description = "When changes are made to an IAM group this rule triggers a lambda function that syncs users belonging to groups with a pathprefix of /iamsync/ to a dynamodb table."

  scope {
    compliance_resource_types = ["AWS::IAM::Group"]
  }

  source {
    owner             = "CUSTOM_LAMBDA"
    source_identifier = "${aws_lambda_function.iamsync.arn}"

    source_detail {
      event_source = "aws.config"
      message_type = "ConfigurationItemChangeNotification"
    }
  }

  depends_on = ["aws_lambda_function.iamsync"]

}

data "aws_iam_policy_document" "lambda_iamsync_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

data "aws_iam_policy_document" "iamsync_lambda" {
  statement {
    actions = [
      "iam:List*",
      "iam:Get*",
    ]

    resources = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:group/iamsync/*"]
  }

  statement {
    actions = [
      "dynamodb:GetItem",
      "dynamodb:UpdateItem",
      "dynamodb:DeleteItem",
      "dynamodb:Scan",
    ]

    resources = ["${aws_dynamodb_table.iamsync_dynamodb_table.arn}"]
  }
}

data "aws_iam_policy_document" "iamsync_lambda_basic_execution" {
  statement {
    actions = [
      "logs:CreateLogGroup",
    ]

    resources = ["arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:*"]
  }

  statement {
    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]

    resources = ["arn:aws:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/aws/lambda/iamsync:*"]
  }
}

```

### Debug Output

`aws_config_config_rule.iamsync_change: InsufficientPermissionsException: The AWS Lambda function arn:aws:lambda:us-west-2:XXXXXXXXXXXX:function:iamsync cannot be invoked. Check the specified function ARN, and check the function's permissions.
        status code: 400, request id: 1d992405-8938-11e9-865e-332ebdbb24d2`

### Expected Behavior

The custom aws config rule should be created but due to the InsufficientPermissions exception the resources aren't being created. 

### Actual Behavior

When I run a terraform plan and apply all of these resources get created except the aws_config_config_rule resource. After some troubleshooting I found that if I log into the console and create a arbitrary custom config rule and attach my lambda function to it, it saves as expected. Following that I then run a plan and apply against the resource I was trying to initially create and it works without error. I was able to reproduce the same behavior across 4 accounts. 

### Steps to Reproduce

1. `terraform plan -out iamsync.plan`
2. `terraform apply iamsync.plan`

**Comment by bflad** [comment]
Hi @simran-ssk 👋 Sorry you are running into trouble here and thank you for reporting this.

Does re-running `terraform apply` after a minute or two without changing anything in your Terraform configuration or doing anything in the AWS Console work? This will help us determine if the issue is some form of eventual consistency between the IAM Role permissions propagating (in which we can introduce retries in the `aws_config_config_rule` resource) or if we should dig deeper into the AWS Console automatically fixing/handling something.

**Comment by simran-ssk** [comment]
@bflad at first I thought it was an eventual consistency issue too. I gave it some time and continued to re-apply with no avail. The only thing that seems to work is assigning the lambda function to some arbitrary config rule. Following that applying works.

**Comment by bflad** [comment]
Great information, @simran-ssk, thank you. Does your configuration work if you add something like the following?

```hcl
resource "aws_lambda_permission" "iamsync-config-service" {
  statement_id  = "AllowExecutionFromConfig"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.iamsync.arn}"
  principal     = "config.amazonaws.com"
}
```

For reference, we have this acceptance testing configuration, which does currently pass our daily testing: https://github.com/terraform-providers/terraform-provider-aws/blob/9a07d07d4d87a9147b50e9427b8f2a4bf2254b74/aws/resource_aws_config_config_rule_test.go#L473-L609

**Comment by ivica-k** [comment]
Not specifying the `source_arn` indeed works.

**Comment by bflad** [comment]
Documentation pull request submitted: #9191
