### ISSUE TITLE
Aurora Serverless Scaling - TimeoutAction Parameter

### ISSUE THREAD

**Issue by araddas** [terraform-providers/terraform-provider-aws#8929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add TimeoutAction as a parameter in the scaling configuration when making an Aurora Serverless Cluster. Currently, the only way to change the TimeoutAction is through AWS CLI or the AWS Console. If the cluster is unable to find a scaling point the default action is to cancel the scaling after the timeout. This is problematic if the load is high on the cluster and can cause service disruption. One should be able to change this parameter with terraform.

### New or Affected Resource(s)

* aws_rds_cluster

### Potential Terraform Configuration
Example of what should be available:

```hcl
resource "aws_rds_cluster" "aurora_cluster" {
  engine      = "aurora"
  engine_mode = "serverless"
...
  scaling_configuration {
    auto_pause   = true
    max_capacity = "4"
    min_capacity = "1"
    seconds_until_auto_pause = 300
    timeout_action = "ForceApplyCapacityChange"
  }
}
```

### References

* [AWS - Creating an Aurora Serverless DB Cluster](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.create.html)

**Comment by bflad** [comment]
Support for the `timeout_action` argument has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected tomorrow. Thanks to @stefansundin for the implementation. 👍
