### ISSUE TITLE
aws_msk_cluster - output bootstrap_brokers returns empty

### ISSUE THREAD

**Issue by cdenneen** [terraform-providers/terraform-provider-aws#8952]
Based on example (https://www.terraform.io/docs/providers/aws/r/msk_cluster.html#) I've setup 2 outputs (one for `bootstrap_brokers` and the other for `zookeeper_connect_string`):

```
output "zookeeper_connect_string" {
    value = "${aws_msk_cluster.kafka.zookeeper_connect_string}"
}

output "bootstrap_brokers" {
    value = "${aws_msk_cluster.kafka.bootstrap_brokers}"
}
```
However only `zookeeper_connect_string` returns during cluster creation. 

```
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

bootstrap_brokers =
zookeeper_connect_string = 10.1.13.241:2181,10.1.11.98:2181,10.1.12.107:2181
```

**Comment by bflad** [comment]
Hi @cdenneen 👋 Thanks for reporting this and sorry you ran into trouble here.

A few questions for you:

* Is the `bootstrap_brokers_tls` attribute value filled in during creation?
* Does the `bootstrap_brokers` output value eventually fill in after a certain period of time?

If you are setting up client broker encryption in transit with just the `TLS` setting like the below:

```hcl
resource "aws_msk_cluster" "example" {
  # ... other configuration ...
  encryption_info {
    # ... other configuration ...
    encrypt_in_transit {
      client_broker = "TLS"
    }
  }
}
```

It is expected that the `bootstrap_brokers` value is empty, while the `bootstrap_brokers_tls` value is filled. We should certainly update our documentation for this case. 👍 Please let us know.

**Comment by cdenneen** [comment]
Ok probably should change example to output the `bootstrap_servers_tls` instead. Thanks for clarifying.

**Comment by bflad** [comment]
I have submitted the following documentation pull request, if you would like to look: #8957

**Comment by adv4000** [comment]
I have same issue 
The following output return empty string:
```
output "msk_kafka_connections" {
  value = "${aws_msk_cluster.datalake.bootstrap_brokers}"
}
```
I'am not using any TLS
Tried to output also `${aws_msk_cluster.datalake.bootstrap_brokers_tls`} got error:
`Resource 'aws_msk_cluster.datalake' does not have attribute 'bootstrap_brokers_tls'`
This is my cluster:
```
resource "aws_msk_cluster" "datalake" {
  cluster_name           = "${var.msk_cluster_name}"
  kafka_version          = "${var.kafka_version}"
  number_of_broker_nodes = "${var.number_of_broker_nodes}"
  enhanced_monitoring    = "${var.monitoring_level}"

  broker_node_group_info {
    instance_type   = "${var.instance_type}"
    ebs_volume_size = "${var.ebs_volume_size}"

    client_subnets = [
      "${data.terraform_remote_state.network.private_subnets.0}",
      "${data.terraform_remote_state.network.private_subnets.1}",
      "${data.terraform_remote_state.network.private_subnets.2}",
    ]

    security_groups = ["${aws_security_group.kafka_sg.id}"]
  }

  tags = {
    Name = "${var.msk_cluster_name}-cluster"
  }
}
```

Definitely BUG

**Comment by bflad** [comment]
Hi @adv4000 -- sorry for the frustrating situation.

Over in https://github.com/terraform-providers/terraform-provider-aws/issues/8953#issuecomment-501481700 we noticed that while the AWS MSK documentation states the default value of client-broker encryption in transit is `TLS_PLAINTEXT`, which would populate both `bootstrap_brokers` and `bootstrap_brokers_tls`, that this is not true in the `us-east-1` AWS region where it defaults to `TLS` and would only populate `bootstrap_brokers_tls`. That outcome of any MSK team feedback there will determine how we handle and document the behavior and example on the resource documentation page.

Regarding the error `does not have attribute 'bootstrap_brokers_tls'`, can you please verify that you are running Terraform AWS Provider version 2.14.0, which [contains that new attribute](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2140-june-06-2019)? Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by adv4000** [comment]
Hi @bflad 
Yes I had previous version of AWS Provider, just updated it  to 2.14 and now `terraform apply`
Show this:
`encryption_info.0.encryption_in_transit.0.client_broker: "TLS" => "TLS_PLAINTEXT" (forces new resource)`
Probably in previous version it was set to **TLS** and in 2.14 it set to **TLS_PLAINTEXT** as default.

I have recreated MKS Cluster from beginning and now output show this:
```
output "msk_kafka_connections" {
  value = "${aws_msk_cluster.datalake.bootstrap_brokers}"
}
```
Still Empty
```
output "msk_kafka_connections_tls" {
  value = "${aws_msk_cluster.datalake.bootstrap_brokers_tls}"
}
```
Show connections string with port 9094.

**Comment by adv4000** [comment]
I would recommend to make Reference only one Kafka Bootstrap, and not two References if they cannot exist together. one is always empty.

By now I will use this to output whatever is not empty:
```
output "msk_kafka_connections" {
  value = "${aws_msk_cluster.mvp.bootstrap_brokers != "" ? aws_msk_cluster.mvp.bootstrap_brokers : aws_msk_cluster.mvp.bootstrap_brokers_tls}"
}
```
