### ISSUE TITLE
feature(sagemaker notebook): Add Git Repository Support

### ISSUE THREAD

**Issue by omarsamad-plutoflume** [terraform-providers/terraform-provider-aws#8959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS SageMaker has an ability to associate git repositories with the sagemaker notebook, can this be added to Terraform please?

### Resources

aws_sagemaker_notebook_instance

### References

https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-git-repo.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-notebookinstance.html#cfn-sagemaker-notebookinstance-additionalcoderepositories

**Comment by mwarkentin** [comment]
This can only be set on create (as far as I can tell) so the only way to set this up and manage it in terraform is to add the instance manually and then import it back into terraform. This is a bit crappy.

**Comment by xmj** [comment]
@mwarkentin  Turns out you can change the setting and attach a repository when the Notebook Instance is stopped.

**Comment by presich** [comment]
What about SageMaker Git Repository entry itself? Do you maybe know if separate ticket has been created already? 
Or the scope of that ticket should be increased maybe?

**Comment by ewbankkit** [comment]
Related:

* https://github.com/terraform-providers/terraform-provider-aws/issues/13817
