### ISSUE TITLE
AWS EKS Introduction - Incorrect attribute value type

### ISSUE THREAD

**Issue by jonigl** [terraform-providers/terraform-provider-aws#8974]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.1
+ provider.aws v2.14.0
+ provider.http v1.1.1

### Affected Resource(s)

* aws_eks_cluster
* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "demo" {
  desired_capacity     = 2
  launch_configuration = "${aws_launch_configuration.demo.id}"
  max_size             = 5
  min_size             = 1
  name                 = "terraform-eks-demo"
  vpc_zone_identifier  = ["${aws_subnet.demo.*.id}"] #<--- Here it's one error

  tag {
    key                 = "Name"
    value               = "terraform-eks-demo"
    propagate_at_launch = true
  }

  tag {
    key                 = "kubernetes.io/cluster/${var.cluster-name}"
    value               = "owned"
    propagate_at_launch = true
  }
}
```

```hcl
resource "aws_eks_cluster" "demo" {
  name     = "${var.cluster-name}"
  role_arn = "${aws_iam_role.demo-cluster.arn}"

  vpc_config {
    security_group_ids = ["${aws_security_group.demo-cluster.id}"]
    subnet_ids         = ["${aws_subnet.demo.*.id}"] #<--- Here it's the other error
  }

  depends_on = [
    "aws_iam_role_policy_attachment.demo-cluster-AmazonEKSClusterPolicy",
    "aws_iam_role_policy_attachment.demo-cluster-AmazonEKSServicePolicy",
  ]
}
```

### Expected Behavior

Apply without any errors

### Actual Behavior

```
Error: Incorrect attribute value type
  on eks-cluster.tf line 80, in resource "aws_eks_cluster" "demo":
  80:     subnet_ids         = ["${aws_subnet.demo.*.id}"]
Inappropriate value for attribute "subnet_ids": element 0: string required.
```

```
Error: Incorrect attribute value type
  on eks-worker-nodes.tf line 132, in resource "aws_autoscaling_group" "demo":
 132:   vpc_zone_identifier  = ["${aws_subnet.demo.*.id}"]
Inappropriate value for attribute "vpc_zone_identifier": element 0: string
required.
```

### Steps to Reproduce

Try this example: https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started

1. `terraform apply`

### References

* https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/271

### Possible Solution
I used `flatten ()` as @marcincuber suggested in https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/271 to resolve these errors and it worked:

`flatten(["${aws_subnet.demo.*.id}"])`
`flatten(["${aws_subnet.demo.*.id}"])`

**Comment by bflad** [comment]
Related #8950

**Comment by dev-e** [comment]
Related [#401](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/401)

**Comment by bflad** [comment]
Hi folks 👋  This issue was resolved as part of work we did to begin automatically verifying all configurations against Terraform 0.12 in the `examples/` directory of the repository. Please open a new issue if there are any continuing issues. 👍
