### ISSUE TITLE
Cross-region S3 object cannot be deleted without provider alias

### ISSUE THREAD

**Issue by brodygov** [terraform-providers/terraform-provider-aws#898]
When a provider alias is used to create a cross-region S3 bucket or object, that provider alias must exist in order to delete the resource. Otherwise terraform plan is bricked with a confusing `BucketRegionError`.

### Terraform Version

```
terraform --version
Terraform v0.9.8
```

### Affected Resource(s)

- `aws_s3_bucket`
- `aws_s3_bucket_object`

This might be a single example of a more general issue with AWS providers. I'm not sure what the expected behavior should be.

### Terraform Configuration Files
```hcl
provider "aws" {
    region = "us-west-2"
}

variable "test_bucket" { }

# == comment out / delete below here to test bug

provider "aws" {
    region = "us-east-1"
    alias = "us-east-1-provider"
}

resource "aws_s3_bucket" "mybucket" {
    provider = "aws.us-east-1-provider"
    bucket = "${var.test_bucket}"
}

resource "aws_s3_bucket_object" "myobject" {
    provider   = "aws.us-east-1-provider"
    key        = "tmp-terraform-s3-bug-test"
    bucket     = "${aws_s3_bucket.mybucket.bucket}"
    content    = "test"
}
```

### Debug Output
https://gist.github.com/brodygov/4bbb39ab3399b5e974c641e5ad2e6aef

### Expected Behavior

At minimum, I would have expected terraform to fail with a more helpful message. Maybe something like:

```
aws_s3_bucket_object.myobject: Cannot refresh status because provider "us-east-1-provider" is gone
```

It's pretty surprising that terraform attempts to charge ahead even though it knows that the provider name referenced in the state file is gone.

But ideally it would have something in the state file to tell it the region for these resources so it can successfully look them up and destroy them. Or, it could follow the HTTP 301 from Amazon and re-query against the correct region. I don't know how hard either of these would be to implement.

### Actual Behavior

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_s3_bucket.mybucket: Refreshing state... (ID: my-tmp-test-deleteme)
Error refreshing state: 1 error(s) occurred:

* aws_s3_bucket.mybucket: aws_s3_bucket.mybucket: error reading S3 bucket "my-tmp-test-deleteme": BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
	status code: 301, request id: , host id: 
```

### Steps to Reproduce

1. `terraform apply` with the config to create the bucket and object (may need to run twice)
2. Comment out or delete the provider.
3. `terraform plan` — this will fail with `BucketRegionError`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/hashicorp/terraform/issues/12287
- https://github.com/terraform-providers/terraform-provider-aws/issues/394
- http://architecture.ginocoates.com/2017/01/03/s3-multi-region-issue-in-terraform/

**Comment by henrydobson** [comment]
There's another similiar scenario to consider here.

Where:
```
provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key  = "${var.aws_secret_key}"
  region         = "eu-west-2"
}

resource "aws_s3_bucket" "s3_bucket" {
  bucket = "some_bucket"
  region  = "eu-west-1"
}

resource "aws_s3_bucket_object" "object" {
  bucket  = "${aws_s3_bucket.s3_bucket.name}"
  key        = "welcome.txt"
  content = "Hello World"
}
```

The aws_s3_bucket_object fails with error:

```
BucketRegionError: incorrect region, the bucket is not in 'eu-west-2' region
```

and there is no region parameter for aws_s3_bucket_object to explicitly target the region.

**Comment by apparentlymart** [comment]
Hi @brodygov and @henrydobson! Sorry for this strange behavior, and for the delay in replying.

The root problem here is something we're familiar with from a different context: removing a module containing its own provider config. (See hashicorp/terraform#15762 for more details.)

However, this does have an interesting extra part: it seems like the `provider` override on the object is being ignored in the case where there is no provider with the given alias, and it's instead falling back on the default (un-aliased) provider.

We actually do retain enough information in state to deal with this, but I suppose it was implemented this way to make reorganization easier. Seeing this in context though I agree that this behavior is not ideal and, I think, also possibly harmful: while S3 has a global namespace and so it was able to return a specialized error here, were this almost any _other_ resource, Terraform would've sent the refresh query to the wrong region, got a "not found" error, and dropped the item from the state altogether, causing Terraform to lose track of it entirely.

This feels like a core bug to me, so I'm gonna try to sum this up in a ticket in the core repository.

**Comment by apparentlymart** [comment]
I created the issue linked above to describe this in Terraform core terms. I don't think there's any AWS-provider-specific work to be done here, so I'm going to close this one. (I captured over there that ideally the state would contain enough of the provider configuration to avoid this, but that's a trickier concern that needs more careful thought and I think it's important to fix this unsafe gotcha with more urgency than that.)
