### ISSUE TITLE
Add Cross Compiler Checks to CI

### ISSUE THREAD

**Issue by nywilken** [terraform-providers/terraform-provider-aws#8988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Update the Travis-CI configuration and project make file `GNUmakefile` with a build step that runs a cross-comipler build for Terraform supported operating systems: Linux, Darwin, Windows, FreeBSD, OpenBSD, Solaris. This check would help catch potential issues with newly updated dependencies before they are merged into master.

An attempt for this check was made on #8458, but it was closed due to the time needed to cross compile for each of the platforms. For anyone picking up this request, the base requirements are as follows:

- [ ] Can run on Travis-CI within a containerized build.
- [ ] Runs as a separate build stage [Travis Matrix Builds](https://docs.travis-ci.com/user/build-matrix/)
- [ ] Runs on PR builds only
- [ ] Total build time for all phases does not exceed 10 minutes 

### New or Affected Files(s)

* .travis.yml

### References

* #0000

**Comment by bflad** [comment]
Ran into a cross-compilation issue not caught by CI again in #14030, we can try this out with GitHub Actions (likely with `goreleaser`) and see how we do.
