### ISSUE TITLE
Amazon Guard​Duty tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of  [AWS SDK v1.20.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.20.0) Amazon Guard​Duty resources can be tagged:
> Support for tagging functionality in Create and Get operations for Detector, IP Set, Threat Intel Set, and Finding Filter resources and 3 new tagging APIs: ListTagsForResource, TagResource, and UntagResource.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8987

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_guardduty_detector`](https://www.terraform.io/docs/providers/aws/r/guardduty_detector.html)
* [`aws_guardduty_ipset`](https://www.terraform.io/docs/providers/aws/r/guardduty_ipset.html)
* [`aws_guardduty_threatintelset`](https://www.terraform.io/docs/providers/aws/r/guardduty_threatintelset.html)

**Comment by bflad** [comment]
Support for resource tagging with existing GuardDuty resources has been merged and will release with version 2.67.0 of the Terraform AWS Provider, likely tomorrow. 👍
