### ISSUE TITLE
AWS App Mesh service discovery using AWS Cloud Map

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#8997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS App Mesh now supports AWS Cloud Map as a [service discovery method](https://docs.aws.amazon.com/app-mesh/latest/userguide/getting_started.html#gs_create_virtual_node).

### New or Affected Resource(s)

* [`aws_appmesh_virtual_node`](https://www.terraform.io/docs/providers/aws/r/appmesh_virtual_node.html#service_discovery)

### References

[AWS announcement](https://aws.amazon.com/about-aws/whats-new/2019/06/aws-app-mesh-service-discovery-with-aws-cloud-map-generally-available/).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8987

**Comment by atali** [comment]
`
{
   "meshName":"simpleapp",
   "spec":{
      "backends":[
         {
            "virtualService":{
               "virtualServiceName":"serviceB.simpleapp.local"
            }
         }
      ],
      "listeners":[
         {
            "portMapping":{
               "port":8080,
               "protocol":"http"
            }
         }
      ],
      "serviceDiscovery":{
         "dns":{
            "hostname":"serviceA.simpleapp.local"
         }
      }
   }
}
`

**Comment by ewbankkit** [comment]
@atali Yes, haven't had time to think about the exact syntax but most likely will use the syntax from the API (snake case instead of camel case).

**Comment by atali** [comment]
@ewbankkit perfect, thanks a lot for your answer. 
Actually, I am trying to use ECS Fargate + AppMesh with terraform. I would like to query through CloudMap API but I am blocked without these feature. 

Do you have any workaround until the feature will be done ?
Do you have an ETA ? 

Thanks for your excellent work !

**Comment by ewbankkit** [comment]
I suggest we get https://github.com/terraform-providers/terraform-provider-aws/pull/8111 merged first.

**Comment by ewbankkit** [comment]
Testing the Cloud Map service name will require https://github.com/terraform-providers/terraform-provider-aws/issues/7016, fixed via https://github.com/terraform-providers/terraform-provider-aws/pull/7341.

**Comment by bflad** [comment]
Support for AWS Cloud Map has been merged for the `aws_appmesh_virtual_node` resource and will release with version 2.19.0 of the Terraform AWS Provider, likely later this week. 👍 Thanks, @ewbankkit!

**Comment by atali** [comment]
great job ! thanks @ewbankkit!

**Comment by bflad** [comment]
This has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
