### ISSUE TITLE
aws_s3_bucket import automatically imports bucket policy

### ISSUE THREAD

**Issue by danielpops** [terraform-providers/terraform-provider-aws#9001]
When doing `terraform import` for `aws_s3_bucket`, terraform will automatically import the bucket policy into a `aws_s3_bucket_policy` resource with the same name, as show in this `terraform import` output =>

```
$ terraform import aws_s3_bucket.THE_BUCKET THE_BUCKET
/Users/dpopes/terraform-0.11/bin/terraform import aws_s3_bucket.THE_BUCKET THE_BUCKET
aws_s3_bucket.THE_BUCKET: Importing from ID "THE_BUCKET"...
aws_s3_bucket.THE_BUCKET: Import complete!
  Imported aws_s3_bucket (ID: THE_BUCKET)
  Imported aws_s3_bucket_policy (ID: THE_BUCKET)
aws_s3_bucket_policy.THE_BUCKET: Refreshing state... (ID: THE_BUCKET)
aws_s3_bucket.THE_BUCKET: Refreshing state... (ID: THE_BUCKET)

Import successful!
```

This behavior is actually probably desirable, it's just not documented, so it was unexpected and I spent a bunch of time trying to understand why my `terraform plan` output did not look correct. The current behavior relies on you defining both `aws_s3_bucket` and `aws_s3_bucket_policy` with the same name, but that' snot clearly called out as a requirement anywhere.

The fix for this should be a documentation update.

**Comment by bflad** [comment]
The automatic `aws_s3_bucket_policy` resource import during `aws_s3_bucket` resource import has been merged and will release with version 3.0.0 of the Terraform AWS Provider, likely in two weeks. Please follow the [v3.0.0 milestone](https://github.com/terraform-providers/terraform-provider-aws/milestone/70) for tracking the progress of that release. You can use the [`aws_s3_bucket_policy` resource import support](https://www.terraform.io/docs/providers/aws/r/s3_bucket_policy.html#import) to import that resource directly after the provider upgrade, similar to all other Terraform resources that support import. 👍
