### ISSUE TITLE
aws_autoscaling_group.test: Resource 'aws_launch_template.test' not found for variable 'aws_launch_template.test.id'

### ISSUE THREAD

**Issue by imriss** [terraform-providers/terraform-provider-aws#9020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.15.0
+ provider.http v1.1.1

### Affected Resource(s)

* aws_autoscaling_group
* aws_launch_template

### Terraform Configuration Files

```hcl
resource "aws_launch_template" "test" {
  network_interfaces {
    associate_public_ip_address = true
  }
  iam_instance_profile        = ["${aws_iam_instance_profile.test-node.name}"]
  image_id                    = "${data.aws_ami.worker.id}"
  instance_type               = "m5.large"
  key_name                    = "mykey"
  name_prefix                 = "terraform-test"
  vpc_security_group_ids      = ["${aws_security_group.test-node.id}"]
  user_data                   = "${base64encode(local.test-node-userdata)}"
  lifecycle {
    create_before_destroy = true
  }
}


resource "aws_autoscaling_group" "test" {
  desired_capacity     = 2
  max_size             = 4
  min_size             = 1

  mixed_instances_policy {
    instances_distribution {
      on_demand_percentage_above_base_capacity = 50
      spot_instance_pools = 2
    }

    launch_template {
      launch_template_specification {
        launch_template_id = "${aws_launch_template.test.id}"
        version            = "$$Latest"
      }
      override {
        instance_type = "m5.large"
      }
      override {
        instance_type = "m5a.large"
      }
    }
  }

  name                 = "terraform-test"
  vpc_zone_identifier  = ["${aws_subnet.test.*.id}"]
}
```

### Expected Behavior

To have the ASG provisioned.

### Actual Behavior

`aws_autoscaling_group.test: Resource 'aws_launch_template.test' not found for variable 'aws_launch_template.test.id'`

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/5735

**Comment by imriss** [comment]
After commenting out the `aws_autoscaling_group` resource, the error message changed to:
```
aws_launch_template.test: iam_instance_profile.0: expected object, got string
```

**Comment by imriss** [comment]
Based on [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/5735#issuecomment-422812091) and [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/5735#issuecomment-502750910), it was fixed when I changed the `iam_instance_profile` to this:
```
  iam_instance_profile  {
    name = "${aws_iam_instance_profile.test-node.name}"
  }
```

**Comment by nywilken** [comment]
Hi @imriss sorry that you ran into trouble provisioning the ASG, but I'm glad you were able to resolve that issue after looking at other related issues. By any chance did you try looking at the [resource documentation](https://www.terraform.io/docs/providers/aws/r/launch_template.html#instance-profile) to help resolve this issue? 

I'm trying to understand if and how we can better the documentation to help with similar issues. I'm going to close this issue as it is a configuration issue, but please feel free to add comments.

**Comment by imriss** [comment]
Hi @nywilken , thanks, and I agree about the resource documentation. However, the main reason to open the issue at the first place was the `Resource ... not found` error message, and I then thought that it could be because of an issue related to resource dependencies. From now, I know that that error message is most probably a sign of a mistake in the resource definition. Thanks
