### ISSUE TITLE
Update aws_ssm_maintenance_window to support optional description

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#9035]
aws_ssm_maintenance_window needs updating to support optional description argument.

![Screenshot 2019-06-18 at 10 33 15](https://user-images.githubusercontent.com/44640934/59670899-9d420080-91b4-11e9-9d9d-b1d0ebf94b4f.png)

**Comment by onedumslack** [comment]
Please support the optional description field.  Currently we have to use a workaround using null resource to execute api call to add the description using a random uuid to make sure it always gets updated.

**Comment by bflad** [comment]
Support for the `description` argument of the `aws_ssm_maintenance_window` resource has been merged and will release with version 2.47.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
