### ISSUE TITLE
aws_db_instance identifier is Truncated to 16 Characters When Using identifier_prefix w/ SQL Server

### ISSUE THREAD

**Issue by thefringeninja** [terraform-providers/terraform-provider-aws#9037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.11

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "database" {
  identifier_prefix         = "contosotest-123"
  instance_class            = "db.t2.medium"
  storage_type              = "gp2"
  allocated_storage         = "128"
  username                  = "user"
  password                  = "password"
  db_subnet_group_name      = "${var.subnet_group}"
  vpc_security_group_ids    = ["${var.security_groups}"]
  engine                    = "sqlserver-se"
  license_model             = "license-included"
  engine_version            = "13"
  apply_immediately         = false
  option_group_name         = "${aws_db_option_group.database.name}"

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

terraform should have provisioned an RDS instance with an identifier up to 63 characters.

### Actual Behavior

The RDS instance identifier was truncated to 16 characters.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

provider.aws version: 2.15

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html

When you look at the UI for RDS it does in fact say the database name is limited to 15 characters, however it will still let you input many many more.

**Comment by pvanbuijtene** [comment]
@aeschright is there anything which can be done to get this merged?
