### ISSUE TITLE
aws_iam_access_key status of Inactive not applied on creation

### ISSUE THREAD

**Issue by kyle-okeeffe** [terraform-providers/terraform-provider-aws#9057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When creating an access key using the aws_iam_access_key with an initial status of Inactive, the access key is created and set to Active. If the terraform is then run again, it will successfully change the status from Active to Inactive.

### Terraform Version

Terraform v0.12.2

### Affected Resource(s)

* aws_iam_access_key

### Terraform Configuration Files

```hcl
resource "aws_iam_access_key" "access_key" {
  user    = "${var.user}"
  pgp_key = "${var.pgp_key}"
  status  = "${var.status}"
}
```

### Debug Output

[https://gist.github.com/kyle-okeeffe/e3cb45def847203686cc186d0582c3e4](https://gist.github.com/kyle-okeeffe/e3cb45def847203686cc186d0582c3e4)

### Expected Behavior

An access key will be created, and the status will be set to Inactive.

### Actual Behavior

An access key is created, and the status is set to Active.

### Steps to Reproduce

1. Apply a new access key to a user with the initial status set to inactive

**Comment by kingpong** [comment]
This bug is dangerous because it leaves an active API key that the plan showed would be Inactive after creation, and there is no obvious Terraform failure to alert the user that there was this was not done.

Creating a key that is deactivated immediately is a realistic scenario when using Terraform to manage secret rotation.
