### ISSUE TITLE
Add capability to enable/configure the Cloudwatch Log to Directory Service

### ISSUE THREAD

**Issue by shard923** [terraform-providers/terraform-provider-aws#9069]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Directory Service has an option to enable "Log Forwarding" for the directory to Cloudwatch logs. I propose the resource provider add capability to enable and configure this setting.

### New or Affected Resource(s)

* #0000

**Comment by bflad** [comment]
The support for this functionality, the new `aws_directory_service_log_subscription` resource, has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
