### ISSUE TITLE
Expose resource ARN for AWS API Gateway Stage

### ISSUE THREAD

**Issue by chendilv** [terraform-providers/terraform-provider-aws#9071]
### Current Terraform Version
```
Terraform v0.12.2
```

### Use-cases
A WAF WebACL can be associated with an API Gateway Stage. This is supported by terraform already : https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl_association.html
However, terraform does not provide a way to access the resource arn for a API Gateway Stage : https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html

(The execution Arn is something different - the API Gateway Stage Arn will have the format arn:aws:apigateway:{region}::/restapis/{api_id}/stages/{stage_name})

So there is no (clean) way to provide a API Gateway stage resource arn to a WebACL association.

### Proposal
Add an attribute called 'arn' to aws_api_gateway_stage that exposes the resource arn of the API Gateway stage.

### References
Closest related GitHub issue : https://github.com/terraform-providers/terraform-provider-aws/issues/6441

Related Terraform docs :
https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl_association.html
https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html

**Comment by CumpsD** [comment]
This would make it a lot easier indeed. I just stumbled on this in trying to figure out how to build the stage arn for WAF

**Comment by idledk** [comment]
We really need this. It makes much easier when applying a WAF to an API gateway, not having to generate the ARN for the API

**Comment by bflad** [comment]
The `arn` attribute will be added as part of #10570

**Comment by bflad** [comment]
Support for the `arn` attribute has been merged and will release with version 2.36.0 of the Terraform AWS Provider, Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
