### ISSUE TITLE
SES receipt rule set not re-created if deleted from console

### ISSUE THREAD

**Issue by codeaholics** [terraform-providers/terraform-provider-aws#9086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.2
+ provider.aws v2.16.0
```

### Affected Resource(s)

* `aws_ses_receipt_rule_set`
* _maybe_ `aws_ses_receipt_rule`

### Terraform Configuration Files

```hcl
provider "aws" {}

resource "aws_ses_receipt_rule_set" "rule_set" {
  rule_set_name = "default-rule-set"
}

resource "aws_ses_receipt_rule" "rule" {
  name          = "all"
  rule_set_name = aws_ses_receipt_rule_set.rule_set.rule_set_name
  recipients    = ["example@example.com"]
  enabled       = true
  scan_enabled  = false

  stop_action {
    scope       = "RuleSet"
    position    = 1
  }
}

resource "aws_ses_active_receipt_rule_set" "active_rule_set" {
  rule_set_name = aws_ses_receipt_rule_set.rule_set.rule_set_name
}
```

### Debug Output

https://gist.github.com/codeaholics/7b0b2d7e9cacae9c6c0ffb5780118b15

### Panic Output

n/a

### Expected Behavior

When deleting a Terraform managed resource directly from the console, I expect it to be recreated. 

### Actual Behavior

Deleting a Terraform managed SES Rule Set results in `Error: RuleSetDoesNotExist: Rule set does not exist: default-rule-set` when subsequently trying to `apply` or `plan`.

### Steps to Reproduce

1. Start with no SES receipt resources (i.e. rulesets) in your AWS account
2. `terraform apply`
3. Go to AWS console and delete newly created SES resources
4. `terraform plan`

### Important Factoids

n/a

### References

n/a

**Comment by anGie44** [comment]
The fix for this has been merged and will release with `v2.64.0` of the Terraform AWS Provider, expected in this week's release.
