### ISSUE TITLE
aws_ssm_parameter: add "version" as output

### ISSUE THREAD

**Issue by itsSaad** [terraform-providers/terraform-provider-aws#9104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to use the version of the newly created `aws_ssm_parameter` to be able to pass to the application stack to use the right version of the parameter for the deployment.

### New or Affected Resource(s)

* aws_ssm_parameter

**Comment by bflad** [comment]
A new `version` attribute has been merged for the `aws_ssm_parameter` data source and resource, which will release in version 2.17.0 of the Terraform AWS Provider, likely later today. Thanks, @stack72!

**Comment by bflad** [comment]
This has been released in [version 2.17.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2170-june-28-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
