### ISSUE TITLE
Bad request response during AssociateRouteTable action

### ISSUE THREAD

**Issue by segonzalez-dev** [terraform-providers/terraform-provider-aws#9113]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.2
+ provider.aws v2.16.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
# EU (Stockholm)
module "project-name_eu-north-1" {
  region = "eu-north-1"
  source = "./modules/project-name"

  providers = {
    aws = "aws.eu-north-1"
  }

  // Some variable inputs omitted
  // ...
}
```

```hcl
# Extract from original file. Sensitive values has been replaced/removed.

resource "aws_vpc" "vpc" {
  cidr_block            = "10.0.0.0/28"
  enable_dns_support    = true
  enable_dns_hostnames  = true

  tags = {
    Name = "project-name"
  }
}

resource "aws_internet_gateway" "internet_gateway" {
  vpc_id = "${aws_vpc.vpc.id}"

  tags = {
    Name = "project-name"
  }
}

resource "aws_subnet" "subnet" {
  vpc_id                  = "${aws_vpc.vpc.id}"
  cidr_block              = "10.0.0.0/28"
  map_public_ip_on_launch = true

  tags = {
    Name = "project-name"
  }
}

resource "aws_route_table" "route_table" {
  vpc_id = "${aws_vpc.vpc.id}"

  tags = {
    Name = "project-name"
  }

  route {
    cidr_block  = "0.0.0.0/0"
    gateway_id  = "${aws_internet_gateway.internet_gateway.id}"
  }
}

resource "aws_route_table_association" "route_table_association" {
  subnet_id       = "${aws_subnet.subnet.id}"
  route_table_id  = "${aws_route_table.route_table.id}"
}

resource "aws_security_group" "security_group" {
  name_prefix   = "project-name-"
  vpc_id        = "${aws_vpc.vpc.id}"

  tags = {
    Name = "project-name"
  }

  # Allow connection from office
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["1.2.3.4/32"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_key_pair" "key_pair" {
  key_name_prefix   = "project-name-"
  public_key        = "${file(var.ssh_public_key)}"
}

data "aws_ami" "ami" {
  most_recent = true
  owners      = ["099720109477"]

  filter {
    name      = "name"
    values    = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
  }

  filter {
    name      = "architecture"
    values    = ["x86_64"]
  }

  filter {
    name      = "virtualization-type"
    values    = ["hvm"]
  }
}

resource "aws_instance" "instance" {
  ami                     = "${data.aws_ami.ami.id}"
  instance_type           = "t2.micro"
  subnet_id               = "${aws_subnet.subnet.id}"
  vpc_security_group_ids  = ["${aws_security_group.security_group.id}"]
  key_name                = "${aws_key_pair.key_pair.key_name}"

  tags = {
    Name = "project-name"
  }

  timeouts {
    create = "6h"
  }

  # Copying application to remote server
  provisioner "file" {
    source        = "${var.project_dir}/project-name"
    destination   = "/home/ubuntu/project-name"

    connection {
      host        = "${aws_instance.instance.public_ip}"
      type        = "ssh"
      user        = "ubuntu"
      private_key = "${file(var.ssh_private_key)}"
    }
  }
}
```

### Debug Output

https://gist.github.com/segonzalez-dev/61c38680f8ce54571f8b1bae59651d7f

### Expected Behavior

Terraform script is working on these AWS regions:

```hcl
# US East (North Virginia)
provider "aws" {
  version = "~> 2.14"
  region  = "us-east-1"
  alias   = "us-east-1"
}

# US West (Oregon)
provider "aws" {
  version = "~> 2.14"
  region  = "us-west-2"
  alias   = "us-west-2"
}

# Asia Pacific (Tokyo)
provider "aws" {
  version = "~> 2.14"
  region  = "ap-northeast-1"
  alias   = "ap-northeast-1"
}

# Canada (Central)
provider "aws" {
  version = "~> 2.14"
  region  = "ca-central-1"
  alias   = "ca-central-1"
}

# EU (Frankfurt)
provider "aws" {
  version = "~> 2.14"
  region  = "eu-central-1"
  alias   = "eu-central-1"
}

# EU (Paris)
provider "aws" {
  version = "~> 2.14"
  region  = "eu-west-3"
  alias   = "eu-west-3"
}

# South America (Sao Paulo)
provider "aws" {
  version = "~> 2.14"
  region  = "sa-east-1"
  alias   = "sa-east-1"
}

```

All AWS resources described on the above script were created successfully.

### Actual Behavior

Same script without changes is failing on these AWS regions:

```hcl
# Asia Pacific (Hong Kong)
provider "aws" {
  version = "~> 2.14"
  region  = "ap-east-1"
  alias   = "ap-east-1"
}

# Asia Pacific (Seoul)
provider "aws" {
  version = "~> 2.14"
  region  = "ap-northeast-2"
  alias   = "ap-northeast-2"
}

# EU (Stockholm)
provider "aws" {
  version = "~> 2.14"
  region  = "eu-north-1"
  alias   = "eu-north-1"
}
```

When the script reaches a step with action name of "AssociateRouteTable", it receives a HTTP response status code of 400 - Bad Request. The error message is described as "The requested configuration is currently not supported. Please check the documentation for supported configurations.".

Hong Kong region was enabled manually on the AWS account. The others were already enabled by default.

**Comment by bflad** [comment]
Hi @segonzalez-dev 👋 Thanks for writing in and sorry for the trouble.

This error message is coming from the `aws_instance` Terraform resource and being passed through from the EC2 API:

```
Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```

Terraform is just passing along the less than helpful error message from the EC2 API. The limitation here is on AWS' side as EC2 is not supporting this Instance Type in all AWS Regions. For example as of this writing, you cannot see `t2.micro` on the [EC2 Pricing page](https://aws.amazon.com/ec2/pricing/on-demand/) when you select Asia Pacific (Hong Kong).

This just came up recently in https://github.com/terraform-providers/terraform-provider-aws/issues/8868, but I'm still not sure that we should codify anything here due to the complexity or potential to mislead operators. See also: https://github.com/terraform-providers/terraform-provider-aws/issues/8868#issuecomment-499223304 and the comment below for a potential data source that might be helpful for this situation.

Regarding improving the vague error messaging, your best bet is to reach out with a feature request in an AWS Support Case or your AWS account managers if you have any. Hope this makes sense.

**Comment by segonzalez-dev** [comment]
Hello @bflad,

Thanks for your quick response. I just noticed the behavior that you are describing in US West (Oregon).

When an instance is scheduled to be created on the availability zone "us-west-2d", the error response says:

```bash
Error launching source instance: Unsupported: Your requested instance type (t2.micro) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.
```

I mitigated this issue on our side by forcing all instances to be created on availability zone A instead of picking up any random available zone. Looks like zone A's are move stable and contains most instance types in comparison with the latest AWS zone letters. If there is a region that doesn't have "t2.micro" instance type, this time our continuous integration pipeline would catch it quickly.

**Comment by bflad** [comment]
The `usw2-az4` zone ID (`us-west-2d` in AWS accounts existing prior to this year) issue has been a huge pain for our acceptance testing. To slightly mitigate the issue, while allowing multiple AZ selection still, we opted to add blacklisting support to the `aws_availability_zones` data source as well: https://github.com/terraform-providers/terraform-provider-aws/pull/8463

e.g.

```hcl
data "aws_availability_zones" "available" {
  blacklisted_zone_ids = ["usw2-az4"]
  state                = "available"
}
```

You may find this helpful in your configurations as well. That said, its unfortunate that EC2 API has the better error messaging there, but not in the case of an entire region not supporting an instance type.
