### ISSUE TITLE
ad_domain_join_user causing aws_emr_cluster cluster to be recreated when there are no changes

### ISSUE THREAD

**Issue by ruortega** [terraform-providers/terraform-provider-aws#9129]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.14
+ provider.aws v2.16.0
+ provider.template v2.1.2
```

### Affected Resource(s)
* aws_emr_cluster

### Terraform Configuration Files
```terraform
resource "aws_emr_cluster" "my_aws_emr_cluster" {

  kerberos_attributes {
    ad_domain_join_password = "${data.aws_ssm_parameter.ad_domain_join_password.value}"
    ad_domain_join_user = "${data.aws_ssm_parameter.ad_domain_join_user.value}"
    cross_realm_trust_principal_password = "${data.aws_ssm_parameter.cross_realm_trust_principal_password.value}"
    kdc_admin_password = "${data.aws_ssm_parameter.kdc_admin_password.value}"
    realm = "${upper(data.aws_ssm_parameter.realm.value)}"
  }

}

```

### Expected Behavior
No cluster recreation.

### Actual Behavior
ad_domain_join_user forces cluster recreation

```
kerberos_attributes.#:                                      "1" => "1"
kerberos_attributes.0.ad_domain_join_password:              <sensitive> => <sensitive> (attribute changed)
kerberos_attributes.0.ad_domain_join_user:                  "********" => "my_ad_domain_join_user" (forces new resource)
kerberos_attributes.0.cross_realm_trust_principal_password: <sensitive> => <sensitive> (attribute changed)
kerberos_attributes.0.kdc_admin_password:                   <sensitive> => <sensitive> (attribute changed)
kerberos_attributes.0.realm:                                "my.realm" => "my.realm"

```

### Steps to Reproduce
1. `terraform plan/apply`

### References

**Comment by farmerbean** [comment]
hey @bflad - remember when I took a selfie with ye at reinforce and you pinky-sweared you'd take a look at this for us, please?! ;)

**Comment by bflad** [comment]
Hi folks 👋 Sorry for the trouble here.

Until this issue gets sorted out in the resource itself, its likely easiest to tell Terraform to ignore changes to these attributes (until you would like to actually update them), which can be accomplished using the [`lifecycle` configuration block `ignore_changes` argument](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) that is available to any Terraform resource:

```hcl
resource "aws_emr_cluster" "example" {
  # ... other configuration ...

  lifecycle {
    ignore_changes = ["kerberos_attributes"]
  }
}
```

As for fixing the resource, I would imagine we will need to either automatically ignore the literal `"********"` string as a difference if that is what is coming back from the API or passthrough the operator provided configuration value and never attempt to refresh it from the API.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to this comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by bflad** [comment]
Looks like there's a potential fix for this already here: #8559

Given this looks right at first glance, I think we will pull this in for release in version 2.18.0 of the Terraform AWS Provider this week and ensure the documentation notes that Terraform cannot provide drift detection for these arguments.

**Comment by bflad** [comment]
The potential fix for this has been merged and will release with version 2.18.0 of the Terraform AWS Provider, likely later this week. 👍

**Comment by bflad** [comment]
This has been released in [version 2.18.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2180-july-05-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!

**Comment by ruortega** [comment]
Thanks @bflad, we have upgraded the provider to 2.18 but we are still seeing the same issue:

```
Terraform v0.11.14
+ provider.aws: version = "~> 2.18"
+ provider.template: version = "~> 2.1"

kerberos_attributes.#:                                      "1" => "1"
kerberos_attributes.0.ad_domain_join_password:              <sensitive> => <sensitive> (attribute changed)
kerberos_attributes.0.ad_domain_join_user:                  "********" => "my_ad_domain_join_user" (forces new resource)
kerberos_attributes.0.cross_realm_trust_principal_password: <sensitive> => <sensitive> (attribute changed)
kerberos_attributes.0.kdc_admin_password:                   <sensitive> => <sensitive> (attribute changed)
```
The EMR cluster was deployed using 2.17, not sure if that has any impact on #8559 fix.
We will recreate the EMR cluster when possible, using 2.18 and see how it goes.

**Comment by bflad** [comment]
There's a good chance that if the Terraform state was already refreshed with the value `********`, then we will also need to automatically ignore the difference between that specific state value and any new value so it doesn't try to force recreation. The only problem with implementing that particular "fix" is then its only possible to trigger resource recreation via `terraform taint` on the resource if that argument is the only change for the resource.

The `ignore_changes` workaround [noted above](https://github.com/terraform-providers/terraform-provider-aws/issues/9129#issuecomment-507263499) is the only way I can think to workaround this behavior for resources with that `********` value already saved.
