### ISSUE TITLE
root_block_device is not expected here

### ISSUE THREAD

**Issue by grdnrio** [terraform-providers/terraform-provider-aws#9130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.3
+ provider.aws v2.16.0
+ provider.null v2.1.0
```

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "master" {
  
  tags = {
    Name = "master-c${count.index + 1}"
  }
  
  count = "${length(var.clusters)}"

  connection {
    user = "ubuntu"
    private_key = "${file(var.private_key_path)}"
  }

  associate_public_ip_address = true
  private_ip = "10.0.1.${count.index + 1}0"

  instance_type = "t2.medium"

  ami = "${data.aws_ami.default.id}"

  key_name = "${var.key_name}"

  vpc_security_group_ids = ["${module.aws_networking.security_group}"]
  subnet_id = "${module.aws_networking.subnet}"

  root_block_device = {
    volume_type = "gp2"
    volume_size = "20"
  }

...
```

### Debug Output

https://gist.github.com/grdnrio/fbf70e0e93a6c08932032811d47fc63f

### Expected Behavior

Expected an instance with a root block device

### Actual Behavior

Got this error:

```
Error: Unsupported argument

  on main.tf line 80, in resource "aws_instance" "master":
  80:   root_block_device = {

An argument named "root_block_device" is not expected here. Did you mean to
define a block of type "root_block_device"?
```

### Steps to Reproduce

1. Create a simple aws_instance with a `root_block_device`
2. `terraform apply`

### References

* #8855 - same issue here but I have always had it as a nested config block

**Comment by bflad** [comment]
Hi @grdnrio 👋 

In Terraform 0.12, the configuration language parser is stricter about the distinction between arguments and configuration blocks. This error:

```
An argument named "XXX" is not expected here. Did you mean to
define a block of type "XXX"?
```

Generally means the `=` (equals sign) needs to be removed from an argument assignment so it parses correctly as a configuration block, e.g.

```
root_block_device {
```

This distinction in HCL syntax may seem trivial, but under the hood this stricter type checking allowed for consistency with JSON syntax. More information about this change can be found in the [Terraform 0.12 Upgrade Guide](https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks). Speaking of which, in that guide it does point to the helpful [`terraform 0.12upgrade` command](https://www.terraform.io/docs/commands/0.12upgrade.html), which should automatically fix issues like these across your Terraform configurations when upgrading from Terraform 0.11. 👍 

Hope this helps!
