### ISSUE TITLE
VPC Traffic Mirroring

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

VPC Traffic Mirroring launched today.
~[AWS SDK v1.20.8](https://github.com/aws/aws-sdk-go/releases/tag/v1.20.8) not yet released so exact API details not available.~

### New or Affected Resource(s)

* aws_vpc_traffic_mirror_filter
* aws_vpc_traffic_mirror_filter_rule
* aws_vpc_traffic_mirror_session
* aws_vpc_traffic_mirror_target

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2019/06/announcing-amazon-vpc-traffic-mirroring-for-amazon-ec2-instances/)
* [Blog post](https://aws.amazon.com/blogs/aws/new-vpc-traffic-mirroring/)
* [`CreateTrafficMirrorFilter`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTrafficMirrorFilter.html)
* [`CreateTrafficMirrorFilterRule`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTrafficMirrorFilterRule.html)
* [`CreateTrafficMirrorSession`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTrafficMirrorSession.html)
* [`CreateTrafficMirrorTarget`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTrafficMirrorTarget.html)

**Comment by ewbankkit** [comment]
Requires https://github.com/terraform-providers/terraform-provider-aws/pull/9141.

**Comment by tkoeck** [comment]
Any news on supporting the new AWS traffic mirror resources?

**Comment by skalragg** [comment]
any update on the on these traffic mirror resources?

**Comment by bflad** [comment]
Support for the four new EC2 Traffic Mirror resources has been merged:

- **New Resource:** `aws_ec2_traffic_mirror_filter`
- **New Resource:** `aws_ec2_traffic_mirror_filter_rule`
- **New Resource:** `aws_ec2_traffic_mirror_filter_session`
- **New Resource:** `aws_ec2_traffic_mirror_filter_target`

These will release with version 2.51.0 of the Terraform AWS Provider, end of next week. Shout out to @johnthedev97 for the implementation. 👍
