### ISSUE TITLE
Allow for Custom User Agent Info

### ISSUE THREAD

**Issue by hasheddan** [terraform-providers/terraform-provider-aws#9149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS client is currently configured to send information in API requests via the UserAgent field including Terraform version and HashiCorp indentification. I propose allowing for users to provide additional configuration information, such as a deployment agent and job ID if they are using Jenkins or similar products.

I would be happy to do the work required to implement this feature.

### New or Affected Resource(s)

This change will not affect the functionality of any AWS resource types.

### References

The User Agent field is currently being configured in [config.go](https://github.com/terraform-providers/terraform-provider-aws/blob/1bb0dead12829bf6c9da9e3170f52a8f24984497/aws/config.go#L322)

**Comment by skorfmann** [comment]
I found [TF_APPEND_USER_AGENT](https://github.com/hashicorp/terraform/blob/a933b44bc56d94444b29577f167f949a24f30ac5/httpclient/useragent.go#L14) in Terraform itself, and was somehow expecting that this would be reflected in providers as well. But according to `TRACE` logging output it's not.

Would be nice if appending to the user-agent via config or ENV was possible somehow. Could be very useful for https://github.com/hashicorp/terraform-cdk and similar tooling.

**Comment by paultyng** [comment]
`TF_APPEND_USER_AGENT` is the way to modify user agents. Many other providers do respect it (it varies per provider, as each uses a different SDK and may or may not use an http.Client in a way thats easily extensible). Its integrated in to the Terraform Provider SDK to append it to a consistent User-Agent value you can send in headers.

Unfortunately the AWS SDK does not just take a User-Agent string, but requires a more specific construction, so the implementation will need to do a bit more work and parse the string, etc.

This is planned to follow the 3.0 release.

**Comment by skorfmann** [comment]
Cool, thanks for elaborating on this 👍

**Comment by bflad** [comment]
Support for this functionality (using the `TF_APPEND_USER_AGENT` environment variable) has been merged in both the Terraform S3 Backend and Terraform AWS Provider, releasing in version 0.13.1 and version 3.3.0 respectively. 👍
