### ISSUE TITLE
Terraform 0.10.7 not working with Terraform init 

### ISSUE THREAD

**Issue by keerthi-penmatsa** [terraform-providers/terraform-provider-aws#9170]
Terraform Version
Terraform v0.10.7

Affected Resource(s)
providers
modules
core

Terraform Configuration Files
terraform {
backend "s3" {
bucket = xxx-ate"
key = "xxx-yyy.tfstate"
workspace_key_prefix = "xx/yy"
dynamodb_table = "xx-lock"
region = "us-east-1"
}
}

Expected Behavior
Expected to see a full run happen aActual Behavior
Fails to initialize terraform (both plugins and modules)

Error:
Provider "provider" not available for installation.

A provider named "provider" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
terraform.d/plugins/linux_386

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

Provider "module" not available for installation.

A provider named "module" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
terraform.d/plugins/linux_386

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

Steps to Reproduce
terraform init

References
N/A

**Comment by ryndaniels** [comment]
Hi @keerthi-penmatsa! Thanks for taking the time to submit this issue. Unfortunately we’re unable to reproduce the reported behavior. The ticket will be closed for now, but if you are still running into this and would like to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
