### ISSUE TITLE
AWS Direct Connect resources: Add support for tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for tagging AWS Direct Connect resources on creation added in [AWS SDK v1.20.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.20.11):

> Tags will now be included in the API responses of all supported resources (Virtual interfaces, Connections, Interconnects and LAGs). You can also add tags while creating these resources.

### New or Affected Resource(s)

* [ ] `aws_dx_connection` - https://github.com/terraform-providers/terraform-provider-aws/pull/11330
* [x] `aws_dx_hosted_private_virtual_interface_accepter` - https://github.com/terraform-providers/terraform-provider-aws/pull/9572
* [x] `aws_dx_hosted_public_virtual_interface_accepter` - https://github.com/terraform-providers/terraform-provider-aws/pull/9572
* [x] [`aws_dx_hosted_transit_virtual_interface_accepter`](https://github.com/terraform-providers/terraform-provider-aws/pull/8523)
* [ ] `aws_dx_lag` - https://github.com/terraform-providers/terraform-provider-aws/pull/11330
* [x] `aws_dx_private_virtual_interface` - https://github.com/terraform-providers/terraform-provider-aws/pull/9572
* [x] `aws_dx_public_virtual_interface` - https://github.com/terraform-providers/terraform-provider-aws/pull/9572
* [x] [`aws_dx_transit_virtual_interface`](https://github.com/terraform-providers/terraform-provider-aws/pull/8522)

### References

Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/2989
* https://github.com/terraform-providers/terraform-provider-aws/issues/8490

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9153

**Comment by ewbankkit** [comment]
[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/07/aws-direct-connect-now-supports-resource-based-authorization-tag-based-authorization-tag-on-resource-creation/).

**Comment by ewbankkit** [comment]
Tag-on-create support for `aws_dx_transit_virtual_interface` and `aws_dx_hosted_transit_virtual_interface_accepter` implemented in https://github.com/terraform-providers/terraform-provider-aws/pull/8522 and https://github.com/terraform-providers/terraform-provider-aws/pull/8523 respectively.

**Comment by ewbankkit** [comment]
This will allow us to replace calls to _resourceAwsDxXXXUpdate_ from _resourceAwsDxXXXCreate_ with calls to _resourceAwsDxXXXRead_, the [preferred pattern](https://github.com/terraform-providers/terraform-provider-aws/blob/669f05c011f9dde3bfcd8315151e8e943035a7f1/.github/CONTRIBUTING.md#common-review-items).

**Comment by bflad** [comment]
The final resources here, `aws_dx_connection` and `aws_dx_lag` have been updated with this support and will release with version 2.43.0 of the Terraform AWS Provider, tomorrow. Thanks @ewbankkit!
