### ISSUE TITLE
Data Lambda Invocation result_map doesn't support all primitive types

### ISSUE THREAD

**Issue by CKost** [terraform-providers/terraform-provider-aws#9184]
Per the documentation for data type "aws_lambda_invocation" the `result_map` output is defined as:

> result_map - This field is set only if result is a map of primitive types.
 
However, the output is only set if the result is a key/value map of strings.  This can be seen in the code here:
[here](https://github.com/terraform-providers/terraform-provider-aws/blob/20151d7b332763952f44209e7356ebb661d9add0/aws/data_source_aws_lambda_invocation.go#L48)
`"result_map": {
				Type:     schema.TypeMap,
				Computed: true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},`

I would like to see this updated to support maps of all primitive types such as boolean/int value as values in the returned map.

**Comment by bflad** [comment]
In Terraform 0.12, its likely that we can deprecate the `result_map` attribute as the built-in [`jsondecode()` function](https://www.terraform.io/docs/configuration/functions/jsondecode.html) should be able to properly decode the `result` string. e.g.

```hcl
data "aws_lambda_invocation" "example" {
  # ... other configuration ...
}

# Given a result string of {"key1": 123}, this should return the integer 123 in Terraform 0.12:
output "result_entry" {
  value = jsondecode(data.aws_lambda_invocation.example.result)["key1"]
}
```

I've marked this issue as a documentation update to include the above and we will likely consider the `result_map` deprecation for the next major version of the Terraform AWS Provider. Hope this helps. 👍

**Comment by bflad** [comment]
Deprecation proposal submitted: #9189 
Documentation pull request submitted: #9190

**Comment by CKost** [comment]
Thank you @bflad !  Appreciate it
