### ISSUE TITLE
Update documentation for "api_gateway_method_response"

### ISSUE THREAD

**Issue by mrballcb** [terraform-providers/terraform-provider-aws#9211]
The documentation for api_gateway_method_response needs to be updated.  (https://www.terraform.io/docs/providers/aws/r/api_gateway_method_response.html)  The name in the Example Usage for this resource is "200", but names can no longer start with a number with terraform 0.12.x.  (This used to work with 0.11.x, and using tfswitch to get back to 0.11.11, this same terraform config works fine.  I'm not sure if this is being enforced by terraform core or the aws provider to be honest, but updating the documentation fixes it in either version of terraform.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.3
+ provider.aws v2.17.0
+ provider.null v2.1.2

### Affected Resource(s)

* api_gateway_method_response (api_gateway_method_response.html.markdown)

### Terraform Configuration Files

```hcl
resource "aws_api_gateway_method_response" "200" {
  rest_api_id = "${aws_api_gateway_rest_api.MyDemoAPI.id}"
  resource_id = "${aws_api_gateway_resource.MyDemoResource.id}"
  http_method = "${aws_api_gateway_method.MyDemoMethod.http_method}"
  status_code = "200"
}
```

### Debug Output

https://gist.github.com/mrballcb/9fb358d23b2c303837f3b35461159819

### Panic Output

N/A

### Expected Behavior

Terraform 0.11.x used to allow this resource to be named "200".  Terraform 0.12.x does not allow this due to strict enforcement of "name must begin with a letter".

### Actual Behavior

`terraform plan` failed complaining about the name of this resource.

### Steps to Reproduce

1. Copy/paste the Example Usage from the documentation at https://www.terraform.io/docs/providers/aws/r/api_gateway_method_response.html
2. `terraform plan`

### Important Factoids

N/A

### References

None found

**Comment by bflad** [comment]
Hi @mrballcb 👋 Thank you for submitting this and sorry for the trouble there. I've updated this issue as a documentation update, but if you or anyone else in the community is willing to work on this, the documentation source can be found at: https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/api_gateway_method_response.html.markdown

**Comment by bflad** [comment]
In my brief searching it looks like the same problem exists in the `api_gateway_integration_response` resource documentation page (https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/api_gateway_integration_response.html.markdown) as well.

```console
$ grep -rE '(data|resource) "aws_.*" "\d' website/docs/{d,r}/*
website/docs/r/api_gateway_integration_response.html.markdown:resource "aws_api_gateway_method_response" "200" {
website/docs/r/api_gateway_method_response.html.markdown:resource "aws_api_gateway_method_response" "200" {
```
