### ISSUE TITLE
Import waf resources

### ISSUE THREAD

**Issue by nunofernandes** [terraform-providers/terraform-provider-aws#9212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At https://github.com/terraform-providers/terraform-provider-aws/issues/424 a lot of AWF related resources got supported but only one or two support importing:

https://github.com/terraform-providers/terraform-provider-aws/issues/4279 is one that is supported but a lot more aren't

### New or Affected Resource(s)

* aws_wafregional_byte_match_set
* aws_wafregional_geo_match_set
* aws_wafregional_rate_based_rule
* aws_wafregional_regex_match_set
* aws_wafregional_regex_pattern_set
* aws_wafregional_rule
* aws_wafregional_rule_group
* aws_wafregional_size_constraint_set
* aws_wafregional_sql_injection_match_set
* aws_wafregional_web_acl
* aws_wafregional_web_acl_association
* aws_wafregional_xss_match_set

**Comment by bflad** [comment]
Resource import support for the following resources:

* aws_waf_rule_group
* aws_wafregional_byte_match_set
* aws_wafregional_rule
* aws_wafregional_rule_group
* aws_wafregional_web_acl

Has been released in [version 2.19.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2190-july-11-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!

**Comment by bflad** [comment]
If anyone is interested in helping out with this feature request by contributing to the project, we have recently added a [`Adding Resource Import Support` section to the Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#adding-resource-import-support) which has information on how implement the necessary changes. 🎉

**Comment by bflad** [comment]
Hi folks 👋 As of version 2.33.0 of the Terraform AWS Provider, released a few weeks ago, these two resources now support import:

* `aws_waf_byte_match_set`
* `aws_waf_rate_based_rule`

For the rest of these below, import support was recently merged and will release with version 2.37.0 of the Terraform AWS Provider, by Thursday next week:

* `aws_waf_geo_match_set`
* `aws_waf_regex_match_set`
* `aws_waf_regex_pattern_set`
* `aws_waf_size_constraint_set`
* `aws_waf_xss_match_set`
* `aws_wafregional_web_acl_association`

Special thanks to @kterada0509 and @DrFaust92 for their help here. If you have additional requests for resource import support for other resources, please create a new feature request issue. Thanks!
