### ISSUE TITLE
AWS Elemental MediaStore container tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of  [AWS SDK v1.20.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.20.14) AWS Elemental MediaStore containers can be tagged:
> This release adds support for tagging, untagging, and listing tags for AWS Elemental MediaStore containers.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9194

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_media_store_container`](https://www.terraform.io/docs/providers/aws/r/media_store_container.html)

**Comment by bflad** [comment]
Support for tagging with the `aws_media_store_container` resource has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected tomorrow. Thanks to @kterada0509 for the implementation.
