### ISSUE TITLE
Amazon Simple Workflow Service domain tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9231]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of  [AWS SDK v1.20.15](https://github.com/aws/aws-sdk-go/releases/tag/v1.20.15) Amazon Simple Workflow Service domains can be tagged:
> This release adds APIs that allow adding and removing tags to a SWF domain, and viewing tags for a domain. It also enables adding tags when creating a domain.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9194

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_swf_domain`](https://www.terraform.io/docs/providers/aws/r/swf_domain.html)

**Comment by bflad** [comment]
Support for tagging functionality in the `aws_swf_domain` resource has been merged and will release with version 2.35.0 of the Terraform AWS Provider, tomorrow. Thanks to @DrFaust92 for the implementation. 👍
