### ISSUE TITLE
Tech debt: API Gateway connection in 'AWSClient' is named misleadingly

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The API Gateway connection member of the `AWSClient` structure is misleadingly named `apigateway` whereas all other service connections are named `<service-name>conn`:
https://github.com/terraform-providers/terraform-provider-aws/blob/5e7aec51f541cf7a598b98de3e1e49eeff5eb25d/aws/config.go#L165-L174

**Comment by ewbankkit** [comment]
I suggest renaming to `apigatewayconn`.

**Comment by bflad** [comment]
I would agree this is worth fixing for consistency. 👍I think a good definition of done (beyond fixing the relevant code locations) would be removing `endpoint` from this testing logic for the `TestAccAWSProvider_Endpoints` acceptance test:

https://github.com/terraform-providers/terraform-provider-aws/blob/5e7aec51f541cf7a598b98de3e1e49eeff5eb25d/aws/provider_test.go#L494

There are a few others that require "special" handling as noted by that testing as well (https://github.com/terraform-providers/terraform-provider-aws/blob/5e7aec51f541cf7a598b98de3e1e49eeff5eb25d/aws/provider_test.go#L458-L500), but fixing the `apigateway` field is certainly an excellent start.

**Comment by bflad** [comment]
This was done in #12372 👍
