### ISSUE TITLE
Unable to use Hong Kong (ap-east-1) region, even though it is enabled in my account

### ISSUE THREAD

**Issue by borgstrom** [terraform-providers/terraform-provider-aws#9234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.3
+ provider.aws v2.17.0

### Affected Resource(s)

* All of aws

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "~> 2.0"
  region  = "ap-east-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "HelloWorld"
  }
}
```

### Expected Behavior

Plan should show an instance being created in ap-east-1

### Actual Behavior

```
#599 ❯❯❯ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


Error: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid
	status code: 403, request id: XXXXX

  on main.tf line 1, in provider "aws":
   1: provider "aws" {

```

```
#603 ❯❯❯ aws --region ap-east-1 sts get-caller-identity
{
    "UserId": "XXXX”,
    "Account": "YYYY”,
    "Arn": "arn:aws:sts::XXXX:assumed-role/nwprod_admin_role/YYYY”
}
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

<img width="978" alt="Screen Shot 2019-07-03 at 3 59 15 PM" src="https://user-images.githubusercontent.com/1594130/60629678-89e58680-9dab-11e9-9b45-1a595f1063ec.png">

**Comment by borgstrom** [comment]
Turns out that this is actually an AWS issue and not a Terraform issue.  I assumed that running `aws --region ap-east-1 sts get-caller-identity` would use https://sts.ap-east-1.amazonaws.com, but it didn’t.

```
#609 ❯❯❯ aws --region ap-east-1 --endpoint-url https://sts.ap-east-1.amazonaws.com sts get-caller-identity

An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid
```

I have opened a ticket with AWS.

Closing this for now.

**Comment by Kumar1325** [comment]
Hi @borgstrom ,

I've executed the same command with endpoint-url as ap-east-1, it was successful 

`aws --profile mizuho-vdms --region ap-east-1 --endpoint-url https://sts.ap-east-1.amazonaws.com sts get-caller-identity
{
    "UserId": "AIDA2TCTB623NTFEQN3YG",
    "Account": "723175089544",
    "Arn": "arn:aws:iam::723175089544:user/kumar.puttakokkula@hitachivantara.com"
}
`

And I'm facing the same issue with Hong Kong region
