### ISSUE TITLE
Load balancer left behind in auto-scaling group

### ISSUE THREAD

**Issue by Tomino2112** [terraform-providers/terraform-provider-aws#925]
Hi,

We have just had major incident when auto-scaling group failed launching new instances. It was because the group was configured in the past with one ELB, which was later on removed (replaced by target groups and ALB). I am not 100% sure when we removed the ELB reference, only realized it after today's incident. 

### Terraform Version
0.9.8 (not sure)

### Affected Resource(s)
aws_autoscaling_group

### Expected Behavior
Load balancer should have been removed from auto-scaling group

### Actual Behavior
Reference to non-existing load balancer was not removed from auto-scaling group

### Steps to Reproduce
1. Create autoscaling group with ELB configured
1. Remove ELB from the autoscaling group

**Comment by catsby** [comment]
Hey @Tomino2112 – I'm sad to hear about a major incident over there, hopefully we can help sort some things out. 

Can you give us more information here? I'm having trouble following events based on your description. 

>  It was because the group was configured in the past with one ELB, which was later on removed (replaced by target groups and ALB)

Was this done with Terraform? Are you using `aws_autoscaling_attachment`? If you could provide any example configuration and steps to reproduce this, without exposing anything sensitive, we'll take a closer look. 

>  I am not 100% sure when we removed the ELB reference, only realized it after today's incident.

Was this done with Terraform? If so, was Terraform showing a diff in any `plan` runs?

> Create autoscaling group with ELB configured

Autoscaling groups don't have a direct attribute for ELBs, so I assume then you were using `aws_autoscaling_attachment`?

**Comment by Tomino2112** [comment]
@catsby I will be happy to track back when exactly stuff happened, just haven't got the time right now. 

But autoscaling groups do infact have ELB param: https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#load_balancers

**Comment by Tomino2112** [comment]
And to answer your other question, yes everything was done through terraform, at the moment we do 99% stuff to our architecture through terraform

**Comment by catsby** [comment]
> But autoscaling groups do infact have ELB param
ah yeah, my mistake, I searched the page for "ELB" 😄

**Comment by Tomino2112** [comment]
no prob :) I would appreciate if you can do some quick code check if indeed there is an obvious bug before I start digging through our history of tfstates (probably tomorrow or friday)

**Comment by catsby** [comment]
Well, `load_balancers` are an `Optional` and `Computed` attribute, so I suspect you hit [a known core bug](https://github.com/hashicorp/terraform/issues/5290), where removing the last item in a collection of optional, computed items from your configuration  is indistinguishable from that item simply being considered OK under the terms of "computed". This means that Terraform doesn't recognize that it needs to make a change, sadly.

**Comment by Tomino2112** [comment]
I suppose that could be it, I don't see us running into the same issue anytime soon, but definitely gonna keep an eye on the known bug when amending other stuff.
