### ISSUE TITLE
Import cloudwatch_event_target

### ISSUE THREAD

**Issue by nunofernandes** [terraform-providers/terraform-provider-aws#9264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for importing aws_cloudwatch_event_target.

The aws_cloudwatch_event_rule already supports import but the aws_cloudwatch_event_target doesn't.

### New or Affected Resource(s)

* aws_cloudwatch_event_target

**Comment by bflad** [comment]
If anyone is interested in helping out with this feature request by contributing to the project, we have recently added a [`Adding Resource Import Support` section to the Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#adding-resource-import-support) which has information on how implement the necessary changes. 🎉

**Comment by chaspy** [comment]
Hi, let me try 💪

**Comment by bflad** [comment]
This has been released in [version 2.21.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2210-july-25-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

For further feature requests, documentation updates, or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
