### ISSUE TITLE
aws_ebs_volume unable to handle "Name" tag

### ISSUE THREAD

**Issue by flypenguin** [terraform-providers/terraform-provider-aws#927]
I am using aws_ebs_volume to create volumes and attach "Name" tags to them. Unfortunately the resource seems completely oblivious if you remove the tag after volume creation - it will not re-add it.

That in itself would not be a problem, had terraform not removed all our volume tags in version 0.9.5 I think (I guess this bug was fixed, hopefully). But now I still cannot use TF to re-add the tags automatically, since the bug exists at least for two versions.

We are using the tags to trigger certain actions (backups, to be precise) on the volumes, so the existance of those tags is really important to us.

### Terraform Version
0.9.8 (and at least two versions before)

### Affected Resource(s)

To my knowledge, at least:
- aws_ebs_volume

### Terraform Configuration Files
```hcl
terraform {}

provider "aws" {
  region = "eu-central-1"
}

resource "aws_ebs_volume" "hashi-test" {
  availability_zone = "eu-central-1a"
  size              = "5"

  tags = {
    Name = "hashi-test"
  }
}
```

### Steps to reproduce
* run terraform with the config given above (`terraform apply`)
* remove the "Name" tag from the created volume from the AWS console or the AWS cli (tested with console)
* re-run terraform (`terraform apply`)

### Expected Behavior
* it should attempt to re-add the "Name" tag

### Actual Behavior
* it does not

### References
*maybe* related to 
* GH-884

**Comment by stack72** [comment]
Hi @flypenguin 

Can you tell me if you are using aws_instance volume tags as well?

**Comment by flypenguin** [comment]
the `volume_tags` parameter in the `aws_instance` resource? no.

and the example is completely self-contained, you can try and reproduce with this.

I use the volumes in another TF project though. originally a data source is responsible for locating the correct volume and then I attach it. I had to change that as well when TF removed all the tags and refused to re-add them.
