### ISSUE TITLE
AWS WAF tagging

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of  [AWS SDK v1.20.17](https://github.com/aws/aws-sdk-go/releases/tag/v1.20.17) AWS WAF resources can be tagged:
> Updated SDK APIs to add tags to WAF Resources: WebACL, Rule, Rulegroup and RateBasedRule. Tags can also be added during creation of these resources.

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9287

**Comment by ewbankkit** [comment]
Affected resources:
* [`aws_waf_rate_based_rule`](https://www.terraform.io/docs/providers/aws/r/waf_rate_based_rule.html)
* [`aws_waf_rule`](https://www.terraform.io/docs/providers/aws/r/waf_rule.html)
* [`aws_waf_rule_group`](https://www.terraform.io/docs/providers/aws/r/waf_rule_group.html)
* [`aws_waf_web_acl`](https://www.terraform.io/docs/providers/aws/r/waf_web_acl.html)
* [`aws_wafregional_rate_based_rule`](https://www.terraform.io/docs/providers/aws/r/wafregional_rate_based_rule.html)
* [`aws_wafregional_rule`](https://www.terraform.io/docs/providers/aws/r/wafregional_rule.html)
* [`aws_wafregional_rule_group`](https://www.terraform.io/docs/providers/aws/r/wafregional_rule_group.html)
* [`aws_wafregional_web_acl`](https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl.html)

**Comment by bflad** [comment]
Support for these is now trickling in, merged today and releasing in version 2.33.0 of the Terraform AWS Provider next week:
* `aws_waf_rule`
* `aws_waf_rule_group`
* `aws_waf_web_acl`

Thanks to @DrFaust92 for the implementation in those.

**Comment by bflad** [comment]
Tagging support for the rest of the WAF and WAF Regional resources that have it available today have been merged and will release with version 2.37.0 of the Terraform AWS Provider by Thursday next week. Thanks to @DrFaust92 for the implementation. 👍
