### ISSUE TITLE
Always destroy and recreate EC2 on AWS

### ISSUE THREAD

**Issue by wwtg99** [terraform-providers/terraform-provider-aws#9295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.3
provider.aws v2.18.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "example" {
  ami           = "ami-2757f631"
  instance_type = "t2.micro"
  subnet_id = "subnet-77033c5f"
  key_name = "ops"
  security_groups = ["sg-079d936f877d0acd3"]
  tags = {
    Name = "test2"
  }
}
```

### Panic Output

```
aws_instance.example: Refreshing state... [id=i-03be88cfbc9639588]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_instance.example must be replaced
-/+ resource "aws_instance" "example" {
...... a lot of thing to add/update/delete
}

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

When I run `terraform apply` to create this EC2, and then re-run `terraform apply` with or without any changes, it shows up that `aws_instance.example must be replaced` and plan 1 to add, 0 to change, 1 to destroy.

But if I remove the security_groups line and create the new resource, everything is OK.
Nothing will be done if I did not change the template and 1 to change if I update some tags.

**Comment by blckct** [comment]
The documentation says:

> security_groups - (Optional, EC2-Classic and default VPC only) A list of security group names (EC2-Classic) or IDs (default VPC) to associate with.

It should work correctly if you use `vpc_security_group_ids` instead.

**Comment by wwtg99** [comment]
> The documentation says:
> 
> > security_groups - (Optional, EC2-Classic and default VPC only) A list of security group names (EC2-Classic) or IDs (default VPC) to associate with.
> 
> It should work correctly if you use `vpc_security_group_ids` instead.

It works, Thanks!

**Comment by blckct** [comment]
@wwtg99 You're welcome. Please close this issue.

**Comment by bflad** [comment]
Closing this as it appears this was resolved and the documentation is already in place.

**Comment by fernandofmendes** [comment]
Use:     vpc_security_group_ids  = [var.sc_groups]
