### ISSUE TITLE
New Resource: `aws_config_organization_config_rule`

### ISSUE THREAD

**Issue by mwarkentin** [terraform-providers/terraform-provider-aws#9299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS just added support for organization level config rules - it would be nice to be able to manage programatically in terraform:

* https://aws.amazon.com/about-aws/whats-new/2019/07/aws-config-now-enables-you-to-provision-config-rules-across-all-aws-accounts-in-your-organization/
* https://docs.aws.amazon.com/config/latest/developerguide/config-rule-multi-account-deployment.html

### New or Affected Resource(s)

* `aws_config_organization_config_rule`

### Potential Terraform Configuration

There are two types of rules - managed and custom. I'm not really sure how the resource should be configured for each (or if there should be two separate resources). It looks like the request shape is different than they used for single-account config rules:

```json
{
   "ExcludedAccounts": [ "string" ],
   "OrganizationConfigRuleName": "string",
   "OrganizationCustomRuleMetadata": { 
      "Description": "string",
      "InputParameters": "string",
      "LambdaFunctionArn": "string",
      "MaximumExecutionFrequency": "string",
      "OrganizationConfigRuleTriggerTypes": [ "string" ],
      "ResourceIdScope": "string",
      "ResourceTypesScope": [ "string" ],
      "TagKeyScope": "string",
      "TagValueScope": "string"
   },
   "OrganizationManagedRuleMetadata": { 
      "Description": "string",
      "InputParameters": "string",
      "MaximumExecutionFrequency": "string",
      "ResourceIdScope": "string",
      "ResourceTypesScope": [ "string" ],
      "RuleIdentifier": "string",
      "TagKeyScope": "string",
      "TagValueScope": "string"
   }
}
```

vs original config rule:

```
{
   "ConfigRule": { 
      "ConfigRuleArn": "string",
      "ConfigRuleId": "string",
      "ConfigRuleName": "string",
      "ConfigRuleState": "string",
      "CreatedBy": "string",
      "Description": "string",
      "InputParameters": "string",
      "MaximumExecutionFrequency": "string",
      "Scope": { 
         "ComplianceResourceId": "string",
         "ComplianceResourceTypes": [ "string" ],
         "TagKey": "string",
         "TagValue": "string"
      },
      "Source": { 
         "Owner": "string",
         "SourceDetails": [ 
            { 
               "EventSource": "string",
               "MaximumExecutionFrequency": "string",
               "MessageType": "string"
            }
         ],
         "SourceIdentifier": "string"
      }
   },
   "Tags": [ 
      { 
         "Key": "string",
         "Value": "string"
      }
   ]
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/07/aws-config-now-enables-you-to-provision-config-rules-across-all-aws-accounts-in-your-organization/
* https://docs.aws.amazon.com/config/latest/developerguide/config-rule-multi-account-deployment.html

**Comment by bflad** [comment]
Hi folks 👋 The team at HashiCorp is picking this feature request up for implementation and we can provide an update about this later today or Monday. 👍

**Comment by bflad** [comment]
Pull request submitted: https://github.com/terraform-providers/terraform-provider-aws/pull/9716

**Comment by bflad** [comment]
Two new resources to manage these rules have been merged:

* **New Resource:** `aws_config_organization_custom_rule`
* **New Resource:** `aws_config_organization_managed_rule`

They will release with version 2.24.0 of the Terraform AWS Provider, later this week.
