### ISSUE TITLE
Cannot provide an empty iam_instance_profile name or ARN in aws_launch_template

### ISSUE THREAD

**Issue by vladimir-shopov-axway** [terraform-providers/terraform-provider-aws#9308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
\+ provider.aws v2.18.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

The idea behind this code is to be able to write a configurable module for launch templates with the ability to optionally provide an instance profile or not. This is obviously just an excerpt from the original module.
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_launch_template" "launch_template" {
  name = "test_launch_template"

  iam_instance_profile {
    name = "${var.iam_instance_profile_name}"
  }

}

variable "iam_instance_profile_name" {
  type    = "string"
  default = ""
}
```

### Expected Behavior

No changes should be detected by Terraform if the same code is applied more than once and there are no changes in it.

### Actual Behavior

When a subsequent plan/apply is made with the same code Terraform makes unanticipated changes to the launch template.
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_launch_template.launch_template: Refreshing state... (ID: lt-02a80ca0f6465141f)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_launch_template.launch_template
      iam_instance_profile.#: "0" => "1"
      latest_version:         "1" => "0"


Plan: 0 to add, 1 to change, 0 to destroy.
```
The same thing happens if instead of name an ARN is provided in the iam_instance_profile block in the launch template.

### Steps to Reproduce

1. initial `terraform apply`
2. subsequent`terraform apply`

**Comment by bflad** [comment]
Hi folks 👋Thanks for reporting this.

In Terraform 0.12 and later, this class of configuration language problem can now be solved via the [`dynamic` block syntax](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks). Please see the documentation for more information about this type of configuration.

Since Terraform 0.12 implements the necessary configuration language features to support this type of configuration, I'm going to close this.

**Comment by vladimir-shopov-axway** [comment]
I wouldn't want to argue with you regarding this, but the dynamic block workaround is really just a workaround. Almost all other AWS resource arguments work in a way so that when an empty value is provided as input ("" or null) this particular option of the resource is not modified by Terraform. However, this is not the case with the iam_instance_profile of the aws_launch_template resource.

I believe that this has to be fixed at the core instead of trying to trick Terraform with a workaround. I'm not sure why the pull request fixing this that was opened 3 months ago wasn't considered as a potential fix. I personally cannot state if the pull request was implementing a proper way to fix this, but I strongly believe that people contributing to this repository and asking for review are doing it with good intentions in mind.
