### ISSUE TITLE
DirectConnectClientException","message":"Association ID has an invalid format

### ISSUE THREAD

**Issue by JagdeepChahal** [terraform-providers/terraform-provider-aws#9317]
We are on Terraform version 11.14 and upgraded to AWS provider version to 2.18.
 Changes made in #8970 (2.16) were suppose to fix this but we are still getting the 'Association ID has an invalid format' error.
We are hit by (#9106) as well so we are not able to go for the workaround mentioned in #8970. Kindly look in to it, this is big blocker for us so we will really appreciate any urgent help!

error -
 2019-07-11T18:27:00.179Z [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: 2019/07/11 18:27:00 [DEBUG] [aws-sdk-go] {"__type":"DirectConnectClientException","message":"Association ID has an invalid format."}
 2019-07-11T18:27:00.179Z [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: 2019/07/11 18:27:00 [DEBUG] [aws-sdk-go] DEBUG: Validate Response directconnect/DescribeDirectConnectGatewayAssociations failed, attempt 0/25, error DirectConnectClientException: Association ID has an invalid format.
 2019-07-11T18:27:00.179Z [DEBUG] plugin.terraform-provider-aws_v2.18.0_x4: status code: 400, request id: 8315b767-a409-11e9-9816-f1d876812434
 2019/07/11 18:27:00 [ERROR] root.tf_mod_dx: eval: *terraform.EvalRefresh, err: aws_dx_gateway_association.dx_connect: error reading Direct Connect gateway association (ga-dd695e31-7713-4bbd-aa74-6cf82b330894vgw-0886ff71ad6933949): DirectConnectClientException: Association ID has an invalid format.
 status code: 400, request id: 8315b767-a409-11e9-9816-f1d876812434
 2019/07/11 18:27:00 [ERROR] root.tf_mod_dx: eval: *terraform.EvalSequence, err: aws_dx_gateway_association.dx_connect: error reading Direct Connect gateway association (ga-dd695e31-7713-4bbd-aa74-6cf82b330894vgw-0886ff71ad6933949): DirectConnectClientException: Association ID has an invalid format.
 status code: 400, request id: 8315b767-a409-11e9-9816-f1d876812434
 2019/07/11 18:27:00 [TRACE] [walkRefresh] Exiting eval tree: module.tf_mod_dx.aws_dx_gateway_association.dx_connect
 2019/07/11 18:27:00 [TRACE] dag/walk: upstream errored, not walking "module.tf_mod_dx.output.dx_connect_id"

**Comment by ewbankkit** [comment]
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/8773

**Comment by ewbankkit** [comment]
Should be fixed by https://github.com/terraform-providers/terraform-provider-aws/pull/8776,

**Comment by JagdeepChahal** [comment]
Kindly prioritize #8776.

**Comment by bflad** [comment]
This was previously released in [version 2.34.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2340-october-31-2019) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
