### ISSUE TITLE
Support Configurations Block for Instance Groups

### ISSUE THREAD

**Issue by joelthompson** [terraform-providers/terraform-provider-aws#9342]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EMR instance groups can have Configurations specific to a given instance group similar to how a cluster also has a Configurations parameter. The `aws_emr_instance_group` should support the `configurations` / `configurations_json` attribute that is already in the `aws_emr_cluster` resource. A specific use case is to have different instance groups with different [YARN node lables](https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/NodeLabel.html).

### New or Affected Resource(s)

* aws_emr_instance_group

### Potential Terraform Configuration

```hcl
resource "aws_emr_instance_group" "HighMemory" {
  cluster_id     = "${aws_emr_cluster.tf-test-cluster.id}"
  instance_count = 2
  instance_type  = "x1e.32xlarge"
  name           = "High Memory Instances"
  configurations_json =  <<EOF
  [
    {
      "Classification": "yarn-site",
      "Properties": {
        "yarn.nodemanager.node-labels.provider": "config",
        "yarn.nodemanager.node-labels.provider.configured-node-partition": "HighMemory"
      }
    }
  ]
EOF
}
```

### References

* As of EMR 5.21, you can also reconfigure a running instance group: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-configure-apps-running-cluster.html

**Comment by bflad** [comment]
Support for a new `configurations_json` argument in the `aws_emr_instance_group` resource has been merged and will release with version 2.32.0 of the Terraform AWS Provider, tomorrow. Thanks @joelthompson for the implementation. 👍
