### ISSUE TITLE
Add support for tagging of AWS Config resources

### ISSUE THREAD

**Issue by PhRosenberg** [terraform-providers/terraform-provider-aws#9353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS added tagging support for some resources (ConfigRule, ConfigurationAggregator, AggregatorAuthorization) earlier this year:
* https://aws.amazon.com/about-aws/whats-new/2019/03/aws-config-now-supports-tagging-of-aws-config-resources/

It would be nice to configure them in Terraform.

### New or Affected Resource(s)

* aws_config_aggregate_authorization
* aws_config_configuration_aggregator
* aws_config_config_rule

### Potential Terraform Configuration

```hcl
resource "aws_config_configuration_aggregator" "example" {
  name = "example"

  organization_aggregation_source {
    all_regions = true
    role_arn    = aws_iam_role.config.arn
  }
  # new code
  tags = {
    CostCenter = "12345"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/03/aws-config-now-supports-tagging-of-aws-config-resources/

**Comment by bflad** [comment]
Support for tagging with those resources has been merged and will release with version 2.22.0 of the Terraform AWS Provider, tomorrow. Thanks to @kterada0509 for the implementation. 👍
