### ISSUE TITLE
Support import for aws_lambda_permssion resource

### ISSUE THREAD

**Issue by dvishniakov** [terraform-providers/terraform-provider-aws#9357]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`aws_lambda_permssion ` resource should support import to a state file.

### New or Affected Resource(s)

* aws_lambda_permssion

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

`terraform import <tf_path> <resource_id>`

**Comment by chaspy** [comment]
Hi, @dvishniakov 👋 
As `aws_autoscaling_lifecycle_hook`, https://github.com/terraform-providers/terraform-provider-aws/pull/9336 was merged.
Probably, this issue for `aws_lambda_permssion`, right?

ref: https://github.com/terraform-providers/terraform-provider-aws/issues/9142

**Comment by chaspy** [comment]
If you want to support lambda_permission, I'm trying.
https://github.com/terraform-providers/terraform-provider-aws/pull/9369

**Comment by dvishniakov** [comment]
Hi @chaspy , that's right! Thank you for catching this
