### ISSUE TITLE
Extend LB Listener Rule Condition Support

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-aws#9360]
The `lb_listener_rule` `condition` needs to have extensions that allow not just `host-header` and `path-pattern` conditions.

It needs to be able to support:

* http-header
* http-request-method
* query-string
* source-ip

Each of these new condition types have their struct in the AWS SDK, therefore the schema will need to adapt to allow them - this will more than likely mean a state migration due to `condition` being `schema.TypeSet`

**Comment by ewbankkit** [comment]
I THINK (not 100% positive, please check PR) that this is being addressed in https://github.com/terraform-providers/terraform-provider-aws/issues/8126, https://github.com/terraform-providers/terraform-provider-aws/pull/8268.

**Comment by stack72** [comment]
Duplicate of #8126

**Comment by stack72** [comment]
Thanks for that @ewbankkit :)
