### ISSUE TITLE
Variable file as parameter to the module

### ISSUE THREAD

**Issue by udayanms** [terraform-providers/terraform-provider-aws#9375]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

It would be helpful if the variables file could be passed as a parameter to the module. I tried to pass --var-file while tf plan but it does not pass on the values to the modules. 
* #0000

**Comment by bflad** [comment]
Hi @udayanms 👋 Thank you for submitting this. From your brief description, this looks like an enhancement that would need to be implemented in Terraform Core and not the Terraform AWS Provider codebase. Terraform Core is where the `terraform` CLI commands and configuration language is implemented. Unfortunately I cannot migrate this feature request for you automatically, so you will need to submit a new issue here: https://github.com/hashicorp/terraform/issues/new/choose
