### ISSUE TITLE
Update doc on Resource: aws_batch_compute_environment

### ISSUE THREAD

**Issue by RANJITHRAJKUMAR** [terraform-providers/terraform-provider-aws#9388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14

### Affected Resource(s)

aws_batch_compute_environment

### Expected Behavior

 Need to have the following line in the aws_batch_compute_environment documentation 
 depends_on = ["aws_iam_role.aws_batch_service_role"] instead of 
 depends_on   = ["aws_iam_role_policy_attachment.aws_batch_service_role"]

### Actual Behavior

depends_on   = ["aws_iam_role_policy_attachment.aws_batch_service_role"] line is causing issues as shown below while running "terraform init"
aws_batch_compute_environment.sample: resource depends on non-existent resource 'aws_iam_role_policy_attachment.aws_batch_service_role'

### Steps to Reproduce

Check URL https://www.terraform.io/docs/providers/aws/r/batch_compute_environment.html

### Important Factoids

None

### References

https://www.terraform.io/docs/providers/aws/r/batch_compute_environment.html

**Comment by nywilken** [comment]
Hi @RANJITHRAJKUMAR have you checked for any copy/pate or typo issues within your configuration? Looking at the documentation I see the resource configuration for `aws_iam_role_policy_attachment.aws_batch_service_role` defined as 

```hcl
resource "aws_iam_role_policy_attachment" "aws_batch_service_role" {
  role       = "${aws_iam_role.aws_batch_service_role.name}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole"
}
```

Running the provided example as documented runs as expected without error.

**Comment by RANJITHRAJKUMAR** [comment]
@nywilken Thanks for your response. Its actually a typo issue. I have corrected it now and its working fine. Thanks again.
