### ISSUE TITLE
Adding an OIDC provider to a Cognito Identity Pool that has a Cognito provider removes the Cognito provider

### ISSUE THREAD

**Issue by mbudnek** [terraform-providers/terraform-provider-aws#9394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10

### Affected Resource(s)

* aws_cognito_identity_pool

### Terraform Configuration Files

```hcl
provider "aws" {}

resource "aws_cognito_user_pool" "test_user_pool" {
  name                     = "test-user-pool"
  username_attributes      = ["email"]
  auto_verified_attributes = ["email"]

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = false
    name                     = "email"
    required                 = true

    string_attribute_constraints {
      min_length = 3
      max_length = 255
    }
  }
}

resource "aws_cognito_user_pool_client" "test_user_pool_client" {
  name            = "test-user-pool-client"
  user_pool_id    = "${aws_cognito_user_pool.test_user_pool.id}"
  generate_secret = false

  explicit_auth_flows = [
    "USER_PASSWORD_AUTH",
  ]
}

resource "aws_iam_openid_connect_provider" "test_oidc_provider" {
  url = "https://myissuer.com"

  client_id_list = [
    "my_client_id",
  ]

  thumbprint_list = [
    "000102030405060708090a0b0c0d0e0f10111213",
  ]
}

resource "aws_cognito_identity_pool" "test_identity_pool" {
  identity_pool_name = "test identity pool"

  cognito_identity_providers {
    client_id     = "${aws_cognito_user_pool_client.test_user_pool_client.id}"
    provider_name = "${aws_cognito_user_pool.test_user_pool.endpoint}"
  }

  openid_connect_provider_arns = [
    "${aws_iam_openid_connect_provider.test_oidc_provider.arn}",
  ]
}
```

### Expected Behavior

The Cognito Identity Pool "test identity pool" has both the Cognito and OIDC providers enabled.

### Actual Behavior

The Cognito Identity Pool "test identity pool" only has the OIDC provider enabled.  The second apply removes the Cognito provider.

### Steps to Reproduce

1. Comment out the `openid_connect_provider_arns` attribute
1. `terraform apply`
    * Cognito provider is enabled on the identity pool
1. Uncomment the `openid_connect_provider_arns` attribute
1. `terraform apply`
    * OIDC provider is enabled on the identity pool.  Cognito is disabled.
1. `terraform apply`
    * Cognito provider is enabled on the identity pool.  OIDC is disabled.
1. Further invocations of `terraform apply` will continue to alternate which provider is enabled.

### References

* #7479 Is likely caused by the same underlying problem, but it was closed as a duplicate of #5704, which I do not think is actually related.

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.20.0 of the Terraform AWS Provider, expected tomorrow. Thanks @mbudnek for the quick implementation turnaround!
