### ISSUE TITLE
Assume role in ap-east-1 Hong Kong

### ISSUE THREAD

**Issue by dave-lew99** [terraform-providers/terraform-provider-aws#9402]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.4 (affects 0.11.13)
+ provider.aws v2.19.0

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

```hcl
# Set up our VPC and provider

provider "aws" {
  region = "ap-east-1"
  assume_role {
      role_arn = "arn:aws:iam::XXXXXXXXX:role/TestRole"
  }
}


# Define our vpc
resource "aws_vpc" "vpc_test" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  instance_tenancy = "default"

}

```

### Expected Behavior

The role is assumed and a plan is produced to create the VPC.

### Actual Behavior

Error: The role "arn:aws:iam::XXXXXXXX:role/TestRole" cannot be assumed.

  There are a number of possible causes of this - the most common are:
    * The credentials used in order to assume the role are invalid
    * The credentials do not have appropriate permission to assume the role
    * The role ARN is not valid

  on test.tf line 3, in provider "aws":
   3: provider "aws" {

### Steps to Reproduce

1. Create an EC2 instance with a role which is allowed to assume the role specified in another account. 
2. `terraform plan`

### Important Factoids

Both accounts have the any-region STS options set, although Hong Kong is only enabled in the account where the target role is located.
Assuming the role on the CLI using the normal aws method (aws sts assume-role) works fine and the region can be interacted with, in the target account.
Assuming role and exporting the credentials to the shell environment, removing the assume role section from the provider - also works fine. 
It only seems to affect it when trying to assume role from within TF when running with an EC2 instance role.

### References

* #0000

**Comment by xose** [comment]
Digging through the session assumption code, the Region is being passed to the STS client config: ([source](https://github.com/hashicorp/aws-sdk-go-base/blob/35d28ffcaaa9eac2580f9ebae3ca553fb7dfcd3f/awsauth.go#L254)), so it is trying to use the ap-east-1 STS endpoint which is not enabled on the source account.

**Comment by dave-lew99** [comment]
Based on that info, i've done some further investigation - 

Yes - it does try to connect to the regional endpoint for STS (which is not valid in the source account). However, the debug output doesn't show this and i had to tcpdump to confirm.

Using an endpoint override didn't work, but enabling the region in the source account did.

So that's a workable solution for me now, although it would have been easier to spot if the error contained the endpoint it was connecting to, or at least in the debug output.

I'm going to close this, hopefully the info above will be useful to others.
