### ISSUE TITLE
data.aws_vpcs returns a set, not list

### ISSUE THREAD

**Issue by brandnewdays** [terraform-providers/terraform-provider-aws#9420]
### Terraform Version
Terraform v0.12.4

### Affected Resource(s)

* data.aws_vpcs

### Terraform Configuration Files

```hcl
data "aws_vpcs" "test" {
  tags = {
    Name = "test-*"
  }
}

data "aws_vpc" "test" {
  count = length(data.aws_vpcs.prod.ids)
  id    = data.aws_vpcs.test.ids[count.index]
}

```

###  Output

  on test.tf line 25, in data "aws_vpc" "prod":
  25:   id    = data.aws_vpcs.test.ids[count.index]
    |----------------
    | count.index is 1
    | data.aws_vpcs.test.ids is set of string with 3 elements

This value does not have any indices.

Error: Invalid index

  on test.tf line 25, in data "aws_vpc" "prod":
  25:   id    = data.aws_vpcs.test.ids[count.index]
    |----------------
    | count.index is 2
    | data.aws_vpcs.test.ids is set of string with 3 elements

This value does not have any indices.

Error: Invalid index

  on test.tf line 25, in data "aws_vpc" "prod":
  25:   id    = data.aws_vpcs.test.ids[count.index]
    |----------------
    | count.index is 0
    | data.aws_vpcs.test.ids is set of string with 3 elements

This value does not have any indices.

### Expected Behavior

According to the docs, ids of data.aws_vpcs is a list, not a set.
 
### Actual Behavior

Acutally ids of data.aws_vpcs is a set

### Steps to Reproduce

1. `terraform apply`

### References

* https://www.terraform.io/docs/providers/aws/d/vpcs.html

**Comment by bflad** [comment]
It appears updating the syntax with this data source was handled by https://github.com/terraform-providers/terraform-provider-aws/pull/8933 so closing this out. 👍
