### ISSUE TITLE
aws_ram_principal_association doesn't expose share invitation ARN

### ISSUE THREAD

**Issue by jdeluyck** [terraform-providers/terraform-provider-aws#9432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Terraform v0.11.14
+ provider.aws v2.20.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Terraform Configuration Files

Using aws_ram_principal_association to associate an account with a resource share doesn't return a sharing invitation arn, which is required to accept the share lateron.

```
aws ram get-resource-share-invitations
{
    "resourceShareInvitations": [
        {
            "resourceShareInvitationArn": "arn:aws:ram:eu-west-1:xxx:resource-share-invitation/xx-xx-xx-xx-xx",
            "resourceShareName": "MyFancyShare",
            "resourceShareArn": "arn:aws:ram:eu-west-1:yyy:resource-share/yy-yy-yy-yy-yy",
            "senderAccountId": "xxx",
            "receiverAccountId": "zzz",
            "invitationTimestamp": 1563519942.422,
            "status": "PENDING"
        }
    ]
}
```

To accept this invitation you need to issue an ```accept_resource_share_invitation```, and this requires the resourceShareInvitationArn, which is not exposed by Terraform.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ram.html#RAM.Client.accept_resource_share_invitation

### Expected Behavior

resourceShareInvitationArn should be exposed by terraform

### Actual Behavior

only the ResourceShareARN is exposed.

### Steps to Reproduce

* #0000

**Comment by brunocous** [comment]
This would also help me out!

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/7601, https://github.com/terraform-providers/terraform-provider-aws/pull/8259

**Comment by bflad** [comment]
Hi @jdeluyck 👋 Thank you for submitting this. In version 2.24.0 of the Terraform AWS Provider, releasing tomorrow, we will have a new `aws_ram_resource_share_accepter` resource (#8259) that can accept these invitations, but does not require knowing the actual invitation ARN. It instead uses just the sending RAM Resource Share ARN.

Given that we should not need to expose the extra API call and invitation information in the existing `aws_ram_principal_association` resource, I'm going to close this for now. If for some reason you have a use case outside what is possible with the new `aws_ram_resource_share_accepter` resource, please open a new feature request and we'll take a look. Thanks again for submitting this.
