### ISSUE TITLE
aws_route should validate which type of gateway is passed

### ISSUE THREAD

**Issue by jen20** [terraform-providers/terraform-provider-aws#9445]
The `aws_route` resource has a number of `*_gateway_id` properties which are documented as reflecting the AWS API for the type of gateway to which a route is being constructed. For example, an Internet Gateway is supposed to use `gateway_id`, and a NAT gateway is supposed to use `nat_gateway_id`. In a quirk of the AWS API, you can set a NAT gateway in `gateway_id`, but it is returned in `nat_gateway_id`, leaving a perpetual diff, but a valid route being created at the provider.

A way to fix this is to validate the prefixes of the various types of gateway being passed to each option. I'll open a pull request for this shortly.

**Comment by jen20** [comment]
Just realised the behaviour here is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/158, but I'll leave this since it proposes a concrete fix to the problem.

**Comment by jeet-parekh** [comment]
Any work or discussion being done on this?
I took a look at this and #158. The solution to validate the prefixes would be a breaking change, right?
I could work on this if there's a decided solution.

**Comment by jen20** [comment]
It would be a breaking change, but one that presents at plan time and prevents a perpetual diff which is probably a net win. I'm no longer a maintainer of this repository so won't be working on this - I've updated the assignment accordingly.
