### ISSUE TITLE
Unable to Provide Volume Tag in Auto Scaling Group

### ISSUE THREAD

**Issue by kundan123456** [terraform-providers/terraform-provider-aws#9448]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.1
provider.aws v2.14.0

### Affected Resource(s)

* aws_launch_configuration
* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "as_conf" {
  name          = "web_config"
  image_id      = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"
root_block_device {
    volume_size           = "10"
    volume_type           = "gp2"
    delete_on_termination = false
  }
  ebs_block_device {
    device_name           = "/dev/sdb"
    volume_size           = "30"
    volume_type           = "gp2"
    delete_on_termination = false
    encrypted             = true
  }
}

resource "aws_autoscaling_group" "asg_instance" {
  name                      = "ASG-demo"
  launch_configuration      = "${aws_launch_configuration.as_conf.name}"
  vpc_zone_identifier       = [var.asg_subnet_id]
  max_size                  = 2
  min_size                  = 1
  desired_capacity          = 1
  health_check_type         = "EC2"
  health_check_grace_period = 1500
  tag {
    key                 = "Name"
    value               = "Ec2-ASG"
    propagate_at_launch = "true"
  }
}
```

### Expected Behavior

How can we give name tag to EBS and ROOT volume inside launch configuration definition ?
Whenever ASG spin up a new instance, it should create the EBS and ROOT volume devices with a unique name.
Tags in ASG provides name tag for EC2 instances.

### Actual Behavior
Unable to provide unique name tags for EBS and ROOT volume inisde launch configuration definition.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* #0000

**Comment by tzatwork** [comment]
My understanding is this is not an issue with terraform's provider. This is a limitation on Amazon's side with ASG launches not tagging ENI or EBS.  

There are examples of people using lambdas to do this on api call creation to solve this.

**Comment by drewinglis** [comment]
You can also supply volume tags if you use the `aws_launch_template` resource for configuring the ASG instead of `aws_launch_configuration`.

**Comment by bflad** [comment]
Hi folks 👋  As mentioned in the previous two comments, this is not available in the [Auto Scaling CreateLaunchConfiguration API](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CreateLaunchConfiguration.html), so therefore this is not something to be implemented in the Terraform AWS Provider and this limitation does not exist when using EC2 Launch Templates instead. See the [`tags_specifications` configuration block(s) of the `aws_launch_template` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#tag-specifications) for information about how to implement volume tags. 👍
