### ISSUE TITLE
r/aws_mq_broker: Add support for KMS to offer server-side encryption

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon MQ now supports the AWS Key Management Service (AWS KMS) to create and manage keys for at-rest encryption of customer data in Amazon MQ.

### New or Affected Resource(s)

* [`aws_mq_broker`](https://www.terraform.io/docs/providers/aws/r/mq_broker.html)

### Potential Terraform Configuration

```hcl
resource "aws_mq_broker" "example" {
  broker_name = "example"

  encryption_options {
    kms_key_id = "${aws_kms_key.example.id}"
    ...
  }
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-mq-adds-support-for-aws-key-management-service-improving-encryption-capabilities/).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9428

**Comment by bflad** [comment]
Support for a new `encryption_options` configuration block in the `aws_mq_broker` resource has been merged and will release with version 2.31.0 of the Terraform AWS Provider, next Thursday.
