### ISSUE TITLE
Support for DynamoDB autoscaling

### ISSUE THREAD

**Issue by lra** [terraform-providers/terraform-provider-aws#948]
See https://aws.amazon.com/blogs/aws/new-auto-scaling-for-amazon-dynamodb/

If I enable DDB autoscaling in AWS:
 - the throughputs in the tfstate constantly change. I can ignore those for `terraform apply` with `ignore_changes` but the state keep changing for no real use
- I did not find a way to declare my autoscaling of DDB in terraform, so it's something we are not tracking in TF yet. There might be a way to track all the autoscaling stuff by tracking all the generated cloudwatch alarms and all, but it's not obvious to me

**Comment by Ninir** [comment]
Hey @lra 

Thanks for opening this issue. This is already been discussed in [another thread](https://github.com/terraform-providers/terraform-provider-aws/issues/866), and being implemented too [right here](https://github.com/terraform-providers/terraform-provider-aws/pull/919).

'Will close this one to centralise the discussion.
