### ISSUE TITLE
r/aws_launch_template: Tag on create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon EC2 now supports tagging launch templates on creation.

This will allow us to remove the not-preferred call to `resourceAwsLaunchTemplateUpdate` from `resourceAwsLaunchTemplateCreate` and replace with a call to `resourceAwsLaunchTemplateRead`.

### New or Affected Resource(s)

* [`aws_launch_template`](https://www.terraform.io/docs/providers/aws/r/launch_template.html)

### Potential Terraform Configuration

n/a

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ec2-now-supports-tagging-launch-templates-on-creation/).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9489

**Comment by bflad** [comment]
Support for this has been merged and will release with version 2.35.0 of the Terraform AWS Provider, tomorrow. Thanks to @ewbankkit for the implementation. 👍
