### ISSUE TITLE
ECR repository immutable image tags

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can now configure an ECR repository to be immutable to prevent image tags from being overwritten.

### New or Affected Resource(s)

* [`aws_ecr_repository`](https://www.terraform.io/docs/providers/aws/r/ecr_repository.html)

### Potential Terraform Configuration

```hcl
resource "aws_ecr_repository" "example" {
  name = "example"

  image_tag_mutability = "IMMUTABLE"
}
```

### References

[Documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html).
[AWS container services roadmap](https://github.com/aws/containers-roadmap/issues/169).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9489

**Comment by bflad** [comment]
Support for the new `image_tag_mutability` argument has been merged and will release with version 2.23.0 of the Terraform AWS Provider in the next day or two. Thanks to @sunilkumarmohanty for the implementation. 👍
