### ISSUE TITLE
Support for gitSubmodulesConfig in source block of codebuild_project resource

### ISSUE THREAD

**Issue by symbol-hayashi** [terraform-providers/terraform-provider-aws#9534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
`gitSubmodulesConfig` is currently not supported in source block of codebuild_project resource.

### New or Affected Resource(s)

* aws_codebuild_project

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://docs.aws.amazon.com/cli/latest/reference/codebuild/create-project.html
https://docs.aws.amazon.com/sdk-for-go/api/service/codebuild/#GitSubmodulesConfig

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.48.0 of the Terraform AWS Provider, later next week. Thanks to @jValdron for the implementation. 👍
