### ISSUE TITLE
Ability to set cache for aws_api_gateway_deployment

### ISSUE THREAD

**Issue by heylookalive** [terraform-providers/terraform-provider-aws#955]
Hi, I'm using terraform with AWS and API Gateway but am having trouble between the `aws_api_gateway_deployment` and `aws_api_gateway_stage` resources.

The `aws_api_gateway_deployment` resource creates a stage when being provisioned, as does `aws_api_gateway_stage`. The difference is that the former doesn't allow you to set cache settings and the latter requires a `aws_api_gateway_deployment` to refer to.

In addition to this when producing a URL for the deployed stage, `aws_api_gateway_deployment` has a URL output but `aws_api_gateway_stage` does not.

Options wise we could:

1. Allow setting of cache behaviour on the `aws_api_gateway_deployment` resource
2. Not have `aws_api_gateway_stage` require a `aws_api_gateway_deployment` and add an output for URL

Help would be appreciated!

**Comment by heylookalive** [comment]
Hi all, any thoughts on this?

**Comment by heylookalive** [comment]
@radeksimko not sure that this is an enhancement, the above makes no logical sense

**Comment by iserko** [comment]
@heylookalive doesn't this https://www.terraform.io/docs/providers/aws/r/api_gateway_method_settings.html#caching_enabled solve your problem. AFAICS Terraform currently doesn't provide you with a way to set settings on a stage level, but you can do it per method.
