### ISSUE TITLE
Support for multiple LB target groups in ECS service 

### ISSUE THREAD

**Issue by oioki** [terraform-providers/terraform-provider-aws#9556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon released support for multiple load balancer target group in ECS service, see [announcement](https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecs-services-now-support-multiple-load-balancer-target-groups/).

This could be useful for using ECS service in several load balancers, particularly, in external and internal at the same time.

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "application" {
...
  load_balancer {
    target_group_arn = aws_lb_target_group.external.arn
    container_name   = local.application
    container_port   = 80
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.internal.arn
    container_name   = local.application
    container_port   = 80
  }
...
}
```

Currently this results in:
```
Error: Too many load_balancer blocks

  on  line 0:
  (source code not available)

No more than 1 "load_balancer" blocks are allowed
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-ecs-services-now-support-multiple-load-balancer-target-groups/
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html

**Comment by bflad** [comment]
Hi @oioki 👋 Thank you for submitting this feature request.

There is currently a previously open issue (#9285) and pull request (#9411) for this functionality. To consolidate discussions and efforts, I'm going to close this issue. Please follow #9285 and #9411 for further updates. Thanks!
