### ISSUE TITLE
Add region as an attribute to the aws_sns_topic resource

### ISSUE THREAD

**Issue by jevon71-work** [terraform-providers/terraform-provider-aws#9562]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aws_sns_topic is region specific.  Therefore it should be possible to specify the region when creating the resource, in the same way as you can with other resources, instead of it automatically inheriting the region from the runtime environment.

### New or Affected Resource(s)

* aws_sns_topic

### Potential Terraform Configuration

```hcl
resource "aws_sns_topic" "user_updates" {
  name   = "user-updates-topic"
  region = "us-east-1"
}
```

**Comment by bflad** [comment]
Hi @jevon71-work 👋 

You can control Terraform AWS Provider resources in multiple regions by defining multiple provider configurations with the `alias` argument and telling specific resources to use the aliased provider. e.g.

```hcl
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

provider "aws" {
  alias  = "us-west-2"
  region = "us-west-2"
}

resource "aws_sns_topic" "user_updates_us-east-1" {
  provider = "aws.us-east-1"

  name   = "user-updates-topic"
}

resource "aws_sns_topic" "user_updates_us-west-2" {
  provider = "aws.us-west-2"

  name   = "user-updates-topic"
}
```

When the `provider` argument is omitted from resources, it defaults to the provider configuration without an `alias` argument.

More information about this can be found in the [Terraform documentation](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances).

Hope this helps!
