### ISSUE TITLE
resource aws_sns_topic_policy doesn't support import

### ISSUE THREAD

**Issue by beatak** [terraform-providers/terraform-provider-aws#9578]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can you support `import` for resource `aws_sns_topic_policy`?

### New or Affected Resource(s)

possibly `aws_sns_topic`?

### Potential Terraform Configuration

n/a

### References

* https://www.terraform.io/docs/providers/aws/r/sns_topic_policy.html
* https://docs.aws.amazon.com/cli/latest/reference/sns/get-topic-attributes.html

**Comment by bflad** [comment]
Support for importing `aws_sns_topic_policy` resources has been merged and will release with version 2.30.0 of the Terraform AWS Provider, later this week. 👍
