### ISSUE TITLE
Template upgrade to v0.12 removes iam_instance_profile

### ISSUE THREAD

**Issue by ishrivatsa** [terraform-providers/terraform-provider-aws#9593]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.12.5

### Affected Resource(s)

aws_instance and iam_instance_profile

### Terraform Configuration Files

TF file on version 0.11

```
resource "aws_instance" "api2" {
     ami                                  = "${var.images["api"]}"
     instance_type                 = "t2.micro"
     subnet_id                        = "${aws_subnet.public_subnet.id}"
     vpc_security_group_ids = ["${aws_security_group.api_sg.id}"]
     key_name                        = "${var.option_6_aws_ssh_key_name}"
     iam_instance_profile      = "Myrole"
     tags {
          App           = "${var.option_3_aws_vpc_name}"
          Name          = "api2-${var.option_3_aws_vpc_name}"
          Tier          = "API"
          Product       = "${var.product}"
          Team          = "${var.team}"
          Owner         = "${var.owner}"
          Environment   = "${var.environment}"
          Organization  = "${var.organization}"
          "Cost Center" = "${var.costcenter}"
     }
}
```

TF file after using the terraform 0.12upgrade command

```
resource "aws_instance" "api2" {
  ami                                   = var.images["api"]
  instance_type                 = "t2.micro"
  subnet_id                        = aws_subnet.public_subnet.id
  vpc_security_group_ids = [aws_security_group.api_sg.id]
  key_name                        = var.option_6_aws_ssh_key_name
  tags = {
    App           = var.option_3_aws_vpc_name
    Name          = "api2-${var.option_3_aws_vpc_name}"
    Tier          = "API"
    Product       = var.product
    Team          = var.team
    Owner         = var.owner
    Environment   = var.environment
    Organization  = var.organization
    "Cost Center" = var.costcenter
  }
}
```
### Expected Behavior

After running the terraform 0.12upgrade command, the iam_instance_profile field should have been retained or converted to the latest format. 

```
resource "aws_instance" "api2" {
  ami                                   = var.images["api"]
  instance_type                 = "t2.micro"
  subnet_id                        = aws_subnet.public_subnet.id
  vpc_security_group_ids = [aws_security_group.api_sg.id]
  key_name                        = var.option_6_aws_ssh_key_name

  iam_instance_profile      = "Myrole"

  tags = {
    App           = var.option_3_aws_vpc_name
    Name          = "api2-${var.option_3_aws_vpc_name}"
    Tier          = "API"
    Product       = var.product
    Team          = var.team
    Owner         = var.owner
    Environment   = var.environment
    Organization  = var.organization
    "Cost Center" = var.costcenter
  }
}
```

### Actual Behavior

The **iam_instance_profile** key-value are removed from the template

### Steps to Reproduce

1. `terraform init`

2. `terraform 0.12upgrade`

**Comment by bflad** [comment]
Hi @ishrivatsa 👋 Sorry for the frustrating behavior and thank you for reporting this. Unfortunately while this issue is filed in the correct location for issues with Terraform AWS Provider resources, the code and logic for the Terraform commands, such as `0.12upgrade`, live upstream in the [Terraform Core repository](https://github.com/hashicorp/terraform/) currently. Since the code of the command itself potentially generated this issue, my suggestion would be to open a bug report there to help get this resolved: https://github.com/hashicorp/terraform/issues/new?template=bug_report.md Thanks again for reporting this and my apologies we cannot automatically transfer the issue.
