### ISSUE TITLE
aws_vpc_endpoint_service not working for govcloud east

### ISSUE THREAD

**Issue by dbadrak** [terraform-providers/terraform-provider-aws#9611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.6
+ provider.aws v2.22.0
```

### Affected Resource(s)

* data aws_vpc_endpoint_service

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-gov-east-1"
  profile = "gov-east"
}

data "aws_vpc_endpoint_service" "s3" {
  service = "s3"
}
```

### Debug Output

https://gist.github.com/dbadrak/911ec19e4f5a929b63679fbc693a5d71

### Panic Output

None

### Expected Behavior

A data items is created to be used in creating a vpc endpoint.

### Actual Behavior

An error is generated and it cannot be completed. This fails for the dynamodb service endpoint too.

```
# results from file logs/plan.20190802.1564774801.log
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_vpc_endpoint_service.s3: Refreshing state...

Error: multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service

  on vpc-endpoints.tf line 6, in data "aws_vpc_endpoint_service" "s3":
   6: data "aws_vpc_endpoint_service" "s3" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This runs within a VPC, in GovCloud East

### References

* #4398

**Comment by ewbankkit** [comment]
It looks like GovCloud is now returning `ServiceDetails` but still not respecting the filter.
https://github.com/terraform-providers/terraform-provider-aws/blob/13456eed4e5f7afc85b271bf7a0b992c47a87fbe/aws/data_source_aws_vpc_endpoint_service.go#L102-L120

**Comment by ewbankkit** [comment]
Maybe related to [this announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/introducing-aws-privatelink-in-the-aws-govcloud-us-east-region/)?

**Comment by dbadrak** [comment]
Ok, I re-ran ```terraform apply``` without changing any files and it works now.  I did not update any of the providers.  It must be working due to the addition of the PrivateLink in AWS Gov East.  Thanks for looking into this.
