### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by Magicloud** [terraform-providers/terraform-provider-aws#9622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.12.6

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

https://github.com/Magicloud/ifp-example/blob/master/alb-test/tester.tf

All modules it uses is in the repo.

### Debug Output

https://github.com/Magicloud/ifp-example/blob/master/alb-test/tf-debug.log

### Panic Output

N/A

### Expected Behavior

A VPC, an ASG, an ELB setup.

### Actual Behavior

```
Error: Provider produced inconsistent final plan

When expanding the plan for module.asg.aws_autoscaling_group.cluster to
include new values learned so far during apply, provider "aws" produced an
invalid new value for .availability_zones: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply`
  Get error.
2. `terraform apply` again
  Works.

### Important Factoids

Nothing special I guess.

### References

I have read some other issues here about "inconsistent final plan". None are similar.

**Comment by vroy** [comment]
We had the same problem and I just figured out the issue. You have both `availability_zones` and `vpc_zone_identifier` set. Removing the `availability_zones` argument solved this for us.

From the docs:

* availability_zones - (Required only for EC2-Classic) A list of one or more availability zones for the group. This parameter should not be specified when using vpc_zone_identifier.

* vpc_zone_identifier (Optional) A list of subnet IDs to launch resources in.

**Comment by Magicloud** [comment]
@vroy Thanks. Works for me.
