### ISSUE TITLE
How to configure AWS instance using name of AMI not the ami-id.

### ISSUE THREAD

**Issue by Dhaamodharan** [terraform-providers/terraform-provider-aws#9637]
Hi All,

I am new to Terraform, wanted to provision an aws instance,  its available in AWS-Marketplace. I have gone througth the documents and got solution to pick the instance image based on its ami-id. But I dont have any ami-id in my image. I wanted to pick with the name. The image is "**CIS Ubuntu Linux 18.04 LTS Benchmark - Level 1"** 

I configured my resources.tf 
=========================
data "aws_ami" "cisubuntu" {
  owners = ["xxxxxxxx"]
 
    filter {
    name = "name"
    values = ["CIS Ubuntu Linux 18.04 LTS Benchmark - Level 1"]
     }
    filter {
    name   = "architecture"
    values = ["x86_64"]
     }
  }

resource "aws_instance" "cis-instance" {
  ami= "${data.aws_ami.cisubuntu.id}"
  instance_type   = "t2.micro"
  key_name = "mykeyfile"
  tags= {
    Name = "cis-instance"
  }
  }
=================
But when I do terraform apply, its throwing the below error:
================
Error: Your query returned no results. Please change your search criteria and try again.
  on aws_ami.tf line 1, in data "aws_ami" "cisubuntu":
   1: data "aws_ami" "cisubuntu" {
=================
Someone help me to configure the same with mentioned AMI.

Thanks,
Dhamodharan.

**Comment by aidanmelen** [comment]
The [aws_instance resource](https://www.terraform.io/docs/providers/aws/r/instance.html) has a good example of how to dynamically look up the latest 14.04 Ubuntu AMI from Canonical in the AWS Marketplace and create a new EC2 instance from that.

This example may be more helpful for you:

```
provider "aws" {
  version = "~> 2.0"
  region  = "us-east-1"
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    # values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
    values = ["CIS Ubuntu Linux 18.04 LTS Benchmark v1.0.0.* - Level 1-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  # owners = ["099720109477"] # Canonical
  owners =["679593333241"]
}

resource "aws_instance" "example" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "helloworld"
  }
}
```

you will need to subscribe and pay for this Image. If you don't, like me, you will get this error during the `terraform apply` phase:

```
aws_instance.example: Creating...

Error: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=b1e35cepur7ecue1bq883thxr
        status code: 401, request id: 52352558-6e83-4ac5-be4d-e47ed88534f6

  on main.tf line 26, in resource "aws_instance" "example":
  26: resource "aws_instance" "example" {
```

**Comment by Dhaamodharan** [comment]
Hi aidanmelen,

Thank you for the revert, really its helpful and I am able to execute the same. Even I referred the same example already but I was not aware of the owners_id. I gave my "aws_id" and "aws_marketplace" so it thrown that error. Then I copied the same owner which you mentioned, its working now. I have doubt here. How to get the owner details for any AMI. Do we have any reference document to verify the owners for different AMI.

**Comment by ryndaniels** [comment]
Hi @Dhaamodharan 👋 thanks for this question! In general, you may have more luck asking questions in the [Terraform Provider forum](https://discuss.hashicorp.com/c/terraform-providers) since issues in this repository are more for specific bug reports or feature requests in the provider code itself. That being said, are you able to try either of the suggested solutions [here](https://stackoverflow.com/questions/47467593/how-am-i-supposed-to-get-the-owner-id-of-an-aws-market-place-ami) to find the AMI owner details?

**Comment by ryndaniels** [comment]
We're going to go ahead and close this since we haven't gotten a response in a couple weeks, but feel free to open a new issue if needed!
