### ISSUE TITLE
AWS GuardDuty: Add support for creating filters

### ISSUE THREAD

**Issue by doublefelix7** [terraform-providers/terraform-provider-aws#9647]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform aws provider does not currently support the capability to manage filters (CreateFilter, GetFilter, DeleteFilter). 
CloudFormation does support this, so this request is to have parity.

### New or Affected Resource(s)

* GuardDuty
* GuardDuty Filters (example resource name: aws_guardduty_filter)

### Potential Terraform Configuration

We could have something like this:

```hcl
resource "aws_guardduty_filter" "foo" {
   name = "MyFilter"
   description = "Description of MyFilter"
   detector_id = aws_guardduty_detector.id
   rank = 1
   finding_criteria = {
      criterion = {
         updatedAt = {
            Gte = 0
         }
      }
   }
}
```

### References

* https://docs.aws.amazon.com/guardduty/latest/ug/create-filter.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-filter.html

**Comment by phundisk** [comment]
Was going to take a stab at this.  Thoughts on the proposal for how the filters aka the criterion might be done?

```
resource "aws_guardduty_filter" "foo" {
   name = "test_filter"
   description = "This is my description"
   detector_id = "11111111111111"
   rank = 1
   auto_archive = true
   filters = [
     {
       filter_type = "Equal"
       filter_key = "service.action.awsApiCallAction.remoteIpDetails.ipAddressV4"
       filter_values = ["1.1.1.1"]
    }  
   ]
}
```
