### ISSUE TITLE
[Documentation] aws_lb docs list "subnets" as an optional parameter but is required

### ISSUE THREAD

**Issue by anilnatha** [terraform-providers/terraform-provider-aws#9654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue Summary

I am learning about Terraform and how to build applications on AWS. That being said, I'm creating modules by adding a resources required arguments to the modules first, and then adding optional arguments one at a time. The [aws_lb resource documentation](https://www.terraform.io/docs/providers/aws/r/lb.html#subnet_mapping) reports that there are no required arguments for the top level arguments, notably, the [subnets](https://www.terraform.io/docs/providers/aws/r/lb.html#subnets) and [subnet_mapping](https://www.terraform.io/docs/providers/aws/r/lb.html#subnet_mapping) arguments are both listed as optional (I understand that if I add these two blocks, each of those, have their own set of required parameters that must be provided).

> subnets - (Optional) A list of subnet IDs to attach to the LB. Subnets cannot be updated for Load Balancers of type network. Changing this value for load balancers of type network will force a recreation of the resource.
> subnet_mapping - (Optional) A subnet mapping block as documented below.

When I attempt to apply my configuration without including these arguments, Terraform reports that at least two subnets _are_ required.

### Terraform Version

v0.12.5

### Affected Resource(s)

* aws_lb
provider.aws version: v2.21.1

#### Config File

This config file is located on my system at `<PROJECT_DIRECTORY>/terraform/environments/dev/aws-lb.tf`

```hcl
module "load_balancer" {

	source = "../../modules/aws_lb"

	is_internal = true
	type = "application"
	
}
```

#### Module Files

These module files are located in a folder on my system at `<PROJECT_DIRECTORY>/terraform/modules/aws_lb`

main.tf
```hcl
resource "aws_lb" "load_balancer" {
	internal = var.is_internal
	load_balancer_type = var.type
}
```

variables.tf
```hcl
variable "is_internal" {
	description = "Flag that specifies if this is an internet facing ('false') or internal ('true') load balancer."
	type = bool
}

variable "type" {
	description = "The type of load balancer to create. Possible values are, \"application\" or \"network\"."
	type = string
}
```

### Expected Behavior

Because none of the arguments are listed as required, I expected my aws_lb module to allow terraform to create the ALB service in my AWS account.

### Actual Behavior

The ALB was not created, and instead I received the error shown below when I ran `terraform apply "tf.plan"`. In addition, running `terraform validate` also did not disclose any validation errors with my configuration.

```
$ terraform apply "tf.plan"
module.load_balancer.aws_lb.load_balancer: Creating...

Error: Error creating application Load Balancer: ValidationError: At least two subnets in two different Availability Zones must be specified
	status code: 400, request id: cd9b0827-b873-11e9-9eb9-b9c460d3c6af

  on ../../modules/aws_lb/main.tf line 1, in resource "aws_lb" "load_balancer":
   1: resource "aws_lb" "load_balancer" {


$
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -out "tf.plan"`

```
$ terraform plan -out "tf.plan"
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

<REMOVED SOME PROJECT STATE INFORMATION FOR SECURITY>
------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.load_balancer.aws_lb.load_balancer will be created
  + resource "aws_lb" "load_balancer" {
      + arn                        = (known after apply)
      + arn_suffix                 = (known after apply)
      + dns_name                   = (known after apply)
      + enable_deletion_protection = false
      + enable_http2               = true
      + id                         = (known after apply)
      + idle_timeout               = 60
      + internal                   = true
      + ip_address_type            = (known after apply)
      + load_balancer_type         = "application"
      + name                       = (known after apply)
      + security_groups            = (known after apply)
      + subnets                    = (known after apply)
      + vpc_id                     = (known after apply)
      + zone_id                    = (known after apply)

      + subnet_mapping {
          + allocation_id = (known after apply)
          + subnet_id     = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: tf.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "tf.plan"

Releasing state lock. This may take a few moments...
$
```

3. `terraform validate`

```
$ terraform validate
Success! The configuration is valid.

$ 
```

4. `terraform apply "tf.plan"`

```
$ terraform apply "tf.plan"
module.load_balancer.aws_lb.load_balancer: Creating...

Error: Error creating application Load Balancer: ValidationError: At least two subnets in two different Availability Zones must be specified
	status code: 400, request id: cd9b0827-b873-11e9-9eb9-b9c460d3c6af

  on ../../modules/aws_lb/main.tf line 1, in resource "aws_lb" "load_balancer":
   1: resource "aws_lb" "load_balancer" {


$
```

### Important Factoids

* I am applying this config to AWS GovCloud

Thank you for your guidance and support as I try to gain knowledge and experience with Terraform.

**Comment by ryndaniels** [comment]
Hi @anilnatha 👋 Thanks for opening this issue! You're right in noticing that both the `subnets` and `subnet_mapping` arguments are listed as optional - it is expected that *one* of those arguments is present, but you're right that it's a bit confusing! I've gone ahead and opened a [PR](#9702) to change the docs to clarify this. You should be able to use whichever of those arguments makes sense in your environment and continue working from there. 🙂

**Comment by anilnatha** [comment]
Thanks for updating the docs.  I did move on and use one of those blocks that fit our proposed architecture so all is good. Thanks again.
