### ISSUE TITLE
aws_route53_record ignores provider when used with aws_acm_certificate_validation which attempts to write a duplicate record set

### ISSUE THREAD

**Issue by jamesongithub** [terraform-providers/terraform-provider-aws#9666]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v2.22.0

### Affected Resource(s)

* aws_acm_certificate_validation
* aws_route53_record
* aws_acm_certificate

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

# root
provider "aws" {
  region = "us-west-1"
  alias = "us-west-1"
}

provider "aws" {
  region = "us-east-1"
  alias = "us-east-1"
}

provider "aws" {
  region = "us-east-2"
  alias = "us-east-2"
}

module "us-east-1" {
  source = "./certs"

  providers = {
      aws.default = "aws.us-west-1"
      aws.current = "aws.us-east-1"
  }
}

module "us-east-2" {
  source = "./certs"

  providers = {
      aws.default = "aws.us-west-1"
      aws.current = "aws.us-east-2"
  }
}

------------
# module
provider "aws" {
  alias = "default"
}

provider "aws" {
  alias = "current"
}

resource "aws_acm_certificate" "certificate" {
  domain_name = "test.example.com"
  lifecycle {
    create_before_destroy = true
  }
  validation_method = "DNS"

  provider = "aws.current"
}

resource "aws_acm_certificate_validation" "validation" {
  certificate_arn = "${aws_acm_certificate.certificate.arn}"
  validation_record_fqdns = [
    "${aws_route53_record.validation.fqdn}",
  ]

  provider = "aws.current"
}


resource "aws_route53_record" "validation" {
  name = "${aws_acm_certificate.certificate.domain_validation_options.0.resource_record_name}"
  type = "${aws_acm_certificate.certificate.domain_validation_options.0.resource_record_type}"
  zone_id = "ZONE_ID"
  records = [
    "${aws_acm_certificate.certificate.domain_validation_options.0.resource_record_value}"
  ]
  ttl = 60

  provider = "aws.default"
}

```

### Expected Behavior

Expected terraform to create two certificates and corresponding certificate validations but sharing 1 route53 record set. (Since the certificates protect the same hostname, the validation produces the same CNAME record). Here we have used 3 providers. 1 provider for cert in us-east-1, 1 provider for the cert in us-east-2 and 1 provider for the route53 record.

### Actual Behavior

In the first run aws_acm_certificate.certificate.resource_record_name is not even populated.

* module.us-east-2.aws_route53_record.validation: Resource 'aws_acm_certificate.certificate' does not have attribute 'domain_validation_options.0.resource_record_name' for variable 'aws_acm_certificate.certificate.domain_validation_options.0.resource_record_name'
* module.us-east-1.aws_route53_record.validation: Resource 'aws_acm_certificate.certificate' does not have attribute 'domain_validation_options.0.resource_record_value' for variable 'aws_acm_certificate.certificate.domain_validation_options.0.resource_record_value'

In the second run resource_record_name is populated, but for some reason attempts to write the same record into two different route53 records. The provider passed into the aws_route53_record resource seems to be ignored and it seems to be tied to the provider that was passed into the aws_acm_certificate/aws_acm_certificate_validation resources.

* aws_route53_record.validation: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='_82d2850c05a64de2f883cb6a23d82529.test.example.com.', type='CNAME'] but it already exists]
	status code: 400, request id: f36a71d5-e00e-42a0-9c04-95e57e2e49ce

The goal here is to create a two certificates with the same hostname in multiple regions.

### Steps to Reproduce

1. `terraform apply` -> fails with missing attribute
2. `terraform apply` -> fails with existing record

### References

* #0000

**Comment by dohoangkhiem** [comment]
I have almost the same Terraform configs for our Infra, 3 regions and for each region we call a module to create resources. The validation aws_route53_record actually worked when we used old AWS plugin (~> 1.56.0), just we tried upgrading it to ~> 2.35.0 today and got the same error about existing Route53 record. 

But It seems to me that it's a correct behaviour from Terraform, 3 modules tried to create the same Route53 record, I don't see it has anything to do with the provider here, whatever provider you use for that aws_route53_record, it will try to create a record which can be created before from the other modules.

**Comment by jamesongithub** [comment]
It's interesting it worked for an older version. Wondering if it consistently worked in the past. It should have something to do with the provider. In your case a newer version of the provider resulted in different behavior.

In the example given, I would thought the `aws_route53_record` resource is shared since the same instance of the provider is passed to both modules.

**Comment by dohoangkhiem** [comment]
Actually my case is a bit different as I even used different providers for creating the same Route53 record, which still accepted in aws 1.5.6, that makes me think it's a bug 

```
ubuntu@ip-172-31-15-42:/vagrant/provision/terraform/configurations/infra$ terraform state list | grep cert_validation
module.vpc_ap-southeast-1.aws_route53_record.cert_validation
module.vpc_eu-central-1.aws_route53_record.cert_validation
module.vpc_us-east-1.aws_route53_record.cert_validation

ubuntu@ip-172-31-15-42:/vagrant/provision/terraform/configurations/infra$ terraform state show module.vpc_ap-southeast-1.aws_route53_record.cert_validation 
id                = Z3OAEYPAZ7ZKRY__daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com._CNAME
allow_overwrite   = true
fqdn              = _daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com
name              = _daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com
records.#         = 1
records.471405270 = _d98e7c2651fc8cdf4d1829c06ec40a9f.duyqrilejt.acm-validations.aws.
ttl               = 60
type              = CNAME
zone_id           = Z3OAEYPAZ7ZKRY

ubuntu@ip-172-31-15-42:/vagrant/provision/terraform/configurations/infra$ terraform state show module.vpc_eu-central-1.aws_route53_record.cert_validation
id                = Z3OAEYPAZ7ZKRY__daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com._CNAME
allow_overwrite   = true
fqdn              = _daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com
name              = _daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com
records.#         = 1
records.471405270 = _d98e7c2651fc8cdf4d1829c06ec40a9f.duyqrilejt.acm-validations.aws.
ttl               = 60
type              = CNAME
zone_id           = Z3OAEYPAZ7ZKRY

ubuntu@ip-172-31-15-42:/vagrant/provision/terraform/configurations/infra$ terraform state show module.vpc_us-east-1.aws_route53_record.cert_validation
id                = Z3OAEYPAZ7ZKRY__daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com._CNAME
allow_overwrite   = true
fqdn              = _daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com
health_check_id   = 
name              = _daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com
records.#         = 1
records.471405270 = _d98e7c2651fc8cdf4d1829c06ec40a9f.duyqrilejt.acm-validations.aws.
set_identifier    = 
ttl               = 60
type              = CNAME
zone_id           = Z3OAEYPAZ7ZKRY
```

**Comment by jamesongithub** [comment]
Different providers seems like it should fail. It might just be the ordering the records were created in. If the id is used to distinguish the resource (Z3OAEYPAZ7ZKRY__daf68f5f773d353f7c1aac2863b381d6.khiem.int.magnolia-cloud.com._CNAME), it might have detected it was created already.

**Comment by bflad** [comment]
Hi folks 👋  When setting up DNS validation records for ACM, [we recommend](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation) enabling the [`aws_route53_record` resource `allow_overwrite` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route53_record#allow_overwrite). This will prevent errors if multiple validation records overlap or these records need to be recreated. 👍
