### ISSUE TITLE
Add support for postgresql enabled_cloudwatch_logs_exports to aws_rds_cluster

### ISSUE THREAD

**Issue by ckuehl** [terraform-providers/terraform-provider-aws#9669]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.12

### Affected Resource(s)

* aws_rds_cluster

### Details

Aurora Postgres now supports exporting `postgresql` logs to CloudWatch:

```
        {
            "Engine": "aurora-postgresql",
            "EngineVersion": "10.7",
            "DBParameterGroupFamily": "aurora-postgresql10",
            "DBEngineDescription": "Aurora (PostgreSQL)",
            "DBEngineVersionDescription": "Aurora PostgreSQL (compatible with PostgreSQL 10.7)",
            "ValidUpgradeTarget": [],
            "ExportableLogTypes": [
                "postgresql"
            ],
            "SupportsLogExportsToCloudwatchLogs": true,
            "SupportsReadReplica": false,
            "SupportedEngineModes": [
                "provisioned"
            ],
            "SupportedFeatureNames": [
                "s3Import"
            ]
        }
```

Attempting to set the value currently generates this error:

```
Error: expected enabled_cloudwatch_logs_exports.0 to be one of [audit error general slowquery], got postgresql
```

This needs to be updated to support `postgresql` as a valid value.

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/6829 (similar change for aws_db_instance)

**Comment by bflad** [comment]
Support for the `postgresql` value has been merged and will release with version 2.25.0 of the Terraform AWS Provider, in about a week. Thanks to @ste1nstone for the implementation. 👍
