### ISSUE TITLE
Support `stopTimeout` in `aws_ecs_task_definition`

### ISSUE THREAD

**Issue by MrHen** [terraform-providers/terraform-provider-aws#9686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `container_definitions` block of `aws_ecs_task_definition` does not apply `stopTimeout`. I assume it needs to be added somewhere in the resource definition. [Perhaps here?](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_ecs_container_definition.go#L67)

### New or Affected Resource(s)

* aws_ecs_task_definition

### Potential Terraform Configuration

```hcl
variable "image" {
  description = "The docker image name, e.g nginx"
}

variable "name" {
  description = "The worker name, if empty the service name is defaulted to the image name"
}

variable "cpu" {
  description = "The number of cpu units to reserve for the container"
  default     = 512
}

variable "env_vars" {
  description = "The raw json of the task env vars"
  default     = "[]"
}

variable "command" {
  description = "The raw json of the task command"
  default     = "[]"
}

variable "entry_point" {
  description = "The docker container entry point"
  default     = "[]"
}

variable "ports" {
  description = "The docker container ports"
  default     = "[]"
}

variable "image_version" {
  description = "The docker image version"
  default     = "latest"
}

variable "memory" {
  description = "The number of MiB of memory to reserve for the container"
  default     = 512
}

variable "stop_timeout" {
  description = "Time duration (in seconds) to wait before the container is forcefully killed if it doesn't exit normally on its own"
  default     = "30"
}

data "aws_ecs_task_definition" "task" {
  depends_on = ["aws_ecs_task_definition.main"]
  task_definition = "${aws_ecs_task_definition.main.family}"
}

resource "aws_ecs_task_definition" "main" {
  family = "${var.name}"

  lifecycle {
    ignore_changes        = ["image"]
    create_before_destroy = true
  }

  container_definitions = <<EOF
[
  {
    "cpu": ${var.cpu},
    "environment": ${var.env_vars},
    "essential": true,
    "command": ${var.command},
    "image": "${var.image}:${var.image_version}",
    "memoryReservation": ${var.memory},
    "name": "${var.name}",
    "portMappings": ${var.ports},
    "entryPoint": ${var.entry_point},
    "mountPoints": [],
    "logConfiguration": {
      "logDriver": "journald",
      "options": {
        "tag": "${var.name}"
      }
    },
    "stopTimeout": ${var.stop_timeout}
  }
]
EOF
}
```

### References

* #0000

**Comment by ryndaniels** [comment]
Hi @MrHen - this functionality was added in v2.3.0 of the AWS Terraform provider (which pulled in the version of the AWS Go SDK that supported this field). If you can make sure you're using the latest version of the provider, you should be able to use `stopTimeout` in your container definitions. Thanks! 🙂
