### ISSUE TITLE
documented attribute is not valid for aws_ssm_association

### ISSUE THREAD

**Issue by overratedpro** [terraform-providers/terraform-provider-aws#9724]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.6
+ provider.archive v1.2.2
+ provider.aws v2.23.0
+ provider.external v1.2.0
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* aws_ssm_association

### Terraform Configuration Files

```hcl
resource "aws_ssm_document" "run_ifconfig" {
  name          = "test_document"
  content       = file("/existing/path.json")
  document_type = "Command"
}

resource "aws_ssm_association" "run_ifconfig" {
  name = "${aws_ssm_document.run_ifconfig.name}"

  targets {
    key    = "tag:tagname"
    values = [
      "tagvalue"
    ]
  }
}

output "test" {
  value = aws_ssm_association.run_ifconfig.instance_ids
}

```

### Expected Behavior

A terraform plan displayed.

### Actual Behavior

Command failed with error:
```
Error: Unsupported attribute

  on output.tf line 2, in output "test":
   2:   value = aws_ssm_association.run_ifconfig.instance_ids

This object has no argument, nested block, or exported attribute named
"instance_ids". Did you mean "instance_id"?

```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids

The attribute 'instance_ids' is documented as valid and exported: https://www.terraform.io/docs/providers/aws/r/ssm_association.html#instance_ids

**Comment by nywilken** [comment]
hi @overratedpro thanks for reporting this documentation issue. The AWS API doesn't actually return a list of associated instance ids, just a single `instance_id` so this just might be a copy paste issue or maybe some positive thinking for future API support. I'm going to re-label this as a documentation bug. 

If you would like to submit a pull-request for the issue I would be happy to help you push through the change. Here's a link to our [CONTRIBUTING](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#documentation-update) guide.
