### ISSUE TITLE
Windows defender detects terraform-provider-aws_v2.23.0_x4.exe file as trojan:win32/ludicrouz.z

### ISSUE THREAD

**Issue by Arlington1985** [terraform-providers/terraform-provider-aws#9727]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.6

### Affected Resource(s)

* aws_v2.23.0_x4

### Terraform Configuration Files

```hcl
no any
```

### Debug Output

no any

### Panic Output

no any

### Expected Behavior

`terraform init` should successfully be executed

### Actual Behavior

Windows defender detects the following file as Trojan
https://releases.hashicorp.com/terraform-provider-aws/2.23.0/terraform-provider-aws_2.23.0_windows_amd64.zip

### Steps to Reproduce

1. `terraform init`

### References

* #0000

**Comment by bflad** [comment]
Hi @Arlington1985 👋 Thank you for reporting this.

I'm having trouble reproducing this with the below and the fairly constant Windows Defender definition updates may have already resolved this issue.

- Windows 10 Pro Version 1903 (OS Build 18362.267)
- Security intelligence version: 1.299.1834.0 (August 12, 2019 11:41 AM)
- Downloading via `terraform init` and directly from https://releases.hashicorp.com/terraform-provider-aws/2.23.0/terraform-provider-aws_2.23.0_windows_amd64.zip in Microsoft Edge browser

Can you please verify the procedure you used to download this file to trigger the Windows Defender message and verify that the `terraform-provider-aws_2.23.0_windows_amd64.zip` file checksum is `243c732dd06e032a4577c69e32b492efb4d504d962523a5627678ca06f263dbe`?

You can do this in PowerShell via:

```
Get-FileHash terraform-provider-aws_2.23.0_windows_amd64.zip -Algorithm SHA256
```

**Comment by Arlington1985** [comment]
Hi @bflad. It seems you have a fresher version of Security intelligence version, as the moment when it happened I had `1.299.1798.0` and now `1.299.1820.0`. Even update didn't help me. I will wait for  >=`1.299.1834.0`. Temporary I switched to `aws-provider v2.22`, it hasn't such problem. 

Ps.. I can't execute `Get-FileHash terraform-provider-aws_2.23.0_windows_amd64.zip -Algorithm SHA256` as the file deleted automatically and as it's company laptop I have not admin access to manipulate on it.

**Comment by fl0ge** [comment]
Hi @bflad and @Arlington1985. I had the same problem yesterday and now it's OK. I have definition update 1.299.1876.0 and nothing bad is detected anymore.
For information, I was able to compare SHA256 hashes while having the issue and it was correct. It may be a temporary Windows Defender issue, now resolved.

**Comment by Arlington1985** [comment]
I can also confirm that today after updating threat definition the problem was resolved. We can close the issue.

**Comment by bflad** [comment]
Great to hear, thanks. Closing. 👍
