### ISSUE TITLE
ECS: Could not create target tracking scaling policy using ALBRequestCountPerTarget

### ISSUE THREAD

**Issue by dohoangkhiem** [terraform-providers/terraform-provider-aws#9734]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
    Terraform v0.12.3
    + provider.aws v2.23.0

### Affected Resource(s)

* aws_appautoscaling_policy

### Terraform Configuration Files

```hcl
...
resource "aws_alb_target_group" "target_group" {
  name        = "${var.service_name}-lb-tg"
  port        = var.container_port
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    enabled = "true"
    interval = 30
    path = "/health_check"
    port = "traffic-port"
    matcher = "200"
  }
}

resource "aws_alb" "load_balancer" {
  name = "${var.service_name}-lb"
  internal = true
  load_balancer_type = "application"
  security_groups = ["${aws_security_group.alb_security_group.id}"]
  subnets = var.subnet_ids
}
...

resource "aws_appautoscaling_target" "ecs_target" {
  max_capacity       = var.max_capacity
  min_capacity       = var.min_capacity
  resource_id        = "service/${aws_ecs_cluster.cluster.name}/${var.service_name}"
  role_arn           = "${data.aws_iam_role.ecs_autoscaling_role.arn}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "ecs_target_tracking_predefined_metric_policy" {
  name               = "sqs-target-scale"
  policy_type        = "TargetTrackingScaling"
  resource_id        = "${aws_appautoscaling_target.ecs_target.resource_id}"
  scalable_dimension = "${aws_appautoscaling_target.ecs_target.scalable_dimension}"
  service_namespace  = "${aws_appautoscaling_target.ecs_target.service_namespace}"

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ALBRequestCountPerTarget"
      resource_label = "${aws_alb_target_group.target_group.arn_suffix}" # "${aws_alb.load_balancer.arn_suffix}"
    }

    target_value       = var.target_value
    scale_in_cooldown  = var.scale_in_cooldown
    scale_out_cooldown = var.scale_out_cooldown
  }
}
```

### Output
```
Error: Failed to create scaling policy: Error putting scaling policy: ValidationException: Invalid resource label 'targetgroup/khiem-test-14-lb-tg/a7fd143efed41500' for predefined metric type ALBRequestCountPerTarget
	status code: 400, request id: 7fe213e0-bd1b-11e9-89a4-b712d89409f6

  on main.tf line 314, in resource "aws_appautoscaling_policy" "ecs_target_tracking_predefined_metric_policy":
 314: resource "aws_appautoscaling_policy" "ecs_target_tracking_predefined_metric_policy" {
```
### Expected Behavior

Target Tracking scaling policy with metric `ALBRequestCountPerTarget` should be created.

### Actual Behavior

Terraform always complains with error `ValidationException: Invalid resource label`, tried both using load balancer ARN suffix and Target Group ARN suffix.
In Terraform docs https://www.terraform.io/docs/providers/aws/r/appautoscaling_policy.html#predefined_metric_specification-1, the resource_label is just documented as ` (Optional) Reserved for future use.`

### Steps to Reproduce

1. `terraform apply`

**Comment by venkz** [comment]
Hey I am stuck at the exact same issue.
Terraform v0.11.14

What is the resolution on this?

**Comment by mtroianovskyi-g** [comment]
It is not quite clear in the Terraform docs, but you need to refer to this: https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_PredefinedMetricSpecification.html
> The format is app/load-balancer-name/load-balancer-id/targetgroup/target-group-name/target-group-id , where
> app/load-balancer-name/load-balancer-id is the final portion of the load balancer ARN, and
> targetgroup/target-group-name/target-group-id is the final portion of the target group ARN.

So the TF config should look like `resource_label = "${lb.arn_suffix}/${tg.arn_suffix}"`.
