### ISSUE TITLE
Support for setting AWS Glue Data Catalog Encryption/settings

### ISSUE THREAD

**Issue by jdillon** [terraform-providers/terraform-provider-aws#9736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Does not look like there is presently any resource to configure the AWS Glue Data Catalog encryption settings:

* https://docs.aws.amazon.com/glue/latest/dg/encrypt-glue-data-catalog.html
### Potential Terraform Configuration

I would have expected to see something like:

```hcl
resource "aws_glue_data_catalog_settings" "settings" {
    metadata_encryption_kms_key_id = "..."
    password_encryption_kms_key_id = "..."
}
```

... and probably the other bits which are exposed to configure the data catalog settings too?

**Comment by stijndehaes** [comment]
Hey I just made a PR for the glue resource policy: https://github.com/terraform-providers/terraform-provider-aws/pull/10361

After that one I am willing to make a PR for the encryption/settings :)
