### ISSUE TITLE
Get recursive ssm keys

### ISSUE THREAD

**Issue by Mor-Walkme** [terraform-providers/terraform-provider-aws#9749]
Hey,
Aws sdk supports getting recursive ssm keys by using "get-parameters-by-path". does it supported by terraform as data resource?

Thanks,
Mor.

**Comment by ryndaniels** [comment]
Hey @Mor-Walkme - thanks for this question! It looks like there is an issue open requesting this data source (#9429) and a PR addressing it (#9615) - if those will address what you need, it would be helpful to us if you could give a 👍 on those issues to help us prioritize as a team. (If not, please feel free to re-open this with more detail about what you'd like to see instead. Thanks!)
