### ISSUE TITLE
aws_rds_cluster should not be able to specify kms_key_id and restore from encrypted snapshot keyed off a different key

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#975]
terraform 0.9.8

- aws_rds_cluster

Specifying an aws_rds_cluster with a kms_key_id, and a snapshot_identifier, will result in a bad resource, if the snapshot has been encrypted with a different kms key. 

Subsequent plans will show something like:

```
-/+ aws_rds_cluster.user
    ...
    kms_key_id:                        "arn:aws:kms:eu-west-1:xxxxxxxxxxxx:key/########-####-####-####-############" => "arn:aws:kms:eu-west-1:xxxxxxxxxxxx:alias/dev/rds" (forces new resource)
```

A check should be made in this combination to prevent this from happening.

**Comment by bflad** [comment]
Are you using `${aws_kms_key.my-key.arn}` or `${aws_kms_alias.my-alias.arn}`? AWS is likely returning the key ARN when reading the physical resource, not the alias ARN. In my experience, the alias ARN will work on creation, but show a similar diff afterwards.

**Comment by gtmtech** [comment]
Yes I am using:

```
data "aws_kms_alias" "rds" {
    name = "alias/dev/rds"
}
```

and then:

```
resource "aws_rds_cluster" "user" {
    kms_key_id                      = "${data.aws_kms_alias.rds.arn}"
}
```

The trouble is that there is no data resource aws_kms_key , and the resource doesnt follow aliases to work out what the actual key id is. 

One of the two would be required to fix this, as its not possible to do otherwise, without having the key id as a variable (suboptimal), or having the key resource itself as part of the same terraform repo (bad if like me you have a different team in charge of security resources and dont just allow blanket access to everything)

**Comment by bflad** [comment]
The `aws_kms_alias` data source has a [`target_key_id` attribute available](https://www.terraform.io/docs/providers/aws/d/kms_alias.html#target_key_id), so while its not exactly easy to use for the ARN, you can apply some parsing to hopefully get what you need (untested):
`${replace(aws_kms_alias.rds.arn, "key\\..*$$", aws_kms_alias.rds.target_key_id)}`

It would be nice if we could get the key ARN directly from the alias data source though.

**Comment by bflad** [comment]
Hi @gtmtech, v1.8.0 of the provider releasing shortly will add `target_key_arn` attributes to both the `aws_key_alias` resource and data source. Can you try those out when they're released and let us know if that solves your problem here?

**Comment by mildwonkey** [comment]
Hi! Sine there hasn't been any response to the ticket, I'm going to close this out, but if anyone is still experiencing this and can either supply a reproduction or logs, feel free to reply below and we can open this back up and get it taken care of. Thanks!
