### ISSUE TITLE
Modifying RDS instance size does not work

### ISSUE THREAD

**Issue by chrisrlong** [terraform-providers/terraform-provider-aws#9756]
Terraform 0.12.6
provider.aws v2.23.0

The below is the config and output after trying to change instance size for a RDS node. The terraform run completes as below, but the AWS console shows that no change was made.

Repeating the run produces the same result.

`resource "aws_db_instance" "default" {
  identifier = "${var.name}-db"
  skip_final_snapshot = "true"
  allocated_storage = "${var.rds_storage}"
  engine = "${var.rds_engine}"
  engine_version = "${var.rds_engine_version}"
  instance_class = "${var.rds_instance}"
  storage_type = "gp2"
  multi_az = "${var.rds_multi_az}"
  username = "xxxxxxxx"
  password = "${var.xxxxxxx}"
  name = "${var.rds_db_name}"
  backup_retention_period = "${var.rds_backup_retention_period}"
  publicly_accessible = "false"
  vpc_security_group_ids = [
    "${xxxxxx}"
  ]
  db_subnet_group_name = "${var.name}-db_subnet_group"
  parameter_group_name = "${var.name}-db-parameter-group"

  tags = {
    App = "${var.name}"
    Env = "${var.environment}"
  }
}`

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.rds.aws_db_instance.default will be updated in-place
  ~ resource "aws_db_instance" "default" {

~ instance_class                        = "db.t2.micro" -> "db.t3.micro"

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.rds.aws_db_instance.default: Modifying... [id=legacy-site-db]
module.rds.aws_db_instance.default: Still modifying... [id=legacy-site-db, 10s elapsed]
module.rds.aws_db_instance.default: Still modifying... [id=legacy-site-db, 20s elapsed]
module.rds.aws_db_instance.default: Still modifying... [id=legacy-site-db, 30s elapsed]
module.rds.aws_db_instance.default: Modifications complete after 31s [id=legacy-site-db]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

**Comment by davejennings** [comment]
If you're expecting changes to be applied immediately, have you set that config option? https://www.terraform.io/docs/providers/aws/r/db_instance.html#apply_immediately

Otherwise it'll be scheduled for the next maintenance window defined for your instance. 

I've fallen for that trap a few times as I don't leave it that way in version control for our production resources as an additional safety measure.

**Comment by chrisrlong** [comment]
@davejennings Oh gosh your totally right. I fired this off after getting it peer reviewed and we both missed it.

We too decided not to set apply_immediately many years back to minimise accidental changes.
