### ISSUE TITLE
Remnant CloudWatch Dashboards persist on each dashboard rename

### ISSUE THREAD

**Issue by JamesPeiris** [terraform-providers/terraform-provider-aws#9782]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
v0.11.13
```

### Affected Resource(s)

* aws_cloudwatch_dashboard

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_dashboard" "example" {
  dashboard_name = "dashboard-name-before"

  dashboard_body = <<EOF
    {
      ... some JSON
    }
  EOF
}

```

### Debug Output

N/A - no relevant debug output - the bug only presents itself in the AWS Console

### Panic Output

N/A - no panics

### Expected Behavior

On update of the dashboard resource's `dashboard_name`
✅ The dashboard with the new name should be deployed to AWS
✅ The dashboard with the original name should be destroyed in AWS

### Actual Behavior

On update of the dashboard resource's `dashboard_name`
✅ The dashboard with the new name is deployed to AWS
❌ The dashboard with the original name is not destroyed in AWS

### Steps to Reproduce

1. Deploy a dashboard with some arbitrary `dashboard_body` JSON
2. Check the dashboard exists and has the correct name.
  ![image](https://user-images.githubusercontent.com/2997151/63099818-b1fd0380-bf6d-11e9-9b52-9470670c4e0b.png)
3. Check the terraform state reflects the deployed infrastructure
  ``` json
  {
    "version": 3,
    "terraform_version": "0.11.13",
    "serial": 1,
    "lineage": "cc8370ef-4c74-de56-db09-db767317bb9c",
    "modules": [
      {
        "path": [
          "root"
        ],
        "outputs": {},
        "resources": {
          "aws_cloudwatch_dashboard.main": {
            "type": "aws_cloudwatch_dashboard",
            "depends_on": [],
            "primary": {
              "id": "dashboard-name-before",
              "attributes": {
                "dashboard_arn": "arn:aws:cloudwatch::<ACCOUNT_ID>:dashboard/dashboard-name-before",
                "dashboard_body": " { ... Dashboard Body JSON here... } ",
                "dashboard_name": "dashboard-name-before",
                "id": "dashboard-name-before"
              },
              "meta": {},
              "tainted": false
            },
            "deposed": [],
            "provider": "provider.aws"
          }
        },
        "depends_on": []
      }
    ]
  }
  ```
4. Once deployed, change only the `dashboard_name` property
5. Run `terraform plan` to see the "update-in-place" output:
  ```
  ~ aws_cloudwatch_dashboard.main
      dashboard_name: "dashboard-name-before" => "dashboard-name-after"

  Plan: 0 to add, 1 to change, 0 to destroy.
  ```
6. Run `terraform apply`
7. Check the renamed dashboard exists and has the correct name.
**8. Confirm that the old dashboard still exists**
  ![image](https://user-images.githubusercontent.com/2997151/63099912-e244a200-bf6d-11e9-96a0-1382f28709fe.png)
**9. Confirm that only the new dashboard exists in the terraform state**
  ``` json
  {
    "version": 3,
    "terraform_version": "0.11.13",
    "serial": 2,
    "lineage": "cc8370ef-4c74-de56-db09-db767317bb9c",
    "modules": [
      {
        "path": [
          "root"
        ],
        "outputs": {},
        "resources": {
          "aws_cloudwatch_dashboard.main": {
            "type": "aws_cloudwatch_dashboard",
            "depends_on": [],
            "primary": {
              "id": "dashboard-name-after",
              "attributes": {
                "dashboard_arn": "arn:aws:cloudwatch::<ACCOUNT_ID>:dashboard/dashboard-name-after",
                "dashboard_body": " { ... Dashboard Body JSON here... } ",
                "dashboard_name": "dashboard-name-after",
                "id": "dashboard-name-after"
              },
              "meta": {},
              "tainted": false
            },
            "deposed": [],
            "provider": "provider.aws"
          }
        },
        "depends_on": []
      }
    ]
  }
  ```

### Important Factoids

N/A - reproduced on personal and work account

### References

* N/A

**Comment by bflad** [comment]
The fix for this has been merged and will release with version 2.44.0 of the Terraform AWS Provider, next Thursday. Thanks to @JamesPeiris for the implementation. 👍
