### ISSUE TITLE
no more support for multiple interfaces in aws_instance module?

### ISSUE THREAD

**Issue by queglay** [terraform-providers/terraform-provider-aws#9806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.6

### Affected Resource(s)
aws_instance
network_interface

### Terraform Configuration Files

in prior versions of the aws provider 1.60 this was acceptable- attaching 2 nic's.  but now terraform init will produce errors on the 2nd NIC.

```hcl
resource "aws_instance" "softnas1" {
  count = "${var.softnas_storage ? 1 : 0}"
  ami           = "${var.softnas_use_custom_ami ? var.softnas_custom_ami : lookup(var.selected_ami, local.softnas_mode_ami)}"
 
  instance_type = "${lookup(var.instance_type, var.softnas_mode)}"

  ebs_optimized = true

  iam_instance_profile = "${aws_iam_instance_profile.softnas_profile.name}"

  network_interface = {
    device_index         = 0
    network_interface_id = "${aws_network_interface.nas1eth0.id}"

    #delete_on_termination = true
  }

  network_interface = {
    device_index         = 1
    network_interface_id = "${aws_network_interface.nas1eth1.id}"

    #delete_on_termination = true
  }
```

### Debug Output
```
vagrant@openfirehawkserverdev:/vagrant$ terraform init
Initializing modules...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Attribute redefined

  on modules/softnas/main.tf line 323, in resource "aws_instance" "softnas1":
 323:   network_interface = {

The argument "network_interface" was already set at
modules/softnas/main.tf:316,3-20. Each argument may be set only once.
```
### Expected Behavior

Previously in aws provider v1.60 it was possible to define multiple NIC's to atttach to the aws_instance module.

### Actual Behavior

errors because it catches a duplicate definition to attach the 2nd NIC

### Steps to Reproduce

Attach 2 NIC's to an instance as defined in the config file above.

### References

* #0000

**Comment by ryndaniels** [comment]
Hi @queglay - thanks for opening this issue! It looks like the problem is with there being extra `=` in your `network_interface` definitions. I was able to get `terraform init` to succeed with this in my config:

```
network_interface {
    device_index         = 0
    network_interface_id = "${aws_network_interface.nas1eth0.id}"

    #delete_on_termination = true
  }

  network_interface {
    device_index         = 1
    network_interface_id = "${aws_network_interface.nas1eth1.id}"

    #delete_on_termination = true
  }
```

So that's `network_interface {` and not `network_interface = {` for each block. Are you able to give that a try in your environment and see if that works for you? 🙂 Thanks!

**Comment by queglay** [comment]
This worked, I must have made this error during conversion to .12 somehow.
