### ISSUE TITLE
Add support for IoT Analytics topic rule action

### ISSUE THREAD

**Issue by ktarasz** [terraform-providers/terraform-provider-aws#9829]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The IoT Analytics Action rule is not yet supported. It would be nice to have that also.
### Affected Resource(s)
aws_iot_topic_rule

### Terraform Configuration Files

```hcl
iot_analytics {
        channel_name: channelName
        role_arn: roleArn
}
```

### References
https://docs.aws.amazon.com/iot/latest/developerguide/iot-rule-actions.html#iotanalytics-rule

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.62.0 of the Terraform AWS Provider, later this week. Thanks to @ktarasz for the implementation. 👍
