### ISSUE TITLE
Add source_version support for aws_codebuild_project with Github Source

### ISSUE THREAD

**Issue by RA999** [terraform-providers/terraform-provider-aws#9831]
When using GitHub repository as source for aws_codebuild_project, I need to be able to specify the source version (e.g. branch name). This is currently supported through the UI:

<img width="817" alt="github" src="https://user-images.githubusercontent.com/13630292/63372419-0fb99300-c354-11e9-8e56-92bdfd31aa74.png">

I would like if the aws_codebuild_project source could support a source_version field or something similar.

**Comment by raskam** [comment]
Source version is a valid option for other git sources as well  (CodeCommit, BitBucket, ...)

**Comment by ranand01** [comment]
thank you

**Comment by mdolian** [comment]
Has this been released yet?  I don't see it in any of the release notes.

**Comment by lifeofguenter** [comment]
There are two API properties on this - both of which are independent of the source type (e.g. works with git/s3/etc.):

* `SourceVersion`: https://github.com/aws/aws-sdk-go/blob/v1.25.11/service/codebuild/api.go#L1934
* `SecondarySourceVersions`: https://github.com/aws/aws-sdk-go/blob/v1.25.11/service/codebuild/api.go#L1917

The latter might be a bit more complex to implement. I would be already very happy if the first type could be implemented ❤️

**Comment by bonovoxly** [comment]
Anyone have any good workarounds for this?

**Comment by ivancasco** [comment]
Pull-request #9877 is open and still waiting for review. You can help the community and maintainers prioritize this request by adding a 👍 [reaction](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment.

**Comment by bflad** [comment]
Support for the top-level `source_version` argument on the `aws_codebuild_project` resource has been merged and will release with version 2.48.0 of the Terraform AWS Provider, Thursday this week. Thanks to @RA999 for the implementation. 👍
