### ISSUE TITLE
Does Terraform AWS  support AWS IoT Analytics 

### ISSUE THREAD

**Issue by yaroslavsukh** [terraform-providers/terraform-provider-aws#9837]
Hello,
I have been going through the documentation but can't seem to find any reference on how to use terraform in combination with AWS  IoT Analytics 
Is this currently supported?

**Comment by ryndaniels** [comment]
Hi @yaroslavsukh - thanks for this question! At the moment we do not have IoT Analytics support in Terraform. However, it looks like someone else is interested in this as well and opened #9930 to that effect. If that issue describes what you're looking for, please give it a 👍 over there as that will help us prioritize what we work on as a team. Thanks! 🙂
