### ISSUE TITLE
r/aws_sqs_queue: Tag on create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9850]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon SQS [now supports](https://github.com/aws/aws-sdk-go/releases/tag/v1.23.6) tagging queues on creation.

This will allow us to remove the not-preferred call to `resourceAwsSqsQueueUpdate` from `resourceAwsSqsQueueCreate` and replace with a call to `resourceAwsSqsQueueRead`.

### New or Affected Resource(s)

* [`aws_sqs_queue`](https://www.terraform.io/docs/providers/aws/r/sqs_queue.html)

### Potential Terraform Configuration

n/a

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-sqs-now-supports-tag-on-create/).
[API reference](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html).

Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/9770

**Comment by bflad** [comment]
Support for tagging `aws_sqs_queue` resources on creation in AWS Commercial regions has been merged and will release with version 2.30.0 of the Terraform AWS Provider, later this week.
