### ISSUE TITLE
AWS - RDS SQL Server : no collation attribute

### ISSUE THREAD

**Issue by valentinmele** [terraform-providers/terraform-provider-aws#9858]
Hi !

### Current Terraform Version
```
Terraform v0.11.11
AWS Provider v2.24.0
```

### Use-cases
I'd like to create an AWS RDS SQL Server instance with a collation I choosed as it is not possible to modify an instance collation after its creation, 

### Attempted Solutions
Add a _collation_ argument in _aws_db_instance_.

### More informations 
The fact to [choose server-level collation](https://aws.amazon.com/about-aws/whats-new/2019/08/amazon-rds-sql-server-supports-changing-server-level-collation/?nc1=h_ls) is pretty new in AWS (06 of August, 2019). I guess this explains why I couldn't find any information about this subject.

**Comment by nywilken** [comment]
hi @valentinmele I don't see support for setting collation within the API when creating DB instances so I don't believe we can support this argument at this time. Do you by chance know, maybe by speaking with your AWS TAM, know it it is something that will be made available in the RDS API? 

If you have any links to the documentation on how to set this attribute via the API that would be helpful. I'll keep this issue open and check back next week to see if there are any new changes to the AWS API.

**Comment by alexwbaule** [comment]
RDS Support Collation, its a CharacterSetName Attribute.

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

https://raw.githubusercontent.com/aws/aws-sdk-go/master/service/rds/api.go


> hi @valentinmele I don't see support for setting collation within the API when creating DB instances so I don't believe we can support this argument at this time. Do you by chance know, maybe by speaking with your AWS TAM, know it it is something that will be made available in the RDS API?
> 
> If you have any links to the documentation on how to set this attribute via the API that would be helpful. I'll keep this issue open and check back next week to see if there are any new changes to the AWS API.
