### ISSUE TITLE
Set Cognito User Pool Lambda Config after provisioning

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-aws#9864]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In our application, we are trying to create a Cognito User Pool with a Lambda post-confirmation trigger that fetches some information from a third-party system and sets some user attributes. We've been unable to do this solely with the return value of the Lambda, so instead we've resorted to using the AWS SDK inside the Lambda code.

This works fairly well, except that it creates a circular dependency between the User Pool and the Lambda in Terraform; the Lambda needs to know User Pool properties (e.g. to set environment variables for the ARN) but the User Pool needs to know about the Lambda (to set the `lambda_config` properties).

This could be worked around by having a new resource `aws_cognito_user_pool_lambda_config` that works exactly like the `lambda_config` block inside the `aws_cognito_user_pool` resource, except modifying the user pool afterwards to register the triggers. If that was available, we could get our setup without circular dependencies (the `aws_cognito_user_pool_lambda_config` resource depends both on the `aws_cognito_user_pool` and the `aws_lambda_function`, but nothing depends on it, and we've broken the dependency of the user pool on the lambda).

### New or Affected Resource(s)
* aws_cognito_user_pool (possibly affected by config coming from other resources)
* aws_cognito_user_pool_lambda_config (new resource)

### Potential Terraform Configuration
```hcl
resource "aws_cognito_user_pool" "pool" {
    name = "user_pool"
    # ...
}

resource "aws_lambda_function" "lambda" {
    name = "lambda"
    # ...
}

resource "aws_cognito_user_pool_lambda_config" "triggers" {
    cognito_user_pool_arn = aws_cognito_user_pool.pool.arn
    lambda_config {
        # exactly the same semantics as the lambda_config block on the aws_cognito_user_pool
        post_confirmation {
            name = aws_lambda_function.lambda.name
            arn  = aws_lambda_function.lambda.arn
        }
    }
}
```

**Comment by tomasaschan** [comment]
Note: my specific issue could probably be solved by breaking the depndency "the other way" as well, e.g. setting the environment variables of the lambda at a later time than when provisioning the lambda itself.

**Comment by nywilken** [comment]
Hi @tomasaschan thanks for the detailed issue/feature request. I would like to think about this issue a little more and get back to you with feedback on you proposed approach, and any possible alternative proposals. For now I am going to add the thinking label to this issue and keep it as an enhancement.

**Comment by tomasaschan** [comment]
@nywilken would love to see this not fall through the cracks, even if it's not something I work with daily anymore.
