### ISSUE TITLE
Incorrect documentation for datasource aws_ecs_cluster 

### ISSUE THREAD

**Issue by zoltan-toth-mw** [terraform-providers/terraform-provider-aws#988]
Hi there,

According to the documentation the aws_ecs_cluster datasource exports the **arn** attribute.
However when I tried to use it terraform told me that it doesn't exists:

> Resource 'data.aws_ecs_cluster.pub' does not have attribute 'arn' for variable 'data.aws_ecs_cluster.pub.arn'

I also checked the aws_ecs_cluster resource documentation which exports the arn as an attribute called **id**. Referring to id   _"${data.aws_ecs_cluster.pub.id}"_ instead of arn solved the problem.

So the documentation is incorrect. aws_ecs_cluster datasource exports an id attirbute (containing the arn) instead of arn as the documentation says. 

### Terraform Version
0.9.8

### Affected Resource(s)
datasource aws_ecs_cluster 

### Terraform Configuration Files
```hcl
data "aws_ecs_cluster" "pub" {
  cluster_name = "${var.public_cluster_name}"
}
resource "aws_ecs_service" "service" {
  cluster = "${data.aws_ecs_cluster.pub.arn}" # no arn exists but id
}
```

**Comment by stack72** [comment]
Hi @zoltan-toth-mw 

Apologies for this - PR in progress to fix this for the next release :)

Paul
