### ISSUE TITLE
Add support for AWS IoT Rule Action to send data to an AWS IoT Events input

### ISSUE THREAD

**Issue by ktarasz** [terraform-providers/terraform-provider-aws#9889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS IoT Rule Action to send data to an AWS IoT Events input is not yet supported. 
### Affected Resource(s)
aws_iot_topic_rule

### Terraform Configuration Files

```hcl
iot_events {
        input_name: (Required) The name of the AWS IoT Events input.
        role_arn: (Required) The ARN of the IAM role that grants access.
        message_id: (Optional) Use this to ensure that only one input (message) with a given messageId is processed by an AWS IoT Events detector. 
}
```

### References
https://docs.aws.amazon.com/iot/latest/developerguide/iot-rule-actions.html#iotevents-rule

**Comment by bflad** [comment]
Support for this functionality has been merged and will release with version 2.62.0 of the Terraform AWS Provider, later this week. Thanks to @ktarasz for the implementation. 👍
