### ISSUE TITLE
Can't properly import resource aws_ses_event_destination; missing attributes

### ISSUE THREAD

**Issue by dehuszar** [terraform-providers/terraform-provider-aws#9897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.12.6

### Affected Resource(s)
aws_ses_event_destination

### Terraform Configuration Files

```hcl
resource "aws_ses_event_destination" "user_events_logs" {
  name                   = "user-events-logs-cloudwatch"
  configuration_set_name = aws_ses_configuration_set.user_events.name
  enabled                = true
  matching_types         = ["send", "reject", "bounce", "complaint", "delivery", "open", "click", "renderingFailure"]

  cloudwatch_destination {
    default_value  = "user_events"
    dimension_name = "user-event-tracking"
    value_source   = "emailHeader"
  }
}
```

### Expected Behavior

After trying to do a `tf state mv previous_resource current_resource`, my expectation was that all the attributes for that resource would have made it over to the new state configuration.  

### Actual Behavior

Instead, it viewed `cloudwatch_destination` block, `matching_types`, `enabled`, and `configuration_set_name` attributes as having no value and thus attempts to destroy/create the resource.  Reviewing the actual attributes from the web console, the attributes are there, but the showing the state contents reveals that only the id is being stored.  Running a `tf state rm <resource_name>` and re-importing it yields the same results.

When attempting to apply the destroy/create plan I get the following error:
```
module.email.aws_ses_event_destination.user_events_logs: Destroying... [id=user-events-logs-cloudwatch]

Error: InvalidParameterValue: The configuration set name must be specified.
        status code: 400
```

The only way I was able to return to a functional state representation was to manually delete the event destination in the web console, and manually delete the resource reference from tf state.  From there, re-deploying the resource worked fine and future plans don't show any absence of state attributes

### Steps to Reproduce

deploy an SES configuration with an aws_ses_event_destination (I used the cloudwatch_destination block, not sure if other targets are similarly affected).  Then after successfully deploying, you should have no changes when you run a plan again.

Then move the resource to a local sub-folder and run `tf state mv <resourceA> <module.resourceB>`.  If you run `tf state show <module.resourceB>` you should see the resource name with only an id attribute.

### References

After discussing the issue on gitter, it was offered that the module might not yet be complete:

* https://github.com/terraform-providers/terraform-provider-aws/blob/5c5e4cf89b4e9b272c9a85e5e0477d5f3ede5fcc/aws/resource_aws_ses_event_destination.go#L190

**Comment by anGie44** [comment]
Fixed with #13466 to release with `v2.64.0` of the provider.
