### ISSUE TITLE
Support managed session policies in assume_role configuration block

### ISSUE THREAD

**Issue by timoguin** [terraform-providers/terraform-provider-aws#9898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow scoping down IAM role permissions using managed IAM policies. In addition to the STS `Policy` parameter, there is now a `PolicyArns` parameter that allows passing up to 10 managed policies for the session.

There are a lot of benefits to this approach over passing the policy as a JSON string. I've highlighted a few reasons in the linked issue for the Terraform S3 backend. I've also opened an issue for the aws-sdk-go-base, since that is what actually drives the auth for the S3 backend and the provider. I've linked them both in the references below.

### New or Affected Resource(s)

This would just add an optional argument to the AWS provider configuration.

### Potential Terraform Configuration

```hcl
provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::0000000000000:role/MooCow"

    policy_arns = [
      "arn:aws:iam::0000000000000:policy/Foo",
      "arn:aws:iam::0000000000000:policy/AnotherFoo",
      "arn:aws:iam::0000000000000:policy/OkayThatIsEnoughPoliciesNow",
    ]
  }
}
```

### References

- Related aws-sdk-go-base issue: hashicorp/aws-sdk-go-base#11
- Related Terraform issue: hashicorp/terraform#22601
- https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
- https://aws.amazon.com/blogs/security/create-fine-grained-session-permissions-using-iam-managed-policies/

**Comment by bflad** [comment]
Support for this (new `policy_arns` argument in the provider `assume_role` configuration block) has been merged and will release with version 3.0.0 of the Terraform AWS Provider, likely in about two weeks. Please note this enhancement was also applied for the Terraform S3 Backend (part of Terraform CLI codebase) as part of 0.13.0-beta2.
