### ISSUE TITLE
Add support for aws_dms_endpoint elasticsearch target engine type

### ISSUE THREAD

**Issue by zvickery** [terraform-providers/terraform-provider-aws#9899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In 2018 AWS added support for DMS endpoints supporting Elasticsearch as a target engine type.  It would be great if terraform supported this.

### New or Affected Resource(s)

* aws_dms_endpoint

### Potential Terraform Configuration

```
resource "aws_dms_endpoint" "my-endpoint" {
...
  endpoint_type = "target"
  engine_name   = "elasticsearch"
...
}
```
### References

AWS documentation is here:
* https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.Elasticsearch.html

**Comment by bflad** [comment]
Support for Elasticsearch has been added to the `aws_dms_endpoint` resource and will release with version 2.58.0 of the Terraform AWS Provider, later this week. Thanks to @timrcoulson for the implementation. 👍
