### ISSUE TITLE
Adding steps to existing EMR cluster cause panic when plan

### ISSUE THREAD

**Issue by rednuht** [terraform-providers/terraform-provider-aws#9902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.7

### Affected Resource(s)

* aws_emr_cluster

### Terraform Configuration Files

Not applicable

### Debug Output

Error: Provider produced invalid plan

### Panic Output

Provider "aws" has indicated "requires replacement" on
module.cluster.aws_emr_cluster.emr-cluster[0] for a non-existent attribute
path cty.Path{cty.GetAttrStep{Name:"step"},
cty.IndexStep{Key:cty.NumberIntVal(0)},
cty.GetAttrStep{Name:"action_on_failure"}}.

### Expected Behavior

Detect new step(s) and display actions that should be taken

### Actual Behavior

No plan is printed out and the panic output is printed.

### Steps to Reproduce

1. Create EMR cluster.
2. Configure a step

**Comment by ryndaniels** [comment]
Hi @rednuht - could you please edit this issue to include the relevant parts of your Terraform configuration where you are seeing this panic when you run `terraform plan`?  This is important information for us to be able to reproduce and investigate this effectively. Thanks!

**Comment by ryndaniels** [comment]
Closing this as we haven't gotten a response in a couple weeks, but please feel free to open a new issue with all the applicable information if you're still having this issue!
