### ISSUE TITLE
Amazon ElastiCache now supports up to 50 characters in cluster name

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#9906]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon ElastiCache now allows you to name your clusters up to 50 characters for cacheClusters and upto 40 characters for replicationGroups.

### New or Affected Resource(s)

* [`aws_elasticache_cluster`](https://www.terraform.io/docs/providers/aws/r/elasticache_cluster.html)
* [`aws_elasticache_replication_group`](https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html)

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/08/elasticache_supports_50_chars_cluster_name/).

**Comment by bflad** [comment]
This will be so nice to increase, as it's bitten me in my past jobs and it'll close out quite a few issues we have open:

https://github.com/terraform-providers/terraform-provider-aws/issues/9131
https://github.com/terraform-providers/terraform-provider-aws/pull/7409
https://github.com/terraform-providers/terraform-provider-aws/issues/5381

I'll take care of submitting this right now.

**Comment by bflad** [comment]
Submitted here: https://github.com/terraform-providers/terraform-provider-aws/pull/9941

**Comment by bflad** [comment]
These updates have been merged and will release in version 2.28.0 of the Terraform AWS Provider, Thursday. 👍
