### ISSUE TITLE
SQS Message?

### ISSUE THREAD

**Issue by cookiecurse** [terraform-providers/terraform-provider-aws#9937]
I have an existing FIFO queue `data "aws_sqs_queue" "FIFOqueue" { name = "myqueue" }` and I can get it's url using the output `output "sqs_url" { value = "$data.aws_sqs_queue.FIFOqueue.url"}`. Is there a Terraform resource that enables me to add a message into the existing SQS Fifo queue? I couldn't find any documentation on this.

Thanks!

**Comment by ryndaniels** [comment]
Hi @cookiecurse - Thanks for this question! In general, this repository is intended to be for bug reports and feature requests within the provider code base, so for future questions like this, you might want to check out [the community forum](https://discuss.hashicorp.com/c/terraform-providers) instead. That being said, Terraform is designed much more for the provisioning of infrastructure (such as the SQS queue) and less towards specific usage (in this case sending messages) so a resource for this use case doesn't exist. Good luck, and be sure to check out the forums if you have additional questions! 🙂
