### ISSUE TITLE
Fix and enable tfproviderlint R003 check: Remove extraneous Exists functions

### ISSUE THREAD

**Issue by ryndaniels** [terraform-providers/terraform-provider-aws#9953]
## Description
As per `tfproviderlint` check `R003`, we want to remove extraneous `Exists` functions from resources. This logic can be handled inside `Read` functions instead to prevent duplication. 

Failing example:
```
func resourceExampleThingExists(d *schema.ResourceData, meta interface{}) (bool, error) { /* ... */ }

func resourceExampleThingRead(d *schema.ResourceData, meta interface{}) error { /* ... */ }

&schema.Resource{
    Exists: resourceExampleThingExists,
    Read:   resourceExampleThingRead,
    /* ... */
}
```

Should become:
```


func resourceExampleThingRead(d *schema.ResourceData, meta interface{}) error { /* ... */ }

&schema.Resource{
    Read: resourceExampleThingRead,
    /* ... */
}
```

## Definition of Done
* In `GNUmakefile`, add `-R003` to `tfproviderlint` command under `lint` target and have TravisCI testing pass

**Comment by ewbankkit** [comment]
After all the linked PRs are merged we can enable `R003` in `GNUmakefile`.
