### ISSUE TITLE
Fix and enable tfproviderlint S018 check: Use TypeList and MaxItems: 1

### ISSUE THREAD

**Issue by ryndaniels** [terraform-providers/terraform-provider-aws#9956]
## Description
As per `tfproviderlint` check `S018`, we want to make sure that schemas use `Type: TypeList` and `MaxItems: 1` if possible.

Failing example:
```
&schema.Schema{
    MaxItems: 1,
    Type:     schema.TypeSet,
}
```

Should become:

```
&schema.Schema{
    MaxItems: 1,
    Type:     schema.TypeList,
}
```
## Affected Files
- [x] GNUMakefile
- [x] aws/provider.go
- [x] aws/resource_aws_api_gateway_usage_plan.go
- [x] aws/resource_aws_api_gateway_usage_plan_test.go
- [x] aws/resource_aws_api_gateway_vpc_link.go
- [x] aws/resource_aws_appmesh_virtual_node.go
- [x] aws/resource_aws_appmesh_virtual_router.go
- [x] aws/resource_aws_cloudfront_distribution.go
- [x] aws/resource_aws_codebuild_project_test.go
- [x] aws/resource_aws_ecs_service.go
- [x] aws/resource_aws_eks_node_group.go
- [x] aws/resource_aws_elastic_transcoder_pipeline.go
- [x] aws/resource_aws_elastic_transcoder_preset.go
- [x] aws/resource_aws_fsx_lustre_file_system.go
- [x] aws/resource_aws_fsx_windows_file_system.go
- [x] aws/resource_aws_kinesis_firehose_delivery_stream.go
- [x] aws/resource_aws_s3_bucket.go
- [x] aws/resource_aws_s3_bucket_test.go
- [x] aws/resource_aws_ses_event_destination.go
- [x] aws/resource_aws_vpc_peering_connection.go
- [x] aws/resource_aws_vpc_peering_connection_test.go
- [x] aws/resource_aws_waf_sql_injection_match_set.go
- [x] aws/resource_aws_waf_sql_injection_match_set_test.go
- [x] aws/resource_aws_waf_web_acl.go
- [x] aws/resource_aws_waf_web_acl_test.go
- [x] aws/waf_helpers.go
- [x] aws/resource_aws_waf_byte_match_set.go
- [x] aws/resource_aws_waf_byte_match_set_test.go

## Definition of Done

* In `GNUmakefile`, add `-S018` to `tfproviderlint` command under `lint` target and have TravisCI testing pass

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/6427
