### ISSUE TITLE
Regression Of Child Module Providers for AWS

### ISSUE THREAD

**Issue by moofish32** [terraform-providers/terraform-provider-aws#998]
Hi there,

The original issue here https://github.com/hashicorp/terraform/issues/1819 indicates that child modules should respect the scoped aws provider. For S3 buckets this seems to be failing. I have the following repo https://github.com/moofish32/terraform-bug which is a copy of the CRR example just separating into two modules and this fails with: 

```
Error applying plan:

1 error(s) occurred:

* module.destination_bucket.aws_s3_bucket.destination: 1 error(s) occurred:

* aws_s3_bucket.destination: Error creating S3 bucket: IllegalLocationConstraintException: The eu-west-1 location constraint is incompatible for the region specific endpoint this request was sent to.
        status code: 400, request id: 8F7437428AD5B9E3, host id: hybt340LVeBG+x75tp8PCzzXDcvRfk1MV3SqOTGpWfm3XIAQpm+fowYvpncSe1F0nZ+jxfDx2Do=
```

### Terraform Version
Terraform v0.9.9

### Affected Resource(s)
Please list the resources as a list, for example:
- s3 bucket 
- s3 bucket policy attach

### Terraform Configuration Files
see repo

### Debug Output
available via running the reproduction

### Panic Output
N/A

### Expected Behavior
The S3 bucket should be created in the nested module configure region which is different than the parent module

### Actual Behavior
Error attempting to use parent module s3 endpoint

### Steps to Reproduce
1. `terraform apply` in repo root above

### References
https://github.com/hashicorp/terraform/issues/1819 I think this is a regression from @apparentlymart last comment in here, but that is only an opinion.

**Comment by moofish32** [comment]
https://github.com/moofish32/terraform-bug/compare/fix/use_alias?expand=1 <-- this appears to be the slightly annoying but easy to do work around.

**Comment by bflad** [comment]
@moofish32 have you tried working with Terraform 0.11+ and its much better handling of module provider inheritance? https://www.terraform.io/docs/modules/usage.html#providers-within-modules

Moving to explicit provider passing in 0.11 fixed a lot of issues in our environment.

**Comment by moofish32** [comment]
Agree @bflad let’s close this issue
